### PR TITLE
added function names in __init__.py in solvers

### PR DESCRIPTION
**Pull request by Yathartha22**
In this I have added a few functions namely:
`domain_check`, `solvify`, `solveset_real`, `solveset_complex`. 
Are these okay?

### CODE REVIEW

**Review by aktech — COMMENTED** [review]
-1 These methods are not supposed to be present in the public API.

**Comment by Yathartha22** [comment]
@aktech I thought adding these would provide more functionality for the user.
Like `domain-check`, the user would be able to check for the values in the domain. Otherwise there is no other way.

**Comment by aktech** [comment]
These are not kept into `__init__.py` because we don't want to expose them and would rather like to keep them private, as their api may change.

**Comment by Yathartha22** [comment]
okay thanks @aktech I would rather close this.

**Comment by kshitij10496** [comment]
I agree that functions such as `solvify`, `domain_check`, `solve_decomposition` and `nonlinsolve` do not have a rigid API system.

@aktech How about exposing only the `solveset_real` and `solveset_complex` methods to the public API?

#### Reasons in favour:
- These wrappers are as stable as `solveset` itself.
- The use-cases of real and complex domains are fairly common. Hence, exposing these functions might be helpful to the end user.

**Pull request closed without merging**
