### PR TITLE
Merge branch 1.1.1

### PR DESCRIPTION
**Pull request by jirikuncar**
solves discussion from #12911

```console
$ git checkout master
$ git fetch upstream
$ git merge --ff-only upstream/pr/13010
```

### CODE REVIEW

**Comment by asmeurer** [comment]
I intend to merge 1.1.1 into master once it is released (that's why it's a pull request).

**Comment by schymans** [comment]
@asmeurer, why can it not be merged into master before release? My work relies on a few PRs that have been merged into master and others that have been merged into 1.1.1, and it is really hard to put together a branch that contains all I need. Also, won't it take more effort to merge 1.1.1 into master the longer you wait?

**Comment by jirikuncar** [comment]
@asmeurer you will need to solve more merge conflicts the longer you wait with the merge, plus there is not a single branch where one has both fixes from master and 1.1.1.

**Comment by jirikuncar** [comment]
Can anyone restart the Travis build https://travis-ci.org/sympy/sympy/jobs/256774592 and merge 1.1.1 into master? Many thanks!

**Comment by jirikuncar** [comment]
@asmeurer I am not sure if you have understood the reasons for regular merges of maintenance branches to master. We can continue the discussion on Gitter if you'd like to and I hope you merge the PR #12911 soon.

**Pull request closed without merging**
