### PR TITLE
[DO NOT MERGE] Changed a number of False to S.false

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed
Testing to see what happens when changing False to S.false (on a few out of the 1940 instances).

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscargus** [comment]
Gah! I'll close this as I'm not sure it is actually beneficial and that there most likely will be import order issues eventually...

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/blob/master/sympy/logic/boolalg.py#L235-L263

`__eq__` should not return S.true/S.false. `__lt__` could for expressions since that can be symbolic.

**Comment by smichr** [comment]
> `__eq__` should not return S.true/S.false
```python
>>> Eq(1,1) is True
False
```

**Comment by oscarbenjamin** [comment]
@asmeurer the docstring you are quoting says 
https://github.com/sympy/sympy/blob/a4297a11fd8f3e8af17efda85e3047e32e470a70/sympy/logic/boolalg.py#L267-L272
but I don't think there should ever be "any doubt" about whether something gives True or S.true. Obviously there can be now but those are bugs which should be fixed by PRs like this.

**Comment by oscargus** [comment]
@smichr This is the incorrect part in `integers.py`: (fortunately is is easier to look for S.true than True...)

```
    def _eval_Eq(self, other):
        if isinstance(self, floor):
            if (self.rewrite(ceiling) == other) or \
                    (self.rewrite(frac) == other):
                return S.true
```

If I understand it correctly, (at least), `__lt__`, `__le__`, `__gt__`, and `__ge__` can/should return `S.true/false`?

(To me it is much easier if one just can go with a "pattern"...)

**Comment by oscargus** [comment]
So all `_eval_Eq` should return `True/False/None`?

**Comment by oscargus** [comment]
@smichr I was wrong about where the incorrect behavior is triggered. Guessed too much based on file name etc...

**Comment by oscargus** [comment]
Btw, it looks like `__new__`of `Equality` only returns `S.true/false`. But most `__eq__` returns `True/False`.

I'll take a break for a while to avoid posting more short observations and corrections...

**Comment by oscarbenjamin** [comment]
> If I understand it correctly, (at least), `__lt__`, `__le__`, `__gt__`, and `__ge__` can/should return `S.true/false`?

We should think that these methods return symbolic Lt, Le etc objects. Those objects can evaluate to symbolic S.true/false. In some cases the methods shortcut and return true/false directly but it should be symbolic S.true/false because it's an evaluation of a symbolic Boolean expression even if we bypass creating the Boolean.

> Btw, it looks like `__new__`of `Equality` only returns `S.true/false`. But most `__eq__` returns `True/False`.

Equality and `__eq__` (i.e. `==`) are not the same. Equality is symbolic and `__eq__` is not. In SymPy Equality represents mathematical equality but `==` is for structural equality e.g.:
```julia
In [48]: Equality(x, 2)
Out[48]: x = 2

In [49]: Equality(x, 2).subs(x, 2)
Out[49]: True

In [50]: x == 2
Out[50]: False
```
So `__eq__/__ne__` should return True/False and should be thought of as a lower-level non-symbolic API like the assumptions system. Equality/Unequality on the other hand are symbolic and should evaluate to S.true/S.false. Of course internally Equality will try `==` (`__eq__`) when evaluating:
https://github.com/sympy/sympy/blob/a4297a11fd8f3e8af17efda85e3047e32e470a70/sympy/core/relational.py#L419-L421

**Comment by asmeurer** [comment]
By the way, the reasoning is that S.true/S.false do the right thing with the boolean operators &, |, ~, and >> without needing to be sympified first. This is the reason they were created in the first place. So for instance `~(a > b)` should always produce `Not(a > b)` (unless of course both `a` and `b` are not SymPy objects, but we cannot control that). If `a > b` returns a Python `bool` then `~` will give the wrong answer, in particular `~True` is `-2` which has a boolean value of True. So this matters for things that one would build larger boolean expressions out of, but not for things that you wouldn't, such as `==`, because `==` is never unevaluated.

**Pull request closed without merging**
