### PR TITLE
Fix bug (variable name mistake)

### PR DESCRIPTION
**Pull request by haru-44**
The variable name is `delta`, not `d`.
Added comment.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by sylee957** [comment]
Can you make some examples of the case where the possible bug can be triggered?

**Comment by haru-44** [comment]
Because sigma is determined randomly, the code must be rewritten for reproducible experiments.

Fix sigma=13. `n=(2**79-1) // 2687` has prime factor 202029703. In this case, the order of Q is `2**2 * 3**2 * 17 * 165041` (this can be seen from `gcd(Q.mont_ladder(2**2 * 3**2 * 17 * 165041).z_cord, n) == 202029703`). So, for example, setting B1=1000, B2=165042 should return 202029703. However, the current code returns 1.

https://www.mersenne.ca/exponent/79

**Comment by oscarbenjamin** [comment]
> Because sigma is determined randomly, the code must be rewritten for reproducible experiments.

It should be changed to use sympy's main rng:
https://github.com/sympy/sympy/blob/0aa50d9fbb2980988566578d79347882ef607a10/sympy/core/random.py#L2-L3

**Comment by oscarbenjamin** [comment]
Thanks @haru-44!

I guess this bug doesn't show up in normal usage because many different curves are used so if one fails it's likely that another succeeds. I agree that the variable name is wrong though.

**Comment by haru-44** [comment]
Thanks for understanding my poor explanation.

As you say, the probability of success is high as a result of trying many curves. However, because the search for stage 2 was almost pointless, the user paid the computational cost of going up to stage 2, but only got stage 1 results.

**Pull request merged**
