### PR TITLE
Replaced solve() with solveset()

### LINKED ISSUE #10006: Replacing solve() with solveset()
This is a tracking issue for the progress forward for replacing `solve` with `solveset`. We need to figure out what this will look like in the long run, as well as what should be done before the 1.0 release. 

Some things:

- [ ] Replacing internal calls with solveset https://github.com/sympy/sympy/issues/8711
- [ ] Add `solveset` (and what other functions?) to `__init__.py`
- [ ] Is the solveset API stable? Do any changes need to be made before 1.0?
- [ ] Figure out how to deprecate solve in favor of solveset. A suggestion was to make solve a higher-level wrapper to solveset. Deprecation may be needed regardless, however, because of API changes.
- [ ] Document the deprecation (even if we don't end up doing a formal deprecation by 1.0, we should still document that the change is happening)

### PR DESCRIPTION
**Pull request by ayazulla007**
###References to other Issues or PRs
Fixes#10006
Fixes#8711

###Brief description of what is fixed or changed
Replaced most of the internal function calls solve() with solveset() 

###Other comments
###Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This has merge conflicts so the tests aren't running (or I can't see their output for some reason).

Can you edit your PR description above to say what this does?

Looking at the changes it looks as if you've done a find/replace for solve/solveset throughout the whole codebase. This has changed the word solve to solveset in many docstrings and comments which doesn't really make sense because solveset isn't an English word:
```
Demonstrates various ways to solveset partial differential equations
```
You've also replace solveset with solvesetset in many places which is definitely not what is wanted.

Replacing solve with solveset in the code is not as simple as changing it from solve to solveset since solveset returns a different type of object so the surrounding code needs to be changed to work with solveset objects as well.

Probably it would be better to start again with this and focus on just one place in the code where you think that using solveset instead of solve would be beneficial.

**Comment by ayazulla007** [comment]
I have resolved the merge conflicts because of which tests weren't running , can you please review it

**Comment by oscarbenjamin** [comment]
You clearly haven't tested any of the code you are changing. It is not possible to simply replace `solve` with `solveset` like this.

You need to start again (without these changes) and find one place in the code where you want to change solve to solveset and test the effect of making that change. If it seems to work then you can push it in a new PR. However it most likely will not work without further changes in the code.

This PR and the changes in it are not usable. You should close this and start again with a fresh branch from master.

**Comment by oscarbenjamin** [comment]
@ayazulla007 you don't understand the issue that you are trying to solve. This is not about simply replacing `solve` with `solveset`. If it was that easy then it would already be fixed by now.

If you want to help with this issue then take some time to understand the differences between solve and solveset. Then find *one* place in the code that is using solve and think about whether it could use solveset instead. When you think you have found a good example then you could open an issue to discuss it.

I'm closing this PR because it will not lead to a useful patch. If you want to submit a PR then please start again from master.

**Pull request closed without merging**
