### PR TITLE
Add contributor Naman Gera

### PR DESCRIPTION
**Pull request by namannimmo10**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
This needs to be updated with the authors_update.py script. See the stuff at the top of the file. 

When I run it, I get the error, `azure-pipelines[bot] was not found at line 751`, so the script may need updating.

**Comment by sylee957** [comment]
I think that this should be done in the release cycle

**Comment by oscarbenjamin** [comment]
I don't think this is done as part of the release cycle. There is the .mailmap file which has to be updated as part of the release script. The list of authors who contribute to the release is added to the release notes.

I don't know when the authors file itself should be updated. Presumably that's what the `bin/authors_update.py` script is for.

**Comment by asmeurer** [comment]
The release script should run the authors and mailmap scripts to make sure they are up-to-date, although it is good to run them periodically off-release to keep them updated. The 1.6.2 release wouldn't get any updates if it is just based off of 1.6.1 with the same authors.

**Pull request closed without merging**
