### PR TITLE
[ci skip] Update reference link in dpll.py (old link broken)

### PR DESCRIPTION
**Pull request by sumith1896**

### CODE REVIEW

**Comment by aktech** [comment]
It seems you need to enable travis testing by amending the commit message in order to make this PR merge-able.

**Comment by debugger22** [comment]
Could have been merged by org admins though. :)

**Comment by Sumith1896** [comment]
No problem, forgot about this. Will amend the message and send it in again maybe.

**Comment by Sumith1896** [comment]
ping @asmeurer

**Comment by leosartaj** [comment]
+1

**Comment by Sumith1896** [comment]
Could you merge this @leosartaj ? I don't have access.

**Comment by Sumith1896** [comment]
Thanks @leosartaj

**Pull request merged**
