### PR TITLE
[WIP] Use pytest for travis tests

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

See #16120 

#### Brief description of what is fixed or changed

This is an experiment to see if pytest can reduce the total run time of the test suite on Travis.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This didn't have the desired effect of reducing the total time needed to run the tests. I will have a think about whether it can be improved.

**Comment by asmeurer** [comment]
The one downside of pytest is that it's slow. I don't think this is a SymPy thing. I've noticed it is slow on every project I've used it on. 

This is what happens when I run `pytest` on SymPy master:

```
sympymaster%=$pytest
========================================================================== test session starts ==========================================================================
platform darwin -- Python 3.7.3, pytest-5.3.1, py-1.8.1, pluggy-0.13.0
rootdir: /Users/aaronmeurer/Documents/Python/sympy/sympy, inifile: pytest.ini, testpaths: sympy, doc/src
plugins: hypothesis-4.50.8, xonsh-0.9.13, mock-1.13.0, cov-2.7.1, flaky-3.6.1, aiohttp-0.3.0
collected 9556 items / 1 error / 9555 selected

================================================================================ ERRORS =================================================================================
__________________________________________________________ ERROR collecting sympy/testing/tests/test_pytest.py __________________________________________________________
ImportError while importing test module '/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/testing/tests/test_pytest.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sympy/testing/tests/test_pytest.py:3: in <module>
    from sympy.testing.pytest import (raises, warns, ignore_warnings,
E   ImportError: cannot import name 'Failed' from 'sympy.testing.pytest' (/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/testing/pytest.py)
=========================================================================== warnings summary ============================================================================
/Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py:47
  /Users/aaronmeurer/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/latest/warnings.html
                                                                            DO *NOT* COMMIT!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================ 1 warning, 1 error in 78.98s (0:01:18) =================================================================
```

Aside from the error, note the runtime. It takes over a minute just to collect the tests! `./bin/test` on the other hand, starts running the tests instantly. 

It looks like `pytest` is a lot faster the second time around, only taking 10 seconds (which is still too much IMO), so I guess it caches stuff. But that doesn't really help for Travis.

**Comment by oscarbenjamin** [comment]
The main reason I use pytest is because it is fast! In particular running tests in parallel (e.g. `-n8`) makes a huge difference. Also rerunning failed tests (`--lf`) is a massive speed-boost while working on something.

The test collection is slow because of the assert rewriting. You can use `--assert=plain` to disable that. I guess that's why it is faster on the second run.

The intention of this PR is to test what happens running with `-n2` on Travis. Theoretically Travis gives 2 cores to each job so if we can leverage that it might make the tests run faster.

**Comment by czgdp1807** [comment]
Are we going to use `pytest` for travis tests?

**Comment by czgdp1807** [comment]
@oscarbenjamin Are we going to use `pytest`?

**Comment by oscarbenjamin** [comment]
Closing in favour of #24291

**Pull request closed without merging**
