### PR TITLE
[WIP] columnspace: Implementation of columnspace of a matrix (fix to issue #8961)

### PR DESCRIPTION
**Pull request by sumith1896**
Implementation of columnspace on the same lines as that of the
already implemented nullspace.
Example:

```
In[1]: A=Matrix([[1,1,2],[2,1,3],[3,1,4]])
In[2]: A.columnspace()
Out[2]: [[1], [1]]
         [ ], [ ]
         [2], [1]
         [ ], [ ]
         [3], [1]
```

### CODE REVIEW

**Comment by moorepants** [comment]
You'll need to add some tests to make sure the function does what it is supposed to, especially if there happen to be edge cases. Pick some known problem/solutions that test the functionality and add it to the test_matrices.py file.

**Comment by moorepants** [comment]
What about this fact: http://en.wikipedia.org/wiki/Column_space#Relation_to_the_left_null_space ?

Maybe that is why it isn't implemented. 

> It follows that the left null space (the null space of AT) is the orthogonal complement to the column space of A.

Can you simply use the nullspace computation to compute the column space? If so, you may not want to duplicate functionality.

**Comment by Sumith1896** [comment]
Given basis of left null space,the null space of matrix with rows as the basis of left null space is the column space.Hence according to me,the feature of column space has to be implemented but we have to discuss which one of the two methods is better.

**Comment by moorepants** [comment]
Regardless of the method, please add some tests so we see that it does the correct thing.

**Comment by Sumith1896** [comment]
@moorepants The tests are up

**Comment by shivamvats** [comment]
Your tests in test_columnspace function are failing. Please run the tests locally and debug them.

**Comment by Sumith1896** [comment]
When I run the test updated in test_matrices.py,  it passes in ./bin/isympy but not when I run ./bin/test.
Any help?

**Comment by Sumith1896** [comment]
Tests now implemented for columnspace now pass but the cost of adding
`from sympy.solvers import solve` in test_matrices.py. Is this a problem? If yes, what is the alternate way doing this.

**Comment by shivamvats** [comment]
There is no problem with importing `solve` as long as you need it.

**Comment by moorepants** [comment]
What happened here? Commits are gone and this closed?

**Pull request closed without merging**
