### PR TITLE
MRG: Allow for complex Numpy scalars in sympify

### PR DESCRIPTION
**Pull request by matthew-brett**
As of Sympy 1.1, the following raises a recursion error:

>>> c = np.longcomplex(1 + 1j)
>>> print(sympify(c))

This is because the sympify code had the following:

   if not isinstance(a, np.floating):
       return sympify(np.asscalar(a))

In the case of `c` above, it is not `np.floating` type (it's complex)
and `np.asscalar(c)` returns another numpy scalar (rather than a Python
scalar, as would be the case for the `np.complex` type), so causing the
loop to go into infinite recursion.

Add handling of the complex case directly in the sympify clause above,
and add test for `np.longcomplex` type.

While I'm at it, add test for `np.longdouble` type, which will be
`np.float96` on 32-bit platforms, `np.float128` on 64-bit.

### CODE REVIEW

**Comment by asmeurer** [comment]
Should be aware of https://github.com/sympy/sympy/issues/12902. Let's make sure this works on 32-bit systems (aside from the existing failures).  Travis doesn't run the tests in 32-bit, so we need to test manually.

**Comment by asmeurer** [comment]
I am +1 to the changes once we confirm that they work.

**Comment by asmeurer** [comment]
OK, I am doing a 1.1.1 release branch. Can you rebase this (I want to avoid unrelated changes from master since the original 1.1 branch)?

**Comment by matthew-brett** [comment]
I've done a cherry pick against 1.1.1 - is that what you mean?

https://github.com/sympy/sympy/pull/12917

**Comment by asmeurer** [comment]
That's fine too (GitHub lets you change the base of the PR, which is what I did, but it doesn't matter). Closing this.

**Pull request closed without merging**
