### PR TITLE
[WIP] Add MatchPy to SymPy

### PR DESCRIPTION
**Pull request by arihantparsoya**
This is WIP to import [MatchPy](https://github.com/HPAC/matchpy) code to SymPy. MatchPy is originally written in Python3.6 and I have used [3to2](https://bitbucket.org/amentajo/lib3to2) to make it compatible with Python2.

#### Notes:
* MatchPy uses few modules which are only available for python3 but I have used backport versions of those modules(such as [typing](https://github.com/python/typing/tree/master/python2)(backport version of `typing`) and [funcsigs](https://github.com/aliles/funcsigs)(backport version of `inspect`)). I have added those modules temporarily for now.
* I have re-written the tests which are already present in MatchPy. 

#### TODO:
- [ ] Add pattern.expressions
- [ ] Add pattern.matching
- [ ] Add Docstrings for all functions.

### CODE REVIEW

**Comment by moorepants** [comment]
Note that we can't just copy other people's code and include it in SymPy like this. It seems MatchPy is licensed with the MIT license, so we could theoretically copy the code (with proper attribution), but it is generally poor practice in Python development to duplicate code like this. If you want to use MatchPy in the SymPy codebase I would suggest making it a dependency of SymPy (optional or required).

**Comment by parsoyaarihant** [comment]
@moorepants , MatchPy is originally written in python3.6 which prevents the possibility that we can import MatchPy into SymPy. I have used `3to2` to convert MatchPy code to python2.

Also, SymPy does not encourage using external libraries.

**Comment by Upabjojr** [comment]
@parsoyaarihant let's not merge it into SymPy, we can temporarily work on a separate repository. Remember to include MatchPy's license if you derive any piece of code from their code.

**Comment by parsoyaarihant** [comment]
@Upabjojr , do you want me to create a seperate repository for Rubi?

MatchPy have some external dependencies which will be required to be added if we are adding MatchPy to SymPy.

In case, MatchPy's conversion to Python2 doesn't work as expected. Should I start working on implemening MatchPy algorithms in SymPy?

**Comment by moorepants** [comment]
I suggest contacting the MatchPy developer and discussing your needs. Maybe he will allow you to submit a PR to his codebase to make it compatible with 2.7 or to include a py 3to2 option for building it and releasing to PyPi/Conda.

**Comment by moorepants** [comment]
And I think that we will certainly add an optional dependency to SymPy and if you have a good case, and Rubi implementation might be one, then it could be worth have a required dependency.

**Comment by Upabjojr** [comment]
@parsoyaarihant Let's first make sure that we can import RUBI into MatchPy. I am not sure that we can import 100% of the rules. I would leave the integration of MatchPy into SymPy as the last step.

**Comment by parsoyaarihant** [comment]
So, shall I continue adding `Constraints` in [https://github.com/parsoyaarihant/Rubi-MatchPy](https://github.com/parsoyaarihant/Rubi-MatchPy) ?

Abdullah is already working on parsing Rules from [Downvalues[]](https://raw.githubusercontent.com/Upabjojr/RUBI_integration_rules/master/RUBI_DownValues_FullForm.txt) you posted.

I think it will be very helpful if we write down our timeline for the project.

**Pull request closed without merging**
