### PR TITLE
[WIP] Orient axes: Proposing a functionality to align axes of two reference frames

### PR DESCRIPTION
**Pull request by angadhn**
Here, I have proposed two functions that allow a user to align axes of two frames with each other that are index agnostic (i.e. A.y can be aligned with N.z). Of course, one can trivially do this using orient but this is a more trivial implementation. By opening this PR, I am hoping to get some insight on what would be a good implementation for this. The two options that I have proposed are called alignyz and align, the latter being more generic. The code should be fairly clear but I can elucidate some more, if needed.

### CODE REVIEW

**Comment by angadhn** [comment]
@moorepants @sympy/mechanics

**Comment by czgdp1807** [comment]
ping @moorepants 
@angadhn Thanks for the contribution. Would you still like to work on this? 
Please do not close this PR.

**Comment by czgdp1807** [comment]
ping @sympy/mechanics Is this needed?

**Comment by czgdp1807** [comment]
Closing this due to inactivity for long time. Thanks for your contributions.

**Pull request closed without merging**
