### PR TITLE
Remove use of Vector.simp in sympy.physics.vector and .mechanics

### PR DESCRIPTION
**Pull request by moorepants**
#### Brief description of what is fixed or changed

`Vector.simp` is a user convenience so that you don't have to explicitly simplify physics vectors when working with them. I think this should be deprecated, but to start I'd like to remove all uses of it in the code base and documentation. The tests can call simplify commands explicitly. We can leave it in as an undocumented feature for uers, but I think it is best that users also explicitly simplify things. Using `Vector.simp = True` will inevitably cause undesired slow downs when working interactively.

Setting this in the unit tests seems to possibly leak into other tests. See https://github.com/sympy/sympy/pull/24896#issuecomment-1484119679. But I'm not quite sure about that.

Here are the uses:

```
grep -r "Vector\.simp" --include "*.py"
sympy/physics/mechanics/tests/test_kane3.py:Vector.simp = False
sympy/physics/mechanics/tests/test_joint.py:Vector.simp = True
sympy/physics/vector/vector.py:        if Vector.simp:
sympy/physics/vector/vector.py:        >>> Vector.simp = True
sympy/physics/vector/functions.py:                if Vector.simp:
sympy/physics/vector/tests/test_vector.py:Vector.simp = True
sympy/physics/vector/tests/test_output.py:Vector.simp = True
sympy/physics/vector/tests/test_frame.py:Vector.simp = True
sympy/physics/vector/tests/test_functions.py:Vector.simp = True
sympy/physics/vector/tests/test_dyadic.py:Vector.simp = True
sympy/physics/vector/frame.py:        If Vector.simp is True, returns a simplified version of the mapped
sympy/physics/vector/frame.py:        if (otherframe, Vector.simp) in self._var_dict:
sympy/physics/vector/frame.py:            return self._var_dict[(otherframe, Vector.simp)]
sympy/physics/vector/frame.py:                if Vector.simp:
sympy/physics/vector/frame.py:            self._var_dict[(otherframe, Vector.simp)] = mapping
sympy/physics/vector/dyadic.py:        >>> Vector.simp = True
```

#### Release Notes

* physics.vector
  * Removed use of Vector.simp in the documentation and unit tests.

### CODE REVIEW

**Comment by moorepants** [comment]
@TJStienstra any idea why I'm getting all the symengine failures?

**Comment by moorepants** [comment]
Seems like symengine requires simplify here when sympy doesn't:

```
>       assert angle.xreplace({u: 1}) == 0
E       assert acos(1/3 + (1/3)*sqrt(2)*sqrt(3)*sin(acos((1/3)*sqrt(3)))) == 0
E        +  where acos(1/3 + (1/3)*sqrt(2)*sqrt(3)*sin(acos((1/3)*sqrt(3)))) = <built-in method xreplace of acos object at 0x7f619e3076d0>({u_J(t): 1})
E        +    where <built-in method xreplace of acos object at 0x7f619e3076d0> = acos(u_J(t)*(1/3 + (1/3)*sqrt(2)*sqrt(3)*sin(acos((1/3)*sqrt(3))))/sqrt(u_J(t)**2)).xreplace
```

**Comment by TJStienstra** [comment]
> Seems like symengine requires simplify here when sympy doesn't:

Yes, just figured out the same thing. I think it is actually not simplify like behaviour but `doit`

**Comment by TJStienstra** [comment]
The easy fix would be to use `_simplify_matrix(compute_mat - expected_mat) == zeros(3, 1)`

**Comment by moorepants** [comment]
I'm getting:

```
*** AttributeError: 'Mul' object has no attribute 'could_extract_minus_sign'
```

guessing that is a missing method in symengine.

**Comment by moorepants** [comment]
I also don't understand why I'm getting these errors now. These tests passed with symengine before.

**Comment by TJStienstra** [comment]
> What about for comparing vectors? I'd rather not convert them to matrices first.

Agreed, currently looking through what fixed can be made.



> I also don't understand why I'm getting these errors now. These tests passed with symengine before.

Well there was probably a `Vector.simp = True` somewhere.

**Comment by TJStienstra** [comment]
Just went through the broken tests caused by the symengine and fixed them by simplifying the subtraction of the computed and expected answer.

**Review by tjstienstra — APPROVED** [review]
LGTM? Thanks for fixing.

**Pull request merged**
