### PR TITLE
Fixed orient_space_fixed doctest.

### PR DESCRIPTION
**Pull request by moorepants**
#### Brief description of what is fixed or changed

Fixes broken doctest introduced in https://github.com/sympy/sympy/pull/20318

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by moorepants** [comment]
@oscarbenjamin This should fix the doctest.

**Comment by oscarbenjamin** [comment]
Thanks. This looks good to me. Tests aren't finished but I'll set this to auto-merge.

**Comment by sidhu1012** [comment]
The failed test doesn't seem to be related with this or #20318


_______ sympy/functions/special/tests/test_elliptic_integrals.py:test_P ________
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/functions/special/tests/test_elliptic_integrals.py", line 158, in test_P
    assert td(P(rx, ry, m), m)
AssertionError

 tests finished: 7231 passed, 1 failed, 242 skipped, 140 expected to fail, 
4 expected to fail but passed, in 1928.16 seconds

**Comment by moorepants** [comment]
That is this https://github.com/sympy/sympy/issues/20933, so maybe we should just merge this.

**Comment by sidhu1012** [comment]
> That is this https://github.com/sympy/sympy/issues/20933, so maybe we should just merge this.

Yes it should be merged

**Comment by moorepants** [comment]
I'll let @oscarbenjamin do that as I don't know how the mpmath issue is being handled.

**Comment by oscarbenjamin** [comment]
In #20944 I'm just proposing to comment out those tests that fail due to mpmath. They won't be able to pass until it gets fixed in mpmath and only then if there is a new release.

**Comment by oscarbenjamin** [comment]
I've just pushed that change here.

**Comment by moorepants** [comment]
This is failing on Travis on master:
```
_________ sympy.physics.vector.frame.ReferenceFrame.orient_space_fixed _________

File "/home/travis/virtualenv/python3.8.7/lib/python3.8/site-packages/sympy-1.8.dev0-py3.8.egg/sympy/physics/vector/frame.py", line 838, in sympy.physics.vector.frame.ReferenceFrame.orient_space_fixed

Failed example:

    B.dcm(N).simplify()

Expected:

    Matrix([

    [ sin(q1)*sin(q2)*sin(q3) + cos(q1)*cos(q3), sin(q1)*cos(q2), sin(q1)*sin(q2)*cos(q3) - sin(q3)*cos(q1)],

    [-sin(q1)*cos(q3) + sin(q2)*sin(q3)*cos(q1), cos(q1)*cos(q2), sin(q1)*sin(q3) + sin(q2)*cos(q1)*cos(q3)],

    [                           sin(q3)*cos(q2),        -sin(q2),                           cos(q2)*cos(q3)]])

Got:

    Matrix([

    [ sin(q1)*sin(q2)*sin(q3) + cos(q1)*cos(q3), sin(q1)*cos(q2),                                                                                sin(q1)*sin(q2)*cos(q3) - sin(q3)*cos(q1)],

    [-sin(q1)*cos(q3) + sin(q2)*sin(q3)*cos(q1), cos(q1)*cos(q2), sin(-q1 + q2 + q3)/4 - sin(q1 - q2 + q3)/4 + sin(q1 + q2 - q3)/4 + sin(q1 + q2 + q3)/4 + cos(q1 - q3)/2 - cos(q1 + q3)/2],

    [                           sin(q3)*cos(q2),        -sin(q2),                                                                                                          cos(q2)*cos(q3)]])

===== tests finished: 3936 passed, 1 failed, 13 skipped, in 372.28 seconds =====
```

Seems like different results on Travis vs the new CI.

**Comment by oscarbenjamin** [comment]
Could this depend on the mpmath version (recently updated) or on any other dependencies?

**Comment by oscarbenjamin** [comment]
Looks like Travis and Actions are both using the same mpmath version:
```
Downloading mpmath-1.2.1-py3-none-any.whl (532 kB)
```

**Comment by oscarbenjamin** [comment]
Is it possible that the output is nondeterministic?

**Comment by oscarbenjamin** [comment]
Running this locally I find that it fails but only if I run the whole doctest suite. If I just run the doctests for this particular file then it passes. I think it might be non-deterministic and perhaps depends on the order in which the tests are run.

Does this test use vector calculations?

I have seen cache-related problems with vector before where I think VectorAdd can store different results in the cache.

**Comment by oscarbenjamin** [comment]
It does depend on the order of the tests.

This passes:
```
$ bin/doctest sympy/physics/vector/frame.py 
====================================================== test process starts =======================================================
executable:         /Users/enojb/current/sympy/sympy/venv/bin/python  (3.8.5-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 2.0.8
numpy:              None
hash randomization: on (PYTHONHASHSEED=1577120259)

sympy/physics/vector/frame.py[15] ...............                                                                             [OK]

========================================== tests finished: 15 passed, in 31.57 seconds ===========================================
```
However if I run all tests then it fails:
```
$ bin/doctest
====================================================== test process starts =======================================================
executable:         /Users/enojb/current/sympy/sympy/venv/bin/python  (3.8.5-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 2.0.8
numpy:              None
hash randomization: on (PYTHONHASHSEED=1904710110)

sympy/abc.py[1] .                                                                                                             [OK]
sympy/series/sequences.py[17] .................                                                                               [OK]
...
sympy/physics/vector/frame.py[15] .....F.........                                                                           [FAIL]
...
__________________________________________________________________________________________________________________________________
__________________________________ sympy.physics.vector.frame.ReferenceFrame.orient_space_fixed __________________________________
File "/Users/enojb/current/sympy/sympy/sympy/physics/vector/frame.py", line 838, in sympy.physics.vector.frame.ReferenceFrame.orient_space_fixed
Failed example:
    B.dcm(N).simplify()
Expected:
    Matrix([
    [ sin(q1)*sin(q2)*sin(q3) + cos(q1)*cos(q3), sin(q1)*cos(q2), sin(q1)*sin(q2)*cos(q3) - sin(q3)*cos(q1)],
    [-sin(q1)*cos(q3) + sin(q2)*sin(q3)*cos(q1), cos(q1)*cos(q2), sin(q1)*sin(q3) + sin(q2)*cos(q1)*cos(q3)],
    [                           sin(q3)*cos(q2),        -sin(q2),                           cos(q2)*cos(q3)]])
Got:
    Matrix([
    [ sin(q1)*sin(q2)*sin(q3) + cos(q1)*cos(q3), sin(q1)*cos(q2),                                                                                sin(q1)*sin(q2)*cos(q3) - sin(q3)*cos(q1)],
    [-sin(q1)*cos(q3) + sin(q2)*sin(q3)*cos(q1), cos(q1)*cos(q2), sin(-q1 + q2 + q3)/4 - sin(q1 - q2 + q3)/4 + sin(q1 + q2 - q3)/4 + sin(q1 + q2 + q3)/4 + cos(q1 - q3)/2 - cos(q1 + q3)/2],
    [                           sin(q3)*cos(q2),        -sin(q2),                                                                                                          cos(q2)*cos(q3)]])

============================== tests finished: 3939 passed, 1 failed, 12 skipped, in 643.77 seconds ==============================
DO *NOT* COMMIT!
```

**Comment by oscarbenjamin** [comment]
In fact the failure can be seen just running the physics doctests:
```
$ bin/doctest sympy/physics/
```

**Comment by moorepants** [comment]
I'm testing a fix.

**Comment by oscarbenjamin** [comment]
In fact only this is needed to see the failure:
```
$ bin/doctest sympy/physics/vector/
```

**Comment by oscarbenjamin** [comment]
> I'm testing a fix.

Great. I think I've got the other immediate CI problems fixed in #20944 so if you can fix this one then we're back to green.

**Comment by moorepants** [comment]
It occurs if dyadic.py is tested before frame.py:

bin/doctest sympy/physics/vector/dyadic.py sympy/physics/vector/frame.py

**Comment by oscarbenjamin** [comment]
What happens if you use `SYMPY_USE_CACHE=no`?

**Comment by moorepants** [comment]
Still fails.

**Comment by oscarbenjamin** [comment]
But does it fail both ways?

**Comment by moorepants** [comment]
I'm going to bed. The easiest thing would be to remove that portion of the doctest and open an issue about this. I'm not sure yet what is causing this.

**Comment by sidhu1012** [comment]
Just found that , this issue was not introduced in #20318. It is an old issue just saw ver 1.7 with similar issue.

https://github.com/sympy/sympy/blob/9e8f62e059d83178c1d8a1e19acac5473bdbf1c1/sympy/physics/vector/frame.py#L639-L642

**Comment by moorepants** [comment]
Looks like I added the docstring here: https://github.com/sympy/sympy/commit/477d1fa4c8cb58cf064ba2d0c5bcf0cd034691f7 and decided to skip the test then.

**Comment by moorepants** [comment]
This may be an issue that's been here since ReferenceFrame was introduced.

**Pull request merged**
