### PR TITLE
Fix enum antipattern practices for `galois_group`

### LINKED ISSUE #24782: galois: enum attributes deprecated in Python 3.12
This gives a DeprecationWarning under Python 3.12 alpha 5:
```
      File "/home/runner/work/sympy/sympy/sympy/combinatorics/galois.py", line 83, in get_perm_group
        if self == self.C4:
                   ^^^^^^^
      File "/opt/hostedtoolcache/Python/3.12.0-alpha.5/x64/lib/python3.12/enum.py", line 210, in __get__
        warnings.warn(
    DeprecationWarning: `member.member` access (e.g. `Color.RED.BLUE`) is deprecated and will be removed in 3.14.
```
This causes the doctests to fail in #24776.

We need to get this fixed in both master and also on the 1.12 branch that I have just created for the release.

_Originally posted by @oscarbenjamin in https://github.com/sympy/sympy/pull/24420#discussion_r1117406136_

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

Fixes #24782

#### Brief description of what is fixed or changed

I'm changing the structure of galois group table to be functional than object-oriented, 
such that it is not using some antipattern practices that is getting warned by Python 3.12

I'm not sure that using 'enum' with custom methods is pro-pattern, and the only feature we all need is some lazy table of constants, so we can just use dictionary for the purpose.
since this is before the release, we have time to reorganize the public API without deprecation.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
CC @skieffer

**Comment by skieffer** [comment]
Why not just replace each of the deprecated tests
```python
self == self.X
```
with
```python
self == type(self).X
```

**Comment by sylee957** [comment]
> self == type(self).X

I don't think that that is common pattern than just using `<class name>.<attribute>` syntax though.

**Comment by skieffer** [comment]
> using `<class name>.<attribute>` syntax

Yes, I agree that that's better than `type(self)`. I've done it that way in #24788, as an alternative resolution.

**Comment by skieffer** [comment]
I think that, for users, there's a lot that's good about object-oriented design.

As a user, I'm much happier if I can do
```python
B = A.get_a_related_thing()
```
than if I have to do
```python
from library import related_thing_getter
B = related_thing_getter(A)
```

**Comment by sylee957** [comment]
> I think that, for users, there's a lot that's good about object-oriented design.

That is in fact, trivially possible with the module system that many python developers overlook.

```python3
import library

B = library.related_thing_getter(A)
```

But I agree that I would go in the direction of https://github.com/sympy/sympy/pull/24788 if that is more minimal fix though.

**Pull request closed without merging**
