### PR TITLE
Fixes to some predicates in new assumptions regarding float arguments

### LINKED ISSUE #9636: Floats shouldn't be even, odd or prime in new assumptions
```
In [1]: from sympy import *

In [2]: a = S(1.0)

In [3]: a.is_odd
Out[3]: False

In [4]: ask(Q.odd(a))
Out[4]: True
```

Same goes for even and prime. Composite works fine.

### PR DESCRIPTION
**Pull request by debugger22**
Fixes #9636 
- `isprime(Float)` now returns `False`
- `ask(Q.integer(Float))` now returns `False`
- `ask(Q.prime(Float))` now returns `False`
- `ask(Q.composite(Float))` now returns `False`
- `ask(Q.even(Float))` now returns `False`
- `ask(Q.odd(Float))` now returns `False`

`satask` already behaves as expected.

@asmeurer please review.

### CODE REVIEW

**Comment by jksuom** [comment]
It is possible to think of returning ``None`` in some cases. For example, if the ``_mpf_`` of a ``Float`` happens to be an integer, we cannot exclude it from the possibilities with certainty. The same applies, if ``_mpf_`` differs from an integer by less than ``_prec``.

**Comment by debugger22** [comment]
Thanks for the comment! Could you please show an example using old assumptions for either possibilities.

**Comment by jksuom** [comment]
I'm not sure if you mean this kind of example, but this is what the old assumptions give.
```
>>> Float(1.0).is_integer
False
>>> Float(1.0 + 10**(-100)).is_integer
False
```
In either case, the ``Float`` is intended to denote a real number within a small interval determined by the precision (~2**(-53) by default, I think). In both cases the interval contains the integer 1. Hence I think it is not quite correct to give a definitive ``False`` as the answer.

However, this may have no significance in practise. I don't think an application dealing with floating point numbers would be interested in their values being integers let alone odd or prime.

**Comment by debugger22** [comment]
I think I understand your concern here. My point is not just about the value of the float. If we have an object of `Float`, we should not classify it as an integer. However, Python itself thinks `1.0 == 1` to be `True`. I can't decide here. Perhaps, this needs more eyes.

**Comment by jksuom** [comment]
> If we have an object of Float, we should not classify it as an integer.

I fully agree. We should not allow ``Float(1.0).is_integer`` to be ``True`` (as in Python).

**Comment by debugger22** [comment]
> However, this may have no significance in practise. I don't think an application dealing with floating point numbers would be interested in their values being integers let alone odd or prime.

I second that and returning `None` will do no good other than just confusing people.

**Comment by asmeurer** [comment]
I agree that 1.0 being considered integer (which is what this basically boils down to) seems odd. I'm not sure what the correct thing to do here is. This issue does come up a lot in various places. Note that in SymPy

```
In [1]: S(1.0) == S(1)
Out[1]: True
```

**Comment by asmeurer** [comment]
Also in the old assumptions:

```
In [2]: S(1.0).is_integer
Out[2]: False
```

There's a decent chance that someone thought about this already, since that is giving False and not None. So we should look for old discussions.

**Comment by jksuom** [comment]
```commit 1f7d52b02d4b0a1fc5709a70eced49f6dceda3e6
Author: Chris Smith <smichr@gmail.com>
Date:   Sun Jan 29 15:03:20 2012 +0545

    let Float == float pass if possible; Float == Float only if same
```

**Comment by jksuom** [comment]
```
commit 830637b9dafa1336b0acf40454c0ba1c63b743bb
Author: Chris Smith <smichr@gmail.com>
Date:   Thu Jan 26 02:43:00 2012 +0545

    round() added to miscellaneous functions; Float mods
    
 ```
followed by a longish discussion.

**Comment by asmeurer** [comment]
Also 9c359bc93

**Comment by asmeurer** [comment]
In particular https://github.com/sympy/sympy/commit/9c359bc9358fe6318db1352516557b4702c9ce85#diff-6cd5274897d73197c25bc41e9afe63e4R721.

**Comment by asmeurer** [comment]
That comes from #1743.

**Comment by debugger22** [comment]
Here's what happens in Mathematica:
```
In[1]:= IntegerQ[1.0]

Out[1]= False

In[15]:= PrimeQ[3.0]

Out[15]= False

In[16]:= OddQ[3.0]

Out[16]= False
```

**Comment by asmeurer** [comment]
How does Mathematica deal with equality of 1.0 and 1?

**Comment by debugger22** [comment]
```
In[1]:= 1.0 == 1

Out[1]= True
```

**Comment by asmeurer** [comment]
Let's merge this and see where it goes. These sorts of issues never seem to be as well thought out in SymPy as they should be. If we start ending up with hacks like `_aresame` to workaround this in the assumptions then we should revisit this from a design point of view. As it is now, this keeps compatibility with the old assumptions, and doesn't seem to break anything (yet).

**Pull request merged**
