### PR TITLE
Fix failing master branch

### PR DESCRIPTION
**Pull request by sidhu1012**
#### References to other Issues or PRs

#21725

#### Brief description of what is fixed or changed
Change the way `pi` was being used to pass the failing test case.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by moorepants** [comment]
Please show the local text with symengine here so we know it works before merging.

**Comment by sidhu1012** [comment]
> Please show the local text with symengine here so we know it works before merging.

Can you pls tell me how to do that?

**Comment by moorepants** [comment]
You need to install symengine locally then run the tests that are failing on master. If you haven't been running tests locally, Testing  is explained in the development workflow document: https://github.com/sympy/sympy/wiki/Development-workflow#be-sure-that-all-tests-of-sympy-pass

**Comment by sidhu1012** [comment]
I have been running tests locally but , idk how to test it with `symengine`.

**Comment by sidhu1012** [comment]
I pip installed `symengine` and then ran bin/test failing test cases and they all pass.

**Comment by moorepants** [comment]
Have you set the `USE_SYMENGINE` environment variable and are sure symengine is running? Also, it is always helpful to post relevant input/output to the thread here.

**Comment by smichr** [comment]
What is failing?
```python
>>> [i%pi==0 and (i/pi).is_odd for i in (S.Zero, pi, 2*pi, 3*pi, pi*3/2)]
[False, True, False, True, False]
```
If the angle could ever be `3*pi` then your mods will fail. Is the angle at this point normalized to be between -pi and pi or 0 and 2*pi?

trig identities use functions to get at the coefficients of pi.

**Comment by sidhu1012** [comment]
> What is failing?
> ```python
> >>> [i%pi==0 and (i/pi).is_odd for i in (S.Zero, pi, 2*pi, 3*pi, pi*3/2)]
> [False, True, False, True, False]
> ```
> If the angle could ever be `3*pi` then your mods will fail. Is the angle at this point normalized to be between -pi and pi or 0 and 2*pi?
> 
> trig identities use functions to get at the coefficients of pi.

I have changed this though, but angle would be [0, pi]

**Comment by oscarbenjamin** [comment]
> I pip installed `symengine`

Which version?

**Comment by oscarbenjamin** [comment]
The "References to other Issues or PRs" section in the PR template should be used. Please include a reference to something that explains where this PR came from.

**Comment by sidhu1012** [comment]
> Which version?

Latest(0.7.2)

**Comment by sidhu1012** [comment]
In current branch it gives

```
bin/test USE_SYMENGINE=true sympy/physics/mechanics/tests/test_joint.py
====================================================== test process starts ======================================================
executable:         /root/sympy/.venv/bin/python  (3.8.5-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              None
random seed:        83003798
hash randomization: on (PYTHONHASHSEED=4082976917)

sympy/physics/mechanics/tests/test_joint.py[6] ......                                                                        [OK]

=========================================== tests finished: 6 passed, in 6.33 seconds ===========================================
```

**Comment by sidhu1012** [comment]
It passes even on mater

```
bin/test USE_SYMENGINE=true sympy/physics/mechanics/tests/test_joint.py
====================================================== test process starts ======================================================
executable:         /root/sympy/.venv/bin/python  (3.8.5-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              None
random seed:        65122839
hash randomization: on (PYTHONHASHSEED=3297973685)

sympy/physics/mechanics/tests/test_joint.py[6] ......                                                                        [OK]

=========================================== tests finished: 6 passed, in 4.28 seconds ===========================================
```

**Comment by sidhu1012** [comment]
Current error on travis is-

```
Still running (30 of 30): conda create -q -n test-environment matchpy numpy scipy gmpy2 matplotlib aesara llvmlite autowrap cython wurlitzer python-symengine tensorflow numexpr ipython antlr-python-runtime>=4.7,<4.8 antlr>=4.7,<4.8 cloudpickle pyglet pycosat lfortran python-clang lxml
Timeout (30 minutes) reached. Terminating "conda create -q -n test-environment matchpy numpy scipy gmpy2 matplotlib aesara llvmlite autowrap cython wurlitzer python-symengine tensorflow numexpr ipython antlr-python-runtime>=4.7,<4.8 antlr>=4.7,<4.8 cloudpickle pyglet pycosat lfortran python-clang lxml"
```

**Comment by oscarbenjamin** [comment]
> > Which version?
> 
> Latest(0.7.2)

You should try this with the version of symengine that was failing on Travis. You need to be able to reproduce the failure before you can confirm any fix for it.

**Comment by sidhu1012** [comment]
@oscarbenjamin But #21725 changed that . Now it uses the latest version and is still failing using latest version.

**Comment by sidhu1012** [comment]
I might suggest merging this PR may solve the problem as I changed the problematic code.

**Comment by sidhu1012** [comment]
@oscarbenjamin Why does same tests pass on GitHub Actions and fail on travis.

**Comment by oscarbenjamin** [comment]
> Now it uses the latest version and is still failing using latest version.

Have you been able to reproduce the problem locally with any version?

**Comment by sidhu1012** [comment]
> Have you been able to reproduce the problem locally with any version?

No , I haven't tried with the older version of symengine yet.

**Comment by oscarbenjamin** [comment]
> > Have you been able to reproduce the problem locally with any version?
> 
> No , I haven't tried with the older version of symengine yet.

It's hard to confirm any fix if the issue hasn't bee reproduced outside of Travis. It's not hard to install a different version of symengine e.g. `pip install symengine==0.5.1`.

**Comment by sidhu1012** [comment]
Yes ik, just a bit occupied. I'll do that soon.

**Comment by moorepants** [comment]
Going to merge this, we will check the conda timeout separately.

**Pull request merged**
