### PR TITLE
An implementation of Pade approximants

### LINKED ISSUE #14215: approximants.py, in the series folder, is it correct
The docs say that it performs Pade approximation
Pade approximants of a function f are a sequence of rational functions which converge to f
In an example, a finite list of Fibonacci numbers is given, and then approximants is applied to the list to create a list of rational functions
Which function is being approximated
This seems very strange to me
When I have seen Pade approximants being used, it would be of the form `Pade(exp(x), 0)`, where it would produce f_1, f_2, f_3, ... , a sequence of rational functions that approximate exp in a neighbourhood of `0`

### PR DESCRIPTION
**Pull request by BeigeHydra3114**
#### References to other Issues or PRs

Fixes #14215

#### Brief description of what is fixed or changed

pade(f, M, N)

Calculates the Pade approximant p/q to the function f at the origin, where deg(p) = M and deg(q) = N
p = p_0 + ... + p_M*x^M  and  q = 1 + q_1x + ... + q_N*x^N

>>> pade(exp(x), 2, 2)
        {p_0: 1, p_1: 1/2, p_2: 1/12, q_1: -1/2, q_2: 1/12}

#### Other comments

The coefficients are calculated and returned to the user
    
I want to extract the coefficients from solve_undetermined_coeffs(t, coeffs) and then create the polynomials p and q and then return (p,q) to the user, but I don't know how to extract the p_i and the q_j from solve_undetermined_coeffs(t, coeffs)
I saw on the net that if y = solve_undetermined_coeffs() and y = {a: 1, b: 1/2, c: 1/12} then the values can be accessed by doing c_0 = y[a]
But I tried v_2 = u[p_2] and it didn't work

I would like to delete approximants.py

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
It would be better to open an issue, show your code there and discuss whether a function should be added rather than opening a pull request just yet.

SymPy already has some existing functionality such as the `approximants` function.

**Comment by smichr** [comment]
If you write `solve_undetermined_coeffs(t, coeffs, x)` you get

```python
>>> pade(exp(x),2,3)
{p_2: 1/20, p_1: 2/5, q_3: -1/60, q_2: 3/20, q_1: -3/5, p_0: 1}
```

**Comment by BeigeHydra3114** [comment]
"SymPy already has some existing functionality such as the approximants function." 
You have code that doesn't work, that no-one uses, that makes no sense, that should be deleted, and I present you with code that works right now, and if someone shows me how to extract the coefficients, then I can return the polynomials to the user

"If you write solve_undetermined_coeffs(t, coeffs, x) you get

>>> pade(exp(x),2,3)
{p_2: 1/20, p_1: 2/5, q_3: -1/60, q_2: 3/20, q_1: -3/5, p_0: 1}"
I don't understand, are you saying that this is false

**Comment by oscarbenjamin** [comment]
> You have code that doesn't work, that no-one uses, that makes no sense, that should be deleted, and I present you with code that works right now, and if someone shows me how to extract the coefficients, then I can return the polynomials to the user

There are many problems with the code that you have written here. I considered pointing out what the problems are but then I decided that there are too many. That is one reason why I have suggested opening an issue to discuss this instead of a pull request.

You might be right that the current code is not useful but:

1. You should be more careful about your language when talking with others in the SymPy community because your comments come across as rude.
2. There needs to be some discussion before deciding what to change or add in the code.

I'm going to close this pull request. If you would like to improve SymPy's capabilities for Pade approximants then please open an issue to discuss it. I don't think that any change like this should be merged until there is a review and an agreement about what the best interface would be.

**Pull request closed without merging**
