### PR TITLE
WIP - Use connected components to split systems in solve

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

Replaces #16299 

This is a PR from my fork rather than the branch I accidentally created in sympy/sympy (#16299) so the original discussion is there.

#### Brief description of what is fixed or changed

Uses the new connected_components function from #16225 to split systems of equations in solve. As an example a system like
```
solve([a-b, a+b+1, c-d, c-d+e, e-2], [a, b, c, d, e])
```
would be split into two parts:
```
solve([a-b, a+b+1], [a, b])
solve([c-d, c-d+e, e-2], [c, d, e])
```
The solution set for the full system is then the Cartesian product of the solution sets for the individual subsystems. Where it is possible to split the system like this solve should be faster as a result of this PR.

#### Release Notes

* solvers
    * solve is faster in many cases for partitionable systems of equations.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Timings for this PR vs master.

First we use these scripts. This is linsys.py
```python
# linsys.py

from sympy import *
import time

def make_sys(N):
    xs = symbols('x:%d' % N)
    ys = symbols('y:%d' % N)
    eqs = []
    for xi, yi in zip(xs, ys):
        eqs.append(xi + yi - 1)
        eqs.append(xi - yi)
    syms = xs + ys
    return eqs, syms

for n in range(1, 10):
    n = 2**n
    eqs, syms = make_sys(n)
    start = time.time()
    solve(eqs, syms)
    print('n=%2d, %.2f secs' % (n, time.time()-start))
```
And this is polysys.py:
```python
# polysys.py

from sympy import *
import time

def make_polysys(N):
    xs = symbols('x:%d' % N)
    ys = symbols('y:%d' % N)
    eqs = []
    for xi, yi in zip(xs, ys):
        eqs.append(xi**2 + yi**2-1)
        eqs.append(xi + yi - 2)
    syms = xs + ys
    return eqs, syms

for n in range(10):
    eqs, syms = make_polysys(n)
    start = time.time()
    solve(eqs, syms)
    print('n=%2d, %.2f secs' % (n, time.time()-start))
```
Each of these scripts generates different sizes of partitionable systems of equations.

The timings for linsys.py are:

linsys.py (master):
```console
$ python linsys.py 
n= 2, 0.02 secs
n= 4, 0.04 secs
n= 8, 0.10 secs
n=16, 0.28 secs
n=32, 1.00 secs
n=64, 4.14 secs
n=128, 19.71 secs
n=256, 108.48 secs
^C
```
linsys.py (this PR):
```console
$ python linsys.py 
n= 2, 0.03 secs
n= 4, 0.03 secs
n= 8, 0.06 secs
n=16, 0.12 secs
n=32, 0.24 secs
n=64, 0.47 secs
n=128, 1.00 secs
n=256, 2.91 secs
n=512, 6.02 secs
```

The timings for polysys.py are:

polysys.py (master):
```console
$ python polysys.py 
n= 0, 0.00 secs
n= 1, 0.66 secs
n= 2, 0.39 secs
n= 3, 1.29 secs
n= 4, 2.55 secs
n= 5, 5.84 secs
n= 6, 13.94 secs
n= 7, 31.95 secs
n= 8, 67.48 secs
n= 9, 154.84 secs
```
polysys.py (this PR):
```console
$ python polysys.py 
n= 0, 0.00 secs
n= 1, 0.35 secs
n= 2, 0.06 secs
n= 3, 0.08 secs
n= 4, 0.10 secs
n= 5, 0.12 secs
n= 6, 0.15 secs
n= 7, 0.19 secs
n= 8, 0.27 secs
n= 9, 0.39 secs
```

These scripts are engineered to show the difference the changes here can give. In many situations this PR makes no difference but in some it lead to a significant speedup.

**Comment by oscarbenjamin** [comment]
I think I might need to completely rewrite `solve_linear_system` so that it has enough consistency to make this work. It seems a bit messy and ad-hoc given that it describes itself as doing Gaussian elimination which should be fairly straight-forward. I can't immediately tell if all the ad-hoc code is needed for various good reasons or if the whole thing just needs cleaning up.

**Comment by oscarbenjamin** [comment]
> I think I might need to completely rewrite `solve_linear_system` so that it has enough consistency to make this work.

I take that back. There is one test case involving an overdetermined system that fails as a result of these changes. Handling overdetermined systems is a general problem with solve though and this PR doesn't really make that better or worse even if one particular case fails in the tests.

I think this can be merged and the issue of properly handling overdetermined systems can remain. The proper solution is something like #16861.

**Comment by czgdp1807** [comment]
This looks an awesome work.

**Comment by oscarbenjamin** [comment]
This PR is now subsumed in #18844

**Comment by oscarbenjamin** [comment]
@smichr Thinking about it now maybe it would be better to finish this PR and get it merged rather than mix it up with the work in #18844. The changes here are obvious concrete improvements whereas the other changes there are less certain or at least need nontrivial work.

**Pull request closed without merging**
