### PR TITLE
Convert the ODE module into a package

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

See also #18403 #18348 

#### Brief description of what is fixed or changed

Converts the ode module in sympy/solvers/ode.py into a package at sympy/solvers/ode with an `__init__.py` and an ode module (`sympy.solvers.ode.ode`) and a tests folder. Moves `test_ode.py` into the tests folder. The renames of `ode.py` and `test_ode.py` are done separately in one commit so that git can track them as renames. The other commit changes some imports etc to keep everything working after the rename.

#### Other comments

This is the start of an attempt to refactor the ode module. It is currently almost 10000 lines long and is one of the largest files in sympy. It is also messy and can do with tidying up. I propose to move it into a package and then refactor code into smaller modules, tidying up in the process (e.g. #18403). This is the first step which just converts the ode module into a package.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This is ready for review. I've moved the ode module into a package called `sympy.solvers.ode` and moved the ode module itself to `sympy.solvers.ode.ode` and `test_ode` into a tests directory.

The `sympy.solvers.ode` package `__init__.py` imports the few names from the ode module that are explicitly documented as being for users:
https://docs.sympy.org/1.5.1/modules/solvers/ode.html#user-functions
Those names are:
```
    'allhints', 'checkinfsol', 'checkodesol', 'classify_ode', 'dsolve',
    'homogeneous_order', 'infinitesimals',
```
I moved `allhints` there because it's the only other thing that is ever imported from the ode module in non-test code in sympy. I had to fix a few internal imports in test code to be e.g. `from sympy.solvers.ode.ode import constant_renumber`.

If anyone is importing the other functions from the ode module such as `odesimp`, `constantsimp`, `constant_renumber`, `ode_sol_simplicity`, 'classify_sysode`, `checksysodesol`  then this PR would break those imports. There are also a large number of `ode_*`  functions but those are not really useful except as part of `dsolve` so I don't imagine anyone is using them (it is a lot of names to move though).

My question is: should I make sure that `odesimp`, `constantsimp`, `constant_renumber`, `ode_sol_simplicity`, can still be imported from the ode module? These are documented although the documentation says
```
These functions are intended for internal use by dsolve() and others. Unlike User Functions, above, these are not intended for every-day use by ordinary SymPy users. Instead, functions such as dsolve() should be used. Nonetheless, these functions contain useful information in their docstrings on the various ODE solving methods. For this reason, they are documented here.
```
Others like `classify_sysode` and `checksysodesol` are not documented at all although these two are more likely to be useful (at least I often import them but maybe that's not typical). These two functions should really be incorporated into `classify_ode` and `checksysodesol` rather than public API though.

I've left the docs as they were but updated sphinx references to functions that are not importable from `sympy.solvers.ode` any more.

**Comment by Mohitbalwani26** [comment]
@oscarbenjamin can you please guide what is next step required for this so that i can work on this?

**Comment by oscarbenjamin** [comment]
I think that if this PR is going to be merged then we need that to happen first because otherwise it is confusing to rebase PRs over the renamed files. It can be done with
```
git rebase --strategy-option="rename-threshold=10" master
```
but I think it would get messy.

You could do some work on this based on #18403 but you would need to manually transfer the changes over later on because I will rewrite that PR from scratch.

I am just waiting for someone to review this PR and then the other work can continue.

**Comment by asmeurer** [comment]
I think constantsimp is useful outside of the ODE module. The others probably not. The simplicity thing we shouldn't make public API because we might want to change how that works. It was a rather simplicitistic (pardon the pun) idea on my part. I think we should also leave ourselves open for the hints being applied in a different order as well, maybe even an order that is specific to a given ODE.

**Comment by asmeurer** [comment]
Although those other functions are included in the documentation. I don't think it's a big deal to change their imports but if we end up removing them maybe we would need to deprecate them first. It might be good to indicate in the documentation better which functions should be treated as internal. Even for the `ode_` methods it isn't very clear in the documentation that they are only listed there because as documentation for the methods themselves, not as public API. Maybe when we move things to classes we can refactor the documentation somehow to make it clearer that the specific documentation is for a given hint.  In general, having internal functions documented on the docs site is fine but it needs to be clear that they are there for developers working on the module itself and shouldn't be relied on as public API.

**Comment by asmeurer** [comment]
I looked through the changes and they look fine, except for the constantsimp issue I mentioned. The other documentation issues can be addressed in a future PR if you want.

**Comment by asmeurer** [comment]
What about the code in deutils.py, and the pde code?

**Comment by oscarbenjamin** [comment]
> What about the code in deutils.py, and the pde code?

I'm not sure about those. The deutils code could be moved. The bulk of the pde module could be moved but I guess that the public functions will need to remain importable from `sympy.solvers.pde`.

I guess the only thing that would need resolving before this PR is if the resulting package should still be called "ode" if it also ends up containing code for PDEs. I can imagine having a package for ODEs, PDEs, SDEs, DAEs, DDEs, etc. That's probably overthinking things for now though given how little there is outside of the ODE module at the moment.

**Comment by asmeurer** [comment]
You could probably leave PDEs alone for now. There's very little there anyway. deutils tries to share a little bit of common code between pde and ode. I think some of that code would be part of the refactor. But maybe if you leave pde alone deutils should stay as it is so that it continues to work. 

I don't know about those other types of equations. Some of the ideas in the ode module could be used for the normal solvers as well, but that's a big rabbit hole. I would suggest getting just ode into a state that seems clean and extensible first.

**Comment by oscarbenjamin** [comment]
I've moved constantsimp so it is importable from `sympy.solvers.ode`. I haven't moved it any higher up the import chain. I've just ensured that it is still importable in the same way it was before.

Thanks for the review @asmeurer. I'm going to merge this now so that the other work can continue.

**Pull request merged**
