### PR TITLE
Piecewise lambdify printing for select uses lists instead of tuples.

### PR DESCRIPTION
**Pull request by richardotis**
Resolves sympy/sympy#9747

CC @aktech @asmeurer

### CODE REVIEW

**Comment by moorepants** [comment]
Is there not a test for this print function? If not, it'd be good to add one now.

**Comment by richardotis** [comment]
There are tests, but Travis doesn't test against older versions of numpy. In this case, the tests would fail when using numpy 1.8.2, but not 1.9.

**Comment by moorepants** [comment]
But shouldn't there be a test to check that this function produces brackets instead of parentheses?

**Comment by richardotis** [comment]
There's no a priori reason that the piecewise printer has to produce lists instead of tuples, only that the result is a valid call to `select`. In principle we should be indifferent to one or the other, but I wrote the printer to use tuples at first because it made future numba compatibility easier (numba/numba#1313). Since `select` in numpy 1.8.2 makes an assumption that the `choicelist` is a list, we have to make this change, but numpy 1.9.2+ doesn't care which sequence type we use.

I'm hesitant to add a test for it now, since type checks aren't generally Pythonic and this workaround becomes less necessary the older numpy 1.8 gets, but I'll defer to others on this.

**Comment by richardotis** [comment]
The existing test suite would have worked fine for catching this particular issue before merging the original PR, but AFAIK we're not testing against older versions of numpy currently. I know @certik is working hard to bring total testing time down and we can't test all possible configurations of course, but since numpy is such a popular package and it will be on nearly every user's machine, perhaps we should commit to testing against the last N versions of numpy.

**Comment by moorepants** [comment]
All I'm asking for is this:

```python
def my_printer():
    return "[]"

def test_my_printer():
    assert my_printer() == "[]"
    not assert my_printer() == "()"
```

If the printer should be printing brackets instead of parentheses and there is a known issue for this, then we should have a regression test. The regression test can also have a quick note explaining why lists are output instead of tuples, wrt to the numpy version issues.

**Comment by certik** [comment]
@richardotis we can probably add different numpy versions to our tests that we already run. That should be cheap.

**Comment by richardotis** [comment]
@moorepants What you're asking for is reasonable. I'll put together a test.

**Comment by moorepants** [comment]
Thanks, it should just be a few lines I think.

**Comment by richardotis** [comment]
@moorepants Take a look at this test. It should fail on current master but pass with this PR.

**Comment by moorepants** [comment]
Thanks, that looks good to me. +1

Once the Travis tests pass, I think it is mergeable.

**Comment by asmeurer** [comment]
I think our tests should only worry about the latest versions of dependencies, but it's fine to fix issues with older versions and add tests that can be run without the dependency. I think it's bad to try to support many versions of dependencies, as that would lead to a combinatorial explosion of our already huge test matrix (and numpy support is optional and only in a small part of SymPy anyway).

**Comment by asmeurer** [comment]
I'm also +1 to merge once the Travis tests pass.

**Comment by aktech** [comment]
+1

**Comment by aktech** [comment]
Thanks @richardotis  for fixing this.

**Pull request merged**
