### PR TITLE
changed stringpict.py

### PR DESCRIPTION
**Pull request by manipalsingh013**
changed line 69, 70, 71, 72 in stringpict.py file.
previous file contains:

```
newHeightBelowBaseline = max(
obj.height() - obj.baseline
for obj in objects:
newHeight = newBaseline + newHeightBelowBaseline
```

changed file contains:

```
newHeightBelowBaseline = max(obj.height() - obj.baseline for obj in objects)
newHeight = newBaseline + newHeightBelowBaseline
```

### CODE REVIEW

**Comment by moorepants** [comment]
Please give a more informative title and description for this PR. We have no idea what you are trying to accomplish and why.

**Comment by manipalsingh013** [comment]
@moorepants next time I will take care of that, btw I was trying to change it for  #10044 issue.

**Comment by asmeurer** [comment]
I don't understand what you did here. It looks like you just changed the formatting.

**Comment by manipalsingh013** [comment]
I'm thinking that I kind of changed nothing but I'm not getting that error anymore even when I run same commands using sympy repo not my forked one.

**Comment by asmeurer** [comment]
The fix here looks wrong. The code in stringpict shouldn't be aware of things like BaseVector (and by the way, use `isinstance` to check what the type of an object is).

**Comment by moorepants** [comment]
I'm closing, there is a fix in #10084

**Pull request closed without merging**
