### PR TITLE
Fixed Issue #9480

### PR DESCRIPTION
**Pull request by mcneela**
From my tests:

```
m = Matrix([[-5 + 5*sqrt(2), -5], [-5*sqrt(2)/2 + 5, -5*sqrt(2)/2]])
print("rank:", m.rank())
print("rref:", m.rref())

Output:

rank: 1
rref: (Matrix([
[1, -5/(-5 + 5*sqrt(2))],
[0,                           0]]), [0])
```

See [wolframalpha] for verification of correctness: http://www.wolframalpha.com/input/?i=rref%28%5B5*sqrt%282%29+-+5%2C+-5%5D%2C+%5B-5*sqrt%282%29%2F2%2B5%2C+-5*sqrt%282%29%2F2%5D%29

### CODE REVIEW

**Comment by mcneela** [comment]
How can I run these tests myself? I find it hard to believe so many failed due to the addition of a single line of code.

**Comment by mcneela** [comment]
@gxyd Since you worked on this issue previously, do you know whether using `simpfunc` causes issues somewhere downstream in the code that would lead to failed tests/builds?

**Comment by gxyd** [comment]
> How can I run these build tests myself?

Read [this](https://github.com/sympy/sympy/wiki/Development-workflow#id38) , which describes how you can run these tests locally on you machine. So you can first check whether `tests` pass on your machine or not.

**Comment by gxyd** [comment]
I would suggest you go through the [Development-Worflow](https://github.com/sympy/sympy/wiki/Development-workflow) , since see these points(like you should not work on your master-branch ever, always create a new branch for solving any issue) i mentioned.

**Comment by gxyd** [comment]
> @gxyd Since you worked on this issue previously, do you know whether using simpfunc causes issues somewhere downstream in the code that would lead to failed tests/builds?

For what even i did in my code, i followed [this](https://github.com/sympy/sympy/issues/9480#issuecomment-114052516) comment by @hargup . But i think that even failed in lot of tests. Reason being expressions like `x + 1/x` can be known to be `zero` or `non-zero` so they have `None` for `.is_zero` hence i made them to raise `NotImplementedError`, which caused `errors`  a lot of them.
But i think the solution can be to only raise a `UserWarning` see my [this](https://github.com/sympy/sympy/pull/9793#issuecomment-128993122) comment.

**Comment by mcneela** [comment]
Thanks for the advice. I'm new to this collaborative Github stuff, so those suggestions really help.

**Comment by moorepants** [comment]
Fixed in master with another PR.

**Pull request closed without merging**
