### PR TITLE
using travis_retry to minimize erroneous build failures

### PR DESCRIPTION
**Pull request by abloomston**
In working https://github.com/sympy/sympy/pull/9429, I've come across travis failing to build due to e.g. a network error downloading libraries. Per http://docs.travis-ci.com/user/build-timeouts/#Timeouts-installing-dependencies, wrapping library installation commands in travis_retry to minimize erroneous failures.

### CODE REVIEW

**Comment by sahilshekhawat** [comment]
[It here](http://docs.travis-ci.com/user/build-timeouts/) says that 
>We recommend careful use of travis_retry, as overusing it can extend your build time when there could be a deeper underlying issue.

To which  I agree, We have more actual failing tests than the ones who failing due to any other reason This will significantly increase time taken during tests. Whenever they fail due to any such error, you can just ask anyone to restart it.

**Comment by abloomston** [comment]
I've introduced travis_retry for only these commands:

* `pip install`
* `apt-get update/install`
* `python setup.py install`

I'm pretty confident that the first two would only fail due to a library installation error. My understanding is the last one also only installs libraries, but of that I am not certain. I have not introduced `travis_retry` for the actual running of tests, unless I am incorrect about `python setup.py install` above.

Thus, I think this change is safe to make, and does not violate best practices for travis. In fact, I think this change may reduce the overall time spent running travis builds, given that a network error on the last build job will currently lead to having to rerun all build jobs for that build.

Also, my experience with travis has been that these network errors can occur with some regularity. Let me know your thoughts @sahilshekhawat.

**Comment by sahilshekhawat** [comment]
Ah! Okay, I think you are right. It will not increase time for actual failing tests.
Thanks for addressing my concerns.

**Comment by toolforger** [comment]
> * `apt-get update/install`

apt-get update/install is installation at the OS level, so if that fails 
it's the testing infrastructure that fails.

 > * `pip install`
 > * `python setup.py install`

Most of these are Python module installation.

I'm not so sure about the install of SymPy itself.
I'd expect a normal test failure if the setup.py of SymPy itself is 
buggy, so I wouldn't want a retry for that. OTOH it's so rare that we do 
anything about that at all that I'm not sure that that's a problem in 
practice.

**Comment by abloomston** [comment]
Thanks for the clarification @toolforger.

I would say that if `python setup.py install` may fail due to library installation, and may also rarely fail due to developer-introduced error, then I would still prefix it with `travis_retry`. A failure mode would be that the build step runs `python setup.py install` a few times due to developer-introduced error, which shouldn't be too time or resource intensive since it is just library/sympy installation.

**Comment by certik** [comment]
I think it's a good idea, though we can just as well restart the failing tests manually, which I've been doing. I am fine either way on this one. Why not to only add the retry on the scipy and theano pip install, which as far as I know are the only ones that failed?

**Comment by certik** [comment]
Let us know. Ideally we should use Anaconda to install packages, and then hopefully we won't see any such failures anymore anyway.

**Comment by debugger22** [comment]
I second that. scipy installation fails a lot more times than anything else.

Also, I do not see number of retries configured. If we set that to `1`, I think we can merge it as it is.

**Comment by abloomston** [comment]
Hey @debugger22: `travis_retry` is hardcoded to check three times, per http://docs.travis-ci.com/user/build-timeouts/:

> you can wrap commands using the function travis_retry which checks the return code of a command, retrying it three times if the return code is non-zero.

**Comment by abloomston** [comment]
Hey @certik,

I think using `travis_retry` makes sense for two reasons:

1. Manual intervention from contributors such as yourself can be focused on problems that require careful deliberation and discussion, rather than routine (and easily automated) steps.
2. Reduce the overall load on travis due to e.g. a build failing on the last step due to a network error causes the entire build to have to be rerun.

I did not restrict the change to just scipy and theano because:

1. If other steps such as `apt-get` start to fail often in the future due to network errors in the future, we will not have to change the installation steps again.
2. To maintain consistency for library installation steps, so that when someone changes them in the future it is obvious that we are wrapping all library installation steps in `travis-retry`, rather than it being a judgement call for each additional library installation step.

If it helps convince you, from http://docs.travis-ci.com/user/build-timeouts/:

> Most of our build-internal commands are wrapped with travis_retry to reduce the impact of temporary network hiccups.

That being said, if the consensus is that we ought to only wrap particular library installation steps in `travis-retry`, I'll go ahead and modify the PR accordingly.

**Comment by toolforger** [comment]
Retries for libraries that are known to have frequent download fails are indeed routine tasks.
Retries for downloads/installs that didn't fail before are something that I'd like to know about, just to get a feeling for how problem-ridden the test runs are, and also to see whether there's something more serious that needs to be done than just retrying. (Ultimately this is the call of those who actually have to start the retries. I'm not one of them, so I won't insist on any particular approach.)

**Comment by abloomston** [comment]
Hey @toolforger-

If a certain call to e.g. `apt-get` often fails on the first try, but usually works the second or third, what would you do besides wrap the call in `travis_retry`? Not sure what else one would do in the context of an open source project such as sympy.

**Comment by toolforger** [comment]
Am 11.06.2015 um 09:49 schrieb Adam Bloomston:
> Hey @toolforger-
>
> If a certain call to e.g. `apt-get` often fails on the first try, but usually works the second or third, what would you do besides wrap the call in `travis_retry`?

I'd do exactly that, but AFAIK the "If" didn't happen. And there are 
other "If"s that may happen, such as an `apt-get` failing persistently, 
where retrying would just obscure the error messages.

**Comment by certik** [comment]
@abloomston I agree with you, but can you please confirm or disprove the following:

* only the scipy package fails to build sometimes
* theano fails to download sometimes
* mpmath fails to download sometimes

That's it.

If that's the case, I think all "pip" commands need it. Any other command doesn't need it, we should rather investigate what is going on.

So I think the apt-get commands do not need it. For the rest you can leave it.

**Comment by abloomston** [comment]
Hey @certik, see below as requested. Let me know how you'd like me to proceed.

# Methodology

* I examined builds at https://travis-ci.org/sympy/sympy/builds/ from number 13877 to 14538 (build numbers are strictly increasing with gaps).
* I looked at the first build job failure only.
* Due to time constraints, I did not double check this work, so I may be e.g. off by a count of a couple or so.

# Results

* Succeeded: 34
* Failed due to test run exceeding 50 minutes: 15
* Failed due to mpmath download failure: 9
* Failed due to build timeout in scipy install: 8
* Failed due to build timeout running tests: 4
* Failed due to test failure or syntax error in python code: 3
* Cancelled: 3

# Questions/comments

* Failures due to build timeout running tests and test run exceeding 50 minutes:
  * "No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself."
  * Usually also showed test failures occurring.
* I'm not 100% sure which step actually causes the mpmath install- is it `python setup.py install`?

# Answering your questions

> only the scipy package fails to build sometimes

scipy looks to timeout in building, rather than failing to download. Should the scipy install step be wrapped in `travis_wait`? See http://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received

> theano fails to download sometimes

I did not observe this occurring.

> mpmath fails to download sometimes

This occurred and triggered a build step failure in 9 out of 76 builds. When it occurred, the output showed:

    Reading http://mpmath.org
    error: timed out

**Comment by toolforger** [comment]
> scipy looks to timeout in building, rather than failing to download. Should the scipy install step be wrapped in `travis_wait`? See http://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received

I'm having a hard time imagining anything but a download timeout to make 
a build fail, so that's why I have always been counting these as 
download errors.

**Comment by abloomston** [comment]
Hey @certik, just wanted to ping you again about the analysis you requested above.

**Comment by certik** [comment]
@abloomston thanks a lot! I saw it and then got busy --- I'll look at it today. Sorry about that.

**Comment by certik** [comment]
This needs to be rebased.

**Comment by certik** [comment]
Sorry, not rebased, but *merged* with master.

**Comment by abloomston** [comment]
Hey @certik, once you tell me how you'd like proceed based on my analysis, i.e. what should have the `travis_retry`, I'll take care of this.

**Comment by abloomston** [comment]
Haven't heard back from @certik on analysis above, closing PR.

**Comment by certik** [comment]
@abloomston sorry about not replying, I forgot about this issue. Is it still a big problem with the failures? In other projects, we now use Conda to install binary packages of all dependencies and that seems to work very well.

**Comment by abloomston** [comment]
I'm not sure, I haven't been actively using sympy lately.

**Pull request closed without merging**
