### PR TITLE
fix in assumtions - addition of infinite terms

### PR DESCRIPTION
**Pull request by AnishShah**
Addresses issues from #8046 
Fixes issues 9-16 from the list

If any one term in Addition is infinite, then is_real/is_complex returns None
If `is_infinite/is_finite` is `None`, then `is_real/is_complex` property of Add depends on `is_real/is_complex` property of each term

### CODE REVIEW

**Comment by AnishShah** [comment]
Travis CI did not get triggered. Any idea?

**Comment by mvnnn** [comment]
@AnishShah push your commit again.
```
git push --force origin <branch-name>
```

**Comment by debugger22** [comment]
> git reset --hard <previous-head>
git cherry-pick <your-commit-head>
git push --force origin <branch-name>

Don't do this. Add a new commit.

**Comment by AnishShah** [comment]
@asmeurer @smichr Can you review this? If there are any changes, I will add a new commit.

**Comment by AnishShah** [comment]
If there are no changes, then I will just add a new commit.

**Comment by AnishShah** [comment]
@debugger22 Can you also have a look at this PR?

**Comment by mvnnn** [comment]
@AnishShah change something in your commit code and use ``` git rebase -i HEAD~2```  to merge your both commit and after doing this use
```
git push --force origin <branch-name>
```

**Comment by debugger22** [comment]
Let the tests run first. Perhaps something is up with Travis CI.

**Comment by AnishShah** [comment]
Travis build has started.I just closed & reopened the PR.

**Comment by asmeurer** [comment]
So the idea here is that you can't say anything about the sum of infinities because you might have oo + -oo, which is not real (even if both oo and -oo are considered real), correct? 

I think this just shows that it is a bad idea to allow oo to be real. The test you added, `(x + y).is_real == True` is wrong because of this.  

I don't think the workaround in this PR will work in the long run, i.e., checking if infinities are present and returning None if they are. If one were to later add more explicit facts to prevent `infinite positive + infinite negative == real`, one would get

```py
>>> (Symbol('x', positive=True) + Symbol('y', negative=True)).is_real
True
>>> # Currently gives None, but should give False
>>> (Symbol('x', positive=True, infinite=True) + Symbol('y', negative=True, infinite=True)).is_real
False
```

The problem is that this breaks monotonicity.  Adding additional assumptions shouldn't change a complete deduction (a True to a False or a False to a True, but it's OK to change a None to a True/False).

So I think I'm -1 to this change, because I think it might lead to inconsistencies in the future. Plus, this doesn't address the inconsistency between the old and new assumptions. In the new assumptions (at least in satask), I don't think a fix like this is possible, because facts can only be written down as (two-valued) logical statements. 

This feels like a bandaid that fixes the specific issues from #8046, but doesn't address the real problem (which is basically `oo.is_real == True`), and I feel like little fixes like this, especially ones that are technically wrong, will only make the assumptions more difficult to fix correctly.

**Comment by AnishShah** [comment]
@asmeurer Agree with you.. Closing this PR.. :+1:

**Pull request closed without merging**
