### PR TITLE
Remove assumption that Quantity is_nonzero

### PR DESCRIPTION
**Pull request by schymans**
Removing the assumption `is_nonzero = True` for quantities. Related to Issue #13267.

### CODE REVIEW

**Comment by asmeurer** [comment]
Apparently nothing breaks. Can you change the comment so it just deletes the line? I agree that quantities should be allowed to be zero.

**Comment by ylemkimon** [comment]
You also should change the _eval_is_positive(): https://github.com/schymans/sympy/blob/f574b4322e469f1c6b8f8debbf93c702a5afe67d/sympy/physics/units/quantities.py#L91-L92

**Comment by schymans** [comment]
Thanks for your feedback! @ylemkimon I do not see anything wrong with _eval_is_positive(). Could you explain?

**Comment by schymans** [comment]
The following is strange:
```python
from sympy import Eq
from sympy.physics.units import Quantity, length, time, meter, second
vel1 = Quantity('vel1', length/time, meter/second)
print vel1.is_zero
vel2 = Quantity('vel2', length/time, 0)
print vel2.is_zero
```
returns:
```
False
None
```
I would either expect 
```
False
True
```
or 
```
None
None
```

**Comment by ylemkimon** [comment]
As _eval_is_positive returns True when scale_factor is True, and positive number cannot be zero, so is_zero returns False.

**Comment by schymans** [comment]
Thanks, sympy is smarter than I thought. To avoid the `None`, I'll add:
```python
    def _eval_is_zero(self):
        return self.scale_factor.is_zero
```

**Comment by asmeurer** [comment]
Can you add a test please? Otherwise this looks good.

**Comment by smichr** [comment]
> A quantity is defined by its name, dimension and factor to a canonical quantity 

You cited this in the issue. It's not clear to me why a scale factor could/should be zero. Rather than patch Quantity to admit a scale factor of 0 it makes more sense to me to have instantiation raise an error `if scale.is_positive is not True`.

**Comment by Upabjojr** [comment]
> it makes more sense to me to have instantiation raise an error if scale.is_positive is not True.

I think we should be open to negative quantities, just think about the electron charge, that's a physical constant, and could be defined as a `Quantity` with negative `scale_factor`.

**Comment by schymans** [comment]
Plus, in the next step, I would like to extend the `Quantity` class to include physical variables with an unspecified scale factor. Or should this be called differently, e. g. `Variable`?

**Comment by smichr** [comment]
> defined as a Quantity with negative scale_factor

Or a positive scale on a negative base unit.

**Comment by Upabjojr** [comment]
> Plus, in the next step, I would like to extend the Quantity class to include physical variables with an unspecified scale factor.

What about just passing a symbol to the scale factor?

**Comment by schymans** [comment]
I tried, but this breaks unit checking, due to: https://github.com/sympy/sympy/blob/b0176512baf3cdad1f8494dcd63d11f24ef8e0cc/sympy/physics/units/quantities.py#L208

**Comment by Upabjojr** [comment]
You could change that line to `i.free_symbols == set() and not isinstance(i, Quantity)`

**Comment by schymans** [comment]
Thanks, but this breaks unit checking even for conventional quantities, i.e. the following does not raise an error, but it should:
```python
tim3 = Quantity('tim3', time, second)
len3 = Quantity('len3', length, meter)
len3 + tim3
```

**Comment by Upabjojr** [comment]
You're right. Maybe `Quantity.get_dimensional_expr` should be modified.

**Comment by schymans** [comment]
@jirikuncar might be be able to give some input here, as he wrote or re-wrote `_Quantity_constructor_postprocessor_Add` and `Quantity.get_dimensional_expr`.

**Comment by smichr** [comment]
>  I couldn't find out what canonical quantities are. I have seen some examples where quantities are used like physical variables, which is what I am doing, too. Perhaps we will need a separate class for this, with information on the unit system but no scale factor, and where assumptions can actually be specified for each separately.

It seems to me that separating Measurement from Quantity would be good. I still cannot see the reason to allow a 0 scale factor. (I now see the need for positive or negative, however, as the base unit of charge is related to the charge of a proton or electron by opposite scale factors.) A measurement is comprised of a magnitude, unit and uncertainty. It seems like what you are doing is wanting to use Quantity like Measurement via the scale factor.

**Comment by asmeurer** [comment]
If SymPy treats Measurement*Quantity like a product, then the assumptions will work the best if Quantity is positive.

**Comment by schymans** [comment]
Has there been any development on the Measurement class or is it just an idea? Since units are essentially Quantities, I would assume that a measurement would be the product of a number and a unit, perhaps accompanied by uncertainty, e.g. Measurement = float*Quantity. In this case, it would indeed make sense to define Quantity as positive only, but then does anything speak against calling 'Quantity' a 'Unit'?

**Comment by schymans** [comment]
Here is another issue related to the scale factor: https://github.com/sympy/sympy/issues/13379
Essentially, is there a way to enable conversions between e.g. Kelvin, Fahrenheit and Celcius throught the scale factor? I have not found a way yet.

**Comment by smichr** [comment]
Revisiting this now, I still feel confident that quantities are unsigned entities. It is the scale factors which have sign. But an entity exists so it cannot be 0 (hence it is nonzero). I believe we should remove the `_eval_is_positive` and not introduce the `_eval_is_zero` which conflates scale and quantity.
```
proton_charge = Quantity('proton', 'p+', charge, +1) 
electron_charge = Quantity('proton', 'e-', charge, -1) 
```
For the same reason `(3*feet).is_positive -> None` because it is a measurement *whose magnitude* has a sign but not the quantity as a whole.

**Comment by schymans** [comment]
The more I think about this, the more I think we need to distinguish between physical constants and units. Using `Quantity()` for both is ambiguous. A unit cannot be negative, but a physical constant can.

**Comment by czgdp1807** [comment]
@schymans Are you still working on it? Please add a release notes entry in the description. Thanks.
Refer, https://github.com/sympy/sympy/wiki/Writing-Release-Notes

**Comment by schymans** [comment]
Sorry, I abandoned this, as I realised that what we call a "Quantity" in sympy is actually a unit, which indeed should not evaluate to 0. I re-factored physical variables in https://github.com/environmentalscience/essm to be based on Symbol, rather than Quantity. I am closing this PR.

**Pull request closed without merging**
