### PR TITLE
Added a shortened URL for a reference in Crypto

### PR DESCRIPTION
**Pull request by Shikhar1998**
The given URL if directly copied and pasted will generate `not a valid URL on web archive`.
The reason is the addition of the blank spaces in front of the second line which is read as a character. 
So, added a shortened URL for convenience,

### CODE REVIEW

**Comment by jksuom** [comment]
How stable are these goo.gl addresses?

**Comment by Shikhar1998** [comment]
As far as I know they never expire. You can check here though.
https://groups.google.com/forum/#!searchin/google-url-shortener/lifetime%7Csort:relevance/google-url-shortener/6IJtdRCsqZM/ksIx_OwOxQ8J

**Comment by jksuom** [comment]
Maybe the original could be left as it is to show the origin, and then something like `short URL: https://goo.gl/ijr22d`, possibly in parentheses.

**Comment by jksuom** [comment]
Thanks!

**Comment by Shikhar1998** [comment]
It is my pleasure to contribute to Sympy. Thanks!

**Pull request merged**
