### PR TITLE
Remove Python 2 from the Travis tests

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### Brief description of what is fixed or changed

Removes Python 2 tests from Travis.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This PR represents officially dropping support for Python 2 so that 3.5 is the minimum supported version. This has a number of advantages:

1. A significant reduction in the test matrix (faster builds on Travis)
2. No need to waste time on fixing Python 2 vs Python 3 code differences
3. Lots of places in the codebase can be cleaned up
4. Can use new features like the typing module (new in Python 3.5)

Can we drop Python 2 now?

**Comment by asmeurer** [comment]
I'll think we'll eventually want to merge a lot of the Travis builds that do very little into a single build, perhaps by making different conda environments. Of course, it will only be better if the overhead from conda is less than the overhead from doing a separate build in the matrix, although there is also the global concurrent build limit.

**Comment by asmeurer** [comment]
I'm in favor of dropping Python 2 generally speaking, and this PR looks good to me.

**Comment by oscarbenjamin** [comment]
Okay, merging.

Python 2 support is officially dropped.

**Pull request merged**
