### PR TITLE
Add MultivariateNormal and MultivariateLaplace functions

### PR DESCRIPTION
**Pull request by ritesh99rakesh**
#### Brief description of what is fixed or changed
Add MultivariateNormal and MultivariateLaplace functions in `sympy/stats/joint_rv_types.py`

#### Other comments
Ping @sidhantnagpal 

#### Release Notes

- stats
    - Added MultivariateNormal and MultivariateLaplace functions in `sympy/stats/joint_rv_types.py`

### CODE REVIEW

**Comment by ritesh99rakesh** [comment]
Please review @Upabjojr

**Comment by sidhantnagpal** [comment]
Can you add docstring examples and include symbolic test(s)?

**Comment by ritesh99rakesh** [comment]
@sidhantnagpal for symbolic tests please refer to #17268

**Comment by czgdp1807** [comment]
I cannot figure out which issue was this PR was fixing. Can someone please let me know so that it can be concluded?

**Comment by czgdp1807** [comment]
AFAIK, `MultivariateNormal` and `MultivariateLaplace` distributions can be created by the existing constructors `Normal` and `Laplace`. Closing this for now. Please let us know if you think this can be re-opened. Thanks for the contributions.

**Pull request closed without merging**
