### PR TITLE
N-dim arrays now in the base namespace.

### PR DESCRIPTION
**Pull request by Upabjojr**
Can now be imported with `from sympy import Array` and so on.

### CODE REVIEW

**Comment by Upabjojr** [comment]
Any objection to merging this?

**Comment by jksuom** [comment]
This looks good, but I did wonder why MatrixBase could not be imported at the top of ndim_array.py. Would there be circularity?

**Comment by Upabjojr** [comment]
> This looks good, but I did wonder why MatrixBase could not be imported at the top of ndim_array.py. Would there be circularity?

I guess so, it couldn't call `from sympy import *` otherwise.

**Comment by jksuom** [comment]
Then I think this is good as it is.

**Pull request merged**
