### PR TITLE
Added function to derive by an array.

### PR DESCRIPTION
**Pull request by Upabjojr**

### CODE REVIEW

**Comment by smichr** [comment]
I'm not sure that this is to be preferred over list comprehensions (`[f.diff(x) for x in v]` or `[[f.diff(x) for f in funcs] for x in v]`). As far as I can tell, it's syntactical sugar for something that is already pretty straightforward to do in Python.

**Comment by Upabjojr** [comment]
@smichr
Would you express a matrix derivative by four nested list comprehensions?

All the algorithms in the differential geometry module are quite unreadable because of the extensive list comprehension usage.

And it's not syntactic sugar, nested list comprehension do not create an array object.

**Comment by Upabjojr** [comment]
@smichr this code could eventually be extended to support specialized algorithms for sparse arrays and matrices. It's definitely not syntactic sugar.

**Comment by Upabjojr** [comment]
@jksuom what do you think?

**Comment by jksuom** [comment]
I think I see your point. Arrays represented by lists might be comfortably handled by list comprehensions, but to take care of sparse representations a dedicated function will be necessary. Hence +1.

**Comment by Upabjojr** [comment]
Also, expressions like these are quite unreadable:
https://github.com/sympy/sympy/blob/ea7bd0bea05c31c093d7b856d06b43be203bc206/sympy/diffgeom/diffgeom.py#L1571

**Comment by jksuom** [comment]
I agree that they don't look nice. I'll merge in 24 hours if there are no more comments.

**Pull request merged**
