### PR TITLE
Updated the docstring in elementary.rst

### LINKED ISSUE #13949: Add the docstrings of real_root and cbrt to the HTML docs
The documentation of [root](http://docs.sympy.org/dev/modules/functions/elementary.html#root) says: 

> See also sympy.polys.rootoftools.rootof, sympy.core.power.integer_nthroot, sqrt, real_root

But `real_root` is not linked and not found anywhere on the site. It's an important function (not just syntactic sugar) as it's the only way to get -2 as the cubic root of -8, which is what a lot of people want. 

Also, `cbrt` is not even mentioned. That one **is** syntactic sugar for `x**Rational(1, 3)` but considering how many people don't understand the importance of using Rational vs `x**(1/3)` I think we should have it listed too. 

So I suggest adding `cbrt` and `real_root` at the end of [this rst file](https://github.com/sympy/sympy/blob/master/doc/src/modules/functions/elementary.rst), which will hopefully get them correctly linked from `root` description.

### PR DESCRIPTION
**Pull request by arighnac**
Fixes #13949 .

This PR adds `cbrt` and `real_root` in elementary.rst .

@normalhuman , @asmeurer please review.

### CODE REVIEW

**Comment by ArighnaIITG** [comment]
Ping @normalhuman .

**Review by gxyd — APPROVED** [review]
LGTM

**Comment by gxyd** [comment]
@ArighnaIITG considering that you've become somewhat comfortable with fixing issues. I would recommend that you fix more that just very trivial issues. (May be move to fixing medium-level issues)

This will also allow beginners (who haven't fixed any issue before) to get a little comfortable with the development workflow.

It is okay for this PR, but may be from the next one.

**Comment by ArighnaIITG** [comment]
Okay, I will keep that in mind from next time.

**Pull request merged**
