### PR TITLE
Fix for issue #9448: error in simplifying one complex number 

### PR DESCRIPTION
**Pull request by wanglongqi**
Constants argument should be real number in `nsimplify`. This is a possible fix for issue #9448.

### CODE REVIEW

**Comment by Sumith1896** [comment]
PR title can be changed, more descriptive. Mention the issue on commit message if you want to.
Just a suggestion, feel free to ignore. :smile:

**Comment by wanglongqi** [comment]
@Sumith1896 I tried to title this PR, did not find a suitable title. Any suggestion?

**Comment by Sumith1896** [comment]
I'll have to look into what this is doing, I'll suggest if I come up with something.
Btw the one reviewing this PR will put his views.

**Comment by hargup** [comment]
+1

**Pull request merged**
