### PR TITLE
[WIP] Fixes #issue 12254 extract_multiplicatively

### LINKED ISSUE #12254: cannot extract_multiplicatively(-2) from (-2*x - 2*y)
I think this might be a bug.
````
>>> (2+4*I).extract_multiplicatively(2)    # yes
1 + 2*I
>>> (-2-4*I).extract_multiplicatively(-1)   # yes
2 + 4*I
>>> (-2-4*I).extract_multiplicatively(-2)   # bug?
````
similarly:
````
>>> (2*x + 4*y + 8).extract_multiplicatively(2)   # yes
x + 2*y + 4
>>> (-2*x - 4*y - 8).extract_multiplicatively(2)    # yes
-x - 2*y - 4
>>> (-2*x - 4*y - 8).extract_multiplicatively(-1)    # yes
2*x + 4*y + 8
>>> (-2*x - 4*y - 8).extract_multiplicatively(-2)    # bug?
````

Assuming it is indeed a bug, here is why it happens:

Look in `core/expr.py` where:
````
>>> (-2*x - 4*y - 8).primitive()
(2, -x - 2*y - 4)
````
which is then made into a *non-evaluated* `Mul`, from which `-2` cannot be multiplicatively extracted; for example:
````
>>> Mul(2, -x).extract_multiplicatively(-2)
x
>>> Mul(2, -x, evaluate=False).extract_multiplicatively(-2)
````
@smichr do you think this is bug? (see your commit 8968b85310506c0a2b34f3d7aeb8e0d88f87885b: not clear whether we still need this special case anyway)

### PR DESCRIPTION
**Pull request by KTaruneshwar**
<!-- If this pull request fixes an issue please indicate which issue by typing "Fixes #12254 " below.>

### CODE REVIEW

**Comment by cbm755** [comment]
I think there may be some extra commits here?

**Comment by KTaruneshwarSai** [comment]
well hmm yes . I'm new to git so...having a bit problem in committing

**Comment by cbm755** [comment]
No problem, I changed the title to "WIP" so people know not to review it.  Remove that once you're happy with the commits.

1.  `git rebase -i origin/master` is probably how I would fix this.
2.  Then you can `git push -f ...` to force push.  In general don't do this during review but ok b/c of the "WIP" note.

**Comment by smichr** [comment]
I left a [comment](https://github.com/sympy/sympy/issues/12254#issuecomment-284921065) on the issue. I will look more closely at this when it is no longer WIP.

**Pull request closed without merging**
