### PR TITLE
Regression in matrix docs 2

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs
#15272 

#### Brief description of what is fixed or changed

I have recently found a lot of matrix docs from `common.py` missing after version `1.0` in the official website. 
As the same reason in #15272, I have added all the separate classes in the new file `common.rst`, except for dummy classes like `MatrixRequired`, `MatrixCommon`

- TODO
  - [x] Fix sphinx errors caused by misformatted docs inside.
  - [ ] (Optional) Adopt inherited methods.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by moorepants** [comment]
Since the matrix code is divided up into layers of classes. Would it be worth just showing the top level classes users are likely to use and use the `inherit_docstrings` flag in sphinx (http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_inherit_docstrings)?

**Comment by asmeurer** [comment]
We explicitly disabled that flag https://github.com/sympy/sympy/issues/14187. As I recall it was adding a lot of clutter and confusion with things like Expr subclasses getting the Expr docstring, which doesn't make sense on subclasses.

**Comment by asmeurer** [comment]
Can that flag be passed to individual `autoclass` directives? I agree it would make sense for the matrices.

**Comment by moorepants** [comment]
I think so:

```rst
.. autoclass:: Noodle
   :members:
   :inherited-members:
```

**Comment by asmeurer** [comment]
I think that's a little different. It pulls in the methods that are inherited, not just the ones defined on the class. The docstring flag makes it so that if a class doesn't have a docstring it shows the one for the superclass instead. But maybe inherited-members is really what we actually want for the matrix module.

**Comment by moorepants** [comment]
I think that you can always manually specify which methods you wan to be shown.

**Pull request merged**
