### PR TITLE
Fixed rational to use True as default  #11745

### PR DESCRIPTION
**Pull request by Lakshya1605**
#11745 @asmeurer  Please review

### CODE REVIEW

**Comment by asmeurer** [comment]
I'm still unconvinced this change is correct. Can you explain the effective difference it makes?

CC @smichr

**Comment by Lakshya1605** [comment]
@asmeurer  It just restores the  default of rational as "True" (as mentioned in the docstring) and regarding this issue it just sees to that "nfloat" function is not called.

**Comment by smichr** [comment]
Just a quick reaction: if the user says nothing about rational then it's float in -> convert to rational for solving -> float back out so I *think* the change is not correct.

**Comment by czgdp1807** [comment]
The associated issue has been fixed. So closing this one. Thanks @Lakshya1605 for the contribution. Please let us know if you want to re-open this for doing extra work if needed.

**Pull request closed without merging**
