### PR TITLE
corrected the documentation

### PR DESCRIPTION
**Pull request by harshagr70**
NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Please choose a better title for the issue like explain what documentation is being changed.

**Comment by harshagr70** [comment]
> Please choose a better title for the issue like explain what documentation is being changed.

ok !! thanks for helping me out

**Comment by 1e9abhi1e10** [comment]
Should reference the issue [#24342]( https://github.com/sympy/sympy/issues/24342 ) in the OP .

**Comment by sylee957** [comment]
I wasn't able to recognize this for https://github.com/sympy/sympy/pull/24435 but I'm closing this because the title is not indicative.

**Pull request closed without merging**
