### PR TITLE
Public name for quaternion logarithm

### LINKED ISSUE #26552: Why is the Quaternion logarithmic map given a private-looking name?
Why is `Quaternion._ln` not given a name like `Quaternion.log` and documented as part of the public interface?

This was asked a while back, but it was tangential to the main topic and thus ignored:

> BTW, Is it any reason to avoid conventional `log` name for method. There is only `_ln`. Leading underscore in the method name may confuse since it looks like a private method. Maybe, adding `log = _ln` to the class definition makes sense.

_Originally posted by @vr050714 in https://github.com/sympy/sympy/issues/21576#issuecomment-855421034_

It seems odd to me, especially since `Quaternion.exp` is public. There are many use cases of quaternions where we wish to go between the Lie group and Lie algebra in both directions.

### PR DESCRIPTION
**Pull request by jpreiss**
#### References to other Issues or PRs
Fixes #26552 

#### Brief description of what is fixed or changed
Renamed the quaternion logarithm method from `Quaternion._ln` to `Quaternion.log`.

#### Other comments
Previously the quaternion logarithm was called `_ln()`.  This was confusing because the quaternion exponential was given a normal "public" name `exp()`. The logarithm is equally important and was documented equally well, but had a "private" name.

Docstring updated to mirror that of `exp()`.

Renamed to `log()` instead of `ln()` because in most math software, `log` refers to the natural logarithm.

My own motivating interest in quaternion exp/log is the mappings between the Lie group SO(3) and its Lie algebra so(3) when using the unit quaternion double-covering to represent SO(3). In this context, logarithm bases other than *e* never occur. I would guess this is the most common use of quaternion exp/log, but I am not sure.

Not sure if we want to add a `_ln()` alias to avoid breaking old code? Or if it can be skipped because callers should not rely on methods that start with an underscore? Please advise.

#### Release Notes

* algebras
  * Renamed the Quaternion logarithm from `_ln` to `log`.

### CODE REVIEW

**Comment by asmeurer** [comment]
This change seems reasonable to me.

**Comment by jpreiss** [comment]
I see this was already merged, thank you! But just want to double-check that the maintainers are OK with removing the old method `_ln()` completely?

**Comment by sylee957** [comment]
> I see this was already merged, thank you! But just want to double-check that the maintainers are OK with removing the old method `_ln()` completely?

I can verify that nothing is broken, because nothing relevent is missing after I search the code `_ln`.
https://github.com/search?q=repo%3Asympy%2Fsympy%20_ln&type=code

It does not 100% guarantee that the change doesn't break anything in theory
(because in Python, you can use `getattr` to access names of methods by dynamically created strings, 
and if there is something broken with code like that, it is generally undecidable), 
However, for 99% of the cases, you can be confident after checking the codebase exhaustively by matching the string of the method names. 
This applies in general programming advices, especially for Python.

**Comment by asmeurer** [comment]
I think he meant more that there isn't other code that is using it. But I'm ok with removing it since the name was private.

**Pull request merged**
