### PR TITLE
[Functions]: Fixes AttributeError in limit evaluation

### PR DESCRIPTION
**Pull request by sachin-4099**
Addresses #19586 for the 1.6 branch (for 1.6.1)

#### Other Comments
Regression Test has been added.

#### Release Notes

* functions
  * Fixes `AttributeError` in limit evaluation

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Thanks. Could you add a test for this?

Also is there a test for this on master? If not then one should be added there before the issue is closed.

**Comment by sachin-4099** [comment]
Actually I was of the opinion that at both places no test is required. And that's why I didn't add one here as well.

**Comment by oscarbenjamin** [comment]
> Actually I was of the opinion that at both places no test is required. And that's why I didn't add one here as well.

The normal reason to add a test is to ensure that future changes will not lead to a similar issue and that this particular example will always give the expected result in future. Also you need to bear in mind that one reason the test might fail in future is because of changes in an unrelated part of the codebase. It's impossible for any one contributor to understand all of the possible effects of many of the changes that are made in sympy. For that reason it is good to have a continuously expanding set of test results especially where there is some case that has clearly been overlooked before.

In this particular example it's easy to see that your fix is correct. However the fact that this problem was previously unnoticed indicates that this particular codepath is untested. It's important to try to ensure that every line of code runs at some point during the tests so that e.g. systemic changes in the core can be accompanied with fixes across the codebase.

I don't necessarily disagree with you but why is it that you think no test is required?

**Comment by sachin-4099** [comment]
Alright I will add the test at both places.

**Comment by oscarbenjamin** [comment]
Again Github has not updated to reflect the fact that the Travis tests are complete even though it has registered the results from codecov (#19589).

I'm hoping that this comment will cause it to update.

**Comment by oscarbenjamin** [comment]
Actually it seems that the tests since the last commit have not finished. The link to Travis from the commit is pointing to the wrong build. The normal "details" link is missing

**Pull request merged**
