### PR TITLE
Mutable matrices should not use caches for eigenvectors and properties

### PR DESCRIPTION
**Pull request by sylee957**
#### Brief description of what is fixed or changed

I find that the original code is not careful about mutability of matrices.
https://github.com/sympy/sympy/blob/ce11e8bcb3a5353980f5c41a22fe517b8f5d8f13/sympy/matrices/matrices.py#L1426-L1462

For example, the second matrix is not diagonalizable, but with `clear_cache` set as `False`, it will constantly give wrong answer based on the stored value.

A more critical case would be the `diagonalize()` function, because it forces `clear_cache=False`
Like below, you can see the wrong result is given by cached variables.

Though it may be possible to make mutable matrices to use cache, but I think bookkeeping would be more complicated. So I have disabled cache for mutable matrices.

#### Other comments

I personally don't think that cacheing eigenvectors was originally good idea.
Eigenvectors can possibly be as large as the matrix itself.
And also I don't think that the cache is used by `eigenvects` function itself, or other functions that can make use of the result, like `eigenvals`, `jordan_form`, or ~~singular_values~~.

#### Release Notes

- matrices
  - Fixed `diagonalize` and `is_diagonalizable` giving wrong results for mutable matrices.

### CODE REVIEW

**Comment by moorepants** [comment]
There are things that have custom caches in SymPy. Would it make sense to switch to the "global" SymPy cache? My guess is that most of these custom caches could.

**Comment by asmeurer** [comment]
I think we have some custom caches in the core, like the int cache, but outside of the core we should use the global cache. 

At any rate, mutable things should use the cache at all. Maybe you could do it by caching the immutable variant, but I think it's simpler to just not cache at all, and we can worry about caching for the immutable one.

**Comment by asmeurer** [comment]
Also, unrelated to this issue, but I still think we should make `Matrix` point to `ImmutableMatrix` by default https://github.com/sympy/sympy/issues/6509.

**Comment by sylee957** [comment]
The tests are failing because of the deprecation warnings.

https://github.com/sympy/sympy/blob/a0711ebd8d1b58ce0930a882c2cff09e6678cb08/sympy/utilities/tests/test_pickling.py#L78-L87

I'm not sure about ignoring the SymPyDeprecationWarning here should be safe here

**Comment by oscarbenjamin** [comment]
> The tests are failing because of the deprecation warnings.

How are you running the tests? They are passing on Travis. Or is it just that you can see warnings in the Travis logs?

**Comment by sylee957** [comment]
The test just before had failed

**Comment by oscarbenjamin** [comment]
That was added in #15503. At the time I think I only saw warnings there for Py2. At the time it was only necessary for Py2 so it seemed best to put it in a version block. Also at the time it could have also been fixed by checking whether the attribute was 'message'.

Maybe a better fix would be to exclude the attributes that generate the warnings (probably `_cache_eigenvects`)

**Comment by oscarbenjamin** [comment]
Here is an improved version to supress these warnings:
```diff
diff --git a/sympy/utilities/tests/test_pickling.py b/sympy/utilities/tests/test_pickling.py
index 86098bcf95..deb47326be 100644
--- a/sympy/utilities/tests/test_pickling.py
+++ b/sympy/utilities/tests/test_pickling.py
@@ -32,7 +32,12 @@
 from sympy.external import import_module
 cloudpickle = import_module('cloudpickle')
 
-excluded_attrs = set(['_assumptions', '_mhash'])
+excluded_attrs = set(['_assumptions', '_mhash', 'message'])
+
+# XXX Can be removed if Py2 support is dropped.
+# Supresses warnings on Python 2.7
+if sys.version_info < (3,):
+    excluded_attrs.add('message')
 
 
 def check(a, exclude=[], check_attr=True):
@@ -68,23 +73,15 @@ def check(a, exclude=[], check_attr=True):
 
         def c(a, b, d):
             for i in d:
-                if not hasattr(a, i) or i in excluded_attrs:
+                if i in excluded_attrs or not hasattr(a, i):
                     continue
                 attr = getattr(a, i)
                 if not hasattr(attr, "__call__"):
                     assert hasattr(b, i), i
                     assert getattr(b, i) == attr, "%s != %s, protocol: %s" % (getattr(b, i), attr, protocol)
 
-        # XXX Can be removed if Py2 support is dropped.
-        # DeprecationWarnings on Python 2.6 from calling e.g. getattr(a, 'message')
-        # This check eliminates 800 warnings.
-        if sys.version_info < (3,):
-            with ignore_warnings(DeprecationWarning):
-                c(a, b, d1)
-                c(b, a, d2)
-        else:
-            c(a, b, d1)
-            c(b, a, d2)
+        c(a, b, d1)
+        c(b, a, d2)
```

You can probably fix the warnings you were seeing by adding to excluded_attrs.

This PR has merge conflicts now.

**Pull request merged**
