### PR TITLE
Remove space around **

### PR DESCRIPTION
**Pull request by anmolks**
This PR removes unnecessary spaces around `**` wherever required.

### CODE REVIEW

**Comment by toolforger** [comment]
PEP8 says that spaces may or may not be used around binary operators. If an expression has operators of different priority, spaces can be used to communicate what's higher priority.

I do not see that recommendation applied (and even made slightly less good in some places).
Can you fix that?

**Comment by Anmolks** [comment]
> I do not see that recommendation applied (and even made slightly less good in some places).
Can you fix that?

I would love to fix that but I need a couple of examples to actually understand the difference. Could you please point some?

**Comment by toolforger** [comment]
The usual convention is that operators with spaces around them are executed after operators with no spaces around them; if code follows this convention, it gives the reader a clue about the order in which operators are executed.

Changing ```Integral(exp(-x**2), (x, -oo, oo)) ** 2``` to ```Integral(exp(-x**2), (x, -oo, oo))**2``` hints that the final ```**2``` is executed very early, but in fact it happens last, so this is bad.

Changing ```Unbounded ** NonZero -> Unbounded``` to ```Unbounded**NonZero -> Unbounded``` is relatively irrelevant, the line is easily readable anyway (it does hint that ```**``` binds tighter than ```->```, but then ```->``` is not a Python operator so readers already know that it's ```Unbounded ** Zero``` and ```-> Unbounded```, not ```Unbounded **``` and ```NonZero->Unbounded```).

Changing ```Abs()<=1 ** Positive -> Bounded``` to ```Abs()<=1**Positive -> Bounded``` is good because ```**``` binds tighter than ```<=```.
Well, that would be the case if these were normal expressions; however, reading the code reveals that the author indeed meant to say that ```Abs()<=1``` is one unit, and ```Positive``` the other (i.e. the intended parentheses would have been ```(Abs()<=1) ** Positive -> Bounded```), so the changed code is actually misleading.
(Mechanically applying a rule tends to produce this kind of problem.)

Changing ```sign(expr.base) * abs(expr.base) ** expr.exp``` to ```sign(expr.base) * abs(expr.base)**expr.exp``` is in fact helpful. (Do you understand why?)

**Comment by asmeurer** [comment]
I think these are all fine, except for the ones at https://github.com/sympy/sympy/pull/9209/files#diff-56f3be0dac83a357c1fd96ca8ba15285R246, because it leads to confusion with the inequalities. SymPy prints `**` without spaces, so to have it different anywhere is just confusing.

**Comment by coder006** [comment]
+1 for @asmeurer's comments

**Comment by toolforger** [comment]
I agree that printed output is an important argument to consider.
It's not the only one; e.g. people tend to place spaces around ```**``` in situations like this: ```(a + b) ** 2```, because here, the ```**``` is applied after the ```+```. ```(a + b)**2``` is easy enough to read so I would probably still stick with the "do it like the printed output" argument, but things can get harder to see as in e.g. ```a + C*b + (super_complicated_expression)**5 + ...)**2 + integral(...)``` - here, my instinctive reaction would be that I'd want to write it as ``` ** 2``` just to leave a hint to future readers. (OTOH I'd probably want to break that expression into subexpressions that are small enough that there's no desire to add hints anymore... so YMMV)

**Comment by debugger22** [comment]
@Anmolks ping.

**Comment by Anmolks** [comment]
Closing

**Pull request closed without merging**
