### PR TITLE
Try mamba, since conda create is timing out.

### PR DESCRIPTION
**Pull request by moorepants**
#### References to other Issues or PRs

- Related #21728
- Related #21725

#### Brief description of what is fixed or changed

mamba solves this conda environment very quickly on my local machine. This is an easy way to buy some time on Travis given that the conda create command is taking very long now that we unpinned symengine.

This PR can only be confirmed after merge to master, since Travis only runs the relevant build on master.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by moorepants** [comment]
> I expect Travis will be disabled soon

Does that mean we shouldn't spend time getting it working again?

**Comment by moorepants** [comment]
I'm going to merge this to see if it works, for the time being.

**Comment by moorepants** [comment]
mamba installs the dependencies it seems but a test is now failing:

```
============================= test process starts ==============================

executable:         /home/travis/miniconda/envs/test-environment/bin/python  (3.9.6-final-0) [CPython]

architecture:       64-bit

cache:              yes

ground types:       gmpy 2.1.0b5

numpy:              1.21.0

random seed:        75077094

hash randomization: on (PYTHONHASHSEED=492547239)

sympy/interactive/tests/test_ipythonprinting.py[5] py-1.9.dev0-py3.9.egg.../home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 

The to_png function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.

  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)

/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 

The to_rgba function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.

  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)

/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 

The to_mask function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.

  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)

/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 

The MathtextBackendBitmap class was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.

  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)

./home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 

The to_png function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.

  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)

/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 

The to_rgba function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.

  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)

/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 

The to_mask function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.

  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)

/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 

The MathtextBackendBitmap class was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.

  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)

.                    [OK]

sympy/physics/quantum/tests/test_printing.py[16] .....f..........           [OK]

sympy/physics/vector/tests/test_printing.py[14] ..............              [OK]

sympy/printing/pretty/tests/test_pretty.py[143] ................................

................................................................................

...............................                                             [OK]

sympy/printing/tests/test_aesaracode.py[38] ................/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/aesara/graph/opt.py:232: UserWarning: Supervisor is not added. Please build a FunctionGraphvia aesara.compile.function.types.std_graph()or add the Supervisor class manually.

  sub_prof = optimizer.optimize(fgraph)

....................

..                                                                          [OK]

sympy/printing/tests/test_c.py[50] ........................................f....

.....                                                                       [OK]

sympy/printing/tests/test_codeprinter.py[3] ...                             [OK]

sympy/printing/tests/test_conventions.py[3] ..f                             [OK]

sympy/printing/tests/test_cupy.py[5] ..s..                                  [OK]

sympy/printing/tests/test_cxx.py[8] ........                                [OK]

sympy/printing/tests/test_dot.py[10] ..........                             [OK]

sympy/printing/tests/test_fortran.py[42] .......................................

...                                                                         [OK]

sympy/printing/tests/test_glsl.py[37] ..................................... [OK]

sympy/printing/tests/test_gtk.py[2] X.                                      [OK]

sympy/printing/tests/test_jscode.py[24] ........................            [OK]

sympy/printing/tests/test_julia.py[33] ...............f.................    [OK]

sympy/printing/tests/test_lambdarepr.py[10] ..........                      [OK]

sympy/printing/tests/test_latex.py[157] .........f..............................

......................................................................f.........

.....................................                                       [OK]m

sympy/printing/tests/test_llvmjit.py[16] ............Traceback (most recent call last):

  File "<stdin>", line 10, in <module>

Exception: Tests failed
```

@sidhu1012, fyi

**Comment by sidhu1012** [comment]
@moorepants All the failing tests I see here are printing errors.

**Pull request merged**
