### PR TITLE
Fix update-docs final version guard

### PR DESCRIPTION
**Pull request by hugokerstens**
#### References to other Issues or PRs
In #26688 it was noted that the guard that should not push non-final version to the public docs was not working. This fixes that.

#### Brief description of what is fixed or changed
The guard that prevents non-final versions to be pushed to the public docs is not working. This is due to accidentally using [`github.env.xxx`](https://docs.github.com/en/actions/learn-github-actions/contexts#:~:text=github.env) instead of `env.xxx`. This PR updates the guard.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by hugokerstens** [comment]
Apparently the `env` context is not available for `jobs.<job_id>.if`: https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability

A dirty fix would be to set the guard on the `if` of the final step, as `env` is available for `jobs.<job_id>.steps.if`.

**Comment by oscarbenjamin** [comment]
> Apparently the `env` context is not available for `jobs.<job_id>.if`:

According to the docs it has the `github, needs, vars, inputs` contexts and we are using the `github` context so should that not work?

The change here is to use `env` instead of `github` which seems like it definitely wouldn't work according to the docs.

**Comment by hugokerstens** [comment]
> we are using the `github` context so should that not work?

The `github.env` variable has an entirely different meaning: it's a string containing the path to a file on the runner containing environment variables ([source](https://docs.github.com/en/actions/learn-github-actions/contexts#:~:text=github.env)):

> `github.env`. `string`. Path on the runner to the file that sets environment variables from workflow commands. This file is unique to the current step and is a different file for each step in a job.

There's not really a nice fix available. [This issue comment](https://github.com/actions/runner/issues/2372#issuecomment-1591370444) suggests to use a dummy job that stores an output as a workaround, which I have now implemented.

**Comment by oscarbenjamin** [comment]
On the release branch if you add yourself to .mailmap then you also need to update AUTHORS:
```
bin/mailmap_check.py --update-authors
```

**Comment by oscarbenjamin** [comment]
Looks good. Thanks!

**Comment by oscarbenjamin** [comment]
Looks like this works:
https://github.com/sympy/sympy/actions/runs/9681838591

**Pull request merged**
