### PR TITLE
Fix divergence in cylindrical coordinates

### PR DESCRIPTION
**Pull request by lindsayad**
This fix is more general than my particular use case, but I wanted to
compute:

```python
from sympy.vector import divergence, gradient, Vector, CoordSys3D
R = CoordSys3D('R', transformation='cylindrical')
divergence(R.i)
```

The correct solution to this is 1/r, however, sympy returned zero
because it was detecting that no base scalars were in the provided
expression, and then using the special case code, returning zero. A
straight-forward solution to this is removing the special case code, and
simply returning a `Derivative` instantiation every time.

- vector
    - Always return `Derivative` instance from `_diff_conditional` in `operators.py` since the `coeffs` may be functions of the base scalars even if `expr` is not

### CODE REVIEW

**Comment by friyaz** [comment]
Looks good. Please add test cases.

**Review by friyaz — DISMISSED** [review]
@lindsayad please fix the flake test.  Importing `BaseScalar` is not needed. I think then we can get this merged.

**Comment by czgdp1807** [comment]
@lindsayad Would you like to conclude this PR? Please let us know and do NOT close this PR. Thanks for your contributions.

**Comment by lindsayad** [comment]
I would like to see it concluded. It looks like my change broke this test:
```
Failed example:
    delop.dot(C.x*C.i)
Expected:
    Derivative(C.x, C.x)
Got:
    Derivative(0, C.y) + Derivative(0, C.z) + Derivative(C.x, C.x)
```
I'm not surprised by this. I guess from my perspective, I would rather have more verbose output than sometimes have wrong output. If you guys agree, then I will change that test. I'm also open to other suggestions.

**Comment by czgdp1807** [comment]
> Derivative(0, C.y) + Derivative(0, C.z) + Derivative(C.x, C.x)

This notation seems better to me. At least it makes clear that `y` and `z` components are 0. Though what happens if we apply `simplify` to the above expression i.e., `(Derivative(0, C.y) + Derivative(0, C.z) + Derivative(C.x, C.x)).simplify()` or `simplify(Derivative(0, C.y) + Derivative(0, C.z) + Derivative(C.x, C.x))`.

@moorepants Any thoughts on this?

**Comment by smichr** [comment]
I will open an issue for adding a test.

**Comment by lindsayad** [comment]
Just yesterday I was on a new machine and manually updated this file when doing some MMS testing and I thought to myself that I really need to get this in. Thanks for getting this over the finish line!

**Pull request merged**
