### PR TITLE
Update .mailmap and AUTHORS

### PR DESCRIPTION
**Pull request by certik**
The same as #10239, but using topological ordering.

### CODE REVIEW

**Comment by asmeurer** [comment]
The only way I've checked for duplicates before is by searching for the person's first name and figuring out if it's the same person if I see it twice. I don't think there's a reliable way to do it automatically, other than some heuristics.

**Comment by certik** [comment]
I also search emails. But if you look at this case:

https://github.com/sympy/sympy/pull/10244/files#diff-c9d540715cff3469b65ddd01f614848bR218

I had to go to git log to figure out who added the person to AUTHORS and then bug @moorepants who committed it to help me de-duplicate it, since neither the name nor the email address is the same.

**Comment by asmeurer** [comment]
In that case you can guess by finding the pull request (https://github.com/sympy/sympy/pull/10098) and looking at the user's profile (https://github.com/mlda065). That's a bit complicated for automation, though.

**Comment by certik** [comment]
Indeed. I would do it by hand on a case by case basis. If tests pass, we can merge it, unless you have any other objections.

**Comment by asmeurer** [comment]
Are you planning to update the aboutus?

**Comment by certik** [comment]
Not in this PR, as I don't have time at the moment to work on that. But I want all current authors to be at least in AUTHORS.

**Comment by asmeurer** [comment]
Fine.

**Comment by certik** [comment]
Tests pass, merging this.

**Pull request merged**
