### PR TITLE
maint(ci): remove Python 2 import job from Actions

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
`py2-import` still shows up in the list of jobs being run on this PR.

**Comment by asmeurer** [comment]
If this can be run in under a minute on an existing job, then it is fine. But I agree it shouldn't have its own job.

**Comment by oscarbenjamin** [comment]
> If this can be run in under a minute on an existing job, then it is fine. But I agree it shouldn't have its own job.

Actually the problem is that CI is currently failing because of this job. The job fails trying to install mpmath which has recently updated and I guess does not support Python 2 any more but without having the correct metadata for pip to understand:
```
$ pip install -U mpmath
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting mpmath
  Using cached 
...
6.0.1/src/setuptools_scm/utils.py", line 41
        print(*k)
              ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7r/5s79v1k53sb1mzz7z_hh9tx0z0q4x7/T/pip-install-KW0ZHo/mpmath/
You are using pip version 19.0.3, however version 20.3.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by oscarbenjamin** [comment]
I've opened #21116 as an alternative

**Pull request closed without merging**
