### PR TITLE
Update lambdify to give the minimum over the first axis

### LINKED ISSUE #18742: Lambdify giving a different response pre- and post-rewrite
This may be a philosophical issue, but in my opinion a set of values passed to a lambdify of an underlying expression should always return the same numerical response, regardless of what form the original expression is written in. That is, the expression should survive a rewrite and expect to produce the same kind of (or same) lambdify output.

To wit:
```python3
import numpy as np
from sympy import symbols, lambdify, Min, Piecewise

x = symbols("x")
expr_a = Min(0.1*x + 3, x + 1, 0.5*x + 1)
f_a = lambdify(x, expr_a, "numpy")

expr_b = expr_a.rewrite(Piecewise)
f_b = lambdify(x, expr_b, "numpy")

x_vals = np.linspace(0, 10, 100)
y_vals_a = f_a(x_vals)
y_vals_b = f_b(x_vals)
```

In the above scenario `y_vals_a` and `y_vals_b` are different results, despite them being from the same expression (albeit the latter being from a rewrite of the expression).

```python3
In [5]: y_vals_a                                                                                                                            
Out[5]: 1.0

In [6]: y_vals_b                                                                                                                            
Out[6]: 
array([1.        , 1.05050505, 1.1010101 , 1.15151515, 1.2020202 ,
       1.25252525, 1.3030303 , 1.35353535, 1.4040404 , 1.45454545,
       1.50505051, 1.55555556, 1.60606061, 1.65656566, 1.70707071,
       1.75757576, 1.80808081, 1.85858586, 1.90909091, 1.95959596,
       2.01010101, 2.06060606, 2.11111111, 2.16161616, 2.21212121,
       2.26262626, 2.31313131, 2.36363636, 2.41414141, 2.46464646,
       2.51515152, 2.56565657, 2.61616162, 2.66666667, 2.71717172,
       2.76767677, 2.81818182, 2.86868687, 2.91919192, 2.96969697,
       3.02020202, 3.07070707, 3.12121212, 3.17171717, 3.22222222,
       3.27272727, 3.32323232, 3.37373737, 3.42424242, 3.47474747,
       3.50505051, 3.51515152, 3.52525253, 3.53535354, 3.54545455,
       3.55555556, 3.56565657, 3.57575758, 3.58585859, 3.5959596 ,
       3.60606061, 3.61616162, 3.62626263, 3.63636364, 3.64646465,
       3.65656566, 3.66666667, 3.67676768, 3.68686869, 3.6969697 ,
       3.70707071, 3.71717172, 3.72727273, 3.73737374, 3.74747475,
       3.75757576, 3.76767677, 3.77777778, 3.78787879, 3.7979798 ,
       3.80808081, 3.81818182, 3.82828283, 3.83838384, 3.84848485,
       3.85858586, 3.86868687, 3.87878788, 3.88888889, 3.8989899 ,
       3.90909091, 3.91919192, 3.92929293, 3.93939394, 3.94949495,
       3.95959596, 3.96969697, 3.97979798, 3.98989899, 4.        ])
```

This may be known behavior but I didn't find anything to corroborate that in all the sympy documentation that I read about [lambdify](https://docs.sympy.org/latest/modules/utilities/lambdify.html) and [numerical computation](https://docs.sympy.org/latest/modules/numeric-computation.html). If it is known then I'm happy to close this issue.

### PR DESCRIPTION
**Pull request by sbt4104**
#### References to other Issues or PRs
Fixes #18742 

#### Brief description of what is fixed or changed

Added axis=0 at the end of the funcstr.
amin((x + 1,0.1*x + 3,0.5*x + 1)) got updated to amin((x + 1,0.1*x + 3,0.5*x + 1), axis=0).

#### Other comments
I also want to apply for GSOC 2020, I am getting more familiar with sympy, I have used sympy before to solve handwritten equations. 
Please suggest changes.

### Release Notes

* utilities
    - Solving inconsistency in the lambdify when used with Min and Max.

### CODE REVIEW

**Comment by sbt4104** [comment]
**Code:**
`import numpy as np
from sympy import symbols, lambdify, Min, Piecewise

x = symbols("x")
expr = Min(0.1*x + 3, x + 1, 0.5*x + 1)
f = lambdify(x, expr, "numpy")
x_vals = np.linspace(0, 10, 100)
y_vals = f(x_vals)
print(y_vals)`

**Output:**
*  [1.         1.05050505 1.1010101  1.15151515 1.2020202  1.25252525
 1.3030303  1.35353535 1.4040404  1.45454545 1.50505051 1.55555556
 1.60606061 1.65656566 1.70707071 1.75757576 1.80808081 1.85858586
 1.90909091 1.95959596 2.01010101 2.06060606 2.11111111 2.16161616
 2.21212121 2.26262626 2.31313131 2.36363636 2.41414141 2.46464646
 2.51515152 2.56565657 2.61616162 2.66666667 2.71717172 2.76767677
 2.81818182 2.86868687 2.91919192 2.96969697 3.02020202 3.07070707
 3.12121212 3.17171717 3.22222222 3.27272727 3.32323232 3.37373737
 3.42424242 3.47474747 3.50505051 3.51515152 3.52525253 3.53535354
 3.54545455 3.55555556 3.56565657 3.57575758 3.58585859 3.5959596
 3.60606061 3.61616162 3.62626263 3.63636364 3.64646465 3.65656566
 3.66666667 3.67676768 3.68686869 3.6969697  3.70707071 3.71717172
 3.72727273 3.73737374 3.74747475 3.75757576 3.76767677 3.77777778
 3.78787879 3.7979798  3.80808081 3.81818182 3.82828283 3.83838384
 3.84848485 3.85858586 3.86868687 3.87878788 3.88888889 3.8989899
 3.90909091 3.91919192 3.92929293 3.93939394 3.94949495 3.95959596
 3.96969697 3.97979798 3.98989899 4. ]

**Comment by asmeurer** [comment]
As I noted on the other PR, this needs to be fixed in the printer, not lambdify.py.

**Comment by sbt4104** [comment]
I want to work on this issue if no one else is working on it.

**Comment by oscarbenjamin** [comment]
You can work on it

**Pull request closed without merging**
