### PR TITLE
fix(lambdify): don't import * from scipy

### LINKED ISSUE #23924: CI failure: lambdify: NameError: name 'polygamma' is not defined
This failure is seen in CI for the 3.11 optional dependency tests:
```
____________ sympy/utilities/tests/test_lambdify.py:test_scipy_fns _____________
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/utilities/tests/test_lambdify.py", line 1103, in test_scipy_fns
    assert abs(f(tv) - sympy_result) < 1e-13*(1 + abs(sympy_result))
               ^^^^^
  File "<lambdifygenerated-604>", line 2, in _lambdifygenerated
    return polygamma(0, x)
           ^^^^^^^^^
NameError: name 'polygamma' is not defined
```
That CI job uses latest cython, numpy and scipy from git so this is likely due to a change in scipy.

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

Extracting the key fix from #23932.

https://github.com/scipy/scipy/pull/15607#issuecomment-1215110575
Fixes https://github.com/sympy/sympy/issues/23924

#### Brief description of what is fixed or changed

Remove the unneeded `from scipy import *` in lambdify. This doesn't really do anything because not much is importable at that level in `scipy`:
```python
In [8]: ns = {}

In [9]: exec('from scipy import *', ns)

In [10]: list(ns)
Out[10]: 
['__builtins__',
 'cluster',
 'fft',
 'fftpack',
 'integrate',
 'interpolate',
 'io',
 'linalg',
 'misc',
 'ndimage',
 'odr',
 'optimize',
 'signal',
 'sparse',
 'spatial',
 'special',
 'stats',
 'LowLevelCallable',
 'test',
 'show_config',
 '__version__',
 '__numpy_version__']

In [11]: import scipy

In [12]: scipy.__all__
Out[12]: 
['cluster',
 'fft',
 'fftpack',
 'integrate',
 'interpolate',
 'io',
 'linalg',
 'misc',
 'ndimage',
 'odr',
 'optimize',
 'signal',
 'sparse',
 'spatial',
 'special',
 'stats',
 'LowLevelCallable',
 'test',
 'show_config',
 '__version__',
 '__numpy_version__']
```
It is conceivable that some code might access functions like `special.zeta` but that isn't how the lambdify printed code works:
```python
In [16]: import inspect

In [17]: print(inspect.getsource(lambdify(x, zeta(x), 'scipy')))
def _lambdifygenerated(x):
    return zeta(x)
```
The import that does the work here is `from scipy.special import *` which does import `zeta`.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
@bjodah does this look good to you?

**Comment by bjodah** [comment]
Yes, this look good to me.

**Comment by oscarbenjamin** [comment]
Great. Thanks.

**Comment by asmeurer** [comment]
Presumably this fixed https://github.com/sympy/sympy/issues/20294#issuecomment-921294268 as well.

**Pull request merged**
