### PR TITLE
ci: remove comment-on-pr workflow

### PR DESCRIPTION
**Pull request by oscarbenjamin**
The workflow is insecure and already does not work after a recent update to the actions it uses. Hopefully there can be a better way to report benchmark results on a pull request.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
I think we perhaps need to take a step back and consider how useful the benchmark comments are (or can be). I found them to be of limited use, but that's partly just because of how they were formatted. 

If we think of the benchmarks as just another CI run, then I would expect the results to just be posted in the workflow log, just like the test runs. Ideally if the code is slower, the run would fail, meaning someone would take a look at the log.

**Comment by oscarbenjamin** [comment]
If we fail checks because of the benchmarks then it would be a somewhat unreliable test but we could try it.

**Comment by asmeurer** [comment]
I think reliability of the benchmark results is really the key thing that needs to be fixed. That was also an issue with the comments as well. It doesn't matter how things are reported, if half the failures are false negatives, everyone is going to just ignore them. 

I guess there's also the issue that an "expected failure" in GitHub actions is quite annoying to deal with since they don't have a proper way to deal with them.

**Comment by oscarbenjamin** [comment]
> That was also an issue with the comments as well. It doesn't matter how things are reported, if half the failures are false negatives,

There were not many false positives/negatives. Many people were confused about the "master vs release" differences but the differences reported were usually accurate. We would get a clearer idea of how reliable these are though if it was actually failing CI checks.

**Comment by asmeurer** [comment]
By the way, there is maybe a third option. GitHub supports "checks", which let CI jobs post comment-like things on pull requests. I'm not completely sure how it works or if you can actually access it from a GitHub Actions PR workflow. Here's an example of how it looks like from codecov https://github.com/matplotlib/matplotlib/pull/28187/files/a22fcc304e251b28b46f9f69884fe053a7790e81#diff-1565d78306cf72de5a28f4e2b196ee2cb09026d1f8aa2dc26178c3a47f3347b8R646. I also don't know if they have to only be inline comments or if you can do something else. 

Really it would be nice if there were a codecov like service for doing benchmarks on CI that could handle these sorts of things for us, but I don't know of any.

**Comment by oscarbenjamin** [comment]
In the meantime it would be good to reenable codecov.

**Comment by asmeurer** [comment]
I remember codecov did have a lot of annoying false positives that didn't seem to have any logical reason behind them. But maybe it's better now.

**Pull request merged**
