### PR TITLE
4596

### PR DESCRIPTION
**Pull request by smichr**
#### References to other Issues or PRs

#4596

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I'm not sure if I'm interpreting this correctly but it looks like because you've added a branch to the main sympy repo the tests will run twice on travis: once for continuous-integration/travis-ci/pr and once for continuous-integration/travis-ci/push

**Comment by smichr** [comment]
> interpreting this correctly

probably. Thanks for the heads up. I'll just cancel the push build when I make changes. 

This is just an experiment. I hope not to burn out my monitor when reviewing the failures.

**Comment by oscarbenjamin** [comment]
I'm running the tests locally. It looks to me like there are a lot of tests that are failing because the precise form of the output has changed:
```
>       assert dsolve(eq2) == sol2
E       assert Eq(f(x), (C1 + 5*x)/3) == Eq(f(x), C1 + 5*x/3)
```
Others are failing because the form of the input has changed and no longer matches:
```
>           raise ValueError(string + str(eq) + " does not match hint " + hint)
E           ValueError: ODE -x**2 + x*f(x) + Derivative(f(x), x) does not match hint 1st_linear
```
(that's just a bug somehow in the matching code)

A lot of bugs are being exposed that should be fixed:
```
>           return _remove_gcd(x_0, y_0, z_0)
E           UnboundLocalError: local variable 'x_0' referenced before assignment
```

There are a few things in simplify etc that would need updating like collect/expand:
```
>       assert collect((1 + (x + y) + (x + y)**2).expand(),
                       [x, y]) == 1 + y + x*(1 + 2*y) + x**2 + y**2
E       assert x**2 + x + y**2 + y + 3 == ((((1 + y) + (x * (1 + (2 * y)))) + (x ** 2)) + (y ** 2))
```

The main substantive problem seems to be the lack of additive cancellation though:
```
>       assert reduce_inequalities(x + y < 1, symbols=[x]) == (x < 1 - y)
E       assert x + y - (y - 1) - 1 < -(y - 1) == (x < (1 - y))
```

I got to 70% complete with 549 failures out of 6000 before it hung in solvers somewhere. Rerunning only the failed tests a few pass on the second run which suggests some non-deterministic fails in there.

**Comment by smichr** [comment]
> lack of additive cancellation

thanks for the feedback. I fixed an error and made greater cancellation possible in Add.flatten. Let's see how it goes this time.

**Comment by oscarbenjamin** [comment]
This doesn't look like an easy thing to fix but I really think it needs fixing. We need multiplication to be associative so `(a*b)*c = a*(b*c)`

**Pull request closed without merging**
