### PR TITLE
fixed issue and add Warning if invalid match input

### PR DESCRIPTION
**Pull request by mvnnn**
fixed for #8694

### CODE REVIEW

**Comment by mvnnn** [comment]
Can anyone review this PR?

**Comment by asmeurer** [comment]
This is not a correct fix. The problem is that the match expression in the issue doesn't work but it should. The matching algorithm needs to be improved. There is no need for a warning when a match doesn't work. The return type of None already indicates this. Furthermore, deprecation warnings are for things that are going to be removed. Nothing here needs to be deprecated, as far as I can tell.

**Comment by mvnnn** [comment]
@asmeurer thanks..i will fix that.

**Comment by mvnnn** [comment]
sympy/core/symbol.py 
```
def matches(self, expr, repl_dict={}, old=False):
        if any(expr.has(x) for x in self.exclude):
            repl_dict={}
            return None
        if any(not f(expr) for f in self.properties):
            repl_dict={}
            return None
        aa = repl_dict
        aa[self] = expr
        return aa
```
i can't update ```repl_dict``` but it's update automatically. @asmeurer can you explain why this happen.

**Comment by mvnnn** [comment]
if i remove```repl_dict=repl_dict.copy``` then i need to remove cache value of ```repl_dict``` because it's cache value make problem in next ```match``` call.

**Comment by asmeurer** [comment]
The `repl_dict = repl_dict.copy()` line is important. Mutable keyword arguments don't "reset" every time a function is called. See https://stackoverflow.com/questions/1132941/least-astonishment-in-python-the-mutable-default-argument (that applies to lists but dictionaries are the same, since they are also mutable).

**Comment by mvnnn** [comment]
:+1:

**Pull request closed without merging**
