### PR TITLE
[WIP] Added Rationals class to fancysets

### PR DESCRIPTION
**Pull request by kshitij10496**
- [x] Added `Rationals` class 
- [x] Added tests
- [ ] Updated docs

Refer: #10757 , #10645

### CODE REVIEW

**Comment by kshitij10496** [comment]
Ping @smichr 

Do have a look and let me know what you think of this.
I will make the necessary changes and add the tests after your go.

Without the `_contains` method, I was having this issue :
```python
In [ ]: x,  y = symbols('x, y', cls=Dummy)
In [ ]: lamda = Lambda((x, y), x/y)
In [ ]: base_set = S.Integers*S.Naturals
In [ ]: bar = ImageSet(lamda, base_set)
In [ ]: foo = S.Rationals

In [ ]: S.Half in foo
Out[ ]: False

In [ ]: S.Half in bar
Out[ ]: True

In [ ]: foo == bar
Out[ ]: True

In [ ]: foo is bar
Out[ ]: False

In [ ]: type(foo)
Out[ ]: sympy.sets.fancysets.Rationals

In [ ]: type(bar)
Out[ ]: sympy.sets.fancysets.ImageSet
``` 

After I added the `_contains` method to the `Rationals` class, the issue was resolved.
I find it a bit odd to add `_contains` method to this class, given how `Reals` work.
Shouldn't the `_contains` method of the super class (`ImageSet`) get called upon in the first place ?

**Comment by smichr** [comment]
> get called upon in the first place

I am really not up to speed on the inheritance behavior, especially when you start subclassing with the wrapper. Sorry. Someone else will have to field questions on this.

I don't know why, but I just think this set is cool. I wonder if __new__ could take an optional keyword `limit_denom` which would limit the denominator to `Interval(1, as_int(limit_denom))`. Is that a good idea? Of course the `S` version would be as you have done with no limit to denom.

**Comment by kshitij10496** [comment]
> Someone else will have to field questions on this.  

Ping @aktech @asmeurer @hargup
I would appreciate if you can clarify my doubt.  

> I wonder if new could take an optional keyword limit_denom which would limit the denominator to Interval(1, as_int(limit_denom))  

For example:
```python
In[] : foo = Rationals() # default limit_denom=S.Infinity 
In[] : bar = Rationals(5)
In[] : S(1)/6 in foo
Out[] : True
In[] : S(1)/6 in bar
Out[] : False
```
The only concern I have is that returning a `False` result wouldn't ascertain that the number is irrational.
From what I think, a Rationals class should be a representative of all the rational numbers.
And returning a `False` result should imply that the input value is an irrational.
What are your thoughts on this ? @smichr

**Comment by smichr** [comment]
> Rationals class should be a representative of all the rational numbers.
> And returning a False result should imply that the input value is an irrational.

The default class represents all rational numbers. Anyone who doesn't want the default would have to understand that it is a Rationals subset and a number will not be in the subset if it is irrational or if it is not a small fraction. I don't think it's confusing. We already answer False for queries when one ore more conditions are met, e.g. a number is not odd if a) it is even or b) if it is not an integer.

**Comment by kshitij10496** [comment]
@smichr I have made the changes.
Would it be a good idea to add a lower limit to the denominator values (just like we did for the upper limit) ?

**Comment by smichr** [comment]
> Do we need to define the set as Interval(1, limit_denom) or would it be better to define it as a FiniteSet(limit_denom)

It could be like this: `__new__(cls, numer=S.Integers, denom=S.Naturals):` and then the user can decide how to define the fraction, e.g. `denom = Range(1, 11)`, `denom = FiniteSet(10)`. The 2nd case will return fractions whose numerator is relatively prime to 10 while the former will include those that have factors or 2 and 5, too.

**Comment by kshitij10496** [comment]
This sounds even better.

**Comment by smichr** [comment]
Here's a possibility for the `__iter__` method, though there is room for improvement.

```python
def __iter__(self):
    """Return fractions in increasing order that are in self

    Examples
    ========

    >>> from sympy.abc import n, d
    >>> from sympy import imageset, Range
    >>> [i for i in iter(imageset((n, d), n/d, Range(3, 6)*Range(4, 8)))]
    [3/7, 4/7, 3/5, 5/7, 3/4, 4/5, 5/6, 5/4]

    http://www.mathblog.dk/project-euler-73-sorted-reduced-proper-fractions/
    """
    num, den = self.base_set.args
    assert num.inf >= 0
    assert den.inf > 0
    if len(num) == 0 or len(den) == 0:
        return
    if len(num) == 1:
        n = num[0]
        for d in den:
            r = Rational(n, d)
            if r.p in num and r.q in den:
                yield r
    elif len(den) == 1:
        d = den[0]
        for n in num:
            r = Rational(n, d)
            if r.p in num and r.q in den:
                yield r
    elif not num[0]:
        yield S.Zero
        for r in iter(num[1:], den):
            if r.p in num and r.q in den:
                yield r
    else:
        A, B = num[0]/den[-1], min(num[0]/den[-2], num[1]/den[-1])
        r = A
        if r.p in num and r.q in den:
            yield r
        r = B
        if r.p in num and r.q in den:
            yield r
        a, b = A.p, A.q
        c, d = B.p, B.q
        N = den.sup
        last = num[-1]/den[0]
        while 1:
            i = (N + b)//d
            e, f = i*c - a, i*d - b
            r = Rational(e, f)
            if e in num and f in den:
                yield r
            a, b, c, d = c, d, e, f
            if r >= last:
                break
```

**Comment by kshitij10496** [comment]
This looks really nice!
I will try to improvise this logic for negative fractions as well.

I have got a concern, though:

For making the `Ratinals` object iterable, don't we need to make sure that the input is terms of finite integer values i.e. it either is a `Range`, `FiniteSet` (with only integer values) ?
Also, we need to handle cases for a universal(defautl) Rationals object separately.

**Comment by smichr** [comment]
> don't we need to make sure that the input is terms of finite

I think we should disallow 0 in the denominators. What is the concern that you have about infinitities? Because we should allow `Range(100, oo)` as an option for numerator or denominator.

**Comment by smichr** [comment]
> negative fractions as well

I was thinking that solving the problem in the range [0, 1] should be sufficient because in (1, oo) we can simply invert values to remap to [0, 1] (and then output inverted results ordered from largest to smallest) and we can remap negatives to positives. If the set contains both pos and negative I thought we might take the same approach as Integers and spiral out from 0, emitting pos and neg with increasing magnitude.

**Comment by kshitij10496** [comment]
> I think we should disallow 0 in the denominators.


I have added checks for disallowing 0 in the denominator.

>  What is the concern that you have about infinitities? 


While creating an iterator for a `Rationals` object, we need to ensure that both the numerator and denominator are integer values. So, I was concerned about not being able to use `Interval` object as my inputs.
Also, how do we approach iterating the default `Rationals` object (with `numer=S.Integers` and `denom=S.Naturals`) ? 

I should have been more specific. Sorry about that !

**Comment by smichr** [comment]
Is there interest in finishing this up?

**Comment by asmeurer** [comment]
What's the point of the limit denominator flag? It seems like a very specific thing which could be achieved with a ConditionSet

**Comment by smichr** [comment]
> point of the limit denominator flag

The point is to limit the rationals that are considered. You hint that this could be handled with ConditionSet...I'm not too adept at this yet, but my first (failing) intuition would be to write `ConditionSet(x, x.q < limit, Rationals())` but that is going to fail because `x` is not a Rational. How would you write the condition?

**Comment by asmeurer** [comment]
I guess ConditionSet is harder because you don't have a symbolic way to access the denominator. But you can use ImageSet, like is done in the constructor of the code here. 

I don't follow where limit denominator would actually be used.

**Comment by smichr** [comment]
> I don't follow where limit denominator would actually be used.

Maybe you would want to have a set of small rationals from which to test something. What about just letting the numerator and denominator sets be optional arguments: `Rational(FiniteSet(1), S.Naturals)` would give any unit fraction. It would also be possible to iterate the Rationals from smallest to largest if the denominator was not infinite as [shown here](https://github.com/sympy/sympy/pull/10777#issuecomment-195604469).

**Comment by sylee957** [comment]
Rationals was already added added in #16896. Should this be closed?

**Comment by oscarbenjamin** [comment]
Yes, this should be closed. Thanks @kshitij10496

**Pull request closed without merging**
