### PR TITLE
Special case Rational +,-,*,/ Integer

### PR DESCRIPTION
**Pull request by isuruf**
`Rational` constructor now takes in a `gcd` parameter for the two inputs. If it's `None`, `gcd` is calculated.

Part of #10928

### CODE REVIEW

**Comment by isuruf** [comment]
Updated notebook here, https://gist.github.com/isuruf/260739f0570e0bc9610749deb30b84bc

**Comment by smichr** [comment]
Seems reasonable to me.

**Comment by isuruf** [comment]
@smichr, can you restart the 2 failed jobs on travis? I think they are unrelated failures.

**Comment by smichr** [comment]
returning zoo seems reasonable, too as that is consistent with `(1/x).subs(x,0)`. If nobody else has objections I will commit in 24 h.

**Comment by smichr** [comment]
Thanks, it's in.

**Pull request merged**
