### PR TITLE
matrix dotprodsimp context manager

### PR DESCRIPTION
**Pull request by tom-pytel**
#### References to other Issues or PRs
Implements #19532

#### Brief description of what is fixed or changed
Matrix operations no longer default to intermediate product simplification but rather have that switched on via context manager.

#### Release Notes

* matrices
  * Disabled default matrix intermediate product simplification and changed it to enable via context manager.

### CODE REVIEW

**Comment by Pristine-Cat** [comment]
Usage:
```julia
>>> Matrix([[1+x, 1-x], [1-x, 1+x]])**4
⎡                                           2                                              ⎤
⎢         2        2   ⎛       2          2⎞                       ⎛       2          2⎞   ⎥
⎢4⋅(1 - x) ⋅(x + 1)  + ⎝(1 - x)  + (x + 1) ⎠     4⋅(1 - x)⋅(x + 1)⋅⎝(1 - x)  + (x + 1) ⎠   ⎥
⎢                                                                                          ⎥
⎢                                                                                         2⎥
⎢                    ⎛       2          2⎞              2        2   ⎛       2          2⎞ ⎥
⎣  4⋅(1 - x)⋅(x + 1)⋅⎝(1 - x)  + (x + 1) ⎠     4⋅(1 - x) ⋅(x + 1)  + ⎝(1 - x)  + (x + 1) ⎠ ⎦

>>> from sympy.matrices import dotprodsimp
>>> with dotprodsimp(True):
...     Matrix([[1+x, 1-x], [1-x, 1+x]])**4
...
⎡   4             4⎤
⎢8⋅x  + 8  8 - 8⋅x ⎥
⎢                  ⎥
⎢       4     4    ⎥
⎣8 - 8⋅x   8⋅x  + 8⎦
```
And so on for all functions which implemented the intermediate simplification. It can also be turned off nested within an on block via `with dotprodsimp(False):` obviously.

**Comment by oscarbenjamin** [comment]
Thanks @Pristine-Cat!

Looks like I just messed up the merge.

Are you still working on this? I could fix it with a force-push but I don't want to do that if you're about to push yourself...

**Comment by Pristine-Cat** [comment]
Actually I think its my fault, didn't start with the latest, give me a bit.

**Comment by Pristine-Cat** [comment]
Ok well it looks like these tests need to be reverted back to what they were before dotprodsimp and the ones that are timing out should either be wrapped in a `with dotprodsimp(True):` or commented out. Don't have time at the moment to chase all of this down but the main thing here is done which is that default matrix behavior is reverted to before dotprodsimp and the option to use it is present via the context manager.

**Comment by oscarbenjamin** [comment]
Thanks. I think I can finish this off

**Comment by oscarbenjamin** [comment]
@sylee957 @Pristine-Cat I think that the tests will pass now.

Does either of you want to review this?

I'll merge tomorrow if I don't hear back and then cherry-pick the relevant commits for 1.6 ready for a 1.6.1 release.

**Comment by oscarbenjamin** [comment]
I've opened #19612 cherry picking the changes here for the 1.6 branch

**Comment by oscarbenjamin** [comment]
If we're all agreed that disabling dotprodsimp by default is what we want then I'll merge this into master and #19612 into 1.6 and then go ahead and release 1.6.1.

**Pull request merged**
