### PR TITLE
maint(ci): add nightly wheel uploads per SPEC 4

### PR DESCRIPTION
**Pull request by oscarbenjamin**
https://scientific-python.org/specs/spec-0004/
https://github.com/scientific-python/upload-nightly-action/issues/111

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
There's no way to test this without merging so I'm just going to merge it.

**Comment by asmeurer** [comment]
Don't we need git versions first? https://github.com/sympy/sympy/issues/27116 Otherwise all the nightly versions are going to just be "1.14.dev".

**Comment by oscarbenjamin** [comment]
You don't need multiple nightly versions. It is just supposed to be "today's version". You can see the wheels uploaded for numpy here:
https://anaconda.org/scientific-python-nightly-wheels/numpy/files?page=1

It would be useful to be able to distinguish which commit someone use retrospectively but that is mostly not needed because they will mainly be used in CI and the point is just that it always gets the most recent upload anyway.

**Comment by asmeurer** [comment]
I didn't realize NumPy would have the same problem. I agree it won't matter for ephemeral things like CI builds, but it would make it harder to use this for something more persistent, because pip would not know that the package should be updated, or even that it's a different file. 

At any rate, the commit hash thing is definitely useful for nightly builds because you can see right from the pip install log exactly what commit of SymPy is being installed. Without that, you just have to guess from the timestamps or other things.

**Comment by oscarbenjamin** [comment]
To be clear I agree that it would be good to have the commit hash in the version and in the filename. I just don't think it is a necessary precondition for having nightly wheels.

**Pull request merged**
