### PR TITLE
Dsolve system

### PR DESCRIPTION
**Pull request by vishalg2235**
dsolve uses same logic for all number of equations except when n=2. As for n=2 the solver is correctly optimised.
So all the test cases where number of equations was 2 were reversed.
Thanks @normalhuman for help!

### CODE REVIEW

**Comment by vishalg2235** [comment]
Ping @jksuom , @normalhuman please review!

**Comment by normalhuman** [comment]
There is a merge conflict

**Comment by normalhuman** [comment]
It's the other way around; the tests won't run until the conflicts are resolved. It wouldn't make sense for them to run because after the conflict resolutions they will have to run again,

**Comment by vishalg2235** [comment]
How will I get to know where conflict is coming because "Resolve conflict" button is not shown?

**Comment by vishalg2235** [comment]
Are conflicts same as in [here](https://github.com/sympy/sympy/pull/14445/conflicts)

**Comment by normalhuman** [comment]
The reason for conflicts is the same: the master branch now has those type corrections, and this branch does not.

**Comment by czgdp1807** [comment]
@oscarbenjamin @mijo2 Can this be closed?

**Comment by mijo2** [comment]
@czgdp1807 This PR can be closed IMO since its implementing the same method which has already been merged and doesn't add any new test case.

**Comment by oscarbenjamin** [comment]
Thanks @vishalg2235 and @normalhuman for the contributions. This is now already implemented on master from https://github.com/sympy/sympy/issues/15946 so I'll close this.

**Pull request closed without merging**
