### PR TITLE
[WIP] Improve simplify()

### LINKED ISSUE #10347: simplify doesn't do the last simplification step
Note: I'm using Python 3.5.1 and sympy 0.7.6.1. Full script is attached in the .zip file: 
[simplify_last_step.zip](https://github.com/sympy/sympy/files/76131/simplify_last_step.zip)

---

I've been using Sympy to compute Laplacian in different geometrical coordinates system. This usually creates extremelly long expressions and simplify usually does a great job. However, I've come against one particular case where simplify does most of the job but doesn't perform the ultimate simplification step. 

I've reduced the problem set getting rid of all of the Derivative terms. The initial 

expression is still huge (675 ops!):

initial_expression

A first call to `simplify` sucessfully reduces it to : 

simplify

Which is great (23 ops), but somehow frustrating as we can factorize it a little more. If I apply `simplify` again, then I get the expression I wanted (7 ops):

simplify_bis

---

If simplify worked perfectly, `simplify(simplify(expr))` shouldn't yield a different result from `simplify(expr)`  

From my understanding of how simplify works, it successively tries different simplification strategies  and compares them. In that case, the order of the different strategies matters. In my particular case, the strategy than eventually did the final factorisation step may have been called to early. 

I fixed that calling simplify again. We could fix it applying an optional recursive mode at the end of the simplify function:

``` python
def simplify(expr, ratio=1.7, measure=count_ops, fu=False, max_rec_steps=0):
    """
    Simplifies the given expression.

    Input
    ========
    max_rec_steps: int
        if >0, simplified is applied recursively with a maximum of 'max_rec_steps'
        times.

    (...)

    """

    (...)

    if measure(expr) > ratio*measure(original_expr):
        expr = original_expr

    if max_rec_steps>0 and measure(expr)<measure(original_expr):
        sexpr = simplify(expr, ratio, measure, fu, max_rec_steps=max_rec_steps-1)
        expr = shorter(expr,sexpr)        

    return expr

```

I can make the pull request if that helps.

### PR DESCRIPTION
**Pull request by ylemkimon**
- Added rational(ize) flag. Like(and adapted from) rational flag in solve(), it rationalizes floats before simplifying if True or None and restores them after if None.
May lead to better simplification where simplifications of float is incorrect, erroneous or not implemented(#10127, #13149) and by combining Float and Rational/Integer with same value.
- Added recursive flag. If recursive > 1, simplify will be called recursively until no further simplification is possible or recursion depth reaches the value of the flag. Fixes #10347. (Related to #4500)

### CODE REVIEW

**Comment by smichr** [comment]
+1

**Comment by asmeurer** [comment]
Not sure about the recursive flag. simplify should be able to simplify that in one pass.

**Comment by asmeurer** [comment]
But also not opposed to it if others think it's a good idea.

**Comment by smichr** [comment]
> simplify that in one pass.

I think that means that internally it will have to do something to see if changes should be made again. Can you determine why it is not detecting the need to do so, @ylemkimon? Alternatively, I would suggest that we make the recursive flag private, `_recursive` so we can remove it when the problem is fixed.

**Comment by ylemkimon** [comment]
@smichr @asmeurer The problem causing #10347 is that `cancel` is not called after function-specific simplification steps like `trigsimp`. Calling `cancel` after them seems to solve the issue and probably solve most of similar problems. I'll make new PR.

**Comment by ylemkimon** [comment]
Opened new PR #13264.

**Pull request closed without merging**
