### PR TITLE
Fix gh-12939, (allow autowrap's tempdir be a relative path)

### PR DESCRIPTION
**Pull request by bjodah**
This works locally for me, let's see what Travis CI says.

cc @moorepants @uweschmitt

### CODE REVIEW

**Comment by asmeurer** [comment]
Why does it need to chdir at all? 

At any rate, this looks good, +1.

**Comment by bjodah** [comment]
I don't think the `chdir` call is needed. I'll add a commit removing it once CI passes.

**Comment by asmeurer** [comment]
I guess it would need to `os.path.join(self.workdir, ...)` everywhere without it.

**Comment by bjodah** [comment]
True, let's leave it there then.

**Pull request merged**
