### PR TITLE
Revert "Merge pull request #9765 from debugger22/rm-autosimp-abs"

### PR DESCRIPTION
**Pull request by asmeurer**
This reverts commit af069afd35905b35c269350249a6230f96fc16b1, reversing
changes made to 863d13c12365e7fb5fba4e4512987d578a81f821.

See #10082 for more information. This fixes the regression refine(sqrt(x**2),
Q.positive(x)) == x (previously it was giving Abs(x)). That pull request
removed the test for this, and this revert adds it back in.

### CODE REVIEW

**Comment by asmeurer** [comment]
@debugger22

**Comment by certik** [comment]
+1 if tests pass. There might have been some good changes, but it was a mistake to remove the test, so we should revert this, as you did, and then later try to do the original PR in a proper way without breaking things.

**Comment by asmeurer** [comment]
I checked and none of the other autosimp removal PRs (https://github.com/sympy/sympy/pulls?q=is%3Apr+author%3Adebugger22+is%3Aclosed) seem to modify tests like this.

**Comment by debugger22** [comment]
+1

**Pull request merged**
