### PR TITLE
maint: make standard packages available as e.g sympy.matrices

### PR DESCRIPTION
**Pull request by oscarbenjamin**
Previously sympy.matrices and sympy.logic etc resolved to submodules
like sympy.matrices.matrices. This was unintentional so it was changed
so that accessing these modules would give a warning. This commit
disables those accidentally imported submodules that conflict with a
possible genuine import e.g. sympy.matrices which should mean the
sympy.matrices package rather than the sympy.matrices.matrices
submodule.

#### Release Notes

* other
  * some subpackages of sympy used to refer to submodules unintentionally. These are made to refer to the top-level sympy packages now. This applies to `sympy.matrices`, `sympy.integrals`, `sympy.logic`, `sympy.sets`, and `sympy.solvers`. It is possible that some import statements will not succeed as a result of this change.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
See also #19554

**Comment by oscarbenjamin** [comment]
See also https://github.com/sympy/sympy/pull/18245#issuecomment-658278822

**Comment by czgdp1807** [comment]
@oscarbenjamin Is it good to go?

**Comment by oscarbenjamin** [comment]
This is related to #19554 which removes all of the deprecated import wrappers. This PR only removes a few of them where they shadow what should be a correct import.

This does not need to be merged if #19554 is merged. However if #19554 is not merged by the next release then this should be merged at least because the shadowing bug remains unfixed for the particular modules addressed here.

**Pull request closed without merging**
