### PR TITLE
Removing Sergey from contributors (on his request)

### PR DESCRIPTION
**Pull request by certik**
Sergey asked me in private email to be removed from contributors, so this PR
does it.

### CODE REVIEW

**Comment by asmeurer** [comment]
Also update https://github.com/sympy/sympy/blob/ca36d47adbdd457cb64a04faba6fa6c132a563a5/bin/mailmap_update.py#L55.

**Comment by certik** [comment]
I updated `mailmap_update.py` and squashed the commits.

**Comment by asmeurer** [comment]
Thanks. Let's merge. I don't think we really need to wait for Travis, but you can if you want.

**Comment by cbm755** [comment]
I have tried to stay out of this unfortunate situation but @skirpichev has written to me privately about this.  Can you delay merging this, in hope of a more amicable split?

**Comment by certik** [comment]
Of course. In fact I was hoping not to merge this at all, but Sergey asked
me to immediately remove him from contributors list, so I am just
fulfilling his wish. I will only merge if I get a final approval from
Sergey.

**Comment by certik** [comment]
Sergey gave the commit a77b86e07d471420df8f8ec57da3aadeee2212bf +1 to merge in an email to me.

@cbm755 let me know if you have any further objections against merging this.

**Comment by cbm755** [comment]
I have no objections.  Only sadness, same as you and others I'm sure.

**Comment by certik** [comment]
Yes, I am sad. But the door is always open if Sergey changes his mind. We can always revert this patch. Merging.

**Pull request merged**
