### PR TITLE
physics.hydrogen: Added normalized hydrogen wave functions psi_{nlm}

### PR DESCRIPTION
**Pull request by der-blaue-elefant**
New feature:
In addition to the already existing radial wave functions of the
hydrogen atom, now there's also the possibility to get the full
wavefunction psi_nlm, depending on the quantum numbers n, l and m
and the spherical coordinates r, phi and theta. Check Wikipedia
"Hydrogen atom" or any quantum text book for validation of the
formula.

See docstring for examples.

<!-- If this pull request fixes an issue please indicate which issue by typing "Fixes #NNNN" below.>

### CODE REVIEW

**Comment by moorepants** [comment]
You'll need to add a unit test for this. Thanks for the contribution.

**Comment by der-blaue-elefant** [comment]
I commited a new version of the file. It now passes both 
`./bin/doctest hydrogen`
and
`./bin/test hydrogen`

**Comment by gxyd** [comment]
@der-blaue-elefant you will need to add test cases for this. For guidelines please read this https://github.com/sympy/sympy/wiki/Writing-test-cases-in-SymPy .

**Comment by gxyd** [comment]
This PR has been inactive for quite sometime, so we are going to close it and open an issue to reference it. We try to keep our pull request queue small and focused on active work.  We encourage you to reopen the pull request if and when you continue to work on this. Please contact us if you have any questions.

Thanks for contributing.

see https://github.com/sympy/sympy/wiki/Closing-pull-requests for our policies on closing pull request.

I've opened #13481 for this pull request so that we don't forget about it.

**Pull request closed without merging**
