### PR TITLE
possible fix for Issue#12300

### PR DESCRIPTION
**Pull request by bhavishyagopesh**
Changed if-else to Kronecker Delta.

### CODE REVIEW

**Comment by bhavishyagopesh** [comment]
@smichr  Please if you could whether the PR is ready to be merged, and if not please tell me what else is required?

**Comment by smichr** [comment]
If you create a test that creates a DiagonalMatrix that is not a Identity matrix and show that this passes with your modification but doesn't pass in master, this will be ready for committing. Please see, for example, #12419 .

**Comment by bhavishyagopesh** [comment]
@smichr But the problem is with identity matrices,so and master says 0 still....

**Comment by smichr** [comment]
> But the problem is with identity matrices,so and master says 0 still

If you update your master you should see that it's fixed. But the same problem exists for DiagonalMatrix.

**Comment by bhavishyagopesh** [comment]
@smichr  I'm so sorry,I somehow missed, Just give me a moment, I need to think a bit...may be of some way of simplifying that piecewise expression.

**Comment by smichr** [comment]
> way of simplifying that piecewise expression

I think this is a red herring -- I would simply use the KroneckerDelta solution that you already have. Just Add a test from the issue that I just added regarding DiagonalMatrix.

**Comment by bhavishyagopesh** [comment]
@smichr  I now added one test, tell me if that's fine.

**Comment by smichr** [comment]
> tell me if that's fine.

#12428 is making progress on this and is almost done, so let's just close this. It would be better, next time you do a PR, to put a more descriptive title. That helps reviewers keep track of what they are looking at.

**Pull request closed without merging**
