### PR TITLE
Merge some matrix tests

### PR DESCRIPTION
**Pull request by sylee957**
#### Brief description of what is fixed or changed

Those two tests are doing exactly the same thing, with different methods, but were  inconveniently  inside different sections
I had also found that this section is missing in LU determinant test, so I have added one.
https://github.com/sympy/sympy/blob/678217d5cc4973e2471c20e4396bf39e52d93eb1/sympy/matrices/tests/test_matrices.py#L353-L359

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by smichr** [comment]
+1

**Comment by jksuom** [comment]
Looks good to me too. But cannot be merged before the Sage issue is solved.

**Comment by jksuom** [comment]
This should probably be merged with current master having new .travis.yml. Restarting the failing job does not help.

**Comment by jksuom** [comment]
There are many new commits. Are those included on purpose?

**Comment by sylee957** [comment]
@jksuom 
I had reverted those commits.
Should there be a selective merge of changes of travis.yml into this branch?

**Comment by jksuom** [comment]
I assume that the [usual method](https://github.com/sympy/sympy/wiki/Development-workflow#id54) would suffice: git checkout master, git pull, git checkout branch, git merge master. If that is what you did, then I think that it should be OK. I only wonder why github would show all those  merged commits. Usually only new commits appear.

**Pull request merged**
