### PR TITLE
Reduced repeated code in sympy.stats.symbolic_probability

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References to other Issues or PRs

Continued https://github.com/sympy/sympy/pull/15610

#### Brief description of what is fixed or changed
Earlier in `sympy.stats.symbolic_probability` the code was duplicate for `_eval_rewrite_as_Integral` and `_eval_rewrite_as_Sum`. However, now that is removed by using alias for the method names.
Thanks to @oscargus and @Upabjojr for the suggestions for the related work.

#### Other comments
N/A

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by czgdp1807** [comment]
@jksuom Please provide your reviews for more changes.

**Comment by Sc0rpi0n101** [comment]
Should I wait for this to be merged before updating the documentation for the file?
Reference: #16557

**Comment by czgdp1807** [comment]
@Sc0rpi0n101 I think the documentation you have done isn't needed, since the interface for those methods is already having the required documentation. 
Valuable views from @jksuom @Upabjojr are also necessary.

**Comment by Upabjojr** [comment]
OK, it looks good.

**Comment by Upabjojr** [comment]
I'm actually not 100% convinced that rewrite as Integral and Sum should behave the same way. Anyway, that's for another discussion.

**Comment by czgdp1807** [comment]
Yeah, sure. I am open for discussion on this, anytime. 
We can keep discussing on this PR, if possible.

**Comment by Sc0rpi0n101** [comment]
Not sure if discussion in a closed PR is a good idea.
 
I would suggest opening a new Issue for an organized discussion and other people can give their insights too.

**Pull request merged**
