### PR TITLE
Transpose String changed #11044 

### LINKED ISSUE #11044: lambdify of Transpose is wrong
Reported from https://stackoverflow.com/questions/36730931/converting-expression-involving-tranpose-of-vector-to-numerical-function-with-la

```
In [19]: x = sympy.MatrixSymbol('x',3,1)

In [20]: f = sympy.lambdify(x, x.T*x)
  File "<string>", line 1
    lambda x: ((x').dot(x))
                          ^
SyntaxError: EOL while scanning string literal
```

On a related note, the `str` printer for Transpose should print valid Python.

### PR DESCRIPTION
**Pull request by nc1337**
Now the output is:

``` python
>>> from sympy import *
>>> from sympy.abc import *
>>> x = MatrixSymbol('x',3,1)
>>> x.T
x.T
>>> f = lambdify(x,x.T*x)
>>> f
<function <lambda> at 0x000000000511CD68>
```

Now, it does not give syntax error but lambdify is still not working.

### CODE REVIEW

**Comment by Nitin216** [comment]
should i add a test case too.

**Comment by Nitin216** [comment]
This is failing due to no ouput on ```test_finite_rv.py```. But on my local machine, it is working.

**Comment by Nitin216** [comment]
ping @asmeurer

**Comment by asmeurer** [comment]
Can you add a test for the lambdify fix?

**Comment by gxyd** [comment]
Duplicate of https://github.com/sympy/sympy/pull/11566 . Closing this.

**Pull request closed without merging**
