### PR TITLE
Fixed a bug in doc string 

### LINKED ISSUE #20918: Garbage output in Diagram.conclusions : fix it
doctest error

>>> from sympy.categories import Object, NamedMorphism, Diagram
 >>> from sympy import pprint, default_sort_key
 >>> A = Object("A")
>>> B = Object("B")
>>> C = Object("C")
>>> f = NamedMorphism(A, B, "f")
>>> g = NamedMorphism(B, C, "g")
>>> d = Diagram([f, g])
>>> premises_keys = sorted(d.premises.keys(), key=default_sort_key)
>>> pprint(premises_keys, use_unicode=False)
     [g*f:A-->C, id:A-->A, id:B-->B, id:C-->C, f:A-->B, g:B-->C]
>>> pprint(d.premises, use_unicode=False)
    {g*f:A-->C: EmptySet, id:A-->A: EmptySet, id:B-->B: EmptySet, id:C-->C: EmptyS
    et, f:A-->B: EmptySet, g:B-->C: EmptySet}
>>> d = Diagram([f, g], {g * f: "unique"})
>>> pprint(d.conclusions)
Expected :
    {g*f:A-->C: {unique}}
get : 
{g∘f:A——▶C: {unique}}

I tried to resolve this error, but I was unable to understand why is it giving such result. If you get this, then please fix it.

### PR DESCRIPTION
**Pull request by ayushbisht2001**
#### References to other Issues or PRs

Fixes #20918 

#### Brief description of what is fixed or changed
Incorrect : 
>> pprint(d.conclusions)
{g∘f:A——▶C: {unique}}

Correct:
>> pprint(d.conclusions,use_unicode = False)
{g*f:A-->C: {unique}}

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by ayushbisht2001** [comment]
@sylee957 , Please review my PR , I don't know why some of the tests are failing. 

> from sympy.categories import Object, NamedMorphism
> from sympy.categories import Diagram, DiagramGrid
> A = Object("A")
> B = Object("B")
> C = Object("C")
> f = NamedMorphism(A, B, "f")
> g = NamedMorphism(B, C, "g")
> diagram = Diagram([f, g])
> grid = DiagramGrid(diagram)
> grid.morphisms

Expected : 
 > {NamedMorphism(Object("A"), Object("B"), "f"): EmptySet(),
 > NamedMorphism(Object("B"), Object("C"), "g"): EmptySet()}

Get : 
> {NamedMorphism(Object("A"), Object("B"), "f"): EmptySet,
 NamedMorphism(Object("B"), Object("C"), "g"): EmptySet}

**Comment by ayushbisht2001** [comment]
@asmeurer ,  please review my PR.

**Comment by oscarbenjamin** [comment]
Can you explain why this change is needed? It seems to change a doctest but I presume the doctest already passed the tests...

**Comment by ayushbisht2001** [comment]
> Can you explain why this change is needed? It seems to change a doctest but I presume the doctest already passed the tests...

@oscarbenjamin , when I was learning category theory using sympy ,  I get some unwanted result  ``g°f:A--?C: {unique}}`` with Diagram( ) , I thought It was because my console doesn't support unicode .  That '?' sign is quite confusing relative to the given result . So I think the documentation need to be correct so that learner might not get confused.

**Comment by sylee957** [comment]
It could be confusing for users who don't know the technical details that init_printing automatically detects the environment
My opinion is that we don't have enough guideline of whether or not to use unicode pprint for docstrings, besides the dejavu font issue, but I'd expect that this should be symmetric across every sympy docstrings.

**Comment by oscarbenjamin** [comment]
@sylee957 what should be done with this PR? I don't understand what its purpose is.

**Comment by ayushbisht2001** [comment]
@sylee957 , what should be done with this PR, would it be worth to merge this PR ??

**Comment by ayushbisht2001** [comment]
@sylee957 , can u please review this one ?? what should be done with this ?

**Pull request merged**
