### PR TITLE
Enable Jupyter LaTeX formatting by default

### LINKED ISSUE #7003: Use IPython display system automatically
```
Is there a good reason to not just use the IPython display system to make SymPy objects always print with mathjax in the notebook? pandas defaults to a custom display in IPython. We could make init_printing() overwrite the default.
```

Original issue for #7003: http://code.google.com/p/sympy/issues/detail?id=3904
Original author: https://code.google.com/u/asmeurer@gmail.com/

### PR DESCRIPTION
**Pull request by asmeurer**
It is still often preferable to use `init_printing()`, however, as this will
also cause builtin numeric types like int to format as LaTeX, as well as
container types like lists and dicts that contain SymPy objects.
`init_printing()` can also be used to change the LaTeX settings, like setting a
custom printer (`init_printing()` overrides the default `_repr_latex_`).

I did not add `_repr_png_` because it would add a large amount of data to any
notebook containing SymPy expressions, and it is only useful in the qtconsole.
`init_printing()` can still be used to get png LaTeX printing.

I have used `'equation*'` here, c.f. #15367.
If we decide to not change the default from `'plain'` to `'equation*'` in that
pull request, we should change that here too.

I was not able to find a way to test this. The IPython printing tests seem to
not render LaTeX at all unless `init_printing()` is used (even if I do
`inst.display_formatter.formatters['text/latex'].enabled = True`).

Fixes #7003.

#### Release Notes

* interactive
  * SymPy objects now render as LaTeX automatically in the Jupyter notebook. `init_printing()` is still required to make Python builtin numeric types (such as `int` and `float`) render as LaTeX, Python container types (such as `list` and `dict`) containing SymPy objects render as LaTeX, to change the printer settings, or to get LaTeX printing in the qtconsole.

### CODE REVIEW

**Comment by asmeurer** [comment]
By the way, I noticed while fixing this that `init_printing()` enables the png formatter in the notebook by default (you have to do `init_printing(use_latex='mathjax')` to disable it). I guess it has been this way for some time. This is unfortunate, because it causes notebooks with SymPy expressions to be larger than they need to be, and also to be slower to render.  But there is no way to distinguish between the notebook and the qtconsole, so I think this will probably not end up changing.

**Comment by moorepants** [comment]
> But there is no way to distinguish between the notebook and the qtconsole, so I think this will probably not end up changing.

Yes this has been discussed times before. IPython/Jupyter doesn't have a mechanism to know what frontend it is being run from (or something like that) so we've always generated pngs and mathjax.

**Comment by asmeurer** [comment]
> Yes this has been discussed times before. IPython/Jupyter doesn't have a mechanism to know what frontend it is being run from (or something like that) so we've always generated pngs and mathjax.

It's unfortunate. It adds about 1 kB to the output even for something as small as `Integral(1/x, (x, 1, 2))`. (Physically) larger expressions are much more. For instance, `Add(*[Integral(1/x**i, (x, 1, 2)) for i in range(100)])` produces a PNG that's almost 14 kB. These are embedded in the notebook, even though they are never used.

**Comment by asmeurer** [comment]
I have enabled support for Vector, Dyadic, and NDimArray as well. 

This is ready to review, but please let's decide on #15367 before merging this.

Also reminder that this isn't automatically tested. It should be tested manually.

**Comment by asmeurer** [comment]
This is the 14kB image by the way: 
image

**Comment by asmeurer** [comment]
Any objections to this?

**Comment by moorepants** [comment]
I think this is long overdue :)

**Pull request merged**
