### PR TITLE
Improve the handling of oscillatory sequences

### PR DESCRIPTION
**Pull request by normalhuman**
#### References to other Issues or PRs

Addresses some (not all) of the issues with oscillatory sequences in #14192

#### Brief description of what is fixed or changed
 
Oscillatory sequences are handled by considering odd and even indices separately (this is more efficient than replacing n by `2*n` or `2*n+1` as was previously done). Also, the presence of sin or cos in the formula now qualifies a sequence as oscillatory.

When the limits along even and odd indices exist but are different, AccumBounds is returned instead of None.

For some sequences, the absolute value can be handled by `limit_seq` while the original sequence cannot (for example, `(I/2)**n`). If the limit of absolute value is 0, the limit of the original sequence is also
0.

### CODE REVIEW

**Comment by gxyd** [comment]
Debugger shows that, actually its because of `gammasimp` simplifies it to zero.
```python
In [1]: a = Abs((I/2)**n)

In [2]: import pdb

In [3]: pdb.run("limit_seq(a, n)")
> <string>(1)<module>()
(Pdb) s
--Call--
> /home/gxyd/dev/sympy/sympy/series/limitseq.py(150)limit_seq()
-> def limit_seq(expr, n=None, trials=5):
(Pdb) s
> /home/gxyd/dev/sympy/sympy/series/limitseq.py(196)limit_seq()
-> from sympy.concrete.summations import Sum
(Pdb) b sympy/series/limitseq.py:116
Breakpoint 1 at /home/gxyd/dev/sympy/sympy/series/limitseq.py:116
(Pdb) c
> /home/gxyd/dev/sympy/sympy/series/limitseq.py(116)_limit_seq()
-> for i in range(trials):
(Pdb) n
> /home/gxyd/dev/sympy/sympy/series/limitseq.py(117)_limit_seq()
-> if not expr.has(Sum):
(Pdb) n
> /home/gxyd/dev/sympy/sympy/series/limitseq.py(118)_limit_seq()
-> result = _limit_inf(expr, n)
(Pdb) n
> /home/gxyd/dev/sympy/sympy/series/limitseq.py(119)_limit_seq()
-> if result is not None:
(Pdb) p result
None
(Pdb) n
> /home/gxyd/dev/sympy/sympy/series/limitseq.py(122)_limit_seq()
-> num, den = expr.as_numer_denom()
(Pdb) p num
*** NameError: NameError("name 'num' is not defined",)
(Pdb) n
> /home/gxyd/dev/sympy/sympy/series/limitseq.py(123)_limit_seq()
-> if not den.has(n) or not num.has(n):
(Pdb) p num
sqrt(I**_n*(-I)**_n)
(Pdb) p den
2**_n
(Pdb) n
> /home/gxyd/dev/sympy/sympy/series/limitseq.py(129)_limit_seq()
-> num, den = (difference_delta(t.expand(), n) for t in [num, den])
(Pdb) n
> /home/gxyd/dev/sympy/sympy/series/limitseq.py(130)_limit_seq()
-> expr = (num / den).gammasimp()
(Pdb) n
> /home/gxyd/dev/sympy/sympy/series/limitseq.py(132)_limit_seq()
-> if not expr.has(Sum):
(Pdb) p expr
0
(Pdb) p num
-sqrt((-1)**_n*I**(2*_n)) + sqrt((-1)**(_n + 1)*I**(2*_n + 2))
(Pdb) p den
2**_n
(Pdb) p (num / den).gammasimp()
0
```
While so is not the case with `(I/2)**n`.

**Comment by gxyd** [comment]
How about (a diff on top of your branch):
```diff
@@ -136,6 +136,13 @@ def _limit_seq(expr, n, trials):
 
         num, den = expr.as_numer_denom()
 
+        if not expr.has(Sum) and not expr.is_Add:
+            num_, den_ = (difference_delta(Abs(t).expand(), n)
+                           for t in [num, den])
+            expr_ = (num_ / den_).gammasimp()
+            if expr_ == 0:
+                return S.Zero
+
         num = dominant(num, n)
         if num is None:
             return None
@@ -224,14 +231,7 @@ def limit_seq(expr, n=None, trials=5):
                         return AccumulationBounds(Min(L1, L2), Max(L1, L2))
                     else:
                         return None
+                elif L1 == L2:
+                    return L1
     else:
-        L1 = _limit_seq(expr.xreplace({n: n_}), n_, trials)
-
-    if L1 is not None:
-        return L1
-    else:
-        # Maybe the absolute value is easier to deal with (though not if
-        # it's a sum). If it tends to 0, the limit is 0.
-        if not(expr.has(Sum) or expr.is_Add):
-            if _limit_seq(Abs(expr.xreplace({n: n_})), n_, trials) is S.Zero:
-                return S.Zero
+        return _limit_seq(expr.xreplace({n: n_}), n_, trials)
```

You can look here as well, https://github.com/gxyd/sympy/commit/a65dd4d08d1f70ae2ea864df8950724d892dc597

**Comment by normalhuman** [comment]
For the geometric sequence `(I/2)**n` there is indeed a simplification to zero after its Abs is separated as 1 / 2**n and the difference_delta is applied to both. This is not the only way how a limit can be found to be 0; this is just what happens for this specific sequence. 

For the sequence `sqrt(n)*(I/2)**n` there will not be such simplification. And I do notice that `limit_seq` fails to find the limit here even with this patch, so this patch isn't ready.

**Comment by normalhuman** [comment]
It seems that the reason  `sqrt(n)*(I/2)**n` was not handled was in Abs, namely #14260.

**Comment by normalhuman** [comment]
Now that Abs has been fixed in #14278, the example of `sqrt(n)*(I/2)**n` and similar evaluate (limit 0)

**Pull request closed without merging**
