### PR TITLE
`memoize_property` decorator now caches value locally

### PR DESCRIPTION
**Pull request by drybalka**
#### Brief description of what is fixed or changed
`memoize_property` decorator now does not require a storage and saves
cached values locally. This allows a one-line use of this decorator for caching
expensive properties without creating and managing a storage explicitly.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by kenluck2001** [comment]
Can you add a test? Simulate the cache and use decorator on some dummy function, then check for the items in the cache.

**Comment by drybalka** [comment]
Well, I checked that beforehand and that is not true. If you try (in 'ipython', for example):
```
>>> object() is object()
False
```
It is precisely the job of `memoize_property` to cache the property on the first evaluation and then return the same object.

**Comment by kenluck2001** [comment]
> Well, I checked that beforehand and that is not true. If you try (in 'ipython', for example):
> 
> ```
> >>> object() is object()
> False
> ```
> 
> It is precisely the job of `memoize_property` to cache the property on the first evaluation and then return the same object.

Thanks for the check that you made. The test now makes sense to me.

**Comment by oscarbenjamin** [comment]
What is the purpose of all these methods you are memoizing? They all just return `Predicate(name)`. I haven't looked much through the new assumptions code but I don't see what the point is. It looks as if these methods could all just be attributes rather than memoized methods.

**Comment by drybalka** [comment]
To tell you the truth, I have no idea what is the purpose of memoization in that particular case as I am not familiar with the assumptions code. These memoizations were in the code before this PR and there's a comment in "ask.py" that states that they are crucial. I would not dare changing the logic of the assumptions code. All this PR does is get rid of the unnecessary memoization storage.

**Comment by oscarbenjamin** [comment]
Given that they are all cached it looks to me as if we could just replace this
```python
    @memoize_property
    def hermitian(self):
         return Predicate('hermitian')
```
with this
```python
    hermitian = Predicate('hermitian')
```

**Comment by drybalka** [comment]
Maybe the original author did not want to evaluate all the properties in the initialization step? Or maybe he wanted to have neat docstrings for each property?

**Comment by oscarbenjamin** [comment]
This looks good. Merging.

I still think that this memoisation probably isn't needed: there are simpler ways to implement this class but that's a separate issue.

**Pull request merged**
