### PR TITLE
I fixed the error described in issue #10395.

### PR DESCRIPTION
**Pull request by ghost**
After doing some manual testing, I discovered that there was even more untold and unexpected behavior produced by 'nfloat()'. For more information, please see the comment I added to issue #10395.

 I found that one line of code, which attempted to set the "re-set"precision, was causing the issue described in #10395. I am not sure why this line of code is needed or how it caused these extremely unexpected behaviors.

I have updated the test with a condition that confirms that the issue is resolved. I am not sure why the other tests use the '_aresame()' function when all of the other tests seem to use '=='. Manually testing each assertion confirmed that each test still passed, so I changed up some of the other assertions.

### CODE REVIEW

**Comment by Spaethk** [comment]
Um, it appears that the test is producing an 'E' which I have discovered means exception. If anyone can provide me with some insight on how to remedy this situation please let me know. All of the assertions work when manually executed to the best of my knowledge.

**Comment by smichr** [comment]
The docstring says the function will "Make all Rationals in expr Floats except those in exponents" so the tests that you have modified where this is not true are wrong. I'm not saying there isn't a problem, however...what you pointed out in the issue is really strange. But if a Rational doesn't become a float in an expression, *that* modification is wrong.

**Comment by smichr** [comment]
The problem is in operations.py. Max is an AssocOp like Mul and Add but the code there doesn't watch out for other AssocOps. I have a PR with the changes that is running tests now.

Thanks for bringing attention to this issue!

**Comment by Spaethk** [comment]
Thank you for the help Christopher. What is the issue number or link to the new PR that you made to change operations.py?

**Pull request closed without merging**
