### PR TITLE
Fix the link to the SymPy logo svg in the docs

### PR DESCRIPTION
**Pull request by asmeurer**
It turns out I can't build the docs (don't have rsvg-convert) and I don't have time to figure it out right now, so someone should check this before merging.

### CODE REVIEW

**Comment by moorepants** [comment]
Did github break links? That seems odd.

**Comment by asmeurer** [comment]
I think replacing `blob` with `tree` still works. The problem is that it's in a logo directory.

**Comment by asmeurer** [comment]
OK, I was able to get the docs building. It looks like this fix works.

**Comment by jcrist** [comment]
@asmeurer : good to merge?

**Pull request merged**
