### PR TITLE
Pretty-print numbers ending with large number of zeros

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References to other Issues or PRs

Closes #12123 

#### Other comments
ping @bjodah 

#### Release Notes

* printing
  * Large numbers are now printed as powers of 10

### CODE REVIEW

**Comment by czgdp1807** [comment]
I think there are some unwanted changes. Will remove them shortly.

**Comment by czgdp1807** [comment]
I don't know why the recent commits are not being reflected here. They are showing on my branch but updates are not being shown here. 
@sylee957 Can you please take a look and help me out.

**Comment by czgdp1807** [comment]
I still want to know the reason of this PR not being updated.

**Comment by sylee957** [comment]
It can be because of the github slowdowns
https://www.githubstatus.com/

**Pull request closed without merging**
