### PR TITLE
Add Gauss-Lobatto quadrature

### PR DESCRIPTION
**Pull request by nicoguaro**
- Add [Gauss-Lobatto quadrature](https://en.wikipedia.org/wiki/Gaussian_quadrature#Gauss.E2.80.93Lobatto_rules)
- Formatted code according to PEP8 (except for hyperlinks that are too long for that)

### CODE REVIEW

**Comment by certik** [comment]
It says "ImportError: cannot import name gauss_lobatto". Did you forget to commit some change?

**Comment by nicoguaro** [comment]
Yes... I am not knowledgeable enough apparently. It is my first time trying to commit to the project. Any suggestions?

**Comment by certik** [comment]
@nicoguaro no worries. I think what you need to do is to take the tests in this PR (#10260) and merge it with the implementation in your other PR (#10245). Do you know how to do that from the command line using git? If not, let me know, I can help.

**Comment by nicoguaro** [comment]
I merged them in my own repo. What should I do now?

**Comment by nicoguaro** [comment]
@certik, if you think that is easier, we can remove this pull request and I start over.

**Comment by certik** [comment]
@nicoguaro keep this PR open, but just rebase your code on top of the latest master, and do any merged that are needed. Ping me if you need help. If I don't reply, please do not hesitate to ping me again. I didn't realize that you were waiting for my input.

**Comment by nicoguaro** [comment]
@certik , I tried to rebase it but it found tons of conflicts from the what I assume is the assumption system changes. Any ideas?

**Comment by smichr** [comment]
I'm guessing the master you based your changes on is too old relative to the new master. What I generally do in this case (if I don't have too many commits) is save the diff and apply it to a fresh master. Assuming you are on the `patch-3` branch I would do the following:

```
git log -oneline  <--find what the SHA1 is before your first commits, call it foo
git diff foo > dif
git checkout master
git pull
git checkout -b wip
git apply dif
git commit -am 'my title...'
git branch -D patch-3
git checkout -b patch-3
git push nicoguaro patch-3
```

One thing that is a little troubling is that what is committed here doesn't include the changes that you must have made to the quadrature file.

**Comment by nicoguaro** [comment]
I can also start from scratch, make the changes on the new and clean setup and then commit it. How does that sound?

**Comment by nicoguaro** [comment]
I created a new PR #11728, for Lobatto quadrature.

**Comment by gxyd** [comment]
I think we can close this one now. The other PR #11728 has been merged.

**Pull request closed without merging**
