### PR TITLE
Generalize Holonomic to work on symbolic powers

### PR DESCRIPTION
**Pull request by zaxtax**
This pull request implements the suggestion of @asmeurer in #12955

Although holomonic.py is not as generic as I want it to be, this is in my opinion a good start.

### CODE REVIEW

**Comment by asmeurer** [comment]
Looks like the Travis failure is unrelated (https://github.com/sympy/sympy/issues/12898).

**Comment by asmeurer** [comment]
I helped @zaxtax with this at the scipy sprints. As I mentioned, it would be simpler if holonomic used Poly internally. This ends up converting to and from Poly to make use of its automatic domain machinery. It would be simpler if the annihilator coeffs were just Poly in the first place.

**Comment by asmeurer** [comment]
It would be useful to add direct tests for the fixes, in addition to the distributions. That way expr_to_holonomic works is ever changed it will still be tested.

**Comment by zaxtax** [comment]
What do you have in mind? Something like this?

````python
>>> from sympy.holonomic import expr_to_holonomic
>>> from sympy import symbols
>>> x, n = symbols("x n")
>>> expr_to_holonomic(x**n, x)
HolonomicFunction((-n) + (x)*Dx, x, 0, [1])
````

**Comment by asmeurer** [comment]
I mean don't use expr_to_holonomic at all in those tests. Directly create a HolonomicFunction and take a symbolic power (and similar for the other fixes).

**Comment by zaxtax** [comment]
So like?

````python
from sympy.holonomic import DifferentialOperators, HolonomicFunction, expr_to_holonomic
from sympy import symbols, QQ

x, n = symbols("x n")
Q = QQ[n].get_field()
_, Dx = DifferentialOperators(Q.old_poly_ring(x), 'Dx')
h1 = HolonomicFunction((-1) + (x)*Dx, x, 0) ** -n
h2 = HolonomicFunction((n) + (x)*Dx, x)
assert h1 == h2
````

**Comment by asmeurer** [comment]
Yeah.

**Comment by zaxtax** [comment]
And it looks like I lucked out with the tests passing!

**Comment by asmeurer** [comment]
This looks good to me. What was the situation with Cauchy?

@jksuom any comments?

**Comment by zaxtax** [comment]
If you replace pi with a symbol it works for Cauchy! Also if you use a RR domain it works with Cauchy but the solution is a bit ugly.

**Comment by asmeurer** [comment]
It should be using either QQ[pi] or EX. What is the exact traceback?

**Comment by zaxtax** [comment]
So I just pass the density to the `expr_to_holonomic`
````
x, loc = symbols("x loc")
g = symbols("g", positive=True)
dens = 1/(pi*g*(1 + (-loc + x)**2/g**2))
````
I get the error

`ValueError: expected an expression convertible to a rational function in Rational function field in g, loc over QQ with lex order, got pi*g**3`

But if I do this

````
from sympy import pi
Q = QQ[loc,g,pi].get_field()
expr_to_holonomic(dens, x, domain=Q)
````
Then it works out and I get:

````
HolonomicFunction((-2*pi*g**3*loc + 2*pi*g**3*x) + (pi*g**5 + pi*g**3*loc**2 - 2*pi*g**3*loc*x + pi*g**3*x**2)*Dx, x, 0, [1/(pi*g*(1 + loc**2/g**2))])
````

So I am pretty pleased.

**Comment by jksuom** [comment]
This looks good to me. If a holonomic function is defined by an equation of degree 1, the equation of its n'th power, even negative, can be given in closed form as it is done here.

The situation is different with equations of degree > 1. Then only positive powers can be defined and the equations cannot generally be given in closed form. (Instead, the powers may be obtained from combined differential and difference equations as holonomic functions of two variables x and n. See e.g. the paper of Bronstein et. al. in ISSAC'97 referred to on this page: https://www-sop.inria.fr/cafe/Manuel.Bronstein/publications/mb_papers.html.)

    Q = QQ[loc,g,pi].get_field()
    expr_to_holonomic(dens, x, domain=Q)

This seems to be the way it has to be done currently. I think there is some code to make this automatic but apparently the task was not quite completed.

**Comment by asmeurer** [comment]
The formula should be correct for any real number, not just integers (as is the case in the beta PDF), as long as the exponent doesn't depend on x. Exponents that do depend on x actually could be holonomic if the base is constant (`a**x`), but that can be fixed another day. The point being that the exponent `n` is not necessarily a polynomial. It could require the EX domain. I believe this code would handle such cases correctly.

> I think there is some code to make this automatic but apparently the task was not quite completed.

This seems related to my suggestion to use Poly internally instead of DMP. Poly generally handles this sort of thing automatically.

**Comment by zaxtax** [comment]
Does sympy support difference equations?

**Comment by asmeurer** [comment]
Not yet.

**Pull request merged**
