### PR TITLE
Custom otional label in Pauli matrices

### PR DESCRIPTION
**Pull request by mikelRM**
Added an optional attribute label="sigma" to the Pauli class in
the sympy.physics.paulialgebra module.

#### Brief description of what is fixed or changed
When working with direct products of two different 2x2 spaces, it is common to 
name Pauli matrices that refer to each one of these two spaces differently. In
this change I implemented the option to change the symbol that is used to 
represent Pauli matrices and added an explanation and some basic examples 
into the docstring.

#### Release Notes

* physics.paulialgebra
  * added the option to change the symbol representing the Pauli matrices

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This patch looks good. I don't know enough about the use case to say that it's a good change to make though. Hopefully someone who does will take a look...

**Comment by oscargus** [comment]
I'm in a similar situation. However, I assume that from a user perspective it will not affect anyone not wanting the feature, right?

**Comment by oscarbenjamin** [comment]
Yeah, I guess it can't hurt anyone who doesn't use it.

**Comment by oscarbenjamin** [comment]
Thanks @mikelRM !

**Pull request merged**
