### PR TITLE
ComplexPlane->ComplexRegion name changed

### LINKED ISSUE #9869: Rename ComplexPlane to ComplexRegion
See https://github.com/sympy/sympy/pull/9500#discussion_r37886701

The complex plane is the whole complex plane, whereas an instance of `ComplexPlane` is generally not.

### PR DESCRIPTION
**Pull request by gxyd**
fixed #9869

### CODE REVIEW

**Comment by jksuom** [comment]
+1

**Comment by leosartaj** [comment]
Looks good. Merging.

**Comment by aktech** [comment]
@gxyd  Thanks for working on this.

**Comment by gxyd** [comment]
Thanks @jksuom @leosartaj @aktech

**Pull request merged**
