### PR TITLE
Update drv.py

### PR DESCRIPTION
**Pull request by koushik101**
probably this will solve this https://github.com/sympy/sympy/issues/13576 issue.

### CODE REVIEW

**Comment by ylemkimon** [comment]
Use floor from `sympy`, specifically `sympy.functions.elementary.integers`. Also, please add tests.

**Comment by koushik101** [comment]
Sure

Thanks
Koushik

**Comment by koushik101** [comment]
sure

**Comment by akash9712** [comment]
Importing `floor` does not solve the issue. `floor` recieves a boolean value from ` sympy.functions.elementary.integers`, which raises a TypeError.

**Comment by akash9712** [comment]
@koushik101 The `_inverse_cdf_expression` method tries to invert the CDF, which is a piecewise, non invertible function. I think a way to fix this would be to restrict the CDF variable to an integer to obtain the invertible part of the CDF (which is what we are concerned with) in this method, and then try to invert it.

**Comment by oscargus** [comment]
As #13576 is resolved elsewhere, I close this for now.

**Pull request closed without merging**
