### PR TITLE
Add a 3.9-dev build to Travis

### PR DESCRIPTION
**Pull request by asmeurer**
We don't necessarily need to merge this, though we might consider it. I mainly want to see if things fail. 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
It looks like the tests didn't manage to run

**Comment by asmeurer** [comment]
Huh. What happened?

**Comment by asmeurer** [comment]
The first thing that would be run is `pip install mpmath`. Maybe it ran and failed somehow and the error didn't end up in the log.

**Comment by jksuom** [comment]
There is pip 20.0.2 while the succeeding jobs seem to have something different.

**Comment by asmeurer** [comment]
I don't have time to look into this now. If someone else wants to, go ahead. Otherwise, I suggest we just try restarting the job every once in a while until we get something more meaningful. I suspect the issue is a bug in Travis or in pip, so it might be fixed upstream eventually.

**Comment by oscarbenjamin** [comment]
I restarted the tests but they seem to have failed in the same way

**Comment by czgdp1807** [comment]
@asmeurer @oscarbenjamin I have restarted the tests.

**Comment by asmeurer** [comment]
It still fails.

**Comment by asmeurer** [comment]
I merged in master so it is no longer installing fastcache, but this still fails. I think it is failing on this line https://github.com/sympy/sympy/pull/18466/files#diff-354f30a63fb0907d4ad57269548329e3R243

```
pip list | grep "numpy" && pip uninstall -y numpy;
```

**Comment by asmeurer** [comment]
OK, I guess this is working now. There are test failures in 3.9 (see #19638). For some reason, the echo line is needed or else Travis truncates the log.

**Comment by oscarbenjamin** [comment]
It doesn't look like the log is truncated. The job previously ran in 30 seconds so it clearly wasn't running the tests.

**Comment by asmeurer** [comment]
I also added a doctests build for 3.9.

**Comment by asmeurer** [comment]
Oh, I see what is happening. The line 

```
pip list | grep "numpy" && pip uninstall -y numpy;
```

gives a non-zero exit status, because numpy is not included in pip list. So it fails the build because of the `set -x`. The `echo done` causes it to not fail because `set -x` only looks at the status of the whole if block, which is based on the status of the last statement.

**Comment by oscarbenjamin** [comment]
Closing and reopening to to rerun the tests after merging #18819

**Comment by oscarbenjamin** [comment]
Seems to be working find after merging #18819.

I think we should merge this. I'm going to cherry-pick for 1.6.1

**Pull request merged**
