### PR TITLE
Improve performance and grammar of Lie algebra E

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

This is about twice as fast as earlier.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
The liealgebras module was largely rewritten in #20459. It's a shame that hasn't been merged.

**Comment by oscarbenjamin** [comment]
The changes here look good

**Comment by oscargus** [comment]
> It's a shame that hasn't been merged.

Ahh, didn't know that. I agree fully. Much more solid work compared to mine. (Although the Rational-creating can be avoided there as well.)

**Comment by sylee957** [comment]
I think that the tests should be re-run, but I'm not sure I have authority now to re-run tests because I can't see the button.
https://github.com/sympy/sympy/pull/20459 already has merge conflicts now, so I'd consider it slightly outdated and we can merge this first

**Comment by asmeurer** [comment]
Closing and reopening makes the tests rerun

**Pull request merged**
