### PR TITLE
Fix lambdify tests

### LINKED ISSUE #18079: Lambdify test failing
https://travis-ci.org/sympy/sympy/jobs/627051548?utm_medium=notification&utm_source=github_status

```python
________________________________________________________________________________
______________________ sympy.utilities.lambdify.lambdify _______________________
File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/utilities/lambdify.py", line 402, in sympy.utilities.lambdify.lambdify
Failed example:
    f.__globals__['sin']
Expected:
    <ufunc 'sin'>
Got:
    <function _deprecated.<locals>.wrap.<locals>.call at 0x7fe9bb18a9d8>
**********************************************************************
File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/utilities/lambdify.py", line 404, in sympy.utilities.lambdify.lambdify
Failed example:
    f.__globals__['cos']
Expected:
    <ufunc 'cos'>
Got:
    <function _deprecated.<locals>.wrap.<locals>.call at 0x7fe9bb1ff510>
**********************************************************************
File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/utilities/lambdify.py", line 406, in sympy.utilities.lambdify.lambdify
Failed example:
    f.__globals__['sin'] is numpy.sin
Expected:
    True
Got:
    False
```

I guess that some external packages have deprecated those functions.
But I'm unable to reproduce the issue with only `numpy` and `tensorflow` installed. Probably some other modules may have to be loaded

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

Fixes #18079 

#### Brief description of what is fixed or changed

A better fix would be a rework of the lambdify to use fully qualified modules instead of overriding the global namespace,
But this workaround may fix the travis issues now.

#### Release Notes

- utilities
  - lambdify: avoid using scipy versions of numpy functions, which are deprecated, in lambdify.

### CODE REVIEW

**Comment by moorepants** [comment]
This doesn't break any tests so I'm fine with merging. It is blocking lots of other PRs that are failing.

Two comments: 1) the order of imports does matter in lambdify so if anyone relied on the prior order of scipy and numpy things could break for them. 2) This will no longer work with older scipy version presumably.

**Comment by oscarbenjamin** [comment]
The effect of this is that any name that is available in both scipy and numpy will be taken in the first instance from numpy. For the examples we see here (sin and cos) that will work fine with older versions. Basically scipy was exporting numpy's sin and cos functions and has now deprecated that.

It looks like a lot of the objects in scipy's namespace are just imported from numpy. A big chunk of those have now been deprecated:
https://github.com/scipy/scipy/blob/c0dc7fccc53d8a8569cde5d55673fca284bca191/scipy/__init__.py#L69-L103

**Comment by asmeurer** [comment]
Are there any functions in both scipy and numpy that aren't now deprecated? Those would be different with this. If not (I suspect not), then this change shouldn't have any effect on the final lambdify behavior. 

Also we will need to put this in the 1.5.1 release, so that the tests pass in it.

**Comment by asmeurer** [comment]
I tired changing the base to 1.5 but it looks like this needs a rebase to make that work.

**Comment by oscarbenjamin** [comment]
There are many names in common between numpy and scipy:
```
In [7]: names_both = (numpy.__dict__.keys() & scipy.__dict__.keys())                                                              

In [8]: len(names_both)                                                                                                           
Out[8]: 593
```
A quarter of those are shared between the two packages:
```
In [12]: len([_ for n in names_both if getattr(numpy, n) is getattr(scipy, n)])                                                   
Out[12]: 169
```
These are the names of the objects that are identical between both packages:
```
['longlong', 'ogrid', 'str0', 'vectorize', 'MAXDIMS', 'recarray', 'FPE_OVERFLOW', 'float32', 'short', 'random', 'BUFSIZE', 'MachAr', 'longcomplex', 'pi', 'string_', 'uint0', 'infty', 'single', 'typecodes', 'cast', 'int_', 'inf', 'uintp', 'ushort', 'complex128', 'double', 'print_function', 'ubyte', 'sctypes', 'int16', 'errstate', 'ERR_PRINT', 'complex64', 'chararray', 'dtype', 'clongfloat', 'flexible', 'iinfo', 'singlecomplex', 'matrix', 'void0', 'cfloat', 'sctypeNA', 'uint32', 'SHIFT_INVALID', 'NINF', 'MAY_SHARE_EXACT', 'bool8', 'void', 'TooHardError', 'ComplexWarning', 'ALLOW_THREADS', 'char', 'bytes0', 'uint8', 'poly1d', 'half', 'timedelta64', 'emath', 'nbytes', 'nan', 'ERR_IGNORE', 'byte', 'uint', 'int32', 'ERR_RAISE', 'int64', 'nditer', 'intp', 'rec', 'RAISE', 'euler_gamma', 'broadcast', 'FPE_DIVIDEBYZERO', 'float128', 'ERR_LOG', 'NaN', 'int0', 'ERR_DEFAULT', 'ERR_WARN', 'object_', 'intc', 'bool_', 'FPE_INVALID', 'ulonglong', 'c_', 'r_', 'longdouble', 'float_', 'ndenumerate', 'ModuleDeprecationWarning', 'signedinteger', 'unicode', 'division', 'unicode_', 'ScalarType', 'str_', 'int8', 'DataSource', 'Infinity', 's_', 'complex256', 'unsignedinteger', 'generic', 'clongdouble', 'FLOATING_POINT_SUPPORT', 'NAN', 'WRAP', 'SHIFT_DIVIDEBYZERO', 'math', 'datetime64', 'Inf', 'inexact', '__builtins__', 'longfloat', 'bytes_', 'object0', 'finfo', 'uintc', 'float64', 'MAY_SHARE_BOUNDS', 'sctypeDict', 'csingle', 'ndarray', 'little_endian', 'index_exp', 'FPE_UNDERFLOW', 'memmap', 'newaxis', 'complexfloating', 'PINF', 'VisibleDeprecationWarning', 'ERR_CALL', 'SHIFT_OVERFLOW', 'floating', 'e', 'cdouble', 'NZERO', 'flatiter', 'tracemalloc_domain', 'ctypeslib', 'RankWarning', 'UFUNC_PYVALS_NAME', 'long', 'uint16', 'uint64', 'SHIFT_UNDERFLOW', 'UFUNC_BUFSIZE_DEFAULT', '_UFUNC_API', 'record', 'busdaycalendar', 'ufunc', 'True_', 'character', 'ma', 'number', 'complex_', 'absolute_import', 'format_parser', 'ndindex', 'mgrid', 'AxisError', 'CLIP', 'typeNA', 'False_', 'typeDict', 'float16', 'PZERO', 'integer']
```
Three quarters of the objects with the same name are not identically equal:
```julia
In [16]: names_unequal = ([_ for n in names_both if getattr(numpy, n) is not getattr(scipy, n)])                                  

In [17]: len(names_unequal)                                                                                                       
Out[17]: 424
```
These are the names that have different objects in numpy and scipy
```
['ix_', 'squeeze', 'issctype', 'putmask', 'frexp', 'power', 'vdot', 'loads', 'allclose', 'logical_and', 'busday_offset', 'var', 'tril_indices_from', 'format_float_scientific', 'diff', 'ravel', 'add_docstring', 'hypot', 'vstack', 'clip', 'zeros_like', 'mask_indices', 'nanprod', 'resize', 'empty', 'asarray', 'mean', 'unwrap', 'cos', 'isnan', 'tril_indices', 'alen', 'ravel_multi_index', 'bitwise_or', 'asanyarray', 'npv', 'bitwise_xor', 'nancumsum', 'less', 'spacing', 'negative', 'mod', 'lcm', '__all__', 'ldexp', 'datetime_as_string', 'set_printoptions', 'ascontiguousarray', 'asarray_chkfinite', 'outer', 'dsplit', '__file__', 'fix', 'argpartition', 'stack', '__spec__', 'full_like', 'show_config', 'take_along_axis', 'array_equal', 'all', 'einsum', 'rad2deg', 'ndfromtxt', 'trim_zeros', '__loader__', 'nanvar', 'insert', 'linspace', 'hamming', 'tensordot', 'byte_bounds', 'min_scalar_type', 'correlate', 'may_share_memory', 'positive', 'nper', 'compare_chararrays', 'packbits', 'array_str', 'issubdtype', 'piecewise', 'exp', 'recfromcsv', 'digitize', 'unpackbits', 'in1d', 'hanning', 'hsplit', 'heaviside', 'ppmt', 'binary_repr', 'log1p', 'radians', 'array_equiv', 'place', '__name__', 'setbufsize', 'array2string', 'int_asbuffer', 'source', 'recfromtxt', 'partition', 'asmatrix', 'promote_types', 'fill_diagonal', 'fv', 'asscalar', '__config__', '_distributor_init', 'logical_or', 'put', 'roll', '_add_newdoc_ufunc', 'isclose', 'result_type', 'mirr', 'asfortranarray', 'frompyfunc', 'isinf', 'rank', 'arange', 'irr', 'moveaxis', 'ptp', 'add', 'cumproduct', 'iscomplex', 'absolute', 'signbit', 'polyadd', 'asfarray', 'sin', 'take', 'broadcast_to', 'polyval', 'polysub', 'conjugate', 'fmax', 'i0', 'nextafter', 'pv', 'percentile', 'delete', 'kron', 'isreal', 'loadtxt', 'expm1', 'polyint', 'pad', 'sort_complex', 'cumsum', 'choose', 'reciprocal', 'ceil', 'concatenate', 'row_stack', 'histogram_bin_edges', 'blackman', '__path__', 'exp2', 'cosh', 'rot90', 'atleast_3d', 'savetxt', 'logaddexp2', 'arctan', 'real_if_close', 'bitwise_and', 'right_shift', 'arctan2', 'mintypecode', 'copysign', 'interp', 'subtract', 'tanh', 'geomspace', 'unique', 'require', 'polymul', 'iterable', 'gcd', 'tile', 'rint', 'count_nonzero', 'zeros', 'indices', 'append', 'vsplit', 'ones_like', 'equal', 'shape', 'mat', 'product', 'tri', 'tril', 'ones', 'triu', 'sometrue', 'sinc', 'nanquantile', 'setxor1d', 'quantile', 'fmod', 'apply_along_axis', 'seterrobj', 'argmin', 'save', 'dstack', 'cumprod', 'logical_xor', 'bincount', 'getbufsize', '__package__', 'cross', 'identity', 'diagonal', 'select', 'histogramdd', 'sinh', 'deg2rad', 'mafromtxt', 'floor', 'swapaxes', 'histogram', 'unravel_index', 'reshape', 'compress', 'intersect1d', 'savez', 'einsum_path', 'flip', 'multiply', 'polydiv', 'lexsort', 'broadcast_arrays', 'maximum', 'true_divide', 'fromregex', 'load', 'nanargmax', 'logspace', 'frombuffer', 'iscomplexobj', 'info', 'extract', 'corrcoef', 'around', 'safe_eval', 'fabs', 'triu_indices', 'typename', 'issubsctype', 'cov', 'deprecate', 'fromfunction', 'dot', 'log10', 'who', 'roots', 'inner', 'argwhere', 'meshgrid', 'ediff1d', 'busday_count', 'sum', 'issubclass_', 'square', 'isin', 'empty_like', 'format_float_positional', 'repeat', 'arcsinh', '__version__', 'test', 'fromiter', 'diag_indices', 'lookfor', 'column_stack', 'invert', 'ndim', 'isnat', 'setdiff1d', 'degrees', 'bartlett', 'diagflat', 'fft', 'amax', 'isposinf', 'sort', 'nansum', 'bitwise_not', 'nanmax', 'deprecate_with_doc', 'average', 'array_repr', 'fromstring', 'nanmean', 'poly', 'divmod', 'array', 'greater_equal', 'nanpercentile', 'get_printoptions', 'set_string_function', 'cbrt', 'version', 'gradient', 'put_along_axis', 'add_newdoc', 'trunc', 'atleast_1d', 'polyder', 'nested_iters', 'full', 'fliplr', 'pmt', 'split', 'atleast_2d', 'eye', 'arcsin', 'set_numeric_ops', 'fromfile', 'datetime_data', 'logaddexp', 'nancumprod', 'sign', 'convolve', 'trace', 'isneginf', 'base_repr', 'diag', 'divide', 'triu_indices_from', 'isscalar', 'modf', 'not_equal', 'isfortran', 'flatnonzero', 'seterrcall', 'log2', 'minimum', 'log', 'remainder', 'fmin', 'prod', 'argsort', 'less_equal', 'maximum_sctype', 'savez_compressed', 'add_newdoc_ufunc', 'angle', 'kaiser', 'size', 'arctanh', 'transpose', 'copy', 'copyto', 'searchsorted', '__cached__', 'printoptions', 'histogram2d', 'array_split', 'msort', 'obj2sctype', 'nonzero', 'arccosh', '__doc__', 'polyfit', 'can_cast', 'rollaxis', 'floor_divide', 'nan_to_num', 'round_', 'vander', 'genfromtxt', 'float_power', 'matmul', 'amin', 'fastCopyAndTranspose', 'std', 'isfinite', 'shares_memory', 'real', 'hstack', 'arccos', 'tan', 'union1d', 'trapz', 'conj', 'disp', 'ipmt', 'left_shift', 'is_busday', 'any', 'geterr', 'bmat', 'block', 'argmax', 'greater', 'seterr', 'geterrcall', 'isrealobj', 'find_common_type', 'diag_indices_from', 'nanargmin', 'sqrt', 'nanstd', 'get_include', 'median', 'get_array_wrap', 'flipud', 'sctype2char', 'common_type', 'imag', 'nanmin', 'geterrobj', 'rate', 'where', 'logical_not', 'nanmedian', 'apply_over_axes', 'expand_dims', 'alltrue']
```
Apart from things like `__doc__` as far as I can tell all of these are just deprecation wrappers around numpy functions:
```
In [37]: scipy.alltrue([1])                                                                                                       
/Users/enojb/current/sympy/37venv/bin/isympy:1: DeprecationWarning: scipy.alltrue is deprecated and will be removed in SciPy 2.0.0, use numpy.alltrue instead
  #!/Users/enojb/current/sympy/37venv/bin/python
Out[37]: True
```

**Comment by asmeurer** [comment]
Does look like functions or classes other than `test` are actually unique

```
>>> nondeprecated = []
>>> for i in names_unequal:
...     doc = getattr(getattr(scipy, i), '__doc__')
...     if doc is not None and 'deprecated' not in doc:
...         nondeprecated.append(i)
>>> nondeprecated
['__all__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', 'fft', 'test']
```

(`numpy.fft` and `scipy.fft` are submodules)

**Comment by oscarbenjamin** [comment]
I'm not sure what's going on there but it looks like scipy.fft is especially deprecated:
https://github.com/scipy/scipy/blob/c0dc7fccc53d8a8569cde5d55673fca284bca191/scipy/__init__.py#L87

I'm going to merge this. There are clearly problems but I don't think that the behaviour in lambdify that is changed was previously well considered so I think our status in terms of "well-debugged" code is not changed by this.

**Pull request merged**
