### PR TITLE
gruntz: Porting changes back from diofant

### PR DESCRIPTION
**Pull request by Upabjojr**
I'm trying to use `git cherry-pick` to port some of diofant's changes back to SymPy.

Related PR:
https://github.com/diofant/diofant/pull/17

### CODE REVIEW

**Comment by asmeurer** [comment]
Why does this create sympy/tests?

**Comment by Upabjojr** [comment]
> Why does this create sympy/tests?

I've picked the wrong commits.

**Comment by skirpichev** [comment]
@Upabjojr, please mention (here and anywhere you do porting stuff) that these changes - from the diofant project, not just "@skirpichev 's changes" (for sure, I'm not doing any changes for SymPy).

**Comment by Upabjojr** [comment]
@skirpichev I've added a link to the cherry-picked PR in diofant.

**Comment by skirpichev** [comment]
Oh, that's fine, thank you.  If you can't add such link (or a number of links to PRs), please just add reference to the diofant repo.

**Pull request merged**
