### PR TITLE
Remove py.typed

### LINKED ISSUE #26150: pyright too slow to infer types from sympy functions
pyright takes more than 12 seconds to infer type informations on sympy codebase. Not even setting `useLibraryCodeForTypes` to `False` could prevent pyright from exploring sympy as the library claims to be a typed library by including a `py.typed` marker file. 

This means that using a project with sympy will make the editor extensions looking for type information return such in more than 10 seconds, killing completely the user experience.

See issue [pyright#7159](https://github.com/microsoft/pyright/issues/7159).

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

Fixes https://github.com/sympy/sympy/issues/26150

#### Brief description of what is fixed or changed

We had discussed about removing `py.typed` because it is not actually necessary for type checking, 
and it degrades performance for type checking for libraries with very few type coverage.
Although it can also disable some autocompletion features, which could be just working,
however, I wouldn't find it to give any useful information for users as well if the type coverage is poor.

However, because we are not frequently releasing, if users may need immediate changes, this may need hotfix for past releases as well.
I also want to check how users of mypy were not raising issues about performance anyway.
(Because I thought pyright was faster than mypy https://github.com/microsoft/pyright/blob/main/docs/mypy-comparison.md#design-goals)

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by zachetienne** [comment]
My sympy-based project NRPy (https://github.com/nrpy/nrpy) uses typehints extensively, and it seems removing py.typed just gave mypy a huge heads up that sympy no longer supports typehints. My CI, which checks `mypy --strict` across my entire codebase is now broken. What is the suggested workaround?

**Comment by oscarbenjamin** [comment]
> sympy no longer supports typehints

To be clear SymPy never supported type hints. Just adding a py.typed file without adding the actual type hints is not support for anything. It was a mistake to add it in gh-22337. Quoting from https://github.com/microsoft/pyright/issues/7159:

> I ran pyright --verifytypes sympy to determine the "type completeness" of the library. Most "py.typed" libraries are 50% or more "type complete". Sympy is currently just 6%. It really has no right to claim that it's a typed library.

If we want to add type hints then I have made a start in gh-25103. I think until SymPy can pass a basic check with pyright the py.typed file should not be there. I also think that we should ignore mypy and focus on pyright which is a much better type checker. Also pyright is a more useful target because it is used by editors etc which are the most likely consumers of the hints.

Presumably mypy has some options for this that you could use in CI. Personally I found that in code that used `mypy --strict` I ended up adding configuration to prevent mypy from looking at the sympy codebase essentially telling it to ignore the py.typed file.

**Comment by sylee957** [comment]
I'd like to see more specific log about how mypy --strict fails here, such that we can investigate if this can be fixed by changing your configuration or options.

**Comment by zachetienne** [comment]
@sylee957 : When py.typed is removed, mypy simply refuses to scan the code!
```
[nrpy directory[$ mypy --strict nrpy/reference_metric.py 
nrpy/reference_metric.py:12: error: Skipping analyzing "sympy": module is installed, but missing library stubs or py.typed marker  [import-untyped]
nrpy/reference_metric.py:12: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```
After spending such a long time adding mypy typehinting support to our codebase, it was quite jarring to see it removed.

@oscarbenjamin : Wow, I really appreciate your efforts. After refactoring our codebase (NRPy, https://github.com/nrpy/nrpy) to support typehints, I understand what you mean by sympy not supporting typehints -- our task to add typehints to NRPy was far from trivial. That said, even the very basic type hints currently inside sympy (for Expr, Basic, Symbol types) are potential lifesavers for large-ish codebases like NRPy, where being able to distinguish between Expr, List[Expr], etc., can be lifesavers. May I please request that py.typed be restored?

**Comment by sylee957** [comment]
https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker

You would likely need to do 
```
[mypy-sympy]
ignore_missing_imports = True
```

**Comment by zachetienne** [comment]
@sylee957 : Yes, I understand one could just force mypy to ignore sympy typehints. However, even though sympy's typehinting is very limited, _even limited typehinting takes care of a large majority of our use cases_.  

Bottom line: even a minimal amount of type hinting is valuable for improving code quality.

**Comment by zachetienne** [comment]
I may be confusing what mypy is actually using from SymPy when analyzing our code. It could be that mypy only infers _types_ from e.g., Expr, Symbol, Basic, etc. That said, removing `py.typed` makes it impossible for mypy to properly analyze any code's usage of these types. Sorry for any confusion.

**Comment by sylee957** [comment]
I still think that there are other workaround for this

> You might also be able to find type stub packages for the sympy library. If installed, they would override the sympy library itself. If you can't find an existing type stub package, you could attempt to create a partial set of stubs yourself.

We would also note that SymPy's type annotation is very experimental, so unfortunately, we would better guide you to workaround for user breaking changes from here, than reverting this change.
I'm open to hear other updates of information, if `py.typed` is really legal or is not very harmful in `mypy`. However, as far as we can tell, we had to do this because we had received the info from the experts.

**Comment by oscarbenjamin** [comment]
I haven't looked very hard but it does not look like there is an option to tell mypy to look at the sympy code when there is no py.typed file unless separate stub files are provided. With pyright it can be done with `--lib` I think. In general I would recommend using pyright over mypy although the current version does crash on the sympy codebase.

The fact that mypy works at all with the sympy codebase required many thousands of small changes only a few of which were fixes to actual bugs. It also only really "passes" because mypy is quite permissive about giving up on untyped code and mostly just fails to analyse the codebase. By contrast pyright which is stricter about wanting to actually infer the types either from hints or from static inference reports 40000 errors. It would be good to bring that number down and it does not really require 40000 type hints but rather a few well chosen ones for the most commonly used types and methods.

For now the only reason I want to keep mypy running in CI is to stop people from adding incorrect type hints (which is what was happening before).

I don't think that py.typed should be added back until there are some meaningful type hints in the sympy codebase. Passing basic checks under pyright seems like a reasonable baseline for this.

**Comment by zachetienne** [comment]
Thank you for your thoughtful reply, @oscarbenjamin. To be honest, I don't think we're using many, if any, type hints implemented in sympy. Rather, we make use of sympy types, like `Expr`, `Basic`, `Symbol`, etc. Without a `py.typed` file, mypy refuses to distinguish these types; setting

```
[mypy-sympy]
ignore_missing_imports = True
```

converts all the sympy types to `Any`, rendering mypy almost completely useless. 

I wonder if the original issue that led to the removal of py.typed could be circumvented using the above trick.

Regarding pyright, in my experience, it seems to be slower than mypy, even after I've cleared my mypy cache... and mypy is slow enough. :stuck_out_tongue: 

@sylee957 There are no typing stub packages for sympy. Truly `py.typed` is necessary for doing anything useful with mypy, which is the most popular type checker in Python, being downloaded 14x more often than pyright over the past month. (https://pypistats.org/packages/pyright ; https://pypistats.org/packages/mypy)

**Comment by oscarbenjamin** [comment]
> I don't think we're using many, if any, type hints implemented in sympy. Rather, we make use of sympy types, like `Expr`, `Basic`, `Symbol`

Type hints are needed for any type checker to understand these. If you look at gh-25103 you can see that its main purpose is essentially to add hints for `Expr.__new__` which is needed for a typechecker to understand what anything in SymPy does because `__new__` is what creates the expressions in the first place and the type of what it returns is not obvious in sympy. The other thing it adds is hints for things like `Expr.__add__` so that the type of `expr1 + expr2` can be inferred. Without understanding these a type checker is not going to be able to do much with any code that uses sympy. Also if you look through all of the methods of Basic and Expr you can see that they end up reaching almost the entire codebase.

> mypy is the most popular type checker in Python, being downloaded 14x more often than pyright over the past month.

It is unfortunate that mypy has this status because pyright is significantly better. Also the checker in pyright underpins pylance which is what is used in e.g. vscode. I am pretty sure that any type hints in SymPy would get far more use in editors like vscode than in downstream projects running mypy.

I think that the primary reason that pyright is slower than mypy is because it is actually checking the types properly rather than using strange heuristic rules as mypy does. I am not sure that it would be possible to get the sympy codebase to the point that both pyright and mypy would be happy with it simultaneously because sympy does many strange things and the two checkers often disagree about nontrivial situations. Note also that when they do disagree pyright's opinion is pretty much always the correct one.

> it prevents folks from using the most popular type checker for sympy type consistency _in their own code_

It does not prevent people from using mypy. It just means that mypy will have limited ability to make inference about any use of sympy. That is already the case anyway though: using mypy with sympy gives only a false notion of checking because mypy cannot understand the vast majority of sympy even if you restrict to "simple" types like Symbol. At least pyright has the decency to crash to show you that it cannot sensibly analyse this codebase!

Also it would be better if mypy had the option to ask it to look at the sympy codebase as pyright does. That is a reasonable feature request for mypy. The default position for now though should be that type checkers do not look at the sympy codebase because it does not have the type hints that would be needed for them to perform sensibly.

I would like to get to the point where sympy has enough type hints to be usable with type checkers but what is needed is the type hints. The py.typed file should only be added after there is reasonable coverage in terms of hints at least on commonly used public API.

**Comment by sylee957** [comment]
I think that we may need to discuss about contributing to ‘typeshed’ for example.
I agree on the point that Expr, Symbol is not very useful at the point now, because they are very ambiguously used, even for things like simplify, solve.

However, basic type stub for modules, for example, can still be robust and helpful for users who want to navigate through sympy codebase

I think that typeshed can be one place, however, I’m not sure if it is really like ‘definitelytyped’ for typescript, because it seems like having few 3rd party type definitions, and poor contribution guidelines about how to handle any non-maintainer of the typeshed project, but maintainers of SymPy, can edit the types, for instance.

**Comment by sylee957** [comment]
I still think that you can generate stubs, with mypy stubgen or pyright generate stubs, and try to maintain, or ship as 3rd party type stubs of sympy.
I think that they are almost identical to the existing behavior

**Comment by sylee957** [comment]
But may not suffer from the existing performance of pyright for instance, trying to scan the whole library code by itself.
I also wonder even if we have better type coverage of sympy, we may still better deploy stubs differently than the package.
For example, if pyright scans sympy codebase by itself, I’m worried if it can give errors when user has more strict settings.

**Comment by oscarbenjamin** [comment]
The pyright folks have a suggestion to add type stub files for sympy: https://github.com/microsoft/pyright/issues/7159#issuecomment-2010658540

I'm not sure whether they are suggesting adding that to pyright or that we should add it to sympy.

**Comment by oscarbenjamin** [comment]
The pyright folks have a suggestion to add type stub files for sympy: https://github.com/microsoft/pyright/issues/7159#issuecomment-2010658540

I'm not sure whether they are suggesting adding that to pyright or that we should add it to sympy.

**Comment by oscarbenjamin** [comment]
I think that the situation has improved a lot now and we could maybe add the py.typed file back. There are still many places where hints should be added but it is not like it crashes pyright any more and at least many basic things have working inference now.

**Comment by sylee957** [comment]
I was about to suggest that we need to check the performance of pyright though.
I had difficulty reviewing after pyright takes too long these days.
I'm not sure how it affects type checking performance from users,
but I hear the argument that type coverage for sympy should be greater than 80% threshold.
We may ignore test files or physics module though

**Comment by oscarbenjamin** [comment]
> For example, if pyright scans sympy codebase by itself, I’m worried if it can give errors when user has more strict settings.

This is more likely to be a problem for mypy users than pyright users. Generally pyright is pretty good about not complaining about code in other codebases. If you run pyright on the sympy codebase it reports 30,000 errors but if you run it on a script that imports and uses sympy it won't show any of them. With mypy it is very common that if you typecheck some code that uses sympy it will throw out random errors from the sympy codebase even though running mypy on the sympy codebase does not show any errors. I'm sure that @zachetienne has experienced this.

**Comment by oscarbenjamin** [comment]
> I had difficulty reviewing after pyright takes too long these days.

Running `pyright sympy` takes a very long time but you can do e.g.:
```
$ time pyright sympy/algebras/
...
  /stuff/current/active/sympy/sympy/algebras/tests/test_quaternion.py:426:37 - error: Argument of type "int" cannot be assigned to parameter "real_field" of type "bool" in function "__new__"
    "int" is not assignable to "bool" (reportArgumentType)
226 errors, 0 warnings, 0 informations 

real	0m13.595s
user	0m29.513s
sys	0m0.740s
```
So that takes only about 10 seconds. More importantly if you open some script that uses sympy in an editor it does not cause pyright to spend 10 minutes consuming all RAM and crashing like it used to. I am using pyright in the editor to identify places in the codebase where inference is not working or hints should be added. It takes about 10 seconds for pyright update after changing the code.

Here is a simple script that uses sympy:
```python
from sympy import *

a, b, c = symbols("a, b, c")
x, y, z = symbols("x, y, z", seq=True)
f = Function('f')

reveal_type(a)  # Any
reveal_type(x)  # Symbol
reveal_type(x+x) # Expr
reveal_type(2*x) # Expr
reveal_type(S(2)) # Integer
reveal_type(cos(2)) # Expr
reveal_type(x.as_coeff_Mul()) # tuple[Number, Expr]
reveal_type(x.evalf()) # Expr
reveal_type(x.subs(x, 1)) # Expr
reveal_type(Add(x, x)) # Expr
reveal_type(Or(x, y)) # Boolean
reveal_type(x | y) # Boolean
reveal_type(f) # type[AppliedUndef]
reveal_type(f(x)) # Expr
```
This is how long it takes with pyright:
```python
$ time pyright t.py 
WARNING: there is a new pyright version available (v1.1.388 -> v1.1.390).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`

/stuff/current/active/sympy/t.py
  /stuff/current/active/sympy/t.py:7:13 - information: Type of "a" is "Any"
  /stuff/current/active/sympy/t.py:8:13 - information: Type of "x" is "Symbol"
  /stuff/current/active/sympy/t.py:9:13 - information: Type of "x + x" is "Expr"
  /stuff/current/active/sympy/t.py:10:13 - information: Type of "2 * x" is "Expr"
  /stuff/current/active/sympy/t.py:11:13 - information: Type of "S(2)" is "Integer"
  /stuff/current/active/sympy/t.py:12:13 - information: Type of "cos(2)" is "Expr"
  /stuff/current/active/sympy/t.py:13:13 - information: Type of "x.as_coeff_Mul()" is "tuple[Number, Expr]"
  /stuff/current/active/sympy/t.py:14:13 - information: Type of "x.evalf()" is "Expr"
  /stuff/current/active/sympy/t.py:15:13 - information: Type of "x.subs(x, 1)" is "Expr"
  /stuff/current/active/sympy/t.py:16:13 - information: Type of "Add(x, x)" is "Expr"
  /stuff/current/active/sympy/t.py:17:13 - information: Type of "Or(x, y)" is "Boolean"
  /stuff/current/active/sympy/t.py:18:13 - information: Type of "x | y" is "Boolean"
  /stuff/current/active/sympy/t.py:19:13 - information: Type of "f" is "type[AppliedUndef]"
  /stuff/current/active/sympy/t.py:20:13 - information: Type of "f(x)" is "Expr"
0 errors, 0 warnings, 14 informations 

real	0m9.642s
user	0m19.478s
sys	0m0.695s
```
This is how long it takes with mypy:
```console
$ time mypy t.py 
t.py:7: note: Revealed type is "Any"
t.py:8: note: Revealed type is "sympy.core.symbol.Symbol"
t.py:9: note: Revealed type is "Any"
t.py:10: note: Revealed type is "Any"
t.py:11: note: Revealed type is "sympy.core.numbers.Integer"
t.py:12: note: Revealed type is "Any"
t.py:13: note: Revealed type is "tuple[sympy.core.numbers.Number, sympy.core.expr.Expr]"
t.py:14: note: Revealed type is "sympy.core.expr.Expr"
t.py:15: note: Revealed type is "sympy.core.expr.Expr"
t.py:16: note: Revealed type is "sympy.core.add.Add"
t.py:17: note: Revealed type is "sympy.logic.boolalg.Or"
t.py:18: note: Revealed type is "Any"
t.py:19: note: Revealed type is "Any"
t.py:20: note: Revealed type is "Any"
Success: no issues found in 1 source file

real	0m4.735s
user	0m4.382s
sys	0m0.352s
```
So it's 5 seconds for mypy and 10 seconds for pyright. Notice though that pyright has inferred all of things correctly (apart from `a`) whereas mypy has many things as `Any` or e.g. `Add` and `Or` which is incorrect. The fundamental problem is that mypy doesn't understand `__new__` (https://github.com/python/mypy/issues/15182). The reason that pyright gets the inference wrong for `a` is explained in gh-27354 (I use that branch here which shows that `seq=True` works with both mypy and pyright).

**Comment by aaron-skydio** [comment]
Just a note that like @zachetienne mentioned, [symforce](https://github.com/symforce-org/symforce) was getting some use out of sympy's incomplete type annotations before py.typed was removed.

On versions of mypy newer than 1.14, you can tell mypy you'd like it to use sympy's annotations by setting `follow_untyped_imports = true` for sympy.

**Comment by oscarbenjamin** [comment]
We should definitely add the py.typed file back now.

**Comment by oscarbenjamin** [comment]
I've opened gh-28716 to add the py.typed file back.

**Pull request merged**
