### PR TITLE
Remove `AppliedUndef.def _sage_`

### PR DESCRIPTION
**Pull request by infinity0**
This is required for newer versions of SageMath:

https://git.sagemath.org/sage.git/tree/build/pkgs/sympy/patches/01_undeffun_sage.patch?h=develop

### CODE REVIEW

**Comment by infinity0** [comment]
@kiwifb

**Comment by asmeurer** [comment]
This causes the sage tests to fail in Travis.

**Comment by infinity0** [comment]
Can you point us to the failures? I suppose some tests also need to be updated, but there is a green tick next to the commit ID up there so I don't know which ones.

**Comment by isuruf** [comment]
See, https://travis-ci.org/sympy/sympy/jobs/176361920
Tests are shown as green, because installing sage on travis-ci vms fail sometimes.

**Comment by asmeurer** [comment]
If you go to the Travis tests and scroll down it's in the allowed failures (I think the PPA fails sometimes or something like that). We need to check that they pass manually for this PR.

**Comment by infinity0** [comment]
Could someone help me with this? I clicked the link and it says "There was an error while trying to fetch the log.". Can we get travis to re-run it?

**Comment by isuruf** [comment]
Restarted the job

**Comment by isuruf** [comment]
Here's the failure
```
________________________________________________________________________________
__________ sympy/external/tests/test_sage.py:test_undefined_function ___________
  File "/home/travis/build/sympy/sympy/sympy/external/tests/test_sage.py", line 222, in test_undefined_function
    assert bool(sf(sx) == f(x)._sage_())
  File "sympy/core/function.py", line 749, in _sage_
    func = getattr(sage, fname)
AttributeError: 'module' object has no attribute 'f'
```

**Comment by asmeurer** [comment]
Sage tests are run with

```
sage -python bin/test sympy/external/tests/test_sage.py
```

**Comment by infinity0** [comment]
I'm on Sage 7.6 and all these tests pass for me. (I do have 2 xpass however, which still counts as a passed test overall). Travis is on Sage 7.5.

Since Sage 7.5 explicitly wants [sympy 1.0](https://git.sagemath.org/sage.git/tree/build/pkgs/sympy/package-version.txt?h=7.5) can we just ignore this travis failure and merge it?

**Comment by infinity0** [comment]
Scratch that, was on a branch without this commit. I can reproduce the failure on 7.6, I'll try to fix.

**Comment by asmeurer** [comment]
Well the whole point of the test is to make sure we don't break Sage integration in SymPy. So I'd rather not skip it. If we can install the latest version in Travis that would be best. I guess it uses [ppa:aims/sagemath](https://github.com/sympy/sympy/blob/1847ae962a20fbbb04808764830f95534f0de15c/.travis.yml#L286).

**Comment by infinity0** [comment]
I found this: https://trac.sagemath.org/ticket/20204 It sounds like perhaps there is an issue in sage and this commit was not supposed to be upstreamed. I'll poke the author (rws) about it.

**Comment by isuruf** [comment]
Yes, this is not the problem. the lines https://github.com/sagemath/sage/blob/master/src/sage/symbolic/expression_conversions.py#L763-L767 doesn't handle symbolic functions properly.

This PR avoids converting `sympy.core.function.AppliedUndef -> sage.symbolic.function_factory.NewSymbolicFunction` because there's no conversion from `sage.symbolic.function_factory.NewSymbolicFunction -> sympy.core.function.AppliedUndef`.

Seems to me, the fix is to add the conversion `sage.symbolic.function_factory.NewSymbolicFunction -> sympy.core.function.AppliedUndef`

cc @rwst

**Comment by rwst** [comment]
Please see #13476.

**Comment by czgdp1807** [comment]
Closing this PR due to inactivity. However, if there is a scope to complete this then please let us know. Thanks for your contributions.

**Comment by kiwifb** [comment]
The problem seems to be fixed in sympy 1.5+ somehow. So closing this is fine. Thank you.

**Pull request closed without merging**
