### PR TITLE
Staging a linear ODE system solver.

### PR DESCRIPTION
**Pull request by Krastanov**
Solve a system of ODEs with optional initial conditions.

Initial conditions are supplied as part of the list of equations. For the
moment the preprocessor for initial conditions is quite simple, thus take
care to insure that there are no free variables in the equations
corresponding to initial conditions.

```
>>> from sympy import ode_system, Symbol, Function
>>> func = Function('f')
>>> gunc = Function('g')
>>> x = Symbol('x')
>>> f = func(x)
>>> f_ = f.diff(x)
>>> f__ = f_.diff(x)
>>> g = gunc(x)
>>> g_ = g.diff(x)
>>> g__ = g_.diff(x)
```

Simple equation:

```
>>> sys = [f_+f]
>>> sol = ode_system(sys, [f], x)
>>> sol[f]
C1*exp(-x)
```

With initial conditions:

```
>>> sys = [f_+f, func(0)-2]
>>> sol = ode_system(sys, [f], x)
>>> sol[f]
2*exp(-x)
```

With "boundary" conditions:

```
>>> sys = [f_+f, func(2)-3]
>>> sol = ode_system(sys, [f], x)
>>> sol[f]
3*exp(2)*exp(-x)
```

Second order system:

```
>>> sys = [f__+f]
>>> sol = ode_system(sys, [f], x)
>>> sol[f]
I*C1*exp(-I*x) - I*C2*exp(I*x)
```

Due to deficiencies in `Derivative` you must jump through hoops to get
initials conditions working here:

```
>>> sys = [g-f_, f+g_] # The same as [f__+f] just substitute g_ = f__
>>> sol = ode_system(sys, [f, g], x)
>>> sol[f]
I*C1*exp(-I*x) - I*C2*exp(I*x)
```

Adding the initial conditions:

```
>>> sys = [g-f_, f+g_, func(0)-1, gunc(0)]
>>> sol = ode_system(sys, [f, g], x)
>>> sol[f]
exp(I*x)/2 + exp(-I*x)/2
```

### CODE REVIEW

**Comment by iScienceLuvr** [comment]
What is the status of this? Has this been merged with desolve? What is happening? Is there a version of sympy with a working dsolve for system of equations?

**Comment by cbm755** [comment]
@iScienceLuvr I'm half-heartedly working on a matrix exponential of Jordan form solver in #9235.  The current dsolve systems code is seriously broken.

Others---esp. @Krastanov---sorry didn't realize there was previous work on this.

**Comment by czgdp1807** [comment]
@Krastanov Is this PR still needed? IMO, current master is having an ODE solver. Please let me know about the updates.

**Comment by oscarbenjamin** [comment]
There is now code for solving ODE systems. It is a bit of a mess and needs a lot of work but at this stage I don't think this PR would help. There might be some bits here that are still useful but most of this PR is not needed any more.

Thanks for the work @Krastanov. I'm going to close this. If you (or anyone else) wants to improve the ODE systems solvers then it would be better to start from current master.

**Pull request closed without merging**
