### PR TITLE
Fix Sphinx docs build

### LINKED ISSUE #11930: Sphinx build failure in Travis
All sphinx builds have failed in Travis after docutils was updated to version 0.13.1. It looks like there is a bug in the new _html_base.py, most likely in image handling. This is a part of how the old doctools did translate lin_pend_nonmin_example.rst:
```
<div align="center" class="align-center"><img src="../../../../_images/pendulum_
nonmin.svg" /></div>
<p>The system will be modeled using both Kane&#8217;s and Lagrange&#8217;s metho
ds, and the
```
while this comes from 0.13.1:
```
<div align="center" class="align-center"> <img src="../../../../_images/pendulu
m_nonmin.svg" /> <p> The system will be modeled using both Kane&#8217;s and Lagr
ange&#8217;s methods, and the
```
Until that is fixed, we should probably arrange to load version 0.12 before sphinx is loaded.

### PR DESCRIPTION
**Pull request by asmeurer**
Build the docs on Travis with docutils 0.12

0.13.1 has a bug that prevents the build from working.

Fixes #11930.

### CODE REVIEW

**Comment by asmeurer** [comment]
I also pushed a fix to make the doctr build not run if the docs fail.

**Comment by asmeurer** [comment]
Actually, not 100% sure that fix works. I pushed a test branch to see. If it worked, doctr shouldn't try to deploy at https://travis-ci.org/asmeurer/sympy/jobs/183383906

**Comment by asmeurer** [comment]
That didn't work (it didn't fail at all!). Let's try this https://travis-ci.org/asmeurer/sympy/jobs/183464854 (should fail, and doctr not run at the end).

**Comment by jksuom** [comment]
I suppose this should be merged?

**Comment by jksuom** [comment]
This seems to be working as expected. Merging.

**Pull request merged**
