### PR TITLE
Fix issues with ImageSet creation

### LINKED ISSUE #18050: imageset broken for complex numbers
With current master:
```
In [4]: imageset(Lambda(n, 1 + I*n), Integers)
Out[4]: {ⅈ⋅n | n ∊ ℤ}
```
The `1` (or any other value) is simply dropped.

### PR DESCRIPTION
**Pull request by gschintgen**
#### References to other Issues or PRs

Fixes #18050

#### Brief description of what is fixed or changed
Some fixes for `ImageSets` with a linear map `a*n+b` as lambda function. When creating an `ImageSet` (either via `imageset` or `ImageSet.doit()`), linear maps are canonicalized in the sense that .e.g `Lambda(n, 2*n+7)` is reduced to `Lambda(n, 2*n + 1)`. The current code in master has some issues when dealing with complex numbers.

The relevant code is actually in `SetExpr._eval_func()`, so this PR modifies it
- to correct a check that should only apply to real `a` with abs=1,
- to correct reduction modulo `a` in `a*n+b`,
- to add reduction modulo `a` for pure imaginary `a`.

It also
- fixes a wrong `imageset` test and adds some new ones,
- adds specific tests for `SetExpr(Integers)`.

#### Release Notes

* sets
  * `SetExpr._eval_func()` is fixed so that `ImageSets` with linear maps involving complex numbers are now instantiated correctly.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Presumably the change here affects `SetExpr` in some way. Can there be a test for that?

**Comment by gschintgen** [comment]
> 
> 
> Presumably the change here affects `SetExpr` in some way. Can there be a test for that?

I'm not sure I'm following. What kind of test(s) do you have in mind? I'll gladly add them.

**Comment by oscarbenjamin** [comment]
I think that `ImageSet` delegates this task to `SetExpr`:
https://github.com/sympy/sympy/blob/7501960ea18912f9055a32be50bda30805fc0c95/sympy/sets/fancysets.py#L493
So if I understand correctly your fix here is really a fix to `SetExpr` that indirectly fixes `ImageSet`.
```julia
In [11]: from sympy.sets.setexpr import SetExpr                                                                                   

In [12]: SetExpr(Integers)                                                                                                        
Out[12]: SetExpr(ℤ)

In [13]: 2*SetExpr(Integers)                                                                                                      
Out[13]: SetExpr({2⋅d | d ∊ ℤ})

In [14]: I*SetExpr(Integers)                                                                                                      
Out[14]: SetExpr({d⋅ⅈ | d ∊ ℤ})

In [15]: 1+I*SetExpr(Integers)                                                                                                    
Out[15]: SetExpr({x + 1 | x ∊ {d⋅ⅈ | d ∊ ℤ}})

In [16]: SetExpr(Integers)._eval_func(Lambda(n, 1+I*n))                                                                           
Out[16]: SetExpr({ⅈ⋅n | n ∊ ℤ})
```

**Comment by gschintgen** [comment]
> I think that `ImageSet` delegates this task to `SetExpr`:
> 
> https://github.com/sympy/sympy/blob/7501960ea18912f9055a32be50bda30805fc0c95/sympy/sets/fancysets.py#L493
> 
> So if I understand correctly your fix here is really a fix to `SetExpr` that indirectly fixes `ImageSet`.

Ah, thanks. I'll add some tests and also reword the OP and release notes a bit.

**Comment by oscarbenjamin** [comment]
Looks good but I'll wait for Travis to sort itself out before merging

**Pull request merged**
