### PR TITLE
Revert "Handling Float Integrals"

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

Reverts sympy/sympy#18434

#### Brief description of what is fixed or changed

There were some problems that the performance got regressed after merging.
I've also reopened #17119 and #14431.
This should be reverted until the next release.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This is a release blocker

**Comment by sylee957** [comment]
I bisected that the #18623 is causing the test failing of `test_issue_11542` and making the original commit not revertible

**Comment by sylee957** [comment]
Another problem I find is that sqf_list is returning wrong result for polynomial with floating points.
```
from sympy import *

t = Symbol('t')
p = Poly([-0.000170138888888889, 0.0816666666666667, -9.8], t, domain='RR')
p.sqf_list()
```

**Comment by oscarbenjamin** [comment]
The Integral that fails is
```
Integral(-0.00416666666666667*_y/(0.00208333333333333*_y**2 - 9.8), _y)
```
That Integral also failed in sympy-1.5.1 and only passes now on master because of #18434 (reverted here).

The difference for `dsolve` is that in 1.5.1 instead this integral is computed:
```
Integral(-0.4*_y/(0.2*_y**2 - 940.8), _y)
```

That change comes about because here
https://github.com/sympy/sympy/blob/c2554ab3f3efb5d0bd6ae9603b7bd9bdc0f18477/sympy/solvers/ode/single.py#L681-L683
The equation `eq` is transformed from
```
(Pdb) p eq
-0.2*v(t)**2 - 96.0*Derivative(v(t), t) + 940.8
```
to this
```
(Pdb) p self.eqs
[0.00208333333333333*v(t)**2 + Derivative(v(t), t) - 9.8]
```
Essentially the equation has been divided by 96.0 but that's enough to make the resulting integral fail.

**Comment by oscarbenjamin** [comment]
This looks good. Thanks

**Pull request merged**
