### PR TITLE
update latex.py for series expansion neglection order

### PR DESCRIPTION
**Pull request by mnmt**
As explained in https://github.com/sympy/sympy/issues/10836, separation needed between \rightarrow and its following symbols(s) for series expansion terms, so that (x --> x0) has correct latex generated

### CODE REVIEW

**Comment by leosartaj** [comment]
This does appear to solve the problem. +1 to merge, if tests pass.

**Comment by jksuom** [comment]
I have also seen empty braces ``{}`` used to mark the end of a keyword in LaTeX code

**Comment by leosartaj** [comment]
You should also add a test case referring to the change.

**Comment by mnmt** [comment]
Seems that https://github.com/skirpichev/omg/commit/7d2da575f715a5d827fee92363ce0eba754ed200 has done this already: since I'm an ametuer to github I'm not sure what I should do wrt closing this.

**Comment by asmeurer** [comment]
There are some tests that need to be fixed (run `./bin/test print`). 

Is `{}` or a space better?

**Comment by mnmt** [comment]
The share latex docs have a space it seems
https://www.sharelatex.com/learn/Operators

**Comment by leosartaj** [comment]
Maybe you could also add a test-case, where you actually found this bug.

**Comment by leosartaj** [comment]
On second though, the current test-cases look sufficient. Merging as is. Thanks! @mnmt

**Comment by mnmt** [comment]
Sorry for the repeated silly commits @leosartaj . Each time I ran `./bin/test print` in my local git repo it passed; I didn't initially realise it was testing the installed site-packages code rather than the modified git repository code.

Definitely a naive question, but would doing something like context.py thing be sensible to prevent that ?
http://docs.python-guide.org/en/latest/writing/structure/#test-suite

(Plus I ought to have read ["Introduction to contributing"](https://github.com/sympy/sympy/wiki/Introduction-to-contributing) earlier on, but I didn't since I thought it was a one character fix, not knowing about tests :P)

**Comment by leosartaj** [comment]
For development purposes, I generally make a new conda environment. It's always easy to start with a clean environment and gradually installing the packages you need. You can install SymPy for development, by running ``python setup.py develop``.

> Definitely a naive question, but would doing something like context.py thing be sensible to prevent that ?
http://docs.python-guide.org/en/latest/writing/structure/#test-suite

I am not a big fan of changing ``sys.path``.

**Pull request merged**
