### PR TITLE
Added Sympy Banner to README.md

### PR DESCRIPTION
**Pull request by ghost**
## Brief description of what is fixed or changed

Witnessing many repositories of reputed organizations, I realized that `README.md` for sympy was lacking a banner. So I designed a custom elementary banner for **sympy**.  We all are well aware of the relevance of `README.md` for any project and thus adding a banner highlights the main functionality of the library in comparison to the normal text which would definitely not be eyecatching.

#### Other comments

I wish to be a part of the contributor's list for **sympy** organization and aspire to deliver my knowledge and experience in elevating the organization to newer levels. As a tyro, I would like to make my first contribution to **sympy** with this banner.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I think that the banner looks nice. The resulting README can be seen here:
https://github.com/akshatsood2249/sympy/tree/sympy-banner

Does anyone else have any views on this?

What's the silver thing in the corner of the banner?

**Comment by moorepants** [comment]
I think it looks nice too. It would be helpful if an SVG was provided so that it could be edited in the future if need be. Or some non-bitmap editable source. @akshatsood2249 Do you have a source file?

**Comment by akshatsood2249** [comment]
It is quite encouraging that @oscarbenjamin  and @moorepants  found my design interesting. I used Canva to design it and here is the shareable [link](https://www.canva.com/design/DAEMVax9nDo/share/preview?token=dDaPZV4wh3e1v_hzMpzH0g&role=EDITOR&utm_content=DAEMVax9nDo&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton)  allowing anyone in the community to edit it for free.

**Comment by moorepants** [comment]
I'm guessing that Canva may not allow an export of an open and editable file type. We can just go with the PNG. It just means if anyone ever wants to change it, it'll likely be from scratch.

**Comment by akshatsood2249** [comment]
Oh well , I have already added banner in `png` format in my branch, people can access it from there

**Comment by akshatsood2249** [comment]
@oscarbenjamin and @moorepants  kindly suggest any sort of changes you would like to reflect on the banner, I will then upload an updated version of the same to be reviewed by the community

**Comment by moorepants** [comment]
I don't have any comments on the design of the banner. The official SymPy logo is in SVG format in the repository. The (easily) editable file is stored in the git repository for longevity and tracking. Anyone can open that file with open source tools to make edits. The PNGs of the logo are generated from that SVG source. If you can make an editable non-bitmap source file for this banner and check it into the library, that is ideal. But if that isn't really possible because the software you use to design the logo doesn't support that, then it's probably fine to just merge in this PNG.

**Comment by oscarbenjamin** [comment]
It looks like you can export as a PDF and then open it in inkscape to convert to SVG. I would probably just make it in inkscape in the first place though.

**Comment by akshatsood2249** [comment]
Well that looks more like an optimal approach ... I have committed pdf as well so that  community can use the same in inkspace for editing.

**Comment by oscarbenjamin** [comment]
I was just suggesting export as PDF so that you could get it out in a vectorised format to edit in inkscape. It would be better to commit as an inkscape-SVG as that's a text format. Does the banner work if it's an SVG file?

**Comment by akshatsood2249** [comment]
Have added the `.svg` file and its working well

**Comment by oscarbenjamin** [comment]
I think the README still references the png rather than the svg.

**Comment by asmeurer** [comment]
I agree just having a SVG would be best. That would also take up less space in the repo history.

**Comment by akshatsood2249** [comment]
Oh really sorry about that ... I forgot to update the README , do you want me to delete .png file as well ?

**Comment by oscarbenjamin** [comment]
The png file will need to be deleted. Also the commits will have to be squashed so that there are not commits adding files that are then removed. The easiest way to do that is just to open a new PR with the final result when we are happy with it.

Having opened the file in inkscape I see that the silver thing in the corner of the banner is actually part of an image of a house. Where does that image come from and is there any copyright on it?

**Comment by akshatsood2249** [comment]
Well, I wasn't aware of the house thing as in the original banner it shows only a cropped part which looks like some sort of pattern. 
I took the pattern from Canva itself. 
If you want I can design a pattern using illustrator or remove the existing one (just keep it blank i.e. white background).

**Comment by oscarbenjamin** [comment]
I don't think we can use any content from Canva. The terms of use are here:
https://about.canva.com/terms-of-use/

They say:
```
6. Our Proprietary Rights
Except for your User Content, the Service and all materials therein or transferred
thereby, including, without limitation, software, images, text, graphics, illustrations,
logos, patents, trademarks, service marks, copyrights, photographs, audio, videos,
music, User Content belonging to other Users, and Stock Media belonging to other
Users (the “Canva Content”), and all Intellectual Property Rights related thereto, are
the exclusive property of Canva and its licensors (including other Users who post
User Content or contribute Stock Media (as defined below) to the Service). Except
as explicitly provided herein, nothing in this Agreement shall be deemed to create a
license in or under any such Intellectual Property Rights, and you agree not to sell,
license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly
perform, publish, adapt, edit or create derivative works from any Canva Content. Use
of the Canva Content for any purpose not expressly permitted by this Agreement is
strictly prohibited.
```

I'm not sure exactly whether that covers the banner you have created but I think it is best to steer well clear of Canva for this because we need to be sure about copyright and IP in sympy.

Can you use inkscape to create a similar banner as SVG without using anything from Canva?

**Comment by akshatsood2249** [comment]
Yeah sure ... I will soon get back to you with another banner

**Comment by akshatsood2249** [comment]
@oscarbenjamin kindly take a look, I have now designed it using inkspace. Would welcome any sort of suggestions

**Comment by oscarbenjamin** [comment]
I think it looks good and I've checked that it can be edited in inkscape.

We don't want to have commits that add and remove files though so can you open a new PR and add the SVG and change the README in a single commit?

The commit message can be "docs: add a banner image for the README"

**Comment by akshatsood2249** [comment]
Yeah sure !!!

**Comment by oscarbenjamin** [comment]
This is continued in #20398

**Pull request closed without merging**
