### PR TITLE
add test for has

### LINKED ISSUE #5190: has() might need wild flag
I got an unexpected result from has():
```
h[1] >>> w=Wild('w')
h[1] >>> S(1).has(w)
True
```
I know this is because it allows for matching. Perhaps has should have a flag to disallow pattern matching. Possibilities include:

wild=False
literal=True
exact=True

Original issue for #5190: http://code.google.com/p/sympy/issues/detail?id=2091
Original author: https://code.google.com/u/117933771799683895267/
Original owner: https://code.google.com/u/117933771799683895267/

### PR DESCRIPTION
**Pull request by bobby-palmer**
#### References to other Issues or PRs

fixes #5190 

#### Brief description of what is fixed or changed
Add a test that has doesn't pattern match for Wild objects ie:
```
>>> S(1).has(Wild)
False
```
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by wermos** [comment]
It looks like this PR has a merge conflict. If you fix the merge conflict, then I think the PR will be automerged.

**Comment by bobby-palmer** [comment]
@faze-geek Im not familiar with this auto merge system. Will this PR eventually get closed automatically or is it still waiting for the test to pass?

**Comment by faze-geek** [comment]
> @faze-geek  Will this PR eventually get closed automatically or is it still waiting for the test to pass?

As soon as you resolve the merge conflict. It will be merged.

**Comment by bobby-palmer** [comment]
While this was still open with a merge conflict, the commit had already been pushed to master. then when I tried to sync my fork it somehow closed the PR. is this normal?

**Pull request closed without merging**
