### PR TITLE
[WIP] Fixed TypeError when using subs with OR

### LINKED ISSUE #16627: TypeError on Or.subs()
Hi,

I'm trying to substitute variables in a Boolean expression but it raises a `TypeError`. I have this error both in 1.3 and 1.4 version of Sympy.

Thanks for your help!
Franck

```python
In [1]: import sympy                                                            

In [2]: e = sympy.Symbol("spam") | sympy.Symbol("foo")                          

In [3]: e.subs("foo", "bar", simultaneous=True)                                 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     93                 try:
---> 94                     retval = cfunc(*args, **kwargs)
     95                 except TypeError:

~/.local/lib/python3.6/site-packages/sympy/core/basic.py in _subs(self, old, new, **hints)
   1110         if rv is None:
-> 1111             rv = fallback(self, old, new)
   1112         return rv

~/.local/lib/python3.6/site-packages/sympy/core/basic.py in fallback(self, old, new)
   1087             if hit:
-> 1088                 rv = self.func(*args)
   1089                 hack2 = hints.get('hack2', False)

~/.local/lib/python3.6/site-packages/sympy/core/operations.py in __new__(cls, *args, **options)
    412             # without having to sympify all values
--> 413             _args = frozenset(cls._new_args_filter(args))
    414         except ShortCircuit:

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in _new_args_filter(cls, args)
    774         rel = []
--> 775         args = BooleanFunction.binary_check_and_simplify(*args)
    776         for x in args:

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in binary_check_and_simplify(self, *args)
    449         from sympy.core.relational import Relational, Eq, Ne
--> 450         args = [as_Boolean(i) for i in args]
    451         bin = set().union(*[i.binary_symbols for i in args])

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in <listcomp>(.0)
    449         from sympy.core.relational import Relational, Eq, Ne
--> 450         args = [as_Boolean(i) for i in args]
    451         bin = set().union(*[i.binary_symbols for i in args])

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in as_Boolean(e)
     52         return e
---> 53     raise TypeError('expecting bool or Boolean, not `%s`.' % e)
     54 

TypeError: expecting bool or Boolean, not `_Dummy_19*_Dummy_20`.

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-3-a3f29c4f1997> in <module>
----> 1 e.subs("foo", "bar", simultaneous=True)

~/.local/lib/python3.6/site-packages/sympy/core/basic.py in subs(self, *args, **kwargs)
    986                 # in things like Derivative(f(x, y), x) in which x
    987                 # is both free and bound
--> 988                 rv = rv._subs(old, d*m, **kwargs)
    989                 if not isinstance(rv, Basic):
    990                     break

~/.local/lib/python3.6/site-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     94                     retval = cfunc(*args, **kwargs)
     95                 except TypeError:
---> 96                     retval = func(*args, **kwargs)
     97                 return retval
     98 

~/.local/lib/python3.6/site-packages/sympy/core/basic.py in _subs(self, old, new, **hints)
   1109         rv = self._eval_subs(old, new)
   1110         if rv is None:
-> 1111             rv = fallback(self, old, new)
   1112         return rv
   1113 

~/.local/lib/python3.6/site-packages/sympy/core/basic.py in fallback(self, old, new)
   1086                     args[i] = arg
   1087             if hit:
-> 1088                 rv = self.func(*args)
   1089                 hack2 = hints.get('hack2', False)
   1090                 if hack2 and self.is_Mul and not rv.is_Mul:  # 2-arg hack

~/.local/lib/python3.6/site-packages/sympy/core/operations.py in __new__(cls, *args, **options)
    411             # is done so short-circuiting can be done
    412             # without having to sympify all values
--> 413             _args = frozenset(cls._new_args_filter(args))
    414         except ShortCircuit:
    415             return sympify(cls.zero)

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in _new_args_filter(cls, args)
    773         newargs = []
    774         rel = []
--> 775         args = BooleanFunction.binary_check_and_simplify(*args)
    776         for x in args:
    777             if x.is_Relational:

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in binary_check_and_simplify(self, *args)
    448     def binary_check_and_simplify(self, *args):
    449         from sympy.core.relational import Relational, Eq, Ne
--> 450         args = [as_Boolean(i) for i in args]
    451         bin = set().union(*[i.binary_symbols for i in args])
    452         rel = set().union(*[i.atoms(Relational) for i in args])

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in <listcomp>(.0)
    448     def binary_check_and_simplify(self, *args):
    449         from sympy.core.relational import Relational, Eq, Ne
--> 450         args = [as_Boolean(i) for i in args]
    451         bin = set().union(*[i.binary_symbols for i in args])
    452         rel = set().union(*[i.atoms(Relational) for i in args])

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in as_Boolean(e)
     51     if isinstance(e, Boolean):
     52         return e
---> 53     raise TypeError('expecting bool or Boolean, not `%s`.' % e)
     54 
     55 

TypeError: expecting bool or Boolean, not `_Dummy_19*_Dummy_20`.
```

### PR DESCRIPTION
**Pull request by Sc0rpi0n101**
#### References to other Issues or PRs

Fixes #16627

#### Brief description of what is fixed or changed
* Removed m from subs() in basic.py
* Added tests for the change
* Commented out faulty tests in test_ode

#### Other comments
3 Tests in test_ode were throwing exceptions after removal of m and passed successfully when m was reintroduced.
I want to find the reason for that and fix that before merging so we don't have any problems like that in the future due to the change.
The test reports are:

```python
__________________________________________________________________________________________________
_______________________ sympy/solvers/tests/test_ode.py:test_classify_ode ________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/tests/test_ode.py", line 764, in test_classify_ode
    assert classify_ode(f(x).diff(x)**2, f(x)) == (
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/ode.py", line 1368, in classify_ode
    r = _nth_algebraic_match(reduced_eq, func)
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/ode.py", line 4135, in _nth_algebraic_match
    solns = solve(subs_eqn, func)
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/solvers.py", line 1171, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/solvers.py", line 1759, in _solve
    result = [r for r in result if
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/solvers.py", line 1760, in <listcomp>
    checksol(f_num, {symbol: r}, **flags) is not False]
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/solvers.py", line 290, in checksol
    if not val.is_constant(*list(sol.keys()), simplify=not minimal):
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/power.py", line 1654, in is_constant
    bz = b.equals(0)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 704, in equals
    constant = diff.is_constant(simplify=False, failing_number=True)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 620, in is_constant
    simultaneous=True)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 991, in subs
    return rv.xreplace(reps)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1180, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1195, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1195, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1202, in _xreplace
    return self.func(*args), True
  File "/home/sc0rpi0n101/Github/sympy/sympy/integrals/integrals.py", line 80, in __new__
    obj = AddWithLimits.__new__(cls, function, *symbols, **assumptions)
  File "/home/sc0rpi0n101/Github/sympy/sympy/concrete/expr_with_limits.py", line 356, in __new__
    pre = _common_new(cls, function, *symbols, **assumptions)
  File "/home/sc0rpi0n101/Github/sympy/sympy/concrete/expr_with_limits.py", line 38, in _common_new
    limits, orientation = _process_limits(*symbols)
  File "/home/sc0rpi0n101/Github/sympy/sympy/concrete/expr_with_limits.py", line 123, in _process_limits
    raise ValueError('Invalid limits given: %s' % str(symbols))
ValueError: Invalid limits given: ((0,),)
__________________________________________________________________________________________________
_______________________ sympy/solvers/tests/test_ode.py:test_Liouville_ODE _______________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/tests/test_ode.py", line 2317, in test_Liouville_ODE
    assert checkodesol(eq1a, sol1a, order=2, solve_for_func=False)[0]
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/ode.py", line 2509, in checkodesol
    ode_or_bool = simplify(ode_or_bool)
  File "/home/sc0rpi0n101/Github/sympy/sympy/simplify/simplify.py", line 518, in simplify
    return _eval_simplify(ratio=ratio, measure=measure, rational=rational, inverse=inverse)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/relational.py", line 527, in _eval_simplify
    ratio, measure, rational, inverse)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/relational.py", line 293, in _eval_simplify
    elif dif.equals(0):  # XXX this is expensive
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 704, in equals
    constant = diff.is_constant(simplify=False, failing_number=True)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 620, in is_constant
    simultaneous=True)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 991, in subs
    return rv.xreplace(reps)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1180, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1195, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1195, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1202, in _xreplace
    return self.func(*args), True
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/function.py", line 1287, in __new__
    __)))
ValueError: 
Can't calculate derivative wrt 0.
__________________________________________________________________________________________________
___________________ sympy/solvers/tests/test_ode.py:test_nth_algebraic_noprep2 ___________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/tests/test_ode.py", line 3381, in test_nth_algebraic_noprep2
    assert checkodesol(eqn, sol, order=2, solve_for_func=False)[0]
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/ode.py", line 2509, in checkodesol
    ode_or_bool = simplify(ode_or_bool)
  File "/home/sc0rpi0n101/Github/sympy/sympy/simplify/simplify.py", line 518, in simplify
    return _eval_simplify(ratio=ratio, measure=measure, rational=rational, inverse=inverse)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/relational.py", line 527, in _eval_simplify
    ratio, measure, rational, inverse)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/relational.py", line 293, in _eval_simplify
    elif dif.equals(0):  # XXX this is expensive
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 704, in equals
    constant = diff.is_constant(simplify=False, failing_number=True)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 620, in is_constant
    simultaneous=True)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 991, in subs
    return rv.xreplace(reps)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1180, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1195, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1195, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1202, in _xreplace
    return self.func(*args), True
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/function.py", line 1287, in __new__
    __)))
ValueError: 
Can't calculate derivative wrt 0.
```

#### Release Notes

* core
   * Removed use of m when processing subs using a dummy variable

### CODE REVIEW

**Comment by Sc0rpi0n101** [comment]
There seems to be a problem for `classify_ode(f(x).diff(x)**n, f(x))` when n>1 
```python
>>> classify_ode(f(x).diff(x), f(x))
('nth_algebraic', 'separable', '1st_linear', '1st_homogeneous_coeff_best', '1st_homogeneous_coeff_subs_indep_div_dep', '1st_homogeneous_coeff_subs_dep_div_indep', '1st_power_series', 'lie_group', 'nth_linear_constant_coeff_homogeneous', 'nth_linear_euler_eq_homogeneous', 'nth_algebraic_Integral', 'separable_Integral', '1st_linear_Integral', '1st_homogeneous_coeff_subs_indep_div_dep_Integral', '1st_homogeneous_coeff_subs_dep_div_indep_Integral')
>>> classify_ode(f(x).diff(x)**3, f(x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/ode.py", line 1368, in classify_ode
    r = _nth_algebraic_match(reduced_eq, func)
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/ode.py", line 4135, in _nth_algebraic_match
    solns = solve(subs_eqn, func)
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/solvers.py", line 1171, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/solvers.py", line 1759, in _solve
    result = [r for r in result if
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/solvers.py", line 1760, in <listcomp>
    checksol(f_num, {symbol: r}, **flags) is not False]
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/solvers.py", line 290, in checksol
    if not val.is_constant(*list(sol.keys()), simplify=not minimal):
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/power.py", line 1654, in is_constant
    bz = b.equals(0)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 704, in equals
    constant = diff.is_constant(simplify=False, failing_number=True)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 620, in is_constant
    simultaneous=True)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 991, in subs
    return rv.xreplace(reps)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1180, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1195, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1195, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1202, in _xreplace
    return self.func(*args), True
  File "/home/sc0rpi0n101/Github/sympy/sympy/integrals/integrals.py", line 80, in __new__
    obj = AddWithLimits.__new__(cls, function, *symbols, **assumptions)
  File "/home/sc0rpi0n101/Github/sympy/sympy/concrete/expr_with_limits.py", line 356, in __new__
    pre = _common_new(cls, function, *symbols, **assumptions)
  File "/home/sc0rpi0n101/Github/sympy/sympy/concrete/expr_with_limits.py", line 38, in _common_new
    limits, orientation = _process_limits(*symbols)
  File "/home/sc0rpi0n101/Github/sympy/sympy/concrete/expr_with_limits.py", line 123, in _process_limits
    raise ValueError('Invalid limits given: %s' % str(symbols))
ValueError: Invalid limits given: ((0,),)
>>> classify_ode(f(x).diff(x)**2, f(x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/ode.py", line 1368, in classify_ode
    r = _nth_algebraic_match(reduced_eq, func)
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/ode.py", line 4135, in _nth_algebraic_match
    solns = solve(subs_eqn, func)
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/solvers.py", line 1171, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/solvers.py", line 1759, in _solve
    result = [r for r in result if
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/solvers.py", line 1760, in <listcomp>
    checksol(f_num, {symbol: r}, **flags) is not False]
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/solvers.py", line 290, in checksol
    if not val.is_constant(*list(sol.keys()), simplify=not minimal):
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/power.py", line 1654, in is_constant
    bz = b.equals(0)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 704, in equals
    constant = diff.is_constant(simplify=False, failing_number=True)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 620, in is_constant
    simultaneous=True)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 991, in subs
    return rv.xreplace(reps)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1180, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1195, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1195, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1202, in _xreplace
    return self.func(*args), True
  File "/home/sc0rpi0n101/Github/sympy/sympy/integrals/integrals.py", line 80, in __new__
    obj = AddWithLimits.__new__(cls, function, *symbols, **assumptions)
  File "/home/sc0rpi0n101/Github/sympy/sympy/concrete/expr_with_limits.py", line 356, in __new__
    pre = _common_new(cls, function, *symbols, **assumptions)
  File "/home/sc0rpi0n101/Github/sympy/sympy/concrete/expr_with_limits.py", line 38, in _common_new
    limits, orientation = _process_limits(*symbols)
  File "/home/sc0rpi0n101/Github/sympy/sympy/concrete/expr_with_limits.py", line 123, in _process_limits
    raise ValueError('Invalid limits given: %s' % str(symbols))
ValueError: Invalid limits given: ((0,),)
```

For the rest of the two errors, I checked with dsolve that the solution is correct but checkdesol throws exception

```python
>>> eqn = Eq(Derivative(x*Derivative(f(x), x), x)/x, exp(x))
>>> sol = Eq(f(x), C1 + C2*log(x) + exp(x) - Ei(x))
>>> dsolve(eqn,f(x))
Eq(f(x), C1 + C2*log(x) + exp(x) - Ei(x))
>>> checkodesol(eqn, sol, solve_for_func=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sc0rpi0n101/Github/sympy/sympy/solvers/ode.py", line 2509, in checkodesol
    ode_or_bool = simplify(ode_or_bool)
  File "/home/sc0rpi0n101/Github/sympy/sympy/simplify/simplify.py", line 518, in simplify
    return _eval_simplify(ratio=ratio, measure=measure, rational=rational, inverse=inverse)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/relational.py", line 527, in _eval_simplify
    ratio, measure, rational, inverse)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/relational.py", line 293, in _eval_simplify
    elif dif.equals(0):  # XXX this is expensive
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 704, in equals
    constant = diff.is_constant(simplify=False, failing_number=True)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 620, in is_constant
    simultaneous=True)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 991, in subs
    return rv.xreplace(reps)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1180, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1195, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1195, in _xreplace
    a_xr = _xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1202, in _xreplace
    return self.func(*args), True
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/function.py", line 1287, in __new__
    __)))
ValueError: 
Can't calculate derivative wrt 0.
```

**Comment by Sc0rpi0n101** [comment]
The current build fails are also due to checkdesol and f(x).diff(x)**n

**Comment by oscarbenjamin** [comment]
All of the tracebacks are from subs which is what you have changed so I'd say it's subs that is causing the build fails.

I don't understand what the code you have removed is doing or why you want to remove it. Presumably it was originally added for a reason though.

**Comment by Sc0rpi0n101** [comment]
As discussed in #16627 
Was testing if m was really required when using subs for the D(f(x, y), x) situations and it seems to only have problems with some cases of checkdesol and when f(x).diff(x) is raised to some power.

And the issues in the build logs are similar, so, I am trying if this could be solved without using this Dummy variable.

**Pull request closed without merging**
