### PR TITLE
Implemented a function sqrtm that returns square root of a matrix

### PR DESCRIPTION
**Pull request by ks147**
#### Release Notes

* matrices
  * Added a function sqrtm that returns square root of a diagonalizable matrix

### CODE REVIEW

**Comment by ks147** [comment]
@sylee957 could you please review this PR

**Comment by sylee957** [comment]
Unfortunately, I don't think that this is needed since we already have the matrix power, and we also shouldn't use floating points like `D = D ** 0.5`
If we are going to elaborate a need of separate square root function, I'd expect a better compilation of research of problems like how to return all branches of square roots, or how to define the square roots uniquely, up to some generalization

**Comment by oscarbenjamin** [comment]
This is already possible with `**`:
```python
In [1]: M = Matrix([[33, 24], [48, 57]])

In [2]: M
Out[2]: 
⎡33  24⎤
⎢      ⎥
⎣48  57⎦

In [3]: M**S.Half
Out[3]: 
⎡5  2⎤
⎢    ⎥
⎣4  7⎦

In [4]: _**2
Out[4]: 
⎡33  24⎤
⎢      ⎥
⎣48  57⎦
```
It also works for non-diagonalisable matrices:
```python
In [5]: M = Matrix([[2, 1], [0, 2]])

In [6]: M**S.Half
Out[6]: 
⎡    √2⎤
⎢√2  ──⎥
⎢    4 ⎥
⎢      ⎥
⎣0   √2⎦

In [7]: _**2
Out[7]: 
⎡2  1⎤
⎢    ⎥
⎣0  2⎦
```

**Comment by ks147** [comment]
Ok my bad I didn't really come across it anywhere in documentation. I probably missed it

**Comment by oscarbenjamin** [comment]
Perhaps it should be added to the docs somewhere

**Pull request closed without merging**
