### PR TITLE
Pretty printing power of limit

### LINKED ISSUE #10803: Bad pretty printing of power of Limit
```
In [240]: 1/limit(airyai(x)*2*root(x, 4)*exp(2*x**(S(3)/2)/3), x, oo)**2
Out[240]:
                             -2
                3/2
             2⋅x
             ──────
      4 ___    3
lim 2⋅╲╱ x ⋅ℯ      ⋅airyai(x)
x─→∞
```

The `-2` power is just floating there. There needs to be parentheses. Marking as easy to fix because it's probably just an issue of marking the precedence of Limit correctly.

### PR DESCRIPTION
**Pull request by rd13123013**
Fixed #10803 
Now 

```
In [1]: 1/limit(airyai(x)*2*root(x, 4)*exp(2*x**(S(3)/2)/3), x, oo)**2
Out[1]: 
                               -2
⎛                3/2          ⎞  
⎜             2⋅x             ⎟  
⎜             ──────          ⎟  
⎜      4 ___    3             ⎟  
⎜lim 2⋅╲╱ x ⋅ℯ      ⋅airyai(x)⎟  
⎝x─→∞                         ⎠  
```

### CODE REVIEW

**Comment by asmeurer** [comment]
Add a test.

**Comment by asmeurer** [comment]
I guess the pretty printer doesn't use parenthesize like the latex printer does. This fix will work for now, but we should refactor this at some point in the future.

**Comment by rd13123013** [comment]
@asmeurer  have a look.

**Comment by asmeurer** [comment]
I don't know why the other tests at the bottom of the file are unicode only, but you should test both unicode and ascii (unless the test is testing something unicode specific, which this isn't).

**Comment by asmeurer** [comment]
I merged https://github.com/sympy/sympy/pull/10940 instead, which I preferred because it used the precedence module.

**Pull request closed without merging**
