### PR TITLE
Fixes a part of #10185: 	Replaced 'repr' with 'srepr' in the tutorial.

### LINKED ISSUE #10185: Clarification about srepr in the docs
Quoting from Gitter chat

> srepr gives the “repr” form, which is what reprwould normally give
but for SymPy we don’t actually use it for `__repr__` because it’s way too verbose
and on top of that when you print a list or a tuple it calls repr on the elements instead of str, so a list of sympy expressions would always have the repr output
that page should probably mention all of this. it could be a lot clearer
oh I guess that’s the tutorial. For the tutorial I would just replace the “repr” heading with “srepr”. But in the docs for srepr it should have the discussion about the repr builtin

We should rename the `repr` section in the tutorial to `srepr`, and add some in-depth discussion (basically what I wrote above) to the `srepr` docstring, which appears [here](http://docs.sympy.org/dev/modules/printing.html?highlight=srepr#sympy.printing.repr.srepr).

### PR DESCRIPTION
**Pull request by sampadsaha5**
Fixes  #10185

### CODE REVIEW

**Comment by sampadsaha5** [comment]
@asmeurer @VinaySingh035

**Comment by moorepants** [comment]
This seems to have a bunch of unrelated changes in the PR. Is that intended? If not you will need to separate them out.

**Comment by sampadsaha5** [comment]
@moorepants 

Sorry for this, Actually the changes in the commit with message "	Got these files after pulling from upstream master" were not donr by me. I was pulling files from upstream master and those files got added by itself . I am trying to figure out the things and fix it as soon as possible.

**Comment by scopatz** [comment]
Seems like the tests fail.

**Comment by moorepants** [comment]
@sampadsaha5 This issue is that you are working in your local master branch. Please read this to get an idea of how to make a feature branch and keep your local master branch synced with the Github master branch.

https://github.com/sympy/sympy/wiki/Development-workflow#create-a-separate-branch

**Comment by sampadsaha5** [comment]
Thanks @moorepants. I am going through it.

**Pull request closed without merging**
