### PR TITLE
Removing Deprecated Features in Jordan Block

### LINKED ISSUE #16208: Deprecate keyword arguments 'rows' and 'cols' for jordan_block
See issue #16102

### PR DESCRIPTION
**Pull request by Smit-create**
Removing Deprecated Features in Jordan Block
#### References to other Issues or PRs

Fixes #16208

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by czgdp1807** [comment]
+ https://github.com/sympy/sympy/pull/18381#issuecomment-575974206

**Comment by oscarbenjamin** [comment]
This feature was only recently deprecated. I don't see a need to remove it now. Note that deprecation removal issues are not intended to be immediately fixed. They are supposed to be there so that we remember in the future to remove the feature.

If you are interested in removing some of these I suggest looking at some older ones. Use
```
$ git grep deprecated_since_version
```
to see all deprecation warnings and the associated version. This was deprecated since version 1.4 and the most recent release is 1.5.1. Some features are deprecated since version 0.7.6 and can certainly be removed now.

**Comment by Smit-create** [comment]
Surely, I will look at it. So should I close this PR?

**Comment by oscarbenjamin** [comment]
Yes this should be closed.

**Pull request closed without merging**
