### PR TITLE
[PEP8] Fixed under-intended lines in satask.py

### PR DESCRIPTION
**Pull request by jremes-foss**
Good morning/afternoon.

Satask.py had some under-intended lines so I decided to amend these into more readable form.

Thank you.

### CODE REVIEW

**Comment by smichr** [comment]
We generally follow the convention that lines in a block-start (like a long `if`) get double indented while others just get indent one extra stop:

```python
if (long.......................
        condition):
    do this
    do (long.................
        this)
```

We've discussed this over the years and I'm not sure we came to a hard and fast rule regarding this. But I do think that it's better not to start these sorts of edits for their own sake or else changes that touch code of pending PRs make them require rebasing/merging and resolving the superficial differences.

n.b.: there may have different opinions (or I may be misrepresenting the current community feeling about this).

**Comment by asmeurer** [comment]
I definitely dislike overindented lines (I'm the one who originally wrote this code). Stuff like https://github.com/sympy/sympy/pull/10595/files#diff-7ec17002e9a664b5c103da3ebd255d55R82 looks worse to me.

**Comment by smichr** [comment]
Thanks, but I think we will pass on this for now. One serious error that I (think I) saw (and am remiss that I did not write it down immediately) was a place where a variable, defined in a conditional block, was used outside the conditional block. If you want to use a code quality tool to find and fix any such cases, that would be very welcome.  The case I am talking about looked like this:

```python
...
if cond:
    var = foo  <-- var not previously defined
if var == smthg:  <--error will raise if cond is ever False
    bar
```

It might have been in the solve module.

**Comment by Newman101** [comment]
Sure, thanks for notifying. I'll have a careful look at these using the QA tools then.

**Pull request closed without merging**
