### PR TITLE
Check for infinite iteration in calculus.util.function_range()

### LINKED ISSUE #13273: function_range keeps iterating over infinite critical points of ImageSet solution
`function_range(sin(x)*exp(x) - 1, x, S.Reals)` hangs forever as it keeps iterating over critical points in the following:

```python
Union(ImageSet(Lambda(_n, 2*_n*pi + 3*pi/4), S.Integers), ImageSet(Lambda(_n, 2*_n*pi + 7*pi/4), S.Integers))
```

https://github.com/sympy/sympy/blob/1e2760d8da15fe238abdb9741dadb3b63a3114ec/sympy/calculus/util.py#L141-L145

### PR DESCRIPTION
**Pull request by gschintgen**
#### References to other Issues or PRs

Fixes #13273.

#### Brief description of what is fixed or changed

If the set of critical values is an `ImageSet`, an exception is raised instead of entering an infinite loop.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscargus** [comment]
Looks good! The only thing I was considering is if there is a better exception than `NotImplementedError`? Would it even be possible to implement this? (Or is the solution "just" to use a bit of set arithmetic (which may not be implemented yet) and return an ImageSet or a FIniteSet? In which case the exception is correct.)

**Comment by gschintgen** [comment]
I thought about the naming too. In as far as the situation indeed arises for functions which have a well defined range, but the current algorithm is not able to compute it, "NotImplementedError" seems to fit. Otherwise it would only make it more cumbersome for the calling function with no real benefit.

With the current approach though, I'd say it won't be easy to correctly account for function expressions such as `sin(x) + x`. In this case it would be possible to separate the sum in two (continuous) parts: one ranging over (-oo, +oo) and the other a bounded function. Maybe such heuristics could be added, but that would definitely need more thought.

**Comment by oscargus** [comment]
Makes sense! I'll let someone with more insights on the actual topic merge it. Thanks!

**Comment by gschintgen** [comment]
> Makes sense! I'll let someone with more insights on the actual topic merge it. Thanks!

Thanks. So, anyone else double-checking this small fix? (@smichr, @aktech, @normalhuman ?)

**Comment by oscargus** [comment]
I've read up a bit more and think it is good to go! Thanks!

**Pull request merged**
