### PR TITLE
Small improvements in the duplicate vertex deletion

### PR DESCRIPTION
**Pull request by Jaime02**
There was a nodup list which could be removed for a more simple code. 
Also there was a if condition: continue code, which is always useless, right?

#### Brief description of what is fixed or changed
Small code improvements in the deletion of repeated vertices. There was a "nodup" list which can be deleted for a better code. 

#### Release Notes

* geometry
  * Small improvements deleting equal vertices, "nodup" list was unnecessary

### CODE REVIEW

**Comment by czgdp1807** [comment]
@Jaime02 Thanks for the contribution. Can you please provide some details in release notes entry, like exactly what improvement has been made?

**Comment by Jaime02** [comment]
@czgdp1807  Hello, the changes are really small but I will try to be more explicit

**Comment by Jaime02** [comment]
I do not know why there are coverage changes. This small improovements should not affect almost any file

**Comment by smichr** [comment]
When removing the nodup code, would duplicates like `b` in `Polygon(a,b,b,c)` be removed?

**Comment by Jaime02** [comment]
@smichr Yes, in theory it should work as in the past but without creating a "nodup" list. I dont know why the tests have failed. It seems like they expected some documentation under the results or something.

**Comment by Jaime02** [comment]
Well, basicly ALL of the white lines have dissappeared, how can I fix this?

**Comment by oscarbenjamin** [comment]
Do you have any idea how the lines got deleted? Maybe your editor did some autoformatting or something...

To fix this I suggest you save a copy of what is supposed to be changed and then start again with a new PR copying those changes in. You can use `git diff HEAD~6` to see all changes in the 6 commits in this PR.

**Comment by sylee957** [comment]
Collinearity test is usually a more generalized algorithm for finding and removing the duplicate vertices, so you won't even need to remove duplicates in priori step and the result can be still correct
But it comes at a cost of computational efficiency due to the computing the matrix rank instead of simply testing the equality.

The result can still be correct after the modification in the code for removing duplicates,
but the duplicate deletion algorithm had became less powerful since it only deals with the first and the last vertex after the changes.

So, the performance can degrade for some cases like
```python3
from sympy import *
import cProfile

pp = [Point(0, 0), Point(1, 0), Point(2, 2)] + [Point(2, 2)] *9999 + [Point(0, 1)]
cProfile.run('Polygon(*pp)')
```
and it had degraded to
`321141 function calls (299214 primitive calls) in 0.104 seconds`
`9250083 function calls (8718211 primitive calls) in 4.201 seconds`
since most of the duplicates should be discovered in collinearity test.

The benchmark can be artificial, but I'm not fully convinced that the code had become more simple and better for that part. Do you have some reason?

**Comment by Jaime02** [comment]
Could it use this? It will keep the order of the arguments.
`
points = [Point(0, 0), Point(1, 0), Point(2, 2)] + [Point(2, 2)] * 9 + [Point(0, 1)]
# print(points)
points = sorted(set(points), key=points.index)
# print(points)
pp = Polygon(*points)
print(pp.vertices)
`

**Comment by smichr** [comment]
> Could it use this?

I don't think so - the order is important. Also, we only want to delete *sequential* duplicates; other duplicates are important as when creating a "bowtie" (two triangle sharing a vertex)
```python
Polygon((0,-1),(0,1),(2,0),(3,1),(3,-1),(2,0),(0,-1))
```

**Comment by Jaime02** [comment]
> > Could it use this?
> 
> I don't think so - the order is important. Also, we only want to delete _consecutive_ duplicates; other duplicates are important as when creating a "bowtie" (two triangle sharing a vertex)
> 
> ```python
> Polygon((0,-1),(0,1),(2,0),(3,1),(3,-1),(2,0),(0,-1))
> ```
> 
> In this case the only duplicate to be removed is the last point (0,-1) since it is the same as the first point. If the first (2,0) were repeated _consecutively_ then only 1 instance would be retained so `Polygon((0,-1),(0,1),(2,0),(2,0),(2,0),(3,1),(3,-1),(2,0),(0,-1))` would reduce to the form shown previously.

Oh that's true, I did not think that. Shall I continue the PR? Changing code without using sets

**Comment by sylee957** [comment]
I think that the changes to make the error message clear may be okay to keep.
Although it would be better to implement 3D polygon properly as well, if we can.

**Comment by Jaime02** [comment]
> I think that the changes to make the error message clear may be okay to keep.
> Although it would be better to implement 3D polygon properly as well, if we can.

The 3D implementation is my current goal. However, this PR was created to change the code of the deleting process of duplicates. I will try to close this PR with the good changes.

**Comment by Jaime02** [comment]
Well I think the code is ready to be pushed, but it needs a review

**Comment by oscarbenjamin** [comment]
It's hard for me to work out what the changes are here because there are also many formatting changes. Are they intentional?

**Comment by Jaime02** [comment]
@oscarbenjamin I know, the formatting has been done by PyCharm after a commit, shall I undo it?

**Comment by oscarbenjamin** [comment]
I think it's best to undo it. Also this PR will need tests

**Comment by Jaime02** [comment]
I will close this PR because no advancements were made and my code is many times slower than the current one.

**Pull request closed without merging**
