### PR TITLE
Printing of Fancy Sets

### LINKED ISSUE #10672: Sets printing issues
Some issues with str and srepr printing in sets. 

Some notes:
- The `str` printer should always generate valid Python, which recreates the expression (but may require some variables to be defined).
- The `srepr` printer should generate an expression that recreates the expression exactly, using only the names from `from sympy import *` (or other relevant imports for other submodules, but that isn't relevant for the sets). 
- Fancy printing should be relegated to the pretty printers (`pprint` and `latex`). 

Here are the issues I found:
1. `str(Interval)`
   
   ```
   In [9]: str(Interval(0, 1, False))
   Out[9]: '[0, 1]'
   
   In [10]: str(Interval(0, 1, True))
   Out[10]: '(0, 1]'
   ```
   
   The former creates a list, not an interval. The latter isn't even valid Python.
2. `srepr(S.Integers)` (and probably others)
   
   ```
   In [11]: srepr(S.Integers)
   Out[11]: 'Integers()'
   ```
   
   `Integers` isn't a name that is imported from `sympy`. It should print as `S.Integers`. The `str` printers should probably do the same. 
3. `str(Union)`
   
   ```
   In [18]: str(Union(S.Integers, FiniteSet(pi))) 
   Out[18]: 'Integers() U {pi}'
   ```
   
   It's not valid Python. It should print as `Union(S.Integers, FiniteSet(pi))`. Printing as `Union(S.Integers, {pi})` is fine when https://github.com/sympy/sympy/issues/10654 gets merged. 

There are likely others. I didn't check too much. An audit of the printing in the sets module would be worthwhile.

### PR DESCRIPTION
**Pull request by AnimeshSinha1309**
#### References to other Issues or PRs
Fixes #10672: Set printing issues

#### Brief description of what is fixed or changed
Changed the way sets `S.Integers`, `S.Reals`, `S.Naturals` and `S.Naturals0` are printed using all of `print()`, `str()`, and `srepr()`.

#### Other comments
Now printing would result in S.Integers instead of Integers or Integers(), which is now the correct name of the set.

#### Release Notes

* printing
  * Changed printing using str() and repr() of S.Integers, S.Reals, S.Naturals and S.Naturals0 to the names of the sets themselves

### CODE REVIEW

**Comment by AnimeshSinha1309** [comment]
I guess I should change the tests. Can anyone provide help here, The things that the tests show as error are the features that I edited. All as was asked for in #10672.

**Comment by AnimeshSinha1309** [comment]
> Is this the expected behaviour of `str()` and `srepr()`:
> 
> ```python
> >>> from sympy import S
> >>> from sympy import srepr
> >>> print(S.Integers)
> S.Integers
> >>> S.Naturals0
> S.Naturals0
> >>> srepr(S.Naturals)
> 'S.Naturals'
> >>> str(S.Reals)
> 'S.Reals'
> ```
> 
> I implemented this but then did not pass the tests as the examples and tests are written for the previous output. Please tell me if this is what was desired so I can fix the tests and examples for the new output.

If someone can help me out by confirming this, please do.

**Comment by asmeurer** [comment]
Given that these names are now imported by default, printing them with the S is no longer necessary.

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/issues/10672#issuecomment-447478556, there is still a fix that can be made here.

**Comment by AnimeshSinha1309** [comment]
I changed just the `srepr` outputs, should I also add tests?

**Comment by AnimeshSinha1309** [comment]
@asmeurer please do check the code.

**Comment by asmeurer** [comment]
Looks good to me.

**Pull request merged**
