### PR TITLE
Added outputs for all plot examples

### LINKED ISSUE #15327: Add example plot outputs to the Sphinx documentation
We enabled the [matplotlib plot directive](https://matplotlib.org/devel/plot_directive.html) in #15310. This allows us to display plot results in the documentation in a number of ways. The first example is at: https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam_problems.html with the source here: https://github.com/sympy/sympy/blob/master/doc/src/modules/physics/continuum_mechanics/beam_problems.rst.

The `sympy.plot()` command does not have any examples in the documentation of the resulting plots. Many of the docstrings could include these. There are also other modules that make use of `sympy.plot()` or `matpltolib.pyplot.plot()` that could use some sprucing up.

Pull requests that add in plots to relevant portions of the documentation would be helpful.

Potential documentation areas that could use improvement:

- [x] https://docs.sympy.org/dev/modules/plotting.html
- [ ] https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam_problems.html
- [ ] https://docs.sympy.org/dev/modules/geometry/index.html

### PR DESCRIPTION
**Pull request by iamprayush**
#### References to other Issues or PRs

#15327

#### Brief description of what is fixed or changed
Added outputs to all the plots using matplotlib plot directive

#### Other comments
This should be enough to close the issue.

#### Release Notes

* plotting
   * Added outputs to all plotting examples in the sphinx docs.

### CODE REVIEW

**Comment by iamprayush** [comment]
These are the outputs that I received:
screenshot from 2018-10-10 00-17-30
screenshot from 2018-10-10 00-17-38
screenshot from 2018-10-10 00-17-43
screenshot from 2018-10-10 00-17-44
screenshot from 2018-10-10 00-17-47
screenshot from 2018-10-10 00-17-51

**Comment by iamprayush** [comment]
@moorepants will this be enough to close the issue?

**Comment by moorepants** [comment]
These look great. +1 to merge once tests pass.

> @moorepants will this be enough to close the issue?

Maybe not. I think more work for the beam examples is still needed, among potential other places in the docs that use plots.

**Comment by moorepants** [comment]
They are already there: https://docs.sympy.org/dev/modules/plotting.html

Yes, you will be added to the authors list on the next release.

**Pull request merged**
