### PR TITLE
Update printer.py

### PR DESCRIPTION
**Pull request by mohit3011**
Replaced Therefor with Therefore in line 19 (issue #11911)

### CODE REVIEW

**Comment by gxyd** [comment]
Thanks. Merging.

**Comment by gxyd** [comment]
From next time. You can use "Fixes #issue_number" in your commit message, that will automatically close the corresponding issue. I am now doing it manually.

**Comment by mohit3011** [comment]
Thank you for your feedback . Actually I am new to open source contribution so kindly guide me.

----- Original Message -----

**Comment by asmeurer** [comment]
@mohit3011 if you can suggest how to make the message "<If this pull request fixes an issue please indicate which issue by typing "Fixes #NNNN" below.>" clearer please let us know (not trying to be passive aggressive, really do want to make it clearer, since it obviously didn't work in this instance).

**Pull request merged**
