### PR TITLE
Added proper_divisor and proper_divisor_count functions

### LINKED ISSUE #15927: Function for proper divisors
A function returning the list of proper divisors seems to be missing

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References to other Issues or PRs

Fixes #15927
https://github.com/sympy/sympy/pull/15928

#### Release Notes

- ntheory
    - Added proper_divisor and proper_divisor_count functions

### CODE REVIEW

**Comment by sylee957** [comment]
Sphinx build is failing
Add these lines in ntheory.rst
```
.. autofunction:: proper_divisors

.. autofunction:: proper_divisor_count
```

**Comment by czgdp1807** [comment]
Restarted the builds due to irrelevant failures in previous one.

**Comment by czgdp1807** [comment]
@jksuom Is it ready to be merged? Please take a look.

**Comment by jksuom** [comment]
Looks good to me.

**Pull request merged**
