### PR TITLE
perf(matrices): speed up eigenvals for triangular matrices

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

Corrects a small performance regression from #21474

#### Brief description of what is fixed or changed

Speed up eigenvals for triangular matrices e.g.:
```python
def make(n):
    def entry(i, j):
        if i == j:
            return i
        elif i > j:
            return j
        else:
            return 0
    return Matrix(n, n, entry)

In [3]: M = make(5)

In [4]: M
Out[4]: 
⎡0  0  0  0  0⎤
⎢             ⎥
⎢0  1  0  0  0⎥
⎢             ⎥
⎢0  1  2  0  0⎥
⎢             ⎥
⎢0  1  2  3  0⎥
⎢             ⎥
⎣0  1  2  3  4⎦

In [5]: %time M.eigenvals()
CPU times: user 810 µs, sys: 313 µs, total: 1.12 ms
Wall time: 1.42 ms
Out[5]: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1}
```
This had slowed down on master since 1.8 as a result of https://github.com/sympy/sympy/pull/21474 which is a performance improvement in general but slows down the particular case of a perfectly triangular matrix that factors completely into 1x1 blocks. The slowdown is due to calling calling charpoly and roots for trivial 1x1 matrices. This  PR just uses the value from the matrix directly as the eigenvalue if it is 1x1 which mostly restores the previous performance.

#### Other comments

This routine could become a lot faster for this kind of matrix after #21626.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by sylee957** [comment]
You also need to change `_eigenvals_list`

**Comment by oscarbenjamin** [comment]
A problem with the approach here:
```python
In [1]: M = Matrix([[(x + y)/z, 0], [0, x/z + y/z]])

In [2]: M
Out[2]: 
⎡x + y       ⎤
⎢─────    0  ⎥
⎢  z         ⎥
⎢            ⎥
⎢       x   y⎥
⎢  0    ─ + ─⎥
⎣       z   z⎦

In [3]: M.eigenvals()
Out[3]: 
⎧x + y     x   y   ⎫
⎨─────: 1, ─ + ─: 1⎬
⎩  z       z   z   ⎭
```
On master that gives:
```python
In [2]: M.eigenvals()
Out[2]: 
⎧x + y   ⎫
⎨─────: 2⎬
⎩  z     ⎭
```
It's possible to fix that here by adding a call to `cancel` but then the speed benefit is lost.

Probably a better way is that after #21626 we could do this only when a proper domain is being used rather than for EXRAW.

**Comment by smichr** [comment]
> possible to fix that here by adding a call

are there cases that need `cancel` or would `factor_terms` (which was made for the obvious cases) be sufficient:
```python
>>> factor_terms(x/z+y/z)
(x + y)/z
```

**Comment by oscarbenjamin** [comment]
In SymPy 1.8 we have this:
```python
In [21]: M = Matrix([[(x**2 - y**2)/(x - y), 0], [0, x + y]])

In [22]: M
Out[22]: 
⎡ 2    2       ⎤
⎢x  - y        ⎥
⎢───────    0  ⎥
⎢ x - y        ⎥
⎢              ⎥
⎣   0     x + y⎦

In [23]: M.eigenvals()
Out[23]: 
⎧ 2    2             ⎫
⎪x  - y              ⎪
⎨───────: 1, x + y: 1⎬
⎪ x - y              ⎪
⎩                    ⎭

In [24]: roots(M.charpoly())
Out[24]: {x + y: 2}
```
However on master that is
```python
In [2]: M.eigenvals()
Out[2]: {x + y: 2}

In [3]: roots(M.charpoly())
Out[3]: {x + y: 2}
```
Getting the multiplicity right is important because e.g. with sympy 1.8 we have
```python
In [1]: M = Matrix([[(x**2 - y**2)/(x - y), 0], [0, x + y]])

In [2]: M.exp()
---------------------------------------------------------------------------
NonInvertibleMatrixError
```
whereas master gives
```python
In [1]: M = Matrix([[(x**2 - y**2)/(x - y), 0], [0, x + y]])

In [2]: M.exp()
Out[2]: 
⎡ x + y        ⎤
⎢ℯ         0   ⎥
⎢              ⎥
⎢         x + y⎥
⎣  0     ℯ     ⎦
```
Currently PR would restore the buggy sympy 1.8 behaviour.

**Comment by smichr** [comment]
Does the following work without slowing things down too much?
```python
def merge_multiple(ev):
    from sympy.solvers.solvers import denoms
    from sympy.utilities.iterables import ordered
    from sympy.core.function import _mexpand
    from collections import defaultdict
    rv = {}
    d = defaultdict(list)
    for i in ev:
        d[tuple(ordered(i.free_symbols))].append(i)
    for i in d:
        if len(d[i]) == 1:
            rv[d[i]] = ev[d[i]]
            continue
        den = Mul(*denoms(Tuple(*d[i])), evaluate=False)
        uniq = defaultdict(list)
        for i in d[i]:
            uniq[_mexpand(den*i)].append(i)
        for i in uniq:
            k = next(ordered(uniq[i]))
            rv[k] = sum(ev[i] for i in uniq[i])
    return rv

    
>>> merge_multiple({(1/x+1/y):1,(x + y)/x/y:1})
{1/y + 1/x: 2}
>>> merge_multiple(Matrix([[(x**2 - y**2)/(x - y), 0], [0, x + y]]).eigenvals())
{x + y: 2}
```

**Comment by oscarbenjamin** [comment]
> Does the following work without slowing things down too much?

I'm not sure but I decided just to only apply this optimisation when the domain of the matrix is ZZ or QQ since then all expressions are in a canonical form.

**Comment by asmeurer** [comment]
Do the domains not include rational functions or other complex domains that also have canonical forms? Maybe we should add a `has_canonical` attribute to the domains. Or add `is_canonical` to the elements. That also opens the interesting possibility of not necessarily keeping things like rational functions in canonical form, which could be useful since cancelling after every operation might be slower than cancelling once at the end in some cases.

**Comment by oscarbenjamin** [comment]
> Do the domains not include rational functions or other complex domains that also have canonical forms?

They do but the implementation I just merged in #21626 only uses the domains automatically for ZZ and QQ. Otherwise the EXRAW domain is used precisely because the canonical forms would not be backwards compatible e.g. right now you can do:
```python
In [15]: M = Matrix([[(x + 1)**10000000000000]])

In [16]: M
Out[16]: 
⎡       10000000000000⎤
⎣(x + 1)              ⎦

In [17]: M**2
Out[17]: 
⎡       20000000000000⎤
⎣(x + 1)              ⎦
```
If that automatically used `ZZ[x]` then those binomials would need to be expanded.

Of course for charpoly/eigenvals we probably do want to use the domains but we need some code to identify the appropriate domain at the start of the routine because Matrix will not do it at construction.

**Comment by oscarbenjamin** [comment]
This is ready for review

**Comment by sylee957** [comment]
> You also need to change `_eigenvals_list`

I don’t think that this comment is resolved yet. I expect simultaneous change for eigenvals_list

**Comment by oscarbenjamin** [comment]
> I don’t think that this comment is resolved yet

Sorry, I forgot that one after the other changes...

**Comment by oscarbenjamin** [comment]
> I expect simultaneous change for eigenvals_list

I've made those changes now. Those functions should be merged somehow (one should call the other).

**Comment by oscarbenjamin** [comment]
Okay, now this is ready for review.

**Pull request merged**
