### PR TITLE
Fix floor(x -/+ S.Half).is_even for negative even x

### LINKED ISSUE #8853: floor(x - S.Half).is_even returns True for negative even 'x'
This should return False.
```python
In [7]: x =Symbol('x', even=True, negative=True)

In [8]: floor(x - S.Half).is_even
Out[8]: True
```

### PR DESCRIPTION
**Pull request by aktech**
Fixes #8853 
@smichr

### CODE REVIEW

**Comment by smichr** [comment]
PR has been sent to you.

**Comment by aktech** [comment]
Thanks! I have Merged that.

**Comment by smichr** [comment]
Thanks, @aktech, I feel a lot better about this little piece of code now. I'll commit once tests pass.

**Comment by aktech** [comment]
@smichr 
Now this can be closed due to #8846 .

**Comment by aktech** [comment]
closed in favor of #8846 .

**Pull request closed without merging**
