### PR TITLE
Fixes #14528, by leaving unevaluated `gamma(p)` for p integer and nonpositive

### LINKED ISSUE #14528: Incorrect binomial simplifications with constant n
SymPy incorrectly simplifies binomials coefficients of the form `binomial(1, k)` to zero for symbolic `k`, and `1` can be replaced by any integer constant. Below are some examples.

````python

# binomial(1, p) is zero if p < 0 or p > 1, and one for p = 0, 1.

binomial(1, -1) # 0
binomial(1, 1) # 1
binomial(1, 2) # 0

# Incorrect.
p = symbols("p")
binomial(1, p).simplify() # 0

# Also incorrect.
p = symbols("p", integer=True)
binomial(1, p).simplify() # 0

# Still incorrect.
p = symbols("p", positive=True, integer=True)
binomial(1, p).simplify() # 0
````
Replacing `.simplify` with `.combsimp` does not fix the issue, and the issue seems to exist for any positive integer upper value. Both `simplify` and `combsimp` are complicated, so I can't determine exactly where the simplifications are going wrong.

### PR DESCRIPTION
**Pull request by jeremies**
The problem in issue #14528 is that when we evaluate `gamma(p)` in SymPy where p is integer and nonpositive it gives `zoo`, but this is not a wise thing because is better to leave it unevaluated as other symbolic mathematical software like Wolfram Mathematica 8.0 gives it. If we evaluate it to `zoo` then we have problems like the one described in the issue. This pull request alters this behaviour of evaluating `gamma(p)`, leaving it non evaluated, an fixes the issue.

### CODE REVIEW

**Comment by Abdullahjavednesar** [comment]
@jeremies add relevant test cases for the changes made and try fix the failing tests.

**Comment by Abdullahjavednesar** [comment]
@jksuom, can you review this, thanks!

**Comment by rwbogl** [comment]
>The problem in issue #14528 is that when we evaluate gamma(p) in SymPy where p is integer and nonpositive it gives zoo, but this is not a wise thing because is better to leave it unevaluated as other symbolic mathematical software like Wolfram Mathematica 8.0 gives it.

But `gamma` at any nonpositive integer _should_ return `zoo`, or else raise an error. Changing the behavior of `gamma` to fix #14528 feels like sidestepping the incorrect rewriting discussed in that issue. (See also [this WolframAlpha query](http://www.wolframalpha.com/input/?i=gamma(0)).)

**Comment by jksuom** [comment]
`gamma` still evaluates to `zoo` for any nonpositive integer:

            elif arg.is_Integer:
                if arg.is_positive:
                    return factorial(arg - 1)
                else:
                    return S.ComplexInfinity

The point is that `p` is not an Integer. Hence `gamma(p)` can provisionally be left unevaluated.

**Comment by rwbogl** [comment]
I may be mistaken, but is `arg.is_Integer` only true provided that `arg` is a constant? That is, for `n = symbols("n", integer=True)`, is `n.is_Integer` false? If so, why limit the `zoo` evaluation to constants if we know that the argument is a nonnegative integer?

**Comment by jksuom** [comment]
@jeremies Please add a test for `combsimp(binomial(1, p))` with `p = symbols("p", positive=True, integer=True)`.

**Comment by jeremies** [comment]
@jksuom Have you read my last message in issue #14577 ?

**Comment by jeremies** [comment]
@rwbogl If you read my last message in issue #14577 you will see that it's a bit difficult to test now this problem, but if you evaluate gamma(p) for p integer and nonpositive to zoo then the simplification is wrong. You can debug it to see how it works internally the simplification of binomial(1,p).

**Comment by jksuom** [comment]
@jeremies This is what I get in your branch:
```
>>> p = symbols("p", positive=True, integer=True)
>>> combsimp(binomial(1, p))
1/(factorial(p)*factorial(-p + 1))
```
This may not be the best possible form but I think it would be quite satisfactory. Do you not want to accept it?

**Comment by jeremies** [comment]
@jksuom Sorry, but I haven't pushed on my github the merge with the updated master branch. Now it gives the following:
``` python
>>> p = symbols("p", positive=True, integer=True)
>>> combsimp(binomial(1, p))
zoo/(p - 1)
```

**Comment by rwbogl** [comment]
@jeremies 
> but if you evaluate gamma(p) for p integer and nonpositive to zoo then the simplification is wrong.

I think that the simplification goes wrong before `gamma` gets involved.

> You can debug it to see how it works internally the simplification of binomial(1,p).

I did this after reporting #14528, and concluded that the custom rising factorial `_rf` in that code was rewriting itself beyond what was valid.

Is there a reason beyond fixing #14528 to change the evaluation of `gamma`?

**Comment by jksuom** [comment]
The branch I am testing with has this diff:
```
diff --git a/sympy/functions/special/gamma_functions.py b/sympy/functions/special/gamma_functions.py
index 64013b1..63a9bfd 100644
--- a/sympy/functions/special/gamma_functions.py
+++ b/sympy/functions/special/gamma_functions.py
@@ -134,9 +134,6 @@ def eval(cls, arg):
                     else:
                         return 2**n*sqrt(S.Pi) / coeff
 
-        if arg.is_integer and arg.is_nonpositive:
-            return S.ComplexInfinity
-
     def _eval_expand_func(self, **hints):
         arg = self.args[0]
         if arg.is_Rational:
```
and it gives the result copied above. Is there another difference in your local branch?

**Comment by jeremies** [comment]
@jksuom Yes, the problem is in pull request #14575, in the file factorials.py, in particular this change that returns binomial(-p,-p) = 0 for p integer and positive.
``` python
     def eval(cls, n, k):
         n, k = map(sympify, (n, k))
-        d = n - k
-        if d.is_zero or k.is_zero:
+        if k.is_zero:
             return S.One
         if (k - 1).is_zero:
```

You can clone my github repository:
`git clone https://github.com/jeremies/sympy`
and then
`git checkout issue_14528_binomial`
There you will get my result copied above.

**Comment by jksuom** [comment]
@jeremies I think you are on the right track. `gamma` with a symbolic argument should not be evaluated before the whole expression has been dealt with. Combinatorial functions like `binomial` should probably be treated in the same way (by changing some `is_integer` to `is_Integer` so that symbolic arguments are not included).

**Comment by jeremies** [comment]
Since now `binomial(-p,-p)` for `p` integer and positive returns 0, it has no sense to replace `_rf(a,b)` for `binomial(a + b - 1, b)*gamma(b + 1)` in _gammasimp, so with my last commit I changed this to replace `_rf(a,b)` for simply `gamma(b + 1)` (since `binomial(a + b - 1, b)` it must evaluate always to 1 in this construction of the simplification). If someday we agree to implement the definition of the binomial in the paper https://arxiv.org/pdf/1105.3689.pdf mentioned in issue #14577 then we could do the first replacement (is the correct one). But now we have to fix it in this way, if not we get incorrect results for `combsimp(binomial(1,p))` for p positive and integer.

I think the pull request is ready for merge, since all works good and the tests are added covering combsimp(binomial(1, p)) with p = symbols("p", positive=True, integer=True).

**Comment by jksuom** [comment]
The first step in `gammasimp` will replace `gamma(n)` by `_rf(1, n - 1)`. It seems to me that, if `as_comb` is true, the second step will now turn it back to `gamma(n - 1 + 1) == gamma(n)` (which is correct, of course). Does this mean that both of these replacements should be omitted in case `as_comb` is true?

**Comment by jeremies** [comment]
But then this piece of code in _gammasimp function, can be deleted?
``` python
    expr = expr.replace(gamma,
        lambda n: _rf(1, (n - 1).expand()))

    if as_comb:
        expr = expr.replace(_rf,
            lambda a, b: gamma(b + 1))
    else:
        expr = expr.replace(_rf,
            lambda a, b: gamma(a + b)/gamma(a))
```
Because you explained the case when `as_comb` is `True`, and when is `False` is similar. I haven't written this function, I don't know the precise motivation of the author... Should I delete this piece of code?

**Comment by jksuom** [comment]
> Should I delete this piece of code?

I don't think all of it should be deleted. The part where `as_comb` is `False` should probably be preserved. Note that `_rf` will do some processing with its arguments that may be beneficial. (On the other hand, I think that the two replacements can be skipped when `as_comb` is `True`.)

**Comment by jeremies** [comment]
@jksuom I tried to replace from this piece of code in function _gammasimp:
``` python
    expr = expr.replace(gamma,
        lambda n: _rf(1, (n - 1).expand()))

    if as_comb:
        expr = expr.replace(_rf,
            lambda a, b: gamma(b + 1))
    else:
        expr = expr.replace(_rf,
            lambda a, b: gamma(a + b)/gamma(a))
```
to this one (according to your recommendation):
``` python
    if not as_comb:
        expr = expr.replace(gamma,
            lambda n: _rf(1, (n - 1).expand()))
        expr = expr.replace(_rf,
            lambda a, b: gamma(a + b)/gamma(a))
```
But then one test fails, more precisely `combsimp(factorial(n)/factorial(n-3))` should give `n*(-1 + n)*(-2 + n)` but with this change gives `factorial(n)/factorial(n-3)`. So I think we shouldn't do no more change and this pull request is ready for merge.

**Comment by jksuom** [comment]
I think you are right. The two replacements do not always cancel each other when `as_comb` is true because `_rf` may modify its arguments. So I also believe this is ready to go. Thank you for your contribution.

**Comment by jeremies** [comment]
Thanks @jksuom !

**Pull request merged**
