### PR TITLE
Added Solver Related Tests to test_solvers.py

### PR DESCRIPTION
**Pull request by guptabhaskar**
My first try at contributing to SymPy.

#### References to other Issues or PRs
 Partial fix for #18666

#### Brief description of what is fixed or changed
migrate all the solvers-related tests from test_matrices.py to a new created file test_solvers.py.

#### Release Notes

- matrices

            Added test_solvers.py file which contains all the solvers-related tests.

### CODE REVIEW

**Comment by guptabhaskar** [comment]
@sylee957 Can you please explain what does conflicting files mean?
I am new to open source and it's my first time contributing to these big projects.

**Comment by sylee957** [comment]
It means that you should resolve merge conflict either by merging the latest master or rebasing.

**Comment by sylee957** [comment]
You should not edit other files

**Comment by guptabhaskar** [comment]
> You should not edit other files
I can't see edit in any file other than test_solvers.py and test_matrices.py. So, can you please tell which edit i made?
And I am sorry if I did edit any other file.

**Comment by sylee957** [comment]
I see there are 39 files changed in github. It could have been introduced by some wrong git usage, as I see you have made lots of redundant commits

I’d recommend you to squash all the commits and inspect what is going wrong.

If you cannot do that, you’d better close this and begin from the scratch. I think that this PR is dangerous to merge, because I’m not sure if you have reverted any other commits accidently or not.

**Comment by guptabhaskar** [comment]
Yeah, I really did some redundant commits and will send a new PR very soon.
Thanks for helping.

**Pull request closed without merging**
