### PR TITLE
Added entropy, mgf, and cf in MultivariateNormalDistribution

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References to other Issues or PRs
https://en.wikipedia.org/wiki/Multivariate_normal_distribution

#### Brief description of what is fixed or changed
The methods, entropy, mgf and cf have been added to
sympy.stats.joint_rv_types.MultivariateNormalDistribution.
Entropy is calculated by entropy, Moment Generating Function
by mgf and Characteristic Function by cf.

#### Other comments
I don't know whether [MGF](https://en.wikipedia.org/wiki/Moment-generating_function), [CF](https://en.wikipedia.org/wiki/Characteristic_function_(probability_theory)) and [Entropy](https://en.wikipedia.org/wiki/Information_entropy) have already been implemented or not for  MultivariateNormalDistribution. Since, I didn't find them in the class, I thought of implementing
them. Just an effort. :-)
In addition, I am doubtful that where to write tests for the methods I have added. I was unable to find tests for pdf, marginal_distribution, etc.

#### Release Notes

* stats
   * entropy, mgf and cf have been added in  MultivariateNormalDistribution.

### CODE REVIEW

**Comment by Upabjojr** [comment]
Every new feature requires tests.

**Comment by czgdp1807** [comment]
I think, MGF, CF and Entropy can be added in other multivariate distributions too. After adding these features in all the multivariate distributions, I will add the tests.

**Comment by Upabjojr** [comment]
Actually these features should be automatically deduced from the density function. I would recommend not to add these features.

**Comment by czgdp1807** [comment]
I thought it would ease out the work of the user so thought of adding them.
If you still recommend not adding them, then I will not work more on it.

**Comment by Upabjojr** [comment]
You are likely to overwrite methods that compute those quantities. There is something like that for the cumulative distribution function, I think maybe `_cdf` if I recall correctly, but it's meant for random variables where the integration fails to give the correct result.

Technically the integration module should be able to compute all these expressions, so we prefer not to create them unless really necessary.

**Comment by czgdp1807** [comment]
I understood your point. I will not work more on this.
Thanks for detailed explanation.

**Comment by czgdp1807** [comment]
Yes closing.

**Pull request closed without merging**
