### PR TITLE
Patch limit printing and parsing

### PR DESCRIPTION
**Pull request by eagleoflqj**
#### Brief description of what is fixed or changed
This is the monkey patch I'm [using](https://github.com/eagleoflqj/sympy_beta/blob/8566f7995130ecc469030bb971365b84d0a09bdc/kernel/api/__init__.py#L41-L83) at SymPy Beta, and I think it should be directly applied in SymPy.
The parsing part is definitely a bug.
The printing part isn't, technically. However it **doesn't need** to return different strings based on limit direction, nor does it need to be based on how SymPy treats default limit direction.

#### Release Notes

* parsing
  * Fixed a bug in parsing latex Limit

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
You've asked for a review from me but this PR covers parsing, printing and limits which are all parts of the codebase that I don't know so well so I will let someone else review this.

**Comment by eagleoflqj** [comment]
Any objections?

**Comment by ThePauliPrinciple** [comment]
Parsing indeed seems to be a bug. As for the printing, it can be surprising for a user that the default behaviour of sympy is to do a limit with a direction, so it would be nice if the string representation includes the dir even if it is a default.
e.g.
```python
>>> from sympy.abc import x
>>> from sympy import *
>>> str(Limit(x, x, 3))
Limit(x, x, 3)
```
to
```python
Limit(x, x, 3, dir='+')
```

The question is, do we consider something like this a regression? Otherwise it looks good to me.

**Comment by eagleoflqj** [comment]
> do we consider something like this a regression

Thanks for your reviewing. I think this can be considered a normal behavior change rather than a regression, as either way it's not a bug.

**Pull request merged**
