### PR TITLE
use headings for separate section of PR number and explanation

### PR DESCRIPTION
**Pull request by gxyd**
using heading easily separates the issue number, the pull request
fixes from the rest of explanation.

Idea taken from
https://github.com/scikit-learn/scikit-learn/blame/master/PULL_REQUEST_TEMPLATE.md

### CODE REVIEW

**Comment by gxyd** [comment]
@asmeurer @ylemkimon WDYT? I've countless PR's from first time contributors which miss mentioning the issue number in the PR description. I believe this will increase chances of issue mentioning.

**Comment by smichr** [comment]
Maybe change `### Reference Issues/PRs` section to have a smaller text and the expanded 'comment' text:

```
#### References to other Issues or PRs
<!--
Include references to related issues or PRs here.
You can refer to issues or PRs in your discussion by typing '#' before
the number of the issue/PR, e.g. #12345.

If this pull request completely fixes an issue please include
-- on its own line -- the text which will automatically close
the issue if this PR is merged, .e.g.

fixes #12345
+-->
````

**Comment by gxyd** [comment]
I've fixed the heading level. I've included the text you've provided, but I don't understand the meaning of 'on its own line', what does that mean?

**Comment by asmeurer** [comment]
I'm not convinced if people won't read one thing they will read another. But we can try.

**Comment by smichr** [comment]
> on its own line

I went back and read [the description of this feature](https://help.github.com/articles/closing-issues-using-keywords/) and I see that I was wrong. The text can appear even in a sentence as they show at the bottom of the page. So no need for that restriction in the directions.

**Comment by smichr** [comment]
```
#### References to other Issues or PRs
<!--
Include references to related issues or PRs here.
You can refer to issues or PRs in your discussion by typing '#' before
the number of the issue/PR, e.g. #12345.

If this pull request completely fixes an issue please include
the text "fixes #NNNNN" where NNNNN is the issue number
that should be closed if this PR is merged. To close multiple issues,
repeat the phrase as in "This fixes #12345, fixes #12346."
+-->
````

**Comment by smichr** [comment]
I made the mods directly. What do you think?

**Comment by asmeurer** [comment]
I kind of like the old one better because it's less text for people to read, but I don't feel strongly about it.

**Comment by asmeurer** [comment]
How about the old text and adding a link to the GitHub docs for auto closing issues?

**Comment by asmeurer** [comment]
Regarding the title part, having the number in the title isn't a problem in itself. It's just bad when people do it instead of a description of what is fixed (as if we somehow have the issue numbers memorized). But perhaps banning them will solve the problem. 

@gxyd, are people also missing the "fixes #123" thing or is it just the title part that's not being followed?

**Comment by gxyd** [comment]
Yes, first time contributors are also missing "Fixes #NNNN" part.

How I would like to go about it is, keep the text very less (as Aaron mentioned, I strongly agree with this) but put examples initially and use links often.
```
#### Reference Issues/PRs

<!--
Example: Fixes #1234, See also #3456.
Please use keywords (e.g., Fixes) to create link to the issues or pull requests
you resolved, so that they will automatically be closed when your pull request
is merged. See https://github.com/blog/1506-closing-issues-via-pull-requests
-->
```
To make people understand how 'fixes #NNNN' works, I had rather simply put a link to github blog post about how 'fixes' works (i.e
https://github.com/blog/1506-closing-issues-via-pull-requests
).

**Comment by smichr** [comment]
I don't like the numbers in the title because 1) you can't click on them and 2) the PR number already automatically appears at the end of the title.

What about this:

```
<!-- Make your title be a short description of what
was changed. Do not include the issue number. -->


#### References to other Issues or PRs
<!-- Refer to related issues by number putting '#' before the number;
write "fix" before each issue that is closed by this PR.
Example: This PR will fix #3 and fix #42. Issue #99 is not fixed." -->


#### Brief description of what is fixed or changed.


#### Other comments.

```

**Comment by gxyd** [comment]
That looks good to me. I would have hoped add one line space (i.e. one blank line) between the heading section i.e. `### Reference to other issues or PRs` and the starting of comment i.e `<!-- Refer to related issues ... -->`, but I would not want text to go out of eyes reach for default text-box size (i.e there should be no need to scroll the default box) of github.

So, I agree @smichr's change.

**Comment by smichr** [comment]
Something that would be a nice addition to github is an autolink to any autoclosing syntax. For example if I say "I don't think this will fix #123" the "fix #123" would become a link to a page that says, 
```
Using an autoclosing keyword before an issue or PR number will cause that issue/PR to be closed when this PR is merged. If this is not your intent, insert the word "issue" before the issue number. See [here](https://help.github.com/articles/closing-issues-using-keywords/) for more details.
```

**Pull request merged**
