### PR TITLE
fixes permutation of types in heurisch

### LINKED ISSUE #26922: The following Integral doesn't evaluate anymore
```py
from sympy import *
init_printing()

a, b, x = symbols("a, b, x", real=True, positive=True)
C = symbols("C", real=True)
i = Integral(-C*x*exp(-a*x**2 - sqrt(b)*x), x) + Integral(C*x*exp(-a*x**2 + sqrt(b)*x), x)
i.doit()
```

Output with sympy 1.12.1 (and older):

image

Output with sympy 1.13.1:

image

### LINKED ISSUE #26930: Simple integral evaluation broken in 1.13
Consider the following integral:

$$\int_0^1 x^{\frac{4}{3}} \ln x \\, \mathrm{d}x,$$

which equals to $-9/49$.<sup>*</sup> It works in previous versions &mdash; however, Sympy 1.13 returns this wildness:

```python
from sympy import Symbol, Rational, integrate

x = Symbol('x')
integrate(x**Rational(4, 3)*ln(x), (x, 0, 1)).simplify()
```

sympy_integral_wrong

Interestingly, if we choose `Rational(m,  n)` such that $m = kn, \\, k\in\mathbb{N}$, Sympy gives the right answer, e.g.:

```python
integrate(x**Rational(4, 2)*ln(x), (x, 0, 1))

>> -1/9
```

<br />
<sup>*</sup>We can generalize this integral so that it can be calculated using Feynman's trick (rather than by integration by parts):

$$I(t) := \int_0^1 x^t \ln x\\,\mathrm{d}x = \int_0^1 \frac{\partial}{\partial t}x^t\\,\mathrm{d}x=\frac{\mathrm{d}}{\mathrm{d}t}\int_0^1 x^t\\,\mathrm{d}x,$$

$$I(t) = \frac{\mathrm{d}}{\mathrm{d}t} \left[\frac{x^{t+1}}{t+1}\right]_0^1 = \frac{\mathrm{d}}{\mathrm{d}t}\left(\frac{1}{t+1}\right) \Rightarrow$$

$$\boxed{I(t) = -\frac{1}{(t+1)^2},\\,\\, t\gt-1.} $$

$$\int_0^1 x^{\frac{4}{3}} \ln x\\,\mathrm{d}x = I\left(\frac{4}{3}\right) = -\frac{9}{49}.$$

### PR DESCRIPTION
**Pull request by smichr**
#### References to other Issues or PRs

closes #26922 
closes #26930 
closes #26934 as alternative to reversion

cf #26358
#### Brief description of what is fixed or changed

Type of *expressions* (not the tuple containing the expression and replacement) are now permuted.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by smichr** [comment]
I am not sure how to backport for 1.13 -- I just opened the PR against 1.13

**Comment by oscarbenjamin** [comment]
> I am not sure how to backport for 1.13 -- I just opened the PR against 1.13

You need to start a new branch off of 1.3 and then cherry-pick the commits:
```
git fetch upstream
git checkout upstream/1.13
git checkout -b pr_branch
git cherry-pick <commit-sha>
<now open a PR against the 1.13 branch>
```
Probably easiest to cherry pick the commits one by one in order. Otherwise you can do a range like:
```
git cherry-pick <first-commit>^..<last-commit>
```

**Comment by smichr** [comment]
I wish we knew how to prevent people from being requested for review -- I didn't make any requests and yet @oscarbenjamin and @moorepants were selected.

**Comment by smichr** [comment]
will reopen later today against 1.13 per directions

**Pull request closed without merging**
