### PR TITLE
Add linsolve sphinx docs

### PR DESCRIPTION
**Pull request by aktech**
See #9438 

TODO:
- [x] Improve matrix rendering in sphinx docs.

@flacjacket  @hargup 

P.S : Latex Equations have not been added so as to facilitate reading docs from ipython.

### CODE REVIEW

**Comment by debugger22** [comment]
I built the docs. Is there a convention to put `.`? If not, it would look better without them. +1 otherwise.

**Comment by aktech** [comment]
> Is there a convention to put .?

Probably not.

**Comment by aktech** [comment]
@hargup
I have Fixed rendering of Matrix in docs using literal block.

**Comment by hargup** [comment]
> I have Fixed rendering of Matrix in docs using literal block.

The rendering looks good now. +1

**Pull request merged**
