### PR TITLE
Don't skip the tests in the coverage report

### PR DESCRIPTION
**Pull request by asmeurer**
Skipping the tests is a bad idea because you generally want to make sure the code in the test files is fully covered by tests (when it isn't there is generally some mistake, like a test that isn't actually being run for some reason). I haven't actually done this here to check if there is anything wrong with any of the test files. 

See also
https://nedbatchelder.com/blog/202008/you_should_include_your_tests_in_coverage.html

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
> I haven't actually done this here to check if there is anything wrong with any of the test files.

I'm currently unable to run the tests locally (one of the compilation tests segfaults), so it would be great if someone else could check this out.

**Comment by oscarbenjamin** [comment]
Personally I don't use this script for coverage measurement and use pytest instead e.g.:
```console
$ pytest sympy/polys/ -m 'not slow' -n3 --cov-report=html --cov sympy.polys
```

**Comment by asmeurer** [comment]
> Personally I don't use this script for coverage measurement and use pytest instead e.g.:

That's enough flags that it's worth having a helper script like this. We could also do things like require 100% coverage in (non-optional dependency) test files. 

I would also love to see this being generated on CI somewhere. We used to use codecov but I guess we stopped because the output was too annoying.

**Comment by oscarbenjamin** [comment]
> We used to use codecov but I guess we stopped because the output was too annoying.

More like when I migrated the CI over to GitHub Actions it was a lot of work on my part just to get the basics working. Having put a lot of time in myself just to keep the basic CI running I hoped that some other people might volunteer to do the bits that I hadn't done. No one else migrated the coverage so now there isn't any in GitHub Actions.

There were problems with Codecov like it was a bit flakey in some ways. It might have improved since then.

**Comment by asmeurer** [comment]
I never liked codecov because of those flakyness issues. I also never personally found it that helpful. 

I think just running the coverage and uploading the report to a CI artifact would be good enough. If someone cares, they can check it there. It's not really a high priority thing, though, and could be some work to get it all working (for instance, the tests run slower with coverage because of the overhead).

Good coverage is really a small thing. Code that is uncovered is obviously bad, but just because code is covered, there's no guarantees that it is actually tested well. In practice in SymPy it's very common for the same line of code to require multiple test cases to really cover all possible corner cases. Just as an example, any line that uses an assumption really ought to cover all three possible values of that assumption. And that doesn't even begin to consider whether the tests themselves are actually correct.

**Comment by oscarbenjamin** [comment]
> Good coverage is really a small thing. Code that is uncovered is obviously bad, but just because code is covered, there's no guarantees that it is actually tested well.

My interpretation of this is that 100% code coverage is basically the minimum level that should be expected. The one part of Codecov that was useful was the diff coverage. It clearly showed if a PR had new untested code. However it didn't necessarily update when the PR updated which then reduced its usefulness to contributors/reviewers/etc.

There are other possibilities like diff-cover:
https://pypi.org/project/diff-cover/

**Comment by oscarbenjamin** [comment]
I haven't tested this but let's get it in.

**Comment by oscarbenjamin** [comment]
> That's enough flags that it's worth having a helper script like this

Those flags are not all needed though. That's just me showing a typical usage for myself where e.g. I don't want to run all the tests in the codebase or consider coverage of everything etc. A script won't help with most of those flags because it won't know what I want the values for the flags to be.

**Pull request merged**
