### PR TITLE
Removed deprecation warning for swapped arguments in kanes_equations.

### LINKED ISSUE #10945: Deprecated kanes_equation method
The kanes_equation() under KanesMethod will be deprecated for a more ideal api in which the order of argument is switched from (loads, body) to (body, load). The reasoning is that sometimes there is no load therefore it makes more sense to have the body first and have an optional load. For details please see #10878.

### PR DESCRIPTION
**Pull request by moorepants**
#### Brief description of what is fixed or changed

Fixes #10945

This has been deprecated since version 1.1, so time to go.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by moorepants** [comment]
@sympy/mechanics

**Comment by oscarbenjamin** [comment]
Should this go in the 1.7 release?

**Comment by moorepants** [comment]
If it is simple to get in, sure.

**Comment by moorepants** [comment]
This is ready for review and merging if it is good to go.

**Comment by moorepants** [comment]
This is ready to go in. Likely, just needs a quick review and merge.

**Comment by jksuom** [comment]
Looks good to me.

**Pull request merged**
