### PR TITLE
Made true.isBoolean=True when true=BooleanTrue()

### LINKED ISSUE #8678: is_Boolean, you had one job!
Neither Boolean nor BooleanAtom define is_Boolean like BooleanFunction does.

This means that `true.is_Boolean` and `false.is_Boolean` are both false.

Recommended fix is to move is_Boolean from BooleanFunction to Boolean (from which it derives)

### PR DESCRIPTION
**Pull request by sahilshekhawat**
Fixes #8678

### CODE REVIEW

**Comment by smichr** [comment]
The issue said that `is_Boolean` could be removed from BooleanFunction. Did you try to do that? Does that comment still apply?

**Comment by sahilshekhawat** [comment]
Yes, I did checked https://github.com/rotu/sympy/commit/44f95e9b6ce791aafd2ead62f21b2d85d46a1c2a, this was introducing many bugs like ``x.is_Boolean==True``.

**Comment by smichr** [comment]
I did the same thing with my first attempt. How about the following, however:

```diff
diff --git a/sympy/logic/boolalg.py b/sympy/logic/boolalg.py
index d4e3fb8..8a92cd5 100644
--- a/sympy/logic/boolalg.py
+++ b/sympy/logic/boolalg.py
@@ -122,6 +122,8 @@ class BooleanAtom(Boolean):
     """
     Base class of BooleanTrue and BooleanFalse.
     """
+    is_Boolean = True
+
     @property
     def canonical(self):
         return self
@@ -241,7 +243,6 @@ class BooleanFunction(Application, Boolean):
     """Boolean function is a function that lives in a boolean space
     It is used as base class for And, Or, Not, etc.
     """
-    is_Boolean = True

     def __call__(self, *args):
         return self.func(*[arg(*args) for arg in self.args])
```

**Comment by sahilshekhawat** [comment]
This will also make ``sympify(False).is_Boolean == True`` as ``BooleanAtom`` is also the base class for ``BooleanFalse``

**Comment by smichr** [comment]
Yes, that's a good thing, I believe, since true and false are both Booleans. The current change only applies to true but it should apply to false, too:

```
>>> true.is_Boolean,false.is_Boolean
(True, False)
```

**Comment by aktech** [comment]
@sahilshekhawat 
Please squash commits (using git rebase), before pushing.

**Comment by sahilshekhawat** [comment]
I don't think I can squash commits in the same branch after pushing to remote without using force push

**Comment by aktech** [comment]
Yes, you can, using force push.
It is very important to have a cleaner git log.

**Comment by asmeurer** [comment]
Strictly speaking, Symbol *is* a Boolean. So x.is_Boolean == True is correct. So I'd say it should go on the Boolean class, and be removed from all subclasses.

**Comment by asmeurer** [comment]
Does x.is_Boolean == True lead to test failures?

**Comment by sahilshekhawat** [comment]
No, it doesn't. I checked it, seems correct. Shifted it to the base class.

**Comment by smichr** [comment]
> Strictly speaking, Symbol is a Boolean

I don't know about that (literally), but that seems odd. Isn't the definition of boolean an object that can have only one of two values? Any python object can be *converted* to a bool but that doesn't mean it is a bool anymore than 1 is a string (as opposed to '1'). Symbols can take on many values and thus by definition are not booleans, it would seem. Is there a distinction between 'boolean' and 'Boolean'?

**Comment by sahilshekhawat** [comment]
@asmeurer @smichr is ``x.is_Boolean == True`` correct or not? It does result in failing tests.

**Comment by smichr** [comment]
As I say in my previous comment, I don't think it's right since "x" can take on more than two values. I would be favorable to the change being made where I indicated.

**Comment by smichr** [comment]
You can remove `is_Boolean` from BooleanFunction, now, too.

**Comment by sahilshekhawat** [comment]
I tried it and it results in ``Or(x.y).is_Boolean == False``  for all  boolean functions.

**Comment by smichr** [comment]
I see. It derives from Application and BooleanAtom so I guess that's the problem. OK, then, this looks good to me. If @asmeurer thinks that symbols should report True for being booleans, a separate issue can be opened. Thanks for working on this. It's in.

**Comment by asmeurer** [comment]
This was done as a workaround (I don't remember what for exactly) until we create a separate BooleanSymbol class.

**Comment by asmeurer** [comment]
I guess it's to make the boolean operators (like `&` and `|`) work on Symbol, and to make Symbols not fail in any boolean function that requires Boolean instances.

**Pull request merged**
