### PR TITLE
Fix docs deployment in the release script

### LINKED ISSUE #19839: The docs page has older versions in the sidebar
See https://docs.sympy.org/latest/index.html. We removed the older versions from the sidebar, but the most recent releases added them back. There should only be "latest" and "dev". The version number on "latest" is also wrong.

### PR DESCRIPTION
**Pull request by asmeurer**
We no longer serve old versions of the docs in the documentation.

See also https://github.com/sympy/sympy_doc/pull/45.

Fixes #19839.

Note that this is untested. I think we can't really test this fully until we do another release. 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I've actually been using this script:
https://github.com/sympy/sympy/blob/master/release/update_docs.py

**Comment by asmeurer** [comment]
Hmm, OK. We need to remove the unused release stuff. The fabfile from the really old release script is still there too.

**Comment by oscarbenjamin** [comment]
I think it would be better to have the steps of the release script as standalone scripts so that they can be run manually or can be called as part of a script that automates everything. I think it would be good to have a process that can be done just by running a documented sequence of commands in order but can also be automated once all the steps are working.

I also broke out this from the release script:
https://github.com/sympy/sympy/blob/master/release/compare_tar_against_git.py
Having it as a separate script means I can run that check (and fix it) before running the main release script so I don't have to wait for the whole test suite to run before discovering a simple problem with the whitelist.

**Comment by asmeurer** [comment]
Rever already lets you do this, with the `-a` flag. But I also don't have strong opinions on how the release script looks like. The person doing the release has the prerogative to improve it as they best see fit.

**Pull request merged**
