### PR TITLE
Soc final fixed

### PR DESCRIPTION
**Pull request by haz**
As per discussion [0](http://groups.google.ca/group/sympy-patches/browse_thread/thread/4c0fb92639357c41) this branch, containing the modifications over the summer for Google's SoC program, is ready to be merged in. A number of iterations has already gone into getting it up to shape, but I'm open to more suggestions if there are any.

  Thanks. Cheers

### CODE REVIEW

**Comment by haz** [comment]
Lordy liftin'...I worked on this over a decade ago. Nice blast from the past!

> do you remember why in dpll2 clause_learning is set to None by default?

My best guess is that the simple method really performed poorly, and a more sophisticated approach to clause learning should be taken.

> What is 1UP?

1st UIP -- a particular way to do clause learning, and one that revolutionized the field ;). [This](https://www.cs.princeton.edu/courses/archive/fall13/cos402/readings/SAT_learning_clauses.pdf) seems to be a good intro to it.

For the record, if I was to approach this project again today, 100% I'd suggest integrating with [pysat](https://github.com/pysathq/pysat).

**Comment by TiloRC** [comment]
@haz thanks for your response!

I'm implementing a linear real arithmetic theory solver so the new assumptions can understand inequalities. I'm trying to understand how your dpll2 algorithm works so that I can connect my theory solver to it.

However, it does seem like there are improvements that can be made to the dpll2 algorithm. So I can bring some attention to them. Speed is still an issue for the new assumptions. 

> For the record, if I was to approach this project again today, 100% I'd suggest integrating with [pysat](https://github.com/pysathq/pysat).

I think SymPy wants to avoid having any hard dependencies and minisat and pycosat are already currently used if you happen to have those installed.

**Comment by haz** [comment]
Ah, ok. Then I'd probably be hesitent to spend too much elbow grease on having the native SAT solver improved for performance. The SAT community has built in multiple decades of insights into their solver, and it's essentially an exercise in trying to reproduce all of that effort if you want the high-performance. Just my $0.02.

Good luck with the integration!

**Comment by TiloRC** [comment]
> Good luck with the integration!

Thanks!

**Pull request merged**
