### PR TITLE
1

### PR DESCRIPTION
**Pull request by ghost**
A circle which is the locus of all points from which two perpendicular tangents may be drawn to the conic is called a Director Circle

#### Brief description of what is fixed or changed
Added Director Circle Feature for Ellipse

#### Other comments

> Help to improve Director Circle Feature if their is any error or wanted to add something in this Feature

#### Release Notes

* geometry
  * Added Director Circle Feature for Ellipse

### CODE REVIEW

**Comment by jimmygraviton** [comment]
can anyone guide me about my program that what wrong i have done. This is my first PR. I would obliged if you give some hint to what i have to change to my program @asmeurer @Sumith1896 @smichr @certik

**Comment by certik** [comment]
Look into the tests (click the red cross), find one that failed, for example this one:

https://travis-ci.org/sympy/sympy/jobs/421127248

and see if you can figure out from the failure what is wrong. It looks like you might need to change `x = _symbol(x, real=True)` to `x = _symbol("x", real=True)` to fix one of the errors.

**Comment by jimmygraviton** [comment]
but if i go to the error how can i find what things are mising which error are occured by which things @certik

**Comment by jimmygraviton** [comment]
i tried but cannot figure out the what error i have done please guide me @certik @asmeurer @Sumith1896 @avishrivastava11 @smichr @sylee957 @jksuom

**Comment by certik** [comment]
@Abdullahjavednesar if you have time, would you please help @jimmygraviton figure it out?

**Comment by sylee957** [comment]
I think that your error suggests that your example code in docstring should match how you literally get in your python shell.
However another problem of this PR would be, you're using same code from #15148

**Comment by jimmygraviton** [comment]
@sylee957 which example code what is doctring what i have to write

**Comment by certik** [comment]
Uh, @jimmygraviton did you just copy the code from #15148?

**Comment by jimmygraviton** [comment]
no @certik  my code is different from that i have seen his code, i just taken the idea of director circle

**Comment by certik** [comment]
@jimmygraviton unfortunately, you cannot copy other people's code like that. This is the original code from #15148:
```python

        x = _symbol(x, real=True)
        y = _symbol(y, real=True)
        t1 = (x - self.center.x)**2
        t2 = (y - self.center.y)**2
        dc_radius = self.hradius**2 + self.vradius**2
        return  t1 + t2 - (dc_radius) 
```
and this is your code, as implemented in e4aaba538c10accba0fd0b87ddafcd6605026cc3:
```python

        x = _symbol(x, real=True)
        y = _symbol(y, real=True)
        j1 = (x - self.center.x)**2
        j2 = (y - self.center.y)**2
        dc_radius = self.hradius**2 + self.vradius**2
        return  j1 + j2 - (dc_radius) 
```
but unlike in #15148, you didn't define the `x` and `y` and that's why your commit e4aaba538c10accba0fd0b87ddafcd6605026cc3 failed, as I pointed out above. As you can see, the code is identical.

So I am going to close this PR. If you want to contribute, you have to write your own code, or you have to obtain permission from others to use their code. You cannot just go to some open PR and copy code from there without giving attribution.

**Comment by jimmygraviton** [comment]
okz @certik i am new to git thank you sorry

**Comment by certik** [comment]
@jimmygraviton no problem, it was your first PR. In open source, but in general in life also, if somebody else creates something, and you use it, you have to make sure to give attribution/credit. And in this case, the person in #15148 wants his code to be merged, so it's not nice to copy his code and try to get your PR to get merged first. The right way to do is to help #15148 to get merged first, and then you can build on top, for example you can improve the docstring, or test, etc.

We are happy to help you with git, or github or Python.

**Comment by Abdullahjavednesar** [comment]
@jimmygraviton if you have a different (preferably better) approach you can surely put that forward.

**Pull request closed without merging**
