### PR TITLE
1.3 release branch

### PR DESCRIPTION
**Pull request by asmeurer**
Do not merge until after the release is made. 

Any changes for this release should be made as pull requests to the `1.3` branch. Only critical changes should go to this branch. Normal changes should go against `master` as usual. 

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
Getting a doctest failure in combinatorics:

```
File "/root/sympy/sympy/combinatorics/homomorphisms.py", line 466, in sympy.combinatorics.homomorphisms.group_isomorphism
Failed example:
    T(b*a*b**-1*a**-1*b**-1)
Expected:
    (0 2 3)
Got:
    Permutation([2, 1, 3, 0])
```

**Comment by asmeurer** [comment]
@valglad @RavicharanN any idea what's going on? It seems it's printing differently than expected (`Permutation(...)` instead of `(...)`), but also giving a different answer. I have not yet been able to reproduce it. The doctests don't print the random seed unfortunately. Could it be related to that?

**Comment by asmeurer** [comment]
I believe the different output is caused by different doctests setting the `print_cyclic` flag (https://github.com/sympy/sympy/blob/master/sympy/combinatorics/permutations.py), meaning this doctest is affected depending on what is run before it. Doctests shouldn't be setting global flags. 

Such a flag probably shouldn't exist in the first place, but that's a separate issue. The module ought to be using the SymPy printing system, which has flags that get set, and doctests that want to modify the defaults can use `init_printing()` with the flags to modify only that doctest.

**Comment by asmeurer** [comment]
This reproduces the issue

```
doctest('perm', subprocess=False)
doctest('homo', subprocess=False)
```

**Comment by asmeurer** [comment]
To clarify, in the docker container where we build the release, the doctests are run out of order, because the filesystem lists the files in a semi-random order. I thought this was the case on Travis too, but I guess it uses a different file system. This does occur on many Linux filesystems, though. 

If the permutation printers are refactored to use a real printer and init_printing as I suggested, this will go away, because of a fix I just pushed here that resets the printing settings between each doctest run. It would also mean the flag doesn't need to be set on any doctest that sets it to the default (assumedly most of them). A quicker fix for now would probably be to set that flag on the homomorphisms doctest as with the other doctests. 

To whoever fixes this, please make sure you make your PR against the `1.3` branch.

**Comment by asmeurer** [comment]
This should be merged as soon as it goes green.

**Comment by asmeurer** [comment]
And delete the branch (or I might have to do it).

**Comment by valglad** [comment]
The test failures are because `release.py` doesn't end with a newline. The branch's not letting me commit directly to it so it'll probably be easiest for you to do it, @asmeurer

**Comment by asmeurer** [comment]
That's what I get for merging with the GitHub interface.

**Comment by cbm755** [comment]
I tried switching my origin remote to https:// but it still doesn't let me delete the 1.3 branch: so I guess @asmeurer has to.

**Comment by cbm755** [comment]
Oops, I mean to `git://`

**Comment by ashishkg0022** [comment]
$zsg

**Pull request merged**
