### PR TITLE
added implementation of Carmichael and Euler pseudo-prime numbers

### PR DESCRIPTION
**Pull request by avishrivastava11**
added implementation of `carmichael numbers` and `euler pseudoprime` numbers.

added class `carmichael` in `sympy/functions/combinatorial/numbers.py` and corresponding tests
added method `is_euler_pseudoprime` in `sympy/ntheory/primetest.py`

Closes  #14473
Please take look and suggest improvements. Thanks.

#### Release Notes

* functions
   * added class `carmichael` in `sympy/functions/combinatorial/numbers.py`
   * added tests - `test_carmichael` in `sympy/functions/combinatorial/tests/test_comb_numbers.py`
   * added class `carmichael` in `sympy/functions/combinatorial/__init1__.py`
* ntheory
   * added method `is_euler_pseudoprime` in `sympy/ntheory/primetest.py`

### CODE REVIEW

**Comment by sidhantnagpal** [comment]
There has been work done on this in #14473. Do you intend to reuse that code?

**Comment by avishrivastava11** [comment]
@sidhantnagpal  Yes. I had seen that PR and since it had been left unattended for quite sometime, and because it interested me, I decided to take it up.

**Comment by avishrivastava11** [comment]
But since work has been started there, I'll close this now.

**Comment by sidhantnagpal** [comment]
You should retain the original commits and reference the PR in the description.

**Comment by avishrivastava11** [comment]
@sidhantnagpal 
>reference the PR in the description.

I've done that now. Thanks for bringing it to my notice.

>You should retain the original commits

You mean the commits in #14473 ? how do i do that?

**Comment by avishrivastava11** [comment]
@sidhantnagpal  Can you take a look now?

**Comment by asmeurer** [comment]
Is this based on https://github.com/sympy/sympy/pull/14473 or rewritten from scratch? If it's based on https://github.com/sympy/sympy/pull/14473, you should rebase your branch so it includes those commits, so that the authorship of both people is included in the git history.

**Comment by asmeurer** [comment]
I believe the easiest way to do this is to use the `--onto` flag of `git rebase`. However, that flag is confusing and easy to get wrong, so I suggest testing it in a test branch first before applying it to this one.

**Comment by avishrivastava11** [comment]
@asmeurer  @sidhantnagpal  I've added the commits of #14473
and then my own commits on top. Hope this fulfils your suggestion.
Please take a look.

**Comment by avishrivastava11** [comment]
@moorepants  Can you take a look? I think this would be quite an important functionality for sympy. If the changes are agreeable and look good, please merge.

**Comment by moorepants** [comment]
I'm not qualified to review the mathematical aspects of this. I recommend asking someone that has done work in this module.

**Comment by avishrivastava11** [comment]
@moorepants  Sure. Can you recommend someone who can review this?

**Comment by moorepants** [comment]
I can't. Use git blame to find out who has worked on different parts of sympy.

**Comment by avishrivastava11** [comment]
@smichr Can you take a look?

**Comment by avishrivastava11** [comment]
@certik @sidhantnagpal @jksuom   Can you take a look?

**Review by certik — CHANGES_REQUESTED** [review]
This implements Carmichael numbers, and tests seem thorough.

Can you please also add tests for the `is_euler_pseudoprime` function?

**Comment by certik** [comment]
After that I think it can be merged.

**Comment by avishrivastava11** [comment]
@certik  Ping.
@sidhantnagpal @Abdullahjavednesar  If this looks good enough, please merge.

**Comment by avishrivastava11** [comment]
@certik  Ping.
@sidhantnagpal @Abdullahjavednesar  If this looks good enough, please merge.

**Comment by avishrivastava11** [comment]
@certik  Ping.
@sidhantnagpal @Abdullahjavednesar  If this looks good enough, please merge.

**Comment by avishrivastava11** [comment]
@certik  Ping.
@sidhantnagpal @Abdullahjavednesar  If this looks good enough, please merge.

**Review by certik — APPROVED** [review]

**Comment by certik** [comment]
That looks good, thank you!

**Pull request merged**
