### PR TITLE
Testing: See what happens when Symbol.is_finite is True by default

### PR DESCRIPTION
**Pull request by asmeurer**
See issue #17224.

This should not be merged without discussion first. I just want to see what Travis tests fail. 

CC @oscarbenjamin

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Does this work for Dummy as well?

**Comment by asmeurer** [comment]
Yes, it looks like Dummy also inherits this from Symbol correctly:

```
>>> Dummy('x').is_finite
True
```

**Comment by asmeurer** [comment]
Looks like this isn't quite the right way to do this:

```pytb
>>> Symbol('x', infinite=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/core/symbol.py", line 237, in __new__
    return Symbol.__xnew_cached_(cls, name, **assumptions)
  File "./sympy/core/symbol.py", line 259, in __new_stage2__
    obj._assumptions = StdFactKB(assumptions)
  File "./sympy/core/assumptions.py", line 242, in __init__
    self.deduce_all_facts(facts)
  File "./sympy/core/facts.py", line 522, in deduce_all_facts
    if not self._tell(k, v) or v is None:
  File "./sympy/core/facts.py", line 493, in _tell
    raise InconsistentAssumptions(self, k, v)
sympy.core.facts.InconsistentAssumptions: {
        algebraic: False,
        composite: False,
        even: False,
        finite: False,
        imaginary: False,
        infinite: True,
        integer: False,
        irrational: False,
        negative: False,
        nonnegative: False,
        nonpositive: False,
        nonzero: False,
        odd: False,
        positive: False,
        prime: False,
        rational: False,
        real: False,
        transcendental: False,
        zero: False}, finite=True
```

The change should probably go in `__new_stage2__`, which is where the `commutative` default goes. I don't know if there is an elegant way to guard against facts that use `finite` or if we just need to hard-code to not set `finite` if `infinite` is set.

**Comment by asmeurer** [comment]
A lot of test failures from things expecting relationals with `x < oo` in them. 

Some more interesting failures in the second test run. 

```
_______________________________________________________________________________
___________ sympy/sets/tests/test_conditionset.py:test_subs_CondSet ____________
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/utilities/runtests.py", line 1308, in _timeout
    function()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/sets/tests/test_conditionset.py", line 115, in test_subs_CondSet
    ).subs(n, x) == ConditionSet(x, x < y, S.Integers)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/core/basic.py", line 999, in subs
    rv = rv._subs(old, new, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/core/basic.py", line 1111, in _subs
    rv = self._eval_subs(old, new)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/sets/conditionset.py", line 220, in _eval_subs
    '''))
ValueError: 
A dummy symbol can only be replaced with a symbol having the same
assumptions or one having a single assumption having the same
commutativity.
________________________________________________________________________________
__ sympy/solvers/tests/test_inequalities.py:test_solve_univariate_inequality ___
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/solvers/inequalities.py", line 473, in solve_univariate_inequality
    expr = expr.xreplace({_gen: gen})
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/core/basic.py", line 1189, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/core/basic.py", line 1211, in _xreplace
    return self.func(*args), True
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/core/relational.py", line 650, in __new__
    r = cls._eval_relation(lhs, rhs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/core/relational.py", line 974, in _eval_relation
    return _sympify(lhs.__lt__(rhs))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/core/expr.py", line 406, in __lt__
    raise TypeError("Invalid comparison of complex %s" % me)
TypeError: Invalid comparison of complex _gen - I
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/utilities/runtests.py", line 1308, in _timeout
    function()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/solvers/tests/test_inequalities.py", line 315, in test_solve_univariate_inequality
    raises(ValueError, lambda: isolve(x - I < 0, x))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/utilities/pytest.py", line 83, in raises
    code()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/solvers/tests/test_inequalities.py", line 315, in <lambda>
    raises(ValueError, lambda: isolve(x - I < 0, x))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/solvers/inequalities.py", line 478, in solve_univariate_inequality
    '''))
TypeError: 
When gen is real, the relational has a complex part which leads to an
invalid comparison like I < 0.
```

I probably won't work on this more, so feel free to pick up the work if you want to see this finished.

**Comment by hewhodares** [comment]
Please don't do this.

**Comment by oscarbenjamin** [comment]
> Please don't do this.

Why not?

Would you be happy with this as an alternative:
```julia
In [16]: 0*Symbol('x')
Out[16]: 0⋅x
```

**Comment by asmeurer** [comment]
@hewhodares this is still up for discussion, so please elaborate why you think it's a bad idea. I'm personally not yet convinced about it either way (but please discuss the general idea on the issue, and only implementation details here on this PR).

**Comment by jksuom** [comment]
How should we define a `not_necessarily_finite` symbol if `finite` is made the default?

**Comment by asmeurer** [comment]
We should make it so that `Symbol('x', finite=None)` and `Symbol('x', infinite=None)` both work. In this current branch they don't.

**Comment by oscarbenjamin** [comment]
There are other cases to consider like `Symbol('x', extended_real=True)` probably should not have finite=True. I was thinking that this is most useful simply as a general default when no assumptions are provided i.e. special casing the default `Symbol('x')` since most assumptions either imply finite or are explicitly intended to allow infinite. I've listed all cases from the core assumptions below.

These are obviously related to finite:
```
finite
infinite
```
These assumptions imply finite:
```
integer
rational
real
algebraic
transcendental
imaginary
odd
even
negative
zero
positive
nonnegative
nonpositive
nonzero
prime
composite
irrational
```
These assumptions do not imply finite:
```
complex
hermitian
antihermitian
extended_real
extended_negative
extended_positive
extended_nonnegative
extended_nonpositive
extended_nonzero
noninteger
```
That's all assumptions except for commutative which is handled differently anyway.

I think complex will move into the finite camp at some point possibly leaving extended_complex in its place. Probably hermitian, antihermitian and noninteger can all be moved to the finite camp as well. At that point the only times a symbol declared with foo=True would not be finite is for the `extended_*` assumptions that are there to explicitly allow infinities (and of course the `infinite` assumption).

So I would suggest that a plain `Symbol('x')` should become finite=True but otherwise if any assumptions are specified then we leave the situation as it currently is.

The awkward question in that scenario would be what to do with something like `Symbol('x', real=False)` or `Symbol('x', extended_real=False)`. Maybe finite should be considered the default of no other assumption is specified as True.

**Comment by asmeurer** [comment]
I think the ones that imply finite aren't a problem. If they are set to True then finite will be True, which it already is by default. If they are set to False then the default finite=True is still valid. And if they are set to None then finite=True does not contradict that. The issue would be anything that finite implies, or equivalently anything that implies !finite, which is just `infinite`.

Actually something that worries me is that finite seems like it ought to mean finite complex. So any non-number assumptions contradict with it. I don't know if that is the case with the facts as we have them now.

**Comment by hewhodares** [comment]
I don't know how to quote and I don't use github (I'm not sure why I have this account but it was signed in) but to answer your question:

Because you have users. 

Like me and a fair few people and projects I know that offload or use sympy.

It is unfair to expect users to keep an eye on such big changes and voice opposition, this will break compatibility and is a relatively big change - the onus is on you to to weight the options and costs of each and decide rationally. 

By all means introduce new helpers that when used set this flag, whatever - just please don't break existing stuff, this is not an instance of strength reduction, this is a change to symbols.

I don't check that often - please play devil's advocate amongst yourselves on this and in future.

**Comment by hewhodares** [comment]
Put differently I should not and don't want to represent (even my local part) of the community that bothered to understand their tools and read the manual ect, or any of those that read different manual versions and compare them, and don't just install it and trust.

It's by dumb luck I spotted this.

**Comment by hewhodares** [comment]
After 30 seconds of thought prepare to have your mind blown!

RealSymbol, FloatSymbol, RationalSymbol, IntegerSymbol, NonNegativeIntegerSymbol .....
RealExtendedSymbol, .....

ect

**Comment by hewhodares** [comment]
No idea how you are quoting, but with the 0.x thing - yes! There are a fair few kiddy-cas interfaces to sympy already. They have no problem with this sort of thing. They'll keep doing what they do using people who know the internals.

Learning curves are not helped by "let's keep them on their toes!" - as sympy has become more general this question was bound to come up and 0*x is the only realistic answer to start with, as more information is GIVEN refine it.

**Comment by oscarbenjamin** [comment]
@hewhodares you haven't given any example of why this would be bad.

It seems that you are saying that the problem is this shouldn't happen is it is a break with backwards compatibility. Looking through the test results though it seems that very little "breaks" as a result of this. On the other hand you seem to be okay with `0*Symbol('x')` not evaluating which is also not backwards compatible. I expect that would cause far more breakage.

**Comment by hewhodares** [comment]
@oscarwhatever - pass. You're not going to get a revolt from the 12 people who'd notice this and are not in this thread, and if you are naive enough not to be able to think for yourself about such an issue beyond "it passes the test" then it's unfortunate that we 13 people got caught in your learning curve.

If you want to be tutored do not expect me to read through what you think and other minutia to go "oh that's what was meant" and correct it. I side-step investing more time by saying "read books on maintaining software and API design, find postings and papers done by practitioners ect ect, this only comes with experience.

Lastly fixing broken things is seldom considered a break. I also remind you that exceptions and warnings are for exceptional thing and for things that merit warning the user.

Should you want to lock on and make this about the words "not evaluate" I am confident that you'll find a way to interpret that which makes sense, and remind you that evaluation is difficult and heuristic, and I believe in general unsolvable. I am of course talking about equality and expressions /evaluating/ (or not!) to 0. 

The blunt tone is to strengthen the correction I'm trying to apply here, I am happy to help if you want resources, or to ask me if a resource is good, or to confirm (general software....) weightings given to various points and counter-points. I seriously doubt there's some profound insight to using free variables in this but should I be wrong I look forward to a future where I don't go through so much paper and of course will give you an owed apology. I wouldn't expect this if I were you.

Feel free to message me or something - not a githubber but I imagine there are notifications I would see if you did.

**Comment by asmeurer** [comment]
@hewhodares please read our code of conduct https://github.com/sympy/sympy/blob/master/CODE_OF_CONDUCT.md. There is no excuse to not be civil and polite on the SymPy forums.

**Comment by certik** [comment]
@hewhodares please be nice to other SymPy developers. You have a good point about not breaking other people's codes that depend on SymPy and you also have a point that there are lots of users of SymPy who will not notice such changes, and don't have time to be vocal, etc. That's all true and you are welcome to raise such issues, but please do that politely and respectfully.

**Comment by hewhodares** [comment]
Not sure how you can say what I said was nasty, if you really feel that'll somehow help the situation please expand on that? (this is not sarcasm) - but otherwise I stand by what I said. 

Play it out in your head, option 1: there's some brand new way of dealing with free variables that no one anywhere has thought of before that can take us out of the dark ages of teaching and using with paper everywhere. 

Option 2....

**Comment by hewhodares** [comment]
RE the link to read, I skimmed it but I see nothing about the topic at hand.

**Comment by hewhodares** [comment]
RE the link to read, I skimmed it but I see nothing about the topic at hand.

**Comment by certik** [comment]
@hewhodares here is an example of what you said that could be perceived as not respectful towards @oscarbenjamin:

> If you want to be tutored do not expect me to read through what you think and other minutia to go "oh that's what was meant" and correct it.

Next time, please don't make it personal, simply assume the best intentions of everybody involved, and discuss the technical merits, like not breaking backwards compatibility and other things.

Thank you.

**Comment by oscargus** [comment]
I think this a valid issue and what I am primarily worried about: #17258 

Ideally, SymPy should eventually complain upon initialization. Here, the user wants to perform a summation with an integer (and therefore finite) symbol, which is the set to go from `-oo`. Sums and Integrals are typical cases where you want to put "normal" constraints on a variable, but still include `oo`. Yes, there are `extended_real`  and one could define `extended_integer`, but it turns out to be quite a few `extended_*`.

I cannot really see what impact it does have in practice to make Variables finite by default. I mean, x*0 is 0 at the moment. There are the discussions about `x*(x+1) >= x**2 + x` (or if it is vice versa, I do not really understand the fundamentals).

The potential problem I see is that people do a lot of work and then let a variable be oo, instead of letting it go towards oo.

On the other hand, I must say that setting assumptions upon initialization is a rather nice approach. Much better compared to refine expressions, provided in every call, or let variables with assumptions print differently so that they cannot be copied and pasted easily as some of the commercial alternatives.

So:
1. How many more `extended_classes` are needed? `extended_integer` for sure. Probably `extended_imaginary` (since a `complex` may be infinite it makes sense).
2. As variables are complex (unless otherwise stated), it is not clear how making them finite works out. I'm tempted to add `extended_complex`.
3. How will integrals, summations, and products with oo be handled?
4. For summations, will something more happen than just replacing every is_integer with is_extended_integer?
5. Will there also be a check in subs for not doing substitutions that breaks the assumptions? 

I think these are things to consider in the discussion.

The upside, as I see it, is that expressions can be simplified, especially relations. However, not sure if it is better to get a more complicated expression that one later on can recompute when one realizes that it is possible to set the variables to finite vs getting a simpler expression that isn't correct for infinite values...

**Comment by asmeurer** [comment]
@hewhodares if you really are interested in following our code of conduct, I suggest you reflect on what you wrote and how it is disrespectful to both Oscar and the SymPy community at large. I count three insulting things in your first paragraph alone (and zero useful things---the entire paragraph could be deleted without removing anything from the technical point you are trying to make).

If you are not interested in being respectful and following our community guidelines, then you should stop posting here.

I'm willing to give you the benefit of the doubt here that you wrote what you wrote in frustration, but the choice is yours now whether to apologize or to double down. If you chose the latter please be aware of our [code of conduct enforcement guidelines](https://github.com/sympy/sympy/blob/master/CODE_OF_CONDUCT.md#enforcement).

Regarding this pull request, let's move the **technical** discussions over to the issue #17224. This pull request achieved what I wanted, which was to see what tests failed if this was enabled. I don't intend to finish the pull request myself, both because I'm not yet convinced it's a good idea and because I don't have the time. So if it's going to be done someone else will need to do it, which will require a new pull request anyway.

**Comment by hewhodares** [comment]
I think what I said was reasonable, it's not as if this topic is new ground - it /is/ unreasonable to expect me to tutor you, this is why we have lectures, I don't have to care (or pretend to, or worry about feelings) when I lecture, I don't have to worry about the rights or wrongs of each's conceptions, I just give them the correct stuff and they integrate it.

Now I am tutoring you about feelings - well outside of my comfort zone - what more of a gesture of good faith could you want? 

-------------------------------------------------------

For the extended stuff, indeed there is! Welcome to type theory, it sucks doesn't it.

I, as I am sure we all do, long for something better than paper, but here is why we don't have it, there are also variations on "extended" - for example single infinity point and stereographic projections (this comes from closure in topology)

I don't have time to go into it now, but there are strong reasons (and proofs that can be offered once we have definitions in place) to only "add" attributes to types, never say "X without Y" only "U with V") based on ending up with things that don't or can't exist. 

And if you extend a types far enough you end up with something equiv to theorem provers which are also, shall we say "very hard" computationally.

**Comment by certik** [comment]
@hewhodares has been blocked for repeated violation of our CoC.

**Pull request closed without merging**
