### PR TITLE
Fixing misformatting of polarization docs

### PR DESCRIPTION
**Pull request by JSenart**
#### Brief description of what is fixed or changed

The formatting of the documentation in the examples page was broken in the lines you present the python console for the stokes vector. Looking at the remaining markdown it seems like this will fix it.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Review by bertiewooster — CHANGES_REQUESTED** [review]
The changes you make seem to fix the problem you identified of the code blocks being misformatted. Nice work!

One additional thing I noticed on this page is that the parameter names in function signatures appear with double backticks around them, for example [theta](https://output.circle-artifacts.com/output/job/4a44193b-c681-4ab0-aed3-c0ec8c63959c/artifacts/0/doc/_build/html/modules/physics/optics/polarization.html#sympy.physics.optics.polarization.half_wave_retarder). I haven't written such entries so I'm not sure, but just going by [another file in the same directory](https://github.com/sympy/sympy/blob/master/sympy/physics/optics/gaussopt.py#L240) that the double backticks should be removed.

**Comment by JSenart** [comment]
> 
Fixed the back tick incongruence here and in all files I could find. I did separate commits in case the remaining files change in unwanted

**Comment by bertiewooster** [comment]
The double backticks surrounding parameter names no longer appear, which is definitely good. I'm not sure whether those backticks were supposed to do something to the parameter names or other strings. For example, [in the live page, in the description of jones_2_stokes, the symbol e at the end of the sentence](https://docs.sympy.org/latest/modules/physics/optics/polarization.html#sympy.physics.optics.polarization.jones_2_stokes) appears in (something like) italics, whereas [in this pull request the e appears with a gray box around it as for code](https://output.circle-artifacts.com/output/job/4c30f65d-7a55-49a0-96d7-031649bdd729/artifacts/0/doc/_build/html/modules/physics/optics/polarization.html#sympy.physics.optics.polarization.jones_2_stokes).

Request advice from someone with experience writing function docstrings such as @asmeurer or @smichr.

**Comment by asmeurer** [comment]
I think this is right now.

**Review by bertiewooster — APPROVED** [review]

**Pull request merged**
