### PR TITLE
series/limits : added some test cases for limits of some discontinuous functions with undefined limit as x approaches infinity

### LINKED ISSUE #14276: limit_seq(log(sin(n))) is log(<-1, 1>)

### PR DESCRIPTION
**Pull request by Xenon1019**
#### References to other Issues or PRs
closes #14276 

#### Brief description of what is fixed or changed
added the test cases for the limits in which function is periodically discontinuous for interval of non-zero length as `x` tends to `infinity`. See #23087 for the detailed discussion.

#### Release Notes

* series
  * added test cases for limits where function is discontinuous as `x` tends to `infinity`

### CODE REVIEW

**Comment by anutosh491** [comment]
LGTM .  Maybe the tests could be made to something like `assert isinstance(limit(sin(n)**cos(n), n, oo, dir='-'), Limit) ` as currently  sympy only tries to return back outputs for any `Limit(......).doit()` call in three forms (anything else might be an error) .
Those are 
1) the value of the limit
2) A `NotImplementedError`
3) A `Limit` object only while returning `self` 
So there's no need to equate too , just checking the instance is sufficient. Maybe this could be changed in other places too where we have such tests !

**Comment by anutosh491** [comment]
@oscarbenjamin this looks ready to me , could you have a look !

**Comment by anutosh491** [comment]
hello @oscarbenjamin this looks good to me , could you merge this after having a look, just a simple test !

**Comment by oscarbenjamin** [comment]
It is usually best not to ask for a review from a particular person as it potentially discourages other people from reviewing something.

Can the commits here be squashed? We don't need 4 merge commits just to add a few lines of code. (I don't see any reason why there were any merges at all)

**Comment by anutosh491** [comment]
Hello @Xenon1019 , would you mind squashing the commits here ? The issue can then be closed before the new release .

**Comment by anutosh491** [comment]
This has been fixed by #23963 , hence closing.

**Pull request closed without merging**
