### PR TITLE
solveset(log(x)/x <= 0, x, S.Reals) ->(0, oo) instead of (0, 1]: #12429

### PR DESCRIPTION
**Pull request by maurogaravello**
I tried to fix the bug  #12429. 

I think that the problem is in the line 104 of solveset.py.
Sympy can't invert the function log(x)/x. In this case the method returns as 's' the value '0',
i.e. the rhs of equation log(x)/x=0. So s.intersection(domain) has not sense in this situation.
I added a test to check whether the result is an inversion. Probably it is not the best way,
but it seems to work.

### CODE REVIEW

**Comment by smichr** [comment]
Looks good to me. Let's see what tests and others have to say.

**Comment by smichr** [comment]
Does this work in this branch: `var('n', positive=True); (log(n)/n**3).is_convergent() is S.true`?

**Comment by maurogaravello** [comment]
Do you mean to check if the `\sum_{n=1}^{\infty} log(n)/n**3` is convergent for sympy? In such a case the following code 

> from __future__ import division, print_function
>
> 
> from sympy import *
> 
> 
> var('n', positive=True)
> 
> expr = log(n)/n**3
> 
> s = Sum(expr, (n,1,oo))
> 
> print(s.is_convergent())
> 

returns 
`NotImplementedError: The algorithm to find the Sum convergence of log(n)/n**3 is not yet implemented`

**Comment by plonter99** [comment]
I think this solution avoids the intersection only in case the first output of _invert_real/complex is the same as the input function. But, there are other cases where such intersection does not make sense. The result of invert may be neither the input function, nor 'x'.
For example:

invert_real(exp(x**2+x-6),1,x,Interval(0,7))
(x**2 + x, {6})
invert_real(exp(x**2+x-6),1,x,Interval(0,5))
(x**2 + x, EmptySet())

and further:

solveset(exp(x**2+x-6)-1,x,Interval(0,7))
{2}
solveset(exp(x**2+x-6)-1,x,Interval(0,5))
EmptySet()

Which is, of course, wrong, since 2 is in both intervals.
I think the intersection **should** be done, though not with the domain, but rather with the image set of the function returned from _invert_real/complex.

**Comment by smichr** [comment]
So do you think what you have done has merit in itself or do you want to change more?

**Comment by maurogaravello** [comment]
I think that the observations of plonter99 are correct.
My solution should correct the case in which the inversion does not work at all, in the sense that it returns the original function. So I think that it improves the inversion method, even if the method itself does not work properly.
Also the intersection with the image could have some problems.

**Comment by smichr** [comment]
baby steps...let's get this much in, then.

**Comment by maurogaravello** [comment]
@smichr Thank you! I opened the PR  #12458 for the convergence of the series
`\sum_{n=1}^{\infty} log(n)/n**3` according to your observation.

**Pull request merged**
