### PR TITLE
Remove autosimp from exp

### PR DESCRIPTION
**Pull request by debugger22**

### CODE REVIEW

**Comment by debugger22** [comment]
@asmeurer Please review this.

**Comment by debugger22** [comment]
@aktech @gxyd Two xpassed tests on this branch.

```
________________________ xpassed tests _________________________
sympy/solvers/tests/test_solveset.py: test_real_imag_splitting1
sympy/solvers/tests/test_solveset.py: test_only_exp_2
```

**Comment by aktech** [comment]
Yeah, I forgot to unXFAIL those after the PR #9628 but now it has been taken care of here: #9784

**Comment by debugger22** [comment]
Alright.

**Comment by debugger22** [comment]
@asmeurer This one is ready I think.

**Comment by asmeurer** [comment]
Great. This is a pretty simple start to this sort of change, so it should be a good place to view people's reactions against it.

**Pull request merged**
