### PR TITLE
Added hyperlinks to AUTHOR and LICENSE files

### PR DESCRIPTION
**Pull request by shubhayu09**
#### References to other Issues or PRs
Fixes #21963

#### Brief description of what is fixed or changed
I have added the hyperlinks of two files in README.md

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
This looks good. I don't know why the release notes bot didn't run.

**Comment by asmeurer** [comment]
> I don't know why the release notes bot didn't run.

Some 404 in the logs. It seems spurious. It ran after I updated the OP, and it hasn't errored on any other PRs.

**Comment by ThePauliPrinciple** [comment]
> This looks good. I don't know why the release notes bot didn't run.

Maybe because the OP removed all the formatting from the first post and the bot can not parse it now?

**Comment by shubhayu09** [comment]
> This looks good. I don't know why the release notes bot didn't run.

Hey, @asmeurer 
 I have also added the release notes now, so will it be possible to merge my PR, or do I have to do something else to clear this bot/release-notes check.

**Comment by ThePauliPrinciple** [comment]
Make sure the original post has this and then please read thoroughly and fill in:
```
<!-- Your title above should be a short description of what
was changed. Do not include the issue number in the title. -->

#### References to other Issues or PRs
<!-- If this pull request fixes an issue, write "Fixes #NNNN" in that exact
format, e.g. "Fixes #1234" (see
https://tinyurl.com/auto-closing for more information). Also, please
write a comment on that issue linking back to this pull request once it is
open. -->


#### Brief description of what is fixed or changed


#### Other comments


#### Release Notes

<!-- Write the release notes for this release below between the BEGIN and END
statements. The basic format is a bulleted list with the name of the subpackage
and the release note for this PR. For example:

* solvers
  * Added a new solver for logarithmic equations.

* functions
  * Fixed a bug with log of integers.

or if no release note(s) should be included use:

NO ENTRY

See https://github.com/sympy/sympy/wiki/Writing-Release-Notes for more
information on how to write release notes. The bot will check your release
notes automatically to see if they are formatted correctly. -->

<!-- BEGIN RELEASE NOTES -->

<!-- END RELEASE NOTES -->
```

**Comment by shubhayu09** [comment]
> 
Thanks,
I have edited my description now as you can see, so will it be sufficient or do I have to commit again the same changes and then write a new description with release notes.

**Comment by ThePauliPrinciple** [comment]
> > 
> 
> Hey @asmeurer , Now I have done all the required changes in the description with the new commit it's still failing in the bot checking test, you can kindly review and merge it if possible.

It is not yet correct, please try to be more precise. Don't remove anything from the template and fill in the required information in the right places.

For further reference read https://github.com/sympy/sympy/wiki/Writing-Release-Notes and https://github.com/sympy/sympy/wiki/Development-workflow thoroughly.

**Comment by ThePauliPrinciple** [comment]
Note that the use of "Solver" and "Function" are examples. Read the release note wiki on how to select the correct header. The markdown format is using two spaces e.g.
```
* header
  * description
```
* header
  * description

**Comment by shubhayu09** [comment]
Ok, thanks for your reviews, 
actually, it's a totally new environment for me that's why I'm still trying.

**Comment by shubhayu09** [comment]
Thanks @asmeurer, @ThePauliPrinciple ,
All checks have passed now and the branch has no conflicts, it seems good to merge.

**Pull request merged**
