### PR TITLE
Allow TensorProduct for ImmutableMatrices

### LINKED ISSUE #10734: TensorProduct does not work with ImmutableMatrices
Currently attempting to pass one or more `ImmutableMatrix` instances to `sympy.physics.quantum.tensorproduct.TensorProduct` leads to an error.

For example,

``` python
>>> from sympy import *
>>> from sympy.physics.quantum.tensorproduct import TensorProduct
>>> M = eye(2).as_immutable()
>>> N = eye(2).as_immutable()
>>> MN = TensorProduct(M, N)
Traceback (most recent call last):
  File "<ipython-input-6-c2dec18d1267>", line 1, in <module>
    MN = TensorProduct(M, N)
  File "/Users/rainesz/anaconda3/lib/python3.5/site-packages/sympy/physics/quantum/tensorproduct.py", line 122, in __new__
    c_part, new_args = cls.flatten(sympify(args))
  File "/Users/rainesz/anaconda3/lib/python3.5/site-packages/sympy/physics/quantum/tensorproduct.py", line 138, in flatten
    cp, ncp = arg.args_cnc()
  File "/Users/rainesz/anaconda3/lib/python3.5/site-packages/sympy/matrices/matrices.py", line 3084, in __getattr__
    "%s has no attribute %s." % (self.__class__.__name__, attr))
AttributeError: ImmutableMatrix has no attribute args_cnc.
```

or

``` python
>>> from sympy import *
>>> from sympy.physics.quantum.tensorproduct import TensorProduct
>>> M = eye(2).as_mutable()
>>> N = eye(2).as_immutable()
>>> MN = TensorProduct(M, N)
Traceback (most recent call last):
  File "<ipython-input-14-c2dec18d1267>", line 1, in <module>
    MN = TensorProduct(M, N)
  File "/Users/rainesz/anaconda3/lib/python3.5/site-packages/sympy/physics/quantum/tensorproduct.py", line 121, in __new__
    return matrix_tensor_product(*args)
  File "/Users/rainesz/anaconda3/lib/python3.5/site-packages/sympy/physics/quantum/matrixutils.py", line 246, in matrix_tensor_product
    return _sympy_tensor_product(*product)
  File "/Users/rainesz/anaconda3/lib/python3.5/site-packages/sympy/physics/quantum/matrixutils.py", line 193, in _sympy_tensor_product
    'Sequence of Matrices expected, got: %s' % repr(matrices)
TypeError: Sequence of Matrices expected, got: (Matrix([
[1, 0],
[0, 1]]), Matrix([
[1, 0],
[0, 1]]))
```

The code specifically tests if objects are of class `Matrix` instead of `MatrixBase`, however, the general logic as written should work perfectly fine for `ImmutableMatrix` instances.

### PR DESCRIPTION
**Pull request by raineszm**
Fixes #10734

Currently, attempting to call `TensorProduct` with an ImmutableMatrix leads to an error.
These commits make a couple of small changes to fix these errors so things work as expect.

``` python
>>> from sympy import *
>>> from sympy.physics.quantum.tensorproduct import TensorProduct
>>> M = eye(2).as_immutable()
>>> N = eye(2).as_immutable()
>>> MN = TensorProduct(M, N)
>>> MN
Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])
>>> type(MN)
<class 'sympy.matrices.immutable.ImmutableMatrix'>
```

I wasn't sure how much it was okay to modify the tests, so I left those changes as a separate commit.

### CODE REVIEW

**Comment by Upabjojr** [comment]
Other libraries call that kind of operation a _Kronecker product_, shall we think of renaming it?

**Comment by raineszm** [comment]
I wouldn't object to a renaming, although I think a bigger issue is that this operation is tucked away in `sympy.physics.quantum.matrixutils` and `sympy.physics.quantum.tensorproduct` instead of being available in `sympy.matrices`. However, that would involve deprecating the old class and methods, so it probably would make sense to split it off into a separate issue/pull request. Not sure what those more involved in the project think about it.

**Comment by Upabjojr** [comment]
I agree, better open an issue for that.

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/issues/10771

**Comment by Upabjojr** [comment]
Anyway, I think you could already move the code to the matrix module with this PR, rename it _KroneckerProduct_, then put a deprecation warning in _sympy.physics.quantum.TensorProduct_ to use the _KroneckerProduct_ instead.

**Comment by basnijholt** [comment]
Any updates on this? I am running into this problem.

**Comment by raineszm** [comment]
Sorry. I never got around to actually moving this functionality to the matrix module and so these fixes never made it into the code base (as far as I know). A work around for now is to call `.as_mutable()` on whichever immutable matrices you're having trouble with inside the TensorProduct constructor.

**Comment by czgdp1807** [comment]
Closing this PR for now. See, https://github.com/sympy/sympy/issues/18444 for latest updates. Thanks for the contributions.

**Pull request closed without merging**
