### PR TITLE
Add `is_fibonacci_prp` etc to `external`

### PR DESCRIPTION
**Pull request by haru-44**
The following `gmpy2` function is implemented.

* `is_fibonacci_prp`
* `is_lucas_prp`
* `is_selfridge_prp`
* `is_strong_lucas_prp`
* `is_strong_selfridge_prp`
* `is_bpsw_prp`
* `is_strong_bpsw_prp`

The following changes were made accordingly

* Moved `_lucas_sequence` from `ntheory.primetest` to `external.ntheory`.
* Removed `primetest._lucas_selfridge_params`.
* Fixed implementation of the following `ntheory.primetest` functions
  * `is_lucas_prp`
  * `is_strong_lucas_prp`
  * `isprime`

#### Release Notes

* ntheory
  * Moved `_lucas_sequence` from `ntheory.primetest` to `external.ntheory`. And removed `primetest._lucas_selfridge_params`.

### CODE REVIEW

**Comment by haru-44** [comment]
`is_extra_strong_lucas_prp` fails the test.
This is because it differs from the `gmpy2` implementation.
I will ask gmpy what they implemented it based on, but I will revert the change in this PR.

**Comment by smichr** [comment]
Do you want to wait until you hear from gmpy before having this committed?

**Comment by smichr** [comment]
Either way, it is going to involve another test run. I will go ahead and commit what is here.

**Comment by casevh** [comment]
Fix commit in gmpy2. Thanks for the report.

**Comment by haru-44** [comment]
Thanks.
As you said, we do not need to include it in this PR, as it would require a new handling of the issue.

**Pull request merged**
