### PR TITLE
Add support for pickling FreeGroup

### PR DESCRIPTION
**Pull request by amirebrahimi**
#### Brief description of what is fixed or changed
We use [ray,io](https://www.ray.io/), which uses `pickle` to transfer objects to task executors. Unfortunately, the `FreeGroup` class isn't pickleable because it is lacking the [__getnewargs__](https://docs.python.org/2/library/pickle.html#object.__getnewargs__) method that is used for protocol 2. This PR adds the method and an additional test.

#### Release Notes

* combinatorics
  * Add pickle support to FreeGroup.

### CODE REVIEW

**Comment by amirebrahimi** [comment]
The `code-quality` failure above looks unrelated to the changes I made. What is required here?

**Comment by amirebrahimi** [comment]
More info about the fix is here: https://stackoverflow.com/a/56552628

**Comment by oscarbenjamin** [comment]
> The `code-quality` failure above looks unrelated to the changes I made. What is required here?

You don't need to do anything about that. The fix is here: gh-27040.

**Comment by amirebrahimi** [comment]
Looks like the `benchmarks` failure might be rectified by a re-run. Should I do another commit to cause that?

**Comment by oscarbenjamin** [comment]
Can you add tests in `test_pickling.py`:
https://github.com/sympy/sympy/blob/master/sympy/utilities/tests/test_pickling.py

**Comment by amirebrahimi** [comment]
> Can you add tests in `test_pickling.py`: https://github.com/sympy/sympy/blob/master/sympy/utilities/tests/test_pickling.py

Done. I did notice that the `Basic` class does basically what I've done. Is there a reason why `FreeGroup` doesn't inherit from `Basic`? My guess is that it is because this class overrides `__new__`?

**Comment by oscarbenjamin** [comment]
> Is there a reason why `FreeGroup` doesn't inherit from `Basic`?

I'm not sure. I don't know the combinatorics module very well. I get the impression that many things are strangely designed.

**Comment by oscarbenjamin** [comment]
Okay looks good. Thanks!

**Pull request merged**
