### PR TITLE
Added sub, neg and scalar mul for TWave

### LINKED ISSUE #8887: Subtracting waves in optics module
The Optics module enables working with waves.

However, subtracting the waves which follows intuitively results in the result being an instance of the `sympy.core.add.Add` class. This stops the user from accessing properties of the resultant wave like amplitude, phase etc. 

This can be fixed by simply returning the result of the  `__add__(self, other)` method with the amplitude of `other` multiplied by `-1`.

Is it a good idea to make this change ?

``` python
In [1]: from sympy.physics.optics import *
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-1d52e0c05aa5> in <module>
----> 1 from sympy.physics.optics import *

AttributeError: module 'sympy.physics.optics' has no attribute 'polarizing_beam_splitte'

In [2]: from sympy.physics.optics import TWave

In [3]: A,f,phi = symbols('A,f,phi')

In [4]: w1 = TWave(A, f)

In [5]: w2 = TWave(A, f, phi)

In [6]: w1+w2
Out[6]: TWave(sqrt(2*A**2*cos(phi) + 2*A**2), f, atan2(A*cos(phi) + A, A*sin(phi)))

In [7]: _.amplitude
Out[7]: 
   ____________________
  ╱    2             2 
╲╱  2⋅A ⋅cos(φ) + 2⋅A  

In [8]: w1 - w2
Out[8]: TWave(A, f) - TWave(A, f, phi)

In [9]: type(_)
Out[9]: sympy.core.add.Add

In [10]: (w1 - w2).amplitude
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-cea1328571ac> in <module>
----> 1 (w1 - w2).amplitude

AttributeError: 'Add' object has no attribute 'amplitude'
```

### PR DESCRIPTION
**Pull request by 0sidharth**
#### References to other Issues or PRs

Fixes #8887 

#### Brief description of what is fixed or changed
TWave subtraction was returning an `Add` object and hence did not have required attributes. This has been fixed.
Neg, sub and scalar mul for `TWave` have been added, as scalar multiplication with `TWave` was also giving a `Mul`.
Some minor changes have been made to the documentation, tests and init.

#### Other comments
All credits for this work go to @kevinventullo but I do not know how to include his commits as his fork and branch have been deleted. Original work was https://github.com/sympy/sympy/pull/8908

#### Release Notes

* physics.optics
    * Fixed bugs related to basic operations on `TWave`

### CODE REVIEW

**Comment by 0sidharth** [comment]
Should I add the author of the original PR as a co-author in my commit? Or is there any other way to give them credits?

**Comment by 0sidharth** [comment]
The commit history is a little weird now, will fix it after reviews

**Comment by oscarbenjamin** [comment]
> Should I add the author of the original PR as a co-author in my commit? Or is there any other way to give them credits?

Ideally you would preserve their original commits and add yours on top.

Adding them as a co-author is fine if needed though. In that case I suggest rebasing their commits to current master, squashing to a single commit and then listing them as a co-author.

**Comment by oscarbenjamin** [comment]
@oscarlazoarjona would you be able to review this?

**Comment by oscarbenjamin** [comment]
I don't know much about optics but this looks like a reasonable PR. If no one else is going to review this then I think it's better to merge.

Thanks for the contribution!

**Comment by 0sidharth** [comment]
Thank you

**Pull request merged**
