### PR TITLE
Improve codegen global variable support

### LINKED ISSUE #9542: codegen octave global vars should print "global foo" at top of function
After #9535, we should improve the octave printing further to print `global foo bar` in the generated function.

### PR DESCRIPTION
**Pull request by cbm755**
Octave: fixes #9542 (puts  "global var1 var2" at top of function).

For other languages, I've added support to deal with global variables in a similar way to local variables.

For C: nothing to be done.

For Fortran: currently raises NotImplementedError.  I think future work could make `COMMON` blocks for F77.  Maybe something different for F90?

### CODE REVIEW

**Comment by cbm755** [comment]
@jcrist I haven't really done anything with Fortran here: I could just `return []` instead of raising the error?   (Then it would function exactly as it does right now)

Or if you/others are uncertain about this, we could take only my first commit for Octave only (and ignore C/Fortran for now).

**Comment by jcrist** [comment]
For Fortran 90 the variable declaration just happens at a global scope (same as in C). For Fortran 77 we'd need to support the common blocks, which is a little trickier. I'm fine with just leaving a `NotImplementedError` for now - this only fails if someone tries to use globals in Fortran. Or you could add support for F90, and only fail on F77.

**Comment by cbm755** [comment]
Thanks for the F90 info!  Looks like we don't support F77 yet so I'll just do as per C.  And leave a comment for future F77 development.

**Comment by cbm755** [comment]
merging master to see if that helps with test timeouts...   but I think it was an unrelated timeout.

**Comment by toolforger** [comment]
#9596 was a configuration change that, as a side effect, puts many of our test runs on faster hardware on Travis.
In fact the running time went down to 15 minutes.
(Running times remain unpredictable, until now I have seen the three SLOW runs taking time between 15 and 30 minutes.)

**Comment by cbm755** [comment]
yes I know but thanks.

**Comment by bjodah** [comment]
This PR looks good to me :+1:

**Comment by jksuom** [comment]
Looks good to me, too.

**Pull request merged**
