### PR TITLE
Changes in RUBI documents

### PR DESCRIPTION
**Pull request by vishalg2235**

### CODE REVIEW

**Comment by vishalg2235** [comment]
@Abdullahjavednesar @gxyd 
Changes in RUBI documents as per comments in https://github.com/sympy/sympy/pull/13261 .

**Comment by gxyd** [comment]
You should build your PR making use of the original commits by @Abdullahjavednesar instead of doing everything from scratch.

**Comment by vishalg2235** [comment]
@gxyd I don't know how to send PR using commits of other. can you explain me how its done ?

**Comment by gxyd** [comment]
Try these commands (you are in sympy master branch) :
```
$ git remote add Abdullahjavednesar https://github.com/Abdullahjavednesar/sympy.git
$ git fetch Abdullahjavednesar  # getting all branches present on Abdullah's sympy repo
$ git checkout -b rubi-integrator-docs Abdullahjavednesar/docm
```

make changes on this branch to Rubi docs. Rest of the things as you do normally.

**Comment by vishalg2235** [comment]
after making changes how to push it ? and then how to pull request ?

**Comment by gxyd** [comment]
After making the changes commit the new changes made. Then push the branch 'rubi-integrator-docs' to github. Just like you pushed this branch.

**Comment by gxyd** [comment]
You should definitely **not** push to `Abdullahjavednesar`.

**Comment by vishalg2235** [comment]
To 'github' ?
Last time I have used "git push origin rubi_doc". Now after 1 commit it saya 
`On branch rubi-integrator-docs
Your branch is ahead of 'Abdullahjavednesar/docm' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
`

**Comment by gxyd** [comment]
Yup I have done okay. Just go to https://github.com/vishalg2235/sympy/tree/rubi-integrator-docs and click on pull request button (or whatever it says).

**Comment by vishalg2235** [comment]
Yup its done!

**Comment by gxyd** [comment]
You should probably close this pull request, since this is no longer going to be worked on.

**Pull request closed without merging**
