### PR TITLE
Changed the derivative function of associated legendre polynomials 

### PR DESCRIPTION
**Pull request by QuantumshWu**
#### Brief description of what is fixed or changed

Changed the derivative function of associated Legendre polynomials where I selected the recurrence formula containing P(n+1, m, x) rather than P(n-1, m, x) such that avoid the corner case (n-m)<1 and makes formula valid always. The corresponding formula can be found at https://en.wikipedia.org/wiki/Associated_Legendre_polynomials#Recurrence_formula.

#### Release Notes

* functions
  * Fixed a bug when evaluating the derivative of associated Legendre polynomials P(n, m, x) with (n-m)<1 by using another recurrence formula for the derivative.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
> selected the recurrence formula containing P(n+1, m, x) rather than P(n-1, m, x) such that avoid the corner case n-1<0 and makes formula valid always.

Is the formula not valid for `n = 0`?
```
In [40]: assoc_legendre(n,m,x).subs(n, 0).subs(m, 0)
Out[40]: 1

In [41]: assoc_legendre(n,m,x).subs(n, 0).subs(m, 0).diff(x)
Out[41]: 0

In [42]: print(assoc_legendre(n,m,x).diff(x))
(n*x*assoc_legendre(n, m, x) - (m + n)*assoc_legendre(n - 1, m, x))/(x**2 - 1)

In [43]: print(assoc_legendre(n,m,x).diff(x).subs(n, 0).subs(m, 0))
0
```

**Comment by QuantumshWu** [comment]
> > selected the recurrence formula containing P(n+1, m, x) rather than P(n-1, m, x) such that avoid the corner case n-1<0 and makes formula valid always.
> 
> Is the formula not valid for `n = 0`?
> 
> ```
> In [40]: assoc_legendre(n,m,x).subs(n, 0).subs(m, 0)
> Out[40]: 1
> 
> In [41]: assoc_legendre(n,m,x).subs(n, 0).subs(m, 0).diff(x)
> Out[41]: 0
> 
> In [42]: print(assoc_legendre(n,m,x).diff(x))
> (n*x*assoc_legendre(n, m, x) - (m + n)*assoc_legendre(n - 1, m, x))/(x**2 - 1)
> 
> In [43]: print(assoc_legendre(n,m,x).diff(x).subs(n, 0).subs(m, 0))
> 0
> ```

Sorry, I meant my change avoids the error for the corner case where (n-m)<1 rather than n<1. Here I show how the case n=m=1 fails after one derivative. You can also tell this error is more likely to happen for high-order derivatives.

```
In [5]: print(assoc_legendre(n, m, x).subs(n, 1).subs(m, 1))
-sqrt(1 - x**2)

In [6]: print(assoc_legendre(n, m, x).subs(n, 1).subs(m, 1).diff(x))
x/sqrt(1 - x**2)

In [3]: print(assoc_legendre(n, m, x).diff(x))
(n*x*assoc_legendre(n, m, x) - (m + n)*assoc_legendre(n - 1, m, x))/(x**2 - 1)

In [4]: print(assoc_legendre(n, m, x).diff(x).subs(n, 1).subs(m, 1))
ValueError: assoc_legendre : abs('2nd index') must be <= '1st index' (got 0, 1)
```

**Comment by oscarbenjamin** [comment]
I think maybe `assoc_legendre` should be changed to return 0 instead of raising an error:
```
In [4]: import mpmath

In [5]: mpmath.legenp(1, 2, 3)
Out[5]: mpf('0.0')

In [6]: assoc_legendre(1, 2, 3)
---------------------------------------------------------------------------
ValueError
```

**Comment by QuantumshWu** [comment]
I agree, this will fix all the corner cases. `assoc_legendre` returns 0 for all n<m or n<0 cases, and then no need to change the derivative function. From the definitions, this extension should be valid and is also used by `mpmath`. Should I close this pull request and come back with the extended  `assoc_legendre`?

**Comment by oscarbenjamin** [comment]
> Should I close this pull request and come back with the extended `assoc_legendre`?

Yes, let's do that.

See also https://github.com/sympy/sympy/issues/15795

**Pull request closed without merging**
