### PR TITLE
Added evaluate flags in miscallaneous.py

### LINKED ISSUE #14000: sqrt and other root functions should inherit from Function
The functions sqrt, cbrt, root, and real_root, defined in `miscellaneous.py`, are plain Python functions, defined with `def sqrt(arg): ...` This is in contrast to all other mathematical SymPy functions, which inherit from class Function. As a result, one cannot use `sqrt(5.5, evaluate=False)` to create un-evaluated sqrt(5.5), the way it works with exp, log, and all others. 

Those functions should be rewritten, following the model used for other functions (see sympy.functions.elementary for many examples).

### PR DESCRIPTION
**Pull request by arighnac**
Fixes #14000 .
Closes #14009 .

This PR removes the merge conflicts, but instead some unnecessary commits pop-up. Note these do not change any file. They are just redundant commits.
This had happened previously, and I have no idea how to exclude them.
Please review.
@normalhuman , @jksuom .

### CODE REVIEW

**Comment by ylemkimon** [comment]
Create a branch based on latest SymPy master.

**Comment by ArighnaIITG** [comment]
I did create a branch on latest Sympy master, but these are set of commits which always come in between the log. How do I remove them?

**Comment by asmeurer** [comment]
@ArighnaIITG you most likely have messed up your master branch through rebasing. Since your change is so simple, the easiest way for you to fix this is to clone again, re-do the change in a new branch, and make a new pull request.

**Comment by ArighnaIITG** [comment]
The issue has been shifted to #14130.
I am closing this PR.

**Pull request closed without merging**
