### PR TITLE
Add pretty and latex printing for Mod

### LINKED ISSUE #11375: Pretty printing of Mod
Mod should have pretty printing. I guess the mathematical way to print `Mod(x, n)` is `x mod n`, with parentheses around the whole thing if it is in a larger expression, like `1 + (x mod n)`.  We need pretty printing and LaTeX printing.

### PR DESCRIPTION
**Pull request by gorisaka**
This PR fixes #11375.

Examples of pretty printing for Mod function after this PR:

``` python
>>> Mod(x, 7)
x mod 7

>>> Mod(x + 1, 7)
(x + 1) mod 7

>>> Mod(2 * x, 7)
2⋅x mod 7

>>> Mod(x, 7) + 1
(x mod 7) + 1

>>> 2 * Mod(x, 7)
2⋅(x mod 7)
```

The same is applied for latex printing.

### CODE REVIEW

**Comment by asmeurer** [comment]
The LaTeX printer should use `\mathrm{mod}`.

**Comment by asmeurer** [comment]
There are merge conflicts.

**Comment by gorisaka** [comment]
@asmeurer I've just found out there is a `\bmod`. What do you think about using it instead? It is the binary version of `\mod` and deals with the spacing.

**Comment by asmeurer** [comment]
Yes, let's use that.

**Comment by gorisaka** [comment]
Fixed latex tag and resolved merge conflicts.

**Pull request merged**
