### PR TITLE
is_zero_dimensional: remove sqrt from the eqs

### PR DESCRIPTION
**Pull request by Shekharrajak**
Fixes some cases of https://github.com/sympy/sympy/issues/11175
#### Master branch

```
In [1]: system = [sqrt(x**2 + y**2) - sqrt(10), x + y - 4]

In [2]:  is_zero_dimensional(system)
Out[2]: False

In [3]:  is_zero_dimensional(system, [x, y])
---------------------------------------------------------------------------
PolynomialError: sqrt(x**2 + y**2) contains an element of the generators set

In [4]: solve(system, [x, y])
Out[4]: [(1, 3), (3, 1)]

In [5]: x1 = 0

In [6]:     y1 = -620

In [7]:     r1 = 920

In [8]:     x2 = 126

In [9]:     y2 = 276

In [10]:     x3 = 51

In [11]:     y3 = 205

In [12]:     r3 = 104

In [13]:     v = [x, y, z]

In [14]:     g1 = sqrt((x - x1)**2 + (y - y1)**2) + z - r1

In [15]:     g2 = (x2 - x)**2 + (y2 - y)**2 - z**2

In [16]:     g3 = sqrt((x - x3)**2 + (y - y3)**2) + z - r3

In [17]:     G = [g1, g2, g3]

In [18]:     is_zero_dimensional(G, v)
PolynomialError
```
#### This branch

```
In [ ]: system = [sqrt(x**2 + y**2) - sqrt(10), x + y - 4]

In [ ]:  is_zero_dimensional(system)
Out[ ]: True

In [ ]:  is_zero_dimensional(system, [x, y])
Out[ ]: True


In [ ]: x1 = 0

In [ ]:     y1 = -620

In [ ]:     r1 = 920

In [ ]:     x2 = 126

In [ ]:     y2 = 276

In [ ]:     x3 = 51

In [ ]:     y3 = 205

In [ ]:     r3 = 104

In [ ]:     v = [x, y, z]

In [ ]:     g1 = sqrt((x - x1)**2 + (y - y1)**2) + z - r1

In [ ]:     g2 = (x2 - x)**2 + (y2 - y)**2 - z**2

In [ ]:     g3 = sqrt((x - x3)**2 + (y - y3)**2) + z - r3

In [ ]:     G = [g1, g2, g3]

In [ ]:     is_zero_dimensional(G, v)
True

```

### CODE REVIEW

**Comment by Shekharrajak** [comment]
ping @sympy/sympy-solvers @asmeurer @smichr

**Comment by Shekharrajak** [comment]
Ping @jksuom

**Comment by jksuom** [comment]
This seems to work when `unrad` is able to remove the radicals without adding new symbols. The original issue was that `is_zero_dimensional` is designed to work with polynomial expressions only.
If there are denominators, they could be removed in the same way by applying `.as_numer_denom` and replacing the expression with the numerator alone.

**Comment by jksuom** [comment]
I feel a little uneasy about this being added to `polys`. I think this is more in the spirit of `solvers`. Perhaps there could be a function in `solvers` that would do the preparations and then call `is_zero_dimensional`.

**Comment by Shekharrajak** [comment]
Thanks @jksuom for comments. I think `is_zero_dimensional` should work for any kind of system of equation, we pass. So this place is good, right?

**Comment by jksuom** [comment]
I think that a general `is_zero_dimensional`, that is expected to work for any kind of system of equations, does logically belong to `solvers`, and  only polynomials should be dealt with in `polys`. In case of polynomials, dimension zero means that the number of solutions is finite. For general systems, the set of solutions can be zero-dimensional and infinite, e.g. for the system `[sin(x), y]`. So, those cases should be taken care of in `solvers`, and `polys` should called only with polynomial arguments.

**Comment by Shekharrajak** [comment]
Thanks @jksuom for explanation. Yes we should use `is_zero_dimensional` for poly system. Testcases I added in this PR, contains polynomial system only.
>is_zero_dimensional should work for any kind of system of equation

I should have used _any kind of polynomial system of equation_, sorry for that. 

I have separated the poly and non polynomial equations using [this helper function](https://github.com/sympy/sympy/pull/11111/files#diff-eec0422923e8f100745c015cd8fdd6cfR1796)

**Comment by Shekharrajak** [comment]
Ping @jksuom .

`is_zero_dimensional` should work for ` [sqrt(x**2 + y**2) - sqrt(10), x + y - 4]` kind of polynomial system isn't it?

**Comment by jksuom** [comment]
Actually, that is not a polynomial system since the argument of the first `sqrt` depends on the variables `x` and `y`. `is_zero_dimensional` in `polys` is not expected to handle this system. It can be used, however, after the expression is simplified to a polynomial expression such as `x**2 + y**2 - 10`.

**Comment by Shekharrajak** [comment]
Thanks @jksuom . These system contains radical.

**Comment by asmeurer** [comment]
In general one could use minpoly:

```
In [157]: is_zero_dimensional([x**2 + y**2 - 10, x + y - 4])
Out[157]: True

In [158]: is_zero_dimensional([minpoly(sqrt(x**2 + y**2) - sqrt(10), z), x + y - 4, z])
Out[158]: True

In [155]: solve([x**2 + y**2 - 10, x + y - 4])
Out[155]: [{x: 1, y: 3}, {x: 3, y: 1}]

In [156]: solve([minpoly(sqrt(x**2 + y**2) - sqrt(10), z), x + y - 4, z])
Out[156]: [{x: 1, y: 3, z: 0}, {x: 3, y: 1, z: 0}]
```

`minpoly(expr, z)` (where `expr` is some algebraic function) gives an expression that equals zero such that `z = expr`. Adding `z` to the list in solve (or `is_zero_dimensional`) tells it that the original `expr = 0`. I don't know how robust minpoly is for general algebraic functions.

**Comment by asmeurer** [comment]
Now, whether is_zero_dimensional should work with algebraic functions or stick to polynomials and require preprocessing is a design question. solve/solveset should definitely work with algebraic functions.

**Comment by Shekharrajak** [comment]
Thanks @asmeurer .

`minpoly` is helpful for removing radicals.

```
In [15]: minpoly(sqrt(2) + sqrt(3), x)
Out[15]: 
 4       2    
x  - 10⋅x  + 1

```

But I didn't understand this case : 

```
In [20]: minimal_polynomial(sqrt(x**2 + y**2) - sqrt(10))
Out[20]: 
 4    2 ⎛     2      2     ⎞    4      2  2       2    4       2      
x  + x ⋅⎝- 2⋅x  - 2⋅y  - 20⎠ + x  + 2⋅x ⋅y  - 20⋅x  + y  - 20⋅y  + 100

In [18]: simplify(cancel(minimal_polynomial(sqrt(x**2 + y**2) - sqrt(10))))
Out[18]: 
 4      2  2      2  2       2    4      2  2       2    4       2      
x  - 2⋅x ⋅x  - 2⋅x ⋅y  - 20⋅x  + x  + 2⋅x ⋅y  - 20⋅x  + y  - 20⋅y  + 100

# x**2 + y**2 - 100 is expected right ?

```

**Comment by asmeurer** [comment]
Be careful. If you don't pass a second argument to `minpoly`, it uses a dummy symbol named `x`, which is pretty confusing if your expression already contains `x` (that's why the expression has `x**2*x**2`). I used `z` above:

```
In [205]: minpoly(sqrt(x**2 + y**2) - sqrt(10), z)
Out[205]:
 4      2  2       2    4       2    4    2 ⎛     2      2     ⎞
x  + 2⋅x ⋅y  - 20⋅x  + y  - 20⋅y  + z  + z ⋅⎝- 2⋅x  - 2⋅y  - 20⎠ + 100
```

This is a degree 4 polynomial in `z` over `Z[x, y]`. One of its roots is `sqrt(x**2 + y**2) - sqrt(10)`:

```
In [209]: minpoly(sqrt(x**2 + y**2) - sqrt(10), z).subs(z, sqrt(x**2 + y**2) - sqrt(10)).expand()
Out[209]: 0
```

Also the polynomial is irreducible (as can be seen by noting that `minpoly(sqrt(x**2 + y**2) - sqrt(10), z).factor(z)` produces no factors), so it's minimal. 

The difference between this and `x**2 + y**2 - 10` is this. For the minimal polynomial, you are basically saying, 

- Let `z = sqrt(x**2 + y**2) - sqrt(10)`. Now rewrite this equation as `P = 0`, where `P` is a polynomial in `z`, `x`, and `y` (and furthermore, it is of minimal degree in `z`). 

For `x**2 + y**2 - 10`, you are saying,

- Let `sqrt(x**2 + y**2) - sqrt(10) = 0`. Rewrite this equation as `P = 0`, where `P` is a polynomial in `x` and `y`. 

Case 2 is somewhat a special case of case 1, when z = 0. And indeed:

```
In [215]: factor(minpoly(sqrt(x**2 + y**2) - sqrt(10), z).subs(z, 0))
Out[215]:
              2
⎛ 2    2     ⎞
⎝x  + y  - 10⎠
```

In fact, writing `solve([minpoly(expr, z), z])` is the same as `solve([minpoly(expr, z).subs(z, 0)])` (sorry that I missed that obvious step above). 

Finally, I should point out that this process can introduce extraneous solutions (because `sqrt(x**2 + y**2) - sqrt(10)` is only one of the four roots of its minimal polynomial). So you should always check the final answers (I believe in this case the `x + y - 4` has prevented any invalid solutions from cropping up).

**Comment by Shekharrajak** [comment]
Thanks a lot @asmeurer , actually [in the docstring](https://github.com/sympy/sympy/blob/master/sympy/polys/numberfields.py#L591) `dummy` thing is not mentioned, so I was confused. 

It is useful to remove radicals , previously I use `unrad` but `minpoly` looks better to get polynomial expr. 
And yes, need to use `checksol` before returning final soln, if solving for a variable.

```
from sympy.solvers.solvers import unrad

In [29]: eq = sqrt(x) + root(x, 3) - 2

In [30]: unrad(eq)
Out[30]: 
⎛ 3    2      ⎡    6    ⎤⎞
⎝p  + p  - 2, ⎣p, p  - x⎦⎠

In [31]: minpoly(eq, z).subs(z, 0)
Out[31]: 
   3    2            
- x  + x  - 64⋅x + 64

```

**Comment by asmeurer** [comment]
The documentation of minpoly should definitely be improved. IMHO it should also use a less common variable name by default, or perhaps notice when the expression already contains a variable named `x`.

**Comment by Shekharrajak** [comment]
Thanks, I will try for it.

**Pull request closed without merging**
