### PR TITLE
Propagate kwargs in action verb "powsimp"

### PR DESCRIPTION
**Pull request by bjodah**
Makes kwargs `force` and `measure` available from `Expr`'s method `powsimp`.

### CODE REVIEW

**Comment by jksuom** [comment]
It seems that `deep` and `combine` could be omitted after the addition of `kwargs`. It could also be added to `radsimp`.

**Comment by bjodah** [comment]
I added `*args` and `**kwargs` in case people relied on positional arguments. The `radsimp` action verb didn't pass any along earlier so just `**kwargs` is enough.

**Comment by smichr** [comment]
+1 but let @jksuom have the final say in case I am missing something

**Comment by jksuom** [comment]
This looks good to me.

**Pull request merged**
