### PR TITLE
Fix issue #11823

### PR DESCRIPTION
**Pull request by tschijnmo**
In commit 15b2646, a simple revision is made that resolves issue #11823 and does not break any existing tests.  In commit 5bc095c, a simple test is made to ensure that the issue is resolved.  Any Sympy member reviewing this PR is deeply appreciated!

### CODE REVIEW

**Comment by tschijnmo** [comment]
This is really a small patch.  Anyone interested in have a review of it?

**Comment by jksuom** [comment]
I think that your conclusion about the role of expand() is correct. But there might be a more general solution. expand() admits a great number of different keywords in addition to power_exp. If a keyword argument `**hints`  is added to the argument list of eval_sum(), and that is passed to expand(), then it would be possible to include also other keywords.

**Comment by tschijnmo** [comment]
@jksuom Thank you for your reply!  Certainly allowing more options to `expand` to be controllable from the invocation of the summation can be very helpful.  But probably I have a question that, [here](https://github.com/sympy/sympy/blob/692064d80b17b083a30ffbb4311cae6fc717ab63/sympy/concrete/summations.py#L171-L175), it seems that the `**hints` is already used and forwarded to the `self.function.doit`.  Could you please help me if it is fine to use it for forwarding to `expand` again?  Probably the hints needs to be separated into arguments to `function.doit` and `expand`?

**Comment by jksuom** [comment]
> Probably the hints needs to be separated into arguments to function.doit and expand?

I think that there is no need for multiple hints, in general. If some conflicts would occur, it is possible to preprocess self.function with any hints, and then set deep=False.

**Pull request closed without merging**
