### PR TITLE
Create FUNDING.yml

### PR DESCRIPTION
**Pull request by certik**
Add a link to a NUMFocus donate page for SymPy.

NO ENTRY

### CODE REVIEW

**Comment by moorepants** [comment]
Nice addition!

**Comment by asmeurer** [comment]
Oh I knew GitHub has its own sponsor thing now but I didn’t know they supported external links.

**Comment by asmeurer** [comment]
Please merge and delete the branch when tests pass. In the future when using the GitHub interface make a PR from your fork.

**Comment by certik** [comment]
Oh, I didn't realize github pushed the branch into the main repo. Sorry about that!

**Comment by asmeurer** [comment]
Yeah, I wish GitHub would let you disable that. Not only does it pollute the main repo with branches, which show up every time someone clones the repo, but it also causes Travis to run twice.

**Comment by certik** [comment]
And GitHub still does not have "merge after pipelines pass"... Now I need to be periodically checking this.

**Comment by certik** [comment]
The sponsor button is there now!

Screenshot_2019-07-25 Create FUNDING yml by certik · Pull Request #17263 · sympy sympy

**Pull request merged**
