### PR TITLE
Added exception catching for GeneratorsNeeded error in as_poly

### LINKED ISSUE #20610: Solve: GeneratorsNeeded with system involving constant equation
I don't think solve should convert all equations to Poly because it can be slow but at least there should be some checking for this case:
```python
>>> from sympy import *
>>> from sympy.abc import x, y
>>> solve([x + y, sqrt(2)], [x, y])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 1099, in solve
    solution = _solve_system(f, symbols, **flags)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 1774, in _solve_system
    subsol = _solve_system(subexpr, subsyms, **flags)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 1805, in _solve_system
    poly = g.as_poly(*symbols, extension=True)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 1109, in as_poly
    poly = Poly(self, *gens, **args)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 162, in __new__
    return cls._from_expr(rep, opt)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 292, in _from_expr
    return cls._from_dict(rep, opt)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 229, in _from_dict
    raise GeneratorsNeeded(
sympy.polys.polyerrors.GeneratorsNeeded: can't initialize from 'dict' without generators
```

### PR DESCRIPTION
**Pull request by kc611**
#### References to other Issues or PRs

Fixes #20610 

#### Brief description of what is fixed or changed

Continuation from #20661 . Starting from a new branch due to rebasing issues 

#### Release Notes

* polys
    * The `poly` function and `as_poly` methods now return `None` instead of raising `GeneratorsNeeded` for constant expressions when no generators are given.
* solvers
    * Fixed a bug causing `solve` to raise `GeneratorsNeeded` when an equation such as `sqrt(2)` is included in a system.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This still has 5 commits instead of 1.

I think maybe your master branch has merge commits in it and those are showing up because you started the PR branch from your master rather than upstream master.

I will fix this for you in this PR and push to it myself.

**Comment by kc611** [comment]
> I will fix this for you in this PR and push to it myself.

Thank you. Can you please list the commands you used to do this so that I could use it for future reference. ( Cause there are other PRs in sympy with master branch merge commits)

**Comment by oscarbenjamin** [comment]
I've fixed it for you with:
```
git fetch upstream
git checkout upstream/pr/20773
git checkout -b tmp_kc611
git diff HEAD^ > t.diff
git reset --hard HEAD~1000
git rebase upstream/master
git apply t.diff
git status
git diff
git commit -a
git push --force https://github.com/kc611/sympy.git tmp_kc611:issue_20610b
```
If you have merge commits on the master branch of your fork then I suggest removing them with this:
```
git fetch upstream
git checkout master
git reset --hard HEAD~1000   # wipe the last 1000 commits (save your work first!)
git rebase upstream/master
git push --force
```
That will restore your master branch locally and on github.

Then you should only merge into your master branch from the main sympy master. I keep my master up to date with:
```
git fetch upstream
git checkout master
git rebase upstream/master
git push
```
(I use rebase rather than merge for this because I never want to create a merge commit but in other situations merge is preferred.)

You can also start a pr directly from upstream master:
```
git fetch upstream
git checkout upstream/master
git checkout -b pr_my_branch
```

**Comment by oscarbenjamin** [comment]
> I've fixed it for you with:

If you want to do this with your own PR then I suggest following this: https://github.com/sympy/sympy/pull/20700#issuecomment-757067113

**Comment by oscarbenjamin** [comment]
Looks good. Thanks

**Pull request merged**
