### PR TITLE
Implemented the solve method for the cable class

### PR DESCRIPTION
**Pull request by Abhishekjsr283204**
#### Brief description of what is fixed or changed
Implemented the solve method for the cable class. For point loads, this method computes the tensions in the segments of the cable, the reaction forces at the supports and updates the length.

#### Release Notes

* physics.continuum_mechanics
   * solve method implemented in the cable class.

### CODE REVIEW

**Comment by Abhishekjsr283204** [comment]
please have a look @anutosh491

**Comment by anutosh491** [comment]
I don't know much about this module. Hopefully someone will review this Pr for you :)

**Comment by Abhishekjsr283204** [comment]
@AdvaitPote have a look, sir

**Comment by AdvaitPote** [comment]
There is already a PR Open related to the solve method for the `cable` class [#25461](https://github.com/sympy/sympy/pull/25461)

**Comment by AdvaitPote** [comment]
I can definitely help with any reviews and suggestions but I won't be able to merge it as the other Pull request is implemented for both loads and was also opened earlier.

**Comment by Abhishekjsr283204** [comment]
@AdvaitPote got it sir no issue can you tell me any issue which I can work on and do my first contribution in sympy has any suggestion for that I aspire to contribute as a member like yourself hope you will help Thank you for response

**Comment by AdvaitPote** [comment]
Go and have a look at the issues with the tag `physics.continuum_mechanics` for issues related to this module. 

Other modules I am afraid I don't have any idea

**Pull request closed without merging**
