### PR TITLE
added LaTeX printers for OneMatrix

### PR DESCRIPTION
**Pull request by Upabjojr**
#### Release Notes

* printing
  * added LaTeX printers for class `OneMatrix`.

### CODE REVIEW

**Comment by oscargus** [comment]
I think it makes sense to have the one and zero matrix print consistently with regards to either showing the size or not.

**Comment by cbm755** [comment]
I haven't been following these developments but can OneMatrix have sizes like `ceiling(delta/2)` by 42?

**Comment by sylee957** [comment]
I also find it confusing that the dimensions are not printed for ZeroMatrix and Identity.

https://en.m.wikipedia.org/wiki/Zero_matrix

And we can use single dimension for square matrix
https://en.m.wikipedia.org/wiki/Identity_matrix

**Comment by Upabjojr** [comment]
> I think it makes sense to have the one and zero matrix print consistently with regards to either showing the size or not.

We can add the dimensions to `ZeroMatrix` and `Identity` matrices.

Anyway, maybe we should not print the dimensions as they may be mistaken for indices.

**Comment by oscargus** [comment]
Makes sense!

**Pull request merged**
