### PR TITLE
Fixed printing of minus-signs in MathML presentation

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed
There was a few issues with printing minus signs in the MathML presentation printer. Sometimes they disappeared, sometimes they were printed in a less ideal position.

Before:
beforeminusfix

After:
afterminusfix

This is fixed and tests are added. (And a bit of rewrite of the code.)

#### Release Notes

* printing
   * Issue with printing of minus signs in MathML presentation printer corrected.
   * MathML printing pf negative powers more consistent with LaTeX output.

### CODE REVIEW

**Comment by oscargus** [comment]
I also fixed printing of fractions and roots so that it is more consistent with the LaTeX printer.

Before:
beforeminusfix

After:
afterminusfix

**Comment by oscargus** [comment]
The _print_Pow method can most likely be written in a more compact form by sharing parts of the code. However, I was just happy to get it working at the moment.

**Comment by oscarbenjamin** [comment]
Looks good. I would merge this now but there's a bit of a Travis queue.

**Comment by oscargus** [comment]
Thanks! Good thing is that erroneous builds fail faster now.

**Comment by oscarbenjamin** [comment]
> erroneous builds fail faster now.

They do but it seems that successful builds and merged PRs can still prevent even the first job running for other PRs. So although an erroneous build might not take long it still has to wait a long time to start.

**Comment by oscargus** [comment]
Yeah, I haven't really understood how it prioritizes. But not obvious what is the best way to do it either. Except for merging in batches when the build queue is long...

**Comment by oscarbenjamin** [comment]
I'm not sure how the merge builds are prioritised with respect to the PR builds but my understanding is: 
1. Each build received by Travis goes into a queue.
2. SymPy gets 15 jobs total to run concurrently for all builds.
3. Jobs are allocated to the next build in the queue that needs jobs to complete a stage.
4. If all jobs outstanding in the stage are running then jobs go to the next build in the queue (and so on if that one is already running).

So once the first build in the queue completes a stage its next stage takes priority over everything else. Since the third stage needs more than 15 jobs as soon as it starts nothing else can run until it finishes.

**Comment by oscargus** [comment]
OK! I've noticed that sometimes the first stage is run and then it has to wait for quite some time. However, since the alternative is that not even that is run it is clearly better.

One could possibly look into running the pypi tests with a lower priority so that they only run if the build queue is empty. May not be worth the effort though.

**Comment by oscargus** [comment]
As I just merged another PR I'll merge this now as well to only get a single build (courtesy of the comment from @oscarbenjamin  above).

**Pull request merged**
