### PR TITLE
Change in E(z) function

### PR DESCRIPTION
**Pull request by ayush1999**
A missing argument in the statement function. The tough part here is finding a test case.

### CODE REVIEW

**Comment by asmeurer** [comment]
I didn't find any existing issues for it searching for "TypeError meijerint" in the issue tracker. How did you find it?

It looks like conds from theorem 1 uses `E`, so I'm guessing in every existing test case `gn.a` is empty?

**Comment by jksuom** [comment]
https://github.com/sympy/sympy/issues/12831, https://github.com/sympy/sympy/pull/12847

**Comment by asmeurer** [comment]
Ah :)

**Comment by ayush1999** [comment]
@asmeurer It is a simple case of argument count mismatch, isn't it? However I can't seem to find an example to show the mismatch.

**Comment by asmeurer** [comment]
It isn't so simple in the sense of, how do you know that the missing argument should be 0?

**Comment by smichr** [comment]
This is a duplicate of #12847

**Pull request closed without merging**
