### PR TITLE
lambdify: Improved speed of generated code when unpacking arguments

### LINKED ISSUE #14654: Performance issue with lambdify() when it uses a list as argument
See the following example:

```
import sympy as sp
x , y = sp.symbols ('x, y')

expr = [x*y]
f1 = sp.lambdify([x,y], expr)
f2 = sp.lambdify([[x,y]], expr)
```

When I check the time that f1 and f2 take to perform a call on my computer, I see a great difference:

`%timeit f1(3,4)` 
Output:
181 ns ± 10 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

`%timeit f2([3,4])`
Output:
6.02 µs ± 275 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

When I use large lists, it can be 1000 times slower.

### PR DESCRIPTION
**Pull request by caley**
#### References to other Issues or PRs
Fixes  #14654

#### Brief description of what is fixed or changed

Improve performance of lambdify generated code when given arguments that
require unpacking.  Changes lambdastr so that the argument unpacking is done
at code-generation-time instead of at run-time.

### CODE REVIEW

**Comment by caley** [comment]
There is already a test for nested arguments - test_issue_2790() in test_lambdify.py (for #2790).  Is that sufficient?  As this is a performance issue, is there a way to add performance tests?  i.e. the benchmarks run by @moorepants  as in #14671?

**Comment by asmeurer** [comment]
You can add benchmarks to https://github.com/sympy/sympy_benchmarks if you like.

**Comment by asmeurer** [comment]
I would actually add some additional tests. The existing tests all have the same format (a, (b, (c, ...))). Additionally, the expression for the existing tests is just x + y + z, which won't catch errors if the arguments are mixed up somehow.

**Comment by caley** [comment]
I've add some test cases for the unpacking.  The changes in this pull request also appear to have fixed #14655, so I've added a test case for that.  But I don't know anything about tensorflow, so perhaps someone can comment on whether the new behaviour is desirable?

**Comment by asmeurer** [comment]
Using the example from the issue, in master, `f2([3,4])` takes 8.88 µs and `f1(3,4)` takes 470 ms. In this branch `f1(3,4)` is the same and `f2([3,4])` takes 983 ns. Still slower but that's to be expected considering it is doing more with the unpacking. 

For reference, I also tested

```py
def f(_0):
    x, y = _0
    return x*y
```

and it takes 450 ns. So my idea would be faster. But it requires a bit more refactoring of the lambdify code.

**Comment by caley** [comment]
I could look at generating function definitions instead of lambdas, if nobody else is.  I've noticed there are a few related issues and open pull requests that would need to be considered, e.g. #12463, #11457.

Also, this wouldn't work with the Tensorflow example in #14655, but perhaps that is ok: it just means the generated function expects an iterable argument.

**Comment by asmeurer** [comment]
@bjodah may have comments on that. We should probably open a dedicated issue for it. I think it's just a question of making sure the printers have a proper split between things that print expressions and things that print statements. I think we already started doing something like this in the C printers, so maybe you could look there.

**Comment by asmeurer** [comment]
I started https://github.com/sympy/sympy/issues/14702 for it. We should look at it for a separate pull request. 

For this PR, I was hoping someone could comment on the tensorflow thing. But if no one does soon, we should just merge it.

**Comment by SebastianRiedel** [comment]
Sorry, I did not have the time to look into it anymore. Regarding this pull request here and looking at the new test cases, the changes seem fine for me and I appreciate your work very much. I could try if it fixes #14655 for me earliest on Wednesday (we're hosting a project workshop atm).

In general, what I did to make things work with Tensorflow last week was adding https://www.tensorflow.org/api_docs/python/tf/split operations to split an array X into columns Xlist = [x0, ..., xn] to call the lambdified function like func(*XList).

I'm not sure about the 
```
def f(_0):
    x, y = _0
    return x*y
```
way and would need to test that with tensorflow on Wednesday as well.

**Comment by SebastianRiedel** [comment]
I can confirm that for me this PR fixes #14655 and I think it is a desirable behavior, also for tensorflow. I think it can be merged.

**Comment by caley** [comment]
There are still the semantic differences to think about.  This PR will fix #14655, but if we will then break it again if we want to implement the slightly faster option
```
def f(_0):
    x, y = _0
    return x*y
```
Python tuple-unpacking expects the right hand side to be iterable (I think?).  But this PR would allow non-iterable _0 as well.

**Comment by asmeurer** [comment]
For tensorflow we can probably use a wrapper. Or generate custom code. This PR adds tests which is good, so the behavior won't break in the future no matter what we do. 

There are semantic differences but hopefully no one (other than tensorflow) will rely on them. And I'm honestly not sure what is going on with tensorflow but it perhaps ought to be fixed upstream.  Anything that can be indexed 0, 1, 2, ... ought be iterable IMHO.

**Comment by caley** [comment]
Yes, good point: For  #14702  we could generate custom code for tensorflow.  Something like
```
def f(_0):
    x, y = _0[0], _0[1]
    return x*y
```

**Pull request merged**
