### PR TITLE
ntheory : Add functionality to return list of all factors

### LINKED ISSUE #12101: List of prime factors including multiplicity is missing
The vast majority of the time when using prime factorization in algorithms I'm interested in a list of prime factors. E.g. for 24 it's `[2, 2, 2, 3]`. However sympy (to my knowledge) only provides `sympy.factorint` which returns a dictionary. I always end up writing a helper function:

    factorlist = lambda fac: sum(([p] * fac[p] for p in sorted(fac)), [])

It would be really nice if factorizations in this format were directly provided by sympy, either by an option to `factorint` (e.g. `sympy.factorint(24, aslist=True)`) or under a new function name entirely.

### PR DESCRIPTION
**Pull request by ArifAhmed1995**
Passing in the argument `multiple=True` to `factorint()` or `factorrat()` returns a list of all the prime factors constituting the number along with multiplicity.

Example:
```
>>> factorint(222,multiple=True)
[2, 3, 37]
>>>factorrat(S(25)/14, multiple=True)
[1/2, 5, 5, 1/7]
```

Fixes #12101

### CODE REVIEW

**Comment by ArifAhmed1995** [comment]
@smichr Can you review this PR ?

**Comment by isuruf** [comment]
Instead of all of these if conditions, would it make sense to implement one of the solutions in the mentioned issue for `multiple=True`?

**Comment by ArifAhmed1995** [comment]
Pardon me , I didn't quite understand what you meant. Did you mean to reduce the number of `if` checks for `multiple` ? The `if` conditions are for the `return` statements and I can't see how to remove even a single one. Actually now I've added an extra `if` check to compute `factorlist` only if `multiple = True`.

**Comment by isuruf** [comment]
Something like
```
if multiple:
    d = factorint(n, multiple=False)
    //produce the list from dictionary and return
```

**Comment by ArifAhmed1995** [comment]
Oh yes ! That's much simpler.

**Pull request closed without merging**
