### PR TITLE
Clean up Theano printer, add comments and docstrings

### PR DESCRIPTION
**Pull request by jlumpe**
### Overview

Made the following changes to the Theano code printer:

* Added docstrings to major parts of user API with detailed information on parameters
* Unified some of the code for caching Theano variables which the printer has created for Sympy symbols.
* Fixed bugs in test cases that caused tests to pass when the should have failed and added additional test cases.
* General cleanup of code in base module and test module.
* Changed the way `theano_function()` works when there is only one output - now accepts a single expression as the output instead of forcing you to wrap it in a list, and has an option to enable a more consistent list-in-list-out behavior. The new behavior is opt-in via a keyword argument in order to avoid breaking backwards compatibility, but the old behavior has been deprecated. See #14986.
* `theano_function()` now optionally returns a wrapper around the Theano function object which converts 0-dimensional arrays in the output (which can be annoying to work with) to scalars.

### Remaining issues

I will resolve these in a 2nd PR:

* The `dim_handling` function only serves to process arguments to `theano_function()`, but seems to be part of the public API. I think this function should be deprecated and the functionality moved to `TheanoPrinter.doprint()` so that it is available through all parts of the public API (see #14985).
* The current logic behind caching Theano variables created for Sympy symbols is opaque to the user. The key incorporates the requested data type, so different Theano variables may be created for the same symbol in different calls to `TheanoPrinter.doprint()` if the user gives that data type the first time but not the 2nd. I have started trying to make this process more transparent with a defined contract with the user.
* The user should be able to associate existing Theano variables (created by themselves or by another library) with Sympy symbols.

### Release notes:

* printing
  * Added `squeeze=False` option to `theanocode.theano_function` to give more consistent sequence-in-sequence-out behavior, keep old behavior as default for now but deprecate it.
  * Added `scalar=True` option to `theanocode.theano_function` to create a function which returns scalars instead of 0-dimensional arrays.

### CODE REVIEW

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/wiki/Deprecating-policy regarding the backwards incompatible behavior.

**Comment by jlumpe** [comment]
@asmeurer this is very nearly ready to merge, but I'm running into a strange issue with the doctests that I'm hoping you can shed some light on. The functions created by `theanocode.theano_function()` always return Numpy arrays, even in the case when the output is a scalar. Somehow the doctests are printing these as plain numbers instead. Here is an example case:

```python
def foo():
    """ Test

    Examples
    ========

    >>> from sympy.printing.theanocode import foo
    >>> foo()
    array(0)
    """
    import numpy as np
    return np.array(0)
```

This fails with `bin/doctest` with the following message:
```
File "/Users/student/git/sympy/sympy/printing/theanocode.py", line 371, in sympy.printing.theanocode.foo
Failed example:
    foo()
Expected:
    array(0)
Got:
    0
```

The doctests do run correctly using `pytest --doctest-modules`, so it seems to be something Sympy-specific.

**Comment by asmeurer** [comment]
@jlumpe the doctests are run through the sympy str printer. I thought the NumPy stuff was fixed, though, but I guess not.

**Comment by asmeurer** [comment]
This is the problem

```
>>> init_printing(pretty_print=False)
>>> np.array(0)
0
```

The init_printing should use `repr` instead of `str` for types that don't have printers. 

Unless you have an easy fix, I would just leave this for now and open an issue about it.

**Comment by jlumpe** [comment]
@asmeurer I have worked around it for now by adding an option to return a wrapper that converts 0-dimensional arrays to scalars in the output, and using that in all the examples. I think that would actually be the way most people would prefer to use it, anyways.

This is now ready to merge. I will file an issue or PR for the doctest behavior.

**Comment by jlumpe** [comment]
@asmeurer, any chance of getting this merged?

**Comment by asmeurer** [comment]
Can you add a note to the "backwards incompatible breaks and deprecations" section of https://github.com/sympy/sympy/wiki/Release-Notes-for-1.4 linking to https://github.com/sympy/sympy/issues/14986

**Comment by moorepants** [comment]
Note that I've come across some backward incompatible changes from this PR and have commented on them here: https://github.com/sympy/sympy/issues/14986

My current opinion is that the backwards incompatible changes (intentional and unintentional) should be reverted.

**Pull request merged**
