### PR TITLE
Non-Symbol _diff_wrt objects derivative fixes

### PR DESCRIPTION
**Pull request by Upabjojr**

### CODE REVIEW

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/pull/11571

**Comment by asmeurer** [comment]
Should this be closed in favor of #11571?

**Comment by asmeurer** [comment]
And either way, can you add a direct test for this?

**Comment by Upabjojr** [comment]
> Should this be closed in favor of #11571? 

No, this is the easy fix that is ready for merging.

> And either way, can you add a direct test for this? 

How can you test this? Derivatives are already extensively tested. There are tests for derivatives of `IndexedBase`, they would have failed if this code had been wrong.

**Comment by asmeurer** [comment]
There's an IndexedBase test that would give 0 if this logic wasn't here?

**Comment by Upabjojr** [comment]
> There's an IndexedBase test that would give 0 if this logic wasn't here?

https://github.com/sympy/sympy/blob/d630b29493b4a2ff4dc2bdd259ad76b4ed6702e4/sympy/tensor/tests/test_indexed.py#L213

**Comment by asmeurer** [comment]
OK, seems fine to me.

**Comment by asmeurer** [comment]
Is this both the first and third checkboxes at https://github.com/sympy/sympy/issues/11568?

**Comment by Upabjojr** [comment]
> Is this both the first and third checkboxes at #11568?

Yes

**Comment by moorepants** [comment]
FYI, this gave about a 4X speed up for taking derivatives wrt to symbols and functions, see for example: http://www.moorepants.info/misc/sympy-asv/#large_exprs.TimeLargeExpressionOperations.time_jacobian_wrt_symbols.

**Pull request merged**
