### PR TITLE
Manually set bounding box for 3d plots

### LINKED ISSUE #19051: Plots are displaying incorrectly on the development documentation website
See: https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam.html#sympy.physics.continuum_mechanics.beam.Beam.plot_bending_moment

Other possible related issues:

- #18901
-  #19023
- #18974

Here are a couple of examples:

image

image

### LINKED ISSUE #19106: Overflowing graphic issues in plot3d_parametric_line
`plot3d_parametric_line((2*cos(x), 2*sin(x), 2*x, (x, -5, 5)), (sin(x), cos(x), x, (x, -5, 5)))`
image
`plot3d_parametric_line((sin(x), cos(x), x, (x, -5, 5)), (2*cos(x), 2*sin(x), 2*x, (x, -5, 5)))`
image

I see a lot of issues like #19051 happen after we had started to use `LineCollection` instead of more high level `Axes.plot` API. But I see this was deliberately done because of the limitation of coloring support for `Axes.plot`.
The problem is that we must set the limits manually if we are manipulating low level graphical primitives.

I think that each `Series` needs some helper for computing the bounds of the overall mesh
rather than doubly computing the points and overriding the limits naively like 
https://github.com/sympy/sympy/blob/d02120c1ec491fe9322f4ad35fc8040b6b6a191d/sympy/plotting/plot.py#L1091-L1094

Although #19088 claims that `autoscale_view` works, I have found that this breaks 3D plotting more worse than before.
image

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

 
Fixes #19051 
Fixes #19106

#### Brief description of what is fixed or changed

Since matplotlib's `autoscale_view` is not properly working with 3D axes, I have made a custom bounding box helper for every 3d plots.
So `_xlim`, `_ylim`, `_zlim` stores the information about minimal bounding box after the points are sampled.

#### Other comments

I've also reorganized the tests to use `TemporaryDirectory` which was not available with python 2.7 before, ~and marked plotting examples using symbolic summations and integrals to be slow because they are impractical.~ I've tried marking with `@slow` but it prevents being run on travis.

#### Release Notes

- plotting
  - Fixed `plot3d_parametric_line` plotting curves out of the box.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This looks good to me although I don't think I understand all of the changes.

@sylee957 I think we want this in 1.6 because it eliminates the use of `set_smart_bounds`. There are a lot of other changes and it isn't clear to me if those can be separated but I want to put this into 1.6 if you've checked this and you think it can go in.

**Comment by sylee957** [comment]
When I try to open a PR to 1.6, I think that the changes from #19239 need to be added.
I'm not sure how to resolve such conflicts if the release branch is based off from the older base

**Comment by oscarbenjamin** [comment]
Those changes can be added as well. It can be done as two separate PRs if needed.

I would do it like:
```
git checkout 1.6
git checkout -b pr_my_branch
git cherry-pick abc123   # one commit
git cherry-pick abc123..def456  # range of commits
```

**Comment by oscarbenjamin** [comment]
@sylee957 this looks good to me. I'll let you merge if you're done with it.

**Pull request merged**
