### PR TITLE
complex and constant functions in theanocode

### PR DESCRIPTION
**Pull request by chrisgee**
- I added conjugate and ImaginaryUnit to the sympy to theano mappings 
- I added a fix in theano_function to map constant sympy expressions into theano variables.

The first adds support for complex algebra, the second fixes a crash in case one of the outputs evaluates to a constant in sympy.

### CODE REVIEW

**Comment by moorepants** [comment]
@chrisgee  Can you please add some unit tests for these new features?

**Comment by chrisgee** [comment]
@morrepants: unit test for theanocode added. Also added a fix to codegen to allow complex valued variables in fortran and unit tests for those

**Comment by moorepants** [comment]
Sorry to leave this hanging. Seems that there are trailing whitespaces in the codegen file that need to be fixed.

**Comment by andryandrew** [comment]
Are there any updates on this? I just stumbled on trying to use constants and complex numbers with Theano, and I'm facing the lack of support. Is there something I can do to help fixing this?

**Comment by moorepants** [comment]
This needs to be updated wrt to master and the failed CI runs need to be investigated. You can pull this branch, try to fix, and submit a new PR if you'd like to help.

**Comment by oscargus** [comment]
I have taken up this PR in #15885 so I close this.

**Pull request closed without merging**
