### PR TITLE
Add hadamard product printing for mathml

### PR DESCRIPTION
**Pull request by sylee957**
#### Brief description of what is fixed or changed

I'm not sure if anything exists for mathml content printer.

#### Release Notes

- printing
  - Add support for `HadamardProduct` in mathml presentation printer.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This needs a test

**Comment by oscargus** [comment]
I will review this, but can you @sylee957 please add a screen dump of what the result looks like? (A test will also be an alternative as I can easily render it myself then.)

**Comment by sylee957** [comment]
So far, I have added two tests from `test_latex`

- `mathml(HadamardProduct(X, Y*Y), printer="presentation")`
  image
- `mathml(HadamardProduct(X, Y)*Y, printer="presentation")`
  image

Unfortunately, my web browser does not allow mathml, so I could only render with 
http://www.mathmlcentral.com/Tools/FromMathML.jsp

**Review by oscargus — APPROVED** [review]
Looks good! I think the number of tests etc are OK. Are you planning to add more? If not, it can be merged.

**Pull request merged**
