### PR TITLE
adding relevant info for non commutative arguments

### PR DESCRIPTION
**Pull request by shilpiprd**
Add information about non commutative arguments

#### Brief description of what is fixed or changed 
Made changes in sympy/doc/src/tutorial/gotcha.rst folder.

I wasn't sure if i should create a new doc file so i made changes in existing gotcha file. But if you need me to make a new file let me know.
This is my first pull request. Please review

### CODE REVIEW

**Comment by anutosh491** [comment]
Being your first Pr make sure to go throught the development workflow and read about creating pull requests , contributing to sympy and related conventions.

This Includes creating a new branch,naming conventions for branches and why you should never push code through your local master branch .

https://github.com/sympy/sympy/wiki/Development-workflow#create-a-new-branch

Also the test fails because you need to add " NO ENTRY " inside the release notes tag ! Hope this helps

**Comment by anutosh491** [comment]
> Being your first Pr make sure that you go throught the development workflow and read about creating pull requests , contributing to sympy and related conventions.
> 
> This Includes creating a new branch,naming conventions for branches and why you should never push code through your local master branch .
> 
> https://github.com/sympy/sympy/wiki/Development-workflow#create-a-new-branch
> 
> Also the test fails because you need to add " NO ENTRY " inside the release notes tag ! Hope this helps

**Comment by shilpiprd** [comment]
Thanks a lot for the feedback. I'll delete this branch and create a new branch which will directly merge with my forked repo.

**Comment by anutosh491** [comment]
@shilpiprd you could close this Pr, now that you've created a new one and I guess don't plan to work on this one anymore !

**Comment by oscarbenjamin** [comment]
If another PR replaces this one then there should be a link to the other PR here.

**Comment by anutosh491** [comment]
> If another PR replaces this one then there should be a link to the other PR here.

Yeah @shilpiprd had committed this from the master branch not knowing that we need to commit every change/Pr through separate branches. So now there's an another PR just above this one where the commit has been done through a different branch . Hence this can be closed .

https://github.com/sympy/sympy/pull/22503
This is the new one !

**Comment by shilpiprd** [comment]
i created this pr in master branch but i'm working on the other one related to the issue. i'll close this pr now

**Pull request closed without merging**
