### PR TITLE
Corrected Failing Tests in Prefixes Module in Units

### PR DESCRIPTION
**Pull request by Shikhar1998**
Trivial Modifications

#### References to other Issues or PRs

None

#### Brief description of what is fixed or changed
Corrected some failing test cases observed while testing locally in `sympy/physics/units/tests/test_prefixes.py` which were skipped otherwise by `CircleCI`.

#### Other comments
None

### CODE REVIEW

**Comment by Shikhar1998** [comment]
ping @smichr.

**Comment by ylemkimon** [comment]
Why this was skipped?

**Comment by Shikhar1998** [comment]
On a closer look, I found that they do not fail on `Circle CI` builds. However, with the current `master` I do get error while running the tests locally. 
mew
I am not able to comprehend the reason why, but some discrepancy does exist.

**Comment by gxyd** [comment]
Is this similar to the discussion here https://github.com/sympy/sympy/pull/13710#discussion_r157346413 ?

**Comment by Shikhar1998** [comment]
+1, it look quite similar. It seems `Circle CI` is passing tests that must actually fail.

**Pull request merged**
