### PR TITLE
Fixes Issue #9506

### PR DESCRIPTION
**Pull request by bhavishyagopesh**

### CODE REVIEW

**Comment by aktech** [comment]
Please have a look at https://github.com/sympy/sympy/wiki/Development-workflow#writing-pull-request-title-and-description

> The description is a good place to:

>show what you have done, perhaps comparing output from master with the output after your changes
refer to the issue that was addressed like "#1234"; that format will automatically create a link to the corresponding issue or pull request, e.g. "This is similar to the problem in issue #1234...". This format also works in the discussion section of the pull request.
use phrases like "closes #1234" or "fixed #1234" (or similar that follow the auto-close syntax) then those other issues or pull requests will be closed when your pull request is merged. Note: this syntax does not work in the discussion of the pull request.

**Comment by smichr** [comment]
This should be detected in the routine, I believe, and raise a warning or error (whichever is preferred). @moorepants

**Comment by moorepants** [comment]
@smichr Agreed.

**Comment by gxyd** [comment]
This PR has been inactive for quite sometime, so we are going to close it and open an issue to reference it. We try to keep our pull request queue small and focused on active work.  We encourage you to reopen the pull request if and when you continue to work on this. Please contact us if you have any questions.

Thanks for contributing.

see https://github.com/sympy/sympy/wiki/Closing-pull-requests for our policies on closing pull request.

**Pull request closed without merging**
