### PR TITLE
units: fixed convert_to() bug and added some tests

### LINKED ISSUE #21463: Unit conversion returns erroneous result for inverse of sum (bad Pow handling probably)
Python version: 3.9.2
SymPy version: 1.6.2

I was able to isolate this unit conversion issue to inverse of sums of quantities. Maybe `conver_to` is not handling powers correctly, since the inverse function is implemented like `(expr)**(-1)`.

```python
from sympy.physics.units import m, convert_to
from sympy.abc import beta
from sympy import Tuple
# suppose beta is a unitless ratio
# units for this should be 1/m
expr = 1/(beta*m+m)

# As expected, the simplified outer expression is a multiple of 1/m
Tuple(expr, expr.simplify())

# Units are 1/m**2 for some reason, maybe because 
Tuple(convert_to(expr, m**(-1)), convert_to(expr, m**(-1)).simplify())

# If the expression is just a multiple of the unit then it works as expected
Tuple(convert_to(expr.simplify(), 1/m), convert_to(expr.simplify(), 1/m).simplify())
```

On jupyter:
image

### PR DESCRIPTION
**Pull request by JotacBravo**
#### References to other Issues or PRs

Fixes #21463

#### Brief description of what is fixed or changed

Fixed a convert_to() function bug where the result for some inverse sums duplicated the expression units incorrectly.
I found that by using the together() function, these duplicates are prevented when the expression is a function.

Examples:

- Before

In [1]: convert_to(1/(beta*meter+meter), 1/meter)
Out [1]: 1/(meter*(meter*beta + meter))

- After

In [2]: convert_to(1/(beta*meter+meter), 1/meter) 
Out [2]: 1/(meter*beta + meter)

#### Release Notes

* physics.units
  * Fixed a bug with convert_to function.

### CODE REVIEW

**Comment by smichr** [comment]
Just used the preferred format for creation of symbols in the test suite.

**Comment by smichr** [comment]
We can wait to see if there are any other comments.

Should `cancel` be used or is `together` sufficient?

**Comment by JotacBravo** [comment]
> We can wait to see if there are any other comments.
> 
> Should `cancel` be used or is `together` sufficient?

I did some more tests and for all of them, cancel and together gave the same results, so together seemed sufficient to me.

**Comment by smichr** [comment]
Nice to have this old issue fixed. Thanks!

**Pull request merged**
