### PR TITLE
Add a Circle CI job to show a preview of the docs on PRs

### LINKED ISSUE #23460: Set up a docs build preview on CI
We should set up a docs build preview on CI. 

I'm not sure how to do it on GitHub pages, but you can see how NumPy does it with Circle CI https://github.com/numpy/numpy/blob/main/.circleci/config.yml. The idea is there should just be a button down with the checks where if you click on "details" it takes you to the docs built for that PR. 

If it is possible to do this on GitHub Actions that would be preferable than setting up a separate CI service, but there might be a reason it can't work.

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes #23460.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
Circle worked but I can't get the GitHub Actions build to appear (maybe I just need to wait?). 

Also the authors build is failing. Is it because it's on a "push" build instead of a PR build?

**Comment by asmeurer** [comment]
The [page for the GitHub Actions](https://github.com/larsoner/circleci-artifacts-redirector-action) says this might not work for PRs from forks. But it seems to work on every NumPy PR I checked, so I'm not sure if that's still true. If it doesn't work we can switch to Jason's idea.

**Comment by oscarbenjamin** [comment]
> The [page for the GitHub Actions](https://github.com/larsoner/circleci-artifacts-redirector-action) says this might not work for PRs from forks.

This is the reason that the benchmarks comment-on-pr workflow is separate from the main runtests workflow. Basically the runtests workflow doesn't have permissions to do things like comment on a PR. A separate workflow that runs with the master branch version of the workflow files can have these permissions.

**Comment by oscarbenjamin** [comment]
I see that the authors test is failing:
```
Run bin/mailmap_check.py --skip-last-commit
fatal: ambiguous argument 'HEAD^2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/bin/mailmap_check.py", line 327, in <module>
    sys.exit(main(*sys.argv[[1](https://github.com/sympy/sympy/runs/6298124542?check_suite_focus=true#step:6:1):]))
  File "/home/runner/work/sympy/sympy/bin/mailmap_check.py", line 56, in main
    git_people = get_authors_from_git(skip_last=args.skip_last_commit)
  File "/home/runner/work/sympy/sympy/bin/mailmap_check.py", line 252, in get_authors_from_git
    move(git_people, 2, 0, 'Ondřej Čertík')
  File "/home/runner/work/sympy/sympy/bin/mailmap_check.py", line 246, in move
    x = l.pop(i1)
IndexError: pop index out of range
Error: Process completed with exit code 1.
```
That ("unknown revision") suggests that the commit use in CI (in the runtests workflow) doesn't have two ancestors for the merge commit. Not sure why that might be...

**Comment by asmeurer** [comment]
> That ("unknown revision") suggests that the commit use in CI (in the runtests workflow) doesn't have two ancestors for the merge commit. Not sure why that might be...

Because it's a "push" build. I pushed the branch directly up to the repo in addition to my fork so that I could test Circle without merging. You'll probably get the same error whenever you make a release branch.

**Comment by asmeurer** [comment]
> A separate workflow that runs with the master branch version of the workflow files can have these permissions.

I wonder if that's why the GitHub Actions preview "build" isn't showing up. Where are those permissions set?

**Comment by asmeurer** [comment]
I removed the merge logic from the authors script, and it seems to be passing. Was it adding some special GitHub user for the merge commit before? It doesn't seem to be doing that https://github.com/sympy/sympy/runs/6314266852?check_suite_focus=true#step:6:12

**Comment by asmeurer** [comment]
I can't figure out how to make the actual GitHub Actions step of this work. It isn't reporting the status with the link to the built page. Maybe it would only work once it is in master itself, although it seems to me it ought to at least work on the push build.

**Comment by oscarbenjamin** [comment]
> I removed the merge logic from the authors script, and it seems to be passing.

The merge logic is needed for someone who has correctly set up their metadata in their commits (with `git config`) but whose github settings mean that github uses different metadata in any commits that it creates for them: https://github.com/sympy/sympy/pull/23265#issuecomment-1074484573.

**Comment by asmeurer** [comment]
OK, I can't figure out how to get the GitHub Actions link to actually show up. I even tried making a PR within the same repo so there are no forks, and it didn't work there either https://github.com/sympy/sympy/pull/23469. @larsoner do you have any suggestions? I've more or less directly copied this from another repo where I know it works. 

The only thing I can think of is that it has to be merged into master first before it will work. I do already have this as a branch pushed to the main repo, so it seems to me that ought to be enough, but maybe it isn't. So we can try merging this. @oscarbenjamin are you OK with the mailmap_update change?

If we can't get this working, I guess we can try using @moorepants's approach instead.

**Comment by asmeurer** [comment]
Oh I didn't see your comments. I'll just revert the mailmap script change. You might need to do something about it for the release branch later. I'm also surprised it doesn't cause the master builds to fail. 

It sounds pretty likely that this just isn't working because it isn't in master. Since I can't think of anything else, I'm just going to merge this (after reverting the mailmap script change). If it doesn't work then, I'll keep hammering on it, or try Jason's approach if I can't figure it out.

**Comment by larsoner** [comment]
> The only thing I can think of is that it has to be merged into master first before it will work.

Yes because it operates on the `[status]` event that only gets processed on `main` AFAIK, you'll probably have to merge it and then see if it works

**Pull request merged**
