### PR TITLE
Some Pyglet fixes

### PR DESCRIPTION
**Pull request by asmeurer**
Apparently I had pyglet installed from conda and there were some test failures.

I fixed the test failures, but the plotting doesn't actually work for me. I'm not sure if it's my computer or not. Can someone with Linux install pyglet and test if the following produces a plot in this branch? 

```py
from sympy.plotting.pygletplot import PygletPlot
import sympy.plotting.pygletplot.plot_modes
from sympy.abc import x, y

PygletPlot(x*y)
```

You can also test it in (Python 2-only) sympy-1.1.1. 

<edit test 1>

### CODE REVIEW

**Comment by jksuom** [comment]
There seem to be errors in Linux as well:
```
>>> p = PygletPlot(x*y)
>>> p.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/plotting/pygletplot/plot.py", line 257, in show
    self._window.activate()
  File "/home/jks/miniconda3/envs/python2/lib/python2.7/site-packages/pyglet/window/xlib/__init__.py", line 571, in activate
    xlib.RevertToParent, xlib.CurrentTime)
ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: wrong type
```

**Comment by thisch** [comment]
I can reproduce the error by @jksuom  on Linux by applying the following patch

```diff
diff --git a/sympy/plotting/pygletplot/color_scheme.py b/sympy/plotting/pygletplot/color_scheme.py
index 74bae4acf..fa95f5354 100644
--- a/sympy/plotting/pygletplot/color_scheme.py
+++ b/sympy/plotting/pygletplot/color_scheme.py
@@ -205,6 +205,7 @@ def _fill_in_vars(self, args):
     def _sort_args(self, args):
         lists, atoms = sift(args,
             lambda a: isinstance(a, (tuple, list)), binary=True)
+        return atoms, lists
```

**Comment by asmeurer** [comment]
That change is already part of this branch. Are you testing against this branch or master?

**Comment by thisch** [comment]
Sry, I forgot to mention that I'm testing against the master branch.

**Comment by oscargus** [comment]
Closing this as it should have been automatically closed when merging #16513

**Pull request closed without merging**
