### PR TITLE
Trying out CodeQL

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed

CodeQL is Githubs static code analysis tool. May be worth using.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscargus** [comment]
If it works, one should probably integrate this into the normal test actions so that it is not executed first.

**Comment by oscarbenjamin** [comment]
Is it necessary to merge this before being able to see what the output is? I don't see a CodeQL job in the actions list.

**Comment by oscargus** [comment]
I do not think so, see https://github.com/matplotlib/matplotlib/pull/22446

It may be that it doesn't start because I created it in the main repo (as the setup was semi-automated) and the CircleCI test failed. I'll give it a try creating the branch in my repo and open a PR from there.

**Comment by oscarbenjamin** [comment]
> I'll give it a try creating the branch in my repo and open a PR from there.

Perhaps you could just push it straight to master in your fork.

**Comment by oscargus** [comment]
Not sure. I do not understand what else is required. Maybe there should be some setting for the repo that I do not have access to?

But I can close them for now.

**Comment by oscarbenjamin** [comment]
> I do not understand what else is required.

It's possible that it just needs to be merged to master before it will run. Have you tried pushing it to your fork and opening a PR against maser there?

**Pull request closed without merging**
