### PR TITLE
Add general solution for the PDEs to the docstrings

### PR DESCRIPTION
**Pull request by nicoguaro**
#### References to other Issues or PRs

Closes #12370

#### Brief description of what is fixed or changed

Update documentation for PDE utils.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Review by sylee957 — COMMENTED** [review]
I'm getting an error while building sphinx doc from your commit
```
Extension error:
Could not import extension numpydoc (exception: cannot import name 'Directive')
Makefile:50: recipe for target 'html' failed
make: *** [html] Error 2
```
And it looks like your branch is too old.
Can you rebase this branch to the current master?

**Comment by nicoguaro** [comment]
@sylee957, I will try. This happened before, my PR are not too important and they get old.

**Comment by nicoguaro** [comment]
@sylee957, I just reran the whole docstring test set and everything was ``[OK]``. Are you running something "special"?

**Comment by oscarbenjamin** [comment]
It's not the doctests that have failed but actually building the html docs.

**Comment by nicoguaro** [comment]
Oh, let met check that out.

**Comment by nicoguaro** [comment]
I get 

    Makefile:146: recipe for target 'logo' failed

But, I think that little to do with my PR, isn't it?

**Comment by oscarbenjamin** [comment]
This is probably because of many other changes that have happened since this PR started. You should rebase it to bring in the more recent changes.

**Comment by nicoguaro** [comment]
I rebased it, and I still get the same error due to the logo.

**Comment by sylee957** [comment]
Does your `make html` or `make logo` command work with upstream master?
If not, there may be some issues with your package installation.
For example, `librsvg` should be installed.

There is a tutorial in
https://github.com/sympy/sympy/tree/master/doc
where you can check whether all the necessary libraries are installed in your machine.

**Comment by nicoguaro** [comment]
I checked and now it works. I also corrected an indentation problem.

**Comment by nicoguaro** [comment]
Regarding the "tutorial" that you pointed out before, I think that it is an orphan page. So I was not aware of it.

**Comment by sylee957** [comment]
Well, I can’t see any changes here, but I think you had pushed new changes to the duplicate PR in #12370.

Can you pick your changes from #12370 here?

**Comment by nicoguaro** [comment]
Ohh, I thought I was commiting to this PR. What should I do then?

**Comment by sylee957** [comment]
I think you should commit to your `master` branch for here, because you have made a pull request from there.
Or make a fresh new start

**Pull request closed without merging**
