### PR TITLE
Check for k=-1 branch real solutions of the Lambert equation

### LINKED ISSUE #8708: Wrong solution for a simple inequality
I have tried to solve the following rather simple inequality:
```python
>>> x = symbols('x', real=True, positive=True)
>>> solve(1-x-exp(-2*x)>0)
False
```
and the result (`False`) was quite surprising, and indeed wrong, as, for example,
```python
>>> (1-x-exp(-2*x)).subs(x, S(1)/2).evalf()
0.132120558828558
```
which looks positive...

### PR DESCRIPTION
**Pull request by skirpichev**
fixes #8708

### CODE REVIEW

**Comment by asmeurer** [comment]
Is there something special about the k=-1 branch that makes it possible to be real (I don't know much about the LambertW function beyond the definition)? My understanding is that all branches are solutions, but most of them are usually nonreal.

**Comment by skirpichev** [comment]
> Is there something special about the k=-1 branch that makes it possible to be real

Yes, see e.g. [this](http://en.wikipedia.org/wiki/Lambert_W_function) or the docstring.

> My understanding is that all branches are solutions, but most of them are usually nonreal. 

Yes, but if the first argument of LamberW is real - we have only two real solutions (at most).

If we want to add all branches - this would be wast of time for the current solve().

**Comment by hargup** [comment]
This should also be added to `solveset`.

**Comment by skirpichev** [comment]
On Wed, Jan 14, 2015 at 09:00:45PM -0800, Harsh Gupta wrote:
>    This should also be added to solveset.

Sure.  Is this a requirement for pr?

**Comment by smichr** [comment]
The recognition of lambert by solveset can now proceed since we are returning a complete (real) solution (if I understand correctly). That is totally independent of this PR, however, and is listed as a nonblocking TODO on the solveset PR.

**Pull request merged**
