### PR TITLE
Expression blowup in matrix operations

### LINKED ISSUE #16823: Matrix rank () return the wrong rank of a complex matrix
There is an error in the Matrix.rank() function.
The rank of the following matrix T should be 8.
`T = Matrix([[S('1+I'),S('-19/4+5/4*I'),S('1/2-I'),S('9/4+55/16*I'),S('-3/4'),S('45/32-37/16*I'),S('1/4+1/2*I'),S('-129/64-9/64*I'),S('1/4-5/16*I'),S('65/128+87/64*I'),S('-9/32-1/16*I'),S('183/256-97/128*I'),S('3/64+13/64*I'),S('-23/32-59/256*I'),S('15/128-3/32*I'),S('19/256+551/1024*I')],[S('21/8+I'),S('-537/64+143/16*I'),S('-5/8-39/16*I'),S('2473/256+137/64*I'),S('-149/64+49/32*I'),S('-177/128-1369/128*I'),S('125/64+87/64*I'),S('-2063/256+541/128*I'),S('85/256-33/16*I'),S('805/128+2415/512*I'),S('-219/128+115/256*I'),S('6301/4096-6609/1024*I'),S('119/128+143/128*I'),S('-10879/2048+4343/4096*I'),S('129/256-549/512*I'),S('42533/16384+29103/8192*I')],[S('-2'),S('17/4-13/2*I'),S('1+I'),S('-19/4+5/4*I'),S('1/2-I'),S('9/4+55/16*I'),S('-3/4'),S('45/32-37/16*I'),S('1/4+1/2*I'),S('-129/64-9/64*I'),S('1/4-5/16*I'),S('65/128+87/64*I'),S('-9/32-1/16*I'),S('183/256-97/128*I'),S('3/64+13/64*I'),S('-23/32-59/256*I')],[S('1/4+13/4*I'),S('-825/64-147/32*I'),S('21/8+I'),S('-537/64+143/16*I'),S('-5/8-39/16*I'),S('2473/256+137/64*I'),S('-149/64+49/32*I'),S('-177/128-1369/128*I'),S('125/64+87/64*I'),S('-2063/256+541/128*I'),S('85/256-33/16*I'),S('805/128+2415/512*I'),S('-219/128+115/256*I'),S('6301/4096-6609/1024*I'),S('119/128+143/128*I'),S('-10879/2048+4343/4096*I')],[S('-4*I'),S('27/2+6*I'),S('-2'),S('17/4-13/2*I'),S('1+I'),S('-19/4+5/4*I'),S('1/2-I'),S('9/4+55/16*I'),S('-3/4'),S('45/32-37/16*I'),S('1/4+1/2*I'),S('-129/64-9/64*I'),S('1/4-5/16*I'),S('65/128+87/64*I'),S('-9/32-1/16*I'),S('183/256-97/128*I')],[S('1/4+5/2*I'),S('-23/8-57/16*I'),S('1/4+13/4*I'),S('-825/64-147/32*I'),S('21/8+I'),S('-537/64+143/16*I'),S('-5/8-39/16*I'),S('2473/256+137/64*I'),S('-149/64+49/32*I'),S('-177/128-1369/128*I'),S('125/64+87/64*I'),S('-2063/256+541/128*I'),S('85/256-33/16*I'),S('805/128+2415/512*I'),S('-219/128+115/256*I'),S('6301/4096-6609/1024*I')],[S('-4'),S('9-5*I'),S('-4*I'),S('27/2+6*I'),S('-2'),S('17/4-13/2*I'),S('1+I'),S('-19/4+5/4*I'),S('1/2-I'),S('9/4+55/16*I'),S('-3/4'),S('45/32-37/16*I'),S('1/4+1/2*I'),S('-129/64-9/64*I'),S('1/4-5/16*I'),S('65/128+87/64*I')],[S('-2*I'),S('119/8+29/4*I'),S('1/4+5/2*I'),S('-23/8-57/16*I'),S('1/4+13/4*I'),S('-825/64-147/32*I'),S('21/8+I'),S('-537/64+143/16*I'),S('-5/8-39/16*I'),S('2473/256+137/64*I'),S('-149/64+49/32*I'),S('-177/128-1369/128*I'),S('125/64+87/64*I'),S('-2063/256+541/128*I'),S('85/256-33/16*I'),S('805/128+2415/512*I')],[S('0'),S('-6'),S('-4'),S('9-5*I'),S('-4*I'),S('27/2+6*I'),S('-2'),S('17/4-13/2*I'),S('1+I'),S('-19/4+5/4*I'),S('1/2-I'),S('9/4+55/16*I'),S('-3/4'),S('45/32-37/16*I'),S('1/4+1/2*I'),S('-129/64-9/64*I')],[S('1'),S('-9/4+3*I'),S('-2*I'),S('119/8+29/4*I'),S('1/4+5/2*I'),S('-23/8-57/16*I'),S('1/4+13/4*I'),S('-825/64-147/32*I'),S('21/8+I'),S('-537/64+143/16*I'),S('-5/8-39/16*I'),S('2473/256+137/64*I'),S('-149/64+49/32*I'),S('-177/128-1369/128*I'),S('125/64+87/64*I'),S('-2063/256+541/128*I')],[S('0'),S('-4*I'),S('0'),S('-6'),S('-4'),S('9-5*I'),S('-4*I'),S('27/2+6*I'),S('-2'),S('17/4-13/2*I'),S('1+I'),S('-19/4+5/4*I'),S('1/2-I'),S('9/4+55/16*I'),S('-3/4'),S('45/32-37/16*I')],[S('0'),S('1/4+1/2*I'),S('1'),S('-9/4+3*I'),S('-2*I'),S('119/8+29/4*I'),S('1/4+5/2*I'),S('-23/8-57/16*I'),S('1/4+13/4*I'),S('-825/64-147/32*I'),S('21/8+I'),S('-537/64+143/16*I'),S('-5/8-39/16*I'),S('2473/256+137/64*I'),S('-149/64+49/32*I'),S('-177/128-1369/128*I')]])
Result; rank= 9 time: 11558.603042602539`
Matrix rank() and matrix rank(simplify=True) produce the wrong result 9.
Moreover, this function takes too much time (library gmpy2 installed).

### PR DESCRIPTION
**Pull request by tom-pytel**
#### References to other Issues or PRs
Fixes #18049

#### Brief description of what is fixed or changed
This is a continuation of #18049 where I've added the dotprodsimp functionality to more matrix functions.

#### Release Notes

* matrices
  * Added optional `dotprodsimp` intermediate simplification to many functions to control blowup.

### CODE REVIEW

**Comment by Pristine-Cat** [comment]
PR 18049 was incomplete since @sylee957 didn't want a huge merge on his hands. This is a continuation of that to extend matrix expression blowup to more matrix functions. Some of these functions may still need some tweaking and maybe there are a few I missed so please advise.

The `dotprodsimp` simplification step works very well in many cases and so-so in some others. I've compiled a matrix of comparisons (pun intended) to the vanilla functionality as well as to simplified vanilla. For ease of parsing I've broken it up into two sections, the first where the `dotprodsimp` functionality clearly helps and the second where it is more mixed:
```
6x6 or 4x4 matrix (time in ms.)             |         A      ops  |         B      ops  |         C      ops  |         D      ops
                                            |                     |                     |                     |
M**4                                        |      1.03      504  |      0.59     9997  |      1.82    21524  |      0.68    22565
M.pow(4, dotprodsimp=True)                  |      3.29      108  |     75.70      396  |      4.48      156  |    523.00    12924
simplify(M**4)                              |    322.00      108  |   6360.00      396  |  17900.00      156  |  35629.77     8929
                                            |                     |                     |                     |
M**16                                       |      2.94     2412  |    243.00  1407529  |   8720.00  3024706  |    266.00  3170757
M.pow(16, dotprodsimp=True)                 |      6.83      108  |    200.00    44892  |     53.30      156  |             failed
simplify(M**16)                             |    985.00      108  |             failed  |             failed  |             failed
                                            |                     |                     |                     |
M.charpoly()                                |   1640.00       11  |  22900.00       10  |  54160.72       30  |  46574.49     1490
M.charpoly(dotprodsimp=True)                |     26.00       11  |     90.40       10  |      6.50       30  |   2690.00     1490
M.charpoly(simplify=lambda e: e)            |     29.80       11  |    219.00       10  |   1410.00    65913  |    939.00    66961
                                            |                     |                     |                     |
M.rref()                                    |     62.40        0  |    295.00       92  |   3470.00     2408  |             failed
M.rref(dotprodsimp=True)                    |     46.60        0  |     26.80        4  |      4.45       33  |             failed
simplify(M.rref()[0])                       |     64.10        0  |    357.00        4  |   6690.00       33  |             failed
                                            |                     |                     |                     |
M.eigenvals()                               |   1630.00        1  |  23000.00       30  |  55383.44     7974  |             failed
M.eigenvals(dotprodsimp=True)               |     28.70        1  |     94.70       30  |    112.81     7974  |             failed
                                            |                     |                     |                     |
M.det('berkowitz')                          |      1.76     1265  |      1.67    20916  |      4.92    45946  |      1.87    46466
M.det('berkowitz', dotprodsimp=True)        |     27.00        0  |     88.60        0  |      5.73        0  |   2570.00      612
simplify(M.det('berkowitz'))                |    803.00        0  |  15700.00        0  |                  0  |  20400.00      612
                                            |                     |                     |                     |
M.det('bareiss')                            |      8.70        0  |     91.80        0  |    198.00        0  |   3280.00
M.det('bareiss', dotprodsimp=True)          |      1.66        0  |      1.32        0  |      3.97        0  |             failed
simplify(M.det('bareiss'))                  |      8.96        0  |     93.60        0  |    196.00        0  |             failed
                                            |                     |                     |                     |
M.det('lu')                                 |      1.06        0  |      1.47     2387  |      1.90     5148  |    204.83     5148
M.det('lu', dotprodsimp=True)               |     20.40        0  |      2.17        0  |      3.47        0  |             failed
simplify(M.det('lu'))                       |      1.06        0  |  11400.00        0  |  33315.70        0  |             failed
                                            |                     |                     |                     |
M.inv(method='CH')                          |     37.00    41290  |     37.40    45530  |     60.80    92731  |     58.20    92731
M.inv(method='CH', dotprodsimp=True)        |    145.00       40  |    253.00       56  |     63.40       46  |     83.40     1192
simplify(M.inv(method='CH'))                |             failed  |             failed  |             failed  |             failed
                                            |                     |                     |                     |
M.inv(method='LDL')                         |     37.10    38465  |     37.40    42563  |     60.00    87537  |     58.20    87537
M.inv(method='LDL', dotprodsimp=True)       |    125.00       40  |    157.00       56  |     73.90       46  |    114.00     2062
simplify(M.inv(method='LDL'))               |             failed  |             failed  |             failed  |             failed
                                            |                     |                     |                     |
M.cofactor(0, 0)                            |      1.10      413  |      1.06     2074  |      1.10     4652  |      1.11     4757
M.cofactor(0, 0, dotprodsimp=True)          |      6.54        0  |     20.60        0  |      3.20        0  |    921.00      355
simplify(M.cofactor(0, 0))                  |    240.00        0  |   1470.00        0  |   2820.00        0  |   2720.00      355
                                            |                     |                     |                     |
M.cofactor_matrix()                         |    287.00    24084  |   1110.00    74583  |   3620.00   159358  |   1500.00   162420
M.cofactor_matrix(dotprodsimp=True)         |    475.00        0  |   5360.00        0  |   3130.00        0  |              11639
simplify(M.cofactor_matrix())               |  14700.00        0  |             failed  |             failed  |             failed
                                            |                     |                     |                     |
M.echelon_form()                            |     63.50       21  |    293.00       30  |   3360.00      554  |             failed
M.echelon_form(dotprodsimp=True)            |     46.90        9  |     26.90       10  |      2.71       75  |             failed
simplify(M.echelon_form())                  |     92.70        9  |    316.00       10  |   3870.00       75  |             failed
                                            |                     |                     |                     |
M.nullspace()                               |     62.50        4  |    295.00       88  |   3470.00     2416  |             failed
M.nullspace(dotprodsimp=True)               |     46.40        4  |     26.60        4  |      4.66       35  |             failed
[simplify(e) for e in M.nullspace()]        |     62.40        4  |    365.00        4  |   6500.00       35  |             failed
                                            |                     |                     |                     |
M.rowspace()                                |     63.90       21  |    287.00       30  |   3200.00      554  |             failed
M.rowspace(dotprodsimp=True)                |     47.00        9  |     26.70       10  |      2.72       75  |             failed
[simplify(e) for e in M.rowspace()]         |     91.00        9  |    313.00       10  |   3870.00       75  |             failed
                                            |                     |                     |                     |
M.columnspace()                             |     64.20       12  |    299.00       11  |   3310.00       87  |             failed
M.columnspace(dotprodsimp=True)             |     48.70       12  |     26.70       11  |      2.83       87  |             failed
[simplify(e) for e in M.columnspace()]      |     97.20       12  |    325.00       11  |   3530.00       87  |             failed
                                            |                     |                     |                     |
M.singular_values()                         |   1550.00     2001  |   1670.00    37176  |   3110.00       30  |  15900.00      289
M.singular_values(dotprodsimp=True)         |    516.00     2001  |    564.00    37176  |      6.18       30  |  13900.00      289
[simplify(e) for e in M.singular_values()]  |   8450.95     1928  |             failed  |   4340.00       28  |             failed
                                            |                     |                     |                     |
M.rank()                                    |     62.60        0  |    288.00        0  |   3260.00        0  |             failed
M.rank(dotprodsimp=True)                    |     46.20        0  |     27.50        0  |      3.31        0  |             failed
                                            |                     |                     |                     |
M.is_nilpotent()                            |   1620.00        0  |  22800.00        0  |  54611.97        0  |  47003.65        0
M.is_nilpotent(dotprodsimp=True)            |     26.30        0  |     92.00        0  |      6.67        0  |   2620.00        0
                                            |                     |                     |                     |
M._eval_is_pos_def()                        |    757.00        0  |   1050.00        0  |    678.00        0  |   2330.00        0
M._eval_is_pos_def(dotprodsimp=True)        |    393.00        0  |    478.00        0  |     67.30        0  |   1920.00        0
```
And now the so-so cases:
```
6x6 or 4x4 matrix (time in ms.)             |         A      ops  |         B      ops  |         C      ops  |         D      ops
                                            |                     |                     |                     |
M.eigenvects()                              |     22.20      691  |      1.85      132  |     22.00       15  |    170.00       70
M.eigenvects(dotprodsimp=True)              |     22.40      313  |      7.51      156  |      1.48       15  |    323.00       54
simplify M.eigenvects()                     |     22.10      297  |     39.00       92  |     32.70        7  |    395.00       30
                                            |                     |                     |                     |
M.left_eigenvects()                         |     63.00      352  |    147.00      140  |     24.50       14  |    720.00      233
M.left_eigenvects(dotprodsimp=True)         |     61.20      199  |    148.00      147  |      2.83       14  |    799.00       42
[simplify(e) for e in M.left_eigenvects()]  |     62.70      352  |    147.00      140  |     25.00       14  |    723.00      233
                                            |                     |                     |                     |
M.inv(method='GE')                          |     21.10       85  |     16.30       77  |      0.85      444  |     11.40      520
M.inv(method='GE', dotprodsimp=True)        |     28.70       40  |     41.00       56  |      2.19       46  |     68.70      192
simplify(M.inv(method='GE'))                |     89.80       39  |    106.00       49  |     91.70       46  |    210.00      149
                                            |                     |                     |                     |
M.inv(method='LU')                          |     21.60       98  |     16.80      106  |      1.38      451  |     11.90      370
M.inv(method='LU', dotprodsimp=True)        |     48.70       43  |     51.20       56  |      3.28       46  |     59.40      177
simplify(M.inv(method='LU'))                |     88.80       39  |    112.00       53  |     80.60       46  |    212.00      149
                                            |                     |                     |                     |
M.inv(method='ADJ')                         |     12.40      444  |     11.00      582  |     15.70     1077  |     24.20     1225
M.inv(method='ADJ', dotprodsimp=True)       |     21.00      133  |     28.60      146  |     18.30      122  |     42.70      748
simplify(M.inv(method='ADJ'))               |     85.10       39  |    104.00       53  |    161.00       46  |    261.00      178
                                            |                     |                     |                     |
M.diagonalize()                             |    401.33        7  |     48.50      116  |             failed  |   4975.46      226
M.diagonalize(dotprodsimp=True)             |    191.08        7  |     46.30      156  |             failed  |   4256.46      384
[simplify(e) for e in M.diagonalize()]      |    260.15        7  |     84.50      116  |             failed  |   5457.84      225
                                            |                     |                     |                     |
M.jordan_form()                             |     72.30      950  |      2.24      132  |     62.40       24  |    778.00       73
M.jordan_form(dotprodsimp=True)             |     72.90      349  |      7.94      156  |      6.98       24  |    907.00       57
[simplify(e) for e in M.jordan_form()]      |    104.00      319  |     46.10      116  |    352.00       24  |   1050.00       50
                                            |                     |                     |                     |
M.is_diagonalizable()                       |     24.60        0  |     47.40        0  |     37.60        0  |    417.00        0
M.is_diagonalizable(dotprodsimp=True)       |     24.80        0  |     45.40        0  |     11.20        0  |    570.00        0
```

**Comment by oscarbenjamin** [comment]
Does this actually fix #16823? It looks that example is fixed when using `dotprodsimp=True` but not when calling simply `T.rank()`.

**Comment by Pristine-Cat** [comment]
Yes it only fixes if `dotprodsimp` is used, otherwise I don't know where the error is coming from, some operation fails on a very large expression, would be very difficult to track down.

**Comment by oscarbenjamin** [comment]
I don't think that this should close #16823 then so can you edit the OP?

**Comment by Pristine-Cat** [comment]
Done, I think this is about ready, am I missing anything?

**Comment by oscarbenjamin** [comment]
The code looks good.

In some docstrings you've added a  parameters section to describe the `dotprodsimp` parameter but not any of the other parameters. It would be better to document all parameters.

@sylee957 does this look good to you?

**Pull request merged**
