### PR TITLE
Enable support for not automatically rewriting functions

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Related to #23417

#### Brief description of what is fixed or changed
Added a setting value `functions_not_to_rewrite` which is meant to be an iterable with names of functions that should not be automatically rewritten.

The problem now is to set that value with something sensible in the autowrap code (it is probably easy to set quite early in the code, but then must propagate pretty long until it is actually used, but then I do not really understand this part of the code that well...)

#### Other comments

Heaviside is rewritten to a Piecewise with a `True` final condition. This is the standard way of doing it and not doing it will break the code generation anyway.

Will hopefully continue to work on fixing the original issue, but not in the near future as it seems.

#### Release Notes

* printing
   * `Heaviside` is better supported in code generation.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This seems somewhat incomplete. Should it be merged as is or left for future completion?

**Comment by oscargus** [comment]
You are right that the modification in codeprinter is not really finished (or rather it is not documented and using it requires knowing that it exists and a bit of hacking...).

The other changes actually removes the need for a specific `Heaviside` rewrite (as autowrap has a requirement that the last conditional in a Piecewise must be True). So that in itself is probably worthwhile to get in. Not sure how much of a problem adding the undocumented code is at this stage.

**Comment by oscargus** [comment]
Darn, messed up the rebase... Will reopen later on with only the Piecewise changes.

**Comment by oscarbenjamin** [comment]
> Not sure how much of a problem adding the undocumented code is at this stage.

It's always a problem to have things that are not properly tested or documented (e.g. the helpers argument to autowrap https://github.com/sympy/sympy/issues/23417). If no one can figure out what the code is supposed to do and downstream code is using it then most likely it will be broken or it will become broken and will be impossible to fix.

**Pull request closed without merging**
