### PR TITLE
Combinatorics: Added naive algorithm for computing conjugacy classes in permutation groups

### PR DESCRIPTION
**Pull request by sachin-4099**
Reference: https://github.com/sympy/sympy/pull/9160

#### Brief description of what is fixed or changed
This pull request adds `conjugacy_class` and `conjugacy_classes` methods to the `PermutationGroup class`, which compute respectively the set of all elements conjugate to an element of a group, and the list of all these equivalence classes.

#### Other comments
Regression tests are also added

#### Release Notes

* combinatorics
  * Added `Permutation.conjugacy_class` and `Permutation.conjugacy_classes` for computing conjugacy classes in permutation groups.

### CODE REVIEW

**Comment by sachin-4099** [comment]
Are the docstrings ok, @sylee957 ?

**Comment by sachin-4099** [comment]
Actually the test which is failing is getting skipped in local.

**Comment by divyanshu132** [comment]
There is another version of the same algorithm mentioned in the referenced pr.Which is claimed to be faster than this one, can you try with that? may be you can test on larger groups and see the difference between the execution time.

**Comment by mohitacecode** [comment]
Hey can anyone tell me why this test is failing? 
Ps: I know the reason but why is that happening?
`py3.7.egg/sympy/core/expr.py", line 298, in __int__
    raise TypeError("can't convert complex to int")
TypeError: can't convert complex to in`

**Comment by oscarbenjamin** [comment]
See #18090. I've restarted the test.

**Comment by sachin-4099** [comment]
> See #18090. I've restarted the test.

Ohk that was the issue.

**Comment by sachin-4099** [comment]
> There is another version of the same algorithm mentioned in the referenced pr.Which is claimed to be faster than this one, can you try with that? may be you can test on larger groups and see the difference between the execution time.

@oscarbenjamin @divyanshu132, shall I take this in another PR or continue with this? Because I also noticed the same thing, but was thinking that we can first add the feature and than proceed to optimize it.

**Comment by sylee957** [comment]
What I read from @pernici's suggestion is that, it's about expanding the array-form computation inside the code.
I don't like such optimizations by code expansions. If you are willing to work on to achieve the same thing, but in more cleaner code, then I may agree on merging this.

**Comment by sachin-4099** [comment]
> What I read from @pernici's suggestion is that, it's about expanding the array-form computation inside the code.
> I don't like such optimizations by code expansions. If you are willing to work on to achieve the same thing, but in more cleaner code, then I may agree on merging this.

Fine I will work on this.

**Comment by sachin-4099** [comment]
@sylee957 @oscarbenjamin, I think this can be merged now.

**Pull request merged**
