### PR TITLE
let refine to simplify arg(x) when x in real

### LINKED ISSUE #21054: `refine()` does not understand how to simplify complex arguments
Just learned about the refine-function, which would come in handy frequently for me.  But
`refine()` does not recognize that argument functions simplify for real numbers.

```
>>> from sympy import *                                                     
>>> var('a,x')                                                              
>>> J = Integral(sin(x)*exp(-a*x),(x,0,oo))                                     
>>> J.doit()
	Piecewise((1/(a**2 + 1), 2*Abs(arg(a)) < pi), (Integral(exp(-a*x)*sin(x), (x, 0, oo)), True))
>>> refine(J.doit(),Q.positive(a))                                                 
        Piecewise((1/(a**2 + 1), 2*Abs(arg(a)) < pi), (Integral(exp(-a*x)*sin(x), (x, 0, oo)), True))
>>> refine(abs(a),Q.positive(a))                                            
	a
>>> refine(arg(a),Q.positive(a))                                            
	arg(a)
```
I cann't find any open issues identifying this.  Easy to fix, though.

### PR DESCRIPTION
**Pull request by zanzibar7**
#### References to other Issues or PRs

Fixes #21054

#### Brief description of what is fixed or changed

refine() is extended to recognize that arg(x) simplifies
if x is known to be either positive or negative.

#### Release Notes

* assumptions
  * refine arg(x) when x is real and nonzero

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This looks reasonable to me. @JSS95 does this look okay?

More generally the problem we have with `refine` is that the way it is currently implemented requires all of the evaluation logic that already exists in e.g. `arg.__new__` to be duplicated in `refine`. There needs to be a way of unifying these to avoid this duplication.

**Comment by JSS95** [comment]
This looks good. @zanzibar7, can you please add this example to the docstring of `arg`?

> More generally the problem we have with refine is that the way it is currently implemented requires all of the evaluation logic that already exists in e.g. arg.__new__ to be duplicated in refine. There needs to be a way of unifying these to avoid this duplication.

I agree. AFAIK `__new__()` method uses old assumption system while `refine()` uses new assumption system. Maybe we can pass a getter function to `eval()` so that it uses `x.is_positive` in `__new__()` and `ask(Q.positive(x), assumptions)` in `refine()`? It needs to be discussed.

**Comment by oscarbenjamin** [comment]
@zanzibar7 this looks good but @JSS95 suggested to ask this to the docstring of `arg`. Can you do that?

**Comment by JSS95** [comment]
Modifying the docstring of `arg` is an optional suggestion and I approve what @zanzibar7 has done so far, so I'm merging this. Thank you, @zanzibar7 !

**Pull request merged**
