### PR TITLE
Improved pattern-based logic simplification

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Pulled the logic simplification part from #17330.

#### Brief description of what is fixed or changed

Better pattern-based simplification. Fewer patterns and combinations tested. Three-term patterns (only for `And` so far).

#### Other comments

Some minor code improvements in the first commit.

#### Release Notes

* logic
    * Improved simplification of Boolean expressions with relations.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I think this looks good. I'm not entirely sure what effect the changes have.

**Comment by oscargus** [comment]
There are four(?) things:

1. Refactoring to a function instead of a method.
2. Better checking of relationals, earlier the code tried all possible combinations of reversing the relationals to make them match, now only the Eq/Ne-relationals are reversed, the others are canonicalized to Le/Lt (unfortunately, I selected Ge/Gt for three-terms, but will fix that later). This also lead to that fewer patterns must be tested (left them commented for now, both in case I was wrong and for other to see that they were considered).
3. Introduced three-term pattern, such that `And(a > b, b > c, c > a)` can be simplified to `False`.
4. Patterns are stored (and matched) as Tuple rather than the Boolean function which makes things a bit better/quicker as there is no evaluation etc.

**Comment by oscargus** [comment]
This is probably an enabler for #17087 as well.

**Comment by oscarbenjamin** [comment]
Okay well it looks good to me although it sounds like you still intend to make more changes.

**Comment by oscargus** [comment]
There are things that can be changed/improved/extended, but hard to say when... I expect to continue working on the simplification, but it is also good to get things in reasonably small batches and based on experience I may not always do linear development, rather jump back and forth to do something that seems intriguing at the moment (based on the amount of time that I believe I have).

**Comment by oscarbenjamin** [comment]
Okay so what does this mean:

> unfortunately, I selected Ge/Gt for three-terms, but will fix that later

Is that a bug or just something that is potentially less efficient or leads to less simple code or something?

**Comment by oscargus** [comment]
The three-term normalizes all inequalities to Gt/Ge. The result is then sent to the two-term where they are normalized to Lt/Le. So inefficient, although the effect is probably minimal (considering that the matching takes much, much longer time), more a bit annoying and "stupid".

**Comment by oscarbenjamin** [comment]
> the matching takes much, much longer time

Is this the kind of thing that matchpy could help with?

https://github.com/HPAC/matchpy#many-to-one-matching

**Comment by oscarbenjamin** [comment]
Okay well looks good for now.

**Pull request merged**
