### PR TITLE
New printing conventions

### LINKED ISSUE #12213: Python code printer
The current Python printer prints expressions in a SymPy-style.

It could be useful to have a printer that prints non-SymPy Python code, for example:

- `Mod(x, 2)` as `x % 2`
- `And(x, y)` as `x and y` instead of SymPy's operator overloaded `x & y`.

Currently:

- `str( )` is supposed to return a valid Python code that is (with some exceptions/caveats) able to reconstruct the SymPy object.
- `lambdify( )` returns a lambda objects for optimized operations.

### PR DESCRIPTION
**Pull request by mohit3011**
Fixes #12213

### CODE REVIEW

**Comment by mohit3011** [comment]
@Upabjojr , I have tried to look for the printing of logical & , but I am not sure it it is correct . Please check , thanks

**Comment by mohit3011** [comment]
Tests are failing but I will change those

**Comment by Upabjojr** [comment]
What are you doing?

**Comment by mohit3011** [comment]
I was looking for the code which was responsible for the printing of logical and operation. Therefore , I changed the part in code printer.py , but I am not sure whether this is correct or not.

**Comment by Upabjojr** [comment]
We don't need this.

**Comment by mohit3011** [comment]
@Upabjojr  , is there something wrong ?

**Comment by Upabjojr** [comment]
This PR destroys all printers. I think you've misunderstood the point of #12213

**Pull request closed without merging**
