### PR TITLE
Make _rewrite_gamma() raise IntegralTransformError (fixes #8882)

### LINKED ISSUE #8882: ValueError: a is not an integer with integral
From http://stackoverflow.com/q/28110908/161801

```
In [27]: print(Psi_H_Psi)
4*pi*r*(-0.5*(a0**2*sin(r) - 2*a0*cos(r) + 2*a0*sin(r)/r - sin(r) - 2*cos(r)/r + 2*sin(r)/r**2)*exp(-a0*r)/r - exp(-a0*r)*sin(r)/r**2)*exp(-a0*r)*sin(r)

In [28]: integrate(Psi_H_Psi,(r,-oo,3))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-2097d3c372ad> in <module>()
----> 1 integrate(Psi_H_Psi,(r,-oo,3))

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/utilities/decorator.py in threaded_func(expr, *args, **kwargs)
     33                                       func(expr.rhs, *args, **kwargs))
     34             else:
---> 35                 return func(expr, *args, **kwargs)
     36
     37     return threaded_func

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/integrals.py in integrate(*args, **kwargs)
   1228     if isinstance(integral, Integral):
   1229         return integral.doit(deep=False, meijerg=meijerg, conds=conds,
-> 1230                              risch=risch, manual=manual)
   1231     else:
   1232         return integral

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/integrals.py in doit(self, **hints)
    463                 and not function.is_Poly and \
    464                     (xab[1].has(oo, -oo) or xab[2].has(oo, -oo)):
--> 465                 ret = try_meijerg(function, xab)
    466                 if ret is not None:
    467                     function = ret

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/integrals.py in try_meijerg(function, xab)
    440                     x, a, b = xab
    441                     try:
--> 442                         res = meijerint_definite(function, x, a, b)
    443                     except NotImplementedError:
    444                         from sympy.integrals.meijerint import _debug

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in meijerint_definite(f, x, a, b)
   1730
   1731     if a == -oo and b != oo:
-> 1732         return meijerint_definite(f.subs(x, -x), x, -b, -a)
   1733
   1734     if a == -oo:

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in meijerint_definite(f, x, a, b)
   1794     _debug('Changed limits to', a, b)
   1795     _debug('Changed function to', f)
-> 1796     res = _meijerint_definite_2(f, x)
   1797     if res is not None:
   1798         if res[0].has(meijerg):

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in _meijerint_definite_2(f, x)
   1851     for g, explanation in _guess_expansion(f, x):
   1852         _debug('Trying', explanation)
-> 1853         res = _meijerint_definite_3(g, x)
   1854         if res is not None and res[1] != False:
   1855             return res

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in _meijerint_definite_3(f, x)
   1868     if f.is_Add:
   1869         _debug('Expanding and evaluating all terms.')
-> 1870         ress = [_meijerint_definite_4(g, x) for g in f.args]
   1871         if all(r is not None for r in ress):
   1872             conds = []

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in <listcomp>(.0)
   1868     if f.is_Add:
   1869         _debug('Expanding and evaluating all terms.')
-> 1870         ress = [_meijerint_definite_4(g, x) for g in f.args]
   1871         if all(r is not None for r in ress):
   1872             conds = []

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in _meijerint_definite_4(f, x, only_double)
   1919
   1920     # Try two G functions.
-> 1921     gs = _rewrite2(f, x)
   1922     if gs is not None:
   1923         for full_pb in [False, True]:

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in _rewrite2(f, x)
   1571     for recursive in [False, True]:
   1572         for fac1, fac2 in l:
-> 1573             g1 = _rewrite_single(fac1, x, recursive)
   1574             g2 = _rewrite_single(fac2, x, recursive)
   1575             if g1 and g2:

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in _rewrite_single(f, x, recursive)
   1499     try:
   1500         F, strip, _ = mellin_transform(f, x, s, integrator=my_integrator,
-> 1501                                        simplify=False, needeval=True)
   1502         g = my_imt(F, s, x, strip)
   1503     except IntegralTransformError:

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/transforms.py in mellin_transform(f, x, s, **hints)
    351     hankel_transform, inverse_hankel_transform
    352     """
--> 353     return MellinTransform(f, x, s).doit(**hints)
    354
    355

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/transforms.py in doit(self, **hints)
    116             try:
    117                 return self._compute_transform(self.function,
--> 118                     self.function_variable, self.transform_variable, **hints)
    119             except IntegralTransformError:
    120                 pass

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/transforms.py in _compute_transform(self, f, x, s, **hints)
    293
    294     def _compute_transform(self, f, x, s, **hints):
--> 295         return _mellin_transform(f, x, s, **hints)
    296
    297     def _as_integral(self, f, x, s):

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/transforms.py in wrapper(*args, **kwargs)
    194         def wrapper(*args, **kwargs):
    195             noconds = kwargs.pop('noconds', default)
--> 196             res = func(*args, **kwargs)
    197             if noconds:
    198                 return res[0]

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/transforms.py in _mellin_transform(f, x, s_, integrator, simplify)
    218     # convergence of the integral.
    219     s = _dummy('s', 'mellin-transform', f)
--> 220     F = integrator(x**(s - 1) * f, x)
    221
    222     if not F.has(Integral):

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in my_integrator(f, x)
   1490     def my_integrator(f, x):
   1491         from sympy import Integral, hyperexpand
-> 1492         r = _meijerint_definite_4(f, x, only_double=True)
   1493         if r is not None:
   1494             res, cond = r

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in _meijerint_definite_4(f, x, only_double)
   1919
   1920     # Try two G functions.
-> 1921     gs = _rewrite2(f, x)
   1922     if gs is not None:
   1923         for full_pb in [False, True]:

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in _rewrite2(f, x)
   1571     for recursive in [False, True]:
   1572         for fac1, fac2 in l:
-> 1573             g1 = _rewrite_single(fac1, x, recursive)
   1574             g2 = _rewrite_single(fac2, x, recursive)
   1575             if g1 and g2:

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in _rewrite_single(f, x, recursive)
   1500         F, strip, _ = mellin_transform(f, x, s, integrator=my_integrator,
   1501                                        simplify=False, needeval=True)
-> 1502         g = my_imt(F, s, x, strip)
   1503     except IntegralTransformError:
   1504         g = None

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/meijerint.py in my_imt(F, s, x, strip)
   1479         try:
   1480             return inverse_mellin_transform(F, s, x, strip,
-> 1481                                             as_meijerg=True, needeval=True)
   1482         except MellinTransformStripError:
   1483             return inverse_mellin_transform(

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/transforms.py in inverse_mellin_transform(F, s, x, strip, **hints)
    860     hankel_transform, inverse_hankel_transform
    861     """
--> 862     return InverseMellinTransform(F, s, x, strip[0], strip[1]).doit(**hints)
    863
    864

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/transforms.py in doit(self, **hints)
    116             try:
    117                 return self._compute_transform(self.function,
--> 118                     self.function_variable, self.transform_variable, **hints)
    119             except IntegralTransformError:
    120                 pass

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/transforms.py in _compute_transform(self, F, s, x, **hints)
    804                                      'Component %s not recognised.' % f)
    805         strip = self.fundamental_strip
--> 806         return _inverse_mellin_transform(F, s, x, strip, **hints)
    807
    808     def _as_integral(self, F, s, x):

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/transforms.py in wrapper(*args, **kwargs)
    194         def wrapper(*args, **kwargs):
    195             noconds = kwargs.pop('noconds', default)
--> 196             res = func(*args, **kwargs)
    197             if noconds:
    198                 return res[0]

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/transforms.py in _inverse_mellin_transform(F, s, x_, strip, as_meijerg)
    723
    724         try:
--> 725             a, b, C, e, fac = _rewrite_gamma(g, s, strip[0], strip[1])
    726         except IntegralTransformError:
    727             continue

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/transforms.py in _rewrite_gamma(f, s, a, b)
    669                 newc = c/p
    670                 if not a.is_Integer:
--> 671                     raise TypeError("a is not an integer")
    672                 for k in range(p):
    673                     gammas += [(newa, newc + k/p)]

TypeError: a is not an integer
```

### PR DESCRIPTION
**Pull request by jksuom**
inverse_mellin_transform() applies _rewrite_gamma() to check whether
the transform can be expressed in terms of Meijer G-functions.
A failure is indicated by raising IntegralTransformError.

For the rewrite it is necessary that the arguments of trigonometric
and gamma functions are of the form `a*pi*s + b` or `a*s + b`,
respectively, where all the multipliers `a` are rational multiples of
a single real number (which can be absorbed into `s`).

The code is modified in phase 1) to test this for all multipliers
instead of only manifestly real ones.

### CODE REVIEW

**Comment by smichr** [comment]
Just some minor suggestions via [PR](https://github.com/jksuom/sympy/pull/1). Otherwise +1.

**Comment by jksuom** [comment]
Should I try to move the imports? (And how?)

**Comment by smichr** [comment]
You can just merge the PR that I sent you.

**Comment by jksuom** [comment]
Thanks, I still have a lot to learn about using git.

**Comment by smichr** [comment]
I don't use but a small subset. And the sympy folks helped a lot.

**Comment by smichr** [comment]
Tests run on my account look good. Thanks, this is in.

**Pull request merged**
