### PR TITLE
Updated Readme.md with Contents.

### PR DESCRIPTION
**Pull request by bhav09**
Updating readme.md for better readability. 

#### References to other Issues or PRs

Related issue: https://github.com/sympy/sympy/issues/21072

#### Brief description of what is fixed or changed

Added a contents section to the readme file. to make it look more presentable and navigatable. 

NO ENTRY

#### Other comments 

Contributors are stealing and claiming PRs on my Issues. Please do have a look at it. 

@asmeurer @oscarbenjamin  please have a look at it and guide me if any changes are needed. Thanks :)

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
There are things that could be improved about the README but I'm not sure the changes here really improve anything.

Closing and reopening to restart the tests. You need to put NO ENTRY for the release notes.

**Comment by oscarbenjamin** [comment]
> Contributors are stealing and claiming PRs on my Issues.

You do not own issues. If you open an issue then any contributor can feel free to open a PR that fixes the issue. Usually that is the purpose of opening an issue: so that someone else will fix it.

**Comment by oscarbenjamin** [comment]
I'm not sure this is needed.

Does anyone think that the README should have a table of contents with links?

**Comment by oscarbenjamin** [comment]
This isn't needed

**Comment by asmeurer** [comment]
Little cleanups like this are fine, but honestly, I think the whole README needs to be completely rewritten. It has way too much stuff that's outdated, and things that aren't that important to its intended audience.

**Comment by bhav09** [comment]
@asmeurer @oscarbenjamin please do tell me how can I help you in rewriting the readme for Sympy. I would love to help. Thanks :)

**Pull request closed without merging**
