### PR TITLE
Added testing for div. by 2

### PR DESCRIPTION
**Pull request by mikaylazgrace**
Added handling under "def test_Pow_is_even_odd():" to handle the exception raised in issue #8648 regarding a number raised to an integer divided by 2.

**Edit**: I learned that I actually only added testing for division by 2 in this problem.  I am working in [here](https://github.com/sympy/sympy/blob/master/sympy/core/mul.py) to try to continue work done that is mentioned in the comments below by @smichr

### CODE REVIEW

**Comment by smichr** [comment]
On the issue page you can see how @debugger22 worked at fixing the issue. Notice that he made modifications in the `Mul` routine. What you have done is added tests which you think should pass once the logic is correct in the `Mul` routine. Although he could have added something specific like

```
a, b = expr.as_two_terms()
if a == S.Half and b.is_Pow and b.exponent.is_even and b.base.is_even:
    return True
```

he tried to be more general. 

[I haven't checked his logic nor your tests; these are just general observations and suggestions.]

**Comment by mikaylazgrace** [comment]
Could you link the work and/or show me the code? I'm very new to GitHub and am still learning how to navigate. Thanks!

Also, in the sample code you posted, are you dividing the base by 2 and then raising it to the power? Because this would potentially create an odd base raised to a power which would always be odd. Order of operations in the issue #8648 would dictate that the even base be raised to the power and then divided by 2 which would always be even as long as the exponent is an integer >1.

**Comment by asmeurer** [comment]
In the future, you should create a separate branch to commit to from master. In general, you should never commit to master, unless you are working in your own private repo.

**Comment by mikaylazgrace** [comment]
I forked the repository and the commits have been under mikaylazgrace/sympy which I believe is my private one. Is that not the case? Have I been committing somewhere else?

I'm new to GitHub, and I'm trying to learn as much as I go, so thank you for the feedback.

**Comment by mikaylazgrace** [comment]
Here is where I believe I've been trying to edit things: https://github.com/mikaylazgrace/sympy

**Comment by asmeurer** [comment]
Private meaning like if you make your own git repo for something. For forks you generally want to avoid committing to master so that you can use it to pull in changes from the upstream master (from https://github.com/sympy/sympy/). Also separate branches will make it possible to do more than one pull request at a time.

**Comment by mikaylazgrace** [comment]
Okay, I think I understand what you're saying. So should I copy my forked version of SymPy into a new repo where I make changes? Or should I simply branch within my forked copy?

Again, thank you for the help and tips! I'm working hard on trying to patch in something useful for GSoC.

**Comment by asmeurer** [comment]
Use your forked repo. This is the workflow I recommend: https://github.com/asmeurer/git-workflow.

We also have more in-depth guides for SymPy: https://github.com/sympy/sympy/wiki/Introduction-to-contributing https://github.com/sympy/sympy/wiki/Development-workflow

**Comment by mikaylazgrace** [comment]
Thanks so much! I'll read and use those, and I'm going to spend some more time figuring out how to implement my patch idea, and then I'll be back, hopefully with a nice PR! I appreciate your time and the resources you've provided.

**Comment by czgdp1807** [comment]
@mikaylazgrace Please provide updates on this PR.

**Pull request closed without merging**
