### PR TITLE
Add Sumith Kulal to AUTHORS/aboutus.rst

### PR DESCRIPTION
**Pull request by hargup**

### CODE REVIEW

**Comment by hargup** [comment]
@Sumith1896

**Comment by Sumith1896** [comment]
Could you add as Sumith because thats what in official docs .

**Comment by Sumith1896** [comment]
Check the comments [below]{https://github.com/sympy/csympy/pull/385)

**Comment by Sumith1896** [comment]
@hargup ping

**Comment by hargup** [comment]
@Sumith1896 changed the PR according to your request.

**Comment by Sumith1896** [comment]
+1. Thanks @hargup.

**Pull request merged**
