### PR TITLE
_eval_refine takes the argument assumptions

### PR DESCRIPTION
**Pull request by asmeurer**
Also changes all implementations of _eval_refine to use ask() and those
assumptions instead of the old assumptions.

**DON'T MERGE**. This currently has some performance issues.

### CODE REVIEW

**Comment by smichr** [comment]
it looks fine to me (performance aside)

**Comment by debugger22** [comment]
I remember that performance was the reason i switched back to use old assumptions there.

**Comment by asmeurer** [comment]
@debugger22 any thoughts on what to do about it? The `sqrt(x**2)` thing mentioned by Ondrej is a regression that needs to be fixed.

**Comment by asmeurer** [comment]
Some possible options:

1. Add a flag to `ask` to allow it to disable `satask` (probably should do this anyway) and manually disable it in some of the `_eval_refine` uses of `ask`. 

2. Add the flag and add `**kwargs` to `_eval_refine` that lets you pass the flag through (and disable it in the slow tests).

3. Mark the slowest tests as @slow.

4. Leave things as they are, and have `refine(sqrt(x**2), Q.positive(x)) == x` be a regression (this is a last resort option. I'd rather not do this).

5. Revert the changes that caused the regression (I'm not sure if it was the `Pow._eval_refine` or the `Abs._eval_refine` thing that caused it).

https://github.com/sympy/sympy/issues/10148 is still an issue to. We really need to revert the refine tests back to using the new assumptions, but the problem is that `Abs._eval_refine` checks for `nonpositive`, which, from that issue, doesn't work in all cases. I suppose the options for working around that are:

1. Checking the case that does work in `Abs._eval_refine` (I think `real and not negative` instead of `nonpositive`).

2. Reverting the `Abs._eval_refine` changes.

3. XFAILing the test in question.

4. Adding whatever the relevant fact would be to `sathandlers` (this is probably the ideal solution, but I'm not sure what the correct fact is at the moment). 

Any suggestions other than what I have thought of here? What do you think is the best way forward? This needs to be fixed ASAP because it is blocking the release and I want to get the release branch made (i.e., all major blockers fixed, including this one) out in the next week or two.

**Comment by asmeurer** [comment]
My preferences are for option 5 in the first point and option 4 in the second.

**Comment by asmeurer** [comment]
So I actually think we should still do this, but also the revert of the abs stuff (which is the bulk of what's here) at https://github.com/sympy/sympy/pull/10600.

**Comment by asmeurer** [comment]
This is merged into master (with https://github.com/sympy/sympy/pull/10600). Without the `_eval_refine` on `Abs` this PR is much simpler, and hopefully shouldn't have performance issues (although it's still possible the `Pow._eval_refine` causes issues).

**Pull request merged**
