### PR TITLE
Solving issue #10926

### PR DESCRIPTION
**Pull request by Upabjojr**

### CODE REVIEW

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/issues/10926

**Comment by Upabjojr** [comment]
@moorepants the _dynamicssymbols_ are causing a lot of problems to the pretty printer.

**Comment by moorepants** [comment]
What exactly is the issue?

The function `dynamicsymbols` simply does something like:

```python
t = symbols('t')
q = Function('q')
q(t)
```

All it does it make a function of a time variable.

**Comment by Upabjojr** [comment]
I wanted to transfer the parenthesization criteria for the LaTeX printer to the precedence module. I'm meeting some difficulties with dynamicssymbols.

**Comment by moorepants** [comment]
Are you referring to the sympy.physics.vector printers?

We have custom printers that support dot notation. If you are getting errors there, we can try to debug them. Maybe post the errors you are getting?

**Comment by Upabjojr** [comment]
Yes, I saw them. I have just overwritten the method _parenthesize_ in _VectorLatexPrinter_.

@moorepants what do you think?

**Comment by Upabjojr** [comment]
@gxyd what do you think? I think this solves it.

@moorepants are the edits to _sympy.physics.vector_ printers OK?

**Comment by moorepants** [comment]
I'm fine if tests pass and functionality didn't change. I'm not sure how good our tests are though...

**Comment by gxyd** [comment]
@Upabjojr i am afraid i will not be able to see this PR (my exams are 
ongoing, will be busy till 1st May). Please do as you see right.

**Comment by Upabjojr** [comment]
OK merging.

**Pull request merged**
