### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by asmeurer** [comment]
Side question: why are the doctests in this function skipped?

**Comment by smichr** [comment]
> why are the doctests in this function skipped?

Not sure. See also https://groups.google.com/forum/#!topic/sympy/nVCzquSZ9EU

+1 regarding the change, however.

**Comment by asmeurer** [comment]
That delta thing must be a bug in the doctest runner (they aren't running for me either). The doctests in this function are explicitly skipped with `doctest: +SKIP`.

**Comment by jksuom** [comment]
It seems that caching prevents ``_extract_delta`` from running. [This line](https://github.com/sympy/sympy/blob/master/sympy/utilities/runtests.py#L1462) gets the following argument
```
(Pdb) p rawname, val
('_extract_delta', <fastcache.clru_cache object at 0x45711c8>)
```
but the fastcache ``val`` does not satisfy the test.

**Comment by asmeurer** [comment]
A bug in fastcache then? @pbrady

**Comment by pbrady** [comment]
Could be but if I remember correctly this also happens without fastcache.  I can't test this right now though

**Comment by pbrady** [comment]
Found it:  #7873

**Comment by smichr** [comment]
> function are explicitly skipped

Now that I look at it I believe they are skipped because they show an output (the contents of a dictionary) whose order might vary depending on how the keys are traversed.

**Comment by asmeurer** [comment]
I see what you mean. We could use `sorted`, but that would be an antipattern for actual use-cases.

**Pull request merged**
