### PR TITLE
Fixed TypeError in SVD

### PR DESCRIPTION
**Pull request by alexthed1rk**
#### References to other Issues or PRs

PR related to [#25162](https://github.com/sympy/sympy/issues/25162)

#### Brief description of what is fixed or changed
Replaced indirect computation of diagonal matrix on singular values
using `zeros` class method by direct `diag` one, so it avoids TypeError exception.

#### Release Notes

* matrices
    * decompositions: fixed svd.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Thanks @DarkNisa. Out of interest why did you close and reopen the PR? 

Was there an intermittent test failure or was it prompted by the benchmarks comment or something else?

**Comment by sylee957** [comment]
I enabled the auto merge, but it got merged with the failing pyodide test though

**Comment by DarkNisa** [comment]
@oscarbenjamin
So I'm a little bit a perfectionist, so I like when the all test are finished successfully.
And the problem here is that I can't reload test (maybe I dont know the correct way) 
that haven't passed because of some internal connection error or like here
because of `The operation was canceled` for `test-pyodide (3)`. So that's why
I close and reopen it so the tests may be reloaded.

**Comment by DarkNisa** [comment]
Benchmarks doesn't scary me, because they seem to be logical,
because I replaced slow python's for loop + zeros matrix construction
by internal method, that I hope constructs diagonal matrix faster by given values.

**Comment by oscarbenjamin** [comment]
> `The operation was canceled` for `test-pyodide (3)`

This error shows up intermittently on multiple PRs. I don't know what causes it but it is definitely not related to the changes here.

> Benchmarks doesn't scary me, because they seem to be logical,
> because I replaced slow python's for loop + zeros matrix construction
> by internal method, that I hope constructs diagonal matrix faster by given values.

This PR has no observable effects on the timings reported by the benchmarks. The changes show are all "master vs previous release" which is to say that some things on the current master branch (without this PR) appear to be faster or slower than SymPy 1.12.

This PR is the first time I have noticed the four benchmarks that show slowdowns:
```
       before           after         ratio
     [8059df73]       [fc410173]
     <sympy-1.12^0>                 
+     8.02±0.02μs      16.7±0.05μs     2.08  core.expand.TimeExpand.time_expand_arit
+     3.90±0.03μs      8.36±0.03μs     2.14  core.expand.TimeExpand.time_expand_modulus
+     7.69±0.02μs       16.8±0.4μs     2.19  core.expand.TimeExpand.time_expand_negative_integers_powers
+     14.5±0.08μs       23.9±0.4μs     1.65  core.expand.TimeExpand.time_expnad_radicals
```
I am almost certain that those are completely unrelated to this PR but otherwise a *different* recently merged PR might have caused slowdowns.

**Comment by sylee957** [comment]
I think that https://github.com/sympy/sympy/pull/25382 could be the reason of slowdown

**Comment by DarkNisa** [comment]
> This PR has no observable effects on the timings reported by the benchmarks. The changes show are all "master vs previous release" which is to say that some things on the current master branch (without this PR) appear to be faster or slower than SymPy 1.12.

Thanks. Now I understand it better.

**Comment by oscarbenjamin** [comment]
> Thanks. Now I understand it better.

Many people misunderstand this. I am not sure how to change the wording to make it clearer.

**Comment by DarkNisa** [comment]
@oscarbenjamin
I think that if you highlight somehow `master vs previous release` 
with colors or bolding, or inside the benchmark report, (taking as 
idea how it now colors the increase / decrease in performance), 
it will be more clearer, because when you get such a message people
focus theit view on shiny colored benchmark and not on what is 
written before / after it.

**Comment by oscarbenjamin** [comment]
Maybe something like this?

**The differences below are not the result of the changes in _this_ pull request. They compare the performance of the current master branch _without_ the changes here against the performance of the previous release of SymPy (version 1.12).**

Significantly changed benchmark results (master vs previous release)

```diff
       before           after         ratio
     [8059df73]       [fc410173]
     <sympy-1.12^0>                 
+     8.02±0.02μs      16.7±0.05μs     2.08  core.expand.TimeExpand.time_expand_arit
+     3.90±0.03μs      8.36±0.03μs     2.14  core.expand.TimeExpand.time_expand_modulus
+     7.69±0.02μs       16.8±0.4μs     2.19  core.expand.TimeExpand.time_expand_negative_integers_powers
+     14.5±0.08μs       23.9±0.4μs     1.65  core.expand.TimeExpand.time_expnad_radicals
-      83.9±0.8ms       55.0±0.1ms     0.66  integrate.TimeIntegrationRisch02.time_doit(10)
-        83.8±1ms       53.9±0.2ms     0.64  integrate.TimeIntegrationRisch02.time_doit_risch(10)
-        2.09±0ms          618±3μs     0.30  polys.TimePREM_LinearDenseQuadraticGCD.time_op(3, 'sparse')
-     10.4±0.03ms      1.88±0.02ms     0.18  polys.TimePREM_LinearDenseQuadraticGCD.time_op(5, 'sparse')
```

**Comment by DarkNisa** [comment]
I think that's now it's too much bold text). I'll think about it tomorrow and write some good ideas.

**Comment by DarkNisa** [comment]
@oscarbenjamin

Based on my BI experience, I created some design drafts:
[google-drive](https://drive.google.com/drive/folders/110YQdiOSh43wq9960CPQC17xhSvWehAr?usp=sharing)
So my ideas are simple:
a. swap green / red highlighting because it's more natural to see green color in
case of increase of performance.
b. add two highlighted lines which describe the meaning of \+ / \- symbols, so
the user will get associations of the table report with symbols \+ / \-.
c. change before / after words to something more meaningful like
stable release / current state.

So, there is also a room for positioning some things around another.
And so we can reduce the amount of text to the minimum like
"Benchmark results from GitHub Actions"
"Significantly changed benchmark results"

**Comment by oscarbenjamin** [comment]
> a. swap green / red highlighting because it's more natural to see green color in
> case of increase of performance.

Currently the text is just output from asv which uses `+/-`. Then GitHub's diff format is used to render it and that shows a `+` as green and a `-` as red. This is just a quick hack. I suppose that we could swap `+` and `-` but otherwise we would need a different way of controlling the colours which would get more complicated:
https://github.com/sympy/sympy/blob/12d7761b5033628cc12dc2f3b3df9546c2378086/.github/workflows/comment-on-pr.yml#L88-L106

The key point of confusion which everyone seems to have (even after reading the text) is that what is usually shown is differences between master and the current release and not differences that are caused by the pull request. Do you have any suggestion for how to make that clear?

**Comment by oscarbenjamin** [comment]
Yes, that does look nicer. I am still not sure that anyone would understand the difference between the two benchmark comparisons though which is the main point of confusion.

**Comment by DarkNisa** [comment]
No, I think it changes a lot, with such highlighting it will be easier to focus on words PR vs Master / Stable Release vs Master, before looking at the generated benchmark report. But if there is a way to write some text if it doesn't draw benchmarks like in here for PR vs Master like 'There are no significant changes' it will be even better.

**Comment by oscarbenjamin** [comment]
> But if there is a way to write some text if it doesn't draw benchmarks like in here for PR vs Master like 'There are no significant changes' it will be even better.

I think that this is the key. We could change the automatically generated output in the block so it looks more like:

_Significantly changed_ benchmark results (**PR** _vs_ **Master**)
`This PR does NOT change any timings in the benchmark suite.`

Probably that should be the last line in the comment so we should flip the order and have master vs release first and then PR vs master afterwards.

I think if the final line of the comment explicitly says
`This PR does NOT change any timings in the benchmark suite`
then that will at least help people to understand the important part of the message.

**Comment by DarkNisa** [comment]
Great. I like it.

**Pull request merged**
