### PR TITLE
Core: Fixes a minor performance issue

### LINKED ISSUE #19534: Major (127x) performance regression: series() on relatively simple (polynomial) expression
The following code, when run with the latest (git version) of sympy (e339db350473e9fe923cef84915f1385de4066e3), requires about **3 minutes, 11 seconds** to run. In sympy 1.6 and lower, it completes within about **1.5 seconds**. I noticed this because my Travis runs are now timing out. **The regression occurred within the past 24 hours from when this ticket was created.** (Also I say "relatively simple" as it's one of the simpler sympy expressions I test.)

```python
from sympy import sqrt,symbols,series

dt = symbols('dt',real=True)

expr = 16*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0)/45 + 49*dt*(-0.049335189898860408029*dt*(2.0*dt + 1.0) + 0.29601113939316244817*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) - 0.12564355335492979587*dt*(0.074074074074074074074*dt*(2.0*dt + 1.0) + 0.2962962962962962963*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) + 0.96296296296296296296*dt + 1.0) + 0.051640768506639183825*dt + dt*(1/2 - sqrt(21)/14) + 1.0)/180 + 49*dt*(-0.23637909581542530626*dt*(2.0*dt + 1.0) - 0.74817562366625959291*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) + 0.88085458023927036857*dt*(0.074074074074074074074*dt*(2.0*dt + 1.0) + 0.2962962962962962963*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) + 0.96296296296296296296*dt + 1.0) + 2.1165151389911680013*dt*(-0.049335189898860408029*dt*(2.0*dt + 1.0) + 0.29601113939316244817*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) - 0.12564355335492979587*dt*(0.074074074074074074074*dt*(2.0*dt + 1.0) + 0.2962962962962962963*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) + 0.96296296296296296296*dt + 1.0) + 0.22431393315265061193*dt + 1.0) - 1.1854881643947648988*dt + dt*(sqrt(21)/14 + 1/2) + 1.0)/180 + dt*(0.66666666666666666667*dt*(2.0*dt + 1.0) + 6.0173399699313066769*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) - 4.1117044797036320069*dt*(0.074074074074074074074*dt*(2.0*dt + 1.0) + 0.2962962962962962963*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) + 0.96296296296296296296*dt + 1.0) - 7.0189140975801991157*dt*(-0.049335189898860408029*dt*(2.0*dt + 1.0) + 0.29601113939316244817*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) - 0.12564355335492979587*dt*(0.074074074074074074074*dt*(2.0*dt + 1.0) + 0.2962962962962962963*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) + 0.96296296296296296296*dt + 1.0) + 0.22431393315265061193*dt + 1.0) + 0.94010945196161777522*dt*(-0.23637909581542530626*dt*(2.0*dt + 1.0) - 0.74817562366625959291*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) + 0.88085458023927036857*dt*(0.074074074074074074074*dt*(2.0*dt + 1.0) + 0.2962962962962962963*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) + 0.96296296296296296296*dt + 1.0) + 2.1165151389911680013*dt*(-0.049335189898860408029*dt*(2.0*dt + 1.0) + 0.29601113939316244817*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) - 0.12564355335492979587*dt*(0.074074074074074074074*dt*(2.0*dt + 1.0) + 0.2962962962962962963*dt*(0.125*dt*(2.0*dt + 1.0) + 0.875*dt + 1.0) + 0.96296296296296296296*dt + 1.0) + 0.22431393315265061193*dt + 1.0) - 0.35816132904077632692*dt + 1.0) + 5.5065024887242400038*dt + 1.0)/20 + dt/20 + 1

series(expr,dt, 0, 8)
print("Finished!")
```

### PR DESCRIPTION
**Pull request by sachin-4099**
Fixes: #19534 

#### Other Comments
Regression Test has been added.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
@zachetienne can you test out this PR to see if it fixes the problem?

**Comment by zachetienne** [comment]
> @zachetienne can you test out this PR to see if it fixes the problem?

Yes, I tried it out while the PR was undergoing the automatic checks. Indeed it fixes the problem, restoring the original performance.

**Comment by zachetienne** [comment]
Thanks so much @sachin-4099 and @jksuom !

**Comment by asmeurer** [comment]
Perhaps we should also add something to the benchmarks, if there isn't already.

**Comment by oscarbenjamin** [comment]
After a significant regression we should add a benchmark to the benchmarks suite:
https://github.com/sympy/sympy_benchmarks

**Pull request merged**
