### PR TITLE
CI: Update ci-sage.yml

### PR DESCRIPTION
**Pull request by mkoeppe**
#### References to other Issues or PRs

As requested in https://github.com/sagemath/sage/pull/35635#issuecomment-1542935262 https://groups.google.com/g/sage-devel/c/fOTkNoU02Oo/m/oSYAexLUBgAJ @wermos @oscarbenjamin @dimpase

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Thanks Matthias.

I've set this to automerge. We can't see how this works until after merge. We could test it by temporarily setting it to run on the master branch but since this job already doesn't work there is no harm in merging now to see if there are any problems.

**Comment by mkoeppe** [comment]
It's running at https://github.com/mkoeppe/sympy/actions/runs/6291631452/job/17080207981

**Comment by mkoeppe** [comment]
Actually ubuntu-focal is no longer a good test platform because Sage has just dropped support for Python 3.8 for the Sage 10.2 release expected at the end of the year; so Sage is building its own copy of Python 3.11 there.
I'll change it to another platform

**Comment by mkoeppe** [comment]
ubuntu-jammy uses Python 3.10. 
I'll use debian-bullseye, which uses Python 3.9, unless you have other preferences

**Comment by oscarbenjamin** [comment]
My preference is just to use the least flakey platform. I doubt that the exact operating system or Python version matters for SymPy/Sage compatibility but it can affect whether the rest of Sage CI is likely to fail.

Previously two platforms were tested and one would fail for reasons unrelated to SymPy much more than the other. The main thing is that this CI is just supposed to be testing changes in SymPy against changes in Sage so that we can keep them in sync.

**Pull request merged**
