### PR TITLE
[WIP] Support conda gcc and gfortran compilers

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

#15832

#### Brief description of what is fixed or changed

Sample PR to check azure failings, and experiment with workarounds

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
Related: https://github.com/sympy/sympy/issues/15385

**Comment by sylee957** [comment]
Would there be any way to automatically initialize the classes after calling import?

**Comment by oscarbenjamin** [comment]
I guess this can be closed now that Azure isn't used.

**Comment by sylee957** [comment]
There can still be some improvements for codegen module to support conda compilers, though.
But this project is a bit suspended right now.

**Pull request closed without merging**
