### PR TITLE
Added multipledispatch as SymPy dependency

### PR DESCRIPTION
**Pull request by Upabjojr**
External library https://github.com/mrocklin/multipledispatch/

### CODE REVIEW

**Comment by Upabjojr** [comment]
If we merge this, we need to find a way to assure the dependency is installed through _pip_ and _conda_.

**Comment by moorepants** [comment]
Shouldn't you add this to the setup.py files in this PR so that pip will install the dependency?

**Comment by asmeurer** [comment]
I don't see the point of adding it as a dependency before it is even being used. 

We also should consider just adding it to the code directly, or adding a similar version (it's not that complicated).

**Comment by Upabjojr** [comment]
> We also should consider just adding it to the code directly, or adding a similar version (it's not that complicated).

We could actually do that.

**Pull request closed without merging**
