### PR TITLE
Assertion was changed to exception

### LINKED ISSUE #5090: Don't use assert in the library code when an exception would be better
Basically, you should rewrite it to use an if construct and a proper exception (ValueError, TypeError, NotImplementedError, or a special error for the module are the usual suspects).  
```
$ git grep assert | grep -v test
```
Will show most offending lines.  I have already fixed matrices.py in my integration3 branch.

Original issue for #5090: http://code.google.com/p/sympy/issues/detail?id=1991
Original author: https://code.google.com/u/asmeurer@gmail.com/
Original owner: https://code.google.com/u/asmeurer@gmail.com/

### PR DESCRIPTION
**Pull request by chehakmalhotra**
#### References to other Issues or PRs
 Fixes #5090

#### Brief description of what is fixed or changed
The two Assertion statements were improved upon and rewritten using if constructs and the exception.

#### Release Notes

* logic
    * Improved upon the assertion statement

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
It isn't necessary to close the PR and open a new one if you want to make some changes. You can just make a new commit and push it.

**Comment by oscarbenjamin** [comment]
The authors check is failing because the .mailmap file is supposed to be in alphabetical order. You just need to run the `bin/mailmap_check.py` script and the file will be reordered for you. Make sure to run it again and see that it says everything is fine.

**Comment by Chehakmalhotra** [comment]
> The authors check is failing because the .mailmap file is supposed to be in alphabetical order. You just need to run the `bin/mailmap_check.py` script and the file will be reordered for you. Make sure to run it again and see that it says everything is fine.

Thank You for the help. Could you also please explain why test/author is still failing and giving file re-ordered error.

**Comment by oscarbenjamin** [comment]
> Could you also please explain why test/author is still failing

Did you actually run the `bin/mailmap_check.py` script?

**Comment by Chehakmalhotra** [comment]
> > Could you also please explain why test/author is still failing
> 
> Did you actually run the `bin/mailmap_check.py` script?

Yes, I did run the file and that has worked. The exact error message is as follows:
Ambiguous name warning: if a person uses more than one email address,
entries should be added to .mailmap to merge them into a single
canonical address. Then re-run this script.
checking .mailmap...
.mailmap lines were re-ordered.

**Comment by oscarbenjamin** [comment]
That output does not come from the `bin/mailmap_check.py` script. It comes from the `bin/mailmap_update.py` script.

**Comment by Chehakmalhotra** [comment]
> That output does not come from the `bin/mailmap_check.py` script. It comes from the `bin/mailmap_update.py` script.

Thank You very much. It works now.

**Comment by oscarbenjamin** [comment]
Now that I look at it this is just changing the code in one of the example notebooks. The issue #5090 is about library code but this isn't library code. It's fine to use an assert in the example notebook. I don't think the changes in this PR are needed.

**Pull request closed without merging**
