### PR TITLE
WIP: 19365 improve matrix isindefinite

### PR DESCRIPTION
**Pull request by galbwe**
This PR fixes a bug that caused `Matrix.is_indefinite` to return `None` when complex expressions were passed to fuzzy logic functions. I replaced the eigenvalue computation that was there with one that uses mpmath, which should improve performance. 

#### References to other Issues or PRs

[Addresses issue 19365](https://github.com/sympy/sympy/issues/19365)

#### Brief description of what is fixed or changed
- Changed implementation of `_is_indefinite` in `eigen.py` to directly use mpmath
- Added tests for real and complex cases to `test_eigen.py`

#### Release Notes

* matrices
  * Fixed bug that caused `Matrix.is_indefinite` to return None.

### CODE REVIEW

**Comment by sylee957** [comment]
Unfortunately, I don't think that it should rely on numeric testing because sympy is not focused on numeric capability, and I'm worried about any garbage in garbage out situations that can occur, unless you can assert about the numeric errors.

However, if the matrix have at least one floating point element, it can make the whole system to be inexact, so that's the only case where numeric test can be used.

**Comment by sylee957** [comment]
I think that if matrix have both positive and negative elements in the diagonals, the matrix is indefinite because having both positive and negative elements in the diagonals implies that the matrix is not negative semidefinite and not positive semidefinite.

This can be a useful property to test out before passing to more slow fallback methods.

**Comment by oscarbenjamin** [comment]
> having both positive and negative elements in the diagonals implies that the matrix is not negative semidefinite and not positive semidefinite.

I think maybe this is true in the diagonally dominant case but it is not true in general e.g.:
```julia
In [22]: M = Matrix([[2, 2], [-1, -1]])                                                                                                        

In [23]: M                                                                                                                                     
Out[23]: 
⎡2   2 ⎤
⎢      ⎥
⎣-1  -1⎦

In [24]: M.eigenvals()                                                                                                                         
Out[24]: {0: 1, 1: 1}
```

**Comment by oscarbenjamin** [comment]
Maybe it's possible to make use of diagonal dominance more in checking for positive definite/semidefinite:
https://en.wikipedia.org/wiki/Diagonally_dominant_matrix#Applications_and_properties
https://en.wikipedia.org/wiki/Weakly_chained_diagonally_dominant_matrix#:~:text=In%20mathematics%2C%20the%20weakly%20chained,the%20strictly%20diagonally%20dominant%20matrices.

**Comment by sylee957** [comment]
Indefinite is often asserted if there are nonzero vectors `x`, `y` with quadratic forms `x.H*A*x > 0 > y.H*A.x`.

https://econweb.ucsd.edu/~jsobel/205f10/notes8.pdf
Here, I also see the interpretation that `indefinite if A has both negative and positive
diagonal entries.`

Now I have some doubts whether the definition `x.H*A*x > 0 > y.H*A.x` is actually correct, if that is the counter example, but at least for your example https://github.com/sympy/sympy/pull/19582#issuecomment-645862105, it have zero determinant and implying at least a zero eigenvalue, so I wonder if the assertion can be made stronger by requiring the determinant to be nonzero too.

**Comment by sylee957** [comment]
Actually, I think that this PR had also changed the definition, because `Matrix([[2, 2], [-1, -1]]).is_indefinite` had been `True` while this had made it to be `False`

**Comment by sylee957** [comment]
And anyway, `M = Matrix([[2, 2], [-1, -1]])` doesn't even look like symmetric matrix, and its symmetrized form `M + M.T` is not singular and is indefinite in any sense.

**Comment by galbwe** [comment]
> Actually, I think that this PR had also changed the definition, because `Matrix([[2, 2], [-1, -1]]).is_indefinite` had been `True` while this had made it to be `False`

I added a test showing that `Matrix([[2, 2], [-1, -1]]).is_indefinite == True` after the most recent changes.

**Comment by galbwe** [comment]
> And anyway, M = Matrix([[2, 2], [-1, -1]]) doesn't even look like symmetric matrix

I thought sympy's checks on definiteness only considered the symmetric part of M. Is this correct?

**Comment by galbwe** [comment]
> I think that if matrix have both positive and negative elements in the diagonals, the matrix is indefinite

I think this is true if we also assume M is symmetric nonsingular.

**Comment by oscarbenjamin** [comment]
I missed the need for the matrix to be symmetric/hermitian when giving the previous example.

> I think this is true if we also assume M is symmetric nonsingular.

Why does it need to be nonsingular?
```julia
In [128]: M = Matrix([[-1, 0, 0], [0, 0, 0], [0, 0, 1]])                                                                                       

In [129]: M                                                                                                                                    
Out[129]: 
⎡-1  0  0⎤
⎢        ⎥
⎢0   0  0⎥
⎢        ⎥
⎣0   0  1⎦

In [130]: M.eigenvals()                                                                                                                        
Out[130]: {-1: 1, 0: 1, 1: 1}
```

**Comment by galbwe** [comment]
@oscarbenjamin I was working off of the definition given [here](http://mathonline.wikidot.com/definite-semi-definite-and-indefinite-matrices), which says M is indefinite iff M is nonsingular and not positive definite and not negative definite. After some thought, this definition seems stronger than what we want to use in sympy. The example you gave should be considered indefinite because quadtratic form associated with `M` is neither strictly positive nor strictly negative.

```python
In [14]: M = sympy.Matrix([[1, 0, 0], [0, 0, 0], [0, 0, -1]])                                                                                                           
In [15]: x1 = sympy.Matrix([[1], [0], [2]])                                                                                                                             
In [16]: x2 = sympy.Matrix([[2], [0], [1]])                                                                                                                             
In [17]: x1.T * M * x1                                                                                                                                                  
Out[17]: Matrix([[-3]])
In [18]: x2.T * M * x2                                                                                                                                                  
Out[18]: Matrix([[3]])
``` 

I added a test expecting `M` to be indefinite and it failed spectacularly. I'll try to remove the assumption that `M` is non-singular and adjust the tests accordingly.

**Comment by oscarbenjamin** [comment]
The definition at the link you've shown says
```
d) If det(A)=Dn=0, then A may be Indefinite or what is known
Positive Semidefinite or Negative Semidefinite.
```
which is not the same as the "iff" in the comment above.

**Comment by sylee957** [comment]
I've got to believe that there are actually two types of definitions of indefinite that people are using.
Some people could been claiming that the matrix should also be nonsingular,

But I don't think that the definition to require nonsingular is good because it doesn't tell about anything for a matrix which have all positive and negative and zero eigenvalues. 
It just introduces an unclassified class of matrices which is neither positive semidefinite, negative semidefinite, and neither indefinite.

**Comment by galbwe** [comment]
@sylee957 I think I have the definition sorted out now. On [Wikipedia](https://en.wikipedia.org/wiki/Definite_symmetric_matrix) it says a matrix is indefinite if it is not positive semidefinite and not negative semidefinite. I think this is meant only to apply to Hermitian matrices. For consistency with the other definiteness properties defined in sympy, I will take the Hermetian part of the input before applying this definition.

If the matrix is Hermetian and has positive and negative real entries on the diagonal, then it is not positive semidefinite and not negative semidefinite by the argument used [here](https://math.stackexchange.com/questions/927902/does-a-positive-semidefinite-matrix-always-have-a-non-negative-trace#:~:text=So%2C%20if%20A%20is%20positive,the%20trace%20is%20non%2Dnegative). I'll take your advice and do a prelimary check for this criterion since it is `O(n)` and can greatly improve the average runtime.

**Comment by sylee957** [comment]
Wait, I don't think that you have to remove the old positive_semidefinite and use numeric evaluation

I have a suggestion to apply
```diff
$ git diff
diff --git a/sympy/matrices/eigen.py b/sympy/matrices/eigen.py
index e3cc7c30f1..868b20fbac 100644
--- a/sympy/matrices/eigen.py
+++ b/sympy/matrices/eigen.py
@@ -673,7 +673,21 @@ def _fuzzy_positive_definite(M):
     return None


+def _fuzzy_positive_semidefinite(M):
+    nonnegative_diagonals = M._has_nonnegative_diagonals()
+    if nonnegative_diagonals is False:
+        return False
+
+    if nonnegative_diagonals and M.is_weakly_diagonally_dominant:
+        return True
+
+    return None
+
+
 def _is_positive_definite(M):
+    if any(x is nan for x in M):
+        raise ValueError
+
     if not M.is_hermitian:
         if not M.is_square:
             return False
@@ -687,19 +701,45 @@ def _is_positive_definite(M):


 def _is_positive_semidefinite(M):
-    if not M.is_square:
-        return False
-    if any(m == nan for m in M):
-        raise ValueError('Matrix contains nan')
-    M = (M + M.H) / 2
+    from .determinant import _find_reasonable_pivot

-    if any(M[i, i].is_negative for i in range(M.rows)):
-        return False
-    elif M.is_weakly_diagonally_dominant:
-        # If diagonal entries of M are nonnegative and
-        # M wdd, then M is positive semidefinite
-        return True
-    return all(re(e.evalf()) >= 0 for e in M.eigenvals())
+    if any(x is nan for x in M):
+        raise ValueError
+
+    if not M.is_hermitian:
+        if not M.is_square:
+            return False
+        M = M + M.H
+
+    fuzzy = _fuzzy_positive_semidefinite(M)
+    if fuzzy is not None:
+        return fuzzy
+
+    # uses Cholesky factorization with complete pivoting
+    # see http://eprints.ma.man.ac.uk/1199/1/covered/MIMS_ep2008_116.pdf
+    M = M.copy()
+    for k in range(M.rows):
+        pivot, _, nonzero, _ = _find_reasonable_pivot(
+            [M[i, i] for i in range(k, M.rows)])
+
+        if pivot is None:
+            if nonzero:
+                return None
+            return True
+
+        if pivot > 0:
+            M.col_swap(k, k+pivot)
+            M.row_swap(k, k+pivot)
+
+        if M[k, k].is_negative:
+            return False
+
+        M[k, k] = sqrt(M[k, k])
+        M[k, (k+1):] /= M[k, k]
+        for j in range(k+1, M.rows):
+            M[(k+1):(j+1), j] -= M[k, (k+1):(j+1)].H * M[k, j]
+
+    return M[-1, -1].is_nonnegative


 def _is_negative_definite(M):
@@ -714,25 +754,26 @@ def _is_indefinite(M):
     """Returns True if M is not positive semi-definite
     and not negative semi-definite and false otherwise
     """
-    if not M.is_square:
-        return False
-    if any(m == nan for m in M):
-        raise ValueError('Matrix contains nan')
-    M = (M + M.H) / 2
-    return (
-        (
-            # faster check
-            # if M has both positive and negative
-            # diagonal entries, it is neither negative
-            # semidefinite nor positive semidefinite,
-            # so it is indefinite
-            any(M[i, i].is_positive for i in range(M.rows)) \
-            and any(M[i, i].is_negative for i in range(M.rows)) \
-        ) \
-        or not (
-            M.is_positive_semidefinite \
-            or M.is_negative_semidefinite \
-        )
-        )
+    if any(x is nan for x in M):
+        raise ValueError
+
+    if not M.is_hermitian:
+        if not M.is_square:
+            return False
+        M = M + M.H
+
+    from sympy.core.logic import fuzzy_or, fuzzy_not
+
+    positive_diags = (M[i, i].is_positive for i in range(M.rows))
+    negative_diags = (M[i, i].is_negative for i in range(M.rows))
+    if fuzzy_or(positive_diags) and fuzzy_or(negative_diags):
+        return True
+
+    return fuzzy_not(
+        fuzzy_or([
+            M.is_positive_semidefinite,
+            M.is_negative_semidefinite
+        ])
     )
```

The only notable differences are:
1. I have corrected the mathematical mistake of using transpose instead of conjugation in #19573, so positive_semidefinite would not be broken for complex matrices.
2. I have used more accurate pivoting method `_find_reasonable_pivot`, and it can detect some mathematically not asserted nonzero cases.
3. I have also translated the logics to use fuzzy bools.

**Comment by galbwe** [comment]
You need to handle zero division errors caused by this line `M[k, (k+1):] /= M[k, k]`. I decided it was better to use a method that did not error and actually worked for all of my test cases.

**Comment by sylee957** [comment]
Pivoting guarantees `M[k, k]` to be nonzero.

**Comment by galbwe** [comment]
I'll take some time to try and understand what was wrong with my implementation of the pivot method.

**Comment by galbwe** [comment]
Also, what are these fuzzy logic functions that get used everywhere?

**Comment by sylee957** [comment]
SymPy fuzzy logic functions should be used if you are going to derive any logic from sympy assumptions system.

Python logic operators shouldn't be used for this because it can have problems like
```
>>> None and False
None
>>> False and None
False
>>> None or True
True
>>> True or None
True
>>> None or False
False
>>> False or None
None
```
so you can even get unexpected results.

**Comment by sylee957** [comment]
I think that it looks too much complicated to introduce new classes and exceptions, and it can be unnecessary if it is not going to be used anywhere else in sympy.
Although I'm not sure that you are actually planning to introduce something more complicated for this.

**Comment by oscarbenjamin** [comment]
This seems a bit over-engineered now

**Comment by galbwe** [comment]
I'm going to bow out of this one and let someone more knowledgable on the subject matter pick it up. One test to be aware of with the Cholesky factorization with pivoting is `Matrix([[0, 1], [1, 0]])`. Its eigenvalues are `-1` and `1`, but is_indefinite currently returns `False`. Maybe it's my particular implementation of the algorithm. I don't know. Good luck to whoever picks it up.

**Pull request closed without merging**
