### PR TITLE
Fix: abs for numexpr, not Abs

### PR DESCRIPTION
**Pull request by jonas-eschle**
#### Brief description of what is fixed or changed

NumexprPrinter has an invalid entry, it's "abs", not "Abs". The name of the function "abs" is "abs" not "Abs".

#### Release Notes

Fix bug in numexpr lambdify that used the invalid identifier Abs instead of abs

 * printing
 	* Fix invalid NumExprPrinter identifier "Abs" to "abs"

### CODE REVIEW

**Comment by smichr** [comment]
> Not exactly,

So it would be more accurate to say that it returns Abs or a SymPy object when the argument is of SymPy type.

**Comment by oscargus** [comment]
`key, value pairs correspond to sympy name and numexpr name`

Well, the SymPy name is Abs, so I guess that it is correct. Is this causing any issues?

**Comment by jonas-eschle** [comment]
> `key, value pairs correspond to sympy name and numexpr name`
> 
> Well, the SymPy name is Abs, so I guess that it is correct. Is this causing any issues?

Yes, indeed. Sorry, I thought this is a no-brainer, but it's truly more complex than thought.

Here it is:
```
import sympy
sympy_expr = sympy.sympify('abs(-42)')
sympy.lambdify([], sympy_expr, modules='numexpr')
```

But actually, as I digged in now, the error seems to be in the parsing, not in the lambdification.

This parses correctly
```
sympy.sympify('Abs(-42)', evaluate=False)
```

I'll close this RP and open an issue then

**Comment by oscargus** [comment]
Would it be possible to just add both lines?
```
'Abs' : 'abs'
'abs' : 'abs'
```

(I have no idea how it works, so this is just a random stab...)

(I also noted that it looked like the problem was actually elsewhere, but in case it reappears here...)

**Pull request closed without merging**
