### PR TITLE
Update secondquant.py

### PR DESCRIPTION
**Pull request by rajeev2010**
dagger was not appearing in ipython notebook

### CODE REVIEW

**Comment by thisch** [comment]
@rajeev2010  is this already fixed in master?

**Comment by rajeev2010** [comment]
@thisch after going through some more examples and testing new codes i realized that the change i made was not correct. the master version is appearing correctly in notebook and latex documents. i guess i had difficulty earlier probably due to some bug in notebook itself. but the current master has this problem at many places (see the link in my comment above). i think "\dag" should be replaced by "\dagger" everywhere.

**Comment by thisch** [comment]
I don't think so. In contrast to \dagger, \dag works in both math and text mode since latex2e. Can you provide a simple example, where you see (in master) that dagger is not properly displayed?

**Comment by rajeev2010** [comment]
it appears to be a bug of ipython/jupyter. if i run the following code in a notebook the first output is not displayed properly, but expressions that use \dagger instead of \dag are just fine -

```python
import sympy
from sympy import latex
from IPython.display import display
from IPython.display import Math
sympy.init_printing()
from sympy.physics.quantum import Dagger
from sympy.physics.quantum.boson import BosonOp

a = BosonOp("a")
display( Math( r"N = " + latex( (Dagger(a) * a) ) ) )
display( Dagger(a) * a )
Dagger(a) * a
```

**Pull request closed without merging**
