### PR TITLE
integrals/intpoly: Change list casting to set casting for decompose()

### LINKED ISSUE #13042: decompose() function in intpoly returns a list of arbitrary order
The decompose() function, with separate=True, returns `list(poly_dict.values())`, which is ordered arbitrarily.  

What is this used for? It should be sorted somehow, or returning a set (in which case, why not just use the returned dictionary and have the caller take the values). This is causing test failures for me after some changes to the core. 

CC @ArifAhmed1995 @certik

### PR DESCRIPTION
**Pull request by ArifAhmed1995**
@asmeurer If `separate=True` the dictionary will have duplicate keys when `expr` is of `Add` type. Then a `list` or more correctly a `set` should be returned. I did not directly return `set` for other cases because of more if-else checks.

Fixes #13042

### CODE REVIEW

**Comment by asmeurer** [comment]
For most intents and purposes, a set of a dictionary's keys is just as good as the dictionary itself. Why is this keyword argument even needed, if a set return type is good enough?

**Comment by ArifAhmed1995** [comment]
When `separate` is `True` the input polynomial is broken up into constituent ones whereas if `False` then it's broken up into constituent smaller polynomials each being homogeneous.

Now, if dictionary was used for both cases then the problem of duplicate keys would arise.
```
>>> decompose(x**2 + x*y, separate=True)
{2: x*y}
```
whereas actually `{2: x**2, 2:x*y}` is needed. But this doesn't make sense and of course not expected from a dictionary.
Returning a set wouldn't suffice in the `separate=False` case because the degree along constituent polynomial is required.

**Comment by asmeurer** [comment]
I see, it's the values, not the keys.

**Comment by certik** [comment]
Thanks @ArifAhmed1995 for the fix and thanks @asmeurer for merging it.

**Pull request merged**
