### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by jjmortensen**
0.125 is 1/8 and not 1/4

### CODE REVIEW

**Comment by scopatz** [comment]
Looks good to me too.

**Comment by leosartaj** [comment]
Thanks @jjmortensen.

**Comment by certik** [comment]
@jjmortensen What is your full name to put into AUTHORS?

**Comment by certik** [comment]
@jjmortensen using [this](http://listserv.fysik.dtu.dk/pipermail/gpaw-developers/2014-October/005045.html) email from your email address, I put your name as "Jens Jørgen Mortensen" in #10270. Please let me know if that's ok.

**Comment by jjmortensen** [comment]
@certik That's fine!

**Comment by certik** [comment]
Perfect, thanks.

**Pull request merged**
