### PR TITLE
Add documentation of the initialization parameters of Kane's method

### PR DESCRIPTION
**Pull request by tjstienstra**
#### Brief description of what is fixed or changed
Added documentation of the initialization parameters of Kane's method.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by TJStienstra** [comment]
@moorepants do you agree on that it would be useful to add a parameters section to Kane's method. I noticed we only had an attributes section.

**Comment by moorepants** [comment]
Yes, the more docs the better. I thought it was there but was it just hidden in the `__init__` doc string?

**Comment by moorepants** [comment]
LGTM

**Comment by TJStienstra** [comment]
> I thought it was there but was it just hidden in the `__init__` doc string?

Nope, we did append some of the parameters to the attributes, such that there was some documentation on those.

**Pull request merged**
