### PR TITLE
elementwise apply function printer review

### PR DESCRIPTION
**Pull request by Upabjojr**
#### Release Notes

* printing
  * Printer for ElementwiseApplyFunc now uses circle before parenthesis

### CODE REVIEW

**Comment by Upabjojr** [comment]
Concern: how to handle expressions of mixed `ElementwiseApplyFunction` and `HadamardProduct`. They both use circle and are likely to appear together in many optimization problems involving matrix expressions (especially with derivatives).

**Comment by asmeurer** [comment]
Is the notation used here standard? 

I guess it's unambiguous in that if the thing to the left of the circle is a function it means elementwise and if it's a matrix or tensor it's Hadamard product. 

For the LaTeX printer we could use something less ambiguous like `\sin_\circ`. That's probably too much for the pretty printer, though, because subscript requires a separate row.

**Comment by asmeurer** [comment]
I didn't find anything when googling, but there's probably a standard notation used in the machine learning literature, since elementwise operations are used all the time there.

**Comment by Upabjojr** [comment]
I was inspired by this comment: https://github.com/sympy/sympy/issues/16680#issuecomment-484796725

Apparently in Julia they are using `sin.(X)` for the elementwise function application.

> For the LaTeX printer we could use something less ambiguous like \sin_\circ. That's probably too much for the pretty printer, though, because subscript requires a separate row.

That's a nice idea. Maybe also combine it with an arrow?

> there's probably a standard notation used in the machine learning literature, since elementwise operations are used all the time there.

For what I know, in machine learning they assume that all functions are applied elementwise. That is, `exp(X)` means `exp` applied elementwise to all elements of `X`. They don't care about the correct mathematical definitions of functions of matrices.

**Comment by Upabjojr** [comment]
Maybe the circle should be put above the function name:
```
 ∘ ⎛ T  ⎞
sin⎝X ⋅X⎠


   ∘
⎛    1⎞      
⎜d ↦ ─⎟(n⋅X)
⎝    d⎠      
```

or below to the right:
```
    ⎛ T  ⎞
sin ⎝X ⋅X⎠
   ∘


⎛    1⎞      
⎜d ↦ ─⎟ (n⋅X)
⎝    d⎠∘  
```

or inside the parenthesis:

```
   ⎛  T  ⎞
sin⎝∘X ⋅X⎠
   


⎛    1⎞      
⎜d ↦ ─⎟(∘n⋅X)
⎝    d⎠  
```

**Comment by Upabjojr** [comment]
My fear is to end up with expressions like:
```
  √2   ⎛⎛ 1   ⎛⎛  ⎛         ⎛    1⎞           ⎞⎞                  ⎞⎞     ⎛ 1                    ⎞⎞
──────⋅⎜⎜────⋅⎜⎜2⋅⎜(-𝟙 + 𝟘)∘⎜d ↦ ─⎟∘(-μ⋅𝟙 + x)⎟⎟∘((-mu)*1 + x).**2⎟⎟∘exp∘⎜────⋅((-mu)*1 + x).**2⎟⎟
2⋅√π⋅σ ⎜⎜   2 ⎝⎝  ⎝         ⎝    d⎠           ⎠⎠                  ⎠⎟     ⎜   2                  ⎟⎟
       ⎝⎝2⋅σ                                                       ⎠     ⎝2⋅σ                   ⎠⎠





```

**Comment by asmeurer** [comment]
.** can be represented as a circle before the exponent. The Wikipedia page for Hadamard product mentions this. I think it’s a common notation.

**Comment by Upabjojr** [comment]
> .** can be represented as a circle before the exponent. The Wikipedia page for Hadamard product mentions this. I think it’s a common notation.

Hadamard products and powers are already correctly represented. The question is about the printer for elementwise functions.

**Comment by Upabjojr** [comment]
Maybe there is a bug in the pretty printer.

**Comment by asmeurer** [comment]
I mentioned that because it was in the example you pasted.

**Comment by oscargus** [comment]
There is at least a circle before the printer in the LaTeX printer. As far as I'm concerned there has never been any printing for HadamardPower in the pretty printer, but it relied on the str-printer (I had to add support in #17295),

**Comment by Upabjojr** [comment]
I was able to find the unicode character `˳` (low circle). This PR is now complete.

**Pull request merged**
