### PR TITLE
1.0

### LINKED ISSUE #9891: SymPy 1.0
This is a tracking issue for SymPy 1.0. Please note any issues that need to be fixed by that release here. 

The release should be considered forthcoming, meaning that unless there are immediate plans to do something, it should be postponed.

### PR DESCRIPTION
**Pull request by asmeurer**
This is the pull request for 1.0. **DO NOT MERGE**. I will merge when the release is finished. Fixes #9891.

The release notes are at https://github.com/sympy/sympy/wiki/Release-Notes-for-1.0. Feel free to edit them.

### CODE REVIEW

**Comment by asmeurer** [comment]
[List of pull requests against this branch](https://github.com/sympy/sympy/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3A1.0)

**Comment by Upabjojr** [comment]
I would like to have https://github.com/sympy/sympy/issues/10599 solved for the 1.0 release.

**Comment by asmeurer** [comment]
Those docs are definitely building for me locally. I marked your issue with the release milestone so I remember to check that they get uploaded when I do that (it's part of the release process, but it doesn't happen until the final release is made).

**Comment by asmeurer** [comment]
Reported by Ondrej on the mailing list:

- [ ] Plotting tests give UserWarnings
- [ ] Examples end with `python: can't open file 'bin/test': [Errno 2] No such file or directory`

**Comment by asmeurer** [comment]
The plotting test warnings are 

```
sympy/plotting/tests/test_plot.py[3] /Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/experimental_lambdify.py:230: UserWarning: The evaluation of the expression is problematic. We are trying a failback method that may still work. Please report this as a bug.
  warnings.warn('The evaluation of the expression is'
...                                                                                                                 [OK]
sympy/plotting/tests/test_plot_implicit.py[2] ./Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/plot_implicit.py:83: UserWarning: Adaptive meshing could not be applied to the expression. Using uniform meshing.
  warnings.warn("Adaptive meshing could not be applied to the"
```

The first warning comes from plotting `Integral(log((sin(x)**2 + 1)*sqrt(x**2 + 1)), (x, 0, y))` on `(y, 1, 5)`. The problem is that the integral can't be directly lambdified (actually experimental_lambdified) to something that can be evaluated. It has to use the fallback method that uses evalf. I'm unclear why this necessarily represents a bug. I suppose for now we should just suppress this warning. 

The second warning comes from a test that his this comment 

```
    #Test plots which cannot be rendered using the adaptive algorithm
    #TODO: catch the warning.
    plot_and_save(Eq(y, re(cos(x) + I*sin(x))), name=name)
```

So it is explicitly testing the warning case. I'll add code to test the warning and suppress it from the test output.

**Comment by asmeurer** [comment]
I've pushed a fix for the plotting warnings. I can't reproduce the examples error. 

Side question: are our examples actually run anywhere (like on Travis)?

**Comment by asmeurer** [comment]
I believe I fixed the other issue too (you'll only see it if you run the tests with `setup.py test` from a different directory in Python 2 and have Sage installed).

**Comment by asmeurer** [comment]
@certik the issues you noted were the only issues that have been reported. I have fixed them and Travis is passing. Unless I hear of other issues by then, I will do a final release tomorrow.

**Comment by certik** [comment]
Can you create me a tarball to test?

**Comment by asmeurer** [comment]
Had to fix one more issue (hopefully the last). Once I get a release built I'll send it to you. Since there were no major issues, I've marked this as the final release (I'm not doing another release candidate).

**Comment by certik** [comment]
That's fine. But do not release before I check it manually. I want to make sure we don't leave some embarrassing bug in there.

**Comment by asmeurer** [comment]
I won't. But because it's not a release candidate, I won't tag and upload the release to the usual place (because that would be a final release). So I'll have to upload the tarball here to the issue (I guess) and you can check it.

**Comment by certik** [comment]
That works. Or use testpypi.python.org

**Comment by asmeurer** [comment]
I'll also not do the final release until the Travis runs finish on the HEAD of this branch.

**Comment by asmeurer** [comment]
@certik these are the changes since the release candidate https://github.com/sympy/sympy/compare/sympy-1.0.rc1...1.0. Do you think we should make another release candidate, or just do a final release?

**Comment by certik** [comment]
I would like to test the tarballs at least. Can you send me the tarballs that will become the release? Let me test them one more time.

**Comment by asmeurer** [comment]
Yeah, I'll send you them either way (I'm building them now, and we also should wait for this final Travis run). But do you think we should also do another release candidate for others to test, or are the changes minor enough that we can just do a final release?

**Comment by asmeurer** [comment]
The release has been tagged and released. I guess I need change the version file in this so that it can be merged.

**Comment by asmeurer** [comment]
OK, please merge this when Travis passes.

**Comment by leosartaj** [comment]
This is in, SymPy 1.0 :smile:

**Pull request merged**
