### PR TITLE
Replaced instances of _needs_brackets with parenthesize in Latex printer

### LINKED ISSUE #10157: Replace needs_brackets with parenthesize in the latex printer
The LaTeX printer has a `_needs_brackets` method, which checks if something needs parentheses. But there is already the parenthesize module, which works more generally. Uses of `_needs_brackets` should be replaced and `_needs_brackets` should be removed or deprecated.

I've already replaced one instance of this over at https://github.com/sympy/sympy/pull/10084, but I didn't bother with the rest. 

This shouldn't be too hard to fix, as long as you have an understanding of how operator precedence works. And hopefully there should be sufficient test coverage to avoid breaking things, although whoever fixes this should probably check that each instance of `_needs_brackets` is tested to be sure.

### PR DESCRIPTION
**Pull request by jailuthra**
Fixes #10157 

I've changed some tests to match the output of parenthesize, see commit [d54b96](https://github.com/jailuthra/sympy/commit/d54b96).

Please let me know if there are any issues, or if I should add more tests.

Cheers!

### CODE REVIEW

**Comment by jailuthra** [comment]
@asmeurer What should be done about the [failing tests](https://travis-ci.org/sympy/sympy/jobs/99363107)?

__tldr:__ Should I change them to match `parenthesize`'s output or is there a workaround?


The physics symbols get precedence _Atom_ when compared in `parenthesize` thus latex output does not have parentheses, but when we used `_needs_brackets` it checked for `is_Atom` attribute which is False for these symbols thus the latex output had parentheses around them.
This is an inconsistency between `parenthesize` and `_needs_brackets`.

We can do changes similar to the following diff to all tests.

```diff
--- a/sympy/physics/quantum/tests/test_printing.py
+++ b/sympy/physics/quantum/tests/test_printing.py
@@ -85,7 +85,7 @@ def test_anticommutator():
 """)
     assert pretty(ac_tall) == ascii_str
     assert upretty(ac_tall) == ucode_str
-    assert latex(ac_tall) == r'\left\{\left(A\right)^{2},B\right\}'
+    assert latex(ac_tall) == r'\left\{A^{2},B\right\}'
     sT(ac_tall, "AntiCommutator(Pow(Operator(Symbol('A')), Integer(2)),Operator(Symbol('B')))")
 
 
@@ -194,7 +194,7 @@ def test_commutator():
 """)
     assert pretty(c_tall) == ascii_str
     assert upretty(c_tall) == ucode_str
-    assert latex(c_tall) == r'\left[\left(A\right)^{2},B\right]'
+    assert latex(c_tall) == r'\left[A^{2},B\right]'
     sT(c_tall, "Commutator(Pow(Operator(Symbol('A')), Integer(2)),Operator(Symbol('B')))")
 
 
@@ -529,7 +529,7 @@ def test_operator():
 """)
     assert pretty(inv) == ascii_str
     assert upretty(inv) == ucode_str
-    assert latex(inv) == r'\left(A\right)^{-1}'
+    assert latex(inv) == r'A^{-1}'
     sT(inv, "Pow(Operator(Symbol('A')), Integer(-1))")
     assert str(d) == 'DifferentialOperator(Derivative(f(x), x),f(x))'
     ascii_str = \
 
```
Issue #10157

**Comment by jailuthra** [comment]
@asmeurer Please review the changes and let me know if I should fix something more

**Comment by asmeurer** [comment]
PRECEDENCE["Pow"] should only be used for _print_Pow. Probably we need to add a new precedence, FUNC, between POW and ATOM (if I got that logic right), and use that for the functions. Not sure if it should go before or after NOT. You'll have to see how that affects things.

**Comment by asmeurer** [comment]
Your changes to the physics module seem to match what I did at https://github.com/sympy/sympy/pull/10084.

**Comment by jailuthra** [comment]
I've updated the branch with the changes in precedence of functions. One travis [job](https://travis-ci.org/sympy/sympy/jobs/102778386) (pypy) is still failing, though it passes on my local install of pypy.

**Pull request merged**
