### PR TITLE
Improve performance of DenseMatrix arithmetic

### PR DESCRIPTION
**Pull request by siefkenj**
An `_InplaceMatrix` object was added as a thin wrapper around a list to allow matrix arithmetic.  Using this in the `_eval_*` routines for `DenseMatrix` gives a 2x performance increase for matrix multiplication and addition.

### CODE REVIEW

**Comment by siefkenj** [comment]
@jksuom @smichr would you mind taking a look at this PR?

**Comment by jksuom** [comment]
Why are the standard matrix operations slow? Is it because copies are made in `_force_mutable`?

**Comment by siefkenj** [comment]
@jksuom at the moment there are several layers of indirection.  For dense matrices, multiplication and addition is done in `MatrixArithmetic`, which limits itself to only indexing. e.g., when it wants the 4,2 entry, it calls `a[4,2]`.  For a dense matrix we know it is stored as a flat list in `a._mat`, so we can use faster list operations instead of looping over indices with the slight overhead that entails.

**Comment by jksuom** [comment]
Did you plan to use `_InplaceMatrix` internally for dense matrices by-passing `MatrixArithmetic`? Is it necessary to introduce yet another class for improved performance?

**Comment by siefkenj** [comment]
This PR uses `_InplaceMatrix` and overrides the `MatrixArithmetic` methods. Are you suggesting things would look better if `_InplaceMatrix` and `DenseMatrix` were merged somehow?

**Comment by jksuom** [comment]
Yes, something like that if the purpose of `_InplaceMatrix` is specifically to improve dense matrix operations. I am beginning to worry about the increasing complexity of the system ("several layers of indirection").

**Comment by jksuom** [comment]
`Add` will try to sympify all arguments and will raise `SympifyError` if that is not possible. Otherwise this looks good.

**Comment by siefkenj** [comment]
There we go.  Good call on integrating the methods.  Another class was overkill...

**Comment by jksuom** [comment]
This looks good now. Thanks!

**Pull request merged**
