### PR TITLE
Create beginnerNewtonRaphsonMethod.py

### PR DESCRIPTION
**Pull request by yesIamHasi**
Implementing Newton-Raphson method using SymPy.

### CODE REVIEW

**Comment by asmeurer** [comment]
Why does this use math functions. It should use SymPy functions.

**Comment by smichr** [comment]
What aspects of SymPy do you want the beginner to learn from this example?

**Comment by Abdullahjavednesar** [comment]
@yesIamHasi seems to be inactive for a long time, can you please respond.

**Comment by czgdp1807** [comment]
@smichr @asmeurer Do you think this PR holds a chance of getting in? I don't think we should merge this because there is already a powerful `solve` function in `SymPy` and there is no need of Newton Raphson Method in `SymPy` since, it is more of a numerical method rather than a symbolic one.

**Comment by czgdp1807** [comment]
Since no one commented, and there is no progress. I think this PR can be closed. If needed it will be reopened in the future. Thanks.

**Pull request closed without merging**
