### PR TITLE
meijerg indefinite_1 bug eliminated

### PR DESCRIPTION
**Pull request by smichr**
#### Brief description of what is fixed or changed

The loop over expr, cond overwrote the previously defined cond. A test was added to show that this will fail if it is not changed: an unevaluated integral results. The result that is there is confirmed for this case:

```python
>>> integrate((b + t)**(-a), (t),meijerg=True).subs(b,1).subs(a,2)
-t/(t + 1)**2 - 1/(t + 1)**2
>>> simplify(_)
1/(-t - 1)
>>> signsimp(_)
-1/(t + 1)
>>> integrate(((b + t)**(-a)).subs(b,1).subs(a,2), t)
-1/(t + 1)
```
#### Other comments

An evaluate option was given to `piecewise_fold`.

#### Release Notes

* functions
    * `piecewise_fold` has the option to avoid evaluation
* integrals
    * a bug in indefinite meijerg integration was fixed

### CODE REVIEW

**Comment by smichr** [comment]
@oscarbenjamin , what do you think about the evaluate option on the folding?

**Comment by oscarbenjamin** [comment]
> @oscarbenjamin , what do you think about the evaluate option on the folding?

I think it's good. I'm not sure I understand what the unpolarify does.

**Comment by smichr** [comment]
> what the unpolarify does.

I didn't write that part; I'm just the editor. :-)

**Comment by jksuom** [comment]
Typical G=functions are branched at the origin. `meijerint` tries to handle different branches internally by using "polar numbers", i.e., complex numbers with an attached argument that belongs to a not necessarily principal branch of `arg`. It is expected that the argument `z` of final result has `arg(z) <= pi` and can therefore be represented by an ordinary complex number. `unpolarify` implements that by dropping the extra argument value. So it is essentially just a cleaning operation.

**Pull request merged**
