### PR TITLE
Remove the galgebra module

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes https://github.com/sympy/sympy/issues/8365.  Galgebra will be maintained as a separate project at https://github.com/brombo/galgebra, as per the discussion on that issue.

@brombo I won't merge this until you sign off on it.

### CODE REVIEW

**Comment by brombo** [comment]
You have my permission.  Go ahead.

**Comment by asmeurer** [comment]
Great. By the way, I would recommend registering and releasing https://github.com/brombo/galgebra to PyPI so that it is easier for people to install.

**Comment by moorepants** [comment]
:disappointed:

**Comment by asmeurer** [comment]
@moorepants care to elaborate (here or on #8365)?

**Comment by moorepants** [comment]
I'm just of the opinion that we should figure out how to support Alan's work to be in SymPy. I'm worried that it will not get as much attention, traction, or testing if not. Same reason why it's nice to have the mechanics stuff in SymPy. This may be the best though, for all parties in terms of maintenance needs.

**Comment by asmeurer** [comment]
See the discussion on the issue. It's up to @brombo, since he is the primary developer. I'm also open to moving the galgebra repo to github.com/sympy so that it is an official SymPy project, but still separate from the SymPy library proper (and giving @brombo direct push access to it, as the primary maintainer).

**Comment by asmeurer** [comment]
Also the existence of this pull request does not constitute a final decision on the matter. But I do want to decide one way or another soon as this blocks on the release.

**Comment by moorepants** [comment]
I'm not blocking anything, just expression my opinion. Proceed with @brombo's blessing.

**Comment by brombo** [comment]
On 10/26/2015 06:54 PM, Aaron Meurer wrote:
>
> See the discussion on the issue. It's up to @brombo 
> <https://github.com/brombo>, since he is the primary developer. I'm 
> also open to moving the galgebra repo to github.com/sympy so that it 
> is an official SymPy project, but still separate from the SymPy 
> library proper (and giving @brombo <https://github.com/brombo> direct 
> push access to it, as the primary maintainer).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sympy/sympy/pull/10046#issuecomment-151307769>.
>
I would be interested in doing that.  Details please?

**Comment by asmeurer** [comment]
See https://help.github.com/articles/transferring-a-repository/. Apparently to do it, I have to give you admin access and then you can move it.

**Comment by isuruf** [comment]
Another way would be to transfer the repo to @asmeurer's account and then @asmeurer can transfer it to SymPy organization

**Comment by certik** [comment]
I am fine with moving it under the `sympy` organization. I am also fine with keeping either part of SymPy or separate (per @brombo's wishes).

**Comment by brombo** [comment]
On 11/25/2015 03:46 PM, Ondřej Čertík wrote:
>
> I am fine with moving it under the |sympy| organization. I am also 
> fine with keeping either part of SymPy or separate (per @brombo 
> <https://github.com/brombo>'s wishes).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sympy/sympy/pull/10046#issuecomment-159727880>.
>
Do the sympy documents have an area that lists programs/modules that use 
sympy with links.

**Comment by asmeurer** [comment]
We might have something but if we do, it's not very conspicuous. However, I'm +1 to adding something like "Projects using SymPy" to the top-level of the docs.

**Comment by moorepants** [comment]
+1 as long as we add the projects that use sympy in a prominent place. See issue #10273.

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/pull/10526. Suggestions there on how to make it more prominent are welcome.  

Also, @brombo if you want to move galgebra to the SymPy namespace just let me know. It's up to you if you want to or not. 

I plan to merge this once the tests pass.

**Comment by brombo** [comment]
On 02/04/2016 02:58 PM, Aaron Meurer wrote:
>
> See #10526 <https://github.com/sympy/sympy/pull/10526>. Suggestions 
> there on how to make it more prominent are welcome.
>
> Also, @brombo <https://github.com/brombo> if you want to move galgebra 
> to the SymPy namespace just let me know. It's up to you if you want to 
> or not.
>
> I plan to merge this once the tests pass.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sympy/sympy/pull/10046#issuecomment-180022972>.
>
What do you mean sympy namespace?

**Comment by asmeurer** [comment]
Sorry, I mean the sympy organization on GitHub.

**Comment by brombo** [comment]
On 02/04/2016 03:21 PM, Aaron Meurer wrote:
>
> Sorry, I mean the sympy organization on GitHub.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sympy/sympy/pull/10046#issuecomment-180030323>.
>
Good idea.  How would I do this?

**Comment by asmeurer** [comment]
See https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts. I have invited you to an empty admin team as described in that doc so you may have to accept that first.

**Comment by asmeurer** [comment]
Tests pass. Merging branch. Another checkbox on the 1.0 list. 

@brombo let me know if you still want to do the move.

**Pull request merged**
