### PR TITLE
Restore sympy.printing.{ccode,fcode,cxxcode} for backwards compatibility

### PR DESCRIPTION
**Pull request by asmeurer**
They were renamed in https://github.com/sympy/sympy/pull/19908, because the
submodule sharing the same name as the function was causing issues in
`__init__.py`. However, these modules also contained things that were not
included in `__init__.py` but were nonetheless part of the public API, such as
the printer classes. Consequently, renaming the imports broke the API. This
restores the submodules as shims, which are not imported by default (and hence
will not cause issues with conflicts in `__init__.py`). Note that after running

import sympy.printing.ccode
(or from sympy.printing.ccode import ...)

any subsequent

from sympy.printing import ccode
(or sympy.printing.ccode)

will result in the ccode submodule, not the function (this is why ccode.py was
renamed to c.py in the first place). Hence, this shim should be avoided and is
only provided for backwards compatibility.

I haven't deprecated these shim modules in this commit, but I may do that in a
later commit.

See also the discussion on #20234.

#### Release Notes

**(NOTE: No entry for this PR, but we will need to modify the release notes entry added from https://github.com/sympy/sympy/pull/19908 when this is merged).**

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
I also didn't address whether these "public API" classes should be added to `sympy/printing/__init__.py` in this PR. I think that's not needed to fix the compatibility issue for the release, and probably involves a bigger discussion about the handling of public vs. private names, so I'd prefer to deal with that issue in a separate PR>

**Comment by oscarbenjamin** [comment]
I had begun to prepare a PR very similar to this.

It seems that somehow the imports don't work in this PR though given the doctest failures

**Comment by asmeurer** [comment]
I guess we are running into the same problem that lead to the rename in the first place (which I described above). Once something imports `sympy.printing.ccode`, then `from sympy.printing import ccode` will import the submodule. And the doctester imports it in order to try to test it (and sympy.printing happens to be run before sympy.codegen).

**Comment by asmeurer** [comment]
I pushed a fix to make the doctester skip them. 

There's still the question here of whether these should be deprecated. Given that actually importing them can break things, I'm starting to lean towards we should deprecate them.

**Comment by oscarbenjamin** [comment]
I agree that we should deprecate them. We should also remove any place that does that kind of import from the docs and from the codebase.

**Comment by asmeurer** [comment]
They're all already removed. The import doesn't work before this PR. The only reason it was being imported in the tests is because the doctests import every module it finds.

**Comment by moorepants** [comment]
For what it's worth, my only opinion is that we likely don't need to fix this issue of functions having the same name as a module (at least not in point releases of SymPy). I think a warning in the documentation could be an adequate way to address this for now, i.e. "be careful when import ccode or simplify because...". We can then tag the issue of modules and their functions having same names as something to properly fix when we are ready for a SymPy 2.0 and are willing to make API changes.

But, if this can be deprecated somehow, then I'm +1 to it happening now. It just isn't clear to me that this can be deprecated.

**Comment by oscarbenjamin** [comment]
We can deprecate them just by adding a warning to the module when it is imported. That already happens for the old testing modules:
https://github.com/sympy/sympy/blob/c094f1bb9b9047eaa4cf98790c1df997f4f489f8/sympy/utilities/pytest.py#L1-L9

**Comment by asmeurer** [comment]
OK, I've added deprecations, and opened the deprecation removal issue #20256

**Comment by oscarbenjamin** [comment]
Looks good

**Comment by moorepants** [comment]
This might be related to these refactor too, not sure though: https://twitter.com/AkhmerovAnton/status/1319243428581023744

**Comment by oscarbenjamin** [comment]
The issue shown on twitter was fixed in 1.6 by #18245. I think the problem they are having is finding a form of the import that works with older sympy.

Their fix is to use `from sympy.core.numbers import One` but that's still not using what I would consider to be a "public" import. I would suggest to use `from sympy import S; One = type(S.One)`.

A related problem to the problems of modules and functions having the same name is the way that singleton classes and instances have the same name. Really the One class that they are importing should be renamed to OneClass or something so that the name One is only used for the instance.

**Pull request merged**
