### PR TITLE
Fix RUBI code to connect to latest MatchPy master

### PR DESCRIPTION
**Pull request by Upabjojr**
# Do not merge until a new version of MatchPy is released.

### ~~Merging this PR will probably break SymEngine's tests.~~ NO, it does not.

* integrals
  * Fix connector to new version of MatchPy.

### CODE REVIEW

**Comment by asmeurer** [comment]
Is the code broken in the new version without this?

If so, we should put this in the 1.4 branch so it gets in the release.

**Comment by Upabjojr** [comment]
> Is the code broken in the new version without this?
> 
> If so, we should put this in the 1.4 branch so it gets in the release.

Yes, as soon as MatchPy is updated to version 0.5.0 the current SymPy tests will break, because of a new way of registering objects to MatchPy.

**Comment by Upabjojr** [comment]
Furthermore this PR removes a double registration of SymPy objects (likely a bug) and also introduces single dispatching to register all SymPy objects in a single step (instead of registering every SymPy class separately).

**Comment by Upabjojr** [comment]
Furthermore, MatchPy can now be used independetly of the _sympy/integrals/rubi_ module.

**Comment by asmeurer** [comment]
OK, I've changed the PR base to `1.4`. 

There are test failures here. Can you fix them?

**Comment by asmeurer** [comment]
MatchPy 0.5.0 has been released https://github.com/HPAC/matchpy/releases.

**Comment by Upabjojr** [comment]
> There are test failures here. Can you fix them?

Did you restart them?

**Comment by Upabjojr** [comment]
This should be merged into both 1.4 and master.

**Comment by Upabjojr** [comment]
@asmeurer it looks like it's not importing the latest matchpy version.

**Comment by asmeurer** [comment]
Looks like conda-forge isn't updated https://github.com/conda-forge/matchpy-feedstock/pull/1. If we can't get that merged soon, let's just work around it by pip installing matchpy.

**Pull request merged**
