### PR TITLE
Asymmetry in roots result of quadratic expressions

### LINKED ISSUE #8813: asymmetry in roots result for quadratic expression
```python
>>> roots(Poly((z - 1)**2 - y**2, y))
{sqrt((z - 1)**2): 1, -sqrt((z - 1)**2): 1}
>>> roots(Poly(z**2 - y**2, y))
{-z: 1, z: 1}  # <--- in this case roots realizes sqrt(z**2) is +/-z but not in the former case
```

It would be preferably to have the former result be +/-(z - 1), too.

### PR DESCRIPTION
**Pull request by darkcoderrises**
Asymmetry in roots result of quadratic expressions were removed.
like roots(z^2-y^2,y) were +/-z but roots((z+1)^2-y^2,y) were  +/-(z^2-2z+1)^(0.5)

fixes #8813

### CODE REVIEW

**Comment by darkcoderrises** [comment]
@smichr Please review and suggest

**Comment by smichr** [comment]
When you are fixing an issue, please put the issue number in the opening paragraph (top of this page) as I have done for you: "fixes #8813".

OK, everything is looking good. Now the failures need to be corrected. Expressions which formerly had squares inside square roots will now fail in the tests so the tests have to be updated. You can see what failed by clicking on the "Details" link in the upper right corner of the Merge status above, then click on one of the job links (e.g. 12969.6 *but usually not other "SPLIT="1/4" links since they will likely be the same* ) to see what the failure is -- scroll to the end of the screen to see the output. It shows you where the failure occurs so you just need to go to that place and update the test. e.g. if you check the output of the wester test by putting a `print(f)` before the assertion you will see that `cos(t*w - t)` is the new result. This is just `cos(t*(w-1))` without the `abs`; this is ok because `cos` gives the same answer for +/-arg. So you just change the assertion to `assert f == cos(t*w - t)`.

**Comment by darkcoderrises** [comment]
Ok, thanks for the advice

**Comment by darkcoderrises** [comment]
f = x**2 + (2*a*e + 2*c*e)/(a - c)*x + (d - b + a*e**2 - c*e**2)/(a - c)
roots(Poly(f, x))
gives a wrong answer (2 is multiplied both in numerator and denominator)

**Comment by smichr** [comment]
Although it's not wrong -- the 2s cancel each other out -- it would be nice to get rid of common factors like that. Something like this is perhaps in order:

```
--- a/sympy/polys/polyroots.py
+++ b/sympy/polys/polyroots.py
@@ -98,7 +98,8 @@ def _simplify(expr):
             d = _simplify(d)
             B = _simplify(B)

-        D = _sqrt(d)/A
+        from sympy import factor_terms
+        D = factor_terms(_sqrt(d)/A)
         r0 = B - D
         r1 = B + D
         if a.is_negative:
```

(But do the import from the correct place at the top of the file if possible. You can find the location of factor_terms with "help(factor_terms)" after using "from sympy import *".

**Comment by smichr** [comment]
I think I just said this in another PR, but please consider it a friendly reminder...could you please change the title of the PR? It's not very useful to have an issue number that can't be clicked there, and the number itself doesn't tell the reviewer what they are going to be seeing. (And when there are lots of Issue ### titles it's hard to remember what's what.)

:eyeglasses: See the section **Writing pull request title and description** at [the wiki](https://github.com/sympy/sympy/wiki/Development-workflow)

**Comment by smichr** [comment]
:one: more test to fix: lines 1305+6 in solvers/tests/test_ode.py should read 
`sol12 = Eq(f(x), C1*exp(-6*k*x) + C2*exp(2*k*x))`

After adding this commit there will be 4 commits. Do you know how to squash commits together? A single commit with an informative title would be best :eyeglasses: See **Writing commit messages** at [the wiki](https://github.com/sympy/sympy/wiki/Development-workflow)

**Comment by darkcoderrises** [comment]
even after adding that code snippet on 1305, its coming assertion error.

**Comment by smichr** [comment]
**Before you make any changes...** if [this Travis run](https://travis-ci.org/smichr/sympy/builds/49358391) passes then you can merge the PR that I sent to you. Then squash the commits together and this will be ready to go.

**Comment by smichr** [comment]
The PR is [here](https://github.com/darkcoderrises/sympy/pull/1)

**Comment by smichr** [comment]
> even after adding that code snippet on 1305, its coming assertion error.

Hmm...see if the PR I sent passes its tests, because the change I made works for me. Also, it would be good to copy and paste your error message by starting a new line with \`\`\`, pasting the code, and putting another ``` on a blank line. That will produce something like this:
```
code
```

**Comment by smichr** [comment]
Thanks, this is in. I pushed a version locally after adding you to the list of SymPy authors and squashing a few commits together. Thanks for working through this issue and welcome to SymPy!

**Comment by darkcoderrises** [comment]
Thanks.

**Pull request closed without merging**
