### PR TITLE
[Not for merge] General form for list of args

### PR DESCRIPTION
**Pull request by Shekharrajak**
As I discussed here :
[wiki/Solveset-and-Solver-Discussion](https://github.com/sympy/sympy/wiki/Solveset-and-Solver-Discussion#simplified-general-form-for-trigonometric-solution) `solveset` need a method that can generalize `args`.
We can simplify the trigonometric solutions ,if we generalize them ,rather than sending each solution into  [solvers/solveset.py#L98](https://github.com/sympy/sympy/blob/master/sympy/solvers/solveset.py#L98).
Another thing is, if solution is `-pi/2` then convert this to positive `3*pi/2`; then generalize.This will give more known general form.
`genform` can be helpful for some other work also.

```
>>> genform(solve((sin(x)-1)*(sin(x)+1),x)[1],solve((sin(x)-1)*(sin(x)+1),x)[2])
⎧π⋅(2⋅n - 1)        ⎫
⎨─────────── | n ∊ ℕ⎬
⎩     2             ⎭

>>> solve((sin(x)-1)*(sin(x)+1),x)
⎡-π   π  3⋅π⎤
⎢───, ─, ───⎥
⎣ 2   2   2 ⎦

>>> solveset((sin(x)-1)*(sin(x)+1),x,S.Reals)
⎧        π        ⎫   ⎧        π        ⎫
⎨2⋅n⋅π - ─ | n ∊ ℤ⎬ ∪ ⎨2⋅n⋅π + ─ | n ∊ ℤ⎬
⎩        2        ⎭   ⎩        2        ⎭


```

This PR is just for discussion purpose.Any type of comment/suggestions will be appreciated.

### CODE REVIEW

**Comment by Shekharrajak** [comment]
Ping @aktech @asmeurer @hargup @jksuom

**Comment by hargup** [comment]
Consider these examples:
```
In [9]: solveset(sin(exp(x)) - 1, x, domain=S.Reals)
Out[9]: ImageSet(Lambda(_n, log((-1)**_n*pi/2 + _n*pi)), Integers())

In [10]: solve(sin(exp(x)) - 1, x)
Out[10]: [log(pi/2)]
```
```
In [11]: solve(sin(x)/x)
Out[11]: [pi]

In [12]: solveset(sin(x)/x, x, domain=S.Reals)
Out[12]: ImageSet(Lambda(_n, 2*_n*pi), Integers()) \ {0} U ImageSet(Lambda(_n, 2*_n*pi + pi), Integers()) \ {0}
```
The issues with your method is:

* You don't know which solutions `solve` will return and how many solutions `solve` will return, it might return only one solution, many solution or no solution even when there are infinitely many solutions.

* There might not exist a general solution where are points are uniformly distributed or is a union of uniformly distributed set.

**Comment by hargup** [comment]
I see two ways to simplify the output of trig solver.

* **Improve the solver**: trig solver basically works by converting the equation to a polynomial then solving the polynomial. The number of unions in the solution is same as degree of the polynomial. So you can iterate over all `sin`, `cos` and other trig function and choose the polynomial with the least degree and then find solution for it. You should also think for solutions using composition of functions.

* **Improve the Union function of imageset**: We solve the intersection problem of `imageset` integers as base set by converting it a problem of solving a Diophantine equation, it would be great if you can come up with similar techniques for union solving though I cannot assure you that a general solution exists. You can also try to formalize the union cases produced by trig solver and find a solution specifically for them, a heuristic implementation might also work well.

cc @kshitij10496

**Comment by Shekharrajak** [comment]
Thanks @hargup , for your comment.
Actually this is just initial code.In first example `solveset(sin(exp(x)) - 1, x, domain=S.Reals)` answer is 
` [log(pi/2)]` so general form will be same if we send this to `_invert_complex` then answer will be 
```
⎧             ⎛π⎞        ⎫
⎨2⋅n⋅ⅈ⋅π + log⎜─⎟ | n ∊ ℤ⎬
⎩             ⎝2⎠        ⎭
```
which is same as  ` log((-1)**_n*pi/2 + _n*pi))`.
If there is more than 1 solution then we can make general form pairwise, this will reduce number of solution exactly half.
And solveset is able to remove any interval if it is not in the solution.
```
>>> solveset((cos(x) - S(1)/2)*(cos(x) +1)/(cos(x)-1) > 0,x,S.Reals)
⎛⎛π   ⎞                  ⎞   ⎛⎛   5⋅π⎞                  ⎞
⎜⎜─, π⎟ \ {2⋅n⋅π | n ∊ ℤ}⎟ ∪ ⎜⎜π, ───⎟ \ {2⋅n⋅π | n ∊ ℤ}⎟
⎝⎝3   ⎠                  ⎠   ⎝⎝    3 ⎠                  ⎠

```

>choose the polynomial with the least degree and then find solution for it. You should also think for >solutions using composition of functions.

I didn't understand this line, please give an example if possible.

>intersection problem of imageset integers as base set by converting it a problem of solving a >Diophantine equation

I didn't knew this before,I still didn't find where this is happening.

**Comment by hargup** [comment]
(Apologies for the late reply)

> In first example `solveset(sin(exp(x)) - 1, x, domain=S.Reals)` answer is 
> ` [log(pi/2)]` so general form will be same if we send this to `_invert_complex` then answer will be 
> ```
> ⎧             ⎛π⎞        ⎫
> ⎨2⋅n⋅ⅈ⋅π + log⎜─⎟ | n ∊ ℤ⎬
> ⎩             ⎝2⎠        ⎭
> ```
> which is same as  ` log((-1)**_n*pi/2 + _n*pi))`.

How do you decided that the period should be 2 pi?


> please give an example if possible.

For example if I have to solve `sin(x) = 0`, the current method is to convert
the equation in `exp` which is `I*(exp(I*x) - exp(-I*x))/2` which is a second
degree rational function in `exp(I*x)`, Second degree means we will have two
solutions of the function, which will correspond to a union of two imagesets
derived from the solution of `exp(-I*x) = y`. The equation `sin(x) = 0` is also
a one degree polynomial in `sin` which means if we solve it in terms of `sin`
we will get only one imageset which is "simpler". Similarly for all trig
equations you convert the equation to different function (exp, sin, cos, sec,
tan etc.) and choose the one which leads to the function with least degree
because that will give the minimum number of imagesets.

You need to a little careful while converting the equations to tan, cot, sec
and cosec because they have singularities. A way to deal with issue can be
solving the equations in extended real system.

**Comment by kshitij10496** [comment]
> iterate over all sin, cos and other trig function and choose the polynomial with the least degree and then find solution for it

This sounds like a nice idea.
However, I have a few concerns regarding this:

- What if the solutions returned by a the least degree polynomial (of trigonometric function) can be further simplified ?
For example: 
If all the polynomials have the same degree `n` (greater than 1), the result will be a Union of `n` different `imageset` objects. Given our inability to handle such unions, how can we be sure that the simplest output possible is being returned ?
I think there is a possibility that this union can further be simplified, isn't it so ?

- Wouldn't we need to hardcode the solutions of the trigonometric equations into the system (the way we have for `exp`) ?
 
- I think we need to have a handler for union of `imageset`  objects, irrespective of the way we simplify the output of trigonometric equations.
I think the system should understand that mathematically 
```{2⋅n⋅π | n ∊ ℤ} ∪ {π⋅(2⋅n + 1) | n ∊ ℤ} = {n⋅π | n ∊ ℤ} ```. 
What are your thoughts on this ?

**Comment by Shekharrajak** [comment]
@hargup , thanks again.

> For example if I have to solve sin(x) = 0, the current method is to convert
> the equation in exp which is I*(exp(I*x) - exp(-I*x))/2 which is a second
> degree rational function in exp(I*x), Second degree means we will have two
> solutions of the function, which will correspond to a union of two imagesets
> derived from the solution of exp(-I*x) = y. The equation sin(x) = 0 is also
> a one degree polynomial in sin which means if we solve it in terms of sin
> we will get only one imageset which is "simpler". Similarly for all trig
> equations you convert the equation to different function (exp, sin, cos, sec,
> tan etc.) and choose the one which leads to the function with least degree
> because that will give the minimum number of imagesets.

When I sent this PR https://github.com/sympy/sympy/pull/10482 then I didn't think much, but when I was trying to solve other bugs then I realize this problem ( In https://github.com/sympy/sympy/pull/10552 ). 
As they have conflicts now because `solveset_real` and `solveset_complex` is using `_solveset` ( this changes solved the some of the bugs, that I tried in these PR.).
after the almost 45 days, I am rewriting these PR fixing XFAIL test-cases https://github.com/sympy/sympy/pull/10733
which fixes above issue [testcase passed for all trig function](https://github.com/sympy/sympy/pull/10733/files#diff-85baa04bbf4e1dfd9128782738e45424R727)

**What I changed in solve_trig**


[L395](https://github.com/sympy/sympy/pull/10733/files#diff-eec0422923e8f100745c015cd8fdd6cfR395) `sin(x) = -I*(exp(I*x) - exp(-I*x))/2`

[L556](https://github.com/sympy/sympy/pull/10733/files#diff-eec0422923e8f100745c015cd8fdd6cfR556) `(exp(2*I*x) - 1)*exp(-I*x)`

[L603](https://github.com/sympy/sympy/pull/10733/files#diff-eec0422923e8f100745c015cd8fdd6cfR603) ` m= (exp(2*I*x) - 1, exp(-I*x))`
when `m= exp(2*I*x) - 1` , then `lhs =x` ,` rhs = ImageSet(Lambda(_n, _n*pi), Integers())`
 
next time `m=exp(-I*x)`  return `(x, EmptySet())`

[L587](https://github.com/sympy/sympy/pull/10733/files#diff-eec0422923e8f100745c015cd8fdd6cfR587) So overall solution is :  `ImageSet(Lambda(_n, _n*pi), Integers()) `

In master branch [solve_trig](https://github.com/sympy/sympy/pull/10733/files#diff-eec0422923e8f100745c015cd8fdd6cfL373)
g: -_y**2*I + I because of this: 
```
y = Dummy('y')                                                                           
   374     g, h = g.expand(), h.expand()                                                            
   375     g, h = g.subs(exp(I*symbol), y), h.subs(exp(I*symbol), y)                                
   376     if g.has(symbol) or h.has(symbol):                                                       
   377         return ConditionSet(symbol, Eq(f, 0), S.Reals)                                 
   378                                                                                        
   379     solns = solveset_complex(g, y) - solveset_complex(h, y) 
```
similarly for all other trig function.
Thanks for sharing this point, it will be helpful in other cases.

>How do you decided that the period should be 2 pi?

For all we add
 [`imageset(Lambda(n,I(2*n*pi+arg(g_y))+log(Abs(g_y))),S.Integers)`](https://github.com/sympy/sympy/blob/master/sympy/solvers/solveset.py#L229)

then further `_invert_complex(f.args[0], exp_invs, symbol)` this simplifies the result, I think. 

>  intersection problem of imageset integers as base set by converting it a problem of solving a Diophantine equation,

If possible please explain a little with example.

**Comment by hargup** [comment]
> > The number of unions in the solution is same as degree of the polynomial
>
> I am not so sure about this.

Nice catch. I should have said "less than or equal to". Imaginary solutions are
treated no different from real solution, the invert function is called upon it
and we take the union of the solution sets returned.

> - Wouldn't we need to hardcode the solutions of the trigonometric equations into the system (the way we have for `exp`) ?

I don't see an issue with it.

> - I think we need to have a handler for union of `imageset`  objects,
>   irrespective of the way we simplify the output of trigonometric equations.

Yes, we need to have a union evaluator.


> - What if the solutions returned by a the least degree polynomial (of trigonometric function) can be further simplified ?
> For example:
>
> If all the polynomials have the same degree `n` (greater than 1), the result
> will be a Union of `n` different `imageset` objects. Given our inability to
> handle such unions, how can we be sure that the simplest output possible is
> being returned ? I think there is a possibility that this union can further be
> simplified, isn't it so ?

So probably a better method would be to count the number of unions in the final
solution given by each method and choose the one which gives the least number
of unions. This is pretty much in the line of our idea about the search based
solver. We have these different method to solve the equation, and we have an
objective function which in this case is the number of unions. The problem at
hand is to find a which minimizes the objective function. This case the number
of methods is small, and we can simply iterate over them. For a more general
solver, a method is a series of techniques that you apply to sub parts of a
problem, sequentially. A more general solver the number of methods can be
infinitely large, which consists of applying a finite set of techniques
sequentially.

**Comment by hargup** [comment]
>>How do you decided that the period should be 2 pi?
>
>For all we add
> [`imageset(Lambda(n,I(2*n*pi+arg(g_y))+log(Abs(g_y))),S.Integers)`](https://github.com/sympy/sympy/blob/master/sympy/solvers/solveset.py#L229)

As far as I have understood your method, trying to fit a few point solutions
given by `solve` into a `{2*pi*n + b for n in Integers}` where `a` and `b`
are variables. What is the mathematical justification that the period will be
`2*pi` and the solutions will be linearly distributed over the number line?

> >  intersection problem of imageset integers as base set by converting it a problem of solving a Diophantine equation,
>
> If possible please explain a little with example.

I recommend reading the [code of `imageset`](https://github.com/sympy/sympy/blob/master/sympy/sets/fancysets.py#L315) that should be self explanatory, if
it does not turn to be the case please ask questions.

For everything said about `solve_trig` in the rest of the comment, I didn't understand what are you proposing, I would appreciate if you paraphrase it in a more structured manner perhaps with examplese.

**Comment by Shekharrajak** [comment]
Thanks @hargup  for your comment.

> As far as I have understood your method, trying to fit a few point solutions
> given by solve into a {2*pi*n + b for n in Integers} where a and b
> are variables. What is the mathematical justification that the period will be
> 2*pi and the solutions will be linearly distributed over the number line?

As I have written some examples/doctest [ above the method](https://github.com/sympy/sympy/pull/10713/files#diff-ebb4c8f41ab547119d47000b901f6f8cR22)
I made this for general case, if you pass any two parameter( that can be expressed as linear function of `n`) then it returns the function that should represent all of the terms.

**Comment by asmeurer** [comment]
I'm a little confused by this PR? Is "general form" a well-defined mathematical term? When I Google it I see references to ["general linear form"](https://www.mathsisfun.com/algebra/line-equation-general-form.html). The docstring doesn't really explain what it does. 

The output of your example `genform(1/6,1/2)` gives (after simplifying) `n/3 - 1/6` (for n in Naturals). The first few terms of this are 1/6, 1/2, 5/6, 7/6, 3/2, 11/6, .... In other words, it just means that you want to find the line that passes through (1, 1/6), (2, 1/2) (if that's all you want, just use the `interpolate` function). 

But it's unclear to me what more than one argument should give. The example

```
>>> genform(pi/6,pi/2,pi)
ImageSet(Lambda(_n, pi*(2*_n - 1)/6), Naturals())
```

also confuses me. `pi` is not an element of the resulting image set (unsurprisingly, since the line that passes through (1, pi/6), (2, pi/2) doesn't pass through pi at an integer value).

**Comment by Shekharrajak** [comment]
@asmeurer , thanks for telling me about `interpolate` method.
`Interpolate` method can be used for getting simplified solution for trigonometric equation easily.To get simplest form we first need to sort the solution (after putting n=0), then pass that to `interpolate` method (negative and positive values separately).

I mistakenly wrote S.`Naturals` instead of ** `S.Integers`** .

Few examples I tried : 
```
>>> factor(interpolate([-pi/6 , -pi/3 ,-pi/2 , -2*pi/3 , -5*pi/6], n))
-π⋅n 
─────
  6  
>>> factor(interpolate([pi/6 , pi/3 ,pi/2 , 2*pi/3 , 5*pi/6], n))
π⋅n
───
 6 
>>> factor(interpolate([pi/2 , - pi/2], n))
-π⋅(2⋅n - 3) 
─────────────
      2      
>>> factor(interpolate([pi/2 , 3*pi/2], n))
π⋅(2⋅n - 1)
───────────
     2     

```
I did the similar thing for just `solve_trig` method here : [# 10898](https://github.com/sympy/sympy/pull/10898/files#diff-eec0422923e8f100745c015cd8fdd6cfR410)
but I think after sorting just need to use `interpolate` method.
I would have added this idea in my GSoC proposal, if I had knew it before.

**Pull request closed without merging**
