### PR TITLE
Added PyPI installation procedure in README

### LINKED ISSUE #7763: Recommended installation path should be with pip
The README file specifies that sympy should be installed using `setup.py`.
Is there something that prevents sympy to be installed using pip?

### PR DESCRIPTION
**Pull request by mijo2**
#### References to other Issues or PRs

Fixes #7763 

#### Brief description of what is fixed or changed

--> Added details about the installation procedure using PyPI

#### Release Notes

* other
  * Updated README to include details about how to install SymPy using PyPI

### CODE REVIEW

**Comment by asmeurer** [comment]
This looks good. I think we should remove the `sudo pip install` section. That's usually not a good idea for people to do unless they know what they are doing.

**Comment by mijo2** [comment]
@asmeurer you mean the ```sudo python setup.py install``` right?

**Comment by asmeurer** [comment]
Yes

**Comment by mijo2** [comment]
@asmeurer I have removed the ```sudo``` part.

**Pull request merged**
