### PR TITLE
Updating autolev variable naming

### LINKED ISSUE #15187: Improve variable naming in autolev parser
Here is an example output from #15165:

```python
import sympy.physics.mechanics as me
import sympy as sm
import math as m
import numpy as np

frame_c = me.ReferenceFrame('c')
frame_d = me.ReferenceFrame('d')
frame_f = me.ReferenceFrame('f')
fd, dc = me.dynamicsymbols('fd dc')
fdd, dcd = me.dynamicsymbols('fd dc', 1)
fdd2, dcd2 = me.dynamicsymbols('fd dc', 2)
r, l = sm.symbols('r l', real=True)
point_o = me.Point('o')
point_e = me.Point('e')
frame_d.orient(frame_f, 'Axis', [fd, frame_f.x])
frame_c.orient(frame_d, 'Axis', [dc, frame_d.y])
frame_c.set_ang_vel(frame_f, (frame_c.ang_vel_in(frame_f)).express(frame_f))
point_e.set_pos(point_o, r*frame_d.y-l*frame_c.x)
point_e.set_pos(point_o, (point_e.pos_from(point_o)).express(frame_d))
point_e.set_vel(frame_f, ((point_e.pos_from(point_o)).dt(frame_f)).express(frame_d))
point_e.set_acc(frame_f, ((point_e.vel(frame_f)).dt(frame_f)).express(frame_d))
```

Name clashes will vary likely happen with the primary import names: `me, sm, np`. There should at least be changed to `_me, _sm, _np` and even better there should be a check to ensure the Autolev code doesn't contain and reserved words and the properly handles them by adding underscores or some kind of pre/post fix. For example in autolev you might declare `MASS ME` as the mass of body E. This will clash with the output code `me`.

The automatic declaration of the time derivatives is currently:

```python
fd, dc = me.dynamicsymbols('fd dc')
fdd, dcd = me.dynamicsymbols('fd dc', 1)
fdd2, dcd2 = me.dynamicsymbols('fd dc', 2)
```

A simple improvement would be:

```python
fd, dc = me.dynamicsymbols('fd dc')
fd_d, dc_d = me.dynamicsymbols('fd dc', 1)
fd_dd, dc_dd = me.dynamicsymbols('fd dc', 2)
```

Where `_d, _dd, _ddd`, etc is dot, double dot, triple dot, etc.

### PR DESCRIPTION
**Pull request by abbyjng**
#### References to other Issues or PRs

Fixes #15187 

#### Brief description of what is fixed or changed

- `me`, `sm`, and `np` imports are renamed to `_me`, `_sm`, and `_np` to prevent these import names from clashing with user-created variables.
- naming of automatic declaration of time derivatives is updated from `var`, `vard`, `vard2` to `var`, `var_d`, `var_dd` respectively, given `var` is the name of the expected time derivative variable.
- spaces are added around `=` when dealing with vec variables, in compliance with PEP8 guidelines.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by abbyjng** [comment]
This PR is a follow up to [#15208](https://github.com/sympy/sympy/pull/15208), which was unfinished and marked as "Please take over". I created a new PR instead, as I could not figure out how to actively take over that PR. I hope this isn't an issue; please let me know if I need to close this in favor of taking over that one instead.

**Comment by naveensaigit** [comment]
Release notes usually consist of important additions to the library. The 2nd point is trivial and can be removed from the release notes.

**Comment by sidhu1012** [comment]
> Release notes usually consist of important additions to the library. The 2nd point is trivial and can be removed from the release notes.

These changes doesn't need release notes as of now.

**Comment by abbyjng** [comment]
> > Release notes usually consist of important additions to the library. The 2nd point is trivial and can be removed from the release notes.
> 
> These changes doesn't need release notes as of now.

Thank you for the correction! I have edited my PR to reflect this.

**Comment by smichr** [comment]
This looks like what @moorepants was suggesting. Thanks, this is in.

**Pull request merged**
