### PR TITLE
Issue #8815: Comparing strings rather than mpf tuples.

### PR DESCRIPTION
**Pull request by mihir-w**
[#8815](https://github.com/sympy/sympy/issues/8815)
@smichr please review.

### CODE REVIEW

**Comment by smichr** [comment]
I'll have to think about this a bit.

**Comment by smichr** [comment]
What about something like this:

```
>>> a=sqrt(2).n(2)
>>> b=S(1.41).n(3)
>>> from mpmath.libmp.libmpf import prec_to_dps as d
>>> sf = d(min(a._prec, b._prec)); abs(a-b).n(sf)*10**sf <= 1
True
>>> b=S(1.46).n(3)
>>> sf = d(min(a._prec, b._prec)); abs(a-b).n(sf)*10**sf <= 1
False
```

**Comment by mihir-w** [comment]
Won't work in all cases.
```
>>> a = Float(1.4).n(2)
>>> b = Float(1.40002,6)
>>> abs(a-b).n(2)*10**2 <= 1
True
```

I had thought about using minimum precision, but could'nt figure a way around such cases.

**Comment by mihir-w** [comment]
Consider these two tests present in `test_numbers.py` and `test_arit.py` respectively,

In `test_numbers.py`, line 1399,
```
assert Float(0.12, 3) != Float(0.12, 4)
```
Here the numbers are not equal, because their precision values are different.

In `test_arit.py`, line 1480,
```
assert Mod(1.3, 1) == Float._new(Float(0.3, 51))
```
Here if we see the precision,
```
>>> prec_to_dps( Mod(1.3, 1)._prec )
15
>>> prec_to_dps( Float._new(Float(0.3, 51))._prec )
14
```
Here the numbers are supposed to be equal, despite having different precision values.

How can both tests be true at the same time ? IMHO, One type of tests have to go.

**Comment by smichr** [comment]
1. Float(.1, 3) != Float(.1, 4)  # OK, they aren't the same number

1. assert Mod(1.3, 1) == Float._new(Float(.3)._mpf_, 51))

That was an attempt to do what this PR is hopefully going to fix. We need a simple way to say that Mod(1.3,1) == .3. They aren't, but we want to say that there is no significant difference between the two.

```python
>>> Mod(1.3,1)
0.300000000000000
>>> _._mpf_
(0, 1351079888211149L, -52, 51)
>>> S(.3)._mpf_
(0, 5404319552844595L, -54, 53)
```

We already have a `comp` function in sympy/utilities/randtest

```python
def comp(z1, z2, tol):
    """Return a bool indicating whether the error between z1 and z2 is <= tol.

    If z2 is non-zero and ``|z1| > 1`` the error is normalized by ``|z1|``, so
    if you want the absolute error, call this as ``comp(z1 - z2, 0, tol)``.
    """
    if not z1:
        z1, z2 = z2, z1
    if not z1:
        return True
    diff = abs(z1 - z2)
    az1 = abs(z1)
    if z2 and az1 > 1:
        return diff/az1 <= tol
    else:
        return diff <= tol
```

Maybe we just need to set tol=None and in that case use the min prec

```python
...
if tol is None:
    from mpmath.libmp.libmpf import prec_to_dps as d
    a = sympify(z1)
    b = sympify(z2)
    sf = d(min(a._prec, b._prec))
    return abs(a-b).n(sf)*10**sf <= 1
```

So then that second test would be `assert comp(Mod(1.3, 1), .3)`. I'll make a PR with this proposal.

> What's going wrong ?

Perhaps a difference in sympy versions? live.sympy.org is not up to date. I also recall something about PY2/3 changes related to long/int, too, but am not sure.

**Comment by smichr** [comment]
see #8939

**Comment by mihir-w** [comment]
> They aren't, but we want to say that there is no significant difference between the two.

Makes sense.

So in future, while testing for such cases we will use `comp` function instead of the float `__eq__`. One can add some docstring in the`__eq__` function advising user to use `comp` function in such cases. 

Then in my opinion, the string comparison in `__eq__` used here, remains a good method to compare other cases.
Correct ?

**Pull request closed without merging**
