### PR TITLE
add cdf for maxwell and rayleigh distributions

### LINKED ISSUE #16446: Add CDF to maxwell distribution
Add function to find CDF of Maxwell distribution using reference: [wiki](https://en.wikipedia.org/wiki/Maxwell%E2%80%93Boltzmann_distribution)

### LINKED ISSUE #16448: Add CDF for Rayleigh distribution
Add function to calculate CDF of Rayleigh distribution, taking reference from: [wiki](https://en.wikipedia.org/wiki/Rayleigh_distribution)

### PR DESCRIPTION
**Pull request by ritesh99rakesh**
#### References to other Issues or PRs
Fixes #16448 
Fixes #16446 

#### Brief description of what is fixed or changed
Added function to caluculate CDF of Rayleigh distribution using [wiki](https://en.wikipedia.org/wiki/Rayleigh_distribution)
and added test for the same.

#### Release Notes

stats:
* added cdf for maxwell, rayleigh distributions, cauchy and gomertz distributions

### CODE REVIEW

**Comment by oscargus** [comment]
This includes a commit from #16447 as well. Probably better to just have a single PR with both (and no issues) in the future.

**Comment by oscargus** [comment]
It would probably make sense to add a test that `cdf(X)(x).diff(x) == density(X)(x)` (or whatever the exact formulation is).

**Comment by ritesh99rakesh** [comment]
@oscargus sorry for it. I will keep that in mind next time. I have closed #16447. Pleae review. Regards.

**Comment by oscarbenjamin** [comment]
Looks good. Thanks!

**Comment by sidhantnagpal** [comment]
Should #16446 be closed as well?

Note that, you need to repeat "Fixes" before each issue in the description to use the auto-close format.

**Comment by jksuom** [comment]
There could also have been a release note entry. (That can be added manually.)

**Pull request merged**
