### PR TITLE
Basic: docstring: not all objects in SymPy are Basic

### PR DESCRIPTION
**Pull request by cbm755**
MutableDenseMatrix and MutableSparseMatrix are not for example.

NO ENTRY

### CODE REVIEW

**Comment by cbm755** [comment]
How about now wording?  Also, listed it under Notes to de-emphasize a bit.

**Comment by cbm755** [comment]
Test failure is timeout: this is just documentation.

**Comment by siefkenj** [comment]
+1 though I might change it to use `ImmutableMatrix(...).as_mutable()` to create the matrix in the example since eventually the default matrix class should be changed to `ImmitableMatrix`

**Comment by cbm755** [comment]
Thank you @siefkenj, I revised it in a similar way.

@asmeurer do you think we should merge this?

**Comment by siefkenj** [comment]
Do we have a verdict on this?

**Comment by czgdp1807** [comment]
@cbm755 @asmeurer Please provide updates on this?

**Comment by czgdp1807** [comment]
@certik @asmeurer Can this be merged?

**Comment by smichr** [comment]
It is useful in pointing out a feature with which developers should be aware. If this is ever not the case the documentation will note the change. Until then it provides a clear example and clarification.

**Pull request merged**
