### PR TITLE
Printing: Change latex printer to print re(x) with parentheses

### LINKED ISSUE #12649: latex(re(x)) should use parentheses
latex(re(x)) returns \Re{x}, but it would be better to use \Re{\left(x\right)}. 

I also don't really like \Re (would prefer \mathrm{Re}), but that's a separate issue.

### PR DESCRIPTION
**Pull request by hanq08**
latex(re(x)) returns \Re{\left(x\right)}

Change latex printer to print re(x) with parentheses

Fixes #12649

### CODE REVIEW

**Comment by jksuom** [comment]
This will add a pair of extra parentheses in some cases.
```
In [15]: latex(re(x/y))
Out[15]: '\\Re{\\left(\\left(\\frac{x}{y}\\right)\\right)}'
```
The braces { } are probably not necessary in connection with the parentheses.

**Comment by hanq08** [comment]
Can I just change the precedence from func to atom? 
`tex = r"\Re{%s}" % self.parenthesize(expr.args[0], PRECEDENCE['Atom'])`

**Comment by asmeurer** [comment]
Yes, I believe you need to modify the precedence.

**Comment by smichr** [comment]
Thanks. It's in.

**Pull request merged**
