### PR TITLE
Added test for limit issue #14503

### PR DESCRIPTION
**Pull request by slacker404**
I have added a new test for a limit that sympy is unable to calculate.
Also, see  #14503

### CODE REVIEW

**Comment by Abdullahjavednesar** [comment]
@slacker404 your first comment should rather link the issue you fix which helps the reviewer to close both, the PR and issue at once.

**Comment by slacker404** [comment]
Is possible that someone explain why all these commits keep failing. I tried to figure out but I did not manage to

**Comment by Abdullahjavednesar** [comment]
@slacker404, you should rather discuss it in gitter.

**Review by maurogaravello — COMMENTED** [review]
Put 

@XFAIL

line before def test....

**Comment by czgdp1807** [comment]
@slacker404 Please make the update as suggested in [this comment](https://github.com/sympy/sympy/pull/14602#pullrequestreview-114294107). This can be a good addition if you complete it. Thanks.

**Comment by czgdp1807** [comment]
Is there a need to add an XFAIL test? May be, a fix would be better. Thanks for the contributions.

**Comment by czgdp1807** [comment]
Closing in reference to https://github.com/sympy/sympy/issues/14503#issuecomment-568665062

**Pull request closed without merging**
