### PR TITLE
Improve consistency between new and old assumptions.

### PR DESCRIPTION
**Pull request by debugger22**
This improves consistency between new and old assumptions.
- Replace `Q.bounded` with `Q.finite`
- Replace `Q.infinity` with `Q.infinite`
- Add a fact `Implies(Q.infinite, ~Q.finite)`

Inspired from https://github.com/skirpichev/omg/commit/ec2ad227553f68d09776949f1d2fffce736a2170

### CODE REVIEW

**Comment by debugger22** [comment]
Old assumptions gives a deprecation warning, is that necessary here too?

**Comment by asmeurer** [comment]
What are all the things that will have to be deprecated as part of the assumptions transition?  If there are a lot, or some that can't be deprecated, we may have to decide to just break compatibility. 

For this, it seems that deprecating is not difficult, so let's do it.

**Comment by skirpichev** [comment]
@debugger22, probably you could preserve commit ownership, if you use them?  After all, there will be less merge conflicts for your (or mine ;)) future inspirations.

Also, it's less logical that ask_generate.py was updated only at the end.

**Comment by debugger22** [comment]
I just did a git grep with sed. I'll take care of the authorship in future.
:)
On Apr 1, 2015 10:40 PM, "Sergey B Kirpichev" <notifications@github.com>
wrote:

@debugger22 <https://github.com/debugger22>, probably you could preserve
commit ownership, if you use them? After all, there will be less merge
conflicts for your (or mine ;)) future inspirations.

Also, it's less logical that ask_generate.py was updated only at the end.

—
Reply to this email directly or view it on GitHub
<https://github.com/sympy/sympy/pull/9228#issuecomment-88555437>.

**Comment by skirpichev** [comment]
> I just did a git grep with sed.

I doubt that your commits are just grep+sed, except m.b. for first two.

**Comment by debugger22** [comment]
> I doubt that your commits are just grep+sed, except m.b. for first two.

I meant that I didn't move any commit. Everything was done manually.

> Also, it's less logical that ask_generate.py was updated only at the end.

I figured that out when tests started to fail.

**Comment by debugger22** [comment]
> What are all the things that will have to be deprecated as part of the assumptions transition?

I can't comment on that now. We should keep that minimum, though.

> For this, it seems that deprecating is not difficult, so let's do it.

I'll add it.

**Comment by debugger22** [comment]
@asmeurer This seems to work but fails with the warning.

It gives warning at the import time and fails to do so when actually needed.

```
In [1]: from sympy import Q
sympy/utilities/decorator.py:207: SymPyDeprecationWarning: 

infinity has been deprecated since SymPy 0.7.7. Use infinite instead.
See https://github.com/sympy/sympy/issues/9426 for more info.

  return self.fget.__get__(obj, klass)()
sympy/utilities/decorator.py:207: SymPyDeprecationWarning: 

bounded has been deprecated since SymPy 0.7.7. Use finite instead. See
https://github.com/sympy/sympy/issues/9425 for more info.

  return self.fget.__get__(obj, klass)()

In [2]: Q.bounded
Out[2]: Q.finite
```

**Comment by asmeurer** [comment]
Where is the warning raised from at import time? Raise an exception in the function to get a traceback.

**Comment by debugger22** [comment]
Nice trick! It occurs when computing `known_facts_keys`.

```
/home/debugger22/workspace/sympy/sympy/assumptions/ask.py in <module>()
    340 
    341 known_facts_keys = [getattr(Q, attr) for attr in Q.__dict__
--> 342                     if not attr.startswith('__')]
    343 known_facts = And(
    344     Implies(Q.infinite, ~Q.finite),
```

**Comment by debugger22** [comment]
This patch works fine.

```
known_facts_keys = [getattr(Q, attr) for attr in Q.__dict__
                    if not (attr.startswith('__') or isinstance(attr, object))]
```

**Comment by debugger22** [comment]
Previously, I was type checking keys. It was wrong. I hope it works now.

**Comment by debugger22** [comment]
@asmeurer does this look good?

**Comment by asmeurer** [comment]
I don't know why you didn't just make Q an instance and use regular properties, but it's fine.

**Pull request merged**
