### PR TITLE
series: Added tests for limits.py for sine of oo

### LINKED ISSUE #7535: Incorrect limit result
Here's one I've stumbled upon:

http://www.sympygamma.com/input/?i=limit+%28tan%28x%29%2Fsin%28tan%28x%29%29+%2Cx%2Cpi%2F2%29

It says that the limit is ∞, but it's incorrect. It reaches -∞ too: sin goes crazy because tan goes to +∞/-∞.

I hope that this is the correct place to report this.

Thank you and best regards.

### PR DESCRIPTION
**Pull request by evatiwari**
Tests for the cases where the limit of sin(x) where x tends to infinity have been
added to the file series/tests/test_limits.py.

#### References to other Issues or PRs

Fixes #7535 

#### Brief description of what is fixed or changed
Tests added for the test cases given in https://github.com/sympy/sympy/issues/7535#issuecomment-637485310

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
The tests have failed because there is no newline at the end of the file.

**Comment by oscarbenjamin** [comment]
You don't need to close the PR. If you make another commit that adds the newline and push it to the same branch then the PR will update.

**Comment by evatiwari** [comment]
My apologies, I forgot.

**Comment by evatiwari** [comment]
@oscarbenjamin I have added a new line in my latest commit, but on running ```python bin/test sympy/testing/tests/test_code_quality.py``` , I'm still getting the following error.
```
AssertionError: File ends with more than 1 newline: d:\documents\sympy\sympy\series\tests\test_limits.py, line 909
```
Is there a way I can fix this?

**Comment by evatiwari** [comment]
@oscarbenjamin when I test locally using ```python bin/test sympy/testing/tests/test_code_quality.py``` after adding one new line, the test passes. But when I make a commit here, the new line is not visible on github and the checks above fail.  When I add another new line, it does not pass the tests locally but here, the Travis CI build is pending. Also, only one new line shows up.

**Comment by sidhu1012** [comment]
Currently it's showing one blank line in end 
Travis build will start running when it's finished with previous PR.

**Comment by evatiwari** [comment]
@sidhu1012 that is because I had added two lines in my local build. test_code_quality.py gives me an error because of that.

**Comment by czgdp1807** [comment]
The current tests seem to pass. Re-starting the Travis CI build. If it passes, will merge tomorrow if no objections raised.

**Comment by evatiwari** [comment]
@czgdp1807  the Travis CI build is complete, I hope it's good enough.

**Pull request merged**
