### PR TITLE
Update the docstring of Number class to include Integer

### PR DESCRIPTION
**Pull request by normalhuman**
The current docstring reflects the time when there was no Integer class and Rational(1) was used to represent 1. Updated to show both Integer and Rational in the example.

### Update

Edited the docstring of Number further. Wrote a docstring for Integer.

### CODE REVIEW

**Comment by asmeurer** [comment]
I don't understand the point of the text at the end of the docstring. It's very misleading, because `Rational(2, 3) + sqrt(Integer(5))` isn't actually an instance of `Number`. In that sense, the first sentence of the docstring is wrong. Really it only represents atomic numbers.

**Comment by asmeurer** [comment]
The change itself here looks fine, though, if you don't want to make additional improvements to the docstring.

**Comment by normalhuman** [comment]
I'll work on this some more, because I now noticed Integer has no docstring at all, while Rational still claims to represent integers.

**Comment by asmeurer** [comment]
Technically Integer is a subclass of Rational. 

It actually might be useful to have a class diagram somewhere (the docstring of Number seems as good a place as any).

**Comment by smichr** [comment]
> I'll work on this some more

Thanks. Something to consider is to just make the example simple, e.g. pointing out that 2/3 creates a python float while Rational(2, 8) creates a SymPy rational...and automatically takes care of reduction to simplest form.

Something I don't like about the current legacy docstring is that it encourages an unecessary paranoia for creating expressions like `sqrt(Integer(5))`...`sqrt` already converts its args so `sqrt(5)` is fine, while `sqrt(2/3)` would need to be entered as...well, you know.

**Comment by smichr** [comment]
+1

**Pull request merged**
