### PR TITLE
Improve testing on Windows

### PR DESCRIPTION
**Pull request by ylemkimon**
- Fixed incorrect architecture detection on 64-bit Windows. [(SO)](https://stackoverflow.com/q/1405913/1448742)
- Skip failing tests on Windows. Fixes partially #13168 until finding out the cause and fixing it.
- Added [AppVeyor](https://ci.appveyor.com/project/ylemkimon/sympy) configuration and script for testing on Windows platform and 32-bit Python. (And non-NumPy environment #13148)

### CODE REVIEW

**Comment by smichr** [comment]
This sort of testing fu is beyond my working toolset. If anybody else wants to review, please feel free, otherwise I go with the principle that "a fix without breakage is fine" and will commit in 2 days.

ping @asmeurer

**Comment by asmeurer** [comment]
I don't like the skip lines. We should figure out the cause of the failures. If we just skip the tests, we will forget about it and never fix them.

**Comment by asmeurer** [comment]
And also we need to actually enable AppVeyor. I hope the AppVeyor queue isn't worse than Travis.

**Comment by ylemkimon** [comment]
As #13168 is caused by NumPy not being installed and a new issue #13326 has been opened and a fix has been PRed(#13346), I'll close this PR.

**Pull request closed without merging**
