### PR TITLE
This change helps in handling unicode text better

### LINKED ISSUE #16087: `subs` doesn't substitute symbols with unicode text in python 2
In python 2.7

```
print(sympy.Symbol(u"s").subs({u"s": 1}))
```

should output

```
1
```

but instead outputs

```
s
```

(If you use the dictionary `{"s": 1"}` then it does work, regardless of whether the symbol has a unicode text or not. If you use the dictionary `{u"s": 1"}` then it fails regardless of the symbol text type.)

### PR DESCRIPTION
**Pull request by supreet11agrawal**
#### References to other Issues or PRs

Fixes #16087 

#### Brief description of what is fixed or changed
In python 2.7, earlier `print(sympy.Symbol(u"s").subs({u"s": 1}))` gave the output as `s` but should give `1`. Now fixed. This was because type of s[0] being generated was unicode

#### Release Notes

* core
  * Improvised Unicode text handling by subs

### CODE REVIEW

**Comment by jksuom** [comment]
There should probably be a test.

**Comment by oscargus** [comment]
Good one! I agree that there should be a test, but otherwise makes sense.

There are a few more cases of `is str` left in the code that probably should be replaced as well, feel free to have a look at it.
```
sympy/core/basic.py:944:            if type(s[0]) is str:
sympy/core/numbers.py:53:    if type(z2) is str:
sympy/core/numbers.py:63:            if type(z2) is str and getattr(z1, 'is_Number', False):
sympy/core/numbers.py:1030:            if type(num[1]) is str:
sympy/geometry/util.py:30:    xs = [i for i in free if (i.name if type(x) is str else i) == x]
sympy/ntheory/factor_.py:124:    if type(n) is str:
sympy/utilities/iterables.py:1328:    if len(multiset) == 1 and type(multiset) is str:
sympy/utilities/misc.py:418:        if type(table) is str and type(s) is str:
```

**Comment by supreet11agrawal** [comment]
Ok, I'll do the necessary changes today

**Comment by oscargus** [comment]
Sounds good. If you consider my comment of changing elsewhere, please see #16094 as a) at least numbers.py should be untouched and b) @divyanshu132 was willing to pick it up (so probably no need for you to do that).

**Comment by supreet11agrawal** [comment]
Anybody can do that, no problem. @divyanshu132 if you are working on this, kindly reply. If not, I'll do the necessary changes.

**Comment by divyanshu132** [comment]
@supreet11agrawal I've already created a pr #16096, please provide your suggestions.

**Comment by asmeurer** [comment]
Please add a test and a release notes entry.

**Comment by supreet11agrawal** [comment]
For Release Notes, should I enter 'printing supports unicode text'? Will it do? @asmeurer

**Comment by asmeurer** [comment]
This change is unrelated to printing.

**Comment by supreet11agrawal** [comment]
Kindly merge @oscargus @jksuom

**Comment by oscargus** [comment]
Looks good! Thanks!

**Pull request merged**
