### PR TITLE
reverted changes of #17723 for 1.5

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References to other Issues or PRs

Reverts #17723 

#### Other comments
For doing the revert for 1.5, I did the changes manually. Probably the release notes for #17723 should be removed manually too.

ping @cbm755 @asmeurer @oscarbenjamin 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by czgdp1807** [comment]
Once this PR will be merged, I will remove the release note entry for #17723 from https://github.com/sympy/sympy/wiki/Release-Notes-for-1.5

**Comment by czgdp1807** [comment]
Feel free to make any change and merge. I have allowed `Allow edit from maintainers`.

**Comment by czgdp1807** [comment]
One more PR will be opened for master to fix the original issue for `1.6`.

**Comment by oscarbenjamin** [comment]
> One more PR will be opened for master to fix the original issue for `1.6`.

I think first we should go back to the original issue or open a new one to discuss what exactly needs to be fixed before opening a PR.

**Comment by cbm755** [comment]
This looks fine.  Next time you could just do `git revert <sha>`.

**Comment by asmeurer** [comment]
I agree that we need more discussion about what the behavior should be. Reverting to the 1.4 behavior for 1.5 is the best course of action.

**Pull request merged**
