### PR TITLE
Fix docs preview link

### PR DESCRIPTION
**Pull request by asmeurer**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
This should work. For instance https://output.circle-artifacts.com/output/job/a9fa0426-c6b1-4be1-a41d-dc2c01e523a0/artifacts/0/doc/_build/html/index.html for #23293

**Comment by asmeurer** [comment]
The preview link doesn't work here, but I think as before it uses what's in master, not the PR, so we can't tell if this will work until after we merge this.

**Comment by oscarbenjamin** [comment]
You could also use the `comment-on-pr` workflow to post the URL to the PR.

**Comment by asmeurer** [comment]
I made use of the Furo announcement feature to add a header the preview pages that points back to the PR and commit, and should make it so that people don't accidentally end up on a PR preview page instead of the real docs. https://output.circle-artifacts.com/output/job/151814d4-bd70-4343-8306-286c2c5e2363/artifacts/0/doc/_build/html/index.html

**Pull request merged**
