### PR TITLE
Init printing docstring addition and bug fix

### PR DESCRIPTION
**Pull request by jbm950**
I added the ability to pass arguments from init_printing to the printer that init_printing uses through a **settings argument a little while back. This addition did not properly interact with the no_global input argument in init_printing and this code should fix that issue. In addition **settings has been added to init_printing's docstring.

### CODE REVIEW

**Comment by moorepants** [comment]
Please add a test for the pretty printing in the ipython notebook to show that the `use_unicode_sqrt_char` kwarg works. You'll need to parse the `settings` dict and create three separate dicts with matching kwargs for the three printers. Here is a way to get the call signatures:

`inspect.getargs(printer.__code__).args:`

**Comment by jbm950** [comment]
I don't think this method is going to work because the printers just take an expression and a **settings dictionary and determine what the additional arguments are internally.

Example
```python
def latex(expr, **settings):
```

**Comment by czgdp1807** [comment]
@moorepants Is this feature still needed? I am unable to figure whether it's already there in the master.

**Comment by eric-wieser** [comment]
This can be closed:

* The `settings` dict is already forwarded to `_stringify_func`: https://github.com/sympy/sympy/blob/63f8f465d48559fecb4e4bf3c48b75bf15a3e0ef/sympy/interactive/printing.py#L541-L551

* The `settings` argument is now documented: https://github.com/sympy/sympy/blob/63f8f465d48559fecb4e4bf3c48b75bf15a3e0ef/sympy/interactive/printing.py#L412-L414

**Comment by oscarbenjamin** [comment]
Thanks @jbm950 for the contribution. It looks like this isn't needed any more so I'll close it.

Thanks for checking @eric-wieser

**Pull request closed without merging**
