### PR TITLE
Increase test coverage of LaTeX printer

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Increase test coverage of LaTeX printer

#### Brief description of what is fixed or changed
Increase test coverage of LaTeX printer

A change is that the subfactorial to a power is now printed with brackets. Earlier it printed `!k^2` which is potentially ambiguous (although `subfactorial(k**2)` prints as  `!(k^2)` so not strictly)

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
This seems a good opportunity to play around with codecov. 

The first thing I don't understand is where there are two statuses, codecov/patch and codecov/project. They both point to the same URL. 

It seems a lot of unrelated files are showing up in the diff. It was mentioned on Gitter that this may be  related to randomness in the test runs. 

For sympy/printing/latex.py, it says it went from -15 (yellow)/-23 (red) to +38 (green). What is the difference between yellow and red? 

Most importantly, how do I actually see which lines had coverage changed? If I click on it, it just shows me the whole file. But I want to see which lines were not covered before but are now.

**Comment by asmeurer** [comment]
I've seen [other people](https://twitter.com/pganssle/status/1091758342341562371) complain about this as well.

**Comment by oscargus** [comment]
Clearly relevant questions.

Patch is the coverage of the newly added  lines. Project for all code.

Red is not covered lines. Yellow is partially covered, typically if cases where only one branch is taken or where not every combination of a larger expression is evaluated (`if x > 0 or y > 0` where only `x = y = 0` and `x > 0` has happened although both branches were taken).

For the files actually listed in one of the tabs (writing on the phone so cannot check the name), it is listed in the left hand side (e.g. both red and green), but for some reason the Latex printer is not there, only the "random" files.

**Comment by oscargus** [comment]
The tab is called Changes and the Latex Printer is in there. However, it doesn't seem correctly marked. Look at another of the files which only shows lines with changed coverage.

**Comment by asmeurer** [comment]
Patch and change are the exact same URL. I checked some other PRs and it's like that everywhere. I guess they do two statuses to have different status messages?

**Comment by oscargus** [comment]
Yes, that is my guess as well. Which makes sense as one is both interested in that the new code has good coverage as well as the total. Since both point to the "Overview" tab I guess that is sort of OK, although one could point e.g. patch to the "Diff" tab.

I've been using it in other projects earlier and I also had the impression that it was better then (although it was some time ago, so I do not clearly remember). There is an issue with the coloring being off in some files when looking at the total coverage. Different parts of the docstring being colored differently etc and some lines not colored at all. So there are clearly things for Codecov to fix.

**Comment by asmeurer** [comment]
There's also alternatives we can look at as well, such as https://coveralls.io.

**Comment by asmeurer** [comment]
The change here itself looks fine by the way. 

I'm not sure about codecov yet. It seems for it to be useful we should at least try to fix https://github.com/sympy/sympy/issues/16196 first, which is a good thing anyway.

**Pull request merged**
