### PR TITLE
Removed deprecated in assumptions

### LINKED ISSUE #9425: Q.bounded is now deprecated
`Q.bounded` has been deprecated. Use `Q.finite` instead.

This is the `Deprecation Removal` issue for the same.

See https://github.com/sympy/sympy/pull/9228

### LINKED ISSUE #9426: Q.infinity is now deprecated
`Q.infinity` has been deprecated. Use `Q.infinite` instead.

This is the `Deprecation Removal` issue for the same.

See https://github.com/sympy/sympy/pull/9228

### LINKED ISSUE #9675: Q.infinitesimal is now deprecated
`Q.infinitesimal` has been deprecated. Use `Q.zero` instead.

This is the `Deprecation Removal` issue for the same.

See https://github.com/sympy/sympy/pull/9676

### PR DESCRIPTION
**Pull request by Smit-create**
Removed deprecated in assumptions
#### References to other Issues or PRs

Fixes #9675
Fixes #9425
Fixes #9426
#### Release Notes

* assumptions
  *  Removed deprecated `Q.bounded` (use `Q.finite` instead). Deprecated since version `1.0` (issue: #9425)
  *  Removed deprecated `Q.infinitesimal` (use `Q.zero` instead). Deprecated since version `1.0` (issue: #9675)
  *  Removed deprecated `Q.infinity` (use `Q.infinte` instead). Deprecated since version  `1.0` (issue: #9426)

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
There should be a release note explaining explicitly which things have been removed, how long they have been deprecated and referring back to the original issue where they were deprecated.

**Comment by Smit-create** [comment]
@oscarbenjamin Can you please review as running the tests locally:
```
>>> sympy.test('sympy/printing/tests/test_tensorflow.py')
==================================================== test process starts ====================================================
executable:         /home/smit/anaconda3/bin/python  (3.7.4-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 2.0.8
numpy:              1.17.2
random seed:        25833597
hash randomization: on (PYTHONHASHSEED=4280413652)

sympy/printing/tests/test_tensorflow.py[9] .s.ssss..                                                                     [OK]

=================================== tests finished: 4 passed, 5 skipped, in 0.38 seconds ====================================
True
```

While on travis:
```
________________________________________________________________________________

_______ sympy/printing/tests/test_tensorflow.py:test_tensorflow_matrices _______

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/testing/runtests.py", line 1328, in _timeout

    function()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/printing/tests/test_tensorflow.py", line 305, in test_tensorflow_matrices

    _compare_tensorflow_matrix((M,), expr, use_float=True)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/printing/tests/test_tensorflow.py", line 69, in _compare_tensorflow_matrix

    abs(a-b) < 10**-(4-int(log(abs(a), 10))) for a, b in zip(r, e))

  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/printing/tests/test_tensorflow.py", line 69, in <genexpr>

    abs(a-b) < 10**-(4-int(log(abs(a), 10))) for a, b in zip(r, e))

  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/core/expr.py", line 300, in __int__

    raise TypeError("can't convert complex to int")

TypeError: can't convert complex to int

 tests finished: 1025 passed, 10 expected to fail, 

1 expected to fail but passed, 1 exceptions, in 17.63 seconds 

DO *NOT* COMMIT!

Traceback (most recent call last):

  File "<stdin>", line 10, in <module>

Exception: Tests failed
```

**Comment by oscarbenjamin** [comment]
> While on travis:

See #18090

**Comment by asmeurer** [comment]
I fixed the release notes (they didn't make sense as written before).

**Comment by Smit-create** [comment]
> I fixed the release notes (they didn't make sense as written before).

Sorry I would make it work correctly further

**Comment by Smit-create** [comment]
@oscarbenjamin  @asmeurer  Is it ready to merge?

**Comment by oscarbenjamin** [comment]
Looks good.

**Pull request merged**
