### PR TITLE
Enabled Non Integer `nu` for `yn` bessel functions

### LINKED ISSUE #11777: assume_integer_order in bessel.py should be more liberal
Right now things like `jn(nu, x).rewrite(besselj)` won't work unless you explicitly set `nu = Symbol('nu', integer=True)`. It should be more liberal, only failing if the argument is not an integer. In general, SymPy should not require the correct assumptions to be true, only for the incorrect assumptions to not be True. 

As a side note: I'm unclear why this has to require nu be an integer. Aren't bessel functions defined for any value?

### PR DESCRIPTION
**Pull request by arihantparsoya**
Fixes #11777.

In reference to:
#11785

### CODE REVIEW

**Comment by parsoyaarihant** [comment]
@asmeurer , can you review this?

**Comment by asmeurer** [comment]
CC @thisch

**Comment by thisch** [comment]
Before I continue reviewing this PR I need a decision on whether we want to support spherical bessel functions of non-integer order in sympy. According to the literature on Bessel functions I've studied, I doub't that we need to support spherical Bessel functions of non-integral order (at least not symbolically).

from MATHEMATICAL METHODS FOR PHYSICISTS, Arfken, Weber, Harris:

> It is not ordinarily useful to introduce spherical Bessel functions with indices that are not integers, so we
assume the index n to be integral (but not necessarily nonnegative).

The only definition of spherical bessel functions of complex-valued order I've found so far is in the documentation of Mathematica, e.g., http://reference.wolfram.com/language/ref/SphericalBesselJ.html. In the case of complex-valued orders `SphericalBesselJ` returns numerical results.

**Comment by parsoyaarihant** [comment]
Hi @thisch , I think your argument is valid.

In that case we should restore the [test case](https://github.com/sympy/sympy/pull/11785/files#diff-59d5c23bc75db1e2030d3e2b8d0f445fL84) which I removed in PR #11785 .

**Comment by parsoyaarihant** [comment]
I have reverted back the changes and added the test case.

**Comment by jksuom** [comment]
Bessel functions of half-integer order can be rewritten in terms of elementary functions. They are 2-valued and branched at the origin in the same way as the square root. They can be expressed as the product of `sqrt(z)` and a single valued elementary function called spherical Bessel function.

The defining formula of a spherical Bessel function can be formally applied to a Bessel function of any complex order: shift the order by 1/2 and divide by `sqrt(z)`. However, the resulting function is not singlevalued and cannot be rewritten in terms of elementary functions. To compute its values it has to be re-rewritten as an ordinary Bessel function. It is hard to find any practical use for such functions.

**Comment by czgdp1807** [comment]
@parsoyaarihant Are you interested to work on this PR? Please add a release notes entry. Refer, https://github.com/sympy/sympy/wiki/Writing-Release-Notes

**Comment by czgdp1807** [comment]
```python
>>> nu = Symbol('nu')
>>> jn(nu, x).rewrite(besselj)
          ___                    
         ╱ 1                     
√2⋅√π⋅  ╱  ─ ⋅besselj(ν + 1/2, x)
      ╲╱   x                     
─────────────────────────────────
                2         
```
The original issue has been fixed. Closing for now. Thanks for your contributions.

**Pull request closed without merging**
