### PR TITLE
fix(core): fix pickling of Basic to use __getnewargs__

### LINKED ISSUE #21121: Same symbols created in different processes are not resolved as being equal
Hello,

When I try to create symbols (and by extension expressions) in different processes, SymPy somehow does not detect that the symbols are the same even though they have the same name and assumptions.

As an example, consider the following code snippet and the respective output:

```
import multiprocessing as mp
import sympy as sp

VAR_X = sp.Symbol('x', real=True, nonzero=True)

def process():
    return sp.Symbol('x', real=True, nonzero=True)

if __name__ == '__main__':
    a1 = sp.Symbol('a', real=True, nonzero=True)
    a2 = sp.Symbol('a', real=True, nonzero=True)
    print(a1, a2, a1 == a2, a1 - a2, '\n')

    pool = mp.Pool(4)
    jobs = []
    for _ in range(5):
        jobs.append(pool.apply_async(process))
    symbols = []
    for job in jobs:
        symbols.append(job.get())
    pool.close()

    for s in symbols:
        print(s, ' | ', VAR_X, ' | ', s - VAR_X, ' | ', sp.simplify(s - VAR_X))
```

Output:
```
a a True 0

x  |  x  |  -x + x  |  -x + x
x  |  x  |  -x + x  |  -x + x
x  |  x  |  -x + x  |  -x + x
x  |  x  |  -x + x  |  -x + x
x  |  x  |  -x + x  |  -x + x
```

@oscarbenjamin thinks this may be related to pickling and unpickling the symbol. Working in the same process creating two different symbols returns the
exact same object:
```
In [5]: x1 = Symbol('x')

In [6]: x2 = Symbol('x')

In [7]: x1 is x2
Out[7]: True
```

I also tried to explicitly pickle and unpickle the symbols using the `dill` library, but this also didn't help.

Interestingly, if I obtain two expressions (separately) from different processes, and one is integrand `f` and the other is expected integral `F` (both containing only one free symbol, `x`), SymPy manages to resolve that `simplify(F.diff() - f) == 0` and `simplify(integrate(f) - F) == 0`. Note that I **do not** pass the symbol `x` with respect to which to differentiate or integrate. If I do it, it fails. Unfortunately, I don't have a small enough code snippet readily prepared to exemplify this behaviour.

### PR DESCRIPTION
**Pull request by oscarbenjamin**
This ensures that pickling of Basic subclasses is based on
`__getnewargs__` with the exception of Symbol that uses `__getnewargs_ex__`
for keyword argument support. The changes here fix pickling using
protocol 2 or higher but remove support for pickling using protocol 0
or 1. Protocol 2 was introduced in Python 2.3.

A number of classes needed to be rearranged or tidied up to accommodate for
this including Singleton and some of the Singleton class such as Reals.

#### References to other Issues or PRs

Fixes #21121 

#### Release Notes

* core
    * Fixed pickling for a number of Basic subclasses (such as a Symbol with assumptions) for protocol 2 or higher. Removed support for pickling with protocol 0 or 1.

### CODE REVIEW

**Comment by asmeurer** [comment]
Does it give an error if you try to pickle with protocol 1 (or is that even possible)?

**Comment by asmeurer** [comment]
Is the bug from the issue tested here? All I see is test_core_symbol in test_pickling.py, but that (presumably) already passes.

**Comment by asmeurer** [comment]
Thanks for working on this. We need to make a more concerted effort to making pickling work better with SymPy. The current state is that either things don't pickle at all, or you get bizzare bugs like #21121 that lead to broken behavior, often in very subtle ways. Pickle not working also means that you can't use multiprocessing with SymPy, so it's hard to speed things up by parallelizing them. 

Incidentally, pickling is one place where Hypothesis testing would be very natural and help to catch bugs in corner cases (#20914).

**Comment by oscarbenjamin** [comment]
> Does it give an error if you try to pickle with protocol 1 (or is that even possible)?

If you try to pickle with protocol 1 then it will work sometimes but not always. There isn't a good way to support protocol 0 and 1 at the same time as the others. For protocol 1 or 0 you need to define `__getstate__` to handle any keyword arguments which doesn't work very well (hence the issue that this fixes). To support protocol 2 or higher the best way is to use `__getnewargs_ex__` for anything that needs keyword arguments but to make that work completely you need to make sure that `__getstate__` returns `None` which breaks protocol 0 or 1. The way to support all protocols is using `__reduce_ex__` but that is not recommended. I think it is better not to try and support the really old protocols.

**Comment by oscarbenjamin** [comment]
> Is the bug from the issue tested here? All I see is test_core_symbol in test_pickling.py, but that (presumably) already passes.

I'm not sure how exactly to test this. It needs to be a test that invokes a subprocess because in-process cacheing can hide the bug.

**Comment by oscarbenjamin** [comment]
> Incidentally, pickling is one place where Hypothesis testing would be very natural and help to catch bugs in corner cases (#20914).

As I mentioned somewhere else I'm not sure that hypothesis is useful in the places where we already know what the problems are :)

Maybe if this is merged and fixes the basic problems so that we think things are good then hypothesis testing to discover unforeseen bugs would be useful. For now it wouldn't be hard to add pickling etc to `test_args` and I expect that a whole bunch of failures would jump right out.

**Comment by asmeurer** [comment]
> If you try to pickle with protocol 1 then it will work sometimes but not always. There isn't a good way to support protocol 0 and 1 at the same time as the others. For protocol 1 or 0 you need to define __getstate__ to handle any keyword arguments which doesn't work very well (hence the issue that this fixes). To support protocol 2 or higher the best way is to use __getnewargs_ex__ for anything that needs keyword arguments but to make that work completely you need to make sure that __getstate__ returns None which breaks protocol 0 or 1. The way to support all protocols is using __reduce_ex__ but that is not recommended. I think it is better not to try and support the really old protocols.

That's the impression I got. But my question was if there is a way to make it error on protocol 1, so that people don't try to use it. But maybe it's not actually that important, since likely very few people are actually using it. It's not the default, and it it's only really required to use if you want to use a version of Python that hasn't been supported in a very long time.

> I'm not sure how exactly to test this. It needs to be a test that invokes a subprocess because in-process cacheing can hide the bug.

So we should extend the pickling test to do this. 

> As I mentioned somewhere else I'm not sure that hypothesis is useful in the places where we already know what the problems are :)

I'm not at all convinced we know what the problems are for pickling. I've seen very bizarre behavior trying to use SymPy/mpmath with multiprocessing, which I know came from pickling, but I have no idea what was going on beyond that. Things like numerical results coming out completely wrong. It's possible this PR would have fixed the issues I had, or that there are tons of more similar latent problems (I highly expect the latter). So the very basic question of, "does this PR fix all the existing issues with pickling Basic instances?" is unanswerable, especially if the answer is purported to be in the positive, because the existing tests aren't very convincing in terms of coverage. Hypothesis would enable you to expand coverage (not line coverage, but search space coverage), to be more confident that a fix does in fact work. Actually pickling is one of those things where things could still be broken anyway, because it's easy to have bugs that can only be reproduced by creating some specific internal state, but even then, it would be much better than what we have now, which is already written like a property test, but only tests against a very small specific set of examples.

**Comment by asmeurer** [comment]
Protocols 2 and 3 aren't really necessary to support either https://docs.python.org/3/library/pickle.html#data-stream-format. Unless there's some other reason someone might use an older protocol that I'm not aware of.

**Comment by oscarbenjamin** [comment]
> I'm not at all convinced we know what the problems are for pickling.

I agree but I think that right now we know what the showstoppers are. Once those are out of the way if we're not sure what problems there are then hypothesis can be a really good way to find them. At the moment I expect a hypothesis test would stumble after immediately finding the bugs that we already know (that I'm trying to fix here).

**Comment by oscarbenjamin** [comment]
> my question was if there is a way to make it error on protocol 1, so that people don't try to use it

I guess we could define `__reduce_ex__` and have it raise for protocol 0 or 1:
https://docs.python.org/3/library/pickle.html#object.__reduce_ex__

I just pushed that as a change.

**Comment by oscarbenjamin** [comment]
I've added an explicit error for protocols 0 and 1.

This is ready for review/merge.

**Pull request merged**
