### PR TITLE
Series/Limits : Fixes leading term for exponential functions involving AccumBounds based arguments

### LINKED ISSUE #18473: Bug in limit
`limit(cos (x)**(1/x),x,oo)` should give `AccumBounds` instead of `1`.

### PR DESCRIPTION
**Pull request by anutosh491**
#### References to other Issues or PRs

Fixes #18473

#### Brief description of what is fixed or changed
On Master
```
>>> limit(sin(x)**(1/x), x, oo)
1
>>> limit(cos(x)**(1/x), x, oo)
1
>>> limit(tan(x)**(1/x), x, oo)
1
>>> exp(x*log(cos(1/x))).as_leading_term(x)
1
>>> exp(x*log(sin(1/x))).as_leading_term(x)
1
>>> exp(x*log(tan(1/x))).as_leading_term(x)
1
>>> log(cos(1/x)).as_leading_term(x)
log(AccumBounds(-1, 1))
>>> log(sin(1/x)).as_leading_term(x)
log(AccumBounds(-1, 1))
>>> log(tan(1/x)).as_leading_term(x)
log(AccumBounds(-oo, oo))
```
The limits shown above cannot be correctly claimed to be `1` . For eg the following
image

Firstly the function isn't continuous in the real domain as `x` tends to `oo` and even if it does the answer is not going to be `1` .
This is because something like `log(cos(1/x)).as_leading_term(x)` returns `log(AccumBounds(-1, 1))` which wouldn't be supportive in the `real` domain . Unfortunately a `subs` operation for `x` by `0` is taking place changing the `x*log(AccumBounds(-1, 1))` to `0` and returning `exp(0)` which is `1` . Hence the Pr fixes the above not really correct result.

On Committed branch . `S.NaN` seems to be the best option we have to tackle non real values of `log` inside `AccumBounds` !
```
>>> x = Symbol('x')
>>> limit(sin(x)**(1/x), x, oo)
Limit(sin(x)**(1/x), x, oo, dir='-')
>>> limit(cos(x)**(1/x), x, oo)
Limit(cos(x)**(1/x), x, oo, dir='-')
>>> limit(tan(x)**(1/x), x, oo)
Limit(tan(x)**(1/x), x, oo, dir='-')
>>> exp(x*log(cos(1/x))).as_leading_term(x)
nan
>>> exp(x*log(sin(1/x))).as_leading_term(x)
nan
>>> exp(x*log(tan(1/x))).as_leading_term(x)
nan
>>> log(cos(1/x)).as_leading_term(x)
nan
>>> log(tan(1/x)).as_leading_term(x)
nan
```

#### Other comments
All Discussion for this Pr had taken place in #23087 but due to couple wrong commands in the past my PR  was based on a master branch which wasn't a straight-copy of the main sympy master branch. Hence since past few Prs after switching to a new branch from master , I would get unwanted code pushed everytime  . Hence I was having problems in squashing, rebasing,reverting commits which was showing fatal error message. I followed @oscarbenjamin 's comment on another Pr helping another fellow contributor to fix a similar issue. This involved setting the main sympy repo as upstream again . This will help me in the future too as now I am sure this problem isn't going to occur again!
This is what I followed to sort the error (https://github.com/sympy/sympy/pull/22872#issuecomment-1031365942)

#### Release Notes

* series
  * Fixes leading term for exponential functions involving AccumBounds based arguments.

### CODE REVIEW

**Comment by anutosh491** [comment]
CC: @jksuom . Sorry for the disorganization and confusion on the other Pr but due to an unwanted mistake with my master branch(as pointed in other comments in the OP) whenever I would try a rebase, squash or revert command , it used to show a fatal error message . But I realized Oscar had helped another fellow contributor to restore the master branch correctly , I realized after trying out all possible options that the error lies there and referring his comment I have fixed the error . This would also help me for future Pr's !
This looks good to go in . The authors file failure isn't a fault of this Pr and is being fixed through another Pr (#23126).
Thanks for your patience and reviews !

**Comment by anutosh491** [comment]
ping @jksuom

**Comment by jksuom** [comment]
This looks good now, thanks!

**Comment by anutosh491** [comment]
> This looks good now, thanks! 

Thanks for the great reviews and suggestions!

**Comment by anutosh491** [comment]
CC: @jksuom . I just realized something which we could improve on here . The inspiration for this was one of my latest prs implementing series and leading term for the frac functions #23044 , which is yet to be reviewed by you !
As `frac(1/x).as_leading_term(x)` is `AccumBounds(0, 1)`, I thought of adding a test which is a corner case like the above ones for eg ( `limit((cos(x) + 1)**(1/x), x, oo)` ) , which should be addressed by this part 
```
        if isinstance(arg0, AccumBounds):
            # This check addresses a corner case involving AccumBounds.
            # if isinstance(arg, AccumBounds) is True, then arg0 can either be 0,
            # AccumBounds(-oo, 0) or AccumBounds(-oo, oo).
            # Check out function: test_issue_18473() in test_exponential.py and
            # test_limits.py for more information.
            return exp(arg0)
```
So we have the following
```
>>> limit(frac(x)**(1/x), x, oo)
AccumBounds(0, 1)
```
image

But then I realized the implementing was missing out on cases involving `-oo` . 
```
# Currently on master
>>> limit((cos(x) + 1)**(1/x), x, oo)
AccumBounds(0, 1)
>>> limit((cos(x) + 1)**(1/x), x, -oo)
AccumBounds(0, 1)
```
But as the graph shows  our implementation is correct for `oo` but won't work for `-oo` implementation 
image
image

So if you think carefully the negative case is just the inversion of the positive case so this is solved by the following . Will be linking all expected results and graphs for the same in a comment below !
```
        if isinstance(arg0, AccumBounds):
            # This check addresses a corner case involving AccumBounds.
            # if isinstance(arg, AccumBounds) is True, then arg0 can either be 0,
            # AccumBounds(-oo, 0) or AccumBounds(-oo, oo).
            # Check out function: test_issue_18473() in test_exponential.py and
            # test_limits.py for more information.
            if cdir == 1:
                return exp(arg0)
            return 1/exp(arg0)
```

**Comment by anutosh491** [comment]
After applying above suggested diff , we can see as while travelling towards positive infinity , the function steeply falls to `0` periodically , similarly while travelling in the opposite direction the function rises steeply to `oo` 

**1)** `(sin(x)**2)**(1/x)`
```
>>> limit((sin(x)**2)**(1/x), x, oo)
AccumBounds(0, 1)
>>> limit((sin(x)**2)**(1/x), x, -oo)
AccumBounds(1, oo)
```
image


**2)** `limit((tan(x)**2)**(2/x) , x, oo)`
```
>>> limit((tan(x)**2)**(2/x) , x, oo)
AccumBounds(0, oo)
>>> limit((tan(x)**2)**(2/x) , x, -oo)
AccumBounds(0, oo)
```
image

**3)** Also a test from the latest pr as reported above #23044 , which is where I spotted this improvement which is `frac(x)**(1/x)`
```
>>> limit(frac(x)**(1/x), x, oo)
AccumBounds(0, 1)
>>> limit(frac(x)**(1/x), x, -oo)
AccumBounds(1, oo)
```
image

**Comment by anutosh491** [comment]
Other cases work perfectly fine at negative infinity too because , either the limit does not exist (where we return self) or the function approaches a constant value in both direction , so we don't need to touch them . For eg this function goes to `1` from both sides 
```
>>> limit((cos(x) + 2)**(1/x), x, oo)
1
>>> limit((cos(x) + 2)**(1/x), x, -oo)
1
```
image

I will

**Pull request merged**
