### PR TITLE
nsolve leaves function unmodified

### LINKED ISSUE #11768: nsolve wrong result
``` py
>>> print(E.subs(sols[0]).diff(t))
-0.0243197537608033*(-0.636658291554981*t + 0.561884537092944)/(-0.0243197537608033*t + 1)**2 + (-2*(t + 1)/(2*t - 2)**2 + 1/(2*t - 2))*exp((t + 1)/(2*t - 2)) + 0.636658291554981/(-0.0243197537608033*t + 1)
>>> nsolve(diff(E.subs(sols[0]), t), .9)
mpf('0.99996577349047597')
>>> E.subs(sols[0]).diff(t).subs(t, 0.99996577349047597) 
0.654436749282803
```

Here's a plot of the function in question. As you can see, the root should be around 0.7.

8pzjlzvm767vqaaaaasuvork5cyii

### PR DESCRIPTION
**Pull request by smichr**
closes #11768

ping @asmeurer

### CODE REVIEW

**Comment by asmeurer** [comment]
Can you add a new test (a simpler example generalized from the idea from the one in the issue should be fine).

**Comment by moorepants** [comment]
Also needs conflicts resolved.

**Comment by asmeurer** [comment]
Another instance where this behavior is useful: if you are trying to find all the roots of a function, it can be helpful to divide by the roots you already found. For instance, something like:

```py
def allroots(expr, degree, prec):
    roots = []
    start = random.random() + random.random()*I
    while len(roots) < degree:
        try:
            r = nsolve(expr/Mul(*[t - r for r in roots]), start,
                maxsteps=1.7*prec, prec=prec)
        except ValueError:
            start *= random.random() + random.random()*I
        else:
            roots.append(r)
    return roots
```

This *only* works if `nsolve` keeps the denominator.  So given this, I am now definitely +1 for making this change (I was unsure before).

**Comment by asmeurer** [comment]
I've pushed up a test to this branch. Will merge once the tests pass.

**Comment by asmeurer** [comment]
Python 3.5 tests are failing right now. We should restart the builds once it is fixed.

**Comment by jksuom** [comment]
It seems that the updated .travis.yml should be included to make the Python 3.5 tests pass.

**Comment by asmeurer** [comment]
Oh right I forgot you have to merge the branch to make .travis.yml fixes work.

**Pull request merged**
