### PR TITLE
numbers:Fixed Integer and StdFactKB memory leak

### PR DESCRIPTION
**Pull request by NoumbissiValere**
Fixed the Integer and StDFactKB memory leak by changing the cache
infrastructure from _intcache which is adhoc and unbound to a proper
cache infrastructure cacheit.
The following code was used to test the success of the issue

>>import os
>>os.environ['SYMPY_USE_CACHE'] = 'no'
>>from sympy.parsing.sympy_parser import parse.expr
>>import gc
>>import objgraph

>>for i in range(100000):
	parse.expr('log({})'.format(i), local_dict=dict(),
evaluate=False)

>>gc.collect()

>>print(objgraph.show_most_common_types(limit=10))

running the above command with the _intcache infrastructure gave the
following results

dict               204812
StdFactKB          200490
Integer            199996
function           15255
tuple              4835
weakref            1820
list               1624
cell               1435
property           1232
wrapper_descriptor 1058
None

After replacing the _intcache with a proper infrastructure, running the
program gave this result

function           15253
tuple              4835
dict               4815
weakref            1820
list               1624
cell               1435
property           1232
wrapper_descriptor 1058
getset_descriptor  866
method_descriptor  857
None

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
If this is reusing the changes from https://github.com/sympy/sympy/pull/9294, you should keep the commits intact so that the authorship is shown correctly in the metadata.

**Comment by NoumbissiValere** [comment]
Please how do i go about that. am i new to open source and this is my first pull request i just did. 
I need to add the reference to #9294 and the release but i don't know to edit pull requests

**Comment by NoumbissiValere** [comment]
@asmeurer does that mean i have to pull branch of #9294 before i do my changes and commit or what? please i don't understand

**Comment by asmeurer** [comment]
Yes, you should start from the git branch from that pull request, and make new commits on top of it. Basically instead of starting your branch from master you should start from debugger22/Integer-new-cache

**Comment by NoumbissiValere** [comment]
ok thanks

**Pull request closed without merging**
