### PR TITLE
polys: use float('-inf') instead of -oo for degree(0)

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### Brief description of what is fixed or changed

Changes it so that within the internal poly code SymPy's symbolic negative infinity (`-oo`) is not used for the degree of zero. This makes various operations faster because symbolic comparisons are avoided in the internals of performance sensitive algorithms.

SymPy defines the degree of 0 as `-oo`:
```python
In [4]: degree(x**2)
Out[4]: 2

In [5]: degree(x)
Out[5]: 1

In [6]: degree(1)
Out[6]: 0

In [7]: degree(0)
Out[7]: -∞
```
In general I am not convinced that this is useful but particularly in the case of the polys code this means that symbolic expressions are being used in low-level algorithms which should be avoided. Low-level functions like `dup_degree` should not return the high-level `-oo` type. The most common thing that is done with the output from `dup_degree` is to test if it is less than zero or to compare two degrees:
https://github.com/sympy/sympy/blob/5cc71ab22cdbe4d332bbe0a17191603288d97e2b/sympy/polys/euclidtools.py#L817-L820

The problem then is this:
```python
In [8]: sinf = -oo

In [9]: ninf = float('-inf')

In [10]: %timeit sinf < 0
32.5 µs ± 141 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [11]: %timeit ninf < 0
43.1 ns ± 0.928 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```
In other words it is 1000x slower to use `-oo` in an inequality comparison than it is to use `float('inf')`.

I have known for some time that this was making various things slow because often when I interrupt a slow operation I will find that it is in the middle of the code that evaluates the inequality `-oo < 0`. I wanted to have a clear example of something that was made slow by this though.

This PR changes it so that all the low level routines like `dup_degree` use `float('-inf')` rather than `-oo` but still the high-level interfaces like `Poly(0, x).degree()` and `degree(0)` will return `-oo`.

An example of what this speeds up is factorisation over ZZ_I or QQ_I. These are timings with master:
```python
In [1]: a, b, c, d, e, f, g, h = symbols('a:h')

In [2]: eq2 = (a*b*d*g*(b*(I*d*e + f) + d*e)*(I*a*d*g + 1)*(a*c*d*(a*d*g - I) + a*d*h*(a*d*(c + g) - I))
   ...: + a*b*d*h*(b*(I*d*e + f) + d*e)*(a*d*g - I)*(a*d*(c + g) - I) - b*(a*d*g - I)*(I*a*d*g + 1)*(I*b*
   ...: d*e + d*e)*(a*c*d*(a*d*g - I) + a*d*h*(a*d*(c + g) - I)))

In [3]: eq2
Out[3]: 
a⋅b⋅d⋅g⋅(b⋅(ⅈ⋅d⋅e + f) + d⋅e)⋅(ⅈ⋅a⋅d⋅g + 1)⋅(a⋅c⋅d⋅(a⋅d⋅g - ⅈ) + a⋅d⋅h⋅(a⋅d⋅(c + g) - ⅈ)) + a⋅b⋅d⋅h⋅(b⋅ ↪

↪ (ⅈ⋅d⋅e + f) + d⋅e)⋅(a⋅d⋅g - ⅈ)⋅(a⋅d⋅(c + g) - ⅈ) - b⋅(a⋅d⋅g - ⅈ)⋅(ⅈ⋅a⋅d⋅g + 1)⋅(ⅈ⋅b⋅d⋅e + d⋅e)⋅(a⋅c⋅d ↪

↪ ⋅(a⋅d⋅g - ⅈ) + a⋅d⋅h⋅(a⋅d⋅(c + g) - ⅈ))

In [4]: %time eq2.factor()
CPU times: user 19 s, sys: 88.8 ms, total: 19.1 s
Wall time: 19.1 s
Out[4]: 
                   2                                                                        
ⅈ⋅a⋅b⋅d⋅(a⋅d⋅g - ⅈ) ⋅(a⋅b⋅c⋅d⋅f⋅g + a⋅b⋅c⋅d⋅f⋅h + a⋅b⋅d⋅f⋅g⋅h - b⋅c⋅d⋅e - ⅈ⋅b⋅f⋅h + ⅈ⋅c⋅d⋅e)
```
With the PR that is:
```python
In [4]: %time eq2.factor()
CPU times: user 4.41 s, sys: 20.7 ms, total: 4.43 s
Wall time: 4.43 s
Out[4]: 
                   2                                                                        
ⅈ⋅a⋅b⋅d⋅(a⋅d⋅g - ⅈ) ⋅(a⋅b⋅c⋅d⋅f⋅g + a⋅b⋅c⋅d⋅f⋅h + a⋅b⋅d⋅f⋅g⋅h - b⋅c⋅d⋅e - ⅈ⋅b⋅f⋅h + ⅈ⋅c⋅d⋅e)
```
So this high-level operation is made 4x faster by the change.

#### Other comments

An alternative convention for the degree of 0 is just -1 which is what python-flint uses:
```python
In [8]: import flint

In [9]: x = flint.fmpz_poly([0, 1])

In [10]: (x**2).degree()
Out[10]: 2

In [11]: (x**1).degree()
Out[11]: 1

In [12]: (x**0).degree()
Out[12]: 0

In [13]: (0*x**0).degree()
Out[13]: -1
```
I'm not sure that returning `-oo` for the degree is ever really useful. The advantage of returning `-1` would be that at least we know that it is always an int. Possibly returning `float('-inf')` is more backwards compatible.

Previously `-1` was used but that was changed in 424bab8 in gh-2436

#### Release Notes

* polys
    * The low-level polynomial implementations such as the polynomial domains and types like DMP now return `float('-inf')` rather than SymPy's symbolic `-oo` for `degree(0)`. This is because using `-oo` was making many operations slow e.g. this change made factorisation over the `ZZ_I` or `QQ_I` domains 4x faster for one case.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
In general I would prefer not to have any code that depends on the value of  `degree(0)`. Any time that happens it would be better to have a check like `if x.is_zero` or `if dup_zero_p(x)` instead.

**Comment by asmeurer** [comment]
degree(0) == -1 is wrong if you ever add degrees, like degree(p*q) == degree(p) + degree(q). -inf also plays better with Laurent polynomials, although I'm not so sure about general rational functions. https://github.com/sympy/sympy/pull/2436 does mention some bugs were caused by -1, but I don't remember what they were.

**Comment by asmeurer** [comment]
This is an obvious performance improvement, so let's merge it. We can discuss if degree(0) should be some other value (or error?) in another issue.

**Comment by oscarbenjamin** [comment]
Thanks!

**Comment by jksuom** [comment]
Relations of type $\deg pq = \deg p + \deg q$ are expected to hold in euclidean domains only for nonzero p and q. I would personally prefer `degree(0)` to be the SymPy object S(-1) instead of a float. That might even be more efficient.

**Comment by oscarbenjamin** [comment]
I think in practice if you look across the codebase at usage of functions like `dup_degree` you can see that it almost always is necessary to check for the case of zero polynomials anyway e.g.:
https://github.com/sympy/sympy/blob/f327f0ba9ca32a15a999e9d8e8704729f9db8c8b/sympy/polys/densearith.py#L527-L533
https://github.com/sympy/sympy/blob/f327f0ba9ca32a15a999e9d8e8704729f9db8c8b/sympy/polys/euclidtools.py#L817-L820
https://github.com/sympy/sympy/blob/f327f0ba9ca32a15a999e9d8e8704729f9db8c8b/sympy/polys/sqfreetools.py#L49-L52
I don't really see any cases where any arithmetic is used that depends on `degree(0) = -oo` and actually it looks more like there is code that needs to work around this case. Many places test for negative degree:
https://github.com/sympy/sympy/blob/f327f0ba9ca32a15a999e9d8e8704729f9db8c8b/sympy/polys/rootisolation.py#L577-L578

I think it would be clearer to write that as:
```python
if dup_ground_p(f):
    return []
```
Or
```python
if dup_zero_p(f):
    return []
```
Internally `dmp_degree` calls `dmp_zero_p` and I think that in most cases it would be clearer to call `dmp_zero_p` directly rather than checking if the degree is negative:
https://github.com/sympy/sympy/blob/f327f0ba9ca32a15a999e9d8e8704729f9db8c8b/sympy/polys/densebasic.py#L181-L184

**Pull request merged**
