### PR TITLE
Modifications to `function_range` for periodic functions

### PR DESCRIPTION
**Pull request by akash9712**
Modified part of function_range dealing with periodic function.
Added test for previously incorrect result.
Example:
```
>>>function_range(sin(x), x, Interval(-oo, -3))
Interval(-1, 1)
>>>function_range(sin(x),  x, Union(Interval(-5, -3), FiniteSet(4)))
Union({sin(4)}, Interval(-sin(3), 1))
```

### CODE REVIEW

**Review by smichr — COMMENTED** [review]
You can unify Union and interval by putting interval into args or make args=Union's args.

**Comment by akash9712** [comment]
@smichr Do you mean something like this:
```
if isinstance(domain, Interval):
    args = (domain,)
elif isinstance(domain, Union):
    args = domain.args
for sub_dom in args:
...
```

**Comment by smichr** [comment]
That lloks good. But what about raising a NotImplemented if anything else is encountered? e.g. if domain were S.Integers or a FiniteSet?

**Comment by akash9712** [comment]
@smichr Implementing the function as mentioned above will raise error if the given domain is a finite set.
I have kept this part of the function the same as in the previous commit, and added the functionality to raise a `NotImplementedError` if the range cannot be calculated.

**Pull request merged**
