### PR TITLE
 added documentation for jordan_cell method in matrices.py 

### PR DESCRIPTION
**Pull request by avishrivastava11**
Added documentation for `jordan_cell` method in sympy/matrices/matrices.py 

Explained what is a `jordan block` as the method `jordan_cell` uses `jordan_block` to make a `jordan_cell`. Also added Wikipedia link to jordan matrix.

Contributers, members, others please review this PR and let me know the improvements.
Any feedback is highly appreciated.
Thanks.

### CODE REVIEW

**Comment by avishrivastava11** [comment]
@asmeurer , @jksuom , @certik  can you review this PR and if there are no issues, please merge it.

**Comment by jksuom** [comment]
It seems that `jordan_cell` is an old name for `jordan_block`. It will probably be removed later on (see https://github.com/sympy/sympy/pull/12708#issue-123830962).

**Comment by avishrivastava11** [comment]
@jksuom 

> It will probably be removed later on

I'd say, until it is not removed, let's keep the documentation which this PR adds. After it is removed, we can change `jordan_cell` to `jordan_block` accordingly in the documentation too.

What do you think?

**Comment by jksuom** [comment]
Perhaps the docstring of `jordan_block` should contain the information.

**Comment by avishrivastava11** [comment]
@jksuom I have added the documentation to `def jordan_block` in `common.py`. But I still feel that until `jordan_cell` is removed from the codebase, the docstring explaining what `jordan_block` is, should be there. Also I've added the documentation to `def jordan_cell` in `dense.py` too. 
Pls review and let me know if there are any further changes

**Comment by avishrivastava11** [comment]
@jksuom , @asmeurer , @certik request you to review this PR and if there are no issues, please merge it.

**Comment by avishrivastava11** [comment]
@certik Review please

**Comment by avishrivastava11** [comment]
@jksuom @smichr  Review please.

**Pull request closed without merging**
