### PR TITLE
Added line_color option to plot_implicit

### LINKED ISSUE #6688: plot_implicit lacks a line_color option
```
Unlike many of the other plotting functions in the new plotting module, plot_implicit lacks the ability to set the color of the line via a line_color function. 

Implementing the option should be very similar to implementing line_color in plot.
```
Original issue for #6688: http://code.google.com/p/sympy/issues/detail?id=3589
Original author: https://code.google.com/u/111207639578282893178/

### PR DESCRIPTION
**Pull request by shivamvats**
Fixes #6688

### CODE REVIEW

**Comment by Krastanov** [comment]
after adding the test mentioned above this should be good for merging

**Comment by amitsaha** [comment]
@shivamvats (sorry about the delay). Yes, that looks good to me. Please add it.

**Comment by shivamvats** [comment]
@amitsaha  I've added the tests.

**Comment by amitsaha** [comment]
@shivamvats :+1: @skirpichev  or somebody else with merge rights can merge this if they are fine with it.

**Comment by shivamvats** [comment]
Thanks @amitsaha !
Could you have a look at my diff in #8756? Let's choose the best way and modify the testing framework accordingly.

**Comment by asmeurer** [comment]
Merging based on @amitsaha's review.

**Pull request merged**
