### PR TITLE
Blacklist sympy.this from the doctester

### PR DESCRIPTION
**Pull request by asmeurer**
Otherwise it prints it during ./bin/doctest when the doctester tries to import
it.

### CODE REVIEW

**Comment by gxyd** [comment]
Please rebase on top of master branch.

**Comment by ylemkimon** [comment]
@gxyd Isn't rebase not necessary unless there are merge conflicts?

**Comment by gxyd** [comment]
I think merging an updated master branch should work just fine. But I preferred to mention rebase instead of merge was because, this PR is too small and wouldn't create no problem with review process (also wouldn't create a un-necessary merge commit).

Anything can be done, unless it hinders the review process, though I personally prefer rebase :)

**Comment by asmeurer** [comment]
I never rebase, so asking me to rebase is like asking a horse to fly.

**Pull request merged**
