### PR TITLE
20113: Plotting - Improving backend support + Plot size

### LINKED ISSUE #20113: Plotting - BaseBackend and Plot size
Users should be able to specify a subclass of Basebackend when creating a plot. Also, users should be able to set the figure size.

I'm opening this issue following the [Development guidelines](https://github.com/sympy/sympy/wiki/Development-workflow#create-a-patch-file-or-pull-request-for-github), as I need to create a pull request.

### PR DESCRIPTION
**Pull request by Davide-sd**
This pull request should fix [issue 20113](https://github.com/sympy/sympy/issues/20113).

Added the keyword argument `size` to Plot, PlotGrid and plot functions.
The user can now specify the figure size. This is useful for generating
plots that are ready to be exported and later included in documents.

Example:
x = symbols("x")
plot(sin(x), size=(8, 4))

#### Release Notes

* plotting
  * users can now specify the plot size

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Hi @Davide-sd and thank you for sending this PR. It looks like a well-written PR although the flake8 test has failed because of an unneeded variable:
```
sympy/plotting/tests/test_plot.py:669:9: F841 local variable 'p4' is assigned to but never used
```

I don't think that the approach here is the right one though. Rather than adding more features for plot to pass through to matplotlib I think that we should provide a clear way for users to pass in a matplotlib `Axes` so that they can do something like:
```python
import matplotlib.pyplot as plt
import sympy as sym

x = sym.Symbol('x')
f = cos(x)
fig = plt.figure(figsize=(8, 4))
ax = fig.add_subplot(1, 1, 1)
sym.plot(f, ax=ax)
plt.show()
```
That would then give all of the capability of matplotlib for setting sizes, ticks, titles, grids etc.

I think that it is good for sympy to provide a convenience function like `plot` but the idea that sympy should provide a full-featured frontend for plotting seems misguided to me.

**Comment by Davide-sd** [comment]
Hello Oscar, thank you for the reply. Damn, how did I missed that output from the flake8 command?!?!? Thank you for pointing that out, I was scratching my head... :)

> I think that it is good for sympy to provide a convenience function like plot but the idea that sympy should provide a full-featured frontend for plotting seems misguided to me.

I agree with you 100%, there is no need to reinvent the wheel. Unfortunately, I fear that your approach requires a significant rewriting and testing of the plotting module, as we not only have to re-think the backend classes, but also the `*Series` classes. Take for example `LineOver1DRangeSeries` (which is the one I'm most familiar with): at the moment, it is very matplotlib-centered, as the `get_segments()` methods returns data that works well with matplotlib's `LineCollection` but not so well with other plotting libraries. Also, I noticed an inconsistency on the data type returned by `get_segments()`, depending on the `adaptive` option. Which leads me to believe that other `*Series` classes may have similar "limitations".

At the end, I created this PR because I recently had to use "plot size" quite a lot, and (selfishly) I would be happy to get it out-of-the-box from Sympy in the next release, so that I can get rid of some ugly custom code.

**Comment by oscarbenjamin** [comment]
> Unfortunately, I fear that your approach requires a significant rewriting and testing of the plotting module

It would potentially involve a lot of changes (I haven't looked through in any detail). Otherwise though sympy will slowly end up having to include redundant code and docs for all of the matplotlib API.

Another approach that might be easier (I haven't checked) is that we could expose the most useful internal routines that are used by sympy's plot function to prepare the data for matplotlib. Then a user can do something like:
```python
import matplotlib.pyplot as plt
import sympy as sym

x = sym.Symbol('x')
f = cos(x)
fig = plt.figure(figsize=(8, 4))
ax = fig.add_subplot(1, 1, 1)
xvals, yvals = sym.plot_data(cos(x))
ax.plot(xvals, yvals)
plt.show()
```
The `plot_data` function could generate the x and y values which is basically the difference between `sym.plot` and `plt.plot`.

Actually I think that we should do both of these things and also expose the internal mpl axes for users so:

1. Make convenience routines like `plot_data` to prepare data for matplotlib (or any other plotting library).

2. Add a way to pass in an Axes from matplotlib to be used by `sympy.plot` so that users can customise the creation of the axes using the matplotlib API.

3. Provide a way to access the Axes that is created by `sympy.plot` so that users can add to the plot using the matplotlib API.

What I don't think we should do is extend the "frontend" API as a workaround because otherwise we will find ourselves doing that indefinitely. If we were extending the frontend API then potentially a `size` argument could be reasonable but not a subclassing API as that is much more constraining and would be completely unnecessary after above points were implemented.

**Comment by Davide-sd** [comment]
> The plot_data function could generate the x and y values which is basically the difference between sym.plot and plt.plot.

That is what I have done in my custom code to be able to plot symbolic expressions with Plotly.

Anyway, the actual plot functions are meant to be convenient functions to quickly plot expressions. We should definitely draw a line on "how much convenience do we need". Let me clarify by considering this example, which shows a couple of severe limitations of the current approach:
```
x = symbols("x")
p = plot((sin(x), (x, -pi, pi)), (cos(x), (x, -2*pi, 2*pi)), 
          show_legend=True)
```

1. all expressions are plotted with the same color. This happens because matplotlib's `LineCollection` is used; by replacing it with `ax.plot()`, matplotlib is perfectly capable of automatic coloring, which should be enough for simple plotting.
2. The current legend is not up for the task, as it shows the actual expressions; this is fine for this very simple example, but it creates a mess for complicated ones. Ideally, I would like to provide meaningful labels, which would require to modify the argument parsing. For example, `plot((sin(x), (x, -pi, pi), "sin"),  (cos(x), (x, -2*pi, 2*pi), "cos"))`.

`MatplotlibBackend` is already going to create a figure and axes objects. We could indeed create a keyword arguments in the `plot()` function accepting a tuple (fig, ax). We could also create a property in the `Plot` class, exposing the backend. That way, to further customize the plot the user could do something like: `ax = p.backend.ax`. This should be a quick fix.

Then, if `plot()` is meant to be simple, I argue that the following keyword arguments should be removed, as the same functionality can be achieved with `ax.method_name(...)`.
* `fill`: to fill the area in between lines, I have to numerical evaluate the expressions. At that point, do I really need to create a symbolic plot? Not really, I can just use the full matplotlib, or I can use the axes exposed by `Plot`. In this regard, the hypothetical `plot_data` function should help a lot.
* `markers`
* `annotations`
* `rectangles`

Which brings me to this question: what about backward compatibility?

**Comment by oscarbenjamin** [comment]
> Which brings me to this question: what about backward compatibility?

I think that right now we should keep the current functionality of plot but we should make it easy to augment that by using the matplotlib API directly. Most importantly the documentation should make it clear how the matplotlib API is being used and what the equivalent matplotlib code is that users could use directly instead of sympy's plot function.

Once we have that sorted we can think about whether or not to change any of the existing features. Backwards compatibility is less of a concern if it is clear how users can replace their current code with a few lines using matplotlib.

There are potential advantages in having a symbolic plot function such as being able to zoom in or out and having the plot data recompute. You could imagine plotting something like `sin(1/x)` and being able to zoom in around `x=0` to see more detail. The current plot module doesn't do anything like that though and I think that if we did want that kind of feature it would be better to add the functionality as a generic feature in matplotlib that sympy could hook into.

I would like to see other extensions to plotting such as domain colouring etc.:
https://en.wikipedia.org/wiki/Domain_coloring

Again though I think that it should be organised like:

1. There is a function `domain_color_data` that generates the basic data you would pass to matplotlib or another library.

2. There is a `domain_color` function which is a convenience function that is clearly documented as being equivalent to calling `domain_color_data` and passing the result to a specific matplotlib function.

We can have lots of different plotting functions but we should focus on sympy doing the symbolic part, numpy etc ding the numeric part, and let the plotting API sit with matplotlib.

The current "frontend" approach (deliberately) makes it difficult for users to use the matplotlib API directly and instead gives a confusing array of extra classes. It would be easier for users to understand as well as easier to implement in sympy if we were just honest about the fact that there is only one backend. The pyglet backend should be deprecated and removed, and the text "backend" is nice but it's really just a single function `textplot`.

The idea of the backends is that it should make it easier to use different plotting libraries. Actually a function like `plot_data` would be much more useful for that. Rather than adding backends we can just add to the docs showing how to use `plot_data` with different plotting libraries.

**Comment by Davide-sd** [comment]
> The idea of the backends is that it should make it easier to use different plotting libraries. Actually a function like `plot_data` would be much more useful for that.

The backends should create very basic plots using different plotting libraries. I like the fact that I can create a plot and set the "x label", "y label", "title" with a single command. More complicated things should definitely be done with the plotting library directly. 

Hence, we should make it clear both to the users and developers that backends are meant to be simple. 

Speaking of `textbackend`, is there really someone using it?

**Comment by oscarbenjamin** [comment]
> The backends should create very basic plots using different plotting libraries.

I disagree. We have a basic plot function that uses matplotlib and that's fine. Support for other libraries should be as minimal as possible i.e. just a function like `plot_data` and maybe a demonstration of how to use that with the other library in the docs.

If someone wants to build a fancier plotting library on top of sympy then they can do that in a separate codebase. Sympy already has 750,000 lines of code and not enough contributors to maintain that code so it is important to keep the scope of sympy clear: it is a library for symbolic manipulation. Other projects make libraries for plotting and users can use those directly to benefit from all of their features without any code needing to be added to sympy.

**Comment by Davide-sd** [comment]
> Support for other libraries should be as minimal as possible i.e. just a function like plot_data and maybe a demonstration of how to use that with the other library in the docs.

I disagree. Support for other plot libraries should be left as an option to the interested users. It's 50% of this PR, making sure that the keyword argument `backend` can accept sub-classes of `BaseBackend`. 

I don't need to waste 2 minutes every time I need to plot something to write all the boilier-plate code for axis names, legends,... that is the work for a backend. Whether the user needs more functionalities, he should use `plot_data` and start from scratch.

**Comment by sylee957** [comment]
We may not be ready for adding some big options until a good cleanups for `experimental_lambdify` is done.
However, I'm sure that the option the author is trying to add is completely independent with any other options, so if some tests can be added to check the consistency, it will not be difficult.

**Comment by oscarbenjamin** [comment]
Okay well I've said my piece :)

I don't object to someone else merging this.

I would prefer a different approach to be taken with plotting in general and I think that if we fix this properly then issues like the ones addressed here can be solved in full generality.

**Comment by Davide-sd** [comment]
There are nice ideas in this PR, so if you'd like to keep it open for a while, maybe somebody else can jump in and implement them. I have a pretty full plate for at least the next couple of months: in this time frame I will not attempt to implement them.

**Comment by moorepants** [comment]
> I would prefer a different approach to be taken with plotting in general and I think that if we fix this properly then issues like the ones addressed here can be solved in full generality.

@oscarbenjamin You may be right about all this, but some account of the history of this should be considered. We already have done a second iteration on plotting. We first had pyglet plotting (still in the codebase) and then we have had one (or more) GSoCs devote careful design and thought implementing what is currently there for the second iteration. For better or worse, it is the plotting functionality that SymPy has and mimics the simplicity for a user when plotting in tools like mathematica and sage.

I think it is unreasonable to ask a new contributor to redesign our potting library like you suggest. That should probably be a GSoC project or a developers pet project. It would require some design presentations of sort to get community buy in and likely be a longer process. What is reasonable, is supporting helpful changes to update and improve what we have in the current framework. This seems like one such thing.

**Comment by moorepants** [comment]
I'm +1 to this change. Tests just need to pass on CI.

**Comment by oscarbenjamin** [comment]
> I think it is unreasonable to ask a new contributor to redesign our potting library like you suggest.

To be clear, I'm not asking @Davide-sd to do this and I don't object to someone else merging this particular PR.

I just want to make it clear that I think it is a mistake to make significant extensions of the plotting API to solve problems that would be better solved simply by giving users direct access to the matplotlib figure and axes handles.

In particular this PR adds (and documents) a feature that allows users to pass in a custom backend class which would be a subclass of the BaseBackend class. This kind of public API is very hard to change in future because it exposes internal details like the BaseBackend class (which is currently an undocumented internal class). Not only does it expose the class but it encourages users to subclass the class which is the strongest possible kind of coupling between upstream and downstream code. Right now we could rewrite the plotting module and completely remove the BaseBackend class. Once it has been subclassed by downstream users every part of the class is fixed and it can not be removed, refactored or changed in any significant way.

**Comment by sylee957** [comment]
The errors are from the documentation build
```
/home/travis/build/sympy/sympy/sympy/plotting/plot.py:docstring of sympy.plotting.plot.plot3d:65: WARNING: Unexpected indentation.
/home/travis/build/sympy/sympy/sympy/plotting/plot.py:docstring of sympy.plotting.plot.plot3d_parametric_surface:63: WARNING: Unexpected indentation.
```
So maybe you should check the newly written docstrings that you have indented consistenly

**Comment by Davide-sd** [comment]
> So maybe you should check the newly written docstrings that you have indented consistenly

Weird, it appears to be fine in my editor (Codium)...

**Comment by Davide-sd** [comment]
@oscarbenjamin Does sympy offer a way for the user to set default options once so that they persists over time and sessions?

**Comment by oscarbenjamin** [comment]
No. Sympy does not use any persistent state.

**Comment by Davide-sd** [comment]
I'm going to [drop a link to a youtube video](https://www.youtube.com/watch?v=et-Ogix6qek) in which I showcase a Plotly backend for Sympy plotting, plus an class allowing interactive controls and plotting. This should be enough to convince even the more skeptical about the need of this PR.

**Comment by oscarbenjamin** [comment]
That does look cool but I'm unclear why this PR in particular is what is needed in order to make that work. My first thought looking at the video is: wouldn't it be easier to build something like this using something like the hypothetical `plot_data` function that I suggested above?

Above you say that you have made a function like that for `Plotly` so what exactly is the "backend support" here needed for?

Are you hoping to add the `Plotly` backend you have created to sympy or is the intention that it would stay as a separate module but using the backend support from this PR?

**Comment by Davide-sd** [comment]
> Above you say that you have made a function like that for Plotly so what exactly is the "backend support" here needed for?

If you look carefully, `plot_data` is implemented in that video.

The backend allows the user to use Plotly (or even matplotlib for that matter) even without being familiar with the library. You don't have to create the boilerplate code to set axis labels, title,... which becomes boring after a couple of plots. 

Even more important, the `iplot` functionality shown in the video only works with Plotly, there is no way to get it working with Matplotlib. Even if there was, it wouldn't be smart to invest time over it, given how slow matplotlib performs in an interactive frame. 

Equally importantly, we can easily convert a plot from one backend to the other with a single command. This is useful when you are prototyping using Plotly backend and, at some point, you need a pdf plot to be included in some publication: all you have to do is convert the plot to matplotlib and save it to ".pgf".

> Are you hoping to add the Plotly backend you have created to sympy or is the intention that it would stay as a separate module but using the backend support from this PR?

Not sure yet. Eventually this backend could be added to Sympy, but in order to use it, first there are a lot of minor issues to solve regarding the output of the `*Series` classes. It's a lot of work.

**Comment by oscarbenjamin** [comment]
If you're making a library for this then it's easy enough to wrap the boilerplate into a single function. Also it should be easy enough to write a function that takes the same data and sends it to matplotlib.

I don't doubt that Plotly has advantages over matplotlib and if you're making a library for this then that's great. If it's not going to be part of sympy though then I don't see why it would make sense for it to be implemented as a sympy plotting backend.

I don't think that the original authors of the plotting module intended that downstream libraries would make their own backends. At least if they did then they should have documented what the interface should be. As far as I can tell you are writing a library based on internal, private, and undocumented interfaces which means that we will end up with a situation where:

1. Your library is fragile and breaks periodically as changes are made in sympy or...
2. It becomes very difficult to make improvements to sympy's plotting module because of the need to maintain backward compatibility in all the private code for libraries like yours. This also makes it difficult to improve sympy in a way that would make it easier for libraries like yours to be built on good documented API in future.

**Comment by Davide-sd** [comment]
> I don't think that the original authors of the plotting module intended that downstream libraries would make their own backends.

No??? Here is [the original commit](https://github.com/Davide-sd/sympy/commit/69a88f2b06f363cef548b73d1fea08efd5db79ec)! Let's read together the docstring of the `Plot` class:

```
class Plot(object):
    """Plotting stuff.
     This class permits the plotting of sympy expressions using numerous
    backends (matplotlib, textplot, the old pyglet module for sympy, Google
    charts api, etc).

    """
```

Note the **etc**!

Clearly, someone has changed the documentation over time. Luckily, I'm not in the mood to open an inquisition over who changed it, nor I have the time... Nonetheless, that was precisely the original intention. 

> I don't doubt that Plotly has advantages over matplotlib and if you're making a library for this then that's great. If it's not going to be part of sympy though then I don't see why it would make sense for it to be implemented as a sympy plotting backend.

_**The whole point of having a backend is to easily use the already implemented Sympy plotting functions with the specified plotting library!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**_ And we already established the original intentions of this implementation...

> As far as I can tell you are writing a library based on internal, private, and undocumented interfaces ...

The only reason we are having this discussion is because there are people that goes around changing documentation and distorting the original intentions. 

> It becomes very difficult to make improvements to sympy's plotting module because of the need to maintain backward compatibility in all the private code for libraries like yours. This also makes it difficult to improve sympy in a way that would make it easier for libraries like yours to be built on good documented API in future.

I do really think this module has a good implementation, even though it is incomplete (or obsolete in the case of `MatplotlibBackend`). I even went that far to create a demonstration of one of capabilities that can be built on top of it. This PR would allow a great deal of flexibility. So, let's proper document the current implementation, shall we?

I get it, for some unknown reasons you hate the current implementation: feel free to share in detail what you dislike, what you would remove and what you would implement. Because right now, I have the feeling that you would remove what I find good, implement the `plot_data` function and then write a doc "Dear user, you want a plot? Do it yourself!".

Finally, I wouldn't mind being selected for a NumFocus project to implement the kind of interactivity shown above. It would definitely be a great addition to Sympy.

**Comment by oscarbenjamin** [comment]
I'm going to back away from this discussion. I'm sure that others are interested in this PR and they can discuss/merge.

> Finally, I wouldn't mind being selected for a NumFocus project to implement the kind of interactivity shown above. It would definitely be a great addition to Sympy.

I think that would be great!

**Comment by moorepants** [comment]
I agree the original intent of the author(s) of the current plotting package and related modules was to setup a framework so that people could call simplified plot commands from SymPy that "just work" (like other popular symbolic software) and that changing a flag `backend={'plotly','matplotlib','ascii','etc'}` would seamlessly produce outputs from those backends.

@oscarbenjamin I think you are and have been counterproductive by effectively blocking new work on the plotting package in sympy that doesn't fit with the way you believe the package should have been designed. Ripping out the plotting package in SymPy and creating a new one based on a different paradigm is a huge undertaking and it isn't helpful to block these PRs to the existing package by talking about a paradigm that doesn't exist yet in SymPy. I hope that we can encourage new and old contributors to improve and maintain the existing code. Maybe some day in the future someone will have the time and energy to revamp the plotting package and your data oriented method may be chosen. It is particularly harmful to put up hurdles for new contributors. Historically we value adding contributors over the perfect code design.

@asmeurer You may want to comment here on this.

**Comment by moorepants** [comment]
@Davide-sd Please resolve the merge conflicts and I'll merge once tests pass. @oscarbenjamin said above he was fine if this was merged by someone else. I see no blocking reasons. The debate on the future of the sympy plotting code should probably best happen on the mailing list.

**Comment by oscarbenjamin** [comment]
> @oscarbenjamin I think you are and have been counterproductive

I agree. My intention is not to block progress but to try and suggest an alternative approach but that clearly isn't helping. I'll keep my views about bigger changes to the plotting module to myself until there is a way to implement them properly.

Then I have only two points about this PR:

1. This PR encourages downstream user/library code to subclass a previously private class in a way that is not documented anywhere. Some documentation should be added that explains what the subclassing API is: which methods should a subclass override and what exactly is the specification for how the methods of the subclass will be used? That does not necessarily need to be in *this* PR but without that I think that merging this PR is a step in the wrong direction.

2. If this is going to be merged into master then it can also go into 1.7. A separate PR would have to be opened cherry-picking the commits from here onto the 1.7 branch though. If this is merged into master then I will merge the other PR into the 1.7 branch so it goes into the 1.7 release.

**Comment by moorepants** [comment]
@oscarbenjamin thanks.

> Some documentation should be added that explains what the subclassing API is: which methods should a subclass override and what exactly is the specification for how the methods of the subclass will be used?

I agree with this. The PR has two things. 1) adding figure size option and 2) enabling passing in this backend class. It would be better if these were separate PRs, but we can work with this, and the second item doesn't seem fleshed out. @Davide-sd Is it possible to add some documentation on this new feature that better describes how to implement the backend?

**Comment by Davide-sd** [comment]
@moorepants @oscarbenjamin Absolutely, no problem in adding the proper documentation. Do you have a timeline for Sympy v1.7 release? 

So to clarify, do I have to remove one of the edits (for example plot size) and open a new PR for that?

**Comment by moorepants** [comment]
If you move the backend thing to a new PR, this fig size change can go in very easily. Then you can add the backend documentation in the new pr for some more discussion.

**Comment by oscarbenjamin** [comment]
> Do you have a timeline for Sympy v1.7 release?

The release will just be as soon as I can get it out. I wanted to put out the release candidate 2 weeks ago but I hit problems. I need to fix those problems which means finding `~3hrs` of uninterrupted time and then I can put out the release after that. During the last week I found zero time that I could use to work on that. There are also some PRs to merge so it's at least a week away if not more.

**Comment by czgdp1807** [comment]
Closing this as the [original issue](https://github.com/sympy/sympy/issues/20113) has been fixed.

**Pull request closed without merging**
