### PR TITLE
MAINT: updated conftest.py with fstrings

### PR DESCRIPTION
**Pull request by sb369**
#### Brief description of what is fixed or changed
#18547

#### Release Notes

#18547

### CODE REVIEW

**Comment by sylee957** [comment]
I had not made strings as f-string in some previous PR because it seemed like failing with py27 import test. But I'm surprised that it works here.

**Comment by oscarbenjamin** [comment]
> py27 import test.

There was a problem with that test before but that is fixed now so any syntax from Python 3.5 upwards is allowed.

**Comment by oscarbenjamin** [comment]
I don't think we need changes like this pull request. The old `%`-formatting is not being removed so there is no need to "update" this code. I think it's fine to use f-strings in new/changed code though.

**Comment by oscarbenjamin** [comment]
@sb369 thank you for this contribution. I don't think that this is needed though.

It is fine to use f-strings in new code but there is no need to go around changing old code to use these since the other methods of string formatting work fine and are not deprecated or planned for removal.

I am going to close this but please do consider making other contributions to sympy.

**Pull request closed without merging**
