### PR TITLE
Issue #9910 removing sin(x) in order as x tends to infinity

### PR DESCRIPTION
**Pull request by meghana-madhyastha**
Fixes Issue #9910. I have added a couple of tests to verify that it fixes the issue. 
The problem here seems to be that extract_leading_term never removes sin(x). So I've added some conditions which check for terms which do not go to infinity when there are other terms which goes to infinity (if the order is to be evaluated at infinity). Please correct me if I have missed something.

### CODE REVIEW

**Comment by jksuom** [comment]
One should not remove all terms that contain sin(x), because they need not always be negligible in comparison with leading terms. For example, in
```
>>> Order(x*log(x) + x**2*sin(x), (x, oo))
O(x*log(x), (x, oo))
```
the sin term is the largest for most values of x.

**Comment by meghana1995** [comment]
You are right. I made a mistake by assuming that x**2*sin(x) when x is substituted with infinity, will become infinity so that term will not be neglected. But that wasn't the case. So I added another condition to fix it and added the case you had mentioned above as a test.

**Comment by meghana1995** [comment]
Or would a better way to approach this be to include a special case just for the terms which have a trigonometric function in them ?

**Comment by czgdp1807** [comment]
@megh1241 Thanks for the contributions. Would you still like to continue your work on this? It looks like  the issue is still unresolved. Please resolve the conflicts.

**Comment by sachin-4099** [comment]
I will takeover and come up with a PR soon.

**Comment by praneethratna** [comment]
This PR can be closed since the issue #9910 seems fixed and also a test case was added in the PR #20361.

**Comment by 0sidharth** [comment]
b777e46 which added a call to `factor` fixed the original issue, for which a test was also added. Closing this, thanks for the contribution!

**Pull request closed without merging**
