### PR TITLE
Added test of limit

### LINKED ISSUE #2929: limit((x*exp(x))/(exp(x)-1), x, -oo) gives -oo
`gruntz()` - returns correct answer, 0.

@asmeurer 

> Ah, so it seems that these incorrect limit heuristics have still not
> been completely abolished from the code base.

Yes, `e.is_Mul` branch is still here.  It's a workaround for test_issue2856 (last test).

### PR DESCRIPTION
**Pull request by Smit-create**
Added test of limit to increase coverage
#### References to other Issues or PRs

Fixes #2929

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by czgdp1807** [comment]
Why the coverage is being reduced?

**Comment by Smit-create** [comment]
> Why the coverage is being reduced?

I am too unable to understand how it will reduce while adding a test itself.

**Comment by Smit-create** [comment]
@czgdp1807  Is it good to merge?

**Comment by czgdp1807** [comment]
Please merge master and push the changes. May lead to failure if merged. Let's be sure.

**Comment by Smit-create** [comment]
I think it is ready to merge, as diff is increasing.

**Comment by czgdp1807** [comment]
@smichr Is it ready to go?

**Comment by gschintgen** [comment]
Looks good! (except that I don't think a test addition is of concern to the end user, so the release notes should be "NO ENTRY")

**Pull request merged**
