### PR TITLE
Add \left and \right to floor, ceil, angle and Dirac ket LaTeX printing

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed
Now, `\left` and `right` is always added to the printing of `floor`, `ceiling`, when `langle` and `rangle` is used, and for the Dirac ket `|a>`.

Before:
image

Now:
image

I also updated the link the the MathJax documentation,

#### Other comments
It can be argued if it should also be changed in the documentation. I did it, although not strictly required.

#### Release Notes

* printing
   * When printing to LaTeX, `ceiling`, `floor`, <> and Dirac ket |a>now always add `\left` and `\right`

### CODE REVIEW

**Comment by oscargus** [comment]
It looks (to me) that the tests fails in exactly the same place as for #15779 (and that #15783 fails in the same place as well, in addition to other places), so I am tempted to state that there is a issue with the test system at the moment since none of these PRs affects the code that fails.

Is it possible to manually restart these tests once it seems to be working again? (If not, I will try to keep my eyes open for a passing PR and force push the PRs...)

**Comment by avishrivastava11** [comment]
@oscargus  Sometimes due to some connection errors, the tests fail too. If you're sure that your code doesn't change/affect a particular test which is failing, then restarting that particular test might help.
A mentor will be able to do this (restarting a test) so you should request them restart either the entire test process or a particular test.

**Comment by oscargus** [comment]
It seems like the head of the master branch cannot pass those tests either, so something is weird. Especially since neither the code nor the underlying library seems to have changed.

**Comment by avishrivastava11** [comment]
@oscargus Maybe a mentor might be able to help/explain here. @asmeurer  has something being changed in the master?

**Comment by oscargus** [comment]
@avishrivastava11 Please check #15784 and #15785 Numpy 1.16.0 introduces an issue that breaks Theano (which is fixed in Theano, but has not got into any package yet).

**Comment by oscarbenjamin** [comment]
Looks good to me

**Pull request merged**
