### PR TITLE
Fix #12361: change all misspelling Bareis to Bareiss

### LINKED ISSUE #12361: Misspelling of "Bareiss" in Matrix module
There are several references to the "Bareis" method for determinants, though his name appears to be spelled "Bareiss".  I assume this should be fixed and the one `s` version should be deprecated.

https://en.wikipedia.org/wiki/Bareiss_algorithm
https://www.genealogy.math.ndsu.nodak.edu/id.php?id=12730

### PR DESCRIPTION
**Pull request by Hell0Kitty**
I have fixed the misspelling "Bareis" into "Bareiss" in sympy/sympy/matrices/matrices.py and sympy/sympy/matrices/test/test_matrices.py

### CODE REVIEW

**Comment by siefkenj** [comment]
This has been handled by #12363  I think it can be closed.

**Comment by mamakancha** [comment]
@Hell0Kitty Yes this issue has been addressed and the PR has also been merged. Kindly update your local branch to see the new changes. And if some typo is still there, review the already submitted PR and suggest the changes.

**Comment by siefkenj** [comment]
Let's close this PR.

**Comment by smichr** [comment]
per request

**Pull request closed without merging**
