### PR TITLE
Cache assumption creation in Symbol

### PR DESCRIPTION
**Pull request by isuruf**
#### Brief description of what is fixed or changed

This makes the following code 3 times faster

```python
import sympy
sympy.symbols("x0:10000")
```

#### Release Notes

* core
  * Cache assumption canonicalization in SymPy.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
If you run `bin/mailmap_check.py` it will sort the .mailmap file for the AUTHORS check.

**Comment by oscarbenjamin** [comment]
The bleeding edge failure is unrelated. There seems to be a problem downloading the scipy nightly wheels right now.

**Comment by oscarbenjamin** [comment]
Looks good.

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
