### PR TITLE
Fixes solveset output for certain trigonometric equations

### LINKED ISSUE #12527: solveset mishandles domain
Giving an explicit domain gives no solution:
```
>>> solveset(1/tan(x),x,Interval(1,10))
EmptySet()
```

whereas giving no domain and intersecting the result gives solutions

```
>>> solveset(1/tan(x),x).intersect(Interval(1,10))
{pi/2, 3*pi/2, 5*pi/2}
```

### PR DESCRIPTION
**Pull request by kshitij10496**
- [x] closes #12527 

The primary reason for this behaviour is explained [here](https://github.com/sympy/sympy/issues/12527#issuecomment-293339210).

This PR adds a check for the input expression `f` in the `domain_check` function.
If the given function is a trigonometric or hyperbolic function, we rewrite it in the form of `exp` (similar to the process in `solve_trig`) and then proceed to apply the conditions of checking domain.

Ping @smichr 
What is your opinion about this fix?

* solvers
  * `solveset` now handles domains correctly

### CODE REVIEW

**Comment by smichr** [comment]
Leave a comment

> What is your opinion about this fix?

I suspect that somewhere in `solveset` the function `orig_f` is being sent to `domain_check`. I think it would be better to redefine `f = orig_f= f.rewrite(exp)` in `solveset` if `f` involves trigonometric functions containing the variable of interest. By doing what you've done here, we have a create two points at which the same change is being made and thus make the code a little more fragile.

Also, I was thinking about this. Maybe the right answer is the empty set. When you rewrite `tan(x)` in terms of `exp(x)` you are creating a numerator and denominator, both having `x` and you can find a solution to the expression `1/tan(x)=0`. But the solution, e.g. pi/2, creates a `zoo` in the original expression...should that be allowed?  So my concern is that the solution to `cot(x)` should perhaps not be the same as `1/tan(x)` for the same reason -- or similar reason -- that the solution of `1/(1/x-1) = 0` is not the same as `together(1/(1/x-1))=0`.

**Comment by kshitij10496** [comment]
> I suspect that somewhere in solveset the function orig_f is being sent to domain_check. I think it would be better to redefine f = orig_f= f.rewrite(exp) in solveset if f involves trigonometric functions containing the variable of interest. By doing what you've done here, we have a create two points at which the same change is being made and thus make the code a little more fragile.

I couldn't agree more. However, the transformation of `f` to an exponential form takes place in the helper `solve_trig` rather than `solveset` itself. This causes slight inconvenient in passing it to `domain_check` further down the execution pathway. 
I can think of only 2 ways to fix this issue:

1. Port the transformation statements in `solve_trig` to `solveset`.
Con: This will make `solveset` messy with the solver handler manipulating the functions as well.
2. Implementing the transformations in `domain_check`.
Con: Duplication of code.

Alternately, I can try to develop a separate, generic method for implementing the function transformations which handles all such operations already present in the `solveset` helpers. This will make the code more modular and maintainable. 
```python
In [] : solve_transform(sin(x), x)
Out []: -I*(exp(I*x) - exp(-I*x))/2
```

Would you recommend this?

**Comment by kshitij10496** [comment]
> Also, I was thinking about this. Maybe the right answer is the empty set. When you rewrite tan(x) in terms of exp(x) you are creating a numerator and denominator, both having x and you can find a solution to the expression 1/tan(x)=0. But the solution, e.g. pi/2, creates a zoo in the original expression...should that be allowed? So my concern is that the solution to cot(x) should perhaps not be the same as 1/tan(x) for the same reason -- or similar reason -- that the solution of 1/(1/x-1) = 0 is not the same as together(1/(1/x-1))=0.

I think `1/(1/(x-1))` simplifies to `x-1` automatically, similar to the behaviour of `x/x`.
Hence, both `1/(1/(x-1))` and `together(1/(1/(x-1)))` equate to the same function.

Mathematically, `pi/2` is not a singularity of `1/tan(x)`, since `sin(x)` is defined at this point.
This is a reason that we shouldn't drop `pi/2` from the solution.

I think we should consider the given expression on the whole for discussing its singularities rather than its individual arguments. If I'm missing something, let me know.

**Comment by smichr** [comment]
> I think 1/(1/(x-1)) simplifies to x-1 automatically

Typo on my part, sorry. It should have read:

```
>>> eq=1/(1/x-1)
>>> solve(eq)
[]
>>> solve(together(eq))
[0]
```

**Comment by smichr** [comment]
> Mathematically, pi/2 is not a singularity of 1/tan(x), since sin(x) is defined at this point.
> This is a reason that we shouldn't drop pi/2 from the solution.

Forgive the non-mathematician in me observing that *to me* it looks like we have `1/f(x) = 0` for which there are no solutions; the only solutions are those that make f(x) infinite -- and aren't those the solutions which involve dividing by zero somewhere in f(x)? This is why I differentiate between 1/tan(x) having no solution -- as I see it -- and cot(x) having a solution.

**Comment by kshitij10496** [comment]
From what I'm able to understand by your suggestion is that we have separate behaviour for `1/tan(x)`, `cot(x)` and `cos(x)/sin(x)`. Am I correct?

Let us consider another similar example:
```python
In [ ]: f = (x-1)**2/((x-1)*x)
In [ ]: solveset(f, x)
Out[ ]: {1}
``` 
If we check for the domain of the given expression `f`, we find that `x=1` is a singularity, ergo it shouldn't be a solution. 

I remember discussing this issue with @hargup and @aktech during my GSoC Project and they suggested that the solution returned by `solveset` can incorporate points of removable discontinuities. This helped justify the result for automatic simplifications.

In the particular case of `1/tan(x)`, as you correctly pointed out, `x=pi/2` is a discontinuity. I was a bit delusion in stating otherwise earlier. What I was trying to convey is that `pi/2` is a removable discontinuity of `1/tan(x)`(as both the left-hand limit and the right-hand limit tend to 0 with opposite signs). Hence, based on the supposed convention for removable singularities, I think we should include it in the solution.

**Comment by asmeurer** [comment]
Is this removable discontinuity behavior documented?  It seems a good idea only if implementing it otherwise is sufficiently complicated or impossible.

**Comment by smichr** [comment]
> I think we should include it in the solution.

If we can centralize this decision in one place, e.g. the singularities function with a keyword like `include_removable`, I think that would be best. As I recall from my conversations with others, removable singularities shouldn't be part of the solution -- that was the motive for the `denoms` function.

**Comment by asmeurer** [comment]
If it's a flag then we have to implement the logic to check for them anyway, in which case I don't see a point to allowing keeping them.

**Comment by czgdp1807** [comment]
ping @smichr @asmeurer Can this be merged?

**Comment by czgdp1807** [comment]
@gschintgen What all is to be done to complete this PR?

**Comment by gschintgen** [comment]
> 
> 
> @gschintgen What all is to be done to complete this PR?

The objective of this PR is summed up by the following new test:
```
   assert domain_check(1/tan(x), x, pi/2) is True
```
This is of course debatable, since `tan` not being defined for pi/2 could/should imply that `1/tan` also cannot be defined for pi/2. I.e. that there is a difference in domain between `cot` and `1/tan`.

Put otherwise: should `solveset` simply allow removable singularities in the solution set or should it treat them as what they are: a particular kind of singularity, hence not a proper solution. That has been discussed controversially above, with critical opinions expressed by some members.

Personally, I'm not in favor of this change, especially not over the reals.

Over the complexes there are some very elegant results if you consider the Riemann sphere, with `zoo` being a regular point where functions can be continuous etc. In this setting treating removable singularities in a more accepting way could be conceivable, but IMO that's not the same thing as "standard" analysis in the complex *plane*.

That's not to say there are no inconsistencies or deficiencies in domain handling (e.g. see https://github.com/sympy/sympy/issues/12527#issuecomment-517997668), but I don't think this is a step in the right direction.

**Comment by smichr** [comment]
> Let us consider another similar example:
> 
> In [ ]: f = (x-1)**2/((x-1)*x)
> In [ ]: solveset(f, x)
> Out[ ]: {1}
> 
> If we check for the domain of the given expression f, we find that x=1 is a singularity, ergo it shouldn't be a solution.

In this case, autosimplification makes the expressions `f = (x - 1)/x` and there is no discontinuity at `x = 1` whereas `1/(1/x-1)`  does not autosimplify to `x/(1-x)` so 0 is not returned as a solution. `solveset` either not take care to check the denominators of unevaluated solutions and returns a solution that is a removable singularity;
```python
>>> with evaluate(False): y = (x-1)**2/(x-1)
>>> solveset(y, x) # vs EmptySet for solveset(x/sin(x),x) which agrees with solve
[1]
>>> solve(y, x)
[]
```
I think the intention of solvers is to not return singularities of any kind so will close this issue.

**Pull request closed without merging**
