### PR TITLE
Remove contractions in documentation

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed

Primarily in documentation, but sometimes some exceptions are also changed.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by smichr** [comment]
-1/10...This doesn't bother me. Not sure if it is the same with others.

**Comment by oscargus** [comment]
Technical/scientific writing should not include it.

**Comment by oscarbenjamin** [comment]
> Technical/scientific writing should not include it.

I agree but like @smichr my feelings are not that strong either way.

**Comment by oscargus** [comment]
It is one thing to do the changes, another to merge it. :-)

**Pull request merged**
