### PR TITLE
UnXFAIL two integral tests in test_failing_integrals.py

### PR DESCRIPTION
**Pull request by debugger22**
Closes https://github.com/sympy/sympy/issues/4950
Closes https://github.com/sympy/sympy/issues/4968

### CODE REVIEW

**Comment by moorepants** [comment]
+1 once tests pass.

**Comment by debugger22** [comment]
Now I'm sceptical about this change after reading comments at https://github.com/sympy/sympy/issues/4968

**Comment by asmeurer** [comment]
It's a bigger problem to teach the integrator to be more rigorous about the difference between `log(x**2)` and `2*log(x)`.

**Comment by debugger22** [comment]
I don't know much about `sympy.integrals` but shouldn't this be done by `simplify`?

Probably `test_issue_4950` can go in.

**Comment by asmeurer** [comment]
The issue is that integrate performs an invalid transformation (under some assumptions). But this is a much bigger issue, and shouldn't block this. These tests work, so we should un-XFAIL them.

**Pull request merged**
