### PR TITLE
Edit README.md to add hyperlinks to relevant files

### PR DESCRIPTION
**Pull request by Arjun31415**
#### Brief description of what is fixed or changed

Added hyperlink on line 12 to AUTHORS file
Added hyperlink on line 19 to LICENSE file

#### Release Notes

 NO ENTRY

### CODE REVIEW

**Comment by sidhu1012** [comment]
Personally I don't think this would help much because not many people would like to go to `License` or `Authors` file.

**Comment by sidhu1012** [comment]
@Arjun31415 I see that you are a first time contributor to sympy, I think you should start with issues have `good first issue` or `easy to fix` labels if you want to contribute.

I also see that you are pushing from your master so I suggest you to read [this](https://github.com/sympy/sympy/blob/master/CONTRIBUTING.md).

**Comment by oscargus** [comment]
I think the changes here are worthwhile, but I agree with the other comments regarding https://github.com/sympy/sympy/issues?q=is%3Aopen+is%3Aissue+label%3A%22Easy+to+Fix%22 and not using master.

**Comment by Arjun31415** [comment]
> @Arjun31415 I see that you are a first time contributor to sympy, I think you should start with issues having `good first issue` or `easy to fix` labels if you want to contribute.
> 
> I also see that you are pushing from your master so I suggest you to read [this](https://github.com/sympy/sympy/blob/master/CONTRIBUTING.md).

Yes thank you i will look into `good first issue`
I'm sorry but I don't quite get you. Why should i not push from master and where in the Contributing readme should i find this.

**Comment by oscargus** [comment]
`master` is your local copy of the main Sympy repository. Right now, if you would like to update your local copy to the latest version, it will also be added to this PR (and that may lead to several hundred commits and files here, so no chance to see what was actually changed). In addition, having this modification in your local master will make it tricky to update it from the main Sympy repository, so you cannot (easily) get new features. Also, if you have multiple PRs, you can keep track of them separately.

Instead, please do create a branch for each PR/feature that you add, like:
`git checkout -b nameofbranch`

**Comment by Arjun31415** [comment]
thank you i will do that

**Pull request closed without merging**
