### PR TITLE
[ci skip] Update link in facts.py

### PR DESCRIPTION
**Pull request by jksuom**

### CODE REVIEW

**Comment by toolforger** [comment]
I see that the new link is still just a personal webpage; it will likely go away as the author moves to another institute.
That's not to mean I'm -1 about this, but it would be nice to find a more stable reference.

Wikipedia describes a generalization, and says how to get the Warshall algorithm from that; it's workable but not ideal.

**Comment by jksuom** [comment]
That particular paper was the exact model and it was moved...

**Comment by toolforger** [comment]
Oh, the Warshall algorithm is much older than that. It was originally published here:
Stephen Warshall: A Theorem on Boolean Matrices. In: Journal of the ACM 9, 1962, 1, ISSN 0004-5411, p. 11–12.
(My first encounter with it was somewhere in the 80ies, in a book by Niklas Wirth.)

That dvi is just a compact no-frills representation.
The original is available at http://citeseer.ist.psu.edu/viewdoc/summary?doi=10.1.1.89.7172

**Comment by jksuom** [comment]
> That dvi is just a compact no-frills representation.

I believe that was the reason for its inclusion.

**Pull request merged**
