### PR TITLE
Add the sphinx-copybutton extension to the docs

### PR DESCRIPTION
**Pull request by asmeurer**
This adds a button that copies the code in doctest example blocks.

I also updated the docs installation instructions to just use requirements.txt. 

#### Release Notes

- other
  - Add the sphinx-copybutton extension to the docs.

### CODE REVIEW

**Comment by bertiewooster** [comment]
I checked out this branch, built the documentation, and verified that the copy button works for copying code blocks.

I recommend merging.

**Review by bertiewooster — APPROVED** [review]
Code changes are logical.

**Comment by asmeurer** [comment]
Thanks for the review.

**Comment by KuldeepBorkar** [comment]
Thank You Sir @asmeurer for adding the `copy-button`, I was planning to do the same but thought I should discuss that if it is okay to add the copy-button or for some reasons it is not added.
I posted the message on gitter regarding the same with image on March 7 but no one responded at that time but thanks I wanted this expecially while learning more and more about sympy from the documentation : )

**Comment by bertiewooster** [comment]
@KuldeepBorkar Thanks for suggesting the `copy-button`. As @asmeurer noted in [analyzing the documentation survey](https://www.sympy.org/sympy-docs-survey/2021-docs-survey.html), the gitter site is little used:

> The Gitter chat room is the least popular response, with only 7.5% of respondents claiming to use it. It may be worth revisiting whether the chatroom is beneficial to the community.

so unfortunately it seems that no one who was working on the Sphinx theme update noticed your comment there. When there is an open pull request or issue on GitHub, I believe posting there is the best way to ensure that a related idea is noted by those already working on it.

This example suggests that the gitter site may be doing more harm than good: @KuldeepBorkar diligently posted a great suggestion, and it was not noted by those working on the feature. I suggest we seriously consider shutting down SymPy's gitter to avoid similar problems in the future, instead funneling communication through a smaller number of platforms.

**Comment by asmeurer** [comment]
Let's discuss the gitter thing on the mailing list. In general, if you have a feature suggestion, it's best to open an issue for it or use an existing issue or PR if relevant.

**Comment by asmeurer** [comment]
Also if you are looking for things to do regarding improving the documentation, there are still plenty of things that can be done. Just take a look at the "Documentation" label on the issue tracker.

**Pull request merged**
