### PR TITLE
laplace_transform(DiracDelta(t),t,s) = 1

### PR DESCRIPTION
**Pull request by zanzibar7**
- resolves issue #10840

### CODE REVIEW

**Comment by jksuom** [comment]
Would it be possible to just substitute 0 for ``Heaviside(0)``?

**Comment by zanzibar7** [comment]
It is possible that `Heaviside(0)` could appearing
in the integrand expression in other places for other reasons, and a `.subs(Heaviside(0),0)`
would indiscriminately treat these all the same.  The distributions we're interested in transforming are
all of the form `a(t) + b(t)*DiracDelta(t)`, so I've tried to keep the change narrow to that scope.
I'm open to more efficient and targetted alternatives.

**Comment by jksuom** [comment]
Have you got some other example in mind where ``Heaviside(0)`` would legitimately appear?

**Comment by zanzibar7** [comment]
There are situations 
where I can foresee this as a problem.  In evolutionary differential game theory, we often work with set-valued correspondences related to differential inclusions.  For example, `Heaviside(x) == Max(x,0).diff(x)`, where `Heaviside(0)` is the set of slopes of tangent lines.  A second-order condition, such as the need of the solution to track a singular manifold then selects out a particular, perhaps dynamic, value for `Heaviside(0)`.  Laplace transforms naturally appear in evolutionary games because discounted future returns are often calculated with the equation
```
∞              
⌠              
⎮       -δ⋅t   
⎮ f(t)⋅ℯ     dt
⌡              
0   
```
which some people like to right as a Laplace transform.  A blanket application of `Heaviside(0)==0` then leads to incorrect results.

**Comment by jksuom** [comment]
The trouble with pattern matching is that it only works with expression of very limited type. It is also difficult to predict which expressions would be properly matched. For example, with your patch I get
```
>>> laplace_transform((t + a + 1)*DiracDelta(t), t, s)
(a - Heaviside(0) + 1, -oo, True)
>>> laplace_transform((cos(t) + a)*DiracDelta(t), t, s)
(a - Heaviside(0) + 1, -oo, True)
```

If it is not possible to set ``Heaviside(0)`` always to 0 in Laplace transforms, then I think that integration of point measures should be generally improved (probably in ``deltaintegrate``) to dispense with the Heaviside function as an "indefinite integral". In order to make this work it seems also necessary to generalize the interface of ``integrate`` for definite integrals. Instead of limits of type ``(t, a, b)`` we should probably have something like ``(t, J)`` where ``J`` is an interval (or possibly a union of intervals, or even a more general set). The Laplace transform should then be an integral over the half open interval ``[0, oo)``. This would explicitly indicate that if a point measure (multiple of ``DiracDelta(t)dt``) is located at 0, it should be included in the integral. The evaluation of the integral should proceed with no need to introduce the Heaviside function. (Even ``integrate(DiracDelta(t), (t, Interval(0, 0)) = 1`` could be properly computed instead of attempting to evaluate something like ``Heaviside(0) - Heaviside(0)``.)

**Comment by zanzibar7** [comment]
Nuts.  I forget how dumb our pattern-matching is.  These particular counter-examples can
be fixed by conditionally repeating the pattern-matching to remove all additive terms with `Heaviside(0)` as a coefficient.

*Regarding the generalization of domains of integration*:   Yes!  This is something that was discussed a little back when I was implementing the superclass `ExprWithLimits` which is used by
`Sum`, `Product`, and `Integral`.  For `Sum`, we also wanted to be able to sum over sets, 
rather than oriented sequences which lead under the Karr convention to weird things like
```
In [11]: Sum(1/x/(x+1), (x,10,1))
Out[11]: 
  1             
 ____           
 ╲              
  ╲        1    
   ╲   ─────────
   ╱   x⋅(x + 1)
  ╱             
 ╱              
 ‾‾‾‾           
x = 10          

In [12]: _.doit()
Out[12]: -2/5
```
However, I am not sure what the formal theory or notational style would be for such.  It seems such a system would need to be able to express each of the following, as they all could take different values ...
```
In [10]: J = Integral(f(x),(x,y,b))

In [11]: Limit(J,y,a,dir='+')
Out[11]: 
     b        
     ⌠        
 lim ⎮ f(x) dx
y─→a⁺⌡        
     y        

In [12]: Limit(J,y,a,dir='-')
Out[12]: 
     b        
     ⌠        
 lim ⎮ f(x) dx
y─→a⁻⌡        
     y        

In [13]: J.subs(y,a)
Out[13]: 
b        
⌠        
⎮ f(x) dx
⌡        
a        
```
`integrate(f(x),(x,Interval.Lopen(a,b))` and `integrate(f(x),(x,Interval.(a,b))` seem to cover
the first and last, but not the middle one.

**Comment by zanzibar7** [comment]
There are more general situations as well, which have the form
```
      b             
      ⌠             
 lim  ⎮   f(x, y) dx
y─→0⁺ ⌡             
     a(y)
```

**Comment by zanzibar7** [comment]
I've looked this over, in light of us now having a heaviside function with an optional value at 0, and don't see any particular way to make it better.  But if there's a preferred alternative to pattern
matching to for simplifying expressions of the form
```
(a1+ a2 + ...) + (b1*Heaviside(0) + b2*Heaviside(0) ...)
```
I'm happy to consider it.

**Comment by mkoeppe** [comment]
Looks like this old PR can be closed? @hanspi42

**Comment by oscarbenjamin** [comment]
Yes, this isn't needed any more since #21469.

**Pull request closed without merging**
