### PR TITLE
Segment: also use dot product test for contains

### PR DESCRIPTION
**Pull request by cbm755**
This is coming from discussion in #13302 .

This currently fails at least one slow test.  So just RFC for now.  CC @jksuom, @siefkenj, for discussion.

### CODE REVIEW

**Comment by cbm755** [comment]
According to the tests,
````
p = Point(x,y)
L = Segment2D(Point2D(0, 0), Point2D(4, 4))
p in L
````
should be False.  Whereas I might've thought `None` in the usual SymPy way.  I don't know enough about the geometry module to know if this is deliberate.  It happens because `rank` is used in `is_collinear` and it behaves that way:
````
>>> Matrix([[1,0],[1,x]]).rank()
2
````

If this is how it is supposed to work, I cannot swap the order of the collinearity test and the dot prod tests...

**Comment by jksuom** [comment]
I would also have expected that `is_collinear(p, L.p1, L.p2)` return `None` in this case but that may be hard to arrange. Apparently `Point` regards `p` as a [generic point](https://en.wikipedia.org/wiki/Generic_point), i.e., a point whose coordinates are algebraically independent. Maybe we'll have to accept this.

**Comment by cbm755** [comment]
I reverted my swap.  And I found a new test for the triangle inequality stuff.

So I figure we can either:

(a) cherry-pick the test only to master: 0da2db501f6c11fb223d935b56ac046b0df674d4

(b) discuss whether adding back the dot prod test is desirable (this PR).

Thoughts?

**Comment by siefkenj** [comment]
Unfortunately sympy matrices assume symbols are different form other values in a matrix, so `Matrix([[1,0],[1,x]]).rank()` returns `2`, even though it made an assumption that `x != 0`. The `rref` routine, with a small modification, could be made to inform the user if any non-zero assumptions needed to be made (`_find_reasonable_pivots` reports its assumptions).

I knew there was some reason I used the triangle inequality, and it looks like complex symbols were it! The relationship between complex numbers and the geometry module seems weird at the moment. If a point is initialized with symbols, should those symbols be recast with the `real=True` assumption? Or should we allow complex numbers as entries and make all routines complex-friendly?

**Comment by cbm755** [comment]
I don't know enough about the `geometry` module to offer an informed opinion.  Numerically stable algorithms with Floats would be nice to have too.

**Comment by jksuom** [comment]
To say that a point `p` is in the segment `p1p2` means that `p = t*p1 + (1 - t)*p2` where `t` is in the interval `[0, 1]`. If the points are collinear then that is true for some `t` which can be explicitly computed from the coordinates (unless `p1 == p2`). Then there only remains to test whether that `t` is real and in the interval `[0, 1]`. That way there would be no need to declare everything real.

**Comment by czgdp1807** [comment]
@cbm755 @jksuom Please provide updates on this PR.

**Comment by czgdp1807** [comment]
@cbm755 Any updates on this?

**Comment by czgdp1807** [comment]
```python
>>> u, v, w, z = symbols('u, v, w, z')
>>> l = Segment(Point(u, w), Point(v, z))
>>> p = Point(2*u/3 + v/3, 2*w/3 + z/3)
>>> l.contains(p)
True
```
The above depicts that the tests in this PR pass on `master`. So, closing this for now. However, if there is a need please re-open this. Thanks.

**Pull request closed without merging**
