### PR TITLE
Enable development docs deployment from GitHub Actions

### PR DESCRIPTION
**Pull request by asmeurer**
The Travis builds no longer seem to be running, so the previous system with doctr is no longer working.

I have already set up an SSH deploy key and added the keypair to the respective repos.

I am making this PR against a branch in the main repo so that I can test it before merging it.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
@oscarbenjamin is it necessary for the sphinx build to depend on the doctest and test builds? If we removed it, the build would run faster which would lead to faster deployments when PRs are merged.

**Comment by asmeurer** [comment]
Are there any objections to removing .travis.yml? As I said, the builds don't seem to be running any more, ever since about a week ago.

**Comment by oscarbenjamin** [comment]
> @oscarbenjamin is it necessary for the sphinx build to depend on the doctest and test builds? If we removed it, the build would run faster which would lead to faster deployments when PRs are merged.

Usually on push to a PR there is no point in running the Shpinx build if the tests fail. Faster deployments don't really seem that important to me since we're talking about something like 40 minutes vs 20 minutes so it wouldn't be instantaneous anyway and it's unusual for anyone to care about the deployment time at all.

If that can be improved for free then go ahead but otherwise what is the trade off?

> Are there any objections to removing .travis.yml?

No

**Comment by asmeurer** [comment]
The deploy works https://github.com/sympy/sympy_doc/commit/c603f77305207e38c058f7c1e0002b08b64b1587#diff-905d01abc123746a6d92e5f67fadfb4438066024ace4d00e96a7bda89cd827d7 (see "last updated" date at the bottom of https://docs.sympy.org/dev/index.html).

**Comment by asmeurer** [comment]
There's actually a lot of mentions of Travis in the codebase as well as multiple files, so it may be cleaner to remove it in a separate PR.

**Comment by asmeurer** [comment]
I pushed a fix which should fix the authors build to work correctly on push builds.

**Comment by asmeurer** [comment]
I've made a PR at https://github.com/sympy/sympy/pull/24239 to remove Travis.

**Comment by asmeurer** [comment]
Any objections to merging this? The dev docs deployment will be broken until we do.

**Comment by oscarbenjamin** [comment]
Looks good to me. Changing the authors script is always fiddly so there might be hiccups but it's probably best to just try it and see.

**Pull request merged**
