### PR TITLE
Make doctest depend on antlr4 rather than antlr

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

See #8446 

#### Brief description of what is fixed or changed

Try changing dependency from antlr to antlr4 for doctests in `autolev/__init__.py`. Hopefully that means that the doctests won't be skipped...

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
Related to this, it looks like the `parse_latex` doctests are just skipped entirely. But they should be runnable with the same doctest_depends_on restriction.

**Comment by oscarbenjamin** [comment]
It looks like this makes the doctests in `autolev/__init__.py` run as hoped.

**Comment by oscarbenjamin** [comment]
I've enabled the parse_latex doctests

**Comment by oscarbenjamin** [comment]
Looks like this is working for both the `autolev/__init__.py` and `latex/__init__.py` doctests.

**Comment by asmeurer** [comment]
I think the test failure is an unrelated random error. I didn't restart the build because I don't know if it's a known issue that we should log an issue for.

**Comment by oscarbenjamin** [comment]
I've seen that on other PRs it is known (to me at least) as an unrelated random error. We should log an issue for it. It seems there are a whole bunch of problems with tensorflow including all the warnings as well.

**Comment by oscarbenjamin** [comment]
I've opened #17951 for the failure

**Comment by oscarbenjamin** [comment]
I've restarted the failed job on Travis.

**Pull request merged**
