### PR TITLE
Matrix inverse: gcdex for inv_mod

### LINKED ISSUE #14344: inv_mod in matrices.py uses totient calculation
The implementation of matrix inverse for given mod uses [totient calculation](https://github.com/sympy/sympy/blob/master/sympy/matrices/matrices.py#L2694) for modular inverse of determinant.
This increases the overall complexity of the algorithm, while it can be done more efficiently by extended euclidean algorithm.

### LINKED ISSUE #14345: Inverse of a matrix for prime fields is not optimal
Currently, SymPy uses adjugate matrix calculation for [inv_mod](https://github.com/sympy/sympy/blob/master/sympy/matrices/matrices.py#L2699), which requires `n^2` determinants to be calculated of matrices of size `(n-1) x (n-1)`, for a `n x n` matrix adjugate. This makes the overall complexity for inverse calculation to be `O(n^5)`.

Since, `Gaussian Elimination` works for fields, inverse of matrices in prime fields can be easily obtained in `O(n^3 lg(p))` where `lg(p)` is the time required for finding modular inverse of a number modulo `prime p`.

For practical usage, the difference will become evident as the size of matrices exceeds `30`.

### PR DESCRIPTION
**Pull request by sidhantnagpal**
#### References to other Issues or PRs
Fixes #14344 

#### Brief description of what is fixed or changed
For matrix inv_mod, changed modular inverse calculation of determinant from Euler Totient Method to mod_inverse (that uses Extended Euclidean Algorithm) - handled in this PR.

#### Other Comments
Matrix inverse for fields will be handled in different PR, as [discussed](https://github.com/sympy/sympy/pull/14347#issuecomment-377507997) with @jksuom.
See #14345 for further discussion.

### CODE REVIEW

**Comment by sidhantnagpal** [comment]
@normalhuman @jksuom Please review.

**Comment by Roland-Sands** [comment]
Elimination can be used to get reduced row echelon form for matrices over fields
In particular it will hold over all finite fields, fields with `p**n` elements

If you stop at echelon form then fields are not necessary

**Comment by Roland-Sands** [comment]
I would love to see support for function fields

**Comment by sidhantnagpal** [comment]
> In particular it will hold over all finite fields, fields with p**n elements.

Yes, since finite fields are only of the form `p**n`, it will hold. Though checking the modulo of the form `p**n` will be more involved. 

> Elimination can be used to get reduced row echelon form for matrices over fields

Yes, since reduced echelon form does not require existence of inverse elements, and rref does.

**Comment by sidhantnagpal** [comment]
Since, the finite field `F_{p^n}` is not the same thing as the ring of integers modulo `p^n` (except in the case n=1, of course), will require an additional restriction, for matrix to have elements belonging to this field. So, I think `prime field` support can be added natively to existing code.

**Comment by Roland-Sands** [comment]
Instead of working with `F_q`, where `q = p**n`, would it be better to explicitly work with `F[x]/<g(x)>`, (the polynomial ring over `F` factored by the ideal generated by `g(x)`) where `F` is the integers modulo `p`, and `g(x)` is an irreducible polynomial over `F` of degree `n`

**Comment by sidhantnagpal** [comment]
That will be helpful, though it will require more intensive implementation, and I think it could be a separate issue, for that matter. Thanks for the explanation.

**Comment by jksuom** [comment]
I would prefer having matrix inversion code independent of the coefficient field. That would be possible with a matrix class that wouldn't try to sympify its entries. Instead, it would convert its inputs into elements of the coefficient domain. (`RawMatrix` can be used before a better version is implemented.)

**Comment by sidhantnagpal** [comment]
@jksuom Actually, while implementing I also thought that it would be better to have operations defined for separate fields (that way the code would be modular and matrix inversion would work seamlessly), but turns out we actually only require this for prime fields (finite). That is why I went with it. 
So, how should we handle this?

**Comment by jksuom** [comment]
I would investigate how the current public methods would work with matrices over prime fields. I would expect that no big changes would be needed.

**Comment by sidhantnagpal** [comment]
@jksuom Thanks for the review, will look forward to the suggestions.

**Comment by sidhantnagpal** [comment]
@jksuom This looks good to me. Do you suggest any changes (ie separate methods for prime modulo) or better patch for commits in this PR corresponding to #14345?

**Comment by jksuom** [comment]
I think that the central matrix methods, including inverse, should be independent of the coefficient field. All arithmetic operations should be taken care of by the methods defined by the field. In case of prime fields F_p, the methods of its dtype (ModularInteger) should be used automatically. There should be no need for a new keyword `prime` in the matrix module (though there could be a more general `ring` argument).

I know that this cannot currently be implemented as easily as it should be because matrix entries are sympified when a matrix is created and the elements of F_p cannot be sympified. A workaround applied elsewhere in polys is defining a subclass RawMatrix that does not sympify its arguments. That can be used to compute with F_p. A better solution would be making the `_sympify` attribute of Matrix a function converting its  arguments to elements of F_p. The coefficient ring (or field) should also be added as an attribute. That would also be necessary for the proper implementation of `zeros` and `eye` (zero and one of the ring instead of S.Zero and S.One).

**Comment by sidhantnagpal** [comment]
@jksuom Thank you for the explanation. So, should I make the desired changes in this PR itself or open a separate PR for #14345, which will make this PR fix only #14344 (and a minor typo in docstring).

**Comment by jksuom** [comment]
I would close this PR and try to make a subclass of matrices that would accept entries in any given (but fixed) ring (not necessarily commutative). Once the methods work uniformly for all rings, it would be possible to improve the methods for some specific types of rings, e.g. finite fields. The same API should work for all rings. (The methods could inspect the properties of the ring whenever desired, is_field, characteristic, etc. It should not be necessary to include the characteristic prime in the API.)

**Comment by sidhantnagpal** [comment]
Okay, but #14344 is also fixed in this PR.
So let's separate #14345 into a different PR for building the subclass of matrices (which doesn't sympify its entries) for all rings.
I will retain fixes of #14344 only in this PR then.

**Review by sidhantnagpal — COMMENTED** [review]
@jksuom 
I only made 3 changes for `mod_inverse` import, method `inv_mod` and typo fix for `the`.
git diff on github is showing excessive changes.

As a side note, I committed to matrices.py from current master branch.

**Comment by sidhantnagpal** [comment]
@jksuom Made the changes for this PR. 
For prime field, should we first discuss the API, methods, args required for its implementation in a separate issue, as you suggested the use of `RawMatrix` and `field` argument.

**Comment by jksuom** [comment]
I think that `RawMatrix` is only a partial solution. It is an example of a subclass of matrices not sympifying their entries. But it is not an ideal solution. Most methods work well but some, like `zeros` and `eye`, will have to be redefined. One way to do that would be adding a class attribute `ring` (a field is a ring, too) that would be automatically inherited by all instances. (It could be `EX` by default.)

**Comment by sidhantnagpal** [comment]
> But it is not an ideal solution.

So should we discuss a better solution in a separate issue, as you mentioned it is a partial solution.

And is this PR fine, now?

**Comment by jksuom** [comment]
> And is this PR fine.

Extension of Cholesky decomposition to complex matrices looks fine to me. The title (and opening paragraph) should probably be edited accordingly.

>  discuss a better solution in a separate issue

Yes, I think that is necessary. Some experimental coding will also be needed.

**Comment by sidhantnagpal** [comment]
@jksuom See [this](https://github.com/sympy/sympy/pull/14347#pullrequestreview-108359539). I didn't author those commits.
I have changed the title and description of PR according to the commits I made (mentioned in the link).

**Comment by sidhantnagpal** [comment]
> Yes, I think that is necessary. Some experimental coding will also be needed.

@jksuom Further discussions, as referenced in PR #14345.

> The title (and opening paragraph) should probably be edited accordingly.

Changed the description, according to the commits.

As a side note, the commits made in this PR, can be seen by running `diff --git` with current master.

**Review by sidhantnagpal — COMMENTED** [review]
The file `matrices.py` contains commits already made in master. This looks good to me @jksuom.

**Comment by jksuom** [comment]
> The file matrices.py contains commits already made in master. 

It seems that only the `inv_mod` bit is new. That looks good to me, thanks.

(BTW, `diff --git` only gives `diff: unrecognized option '--git'` on my system. But `git diff master -- ...` works.)

**Comment by sidhantnagpal** [comment]
Thanks @jksuom.

**Pull request merged**
