### PR TITLE
make test_perm_groups more PEP-8 compliant

### PR DESCRIPTION
**Pull request by michelececcacci**
#### Brief description of what is fixed or changed

Improving PEP-8 compliance

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by hanspi42** [comment]
Looks OK, but my question would be, while you are at it, wouldn't you prefer to correct more pep8-non-compliant things semi-automatically? test_perm_groups.py still has several more pep8 violations.

Are you using Spyder? If yes, you can switch on "Show Code Style Warnings" in the menu Source, and then you see all warnings. If you mark a few lines, then you can use "Format file or selection with autopep8" in the Source menu, which often gives a good result (not always), so you might not want to do the whole file at once.

**Comment by michelececcacci** [comment]
Hi! I'm currently using vscode with ruff! I never used spyder, but i can give it a try.

**Comment by hanspi42** [comment]
Maybe I will ask @sylee957 first: @michelececcacci fixes PEP-8; how much / how extensively is it worthwhile in your opinion to do it?  Should the lambdas be fixed when found? PEP-8: "Always use a def statement instead of an assignment statement that binds a lambda expression directly to an identifier."

**Comment by sylee957** [comment]
> PEP-8: "Always use a def statement instead of an assignment statement that binds a lambda expression directly to an identifier."

I think that it is good to rely less on lambda and write functions to have meaningful names though.

**Pull request merged**
