### PR TITLE
Amended issue #9946

### PR DESCRIPTION
**Pull request by jremes-foss**
Amended issue number #9946.

Changed

Returns if a function is decreasing or not, in the given
Interval.

To:

Returns if a function is strictly decreasing or not, in the given
Interval

Thank you.

### CODE REVIEW

**Comment by gxyd** [comment]
:+1:

**Comment by gxyd** [comment]
Though this could have a better commit message, instead of just "Amended issue 9946". A better commit message could be, "updated docstring of is_strictly_decreasing".

**Comment by Newman101** [comment]
Hi. Sorry for short commit message, I will be more careful next time. =)

**Comment by gxyd** [comment]
This was a smaller issue, some other changes were also required to be made. I have fixed this in PR #9951 . So the PR can be closed, i am closing the corresponding issue.

**Comment by Newman101** [comment]
Sure, I will close the PR then. Thanks for a swift response.

**Comment by gxyd** [comment]
Sorry for your wasted effort.

**Comment by Newman101** [comment]
No worries. =)

**Pull request closed without merging**
