### PR TITLE
Fix some more lgtm alerts

### PR DESCRIPTION
**Pull request by rneatherway**
Hi, I have been taking a bit more of a look over the [lgtm.com alerts](https://lgtm.com/projects/g/sympy/sympy/alerts/), and fixed a few more here. Follows https://github.com/sympy/sympy/pull/12643

Hope it's a useful bit of tidying!

### CODE REVIEW

**Comment by asmeurer** [comment]
These all seem correct. Do you know what tool they are using that can detect these things?

**Review by asmeurer — APPROVED** [review]

**Comment by rneatherway** [comment]
Full disclosure: I'm one of the developers, hence my interest! The analysis is done by converting the code into a [database](https://lgtm.com/docs/lgtm/tech/generate-db), and then writing queries against that database in an object-oriented [query language](https://lgtm.com/docs/ql/about-ql). You can see the source of the default queries on the website, for example 'Unnecessary pass': https://lgtm.com/query/rule:910088/project:16060037/lang:python/, and even play around with writing your own queries in the query console there.

**Comment by asmeurer** [comment]
I see. So the fixes are done by hand, I take it. 

I'm mostly curious about the change in sympy/liealgebras/cartan_type.py. How smart is it actually being there to notice that? Is it doing real type inference, to notice that `n` is an integer, or does it just assume that `not (n < 0)` implies `n >= 0`?

I'm also wondering what the false positive rate is like for it. That tends to be the most annoying thing for me when using a linter.

**Comment by rneatherway** [comment]
> I see. So the fixes are done by hand, I take it.

Yes, that's right.

> I'm mostly curious about the change in sympy/liealgebras/cartan_type.py. How smart is it actually being there to notice that? Is it doing real type inference, to notice that n is an integer, or does it just assume that not (n < 0) implies n >= 0?

It's done with a kind of flow analysis, so the query library has built up a notion of which values can flow into which variables, and in this case, the conversion to `int` on line 14 and the subsequent `n < 0` guard are sufficient to guarantee that n is a non-negative integer.

> I'm also wondering what the false positive rate is like for it. That tends to be the most annoying thing for me when using a linter.

Of course that is a tough one to answer. We are always trying to improve the accuracy of our analyses, and feedback is welcome on our community forum at https://discuss.lgtm.com/.

Personally, I find working with the analysis most useful as a PR check, when the results are specific to code that I am currently working on, and generally limited in number to being roughly proportional to the size of the PR.

**Pull request merged**
