### PR TITLE
fix Mul.as_coefficients_dict()

### PR DESCRIPTION
**Pull request by rwst**

### CODE REVIEW

**Comment by jksuom** [comment]
The same functionality is currently implemented in `polys`, though not exactly in the expected form. It can even take care of coefficients that are algebraic numbers. Several methods in `Expr` are wrappers for methods in `polys`. That could also be possible in case of `Expr.as_coefficients_dict`. Even a separate `Add.as_coefficients_dict` would not be needed.
```
from sympy.polys.monomials import Monomial
from sympy.polys.polyutils import dict_from_expr
rep, gens = dict_from_expr(expr, extension=True)
return {Monomial(m, gens).as_expr(): rep[m] for m in rep}
```
(The purpose of `extension=True` is to include algebraic numbers in the coefficients.)

**Comment by smichr** [comment]
I am presently -1 to the change.

The docstring for `Expr.as_coefficients_dict` starts as follows: "Return a dictionary mapping terms to their Rational coefficient." `3.0` is not a `Rational`, it is a `Float` with limited precision. There are special things we can do with Rationals that we can't do (without silent assumtions) with Floats.

**Comment by rwst** [comment]
Well, it was considered a bug on gitter, and I still think so as long as the name `as_coefficients_dict` does not reflect the restriction to rational. So I propose to rename it to `as_rational_coefficients_dict` and add the PR code under the name `as_coefficients_dict`.

**Comment by smichr** [comment]
> I propose to rename it

It was my impression that "coeff" is nearly synonymous with "Rational in slot 0" when it comes to expressions, e.g. 'Expr.as_coeff_Add'. I checked out `Expr.as_coeff_Mul`, however, and found

```
>>> help(Expr.as_coeff_Mul)
as_coeff_Mul(self, rational=False) unbound sympy.core.expr.Expr method
    Efficiently extract the coefficient of a product.
>>> (3.*x).as_coeff_Mul()
(3.00000000000000, x)
```

So there is precedent for your change. What I would suggest is that you add a `rational=True` flag to `as_coefficiients_dict`. This would give the option to extract Floats if so desired while maintaining backward compatibility. Without reviewing use cases in the code base I can't say whether it would be a better idea to make the default be `False`. I defer to someone else on this.

**Comment by jksuom** [comment]
It seems that `as_coefficients_dict` is only used in `diophantine` to verify that the coefficients of a diophantine equation are really integers. In its current form the test will accept expressions like `2.5*x**2 *y`, which is not correct (even though that may have no effect on the set of solutions).

I'd prefer having `as_coefficients_dict` return all numerical factors as coefficients. It would probably be possible to develop another method for the separation of rational and nonrational factors of a numerical expression if necessary.

**Comment by smichr** [comment]
> In its current form the test will accept expressions like

Thanks for looking into this. I'm surprised this is not used more. 

The way that `as_coefficients_dict` is used in diophantine, any coefficient that is returned that can't pass `_as_int` will fail. So changes of this PR will not affect the cse behavior. So it looks like if it is important to limit the coefficients to be Rational, a flag (as mentioned in my previous post) could be added, defaulting to `rational=False` as is the case for `as_coeff_Add`.

> prefer having as_coefficients_dict return all numerical factors

If you want coefficients to be more than Numbers then the current PR could perhaps use

```
d = defaultdict(int)
ind, dep = self.as_independent(*self.free_symbols)
d[dep] = ind
return d
```

I have no objections to the current PR since a coefficient is generally regarded as what is a number in slot 0, e.g. (sqrt(2)*x).as_coeff_Mul() returns `1` for the coefficient..

**Comment by rwst** [comment]
So if I understand it right, there are no objections but a suggestion to use `(rational=False)`?

**Comment by jksuom** [comment]
That appears to be so. Though I am still having doubts about the need for the functionality of `rational=True`, which is currently used nowhere. I think that if some application has to make a distinction between rational and nonrational parts of a coefficient, that could best be solved by means of a specialized method applied on the values produced by `as_coefficients_dict`, That way no numerical components, e.g. floats, would appear in the keys.

**Comment by smichr** [comment]
If your suggestion that *any* numerical coefficient be returned, @jksuom , then the current PR will have to be modified as I suggested above. Do you think that should be added in this PR?

**Comment by jksuom** [comment]
I have no definite opinion on exactly what kind of numerical coefficients should be returned. There are several possibilities. In any case, I think that both rational and floating point numbers should be accepted.

In `polys. _parallel_dict_from_expr_no_gens` there are many options (controlled by keywords on a higher level). The default is `factor.is_Number`, which includes rational and floating point numbers.  If `greedy=False` (not set by default), then the test is `factor.is_number`, which adds algebraic numbers and transcendental numbers like `pi` and `E`. In many cases it is convenient to treat transcendental numbers as independent variables (which they actually are from the algebraic point of view). Then setting `extension=True` will include algebraic numbers like `sqrt(2)` and `GoldenRatio` but no transcendental numbers.

I would prefer to have these options available also in `as_coefficients_dict`. That could easily be implemented by calling `dict_from_expr(expr, **kwargs)` with a suitable keyword argument. What would you think of that kind of implementation?

**Comment by smichr** [comment]
> I would prefer to have these options available also in as_coefficients_dict. That could easily be implemented by calling dict_from_expr(expr, **kwargs) with a suitable keyword argument. What would you think of that kind of implementation?

I'm ok with that. It seems, then, that this can be committed as is and any modifications left for a future PR. BTW I am in favor of trying to keep modification routines unified in terms of the kwargs that are used.

**Comment by rwst** [comment]
Thanks for the review.

**Pull request merged**
