### PR TITLE
2 fixes for `Circle` from equation

### LINKED ISSUE #23264: Circle from equation has error in formula -> wrong radius
With current master:
```
In [1]: from sympy.geometry import Circle

In [2]: eq = (x - 1)**2 + y**2 - 9

In [3]: expand(2*eq)
Out[3]:
   2            2
2⋅x  - 4⋅x + 2⋅y  - 16

In [4]: Circle(_3)
Out[4]: Circle(Point2D(1, 0), sqrt(17))
```
The circle has a radius of 3 (see `eq`), not sqrt(17). This is because a wrong handling of equations where `x**2` and `y**2` have a coefficient different from 1.

Also, with the same equation `eq` as above:
```
In [5]: Circle(eq)
---------------------------------------------------------------------------
NonlinearError                            Traceback (most recent call last)
~/sympy3/sympy/geometry/ellipse.py in __new__(cls, *args, **kwargs)
   1566             try:
-> 1567                 a, b, c, d, e = linear_coeffs(equation, x**2, y**2, x, y)
   1568             except ValueError:

~/sympy3/sympy/solvers/solveset.py in linear_coeffs(eq, *syms, **_kw)
   2471         return d  # default is still list but this won't matter
-> 2472     raise NonlinearError('nonlinear term encountered: %s' % t)
   2473

NonlinearError: nonlinear term encountered: (x - 1)**2

During handling of the above exception, another exception occurred:

GeometryError                             Traceback (most recent call last)
<ipython-input-5-53c289b8e5ff> in <module>
----> 1 Circle(eq)

~/sympy3/sympy/geometry/ellipse.py in __new__(cls, *args, **kwargs)
   1567                 a, b, c, d, e = linear_coeffs(equation, x**2, y**2, x, y)
   1568             except ValueError:
-> 1569                 raise GeometryError("The given equation is not that of a circle.")
   1570
   1571             if S.Zero in (a, b) or a != b:

GeometryError: The given equation is not that of a circle.
```
I'll file a PR shortly.

### PR DESCRIPTION
**Pull request by gschintgen**
#### References to other Issues or PRs

Fixes #23264

#### Brief description of what is fixed or changed
With this PR both issues described in #23264 are fixed. Example session:
```
In [1]: from sympy.geometry import Circle

In [2]: eq = (x - 1)**2 + y**2 - 9

In [3]: expand(2*eq)
Out[3]:
   2            2
2⋅x  - 4⋅x + 2⋅y  - 16

In [4]: Circle(_3)
Out[4]: Circle(Point2D(1, 0), 3)

In [5]: Circle(eq)
Out[5]: Circle(Point2D(1, 0), 3)
```
Previously, the first `Circle` call would return an incorrect radius and the second one would throw an exception.

#### Release Notes

* geometry
  * Fixed `Circle` from equation (wrong radius in some cases; allow non-expanded equation).

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
You are listed in the .mailmap file as:
```
Gilles Schintgen <gschintgen@hambier.lu>
```
Somehow the AUTHORS script finds this metadata:
```
Gilles Schintgen <gschintgen@users.noreply.github.com>
```
The line in .mailmap should be changed to
```
Gilles Schintgen <gschintgen@hambier.lu> Gilles Schintgen <gschintgen@users.noreply.github.com>
```
I'm not sure what causes this though. Did you make any of the commits with the GitHub web UI or did you make them all locally with git?

**Comment by gschintgen** [comment]
> You are listed in the .mailmap file as:
> 
> ```
> Gilles Schintgen <gschintgen@hambier.lu>
> ```
> 
> Somehow the AUTHORS script finds this metadata:
> 
> ```
> Gilles Schintgen <gschintgen@users.noreply.github.com>
> ```
> 
> The line in .mailmap should be changed to
> 
> ```
> Gilles Schintgen <gschintgen@hambier.lu> Gilles Schintgen <gschintgen@users.noreply.github.com>
> ```
> 
> I'm not sure what causes this though. Did you make any of the commits with the GitHub web UI or did you make them all locally with git?

That's unexpected. I did them all locally. And it's even the same development container that I used previously to submit PRs to sympy. Locally `git log` shows my regular email address. I may have enabled the "keep email private" setting some time ago in GitHub's settings. But that shouldn't interfere with the actual commits?

I'd rather not want to litter the .mailmap file but I'm not sure if it's sufficient to disable email privacy (which, at this point, is probably rather pointless anyway.) I've unticked the box in github's settings, but I'm not sure if that will take effect for the current PR.

**Comment by oscarbenjamin** [comment]
> I'd rather not want to litter the .mailmap file

The way that the .mailmap file is used has changed since you last submitted a PR so it is now required. All commits need to be mapped to a single author who is then listed in the AUTHORS file. Note that you are already in that file (anyone who has any commits is in there). It also needs to be updated with this alternate alias though so the line should be changed to what I said above to associate that alias with you.

There's something about the way that this script runs in CI that makes this happen. If I checkout this PR locally then the .mailmap seems fine:
```console
$ bin/mailmap_check.py 
No changes needed in .mailmap

The following authors will be added to the AUTHORS file at the time of
the next SymPy release.

	Andrii Oriekhov <andriyorehov@gmail.com>
	Arie Bovenberg <a.c.bovenberg@gmail.com>
	Gaurav Jain <gjain369@gmail.com>
	Luis Talavera <luisfertalavera15@gmail.com>
	Shivam Sagar <technoshivam12@gmail.com>
	Siddhant Jain <siddhantashoknagar@gmail.com>
	Sumit Kumar <mr.sumitkrr@gmail.com>
	Tirthankar Mazumder <63574588+wermos@users.noreply.github.com>
```
I think that the difference is that in CI this script runs on a new commit that is made by merging the PR into master sort of like this:
```
git checkout master
git checkout -b tmp_ci_branch
git merge fix-circle-eq  # <--- new merge commit
```
That new commit is created implicitly by GitHub Actions and I guess it must be that commit that uses the noreply email address which is then picked up by the `mailmap_check.py` script when it runs in CI.

> I've unticked the box in github's settings, but I'm not sure if that will take effect for the current PR.

I'm interested to know if that is the cause so I'll try closing and reopening this to rerun CI...

**Comment by oscarbenjamin** [comment]
> > I've unticked the box in github's settings, but I'm not sure if that will take effect for the current PR.
> 
> I'm interested to know if that is the cause so I'll try closing and reopening this to rerun CI...

It seems that the AUTHORS check now passes. That resolves something that was a bit of a mystery to me for a while.

**Comment by oscarbenjamin** [comment]
Looks good. Thanks!

**Pull request merged**
