### PR TITLE
Catalan rewrite and doctests for latex equations

### PR DESCRIPTION
**Pull request by cbm755**
First, implement `S.Catalan.rewrite(Sum)`.

Also, something I've been thinking about for while: we have lots of LaTeX in our docs.  In many cases we could generate those equations ourselves instead of typing them manually (I found errors while doing #11014 for example).

This PR should demonstrate the idea.  @asmeurer what do you think?  Will this work?  Its certainly nice for maintainance, although it is probably slightly less readable...

(If we want to do this widely, the latex printer could probably be optimized for things like `^{2}` and when it uses `\left(` instead of `(`.)

#### Release notes

* core
  * Catalan can be rewritten as a sum

### CODE REVIEW

**Comment by asmeurer** [comment]
Does this actually work?

**Comment by asmeurer** [comment]
Actually this works

```diff
diff --git a/sympy/core/numbers.py b/sympy/core/numbers.py
index f65e053b0c..015789f82a 100644
--- a/sympy/core/numbers.py
+++ b/sympy/core/numbers.py
@@ -3756,7 +3756,8 @@ class Catalan(with_metaclass(Singleton, NumberSymbol)):
     `K = 0.91596559\ldots` is given by the infinite series
 
     >>> from sympy import S, latex, Sum
-    >>> print(".. math:: K = " + latex(S.Catalan.rewrite(Sum)))
+    >>> print("\n.. math:: K = " + latex(S.Catalan.rewrite(Sum)))
+
     .. math:: K = \sum_{k=0}^{\infty} \frac{\left(-1\right)^{k}}{\left(2 k + 1\right)^{2}}
 
     Catalan is a singleton, and can be accessed by ``S.Catalan``.

```

screen shot 2018-07-24 at 4 10 13 pm

But even so, I don't like it. Doctests are supposed to be examples for users, and convoluting them with RST directives just makes things more complicated. So if we were to do this, I would rather do like I said and create a Sphinx extension that lets you write 

```
:sympy:`S.Catalan.rewrite(Sum)`
```

and it would replace it with a `:math:` directive with `latex(S.Catalan.rewrite(Sum))`.

We could even make it a separate project. I think it could be useful to others as well.

**Comment by czgdp1807** [comment]
@asmeurer Can I apply your diff given above to continue this PR?

**Comment by cbm755** [comment]
@czgdp1807 probably you should just cherry-pick the Catalan rewrite part.  The rest of is needs more discussion.

Or if you're prefer I do that, let me now.

**Pull request closed without merging**
