### PR TITLE
[WIP] Using scipy.stats to sample Inverse Gamma

### LINKED ISSUE #7358: Use scipy.stats when sampling from sympy.stats distributions
The `sample` operation samples a random expression. 

```
>>> X = Normal('X', 0, 1)
>>> sample(100 + X)
100.325245
```

This depends on `*Distribution.sample` methods for each type of distribution (like `NormalDistribution`.)  These methods often call out to a sampling method in the `random` stdlib module.  When these methods do not exist we attempt to create one analytically by computing the CDF of the distribution.

In some cases the distribution is not found in `random` and the computation of the CDF is difficult.  When these two happen together it breaks our ability to sample.

One way to resolve this issue is to depend on the `scipy.stats` module instead of `random`, which is generally far more comprehensive.  This dependence would need to be shielded in case `scipy` wasn't present on the user's machine.

If someone wanted to fix this they should look at `sympy/stats/crv_types.py`, take a look at `GammaDistribution.sample` (works) and then try to implement the same thing for `GammaInverseDistribution.sample` (does not yet exist) using `scipy.stats.invgamma`.  Once that works there are several more!

### PR DESCRIPTION
**Pull request by tokencolour**
Uses scipy.stats.invgamma to sample for class GammaInverseDistribution
Trying to fix #7358

### CODE REVIEW

**Comment by tokencolour** [comment]
This does not work. I am trying to figure out a way.  The problem here is as explained below:
I am trying to execute this with the changed code:
```
from sympy.stats import GammaInverse, sample
X=GammaInverse('X', 1, 1)
samp=sample(X)
print(samp)
```
When the control encounters the line `samp=sample(X)` it goes on to rv.py , line 806
```
def sample(expr, condition=None, **kwargs):
    return next(sample_iter(expr, condition, numsamples=1))
```
and there on moves to sample_iter in the same file, line 837
```
def sample_iter(expr, condition=None, numsamples=S.Infinity, **kwargs):
    try:
        return sample_iter_lambdify(expr, condition, numsamples, **kwargs)
```
and hence moves to method `sample_iter_lambdify` in the same file again, line 862
```
def sample_iter_lambdify(expr, condition=None, numsamples=S.Infinity, **kwargs):
    """
    See sample_iter

    Uses lambdify for computation. This is fast but does not always work.
    """
    if condition:
        ps = pspace(Tuple(expr, condition))
    else:
        ps = pspace(expr)

    rvs = list(ps.values)
    fn = lambdify(rvs, expr, **kwargs)
    if condition:
        given_fn = lambdify(rvs, condition, **kwargs)

    # Check that lambdify can handle the expression
    # Some operations like Sum can prove difficult
    try:
        d = ps.sample()  # a dictionary that maps RVs to values 
```
goes on to file crv.py, line 367
```
def sample(self):
        """
        Internal sample method

        Returns dictionary mapping RandomSymbol to realization value.
        """
        return {self.value: self.distribution.sample()}
```
And from here the control goes to crv.py, line 171
```
class SingleContinuousDistribution(ContinuousDistribution, NamedArgsMixin):
    set = Interval(-oo, oo)
    def __new__(cls, *args):
        args = list(map(sympify, args))
        return Basic.__new__(cls, *args)

    @staticmethod
    def check(*args):
        pass

    def sample(self):
        """ A random realization from the distribution """
        icdf = self._inverse_cdf_expression()
        return icdf(random.uniform(0, 1))
```
so as to compute a sample by inverse sampling method, probably. In my opinion, from here the control must go to the file I just changed, i.e. crv_types.py to
```
class GammaInverseDistribution(SingleContinuousDistribution):
    _argnames = ('a', 'b')

    set = Interval(0, oo)

    @staticmethod
    def check(a, b):
        _value_check(a > 0, "alpha must be positive")
        _value_check(b > 0, "beta must be positive")

    def pdf(self, x):
        a, b = self.a, self.b
        return b**a/gamma(a) * x**(-a-1) * exp(-b/x)

    def sample(self):
        try:
            import_module('scipy.stats')
        except ImportError:
            raise ImportError("can't import scipy.stats")
        inv_g = scipy.stats.invgamma(self.a, self.b)
        return inv_g(1)[0]
```
And may be this inverse sampling function is returning a set (which can't be indexed) and therefore, throwing error:
```
TypeError: 'FiniteSet' object does not support indexing
```
What am I missing? How should I make this behave the normal, expected way? @leosartaj, Please take a look into this.

**Comment by tokencolour** [comment]
@mrocklin Can you please help me with this?

**Comment by tokencolour** [comment]
@moorepants Can you please help me with this?

**Comment by moorepants** [comment]
I don't know anything about this.

**Comment by sidhantnagpal** [comment]
PR #14250 has been merged, adding scipy for sampling the inverse gamma distribution. You can go ahead and try to fix #7358 after resolving the conflicts.

**Comment by leosartaj** [comment]
Hi, It looks like this is not being worked on anymore. I am closing this.

**Pull request closed without merging**
