### PR TITLE
Dropping Python 2 support 

### PR DESCRIPTION
**Pull request by namannimmo10**
#### References to other Issues or PRs

#17943 

#### Brief description of what is fixed or changed
 --> Removes `unichr`, `long`, `Iterator` and `round` imports from compatibility since python-2 support is dropped. 
 
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by namannimmo10** [comment]
@asmeurer, I suggest that we can also remove `from __future__ import <something>` from all the files.

**Comment by asmeurer** [comment]
Yes, the `__future__` imports can be dropped.

**Comment by sylee957** [comment]
I think that things can be deleted one by one.
But are you going to work on this more, on dropping `__future__`?

**Comment by namannimmo10** [comment]
Yes, I'll further clean up compatibility and also remove `__future__` imports from the codebase.

**Comment by namannimmo10** [comment]
@sylee957, I'm trying to remove `__future__` imports using sed. 
```
sed --in-place '/from __future__ import/d' sympy/simplify/tests/test_trigsimp.py
```
This works only for specific files... But how do I delete all such instances (from all the files) in a directory? 
This doesn't work: `sed -i.bak '/from __future__ import/d' /home/namannimmo/sympy/*`

**Comment by namannimmo10** [comment]
@asmeurer, Please review this.

**Comment by namannimmo10** [comment]
This can be merged now!

**Comment by namannimmo10** [comment]
I think this can be merged as it is. Removing `__future__` imports will take a considerable amount of time because there are so many files to deal with.

**Pull request merged**
