### PR TITLE
It fixes the problem of the integral not being solved by SymPy.

### PR DESCRIPTION
**Pull request by abaokar-07**
I have fixed the problem of integral. This code now gives the answer of this integral. I have made 't' positive because if it becomes negative, the whole function will become complex and as integral means area under the curve, we cannot find the integral.

@asmeurer Please review it, and tell me what's wrong(if it is)

### CODE REVIEW

**Comment by gamer-sparckzz** [comment]
@smichr please review it

**Comment by debugger22** [comment]
Did you add a file with the name `Fixes the issue #11813`?

**Comment by gamer-sparckzz** [comment]
@debugger22 I have now added a file

**Comment by debugger22** [comment]
> `Fixes the issue #11813.py`

This isn't what a sympy filename should look like. You should explore through the existing codebase before working on anything. You should also read the development workflow on the wiki.

**Comment by gamer-sparckzz** [comment]
I have changed the file name, is it okay now or it is still wrong?

@debugger22

**Comment by gamer-sparckzz** [comment]
Is there something wrong with the code @debugger22

**Comment by gamer-sparckzz** [comment]
What should I do to have this merged in the master branch @debugger22

**Review by asmeurer — CHANGES_REQUESTED** [review]
This doesn't fix the issue at all. To fix the issue, you need to modify the algorithms in SymPy so that it can compute `integrate(1/sqrt(x-t)*t, (t, 0, x))`. Simply adding a file to the root of the directory showing how to work around the issue is not helpful at all. If you know how to work around the issue, I would suggest adding that as a comment to the original issue.

**Comment by gxyd** [comment]
@abaokar-07 can you please address the requested changes?

**Comment by gxyd** [comment]
@abaokar-07 I am closing this pull request for now, since this PR has been inactive. Please feel free to push code addressing requested changes, and then re-open it.

**Comment by abaokar-07** [comment]
Hello sir, you closed this PR a few days back. I just wanted to ask you
that how should I work on to fix any bug in SymPy. I am looking forward to
GSoC, so can you please help me a bit on how should I proceed?
I actually saw some codes on fixing bugs and that seemed a little bit new
to me, so can you please help me out?

**Comment by gxyd** [comment]
You can choose any Easy to fix issue from https://github.com/sympy/sympy/issues?q=is%3Aopen+is%3Aissue+label%3A%22Easy+to+Fix%22 , in particular I recently opened issue https://github.com/sympy/sympy/issues/13515 which you can try to fix.

**Comment by gxyd** [comment]
In any case, for general discussions you can use https://gitter.im/sympy/sympy for discussion, post your message there.

**Comment by abaokar-07** [comment]
Okay, thank you very much sir!

On Oct 23, 2017 09:51, "Gaurav Dhingra" <notifications@github.com> wrote:

In any case, for general discussions you can use
https://gitter.im/sympy/sympy for discussion, post your message there.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sympy/sympy/pull/12358#issuecomment-338544271>, or mute
the thread

**Comment by abaokar-07** [comment]
@gxyd if we change the function t/sqrt(x-t) to (x-t)/sqrt(t) by the integral property f(x) = f(a-x), the limit being (0,a) and if we add the flag to the symbol t to be positive, then it calculates the correct answer.

**Pull request closed without merging**
