### PR TITLE
Speed up Symbol.sort_key

### PR DESCRIPTION
**Pull request by eric-wieser**
There's no need to go through `StrPrinter` here.

This does not affect the sort order of any of these types.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by smichr** [comment]
If you make this account for underscores I think this would be fine:
```
>>> Dummy('x').name,str(Dummy('x')),Wild('x').name, str(Wild('x'))
('x', '_x', 'x', 'x_')
```
i.e. `('_' if isinstance(self, Dummy) else '') + self.name + ('_' if isinstance(self, Wild) else '')`

This would always make Dummy < Symbol < Wild if they had the same names.

A test for this could be made as well as an assertion that `str(Dummy())` starts with underscore and `str(Wild())` ends with one.

**Comment by eric-wieser** [comment]
@smichr: Before and after this patch, `Dummy('a').sort_key() < Symbol('a').sort_key() < Wild('a').sort_key()`, because the comparison goes no further than `Dummy.class_key() < Symbol.class_key() < Wild('a').class_key()`.

So adding / removing `_` in the sort key makes no difference anyway.

**Comment by eric-wieser** [comment]
My follow-up question would be why this code needs to go through `StrPrinter`:

https://github.com/eric-wieser/sympy/blob/e359645106eb79856089dcc2d6c6871b63550c97/sympy/polys/polyutils.py#L76

**Comment by jksuom** [comment]
I'm not sure but I think that the reason is the special way in which polynomial generators are ordered.

**Pull request merged**
