### PR TITLE
Handle Mul.is_imaginary for infinite values

### LINKED ISSUE #17556: Mul.is_imaginary fails for infinite values
After #16666 we have that imaginary implies finite. The `Mul._eval_is_imaginary` method needs to be updated to reflect this:
```julia
In [1]: z = sqrt(-oo)                                                                                                             

In [2]: z.is_imaginary                                                                                                            
Out[2]: True

In [3]: z.is_finite                                                                                                               
Out[3]: True

In [4]: z                                                                                                                         
Out[4]: ∞⋅ⅈ

In [5]: z._eval_is_imaginary()                                                                                                    
Out[5]: True

In [6]: z._eval_is_finite()                                                                                                       
Out[6]: False
```

### PR DESCRIPTION
**Pull request by namannimmo10**
#### References to other Issues or PRs

Fixes #17556

#### Release Notes

* assumptions
    *  Updated `Mul.is_imaginary` to support infinite values.

### CODE REVIEW

**Comment by namannimmo10** [comment]
@oscarbenjamin could you please look into this?

**Comment by namannimmo10** [comment]
from travis' log:
>  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/sympy-1.6.dev0-py3.8.egg/sympy/functions/special/tests/test_bessel.py", line 312, in test_bessel_eval
    assert f(m, I*S.Infinity) is S.Zero
AssertionError

**Comment by oscarbenjamin** [comment]
If you find where that failed test is you can get the code from there to see what has changed. Presumably the bessel function now evaluates differently for `I*oo` so the logic there might need to be fixed.

**Comment by namannimmo10** [comment]
Okay, I'll look into it. Happy new year btw!

**Comment by Sc0rpi0n101** [comment]
The release notes should be something like 
Updated `Mul.is_imaginary` to support infinite values
or
`Mul.is_imaginary` now supports infinite values

There is no need to mention the changes to tests, they do not affect the users.

**Comment by namannimmo10** [comment]
@Sc0rpi0n101 Thanks for the advice. 

> There is no need to mention the changes to tests, they do not affect the users.

I'll consider that for the future PRs.

**Comment by V1krant** [comment]
This should fix the failing tests. 

```
diff --git a/sympy/functions/special/bessel.py b/sympy/functions/special/bessel.py
index fd839e00b0..5a2395a0a3 100644
--- a/sympy/functions/special/bessel.py
+++ b/sympy/functions/special/bessel.py
@@ -350,9 +350,8 @@ def eval(cls, nu, z):
                 return S.ComplexInfinity
             elif nu.is_imaginary:
                 return S.NaN
-        if z.is_imaginary:
-            if im(z) is S.Infinity or im(z) is S.NegativeInfinity:
-                return S.Zero
+        if im(z) is S.Infinity or im(z) is S.NegativeInfinity:
+            return S.Zero
 
         if z.could_extract_minus_sign():
             return (z)**nu*(-z)**(-nu)*besseli(nu, -z)
@@ -449,9 +448,8 @@ def eval(cls, nu, z):
                 return S.ComplexInfinity
             elif re(nu).is_zero:
                 return S.NaN
-        if z.is_imaginary:
-            if im(z) is S.Infinity or im(z) is S.NegativeInfinity:
-                return S.Zero
+        if im(z) is S.Infinity or im(z) is S.NegativeInfinity:
+            return S.Zero
 
         if nu.is_integer:
             if nu.could_extract_minus_sign():

```

**Comment by namannimmo10** [comment]
Thank you, @V1krant. :)

**Comment by namannimmo10** [comment]
@oscarbenjamin @czgdp1807 This diff indeed fixes the failing test. 
But I'm getting `ImportError` on travis. What could be the reason behind that? 
Travis' log: 
>  File "/home/travis/.venv-no-setuptools/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 16, in <module>
    from pip._internal.distributions import (
  File "/home/travis/.venv-no-setuptools/lib/python3.5/site-packages/pip/_internal/distributions/__init__.py", line 1, in <module>
    from pip._internal.distributions.source import SourceDistribution
ImportError: cannot import name 'SourceDistribution' 

There's no such failure on running the tests locally.

**Comment by oscarbenjamin** [comment]
That's a bug in pip

**Comment by namannimmo10** [comment]
How can I fix that?

**Comment by oscarbenjamin** [comment]
Looks good. Thanks all.

**Comment by namannimmo10** [comment]
Thanks all.

**Pull request merged**
