### PR TITLE
Performance improvement of _remove_repeated utility function

### PR DESCRIPTION
**Pull request by kpsychas**
Performance measured with following code (store in a file or run in terminal)

```
def r_old(inds):
    sum_index = {}
    for i in inds:
        if i in sum_index:
            sum_index[i] += 1
        else:
            sum_index[i] = 0
    inds = [x for x in inds if not sum_index[x]]
    return set(inds), tuple([ i for i in sum_index if sum_index[i] ])

def r_new(inds):
    ind_set = set()
    remove_set = set()
    for i in inds:
        if i in ind_set:
            remove_set.add(i)
        else:
            ind_set.add(i)
    return ind_set-remove_set, tuple(remove_set)

if __name__ == "__main__":
    import timeit
    print(timeit.repeat("r_old([1, 2, 3, 2, 4, 2, 3, 5, 1, 2, 3])",
                        "from __main__ import r_old", number=100000))
    print(timeit.repeat("r_new([1, 2, 3, 2, 4, 2, 3, 5, 1, 2, 3])",
                        "from __main__ import r_new", number=100000))
```

Results:
python 3.4
[0.34863924486407843, 0.3507206412770802, 0.34888814001763657]
[0.22447691390537017, 0.22464669290186956, 0.22363443374641934]
python 2.7
[0.2722262944472432, 0.2710292883736882, 0.27160191828883296]
[0.20663686197095876, 0.20522389017137832, 0.20427492394157531]

### CODE REVIEW

**Comment by smichr** [comment]
+1 this is similar to the strategy used by `iterables.uniq`.

**Comment by kpsychas** [comment]
If there is no particular reason to return a tuple instead of set this method will be even faster. Currently only one method in the module uses the second argument

**Comment by smichr** [comment]
When used, the dummies are used as a key in a dictionary so you can't return a set, but for that case the returned set could be converted to a FiniteSet.

**Comment by smichr** [comment]
In my `tensor` branch the last commit attempts the FiniteSet approach. Feel free to cherry pick it.

**Comment by smichr** [comment]
I added another commit to fix doctests, but don't have any help for fixing the code printing examples. :-(

**Comment by kpsychas** [comment]
I reverted code to use tuple. Maybe the use of FiniteSet should be applied to a new branch. I should have run the doctests in previous commit.

**Comment by czgdp1807** [comment]
`r_new` is still faster by a factor of 1.6. Though the absolute difference is around 0.08. So, IMO, we can close this. Attaching `Could Close` label.

**Comment by kpsychas** [comment]
It's been a while since I submitted this, but if performance matters to this project at all I see no reason to close this. There are functions that depend on this one and I tried to improve it just because it looks like it can be the bottleneck. That means even build times will likely get faster.

**Comment by smichr** [comment]
A couple of observations: 
1 - it might be possible to add a keyword like `dups=False` which will return uniq *and* dups if dups is True.
2 - sets are unordered and there are places here where sets are simply converted to tuples; this will (I believe) lead to noncanonical results and should be considered

**Comment by kpsychas** [comment]
> A couple of observations:
> 1 - it might be possible to add a keyword like `dups=False` which will return uniq _and_ dups if dups is True.
> 2 - sets are unordered and there are places here where sets are simply converted to tuples; this will (I believe) lead to noncanonical results and should be considered

These are valid issues but original solution does not resolve them either. Order of results depends on order of keys of `sum_index` which inherently have no order.

**Comment by kpsychas** [comment]
I checked out the master branch and does a better job at resolving performance and issues related to the order of indexes. First argument is a set so inevitably order does not matter. Returning a single argument instead of 2 will not help with performance and whoever calls the function and wants one argument can simply write `set1, _ = _remove_repeated(...)`.

**Pull request closed without merging**
