### PR TITLE
[GSoC] Allowed Dict in ArrayComprehension

### LINKED ISSUE #16944: Unevaluated dictionary in SymPy
Currently for `Binomial` distribution under `sympy/stats/frv_types.py` we have the following code for returning `density` as `dict`:
```python
def dict(self):
        n, p, succ, fail = self.n, self.p, self.succ, self.fail
        n = as_int(n)
        return dict((k*succ + (n - k)*fail,
                binomial(n, k) * p**k * (1 - p)**(n - k)) for k in range(0, n + 1))
```
This forces `n` to be an Integer. Is there a way to construct a dictionary with symbolic `n`?

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References to other Issues or PRs

https://github.com/sympy/sympy/pull/16815#issuecomment-498044725

#### Brief description of what is fixed or changed
`Dict` with single symbol has been allowed as functions in `ArrayComprehension`.

#### Other comments
I have fixed this because no PR referenced this issue from past few hours. I have made just an attempt to help. 
The issue which I observed with `ImmutableDenseNDimArray` is that it converts `Dict` and similar containers to `list` which I think should not be done. However, counter argument is that it doesn't sounds good to have tensors with `Dict` as elements. Since, `ArrayComprehension` corresponds to symbolic lists so, at least they should support `Dict`.
Any comments from the community will be appreciated.

#### Release Notes

* tensor
  * `Dict` can be passed as function in `ArrayComprehension`

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Maybe I misunderstand but I don't think this does fix #16944. There the request is to have a dict where the number of items in the dict is a symbol.

How would you (using this PR) implement the dict method from #16944 with symbolic dimensions?

**Comment by czgdp1807** [comment]
Ah! Actually, I misinterpreted https://github.com/sympy/sympy/pull/16815#issuecomment-498044725 for #16944 . I have updated the description. Thanks for bringing it my notice.

**Comment by czgdp1807** [comment]
> How would you (using this PR) implement the dict method from #16944 with symbolic dimensions?

I don't know about `Dict` with symbolic dimensions but as far as I can understand, may be he wanted this,
**Code**
```
from sympy.tensor.array import ArrayComprehension
from sympy import Dict, symbols
k, n = symbols('k n')
L1 = ArrayComprehension(Dict((k, k**2)), (k, 0, n + 1))
print(L1)
print(L1.subs(n, 3).doit())
```
**Output**
```
ArrayComprehension({k: k**2}, (k, 0, n + 1))
[{0: 0}, {1: 1}, {2: 4}, {3: 9}, {4: 16}]
```

**Comment by czgdp1807** [comment]
Some more work needs to be done, to do something like this,
```
ArrayComprehension({k: k**2}, (k, 0, n + 1))
{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}
```

**Pull request closed without merging**
