### PR TITLE
Solving issue of spurious solutions

### PR DESCRIPTION
**Pull request by czgdp1807**
I have added a code to filter out the correct solutions, in solve method of solvers.py to fix the issue of
spurious solutions passing unfiltered. Issue details are available at https://github.com/sympy/sympy/issues/14779. I have also added a test_issue_14779 in test_solvers.py to take into account this issue.

### CODE REVIEW

**Comment by Yathartha22** [comment]
add some tests (in `test_solvers.py`).

**Comment by czgdp1807** [comment]
@Yathartha22 I have added a `test_issue_14779`. Please give your feedback.

**Comment by Yathartha22** [comment]
> Like, checksol(sqrt(x**4 - 130*x**2 + 1089) + sqrt(x**4 - 130*x**2 + 3969) - 96*Abs(x)/x,-sqrt(130),x) should return False

`x` should be the second argument

```
>>> checksol(sqrt(x**4 - 130*x**2 + 1089) + sqrt(x**4 - 130*x**2 + 3969) - 96*Abs(x)/x, x, -sqrt(130))
False
```
I am currently stuck in some work, will probably look at your changes in a day or so. But I guess `solve` already uses `checksol` for filtering spurious solutions. See [here](https://github.com/sympy/sympy/blob/master/sympy/solvers/solvers.py#L1744). Not sure though but unwanted values are getting through with this check.

**Comment by czgdp1807** [comment]
@Yathartha22 Yes it was a silly mistake. I apologize for that and now I expect only one test to be failed `solve([x-2,x**2+f(x)],{f(x),x})`. My code gives output `[]`, however, the expected output is `[{x: 2, f(x): -4}]`.

**Comment by Abdullahjavednesar** [comment]
The commit message should be relevant to the changes in it, you should keep that in mind.

**Comment by czgdp1807** [comment]
@Abdullahjavednesar I have updated my first comment. I will also take care from my next PR to make a more detailed and accurate message.Thanks for your feedback. :-) 
Is there any way to update my commit message? What I have updated is a comment and will it also update the commit message?

**Comment by smichr** [comment]
```diff
diff --git a/sympy/solvers/solvers.py b/sympy/solvers/solvers.py
index 6371fcc..a6f8655 100644
--- a/sympy/solvers/solvers.py
+++ b/sympy/solvers/solvers.py
@@ -1430,7 +1430,6 @@ def _solve(f, *symbols, **flags):
     # /!\ capture this flag then set it to False so that no checking in
     # recursive calls will be done; only the final answer is checked
     checkdens = check = flags.pop('check', True)
-    flags['check'] = False

     # build up solutions if f is a Mul
     if f.is_Mul:
@@ -1450,7 +1449,8 @@ def _solve(f, *symbols, **flags):
             result = [s for s in result if
                 all(not checksol(den, {symbol: s}, **flags) for den in
                 dens)]
-        # set flags for quick exit at end
+        # set flags for quick exit at end; checking and simplification
+        # were already done for each factor
         check = False
         flags['simplify'] = False

@@ -1485,9 +1485,10 @@ def _solve(f, *symbols, **flags):
                 result.add(Piecewise(
                     (candidate, v),
                     (S.NaN, True)))
-        # the solutions need not be checked again since they
-        # were checked in finding the solutions for each piece
+        # set flags for quick exit at end; checking and simplification
+        # were already done for each piece
         check = False
+        flags['simplify'] = False
     else:
         # first see if it really depends on symbol and whether there
         # is only a linear solution

**Comment by czgdp1807** [comment]
@smichr I couldn't understand your comment. Can you please explain to me what it means, I am curious to know. :-)

**Comment by smichr** [comment]
I suspect that this is closer to the solution to the problem:

```diff
diff --git a/sympy/solvers/solvers.py b/sympy/solvers/solvers.py
index 6371fcc..9f30f93 100644
--- a/sympy/solvers/solvers.py
+++ b/sympy/solvers/solvers.py
@@ -1427,10 +1427,7 @@ def _solve(f, *symbols, **flags):
             raise NotImplementedError(not_impl_msg % f)
     symbol = symbols[0]

-    # /!\ capture this flag then set it to False so that no checking in
-    # recursive calls will be done; only the final answer is checked
-    checkdens = check = flags.pop('check', True)
-    flags['check'] = False
+    flags['check'] = checkdens = check = flags.pop('check', True)

     # build up solutions if f is a Mul
     if f.is_Mul:
@@ -1450,7 +1447,8 @@ def _solve(f, *symbols, **flags):
             result = [s for s in result if
                 all(not checksol(den, {symbol: s}, **flags) for den in
                 dens)]
-        # set flags for quick exit at end
+        # set flags for quick exit at end; solutions for each
+        # factor were already checked and simplified
         check = False
         flags['simplify'] = False

@@ -1485,9 +1483,10 @@ def _solve(f, *symbols, **flags):
                 result.add(Piecewise(
                     (candidate, v),
                     (S.NaN, True)))
-        # the solutions need not be checked again since they
-        # were checked in finding the solutions for each piece
+        # set flags for quick exit at end; solutions for each
+        # piece were already checked and simplified
         check = False
+        flags['simplify'] = False
     else:
         # first see if it really depends on symbol and whether there
         # is only a linear solution
@@ -1561,7 +1560,11 @@ def _as_base_q(x):
                 if not other and len(funcs.intersection(trig)) > 1:
                     newf = TR1(f_num).rewrite(tan)
                     if newf != f_num:
+                        # don't check the rewritten form -- check
+                        # solutions in the un-rewritten form below
+                        flags['check'] = False
                         result = _solve(newf, symbol, **flags)
+                        flags['check'] = check

                 # just a simple case - see if replacement of single function
                 # clears all symbol-dependent functions, e.g.
```

**Comment by czgdp1807** [comment]
Yes I analyzed the changes you made. So, was my PR helpful in anyway to solve the issue?

**Comment by smichr** [comment]
> was my PR helpful in anyway to solve the issue

No, it duplicates code that is already capable of checking solutions. Feel free to submit a PR with the diff I provided. The issue of interest and all other `test_solvers.py` tests passed with it. I don't know if some other problem will show up, however.

**Comment by czgdp1807** [comment]
@smichr I have done all the changes that your diff suggested but it's only removing `-sqrt(130)` from `[0, sqrt(130), -sqrt(130)]` and `0` is still there in the list. Though I am trying to figure out the issue. Please correct me if i observed wrongly.

**Comment by smichr** [comment]
The problem is that Abs(x)/x gets rewritten in solve but the solutions only get checked against the re-written form which doesn't have the x in the denominator anymore. Perhaps one solution would be to pass the denominators of the original equation to `_solve`:

```diff
diff --git a/sympy/solvers/solvers.py b/sympy/solvers/solvers.py
index 9f30f93..ecdea86 100644
--- a/sympy/solvers/solvers.py
+++ b/sympy/solvers/solvers.py
@@ -1140,6 +1140,10 @@ def _sympified_list(w):
                 floats = True
                 f[i] = nsimplify(fi, rational=True)

+    # capture any denominators before rewriting since
+    # they may disappear after the rewrite, e.g. issue 14779
+    flags['_denominators'] = _simple_dens(f[0], symbols)
+
     # Any embedded piecewise functions need to be brought out to the
     # top level so that the appropriate strategy gets selected.
     # However, this is necessary only if one of the piecewise
@@ -1443,7 +1447,7 @@ def _solve(f, *symbols, **flags):
             # all solutions have been checked but now we must
             # check that the solutions do not set denominators
             # in any factor to zero
-            dens = _simple_dens(f, symbols)
+            dens = flags.get('_denominators', _simple_dens(f, symbols))
             result = [s for s in result if
                 all(not checksol(den, {symbol: s}, **flags) for den in
                 dens)]
```

That eliminates the 0 from the solution of the equation given in the issue prompting this PR.

**Comment by smichr** [comment]
Perhaps the better thing to do is to move all denominator checking into `solve`.

**Comment by czgdp1807** [comment]
I think keeping all the testing of solutions in `_solve` method would be better because its written in its documentation that it returns tested solution. Moreover, there may be other methods which may be using `_solve`. If you will say then I will move the denominator checking into `solve` method.

**Comment by smichr** [comment]
> If you will say then I will move the denominator checking into solve method.

agreed.

This is what I was working on:

```
diff --git a/sympy/solvers/solvers.py b/sympy/solvers/solvers.py
index 9f30f93..ada87d1 100644
--- a/sympy/solvers/solvers.py
+++ b/sympy/solvers/solvers.py
@@ -1140,6 +1140,11 @@ def _sympified_list(w):
                 floats = True
                 f[i] = nsimplify(fi, rational=True)
 
+    # capture denominators before any folding (issue 14779)
+    flags['dens'] = set()
+    for fi in f:
+        flags['dens'].update(_simple_dens(fi, symbols))
+
     # Any embedded piecewise functions need to be brought out to the
     # top level so that the appropriate strategy gets selected.
     # However, this is necessary only if one of the piecewise
@@ -1354,6 +1359,7 @@ def _solve(f, *symbols, **flags):
     gives None a ValueError will be raised."""
 
     not_impl_msg = "No algorithms are implemented to solve equation %s"
+    flags['check'] = checkdens = check = flags.pop('check', True)
 
     if len(symbols) != 1:
         soln = None
@@ -1395,7 +1401,8 @@ def _solve(f, *symbols, **flags):
         got_s = set([])
         result = []
         for s in symbols:
-            xi, v = solve_linear(f, symbols=[s])
+            dens = flags.get('dens', None) if check else set()
+            xi, v = solve_linear(f, symbols=[s], dens=dens)
             if xi == s:
                 # no need to check but we should simplify if desired
                 if flags.get('simplify', True):
@@ -1427,7 +1434,6 @@ def _solve(f, *symbols, **flags):
             raise NotImplementedError(not_impl_msg % f)
     symbol = symbols[0]
 
-    flags['check'] = checkdens = check = flags.pop('check', True)
 
     # build up solutions if f is a Mul
     if f.is_Mul:
@@ -1443,10 +1449,9 @@ def _solve(f, *symbols, **flags):
             # all solutions have been checked but now we must
             # check that the solutions do not set denominators
             # in any factor to zero
-            dens = _simple_dens(f, symbols)
             result = [s for s in result if
                 all(not checksol(den, {symbol: s}, **flags) for den in
-                dens)]
+                flags.get('dens', _simple_dens(f, symbols)))]
         # set flags for quick exit at end; solutions for each
         # factor were already checked and simplified
         check = False
@@ -1490,7 +1495,8 @@ def _solve(f, *symbols, **flags):
     else:
         # first see if it really depends on symbol and whether there
         # is only a linear solution
-        f_num, sol = solve_linear(f, symbols=symbols)
+        dens = flags.get('dens', None) if check else set()
+        f_num, sol = solve_linear(f, symbols=symbols, dens=dens)
         if f_num is S.Zero or sol is S.NaN:
             return []
         elif f_num.is_Symbol:
@@ -1738,10 +1744,9 @@ def _expand(p):
     if checkdens:
         # reject any result that makes any denom. affirmatively 0;
         # if in doubt, keep it
-        dens = _simple_dens(f, symbols)
         result = [s for s in result if
                   all(not checksol(d, {symbol: s}, **flags)
-                    for d in dens)]
+                    for d in flags.get('dens', _simple_dens(f, symbols)))]
     if check:
         # keep only results if the check is not False
         result = [r for r in result if
@@ -1754,15 +1759,21 @@ def _solve_system(exprs, symbols, **flags):
         return []
 
     polys = []
-    dens = set()
     failed = []
     result = False
     linear = False
     manual = flags.get('manual', False)
     checkdens = check = flags.get('check', True)
+    if 'dens' in flags:
+        dens = flags['dens']
+        dodens = False
+    else:
+        dens = set()
+        dodens = True
 
     for j, g in enumerate(exprs):
-        dens.update(_simple_dens(g, symbols))
+        if dodens:
+            dens.update(_simple_dens(g, symbols))
         i, d = _invert(g, *symbols)
         g = d - i
         g = g.as_numer_denom()[0]
@@ -1950,7 +1961,7 @@ def _ok_syms(e, sort=False):
     return result
 
 
-def solve_linear(lhs, rhs=0, symbols=[], exclude=[]):
+def solve_linear(lhs, rhs=0, symbols=[], exclude=[], dens=None):
     r""" Return a tuple derived from f = lhs - rhs that is one of
     the following:
 
@@ -1988,6 +1999,10 @@ def solve_linear(lhs, rhs=0, symbols=[], exclude=[]):
         unless a solution for that symbol was found (in which case
         the second element is the solution, not the denominator).
 
+        If a set ``dens`` is provided, no solution will be
+        returned if it affirmatively sets any expression in ``dens``
+        to zero. If it is not provided (default) it will comprise all
+        denominators that appear in ``lhs`` and ``rhs``.
 
     Examples
     ========
@@ -2063,7 +2078,7 @@ def solve_linear(lhs, rhs=0, symbols=[], exclude=[]):
             If lhs is an Equality, rhs must be 0 but was %s''' % rhs))
         rhs = lhs.rhs
         lhs = lhs.lhs
-    dens = None
+
     eq = lhs - rhs
     n, d = eq.as_numer_denom()
     if not n:
@@ -2117,7 +2132,8 @@ def solve_linear(lhs, rhs=0, symbols=[], exclude=[]):
             if xi not in dnewn_dxi.free_symbols:
                 vi = -1/dnewn_dxi*(newn.subs(xi, 0))
                 if dens is None:
-                    dens = _simple_dens(eq, symbols)
+                    dens = _simple_dens(lhs, symbols)
+                    dens.update(_simple_dens(rhs, symbols))
                 if not any(checksol(di, {xi: vi}, minimal=True) is True
                           for di in dens):
                     # simplify any trivial integral
```

I wonder whether we need both check and checkdens flags now. I haven't looked closely at that. Tests are needed in which solutions are rejected based on setting a denominator to 0 for each of the solvers affected (`_solve`, `solve_linear` and `_solve_system`).

**Comment by czgdp1807** [comment]
I was also planning to add a similar kind of mechanism when I was facing the problem of `0` being coming up in the solutions but thought of reporting to you first. Now, I will move the denominator checking to `solve` method as soon as possible. Thanks for your help in fixing this issue. :-)

**Comment by czgdp1807** [comment]
One more thing I want to ask, whether I need to add the changes you suggested in your latest comment or I should only shift the denominator checking from `_solve` to `solve` and some few tests for `_solve`, `solve_linear` and `_solve_system` . I will do as you will say.

**Comment by smichr** [comment]
Since assumptions are checked at the `solve` level it might make sense to only do the denominator checking there, too, with denominators taken from the raw equations that were passed to `solve`. For `solve_linear`, then, `set()` should be passed from the `_solve` routine and the checking would be done later in `solve` or (in case someone was calling `solve_linear` directly) the checking of what was passed would still be done. So in the diff, `solve_linear(f, symbols=[s], dens=dens)` would be `solve_linear(f, symbols=[s], dens=set())`.

**Pull request closed without merging**
