### PR TITLE
Mutable and immutable N-dim arrays

### PR DESCRIPTION
**Pull request by Upabjojr**
Four classes are provided:
- MutableDenseNDimArray
- MutableSparseNDimArray
- ImmutableDenseNDimArray
- ImmutableSparseNDimArray

Immutable ones are SymPy objects (they subclass _Expr_), mutable ones are not. The structure loosely reflects the matrix module.

### CODE REVIEW

**Comment by Upabjojr** [comment]
@asmeurer here are the immutable N-dim arrays, they subclass `Expr`.

I am still not sure on whether the dimensions should be specified after the iterable in the array construction.

**Comment by moorepants** [comment]
The class names are pretty lengthy. I think that at least dropping the "NDim" part would be a good idea, as it doesn't add that much to the picture.

**Comment by Upabjojr** [comment]
> The class names are pretty lengthy. I think that at least dropping the "NDim" part would be a good idea, as it doesn't add that much to the picture.

My idea was to default `NDimArray` to `ImmutableDenseNDimArray`, and make it the ordinary use case (as `Matrix` is currently a short form for mutable dense matrices).

I'm not sure about dropping _NDim_, usually arrays are meant to be 1-dimensional. It has to be clear that they can be any dimension.

**Comment by moorepants** [comment]
Ok that sounds fine for the NDimArray.

I'm not sure I agree that arrays are usually meant to be 1 dimensional though. I suspect that is domain specific to some degree.

**Comment by Upabjojr** [comment]
@certik I don't currently see anything else to do on this.

@jksuom this is the same code you reviewed on the other PR. Only with the addition of the immutable classes and _shape_ parameter.

I believe this is ready for merging.

**Comment by certik** [comment]
I think this looks good to me. @asmeurer any objections?

**Comment by asmeurer** [comment]
Is there a reason to use Expr instead of Basic?

**Comment by asmeurer** [comment]
Just that one comment.

**Comment by Upabjojr** [comment]
> Is there a reason to use Expr instead of Basic?

Not really, should I change it into _Basic_?

**Comment by Upabjojr** [comment]
@asmeurer, I changed _Expr_ to _Basic_ as you pointed out.

One test went timeout on Travis. I believe all tests pass.

**Comment by certik** [comment]
That looks good to me. The test failure is unrelated. Merging.

**Comment by certik** [comment]
Thanks @Upabjojr for the work!

**Pull request merged**
