### PR TITLE
feat(polys): Add GROUND_TYPES='flint'

### PR DESCRIPTION
**Pull request by oscarbenjamin**
CC @fredrik-johansson 

Adds the option to use python-flint for the ground types instead of gmpy2. Set the environment variable SYMPY_GROUND_TYPES='flint' to activate this (and install python-flint).

#### References to other Issues or PRs

See the python-flint package:
https://github.com/fredrik-johansson/python-flint

The underlying Flint C library:
https://flintlib.org/

Possibly the latest master version of python-flint is needed. An older version of python-flint can be installed with conda (although not on Windows). Otherwise it needs to be built from source which is not completely trivial. The next release of python-flint will have binaries on PyPI for Windows, OSX and Linux.

#### Brief description of what is fixed or changed

Adds a new `GROUND_TYPES=flint` option in addition to `GROUND_TYPES=python` and `GROUND_TYPES=gmpy`. If `python-flint` is installed and the environment variable `SYMPY_GROUND_TYPES` is set to `flint` then python-flint's `fmpz` and `fmpq` types will be used as the implementation of the `ZZ` and `QQ` poly domains.

To see the effect of the changes in this PR you can do:
```python
$ SYMPY_GROUND_TYPES=python python -c 'import sympy; print(type(sympy.ZZ(1)))'
<class 'int'>
$ SYMPY_GROUND_TYPES=gmpy python -c 'import sympy; print(type(sympy.ZZ(1)))'
<class 'mpz'>
$ SYMPY_GROUND_TYPES=flint python -c 'import sympy; print(type(sympy.ZZ(1)))'
<class 'flint._flint.fmpz'>
```
The `HAS_GMPY` variable no longer really makes sense if there are more than two ground type options so most usage is replaced by checking `GROUND_TYPES` instead. Now `HAS_GMPY` is not used anywhere outside of the `sympy.external.gmpy` module although the variable is still there in case any downstream code uses it. If `flint` is used then `HAS_GMPY` is set to `0` so `HAS_GMPY==0` does not imply `GROUND_TYPES=='python'` any more but `HAS_GMPY==2` still implies `GROUND_TYPES=='gmpy'`.

The `sympy.external.gmpy` module should probably be renamed but for now I left it there although I did move the various pure Python number theory functions into a separate `sympy.external.ntheory` module.

I have not added any CI testing for this although I have run the core and polys tests locally and I will test the full test suite. Changes are needed both in python-flint and in sympy to make this work. I will add CI testing when there is a release of python-flint that has the latest changes in master and also binaries on PyPI that can be installed easily in SymPy's CI. I can see some things that don't work but so far I think that those are things to be fixed in python-flint rather than in SymPy so it should not hold up merging this so that `GROUND_TYPES='flint'` can be tested more widely.

#### Other comments

As it stands with this PR I don't expect that using `GROUND_TYPES=flint` will bring any substantial improvements over using `gmpy2` but this is just the first step. This might make some things faster and might make other things slower. Using flint is not enabled by default though so it should not introduce any regression unless someone opts in with `SYMPY_GROUND_TYPES=flint`.

The big improvements for SymPy will come later from using `python-flint` for things that gmpy2 does not provide like polynomials, matrices, Arb, calcium etc.

The reason to use flint for the ground types is that:

1. If someone is using python-flint then they no longer need to have gmpy2 installed as well.
2. Using `fmpz` and `fmpq` as the ground types makes it more efficient to convert say a list of `ZZ` into a `fmpz_poly` so when it is possible to use flint's other types it will make sense to use them also for ZZ and QQ. 

As an example of this conversion we can do e.g.:
```python
In [7]: M = randMatrix(50)

In [8]: %time ok = M.det()
CPU times: user 2.47 s, sys: 9.13 ms, total: 2.48 s
Wall time: 2.48 s

In [9]: %time ok = M.to_DM().det()  # DomainMatrix
CPU times: user 75.5 ms, sys: 12 µs, total: 75.5 ms
Wall time: 74.3 ms

In [10]: %time ok = flint.fmpz_mat(M.to_DM().to_list()).det()
CPU times: user 6.86 ms, sys: 3.91 ms, total: 10.8 ms
Wall time: 10.9 ms
```
Actually flint is a lot faster than that so the overhead here is mostly conversion:
```python
In [11]: fM =  flint.fmpz_mat(M.to_DM().to_list())

In [12]: %time fM.det()
CPU times: user 4.55 ms, sys: 39 µs, total: 4.59 ms
Wall time: 4.54 ms
Out[12]: -15247324201397047106854518724916370205843752908424986648046567389005648338935854480845854186655584056237196

In [13]: %timeit fM.det()
1.38 ms ± 3.69 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
I intend to make it so that flint matrices can be used as the dense version of DomainMatrix for any supported domains i.e. ZZ and QQ. This example with a matrix of integers is not the most interesting comparison because SymPy already has `DomainMatrix` that is now relatively fast for a pure Python implementation and in simple cases probably uses similar algorithms.

Bigger improvements will come from using flint's univariate dense polynomials:
```python
In [11]: p1 = random_poly(x, 50, -100, 100)

In [12]: p2 = random_poly(x, 50, -100, 100)

In [13]: p = (p1*p2).expand()

In [14]: fp = flint.fmpz_poly(p.as_poly().rep.rep)

In [15]: %time ok = fp.factor()
CPU times: user 20.1 ms, sys: 0 ns, total: 20.1 ms
Wall time: 20 ms
```
That is a lot faster than e.g.
```
In [16]: %time ok = p.factor()
CPU times: user 796 ms, sys: 236 µs, total: 796 ms
Wall time: 796 ms
```
The differences will be more significant for larger polynomials and probably other algorithms than just factorisation (the polys module has relatively good algorithms for some things but not so much for others).

Currently python-flint does not expose flint's sparse polynomials but that is something that should be exposed and that will make a *huge* speed difference for SymPy in things like `solve`, matrix operations etc.

It is also possible to use flint for `GF(p)` although a bit more work would be needed on that. Currently with python-flint `GF(p)` only works for `p` up to the word-size:
```python
In [2]: n = flint.nmod(5, nextprime(2**64))
---------------------------------------------------------------------------
OverflowError 
```
Within flint itself there is an implementation of `GF(p)` (`fmpz_mod`)  for large `p` but probably the `python-flint` wrapper should smooth over this difference on behalf of its Python-based users. SymPy could still use flint for `GF(p)` with small `p` but would need to deprecate and remove the `to_int` method first.

Other python-flint feature such as Arb could be used in `evalf`. There is too much there fore me to list it all here.

#### Release Notes

* polys
    * A new ground type option is added to use python-flint for the ground types rather than Python or gmpy2. For now this is experimental and is not used by default but can be enabled by installing `python-flint` and setting the environment variable `SYMPY_GROUND_TYPES=flint` before importing SymPy. With `GROUND_TYPES=flint` the `ZZ` and `QQ` poly domains will use `flint.fmpz` and `flint.fmpq` rather than `gmpy2.mpz` and `gmpy2.mpq`. This should not lead to any noticeable difference in behaviour for ordinary usage of SymPy but might have an effect on performance in some cases. Both `gmpy2` and `python-flint` use GMP internally so for pure integer/rational arithmetic they should mostly have comparable performance. Adding `GROUND_TYPES=flint` lays the ground work for adding other flint types that gmpy2 does not have such as polynomials and matrices in future which will bring significant future speedups for SymPy.

### CODE REVIEW

**Comment by smichr** [comment]
I looked it over and nothing stands out as needing changing.

**Comment by oscarbenjamin** [comment]
> I looked it over and nothing stands out as needing changing.

Thanks.

I am still working in the background at making changes in both SymPy and python-flint to get the test suite to pass with `SYMPY_GROUND_TYPES=flint`. A lot of things need changing in python-flint and a few changes will be needed in SymPy that I will push here once I reach a reasonable progress milestone.

**Comment by oscarbenjamin** [comment]
As of the last commit this PR in combination with https://github.com/fredrik-johansson/python-flint/pull/44 mean that the full SymPy test suite (all not slow tests and all doctests) can pass with `SYMPY_GROUND_TYPES=flint`.

Actually there are some doctest failures in ntheory and plotting tests in continuum_mechanics but I see those failures also with master at least when running `bin/doctest` with gmpy2 installed (CC @Davide-sd, @haru-44). I guess that `bin/doctest` is now different somehow from `pytest --doctest-plus sympy` which is why those failures are not seen in CI (CC @brocksam). I will open a separate issue for those.

Otherwise though I will finish off the python-flint PR but this PR for SymPy is ready for review.

To be clear there are big improvements that can be built on this PR to make more use of python-flint so I would like to get this in ASAP. The most immediate next step is to use python-flint for univariate polynomials and matrices over ZZ and QQ where it can bring immediate speed improvements with no additional work needed on the python-flint side.

**Comment by oscarbenjamin** [comment]
The changes on the python-flint side are now merged:

https://github.com/fredrik-johansson/python-flint/pull/44

I will put out a new release of python-flint shortly.

This PR in combination with the current python-flint master passes all tests and doctests except for a couple of doctests:
https://github.com/sympy/sympy/blob/b68285262a06a914d9d920aba980d726be2efc39/sympy/polys/domains/domain.py#L1101-L1114
https://github.com/sympy/sympy/blob/b68285262a06a914d9d920aba980d726be2efc39/sympy/polys/densebasic.py#L477-L491
These are because of two differences between python-flint's `fmpz` and int/gmpy.mpz. The two differences are:
```python
>>> import flint
>>> flint.fmpz(2) / flint.fmpz(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for /: 'flint._flint.fmpz' and 'flint._flint.fmpz'
>>> flint.fmpz(2.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/flint/fmpz.pyx", line 92, in flint._flint.fmpz.__init__
    raise TypeError("cannot create fmpz from type %s" % type(val))
TypeError: cannot create fmpz from type <class 'float'>
```
In the context of the domain system `/` should not be used with elements of `ZZ` (which is what the doctest above is explaining) so I think it is actually a good thing that this raises because it ensures that `/` won't be used accidentally somewhere. The other failure I think is also something that should be avoided in the domain system: a conversion from float to `ZZ` should be done with appropriate routines that decide how to handle rounding etc so it is a good thing that this fails.

With this PR and `SYMPY_GROUND_TYPES=flint` these two differences manifest as:
```python
In [1]: ZZ(2) / ZZ(2)
---------------------------------------------------------------------------
TypeError: unsupported operand type(s) for /: 'flint._flint.fmpz' and 'flint._flint.fmpz'

In [2]: ZZ(2.0)
---------------------------------------------------------------------------
TypeError: cannot create fmpz from type <class 'float'>
```
I'm going to put out a release of python-flint shortly so that it can be added in CI.

I think that this PR should still be merged without the CI though. I have already run all tests and any problems could be fixed when CI is added. Note that the PR still makes the use of flint opt-in so by default gmpy2 will still be used if it is installed or otherwise the python types will be used. This only changes things if python-flint is installed *and* `SYMPY_GROUND_TYPES=flint` is set.

**Pull request merged**
