### PR TITLE
Fixes #14987: linear_eq_to_matrix proceeds without exception even if equations are nonlinear

### LINKED ISSUE #14987: linear_eq_to_matrix proceeds without exception even if equations are nonlinear
Hi,

I would expect the following code to throw an exception (or give me a warning telling me I'm silly), but it does not. `x**2=0` is not a linear equation.

```
from sympy import symbols, linear_eq_to_matrix, linsolve
x = symbols("x")
linear_eq_to_matrix([x**2], [x])
```

### PR DESCRIPTION
**Pull request by czgdp1807**
I have added a mechanism to linear_eq_to_matrix to check if
the equations passed to the method are linear or not. If they
are not linear then appropriate error messages as raised. I
add regression test after receiving feedback.

### CODE REVIEW

**Comment by cbm755** [comment]
Why closed, this was looking good...  Will needs tests, and a release log entry.

Also, can the while loop be a comprehension?

**Comment by czgdp1807** [comment]
I closed because of the SymPy bot error. I forgot to add the release notes.
Yes, I was looking for a method to traverse two lists simultaneously. Can you please suggest me some method to do so?

**Comment by sidhantnagpal** [comment]
> I closed because of the SymPy bot error. I forgot to add the release notes.

You can edit the description for the Pull Request for the addition.

> I was looking for a method to traverse two lists simultaneously.

You can use `zip()` for that purpose.

**Comment by cbm755** [comment]
Was there anything wrong with this general approach?  It seems simpler to me than #14999.

We need to extract the linear system anyway, so trying and then substracting from the original system to check for zero seems cheaper to me than messing around with derivatives.

**Comment by czgdp1807** [comment]
Subtracting doesn't gives 100% accuarcy. Even sometimes, `coeff`  method fails when equations is in expanded fails. See my latest comment on #14999

**Pull request closed without merging**
