### PR TITLE
fix(core): match/replace no longer treat bound symbols as wild cards

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

Partial fix for gh-27142

#### Release Notes

* core
   * BREAKING CHANGE: In SymPy 1.7 Basic.match and Basic.replace were changed to treat bound symbols in a pattern as wild cards. This change is now reverted so that patterns are matched structurally without distinguishing between free and bound symbols. This means that e.g. `Integral(x, (x, 0, 1)).match(Integral(y, (y, 0, 1)))` no longer matches if `y` is an ordinary symbol. Matching bound symbols was redundant since a Wild symbol can be used in place of any bound symbol in the pattern e.g. `Integral(x, (x, 0, 1)).match(Integral(w, (w, 0, 1)))` where `w = Wild('w')`. This change to match fixes a bug in replace where matches involving expressions with bound symbols would give incorrect expressions involving Dummy symbols.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This also fixes a performance problem where match calls `as_dummy` which calls replace which calls match which calls as_dummy again. I don't even know how that avoids an infinite loop but it is absurd from a performance perspective. I added some print statements to the code to show what happens:
```python
In [3]: (x**(1 + y)).replace(x**(1 + a), a)
(x**(y + 1)).replace(x**(a_ + 1), a_) called
(x).match(x**(a_ + 1)) called
(x**(a_ + 1)).as_dummy() called
(x**(a_ + 1)).replace(<function Basic.as_dummy.<locals>.<lambda> at 0x7dd6709ace00>, <function Basic.as_dummy.<locals>.can at 0x7dd6709accc0>) called
(1).match(x**(a_ + 1)) called
(x**(a_ + 1)).as_dummy() called
(x**(a_ + 1)).replace(<function Basic.as_dummy.<locals>.<lambda> at 0x7dd6709acfe0>, <function Basic.as_dummy.<locals>.can at 0x7dd6709acd60>) called
(1).as_dummy() called
(y).match(x**(a_ + 1)) called
(x**(a_ + 1)).as_dummy() called
(x**(a_ + 1)).replace(<function Basic.as_dummy.<locals>.<lambda> at 0x7dd6709af4c0>, <function Basic.as_dummy.<locals>.can at 0x7dd6709ace00>) called
(y - 1).match(x**(a_ + 1)) called
(x**(a_ + 1)).as_dummy() called
(x**(a_ + 1)).replace(<function Basic.as_dummy.<locals>.<lambda> at 0x7dd6709afe20>, <function Basic.as_dummy.<locals>.can at 0x7dd6709ae020>) called
(y - 1).as_dummy() called
(y - 1).replace(<function Basic.as_dummy.<locals>.<lambda> at 0x7dd6709acfe0>, <function Basic.as_dummy.<locals>.can at 0x7dd6709afe20>) called
(0**(y - 1)).match(x**(a_ + 1)) called
(x**(a_ + 1)).as_dummy() called
(x**(a_ + 1)).replace(<function Basic.as_dummy.<locals>.<lambda> at 0x7dd6709afce0>, <function Basic.as_dummy.<locals>.can at 0x7dd6709ae520>) called
(0**(y - 1)).as_dummy() called
(0**(y - 1)).replace(<function Basic.as_dummy.<locals>.<lambda> at 0x7dd6709ae520>, <function Basic.as_dummy.<locals>.can at 0x7dd6709afce0>) called
Out[3]: 
 y - 1
0     
```
With the PR it looks like:
```python
In [3]: (x**(1 + y)).replace(x**(1 + a), a)
(x**(y + 1)).replace(x**(a_ + 1), a_) called
(x).match(x**(a_ + 1)) called
(1).match(x**(a_ + 1)) called
(y).match(x**(a_ + 1)) called
(y - 1).match(x**(a_ + 1)) called
(0**(y - 1)).match(x**(a_ + 1)) called
Out[3]: 
 y - 1
0
```
The `as_dummy` function is supposed to be idempotent so there should never be a reason to call it more than once. The call structure here scales horribly with the depth of the expression tree because match is called recursively for each subexpression and `as_dummy` then recurses the entire subtree calling match which again calls `as_dummy` and so on.

This PR doesn't affect the output but this is also a bug somehow:
```python
In [1]: a, b = symbols('a, b', cls=Wild)

In [2]: (x**(1 + y)).replace(x**(1 + a), a)
Out[2]: 
 y - 1
0  
```

**Comment by oscarbenjamin** [comment]
This is ready for review.

**Comment by sylee957** [comment]
I'm okay with the change. But I'm not certain about committing this without breaking change entry if there is change to documented behavior.

**Comment by asmeurer** [comment]
This fix seems fine, but the PR text implies that this is changing a lot more than it actually is.

**Comment by oscarbenjamin** [comment]
I've changed the PR title and edited the release note to explain more precisely what is changed.

**Comment by sylee957** [comment]
Thanks

**Comment by oscarbenjamin** [comment]
Thanks

**Pull request merged**
