### PR TITLE
Remove the so-called "User's guide"

### PR DESCRIPTION
**Pull request by asmeurer**
This was an old document in the Sphinx documentation that referenced very old 
versions of SymPy, and didn't contain any information that isn't already 
written better somewhere else.

This fixes part of #2806.

### CODE REVIEW

**Comment by asmeurer** [comment]
@smichr did you ever do any work to clean up this document or move its contents to other places?

**Comment by toolforger** [comment]
What I see here is a document that's not just outdated but actively misleading (it's referring to classes that have been removed years ago, such as MetaBasicMeths).
My suggestion to move this forward:
1) Add a big "this is outdated" warning to the file.
2) Remove the factually wrong sections. Or add warnings.
3) Move stuff elsewhere that belongs elsewhere.
4) If any of the above can't be done right now, open an issue and see who might pick it up.

**Comment by oscarbenjamin** [comment]
I guess what's missing from the current docs is a detailed guide for the internals of SymPy that would be useful for contributors and advanced downstream users. In particular there should be something that explains

1. The architecture of Basic (immutability, args, func, etc)
2. The various Basic subclasses (Set, Expr, Boolean, etc)
3. The core Expr classes Add, Pow, Mul and Function
4. The old assumption system and how to implement it
5. Fuzzy logic and Relational and how/when to use them (e.g. don't do `if x < 2`)
6. Various special methods for subclasses (`_eval_is*`, `_eval_rewrite*` etc)
7. The meaning of special attributes (is_number, is_Number etc)
8. How/when (not) to use special methods like `__add__`, `__eq__`, etc
9. Dos and don'ts for the SymPy codebase

Maybe other things...

**Comment by czgdp1807** [comment]
May this can be a part of next GSoD. What do you all say?

**Comment by asmeurer** [comment]
GSoD is generally better for things that don't require direct technical knowledge of SymPy (so improvements to existing documentation, rather than new documentation). 

If our SciPy tutorial is accepted we plan to have a section on this sort of thing, although less detailed. It might be a good idea to write this as part of that.

**Comment by czgdp1807** [comment]
Closing this in favour of https://github.com/sympy/sympy/pull/19190

**Pull request closed without merging**
