### PR TITLE
Support augmented matrices in rref()

### PR DESCRIPTION
**Pull request by bjodah**
This is a way to allow rref to handle augmented matrices without introducing any backward incompatible changes. cf. https://en.wikipedia.org/wiki/Row_echelon_form#Systems_of_linear_equations and https://en.wikipedia.org/wiki/Augmented_matrix#Solution_of_a_linear_system

Let me know what you think.

### CODE REVIEW

**Comment by bjodah** [comment]
cc @siefkenj if interested (based on git blame).

**Comment by siefkenj** [comment]
Interesting.  In general I am not in favor of adding unnecessary complexity to the math algorithms.  Is there a reason you don't augment the matrix with `row_stack`/`col_stack`, row reduce, and then extract the augmented part?  This would avoid the need to change the rref algorithm at all.

Augmented matrices in general seem like they might be better served by a subclass of `MutableMatrix`  That is, you subclass `MutableMatrix` to `AugmentedMatrix` which is aware of which part is the _main_ matrix and which part is the _augmented_ part.  Then you could do something like `AugmentedMatrix(...).rref().get_parts()` or some such.

**Comment by bjodah** [comment]
The `rref` algortihm did not play well with an extra column, here is the matrix from my new test:
```
>>> from sympy import Matrix, symbols
>>> x, y, z = symbols('x y z')
>>> A = Matrix([[-1, 0, 1, x], [1, 2, 1, y], [1, 1, 0, z]])
>>> A.rref()
(Matrix([
 [1, 0, -1, 0],
 [0, 1,  1, 0],
 [0, 0,  0, 1]]), [0, 1, 3])
``` 
as you can see the symbols are lost, perhaps it should be considered a bug in `rref`?

An augmented matrix class could very well be useful, but perhaps it should handle more things than `rref` then?

**Comment by jksuom** [comment]
It could also be possible to have a single augmented input matrix together with an optional keyword `cols` showing the extent of the main part of the matrix. (`if not cols: cols = self.cols`, `for i in range(cols):`)

**Comment by bjodah** [comment]
It seems like `rref` in master branch currently handles an extra symbolic column in the augmented matrix when the original matrix has full rank (since the loop exits before reaching the augmented part), but not if the original matrix is rank deficient. The `cols` kwargs might be needed for this situtation?

**Comment by siefkenj** [comment]
@bjodah The system you showed above is inconsistent.  Is there an instance where you would want more information than "inconsistent"?

**Comment by bjodah** [comment]
@siefkenj, are we talking about:
```
A = Matrix([[-1, 0, 1, x], [1, 2, 1, y], [1, 1, 0, z]])
```
where the last column is part of the augmented matrix (and not the 3x3 matrix describing the system)?

Then I would argue that it the third row is simply a linear combination of the above rows (row3 = ½row2 - ½row1) and hence the system is simply underdetermined. I'm writing a library that will deal with under determined systems all the time (with varying degree of "underdeterminedness").

**Comment by siefkenj** [comment]
@bjodah to get your expected behavior, you can augment with the identity, row reduce, extract the right hand side, and then multiply your "augmented" column `[x,y,z]` by what you extracted.  This will avoid over-reducing but also won't affect the algorithm.

**Comment by bjodah** [comment]
@siefkenj thank you for pointing this out. I didn't think about that, I realize I need to tackle my problem differently.

This also made me realize that the result of rref on an augmented matrix corresponding to a under determined (although consistent) system like mine has not one, but multiple solutions:
```
1, 0,  1 | (y - x)/2
0, 1, -1 | x
0, 0,  0 | ½(x - y + 2z)
```
and
```
1, 0,  1 | z
0, 1, -1 | y - 2z
0, 0,  0 | x - y + 2z
```
and
```
1, 0,  1 | z
0, 1, -1 | x
0, 0,  0 | -(x - y + 2z)
```
which is natural since the system has an infinite number of solutions.

I was simply hoping rref would make the system canonical, but I guess this is not possible (unless one define some extra criterion for canonicalization).

**Pull request closed without merging**
