### PR TITLE
Fixed #17405

### LINKED ISSUE #17405: plot of function with fractional exponent fails (version 1.4)
Plotting a function with a broken exponent fails with sympy version 1.4. No error is displayed. The coordinate cross is displayed, but the graph of the function is missing.
With sympy version 1.3 the function is plotted correctly (see attached example).
System is Python 3.7.4 on Windows (WinPython)

plot_test

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Fixes #17405 

#### Brief description of what is fixed or changed
Plotting works even if the start-point happens to be `None` (because it is a complex number(?)).

#### Release Notes

* plotting
   * Plots with fractional exponents and negative base values works again.

### CODE REVIEW

**Comment by jmig5776** [comment]
Does this code gives correct graph?
```
from sympy import cos, log, plot
from sympy.abc import x
plot(sin(log(x), (x, .001,10), xscale='log')
```

**Comment by oscargus** [comment]
Will check later. Maybe you are right that the log- stuff breaks again... We really need a way to test plotting...

**Comment by oscargus** [comment]
This is correct, right?

image

**Comment by oscargus** [comment]
I think I've found a way to confirm that we at least do not get an empty plot for these two cases. Will add a test eventually.

**Comment by jmig5776** [comment]
> This is correct, right?

Yes, it is right as expected.

> Will add a test eventually.

Yeah, this is necessary because previously the test was not added for it.

**Comment by oscargus** [comment]
Added tests for these issues. Basically, the test is to make sure that there are segments added to the plot. Not sure if I actually test the correct thing for #16796, but at least the plot cannot disappear without the test failing...

Also fixed a small discrepancy where the first and last points of the plot was not np.array, but standard lists. Clearly it didn't matter. Not sure if it may be better to change it to not use np.array?

**Pull request merged**
