### PR TITLE
Latex parsing of not equal, less than, greater than

### PR DESCRIPTION
**Pull request by bhpayne**
#### References to other Issues or PRs
no issues related to neq in Latex

#### Brief description of what is fixed or changed
added support for \neq in Latex based on @iammosespaulr 's work, and expanded less than, greater than support in Latex

#### Release Notes

* parsing
  * added Latex support for "not equal" and expanded support for less than, greater than symbols

### CODE REVIEW

**Comment by bhpayne** [comment]
The failed test appears to be a timeout

    The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by bhpayne** [comment]
I tested this branch locally on my computer using both

    >>> sympy.test()
    >>> sympy.test("sympy/parsing/tests/test_latex.py")

The first took 2 hours; the second took 4.5 seconds. Both passed.

**Comment by oscarbenjamin** [comment]
I've restarted the test that timed out. Maybe it's just a momentary problem on the test server

**Comment by czgdp1807** [comment]
Is it good to merge? @iammosespaulr @oscarbenjamin

**Pull request merged**
