### PR TITLE
Tensor module: STEP 2 of removal of polynomial dependence of the algorithms

### PR DESCRIPTION
**Pull request by Upabjojr**
_TIDS_ class now completely disconnected from tensor expressions.

New class _IndexStructure_ does not contain references to components: only to indices.

This is another step towards a tensor module which supports expressions different from polynomial ones.

_gamma_matrices.py_ does not work anymore. I don't feel like fixing it again, as there will likely be other breaking commits in the future. By the way, _gamma_matrices.py_ had logical flaws, it had to be rewritten anyway.

At first sight, this PR may seem to be harmful: no new features, breaking some features about gamma matrices. Unfortunately it's a necessary step. The tensor module was originally written to perform only on expanded polynomial expressions. This step will allow to generalize it in the (next) future.

I feel confident that we are getting close to support derivatives of tensor expressions, at last enabling some physical calculations.

### CODE REVIEW

**Comment by Upabjojr** [comment]
@certik this is the second step of the refactory I started last december.

I eliminated the dependence on the _TIDS_ class, which contained information about indices of polynomial tensor expressions, and created the _\_IndexStructure_ class, which handles indices only.

I feel confident that I am a step closer to being able to represent partial derivatives with this module.

Unfortunately the gamma matrix code does not work anymore. I don't think that's a problem, as gamma matrices without derivatives are practically useless, i.e. most possible practical calculations involving gamma matrices also require derivatives. Furthermore, I really regret choosing that kind of subtyping for the gamma matrix object... That module needs to be rewritten, but only after a refactory of this module is completed.

I don't want to try to fix the gamma matrices classes, because it's likely that the next rewriting step will also require them to be fixed, again.

So, have a look, if you think this could be merged.

**Comment by certik** [comment]
Thanks @Upabjojr I'll have a look. I understand that the current system in master is not ideal, but what is the point of having a broken code in there? Why not just remove the gamma matrices functionality completely?

**Comment by Upabjojr** [comment]
I left the broken code there because that will keep reminding people to eventually fix it. Furthermore, when the code will be fixed, git will show immediately the differences, while deleting and recreating the code will show everything as new.

Anyway, that's just my thought, should I remove the gamma matrices from master temporarily?

**Comment by Upabjojr** [comment]
Note: after this PR, all index algorithms will be separated from the tensor expression algorithms, at last!

I thought as the next step of the creation of an index mapping for all classes inheriting _TensExpr_, and of trying the creation of a _PartialDerivative_ object inheriting _TensExpr_.

**Pull request merged**
