### PR TITLE
Failing travis warnings

### PR DESCRIPTION
**Pull request by iammosespaulr**
This PR is for checking whether benchmarks fail when performance is significantly poorer than the earlier implementation.
From #19223

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by iammosespaulr** [comment]
I made some changes to slow down binomial, it slowed it down too much and travis failed with a timeout error. @oscarbenjamin

**Comment by oscarbenjamin** [comment]
If you're looking for a way to break the benchmarks then try the opposite of #19233

**Comment by oscarbenjamin** [comment]
I think the improvements from #19205 have meant that this still didn't fail the benchmarks. It would for cholesky_solve with n=3 but that isn't run because it was too slow before.

Maybe just add a call to `eigenvals` in `is_positive_definite` because that was the original slowdown that failed the benchmark.

**Comment by iammosespaulr** [comment]
@oscarbenjamin I reverted the commit which removed `eigen` from `is_positive_definite` and kinda messed it up, I'll revert the latest commit and could you make the change mentioned 👇 ( I am not really familiar with the matrices codebase yet 😁)

> 
> Maybe just add a call to `eigenvals` in `is_positive_definite` because that was the original slowdown that failed the benchmark.

**Comment by sylee957** [comment]
You should revert the duplicate changes with #19233

**Comment by oscarbenjamin** [comment]
I think `asv compare` gives a non-zero exit code regardless of the benchmark results so we probably need to parse the output in order to get the travis job to fail.

**Comment by oscarbenjamin** [comment]
Looks like this isn't working. This PR can be closed I guess

**Pull request closed without merging**
