### PR TITLE
utilities._compilation: allow passing extra objects

### PR DESCRIPTION
**Pull request by bjodah**
#### References to other Issues or PRs
In one way, this is a natural extension of gh-25735, there we tested that we could build object files, but there was no natural way to use those in our existing API.

#### Brief description of what is fixed or changed
A new keyword argument `extra_objs=None` is introduced in a few functions. This is somewhat awkward in `link(obj_files, ...)`, but currently the name of the generated file taken to be the last of the files among `obj_files` by default. This causes problems when, for example, building a Cython extension, since the name of the extension module (shared object file) must match the `PyInit_NAMEOFEXTENSION` symbol for python's loader to work.

#### Other comments
~~When developing this, I used pytest with the `--pdb` flag, for that workflow `tempfile.TemporaryDirectory` has the poor habit of deleting all the interesting files before entering the debugger. Therefore I include a variant here which postpones cleanup to end of process, cf. https://github.com/sympy/sympy/pull/25735#discussion_r1338913970 .~~

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Would it work to use pytest's tmpdir fixture:
https://docs.pytest.org/en/6.2.x/tmpdir.html#the-tmpdir-fixture

**Comment by bjodah** [comment]
It might work, typically I shy away from test fixtures if I can (I find them complicated/"too much magic"/unnecessary coupling testing framework, but perhaps it speaks more to my inexperience with them).

I can also simply revert that part of the change and keep using `tempfile.TemporaryDirectory` (which is fine in our CI environment since will not be performing an live debugging there either way...).

**Comment by bjodah** [comment]
So adding an argument `tmpdir` seems to work. One added benefit is also that the test files aren't removed after pytest has finished.

**Comment by oscarbenjamin** [comment]
> the test files aren't removed after pytest has finished

Do we not want them to be removed?

**Comment by bjodah** [comment]
pytest limits the number of retained temporary directories held onto to at
most three. Also, at least under *nix, they seem to reside under /tmp,
which means that they typically gets cleaned up at reboot either way.

**Comment by oscarbenjamin** [comment]
Okay, looks good.

**Comment by oscarbenjamin** [comment]
> I shy away from test fixtures if I can (I find them complicated/"too much magic"/unnecessary coupling testing framework

I agree. This is probably not much better than using atexit but I was hoping there could be a better way and maybe there just isn't.

**Comment by bjodah** [comment]
Thank  you for the review!

**Pull request merged**
