### PR TITLE
Make dynamicsymbols real by default 2

### PR DESCRIPTION
**Pull request by moorepants**
Added a commit to #9818.

### CODE REVIEW

**Comment by moorepants** [comment]
I'd like it if monkeypatching `TIME` worked like this:

```pycon
>>> import sympy.physics.vector.functions
>>> sympy.physics.vector.functions.TIME = Symbol('T')
>>> from sympy.physics.mechanics import dynamicsymbols
>>> print(dynamicsymbols.t)
T
```

**Comment by asmeurer** [comment]
I guess it should be better documented in the intro stuff that you should always use `dynamicssymbols.t`.

**Comment by asmeurer** [comment]
What is the value of having the separate `TIME` module variable? The docs show monkeypatching `dynamicssymbols.t`.

**Comment by moorepants** [comment]
I personally think that having the `.t` attribute attached to `dynamicsymbols()` is confusing and odd, even if we document it better. We need a default symbol for time that the classes and functions in sympy.physics.vector/mechanics recognize unless the user sets it to something else. It seems more intuitive to have a global variable of sort that can be modified. I'd like to remove `dynamicsymbols.t`` in the long run.

I'm not quite sure how to implement this though.

**Pull request closed without merging**
