### PR TITLE
Added tests for floor function

### PR DESCRIPTION
**Pull request by techytoes**
Added tests for floor functions in `test_ccode.py`.

Please review it @asmeurer @smichr @bjodah

### CODE REVIEW

**Comment by bjodah** [comment]
Is this just in order to add a test? on master:
```
In [1]: ccode(floor(x))
Out[1]: 'floor(x)'
```
We should test all math related functions. When [this PR](https://github.com/sympy/sympy/pull/12693/files#diff-cd286781db8026a95298392e102bd143R653) is merged that should be covered.

**Comment by smichr** [comment]
> When this PR is merged that should be covered.

So are you saying this PR is redundant or are you ok with this PR as is?

**Comment by bjodah** [comment]
Maybe a little redundant? The first simple of test of `floor` is fine.
@firedranzer would you mind elaborating a little on this test:
```
assert ccode(floor(x)), user_functions=custom_functions) == "floor(x)"
```
isn't this functionality already tested in the other tests specifying `user_functions`?

I'm fine with the PR as is though, I guess there is no need to keep the test suite minimal.

**Comment by firedranzer** [comment]
@bjodah I am not sure if the tests would run fine without this functionality.
Are you suggesting about removing this functionality because looking at the `ceiling` function, I felt the need to address the same functionality to `floor` function.

**Comment by firedranzer** [comment]
@bjodah I have removed the functionality specifying `user_functions` .
please review the changes.

**Comment by smichr** [comment]
> in an ad hoc manner

I agree

**Comment by gxyd** [comment]
@bjodah can you please confirm if this PR is needed at all now? The links seems to referring to old changes, and may be you already made those changes in PR #12693.

**Comment by bjodah** [comment]
@gxyd you're right that #12693 includes the neccessary testing. Thank you @firedranzer for the PR.

**Pull request closed without merging**
