### PR TITLE
Implemented tendon force-length characteristic curve in `sympy.physics._biomechanics`

### PR DESCRIPTION
**Pull request by brocksam**
#### References to other Issues or PRs

Forms part of the CZI biomechanics work program described in https://github.com/sympy/sympy/issues/24240.

#### Brief description of what is fixed or changed

This PR creates a new module within `sympy.physics` called `_biomechanics`, which will contain the biomechanics functionality for SymPy, an extension of `sympy.physics.mechanics`.

This first PR implements the first (of many) musculotendon characteristic curves. Specifically it implements a SymPy `Function` defining the tendon force-length characteristic based on the equations from De Groote et al. (2016). This is to act as a template for other characteristic curves. It supports code generation across a range of target languages, more of which can easily be added by following the pattern in `sympy/physics/_biomechanics/characteristic.py`.

I have named the module with a leading underscore for the time being to signify that it is experimental and therefore does not guarantee that API changes will not happen. I believe that this is very important as its likely breaking API changes will need to be introduced as further (biomechanics) functionality is introduced, fed back on, and tested.

I have not added any documentation beyond docstrings, nor have I added the docstrings to the online documentation yet. For the reasoning above this would likely need significant rewriting after any API changes. Documentation will be contributed in a future PR when the whole biomechanics module is moved to `sympy/physics/biomechanics`.

#### Other comments

I have specifically left the release notes entry empty. These will be added in the PR that moves the whole biomechanics module to `sympy/physics/biomechanics`.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by brocksam** [comment]
JAX printing tests will pass after merging PR #25439.

**Comment by brocksam** [comment]
Tests not passing because test cases needed for new `Function` subclasses in `sympy/core/tests/test_args.py::test_all_classes_are_tested`.

**Comment by brocksam** [comment]
I'm now coming round to the idea that `TendonForceLengthDeGroote2016` would be a better naming pattern to follow for the musculotendon curve `Function`s.

**Comment by moorepants** [comment]
I've walked through this with Sam and am good with the basic implementation. I can be merged with some minor updates he's making now.

**Comment by brocksam** [comment]
Type hints removed in https://github.com/sympy/sympy/pull/25516.

**Review by moorepants — APPROVED** [review]

**Pull request merged**
