### PR TITLE
enforce Boolean args in BooleanFunction

### LINKED ISSUE #13223: ITE.to_nnf appears to use Boolean of else arg
I expect both to give the same result in the following:

```
>>> e = ITE(x<1,(1,2),S.NaN)
>>> e.to_nnf().subs(x,2)
True
>>> e.subs(x,2)
NaN
```

The NaN evaluates in a different way than the (1,2) does in an Or: Or(x<1,foo) is True if foo is a Number.

### PR DESCRIPTION
**Pull request by smichr**
Current modifications:

* SymPy now enforces Boolean args where and when appropriate, e.g. `And(1, 0)` -> False but `And(1, 2)` and `And(x + 1, y)` raise a TypeError b/c of 2 and `x + 1`, respectively.
* ITE is still allowed to contain arbitrary, unsympified args.
* `Boolean.to_nnf` was added so `ITE(x, 1, 0).to_nnf()` does not generate an error.
```
>>> ITE(x, 1, 0)
x  # didn't have to_nnf method
```

=============== old comments

The Bool function was added which converts, when possible, its argument to
a True or a False value. This is similar to the bool function of python
with the following difference: **plain symbols and values which cannot be
determined to be zero or nonzero are not converted (and nan, being a
Number which is neither zero nor non-zero, is not converted)**. This opens
the posibility of representing Piecewise with no default condition as
an ITE with a nan for the default, e.g.

Piecewise((x, x > 1)).rewrite(ITE) -> ITE(x > 1, x, S.NaN)

(This change is not part of this commit, however.)

```
>>> bool(x)
True
>>> x.is_Boolean, isinstance(x, Boolean)
False, True  # is that right?
>>> Bool(x)
x
>>> Bool(S.NaN)
S.NaN
>>> ITE(x<1,(1,2),S.NaN).to_nnf()  # from #13223
nan | (x < 1)
```

closes #13223

### CODE REVIEW

**Comment by asmeurer** [comment]
I think this needs a better name. Bool sounds too much like the type (which is `Boolean`).

**Comment by asmeurer** [comment]
Also I'm not sure I like having this by default in Boolean. I'd rather see Boolean kept "pure", from a mathematical perspective.

**Comment by smichr** [comment]
> Also I'm not sure I like having this by default in Boolean. I'd rather see Boolean kept "pure", from a mathematical perspective.

Can you give me a concrete example of something that you like now that you don't like with these changes?

**Comment by asmeurer** [comment]
I like that booleans are a separate type from scalars (with the exception of Symbol, which currently can act as both https://github.com/sympy/sympy/issues/8192). This is analogous to scalars vs. matrices, which cannot be mixed except where it mathematically makes sense.

**Comment by smichr** [comment]
> I like that booleans are a separate type from scalars

Agree...but I am not sure what it is that I changed that you don't like.

Also, are you aware that for `var('x')`, `x.is_Boolean` is false while `isinstance(x, Boolean)` is true?

**Comment by asmeurer** [comment]
Oh apparently we did make Symbol a subclass of Boolean at some point. I had forgotten about that.

**Comment by asmeurer** [comment]
I don't like that it makes it official that `expr` means `expr != 0` in the logic module. It already works that way with numbers, but I'd say that's by accident (garbage in, garbage out).  I would prefer to be explicit Q.nonzero(expr) or `Ne(expr, 0)` (and then make the logic and assumptions functions work better with those if necessary).

**Comment by smichr** [comment]
> I don't like that it makes it official that expr means expr != 0 in the logic module

Maybe you are missing that it is careful *not* to make this assumption:

```  
 45 +    if isinstance(e, Expr):  
 46 +        z = e.is_zero  
 47 +        return S.false if z else (S.true if z is False else e)  
```

`expr (e) -> False` only if `e.is_zero` is True;  `Bool(var('x') + 1)` is just `x + 1`. This is the motivation of Bool over bool: the latter assumes that `expr != 0` -> True while Bool does not.

The name might be misleading if you think that Bool does what bool does but returns true and false instead of True and False. Perhaps `Truth` or `logic_val` would be a better name...I'm grasping, here...I'm not really sure what else to call it.

**Comment by smichr** [comment]
@asmeurer , what do you think about these requirements:

```
for ITE(b, e1, e2) assert isinstance(b, Boolean) 
but e1 and e2 can be anything and are unmodified args

given ITE, ITE.to_nnf() converts e1 and e2 to equivalent Booleans
except when they are Expr (in which case they are only converted if ei.is_zero is not None) 
or S.NaN (which is also not converted).
```

**Comment by asmeurer** [comment]
I get that it is more mathematically aware (when I say `= 0` above I mean mathematically equal, not Python `==`).  I just think being fuzzy with types is mathematically imprecise and can lead to problems, especially for SymPy where things need to be mathematically correct.

**Comment by asmeurer** [comment]
Perhaps this will make things clearer.  Consider the end-goal here, to make `Piecewise((a, cond), (b, True)).rewrite(ITE)` give `ITE(cond, a, b)`. Under this change, we would have

    Piecewise((0, x > 0), (1, True))

give

    ITE(x > 0, False, True)

which is equivalent to

    Not(x > 0)

(you can see it auto simplifies to `x <= 0`). One way to think of this is that "if x > 0, False", as a boolean condition, implies that `x > 0` is not true. Or consider the possible values for `x > 0`. If `x > 0` is True (x is positive), then the first part of the ITE is used (the second argument), `False`. If `x > 0` is False (x is negative), then the second part if used (the third argument), `True`. So it has the truth table

    x > 0 | ITE(x > 0, False, True)
    -------------------------------
    True  | False
    False | True

which is the same truth table as `Not(x > 0)`. Hence, they are logically equivalent. 

Now to get to the point, `x <= 0` is a very different thing than `Piecewise((0, x > 0), (1, True))`. One is a boolean condition, the other is a piecewise function. The only way you could possibly map `x <= 0` back to `Piecewise((0, x > 0), (1, True))` would be with the [indicator function](https://en.wikipedia.org/wiki/Indicator_function) (we don't have the indicator function in SymPy, one would have to use a Piecewise). Even if you wanted to be cavalier about the distinction between a boolean, its set, and the set's indicator function, consider instead `Piecewise((0, x > 0), (2, True))`. This example would actually be 2 times the indicator function for `x <= 0`. But with the logic in this PR, both `ITE(x > 0, 0, 1)` and `ITE(x > 0, 0, 2)` are the same thing. 

So to summarize:

- I think converting Piecewise to ITE or ITE to Piecewise is a bad idea. It can make sense if the Piecewise has booleans for the expr, but even then I would prefer to keep the two separate. 

- I don't think there's a benefit to the logic module to consider an expression `expr` to implicitly represent `expr != 0`. One can easily create such a boolean with `Q.nonzero(expr)` or `Ne(expr, 0)`, which is only a few more characters, but way more explicit. And it avoids issues inherent in the one-directionalness of such a transformations of `numbers` -> {True, False}. 

I'm trying to understand what is your end goal here with Piecewise and ITE. Where is Piecewise currently being used in SymPy with `expr` terms that are not expressions (I also want to know where they could be a tuple)? 

Maybe it makes sense for Piecewise to have anything as the expr. After all, it could happen anywhere  that you'd want something to be a different thing based on a condition. I don't think it's designed for it, but maybe things could be changed (for example, the fact that NaN is used implicitly means it is an expression, since NaN only makes sense in expression contexts). But for the specific case of booleans, ITE is a better approach, and conversely, ITE is a very *wrong* approach when the arguments are not booleans. I think trying to shoehorn NaN into non-expression contexts just because Piecewise uses it is also a bad idea.

**Review by asmeurer — DISMISSED** [review]
I don't think this PR is a good idea. See the comments.

**Comment by smichr** [comment]
Appreciate your sentiments and have made the following changes:

* SymPy now enforces Boolean args where and when appropriate.
* ITE is still allowed to contain arbitrary, unsympified args.
* `Symbol.to_nnf` was added so `ITE(x, 1, 0).to_nnf()` does not generate an error. The ITE -> x.

**Comment by asmeurer** [comment]
Did you push? I don't see them. 

Also, the default to_nnf should probably be on Boolean itself, so that any Boolean won't have that issue.

**Comment by smichr** [comment]
> the default to_nnf should probably be on Boolean

In the flurry of activity before I left, I didn't push. Just as well -- I was able to relocate the `to_nnf` to Boolean as you suggested.

In the issue you asked in which circumstances a Piecewise to ITE might be necessary. This arises for the case where a condition in a Piecewise is itself given as a Piecewise, e.g. 

```
c = Piecewise((x < 1, y > 1), (x < 2, True))
Piecewise((x + 1, c))
```

In order to rewrite this as a Boolean I was thinking to rewrite to ITE and convert to Boolean via to_nnf. Alternatively, one could just be forced to write this as `ITE(y > 1, x < 1, x < 2)`. Perhaps it would be better to do so since this would enforce that the condition is completely specified; Piecewise would not (and can not trivially) tell whether this has been done or not, e.g. `Piecewise((a, x<1), (b x > 1))` does not handle `x == 1`.

**Comment by smichr** [comment]
> I'm trying to understand what is your end goal here with Piecewise and ITE

See our discussion [here](https://github.com/sympy/sympy/pull/13204#issuecomment-326121768) where a Piecewise is used as a lhs in a Relational. This is what we might call a proper use of Piecewise as the expr contains Expr and the cond contains Boolean. When this is folded, however, a Piecewise results. (That was a change that I made over old behavior.) Perhaps that was the reason that the code to turn Piecewise with Boolean expr into full Booleans was there in the first place. If I put that code back in (or its equivalent) then we would be back to enforcing Expr and Boolean only residing in ExprCond pairs.  I'll look again at that old rewriting of Piecewise with Boolean exprs.

**Comment by asmeurer** [comment]
> See our discussion here where a Piecewise is used as a lhs in a Relational. 

OK, this seems legitimate. My only concern is, will Piecewise methods and functions assume that the `expr` parts are `Expr` (use whatever methods of Expr, like as_coeff_whatever, which don't exist on Boolean)? If so, it's cleaner to use ITE here instead of Piecewise, and improve the printing, etc. of ITE (or alternately, always fold such Piecewise as I suggested in the comment, which ITE can help with). 

> Perhaps it would be better to do so since this would enforce that the condition is completely specified

Another good point. The default `nan` else clause for Piecewise doesn't make sense as a boolean. Although I think False is the best default else for this context because it would cause it to move the next condition of the (outer) Piecewise. For ITE generally, though I don't know if a "default" else of either True or False makes sense (there are probably contexts where you would want to default to True instead).

**Comment by asmeurer** [comment]
By the way, `nnf` or `cnf` aren't necessarily the simplest forms of a logical expression, in terms of ability for a human to parse. Another way to think of `ITE(x, y, z)` is `And(Implies(x, y), Implies(~x, z))` ('if x, then y; if not x, then z').

**Comment by smichr** [comment]
> If so, it's cleaner to use ITE here instead of Piecewise

I'm working on another PR that is based off of this one (#13204). The way I've come to deal with it there is this: Piecewise can hold any Basic in the expression slot, but the condition slot must be some variety of Piecewise-free Boolean; this is enforced in ExprCondPair. So if a Piecewise involving Boolean expressions is written as a condition it is converted to ITE.

```
>>> cond = Piecewise((x<1,y<1),(x<2,True))
>>> cond
Piecewise((x < 1, y < 1), (x < 2, True))
>>> Piecewise((1, cond))
Piecewise((1, ITE(y < 1, x < 1, x < 2)))

>>> pcond
x < Piecewise((1, y < 1), (2, True))
>>> Piecewise((1, pcond))
Piecewise((1, ITE(y < 1, x < 1, x < 2)))
```

When folding, ITE is converted to nnf form so when any part of SymPy is working with a folded expression, they know they will only have to unpack, at worst, a BooleanFunction as a condition
-- and, BTW, I am using simplification of *univariate* expressions so it comes out simpler than the nnf:
```
>>> piecewise_fold(_)
Piecewise((1, ((y >= 1) | (x < 1)) & ((x < 2) | (y < 1))))
```

> will Piecewise methods and functions assume that the expr parts are Expr

I haven't had too much problem yet with allowing Basic in general. But this situation is not too different than dealing with a non-piecewise object: garbage in garbage out.

> For ITE generally, though I don't know if a "default" else of either True or False makes sense

I agree. This is the place for the fuzzy S.none ;-) One could supply a dummy so that `ITE(x < 1, x).subs(x, 2)` -> `Dummy('unknown'))`

One of the things that I'm running into with the Piecewise is trying to represent solutions to Piecewise equations. Here is a simple example:

```
f = Piecewise(((x - 2)**2, x >= 0), (0, True))
assert solve(f, x) == [2, Piecewise((x, x < 0), (S.NaN, True))]
```

2 is always part of the solution and the other solution is x when x < 0. The nan is included as an arg in master and I didn't change it...but I don't like it either because you end up with a "gremlin" in the list. I would prefer `Piecewise((Tuple(x, 2), x < 0), (Tuple(2), True))`.

======

For the purposes of this PR, all we have to decide on is whether or not to insist that the ITE condition be a Boolean and whether ITE.to_nnf can raise an error if non-Booleans are in the non-condition slots.

**Comment by asmeurer** [comment]
> 2 is always part of the solution and the other solution is x when x < 0. The nan is included as an arg in master and I didn't change it...but I don't like it either because you end up with a "gremlin" in the list.

That doesn't seem right. The solution of an equation in x should not depend on x.

**Comment by asmeurer** [comment]
This is probably where solveset makes things clearer. The solution set is {x | Not(x >= 0}} U {2} (the first part being a different thing depending on if the domain is real or complex).

**Comment by asmeurer** [comment]
Or another way to think of it is that `solve` doesn't support infinite solution sets, because it returns expressions and the only way to represent an infinite set with an expression is to add a new variable as a parameter. So for instance sin(x) = 0 has the solution set `n*pi`, but you have to introduce `n`, which `solve` has not tried to do (solveset nicely avoids the problem by returning a set, where `n` can be introduced as a bound variable). 

If you did somehow return `n*pi` for `solve(sin(x), x)` you'd have to have `n = Symbol('n', integer=True)`. For this, you'd have to return `[2, a]`, where `a = Symbol('a', nonpositive=True)`. To be clear, I'm not suggesting this should be actually done. It's a bad idea because

- The symbol, to be unique, has to be a Dummy, which means it also has to be returned separately to be easily accessible (which clutters the API even more). 
- The old assumptions are relatively hidden. You can't see that `a` really means "nonpositive numbers" without some introspection. 
- The old assumptions are limiting. You couldn't do the same for `a <= 1` (at least without jumping through some hoops, which would make the solution more complex).
- `solveset` already solves this problem quite elegantly. 

I think the fact that you are quickly getting infinite solution possibilities means that solveset, not solve, should be extended to solve Piecewise expressions.  In fact, isn't `solveset(Piecewise((expr, cond))` the same as `solveset(expr, domain=ConditionSet(cond))`? 

Regarding the other one, I don't think `nan` should ever be returned by solve (is it even possible to have an expression where you plug in nan and get 0? The only thing I can think of is `Piecewise((0, Eq(x, nan))`).

**Comment by smichr** [comment]
discussion moved to #13204 which includes modification of Piecewise, too.

**Pull request closed without merging**
