### PR TITLE
added is_number property for meijerg 

### PR DESCRIPTION
**Pull request by ashishkg0022**
meijerg.is_number was giving a wrong answer according to issue #13071.  so I added a new property for it.

### CODE REVIEW

**Comment by ashishkg0022** [comment]
@jksuom  can you please review it ?

**Comment by jksuom** [comment]
There is an example in core.expr.is_number that contains a symbol:
```
>>> (2 + Integral(2, (x, 1, 2))).is_number
True
>>> (2 + Integral(2, (x, 1, 2))).atoms(Symbol)
set([x])
```
Perhaps the test should be modified to ignore bound symbols such as `x` in the integral above.

**Comment by ashishkg0022** [comment]
Is it fine now ?

**Comment by ashishkg0022** [comment]
@jksuom  Is it fine now ?

**Comment by jksuom** [comment]
I think the code is fine, but there could also be a test where the result is not a number.

**Comment by ashishkg0022** [comment]
@jksuom i already have added it . line 126  `assert g.is_number is False`

**Comment by jksuom** [comment]
That is true. I failed to see that  g  was also a G-function.

Thanks! I think this is ready.

**Comment by ashishkg0022** [comment]
@jksuom  I think , I also should modify docstrings (examples) in `hyper.py` . what do you say ?

**Comment by ashishkg0022** [comment]
@jksuom 
```
 Examples
    ========

    You can pass the parameters either as four separate vectors:

    >>> from sympy.functions import meijerg
    >>> from sympy.abc import x, a
    >>> from sympy.core.containers import Tuple
    >>> from sympy import pprint
    >>> pprint(meijerg((1, 2), (a, 4), (5,), [], x), use_unicode=False)
     __1, 2 /1, 2  a, 4 |  \
    /__     |           | x|
    \_|4, 1 \ 5         |  /

    or as two nested vectors:

    >>> pprint(meijerg([(1, 2), (3, 4)], ([5], Tuple()), x), use_unicode=False)
     __1, 2 /1, 2  3, 4 |  \
    /__     |           | x|
    \_|4, 1 \ 5         |  /

    As with the hypergeometric function, the parameters may be passed as
    arbitrary iterables. Vectors of length zero and one also have to be
    passed as iterables. The parameters need not be constants, but if they
    depend on the argument then not much implemented functionality should be
    expected.

    All the subvectors of parameters are available:

    >>> from sympy import pprint
    >>> g = meijerg([1], [2], [3], [4], x)
    >>> pprint(g, use_unicode=False)
     __1, 1 /1  2 |  \
    /__     |     | x|
    \_|2, 2 \3  4 |  /
    >>> g.an
    (1,)
    >>> g.ap
    (1, 2)
    >>> g.aother
    (2,)
    >>> g.bm
    (3,)
    >>> g.bq
    (3, 4)
    >>> g.bother
    (4,)
```
In these examples `.is_number` should be added. Should I add it ?

**Comment by ashishkg0022** [comment]
I just want to add the example.

**Comment by jksuom** [comment]
Is there something wrong or do you just want to add some examples?

**Comment by jksuom** [comment]
It seems that docstring examples are generally focused on explaining the main subject. There is a big number of methods of the type `.is_xxxxx` and those are added to docstrings only if that would help to clarify the matter. In this case, I don't think that `.is_number` would be necessary in the docstring of `meijerg`.

**Comment by ashishkg0022** [comment]
ok. Thanks :)

**Comment by gxyd** [comment]
You can use 'Fixes #13071 ' in your commit message. That will close the issue.

**Pull request merged**
