### PR TITLE
printing: Update the example to caution against calling doprint

### PR DESCRIPTION
**Pull request by eric-wieser**
LatexPrinter.doprint() contains code to wrap the final result.
Calling this recursively leads to unwanted dollar signs.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Would it make sense to turn these examples into doctests somehow?

**Comment by eric-wieser** [comment]
It probably would, yes

**Comment by oscarbenjamin** [comment]
Is it just a case of adding the `>>>`?

**Comment by eric-wieser** [comment]
@oscarbenjamin: Updated to do just that, and also added some more explanation of what the examples are showing.

**Comment by oscarbenjamin** [comment]
Looks good

**Pull request merged**
