### PR TITLE
tangent to curve

### PR DESCRIPTION
**Pull request by AyushShuklaGit**
#### References to other Issues or PRs

#18871

### CODE REVIEW

**Comment by Smit-create** [comment]
You should create a branch in your forked repo and commit over it.
Also, please mention the  concerned issue in the OP and a brief description of what is changed

**Comment by smitgajjar** [comment]
Also, if you are new here, please go through [Sympy's development workflow](https://github.com/sympy/sympy/wiki/Development-workflow) once before contributing!

**Comment by Smit-create** [comment]
You need to change title so that it is related to change you are making.

**Comment by Smit-create** [comment]
Also please put this function in the related file instead of creating a new file. See other files for examples that are present in geometry module.

**Comment by smichr** [comment]
Just some ideas about other ways to represent this:

Define an expression in x and y

    >>> a,b,c,d,e,f,g,h=[randint(1,10) for i in range(8)]
    >>> eq = (x**2)*a+(y**2)*b+2*g*x+2*h*x*y+2*f*y+c

Get an expression for `dy/dx`

    >>> dydx = idiff(eq, y, x); dydx
    -(8*x + 9*y + 10)/(9*x + 7*y + 3)

Define an expression for the tangent:

    >>> T = Piecewise(
    (Symbol('above'), eq > 0),
    (Symbol('below'), eq < 0),
    (oo, Eq(denom(dydx), 0)),
    (dydx, True))

Find a point on the curve

    >>> solve(eq.subs(y,0))
    [-5/4 - sqrt(21)/4, -5/4 + sqrt(21)/4]
    >>> xx = _[0]

Test the T function

    >>> T.subs({x:xx,y:1})
    below
    >>> T.subs({x:xx,y:-1})
    above
    >>> T.subs({x:xx,y:0})
    2*sqrt(21)/(-9*sqrt(21)/4 - 33/4)

Another idea would be to return a value -- the value of eq at x and y -- if it is not on the curve, else a `Line((x, y), slope=tangent)`:

    >>> den = dydx.as_numer_denom()[1]
    >>> TT = Piecewise(
    (eq,
      Ne(eq, 0)),
    (Line((x, y), slope=Piecewise(
        (dydx, Ne(den, 0)),
        (oo, True))),
      True))

Find a vertical point:

    >>> xy = solve(1/dydx, x); xy
    [-7*y/9 - 1/3]
    >>> solve(eq.subs(x, xy[0]))
    [-66/25 - 9*sqrt(1974)/175, -66/25 + 9*sqrt(1974)/175]
    >>> TT.subs(x, xy[0]).subs(y, _[0])
    Line2D(Point2D(43/25 + sqrt(1974)/25, -66/25 - 9*sqrt(1974)/175), Point2D(sqrt(1
    974)/25 + 68/25, oo))

    >>> TT.subs(x,0).subs(y,1)
    15
    >>> TT.subs(x,-1).subs(y,1)
    -15

**Comment by czgdp1807** [comment]
Which issue is this PR fixing?

**Pull request closed without merging**
