### PR TITLE
Improve combsimp()

### LINKED ISSUE #6153: Simplification of ratios of gamma functions
```
Sympy can not simplify some rations of two gamma functions.
An example is:

In [3]: gamma(1/S(4))/gamma(5/S(4))
Out[3]: gamma(1/4)/gamma(5/4)

In [4]: simplify(_)
Out[4]: gamma(1/4)/gamma(5/4)

In [5]: combsimp(_)
Out[5]: gamma(1/4)/gamma(5/4)

In [7]: expand_func(_)        
Out[7]: gamma(1/4)/gamma(5/4)

The correct result would be 4

Another one:

In [8]: gamma(S(3)/4)gamma(S(7)/4)
Out[8]: gamma(3/4)/gamma(7/4)

In [9]: combsimp(_)
Out[9]: gamma(3/4)/gamma(7/4)

The correct result would be 4/3

The formulas here could be useful: http://en.wikipedia.org/wiki/Particular_values_of_the_gamma_function#General_rational_arguments
```

Original issue for #6153: http://code.google.com/p/sympy/issues/detail?id=3054
Original author: https://code.google.com/u/107490137238222069432/

### LINKED ISSUE #6341: combsimp and binomial coefficients
```
In [161]: summation( binomial(n,k)**2, (k,0,oo))
Out[161]: 
Γ(2⋅n + 1)
──────────
        2 
Γ(n + 1)  

In [162]: combsimp(summation( binomial(n,k)**2, (k,0,oo)))
Out[162]: 
 2⋅n + 1           
2       ⋅Γ(n + 1/2)
───────────────────
      ___          
  2⋅╲╱ π ⋅Γ(n + 1) 

First off, I have n defined as an integer, so IMHO gamma should reduce to factorial in that case.

Second, this is just binomial(2*n, n).

Third, why doesn't this work:

In [165]: summation( binomial(n,k)**2, (k,0,oo)).rewrite(factorial)
Out[165]: 
Γ(2⋅n + 1)
──────────
        2 
Γ(n + 1)
```

Original issue for #6341: http://code.google.com/p/sympy/issues/detail?id=3242
Original author: https://code.google.com/u/asmeurer@gmail.com/

### LINKED ISSUE #6658: simplification of symbolic binomial
```
perhaps trivial equalities could be handled at instantiation;


>>> binomial(n,r)
binomial(n, r)
>>> binomial(n,n-r)
binomial(n, n - r)

The 2nd one could be binomial(n, r).
```

Original issue for #6658: http://code.google.com/p/sympy/issues/detail?id=3559
Original author: https://code.google.com/u/117933771799683895267/

### LINKED ISSUE #7135: rewrite(binomial) does not convert factorial expression
```
>>> binomial(n,k).rewrite(factorial)
factorial(n)/(factorial(k)*factorial(-k + n))
>>> _.rewrite(binomial)
factorial(n)/(factorial(k)*factorial(-k + n))

Should return: binomial(n,k)
```

Original issue for #7135: http://code.google.com/p/sympy/issues/detail?id=4036
Original author: https://code.google.com/u/118279007905392951376/

### LINKED ISSUE #8156: binomial coefficient of rationals does not simplify properly
I'll explain giving an example.

``` python
n = S(5) / 2
m = S(1) / 2
print gamma(n + 1) / (gamma(m + 1) * gamma(n - m + 1))  ## prints 15/8
print binomial(n, m)  ## prints binomial(5/2, 1/2)
print binomial(n, m).evalf()  ## prints 1.87500000000000
```

so, while the gamma function simplifies well enough, the binomial function does not; but it can simply use it, can't it?

### LINKED ISSUE #10101: Fresnel integrals contain gamma fcns and do not simplify enough
```
>>> y = sin(pi/2*t**2).integrate()
>>> pprint(y)

3⋅fresnels(t)⋅Γ(3/4)
────────────────────
      4⋅Γ(7/4)      

>>> pprint(simplify(y))

3⋅fresnels(t)⋅Γ(3/4)
────────────────────
      4⋅Γ(7/4)      
```

But the various constants are (correctly) just 1:

```
>>> pprint(N(y))

1.0⋅fresnels(t)
```

I haven't looked carefully, but one possibility is

```
>>> gamma(S(3)/4) / gamma(S(7)/4)

gamma(3/4)/gamma(7/4)

>>> simplify(gamma(S(3)/4) / gamma(S(7)/4))

gamma(3/4)/gamma(7/4)

>>> N(gamma(S(3)/4) / gamma(S(7)/4))

1.33333333333333
```

which is possibly related to #8156.

### LINKED ISSUE #11548: simplification of binomial (0,m) gives 0
If `m = symbols("m", integer=True)`, the simplification of the binomial `simplify(binomial(0,m))` return 0, which is not correct when `m=0`.

This is for SymPy 1.0 (Python 3.5.2-64-bit) installed via Anaconda 3.

### PR DESCRIPTION
**Pull request by ylemkimon**
* Removed original as_gamma, as_factorial, as_binomial detection by checking whether original expression contained them.
* Added as_gamma as option(default None), and when None, it automatically detects by checking non-integer arguments of CombinatorialFunctions and gamma functions exist. Since factorial and binomial coefficient are defined for integers and expanded to real numbers with gamma function, I think if non-integer arguments are present, it makes more sense and is more simplified to write them in gamma functions. Fixes #8156
* Removed rewriting binomial coefficient to `_rf((n - k + 1).expand(), k.expand())/_rf(1, k.expand()))`. Fixes #11548 
* Added binomial coefficient simplification using `binomial(n, n-r) = binomial(n, r)`. Fixes #6658 
* Only apply gamma function simplifications when as_gamma is True to preserve integer arguments. Fixes #6341
* Expand gamma functions with rational number argument. Fixes #6153 and fixes #10101
* Added as_binomial as option(default True), and when True, it finds (a+b)!/a!b! and replaces with binomial coefficient. Fixes #7135 and #6341 (Should include inexact matches like (a+b-1)!/a!b!? It may become more complicated.)

~~**TODO:**~~

- [x] ~~Rewrite to binomial coefficient doesn't work when a == b since it is automatically combined to Pow~~
- [x] ~~Add/fix test cases~~

Related issue(discussion) : #9785

### CODE REVIEW

**Comment by asmeurer** [comment]
Didn't see #9785 before. What do you think about splitting it into separate functions?

**Comment by ylemkimon** [comment]
@asmeurer I'm not sure. I think the question is simplification of 1. combinatorial functions with non-integer argument(s) and 2. gamma functions with (positive) integer argument.

**Comment by asmeurer** [comment]
We should probably decide how we want to handle this going forward, since this adds keywords to the combsimp API that we probably wouldn't want to have if we added a separate gammasimp function. 

I want to add that for any given expression you probably either want combinatoric functions (factorial, binomial) or analytic functions (gamma, beta), depending on whether the expression operates on integers or complex numbers. So it makes sense to me to split these into separate functions. In particular, combsimp would try to return an expression with factorials, binomials, etc. and gammasimp would try to return an expression with gammas, betas, and so on, even (optionally) converting gammas into factorials or factorials into gammas, respectively.

**Comment by ylemkimon** [comment]
@smichr So,
```python
n = Symbol('n', integer = True)
combsimp(fact(n)) -> fact(n)
combsimp(gamma(n + 1)) -> fact(n)
gammasimp(fact(n - S.Half)) -> gamma(n + S.Half)
gammasimp(gamma(n + S.Half)) -> gamma(n + S.Half)
```
?

**Comment by asmeurer** [comment]
(assuming you mean me, not smichr)

Perhaps it could do that, but only given that n is defined as an integer. Otherwise, gamma -> factorial is losing information, since it's only defined on integers. @jksuom you opened #9785 originally, what do you think?

**Comment by jksuom** [comment]
> but only given that n is defined as an integer.

I think this is the decisive point. `combsimp` would be designed to work with integers only. It should probably check the arguments and return ValueError if they are not integers (numbers or symbols defined as integers). It could also accept gamma (and convert it to factorial) provided the argument is an integer. `gammasimp` could accept also combinatorial functions and freely express them in terms of gamma for internal operations. It is conceivable that some of the resulting gammas could be converted to factorials on output if their arguments turn out to be integers, but that could be controlled by keyword arguments.

**Comment by ylemkimon** [comment]
@asmeurer @jksuom To sum up, what do you think about
Arguments | combsimp() | gammasimp() | gammasimp(as_comb=True)
----------- | ------------ | ------------ | ------------
integer | factorial, binomial | gamma | factorial, binomial
non-integer | Deprecated(ValueError in future) | gamma | gamma

**Comment by jksuom** [comment]
That looks like a good starting point to me.

**Comment by ylemkimon** [comment]
@asmeurer @jksuom Thank you.

Opened new PR #13210.

**Pull request closed without merging**
