### PR TITLE
Fixed the piecewise simplify when boolean conditions are included

### PR DESCRIPTION
**Pull request by geetikavadali**
#### References to other Issues or PRs

Solves the #25603 by #25615 

#### Brief description of what is fixed or changed
Fixed the conditions in piecewise when boolean is included. So now the preceding conditions are checked if covered already or not. 

#### Other comments
@smichr 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This is not correct:
```python
In [1]: p = Piecewise((f(1), (0 < x) & (x < 2)), (f(2), (1 < x) & (x < 3)))

In [2]: p
Out[2]: 
⎧f(1)  for x > 0 ∧ x < 2
⎨                       
⎩f(2)  for x > 1 ∧ x < 3

In [3]: p.subs(x, -2)
Out[3]: nan

In [4]: p.simplify()
Out[4]: 
⎧f(1)  for x > 0 ∧ x < 2
⎪                       
⎨f(2)      for x < 3    
⎪                       
⎩nan       otherwise    

In [5]: p.simplify().subs(x, -2)
Out[5]: f(2)
```

**Comment by oscarbenjamin** [comment]
I think that this whole block is not right:
https://github.com/sympy/sympy/blob/62c8a4e063c1af5d10045628c3fd5d6b4ffb79ab/sympy/functions/elementary/piecewise.py#L1167-L1208
The use of `covered` does not work because `covered` is the union of intervals previously seen. We can only skip something like `x > 1` if we have previously seen the entire interval `[-oo, 1]`.

**Comment by oscarbenjamin** [comment]
The checks should be more like
```python
if Interval(-oo, a).is_subset(covered):
```
rather than
```python
if a in covered:
```

**Comment by smichr** [comment]
If the Interval (a,b) being added does not have `a` in an interval with ivl.inf = -oo, then `a` must be included the condition it is not necessary that the new Interval be a subset, only that its lower bound be in a semi infinite Interval already covered. If `a` is in a finite Interval with maximal `bmax` then `a` should be replaced with `bmax` (or any integer, for simplicity, in that interval?) and included.

**Comment by smichr** [comment]
If you have some time could you look over this diff? I am differentiating between where to start the next interval and whether to include that starting point with `a >= x` or `a > x`. I added some additional tests.
```diff
diff --git a/sympy/functions/elementary/piecewise.py b/sympy/functions/elementary/piecewise.py
index 5793f9748f..3ef847644b 100644
--- a/sympy/functions/elementary/piecewise.py
+++ b/sympy/functions/elementary/piecewise.py
@@ -1144,6 +1144,7 @@ def _clip(A, B, k):
 
 def piecewise_simplify_arguments(expr, **kwargs):
     from sympy.simplify.simplify import simplify
+    from sympy.sets import Union
 
     # simplify conditions
     f1 = expr.args[0].cond.free_symbols
@@ -1160,12 +1161,21 @@ def include(c, x, a):
                 return c.subs(x, a) == True
             except TypeError:
                 return False
+        def lhs(a):
+            if a.is_finite and covered:
+                ivls = [covered] if not isinstance(covered, Union) else covered.args
+                for ivl in ivls:
+                    if a in ivl:
+                        return ivl.sup
+            return a
+
         if ok:
             args = []
             covered = S.EmptySet
             from sympy.sets.sets import Interval
             for a, b, e, i in abe_:
                 c = expr.args[i].cond
+                a = lhs(a)
                 incl_a = include(c, x, a)
                 incl_b = include(c, x, b)
                 iv = Interval(a, b, not incl_a, not incl_b)
@@ -1177,24 +1187,28 @@ def include(c, x, a):
                         c = S.true
                     elif b.is_infinite:
                         c = (x >= a)
-                    elif a in covered or a.is_infinite:
+                    elif a.is_infinite:
                         c = (x <= b)
+                    elif a in covered:
+                        c = And(a < x, x <= b)
                     else:
                         c = And(a <= x, x <= b)
                 elif incl_a:
-                    if a in covered or a.is_infinite:
+                    if a.is_infinite:
                         c = (x < b)
+                    elif a in covered:
+                        c = And(a < x, x < b)
                     else:
                         c = And(a <= x, x < b)
                 elif incl_b:
                     if b.is_infinite:
                         c = (x > a)
-                    elif a in covered:
+                    elif a.is_infinite:
                         c = (x <= b)
                     else:
                         c = And(a < x, x <= b)
                 else:
-                    if a in covered:
+                    if a.is_infinite:
                         c = (x < b)
                     else:
                         c = And(a < x, x < b)
diff --git a/sympy/functions/elementary/tests/test_piecewise.py b/sympy/functions/elementary/tests/test_piecewise.py
index ea07a4397d..dc03096c32 100644
--- a/sympy/functions/elementary/tests/test_piecewise.py
+++ b/sympy/functions/elementary/tests/test_piecewise.py
@@ -525,7 +525,8 @@ def test_piecewise_simplify():
     # coverage
     nan = Undefined
     covered = Piecewise((1, x > 3), (2, x < 2), (3, x > 1))
-    assert covered.simplify().args  == covered.args
+    ans = Piecewise((1, x > 3), (2, x < 2), (3, True))
+    assert covered.simplify()  == ans, (covered.simplify(),ans)
     assert Piecewise((1, x < 2), (2, x < 1), (3, True)).simplify(
         ) == Piecewise((1, x < 2), (3, True))
     assert Piecewise((1, x > 2)).simplify() == Piecewise((1, x > 2),
@@ -547,6 +548,12 @@ def test_piecewise_simplify():
     # https://github.com/sympy/sympy/issues/25603
     assert Piecewise((log(x), (x <= 5) & (x > 3)), (x, True)
         ).simplify() == Piecewise((log(x), (x <= 5) & (x > 3)), (x, True))
+    assert Piecewise((1, (x >= 1) & (x < 3)), (2, (x > 2) & (x < 4))
+        ).simplify() == Piecewise((1, (x >= 1) & (x < 3)), (
+        2, (x >= 3) & (x < 4)), (nan, True))
+    assert Piecewise((1, (x >= 1) & (x <= 3)), (2, (x > 2) & (x < 4))
+        ).simplify() == Piecewise((1, (x >= 1) & (x <= 3)), (
+        2, (x > 3) & (x < 4)), (nan, True))
 
 
 def test_piecewise_solve():
@@ -1343,6 +1350,7 @@ def test_issue_14787():
     f = Piecewise((x, x < 1), ((S(58) / 7), True))
     assert str(f.evalf()) == "Piecewise((x, x < 1), (8.28571428571429, True))"
 
+
 def test_issue_21481():
     b, e = symbols('b e')
     C = Piecewise(
```
This is the last commit in my pwsimp branch. If it looks good you could copy it here or apply the diff to your branch ... or come up with a better way to handle this.

**Comment by smichr** [comment]
@oscarbenjamin @geetHonve , please check modifications.

**Comment by geetHonve** [comment]
Is there a version issue? my fork is slightly different from your diff one even after syncing

**Comment by smichr** [comment]
Yes, if you 
1. apply this diff and 
2. commit it and then 
3. do `git rebase master` it will bring your branch to the same state as mine and allow you to squash commits together. I usually do 
4. `git reset head~n` where `n` is the number of recent commits that I want to squash together. Then I do 
5. `git commit  -am 'single commit name'`
```diff
diff --git a/sympy/functions/elementary/piecewise.py b/sympy/functions/elementary/piecewise.py
index d2dc7d7ce4..03a0971bce 100644
--- a/sympy/functions/elementary/piecewise.py
+++ b/sympy/functions/elementary/piecewise.py
@@ -1144,7 +1144,6 @@ def _clip(A, B, k):
 
 def piecewise_simplify_arguments(expr, **kwargs):
     from sympy.simplify.simplify import simplify
-    from sympy.sets import Union
 
     # simplify conditions
     f1 = expr.args[0].cond.free_symbols
@@ -1161,28 +1160,22 @@ def include(c, x, a):
                 return c.subs(x, a) == True
             except TypeError:
                 return False
-        def lhs(a):
-            if a.is_finite and covered:
-                ivls = [covered] if not isinstance(covered, Union) else covered.args
-                for ivl in ivls:
-                    if a in ivl:
-                        return ivl.sup
-            return a
-            
         if ok:
             args = []
             covered = S.EmptySet
             from sympy.sets.sets import Interval
             for a, b, e, i in abe_:
                 c = expr.args[i].cond
-                a = lhs(a)
                 incl_a = include(c, x, a)
                 incl_b = include(c, x, b)
                 iv = Interval(a, b, not incl_a, not incl_b)
                 cset = iv - covered
                 if not cset:
                     continue
-                a = cset.inf
+                try:
+                    a = cset.inf
+                except:
+                    pass # not sure what smallest uncovered value is
                 incl_a = include(c, x, a)
                 if incl_a and incl_b:
                     if a.is_infinite and b.is_infinite:
@@ -1205,8 +1198,6 @@ def lhs(a):
                 elif incl_b:
                     if b.is_infinite:
                         c = (x > a)
-                    elif a.is_infinite:
-                        c = (x <= b)
                     else:
                         c = And(a < x, x <= b)
                 else:
diff --git a/sympy/functions/elementary/tests/test_piecewise.py b/sympy/functions/elementary/tests/test_piecewise.py
index f7bf580bdd..b79411d54c 100644
--- a/sympy/functions/elementary/tests/test_piecewise.py
+++ b/sympy/functions/elementary/tests/test_piecewise.py
@@ -555,6 +555,17 @@ def test_piecewise_simplify():
         ).simplify() == Piecewise((1, (x >= 1) & (x <= 3)), (
         2, (x > 3) & (x < 4)), (nan, True))
 
+    # involves a symbolic range so cset.inf fails
+    L = Symbol('L', nonnegative=True)
+    p = Piecewise((nan, x <= 0), (0, (x >= 0) & (L > x) & (L - x <= 0)),
+        (x - L/2, (L > x) & (L - x <= 0)),
+        (L/2 - x, (x >= 0) & (L > x)),
+        (0, L > x), (nan, True))
+    assert p.simplify() == Piecewise(
+        (nan, x <= 0), (L/2 - x, L > x), (nan, True))
+    assert p.subs(L, y).simplify() == Piecewise(
+        (nan, x <= 0), (-x + y/2, x < Max(0, y)), (0, x < y), (nan, True))
+
 
 def test_piecewise_solve():
     abs2 = Piecewise((-x, x <= 0), (x, x > 0))
```

**Comment by smichr** [comment]
Looks like you might be busy with other things. I will push the changes to a new PR.

**Comment by geetHonve** [comment]
Hey i am sorry, I just issues with my vs code and git. Just fixed them and checked PR. I apologize for the delays. If there's anything you want me to do, I'll be online on github today.

**Pull request closed without merging**
