### PR TITLE
Pattern argument rewrite

### PR DESCRIPTION
**Pull request by Shekharrajak**
Fixes this issue : https://groups.google.com/forum/#!topic/sympy/eYZE0mUJ3-0
## Current master branch 

```
In [17]: f2 = sin(x) + cos(x)

In [18]: f2.rewrite(cos,exp)
Out[18]: 
    ⎛ ⅈ⋅x    -ⅈ⋅x⎞    ⅈ⋅x    -ⅈ⋅x
  ⅈ⋅⎝ℯ    - ℯ    ⎠   ℯ      ℯ    
- ──────────────── + ──── + ─────
         2            2       2  

In [19]: f2.rewrite([cos],sin)
Out[19]: 
            ⎛    π⎞
sin(x) + sin⎜x + ─⎟
            ⎝    2⎠

In [20]:  f=sin(x)+cos(y)/gamma(z)

In [21]: 

In [21]: f.rewrite(exp)
Out[21]: 
                      ⅈ⋅y    -ⅈ⋅y
                     ℯ      ℯ    
    ⎛ ⅈ⋅x    -ⅈ⋅x⎞   ──── + ─────
  ⅈ⋅⎝ℯ    - ℯ    ⎠    2       2  
- ──────────────── + ────────────
         2               Γ(z)    

In [22]: f.rewrite(sin,exp)
Out[22]: 
                      ⅈ⋅y    -ⅈ⋅y
                     ℯ      ℯ    
    ⎛ ⅈ⋅x    -ⅈ⋅x⎞   ──── + ─────
  ⅈ⋅⎝ℯ    - ℯ    ⎠    2       2  
- ──────────────── + ────────────
         2               Γ(z)   
```

## After this PR 

```
In [1]: f2 = sin(x) + cos(x)

In [2]: f2.rewrite([cos],sin)
Out[2]: 
            ⎛    π⎞
sin(x) + sin⎜x + ─⎟
            ⎝    2⎠

In [3]: f2.rewrite(cos,exp)
Out[3]: 
 ⅈ⋅x             -ⅈ⋅x
ℯ               ℯ    
──── + sin(x) + ─────
 2                2  

In [4]:  f=sin(x)+cos(y)/gamma(z)

In [5]:  f.rewrite(exp)
Out[5]: 
                      ⅈ⋅y    -ⅈ⋅y
                     ℯ      ℯ    
    ⎛ ⅈ⋅x    -ⅈ⋅x⎞   ──── + ─────
  ⅈ⋅⎝ℯ    - ℯ    ⎠    2       2  
- ──────────────── + ────────────
         2               Γ(z)    

In [6]:  f.rewrite(sin,exp)
Out[6]: 
    ⎛ ⅈ⋅x    -ⅈ⋅x⎞         
  ⅈ⋅⎝ℯ    - ℯ    ⎠   cos(y)
- ──────────────── + ──────
         2            Γ(z) 

```

### CODE REVIEW

**Comment by Shekharrajak** [comment]
Ping @asmeurer @jksuom @smichr

**Comment by jksuom** [comment]
Space is missing after some commas and on either side of +, but otherwise this looks good.

**Review by asmeurer — APPROVED** [review]

**Comment by Shekharrajak** [comment]
Thanks for review. I have added space either side of the `+` .

**Comment by asmeurer** [comment]
Thanks for the fix.

**Pull request merged**
