### PR TITLE
LaTeX printing: Use "standalone" document class for preview()

### PR DESCRIPTION
**Pull request by mgeier**
#### References to other Issues or PRs

Fix for bug discovered in #15625.

#### Brief description of what is fixed or changed

If `preview()` is used with a very long expression in inline mode (using `$...$`), the intermediate DVI file grows larger than one page and the following conversion to PNG only shows the last page.

The same problem appears when using `init_printing(use_latex='png')`  because it uses the same machinery.

This PR switches to the `standalone` document class, which doesn't create multiple pages.

#### Release Notes

* printing
  * use `\documentclass{standalone}` by default when using LaTeX to render expressions

### CODE REVIEW

**Comment by asmeurer** [comment]
I tried the expression `Add(*[Integral(1/x**i, (x, 1, 2)) for i in range(1000)])` and it produced a png which I'm not sure if it's broken or if it's just so wide my image viewer can't handle it:

test

**Comment by asmeurer** [comment]
Is it not possible to keep the equation wrapping, but disable page splitting, or make the page size very large (I think LaTeX has a maximum that it can handle anyway).

**Comment by mgeier** [comment]
I was able to open your file with the GIMP. It starts at the very left with:

image

 The expression ends with:

image

Then there is a wide white area, and somewhere in the middle, there's this (there's nothing else close to it):

image

The whole area on the right (about half of the image) is just white.

So yes, it is definitely broken.

Did you create it with this PR or on `master`?

> Is it not possible to keep the equation wrapping, but disable page splitting

I guess it would be possible to define a width for the `standalone` document class, but this would be totally arbitrary. So I decided not to even try it.

I actually agree with you: displaying this wide image (and possibly scrolling) would be the responsibility of the wrapping application (like Qt Console) and not of SymPy.

> or make the page size very large

I think it makes more sense to add a horizontal constraint to `standalone` than to remove a vertical constraint from `article`.

But I think it would be best to leave it totally unconstrained.

If people work with such long expressions, they should simply use a more appropriate display method, like using MathJax or just plain text.

**Comment by mgeier** [comment]
This time the intermediate DVI looks fine (at least it starts with the correct term, but I can only see the beginning of the line with my DVI viewer) and it has only a single page.

The error seems to appear during the conversion with `dvipng`.
I don't know what to do against that (except ignore it).

I tried a few things to force line breaks in the `standalone` class, but I wasn't really successful. Someone with more low-level LaTeX/TeX knowledge than me should give it a shot.

I only managed to force line breaks by putting the expression into a `minipage` environment with a given width, but I'm not sure if that's a good way to do it.

**Comment by mgeier** [comment]
In one last desperate attempt, I tried the `varwidth` option of the `standalone` class, and it seems to create line breaks and it shows the whole expression!

I've added a commit: ba5d5bcf7d751f8a801a88c87688466b1d62a8de

TBH, I don't understand what `varwidth` is supposed to do, but somehow it seems to work for us.

Please note that this still doesn't work for `latex_mode='equation*'` (which isn't supposed to have line breaks). But the same problem already exists in the `master` branch.

BTW, I found out that double-clicking in the cell output still works for those very long PNGs, you just have to hit the right line of pixels. After a few attempts, I can get it to display with scrollbars.

**Comment by asmeurer** [comment]
> BTW, I found out that double-clicking in the cell output still works for those very long PNGs, you just have to hit the right line of pixels. After a few attempts, I can get it to display with scrollbars.

This is an upstream Jupyter issue. It's the same if you open the image in your browser. You can zoom in on it, but only if you can find it with your mouse to click on it.

**Comment by asmeurer** [comment]
This is what it says in the documentation of `standalone`:

> A trailing empty line between the content and \end{document} will normally create a paragraph which is \linewidth wide. This paragraph (or any other one) will enlarge the size of smaller pictures and display itself as a large right border. This option uses the varwidth package to wrap the content into a varwidth environment, which is based on minipage, but will always use the natural width of the content if it is smaller than the given maximum width. The resulting effect is that the created paragraph will not cause any additional width and that multiple paragraphs can be included as part of the content. The used maximal width (which is provided to the underlying minipage environment) is \linewidth by default, but can be set by provided a width as value to the option. Doing so will also switch the option on.
If the crop option is used the content is placed in restricted horizontal mode which ignores paragraph breaks. Using the varwidth option paragraph breaks are enabled again.
A drawback of this option is that the content will be limited to the given width, i.e. wider picture environment will be cropped to the width at the right side. In such cases either a larger width should be selected, the option be switch off, any paragraph breaks should be avoided (no trailing empty lines) or one of the specific picture options like tikz or pstricks should be used instead.
This option can be changed during the document using \standaloneconfig and will affect all content of the following pages.

I tested it and it seems like removing the blank line before `\end{document}` in `preview` also fixes it (remember that blank lines have semantic meaning in LaTeX).

**Comment by mgeier** [comment]
You mean removing one (or several?) `\n` from this line:

https://github.com/sympy/sympy/blob/28eba540390e8f0afa4f1ee14c994cad6bd482e9/sympy/printing/preview.py#L179

... leads to line breaks in inline PNG equations?

I cannot reproduce this.

Without `varwidth` I'm always getting a single line and somewhere between 300 and 350 terms it seems to fail and fall back to `'matplotlib'` (still having no line breaks).

**Comment by asmeurer** [comment]
I can't reproduce it now either. I might have been running against the wrong code. The varwidth thing does seem to work, though.

**Pull request merged**
