### PR TITLE
[GSoC][WIP] Add Matrix Gamma distribution

### PR DESCRIPTION
**Pull request by Smit-create**
Add Matrix Gamma Distribution
#### References to other Issues or PRs

Discussions in #19723

## Major Changes
- [x] Corrected density API for random matrices and now works the same as other Random Variables
Example:
Previously:
```py
>>> from sympy.stats import GaussianUnitaryEnsemble as GUE, density
>>> G = GUE('U', 2)
>>> density(G)
Lambda(H, exp(-Trace(H**2))/(2*pi**2))
```
Now:
```py
>>> from sympy.stats import GaussianUnitaryEnsemble as GUE, density
>>> from sympy import MatrixSymbol
>>> X = MatrixSymbol('X', 2, 2)
>>> G = GUE('U', 2)
>>> density(G)
GaussianUnitaryEnsemble(U, 2)
>>> density(G)(X)
exp(-Trace(X**2))/(2*pi**2)
```
>>> 
- [x] Added classes of `MatrixPSpace`, `MatrixDistribution` (General Framework of Matrix Distributions)
- [x] Add MatrixGammaDistribution
- [x] Add tests and docs
#### Release Notes

* stats
   * Added `MatrixGamma` Distribution

ping @Upabjojr @czgdp1807 @jmig5776

### CODE REVIEW

**Comment by Smit-create** [comment]
On the current diff, I get the following results:
@czgdp1807 @Upabjojr 
```py

In [1]: from sympy.stats.random_matrix_models import MatrixGammaDistribution

In [2]: M = MatrixGammaDistribution('M', 1,2,[[1, 0], [0, 1]])

In [3]: M
Out[3]: M

In [4]: from sympy.stats import density


In [5]: density(M)
Out[5]:
       ⎛⎡-1/2   0  ⎤  ⎞
     tr⎜⎢          ⎥⋅H⎟
       ⎝⎣ 0    -1/2⎦  ⎠    -0.5
    ℯ                  ⋅│H│
H ↦ ───────────────────────────
                │⎡1  0⎤│
            4⋅π⋅│⎢    ⎥│
                │⎣0  1⎦│

In [6]: density(M)(M)
Out[6]:
   ⎛⎡-1/2   0  ⎤  ⎞
 tr⎜⎢          ⎥⋅M⎟
   ⎝⎣ 0    -1/2⎦  ⎠    -0.5
ℯ                  ⋅│M│
───────────────────────────
            │⎡1  0⎤│
        4⋅π⋅│⎢    ⎥│
            │⎣0  1⎦│

In [7]: density(M)(Matrix([[2, 1], [1, 2]]))

Out[7]:
   ⎛⎡-1/2   0  ⎤ ⎡2  1⎤⎞
 tr⎜⎢          ⎥⋅⎢    ⎥⎟         -0.5
   ⎝⎣ 0    -1/2⎦ ⎣1  2⎦⎠ │⎡2  1⎤│
ℯ                       ⋅│⎢    ⎥│
                         │⎣1  2⎦│
─────────────────────────────────────
                 │⎡1  0⎤│
             4⋅π⋅│⎢    ⎥│
                 │⎣0  1⎦│

In [8]: density(M)(Matrix([[2, 1], [1, 2]])).doit()
Out[8]:
                   -2
0.144337567297406⋅ℯ
─────────────────────
          π

In [9]: X1 = MatrixSymbol('X1',1,2)

In [10]: X2 = MatrixSymbol('X2',1,2)


In [11]: density(M)(Matrix([X1, X2]))
Out[11]:
   ⎛⎡-1/2   0  ⎤ ⎡X₁ ₀₀  X₁ ₀₁⎤⎞
 tr⎜⎢          ⎥⋅⎢            ⎥⎟                 -0.5
   ⎝⎣ 0    -1/2⎦ ⎣X₂ ₀₀  X₂ ₀₁⎦⎠ │⎡X₁ ₀₀  X₁ ₀₁⎤│
ℯ                               ⋅│⎢            ⎥│
                                 │⎣X₂ ₀₀  X₂ ₀₁⎦│
─────────────────────────────────────────────────────
                         │⎡1  0⎤│
                     4⋅π⋅│⎢    ⎥│
                         │⎣0  1⎦│

In [12]: density(M)(Matrix([X1, X2])).doit()
Out[12]:
                                   X₁ ₀₀   X₂ ₀₁
                                 - ───── - ─────
                           -0.5      2       2
(X₁ ₀₀⋅X₂ ₀₁ - X₁ ₀₁⋅X₂ ₀₀)    ⋅ℯ
────────────────────────────────────────────────
                      4⋅π

```

**Comment by czgdp1807** [comment]
I don't think ensembles is the right place for matrix distributions. Can you create a new file, `matrix_distributions` for distributions of matrices.

**Comment by Smit-create** [comment]
>  Can you create a new file, `matrix_distributions` for distributions of matrices.

Yes, I have done that. Please have a look if the framework looks good.

**Comment by czgdp1807** [comment]
Please add tests.

**Comment by Smit-create** [comment]
Currently, I have used the `RandomMatrixPspace`, if you think that we should use a new PSpace say `MatrixPSpace` then, I would change that accordingly and leave the random matrix untouched.

**Comment by Smit-create** [comment]
I have added `MatrixPSpace`, if this looks good then I will add docs and remaining tests.

**Comment by czgdp1807** [comment]
> if this looks good then I will add docs and remaining tests.

Yes.

**Comment by Smit-create** [comment]
@czgdp1807 @Upabjojr Please have a look if this looks good for adding more of such distributions upon this.

**Comment by czgdp1807** [comment]
This is okay. After this is merged you can add more distributions.

**Comment by Smit-create** [comment]
@Upabjojr @czgdp1807 Tests have passed. Please merge this so that I will add more distributions in a new PR.

**Comment by Upabjojr** [comment]
I'm OK for merging.

**Pull request merged**
