### PR TITLE
Amended typo in coupled_cluster.py

### PR DESCRIPTION
**Pull request by jremes-foss**
Amended a typo in coupled_cluster.py. 
Line 91: Hausdoff -> Hausdorff.

### CODE REVIEW

**Comment by debugger22** [comment]
+1

**Comment by debugger22** [comment]
You should't commit directly into your master branch. You may want to read [development workflow](https://github.com/sympy/sympy/wiki/Development-workflow) in SymPy.

**Comment by Newman101** [comment]
Ok, thanks for the information. I'll read it through carefully and stop committing directly to master then.

**Comment by debugger22** [comment]
Tell me your name so that I could add it in SymPy's AUTHORS list.

**Comment by Newman101** [comment]
Juha Remes <jremes@outlook.com> 

Thanks. :)

**Pull request merged**
