### PR TITLE
polytools: fix cancel() to output simplified term

### LINKED ISSUE #27096: cancel result is not canonical for equivalent expressions
```python
p, q = Poly(x**2/4 - 1), Poly(x/2 - 1)
e1 = (p/q).as_expr()
case1 = p.cancel(q); case1
(1/2, Poly(x + 2, x, domain='QQ'), Poly(1, x, domain='QQ'))

p, q = [Poly(i) for i in (p/q).as_expr().as_numer_denom()]
e2 = (p/q).as_expr()
assert p.as_expr() == 2*x**2 - 8
assert q.as_expr() == 4*x - 8
case2 = p.cancel(q); case2
(1, Poly(x + 2, x, domain='ZZ'), Poly(2, x, domain='ZZ'))

>>> e1==e2  # ok
False
>>> e1.equals(e2) # they are the same
True
>>> case1==case2 # they cancel differently
False
```

### PR DESCRIPTION
**Pull request by Brayden-Smith**
#### References to other Issues or PRs

Fixes #27096

#### Brief description of what is fixed or changed
Expresses the results of cancel over QQ as a cancel over ZZ if applicable. Does so by multiplying out the numerator and denominator of the cancel coefficient and then changing the domains to ZZ if possible.

#### Other comments
Tried to ensure that this change won't mess up the results of cancel on untargeted domains

#### Release Notes

* polys
  * Converts cancel over QQ to equivalent cancel over ZZ when possible

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
It is not usually necessary to close the pull request and open a new one if there are problems. For the release note you can just edit the comment. If there are problems with the code then you can push new commit to the same pull request.

**Comment by oscarbenjamin** [comment]
The fix for this issue should probably be in this function:
https://github.com/sympy/sympy/blob/dc69be1c42b3dfdbf03478d14b9ad2ca5a7dbc9e/sympy/polys/euclidtools.py#L1862-L1912

**Comment by oscarbenjamin** [comment]
Any change here will require updates to other parts of the code and to some tests as well so it is not a simple change to make.

**Comment by smichr** [comment]
@Brayden-Smith , very interesting! It would be fun to compare notes with you, especially since we found our way to the same sort of fix, at different levels in the polys labyrinth. See #27122 where I am making the changes at a lower level. I would be happy to have you take that over or else am happy to keep working on it but could use some collaboration.

**Comment by smichr** [comment]
I think I have a minimal fix in #27122

**Comment by oscarbenjamin** [comment]
Thanks for opening this pull request but I don't think that this is the right fix. In the end I think that the 3-value return form of `Poly.cancel` is just weird and should probably be considered a mistake. See my comments at https://github.com/sympy/sympy/issues/27096#issuecomment-2389139090

Before fixing the 3-value form of `Poly.cancel` we should consider if it is ever actually needed for anything or whether we can make the two value form be the only one that is actually used anywhere.

For now I'm going to close this PR.

**Pull request closed without merging**
