### PR TITLE
rs_series allows division by monomials

### LINKED ISSUE #9843: rs_series fails if input involves division
```
In [31]: rs_series(sin(a)/a**2,a,5)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-e542bef2079e> in <module>()
----> 1 rs_series(sin(a)/a**2,a,5)

/home/aries/foss/sympy/sympy/polys/ring_series.pyc in rs_series(expr, a, prec)
   1907 
   1908         for i in range(n):
-> 1909             _series = _rs_series(args[i], R(args[i]), a, prec - sum_pows +
   1910                 min_pows[i])
   1911             R = R.compose(_series.ring)

/home/aries/foss/sympy/sympy/polys/ring_series.pyc in _rs_series(expr, series_rs, a, prec)
   1834     if dp:
   1835         q = q*x**dp
-> 1836     return q
   1837 
   1838 

/home/aries/foss/sympy/sympy/polys/rings.pyc in ring_new(self, element)
    321                 return self.from_list(element)
    322         elif isinstance(element, Expr):
--> 323             return self.from_expr(element)
    324         else:
    325             return self.ground_new(element)

/home/aries/foss/sympy/sympy/polys/rings.pyc in from_expr(self, expr)
    369             poly = self._rebuild_expr(expr, mapping)
    370         except CoercionFailed:
--> 371             raise ValueError("expected an expression convertible to a polynomial in %s, got %s" % (self, expr))
    372         else:
    373             return self.ring_new(poly)

ValueError: expected an expression convertible to a polynomial in Polynomial ring in 1/a, sin(a), a over QQ with lex order, got a**(-2)
```

### PR DESCRIPTION
**Pull request by aniketgattani**
Fixes: #9843

### CODE REVIEW

**Comment by shivamvats** [comment]
@aniketgattani Could you add some tests for this?

**Comment by shivamvats** [comment]
@aniketgattani I do not think you should make any change in the polynomial code. `rings.py` deals with polynomials (no negative exponent by definition), which is the reason for that `ValueError` test. `ring_series` is different from `rings` in that we want to support negative and fractional exponents by making use of the polynomials code. Hence, any modification should be restricted to `ring_series`.

**Comment by aniketgattani** [comment]
But ring_series uses rings for the polynomial expansions. Unless I make changes in rings I wont be able to make any modifications to ring_series

**Comment by shivamvats** [comment]
Could you tell me what you plan to do?
I had run into the same issue. Please look at https://github.com/sympy/sympy/blob/master/doc/src/modules/polys/ringseries.rst and https://shivamvats.github.io/gsoc/GSoC-Week-12/ . 

A solution that doesn't modify `polys` will be preferable.

**Comment by aniketgattani** [comment]
Would be better if we could talk on gitter I feel

**Comment by shivamvats** [comment]
-1

**Pull request closed without merging**
