### PR TITLE
Fixed tensor contraction problem

### LINKED ISSUE #18465: Tensor contractions are wrong
This is essentially a generalization of #17328.

The problem in the current implementation is that contractions are handled before applications of the metric, which leads to incorrect results such as in #17328.

In `tensor/tensor.py`:
```python
class Tensor(TensExpr):
# ...
    def _extract_data(self, replacement_dict):
    # ...
        if len(dum1) > 0:
            indices2 = other.get_indices()
            repl = {}
            for p1, p2 in dum1:
                repl[indices2[p2]] = -indices2[p1]
            other = other.xreplace(repl).doit()
            array = _TensorDataLazyEvaluator.data_contract_dum([array], dum1, len(indices2))

        free_ind1 = self.get_free_indices()
        free_ind2 = other.get_free_indices()

        return self._match_indices_with_other_tensor(array, free_ind1, free_ind2, replacement_dict)
```
And thus, the issue is that `_TensorDataLazyEvaluator.data_contract_dum` is being called prior to `self._match_indices_with_other_tensor` (where the metric is applied).

The reason that this ordering matters is because tensor contraction is itself the abstraction of applying the metric to the tensors that represent psuedo-riemannian manifolds. In essence, it means that we must have it that equation; however, this isn't the case here.

I've tried tampering with the code above, but by the way tensors have been designed, this bug is essentially unavoidable. As a consequence, the tensor module needs to be refactored in order to get accurate results. (Also, I couldn't help but notice that the last argument to `_TensorDataLazyEvaluator.data_contract_dum` isn't used).

@drybalka had mentioned that he had this sort of refactoring in the works, but based on his fork, progress seems to be slow. I think discussions should be in order for reorganizing how tensors actually represent their components in this module.

### PR DESCRIPTION
**Pull request by rj-calvin**
#### References to other Issues or PRs

Fixes #18465 

#### Brief description of what is fixed or changed

Tensor contractions using `replace_with_arrays` would prematurely contract the data arrays before applying the metric—yielding incorrect results. The solution implemented here is a rather trivial one in that it simply separates out an existing function for doing matrix multiplication with an existing data array with the metric and utilizes it in `Tensor._extract_data` to apply the metric before dummy indices are contracted.

#### Other comments

This is my first pull request with Sympy. Let me know if I should make any adjustments to my code.

#### Release Notes

* tensor
  * Fixed a bug where tensor contractions in calls to `replace_with_arrays` would fail to apply the metric.

### CODE REVIEW

**Comment by asmeurer** [comment]
This needs tests.

**Comment by Upabjojr** [comment]
Yes, we need an assert with an expression that used not to work before this PR. It's to make sure the code won't be broken by accident in the future.

**Comment by cjayross** [comment]
Ah, of course. Yeah, I could definitely add one.

**Comment by cjayross** [comment]
I added two assertion to an existing test case that used to apply to the old `Tensor.data` properties. I checked the tests against master to verify that they in fact fail without the change.

**Comment by cjayross** [comment]
@asmeurer @Upabjojr, do you guys have any additional requests?

**Comment by Upabjojr** [comment]
@cjayross Thanks for your contribution!

**Pull request merged**
