### PR TITLE
Cartesian product is not associative

### PR DESCRIPTION
**Pull request by sylee957**
#### Brief description of what is fixed or changed

From https://en.wikipedia.org/wiki/Cartesian_product#Non-commutativity_and_non-associativity, it states that the cartesian product is not associative.

> Strictly speaking, the Cartesian product is not associative (unless one of the involved sets is empty).

But sympy flattens the product
```python
>>> from sympy import *

>>> a = FiniteSet(1, 2)
>>> b = a * a
>>> c = b * a
>>> FiniteSet(*c)
{(1, 1, 1), (1, 1, 2), (1, 2, 1), (1, 2, 2), (2, 1, 1), (2, 1, 2), (2, 2, 1), (2, 2, 2)}
```
and I think that things can be ambiguous, and there would be no way to distinguish a set of tuples like `(1, (1, 1))`, `((1, 1), 1)`

There is a separate definition for n-ary cartesian product, which can make the set of n-tuples like `(1, 1, 1)`
https://en.wikipedia.org/wiki/Cartesian_product#Cartesian_products_of_several_sets

Also, I just wonder Cartesian product of a single set should be `{(1), (2)}` instead of `{1, 2}`, if there can be a tuple containing single element.

However, things can go down to how n-Tuple can be defined
https://en.wikipedia.org/wiki/Tuple
and there are some different definitions for tuple
https://en.wikipedia.org/wiki/Ordered_pair
which doesn't seem like compatible each other

#### Release Notes

- sets
  - Made `ProductSet` not associative

### CODE REVIEW

**Comment by smichr** [comment]
> tuple containing single element.

A singleton tuple is `(1,)`; all tuples have a comma in them.

**Comment by oscarbenjamin** [comment]
I guess that the finite sets and the infinite sets should be consistent here:
```
In [54]: S.Reals*S.Reals*S.Reals                                                                                                  
Out[54]: 
 3
ℝ 

In [56]: (1,1,1) in S.Reals*(S.Reals*S.Reals)                                                                                     
Out[56]: True
```

**Comment by jksuom** [comment]
There are natural 1-1 correspondences between elements of differently grouped products. Perhaps there should be explicit methods for the conversions: `(1, (2, 3)) -> (1, 2, 3)` etc.

**Comment by smichr** [comment]
> should be explicit methods for the conversions

When would such conversions be used? What would be an example of a situation where one would want `((1,2),3) == (1, (2, 3))`?

**Comment by oscarbenjamin** [comment]
@sylee957 is this still needed after #17557?

**Pull request closed without merging**
