### PR TITLE
fix #8167 - zero=True assumption is ignored

### LINKED ISSUE #8167: zero=True assumption is ignored?
For `a = Symbol('a', zero=True)`, the following happen:
1. `a == 0` returns `False`
2. `a.evalf()` returns `a` (why not 0?)
3. while `limit((E**0)**x, x, oo)` returns 1, `limit((E**a)**x, x, oo)` raises `PoleError: Don't know how to calculate the limit(exp(a/x), x, 0, dir=+), sorry.`

Adding `real=True` to `a`'s construction does not help.

(1.) and (2.) and (3.) occur also when `a = Symbol('a', real=True, positive=False, negative=False)`.

I am not sure if (1.) is a bug, as I am not entirely sure what the `==` should really mean here. But if `a >= 0` returns `True` and `a > 0` returns `False`, then clearly `a` could be evaluated to `0` only, and the limit should work.

### PR DESCRIPTION
**Pull request by leosartaj**
I have added a simple check in doit method of Limit, to substitute all the symbols that are zero in the expression. Now 

```
>>> a = Symbol('a', zero=True)
>>> limit((E**a)**x, x, oo)
1
```

### CODE REVIEW

**Comment by smichr** [comment]
I doubt that this is the way to handle this issue. At least I don't think we want to include this special behavior in just this `doit` method. Perhaps `E**a` should have reduced to 1 at instantiation but a literal zero was being checked for instead of a symbolic one.

**Comment by leosartaj** [comment]
Now, 

```
>>> a  = Symbol('a', zero=True)
>>> E**a
1
```

As suggested by @pelegm [here](https://github.com/sympy/sympy/issues/8167#issuecomment-68515996). This fixes the issue.

@smichr @jksuom

**Comment by jksuom** [comment]
```
In [1]: a = Symbol('a', zero=True)

In [2]: exp(1/a)**a
Out[2]: 1

In [3]: limit(exp(1/x)**x, x, 0)
Out[3]: ℯ
```
I would expect to have the same result.

**Comment by leosartaj** [comment]
In the case of ``In [2]``, ``a`` is exactly zero. As anything multiplied my zero is zero, hence ``E**0`` gives ``1`` (correct).

For ``In [3]``, in the limit ``x`` tends to ``0`` and is *not* exactly zero. Therefore, ``(1/x)*x`` is a ``0/0`` form, applying L'Hospital's Rule, we get ``1``. Hence the result ``E``. In my opinion the result is correct. [Wolfram](https://www.wolframalpha.com/input/?i=lim+exp%5B1%2Fx%5D%5Ex+as+x-%3E0) agrees.

@jksuom

**Comment by jksuom** [comment]
``b = exp(1/a)**a`` has the indeterminate form ``oo**0``. It is analogous to ``c = exp(a)**(1/a)`` which has the indeterminate form ``1**oo``. In Sympy, ``c`` has the value ``E``, which is the limit of ``exp(x)**(1/x)`` as ``x`` tends to zero. Hence it would seem reasonable that also ``b`` should have the limit value ``E``.

**Comment by leosartaj** [comment]
Now I get it. Will fix this.
Thanks!

**Comment by certik** [comment]
@leosartaj please ping us once you fix it.

**Comment by czgdp1807** [comment]
```python
>>> a = Symbol('a', zero=True)
>>> limit((E**a)**x, x, oo)
1
>>> exp(1/a)**a
ℯ
>>> limit(exp(1/x)**x, x, 0)
ℯ
```
The above suggests the issue has been fixed. Please let me know if there is a need to re-open it. Closing this for now. Thanks.

**Pull request closed without merging**
