### PR TITLE
Union works with python sets

### PR DESCRIPTION
**Pull request by vva2**
Union with python sets
#### References to other Issues or PRs
#15448

#### Brief description of what is fixed or changed
In sets.py file the class Union is modified so that it works for python sets too.

#### Release Notes

* sets
  * Union works with python sets.

### CODE REVIEW

**Comment by vishal-vardhan** [comment]
@asmeurer i've changed the sets.py code for Union to work normally for Inetervals and FiniteSets.And when given python sets as input to Union function it returns final value as a FiniteSet type.As u said i used simpify to convert the type of python sets.I also appropriately changed the code to work with empty python set when inputted using try-except.I've checked with different inputs also it worked fine.But i dont know why it fails the tests in azure...  And what are doc-tests in azure page will they check the style of the code?

**Comment by smichr** [comment]
cf #15479

**Comment by vishal-vardhan** [comment]
@smichr can review my PR

**Comment by oscargus** [comment]
Please add a few tests for different scenarios.

**Comment by czgdp1807** [comment]
The issue associated with this PR has been resolved. Closing it. Thanks for the contribution though. :D

**Pull request closed without merging**
