### PR TITLE
Make orthogonal polynomials lazy and evalute only if asked to

### PR DESCRIPTION
**Pull request by raoulb**
TODO:
- [ ] Adapt tests
- [ ] Change docstrings

In [8]: legendre(4, x)
Out[8]: legendre(4, x)

In [9]: expand_func(_)
Out[9]: 35_x__4/8 - 15_x**2/4 + 3/8

In [10]: hermite(4, x)
Out[10]: hermite(4, x)

In [11]: expand_func(_)
Out[11]: 16_x__4 - 48_x**2 + 12

In [12]: laguerre(4, x)
Out[12]: laguerre(4, x)

In [13]: expand_func(_)
Out[13]: x**4/24 - 2*x**3/3 + 3_x__2 - 4_x + 1

In [14]: laguerre(-n, 2_x)
Out[14]: laguerre(-n, 2_x)

In [15]: expand_func(_)
Out[15]: exp(2_x)_laguerre(-n - 1, -2*x)

### CODE REVIEW

**Comment by czgdp1807** [comment]
Do we need this?

**Comment by oscarbenjamin** [comment]
I don't know if the changes in this PR itself are still relevant but I think it probably would be better if special polynomials kept their form unless a user explicitly asks to rewrite them in some other form.

**Comment by czgdp1807** [comment]
IMHO, consistency should be maintained and polynomials should be un-evaluated only if `evaluate=False` as is the case with other APIs. Keeping some objects un-evaluated by default and some other evaluated will generate confusion for the end user. Closing this for now, but if it can be re-opened, then feel free to do so. If you are not able to do so, let us know in the comments. Thanks for the contributions.

**Comment by oscarbenjamin** [comment]
I disagree. Most/all Basic subclasses should not evaluate by default. The use of `evaluate=False` is just a reflection of poor design decisions in the past that are difficult but not impossible to fix at this stage.

This PR looks reasonable except it needs tests.

**Pull request closed without merging**
