### PR TITLE
A

### LINKED ISSUE #18806: Matrix Matrix exponntial
Sympy probably doesn't support this https://en.wikipedia.org/wiki/Matrix_exponential#Matrix-matrix_exponentials
It should be easy to implement. Only question is that should this be a  different function or can be included in  `pow` function.

### PR DESCRIPTION
**Pull request by jainsee24**

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
There is a matrix log method:
```
In [30]: t = Symbol('t', real=True)                                                                                                                           

In [31]: M = Matrix([[t, t], [0, t]])                                                                                                                         

In [32]: M.exp()                                                                                                                                              
Out[32]: 
⎡ t     t⎤
⎢ℯ   t⋅ℯ ⎥
⎢        ⎥
⎢      t ⎥
⎣0    ℯ  ⎦

In [33]: M.exp().log()                                                                                                                                        
Out[33]: 
⎡t  t⎤
⎢    ⎥
⎣0  t⎦
```
Is there a reason for choosing to use `analytic_func` instead?

**Comment by Sk140998** [comment]
I think that this pr is copied from #18823 . Every thing is similar even the test case.

**Comment by jainsee24** [comment]
> I think that this pr is copied from #18823 . Every thing is similar even the test case.

**Comment by Sk140998** [comment]
You shouldn't do this. I am sure that you have copied his code. You also made the same mistake of 'print(log_X)' similar in first commit #18823 . This is very bad for open source. I am sad to see this.

**Comment by oscarbenjamin** [comment]
This kind of thing normally happens because new contributors get confused about how the commit pull request workflow works. It is fine to work on the same thing as other contributors as long as the author attribution is correct. So for example if this is based on the work for #18823 then it should keep the commits from there with the original author name in the commits. Then you can make new commits on top with yourself listed as the author.

Given that #18823 is still being worked on though it is probably better not to do that. If you want to help with it then you could review the PR and make comments/suggestions. If you have an idea for a different approach then you can make a separate PR showing your alternative idea.

**Pull request closed without merging**
