### PR TITLE
Add support for bidirectional limits (dir="real")

### PR DESCRIPTION
**Pull request by skirpichev**
- [ ] Do we need this at all? 1) We don't have specific algorithms for bidirectional limits yet.  2) Not all CAS support this conception, see e.g. [Mathematica](http://reference.wolfram.com/language/ref/Limit.html).
- [ ] Better name for dir value? (variants: "0", "both" or just None); "real" is [from the Maple](http://www.maplesoft.com/support/help/Maple/view.aspx?path=limit/dir).
- [ ] Raise different errors for [discontinuities of different type](http://en.wikipedia.org/wiki/Classification_of_discontinuities).

### CODE REVIEW

**Comment by skirpichev** [comment]
Feel free to pick up this work.

**Comment by cbm755** [comment]
@pelegm, @asmeurer I think this should be merged.  Performance doesn't strike me as a big deal b/c this PR does not propose making it the default.  Can one of you re-open this?

We can file an issue for improving the performance (although I'm not volunteering to do that) and/or making it default.

**Comment by cbm755** [comment]
Ok, maybe this is not so easy:
````
a = limit(sin(1/x**2), x, 0, '-')
# sin(oo)
b = limit(sin(1/x**2), x, 0, '+')
# sin(oo)
(a - b).equals(0)
# True
````
`limit(sin(x), x, oo)` should be NaN, or `Eq(sin(oo), sin(oo))` should be False, something like that.

But probably there are similar silent failures where the left- and right-hand limit are unevaluated expressions.

**Comment by cbm755** [comment]
`sin(oo)` thing is #5299.

**Comment by amitsaha** [comment]
@asmeurer  Strictly from a SymPy user's point of view (and writing about it for others to learn), is it possible that the default will be bidirectional in a future release?

**Comment by pelegm** [comment]
@amitsaha see discussion [here](https://github.com/sympy/sympy/issues/8165). I personally agree with you.

**Pull request closed without merging**
