### PR TITLE
sympy.plot issue with logarithmic axis solved

### LINKED ISSUE #15556: sympy.plot sampling issue with logarithmic axis
It looks like `plot` is sampling in a linear space even if the plot command requested a logarithmic x-axis.
Minimum example
```
from sympy import cos, log, plot
from sympy.abc import x
plot(sin(log(x), (x, .001,10), xscale='log')
```
produces
figure_3
while, e.g., Gnuplot 
```
gnuplot> set xrange [.001: 10]
gnuplot> set log x
gnuplot> plot sin(log(x))
```
gives
sin

### PR DESCRIPTION
**Pull request by jmig5776**
#### References to other Issues or PRs

"Fixes #15556 "

#### Brief description of what is fixed or changed
Modified plot.py such that now plot is sampling in a logarithmic space instead of linear space ,if xscale is given to be 'log'

For example:

from sympy import cos, log, plot
from sympy.abc import x
plot(sin(log(x), (x, .001,10), xscale='log'

sympy_issue

#### Other comments
Now xlabel and ylabel also show with respect to log if xscale='log is to be given
#### Release Notes

* plotting
       * fixed a issue of logarithmic plot

### CODE REVIEW

**Comment by jmig5776** [comment]
I am trying to solve this two lines issue ,I am trying to change in sample function . Did i had to change any other file also such that  experimental_lambdify.py ??

**Comment by jmig5776** [comment]
Now it fixes the above problem of two lines also

from sympy import cos, log, plot
from sympy.abc import x
plot(sin(log(x), (x, .001,10), xscale='log'

download sympy2


Now it shows the graph in logarithmic axis in the given range.

**Comment by jmig5776** [comment]
@moorepants Please review it.

**Comment by smichr** [comment]
The demo graph looks good and it looks like you solved this issue. Here's to more beautiful logarithmic graphs!

**Pull request merged**
