### PR TITLE
maint(ci): run tests through github actions

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

See #20374 

#### Brief description of what is fixed or changed

Adds a basic file that runs tests through github actions.

#### Other comments

I don't know how much time I can give to this but we do urgently need to move away from Travis so if anyone can help finish this then please do.

Where I'm at with this is that the basics are working but I don't think that the timeout parameter for the slow tests is working properly (the tests don't seem to time out).

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I guess that some setting needs to be change on the repo. I already tested this on my fork and it ran github actions there.

**Comment by asmeurer** [comment]
It seems to be enabled. Maybe it won't run until the file exists on master. Try pushing the branch up to this repo?

**Comment by asmeurer** [comment]
Alternately just merge this and finish it in a new PR.

**Comment by oscarbenjamin** [comment]
Pushing it to a branch in the repo works. I can see the actions jobs in this PR now but I'm not sure if that's just because it's the same commit I pushed to the `pr_actions_poc` branch.

**Comment by oscarbenjamin** [comment]
I've pushed another commit and now it seems to be working.

I've disabled the slow tests for now so that the actions tests should pass. That might be enough to merge this and then improve in subsequent PRs.

**Comment by oscarbenjamin** [comment]
I'm going to merge this now. I think that means that the actions will run all new PRs and pushes. I already have improvements to it but it takes a long time for anything to pass on Travis so I'll put them in a separate PR.

We should pay attention to how actions compares with Travis while both are running on all PRs. We can always disable actions on the repo if this is causing problems.

**Pull request merged**
