### PR TITLE
Fixed some flake 8 issues

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References to other Issues or PRs

https://travis-ci.org/sympy/sympy/jobs/635659261?utm_medium=notification&utm_source=github_status

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by czgdp1807** [comment]
Will merge if no one objects for sometime. Thanks.

**Comment by oscarbenjamin** [comment]
Can you also add this:
```diff
diff --git a/.travis.yml b/.travis.yml
index dfa2795388..1e6fd58614 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -203,6 +203,8 @@ matrix:
         - BENCHMARK="true"
 
   allow_failures:
+    - env:
+        - TEST_FLAKE8="true"
     - env:
         - BENCHMARK="true"
```
The flake8 job should not be an allowed failure but I forgot to remove this bit.

**Comment by czgdp1807** [comment]
Sure will add shortly.

**Comment by oscarbenjamin** [comment]
Whoops I had that diff in reverse: I've just fixed it to show that the two lines should be deleted not added.

**Pull request merged**
