### PR TITLE
oo and zoo are not prime

### LINKED ISSUE #8487: oo.is_prime is not False
`oo.is_prime` should be False, I guess, and same with `zoo.is_prime`.

### PR DESCRIPTION
**Pull request by pelegm**
This fixes #8487.

### CODE REVIEW

**Comment by pelegm** [comment]
I am not sure what's wrong with travis here. Any ideas? All tests seem to be ok.

**Comment by toolforger** [comment]
It fails due to timeouts, some of the tests simply take too long and Travis isn't sure whether there's a failed test or not.

**Comment by pelegm** [comment]
Thanks.

What can I do about it? Can I restart the tests somehow?

**Comment by toolforger** [comment]
I think it restarted on its own, it's now all green.

**Comment by smichr** [comment]
And you didn't do this to -oo because it's negative (hence not considered prime). Looks good.

**Pull request merged**
