### PR TITLE
Added an Integer cast in the gaunt formula

### LINKED ISSUE #12624: sympy.physics.wigner.gaunt does not return rational number
example:
In [1]: import sympy.physics.wigner

In [2]: sympy.physics.wigner.gaunt(1,1,0,-1,1,0)
Out[2]: -0.5/sqrt(pi)
which does not return rational number

However, its equivalent return the rational
In [3]: sympy.physics.wigner.gaunt(0,1,1,0,-1,1)
Out[3]: -1/(2*sqrt(pi))

I use sympy 1.0

### PR DESCRIPTION
**Pull request by NikhilPappu**
#### References to other Issues or PRs

This PR Fixes #12624.

### CODE REVIEW

**Comment by gxyd** [comment]
Thanks for your contribution. Can you please add test cases for the made changes?
See this https://github.com/sympy/sympy/wiki/Writing-test-cases-in-SymPy for guidelines on how to write test cases.

**Comment by NikhilPappu** [comment]
@gxyd  Can assert tell the difference between -0.5*(sqrt(pi)) and -1/(2*sqrt(pi))? It did not seem to work that way when i tested it.

**Comment by gxyd** [comment]
Can you please paste the code, for what you expect and what you get (write in comments for what you expected and what you got)? That will help.

**Comment by NikhilPappu** [comment]
Without the fix, `print(gaunt(1, 1, 0, -1, 1, 0))` outputs `-0.5*(sqrt(pi))` but `assert gaunt(1, 1, 0, -1, 1, 0) == -1/(2*sqrt(pi))` returns True so I don't see how the test would help. With the fix the output is `-1/(2*sqrt(pi))`.

**Comment by NikhilPappu** [comment]
@gxyd Do you know of a way to write a test that checks the exact form of the expression?

**Comment by gxyd** [comment]
See:
```python
In [1]: a = -1/(2*sqrt(pi))

In [2]: b = -0.5*(sqrt(pi))

In [3]: a is S(-1)/(2*sqrt(pi))
Out[3]: True

In [4]: b is S(-1)/(2*sqrt(pi))
Out[4]: False
```

I'm not saying that 'is' is the way to add a test here, I haven't given thought as to the best way of writing test for this. But there definitely are ways to write tests for this.

**Comment by NikhilPappu** [comment]
@gxyd Thanks for that! I'll add the test.

**Comment by NikhilPappu** [comment]
@gxyd 'is' doesn't seem to work. This is the kind of behaviour. Also how do I past code like that?
```
In [1]: a = -1/(2*sqrt(pi))

In [2]: b = gaunt(1, 1, 0, -1, 1, 0)

In [3]: a is S(-1)/(2*sqrt(pi))
Out[3]: True

In [4]: b is S(-1)/(2*sqrt(pi))
Out[4]: False

In [5]: b
Out[5]: -1/(2*sqrt(pi))
```

**Comment by jksuom** [comment]
You can use `srepr` to see the structure:
```
>>> a = -1/(2*sqrt(pi))
>>> srepr(a)
'Mul(Integer(-1), Rational(1, 2), Pow(pi, Rational(-1, 2)))'
>>> b = gaunt(1, 1, 0, -1, 1, 0)
>>> srepr(b)
"Mul(Integer(-1), Float('0.5', precision=53), Pow(pi, Rational(-1, 2)))"
```

**Comment by ylemkimon** [comment]
For example, if
```python
>>> srepr(b)
"Mul(Integer(-1), Float('0.5', precision=53), Pow(pi, Rational(-1, 2)))"
```
then you can do `assert isinstance(b.args[1], Float)`.

**Review by ylemkimon — APPROVED** [review]
LGTM

**Comment by ylemkimon** [comment]
Thank you! It's merged.

**Pull request merged**
