### PR TITLE
Implement matches method for Tensor

### PR DESCRIPTION
**Pull request by Kishore96in**
#### References to other Issues or PRs

Supersedes #24668 (I am splitting it into smaller PRs)

#### Brief description of what is fixed or changed

A matches method has been added to Tensor. It accounts for the index symmetries of the tensor while matching.

#### Other comments

Implementation of matching for TensAdd and TensMul (coming in future PRs) relies on this.

#### Release Notes

* tensor
  * Calling match on Tensor instances now accounts for index symmetries

### CODE REVIEW

**Comment by Kishore96in** [comment]
I don't understand why `./bin/mailmap_check.py` succeeds on my local machine with
```
No changes needed in .mailmap
````
but fails in the Github tests with output like
```
This author is in the AUTHORS file but not .mailmap:
Zac Hatfield-Dodds <zac.hatfield.dodds@gmail.com>
```
and so on (I don't see my name in any of the output, since my name is already in `.mailmap`). Any hints on how I should fix this? I don't see this particular scenario covered in <https://docs.sympy.org/dev/contributing/new-contributors-guide/workflow-process.html#mailmap-instructions>

**Comment by Kishore96in** [comment]
@Upabjojr could you take a look at this?

**Comment by Upabjojr** [comment]
This looks good to me.

Two tests have not finished yet... maybe the remote server froze?

**Comment by Upabjojr** [comment]
Closed and reopened this PR in order to restart the tests.

**Pull request merged**
