### PR TITLE
Updated durations.json

### PR DESCRIPTION
**Pull request by bjodah**
#### Brief description of what is fixed or changed
Updated `.ci/durations.json`, also added a README (cf. https://github.com/sympy/sympy/issues/15149#issuecomment-483128569).

#### Other comments
@oscarbenjamin what do you think of the README, clear enough?

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Maybe add a note here:
https://github.com/sympy/sympy/blob/6da0ab837c472e933145cf37fd2ab0634ffa1aa6/sympy/utilities/runtests.py#L52
explaining that this durations.json should also be updated.

Maybe --veryquickcheck should be changed so that it defaults to not running unrecognised tests. Otherwise it will rapidly become not very quick.

**Comment by oscarbenjamin** [comment]
I just tried --quickcheck with -n4 and takes longer than the way I normally run the tests.
```
$ pytest -m 'not slow' -n4    # 1620 seconds
$ pytest --quickcheck -n4   # 3973 seconds
```
I probably should have checked with master but was in the middle of a PR at the time.

Do you know why the timings would be like that?

**Comment by bjodah** [comment]
quickcheck and 'not slow' would run different sets of tests. `--quickcheck` and `--veryquickcheck` are based on `durations.json`, whereas 'slow' uses the manual markers. We could tweak the [selection criteria 'limits'](https://github.com/sympy/sympy/blob/master/.ci/parse_durations_log.py#L32) for the "medium slow" ones?

We should eventually only have one mechanism for selecting slow/fast tests. The `durations.json` file has so far been something of an unofficial experiment (hence I'm wary of mentioning it in runtests.py).

I'm definitely open to changing `durations.json` to whitelist quick tests instead. A more elaborate solution would be to have travis push the durations after each successful CI run to some server where one could analyze durations statistically, but that adds a whole other level of complexity.

**Comment by bjodah** [comment]
we can improve on this in a later PR

**Pull request merged**
