### PR TITLE
y*(x*M) != x*(y*M) for non-commutative symbols `x` and `y`

### PR DESCRIPTION
**Pull request by gxyd**
fixes issue #9422 .
I have not taken the `MatrixSymbol` into account since they employ `MatMul` instead of `*` operation.
For Matrices

```
>>> x, y = symbol('x, y', commutative=False)
>>> y*(x*M) != x*(y*M)
```

Please have a look

### CODE REVIEW

**Comment by gxyd** [comment]
Can some please review PR and restart the tests .

**Comment by jksuom** [comment]
Perhaps you could add the original version of the issue to the tests. I also wonder if the parentheses have any effect on the results. Are ``x*y*M`` and ``x*(y*M)`` (and ``(x*y)*M``) the same?
(The addition of those would also restart the tests though the slow test seems to fail quite stubbornly.)

Another matter is that I vaguely recall having seen some comments about the possible admission of non-commutative entries in matrices. However, I could not find that now. Can anybody point me to that discussion?

**Comment by gxyd** [comment]
> if the parentheses have any effect on the results. Are x*y*M and x*(y*M) (and (x*y)*M) the same?

Yes i think they are same. Since they were written like that in the main-issue.

**Comment by jksuom** [comment]
+1. The slow test timeout should be harmless.
No-one seems to mind having non-commutative entries in matrices.
Merging in 24 hours, if there are no objections.

**Pull request merged**
