### PR TITLE
Fixed is_regular and is_absorbing_chain for Discrete Markov Chains

### PR DESCRIPTION
**Pull request by Maelstrom6**
#### Brief description of what is fixed or changed

The current version of SymPy has had to use functions that only gave the correct answer some of the time. Since `decompose` has been added, this can be fixed to produce more reliable, faster results for `is_regular` and `is_absorbing_chain`.

#### Other comments

A Markov chain is regular iff some power of the transition matrix has only positive elements [Definition 11.5](https://www.dartmouth.edu/~chance/teaching_aids/books_articles/probability_book/Chapter11.pdf). This is equivalent to being irreducible and aperiodic for any finite Markov Chain [source](https://cran.r-project.org/web/packages/markovchain/vignettes/an_introduction_to_markovchain_package.pdf). This means the current implementation had problems. See, the matrix 
```
0 1
1 0
```
is not regular but current implementation says that it is. See [Example 11.16](https://www.dartmouth.edu/~chance/teaching_aids/books_articles/probability_book/Chapter11.pdf).

Also, the matrix
```
0 1 0
1 0 0
0 0 1
```
is not absorbing since the non-absorbing state 0 cannot reach the absorbing state 2. But current implementation says that is it absorbing. The added implementation is also `O(n**2)` instead of `O(n**2.3)` which I think is the best complexity of `linsolve`. [source](https://math.stackexchange.com/questions/1668781/what-is-computational-complexity-of-ax-b-when-size-of-a-increasing)

I have also added `is_ergodic` which is equivalent to being irreducible. See [Definition 11.4](https://www.dartmouth.edu/~chance/teaching_aids/books_articles/probability_book/Chapter11.pdf).

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by Maelstrom6** [comment]
@povinsahu1909, could you please verify these definitions? Just so we have two people that say these changes are correct.

@czgdp1807, I'm not sure how close 1.7 is to releasing. But would it be possible to include this as well? It's just a small fix.

**Comment by povinsahu1909** [comment]
According to me, all the definitions are true and IMO all the changes that you made are required as I have encountered the same.

**Comment by czgdp1807** [comment]
Apologies for not responding earlier due to some commitments. Can you please add some references(some textbook examples) for tests so that they can be verified and this PR can be merged?

**Comment by Maelstrom6** [comment]
Will do so in about 20 hours from now.

**Comment by Maelstrom6** [comment]
I had to change a few lines in `communication_classes` since there was a bug. When I first created it, I thought that the size of a communication class must be divisible by its periodicity. Hopefully it seems like a reasonable assumption since `communication_classes` was called roughly 20 to 40 times with all the testing and doc tests. 

Turns out this is not the case. The test on line 228 proves this assumption wrong.

**Comment by czgdp1807** [comment]
LGTM. Will merge tomorrow.

**Pull request merged**
