### PR TITLE
Issue: #14366

### PR DESCRIPTION
**Pull request by czgdp1807**
I have moved set arithmetic operators to sympy/sets/sets.py
from sympy/sets/setexpr.py

### CODE REVIEW

**Comment by abaokar-07** [comment]
This type of title is not recommended, see [here](https://github.com/sympy/sympy/wiki/Development-workflow#writing-pull-request-title-and-description) for how to write title names

**Comment by Abdullahjavednesar** [comment]
@ylemkimon can you review this.

**Comment by Abdullahjavednesar** [comment]
@czgdp1807 better rename the PR to something meaningful.

**Comment by abaokar-07** [comment]
This issue has been fixed now

**Pull request closed without merging**
