### PR TITLE
Added size property to the Union class

### PR DESCRIPTION
**Pull request by michaelcchu**
#### Brief description of what is fixed or changed
Added size property to the Union class to calculate the size/number-of-
-elements/cardinality of the Union of two disjoint Ranges. (Disjoint 
Ranges are Ranges whose intersection is the EmptySet). The primary
motivation for this addition is that we are able to calculate the sizes of 
Ranges, so we should be able to calculate the sizes of Unions of Ranges 
too.

Example:
```
>>> from sympy import *
>>> S1 = Range(5)
>>> S1.size
5
>>> S2 = Union(Range(5), Range(7,11))
>>> S2.size
9
>>>
```

This is what used to happen:
```
>>> from sympy import *
>>> S1 = Range(5)
>>> S1.size
5
>>> S2 = Union(Range(5), Range(5,7))
>>> S2.size
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Union' object has no attribute 'size'
>>>
```

#### Other comments
Since this property, size, only applies to Unions of Ranges, I wasn't sure if I 
should put it in the Union class or the Range class (or somewhere else).
If you have any advice/feedback on this, I would greatly appreciate that!

The most natural extension of this feature is to calculate the size of the 
Union of an *arbitrary* number of disjoint Ranges (not just two). Another 
natural extension is calculating the sizes of Unions of disjoint FiniteSets 
(do FiniteSets have a property that is equivalent to the size property of 
Ranges?). 

Also, one question I have is: should size be added to the Range 
documentation? (I feel that it should be added)

A more difficult extension of this feature is calculating the sizes of Unions of 
*non*-disjoint sets.

#### Release Notes

* sets
  * Added size property to the Union class.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Adding a more general `cardinality` function for sets would be useful. There are cases where it would be difficult though. We probably need to have possibility of an unevaluated `Cardinality` object.

I don't think adding something that only works for union of two ranges is very useful.

**Comment by mccode187** [comment]
That sounds like a good idea! If we added a cardinality function in the Set class, we could use it for Ranges, Unions, Intersections, FiniteSets, etc. Also, the size property in the Range class would probably become unnecessary.

I agree that allowing the possibility of an unevaluated Cardinality object would be good, because some cardinalities (especially cardinalities of symbolic sets) might be tricky to calculate. 

Since a Cardinality object is not a Set, where do you think we should put the Cardinality class?

**Comment by oscarbenjamin** [comment]
It should still go in the sets module. There is an old issue about this: https://github.com/sympy/sympy/issues/2995

I suggest discussing your idea on the issue before submitting a PR.

**Comment by oscarbenjamin** [comment]
I'm going to close this PR because it isn't needed.

**Pull request closed without merging**
