### PR TITLE
Replaced 3.5 builds in travis with 3.6

### PR DESCRIPTION
**Pull request by techytoes**
All tests passed for the change in `travis.yml` locally.Please review this PR @asmeurer .#12814

### CODE REVIEW

**Comment by firedranzer** [comment]
@asmeurer please have a look at the travis build and suggest me changes.

**Comment by souravsingh** [comment]
@firedranzer Please fix the merge conflicts

**Comment by firedranzer** [comment]
@souravsingh suggest me some changes .I am currently running out of ideas and stuck at the error.

**Comment by gxyd** [comment]
@firedranzer can you please fix the merge conflicts? We may then be able to proceed.

**Comment by gxyd** [comment]
I am closing this PR. A PR with similar changes #13399 was closed, since it was not required. So this PR is also not required no more.

**Pull request closed without merging**
