### PR TITLE
Get rid of some unnecessary commented out code (issue #6849)

### LINKED ISSUE #6849: Get rid of some unnecessary commented out code with eradicate
```
A lot of commented out code is unnecessary, because it is still in the version history. There is a tool https://github.com/myint/eradicate , which can help to find and remove such comments.  You'll have to review each change carefully, as it removes a lot of false positives from cases where the commented out code is descriptive.
```
Original issue for #6849: http://code.google.com/p/sympy/issues/detail?id=3750
Original author: https://code.google.com/u/asmeurer@gmail.com/

### PR DESCRIPTION
**Pull request by skirpichev**
There is a lot of false positives (see [attached logs](http://code.google.com/p/sympy/issues/detail?id=3750#c1)), so I don't think that we should automate such cleanup.

fixes #6849

### CODE REVIEW

**Comment by skirpichev** [comment]
Rebased again.

**Comment by skirpichev** [comment]
Feel free to pick up this work.

Goodbye and thanks for all the fish! :)

**Comment by smichr** [comment]
Rather than let this go stale again, I will commit in 24 unless you object, @asmeurer. 3 other people have looked at this. I looked at every change. @skirpichev responded to various objections you had. This is a thankless task that should be done from time to time -- not without human checking, as the review process has shown, however. That being done, let's not throw away the time that has been invested in the process.

**Comment by asmeurer** [comment]
I haven't looked at this in a long time but I trust your judgement.

**Pull request merged**
