### PR TITLE
aligned middle of matrix with baseline

### LINKED ISSUE #10472: pprint should align the middle of the matrix to the baseline?
Consider the current behaviour, where operators align with the top of the matrix:

```
>>> Z = Matrix(5,5, lambda i,j: i+j)
>>> pprint(MatMul(2,Z))
2⋅⎡0  1  2  3  4⎤
  ⎢             ⎥
  ⎢1  2  3  4  5⎥
  ⎢             ⎥
  ⎢2  3  4  5  6⎥
  ⎢             ⎥
  ⎢3  4  5  6  7⎥
  ⎢             ⎥
  ⎣4  5  6  7  8⎦
>>> pprint(MatAdd(Z,Z))
⎡0  1  2  3  4⎤ + ⎡0  1  2  3  4⎤
⎢             ⎥   ⎢             ⎥
⎢1  2  3  4  5⎥   ⎢1  2  3  4  5⎥
⎢             ⎥   ⎢             ⎥
⎢2  3  4  5  6⎥   ⎢2  3  4  5  6⎥
⎢             ⎥   ⎢             ⎥
⎢3  4  5  6  7⎥   ⎢3  4  5  6  7⎥
⎢             ⎥   ⎢             ⎥
⎣4  5  6  7  8⎦   ⎣4  5  6  7  8⎦
```

This looks poor, but I figured it might be the desired behaviour...

Here's the example that makes me think its wrong:

```
>>> pprint(sin((1+1/x)/(1+1/y)) + det(MatMul(2,Z)))
   ⎛    1⎞                       
   ⎜1 + ─⎟                       
   ⎜    x⎟                       
sin⎜─────⎟ + 32⋅│⎡0  1  2  3  4⎤│
   ⎜    1⎟      │⎢             ⎥│
   ⎜1 + ─⎟      │⎢1  2  3  4  5⎥│
   ⎝    y⎠      │⎢             ⎥│
                │⎢2  3  4  5  6⎥│
                │⎢             ⎥│
                │⎢3  4  5  6  7⎥│
                │⎢             ⎥│
                │⎣4  5  6  7  8⎦│
```

Here's how I think it should work, using the proposed #10423:

```
pprint(sin((1+1/x)/y) + Trace(Z))
               ⎛⎡0  1  2  3  4⎤⎞
   ⎛    1⎞     ⎜⎢             ⎥⎟
   ⎜1 + ─⎟     ⎜⎢1  2  3  4  5⎥⎟
   ⎜    x⎟     ⎜⎢             ⎥⎟
sin⎜─────⎟ + tr⎜⎢2  3  4  5  6⎥⎟
   ⎝  y  ⎠     ⎜⎢             ⎥⎟
               ⎜⎢3  4  5  6  7⎥⎟
               ⎜⎢             ⎥⎟
               ⎝⎣4  5  6  7  8⎦⎠
```

where note the `sin` alignment is by-design, and (relevant to this bug) the `+` and `tr` operator line up with `sin`.

At least, det, MatAdd, MatMul, MatPow would need fixed, maybe others I haven't thought of.

### PR DESCRIPTION
**Pull request by madan96**
**Previous Output**: 

```
>>> Z = Matrix(5,5, lambda i,j: i+j)
>>> pprint(MatMul(2,Z))
2⋅⎡0  1  2  3  4⎤
  ⎢             ⎥
  ⎢1  2  3  4  5⎥
  ⎢             ⎥
  ⎢2  3  4  5  6⎥
  ⎢             ⎥
  ⎢3  4  5  6  7⎥
  ⎢             ⎥
  ⎣4  5  6  7  8⎦
```

**Output after this PR**:
```
>>> Z = Matrix(5,5, lambda i,j: i+j)
>>> pprint(MatMul(2,Z))
  ⎡0  1  2  3  4⎤
  ⎢             ⎥
  ⎢1  2  3  4  5⎥
  ⎢             ⎥
2.⎢2  3  4  5  6⎥
  ⎢             ⎥
  ⎢3  4  5  6  7⎥
  ⎢             ⎥
  ⎣4  5  6  7  8⎦
```
Fixes #10472 .

### CODE REVIEW

**Comment by madan96** [comment]
@cbm755 I will have to change some of the test cases as the results in those cases are tested for the older  print format.

**Comment by cbm755** [comment]
Can you add a test?  And fix the breaking test, if appropriate.

*ping* is usually when someone doesn't reply for like a week (most of us get email automatically for changes).  (No worries, its just FYI).

**Comment by madan96** [comment]
Please review! :simple_smile:

**Comment by cbm755** [comment]
I think we might want a slightly different treatment for even/odd heights:
````
(Matrix([[0, 0], [0, 0]]), Matrix([0, x**2]))
Out[25]: 
⎛        ⎡0 ⎤⎞
⎜⎡0  0⎤  ⎢  ⎥⎟
⎜⎢    ⎥, ⎢ 2⎥⎟
⎝⎣0  0⎦  ⎣x ⎦⎠
````
The tops of those two matrices should align.  There are are least two examples in the tests that would need to change too.

Right now its floor(x/2), perhaps should be ceil(x/2)?

**Comment by asmeurer** [comment]
Why should the tops align? It seems more natural to me for the bottoms to align.

**Comment by asmeurer** [comment]
I'm +1 to this bug I guess we should figure out how to handle the even/odd thing.

**Comment by asmeurer** [comment]
As far as I can tell with other expressions, when they are an even number of characters high the baseline is the lower mid-character. Consider examples:

```
In [6]: Sum(f(x), (x, y**2, 1)) + Integral(x, x)
Out[6]:
           1
          ___
          ╲
⌠          ╲    f(x)
⎮ x dx +   ╱
⌡         ╱
          ‾‾‾
              2
         x = y

In [17]: binomial(1, x**2) + x
Out[17]:
    ⎛1 ⎞
    ⎜  ⎟
x + ⎜ 2⎟
    ⎝x ⎠

In [10]: 1/x + (x**2)**x # not 100% sure how the baseline is computed here
Out[10]:
    x
⎛ 2⎞    1
⎝x ⎠  + ─
        x

```

**Comment by cbm755** [comment]
@asmeuer perhaps b/c matrices index from the top increasing downwards?   But I don't feel that strongly about it.

**Comment by madan96** [comment]
I made changes to top align the matrices by adding conditions for odd/even heights. But I feel that instead of top/bottom align we should focus on middle align. I mean two matrices should be aligned w.r.t to their middle height. For odd, there would exist only one middle, but in case of even height we have got two options. Now I guess what @cbm755 is suggesting is that we should use upper middle height for even height so that there is top alignment whenever possible. Also, I think the only way we can achieve proper alignment in cases like : 

```
In [17]: binomial(1, x**2) + x
Out[17]:
    ⎛1 ⎞
    ⎜  ⎟
x + ⎜ 2⎟
    ⎝x ⎠
```
is by converting even heights to odd by providing an exta newline in b/w. Like this:

```
In [17]: binomial(1, x**2) + x
Out[17]:
    ⎛1 ⎞
    ⎜  ⎟
x + ⎜  ⎟
    ⎜ 2⎟
    ⎝x ⎠
```

**Comment by cbm755** [comment]
@madan96: padding-to-odd height would be a bigger change than this PR.  I don't know enough about the box drawing model to know how do-able it is.

**Comment by cbm755** [comment]
To my eye, this would look better with the tall vector shifted down:
````
             ⎡1 ⎤       
             ⎢  ⎥       
             ⎢2 ⎥       
⎡4  5  6  1⎤ ⎢  ⎥   ⎡36⎤
⎢          ⎥⋅⎢3 ⎥ = ⎢  ⎥
⎣7  8  9  2⎦ ⎢  ⎥   ⎣58⎦
             ⎢ 2⎥       
             ⎣y ⎦       
````
*BUT* this would look worse:
````
MatMul(exp(y),Matrix([[y**2]]),evaluate=False)
 y ⎡ 2⎤
ℯ ⋅⎣y ⎦
````
Because it would become:
````
 y
ℯ ⋅⎡ 2⎤
   ⎣y ⎦
````

I think simpler solution wins, treat matrices same as others w.r.t. odd-height.  As this patch is currently.

**Comment by cbm755** [comment]
@asmeurer shall I merge this as-as?

**Comment by asmeurer** [comment]
I'm +1 to this as-is.

**Pull request merged**
