### PR TITLE
Removed all references to C from sympy.assumptions.

### PR DESCRIPTION
**Pull request by toolforger**

### CODE REVIEW

**Comment by toolforger** [comment]
This is a toe-in-the-water PR: Let me know whether doing a module-by-module C elimination is preferred over a monster commit that eliminates C everywhere at once.
Plus for module-by-module: easier to keep mergeable, easier to review.
Plus for all-at-once: less commits in the history.

I have a preference for module-by-module.

**Comment by toolforger** [comment]
Anybody got an idea what's up with the failed tests?
They seem unrelated to the changes. FWIW they're all happening with pypy, not elsewhere.

**Comment by toolforger** [comment]
Restarting the jobs got me the same errors, so it seems deterministic.

**Comment by aktech** [comment]
> Anybody got an idea what's up with the failed tests?
They seem unrelated to the changes. FWIW they're all happening with pypy, not elsewhere.

Indeed. See #8972

**Comment by asmeurer** [comment]
Doing it bit by bit sounds much better.

**Pull request merged**
