### PR TITLE
Changed the basic class for making

### PR DESCRIPTION
**Pull request by Abhishek-IOT**
#### References to other Issues or PRs
No issue 

#### Brief description of what is fixed or changed
I changed the basic class from the examples package.
Made the new method for  Normal equation example and renamed main to squared equations

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by Abhishek-IOT** [comment]
not done

**Comment by oscarbenjamin** [comment]
@Abhishek-IOT can you stop opening and closing pull requests?

**Comment by Abhishek-IOT** [comment]
I am not able to do pull request..........I am not able to get the reason why it is done. Can you help me it.

**Comment by jksuom** [comment]
@Abhishek-IOT From which repository and branch did you send the pull request? I don't see a sympy repository among your GitHub repositories. You cannot send a pull request directly from your local repository. You must first push the branch to GitHub. See https://github.com/sympy/sympy/wiki/Development-workflow#id52.

**Comment by Abhishek-IOT** [comment]
I did delete that repo because it after having more than 50 attemps it was not working.My work i have expalined in the pull request.I will again fork the repository and will again do the commits .It was my first experience.Thank for replying Kalevi Suominen.I am new to contributing to open source it was my first experience.Can you guide me how can I do so.

**Comment by Abhishek-IOT** [comment]
I am B.tech Student of Second year.I know Python well but I am new to open source that why I created this much chaos.

**Comment by Abhishek-IOT** [comment]
IMG_20200524_134650
This was my contribution it did not fix an issue but I made having more precise explanation of working of Sympy.My 2 mistakes are =
1)I did not make a virtual environment 
2)Uploaded my code from Python 3.8 version

**Pull request closed without merging**
