### PR TITLE
Updated trailing function

### PR DESCRIPTION
**Pull request by ghost**
#### Brief description of what is fixed or changed
Tweaked the trailing function, performance improvement is not much for random numbers (~1.05 times faster) but it is 2.5 times faster for powers of 2

#### Release Notes

- ntheory
    - trailing function improved for n < 2**300

### CODE REVIEW

**Comment by oscargus** [comment]
Thanks! It seems like your editor made tabs instead of spaces, hence the failed test. Can you please update this?

**Comment by smichr** [comment]
what is the break even point for powers of 2 handled by each method?

**Comment by jksuom** [comment]
> 2.5 times faster for powers of 2

I am not sure about this. Apparently there is no change in the code for exact powers of 2. 

In general, there seems to be no significant difference in timing. However, I find this code easier to understand than the old code.

**Comment by adhoc-king** [comment]
@jksuom @smichr I ran a test case for powers of two and the new code was running faster, even I was confused about this because I am not handling it separately.
@oscargus The performance for random numbers is not decreasing so even if this code has increased performance for numbers with large trailing zeros then it should be an issue. Also, the code looks more readable than the previous one.

**Comment by jksuom** [comment]
I don't know how the time should be measured. I seem to get inconsistent results with ipython:
```
In [2]: %time trailing(3<<55)
CPU times: user 27 µs, sys: 4 µs, total: 31 µs
Wall time: 30 µs
Out[2]: 55

In [3]: %timeit trailing(3<<55)
100000 loops, best of 3: 2.29 µs per loop
```
In any case, the time is insignificant, and I agree that this code looks more readable.

**Comment by smichr** [comment]
OK, it's been some time since I looked at this function. The reason that it is unchanged for perfect powers of 2 is that these are handled by the code preceding the changed code. 

The changes, however, force non-perfect powers to be eaten 8 bytes at a time -- even when there may be very many bites to eat. The more cryptic code is doubling the bite size with each step. This can make a big difference. And since (fortunately) python supports large ints, this becomes a factor well before any memory limit is reached. The loop is essentially doing a binary search up and down until all powers of two have been removed. The 8-bytes at a time is good if there are relatively few trailing bits. My testing here suggests that the break-even is somewhere around `2**300` (which is the upper limit used in mpmath's `python_bitcount` before switching to using `math.log`) so the following may be the better change which adds a single test to see if the 8-byte nibbling might be better:

```python
def trailing(n):
    n = abs(int(n))
    if not n:
        return 0
    low_byte = n & 0xff
    if low_byte:
        return small_trailing[low_byte]

    # 2**m is quick for z up through 2**30
    z = bitcount(n) - 1
    if isinstance(z, SYMPY_INTS):
        if n == 1 << z:
            return z

    if z < 300:
        # fixed 8-byte reduction
        t = 8
        n >>= 8
        while not n & 0xff:
            n >>= 8
            t += 8
        return t + small_trailing[n & 0xff]

    # binary reduction important when there might be a large
    # number of trailing 0s
    t = 0
    p = 8
    while not n & 1:
        while not n & ((1 << p) - 1):
            n >>= p
            t += p
            p *= 2
        p //= 2
    return t
```

**Comment by smichr** [comment]
For timing, try `timeit('for k in range(300,1000):ok=trailing(2**k + 2**(k-1))', 'from sympy import trailing',number=100)`

**Comment by adhoc-king** [comment]
I think this can be merged now

**Pull request merged**
