### PR TITLE
[GSoC] Added Nyquist plot to control plots.

### PR DESCRIPTION
**Pull request by abhiphile**
This release introduces the `nyquist_plot` function to the control module, providing users with the ability to generate Nyquist plots for Single-Input Single-Output (SISO) Linear Time-Invariant (LTI) systems. It plots the complex values of a system's frequency response as a function of frequency, showing how the output of the system changes in magnitude and phase as the frequency varies.
SymPy own `plot_parametric` function have been used to make `nyquist_plot`.

#### Release Notes

* physics.control
  * Added Nyquist plot to control.

### CODE REVIEW

**Comment by abhiphile** [comment]
This implementation of nyquist plot uses only symbolic methods. I've used plot_parametric method to do so.

**Comment by abhiphile** [comment]
```
>>> tf1 = TransferFunction(2*s**2+5*s+1, s**2+2*s+3, s)
>>> nyquist_plot(tf1)
```
## MATLAB Output
image
## SymPy Output
image

**Comment by abhiphile** [comment]
@Sc0rpi0n101 @faze-geek I've used symbolic methods for this method. The only problem I'm facing with this is that I'm not able to draw a external boundary using the `plot_parametric` function.

**Comment by Sc0rpi0n101** [comment]
> @Sc0rpi0n101 @faze-geek I've used symbolic methods for this method. The only problem I'm facing with this is that I'm not able to draw a external boundary using the `plot_parametric` function.

It looks like the right and top spines are hidden by default: https://github.com/sympy/sympy/blob/05e3ffc6ea7345db9081b4419daa12d3f63980c4/sympy/plotting/backends/matplotlibbackend/matplotlib.py#L67

and the left and bottom spines are aligned around the data points, not the axes: https://github.com/sympy/sympy/blob/05e3ffc6ea7345db9081b4419daa12d3f63980c4/sympy/plotting/backends/matplotlibbackend/matplotlib.py#L258

And, there is no logic for adding a grid. So, it will be hard to add the external boundary as it is. 

If you think it'll also be helpful elsewhere, I can make a PR adding these customizations for the backend.

**Review by Sc0rpi0n101 — APPROVED** [review]

**Pull request merged**
