### PR TITLE
 Fix __rfloordiv__ not reversed

### PR DESCRIPTION
**Pull request by ylemkimon**
Fixed `__rfloordiv__` not being reversed.

### CODE REVIEW

**Comment by smichr** [comment]
Please add a test.

**Comment by ylemkimon** [comment]
@smichr I'm not sure how we can test that. Current `test_priority.py` seems to not work with `floordiv`.

**Comment by ylemkimon** [comment]
@smichr Refactored test_priority.py to test reverse operations, mod(%), and floordiv(//).

**Comment by smichr** [comment]
Congratulations on finding a way to test this...and for catching this error!

**Pull request merged**
