### PR TITLE
FIX: `solve` now acknowledges `dict=True` for Relational args

### LINKED ISSUE #13534: solve dict=True ignored
```
In [22]: solve(Eq(2*x,1), dict=true)
Out[22]: [{x: 1/2}]

In [23]: solve([Eq(x**2-1,0),Gt(x,0)],(x,),dict=True)
Out[23]: x = 1
```

### PR DESCRIPTION
**Pull request by AtharvaKhare**
Solve method will return a list of dictionaries for Relational args.
Currently, it only supports solution with And, Or only.

Fixes #13534.

(Accidentally closed previous PR https://github.com/sympy/sympy/pull/13537)

### CODE REVIEW

**Comment by jksuom** [comment]
> Accidentally closed previous PR #13537

It would have been possible to reopen it.

**Comment by AtharvaKhare** [comment]
Should I add anything else??

**Comment by czgdp1807** [comment]
@AtharvaKhare Are you still working on it?

**Comment by AtharvaKhare** [comment]
@czgdp1807 Not at the moment, can be closed if the code can't be reused.

**Comment by czgdp1807** [comment]
@smichr @aktech Can this PR be reused? It looks like the issue is still not fixed. This PR fixes the same successfully,
```python
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x = symbols('x', real=True)
>>> solve(Eq(2*x,1), dict=true)
[{x: 1/2}]
>>> solve([Eq(x**2-1,0),Gt(x,0)],(x,),dict=True)
[{x: 1}]
```

**Comment by czgdp1807** [comment]
ping @smichr @aktech

**Comment by czgdp1807** [comment]
Just for information, I will continue this PR today to complete it.

**Pull request closed without merging**
