### PR TITLE
Removes Symengine backend from sympy.physics.vector/mechanics/_biomechanics.

### LINKED ISSUE #25401: Removal of SymEngine from `sympy.physics.mechanics`/`sympy.physics.vector`
This issue stems from a discussion on PR #25400.

Due to the increasingly drifting parity between SymPy and SymEngine, and inability for SymPy developers to actively fix all relevant SymEngine bugs (due to e.g. lack of C++ experience, delays due to release cycle etc.), we are proposing to unfortunately drop support for SymEngine within `sympy.physics.mechanics` and `sympy.physics.vector`.

@moorepants has suggested that we we might be able to do this "[without deprecation because it does not change results or API, it only has to do with performance](https://github.com/sympy/sympy/pull/25400#issuecomment-1643952943)."

We are making an assumption here that there are very few, if any, users of SymEngine with `sympy.physics.mechanics`/`sympy.physics.vector`. If you _do_ use SymEngine in this way, please let us know!

### PR DESCRIPTION
**Pull request by moorepants**
#### References to other Issues or PRs

Fixes #25401

#### Brief description of what is fixed or changed

Symengine was added as a backend for sympy.physics.mechanics and related packages and modules to improve performance. Instead it created a maintenance burden because the developers of these SymPy packages do not develop Symengine and many additions improvements to the SymPy packages require duplicating functionality in Symengine. This PR removes support for the Symengine backend in a backwards compatible fashion. If a user was using this, results will not change but their code execution may become slower.

#### Release Notes

* physics.vector
  * Symengine backend support removed.
* physics.mechanics
  * Symengine backend support removed.
* physics.biomechanics
  * Symengine backend support removed.

### CODE REVIEW

**Comment by ThePauliPrinciple** [comment]
The changes look good, but two comments:

The imports should be using the full imports and not just import from `sympy`.
There is one import which renames `Expr`: `from sympy.core.expr import Expr as ExprType`, I suspect this rename might no longer be needed (but was before because of the symengine backend) but I'm not certain.

**Comment by asmeurer** [comment]
Let's make sure this gets flagged as backwards incompatible in the release notes.

**Comment by oscarbenjamin** [comment]
As far as I can tell from the discussion in gh-25401 we are agreed that this should be merged so merging.

CC @certik @isuruf

**Comment by oscarbenjamin** [comment]
> The changes look good, but two comments:

Sorry I just missed this comment when merging.

> The imports should be using the full imports and not just import from `sympy`.

I think that because mechanics is a "leaf node" in the import graph then it is okay to just import things in the way that users would.

The situation where it is important to use fully qualified imports is really for anything that would be imported during the process of `import sympy` because then it causes circularity problems etc. Otherwise the intended way to import things is always `from sympy import X` which is what users should do. Also in test code things should be imported in the way that users are expected to import thing (not fully qualified imports).

> There is one import which renames `Expr`: `from sympy.core.expr import Expr as ExprType`, I suspect this rename might no longer be needed (but was before because of the symengine backend) but I'm not certain.

Yes, probably that is not needed...

**Comment by asmeurer** [comment]
Fully qualified imports in library code is something that could be enforced with a linter. Although I've never really been that convinced that it's that important. There's a misconception that `from sympy.core.symbol import Symbol` is faster than `from sympy import Symbol`, but that isn't true at all.

**Comment by oscarbenjamin** [comment]
> Although I've never really been that convinced that it's that important.

It wouldn't be important if SymPy was not full of circular imports.

**Pull request merged**
