### PR TITLE
Revert gh-26385 (maintain ordering in heurisch mapping)

### LINKED ISSUE #26922: The following Integral doesn't evaluate anymore
```py
from sympy import *
init_printing()

a, b, x = symbols("a, b, x", real=True, positive=True)
C = symbols("C", real=True)
i = Integral(-C*x*exp(-a*x**2 - sqrt(b)*x), x) + Integral(C*x*exp(-a*x**2 + sqrt(b)*x), x)
i.doit()
```

Output with sympy 1.12.1 (and older):

image

Output with sympy 1.13.1:

image

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

Reverts gh-26358
Fixes https://github.com/sympy/sympy/issues/26922 and https://github.com/sympy/sympy/issues/26930

#### Release Notes

* integrals
   * A change to the heurisch integration routine in SymPy 1.13 was reverted because to fix reported regressions. Previously the change resulted in heurisch failing to integrate some functions.

### CODE REVIEW

**Comment by smichr** [comment]
Are the newly added tests passing because they are solved by `heurisch`?

**Comment by oscarbenjamin** [comment]
> Are the newly added tests passing because they are solved by `heurisch`?

One is and I have now changed it to call heurisch explicitly in the test.

I'm not sure about the one from gh-26922. It doesn't seem like heurisch can solve those integrals. I did bisect it to the reverted commit though and I can confirm that this PR fixes it compared to master.

More investigation is definitely needed but in this PR I just want to revert the change and add regression tests. Feel free to do more detailed investigation and come up with a fix for the original issue that avoids the reported regressions.

**Comment by asmeurer** [comment]
Heurisch is so sensitive to little changes in the algorithm like this. I wouldn't be surprised if this change also resulted in some other integrals being able to be computed which weren't before.

**Comment by oscarbenjamin** [comment]
> I wouldn't be surprised if this change also resulted in some other integrals being able to be computed which weren't before.

I wouldn't be surprised either but we have two regression reports in two days. It would be really good for someone to sit down and analyse this in detail. I don't have time though and we need to revert this change for now.

**Comment by oscarbenjamin** [comment]
> I don't have time though and we need to revert this change for now.

To be clear we need to backport this in a bugfix release. I will wait a short time for review but otherwise I will merge this and backport for bugfix.

It would be great if others would review and merge this but my experience is that in this sort of situation that cannot be depended on so if needed I will self-merge and backport. If anyone thinks that this is not the right fix then they need to produce something better quickly because otherwise revert is the default position here. This does not mean that the original change is bad but just that it needed more consideration which can still happen in future.

**Comment by asmeurer** [comment]
I agree a revert is a good idea. I'm just pointing out that making changes to heurisch is very difficult for this reason. It's not even clear when you can say a change to heurisch is "better" or not without some huge dataset of test integrals or some kind of way to generate them automatically.

**Comment by asmeurer** [comment]
Although it's a little unfortunate that we are choosing between "can no longer do some integrals" and "fixes some wrong results" here. I might be missing some context, but given that choice I would typically prefer the version that has no wrong results even if it can't compute as much.

**Comment by oscarbenjamin** [comment]
> I would typically prefer the version that has no wrong results even if it can't compute as much.

We are only looking at a handful of examples. I don't understand the change well enough to conclude that it does not also produce incorrect results for other cases.

To be clear: I don't want to work on this at all but there are regressions reported against 1.13. This is one example of many where Chris made a change that was self-merged without review and now there are reports of problems in this case as also in some others. Maybe the change is good but investigating that even slightly is more time than I want to spend on this. If anyone wants something better than this revert then they need to put some actual work in (this has already consumed more of my time than I was willing to commit).

**Comment by smichr** [comment]
> To be clear: I don't want to work on this at all but there are regressions reported against 1.13

I don't like the idea of reverting a change which fixed a problem  (and identified concrete reasons the algorithm was wrong) and didn't break anything known at the time. When there are regressions that are identified *later*, why are those (new) problems more important than the old problem? We have *lots* of open issues. What is the problem with letting the issues/regressions become new issues?

**Comment by oscarbenjamin** [comment]
> I don't like the idea of reverting a change which fixed a problem

Neither do I but I don't accept your claim that this "fixed a problem". I want *someone else* to review this work.

I want someone else to confirm that this change is correct. Aaron has commented here in general support but has not confirmed that the change is correct.

I also want someone other than me to investigate the regressions. If the change is a proper bugfix and that means that some integrals are left unevaluated than that is fine but someone needs to investigate that. That also means investigating the cases that are reported as regressions and explaining why they no longer evaluate or otherwise fixing it so that they do.

You have just pushed a commit into this PR so I am going to close it. Do not push commits into my PRs again in future or I will block you from doing so.

**Comment by smichr** [comment]
> Do not push commits into my PRs again in future or I will block you from doing so.

This sounds more aggressive than I hope you intend. It is always an option to refuse commits from maintainers. If you don't wish to collaborate, that would be a good option to select. Otherwise, the change I made solved the problem and was not one that you were likely to make. Hopefully it failed the test that you had identified.

Does it make more sense to just reopen this or to cherry pick changes you made to tests?

**Comment by oscarbenjamin** [comment]
> I want _someone else_ to review this work.

Note that it would not be necessary to labour this point if someone else had reviewed the work in the first place. You very often merge your own unreviewed work and it very often is the source of bugs.

That is why I don't accept your claim that the original PR "fixed a problem": I have seen many PRs in the past that looked like they fixed a problem but were actually bad ideas that just needed reverting. I want someone else to verify that this change is correct or otherwise I will revert it for now.

**Comment by oscarbenjamin** [comment]
> Otherwise, the change I made solved the problem and was not one that you were likely to make

Use a separate PR for that. This PR was intended to do precisely two things:

1. Revert the change
2. Add regression tests

If you want to do something else then do it in a separate PR. Don't presume that I am happy for this PR to be co-opted for another purpose.

**Pull request closed without merging**
