### PR TITLE
Fix plot piecewise function

### PR DESCRIPTION
**Pull request by wanglongqi**
flat function in `plot.py` does not convert the vector to float type, thus numpy return AttributeError: sqrt.

Convert the vector explicitly to np.float will fix this bug.

### CODE REVIEW

**Comment by pelegm** [comment]
It is simply a code quality issue:
```pytb
AssertionError: File contains trailing whitespace: /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sympy/plotting/tests/test_plot.py, line 94.
```

Do you plan to fix that?

**Comment by wanglongqi** [comment]
@pelegm the white spaces are removed.

**Comment by cbm755** [comment]
This looks reasonable and tests pass...

But is there a deeper bug that Float's are getting this far?  `x` and `y` are numpy arrays.  For plotting `sin` they have `dtype('float64')`.  But when plotting your piecewise example, `x` has `dtype('O')` (with Floats inside).

So are we just wallpapering over something that should've happened higher up?  I'm not familar with this code but presumably for efficiency, plotting should use hardware floats as soon as possible.

Maybe I'm wrong and this is the right fix... if so, convince me :)

**Comment by wanglongqi** [comment]
The array is dtype('o') is coming from `y` value in piecewise function is a `Float` object. Should we change it to a `float64` as soon as possible? At the beginning of `plot` function or any other place?

**Comment by cbm755** [comment]
I'm not sure, I suspect you know this code better than I do.  What do you think?

**Comment by wanglongqi** [comment]
`plot.py` uses a self defined `lambdify` function, thus it behaviors not the same as `lambdify`  in `sympy.utilities.lambdify`. I think someone else is working one the `lambdify` function, they commented in the file:

	rewrite of lambdify - This stuff is not stable at all.

	It is for internal use in the new plotting module.
	It may (will! see the Q'n'A in the source) be rewritten.

	It's completely self contained. Especially it does not use lambdarepr.

	It does not aim to replace the current lambdify. Most importantly it will never
	ever support anything else than sympy expressions (no Matrices, dictionaries
	and so on).

However, at this stage I think it is better to have a backup at end of `lambdify`, in case the 'experimental' feature fails.

**Comment by certik** [comment]
@wanglongqi, @cbm755 what is the status of this? The change seem simply. I am a little worried about saving a file as part of the test, but hopefully that doesn't break anything. Is this fix not the right one? If so, how should we fix it?

**Comment by wanglongqi** [comment]
@certik this one is just a workaround to ensure the function become numerical before plot. The error is in the unstable `lambdify`, which I think unlikely to be fixed in a short time. The workaround will slow the plotting process a bit by calling the `astype` function, but I think it worth to have a backup for the cases where those experimental features failed. I do not think this one will break anything, at most it add several trivial function calls  to the plotting process.

**Comment by cbm755** [comment]
Perhaps add a comment indicating this issue number and a one-line explanation?  `# Workaround plotting piecewise (#9577): perhaps a lower-level fix is possible` or something like that.

That way, if someone wants to try a deeper fix, she can see the comment.

**Comment by cbm755** [comment]
Then I'm +1

**Comment by certik** [comment]
Ok, this is ready to get merged if tests pass. +1 from me as well.

**Comment by cbm755** [comment]
@wanglongqi please see #9514.

Thanks for this.

**Comment by hargup** [comment]
For some reason, tests with Python 3 fail on my machine, though it works correctly with python2:
```
./bin/test sympy/plotting/tests/test_plot.py 
====================================================================================== test process starts =======================================================================================
executable:         /home/hargup/anaconda/envs/py3.4/bin/python  (3.4.3-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 1.16
random seed:        55247481
hash randomization: on (PYTHONHASHSEED=1371621615)

sympy/plotting/tests/test_plot.py[3] .E.                                                                                                                                                    [FAIL]

__________________________________________________________________________________________________________________________________________________________________________________________________
_______________________________________________________________________ sympy/plotting/tests/test_plot.py:test_matplotlib ________________________________________________________________________
  File "/home/hargup/210fs/software_sources/sympy/sympy/plotting/tests/test_plot.py", line 239, in test_matplotlib
    plot_and_save('test')
  File "/home/hargup/210fs/software_sources/sympy/sympy/plotting/tests/test_plot.py", line 91, in plot_and_save
    p = plot(Piecewise((1, x > 0), (0, True)),(x,-1,1))
  File "/home/hargup/210fs/software_sources/sympy/sympy/plotting/plot.py", line 1284, in plot
    plots.show()
  File "/home/hargup/210fs/software_sources/sympy/sympy/plotting/plot.py", line 185, in show
    self._backend.show()
  File "/home/hargup/210fs/software_sources/sympy/sympy/plotting/plot.py", line 1018, in show
    self.process_series()
  File "/home/hargup/210fs/software_sources/sympy/sympy/plotting/plot.py", line 897, in process_series
    collection = self.LineCollection(s.get_segments())
  File "/home/hargup/210fs/software_sources/sympy/sympy/plotting/plot.py", line 503, in get_segments
    f_start = f(self.start)
  File "/home/hargup/210fs/software_sources/sympy/sympy/plotting/experimental_lambdify.py", line 228, in __call__
    result = self.lambda_func(args)
  File "<string>", line 1, in <lambda>
TypeError: unorderable types: complex() > int()

==================================================================== tests finished: 2 passed, 1 exceptions, in 3.54 seconds =====================================================================
DO *NOT* COMMIT!
```

**Comment by wanglongqi** [comment]
@hargup it is not so surprise the test fails `sympy` in other system. The test function has just added to the tests list. It seems the experimental `lambdify` function is even more unstable than we previous predicted.

**Comment by cbm755** [comment]
I can also reproduce the error :( That's not good...  Travis seems ok.   @hargup do you think we should revert this?  File another issue?

**Comment by cbm755** [comment]
@wanglongqi are you able to reproduce the error?    I had to modify `bin/test`, changing the first line to `#!/usr/bin/env python3`

**Comment by wanglongqi** [comment]
@cbm755 I do not have python3 installed. The issue should be existed in the experimental `lambdify` function for a quite long time. I think another issue should be filed. I agree to revert this PR, putting the test into tests will fail the tests for a while. Because it seems no one is working on `lambdify` function in the `plotting` module right now.

**Comment by toolforger** [comment]
You can install python3 via virtualenv if you don't have admin privileges on your machine.
It's straightforward on Linux, I don't know about Windows.

**Comment by wanglongqi** [comment]
@cbm755 I cannot reproduce the error on python3. Quite strange.

	$ /c/Python34/python bin/test test_plot
	============================= test process starts =============================
	executable:         c:\Python34\python.exe  (3.4.2-final-0) [CPython]
	architecture:       32-bit
	cache:              yes
	ground types:       python
	random seed:        27088119
	hash randomization: on (PYTHONHASHSEED=1698228995)

	sympy\plotting\tests\test_plot.py[3] .s.                                   [OK]
	sympy\plotting\tests\test_plot_implicit.py[1] s                            [OK]

	============ tests finished: 2 passed, 2 skipped, in 0.08 seconds =============


I can get the plot as well

	Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (In
	tel)]
	Type "copyright", "credits" or "license" for more information.
	In [4]: p = plot(Piecewise((1, x > 0), (0, True)),(x,-1,1))
	      1 |
	        |
	        |
	        |
	        |
	        |
	        |
	        |
	    0.5 | -------------------------------------------------------
	        |
	        |
	        |
	        |
	        |
	        |
	        |
	        |
	      0 | ............................
	          -1                     0                          1

**Pull request merged**
