### PR TITLE
Fixing #11801

### PR DESCRIPTION
**Pull request by Alsheh**
The code in the split_super_sub in conventions.py file assumes that that the length of the symbol is greater than 0. So I added an if statement to check for variable names that have length 0 and return the expected result.

### CODE REVIEW

**Comment by asmeurer** [comment]
Please add a test.

**Comment by Alsheh** [comment]
@asmeurer I added a test case for Symbol('').

**Comment by asmeurer** [comment]
A direct test for `pprint(Symbol(''))` would also be nice.

**Comment by asmeurer** [comment]
Otherwise +1

**Comment by Alsheh** [comment]
@asmeurer I just added a direct test case for pprint(Symbol('')).

**Pull request merged**
