### PR TITLE
Modified the _print_Piecewise method to generate correct octave code

### LINKED ISSUE #15012: Piecewise with nan gives invalid Octave/Matlab code
Consider
```
>>> f = Piecewise((42, x>7), (nan, True))
>>> f
⎧42   for x > 7
⎨              
⎩nan  otherwise
>>> octave_code(f)
'((x > 7).*(42) + (~(x > 7)).*(NaN))'
```
But this is wrong for `x = 8` because `nan*0` is `nan` rather than `0`.  Should make sure the other codegen don't have a similar problem.

Could perhaps be fixed by checking if any of the subfunctions of the `Piecewise` are `nan` and if so, printing the code differently: it may not be possible to do it with inline code.

- - - -

This is probably "easy to fix" if:
   * you're familiar with Octave or Matlab.
   * you understand the difference between `*` and `.*`.

### PR DESCRIPTION
**Pull request by czgdp1807**
Changed the settings["inline"] part of  _print_Piecewise so that the octave code generated returns correct ouput everytime

* printing
  * made changes in _print_Piecewise in octave.py so that it generates octave code which gives correct output

### CODE REVIEW

**Comment by czgdp1807** [comment]
I am unable to understand one thing. I have added only 454 to 464 lines but diff showing 38 deletions and 25 additions. What is the reason behind this? Will it affect in any way the chances of my PR being merged?
Please help.

**Comment by czgdp1807** [comment]
I have tried to update octave.py. Now it's showing print_zeta method which I haven't added. What is the reason behind this?

**Comment by asmeurer** [comment]
I would suggest rebasing if you know how (if you don't know how you can recreate the PR from scratch). I think you've somehow reverted some changes, for instance de1645b1aa9. Also, for your new commit/PR, please do the following:

- Do not put the `<!-- BEGIN RELEASE NOTES -->` in the commit message. It should only go in the PR description. Commit messages should describe what has changed in that commit. See https://github.com/sympy/sympy/wiki/Development-workflow#writing-commit-messages

- Do not put the issue number in the PR title. It should go in the description, but the title should be descriptive of the change. The title is what's used in the PR list and email notifications, and if people just see a number there that they don't know what it refers to, they are less likely to look at it.

I recommend not clearing the PR template when you create the pull request, but filling it out as is.

**Comment by czgdp1807** [comment]
I got your point. So should I close this PR and create a new one?

**Comment by czgdp1807** [comment]
@asmeurer Now I think the changes look fine.

**Comment by asmeurer** [comment]
If you don't know how to rebase I would suggest creating a new PR. We are probably going to make it so the bot will fail if the release notes block is in a commit message (https://github.com/sympy/sympy-bot/issues/27), so if you keep this PR you will need to rebase anyway to fix that commit message.

**Comment by czgdp1807** [comment]
I am closing this PR.

**Pull request closed without merging**
