### PR TITLE
CSE: properly handle MatrixSymbols

### LINKED ISSUE #11991: cse() has strange behaviour for MatrixSymbol indexing
Example: 
```python
import sympy as sp
from pprint import pprint


def sub_in_matrixsymbols(exp, matrices):
    for matrix in matrices:
        for i in range(matrix.shape[0]):
            for j in range(matrix.shape[1]):
                name = "%s_%d_%d" % (matrix.name, i, j)
                sym = sp.symbols(name)
                exp = exp.subs(sym, matrix[i, j])
    return exp


def t44(name):
    return sp.Matrix(4, 4, lambda i, j: sp.symbols('%s_%d_%d' % (name, i, j)))


# Construct matrices of symbols that work with our
# expressions. (MatrixSymbols does not.)
a = t44("a")
b = t44("b")

# Set up expression. This is a just a simple example.
e = a * b

# Put in matrixsymbols. (Gives array-input in codegen.)
e2 = sub_in_matrixsymbols(e, [sp.MatrixSymbol("a", 4, 4), sp.MatrixSymbol("b", 4, 4)])
cse_subs, cse_reduced = sp.cse(e2)
pprint((cse_subs, cse_reduced))

# Codegen, etc..
print "\nccode:"
for sym, expr in cse_subs:
    constants, not_c, c_expr = sympy.printing.ccode(
        expr,
        human=False,
        assign_to=sympy.printing.ccode(sym),
    )
    assert not constants, constants
    assert not not_c, not_c
    print "%s\n" % c_expr

```

This gives the following output:

```
([(x0, a),
  (x1, x0[0, 0]),
  (x2, b),
  (x3, x2[0, 0]),
  (x4, x0[0, 1]),
  (x5, x2[1, 0]),
  (x6, x0[0, 2]),
  (x7, x2[2, 0]),
  (x8, x0[0, 3]),
  (x9, x2[3, 0]),
  (x10, x2[0, 1]),
  (x11, x2[1, 1]),
  (x12, x2[2, 1]),
  (x13, x2[3, 1]),
  (x14, x2[0, 2]),
  (x15, x2[1, 2]),
  (x16, x2[2, 2]),
  (x17, x2[3, 2]),
  (x18, x2[0, 3]),
  (x19, x2[1, 3]),
  (x20, x2[2, 3]),
  (x21, x2[3, 3]),
  (x22, x0[1, 0]),
  (x23, x0[1, 1]),
  (x24, x0[1, 2]),
  (x25, x0[1, 3]),
  (x26, x0[2, 0]),
  (x27, x0[2, 1]),
  (x28, x0[2, 2]),
  (x29, x0[2, 3]),
  (x30, x0[3, 0]),
  (x31, x0[3, 1]),
  (x32, x0[3, 2]),
  (x33, x0[3, 3])],
 [Matrix([
[    x1*x3 + x4*x5 + x6*x7 + x8*x9,     x1*x10 + x11*x4 + x12*x6 + x13*x8,     x1*x14 + x15*x4 + x16*x6 + x17*x8,     x1*x18 + x19*x4 + x20*x6 + x21*x8],
[x22*x3 + x23*x5 + x24*x7 + x25*x9, x10*x22 + x11*x23 + x12*x24 + x13*x25, x14*x22 + x15*x23 + x16*x24 + x17*x25, x18*x22 + x19*x23 + x20*x24 + x21*x25],
[x26*x3 + x27*x5 + x28*x7 + x29*x9, x10*x26 + x11*x27 + x12*x28 + x13*x29, x14*x26 + x15*x27 + x16*x28 + x17*x29, x18*x26 + x19*x27 + x20*x28 + x21*x29],
[x3*x30 + x31*x5 + x32*x7 + x33*x9, x10*x30 + x11*x31 + x12*x32 + x13*x33, x14*x30 + x15*x31 + x16*x32 + x17*x33, x18*x30 + x19*x31 + x20*x32 + x21*x33]])])

ccode:
x0[0] = a[0];
x0[1] = a[1];
x0[2] = a[2];
x0[3] = a[3];
x0[4] = a[4];
x0[5] = a[5];
x0[6] = a[6];
x0[7] = a[7];
x0[8] = a[8];
x0[9] = a[9];
x0[10] = a[10];
x0[11] = a[11];
x0[12] = a[12];
x0[13] = a[13];
x0[14] = a[14];
x0[15] = a[15];
x1 = x0[0];
x2[0] = b[0];
x2[1] = b[1];
x2[2] = b[2];
x2[3] = b[3];
x2[4] = b[4];
x2[5] = b[5];
x2[6] = b[6];
x2[7] = b[7];
x2[8] = b[8];
x2[9] = b[9];
x2[10] = b[10];
x2[11] = b[11];
x2[12] = b[12];
x2[13] = b[13];
x2[14] = b[14];
x2[15] = b[15];
x3 = x2[0];
x4 = x0[1];
x5 = x2[4];
x6 = x0[2];
x7 = x2[8];
x8 = x0[3];
x9 = x2[12];
x10 = x2[1];
x11 = x2[5];
x12 = x2[9];
x13 = x2[13];
x14 = x2[2];
x15 = x2[6];
x16 = x2[10];
x17 = x2[14];
x18 = x2[3];
x19 = x2[7];
x20 = x2[11];
x21 = x2[15];
x22 = x0[4];
x23 = x0[5];
x24 = x0[6];
x25 = x0[7];
x26 = x0[8];
x27 = x0[9];
x28 = x0[10];
x29 = x0[11];
x30 = x0[12];
x31 = x0[13];
x32 = x0[14];
x33 = x0[15];
```

`x0` and `x2` are just copies of the matrices `a` and `b`, respectively.

### PR DESCRIPTION
**Pull request by peabody124**
Specifically treate the symbol itself and subelements as atomic instead of 
redefining them as individual variables.

fixes #11991

### CODE REVIEW

**Comment by asmeurer** [comment]
What if the index into a matrix symbol can be CSE'd? Like `A[0, i + j] + B[0, i + j]`.

**Comment by asmeurer** [comment]
This also makes me think that objects should have some way to extend themselves wrt cse(). We should think about the right API for this. We already special-case Order (it should be ignored by cse()). For MatrixElement I think we want to cse the index but not the matrix symbol.

**Comment by asmeurer** [comment]
Perhaps we should allow objects to define `cse_args` which would be used instead of `args` in `_find_repeated`. For `Order` it would return `()`. For MatrixElement it would return `self.args[1:]`. What do you think? 

CC @bjodah

**Comment by bjodah** [comment]
+1 for introducing a lookup on `.cse_args`. I also think that cse should detect repeated expressions in indices.

**Comment by peabody124** [comment]
@asmeurer I will add a test case for this when I'm home and verify. I believe that should be properly handled already as (i + j) is not going to catch that filter and should be pulled out by this

"""
if expr.is_Atom or expr.is_Order or isinstance(expr, MatrixSymbol) or isinstance(expr, MatrixElement): 
"""

**Comment by peabody124** [comment]
Ok. I looked into the matrix indices. It doesn't work before or after my change. Specifically before it doesn't appear optimization delved into the indices at all. At least for this test below, my change did improve things by avoiding a pointless definition, though.

Before:
```
In [2]: import sympy as sm
   ...: a = sm.MatrixSymbol('a',3,3)
   ...: i,j = sm.symbols('i j')
   ...: sm.cse([a[i+j,0], a[(i+j)*2,0]])
   ...: 
Out[2]: ([(x0, a)], [x0[i + j, 0], x0[2*i + 2*j, 0]])
```

After:
```
In [2]: import sympy as sm
   ...: a = sm.MatrixSymbol('a',3,3)
   ...: i,j = sm.symbols('i j')
   ...: sm.cse([a[i+j,0], a[(i+j)*2,0]])
   ...: 
Out[2]: ([], [a[i + j, 0], a[2*i + 2*j, 0]])
```

I'm not sure if changing this behavior is in the scope of this PR, although with some guidance I'd be willing to make improvements. If it is adding a whole layer of abstraction across the core objects, probably not the best place for a newbie to be playing ;-)

**Comment by asmeurer** [comment]
There must be some other issue at play there. This works

```
>>> cse([a[i+j,0], b[(i+j),0]])
([(x0, i + j)], [a[x0, 0], b[x0, 0]])
```

**Comment by asmeurer** [comment]
Actually, it occurs to me that even the first argument of a matrix element can make sense to replace, since it can be a more complicated expression like `(A*B)[0]`. The real problem here is that cse isn't recognizing that a single MatrixSymbol shouldn't be replaced (any more than a normal Symbol).

**Comment by peabody124** [comment]
hm... the current behavior is quite idiosyncratic. for example (on current HEAD)

```
In [9]: cse([a[i+j,0], b[i+j,0]])
Out[9]: ([(x0, i + j)], [a[x0, 0], b[x0, 0]])

In [10]: cse([a[i+j,0], a[(i+j)*2,0]])
Out[10]: ([(x0, a)], [x0[i + j, 0], x0[2*i + 2*j, 0]])
```

where the second one fails to improve the indexing and just is silly and renames a variable

**Comment by peabody124** [comment]
Let me know how you guys would like to go on this one. It seems like symbol substitution going into the indices was already unreliable at baseline. I'm not sure I can follow the code in tree_cse well enough to fix that component, but would be happy to try with some guidance if you'd like. I think the code generated with this change will be reliably correct if potentially missing some optimization opportunities in indices.

I also opened #13192 which seems related

**Comment by peabody124** [comment]
For what it's worth I rebased this onto next. The unit test I added still fails on the current HEAD.

**Comment by czgdp1807** [comment]
@peabody124 Are you still working on it. Please add a release notes entry in the description of this PR. Thanks for the contribution. Refer, https://github.com/sympy/sympy/wiki/Writing-Release-Notes

**Comment by asmeurer** [comment]
@smichr why did you merge this? My comment here was not addressed https://github.com/sympy/sympy/pull/13185#issuecomment-324563656.

Before this PR:

```py
>>> A = MatrixSymbol("A", n, n)
>>> B = MatrixSymbol("B", n, n)
>>> i, j = symbols('i, j')
>>> cse(A[0, i + j] + B[0, i + j])
([(x0, i + j)], [A[0, x0] + B[0, x0]])
```

After this PR:

```py
>>> A = MatrixSymbol("A", n, n)
>>> B = MatrixSymbol("B", n, n)
>>> i, j = symbols('i, j')
>>> cse(A[0, i + j] + B[0, i + j])
([], [A[0, i + j] + B[0, i + j]])
```

This clearly isn't tested, but I imagine it could have real consequences for people using cse. The previous behavior, while not ideal, is mostly harmless comparatively (it just adds more variables than necessary).

**Comment by asmeurer** [comment]
I guess this was actually merged via https://github.com/sympy/sympy/pull/22840 (explains the bot and CI issues). My comment still stands, though.

**Pull request merged**
