### PR TITLE
documentation: Explainer for rop and rel_op in core.relational docstring

### LINKED ISSUE #22674: Explain rel_op and rop values in core.relational
`rel_op` is a property of a relational. `rop` is used to instantiate a relational.

-----

Good idea to have a table of the valid values for `rop`: the documentation says "Valid values can be found in the keys of Relational.ValidRelationOperator," and I can't find "ValidRelationOperator" anywhere else in the documentation.

_Originally posted by @bertiewooster in https://github.com/sympy/sympy/discussions/22603#discussioncomment-1760085_

### PR DESCRIPTION
**Pull request by bertiewooster**
#### References to other Issues or PRs

Fixes #22674

#### Brief description of what is fixed or changed
In core.relational docstring, added table and examples of how to use `rop` (to set the relation type upon instantiation of a relational) and `rel_op` (to extract the relation type from an existing relational).

#### Release Notes

NO ENTRY

Here's a screenshot. Should code entries in tables be formatted as `code`?

Preview

### CODE REVIEW

**Comment by bertiewooster** [comment]
This is ready for review.

**Comment by bertiewooster** [comment]
Hi @oscargus could you review this explainer for rop and rel_op given your comments on discussion #22603? The docstring includes doctests. Thanks!

**Comment by oscargus** [comment]
Looks great! I totally missed it earlier. Thanks!

Will restart the tests as the naming of the require tests have changed so I cannot merge as is. But will enable auto-merge.

**Comment by bertiewooster** [comment]
Great, thanks @oscargus! The [rop and rel_op explainer is now live in the dev documentation](https://docs.sympy.org/dev/modules/core.html?#sympy.core.relational.Relational).

**Pull request merged**
