### PR TITLE
dsolve fix for 1st_exact_Integral

### PR DESCRIPTION
**Pull request by arihantparsoya**
This is fix for #11290. Prevented substitution of `y` in the expression.
#### Output before this PR:

``` python
In [15]: dsolve(cos(f(x)) - (x*sin(f(x)) - f(x)**2)*f(x).diff(x), f(x), simplify=False, hint='1st_exact_Integral')
Out[15]:
f(x)
 ⌠
 ⎮   ⎛ 2              ⌠           ⎞      ⌠
 ⎮   ⎜y  - x⋅sin(y) - ⎮ -sin(y) dx⎟ dy + ⎮ cos(f(x)) dx = C₁
 ⎮   ⎝                ⌡           ⎠      ⌡
 ⌡


In [16]: dsolve(cos(f(x)) - (x*sin(f(x)) - f(x)**2)*f(x).diff(x), f(x), simplify=False, hint='1st_exact_Integral').doit()
Out[16]:
 3
f (x)   ⌠
───── + ⎮ cos(f(x)) dx = C₁
  3     ⌡
```
#### Output after this PR:

``` python
>>> from sympy import Function, dsolve, cos, sin
>>> from sympy.abc import x
>>> f = Function('f')
>>> pprint(dsolve(cos(f(x)) - (x*sin(f(x)) - f(x)**2)*f(x).diff(x), f(x), simplify=False, hint='1st_exact_Integral'))
⌠                                                     
⎮ ⎛ 2              ⌠           ⎞      ⌠               
⎮ ⎜y  - x⋅sin(y) - ⎮ -sin(y) dx⎟ dy + ⎮ cos(y) dx = C₁
⎮ ⎝                ⌡           ⎠      ⌡               
⌡                                                     
>>> pprint(dsolve(cos(f(x)) - (x*sin(f(x)) - f(x)**2)*f(x).diff(x), f(x), simplify=False, hint='1st_exact_Integral').doit())
 3                
y                 
── + x⋅cos(y) = C₁
3                 
```

### CODE REVIEW

**Comment by parsoyaarihant** [comment]
@asmeurer , can you review this?

**Comment by asmeurer** [comment]
The final output should use f(x), not y.

**Comment by parsoyaarihant** [comment]
@asmeurer , based on the chat on gitter, how can the final answer be `Integral(cos(f(x)), x)`?

**Review by certik — CHANGES_REQUESTED** [review]
Looks like this requires some changes.

**Pull request closed without merging**
