### PR TITLE
missing print brackets

### LINKED ISSUE #19434: Sympy contains calls to print without parentheses
Found while investigating something else.

There are bits of code like:

https://github.com/sympy/sympy/blob/4e53a868e8d3b0e5bf241dca9df61c4ce2c339dd/sympy/utilities/iterables.py#L423-L426

and

https://github.com/sympy/sympy/blob/4e53a868e8d3b0e5bf241dca9df61c4ce2c339dd/examples/advanced/pidigits.py#L24-L26

and

https://github.com/sympy/sympy/blob/4e53a868e8d3b0e5bf241dca9df61c4ce2c339dd/sympy/interactive/printing.py#L243-L249

Which presumably were missed in a python 2 -> python 3 conversion, and should instead say `print()`.

### PR DESCRIPTION
**Pull request by sidhu1012**
Missing print  bracekts solved
#### References to other Issues or PRs

fixes #19434 
#### Brief description of what is fixed or changed
Sympy contained calls to print without parentheses, placed missing parenthesis.

#### Other comments
print --> print()

#### Release Notes

NO ENTRY

### CODE REVIEW

**Review by eric-wieser — DISMISSED** [review]
Looks good, thanks

**Review by namannimmo10 — APPROVED** [review]
LGTM!

**Comment by eric-wieser** [comment]
@sidhu, your second commit looks like a good idea, but it would make more sense in a separate PR. At present, this PR has grown by a factor of almost 1000.

**Comment by sidhu1012** [comment]
new PR sent by mistake , correcting it

**Comment by czgdp1807** [comment]
Closing in favour of https://github.com/sympy/sympy/pull/20009

**Pull request closed without merging**
