### PR TITLE
Don't merge: demonstration of -q flag in .travis.yml

### PR DESCRIPTION
**Pull request by supreet11agrawal**
#### References to other Issues or PRs

Checks #16154 
Checks #16097 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
Please test an invalid escape in a string as well.

**Comment by asmeurer** [comment]
Oh I didn't see the comment on the other PR. I'm not clear where that commit comes from but it looks correct.

**Comment by supreet11agrawal** [comment]
@asmeurer from here https://github.com/sympy/sympy/pull/16156/commits/15f536e6caf56522e0d1557520e83ecd5f899d99.
I can delete this branch now. Right?

**Comment by oscarbenjamin** [comment]
Yeah this has served its purpose.

**Pull request closed without merging**
