### PR TITLE
Added \overline in LaTeX.

### PR DESCRIPTION
**Pull request by costika1234**
#### Brief description of what is fixed or changed
Extended the LaTeX parser with support for `\overline` to help evaluate complex conjugates.

#### Other comments
I wrote a couple of tests in `parsing/tests/test_latex.py`, but had to use raw strings because otherwise the command checking code quality, i.e. 
```
python -We:invalid -We::SyntaxWarning -m compileall -f -q sympy/
``` 
gives the following `SyntaxError: invalid escape sequence \o` when using `\\overline` within double quotes. 

Changing `"\\overline"` to `r"\overline"` silenced the error; however, this comes at the expense of breaking consistency within that test file. 

#### Release Notes

* parsing
  * Extended the LaTeX parser with support for complex conjugates (via `\overline{...}`).

### CODE REVIEW

**Comment by asmeurer** [comment]
The double quotes should work just fine. Are you sure you used double quotes in every instance?

Either way, raw strings are better. We really should be using raw strings for all those tests. The only reason to not use a raw string in the presence of backslashes is if you need to also include an escaped literal in the string, like a newline.

**Comment by asmeurer** [comment]
I didn't realize the latex parser creates expressions with evaluate=False. That makes sense, but there should perhaps be a flag to disable it.

**Comment by costika1234** [comment]
> The double quotes should work just fine. Are you sure you used double quotes in every instance?
> 
> Either way, raw strings are better. We really should be using raw strings for all those tests. The only reason to not use a raw string in the presence of backslashes is if you need to also include an escaped literal in the string, like a newline.

Ah, I think I must have written `\overline` instead of `\\overline` within those double quotes. Just tried with double quotes again and it works fine. That being said, I will create a different PR to replace those strings with raw strings since it's highly unlikely that we would have newlines in any of those test cases.

**Comment by asmeurer** [comment]
BTW, I don't know why I didn't notice this, but \ is called a backslash, not a quote (quotes are ' and ").

**Comment by costika1234** [comment]
Ah, yes, you meant double backslashes instead of double quotes in one of the sentences above. I've just naturally parsed that the way you intended :-). 

On the other hand, I am not sure if we want to replace all strings in that test file with raw strings given that there are a number of them which don't have any LaTeX commands. So would it be okay to leave `"1"` as it is and change strings like `"\\frac{1}{2}"` to `r"\frac{1}{2}"`? Or should we replace everything with `r"..."` for consistency?

I've also had a look at https://github.com/sympy/sympy/blob/master/sympy/printing/tests/test_latex.py and most strings that have LaTeX commands are raw, but sometimes I've seen `r'...'` instead of `r"..."`. Would you instead like to have double quotes everywhere (at least for raw strings)? The reason I ask is because I've seen strings within single quotes when passed as arguments to functions, but this isn't always the case, e.g. https://github.com/sympy/sympy/blob/6823a8a9b837e5b611b75a917d2f0e8728d7c9da/sympy/printing/tests/test_latex.py#L1333. 

What would be a good rule of thumb to follow throughout this project?

**Comment by asmeurer** [comment]
It's fine to use raw strings everywhere, even if they don't have backslashes. That makes things more uniform and easier to avoid mistakes if a backslash is added later. 

Double vs. single quotes doesn't matter. We don't really have a consistent style. They're both equivalent so it doesn't really matter.

**Pull request merged**
