### PR TITLE
lts.1 piecewise_fold, Relational.canonical and Piecewise instantiation modifications

### PR DESCRIPTION
**Pull request by smichr**
I am presenting some of the foundational modifications to Piecewise that are implemented fully with other modifications in #12587 with hopes of doing this more incrementally. There, there are about 2000 lines added and 600 removed; here we have about +500 - 200.

Many issues are solved with that PR along with the continuous indefinite integration of Piecewise functions. The issues aren't few and they are significant -- Piecewise integration and folding is broken except for some limited cases. Making things work has not been trivial: as @zanzibar7 commented in #10137, "resolving arbitrary conditionals is hard." I have appreciated @jksuom's input on this problem. I welcome input from anyone else that has an interest in seeing functionality for discontinuous functions improved.

**changes introduced**

- the canonical method for Relationals now avoids an infinite loop and a private `_canonical` function has been added
- Piecewise.eval is more sensitive to repeat/redundant conditionals and is more likely to give an unconditional "True" condition last if all reals are covered by the conditions of the pieces, e.g. `Piecewise((1, x < 1), (2, x >= 1)) --> Piecewise((1, x < 1), (2, True))`. I don't believe there is any loss in integrity wrt x being imaginary by replacing the last condition with True (which is independent of x) since in order to "cover all reals" there has to be some sort of preceding relationship involving "<" or ">" before the True condition and that/those preceding relationships would raise an error if x were not real.
- issues with `piecewise_fold` should be resolved and a Piecewise result is always returned (there is no longer a reduction of some expressions to a logical expression -- that should probably be handled as a rewriting request
- a new method `piecewise_integrate` aims to be the replacement for the current `_eval_interval` which gives a discontinuous indefinite integral: the *pieces* of the function are integrated independently of one another; in the future, the `integrate` method (which calls `_eval_integral`) will give a continuous result. This also necessesitates a better handling of Piecewise functions in `integrals.py` so the Piecewise is not passed off to `meijerg` methods: only the *pieces* should be thus integrated *and* they should know what hints should be used. The full changes of `_eval_integral` are part of #12587 but are not included here.
- solvers had to be modified to better handle Piecewise results, giving a list when possible, else a Piecewise containing lists as arguments.

### CODE REVIEW

**Comment by smichr** [comment]
@asmeur can we get this in for the release? It doesn't fix everything but ppl will have a better chance of doing things right with this.

**Comment by asmeurer** [comment]
You somehow inserted nonbreaking spaces instead of real spaces in a file, causing a syntax error (see https://stackoverflow.com/questions/2774471/what-is-c2-a0-in-mime-encoded-quoted-printable-text).

**Comment by asmeurer** [comment]
> Piecewise.eval is more sensitive to repeat/redundant conditionals and is more likely to give an unconditional "True" condition last if all reals are covered by the conditions of the pieces, e.g. Piecewise((1, x < 1), (2, x >= 1)) --> Piecewise((1, x < 1), (2, True)).

Unsure about this. Wouldn't they be different if `x` is imaginary? How about instead of `eval`, putting that in some simplification function that assumes the variables are real (which can be applied during definite integration on a real interval).

**Comment by asmeurer** [comment]
Did you intent to push the `lts1.patch` branch to sympy/sympy?

**Comment by smichr** [comment]
> Did you intent to push

totally did not. I (again) thought I was editing the branch online. It was different, in that I was trying to resolve a merge conflict rather than just editing a file. The latter has been pretty clear (git-wise) in letting me know where the edit is going. So what went in?? I'll start checking. Perhaps the best thing is to just revert it?

**Comment by smichr** [comment]
Perusing master, I don't see it there. Did it just go as a PR somewhere? Please tell me what you are seeing and where.

**Comment by smichr** [comment]
> Wouldn't they be different if x is imaginary?

I though about this. As long as there is relational, it will discriminate against imaginary arguments. So having a True (where no such check is performed) won't matter (AFAICT) because to get to the True all the preceding relationals had to be checked.

**Comment by smichr** [comment]
@asmeurer, if you can provide any more details on what I might have done wrong, please drop me an email. I am closing this to make smaller incremental steps towards getting the piecewise working.

**Pull request closed without merging**
