### PR TITLE
Fix Integer and StdFactKB memory leak with patch from #9294

### LINKED ISSUE #9292: Why do integers have their own cache?
I just noticed that `Integer` has its own cache, which is separate from the main cache https://github.com/sympy/sympy/blob/01400b0616f257ca7cfbba7b26a7b6305d1acb8d/sympy/core/numbers.py#L1670-L1679. Why is this here? https://github.com/sympy/sympy/commit/be7f58bfab412743ffdff170ea7b099504e5dd6f suggests it was initially done for speed purposes. We have a new cache now, so we should reevaluate. The new cache is also LRU, whereas this cache can grow unbounded. Also, this cache isn't disabled when the main cache is. It's possible this is fine (I haven't heard any complaints about it), but we should at least check what happens if we use the normal cache. 

Worth noting that some places in the code do `is` comparison against Integer objects, so if this is changed, we will have to check those code paths.

### LINKED ISSUE #15778: Integer and StdFactKB memory leak
There is a memory leak in the Integer class. The internal ```_intcache``` caching dictionary does not have any size limitation and an instance of ```Integer``` and ```StdFactKB``` is kept for each integer that is ever used.

The following script reproduces the issue: a simple 100k "do-nothing" loop that takes around 350 Mb of memory.

```python3
import os
os.environ['SYMPY_USE_CACHE'] = 'no'

from sympy.parsing.sympy_parser import parse_expr

import gc
import objgraph

for i in range(100000):
    parse_expr('log({})'.format(i), local_dict=dict(), evaluate=False)

gc.collect()

print(objgraph.show_most_common_types(limit=10))
```

(the ```objgraph``` module is available at https://mg.pov.lt/objgraph/)

The script reports the following object usage:
```
dict      204547
StdFactKB 200468
Integer   199996
function  14659
tuple     4547
None
```

It seems that this issue can be resolved through https://github.com/sympy/sympy/pull/9294.

### PR DESCRIPTION
**Pull request by NoumbissiValere**
#### References to other Issues or PRs

Fixes #15778 
Fixes #9292

#### Brief description of what is fixed or changed
The unbounded and adhoc cache infrastructure (_intcache) was replaced with lru_cache in numbers.py.
Inline with this, the test_integer_cache was removed from test_numbers.py   

#### Release Notes

* core 
  * Removed special cache for integers and used standard cache.

### CODE REVIEW

**Comment by asmeurer** [comment]
Please fill out the template in the pull request description.

**Comment by NoumbissiValere** [comment]
@asmeurer  i have updated the template.
Is there anything to update again?

**Comment by iblanes** [comment]
@NoumbissiValere would you mind adding an empty commit to your pull request to fix the build issue? Something along the lines of ```git commit --allow-empty -m "Trigger Travis-CI rebuild"```. Thanks.

**Comment by oscargus** [comment]
Looks good as far as I can tell. Good that you @NoumbissiValere based in on the earlier PR. As it involves a bit a git hassle, it is far too common that one just use the easier "copy-and-paste"-methodology.

What do you say @moorepants ? Is there something from #9294 still to be done to verify the (positive) impact? Seems like it would be nice to get this in if there are no obvious drawbacks.

Maybe one should try and run the example code from #15778 and see what it shows now? Would that be possible for you @NoumbissiValere ?

**Comment by oscargus** [comment]
The requested results from #15778 I just found in #15801 so that looks fine from a memory perspective.

**Comment by oscarbenjamin** [comment]
I just tried this PR and I was able to reproduce the objgraph results from #15801 so it looks like it solves the memory issue from #15778.

I also ran the whole non-slow test suite and got:
master: 1841 secs
this PR: 1665 secs
master with this PR merged in: 1811 secs

So it looks like this PR offers a 30 secs speedup over master but that might just be noise.

Also looks like there was a significant slowdown on master between the base of this branch and current tip...

**Comment by oscargus** [comment]
It may, at least to some extent, be that there are simply more tests now. Some non-slow tests were far from non-slow so if any of those are added since... But probably not the whole explanation.

Possible speed-up and fixed memory leak sounds good though.

**Comment by oscarbenjamin** [comment]
@NoumbissiValere sorry it has taken so long to merge this. I wasn't familiar with SymPy's caching code. I've taken a bit of a look at that and this and the related issues and this looks good to me.

I will merge this soon (just waiting until there isn't a build queue on Travis).

**Pull request merged**
