### PR TITLE
Debugging messages added for manualintegrate

### LINKED ISSUE #13987: Add debugging messages to manualintegrate
Some of the more complex algorithms in SymPy, such as Gruntz for limits and Meijer G for integrals, issue debugging messages. Examples from meijergint: 
```
from sympy.utilities.misc import debug
debug('Integrating', f, 'wrt %s from %s to %s.' % (x, a, b))
debug('Trying recursive Mellin transform method.')
debug('Try rewriting hyperbolics in terms of exp.')
```
These are shown if one uses `export SYMPY_DEBUG=True` before starting Python. I found them helpful in tracing integration issues, and I guess it's not just me.

I propose that manualintegrate.py should also issue `debug` messages when it attempts some transformation rule. It could be a message like 
```
debug("Trying to integrate {} by using {}".format(function, rule))
```
This way, when integration does something strange or goes into an infinite loop, we'll know where the problem is without tracing the different integration routines.

### PR DESCRIPTION
**Pull request by ghost**
#### References to other Issues or PRs

Fixes #13987

#### Brief description of what is fixed or changed
Debugging messages added for manualintegrate.py

### CODE REVIEW

**Comment by normalhuman** [comment]
I tried it on the example `integrate((1-cos(x))/x, x)` which hangs in manual integrate module. As expected, the debug messages were an infinite stream of 
```
using TrigRule(func='cos', arg=x, context=cos(x), symbol=x)
using TrigRule(func='sin', arg=x, context=sin(x), symbol=x)
```
This is somewhat opaque, unfortunately. Can you tell from here what the function was when the rule tried to transform it, and what it became? Further study of manualintegrate logic seems necessary.

**Comment by czgdp1807** [comment]
@abhayjindal51 Are you still interested to work on it?

**Comment by kenluck2001** [comment]
> I tried it on the example `integrate((1-cos(x))/x, x)` which hangs in manual integrate module. As expected, the debug messages were an infinite stream of
> 
> ```
> using TrigRule(func='cos', arg=x, context=cos(x), symbol=x)
> using TrigRule(func='sin', arg=x, context=sin(x), symbol=x)
> ```
> 
> This is somewhat opaque, unfortunately. Can you tell from here what the function was when the rule tried to transform it, and what it became? Further study of manualintegrate logic seems necessary.

Getting the logs on a looping process is the issue. It is harder to detect if a process is hung by loop, even observing CPU usage is not reliable metric. Detecting if the process is dead can be done using signals with are OS dependent. Is it a requirement to print at least stack trace on a hung process (infinite) loop @normalhuman @czgdp1807 I will thinking of completing this PR but want to verify the expectation. Are OS (linux specifc) dependent codes allowed in the sympy or cross-platform support is always guaranteed for every PR.

**Comment by oscarbenjamin** [comment]
> Are OS (linux specifc) dependent codes allowed in the sympy

Generally not but there's nothing to stop you adding something while debugging on your own computer.

In this case I can debug this just by checking out this PR, running the code and interrupting with Ctrl-C. I get the following stacktrace:
```python
>>> integrate((1-cos(x))/x, x) 
/Users/enojb/current/sympy/sympy/sympy/core/function.py:1241: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(v, (collections.Iterable, Tuple, MatrixCommon, NDimArray)):
^CTraceback (most recent call last):
  File "/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py", line 244, in getit
    return self._assumptions[fact]
KeyError: 'negative'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 1352, in integrate
    risch=risch, manual=manual)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 527, in doit
    function, xab[0], **eval_kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 975, in _eval_integral
    result = manualintegrate(g, x)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 1251, in manualintegrate
    return _manualintegrate(integral_steps(f, var))
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 1038, in integral_steps
    fallback_rule)(integral)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 65, in null_safe_rl
    result = rule(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 216, in _alternatives
    result = rule(integral)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 33, in conditioned_rl
    return rule(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 180, in _rewriter
    substep = integral_steps(rewritten, symbol)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 1038, in integral_steps
    fallback_rule)(integral)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 65, in null_safe_rl
    result = rule(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 95, in switch_rl
    return rl(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 65, in null_safe_rl
    result = rule(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 337, in mul_rule
    next_step = integral_steps(f, symbol)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 1038, in integral_steps
    fallback_rule)(integral)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 65, in null_safe_rl
    result = rule(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 216, in _alternatives
    result = rule(integral)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 33, in conditioned_rl
    return rule(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 180, in _rewriter
    substep = integral_steps(rewritten, symbol)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 1038, in integral_steps
    fallback_rule)(integral)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 65, in null_safe_rl
    result = rule(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 95, in switch_rl
    return rl(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 328, in add_rule
    for g in integrand.as_ordered_terms()]
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 328, in <listcomp>
    for g in integrand.as_ordered_terms()]
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 1038, in integral_steps
    fallback_rule)(integral)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 65, in null_safe_rl
    result = rule(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 216, in _alternatives
    result = rule(integral)
  File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 33, in conditioned_rl
    return rule(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 418, in parts_rule
    if (integrand / (v * du)).cancel() == 1:
  File "/Users/enojb/current/sympy/sympy/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/Users/enojb/current/sympy/sympy/sympy/core/decorators.py", line 132, in binary_op_wrapper
    return func(self, other)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 177, in __div__
    return Mul(self, Pow(other, S.NegativeOne))
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/power.py", line 286, in __new__
    obj = b._eval_power(e)
  File "/Users/enojb/current/sympy/sympy/sympy/core/mul.py", line 634, in _eval_power
    return Mul(*[Pow(b, e, evaluate=False) for b in cargs]) * \
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/operations.py", line 42, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "/Users/enojb/current/sympy/sympy/sympy/core/mul.py", line 308, in flatten
    coeff *= Pow(b, e)  # it is an unevaluated power
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/power.py", line 261, in __new__
    e.is_integer and _coeff_isneg(b):
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 84, in _coeff_isneg
    return a.is_Number and a.is_negative
  File "/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py", line 248, in getit
    return _ask(fact, self)
  File "/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py", line 291, in _ask
    a = evaluate(obj)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 791, in _eval_is_negative
    n, i = self.evalf(2).as_real_imag()
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 1751, in as_real_imag
    return (re(self), im(self))
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 423, in __new__
    if n not in cls.nargs:
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 219, in nargs
    return FiniteSet(*self._nargs) if self._nargs else S.Naturals0
  File "/Users/enojb/current/sympy/sympy/sympy/sets/sets.py", line 1909, in __new__
    args = list(ordered(frozenset(tuple(args)), Set._infimum_key))
  File "/Users/enojb/current/sympy/sympy/sympy/core/compatibility.py", line 630, in ordered
    d.pop(k)
  File "/Users/enojb/current/sympy/sympy/sympy/core/numbers.py", line 2849, in __hash__
    return super(Infinity, self).__hash__()
  File "/Users/enojb/current/sympy/sympy/sympy/core/numbers.py", line 728, in __hash__
    return super(Number, self).__hash__()
KeyboardInterrupt
```
Interestingly running the same again immediately after gives the result:
```python
>>> integrate((1-cos(x))/x, x)
2*log(x) - log(x**2)/2 - Ci(x)
>>> _.diff(x)
-cos(x)/x + 1/x
```
Starting a new Python process it hangs again and I get a new stacktrace which matches the one above down to the line:
```
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 418, in parts_rule
```
So I guess that's where it hangs. Indeed there is a potentially infinite loop there:
https://github.com/sympy/sympy/blob/cf80dffb31f156b35dfe39e2bc23edb8e2704e1b/sympy/integrals/manualintegrate.py#L417-L439

Making this change allows me to see the problem:
```diff
diff --git a/sympy/integrals/manualintegrate.py b/sympy/integrals/manualintegrate.py
index 5064bb6b05..d41840ee64 100644
--- a/sympy/integrals/manualintegrate.py
+++ b/sympy/integrals/manualintegrate.py
@@ -415,6 +415,7 @@ def parts_rule(integral):
             return
 
         while True:
+            print(integrand, v, du)
             if (integrand / (v * du)).cancel() == 1:
                 break
             if symbol not in (integrand / (v * du)).cancel().free_symbols:
```
Output:
```python
>>> integrate((1-cos(x))/x, x)
cos(x)/x sin(x) -1/x**2
cos(x)/x -cos(x) 2/x**3
cos(x)/x sin(x) 6/x**4
cos(x)/x -cos(x) -24/x**5
cos(x)/x sin(x) -120/x**6
cos(x)/x -cos(x) 720/x**7
cos(x)/x sin(x) 5040/x**8
cos(x)/x -cos(x) -40320/x**9
cos(x)/x sin(x) -362880/x**10
cos(x)/x -cos(x) 3628800/x**11
cos(x)/x sin(x) 39916800/x**12
cos(x)/x -cos(x) -479001600/x**13
cos(x)/x sin(x) -6227020800/x**14
cos(x)/x -cos(x) 87178291200/x**15
cos(x)/x sin(x) 1307674368000/x**16
cos(x)/x -cos(x) -20922789888000/x**17
cos(x)/x sin(x) -355687428096000/x**18
cos(x)/x -cos(x) 6402373705728000/x**19
cos(x)/x sin(x) 121645100408832000/x**20
cos(x)/x -cos(x) -2432902008176640000/x**21
cos(x)/x sin(x) -51090942171709440000/x**22
...
```
Now it's fairly obvious what is going wrong. What is needed is some way for the debug output to show that.

**Comment by kenluck2001** [comment]
> > Are OS (linux specifc) dependent codes allowed in the sympy
> 
> Generally not but there's nothing to stop you adding something while debugging on your own computer.
> 
> In this case I can debug this just by checking out this PR, running the code and interrupting with Ctrl-C. I get the following stacktrace:
> 
> ```python
> >>> integrate((1-cos(x))/x, x) 
> /Users/enojb/current/sympy/sympy/sympy/core/function.py:1241: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
>   if isinstance(v, (collections.Iterable, Tuple, MatrixCommon, NDimArray)):
> ^CTraceback (most recent call last):
>   File "/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py", line 244, in getit
>     return self._assumptions[fact]
> KeyError: 'negative'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 1352, in integrate
>     risch=risch, manual=manual)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 527, in doit
>     function, xab[0], **eval_kwargs)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 975, in _eval_integral
>     result = manualintegrate(g, x)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 1251, in manualintegrate
>     return _manualintegrate(integral_steps(f, var))
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 1038, in integral_steps
>     fallback_rule)(integral)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
>     result = rl(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
>     result = rl(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 65, in null_safe_rl
>     result = rule(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 216, in _alternatives
>     result = rule(integral)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 33, in conditioned_rl
>     return rule(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 180, in _rewriter
>     substep = integral_steps(rewritten, symbol)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 1038, in integral_steps
>     fallback_rule)(integral)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
>     result = rl(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 65, in null_safe_rl
>     result = rule(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 95, in switch_rl
>     return rl(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
>     result = rl(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 65, in null_safe_rl
>     result = rule(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 337, in mul_rule
>     next_step = integral_steps(f, symbol)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 1038, in integral_steps
>     fallback_rule)(integral)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
>     result = rl(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
>     result = rl(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 65, in null_safe_rl
>     result = rule(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 216, in _alternatives
>     result = rule(integral)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 33, in conditioned_rl
>     return rule(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 180, in _rewriter
>     substep = integral_steps(rewritten, symbol)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 1038, in integral_steps
>     fallback_rule)(integral)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
>     result = rl(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 65, in null_safe_rl
>     result = rule(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 95, in switch_rl
>     return rl(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 328, in add_rule
>     for g in integrand.as_ordered_terms()]
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 328, in <listcomp>
>     for g in integrand.as_ordered_terms()]
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 1038, in integral_steps
>     fallback_rule)(integral)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
>     result = rl(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 85, in do_one_rl
>     result = rl(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 65, in null_safe_rl
>     result = rule(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 216, in _alternatives
>     result = rule(integral)
>   File "/Users/enojb/current/sympy/sympy/sympy/strategies/core.py", line 33, in conditioned_rl
>     return rule(expr)
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 418, in parts_rule
>     if (integrand / (v * du)).cancel() == 1:
>   File "/Users/enojb/current/sympy/sympy/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
>     return func(a, b)
>   File "/Users/enojb/current/sympy/sympy/sympy/core/decorators.py", line 132, in binary_op_wrapper
>     return func(self, other)
>   File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 177, in __div__
>     return Mul(self, Pow(other, S.NegativeOne))
>   File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 93, in wrapper
>     retval = cfunc(*args, **kwargs)
>   File "/Users/enojb/current/sympy/sympy/sympy/core/power.py", line 286, in __new__
>     obj = b._eval_power(e)
>   File "/Users/enojb/current/sympy/sympy/sympy/core/mul.py", line 634, in _eval_power
>     return Mul(*[Pow(b, e, evaluate=False) for b in cargs]) * \
>   File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 93, in wrapper
>     retval = cfunc(*args, **kwargs)
>   File "/Users/enojb/current/sympy/sympy/sympy/core/operations.py", line 42, in __new__
>     c_part, nc_part, order_symbols = cls.flatten(args)
>   File "/Users/enojb/current/sympy/sympy/sympy/core/mul.py", line 308, in flatten
>     coeff *= Pow(b, e)  # it is an unevaluated power
>   File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 93, in wrapper
>     retval = cfunc(*args, **kwargs)
>   File "/Users/enojb/current/sympy/sympy/sympy/core/power.py", line 261, in __new__
>     e.is_integer and _coeff_isneg(b):
>   File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 84, in _coeff_isneg
>     return a.is_Number and a.is_negative
>   File "/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py", line 248, in getit
>     return _ask(fact, self)
>   File "/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py", line 291, in _ask
>     a = evaluate(obj)
>   File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 791, in _eval_is_negative
>     n, i = self.evalf(2).as_real_imag()
>   File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 1751, in as_real_imag
>     return (re(self), im(self))
>   File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 93, in wrapper
>     retval = cfunc(*args, **kwargs)
>   File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 423, in __new__
>     if n not in cls.nargs:
>   File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 219, in nargs
>     return FiniteSet(*self._nargs) if self._nargs else S.Naturals0
>   File "/Users/enojb/current/sympy/sympy/sympy/sets/sets.py", line 1909, in __new__
>     args = list(ordered(frozenset(tuple(args)), Set._infimum_key))
>   File "/Users/enojb/current/sympy/sympy/sympy/core/compatibility.py", line 630, in ordered
>     d.pop(k)
>   File "/Users/enojb/current/sympy/sympy/sympy/core/numbers.py", line 2849, in __hash__
>     return super(Infinity, self).__hash__()
>   File "/Users/enojb/current/sympy/sympy/sympy/core/numbers.py", line 728, in __hash__
>     return super(Number, self).__hash__()
> KeyboardInterrupt
> ```
> 
> Interestingly running the same again immediately after gives the result:
> 
> ```python
> >>> integrate((1-cos(x))/x, x)
> 2*log(x) - log(x**2)/2 - Ci(x)
> >>> _.diff(x)
> -cos(x)/x + 1/x
> ```
> 
> Starting a new Python process it hangs again and I get a new stacktrace which matches the one above down to the line:
> 
> ```
>   File "/Users/enojb/current/sympy/sympy/sympy/integrals/manualintegrate.py", line 418, in parts_rule
> ```
> 
> So I guess that's where it hangs. Indeed there is a potentially infinite loop there:
> 
> https://github.com/sympy/sympy/blob/cf80dffb31f156b35dfe39e2bc23edb8e2704e1b/sympy/integrals/manualintegrate.py#L417-L439
> 
> Making this change allows me to see the problem:
> 
> ```diff
> diff --git a/sympy/integrals/manualintegrate.py b/sympy/integrals/manualintegrate.py
> index 5064bb6b05..d41840ee64 100644
> --- a/sympy/integrals/manualintegrate.py
> +++ b/sympy/integrals/manualintegrate.py
> @@ -415,6 +415,7 @@ def parts_rule(integral):
>              return
>  
>          while True:
> +            print(integrand, v, du)
>              if (integrand / (v * du)).cancel() == 1:
>                  break
>              if symbol not in (integrand / (v * du)).cancel().free_symbols:
> ```
> 
> Output:
> 
> ```python
> >>> integrate((1-cos(x))/x, x)
> cos(x)/x sin(x) -1/x**2
> cos(x)/x -cos(x) 2/x**3
> cos(x)/x sin(x) 6/x**4
> cos(x)/x -cos(x) -24/x**5
> cos(x)/x sin(x) -120/x**6
> cos(x)/x -cos(x) 720/x**7
> cos(x)/x sin(x) 5040/x**8
> cos(x)/x -cos(x) -40320/x**9
> cos(x)/x sin(x) -362880/x**10
> cos(x)/x -cos(x) 3628800/x**11
> cos(x)/x sin(x) 39916800/x**12
> cos(x)/x -cos(x) -479001600/x**13
> cos(x)/x sin(x) -6227020800/x**14
> cos(x)/x -cos(x) 87178291200/x**15
> cos(x)/x sin(x) 1307674368000/x**16
> cos(x)/x -cos(x) -20922789888000/x**17
> cos(x)/x sin(x) -355687428096000/x**18
> cos(x)/x -cos(x) 6402373705728000/x**19
> cos(x)/x sin(x) 121645100408832000/x**20
> cos(x)/x -cos(x) -2432902008176640000/x**21
> cos(x)/x sin(x) -51090942171709440000/x**22
> ...
> ```
> 
> Now it's fairly obvious what is going wrong. What is needed is some way for the debug output to show that.

Thanks so much. I am debugging to find the best positions in the code for debugging. PR will be updated in a few days. I am grateful @oscarbenjamin

**Pull request closed without merging**
