### PR TITLE
Define subfactorial for noninteger args

### LINKED ISSUE #8730: Limit of subfactorial
Despite the fact that `subfactorial` is defined over nonnegative integers only, it still has a limit at `oo`, which is `oo`. So I'd expect `limit(subfactorial(n), n, oo)` to work (and return `oo`), but that insted raises a `ValueError`. I am not sure how to solve that.

### PR DESCRIPTION
**Pull request by skirpichev**
fixes #8730

### CODE REVIEW

**Comment by pelegm** [comment]
Perhaps merge #8726 and then rebase upon it?

**Comment by pelegm** [comment]
Also see #8728, which is about another factorial function which may be, perhaps, extended to complex numbers (but it might be more difficult there).

**Comment by skirpichev** [comment]
> Perhaps merge #8726 and then rebase upon it?

If we are going to merge this, I would see #8726 be fixed first, just like "is_integer" helper here.

**Comment by pelegm** [comment]
I see what you mean. Sure, I'll fix that.

**Comment by skirpichev** [comment]
#8726 is not fixed yet.  Lets merge this first.

**Comment by pelegm** [comment]
Sure. I'll fix #8726 on top of this.

**Pull request merged**
