### PR TITLE
Travis: Remove deprecated pip list format 'legacy'

### PR DESCRIPTION
**Pull request by jksuom**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
I guess we can remove that uninstall line. Maybe we should run the no-setuptools test in a separate virtualenv.

**Comment by asmeurer** [comment]
Either way let's get this merged soon as it fixes the Travis issues.

**Comment by jksuom** [comment]
I am not sure of how the setup test is supposed to work. Removing the uninstall line suits fine to me.

**Comment by asmeurer** [comment]
Let's merge this now. I'll see if I can get a version that runs this in a separate environment.

**Pull request merged**
