### PR TITLE
nonlinsolve documentation

### PR DESCRIPTION
**Pull request by Shekharrajak**
- [x]  `nonlinsolve` examples added in `doc/src/tutorial/solvers.rst`

### CODE REVIEW

**Comment by Shekharrajak** [comment]
Ping @sympy/sympy-solvers . I don't know why [this error](https://travis-ci.org/sympy/sympy/jobs/153659191#L4156) is coming in the build. I didn't change anything in line [199](https://github.com/sympy/sympy/pull/11532/commits/0b0a2ae8ea4822fdfd98d3ad2fa5ea574b8e850e#diff-5b15c06e5d2b69438b57c687cf1ce3ddR199)

**Comment by aktech** [comment]
I have restarted the build, lets see if it happens again.

**Comment by Shekharrajak** [comment]
Thanks @aktech

**Comment by Shekharrajak** [comment]
@aktech , I don't understand why this error is coming : https://travis-ci.org/sympy/sympy/jobs/153980079#L4291 .  Please have a look.

**Comment by jksuom** [comment]
It seems that `Returns` in the docstring of `nonlinsolve` does not follow the guidelines in https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

**Comment by gxyd** [comment]
We should have something similar in SymPy as well, that seems helpful.

**Comment by Shekharrajak** [comment]
Thanks @jksuom . But I saw somewhere that type of `Returns` docstring.
Is there any way to test `.rst` file ?

**Comment by Shekharrajak** [comment]
Thanks @jksuom @gxyd , there was a problem in `solveset.py/nonlinsolve` docstring bullet listing. Now its fine.

**Comment by Shekharrajak** [comment]
Ping @aktech

**Comment by aktech** [comment]
Looks good.

**Pull request merged**
