### PR TITLE
Inclusion of evalf function in sympy/physics/vector/vector

### LINKED ISSUE #18064: Add .evalf() method to sympy.physics.vector.Vector and Dyadic
These two classes are missing many of the core SymPy methods because they do not inherit from the core SymPy classes. It would be nice to add them, starting with `.evalf()`.

### PR DESCRIPTION
**Pull request by Saanidhyavats**
#### References to other Issues or PRs

Fixes #18064 

#### Release Notes

* physics.vector
  * Imported the `EvalfMixin` class from the `sympy/core/evalf`

### CODE REVIEW

**Comment by Smit-create** [comment]
Your need a release note entry as:
```
<!-- BEGIN RELEASE NOTES -->
* physics.vector
  * Description of what is changed
<!-- END RELEASE NOTES -->
```
Also, you need to merge master in your branch and resolve the conflicts.

**Comment by Saanidhyavats** [comment]
Thank you @Smit-create for guiding me. I have added the description in release notes.

**Comment by oscarbenjamin** [comment]
There is a flake8 error:
```
sympy/core/function.py:1389:20: F821 undefined name 'self'
```

**Comment by Saanidhyavats** [comment]
Even after importing and inheriting I am unable to use `evalf` function for Vector class. I think we have to use `super()` function. Is it correct?

**Comment by Saanidhyavats** [comment]
For  `sympy/physics/vector` `evalf` function is still not working. I think it will work if we introduce a new function and in that call the evalf function. Somewhat like this:
`def _evalf(self, n=15, subs=None, maxn=100, chop=False, strict=False, quad=None, verbose=False):
        return(evalf(self, n, subs, maxn, chop, strict, quad, verbose))`
correct me if I am wrong

**Comment by oscarbenjamin** [comment]
I think maybe the problem is that vector is not a Basic subclass

**Comment by Saanidhyavats** [comment]
Some of the functions which are present in `evalf.py` used by `evalf` function are not imported in vector file. I think this may be the reason for error.
For example:
`  rv = rv.round(1 - m)`
where `round` function is not imported in `vector` file

**Comment by Saanidhyavats** [comment]
Is it correct @oscarbenjamin 


> Some of the functions which are present in `evalf.py` used by `evalf` function are not imported in vector file. I think this may be the reason for error.
> For example:
> ` rv = rv.round(1 - m)`
> where `round` function is not imported in `vector` file

**Comment by moorepants** [comment]
Vector is not based on any SymPy class because it's design require mutability. You'll need to create a solution that works with standalone mutable objects.

**Comment by oscarbenjamin** [comment]
@Saanidhyavats I don't know what the right way to do this is. The main work involved in fixing this is figuring that out.

I haven't spent much time looking at it myself but when I briefly looked I realised that I didn't fully understand how sympy's vector objects work. That is why I removed the "easy to fix" label from the original issue.

Feel free to figure out a way to make this work but I don't think that I can give good advice. Unless someone else can then I would recommend working on something else.

**Comment by moorepants** [comment]
I suspect a very simple solution would be to create new methods for evalf on the two objects (Vector, Dyadic) and those call evalf on the coefficients (which are sympy base types). Then construct new vector (or dyadic) and return. That is how most of the other methods are implemented. I think it is a pretty easy fix, if done that way.

**Comment by Saanidhyavats** [comment]
I will look into it

**Comment by Saanidhyavats** [comment]
Thank you @moorepants  for the suggestion. I have gone through other codes and  think this is the correct one to implement it:
`def evalf(self, a, prec=None, **options):
        return self.to_sympy(a).evalf(prec, **options)`
correct me if I am wrong @moorepants

**Comment by Saanidhyavats** [comment]
@moorepants I have updated the changes in file vector.py correct me if I am wrong somewhere

**Comment by Smit-create** [comment]
Please add the relevant test cases to validate the change you have made.

**Comment by Saanidhyavats** [comment]
>>>a, b, c = symbols('a, b, c')
>>>A = ReferenceFrame('A')
>>>B = A.orientnew('B', 'Axis', (pi, A.x))
>>>v = a*pi*A.x + b*2*pi*B.x + c*3*pi*B.z
>>> v._eval_evalf(3)
3.0*a*A.x + 6.0*b*B.x + 9.0*c*B.z

is this the expected answer or something else?

**Comment by Saanidhyavats** [comment]
I am getting the assertion error in test files though I am getting the expected result .

> a, b, c = symbols('a, b, c')
    B = A.orientnew('B', 'Axis', (pi, A.x))
    v = a*pi*A.x + b*2*pi*B.x + c*3*pi*B.z
    assert v._eval_evalf(3) 
   3.0*a*A.x + 6.0*b*B.x + 9.0*c*B.z

**Comment by czgdp1807** [comment]
The diff coverage is low. 
@moorepants Are the results in https://github.com/sympy/sympy/pull/18559#issuecomment-605836514 correct?

**Pull request closed without merging**
