### PR TITLE
GeometricEntities are now Sets

### PR DESCRIPTION
**Pull request by siefkenj**
IPython uses _repr_svg_ to render an object when in
IPython notebook.  This patch adds _repr_svg_ methods
to appropriate subclasses of GeometricEntity.  Some
code is borrowed from the BSD liscened shapely project.
https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/base.py

### CODE REVIEW

**Comment by siefkenj** [comment]
The build now seems to only be failing on pypy.  I cannot get it to fail on my local pypy install.  I wonder if anyone can help identify the issue?  I assume it's a pypy issue...

**Comment by toolforger** [comment]
It is this:

```
______________ sympy/geometry/tests/test_geometry.py:test_polygon ______________

  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/geometry/tests/test_geometry.py", line 1445, in test_polygon

    assert len(intersection(*bisectors.values())) == 1

AssertionError
```

Are you using
One important difference: Normal Python keeps dictionary keys in the order that they were inserted, pypy uses some other order.

**Comment by toolforger** [comment]
What pypy version are you using? The dict key handling in pypy changed in, uh, 2.5 IIRC.

**Comment by siefkenj** [comment]
Hmmm...PyPy 2.4.0 is what I used. Is it possible to see what the output of intersection(*bisectors.values()) from travis is? I don't recall ever using a dictionary in my code...

**Comment by toolforger** [comment]
Set up a virtualenv with pypy 2.5. It's really recommended.

To see the output of some expression, just add a `print` call to the test and `git push` to the branch - the test will still fail, but you'll see the output :-) (I'd recommend throwing a guaranteed-to-fail-the-test exception to make sure that the thing doesn't accidentally pass and gets merged).
However, be warned that that's going to be an extremely slow and frustrating edit-debug cycle. 

You may not be using an explicit dictionary; I didn't see anything like that in your changes either.
However, some of the stuff you're calling might be building a dictionary internally.
Or it might return data from a dictionary in the form of a tuple.
And maybe it's not dictionary in the first place.
Or maybe what we're seeing here is just a follow-up bug to something that went wrong deep inside of SymPy.

**Comment by siefkenj** [comment]
Haha, I believe you're onto something! I installed pypy 2.5.1 and now it fails.  Further, upon inspection, 

`bisectors.values()` returns a `dict_values` object and the coordinates defining each Segment are in a different order!

**Comment by siefkenj** [comment]
Found the error! It is in the Matrix.rank function...It also appears to be in Matrix.rref.

    m = Matrix([[-5 + 5*sqrt(2), -5], [-5*sqrt(2)/2 + 5, -5*sqrt(2)/2]])
    print("shape:", m.shape)
    print("det:", m.det())
    print("rank:", m.rank())

outputs

    shape: (2, 2)
    det: 0
    rank: 2

but should output

    shape: (2, 2)
    det: 0
    rank: 1

**Comment by toolforger** [comment]
We should fix the underlying problem instead of working around it.

**Comment by toolforger** [comment]
Oh, I see you added an Issue. You should mention it in the comment that does the workaround, and mention the workaround in the issue, so people will know to undo the workaround when they touch the `rank` problem.

**Comment by siefkenj** [comment]
@toolforger are you suggesting I edit the commit message?  I am not sure I know how to do that...

**Comment by toolforger** [comment]
I'm suggesting to edit the code and add a comment that mentions the issue.
Also, to add a remark on the Issue. Either with an additional entry, or by editing the Issue itself (there's an easily-overlooked Edit button right next to the title on GitHub).

**Comment by certik** [comment]
I reviewed the whole PR and it looks good to me. Thanks for refactoring the points!

**Pull request merged**
