### PR TITLE
Remove unexpected keyword argument order

### PR DESCRIPTION
**Pull request by debugger22**
It looks like this part of code isn't being covered in any test.

@Mechcoder please review.

### CODE REVIEW

**Comment by hargup** [comment]
@debugger22 @MechCoder are you working on this code?

**Comment by MechCoder** [comment]
I do not have the time right now. :( . Feel free to close (unless Sudhanshu is working on it)and open an issue. (It should be EasyToFix)

**Comment by debugger22** [comment]
>  Feel free to close and open an issue.

+1

**Comment by dineshiith** [comment]
h






regards,
Kakarla Dinesh,
Second Year Graduate,
Dept. of Computer Science,
IIIT Hyderabad.

On Fri, Jun 12, 2015 at 10:22 PM, Sudhanshu Mishra <notifications@github.com

**Comment by debugger22** [comment]
@dineshiith do you want to take this up?

**Comment by czgdp1807** [comment]
The purpose of this PR is already fulfilled in the current `master`. Closing this for now.

**Pull request closed without merging**
