### PR TITLE
Move test code from utilities into a new testing package

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

See #18091 

#### Brief description of what is fixed or changed

1. Move test runner files from the `sympy.utilities` package to a new `sympy.testing` package. The files moved are:
```
benchmarking.py
quality_unicode.py
runtests.py
pytest.py
randtest.py
tmpfiles.py
```

2. Update docs for the moved files.

3. Fix all imports - there are a lot of imports from `sympy.utilities.pytest` in the test code and these have all been changed.

#### Other comments

While working on trying to disentangle cyclic imports in SymPy I found that I couldn't even get the tests to start without incurring cyclic imports. That's why I think that the first step in reorganising is to move the tests to their own package and ensure that it doesn't depend on anything else in sympy.

With this PR as it stands the testing package still has a few imports for the following modules:
```
sympy.core.compatibility
sympy.utilities.exceptions
sympy.utilities.misc
```
These two are imported once each:
```
sympy.core.cache (clear_cache)
sympy.external (import_module)
```
The `randtest.py` file has a whole bunch of imports from core, simplify etc. Actually the functions in this file are used a lot in non-test code. Maybe they belong somewhere else and should not be considered part of the testing code.

#### Release Notes

* utilities
    * Code for the test runner is moved to a new `sympy.testing` package.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This is ready for review

**Comment by oscarbenjamin** [comment]
Just rebased again. Does anyone have any view on this?

**Comment by jksuom** [comment]
I did not look into all the changed files but the checks have passed so I am +1 for this.

**Comment by oscarbenjamin** [comment]
Thanks for the review @jksuom.

Please don't merge this right now though as I need to check this carefully at the time of merge to ensure that it doesn't break master.

**Comment by oscarbenjamin** [comment]
Okay, it looks like there have been no changes in utilities since the base of this PR. I've checked that the new files created in this PR are the same as the files on current master apart from necessary changes to imports.

The tests might still fail though because of newly added imports from utilities during the last 3 days. If they pass then this can be merged.

**Comment by oscarbenjamin** [comment]
I've just been back through the diff and it looks fine. The diff is large but it's mostly just changed imports. The substantive changes are just the moved files which apart from changes to imports have just been moved from one directory to another. It also looks like the tests will pass.

This PR is difficult to keep up to date with changes in master though so I will merge as soon as tests pass unless I hear anything.

**Comment by asmeurer** [comment]
sympy.external.importtools is supposed to be independent of the rest of sympy, so it shouldn't cause any issues with this sort of thing.

**Pull request merged**
