### PR TITLE
misc changes from matrix mul testing

### PR DESCRIPTION
**Pull request by tom-pytel**
#### References to other Issues or PRs
Ref #17247 

#### Brief description of what is fixed or changed
Added tests for failing and inoptimal matrix multiplications and modified simplify/hyperexpand to not depend explicitly on current matrix multiplication returned form so that when it is eventually optimized hyperexpand won't break.

#### Other comments
This comes out of testing various intermediate matrix multiplication simplifications which for the most part solve these problems but cause some others, so not implemented yet but the test cases are worth having for any potential matmul optimization testing in the future.

#### Release Notes

* matrices
  * added tests for current matmul failure and inoptimal cases
* simplify
  * removed hyperexpand dependance on return from from matrix multiplication

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Thanks for this.

**Comment by oscargus** [comment]
This PR increased the time for some integrals significantly. Especially: `test_issue_9101 - Took 60.445  seconds` (was well below 10 seconds earlier).

To be honest, I would have expected a non-failing test to illustrate the benefit of the modification. At the moment it is not clear what the consequence is (except longer time for identical results...). (It adds about three minutes of total test time and the XFAIL-tests are not included among the tests that takes the longest time, so I would expect that most of the additional time is from other tests.)

Btw, it is possible to skip a test, see e.g. https://github.com/sympy/sympy/blob/c91f596b651f137df6fc252b50418df0ccc55745/sympy/integrals/tests/test_failing_integrals.py#L13

**Comment by Pristine-Cat** [comment]
> This PR increased the time for some integrals significantly. Especially: `test_issue_9101 - Took 60.445 seconds` (was well below 10 seconds earlier).
> 
> To be honest, I would have expected a non-failing test to illustrate the benefit of the modification. At the moment it is not clear what the consequence is (except longer time for identical results...). (It adds about three minutes of total test time and the XFAIL-tests are not included among the tests that takes the longest time, so I would expect that most of the additional time is from other tests.)
> 
> Btw, it is possible to skip a test, see e.g.
> 
> https://github.com/sympy/sympy/blob/c91f596b651f137df6fc252b50418df0ccc55745/sympy/integrals/tests/test_failing_integrals.py#L13

Hmm, it really shouldn't do that, no functionality was changed just straight multiplication was used instead of calling out to multiply, I will have a look.

**Comment by Pristine-Cat** [comment]
> This PR increased the time for some integrals significantly. Especially: `test_issue_9101 - Took 60.445 seconds` (was well below 10 seconds earlier).

Not my fault. Reverted to old code and ran the test a few times and noticed especially `test_issue_9101' seems to be non-deterministic. Got this in one run
```
test_issue_9101 - Took 180.929 seconds
==================== tests finished: 0 passed, 12 skipped, 27 expected to fail, in 196.59 seconds =====================
```

Other runs under 20s, sometimes it just stalls out. In any case the only code change I did in this PR was to change a few row x column matrix multiplies of the form:
```
return (self.C*self.B)[0]
```
to
```
return reduce(lambda s,m: s+m[0]*m[1], zip(self.C, self.B), S.Zero)
```
to avoid the matrix multiplies since I am working on those in another PR and they may change form and hyperexpand specifically seems to depend on the current returned form.

If you reeeally want I can change this to:
```
C = self.C
B = self.B
r = C[0]*B[0]
for i in range(1, len (C)):
     r += C[i]*B[i]
```
but I would have to push it up as a new PR since I already deleted the branch.

**Comment by oscargus** [comment]
Ah, sorry about that then. I looked at all the recent master build tests and there was a clear distinction at this PR as far as I could tell, even though it wasn't really clear to me why this PR would affect it as it seemed to deal with matrices (it was one of the last ones I checked because of it), but there were some changes in hyperexpand that I though at least theoretically could affect it (at the time I was to tired to look more into the details of the code). Plus the time "evidence".

(Just trying to keep tests "sorted" correctly between slow and non-slow... So I notice these things now and then. I've since realized that the three minutes total may not be that bad though and that there is a spread every now and then.)

**Comment by Pristine-Cat** [comment]
> affect it as it seemed to deal with matrices (it was one of the last ones I checked because of it), but 

A couple of integral tests use matrices, and the matrix PR I am working on used some simplifications in matrix multiplication which eventually used hyperexpand, not sure if it still goes down that codepath.

> (Just trying to keep tests "sorted" correctly between slow and non-slow... So I notice these things now and then. I've since realized that the three minutes total may not be that bad though and that there is a spread every now and then.)

So just to verify, it was the hyperexpand change you were wondering about and not the new failing matrix tests? Because if those are too slow you can just comment them out but leave them as a record of what is currently failing so that they can be re-enabled if/when matrix multiplication gets fixed.

**Pull request merged**
