### PR TITLE
Dimension system refactoring

### PR DESCRIPTION
**Pull request by Upabjojr**
Dimensional dependencies are not absolute, they depend on the dimension system (class `DimensionSystem`).

Even relations like `velocity == length / time` actually depend on the dimension system you're currently using. If you are in special relativity, maybe you want to use `length == time` so that the `velocity` is dimensionless.

In the gaussian units, the unit of _charge_ is the _statcoulomb_, which does not depend on the _Ampere_ (the _current_ is not a fundamental dimension and the charge can be expressed as a combination of _length_, _time_, and _mass_ without _current_).

This PR makes the relation between base dimensions and derived dimensions part of `DimensionSystem`, so that they are no longer absolute.

For compatibility reasons, the SI dimension standard is kept as a reference point.

TODO:
- [ ] release deprecation warnings

### CODE REVIEW

**Comment by Upabjojr** [comment]
@schymans

**Comment by schymans** [comment]
This looks very nice. Would you be able to give some usage examples, especially of the new class `DimensionalDependency(Basic)`? I have been struggling a lot with figuring out the motivations for some past code changes in sympy and realised that simple usage examples of the intended behaviour would have helped. Thanks!

**Comment by Upabjojr** [comment]
> especially of the new class DimensionalDependency(Basic)?

I have merged that class into `DimensionSystem` in my last commit.

> I have been struggling a lot with figuring out the motivations for some past code changes

The `DimensionSystem` class should contain information about the relations between dimensions, for example that `velocity == length / time`.

**Comment by Upabjojr** [comment]
@schymans I know you are using a lot the code in units, I was wondering whether you can check if you find any trouble by using this branch (to make sure it won't break too much).

**Comment by schymans** [comment]
OK, I'll try and report, but it won't be until next week.

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/issues/13336

**Pull request merged**
