### PR TITLE
Added link to pdf version of docs in the main documentation page

### LINKED ISSUE #11927: Add link to PDF docs to docs site
We build PDF docs with the release at https://github.com/sympy/sympy/releases, but people might not know about it. We should add a link to the release docs at http://docs.sympy.org/latest/index.html to the PDF docs. Probably the simplest solution would be to just add a sentence to the top that says "a PDF version of these docs can be found at https://github.com/sympy/sympy/releases".

### PR DESCRIPTION
**Pull request by karthikchintapalli**
Fixes #11927.

- Added a link to the pdf version of the docs at the top of the documentation page at http://docs.sympy.org/latest/index.html

### CODE REVIEW

**Review by asmeurer — APPROVED** [review]

**Comment by karthikchintapalli** [comment]
I'm not able to figure out why Job #20253.23 is failing. Can the reviewers please check it out?

**Comment by gxyd** [comment]
Seems like it is not related to your changes, it is failing because of issue #11930 .

**Comment by asmeurer** [comment]
I have a [PR](https://github.com/sympy/sympy/pull/11935) in to fix Travis. Once it is merged, we can merge this.

**Comment by asmeurer** [comment]
I restarted the build but it didn't seem to pick up the change from master.

**Comment by asmeurer** [comment]
I tried restarting it again.

**Comment by jksuom** [comment]
This should be synchronized with the updated master.

**Comment by karthikchintapalli** [comment]
Can I ask what the status of the build rerun is? It still says "checks failed".

**Comment by jksuom** [comment]
This fails because the .travis.yml file in your branch (https://github.com/karthikchintapalli/sympy) is still the old version ("Use symengine=0.2.0", Sep 26, 2016). The branch should be synchronized with master (and then pushed to github). See e,g. https://github.com/sympy/sympy/wiki/Development-workflow.

**Comment by karthikchintapalli** [comment]
Ok, I think I synchronized it. Is it fine now?

**Comment by asmeurer** [comment]
Oh I get it, the travis file is read before using the merged branch.

**Comment by asmeurer** [comment]
You should see your change at http://docs.sympy.org/dev/ once https://travis-ci.org/sympy/sympy/jobs/184333238 builds.

**Pull request merged**
