### PR TITLE
Get the release notes from the pull request description automatically using a bot

### LINKED ISSUE #10942: Including Release Notes in sympy repo.
Is there a specific reason why we don't have release notes version controlled? If version controlled, we can then also include them in the docs which seems missing to me.

### PR DESCRIPTION
**Pull request by asmeurer**
The bot (https://github.com/sympy/sympy-bot) automatically checks every pull
request to make sure there is a valid release notes entry in the description.
The release notes entry should placed between the `` lines and be formatted like

```
* solvers
  * improved logarithmic solving
```

In other words, each release note entry should have a heading with the
submodule that was changed, or `other`, and have a bulleted list of the
changes.

I have written a guide on how to write release notes at
https://github.com/sympy/sympy/wiki/Writing-Release-Notes.

Whenever a new pull request is made, or the description is edited, the bot
will automatically check the release notes to see if they are formatted
correctly.

When the pull request is merged, the bot will automatically take the parsed
release notes and add them to the release notes on the wiki.

Any suggestions on the wording here or in the bot are welcome.

#### References to other Issues or PRs

Closes #13584
Closes #10942 

#### Brief description of what is fixed or changed

This pull request just updates the PULL_REQUEST_TEMPLATE.md

#### Other comments

I will set up the bot and configure it to only run on this pull request (I will make it run everywhere once this is merged). Please feel free to play around with it by editing the text below:

#### Release Notes

* other
  * the release notes are now automatically collected from pull request descriptions using a [bot](https://github.com/sympy/sympy-bot).

### CODE REVIEW

**Comment by isuruf** [comment]
You could also use the github status API to add a status to the latest commit sha and make it required for merging pull requests.

**Comment by asmeurer** [comment]
@isuruf yes, it is supposed to be doing that. But I just noticed that for whatever reason it isn't working on this pull request.

**Comment by asmeurer** [comment]
Ah figured out the problem. The bot has to have push access to add a status (unfortunately), and I forgot to accept the invitation. You can see the status check now.

**Comment by asmeurer** [comment]
@smichr @jksuom @Upabjojr you'd done the [bulk of the pull request merging](https://gist.github.com/asmeurer/c5b8605cd5b7ed179afc30acdda060fc) recently. I'd love to hear your thought on this before we deploy it.

**Comment by jksuom** [comment]
This looks good to me. It should not be too hard to edit the notes section before merging if necessary.

**Comment by asmeurer** [comment]
It's working now https://github.com/sympy/sympy/wiki/Release-Notes-for-1.2.1

Reminder to everyone: if you edit the pull request description, you need to reload the page to see the updated comment (the bot generally runs instantly, but GitHub doesn't autoupdate edited comments).

**Comment by asmeurer** [comment]
I have set the bot as required to merge. To trigger the bot on an existing pull request, just edit the pull request description. Just editing the description is better than closing and reopening the pull request, as that also causes Travis to rebuild.

**Comment by asmeurer** [comment]
Yes, that is because I set the bot to required. This is intentional because all PRs merged from now on should have release notes. You can trigger the bot on a PR by editing the description (even a trivial edit like adding a newline). That will change the status from pending to passed or failed.

**Comment by asmeurer** [comment]
Actually I guess you need push access to do that. Otherwise you can only edit your own pull requests.

**Comment by moorepants** [comment]
I just wanted to note how awesome this addition is! The release notes for 1.2.1 are so nice.

**Comment by asmeurer** [comment]
Thanks Jason. Yes, it's already looking as good as the 1.2 notes, which took me a month to compile. 

If you have any feedback on the bot please let me know over at https://github.com/sympy/sympy-bot

**Pull request merged**
