### PR TITLE
Solves compatibility issues in Min and Max (jax with tuples)  

### LINKED ISSUE #26139: jax printer doesn't properly convert sympy Min and Max during lambdify
jax can't accept tuples as input to amin and amax the same way that numpy does.  this results in the following error when lambdifying a sympy expression with min/max:

```
TypeError: max requires ndarray or scalar arguments, got <class 'tuple'> at position 0.
```

https://github.com/sympy/sympy/blob/a07d5bceb6b58a06af354c035ed2ac1854669a16/sympy/printing/numpy.py#L218-L222

i think the fix is simply to wrap the tuple in a `jax.numpy.asarray()` call (similarly to how and/or are carved out for jax)

### PR DESCRIPTION
**Pull request by virajvekaria**
#### References to other Issues or PRs

Fixes #26139

#### Brief description of what is fixed or changed
Adding wrapper function to jax amin and amax, which converts incoming iterables to ndarrays

#### Release Notes

* printing
  *  Fix issues of `Min` and `Max` generating wrong code for `jax`.

### CODE REVIEW

**Comment by virajvekaria** [comment]
How do I solve the test/authors issue?

**Comment by virajvekaria** [comment]
So the only test that failed is the authors one, and I can't figure out what is wrong

**Comment by Ravindu-Hirimuthugoda** [comment]
> So the only test that failed is the authors one, and I can't figure out what is wrong

Run` bin/mailmap_check.py`. 
`.mailmap` file is not in proper order. That's why it is failing.

**Comment by virajvekaria** [comment]
Can someone please review the code so that we can proceed further

**Comment by sylee957** [comment]
I think that you may need tests
See if you can follow the format of https://github.com/sympy/sympy/blob/26b3c1365563faac3e37810fd0c8fd772a71cc49/sympy/printing/tests/test_jax.py

**Comment by virajvekaria** [comment]
can not understand the issue here, what is this test trying to say?

**Comment by sylee957** [comment]
I think that the problem is you are importing jax directly, which the CI environments does not have.
You may need some guides to how to import the external packages for tests, however, I may take second look if your tests should be written in alternative way.

**Comment by virajvekaria** [comment]
so should I look into ways to import external modules?

**Comment by virajvekaria** [comment]
looked into it

**Comment by sylee957** [comment]
You may need import guard

if not jax:
    skip(...)

See how numpy specific tests are written

**Comment by virajvekaria** [comment]
if these set of tests do not pass I think I will have to do that

**Comment by virajvekaria** [comment]
or if you recommend it I can look into it now, because I do not need the whole library, I just need the asarray function of jax.numpy

**Comment by sylee957** [comment]
I think that the correct way should be 

that test should be using ‘jax’. If you just use lambdify, it may default with numpy, which is not expected.

You should also try and verify that without your changes in your printer, the test should fail. 
(You may try to do it locally)
It should justify the changes before and after the changes to the printer.

**Comment by virajvekaria** [comment]
the weird part is that it passes all the tests on my local computer

**Comment by virajvekaria** [comment]
i think i got it now, this should do it

**Comment by virajvekaria** [comment]
So, how do we proceed now? Do I have to make more changes, or should it be merged?

**Comment by sylee957** [comment]
I may check some things for tomorrow. You can do other things unless there are other comments from someone.

**Comment by virajvekaria** [comment]
So you mean I should solve other issues?

**Pull request merged**
