### PR TITLE
Support fractions in is_deriv_k

### PR DESCRIPTION
**Pull request by jksuom**
Fixes issue #10798

### CODE REVIEW

**Comment by smichr** [comment]
By symmetry considerations, this looks like the proper handling of the denominator. +1

**Comment by jksuom** [comment]
I wonder why this is not being tested. Is there something wrong with Travis?

**Comment by smichr** [comment]
That was strange about the tests...I closed and reopened and that started them.

**Comment by jksuom** [comment]
Ok, thanks. I also thought that maybe should help.

**Comment by smichr** [comment]
Thanks, it's in.

**Comment by asmeurer** [comment]
I would have preferred to see a more direct test of is_deriv_k.

**Comment by jksuom** [comment]
I'll try to set up a test calling is_deriv_k.

**Pull request merged**
