### PR TITLE
Deprecating get_points, get_meshes, get_raster of data series classes

### PR DESCRIPTION
**Pull request by Davide-sd**
#### References to other Issues or PRs

Another PR related to Issue #23036 .

#### Brief description of what is fixed or changed

The plotting module implements ``*Series`` classes in order to generate numerical data for plots. Each class exposes a different method to retrieve the numerical data. For example, line-related series expose ``get_points``, surface-related series expose ``get_meshes``, implicit series exposes ``get_raster``.

As the number of ``*Series`` classes is going to increase, a common method to retrieve numerical data is introduced: ``get_data``.

#### Release Notes

* plotting
  * DEPRECATION: Deprecating `get_points`, `get_meshes`, `get_raster` of data series classes.

### CODE REVIEW

**Comment by Davide-sd** [comment]
Code quality tests with `flake8` are failing with: `C408 Unnecessary dict call - rewrite as a literal.`

While I could easily rewrite these two tests to use literal dictionaries, the new plotting module makes intensive use of dict calls because I find them to be faster to type and easier on the eyes (less `"` or `'` characters). Would it be possible to relax `flake8` on `C408` cases?

**Comment by oscarbenjamin** [comment]
We're talking about this:
```python
options = dict(show=False, adaptive=False)
```
rather than this:
```python
options = {'show': False, 'adaptive': False}
```
I didn't realise that the linter would reject the former and I'm not sure if I agree with the linter doing that but I definitely prefer the latter form.

In context though it looks like:
```python
    options = dict(show=False, adaptive=False)
    p = plot(x, (x, -10, 10), **options)
```
which would be clearer as
```python
    p = plot(x, (x, -10, 10), show=False, adaptive=False)
```

The other case is longer:
```python
    options = dict(show=False, nb_of_points_x=5, nb_of_points_y=5)
    p = plot3d(cos(x*y), (x, -3, 3), (y, -3, 3), **options)
```
That might be too long as a single line or at least it is clear that with enough kwargs it would be too long:
```python
    p = plot3d(cos(x*y), (x, -3, 3), (y, -3, 3), show=False, nb_of_points_x=5, nb_of_points_y=5)
```
Running black on that gives
```python
    p = plot3d(
        cos(x * y),
        (x, -3, 3),
        (y, -3, 3),
        show=False,
        nb_of_points_x=5,
        nb_of_points_y=5,
    )
```
Personally I think that is quite acceptable. There is one clear thing happening on each line and the end result is quite readable.

**Comment by sylee957** [comment]
I don't think that we should relax the stylish changes globally for the stuff what was decided before.
But I think that its worth thinking about sympy as monorepo if separate projects need different code style configuration.

**Comment by Davide-sd** [comment]
Let's consider this:

```py
options = dict(show=False, nb_of_points_x=5, nb_of_points_y=5)
p1 = plot3d(cos(x*y), (x, -3, 3), (y, -3, 3), **options)
p2 = plot3d(cos(x*y), (x, -3, 3), (y, -3, 3), show=False, nb_of_points_x=5, nb_of_points_y=5)
p3 = plot3d(
        cos(x * y),
        (x, -3, 3),
        (y, -3, 3),
        show=False,
        nb_of_points_x=5,
        nb_of_points_y=5,
)
```

The beauty of  ``options`` is that it can be reused on multiple function calls. On my module, inside test files there are hundreds if not thousands of occurrences where I used ``options`` to make code easier to read, more maintainable and more compact. Changing them from dict calls to literals is definitely going to be a PITA.

Consider that many test files easily contains more than a thousand lines of code and that there are hundreds of tests. if I were to follow the syntax of `p2` or `p3` it would become unmaintainable: a simple edit down the road (like deprecating a keyword argument if favor of something else) definitely requires more time invested to adapt test files. If I were to use syntax of `p3`, test files would become unnecessarily long.

> But I think that its worth thinking about sympy as monorepo if separate projects need different code style configuration.

This would be great.

**Comment by sylee957** [comment]
In my opintion, I don't think that it's the best answer to use `kwargs` anyway,
it's better to use `TypedDict` to make sure that implementations can interpret every options there,
and also for users to quickly validate the code with the help of IDE and linters.

```python3
class PlotOptions(TypedDict):
    show: bool
    nb_of_points: int
    ...
```

And the options need to be implemented as classes to allow shared documentation.
Now it looks chaotic that options need to be documented everywhere and quickly get forgotten, outdated everywhere.

There are PEP for using `TypedDict` as schema for options are improved as following:
https://peps.python.org/pep-0589/
https://peps.python.org/pep-0655/
https://peps.python.org/pep-0692/

**Comment by sylee957** [comment]
My opinion is that that could workaround to using `dict` in linters though.
The linters may be able to recognize the nontriviality between it and `dict` and `{}`

**Comment by oscarbenjamin** [comment]
> I don't think that we should relax the stylish changes globally for the stuff what was decided before.

I'm not sure that anything was "decided" except just that this is part of the default linting rules for flake8.

> The beauty of `options` is that it can be reused on multiple function calls.

Okay, I see what you mean. The idea is to factor out the kwargs from repeated use like:
```python
    options = dict(show=False, adaptive=False)
    p1 = plot(x1, (x1, -10, 10), **options)
    p2 = plot(x2, (x2, -10, 10), **options)
    p3 = plot(x3, (x3, -10, 10), **options)
```
That does seem reasonable to me and I can see why the `dict(...)` style could be preferred because it makes the keyword arguments still look like keyword arguments as they would if used directly in the function call.

I think it would be fine to exclude C408 in the flake8 config. I don't think that rejecting `dict(...)` particularly helps with readability of the codebase. It is less efficient than a dict display but that is unlikely to be important.

**Comment by Davide-sd** [comment]
I'm not forcing anyone: as far as code is readable, maintainable and does the job it's supposed to, I think anyone should use the best syntax for the job. In this particular case, `dict` has clear benefits over literal (which I made the case in the above comments).

> I don't think that we should relax the stylish changes globally for the stuff what was decided before

By the way, this convention was introduced with pull #24741 .

**Comment by oscarbenjamin** [comment]
> I don't think that we should relax the stylish changes globally for the stuff what was decided before

Maybe just change the lint rules specifically for the plotting module then.

**Comment by sylee957** [comment]
Anyway, my opinion is still I can't get the clear advantage of deprecating this in terms of the type theory of python.

> As the number of *Series classes is going to increase, a common method to retrieve numerical data is introduced: get_data.

It means that `get_data` is a single function that returns union of many variant types (2-tuples, 3-tuples, ...), 
which are not compatible override though.

**Comment by Davide-sd** [comment]
bump.

**Comment by oscarbenjamin** [comment]
I've just looked through and it is unclear to me what the advantage is of deprecating these methods. Can they not just be left there even if the docs suggest to use a newer method?

**Comment by Davide-sd** [comment]
> I've just looked through and it is unclear to me what the advantage is of deprecating these methods. Can they not just be left there even if the docs suggest to use a newer method?

It's called house cleaning, sometime it must be done. In my opinion, a (method) name should reflect its intention. That is not the case anymore: those methods did their part, and should not exist anymore. Hence the deprecation, and sooner or later, the removal. Why keeping stuff that is not useful and is confusing?

**Comment by oscarbenjamin** [comment]
> Why keeping stuff that is not useful and is confusing?

Because downstream code probably uses it.

It is possible to make changes in a backwards compatible way like this:

1. Add the new method `get_data`.
2. Change all internal code to call the new method.
3. Make the old methods (`get_points` etc) wrap the new method (`get_data`) to minimise the cost of maintaining them.
4. Change the docstring of the old methods to say that they are deprecated and that the new method should be used instead.

Then downstream code that uses the old method can continue working but the old method is not used internally and anyone looking at the old method in the docs/code will see that they should not use it.

As far as I can tell this PR does all of the things that I described above except that:

1. Internal code still seems to use the old methods (just renamed with underscore).
2. As well as changing the docstring a warning is emitted at runtime.

Firstly if internal code still uses the old methods (`_get_points` etc) then that suggests that they are in fact useful and so maybe there is a reason to keep them rather than remove them.

Secondly what benefit is gained by giving out a warning at runtime? I would say that there is no immediate benefit in doing this.

If we want to give out a warning then that should mean that it is already time for downstream code to be changed to use the alternate method. If that new method is added in the same release that the other method starts giving out a warning then that makes it awkward for downstream code to have compatibility with multiple versions of sympy: the new method should exist in at least some sympy releases before the old method begins to give any warnings.

My suggestion is just to remove the runtime warnings and have the docstrings say to use the newer method. I understand why you want to add the runtime warnings which is because you want to subsequently remove the old methods as soon as possible but I don't actually see what the benefit of doing that is either.

If we follow steps 1-4 above then we reach a situation where the old methods have almost no cost and can just be left indefinitely. If we have a SymPy 2.0 (gh-25145) then we can do "house cleaning" then but in the mean time that is not in itself a good reason to break downstream code or to force it to be changed.

I consider this PR different from gh-25117 for several reasons:

- In that case it seemed unlikely that downstream code might depend on the deprecated behaviour.
- In that case the suggestion is for code to be changed to something that already works in previous releases and was already the documented way to use the plotting module anyway.
- I can see why in that case setting plot properties after the fact might not work for other backends so that maybe continuing to support that could cause significant problems for the internal code in future.

The last point is the most important because it shows some that there could be significant benefit for the eventual removal of the code. I don't see any tangible benefit for the actual removal of the methods that are deprecated in this PR.

**Comment by sylee957** [comment]
Unfortunately, keeping the duplicate methods introduces as much redundancy as raising deprecation warnings at haste.
I don't consider deprecation 'warnings' to be a huge burden or such, especially if the migration efforts are not difficult, and I can't understand why some developers are unhappy even with the future warnings.

If we are not going to raise deprecation errors, then there should be a supporting reason to insist that having duplicate functions are done by purpose than accident.

**Pull request closed without merging**
