### PR TITLE
SOPform__int(), POSform__int() SUGGEST

### PR DESCRIPTION
**Pull request by Salmista-94**
SUGGEST   ->   SOPform__int(), POSform__int()

### CODE REVIEW

**Comment by Salmista-94** [comment]
I did not know where comment, so I mention here.

I suggest which can be included:
equation_sympy::domain() -> a,b, ecuRes / 'a' is a space, 'b' are restrictions and is ecuRes
equation that defines the domain in the corresponding variables...
ej: R - {-4,5,9};
     a  = R
     b = {-4,5,9}
     ecuRes = "Sympy equation"

**Comment by asmeurer** [comment]
Can we just modify the existing SOPform function to accept this input?

Also, don't use double underscores for variable names. A single underscore is sufficient.

**Comment by oscargus** [comment]
Needs empty lines around documentation titles (will also make the doctests pass).

A check of `isinstance(item, list)` should do the trick of using a single function and also allow multi-format input (`[[1, 0, 1], 3]`).

Seems like a useful thing anyway.

**Comment by oscargus** [comment]
https://stackoverflow.com/questions/13557937/how-to-convert-decimal-to-binary-list-in-python
https://stackoverflow.com/questions/13522773/convert-an-integer-to-binary-without-using-the-built-in-bin-function

Probably:
```
def tobin(x,s):
    return [(x>>k)&1 for k in range(0,s)]
```
is the most useful answer given that we need to control the number of bits in the result.

**Pull request closed without merging**
