### PR TITLE
Pretty print roots for small integers and short Symbols

### LINKED ISSUE #17616: inaccurate rendering of pi**(1/E)
This claims to be version 1.5.dev; I just merged from the project master, so I hope this is current.  I didn't notice this bug among others in printing.pretty.

```
In [52]: pi**(1/E)                                                               
Out[52]: 
-1___
╲╱ π 

```
LaTeX and str not fooled:
```
In [53]: print(latex(pi**(1/E)))                                                 
\pi^{e^{-1}}

In [54]: str(pi**(1/E))                                                          
Out[54]: 'pi**exp(-1)'
```

### PR DESCRIPTION
**Pull request by cbm755**
pretty: use nth root notation only for small integers and symbols
    
But don't use it if the integer is too big or the symbol is too long:
current threshold set to three characters.

#### References to other Issues or PRs

An alternative to #17620.  Still fixes #17616.  If this is accepted, a similar change could/should be done for LaTeXPrinter as well.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
@cbm755 you've opened two separate PRs here. Which do you think is best?

**Comment by oscarbenjamin** [comment]
@cbm755 I think either of these PRs looks good. Do you have an opinion which is best?

**Comment by oscarbenjamin** [comment]
I don't like this:
```julia
In [4]: pi**(1/E)                                                                                                                                             
Out[4]: 
ℯ ___
╲╱ π 
```
I think this notation should only be used where the exponent is 1/integer.

**Comment by czgdp1807** [comment]
> @cbm755 I think either of these PRs looks good. Do you have an opinion which is best?

ping @cbm755 Please update on this. @oscarbenjamin Can we add `Closes #NUMBER_OF_OTHER_PR` so that if one is merged, the other is closed.

**Comment by czgdp1807** [comment]
Any updates on this? Any conclusion reached? Please let me know if a `Please take over` label is needed here.

**Comment by czgdp1807** [comment]
Current status,
```python
>>> pi**(1/exp(1))
-1___
╲╱ π 
```

**Pull request closed without merging**
