### PR TITLE
converted except BaseException to except NotImplementedError

### PR DESCRIPTION
**Pull request by nilabja-bhattacharya**
As per discussion in pull request #12072 I've converted expect BaseException to except NotImplementedError

### CODE REVIEW

**Comment by gxyd** [comment]
Partial fix to #11668

**Comment by gxyd** [comment]
Can anyone please review this pull request?

**Comment by gxyd** [comment]
@nilabja10201992 thanks for the pull request, its in :) . Thanks @smichr for the review.

**Comment by nilabja10201992** [comment]
@gxyd Thank you for guiding me, I'm grateful that my request was merged. I want to contribute more, please suggest me some easy fixes that will be good to start with.

**Comment by gxyd** [comment]
It's good that you got back (even after quite a few months) to complete the PR. One issue that I can guide you on is #13111 . Its an easy to fix issue. I'll be active in the morning IST time(between 9 AM to 11 AM).

**Comment by nilabja10201992** [comment]
@gxyd Yes, there is lots of code that is of type (expr.func is xyz) in core folder of sympy, should I fix all of them? I'll be active in github tomorrow by 9:30 AM IST

**Pull request merged**
