### PR TITLE
Making `Eq(True, 1)` type commands evaluate to False

### PR DESCRIPTION
**Pull request by ishanaj**
Fixes issue #13348.
closes #13445

### CODE REVIEW

**Comment by smichr** [comment]
In this branch, what do you get for `S.true in [1]`?

**Comment by ishanaj** [comment]
It gives `False`. Is it okay?

**Comment by ishanaj** [comment]
@smichr The following doctest fails :
The output of the statement : 
 `parse_expr("(1*2=x)=False", transformations=(
    ... standard_transformations + (convert_equals_signs,)))` comes out to be `Eq(Eq(2, x), False)` but according to me it should give `False`. What do you suggest?

**Comment by smichr** [comment]
Does Eq(True, S.true) give True in your branch?

**Comment by ishanaj** [comment]
Yes, `Eq(True, S.true)` gives `True` in this branch.

**Comment by ishanaj** [comment]
Actually, this branch returns `False` if any one of the `lhs` or `rhs` is an instance of the class `BooleanAtom`, except for the case when both lhs and rhs are equal which gets checked by the line just before it.
For example :
`Eq(False, True)` returns `False`, while, 
`Eq(True, True)` returns `True`

**Comment by smichr** [comment]
I made a mod that I think will pass.

**Comment by smichr** [comment]
This new code found a logical error in the ode module. I will send a PR to this.

**Comment by smichr** [comment]
Do you see a pull request to this?

**Comment by smichr** [comment]
PR is [here](https://github.com/ishanaj/sympy/pull/1)

**Pull request closed without merging**
