### PR TITLE
Finding and then solving Bugs in module sympy/holonomic

### PR DESCRIPTION
**Pull request by shubhamtibra**

### CODE REVIEW

**Comment by shubhamtibra** [comment]
Although I am not clearly seeing How I would do that. Any ideas?

**Comment by jksuom** [comment]
The set of holonomic functions is closed under addition and multiplication but not under division, so the class of holonomic expressions is necessarily limited. A collection of functions known to be holonomic could be a starting point. Another collection of non-holonomic functions could also be useful.

**Comment by shubhamtibra** [comment]
I think this is ready to merge.

**Comment by jksuom** [comment]
Yes, I think so too.

**Comment by shubhamtibra** [comment]
I think we can merge this, delaying will cause conflicts in the newer PR. Ping @jksuom @certik .

**Comment by certik** [comment]
+1. Sorry about the delay.

**Pull request merged**
