### PR TITLE
matrices: set the default value for dotprodsimp to None

### LINKED ISSUE #20239: Default value of dotprodsimp state variable
During the 1.6 release series performance regressions were identified in some cases involving matrix operations and so the dotprodsimp variable was changed to disable dotprodsimp by default for many operations. This happened in #19588 for master which was then cherry-picked for 1.6.1 in #19612.

Somehow though the two branches ended up with a different default value for the dotprodsimp state variable. On current master we now have:
```julia
In [1]: from sympy.matrices.utilities import _dotprodsimp_state                                                                                

In [2]: _dotprodsimp_state.state                                                                                                               
Out[2]: False
```
Whereas in sympy 1.6.2 we have:
```julia
In [3]: print(_dotprodsimp_state.state)                                                                                                        
None
```

@Pristine-Cat what should be the correct default value for the variable?

I thought that any regressions identified has been fixed in both 1.6.2 and master but running the benchmarks in #20234 I now see that there is a benchmark showing a regression on master (1.7) compared to 1.6.2 which is:
```julia
In [4]: A = Matrix([ 
   ...: [x, 8, 10, 5], 
   ...: [x, 9,  3, 7], 
   ...: [5, 9,  x, 0], 
   ...: [1, 8,  x, 7]])                                                                                                                        

In [5]: %timeit A.det()     # 1.6.2                                                                                                                   
2.75 ms ± 333 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
```julia
In [2]: %timeit A.det()      # 1.7/master                                                                                                                  
16 ms ± 206 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

This diff seems to fix it:
```diff
diff --git a/sympy/matrices/utilities.py b/sympy/matrices/utilities.py
index a65a50b929..cddbe30273 100644
--- a/sympy/matrices/utilities.py
+++ b/sympy/matrices/utilities.py
@@ -9,7 +9,7 @@
 
 class DotProdSimpState(local):
     def __init__(self):
-        self.state = False
+        self.state = None
 
 _dotprodsimp_state = DotProdSimpState()
```
That only gives one failure in matrices (testing the state explicitly) and seems to make some XFAIL tests XPASS:
```console
$ pytest sympy/matrices/ --instafail --tb=short -n4 -d -ra
/Users/enojb/current/sympy/38venv/lib/python3.8/site-packages/_pytest/compat.py:333: PytestDeprecationWarning: The TerminalReporter.writer attribute is deprecated, use TerminalReporter._tw instead at your own risk.
See https://docs.pytest.org/en/latest/deprecations.html#terminalreporter-writer for more information.
  return getattr(object, name, default)
============================================================= test session starts =============================================================
platform darwin -- Python 3.8.1, pytest-5.4.3, py-1.8.1, pluggy-0.13.1
architecture: 64-bit
cache:        yes
ground types: gmpy 2.0.8

rootdir: /Users/enojb/current/sympy/sympy, inifile: pytest.ini
plugins: doctestplus-0.7.0, instafail-0.4.2, xonsh-0.9.13.dev1, cov-2.10.0, profiling-1.7.0, forked-1.1.3, xdist-1.32.0
gw0 [602] / gw1 [602] / gw2 [602] / gw3 [602]
...........................................x.......................................x................................................... [ 22%]
......x........x...................................................x......................................................x............ [ 44%]
.....................................................................................................x.......X.......XX..X............. [ 67%]
...................................................x..........................................x.................................F
______________________________________________________________ test_issue_19809 _______________________________________________________________
[gw1] darwin -- Python 3.8.1 /Users/enojb/current/sympy/38venv/bin/python
sympy/matrices/tests/test_matrices.py:2931: in test_issue_19809
    assert future.result()
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py:432: in result
    return self.__get_result()
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py:388: in __get_result
    raise self._exception
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py:57: in run
    result = self.fn(*self.args, **self.kwargs)
sympy/matrices/tests/test_matrices.py:2923: in f
    assert _dotprodsimp_state.state == False
E   assert None == False
E    +  where None = <sympy.matrices.utilities.DotProdSimpState object at 0x11312e8e0>.state
.....................................................x..............                                                                    [100%]
                                                               DO *NOT* COMMIT!                                                               
=========================================================== short test summary info ===========================================================
XFAIL sympy/matrices/expressions/tests/test_indexing.py::test_block_index_symbolic_fail
XFAIL sympy/matrices/expressions/tests/test_matexpr.py::test_factor_expand
XFAIL sympy/matrices/expressions/tests/test_matmul.py::test_matmul_args_cnc_symbols
XFAIL sympy/matrices/expressions/tests/test_matadd.py::test_matrix_Add_with_scalar
XFAIL sympy/matrices/expressions/tests/test_slice.py::test_symmetry
XFAIL sympy/matrices/tests/test_commonmatrix.py::test_diff
XFAIL sympy/matrices/expressions/tests/test_matexpr.py::test_MatAdd_postprocessor_xfail
XFAIL sympy/matrices/tests/test_eigen.py::test_eigen_vects
XFAIL sympy/matrices/tests/test_matrices.py::test_issue_3979
XFAIL sympy/matrices/tests/test_matrices.py::test_pinv_rank_deficient_when_diagonalization_fails
XPASS sympy/matrices/tests/test_matrices.py::test_issue_17247_expression_blowup_22 
XPASS sympy/matrices/tests/test_matrices.py::test_issue_17247_expression_blowup_8 
XPASS sympy/matrices/tests/test_matrices.py::test_issue_17247_expression_blowup_24 
XPASS sympy/matrices/tests/test_matrices.py::test_issue_17247_expression_blowup_25 
FAILED sympy/matrices/tests/test_matrices.py::test_issue_19809 - assert None == False
======================================= 1 failed, 587 passed, 10 xfailed, 4 xpassed in 93.18s (0:01:33) ====================================
```
Since that makes master consistent with 1.6.2 the last release it would seem safest to make that change so that 1.7 is no different from 1.6.2 but I'm not sure exactly what the intent is of None rather than False.

### PR DESCRIPTION
**Pull request by oscarbenjamin**
Somehow this ended up being set to False on master but None in the 1.6
release branch. This commit ensures that 1.7 will have the same value as
1.6. Setting the value to None means that dotprodsimp can be used when
requested whereas setting it to False disables dotprodsimp in most
calculations.

#### Brief description of what is fixed or changed

Fixes #20239
See also #20234 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by Pristine-Cat** [comment]
Ok well if the only change is to set dotprodsimp default to `None` then this is fine. To clear up the behavior for any future issues  when checking for `dotprodsimp`, it is this:
* If global `dotprodsimp` or function arg `dotprodsimp` is `False` then no dotprodsimp done.
* Otherwise if global `dotprodsimp` or function arg `dotprodsimp` is `True` then dotprodsimp done.
* Otherwise no dotprodsimp done.

This allows a global `dotprodsimp` of `None` to allow dotprodsimp when it is requested by function arg, otherwise a global `False` prevents it. The context manager changes the global value so can prohibit it (`False`), or turn it on in all cases (`True`) except in cases where function arg is `False`.

**Comment by oscarbenjamin** [comment]
> Ok well if the only change is to set dotprodsimp default to `None` then this is fine

Were you expecting other changes or should there be other changes?

**Comment by Pristine-Cat** [comment]
> Were you expecting other changes or should there be other changes?

No, just that.

**Comment by oscarbenjamin** [comment]
Okay, this looks good. I'm surprised at how few tests needed to be changed for this.

The profile results are a mirror image of the differences seen in https://github.com/sympy/sympy/issues/20234#issuecomment-706366565

Most profile results are unchanged, a few show speed up and one shows a noticeable slowdown. Importantly this actually preserves the status quo since the 1.6.2 release so on that basis I think that it is safest to go with this.

Profile results (red faster, green slower):
```diff
       before           after         ratio
     [2513aca3]       [5bd7b619]
     <master>                   
          426±7ns          412±3ns     0.97  baseline.TimeBaseline.time_loop10
          190±4ms          190±4ms     1.00  baseline.TimeBaseline.time_loop10000000
         79.8±3ns       77.1±0.2ns     0.97  baseline.TimeBaseline.time_noop
         1.15±0μs      1.17±0.01μs     1.02  baseline.TimeBasicGCD.time_gcd
      4.15±0.07μs      4.15±0.05μs     1.00  core.arit.Time_Arit.time_Add_1x
      22.7±0.06μs       22.8±0.2μs     1.00  core.arit.Time_Arit.time_Add_x05
      4.03±0.03μs      4.15±0.02μs     1.03  core.arit.Time_Arit.time_Add_x1
      1.96±0.01μs      1.97±0.01μs     1.01  core.arit.Time_Arit.time_Add_xy
      1.20±0.01μs         1.20±0μs     1.00  core.arit.Time_Arit.time_Add_xyz
      5.28±0.04μs      5.34±0.02μs     1.01  core.arit.Time_Arit.time_Div_2y
      3.02±0.01μs      3.08±0.01μs     1.02  core.arit.Time_Arit.time_Div_xy
      1.97±0.02μs      1.98±0.01μs     1.01  core.arit.Time_Arit.time_Mul_xy
      1.21±0.01μs      1.22±0.01μs     1.00  core.arit.Time_Arit.time_Mul_xyz
          557±2μs          563±2μs     1.01  core.arit.Time_Arit.time_mod_pow
      1.81±0.02μs      1.81±0.01μs     1.00  core.arit.Time_Arit.time_neg
          791±9ns          770±3ns     0.97  core.arit.Time_Arit.time_pow100
          796±3ns          763±3ns     0.96  core.arit.Time_Arit.time_pow2
       27.7±0.2μs      27.8±0.08μs     1.00  core.arit.Time_Arit.time_pow_im
      10.1±0.01μs      10.5±0.03μs     1.04  core.arit.Time_assumption.time_Add_Mul_is_finite
      15.3±0.07μs      15.5±0.05μs     1.01  core.arit.Time_assumption.time_Add_Mul_is_integer
       40.8±0.1μs       42.1±0.2μs     1.03  core.arit.Time_assumption.time_ncmul
       49.2±0.2μs       52.2±0.9μs     1.06  core.arit.Time_assumption.time_ncpow
      14.2±0.03μs       14.7±0.1μs     1.03  core.expand.TimeExpand.time_expand_arit
      13.0±0.06μs       13.5±0.5μs     1.04  core.expand.TimeExpand.time_expand_complex_number_1
       18.9±0.1μs       19.7±0.6μs     1.04  core.expand.TimeExpand.time_expand_complex_number_2
      17.2±0.04μs      17.4±0.02μs     1.01  core.expand.TimeExpand.time_expand_frac
       43.6±0.1μs       43.9±0.2μs     1.01  core.expand.TimeExpand.time_expand_log
      6.88±0.01μs      7.04±0.05μs     1.02  core.expand.TimeExpand.time_expand_modulus
      13.6±0.05μs      14.0±0.03μs     1.03  core.expand.TimeExpand.time_expand_negative_integers_powers
      14.0±0.02μs      14.0±0.04μs     1.00  core.expand.TimeExpand.time_expand_no_log
      18.6±0.04μs      19.1±0.08μs     1.03  core.expand.TimeExpand.time_expand_no_multinomial
       19.2±0.1μs       19.7±0.2μs     1.02  core.expand.TimeExpand.time_expand_non_commutative
          607±5ns          594±2ns     0.98  core.expand.TimeExpand.time_expand_nothing_todo
       18.1±0.3μs      18.4±0.08μs     1.01  core.expand.TimeExpand.time_expand_power_base
       24.7±0.3μs       24.7±0.1μs     1.00  core.expand.TimeExpand.time_expnad_radicals
      2.07±0.01ms      2.09±0.02ms     1.01  cse.TimeCSE.time_cse((2, 10))
      2.28±0.01ms      2.27±0.01ms     0.99  cse.TimeCSE.time_cse((2, 11))
      1.75±0.04ms      1.68±0.01ms     0.96  cse.TimeCSE.time_cse((2, 8))
      1.89±0.01ms      1.88±0.01ms     0.99  cse.TimeCSE.time_cse((2, 9))
         1.75±0ms      1.75±0.01ms     1.00  cse.TimeCSE.time_cse((3, 8))
      1.77±0.01ms      1.75±0.01ms     0.99  cse.TimeCSE.time_cse((4, 8))
       1.19±0.01s       1.18±0.01s     1.00  dsolve.TimeDsolve01.time_dsolve
          135±2ms        134±0.8ms     0.99  integrate.TimeIntegration01.time_doit
       60.9±0.2ms      60.5±0.09ms     0.99  integrate.TimeIntegration01.time_doit_meijerg
       27.7±0.1ms       28.8±0.3ms     1.04  integrate.TimeIntegrationRisch01.time_doit(1)
      40.4±0.05ms       42.0±0.5ms     1.04  integrate.TimeIntegrationRisch01.time_doit(10)
        503±0.4ms          506±1ms     1.01  integrate.TimeIntegrationRisch01.time_doit(100)
      28.4±0.06ms       28.1±0.1ms     0.99  integrate.TimeIntegrationRisch01.time_doit_risch(1)
       41.0±0.6ms       41.4±0.6ms     1.01  integrate.TimeIntegrationRisch01.time_doit_risch(10)
          504±1ms          505±1ms     1.00  integrate.TimeIntegrationRisch01.time_doit_risch(100)
      4.50±0.02μs      4.43±0.04μs     0.99  integrate.TimeIntegrationRisch02.time_doit(1)
        117±0.4ms        117±0.3ms     1.00  integrate.TimeIntegrationRisch02.time_doit(10)
       12.0±0.01s       12.0±0.02s     1.00  integrate.TimeIntegrationRisch02.time_doit(100)
      5.78±0.06μs      5.85±0.02μs     1.01  integrate.TimeIntegrationRisch02.time_doit_risch(1)
        116±0.5ms        116±0.3ms     1.00  integrate.TimeIntegrationRisch02.time_doit_risch(10)
       12.0±0.03s       12.0±0.01s     1.00  integrate.TimeIntegrationRisch02.time_doit_risch(100)
       42.3±0.6μs       42.8±0.7μs     1.01  integrate.TimeIntegrationRisch03.time_doit(1)
        170±0.7ms          173±2ms     1.02  integrate.TimeIntegrationRisch03.time_doit(10)
       2.39±0.01s       2.42±0.02s     1.01  integrate.TimeIntegrationRisch03.time_doit(100)
          599±8μs          591±4μs     0.99  integrate.TimeIntegrationRisch03.time_doit_risch(1)
          171±1ms          172±2ms     1.01  integrate.TimeIntegrationRisch03.time_doit_risch(10)
       2.39±0.01s       2.41±0.01s     1.01  integrate.TimeIntegrationRisch03.time_doit_risch(100)
       32.9±0.1ms       33.4±0.9ms     1.02  lambdify.TimeLambdifyCreation.time_lambdify_create(['math'])
       33.0±0.2ms       34.0±0.7ms     1.03  lambdify.TimeLambdifyCreation.time_lambdify_create(['numpy'])
      7.87±0.02μs      7.78±0.03μs     0.99  lambdify.TimeLambdifyEvaluate.time_lambdify_evaluate(['math'])
         60.2±2μs         60.0±3μs     1.00  lambdify.TimeLambdifyEvaluate.time_lambdify_evaluate(['numpy'])
            52.4M            52.7M     1.01  large_exprs.TimeLargeExpressionOperations.peakmem_jacobian_wrt_functions
            51.4M            51.7M     1.01  large_exprs.TimeLargeExpressionOperations.peakmem_jacobian_wrt_symbols
            51.2M            51.5M     1.01  large_exprs.TimeLargeExpressionOperations.peakmem_subs
      27.7±0.09ms      28.2±0.03ms     1.02  large_exprs.TimeLargeExpressionOperations.time_count_ops
       27.5±0.2ms       27.5±0.2ms     1.00  large_exprs.TimeLargeExpressionOperations.time_cse
      7.07±0.06ms      6.93±0.07ms     0.98  large_exprs.TimeLargeExpressionOperations.time_free_symbols
          1.25±0s          1.24±0s     1.00  large_exprs.TimeLargeExpressionOperations.time_jacobian_wrt_functions
       31.3±0.1ms       31.4±0.1ms     1.01  large_exprs.TimeLargeExpressionOperations.time_jacobian_wrt_symbols
          1.25±0s          1.24±0s     0.99  large_exprs.TimeLargeExpressionOperations.time_manual_jacobian_wrt_functions
          387±1ms        386±0.8ms     1.00  large_exprs.TimeLargeExpressionOperations.time_subs
          3.20±0s          3.19±0s     1.00  logic.LogicSuite.time_dpll
        128±0.5ms        142±0.7ms     1.11  logic.LogicSuite.time_dpll2
      21.4±0.09ms       21.4±0.1ms     1.00  logic.LogicSuite.time_load_file
        118±0.4μs        117±0.6μs     0.99  matrices.TimeDiagonalEigenvals.time_eigenvals
      7.01±0.04μs      6.87±0.03μs     0.98  matrices.TimeMatrixExpression.time_Add
       41.5±0.1μs       41.0±0.2μs     0.99  matrices.TimeMatrixExpression.time_MatAdd
       21.3±0.1ms       21.5±0.1ms     1.01  matrices.TimeMatrixExpression.time_MatAdd_doit
          372±1μs          375±1μs     1.01  matrices.TimeMatrixExpression.time_MatMul
      21.7±0.08ms      21.8±0.09ms     1.00  matrices.TimeMatrixExpression.time_MatMul_doit
      6.96±0.02μs      6.87±0.03μs     0.99  matrices.TimeMatrixExpression.time_Mul
        141±0.7μs        142±0.8μs     1.00  matrices.TimeMatrixGetItem.time_ImmutableDenseMatrix_getitem
        144±0.5μs        142±0.9μs     0.99  matrices.TimeMatrixGetItem.time_ImmutableSparseMatrix_getitem
        139±0.7μs        137±0.4μs     0.98  matrices.TimeMatrixGetItem.time_MutableDenseMatrix_getitem
          143±1μs        141±0.6μs     0.98  matrices.TimeMatrixGetItem.time_MutableSparseMatrix_getitem
+     2.46±0.01ms      7.34±0.04ms     2.98  matrices.TimeMatrixPower.time_Case1
-       320±0.2ms       95.4±0.7ms     0.30  matrices.TimeMatrixPower.time_Case2
-         456±7ms         95.6±2ms     0.21  matrices.TimeMatrixPower.time_Case3
      7.13±0.02ms      7.16��0.03ms     1.00  physics.mechanics.kane.KanesMethodMassSpringDamper.time_kanesmethod_mass_spring_damper
      21.6±0.09ms       21.7±0.2ms     1.00  physics.mechanics.lagrange.LagrangesMethodMassSpringDamper.time_lagrangesmethod_mass_spring_damper
          5.82±0s       5.93±0.01s     1.02  polygon.PolygonArbitraryPoint.time_bench01
          283±1μs        283±0.6μs     1.00  polygon.PolygonAttributes.time_area
         1.43±0ms         1.42±0ms     0.99  polygon.PolygonAttributes.time_centroid
      4.79±0.07ms      4.71±0.03ms     0.98  polygon.PolygonAttributes.time_create
         1.14±0ms         1.15±0ms     1.01  polygon.PolygonAttributes.time_perimeter
         1.16±0ms         1.14±0ms     0.98  polygon.PolygonAttributes.time_sides
          942±2ms          952±4ms     1.01  polygon.PolygonCutSection.time_bench01
        99.2±20ms         99.6±6ms     1.00  polygon.PolygonDistance.time_bench01
        111±0.2ms        135±0.1ms     1.21  polygon.PolygonEnclosesPoint.time_bench01
          731±2ms          737±3ms     1.01  polygon.PolygonFirstMoment.time_bench01
      40.5±0.08ms       40.6±0.1ms     1.00  polygon.PolygonIsConvex.time_bench01
      5.41±0.01ms      5.41±0.02ms     1.00  polygon.PolygonPolarSecondMoment.time_bench01
      5.37±0.02ms      5.37±0.02ms     1.00  polygon.PolygonSecondMoment.time_bench01
      7.45±0.02ms      7.42±0.02ms     1.00  polygon.PolygonSectionModulus.time_bench01
       76.0±0.2μs       76.5±0.2μs     1.01  polys.TimePolyManyGens.time_create_poly(1)
        114±0.6μs        115±0.6μs     1.01  polys.TimePolyManyGens.time_create_poly(10)
          985±3μs          986±5μs     1.00  polys.TimePolyManyGens.time_create_poly(100)
      17.0±0.04ms       16.9±0.1ms     0.99  polys.TimePolyManyGens.time_create_poly(500)
      2.52±0.02μs      2.46±0.02μs     0.97  polys.TimePolyManyGens.time_is_linear(1)
      29.6±0.09μs       29.0±0.1μs     0.98  polys.TimePolyManyGens.time_is_linear(10)
          790±5μs          786±3μs     1.00  polys.TimePolyManyGens.time_is_linear(100)
      16.4±0.05ms      16.2±0.07ms     0.99  polys.TimePolyManyGens.time_is_linear(500)
          119±1μs        114±0.9μs     0.96  solve.TimeMatrixArithmetic.time_dense_add(10, 0)
        122±0.8μs        120±0.5μs     0.98  solve.TimeMatrixArithmetic.time_dense_add(10, 5)
      15.5±0.09μs       15.3±0.1μs     0.99  solve.TimeMatrixArithmetic.time_dense_add(3, 0)
      18.2±0.05μs      18.3±0.06μs     1.00  solve.TimeMatrixArithmetic.time_dense_add(3, 5)
       23.6±0.2μs       23.2±0.1μs     0.98  solve.TimeMatrixArithmetic.time_dense_add(4, 0)
      27.4±0.09μs       27.1±0.2μs     0.99  solve.TimeMatrixArithmetic.time_dense_add(4, 5)
       46.6±0.2μs       45.0±0.4μs     0.97  solve.TimeMatrixArithmetic.time_dense_add(6, 0)
       51.3±0.3μs       50.1±0.2μs     0.98  solve.TimeMatrixArithmetic.time_dense_add(6, 5)
      1.63±0.01ms      1.59±0.01ms     0.98  solve.TimeMatrixArithmetic.time_dense_multiply(10, 0)
      1.90±0.01ms         1.88±0ms     0.99  solve.TimeMatrixArithmetic.time_dense_multiply(10, 5)
       62.4±0.6μs       61.1±0.4μs     0.98  solve.TimeMatrixArithmetic.time_dense_multiply(3, 0)
       94.9±0.2μs       95.7±0.5μs     1.01  solve.TimeMatrixArithmetic.time_dense_multiply(3, 5)
        130±0.8μs        127±0.5μs     0.98  solve.TimeMatrixArithmetic.time_dense_multiply(4, 0)
        210±0.9μs        211±0.8μs     1.00  solve.TimeMatrixArithmetic.time_dense_multiply(4, 5)
          388±3μs          376±3μs     0.97  solve.TimeMatrixArithmetic.time_dense_multiply(6, 0)
          567±4μs          562±2μs     0.99  solve.TimeMatrixArithmetic.time_dense_multiply(6, 5)
        137±0.7μs        137±0.5μs     0.99  solve.TimeMatrixOperations.time_det(3, 0)
          179±1μs          217±3μs     1.21  solve.TimeMatrixOperations.time_det(3, 2)
          185±1μs          212±3μs     1.14  solve.TimeMatrixOperations.time_det(3, 5)
         707±10μs         725±10μs     1.03  solve.TimeMatrixOperations.time_det(4, 0)
-     18.3±0.04ms      4.63±0.07ms     0.25  solve.TimeMatrixOperations.time_det(4, 2)
-      14.4±0.1ms      1.20±0.01ms     0.08  solve.TimeMatrixOperations.time_det(4, 5)
        137±0.6μs        137±0.5μs     1.00  solve.TimeMatrixOperations.time_det_bareiss(3, 0)
        174±0.3μs          215±2μs     1.23  solve.TimeMatrixOperations.time_det_bareiss(3, 2)
          180±3μs        207±0.7μs     1.15  solve.TimeMatrixOperations.time_det_bareiss(3, 5)
          702±4μs          715±2μs     1.02  solve.TimeMatrixOperations.time_det_bareiss(4, 0)
-      18.6±0.2ms      4.59±0.06ms     0.25  solve.TimeMatrixOperations.time_det_bareiss(4, 2)
-      14.7±0.1ms      1.18±0.01ms     0.08  solve.TimeMatrixOperations.time_det_bareiss(4, 5)
          138±2μs        136±0.2μs     0.99  solve.TimeMatrixOperations.time_det_berkowitz(3, 0)
          178±3μs        212±0.7μs     1.19  solve.TimeMatrixOperations.time_det_berkowitz(3, 2)
          185±3μs          208±1μs     1.13  solve.TimeMatrixOperations.time_det_berkowitz(3, 5)
          943±3μs          942±3μs     1.00  solve.TimeMatrixOperations.time_det_berkowitz(4, 0)
         1.10±0ms         1.11±0ms     1.01  solve.TimeMatrixOperations.time_det_berkowitz(4, 2)
      1.17±0.01ms      1.16±0.01ms     1.00  solve.TimeMatrixOperations.time_det_berkowitz(4, 5)
          348±1μs          353±2μs     1.02  solve.TimeMatrixOperations.time_rank(3, 0)
       69.3±0.5ms       59.8±0.2ms     0.86  solve.TimeMatrixOperations.time_rank(3, 2)
       35.1±0.2ms       29.3±0.2ms     0.83  solve.TimeMatrixOperations.time_rank(3, 5)
          559±6μs          561±2μs     1.00  solve.TimeMatrixOperations.time_rank(4, 0)
       70.5±0.1ms       64.2±0.2ms     0.91  solve.TimeMatrixOperations.time_rank(4, 2)
       80.3±0.4ms       64.1±0.2ms     0.80  solve.TimeMatrixOperations.time_rank(4, 5)
        142±0.4μs        155±0.2μs     1.09  solve.TimeMatrixOperations.time_rref(3, 0)
       39.4±0.1ms       31.5±0.2ms     0.80  solve.TimeMatrixOperations.time_rref(3, 2)
       75.3±0.2ms       60.4±0.1ms     0.80  solve.TimeMatrixOperations.time_rref(3, 5)
        291±0.9μs          320±1μs     1.10  solve.TimeMatrixOperations.time_rref(4, 0)
        104±0.4ms       78.0±0.2ms     0.75  solve.TimeMatrixOperations.time_rref(4, 2)
-         135±1ms       89.1±0.3ms     0.66  solve.TimeMatrixOperations.time_rref(4, 5)
       46.8±0.3ms       47.0±0.4ms     1.01  solve.TimeMatrixPositiveDefinite.time_A_is_positive_definite
       46.3±0.2ms       47.6±0.5ms     1.03  solve.TimeMatrixPositiveDefinite.time_A_sym_is_positive_definite
          249±1ms          250±3ms     1.00  solve.TimeMatrixSolve.time_solve('ADJ')
          561±2ms          654±7ms     1.17  solve.TimeMatrixSolve.time_solve('GE')
          917±5μs          913±8μs     1.00  solve.TimeMatrixSolve.time_solve('LU')
          199±7ms          196±1ms     0.99  solve.TimeMatrixSolve.time_solve_sym('ADJ')
          451±2ms          562±5ms     1.25  solve.TimeMatrixSolve.time_solve_sym('GE')
          914±4μs          945±4μs     1.03  solve.TimeMatrixSolve.time_solve_sym('LU')
      1.83±0.01ms      1.84±0.01ms     1.01  solve.TimeMatrixSolve2.time_LDLsolve
      1.65±0.01ms      1.65±0.01ms     1.00  solve.TimeMatrixSolve2.time_cholesky_solve
          910±4μs          917±8μs     1.01  solve.TimeMatrixSolve2.time_lusolve
          550±4μs          549±6μs     1.00  solve.TimeMatrixSolvePyDyFast.time_LUsolve(1)
          918±7μs         929±20μs     1.01  solve.TimeMatrixSolvePyDyFast.time_LUsolve(2)
      1.58±0.02ms         1.55±0ms     0.98  solve.TimeMatrixSolvePyDyFast.time_LUsolve(3)
         989±10μs          971±5μs     0.98  solve.TimeMatrixSolvePyDySlow.time_LDLsolve(1)
         886±10μs          877±6μs     0.99  solve.TimeMatrixSolvePyDySlow.time_cholesky_solve(1)
       46.4±0.5ms       46.4±0.2ms     1.00  solve.TimeMatrixSolvePyDySlow.time_linsolve(1)
       48.3±0.6ms       47.9±0.1ms     0.99  solve.TimeMatrixSolvePyDySlow.time_solve(1)
          366±2μs          378±6μs     1.03  solve.TimeRationalSystem.time_linsolve(1)
      15.3±0.07ms      15.2±0.03ms     0.99  solve.TimeRationalSystem.time_linsolve(10)
      1.40±0.01ms      1.45±0.02ms     1.03  solve.TimeRationalSystem.time_linsolve(3)
      3.39±0.02ms      3.40±0.01ms     1.00  solve.TimeRationalSystem.time_linsolve(5)
      1.21±0.01ms      1.20±0.01ms     0.99  solve.TimeRationalSystem.time_solve(1)
       49.7±0.8ms       49.8±0.9ms     1.00  solve.TimeRationalSystem.time_solve(10)
      5.76±0.04ms      5.58±0.04ms     0.97  solve.TimeRationalSystem.time_solve(3)
       13.6±0.3ms      13.3±0.06ms     0.98  solve.TimeRationalSystem.time_solve(5)
          945±5μs         982±20μs     1.04  solve.TimeRationalSystemSymbol.time_linsolve(1)
      4.08±0.03ms      4.06±0.02ms     0.99  solve.TimeRationalSystemSymbol.time_linsolve(3)
      10.6±0.02ms      10.6±0.03ms     1.00  solve.TimeRationalSystemSymbol.time_linsolve(5)
         1.30±0ms      1.29±0.01ms     0.99  solve.TimeRationalSystemSymbol.time_solve(1)
      6.01±0.02ms      6.00±0.02ms     1.00  solve.TimeRationalSystemSymbol.time_solve(3)
      13.8±0.06ms       13.9±0.3ms     1.00  solve.TimeRationalSystemSymbol.time_solve(5)
       38.7±0.3ms       38.9±0.5ms     1.01  solve.TimeSolve01.time_solve
       38.5±0.2ms       39.3±0.5ms     1.02  solve.TimeSolve01.time_solve_nocheck
              n/a              n/a      n/a  solve.TimeSolveLinSys.time_solve_lin_sys
              n/a              n/a      n/a  solve.TimeSolveLinSys.time_to_expr_eqs
              n/a              n/a      n/a  solve.TimeSolveLinSys.time_verify_sol
              n/a              n/a      n/a  solve.TimeSolveLinSys10x8.time_solve_lin_sys
              n/a              n/a      n/a  solve.TimeSolveLinSys10x8.time_to_expr_eqs
              n/a              n/a      n/a  solve.TimeSolveLinSys10x8.time_verify_sol
              n/a              n/a      n/a  solve.TimeSolveLinSys165x165.time_solve_lin_sys
              n/a              n/a      n/a  solve.TimeSolveLinSys165x165.time_to_expr_eqs
              n/a              n/a      n/a  solve.TimeSolveLinSys165x165.time_verify_sol
       57.4±0.2ms       59.1±0.4ms     1.03  solve.TimeSolveLinSys189x49.time_solve_lin_sys
       56.3±0.3ms       56.8±0.5ms     1.01  solve.TimeSolveLinSys189x49.time_to_expr_eqs
          249±1ms        251±0.5ms     1.01  solve.TimeSolveLinSys189x49.time_verify_sol
       13.7±0.3ms      13.2±0.09ms     0.96  solve.TimeSolveSparsePolySystem.time_solve(1)
       27.3±0.3ms       26.9±0.1ms     0.98  solve.TimeSolveSparsePolySystem.time_solve(2)
       41.3±0.6ms       40.6±0.2ms     0.98  solve.TimeSolveSparsePolySystem.time_solve(3)
      1.26±0.01ms         1.25±0ms     0.99  solve.TimeSparseSystem.time_linear_eq_to_matrix(10)
      3.82±0.01ms      3.81±0.02ms     1.00  solve.TimeSparseSystem.time_linear_eq_to_matrix(20)
      7.76±0.03ms      7.69±0.02ms     0.99  solve.TimeSparseSystem.time_linear_eq_to_matrix(30)
       21.2±0.2ms       21.1±0.1ms     0.99  solve.TimeSparseSystem.time_linsolve_Aaug(10)
       56.2±0.3ms         56.4±1ms     1.00  solve.TimeSparseSystem.time_linsolve_Aaug(20)
        107±0.4ms          107±1ms     1.00  solve.TimeSparseSystem.time_linsolve_Aaug(30)
       21.0±0.1ms       20.8±0.1ms     0.99  solve.TimeSparseSystem.time_linsolve_Ab(10)
       55.7±0.2ms       55.8±0.3ms     1.00  solve.TimeSparseSystem.time_linsolve_Ab(20)
        106±0.5ms        105±0.7ms     0.99  solve.TimeSparseSystem.time_linsolve_Ab(30)
      8.97±0.02ms      8.97±0.03ms     1.00  solve.TimeSparseSystem.time_linsolve_eqs(10)
      24.8±0.09ms      24.9±0.07ms     1.00  solve.TimeSparseSystem.time_linsolve_eqs(20)
       47.8±0.1ms       47.7±0.1ms     1.00  solve.TimeSparseSystem.time_linsolve_eqs(30)
      28.2±0.07ms       28.0±0.2ms     0.99  solve.TimeSparseSystem.time_solve(10)
       56.8±0.1ms       56.6±0.6ms     1.00  solve.TimeSparseSystem.time_solve(20)
       85.8±0.2ms         86.3±1ms     1.01  solve.TimeSparseSystem.time_solve(30)
          169±1ms          168±1ms     1.00  sum.TimeSum.time_doit
```

**Pull request merged**
