### PR TITLE
Use matplotlib < 3.2 on Travis.

### PR DESCRIPTION
**Pull request by moorepants**
- https://github.com/sympy/sympy/issues/19051

#### Brief description of what is fixed or changed

There is a regression in matplotlib 3.2 that causes SymPy plotting to return incorrect results. See:

https://github.com/matplotlib/matplotlib/issues/17004

This PR sets matplotlib on Travis to be less than version 3.2 until this issue is resolved.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
It seems I misdiagnosed the problem which is in fact now fixed by #19086. Now that Travis builds successfully I'm not sure there is a need to pin the matplotlib version rather than fix the actual issue that we need to fine a replacement for `set_smart_bounds` before matplotlib 3.4.

**Comment by moorepants** [comment]
This would at least let the dev docs build correctly.

Yes, we should find an alternative for set_smart_bounds since they are going to deprecate, but it seems that matplotlib's output has changed from 3.1 to 3.2 irrespective of the set_smart_bounds deprecation warning. So there are those two distinct issues to deal with.

**Comment by tacaswell** [comment]
It would be better to add an explicit `ax.autoscale` to sympy.

**Comment by moorepants** [comment]
I think we should merge this for the time being.

**Comment by jksuom** [comment]
I agree. #19088 may be useful but it does not seem to fix this.

**Pull request merged**
