### PR TITLE
Fix round function for precision over 15 decimals

### LINKED ISSUE #12056: round for Float loses precision
The `__round__` method on `Float` uses `float`, which causes it to lose precision.

### PR DESCRIPTION
**Pull request by barun511**
Fixes #12056

### CODE REVIEW

**Comment by barun511** [comment]
This is a work in progress PR, because I haven't added tests.

**Comment by Scrypy** [comment]
Hi @barun511 . I'm trying to help and learn here.
I think your solution has bugs. I've done this tests:

```python
assert round(sp.pi.evalf(), 5) == round(math.pi, 5)
assert round(sp.pi.evalf(100), 5) == 3.14159
assert round(sp.pi.evalf(100), 4) == 3.1416
assert round(2.314855, 5) == 2.31486
assert round(0.0001, 2) == 0.0
assert round(0.000, 2) == 0.0
assert round(1.999, 2) == 2.0
assert round(1.999) == 2
assert round(sp.Float(0.54345), 4) == 0.5435
assert round(sp.Float(-1.835), 2) == -1.84
assert round(sp.Float(-0.001), 2) == 0.0
assert round(sp.Float(-0.991), 2) == -0.99
assert round(sp.Float(-0.992), 1) == -1
assert round(sp.Float(-0.999), 2) == -1
```

and your function fails in number 9 and 10. I would do something like:

```python
def __round__(self, *args):
        if (len(args) == 0):
            precision = 0
        else:
            precision = args[0]
        rounded = Float(self) * (10 ** precision)
        sign = 1
        if rounded < 0:
            sign = -1
            rounded = -rounded
        if abs(rounded - int(rounded)) >= abs(int(rounded) + 1 - rounded):
            rounded = int(rounded) + 1
        else:
            rounded = int(rounded)
        rounded = rounded / (10 ** precision)
        if precision < 14:
            rounded = float(rounded)
        return rounded * sign
```

This one passes the tests I've done, but I'm not sure if it is efficient enough for the liking of the people in this project.

**Comment by barun511** [comment]
Thanks for the help! If you like, I'll close this PR and you can open one :)

**Comment by Scrypy** [comment]
My problem is that I don't know how to handle the problem with versions of Python prior to 3 in the tests. Aaron said "only Python 3 supports returning a non-float from `round` [...] this will need to be accounted for in the tests". If I do a PR I will get stuck without knowing what to do with this.

**Comment by asmeurer** [comment]
Make the test check `PY3` (from `sympy.core.compatibility`) and only run if it is True.

**Comment by Scrypy** [comment]
I've read the doc for `round` in Python 3.x and now I understand @barun511 's function is actually intended to round towards even numbers. I didn't know about this method of rounding.

@asmeurer thanks for the clarification. The test runs only if PY3 is True, but what happens if somebody is using sympy in Python 2.x and calls `round`?🤔

**Comment by czgdp1807** [comment]
@barun511 Thanks for the contribution. 
I think the associated issue is fixed by https://github.com/sympy/sympy/pull/16608 so closing this PR.

**Pull request closed without merging**
