### PR TITLE
Fixed compute_expectation to use non-sympify parameters

### LINKED ISSUE #8248: PSpace cannot integrate an `int`
While pspaces can integrate a symbolic integer (`Integer`), they cannot integrate a pythonic integer (`int`). Example:

``` python
In [4]: p = Poisson('p', 3)

In [5]: p.pspace.integrate(1)
```

raises

``` pytb
Traceback (most recent call last):
  File "<ipython-input-5-f408d8c9c5ad>", line 1, in <module>
    p.pspace.integrate(1)
  File "sympy/stats/drv.py", line 113, in integrate
    expr = expr.xreplace(dict((rv, rv.symbol) for rv in rvs))
AttributeError: 'int' object has no attribute 'xreplace'
```

I guess that since `Expr` has `xreplace`, this `AttributeError` should be caught, and the conclusion should be that the argument is not an `Expr`, and if it is `Expr`-friendly (python `int`', `float`, etc.), it should be casted into one (perhaps via `S(1)` or so).

### PR DESCRIPTION
**Pull request by Smit-create**
Fixed compute_expectation to use non-sympify parameters
#### References to other Issues or PRs

Fixes #8248

#### Brief description of what is fixed or changed
Before fixing:
```
>>> from sympy.stats import *
>>> Poisson('p', 3).pspace.compute_expectation(1)
Traceback (most recent call last):
  ...
AttributeError: 'int' object has no attribute 'xreplace'
```

After fixing:
```
>>> from sympy.stats import *
>>> Poisson('p', 3).pspace.compute_expectation(1)
1
```

#### Release Notes

* stats
  * sympify expression in compute_expectation

### CODE REVIEW

**Comment by smichr** [comment]
Can you add tests for the other places that are anticipated to have this problem, the other places where you added `_sympify`?

**Review by smichr — CHANGES_REQUESTED** [review]
additional tests needed for other places that `_sympify` was added

**Comment by Smit-create** [comment]
Yes, adding them too.

**Comment by oscarbenjamin** [comment]
Is compute_expectation a public API? I thought the idea was to do `E(x)`.

**Comment by Smit-create** [comment]
`compute_expectation` is an internal method not public. You are correct, it is accessed through `E(x)`

**Comment by oscarbenjamin** [comment]
> `compute_expectation` is an internal method not public. You are correct, it is accessed through `E(x)`

Then why does it need to accept unsympified inputs?

**Comment by Smit-create** [comment]
`E(x)` calls compute_expectation of the expression only when there are random variables present in it, so previously sympify was not used.
Here when `rv.pspace.compute_expectation(1)` is used, it has no random variables hence we need to use sympify.

**Comment by oscarbenjamin** [comment]
I have no objection to anyone else merging this but in general I think that we should use sympify at the "boundaries" where user input is received. It shouldn't be necessary to use sympify in internal functions unless there is some particular reason why non-sympy types might be used internally.

**Comment by Smit-create** [comment]
I will avoid using sympify in internal methods,  where there is no direct input. Thanks for the review @oscarbenjamin

**Comment by smichr** [comment]
5 changes but only 3 tests. Please add 2 more tests.

**Comment by Smit-create** [comment]
The other  2 changes I have made are in `FiniteSpace` and `ContinuousPSpace`, and they are inherited by `SingleFinitePSpace` and `SingleContinuousPSpace` for which I have added the test cases.  I haven't find random variables of `ContinuousPSpace` , `FinitePSpace` directly accessing them as they are used mostly in internal computation like conditional space.

**Comment by smichr** [comment]
> as they are used mostly in internal computation like conditional space.

Is sympify needed in these cases, then, or should the sympify be in the function that calls them?

**Comment by Smit-create** [comment]
> Is sympify needed in these cases, then, or should the sympify be in the function that calls them?

They are called with the expressions containing the random variables only, so we could remove `sympify` in them. Should I remove them in other 2 methods?

**Comment by Smit-create** [comment]
@oscarbenjamin @smichr Is this good now?

**Review by smichr — APPROVED** [review]

**Comment by smichr** [comment]
Looks good.

**Comment by Smit-create** [comment]
Thanks @smichr

**Pull request merged**
