### PR TITLE
Fixed nthroot_mod to work with composite numbers

### PR DESCRIPTION
**Pull request by risubaba**
Change `p-1` to `totient(p)` to accommodate composite numbers
#### References to other Issues or PRs

Fixes #17373 
Fixes #17377 

#### Brief description of what is fixed or changed
`totient(p) = p - 1` for prime numbers
All `p - 1` have been changed to `totient(p)` , this helps give proper output when p is composite

#### Release Notes

* ntheory
  * Modified residue functions to work with composite numbers.

### CODE REVIEW

**Comment by risubaba** [comment]
I have tested for many different cases and answers are correct for all of them. Is there anything else that should be done?

**Comment by smichr** [comment]
See how the failing test results need to be modified (if at all): `solveset(Mod(x**4, 9) - 4, x, S.Integers)` fails to give the expected result.

**Comment by risubaba** [comment]
`Attribute 'integers' was not installed on SymPy registry S`
I am getting this error.

**Comment by risubaba** [comment]
@jksuom could you please tell why I am getting this error?

**Comment by jksuom** [comment]
It seems that some algorithms expect that `p` is a prime. Changing `p - 1` to `totient(p)` does not necessarily make them work for general `p`.
```
>>> list(_primitive_root_prime_iter(9))
[2, 3, 5, 6]
>>> [2**i % 9 for i in range(6)]
[1, 2, 4, 8, 7, 5]
>>> [3**i % 9 for i in range(6)]
[1, 3, 0, 0, 0, 0]
>>> [5**i % 9 for i in range(6)]
[1, 5, 7, 8, 4, 2]
>>> [6**i % 9 for i in range(6)]
[1, 6, 0, 0, 0, 0]
```
Only 2 and 5 are primitive roots mod 9.

**Comment by risubaba** [comment]
Thanks for pointing this out. Should i add function for calculating primitive root of composite numbers.

**Comment by jksuom** [comment]
Primitive roots need not exist for composite numbers. Even if they exist, they do not give a complete solution for the nth root problem as many numbers are not powers of primitive roots mod m. An efficient general nth root algorithm is more complicated than `nthroot_mod`.

**Comment by jksuom** [comment]
To extend the scope of `nthroot_mod`, I would first consider odd prime power moduli. Then primitive roots always exist and the nth-root residues can be found with reasonable efficiency. Powers of 2 are harder as a primitive root exists only for 2 and 4. Finding the nth-root residues for higher powers of 2 will be more complicated. For general composite numbers I would apply the Chinese remainder theorem.

**Comment by risubaba** [comment]
So as a temporary fix should we keep a primality test for the modulo or try to create primitive roots and check if they do indeed satisfy the equation. Also for the general implementation that you are talking about i would like to work on that and extend the overall scope of the function

**Comment by jksuom** [comment]
I would now add a test for `p` and raise ValueError if it is not prime. That can be removed later when the algorithm has been extended to work with more general moduli.

**Comment by risubaba** [comment]
Sure I would do that. I want to work on extending the scope of the function for composite numbers. Can i do that?

**Comment by risubaba** [comment]
I would need to change some tests such as the one above. Am I allowed to change/remove existing tests?

**Comment by jksuom** [comment]
> Am I allowed to change/remove existing tests?

The test can be changed, for example, if the result is wrong or has a new format.

**Comment by risubaba** [comment]
Closed in favour of #18194. 
Please tell if this was wrong to stop work here and continue on a new PR. 
I did this as the method followed was different.

**Pull request closed without merging**
