### PR TITLE
Simplification of an expression with exponent containing assumption symbol

### LINKED ISSUE #10195: Simplification bug on alternating series.
Hi!
```python
from sympy import *
n = Symbol('n', odd=true, nonzero=true)
x = (-1)**(n/2 - Rational(1,2)) - (-1)**(3*n/2 - Rational(1,2))
print( x.subs(n,1)) # 2
print( x.subs(n,3)) # -2
print( x.subs(n,5)) # 2
print(simplify(x)) # -> 2 bug
```
I think this should be considered a bug.

### PR DESCRIPTION
**Pull request by gxyd**
I don't know if these are the best changes but these seem to work good. On the basis of assumptions on symbols provided.

(As a side note: i have not seen skirpichev's commit code, so if there is any similarity in code, then that is a mere coincidence)

fixes #10195 
Also i am first time making a PR on github "itself".

[Edit]: Also no need to make `n = Symbol('n', odd=True)` with `nonzero=True`, i.e is automatically true.

### CODE REVIEW

**Comment by gxyd** [comment]
@jksuom please review.

**Comment by jksuom** [comment]
Seems a good solution to me. The simplify logic appears quite involved, and I was wondering why ``c`` would be Rational if it is not 1. But maybe that is always so?

**Comment by gxyd** [comment]
Sorry, i don't know if i understood your comment clearly, but if i did then: in the added `test-cases` we have `c` is already a `Rational` and `is not S.One` for example in  `(-1)**(n/2)` we have `c = 1/2` and `m = n`, so `c` is a Rational and `is not 1`.
Did i missed something?

**Comment by jksuom** [comment]
I was too lazy to analyse the whole simplification process to see why at that point we should have either ``c == 1`` or ``c.is_Rational`` and not ``c`` an integer different from 1. But I guess that must be so, since otherwise we should have seen attribute errors long time ago (for ``c.p`` and ``c.q``). So there is probably no need to test if a ``c`` different from 1 is a true Rational. I was only thinking that maybe you would have an explanation for this.

**Comment by gxyd** [comment]
I don't have any explanation (apart from the one you listed).

**Comment by jksuom** [comment]
Thanks, I think this is ready then. Merging..

**Comment by gxyd** [comment]
Thanks @jksuom

**Pull request merged**
