### PR TITLE
Remove unreachable part of code

### PR DESCRIPTION
**Pull request by namannimmo10**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by namannimmo10** [comment]
@sylee957 @oscarbenjamin Is it ready to be merged?

**Comment by smichr** [comment]
Although we dropped Python 2 from testing on Travis, support for it hasn't been removed in the codebase. I'm not sure that this should be committed yet. @oscarbenjamin will know.

**Comment by oscarbenjamin** [comment]
> Although we dropped Python 2 from testing on Travis, support for it hasn't been removed in the codebase. I'm not sure that this should be committed yet. @oscarbenjamin will know.

Python 2 support can be removed in full now. There is a test on Travis that tries to import sympy under Python 2 to check for the ImportError message. That test was preventing Python 3 only syntax (because it also called compileall) but I fixed that in a recent PR so it should be possible to merge Python 3 only syntax now and there is no need to worry any more about Python 2 compatibility in the codebase.

**Comment by namannimmo10** [comment]
Yeah, I removed python 2 related things from compatibility in [this](https://github.com/sympy/sympy/pull/18286) PR. 
> Python 2 support can be removed in full now

If this is the case, then we can merge this.

**Comment by namannimmo10** [comment]
Ping @oscarbenjamin @smichr

**Pull request merged**
