### PR TITLE
Fixed issue #16140

### LINKED ISSUE #16140: subs method doesn't work with a partial derivative
from sympy import *

x, y = symbols("x,y")
a, b = Function("a")(x,y),  Function("b")(x,y)
U = Function("U")(a,b)

from sympy import diff as D

#this doesn't work
( D(U,x) ).subs( D(U,a), 0 )

#Note, however:
In [1]   (D(U,x)).args[0].args[1] == D(U,a)
Out[1]   True

### PR DESCRIPTION
**Pull request by stunn-areeb09**
#### References to other Issues or PRs

#Fixes #16140 

#### Brief description of what is fixed or changed
Subs now works correctly with partial derivative.

#### Release Notes

* core
    * subs now work correctly on partial derivatives

### CODE REVIEW

**Comment by Abdullahjavednesar** [comment]
See how to write [PR title](https://github.com/sympy/sympy/wiki/Development-workflow#writing-pull-request-title-and-description).

**Comment by Naba7** [comment]
Tests are failing because you have changed some variables and omitted some dashes according to prettyprint . Run tests locally as in ``./bin/test`` for checking all the modules. For code-quality check ``./bin/test quality``.If you want to check for only one particular module 
```
cd sympy/
python
import sympy
sympy.test("_module_name")
```

**Comment by Syed-Areeb-Wadood** [comment]
@asmeurer Can you have a look here? I do not why doctest is failing.

**Comment by oscarbenjamin** [comment]
If you look in the test logs you can see that these are the failures:
```
_____________________ sympy.diffgeom.diffgeom.Differential _____________________
File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/diffgeom/diffgeom.py", line 706, in sympy.diffgeom.diffgeom.Differential
Failed example:
    pprint(dg(e_x))
Expected:
    /  d              \|
    |-----(g(xi_1, y))||
    \dxi_1            /|xi_1=x
Got:
    / d           \|    
    |---(g(xi, y))||    
    \dxi          /|xi=x
**********************************************************************
File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/diffgeom/diffgeom.py", line 710, in sympy.diffgeom.diffgeom.Differential
Failed example:
    pprint(dg(e_y))
Expected:
    /  d              \|
    |-----(g(x, xi_2))||
    \dxi_2            /|xi_2=y
Got:
    / d           \|    
    |---(g(x, xi))||    
    \dxi          /|xi=y
________________________________________________________________________________
___________________ sympy.diffgeom.diffgeom.BaseVectorField ____________________
File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/diffgeom/diffgeom.py", line 537, in sympy.diffgeom.diffgeom.BaseVectorField
Failed example:
    pprint(v(s_field))
Expected:
    /  d              \|
    |-----(g(x, xi_2))||
    \dxi_2            /|xi_2=y
Got:
    / d           \|    
    |---(g(x, xi))||    
    \dxi          /|xi=y
**********************************************************************
File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/diffgeom/diffgeom.py", line 545, in sympy.diffgeom.diffgeom.BaseVectorField
Failed example:
    pprint(v(s_field).rcall(point_p))
Expected:
    /  d                           \|
    |-----(g(r0*cos(theta0), xi_2))||
    \dxi_2                         /|xi_2=r0*sin(theta0)
Got:
    / d                        \|                 
    |---(g(r0*cos(theta0), xi))||                 
    \dxi                       /|xi=r0*sin(theta0)
```

These tests are failing just because the output has changed. The new output is equivalent but has a different name for the dummy symbols. You can fix this by updating the doctests so that the outpu reflects what is returned with this patch.

First investigate those examples though. Should they come out like that? Isn't this patch supposed to mean that they come out different?

**Comment by oscarbenjamin** [comment]
Can you also give the PR a better title? The release note has a better wording than the title.

**Comment by czgdp1807** [comment]
@Syed-Areeb-Wadood Thanks for the contributions. Are you still working on this issue? Can you please look into the test failures.

**Comment by czgdp1807** [comment]
Closing this in favour https://github.com/sympy/sympy/pull/18326

**Pull request closed without merging**
