### PR TITLE
cse : added condition for Tuples containing matrices

### LINKED ISSUE #14118: cse fails when given matrices in a Tuple
Originally reported by @stewpend0us [here](https://github.com/bjodah/sympy/pull/2):
```python
>>> x0 = Symbol('x0')
>>> m1, m2 = Matrix([[x, sin(y)],[3, 4]]), Matrix([[sin(y), 2*sin(y)], [sin(y)**2, 7]])
>>> t = Tuple(m1, m2)  # the error only occurs then wrapping these in tuple, e.g. list is fine
>>> cse(t)
...
TypeError: Data type not understood
```
note that this works as expected:
```python
>>> cse(list(t))
⎛                ⎡         ⎡x₀   2⋅x₀⎤⎤⎞
⎜                ⎢⎡x  x₀⎤  ⎢         ⎥⎥⎟
⎜[(x₀, sin(y))], ⎢⎢     ⎥, ⎢  2      ⎥⎥⎟
⎝                ⎣⎣3  4 ⎦  ⎣x₀    7  ⎦⎦⎠
```

### PR DESCRIPTION
**Pull request by jashan498**
Fixes #14118

Whenever any `Matrix` is passed inside `cse`, it gets flattened [here](https://github.com/sympy/sympy/blob/53bf458a0a03d7d9611c8850afaf5803e6d0ce63/sympy/simplify/cse_main.py#L692). But [this](https://github.com/sympy/sympy/blob/53bf458a0a03d7d9611c8850afaf5803e6d0ce63/sympy/simplify/cse_main.py#L688) converted the `Tuple`(a `basic` class instance) into a list containing those tuples. So iterating object inside the loop was a `Tuple` indeed rather than matrices. Hence they never entered into the condition which flattened matrices.

I just added a check to avoid that (also there is no need to convert those Tuple instances into a list as `tree_cse` can take them as an argument as it is).

### CODE REVIEW

**Comment by smichr** [comment]
This seems to leave too many corner cases open. What about this:

```
cse(Dict((Matrix(((x**2,2), (x**2,3))), 1)))
```

Explicit is better than implicit: test for what you can handle (Tuple, MatrixBase) and raise an error if you don't get those (or figure out a general way to handle any SymPy object).

**Comment by jashan498** [comment]
@smichr I didn't quite understand the usage of `Dict` inside `cse`(like what is the function of keys here?).

Can you give more examples of corner cases(i tried to be specific to `Tuple` containing matrices only)? 
  For now, i can only think of nested tuples containing matrices as a failing case but `cse` is supposed to take expressions(or an iteration of expressions) right?

**Comment by jashan498** [comment]
One way for nested `Tuple`s containing matrices can be breaking of all the matrices into its constituent expressions before the `if` block?

**Comment by smichr** [comment]
cse should accept either Expr or a finite iterable but the initial test is for Basic and MatrixBase. The Dict example that I gave is a Basic type so it is a corner case. (And I do see that this preceded your modifications.) How about recasting iterables as list from the outset -- this will also do what should have been done which is convert Tuple to list rather than treating it like an expression.

Initial changes are cosmetic:

```
diff --git a/sympy/simplify/cse_main.py b/sympy/simplify/cse_main.py
index cdbab4f..4f34feb 100644
--- a/sympy/simplify/cse_main.py
+++ b/sympy/simplify/cse_main.py
@@ -2,7 +2,7 @@
 """
 from __future__ import print_function, division
 
-from sympy.core import Basic, Mul, Add, Pow, sympify, Symbol
+from sympy.core import Expr, Basic, Mul, Add, Pow, sympify, Symbol
 from sympy.core.containers import Tuple, OrderedSet
 from sympy.core.singleton import S
 from sympy.core.function import _coeff_isneg
@@ -13,8 +13,9 @@
 
 from . import cse_opts
 
+
 # (preprocessor, postprocessor) pairs which are commonly useful. They should
-# each take a sympy expression and return a possibly transformed expression.
+# each take a SymPy expression and return a possibly transformed expression.
 # When used in the function ``cse()``, the target expressions will be transformed
 # by each of the preprocessor functions in order. After the common
 # subexpressions are eliminated, each resulting expression will have the
@@ -97,14 +98,14 @@ def preprocess_for_cse(expr, optimizations):
 
     Parameters
     ----------
-    expr : sympy expression
+    expr : SymPy expression
         The target expression to optimize.
     optimizations : list of (callable, callable) pairs
         The (preprocessor, postprocessor) pairs.
 
     Returns
     -------
-    expr : sympy expression
+    expr : SymPy expression
         The transformed expression.
     """
     for pre, post in optimizations:
@@ -115,11 +116,11 @@ def preprocess_for_cse(expr, optimizations):
 
 def postprocess_for_cse(expr, optimizations):
     """ Postprocess an expression after common subexpression elimination to
-    return the expression to canonical sympy form.
+    return the expression to canonical SymPy form.
 
     Parameters
     ----------
-    expr : sympy expression
+    expr : SymPy expression
         The target expression to transform.
     optimizations : list of (callable, callable) pairs, optional
         The (preprocessor, postprocessor) pairs.  The postprocessors will be
@@ -128,7 +129,7 @@ def postprocess_for_cse(expr, optimizations):
 
     Returns
     -------
-    expr : sympy expression
+    expr : SymPy expression
         The transformed expression.
     """
     for pre, post in reversed(optimizations):
@@ -375,7 +376,7 @@ def opt_cse(exprs, order='canonical'):
 
     Parameters
     ----------
-    exprs : list of sympy expressions
+    exprs : list of SymPy expressions
         The expressions to optimize.
     order : string, 'none' or 'canonical'
         The order by which Mul and Add arguments are processed. For large
@@ -471,7 +472,7 @@ def tree_cse(exprs, symbols, opt_subs=None, order='canonical', ignore=()):
     Parameters
     ==========
 
-    exprs : list of sympy expressions
+    exprs : list of SymPy expressions
         The expressions to reduce.
     symbols : infinite iterator yielding unique Symbols
         The symbols used to label the common subexpressions which are pulled
@@ -613,7 +614,7 @@ def cse(exprs, symbols=None, optimizations=None, postprocess=None,
     Parameters
     ==========
 
-    exprs : list of sympy expressions, or a single sympy expression
+    exprs : list of SymPy expressions, or a single SymPy expression
         The expressions to reduce.
     symbols : infinite iterator yielding unique Symbols
         The symbols used to label the common subexpressions which are pulled
@@ -646,7 +647,7 @@ def cse(exprs, symbols=None, optimizations=None, postprocess=None,
         All of the common subexpressions that were replaced. Subexpressions
         earlier in this list might show up in subexpressions later in this
         list.
-    reduced_exprs : list of sympy expressions
+    reduced_exprs : list of SymPy expressions
         The reduced expressions with all of the replacements above.
 
     Examples
@@ -665,7 +666,7 @@ def cse(exprs, symbols=None, optimizations=None, postprocess=None,
     List of expressions with recursive substitutions:
 
     >>> m = SparseMatrix([x + y, x + y + z])
-    >>> cse([(x+y)**2, x + y + z, y + z, x + z + y, m])
+    >>> cse([(x + y)**2, x + y + z, y + z, x + z + y, m])
     ([(x0, x + y), (x1, x0 + z)], [x0**2, x1, y + z, x1, Matrix([
     [x0],
     [x1]])])
@@ -683,9 +684,13 @@ def cse(exprs, symbols=None, optimizations=None, postprocess=None,
     from sympy.matrices import (MatrixBase, Matrix, ImmutableMatrix,
                                 SparseMatrix, ImmutableSparseMatrix)
 
-    # Handle the case if just one expression was passed.
-    if isinstance(exprs, (Basic, MatrixBase)):
+    # sanitize input
+    if isinstance(exprs, (Expr, MatrixBase)):
         exprs = [exprs]
+    elif iterable(exprs):
+        exprs = list(exprs)
+    else:
+        raise TypeError('unrecognized input')
 
     copy = exprs
     temp = []
diff --git a/sympy/simplify/tests/test_cse.py b/sympy/simplify/tests/test_cse.py
index 41edc36..6a086ec 100644
--- a/sympy/simplify/tests/test_cse.py
+++ b/sympy/simplify/tests/test_cse.py
@@ -288,8 +288,8 @@ def test_issue_4499():
         [(x0, 2*a), (x1, -b), (x2, x0 + x1), (x3, x2 + 1), (x4, sqrt(z)), (x5,
         B(b - 1, x4)), (x6, -x0), (x7, (x4/2)**(x6 + 1)*G(b)*G(x3)), (x8,
         x7*B(x2, x4)), (x9, B(b, x4)), (x10, x7*B(x3, x4))],
-        [(a, a + 1/2, x0, b, x3, x5*x8, x4*x8*x9, x10*x4*x5, x10*x9,
-        1, 0, 1/2, z/2, x1 + 1, b + x6, x6)])
+        [a, a + 1/2, x0, b, x3, x5*x8, x4*x8*x9, x10*x4*x5, x10*x9,
+        1, 0, 1/2, z/2, x1 + 1, b + x6, x6])
     assert ans == c
```

**Comment by jashan498** [comment]
@smichr I would say yours one is much neater. But before I commit these changes, how about doing:
```
    # sanitize input
    if isinstance(exprs, (Expr, MatrixBase)):
        exprs = [exprs]
    elif iterable(exprs):
        if any((iterable(e) and not(isinstance(e, (Matrix, ImmutableMatrix,
                        SparseMatrix, ImmutableSparseMatrix)))) for e in exprs):
            raise TypeError('Iterration of expressions is expected')
        exprs = list(exprs)
    else:
        raise TypeError('unrecognized input')
```
Thus adding a check for cases like `cse(Tuple(Tuple(x+y), x, x-y))` or am i overthinking?

**Comment by smichr** [comment]
> or am i overthinking?

You are probably asking the wrong guy LOL :-) I think what you have makes sense, eliminating more corners. I would only suggest:

```
# sanitize input
    if isinstance(exprs, (Expr, MatrixBase)):
        exprs = [exprs]
    elif iterable(exprs) and not any(
            iterable(e, exclude=MatrixBase) for e in exprs):
        exprs = list(exprs)
    else:
        raise TypeError('unrecognized input')
```

**Comment by jashan498** [comment]
I made these changes(I raised an error instead of `exprs=None` because otherwise `None`  gives error when we have to iterate over exprs):
```
elif iterable(exprs):
        exprs = list(exprs)
        if any((iterable(e) and not isinstance(e, MatrixBase)) for e in exprs):
            raise TypeError('Only expression iterations allowed')
```
Actually applying `Tuple` on `Matrix` makes it `ImmutableDenseMatrix`: 
```
>>> [type(e) for e in Tuple(Matrix())]
[<class 'sympy.matrices.immutable.ImmutableDenseMatrix'>]

```
and `iterable(ImmutableDenseMatrix(), exclude=MatrixBase) = True`

**Comment by jashan498** [comment]
@smichr I opened separate PR #14150 which is needed to be merged earlier to allow this one to go further. 
I didn't make those changes in this one because it dealt with different files (and also I think this one can be worked out even if other is not merged). So should I close this PR for now or wait for the other one to merge/close?

**Comment by smichr** [comment]
> So should I close this PR for now

I think you can leave it open until the other PR is resolved.

**Pull request closed without merging**
