### PR TITLE
maint(test): add optional dependency tests to actions

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

See #20374

#### Brief description of what is fixed or changed

Adds optional dependency tests to github actions.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
FWIW I think even with GHA it would be simpler to keep the bulk of the CI logic in a separate script like we have with test_travis.sh. It's much easier to deal with bash logic in a proper bash script than in a YAML file.

**Comment by asmeurer** [comment]
I guess doing it this way causes things to split up in the logs. I wonder if there's a way to get the best of both worlds with this.

**Comment by asmeurer** [comment]
I guess for stuff like this that's "oneliners" we can put it in the YAML file, but for longer stuff, like most of what is still in test_travis.sh, we should keep a bash script.

**Comment by asmeurer** [comment]
Also worth noting (from https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps):

> Each step runs in its own process in the runner environment and has access to the workspace and filesystem. Because steps run in their own process, changes to environment variables are not preserved between steps. GitHub provides built-in steps to set up and complete a job.

So things should only be split out like this if they really are separate.

**Comment by oscarbenjamin** [comment]
> FWIW I think even with GHA it would be simpler to keep the bulk of the CI logic in a separate script like we have with test_travis.sh. It's much easier to deal with bash logic in a proper bash script than in a YAML file.

I could make a `bin/test_optional_dependencies.py`. Personally I think that the travis.sh/.travis.yml set up is a mess that has only built up that way because Travis uses environment variables to identify different jobs. The `run:` key in actions makes it much clearer what commands are being run in each job.

**Comment by asmeurer** [comment]
If .py seems better than .sh that's fine. The main thing I take issue with is having complex code in a YAML file. Actually test_travis already contains a lot of Python in strings, which has the same problems. So moving it to a Python script is probably better anyway.

**Comment by oscarbenjamin** [comment]
@asmeurer does this look okay to you?

There is clearly room for improvement in this but just shifting everything over to Actions is top priority right now and this is only one part of that.

**Comment by asmeurer** [comment]
It looks good. I think Travis still has the dev docs deployment, but is there anything else left? For the time being, I would just disable every build on Travis except for the dev docs deployment build (and make it only run on master and not be required to merge).

**Comment by oscarbenjamin** [comment]
> I think Travis still has the dev docs deployment, but is there anything else left?

I haven't included the docs deployment yet.

The other things not included are:

1. Test on all supported Python versions.
2. Coverage measurement
3. Test Py2 import
4. Benchmarks
5. Tensorflow 1.x
6. Test with pypy

I wonder how many of these we need now. We should certainly test at least the minimum and maximum supported Python versions but we don't necessarily need to test all versions in between.

I think that coverage measurement is useful but also not critical if we're in a rush. I'm not that impressed with codecov so I wonder if there's a better way. We can have artifacts in actions so maybe we should just use those to show diff coverage somehow...

I'm not sure how long we need to keep the Py2 test.

The benchmarks are useful sometimes. I'd like to find a way of making the output from the benchmarks more noticeable. Currently on Travis the benchmarks job always passes. I would like to get to a point where CI picks up on slowdowns but we don't have that with Travis so it can't be critical in the transition to actions.

I think we can just ditch the Tensorflow 1.x tests.

I can't remember the last time I saw anything meaningful from the pypy tests. Maybe they were more useful before but they don't seem that worthwhile to me.

**Comment by asmeurer** [comment]
PyPy used to fail a lot. I guess that doesn't happen any more? 

I agree I personally don't find codecov useful (partly because of https://github.com/sympy/sympy/issues/16196), but perhaps others do.

Testing the benchmarks in a way that actually gives useful benchmarks is a harder problem. It might be easier with actions since we can use self hosted runners. I would worry about this later, though. I thought the point of the benchmarks run was just to make sure the benchmarks don't break. 

I have no idea what the situation is with tensorflow. 

The py2 test is very simple, and I think it's worth keeping for the time being.

> I wonder how many of these we need now. We should certainly test at least the minimum and maximum supported Python versions but we don't necessarily need to test all versions in between.

I'm not sure. But we should also consider changing our Python version policy to match something like [NEP 19](https://numpy.org/neps/nep-0029-deprecation_policy.html), where we drop Python versions earlier. The issue is that Python has increased the cadence of releases, so our current policy of supporting Python versions that are still supported by Python itself means we now support 5 Python versions at once (see https://www.python.org/dev/peps/pep-0602/).

Regarding docs deployment, I'm working on https://github.com/drdoctr/doctr/pull/372.

**Comment by oscarbenjamin** [comment]
So the main things needed are:

1. Test all Python versions (and perhaps pypy).
2. Test the Python 2 import.

That should be enough to switch off Travis.

I agree we should follow NEP 19.

Deploying the docs might be easier with actions.

**Pull request merged**
