### PR TITLE
Applying Lambda along with Indexed function #14852

### LINKED ISSUE #14852: `Lambda` does not accept indexed symbols.
`Lambda` raises an TypeError when the variable argument passed is an indexed symbol. Example:
```
>>> x1 = Indexed('x', 1)
>>> x1.is_Symbol
False
>>> Lambda(x1, x1**2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/akash/sympy/sympy/core/function.py", line 1659, in __new__
    raise TypeError('variable is not a symbol: %s' % i)
TypeError: variable is not a symbol: x[1]
```

### PR DESCRIPTION
**Pull request by say2sankalp**
References to other Issues or PRs
Fixes #14852 

Brief description of what is fixed or changed
Added is_Symbol=true so that Lambda function could work along with Indexed function
which was present in version 1.1.1, however, missing in 1.2.1.dev.

### CODE REVIEW

**Comment by akash9712** [comment]
@say2sankalp You need to add tests for the changes you have made.

**Comment by akash9712** [comment]
The tests passing when `Lambda` did not accept indexed symbols indicates that the tests were not present. You don't need to open an issue, you can just update the PR by pushing to this branch.

**Comment by say2sankalp** [comment]
I get it, will do it and notify you !!

**Comment by say2sankalp** [comment]
@akash9712 I have added the test, hope this fix the zone.

**Comment by akash9712** [comment]
I don't have write access to this repository, so you will have to wait for someone who does to review this as well. :)

**Comment by say2sankalp** [comment]
@asmeurer  Added the test, hope this fix the zone.

**Pull request closed without merging**
