### PR TITLE
Bidirectional limits

### PR DESCRIPTION
**Pull request by gxyd**
Commits takes from PR #11694. @asmeurer approved that PR, but it has been sometime since those changes were made, and the PR didn't receive many comments.

I have taken partial commits from the PR since the rest of commits in PR #11694 rather only revert these changes. I have closed the other PR.

[Edit]: Related issue where discussion was there #11667.

### CODE REVIEW

**Comment by gxyd** [comment]
Ofcourse some cosmetic changes are expected from the PR, I'll add that later.

**Review by smichr — COMMENTED** [review]
I think we need a different keyword for exc.  What is it short for?

**Comment by gxyd** [comment]
I think `exc` stands for "exception", i.e whether to raise an exception (when left and right hand limits are not equal) or to return `None`. By default it will raise an exception (`ValueError`).

**Comment by gxyd** [comment]
I have improved the documentation. Now it looks good to me.

**Comment by asmeurer** [comment]
I would find a more descriptive keyword name than `exc`.

**Comment by asmeurer** [comment]
Actually, I don't see the point of the `exc` argument. I would just remove it.

**Comment by gxyd** [comment]
@asmeurer @smichr please review.

**Comment by ylemkimon** [comment]
How about including left and right limit results in the error message? Also I think we should make bi-directional limit default.

**Comment by gxyd** [comment]
> How about including left and right limit results in the error message?

That sounds good.

> Also I think we should make bi-directional limit default.

That sounds like should have been a default, but now since `dir='+'` has been default from a very long time (from beginning may be), I wouldn't recommend changing that.

**Comment by ylemkimon** [comment]
> That sounds like should have been a default, but now since dir='+' has been default from a very long time (from beginning may be), I wouldn't recommend changing that.

I meant more like a long-term goal.

**Comment by gxyd** [comment]
But I wonder the reason why `dir='+'` chosen as default instead of `dir='+-'` initially.

**Comment by gxyd** [comment]
@ylemkimon should we consider making `dir='+-'` as a separate issue and merge this PR?

**Comment by ylemkimon** [comment]
@gxyd I agree.

**Comment by ylemkimon** [comment]
Is the term “bi-directional limit“ commonly used?

**Comment by gxyd** [comment]
I think so. Also matlab uses it in documentation http://in.mathworks.com/help/symbolic/limit.html .

**Comment by gxyd** [comment]
We will also need to open a new issue for 'printing' of bidirectional limits. That will be easy to fix.

**Comment by gxyd** [comment]
Also @jksuom do you think raising `ValueError` is best or may be something more mathematically meaningful could be `PoleError`?

**Comment by jksuom** [comment]
I'm not sure what the intended meaning of `PoleError` should be. It seems to be used when a function does not have a (nice) expansion at a point (or that has not been found). Therefore it could perhaps mean that the singularity is worse than a pole (essential singularity). That is different from the non-existence of a (two-sided) limit. For example, `1/x` has no limit in the extended real line at the origin though it is a Laurent polynomial.

**Comment by gxyd** [comment]
Okay. I am merging this as is for now. There are a few issues:
1. Better error type for limits in case of `dir=+-`
2. `Limit(1/x, x, 0, dir='+-')` fails.
3. printing issue for limits with `dir=+-`

**Comment by gxyd** [comment]
I think this should be added to the release notes.

**Pull request merged**
