### PR TITLE
Add evaluate option to subs method

### LINKED ISSUE #19371: Suggestion: allow evaluate option to subs
Just as `diff` method with `evaluate=False` returns `Derivative`, I think it would be nice to allow `evaluate=False` option (which is by default `True`) for `subs` method to return `Subs`.  

Here is an example:
```python
>>> from sympy.abc import x,y
>>> (x+y).subs(x,1)
y + 1
>>> (x+y).subs(x,1, evaluate=False)
Subs(x+y, x, 1)
>>> (x+y).subs(x,1, evaluate=False).doit()
y + 1
```

How is it? If this is OK, I can make a PR for this.

### PR DESCRIPTION
**Pull request by mcpl-sympy**
#### References to other Issues or PRs

Fixes #19371

#### Brief description of what is fixed or changed
keyword argument `evaluate` is added. If `evaluate=False`, `Subs` instance is returned.

#### Release Notes

- core
    - `evaluate` option is added to `Basic.subs`. When `evaluate=False` is passed, `Subs` instance is returned. This option is `True` by default.

### CODE REVIEW

**Comment by mcpl-sympy** [comment]
This PR is ready to be merged.

**Comment by smichr** [comment]
Isn't it easier to just type `Subs(expr, old, new)` than `expr.subs(list(zip(old, new)), evaluate=False)`?

**Comment by oscarbenjamin** [comment]
> Isn't it easier to just type `Subs(expr, old, new)` than `expr.subs(list(zip(old, new)), evaluate=False)`?

If you started with a dict it would be `Subs(expr, list(rep.keys()), list(rep.values()))` rather than `expr.subs(rep, evaluate=False)`. There is no equivalent of `simultaneous` with `Subs`. Also `subs` can grow new options like accepting equations but I wouldn't want to complicate the signature of `Subs` to support those.

**Comment by mcpl-sympy** [comment]
@smichr @oscarbenjamin 
Thanks. Any more comment, please?

**Comment by smichr** [comment]
> Subs(expr, list(rep.keys()), list(rep.values()))
:-)
```
Subs(expr,*zip(*rep.items()))
expr.subs(rep, evaluate=False)
```

**Comment by smichr** [comment]
> There is no equivalent of `simultaneous` with `Subs`

I see. So this will allow Subs to canonically handle unordered substitutions. I am not sure of the pertinence of the `simultaneous` comment, however. Could you please clarify? The Subs result will not be the same as the `simlultaneous=True` result from `subs` in general and is not affected by the setting for `evaluate` to `subs`. In order to be compatible you would need something like...nevermind: you don't want to do this. Use of those two keywords as True should raise a NotImplementedError. (Part of what I had to fix in `replace` was a way to do simultaneous replacement without breaking the expression tree.)

**Comment by oscarbenjamin** [comment]
You can do a simultaneous subs with Subs like:
```julia
In [1]: expr = x*(1+y)                                                                               

In [2]: expr                                                                                         
Out[2]: x⋅(y + 1)

In [3]: expr.subs({x:y, y:x})                                                                        
Out[3]: x⋅(x + 1)

In [4]: expr.subs({x:y, y:x}, simultaneous=True)                                                     
Out[4]: y⋅(x + 1)

In [5]: d1, d2 = symbols('d1:3', cls=Dummy)                                                          

In [6]: expr1 = Subs(Subs(expr, (x, y), (d1, d2)), (d2, d1), (x, y))                                 

In [7]: expr1                                                                                        
Out[7]: 
(x⋅(y + 1))│                      
           │x=d₁, y=d₂, d₂=x, d₁=y

In [8]: expr1.doit()                                                                                 
Out[8]: y⋅(x + 1)
```

**Comment by smichr** [comment]
> You can do a simultaneous subs with Subs like:

Yes. It's robust only for expressions in which the target pattern can be represented with a symbol. As you know, not everything that is an Expr can be thus replaced (e.g. `Lambda` of #19347)

I am not sure what other things lurk this way, but here is another way in which it is fragile:
```python
>>> Subs(Subs(Derivative(f(x),x),f(x),y),y,g(x)).doit()
0
```
To do this right is complex (though not necessarily complicated); it is not trivial.

**Comment by smichr** [comment]
I would rather see Subs gain the ability to handle a dictionary than to see `subs` hijacked to do it. I would expect `evaluate=False` to do something like make a substitution but don't allow the expression to evaluate so `(x*(1 + y)).subs(x, 2, evaluate=False)` -> `2*(1 + y)` or `(x**y).subs({x:2,y:3}, evaluate=False)`->`2**3`.

I am not currently in favor of this change.

**Comment by mcpl-sympy** [comment]
@smichr 
My original intention was to make the signatures of methods same. For example, `diff` takes `evaluate` option, while `integrate` and `subs` don't. (When I first used SymPy, this inconsistence was confusing.)  
Maybe the method design of core needs to be discussed. If we decide that `evaluate` option is unnecessary, perhaps `expr.diff(x, evaluate=False)` needs to be deprecated.

I'd like to hear your opinion on this matter before closing this PR.

**Comment by oscarbenjamin** [comment]
> I would expect `evaluate=False` to do something like make a substitution but don't allow the expression to evaluate

That's a good point. That would be useful and would make more sense for an evaluate keyword here

**Comment by mcpl-sympy** [comment]
@smichr @oscarbenjamin

I agree with this. However, I think this should be a default behavior for subs. In PR 18873 and its related pages, there was a discussion that every core objects should be unevaluated by default.

Perhaps I'll close this PR now, until this change in core is made.

**Comment by oscarbenjamin** [comment]
> I would expect `evaluate=False` to do something like make a substitution but don't allow the expression to evaluate so

That's a good point and actually it would be useful if `subs` could do that.

**Pull request closed without merging**
