### PR TITLE
Updated argument of entropy function in stats module

### LINKED ISSUE #13683: Document methods and classes when *args, **kwargs are present
A lot of functions in sympy use `*args` and `**kwargs`, which ofcourse is itself is like making a good use of python language.

But usage of `*args`, `**kwargs` brings in obscurity as to what possible argument the method or functions could possibly take. For example, this is the signature of `collect_const`
```python
Signature: collect_const(expr, *vars, **kwargs)
Docstring:
A non-greedy collection of terms with similar number coefficients in
an Add expr. If ``vars`` is given then only those constants will be
targeted. Although any Number can also be targeted, if this is not
desired set ``Numbers=False`` and no Float or Rational will be collected.

Examples
========

>>> from sympy import sqrt
>>> from sympy.abc import a, s, x, y, z
>>> from sympy.simplify.radsimp import collect_const
>>> collect_const(sqrt(3) + sqrt(3)*(1 + sqrt(2)))
sqrt(3)*(sqrt(2) + 2)
>>> collect_const(sqrt(3)*s + sqrt(7)*s + sqrt(3) + sqrt(7))
(sqrt(3) + sqrt(7))*(s + 1)
>>> s = sqrt(2) + 2
>>> collect_const(sqrt(3)*s + sqrt(3) + sqrt(7)*s + sqrt(7))
(sqrt(2) + 3)*(sqrt(3) + sqrt(7))
>>> collect_const(sqrt(3)*s + sqrt(3) + sqrt(7)*s + sqrt(7), sqrt(3))
sqrt(7) + sqrt(3)*(sqrt(2) + 3) + sqrt(7)*(sqrt(2) + 2)

The collection is sign-sensitive, giving higher precedence to the
unsigned values:

>>> collect_const(x - y - z)
x - (y + z)
>>> collect_const(-y - z)
-(y + z)
>>> collect_const(2*x - 2*y - 2*z, 2)
2*(x - y - z)
>>> collect_const(2*x - 2*y - 2*z, -2)
2*x - 2*(y + z)

See Also
========
collect, collect_sqrt, rcollect
File:      ~/dev/sympy/sympy/simplify/radsimp.py
Type:      function
```

this doesn't have a good mention of what possible arguments could be taken. So the issue is to properly document the possible arguments in case `*args` and `**kwargs` is used. So if a user can't directly make use of signature to get idea of possible arguments, atleast the docstring should make it very clear about possible `*args`, `**kwargs`.

This is probably a not to be fixed by a single PR but by some smaller PR's.

### PR DESCRIPTION
**Pull request by Vishalghyv**
#### References to other Issues or PRs
#13683

#### Brief description of what is fixed or changed
Changed the function arguments

#### Other comments
This is just the first commit, Wanted to start small and see if there is  any errors

### CODE REVIEW

**Comment by Vishalghyv** [comment]
Hello, I am new to sympy but wanted to contribute to it,
Please do let me know which module should I look into further,
I am looking into the functions which have a description and use arguments from kwargs

**Comment by hyadav2k** [comment]
@Vishalghyv, Go through https://github.com/sympy/sympy/wiki/Writing-Release-Notes once, it will solve your failing check.

**Comment by czgdp1807** [comment]
Nothing much is changed with this PR. I am not sure if we really need this change.

**Comment by Vishalghyv** [comment]
Thanks for the review, I will try and add more changes for functions

**Comment by czgdp1807** [comment]
Closing as of now.

**Pull request closed without merging**
