### PR TITLE
moving nth_algebraic tests

### PR DESCRIPTION
**Pull request by Mohitbalwani26**
#### Brief description of what is fixed or changed
SEE #18377

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by Mohitbalwani26** [comment]
@oscarbenjamin test is failing for `test_digit.py` which is part of `ntheory` module. i am not able to understand the problem for failure so can you please have a look?

**Comment by oscarbenjamin** [comment]
That's a random test that appears to have gone into an infinite loop. I've restarted the test.

**Comment by oscarbenjamin** [comment]
Looks good. Merging

**Comment by oscarbenjamin** [comment]
In future can you try to use more explicit commit messages and PR titles. Both should use the imperative tense and should give context for which aspect of the codebase is changing and why e.g. "refactor(dsolve): move nth_algebraic tests to test_single.py"

**Comment by Mohitbalwani26** [comment]
> In future can you try to use more explicit commit messages and PR titles. Both should use the imperative tense and should give context for which aspect of the codebase is changing and why e.g. "refactor(dsolve): move nth_algebraic tests to test_single.py"

okay surely ,i will take care of this

**Pull request merged**
