### PR TITLE
Hypergeometric Expansion : Changed Less_than_Equal_to(<=) operator with .is_nonpositive

### PR DESCRIPTION
**Pull request by jashan498**
### Whenever we use a relational operator such as  **`x <= 0`**, the value of **`x`** has to be known so that this expression can get evaluated to either **True** or **False**.

But this is not always the case in symbolic maths, so we use expressions like `.is_integer` or `.is_nonpositive`. There was an issue I was working on which exposed [this line](https://github.com/sympy/sympy/blob/master/sympy/simplify/hyperexpand.py#L1344).
`if bj.is_integer and bj <= 0: return None`
Here `.is_integer` doesn't requires `bj` to be known integer whereas `bj <= 0` creates a problem. 
A suitable test case is : 

***>>>*** `k, m = symbols('k m', integer=True)`
***>>>*** `Sum(binomial(2, k)*k**2, (k, 0, m)).doit()`

Above commands give an error because they cant determine the truth value of 'bj<=0' expression. changing it with `.is_nonpositive` gets us to answer.

### CODE REVIEW

**Comment by normalhuman** [comment]
The first line of your test case should be `k, m = symbols('k m', integer=True)`

**Comment by jashan498** [comment]
changed. Thanks for pointing that lol

**Comment by ylemkimon** [comment]
SymPy internally uses assumptions to perform comparison, so if `x.is_nonpositive`, `x <= 0` should return True:
```python
In [3]: x = Symbol('x', nonpositive=True)

In [4]: x.is_nonpositive
Out[4]: True

In [5]: x <= 0
Out[5]: True
```

**Comment by normalhuman** [comment]
@ylemkimon In your example, the truth value is known, so there is no difference. But in general, there is:  
```
>>> var('x')
>>> if x <= 0:
...     print('x is nonpositive')
```
Results in "TypeError: cannot determine truth value of Relational", halting execution.  

Contrasted with 
```
>>> if x.is_nonpositive:
...     print('x is nonpositive')
```
Results in: no output because x is not known to be nonpositive, execution proceeds.

**Comment by ylemkimon** [comment]
I see what you mean. +1

**Pull request merged**
