### PR TITLE
Fixed typo in factortools.py and fixed issues in sqfreetools.py

### LINKED ISSUE #19360: factor(extension=sqrt(2)) hangs
```julia
In [1]: e = (sqrt(2)*x - y)**2                                                                                                    

In [2]: e                                                                                                                         
Out[2]: 
          2
(√2⋅x - y) 

In [3]: expand(e)                                                                                                                 
Out[3]: 
   2               2
2⋅x  - 2⋅√2⋅x⋅y + y 

In [4]: expand(e).factor(extension=[sqrt(2)]) # hangs
```

### PR DESCRIPTION
**Pull request by vaish3496**
#### References to other Issues or PRs

Fixes #19360

#### Brief description of what is fixed or changed
Fixed typo in `sympy/polys/factortools.py` and fixed issues in  `sympy/polys/sqfreetools.py`
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by jksuom** [comment]
Please add a test (`test_issue_19360`) for `factor(2*x**2 - 2*sqrt(2)*x*y + y**2, extension=sqrt(2)` and `factor(-I*t*x - t*y + x*z - I*y*z, extension=I)`.

**Comment by vaish3496** [comment]
@jksuom 


def test_issue_19360:
    x,y,z,t = symbols('x y z t')

    f = 2*x**2 - 2*sqrt(2)*x*y + y**2
    assert factor(f, extension=sqrt(2)) == 2*(x-(sqrt(2)*y/2))**2
    
    f = -I*t*x - t*y + x*z - I*y*z
    assert factor(f, extension=I) == (x-I*y)*(-I*t + z)

Is this code fine? And also should I place the code in `test_factortools.py` ?

**Comment by jksuom** [comment]
It could be placed in `test_polytools.py` as the public function `factor` is being tested. There the symbols `x, y, z, t` are defined globally so there is no need to redefine them in the test.

**Comment by jksuom** [comment]
Looks good. Thanks.

**Comment by vaish3496** [comment]
@jksuom Do you mind sharing 

> It may be possible to fix the algorithm by taking the gcd of f and all of its derivatives.


some resources of the above mathematical concept?

**Comment by jksuom** [comment]
https://en.wikipedia.org/wiki/Square-free_polynomial

**Pull request merged**
