### PR TITLE
Solving `Eq(sin(Abs(x)), 1)` no longer returns ConditionSet

### LINKED ISSUE #9846: `test_conditonset()` in solveset.py fails in master
```python

sympy/solvers/tests/test_solveset.py[61] .fffffffff................................s........F.........                     [FAIL]

_________________________________________________________________________________________________________________________________
_____________________________________ sympy/solvers/tests/test_solveset.py:test_conditonset _____________________________________
  File "/home/amit/Desktop/myrepo/sympy/sympy/solvers/tests/test_solveset.py", line 851, in test_conditonset
    ConditionSet(Lambda(x, Eq(sin(Abs(x)) - 1, 0)), S.Reals)
AssertionError

===================== tests finished: 50 passed, 1 failed, 1 skipped, 9 expected to fail, in 14.70 seconds ======================
DO *NOT* COMMIT!
```

This is because #9591  was in after tests in #9790 passed :
which caused `solveset(Eq(sin(Abs(x)), 1), x, domain=S.Reals)` return solution, which earlier was returning `NotImplementedError`

```
In [4]: solveset(Eq(sin(Abs(x)), 1), x, domain=S.Reals)
Out[4]: Intersection((-oo, 0], ImageSet(Lambda(_n, (-1)**_n*pi/2 + _n*pi), Integers())) U Intersection([0, oo), ImageSet(Lambda(_n, (-1)**_n*pi/2 + _n*pi), Integers()))
```

### PR DESCRIPTION
**Pull request by aktech**
The equation `Eq(sin(Abs(x)), 1)` is now solvable by `solveset` so not a candidate for `ConditionSet` tests:  `def test_conditonset():`

Fixes #9846 

@hargup @flacjacket

### CODE REVIEW

**Comment by aktech** [comment]
If `solveset(Eq(sin(Abs(x)), 1), x, domain=S.Reals)` is solved correctly then, It should be added to the tests.

**Comment by flacjacket** [comment]
Maybe move that test to an XFAIL then?

**Comment by aktech** [comment]
> Maybe move that test to an XFAIL then?

The given test:

```
    assert solveset(Eq(sin(Abs(x)), 1), x, domain=S.Reals) == \
        ConditionSet(Lambda(x, Eq(sin(Abs(x)) - 1, 0)), S.Reals)
```

is wrong since, `ConditionSet` is used when the equation is unevaluated like say for `NotImplementedError` cases, but the equation `Eq(sin(Abs(x)), 1)`  is currently solved, but the solution returned is wrong. Since the correct solution should be:

```
In [21]: ImageSet(Lambda(n, pi*(4*n + 1)/2), S.Naturals0)
Out[21]: 
⎧π⋅(4⋅n + 1)                   ⎫
⎨─────────── | n ∊ Naturals0()⎬
⎩     2                        ⎭

```

**Comment by kumarkrishna** [comment]
@aktech, as you pointed out, the fail was because #9591 came in between the passing of tests for #9790 and its merge. In essence `test_conditionset` keeps track of some of the `Not Implemented` class of equations. As implementations for such cases are added, these tests need to be updated or removed. To maintain the coverage for `ConditionSets` the following test could be added : 

```
 >>> solveset(Eq(sin(Abs(x)), x), x, domain=S.Reals)
 ConditionSet(Lambda(x, Eq(-x + sin(Abs(x)), 0)), (-oo, oo)
```
Thanks!

**Comment by gxyd** [comment]
> Since the correct solution should be:
In [21]: ImageSet(Lambda(n, pi*(4*n + 1)/2), S.Naturals0)
Out[21]: 
⎧π⋅(4⋅n + 1)                   ⎫
⎨─────────── | n ∊ Naturals0()⎬
⎩     2                        ⎭


No that's not correct either. Since
```
>>> expr = sin(Abs(x))
>>> expr.subs({x: -pi/2})
1
>>> -pi/2 in ImageSet(Lambda(n, pi*(4*n + 1)/2), S.Naturals0)       
False                  # -pi/2 is not contained in the solution you suggested
```
All the negative solutions(atleast) are missing in that.

**Comment by aktech** [comment]
@gxyd 

Yes, you are right. I referred wolfram, but forgot to write the complete solution from [Wolframalpha](http://www.wolframalpha.com/input/?i=solve+sin%28Abs%28x%29%29+%3D+1) itself.
Your solution looks good. Thanks!

**Comment by aktech** [comment]
@kumarkrishna 

Yes, `solveset(Eq(sin(Abs(x)), x), x, domain=S.Reals)` could be added to the `test_conditionset` Thanks!

**Comment by aktech** [comment]
@gxyd  @kumarkrishna  Please have a look.

**Comment by gxyd** [comment]
Looks good +1.

**Comment by aktech** [comment]
Thanks, Merging.

**Pull request merged**
