### PR TITLE
Bump version to 1.12.1a1

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

This is a hotfix prerelease as a temporary fix for gh-26273

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
Feel free to close #26408 and delete the branch.

**Comment by oscarbenjamin** [comment]
I think we also need gh-26386

**Comment by asmeurer** [comment]
We'll definitely want 3.13 and numpy 2.0 fixes for 1.12.1. I don't know if they are necessary for this quick-fix alpha, but if it doesn't take any extra time to add them I guess it's not a problem.

**Comment by oscarbenjamin** [comment]
Also included gh-26112

**Comment by oscarbenjamin** [comment]
Looks like this is working. I expect CI to pass. The generate release files will be in the release workflow and can be uploaded to PyPI.

I'm going to bed though.

**Comment by oscarbenjamin** [comment]
I'm just running local tests with this before uploading.

**Comment by oscarbenjamin** [comment]
Also including gh-26269

**Comment by oscarbenjamin** [comment]
I've just pushed this as 1.12.1a1 to PyPI:
https://pypi.org/project/sympy/#history

**Pull request merged**
