### PR TITLE
Physics mechanics devel

### PR DESCRIPTION
**Pull request by tjstienstra**
# PR purpose
The current implementation of the `sympy.physics.mechanics` module is problematic in several ways. To support @brocksam's work for the CZI grant (specifically adding support for `biomechanics`) it will be necessary to make some structural and implementational changes to the module. The purpose of this issue is to present a proposal and keep track of the development. This first comment is divided into several sections. The first section outlines the existing problems and how these will be solved at a high level. The second section proposes the approach of implementation. The last section contains a task list describing the current state of the development. Together with a list of issues that discusses the implementation of a specific set of features.

## An overview
The aim is to provide an API for creating models and generating equations of motion that is high level, easy to learn and hard to misuse. While the joints framework already goes a long way in meeting this aim, it has several problems.

One problem is the `Body` object, which inherits both `RigidBody` and `Particle`. This is conceptually strange and gives rise to various compatibility problems. Instead, a `BodyBase` abstract base class will be implemented, which both `Particle` and `RigidBody` will inherit from. This revised inheritance structure will improve the similarity and provide compatibility with the joints framework for both `RigidBody` and `Particle`.

Another closely related problem is the use of `tuples` for inertias and loads. While it is convenient to use a standard data type to store the location and the quantity, it can be confusing for the user to keep track of the order of arguments in these `tuples`. Therefore, the objective is to implement special classes for both the inertia and the different types of loads. For the inertia we propose implementing an `InertiaTuple(tuple)`. As for the loads we propose implementing an abstract `_Load` class, which will be inherited by `Force` and `Torque`.

Another change is to replace the `JointsMethod` with `System`. `System` is a clearer name and can also be used outside the joints framework. `System` would be a single instance object that is used to do the book-keeping of all model-associated objects like the bodies and loads. A user should be able to instantiate a `System` at the start of their script and implement the model incrementally, or create the entire model and then supply all objects to the `System` (as is currently done with `JointsMethod`). After a user has constructed their entire model the equations of motion can be formed using the `form_eoms` method driven by a specified backend of their choice (e.g. `KanesMethod`). While implementing `System`, `_Method` will also be updated (related to #21772).

Before further improvements to the mechanics module can be made, an `Actuator` class will be implemented for describing coupled loads. After these structural changes to the `sympy.physics.mechanics` module are complete, further improvements to its functionality will be made. This will involve mechanics features as well as the implementation of biomechanics.
Below is a list of brief descriptions of desired mechanics features. Another list of biomechanics features will follow in a separate issue.

Mechanics:
- Implement an `Actuator` class for describing coupled loads.
  - Implement default actuators, e.g. springs and dampers.
- Enhanced bodies functionality:
  - Implement `_Body.add_point(self, point)` and `_Body.get_point(self, name)` for storing point objects related to a body in the body itself.
  - Implement `RigidBody.as_thin_rod` for creating a `RigidBody` that represents a thin rod.
- Implement constants as generalized coordinates in `Joint`, so you can parse `pi / 2` as generalized coordinate to the `PinJoint`.
- Implement an automatic efficient choice of the kinematic differential equations in the joints framework, see [#24035 (comment)](https://github.com/sympy/sympy/pull/24053#issuecomment-1262468801).
- Implement a `CustomJoint`, which will make it possible to create joints describing complex motions.

As this list is not complete, feel free to suggest features with some desired code how you expect it to work.

## Development approach
A `physics-mechanics-devel` branch will be created for this experimental development. This branch will be rebased regularly on `master`. Implementing new features will follow the standard PR procedure. When a feature has been deemed reliable and complete in this experimental branch, it can be merged into `master`. This approach is advantageous because the development is transparent and new features can be tested before inclusion. The risk is that features remain in the experimental branch indefinitely. To counter this risk the timeline contains an aimed approval date associated to each feature.

## Timeline
To organize the timeline the following structure of each feature is used:
- Task containing the feature description
  - Issue: Issue reference to the topic this PR is coupled to
  - PR: PR reference
  - Development date: date that the PR has been merged in the development branch
  - Approval date: aimed date to implement the feature in `master`

Task list:

- [x] Update the bodies structure: `BodyBase`, `Particle(BodyBase)`, `RigidBody(BodyBase)`
  - PR: #24238 
  - Development date: 19-01-2023
  - Approval date: TBD
- [x] Implement compatibility of `Particle` and `RigidBody` with `Joint`
  - PR: #24550 and #24699
  - Development date: 30-1-2023
  - Approval date: 9-3-2023
- [ ] Deprecate `Body`
- [x] Implement `Inertia` object
  - PRs: #24588 and #24722
  - Development date: 31-1-2023
  - Approval date: 16-3-2023
- [x] Implement loads: `LoadBase`, `Force(LoadBase)`, `Torque(LoadBase)`
  - PR: #24641
  - Development date: 3-2-2023
  - Approval date: 22-03-2023
- [x] Implement `System` 
  - PR: #24731 and #24822
  - Development date: 28-2-2023
  - Approval date: TBD
- [ ] Deprecate `JointsMethod`
- [ ] Update `_Method`
- [x] Implement `Actuator`
- [x] Implement actuators:
  - [x] Implement `LinearSpring`
  - [x] Implement `LinearDamper`
- [ ] Enhance bodies functionality:
  - [ ] Implement `_Body.add_point` and `_Body.get_point`
  - [ ] Implement `RigidBody.as_thin_rod`
- [ ] Implement constants as generalized coordinates in `Joint`, so you can parse `pi / 2` as generalized coordinate to the `PinJoint`
- [ ] Implement an automatic efficient choice of the kinematic differential equations in the joints framework, see [#24035 (comment)](https://github.com/sympy/sympy/pull/24053#issuecomment-1262468801)
- [ ] Implement `CustomJoint` for describing complex joint motions

Issue list
- #24256 discusses the reorganization of the body classes.
- #24257 discusses the implementation of a class to store an inertia.
- #24258 discusses the implementation of a class to represent a load.
- #24263 discusses the implementation of a class for handling a model and generating the equations of motion, like `JointsMethod`.
- #24264 discusses the implementation of actuator classes.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by TJStienstra** [comment]
This first commit was just to get a diff, so the PR could be created.

**Comment by moorepants** [comment]
Hi @TJStienstra. Looking at the task list, it seems that most, if not all, of these items are independent of each other. When we discussed in my office, I got the impression that these changes would be heavily layered, thus necessitating this overarching development branch and non-sympy-traditional workflow. Given the  current list it seems like it would be useful to have separate issues for each task list item so the individual  "problem" can be discussed in that issue. If we do all the discussion here, then this PR thread will will likely get too unwieldy due to so many different topics. We also will not have a more orderly issue<->PR history in Github. As an example, take the idea of an inertia tuple. That seems like it could be introduced as a new issue and then a single PR to address it. You already have PR #24238 but there is no associated issue that describes what needs addressing or to be solved and thus no opportunity to discuss whether something is actually problem or what a possible solution is. Everything in your overview seems to be declared rather than proposed as a possible issue and thus open for discussion. How do you propose we discuss the issues before PRs are made?

**Comment by TJStienstra** [comment]
@moorepants thank you for your assessment. When making the task list of the proposal the goal was to make sure the tasks would be separated as much as possible. While my current plan was to do the generic discussion in the PR and the discussion of a specific solutions in the PR implementing the feature. In the case of the `InertiaTuple` this would mean in the `InertiaTuple` PR. However this does give rise to the problem that it is more difficult to discuss a solution on beforehand. This is why I will be creating an issue for each set of PRs to get a discussion started.

This overview is meant to be a proposal and a tracker of the current state. Both of these have a more declarative tone, however this does not mean that it is already fixed. It is still open for discussion even when a PR is already merged in the development branch. One of the reasons for the development branch is that we can revert or radically change features.

**Comment by moorepants** [comment]
Ok, sounds good!

**Comment by moorepants** [comment]
@TJStienstra  and @brocksam, is this used or relevant anymore? Should we close it and move anything to issues if needed?

**Comment by brocksam** [comment]
Yes, this no longer needs to remain open. Some of the incomplete ideas in here have potentially been superseded or rendered redundant so @TJStienstra and I will have a discussion next week and open issues for anything still relevant and outstanding.

**Pull request closed without merging**
