### PR TITLE
[WIP] Progress of code generation

### PR DESCRIPTION
**Pull request by ashishkg0022**
This PR contains the progress made in code generation. Currently the code is generated but some expressions are not matched corectly. 

NO ENTRY

### CODE REVIEW

**Comment by ashishkg0022** [comment]
This Pr doesn't contain the generated code. You can create it by running
```
In [1]: from sympy.integrals.rubi.codgen import generate

In [2]: generate()
```

After file is generated, this generated file can be used for integration. Changes has been made in `rubi.py` , which contains a function `code_generated_int`.

**Comment by czgdp1807** [comment]
@ashishkg0022 Any updates on this? @asmeurer @certik Does this PR still holds a chance for merging or any further work?

**Comment by certik** [comment]
@Upabjojr do you know what the status is of this?

**Comment by Upabjojr** [comment]
I tried some time ago... it's not so trivial. Some work is still necessary.

**Comment by Upabjojr** [comment]
This PR was blocked by a bug in MatchPy which has since been fixed. This PR was meant to stay open until this issue was fixed.

There is still some work to do. The code generator is still generating a huge expression tree, for example.

**Comment by Upabjojr** [comment]
There might be other problems related to MatchPy. For example the generated decision tree appears to have many cul-de-sac-like twigs.

**Comment by certik** [comment]
@Upabjojr is tihs PR trying to implement the step 1. in this plan: https://github.com/symengine/symengine/issues/1597#issuecomment-521721092 ?

**Comment by Upabjojr** [comment]
In a certain sense yes. I would actually do it in a different way. I think the code generator should be revised in order to produce public replacement rules. They are currently defined inside a function.

**Comment by certik** [comment]
Ok, I installed `matchpy` from conda-forge and I got:
```
In [1]: from sympy.integrals.rubi.codgen import generate                        
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-3e82834e8c18> in <module>
----> 1 from sympy.integrals.rubi.codgen import generate

~/repos/sympy/sympy/integrals/rubi/codgen.py in <module>
      3 
      4 from sympy.core.expr import Basic
----> 5 from sympy.integrals.rubi.rubi import rubi_object
      6 from sympy.integrals.rubi.rubi import *
      7 from sympy import *

~/repos/sympy/sympy/integrals/rubi/rubi.py in <module>
      9     from matchpy import (Operation, CommutativeOperation, AssociativeOperation,
     10         ManyToOneReplacer, OneIdentityOperation, CustomConstraint)
---> 11     from matchpy.expressions.functions import register_operation_iterator, register_operation_factory
     12     from sympy import Pow, Add, Integral, Basic, Mul, S, Function, E
     13     from sympy.functions import (log, sin, cos, tan, cot, csc, sec, sqrt, erf,

ImportError: cannot import name 'register_operation_iterator' from 'matchpy.expressions.functions' (/home/certik/miniconda3/envs/sympy/lib/python3.7/site-packages/matchpy/expressions/functions.py)
```
Which is a different error now.

**Comment by Upabjojr** [comment]
Oh dear... they haven't updated the version on Conda yet. Try using `pip`.

**Comment by Upabjojr** [comment]
Anyway, I've been able to generate the code. My first impression is that it's missing some constraints in the decision tree, therefore matching too much.

**Comment by certik** [comment]
The conda package seems to be equivalent to the pip version. Just to be sure, I uninstalled the conda version and did `pip install matchpy` and it fails with the same error. What version of matchpy do you have? I have 0.5.1.

**Comment by Upabjojr** [comment]
Maybe you have to merge the newest SymPy version then. The SymPy-MatchPy connector has been changed as well.

This PR is probably no longer compatible with the newest MatchPy version. On this PR, you should use MatchPy < 0.5 (strict less).

**Comment by certik** [comment]
@Upabjojr thanks, that worked! Here are the instructions to get this PR working:
```
$ conda create -n sympy python=3.7 mpmath ipython matchpy=0.4.6
$ conda activate sympy
$ ipython
In [1]: from sympy.integrals.rubi.codgen import generate                        

In [2]: generate()

In [3]:                                                                                                                                       
```
It takes about a minute or two to finish.

It creates [generated_1.py](https://gist.github.com/certik/4d8e6f36ab9e3846c9ccaf2a99e25106), which has 63,715 lines.

**Comment by Upabjojr** [comment]
In my working PR, I need about 1 hour to generate the code.

I have tested the generated code but it does not always find the results:

```python
⌠     
⎮ x dx
⌡     
⎡ 2⎤
⎢x ⎥
⎢──⎥
⎣2 ⎦
===========================
⌠      
⎮  2   
⎮ x  dx
⌡      
⎡       3   3⎤
⎢      x   x ⎥
⎢0, 0, ──, ──⎥
⎣      3   3 ⎦
===========================
⌠         
⎮   1     
⎮ ───── dx
⎮ x + 1   
⌡         
[]
===========================
⌠     
⎮ 1   
⎮ ─ dx
⎮ x   
⌡     
[0]
===========================
⌠          
⎮ sin(x) dx
⌡          
⎡     ⎛        ⎛x⎞           ⎞         ⎤
⎢     ⎜   2⋅tan⎜─⎟           ⎟         ⎥
⎢     ⎜        ⎝2⎠        ⎛x⎞⎟         ⎥
⎢2⋅Int⎜──────────────, tan⎜─⎟⎟, -cos(x)⎥
⎢     ⎜             2     ⎝2⎠⎟         ⎥
⎢     ⎜⎛   2⎛x⎞    ⎞         ⎟         ⎥
⎢     ⎜⎜tan ⎜─⎟ + 1⎟         ⎟         ⎥
⎣     ⎝⎝    ⎝2⎠    ⎠         ⎠         ⎦
===========================
⌠                 
⎮ sin(x)⋅cos(x) dx
⌡                 
⎡                           ⎛   ⎛   2⎛x⎞    ⎞    ⎛x⎞         ⎞⎤
⎢                           ⎜-2⋅⎜tan ⎜─⎟ - 1⎟⋅tan⎜─⎟         ⎟⎥
⎢                           ⎜   ⎝    ⎝2⎠    ⎠    ⎝2⎠      ⎛x⎞⎟⎥
⎢-Int(cos(x), cos(x)), 2⋅Int⎜────────────────────────, tan⎜─⎟⎟⎥
⎢                           ⎜                  3          ⎝2⎠⎟⎥
⎢                           ⎜     ⎛   2⎛x⎞    ⎞              ⎟⎥
⎢                           ⎜     ⎜tan ⎜─⎟ + 1⎟              ⎟⎥
⎣                           ⎝     ⎝    ⎝2⎠    ⎠              ⎠⎦
===========================
```

**Comment by Upabjojr** [comment]
That is... `1/x` and `1/(1+x)` have both failed. The other ones kind of work.

Some wrong results for `x**2`... caused by some patterns missing the constraint in the generated code.

**Comment by certik** [comment]
How do you actually test the generated code? Can you post the exact line you executed in Python?

**Comment by Upabjojr** [comment]
> How do you actually test the generated code? Can you post the exact line you executed in Python?

Do you mean the whole branch?

https://github.com/sympy/sympy/pull/17614

Code generator:
https://gist.github.com/Upabjojr/114d05b1a8367d8493171f647ab99c43

Then run with:
https://gist.github.com/Upabjojr/f866ce14d3eee6b0dd5f28c340785814

**Comment by certik** [comment]
@Upabjojr thank you. I'll play with it.

**Comment by Upabjojr** [comment]
I've just noted that imports are missing.

**Comment by Upabjojr** [comment]
I have moved the development of the code generator to another project
https://github.com/Upabjojr/rubi_generated

I will close this PR for now.

**Comment by certik** [comment]
Ok, Thanks. 

I would like to have something that works for a small subset of rules, but works reliably, both in Python and in SymEngine. And all that is needed from then on is to just add more rules, and have some mechanism to ensure that the new rules do not create conflicts or other issues. That way lots of people can help with this, small contribution at a time.

**Comment by Upabjojr** [comment]
The decision tree unfortunately has to be generated from MatchPy. The logic of adding new rules is quite complicated and has to be handled by MatchPy.

If MatchPy is too slow, I have already translated the most complicated parts into C++. One could finish by translating the rest of MatchPy into C++ and have a fast rule update.

Currently in RUBI there are three levels of code generation:

1. From Mathematica's FullForm of the matcher to Python lists.
2. From Python lists to MatchPy rules (i.e. mano-to-one matcher).
3. From MatchPy's many-to-one matcher to a decision tree.

**Comment by Upabjojr** [comment]
There is actually a possibility at updating the code dynamically: instead of targeting C++, one could use Clang's API. We should check how much it can be handled.

**Pull request closed without merging**
