### PR TITLE
Define Is meromorphic

### PR DESCRIPTION
**Pull request by jksuom**
#### References to other Issues or PRs

See #8320

#### Brief description of what is fixed or changed
Added a new method, `.is_meromorphic(x, a)` to check whether an expression is a
meromorphic function of `x` at `a`.

#### Other comments
Limits of meromorphic functions can be easily found from the leading terms of their Laurent
series expansions. There is some heuristic in `Limit.doit()` for that purpose (`if all(ok(w) ...)`)
but in most cases the limit will be handled by `gruntz`. That will make a change of variables
introducing an essential singularity and consequently increasing the difficulty of finding a limit.

This method can be used to cover most cases where the limit can be found from the leading
term.

#### Release Notes

* core
    * expr: A new method `is_meromorphic` is added.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This looks useful but I wonder if it should be a method on all of Expr firstly because there are too many methods on Expr but also because I'm not sure it can make sense for all of Expr e.g.:
```julia
In [1]: M = MatrixSymbol('M', 2, 2)                                                                                               

In [2]: M.is_meromorphic(x, 0)                                                                                                    
Out[2]: True
```
Maybe `is_complex` should be checked in the default handler (that doesn't include zoo though).

**Comment by jksuom** [comment]
Maybe `is_complex` could be added though matrix-valued functions can also be meromorphic.

**Comment by oscarbenjamin** [comment]
Is this correct?
```julia
In [23]: sqrt(x).is_meromorphic(x, -1)                                                                                            
Out[23]: True
```

**Comment by jksuom** [comment]
Yes, the two branches of `sqrt` are meromorphic everywhere except at the origin. The Taylor series at -1 is the one having constant term `I`. It can be used to find the limit at -1.

**Comment by oscarbenjamin** [comment]
Is this correct:
```julia
In [14]: x = Symbol('x', real=True)                                                                                               

In [15]: sqrt(-1 +I*x).limit(x, 0)                                                                                                
Out[15]: ⅈ

In [16]: sqrt(-1 +I*x).limit(x, 0, '+')                                                                                           
Out[16]: ⅈ

In [17]: sqrt(-1 +I*x).limit(x, 0, '-')                                                                                           
Out[17]: ⅈ

In [18]: sqrt(-1 + I*1e-10).n()                                                                                                   
Out[18]: 5.0e-11 + 1.0⋅ⅈ

In [19]: sqrt(-1 - I*1e-10).n()                                                                                                   
Out[19]: 5.0e-11 - 1.0⋅ⅈ
```
Should the limit not be different in the two directions approaching the branch cut?

**Comment by jksuom** [comment]
> Should the limit not be different in the two directions approaching the branch cut?

That is something that `limit` should handle. Another method would probably be needed to see if something lands on a branch cut.

**Comment by oscarbenjamin** [comment]
I guess I don't really understand what meromorphic means if the sqrt function defined in this way can be meromorphic on the negative reals. Wikipedia says:
```
In the mathematical field of complex analysis, a meromorphic function on an
open subset D of the complex plane is a function that is holomorphic on all
of D except for a set of isolated points, which are poles of the function
```
https://en.wikipedia.org/wiki/Meromorphic_function

Here we talk about being meromorphic at a point which presumably means in a neighbourhood of that point so `f(z)` is meromorphic "in `z` at `a`" if there is an open subset of the complex plane containing `a` within which `f(z)` is holomorphic except at isolated points.

The `sqrt(z)` function as defined in sympy is discontinuous and therefore not holomorphic along the whole negative real axis. It seems to me that an open set around any point on the negative axis will contain an open interval of the real line along which `sqrt(z)` is not holomorphic.

**Comment by jksuom** [comment]
I am used to consider multivalued functions meromorphic at point if all its branches are meromorphic. Some mechanism should be implemented for choosing the branch at a branch cut. I have made an attempt towards that in https://github.com/sympy/sympy/pull/14715. Some methods like `_eval_nseries` of functions should probably need the ability to make the proper choice at a branch cut.

**Comment by oscarbenjamin** [comment]
Perhaps a definition of meromorphic could be given in the docstring with the `sqrt(z)` example to illustrate what it means.

**Comment by jksuom** [comment]
That looks like a good idea.

**Comment by oscarbenjamin** [comment]
Looks good to me

**Comment by jksuom** [comment]
Thanks, @oscarbenjamin

**Pull request merged**
