### PR TITLE
clean up of 16888

### PR DESCRIPTION
**Pull request by smichr**
#### References to other Issues or PRs

Please refer to discussion on PR  https://github.com/sympy/sympy/pull/16848#issuecomment-494740582

closes #16888 (from which most of this is derived)

#### Brief description of what is fixed or changed
Before
```
>>> x, a = symbols('x a')
>>> Mul._combine_inverse(x*x**a, x**a)
x
>>> Mul._combine_inverse(x*x**(a+1), x**(a+1))
x*x**(-a - 1)*x**(a + 1)
```
After
```
>>> x, a = symbols('x a')
>>> Mul._combine_inverse(x*x**a, x**a)
x
>>> Mul._combine_inverse(x*x**(a+1), x**(a+1))
x
>>> Mul._combine_inverse(x*x**(y+1), x**(y+1))
x
```
Modified `sympy/core/mul.py` and added test to `sympy/core/tests/test_match.py`
Changes suggested by @jksuom 
#### Release Notes

- core
    - `Mul._combine_inverse` acts when either lhs or rhs are a Mul or Pow and will keep any I
      from combining with powers of -1
    - (-oo).as_powers_dict now returns {-1:1, oo:1}

### CODE REVIEW

**Comment by jksuom** [comment]
It looks like this will also fix `dolve(eq8)` in `test_linear_2eq_order2`. The current `sol8` is incorrect:
```
(Pdb) p checksysodesol(eq8, sympify(sol8))
(False, [sqrt(133)*C2*t/12 + 5*C2*t/12 - 5*C1*t**2/24 - sqrt(133)*C1*t**2/24 + 5*sqrt(133)*C1*t**3/36 + 25*C1*t**3/36 + O(t**4), C2*t - C1*t**2/2 + 5*C1*t**3/3 + O(t**4)])
```
while now only the order terms remain (which is to be expected):
```
(Pdb) p checksysodesol(eq8, dsolve(eq8))
(False, [O(t**4), O(t**4)])
```

**Comment by smichr** [comment]
> while now only the order terms remain (which is to be expected):

I'm glad you can give some interpretation to this. I only note that the expanded and collected forms are considerably simpler but have not attempted to rewrite the solution in the test:
```python
[Eq(x(t),
 t**3*(C2/8 + sqrt(133)*C2/72) +
 t**4*(-sqrt(133)*C1/288 + C1/96) +
 t**5*(5*C1/144 +
 sqrt(133)*C1/144) +
 C2/12 +
 C1*t/12 +
 O(t**6)),
Eq(y(t), C2*t**3/3 + C1*t**4/24 + C1*t**5/12 + O(t**6))]
```

**Comment by jksuom** [comment]
The second derivatives of the terms of order `t**6` are `O(t**4)` which means that the best that `checkodesol` can be expected to do is checking the equality of lower order terms. Hence I think that it would be completely acceptable to have `(False, [O(t**4), O(t**4)])` asserted (though not necessarily in this PR).

This looks fine to me.

**Comment by ritesh99rakesh** [comment]
@smichr @jksuom thank you for solving this!

**Pull request merged**
