### PR TITLE
[Enhancement] Updated Documentation and Testing for stats module

### PR DESCRIPTION
**Pull request by Sc0rpi0n101**
#### References to other Issues or PRs

Related to #16318 (Increase test coverage)

#### Brief description of what is fixed or changed
* Documentation updated and improved for stats module
* New tests added for the areas that lacked tests
* Test coverage of the module increased

#### Other comments
* There is still work needed to be done on test coverage. It can be improved further.
* Documentation can also be worked on to make it better

#### Release Notes

* stats
  * Improved Documentation for the module

### CODE REVIEW

**Comment by ritesh99rakesh** [comment]
Your code has many errors. Please refer [this](https://travis-ci.org/sympy/sympy/jobs/516035181) and [this](https://travis-ci.org/sympy/sympy/jobs/516035183) for more details.

**Comment by Sc0rpi0n101** [comment]
I know.
Currently fixing them

**Comment by oscargus** [comment]
Some general comments about the documentation:

 * Please make all the `===`-lines the same length as the word above it.
 * Be consistent with casing for the titles (there is one "returns" rather than "Returns")
 * Use an empty lines before and after every title.
 *  There is no need to add documentation of  the method returning `NotImplementedError` if that is the only thing it does (no need to remove it either, but please do not add more).
 * Right now it says "Paramemeters" instead of "Parameters" in a number of places

Regarding the tests, they look OK, but will be easier to tell once the coverage report is back (once the tests passes). There is at least one test which I do not think will pass, but let's see about that.

**Comment by Sc0rpi0n101** [comment]
@oscargus 
My plan with the ===  lines was to keep their length constant at 8, but I will make the length the same as the word length.
I will also take care of the other remarks too.

Thank you for the review

**Comment by Sc0rpi0n101** [comment]
Test coverage has not increased much.
But I've commented out some faulty tests that were causing build errors.
I wanted to first see if everything is working and passes the build test so that I or anyone else can work at any time improve them further and fix them.
I will soon commit the documentation updates following the review.

**Comment by oscarbenjamin** [comment]
I'm not sure I trust the output from codecov in this case (after clicking through to their website)

**Comment by Sc0rpi0n101** [comment]
@oscargus  So what should I do?

Also,
I only updated some documentation without touching examples and tests
How did the coverage % change?

**Comment by Sc0rpi0n101** [comment]
Would anyone like to review the changes now?
Please tell me if there are still issues or if it can be improved more.

**Comment by oscarbenjamin** [comment]
There should always be a blank line after the === line.

One-line docstrings should be on one line:
[https://www.python.org/dev/peps/pep-0257/](https://www.python.org/dev/peps/pep-0257/)

I prefer docstrings to be either either an imperative or a noun. For example "Return X" rather than "Returns X"  or "Do X" rather than "Does X".

Private methods (with a leading underscore) will usually not need a docstring.

Many of these docstrings could be simplified. Example:
```
        """
        Calculate probability density function
        for the given Yule-Simon Distribution
        Returns
        =======
        A PDF expression
        """
```
There isn't much information there so that could be a one-liner:
```
    """PDF for the Yule-Simon Distribution"""
```

Maybe it would make more sense to have a single pdf function in the superclass that has a detailed docstring with examples and called _pdf from the subclass. Then the subclasses wouldn't need to have docstrings at all...

**Comment by Sc0rpi0n101** [comment]
Ok, I will work on it

**Comment by czgdp1807** [comment]
@Sc0rpi0n101 One suggestion from my side would be to use a different branch than master for making a PR.
Moreover, please make smaller PRs, so that it's easier to review. Infact, it will be easier for you too, to make changes in smaller PRs.

**Comment by Sc0rpi0n101** [comment]
Yeah, I'm working on the smaller PRs part

I did not realize I was editing in master until I changed a few files. So, I thought I can continue this one and start branching from the next one.

**Comment by Sc0rpi0n101** [comment]
I have reduced and fixed the documentation.
Now, it's not as excessive and still covers almost everything.

I need a little help with the tests.

File: test_continuous_rv.py  Line:278
```
k = Symbol("k", integer=True)
x = Symbol('x')
X = Chi('x', k)
C = sqrt(2)*I*x*gamma(k/2 + 1/2)*hyper((k/2 + 1/2,), (3/2,), -x**2/2)/gamma(k/2) + hyper((k/2,), (1/2,), -x**2/2)
assert characteristic_function(X)(x) == C
M = sqrt(2)*x*gamma(k/2 + 1/2)*hyper((k/2 + 1/2,), (3/2,), x**2/2)/gamma(k/2) + hyper((k/2,), (1/2,), x**2/2)
assert moment_generating_function(X)(x) == M
```

File: test_continuous_rv.py   Line:561
```
mu = Symbol("mu", real=True)
sigma = Symbol("sigma", positive=True)
X = LogNormal('x', mu, sigma)
assert cdf(X)(x) == Piecewise((erf(sqrt(2)*(-mu + log(x))/(2*sigma))/2 + 1/2, x > 0), (0, True))
```
These tests pass in Python3 but fail in Python2

File:test_rv.py  Line: 80
```
X = Normal('X',0,1)
Y = DiscreteUniform('Y', [1,2,7])
Z = Poisson('Z', 2)

expr = X**2 + 3
iterator = sample_iter(expr)

expr2 = Y**2 + 5*Y + 4
iterator2 = sample_iter(expr2)

expr3 = Z**3 + 4
iterator3 = sample_iter(expr3)

def is_iterator(obj):
    if (
        hasattr(obj, '__iter__') and
        hasattr(obj, 'next') and      # or __next__ in Python 3
        callable(obj.__iter__) and
        obj.__iter__() is obj
       ):
        return True
    else:
        return False

Passes in python2 but fails in python3
assert is_iterator(iterator)
assert is_iterator(iterator2)
assert is_iterator(iterator3)
```
These tests pass in python2 but fail in python 3

Environment:
debian_9_stretch(stable) - amd64

conda sympy-dev-py27 with mpmath
python 2.7.13

conda sympy-dev-py37 with mpmath
python 3.7.1

Rest of the tests are passing the test consistently.

**Comment by Sc0rpi0n101** [comment]
Would anyone like to review the documentation changes?

If they are fine now or should I change them further?

**Comment by Sc0rpi0n101** [comment]
@oscarbenjamin @oscargus Should I close this PR? 
It will clear my master as I've done the changes in master, unfortunately.
Also, this is a big PR and it will be hard to review it. 
It can be done in small steps.
Thoughts?

**Comment by oscarbenjamin** [comment]
It looks like there are some good changes here so don't discard them. However if these are on your master branch you should get them off of there.

First make sure you've saved your work in files outside of git and outside of the sympy root directory.

Create a new branch from master for these changes:
```
$ git checkout master
$ git checkout -b stats_docfix
```
You can then push the stats_docfix branch and open a new PR from there with these changes.

Then you want to reset your master branch. Add sympy/sympy as upstream:
```
$ git remote add upstream https://github.com/sympy/sympy.git
$ git fetch upstream
```

Now reset your master branch to undo the changes you've done. This is okay because the changes will still br in the stats_docfix branch. Use `$ git log` to find the hash of the last commit on master before you made your cmmitts. Let's say that's ab1234. Then you can reset your master branch with
```
$ git reset ab1234   # This undoes the commits
$ git reset --hard     #This reverts all the files (make sure your work is saved first!)
 ```

Now you can update your branch from master:
```
$ git rebase upstream/master
```

Your work should be saved in the stats_docfix branch which you can use for a new PR. The aboce steps should restore your master branch.

**Comment by Sc0rpi0n101** [comment]
@oscarbenjamin  Created a new PR with a new branch, you can review it whenever you have time.

Also, for updating my master, I like to first rebase upstream/master.
Then rebase my commits and drop all of them, Does that work fine?

**Pull request closed without merging**
