### PR TITLE
Add is_symmetric for permutation groups

### PR DESCRIPTION
**Pull request by sylee957**
#### Brief description of what is fixed or changed

I think that `is_symmetric` predicate is missing even if `_is_sym` cache is used in permutation groups.
I've used a naive test that the symmetric group is the largest permutation group that can be created from a base set of cardinality `n`, and have an order of `n!`.

#### Other comments

I think that permutation group is using custom cache for assumptions. But if there is a way to directly manipulate the global LRU cache or assumptions0 cache if some predicates are revealed during the computation, it may have to use those.

#### Release Notes

- combinatorics
  - Added a new predicate `is_symmetric` to test out if a permutation group is a symmetric group.
  - Added a new predicate `is_alternating` to test out if a permutation group is a alternating group.

### CODE REVIEW

**Comment by jksuom** [comment]
`Permutation.is_alt_sym` is related. It is intended for large groups whose order is not easily found.

**Comment by sylee957** [comment]
One problem of using `is_alt_sym` for quicker test for `True` is that it treats symmetric group and alternating group as same.
I'm not sure how the algorithm behind `_check_cycles_alt_sym` can be improved to target only one predicate specifically. But I'll take a look.

**Comment by sylee957** [comment]
Unfortunately, I don’t think that the jordan’s theorem can discriminate between an alternating group or a symmetric group, so there would not be able to modify the algorithm.

is_alternating may also need to be added for the reason.

**Comment by jksuom** [comment]
It is not hard to distinguish between Alt and Sym: If all generators are even, the group is Alt, otherwise it is Sym.

**Comment by sylee957** [comment]
I have some questions that if `G.is_transistive() == False` can also be a sufficient condition for `is_alt == False` and `is_sym == False`, and the cache can be updated.
I believe it is true from http://mathworld.wolfram.com/TransitiveGroup.html

I also think that the monte-carlo test can use `None` instead of `False` some uncertain false.
I would just want the direction to be more clear that
1. Add `is_alternating` and `is_symmetric` helpers.
2. Modify `is_alt_sym` to give `None` instead of some uncertain `False`.

**Comment by jksuom** [comment]
Looks good.

**Pull request merged**
