### PR TITLE
Added min_fixed and max_fixed options for Float in printers

### LINKED ISSUE #7847: Allow to set min_fixed and max_fixed for Float in the printers
The mpmath printer has `min_fixed` and `max_fixed` settings, which should be exposed to the printers. Right now, only the `strip_zeros` option is exposed. 

We should also unify the Float printer for the various printers. For example, the LaTeX printer doesn't have the same behavior as the string printer.

### PR DESCRIPTION
**Pull request by mijo2**
#### References to other Issues or PRs

Fixes #7847 

#### Brief description of what is fixed or changed

--> Exposed min_fixed and max_fixed options for printers to print floating point numbers

#### Other comments

Example:
```
>>> from sympy import *
>>> from sympy.printing.str import StrPrinter
>>> StrPrinter({'full_prec': False, 'min': -2, 'max':2}).doprint(Float('10000000', 5))
'1.0e+7'
>>> StrPrinter({'full_prec': False, 'min': -2, 'max':2}).doprint(Float('10000000'))
'1.0e+7'
>>> StrPrinter({'full_prec': False, 'min': -2, 'max':8}).doprint(Float('10000000'))
'10000000.0'
>>> StrPrinter({'full_prec': False, 'min': -2, 'max':7}).doprint(Float('10000000'))
'1.0e+7'
>>> StrPrinter({'full_prec': False, 'min': -2, 'max':7}).doprint(Float('0.45'))
'0.45'
>>> StrPrinter({'full_prec': False, 'min': -1, 'max':7}).doprint(Float('0.45'))
'4.5e-1'
>>> 
```
As you can see, the bounds are exclusive.

#### Release Notes

* printing
  * Added min and max options for printers to set a range for floating point numbers that can\
    be printed in fixed-point format.

### CODE REVIEW

**Comment by sylee957** [comment]
I'm not sure that it's useful for code printers unless it's about printing human-readable code.

**Comment by mijo2** [comment]
Ok @sylee957, I will add min_fixed and max_fixed options only for Latex printers and string printers.

**Comment by asmeurer** [comment]
This needs tests. 

I wouldn't put this in the code printers. For the code printers, it is more important to print the exact float value so precision isn't lost. Different parameters might exist to approximate float literals in the code printers, but those would work differently than these, which are based on visual output rather than mathematical rounding.

**Comment by mijo2** [comment]
Ok @asmeurer thanks for your feedback! I have already removed the options from codeprinters. I will start making test cases for latex printers and string printers and will add them soon along with updating the docstring for adding this feature.

**Comment by mijo2** [comment]
@asmeurer I have added the tests cases.

**Comment by mijo2** [comment]
@asmeurer I have added the tests for latex printers as well.

@sylee957 @asmeurer You can review this now to check if anything else needs to be changed or added. Thanks.

**Pull request merged**
