### PR TITLE
Fix evalf to return inf instead of 0

### LINKED ISSUE #8242: (1/x).evalf(subs={x: 0}) produces 0
Here's how it looks like:

``` python
In [1]: sp.__version__
Out[1]: '0.7.5-git'

In [2]: x = sp.abc.x

In [3]: (1/x).evalf(subs={x: 0})
Out[3]: 0

In [4]: (1/x).subs({x: 0})
Out[4]: zoo

In [5]: (1/x).xreplace({x: 0})
Out[5]: zoo
```

I did investigate it some time ago and, AFAIR, it happens in `Pow` evaluation that short-circuits to 0 whenever the base is 0 while it should return infs if the exponent is negative.

### PR DESCRIPTION
**Pull request by divyanshu132**
#### References to other Issues or PRs
Fixes #8242

#### Brief description of what is fixed or changed

Previously:
```
>>> (1/x).evalf(subs={x: 0})
0
```

Now:
```
>>> (1/x).evalf(subs={x: 0})
inf
```

#### Release Notes

*  core
   * function evalf is modified to return inf

### CODE REVIEW

**Comment by jksuom** [comment]
This looks good. Should the same be done for [non-integer exponents]( https://github.com/sympy/sympy/blob/master/sympy/core/evalf.py#L740)?

**Comment by divyanshu132** [comment]
@jksuom I think we should do that because for now it also evaluates to 0.
```
>>> (1/(x**1.5)).evalf(subs={x: 0})
0
```

**Comment by smichr** [comment]
Is there a complex infinity equivalent in mpmath?
```python
>>> S(1)/0
zoo
```

**Comment by jksuom** [comment]
mpmath's mpc values are tuples `z = (re, im)` and `mpc_is_inf(z)` returns True if `re` or `im` is either `finf` or `fninf`. So one might consider `(0, finf)` as a complex infinity.

**Comment by smichr** [comment]
> So one might consider `(0, finf)` as a complex infinity.

Does that make the routine return `zoo` for the test case? (I am just looking for a way to make direct and subs evaluation give the same value.)

**Comment by jksuom** [comment]
> Does that make the routine return zoo for the test case?

Do we expect that `.evalf()` would also return `zoo`?

**Comment by smichr** [comment]
```python
>>> Pow(0,-1,evaluate=0)
1/0
>>> Pow(0,-1,evaluate=0).n()
0
```

**Comment by jksuom** [comment]
I think it would be possible to make `evalf` return `zoo` for `(1/x).evalf(subs={x: 0})`. That could be done by returning `None, mpmath_inf._mpf_, None, target_prec` instead of `mpmath_inf._mpf_, None, target_prec, None` from `evalf_pow`, and then transforming results having infinite imaginary part to `zoo` instead something like `x + I*oo`.

**Comment by asmeurer** [comment]
Infinite imaginary parts are already supported. 

```py
>>> oo*I
oo*I
>>> 1 + oo*I
1 + oo*I
>>> oo + oo*I
oo + oo*I
```

We could make them give `zoo`, but it would probably be a harder fix. I'm not really clear if they should give zoo or not. Such things do come up for instance in the definition of the inverse Laplace transform. Maybe that's irrelevant to things that would come from evalf()?

**Comment by asmeurer** [comment]
Actually I'm not sure if `oo + oo*I` is meaningful, even if we allow that `1 + oo*I` can have meaning. The problem is that oo appears in the expression twice so it isn't clear how the two infinities should relate to each other (I would instead use something like `exp_polar(I*pi/4)*oo`). So maybe it would not be a big deal to make it always result in `zoo`.

For evalf we could also just have it return `zoo` instead of the 4-tuple, and check for that. Are the evalf functions in evalf.py public API?

**Comment by jksuom** [comment]
> For evalf we could also just have it return zoo instead of the 4-tuple,

The 4-tuple is only used internally by evalf. Its mpf and prec components are transformed to two Floats,  x and y, and then SymPy expression `x +y*I` is returned. I think that we could return `zoo` in case y is infinite. That could be done with a small change in the [transformation code](https://github.com/sympy/sympy/blob/master/sympy/core/evalf.py#L1451-L1462).

**Comment by divyanshu132** [comment]
> I think it would be possible to make `evalf` return `zoo` for `(1/x).evalf(subs={x: 0})`. That could be done by returning `None, mpmath_inf._mpf_, None, target_prec` instead of `mpmath_inf._mpf_, None, target_prec, None` from `evalf_pow`, and then transforming results having infinite imaginary part to `zoo` instead something like `x + I*oo`.

@jksuom I have tried with above changes and tested on an example and it seems to give wrong result.
please look at the below example.
```
>>> ((x+x**2)/x**2 + 1).evalf(subs={x: 0})
1.00000000000000
```

I have also tried the same example with the current changes and result seems to be correct.
```
>>> ((x+x**2)/x**2 + 1).evalf(subs={x: 0})
inf
```

and we can easily check that  `((x+x**2)/x**2 + 1).evalf(subs={x: 0})` should evaluate to either `inf` or `zoo`.

**Comment by jksuom** [comment]
It seems that `evalf` cannot compute limits reliably with subs. I think that this result is rather accidental:

    >>> ((x+x**2)/x**2 + 1).evalf(subs={x: 0})
    inf

For a slightly different expression with finite limit, the result will be wrong:
```
>>> ((x+x**2)/x + 1).evalf(subs={x: 0})
inf
```
I don't know how to fix this. Probably limits should be computed before applying `evalf`.

**Comment by divyanshu132** [comment]
Both the changes seems to give answer for this test.
for `None, mpmath_inf._mpf_, None, target_prec`
```
>>> ((x+x**2)/x + 1).evalf(subs={x: 0})
1.00000000000000
```

**Comment by oscarbenjamin** [comment]
> I don't know how to fix this. Probably limits should be computed before applying `evalf`.

Maybe evalf could try to numerically compute the limit.

**Comment by smichr** [comment]
Perhaps evalf needs to be careful and watch for negative power which have a zero base so expressions like `((x+x**2)/x**2 + 1)` don't evaluate to 1 with subs of `{x:0}`.

**Comment by smichr** [comment]
It doesn't seem too bad to me to get `inf` when there is a division by zero. I think it's better than 0 which gives you no sense that something is not right about the evaluation. Are there objections to this as it is? `evalf` is not `limit` so I wouldn't expect it to give the same result.

Would returning nan when there is a division by zero be better?

**Comment by jksuom** [comment]
> Would returning nan when there is a division by zero be better?

I think that nan should be returned for `0/0` and zoo for `a/0` when a is non-zero. That could be done in `evalf_mul`. `0**-1` is currently (wrongly) evaluated as 0 while this PR evaluates it as inf. `evalf_mul` currently collects factors having value nan or inf in a list, `special`, and returns `Mul(*special)` in evaluated form. That is not correct as there could be also factors of value 0.

So, if there is a factor 0 and a factor inf (coming from, e.g., `0**-1`), then nan should be returned. If there is no factor 0 (or nan) and a factor inf, then zoo could be returned.

**Comment by asmeurer** [comment]
In this branch `(0**x).evalf(subs={x: -1})` still gives 0.

**Comment by asmeurer** [comment]
Also this branch doesn't return -inf for `(-1/x).evalf(subs={x: 0})`.

**Pull request closed without merging**
