### PR TITLE
Addition of Laplacian operation

### LINKED ISSUE #12381: Addition of the Laplacian Operator
While going through the Vector Module I noticed that Laplacian operations haven't been implemented in Sympy yet. I think this functionality can be added as in physics Laplacian operator plays a major role (like in Schrodinger Wave Equations).

Laplacian operations on Scalar functions is of importance and I would like to implement it.
What I hope after this implementation would be
```
>>>from sympy.vector import CoordSysCartesian, laplace
>>>R = CoordSysCartesian('R')
>>>v = R.x**2*R.y**2*R.z**2
>>>laplace(v, R)
2*R.x**2*R.y**2 + 2*R.x**2*R.z**2 + 2*R.y**2*R.z**2
```

### PR DESCRIPTION
**Pull request by mohit3011**
Fixes #12381

### CODE REVIEW

**Comment by jksuom** [comment]
This appears related to #12261.

**Comment by mohit3011** [comment]
@jksuom ,then would you merge these changes?

**Comment by asmeurer** [comment]
I agree this looks a lot like the other PR. I would likely prefer the other one as it is older, but also I prefer the changes slightly (it calls the function `laplacian` instead of `laplace`, also "Laplacian" is a different concept from "Laplace transform").

**Comment by mohit3011** [comment]
@jksuom  , @asmeurer  , thanks for reviewing it. I think I will close this PR.

**Comment by mohit3011** [comment]
I just wanted to know, why there is an error coming in doc tests. Also, I ran the code quality tests on my terminal then they were running fine but here in Travis test, these are giving error. 
Please explain. Thanks.

**Comment by jksuom** [comment]
`bin/doctest` was failing because `laplace` was not imported in its doctstring examples (https://travis-ci.org/sympy/sympy/jobs/213513081).

**Comment by mohit3011** [comment]
So , does that mean that every time I include some examples (like here , I included Examples of Laplace in vector/functions.py) I have to include the function name of functions in docstrings too ?

**Comment by jksuom** [comment]
When doctest is running the examples in docstrings, such as this one, for example,
```
    >>> from sympy.vector import CoordSysCartesian, divergence
    >>> R = CoordSysCartesian('R')
    >>> v1 = R.x**2*R.y**2*R.z**2
    >>> laplace(v1, R)
    2*R.x**2*R.y**2 + 2*R.x**2*R.z**2 + 2*R.y**2*R.z**2
    >>> v2 = 2*R.y**2*R.z
    >>> laplace(v2, R)
```
it simply copies each >>> line verbatim and feeds it to the Python interpreter. It does not automatically import the function. Therefore everything has to be given in the same way as when running the examples manually.

**Comment by mohit3011** [comment]
Ok , Thanks  @jksuom

**Pull request closed without merging**
