### PR TITLE
add test to close 14037

### LINKED ISSUE #14037: residue(sin(x**50)/x**51, x, 0) raises an error
The code in residue.py has a weird loop over powers of 2, it can't possibly be correct
I ran this to confirm

### PR DESCRIPTION
**Pull request by goddus**
#### References to other Issues or PRs

Fixes #14037 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Review by sachin-4099 — COMMENTED** [review]
Just add this testcase as well to `series/test_series.py`:
```
In [2]: (sin(x**50)/x**51).series(x, n=0)
Out[2]:
1
- + O(1)
x
```

**Comment by goddus** [comment]
@sachin-4099 I added the test, however it is causing an assertion error and I can't seem to figure out why. I ran the command on the master and it worked fine, so I was wondering if it could possibly be a syntax issue or something else.

The contents of the test are `assert (sin(x**50)/x**51).series(x, n=0) == 1/x + O(1)`

**Comment by sachin-4099** [comment]
This will work:
`assert (sin(x**50)/x**51).series(x, n=0) == 1/x + O(1, x)`

**Comment by sachin-4099** [comment]
Looks good to me. This can be merged @jksuom.

**Comment by jksuom** [comment]
Thanks.

**Pull request merged**
