### PR TITLE
polytools.gcd to numbers.igcd

### PR DESCRIPTION
**Pull request by haru-44**
It is sufficient to be able to compute gcd in integers, even if you do not use polytools.gcd, which can compute more general gcd. There is also a function to compute the integer part of the square root, so this function is used.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I think that it would be best to add the `igcd` function here:
https://github.com/sympy/sympy/blob/bce780e23c0408e76c83d1c2866b469baa1e1e66/sympy/external/gmpy.py#L83-L104
Then ecm can use that directly but also the `igcd` function in `numbers.py` could use it as well. What is needed in ecm is just a pairwise gcd where the inputs are already known to be integers. In that case the additional features of the `igcd` function in `numbers.py` are not needed.

**Comment by smichr** [comment]
> I think that it would be best to add the `igcd` function here:

Do you meanthat  `gcd = igcd` should be added?

**Comment by oscarbenjamin** [comment]
> Do you meanthat `gcd = igcd` should be added?

Yes, and then ntheory should use that directly. Ideally `ntheory` should not import anything from core.

**Comment by haru-44** [comment]
> Ideally `ntheory` should not import anything from core.

What is the advantage of doing it that way?

Also, `ntheory` utilizes other `core` functions (e.g., igcdex, mod_inverse). Does this mean that these should not be used directly as well?

**Comment by oscarbenjamin** [comment]
> > Ideally `ntheory` should not import anything from core.
> 
> What is the advantage of doing it that way?

The core  depends on ntheory because it needs to do things like factorise integers:

https://github.com/sympy/sympy/blob/bb7d7d1448143b6e38e93d2f30686e6e830426b8/sympy/core/numbers.py#L1984

That is used to do things like:
```python
In [3]: sqrt(120)
Out[3]: 2⋅√30
```

Having ntheory also depend on the core is circular. SymPy has a lot of problems with circularity because contributors often don't think about the fact that the design of any codebase should ideally be a directed acyclic graph of dependencies. The basic features in ntheory that operate on concrete integers have no need to depend on core so they should not. If ntheory needs this function that is in core then it would make more sense to move the function to ntheory.

On the other hand ntheory does not need this function from core because the function is designed to extend the basic igcd functions provided by other libraries in order to add features that are not needed in ecm like converting different types to integer and handling more than 2 arguments. Using the primitive functions from elsewhere is more efficient:
```python
In [5]: from gmpy2 import gcd as gmpy2_igcd

In [6]: from math import gcd as math_igcd

In [7]: from sympy.core.numbers import igcd as numbers_igcd

In [8]: numbers = [(i, i*10 + 1) for i in range(1000)]

In [10]: %time ok = [numbers_igcd(*p) for p in numbers]
CPU times: user 4.89 ms, sys: 303 µs, total: 5.19 ms
Wall time: 6.54 ms

In [11]: %time ok = [gmpy2_igcd(*p) for p in numbers]
CPU times: user 342 µs, sys: 14 µs, total: 356 µs
Wall time: 362 µs

In [12]: %time ok = [math_igcd(*p) for p in numbers]
CPU times: user 480 µs, sys: 9 µs, total: 489 µs
Wall time: 502 µs
```
Note that I deliberately did not use timeit because `numbers_igcd` uses a cache. If the cache is beneficial to ecm then it should use a direct cache of `gmpy_igcd` or `math_igcd` rather than the `numbers_igcd` function.

The `numbers.igcd` function explicitly checks `HAS_GMPY` which it should not. That logic should all be handled in one place in `sympy.external.gmpy`. Then `numbers.igcd` should just `import igcd` from there if it needs to extend the functions from gmpy2/math.

> Also, `ntheory` utilizes other `core` functions (e.g., igcdex, mod_inverse). Does this mean that these should not be used directly as well?

I would say that if ntheory needs these then they should really be define in ntheory and the core should import them from there rather than having ntheory import them from the core. Likewise if there are function in gmpy2, mpmath, math etc that can make these operations faster then those should also be used and the logic to decide which one to use belongs in `sympy.external.gmpy`.

In the case of `mod_inverse` in particular Python already provides this as a built-in through `pow` and gmpy2 has `invert`. I am not sure why those functions are needed at all (maybe they are more efficient in some cases?):
```python
In [36]: from sympy.core.numbers import mod_inverse

In [37]: from gmpy2 import invert

In [38]: p = 1009

In [39]: nums = range(1, 1000)

In [40]: %time nums1 = [mod_inverse(n, p) for n in nums]
CPU times: user 3.18 ms, sys: 1 µs, total: 3.18 ms
Wall time: 3.2 ms

In [41]: %time nums2 = [invert(n, p) for n in nums]
CPU times: user 509 µs, sys: 13 µs, total: 522 µs
Wall time: 530 µs

In [42]: %time nums3 = [pow(n, -1, p) for n in nums]
CPU times: user 632 µs, sys: 1 µs, total: 633 µs
Wall time: 636 µs

In [43]: nums1 == nums2 == nums3
Out[43]: True
```
Probably gmpy2's `gcdext` should be used for `igcdex`. 

It is also possible that `mpmath` has optimised implementations of some of these things that are better to use in the case that gmpy2 is not installed.

**Comment by haru-44** [comment]
Thank you. I understand about the concept.

It will not happen overnight. I would like to work on it little by little.

**Comment by asmeurer** [comment]
I would rather say the core should not import from ntheory. The core is the one module that everything else needs to import, so if there are circular imports it's really the core's fault for importing other things. Consider also that ntheory imports things like `Function` from the core to make some of its functions symbolic (and in my opinion, more ntheory functions should be symbolic). I don't think it would be so easy to make `ntheory` not import from `core`.

If a ntheory function is used a lot in the core, it should just be moved to the core. Otherwise, the imports should go inside of the function or method that uses it. This will only cause a circular import if an expression is created at import time, which should be avoided anyway because it slows down the sympy import time.

**Comment by oscarbenjamin** [comment]
> The core is the one module that everything else needs to import, so if there are circular imports it's really the core's fault for importing other things.

I think that's overly simplistic. It might be called "the core" but it has dependencies and the thing to do is to recognise that and clearly understand which things are depended on by the core. The core depends on some things from ntheory and the bulk of ntheory has no need for the core.

If I was to order the dependencies it would look something like:

1. external (i.e. external.gmpy)
2. ntheory
3. polys
4. core
5. functions
6. Everything else.

Exact details can vary but the point is that the "core" is not the base of the dependency graph.

> ntheory imports things like `Function` from the core to make some of its functions symbolic

The symbolic versions of ntheory functions should be in `sympy.functions` rather than `sympy.ntheory`.

> If a ntheory function is used a lot in the core, it should just be moved to the core.

Following this we would end up growing the core indefinitely. Let's just recognise that the core needs some things and it might not make sense to put those things in core but we need to keep them separate from the things that do depend on core.

Regardless of this discussion about core/ntheory there is no reason for ecm to use this function from core because it is just not the right function to use. As I explained above the functions provided by gmpy or otherwise can be provided by external and should then be used directly in ntheory rather than using the version from core which offers no benefit in this particular usage in ntheory.

**Comment by asmeurer** [comment]
> Following this we would end up growing the core indefinitely. Let's just recognise that the core needs some things and it might not make sense to put those things in core but we need to keep them separate from the things that do depend on core.

I'd say on the contrary, there's few enough things in ntheory that are required in the core that if we redefine `ntheory` to be just those things and move everything else to `functions` or somewhere else then most of the number theory functionality will be outside of ntheory. 

The only way this makes sense to me is if ntheory is only pure algorithmic functions with no knowledge of symbolics, and the symbolic functions are just thin wrappers over those. But I fear this kind of abstraction will start to fall apart as soon as you want to implement nontrivial things like in the symbolics (like simplifications and whatnot).

**Pull request merged**
