### PR TITLE
Fix `child_joint_pos` docstring

### PR DESCRIPTION
**Pull request by schnili**
If I'm not mistaken this is a copy-paste error :)

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by sidhu1012** [comment]
Fix typo in line 310 also.

**Comment by moorepants** [comment]
Thanks, it will merge when the tests pass.

**Comment by moorepants** [comment]
After this merged (everything pass here), Travis CI is run on the master branch and it fails:

https://travis-ci.org/github/sympy/sympy/jobs/774657659

It seems like the symengine backend is being used in joint.py and there are failures:

```
sympy/physics/mechanics/tests/test_joint.py[6] .EEEEE                     [FAIL]

sympy/physics/mechanics/tests/test_kane.py[7] .......                       [OK]

sympy/physics/mechanics/tests/test_kane2.py[4] ....                         [OK]

sympy/physics/mechanics/tests/test_kane3.py[1] w                            [OK]

sympy/physics/mechanics/tests/test_kane4.py[1] .                            [OK]

sympy/physics/mechanics/tests/test_lagrange.py[5] .....                     [OK]

sympy/physics/mechanics/tests/test_lagrange2.py[1] .                        [OK]

sympy/physics/mechanics/tests/test_linearize.py[6] w.....                   [OK]

sympy/physics/mechanics/tests/test_models.py[4] ....                        [OK]

sympy/physics/mechanics/tests/test_particle.py[2] ..                        [OK]

sympy/physics/mechanics/tests/test_rigidbody.py[5] .....                    [OK]

sympy/physics/mechanics/tests/test_system.py[5] .....                       [OK]

________________________________________________________________________________

__________ sympy/physics/mechanics/tests/test_joint.py:test_pinjoint ___________

Traceback (most recent call last):

  File "/home/travis/build/sympy/sympy/sympy/testing/runtests.py", line 1348, in _timeout

    function()

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_joint.py", line 31, in test_pinjoint

    Pj = PinJoint('J', P, C)

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 485, in __init__

    child_axis)

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 112, in __init__

    self._orient_frames()

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 514, in _orient_frames

    if angle%pi == 0:

  File "symengine_wrapper.pyx", line 1713, in symengine.lib.symengine_wrapper.Integer.__mod__

  File "symengine_wrapper.pyx", line 4145, in symengine.lib.symengine_wrapper.mod

  File "symengine_wrapper.pyx", line 4089, in symengine.lib.symengine_wrapper.require

TypeError: <class 'symengine.lib.symengine_wrapper.Integer'> required. pi is of type <class 'symengine.lib.symengine_wrapper.Pi'>

________________________________________________________________________________

__ sympy/physics/mechanics/tests/test_joint.py:test_pin_joint_double_pendulum __

Traceback (most recent call last):

  File "/home/travis/build/sympy/sympy/sympy/testing/runtests.py", line 1348, in _timeout

    function()

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_joint.py", line 71, in test_pin_joint_double_pendulum

    child_axis=PartP.frame.z)

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 485, in __init__

    child_axis)

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 112, in __init__

    self._orient_frames()

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 514, in _orient_frames

    if angle%pi == 0:

  File "symengine_wrapper.pyx", line 1713, in symengine.lib.symengine_wrapper.Integer.__mod__

  File "symengine_wrapper.pyx", line 4145, in symengine.lib.symengine_wrapper.mod

  File "symengine_wrapper.pyx", line 4089, in symengine.lib.symengine_wrapper.require

TypeError: <class 'symengine.lib.symengine_wrapper.Integer'> required. pi is of type <class 'symengine.lib.symengine_wrapper.Pi'>

________________________________________________________________________________

__ sympy/physics/mechanics/tests/test_joint.py:test_pin_joint_chaos_pendulum ___

Traceback (most recent call last):

  File "/home/travis/build/sympy/sympy/sympy/testing/runtests.py", line 1348, in _timeout

    function()

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_joint.py", line 112, in test_pin_joint_chaos_pendulum

    child_joint_pos=lA*A.z, parent_axis=N.y, child_axis=A.y)

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 485, in __init__

    child_axis)

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 112, in __init__

    self._orient_frames()

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 514, in _orient_frames

    if angle%pi == 0:

  File "symengine_wrapper.pyx", line 1713, in symengine.lib.symengine_wrapper.Integer.__mod__

  File "symengine_wrapper.pyx", line 4145, in symengine.lib.symengine_wrapper.mod

  File "symengine_wrapper.pyx", line 4089, in symengine.lib.symengine_wrapper.require

TypeError: <class 'symengine.lib.symengine_wrapper.Integer'> required. pi is of type <class 'symengine.lib.symengine_wrapper.Pi'>

________________________________________________________________________________

___ sympy/physics/mechanics/tests/test_joint.py:test_pinjoint_arbitrary_axis ___

Traceback (most recent call last):

  File "/home/travis/build/sympy/sympy/sympy/testing/runtests.py", line 1348, in _timeout

    function()

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_joint.py", line 152, in test_pinjoint_arbitrary_axis

    PinJoint('J', P, C, child_axis=-A.x)

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 485, in __init__

    child_axis)

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 112, in __init__

    self._orient_frames()

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 515, in _orient_frames

    if (angle/pi).is_odd:

AttributeError: 'One' object has no attribute 'is_odd'

________________________________________________________________________________

_________ sympy/physics/mechanics/tests/test_joint.py:test_pinjoint_pi _________

Traceback (most recent call last):

  File "/home/travis/build/sympy/sympy/sympy/testing/runtests.py", line 1348, in _timeout

    function()

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_joint.py", line 292, in test_pinjoint_pi

    J = PinJoint('J', P, C, child_axis=-C.frame.x)

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 485, in __init__

    child_axis)

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 112, in __init__

    self._orient_frames()

  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/joint.py", line 515, in _orient_frames

    if (angle/pi).is_odd:

AttributeError: 'One' object has no attribute 'is_odd'
```

I'm not sure why this test runs on master but not on a PR.

**Comment by moorepants** [comment]
@sidhu1012, maybe we need to somehow disable the optional use of symengine in joint.py?

**Comment by moorepants** [comment]
Also I'm not sure using the mod operator in joint.py for symbolic objects is the correct thing to do:

```
    if angle%pi == 0:
```

**Comment by sidhu1012** [comment]
@moorepants Idk why symengine fails, but I think without disabling it, we can fix it, it's an easy to fix issue, I'll fix it by Friday since I have an interview tomorrow.

**Comment by oscarbenjamin** [comment]
Travis has the symengine version pinned to 0.5.1 whereas the GA setup installs the latest from pip which is currently 0.7.2.

**Comment by moorepants** [comment]
@sidhu1012, if we are supporting symengine back to 0.5.1 then we need to test against that. But it would make more sense to set the symengine version in the github actions tests to the same version as travis CI.

**Comment by oscarbenjamin** [comment]
> But it would make more sense to set the symengine version in the github actions tests to the same version as travis CI.

I think it's actually better to test with the most recent symengine. The issue above is a bug in symengine which is fixed in newer versions.

**Comment by moorepants** [comment]
@sidhu1012 You can try bumping the version in travsi CI.

**Comment by sidhu1012** [comment]
@moorepants PR #21674 shall remove that symengine issue. I'll try bumping verison in travis now.

**Pull request merged**
