### PR TITLE
If U+2013 is present in the URL, sphinx will not recognize it as a link

### PR DESCRIPTION
**Pull request by haru-44**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by smichr** [comment]
seems ok to me...waiting for other input

**Comment by skieffer** [comment]
The default Docutils inliner used by Sphinx recognizes only the basic set of valid URI characters:

<https://sourceforge.net/p/docutils/code/9426/tree/trunk/docutils/docutils/parsers/rst/states.py#l674>

Theoretically possible to use a custom inliner, but probably not worth it. I'd say as long as the link works in the built SymPy docs, this is a good solution.

**Comment by haru-44** [comment]
What do I have to do to be merged?

**Comment by haru-44** [comment]
Thank you.

**Pull request merged**
