### PR TITLE
sinc added to the meijerg tables.

### LINKED ISSUE #10464: integrate(sinc(x)**2, (x, -oo, oo)) can't do it
But the algorithm itself can do it:
```
In [7]: integrate(sinc(x)**2, (x, -oo, oo))
Out[7]: 
∞             
⌠             
⎮      2      
⎮  sinc (x) dx
⌡             
-∞            

In [8]: integrate((sin(x)/x), (x, -oo, oo))
Out[8]: π

In [9]: integrate((sin(x)/x)**2, (x, -oo, oo))
Out[9]: π
```
I.e. [7] is equivalent to [9].

### PR DESCRIPTION
**Pull request by shubhamtibra**
FIX #10464 integrate(sinc(x)**2, (x, -oo, oo)) can't do it

Added sinc to the meijerg tables, Now `integrate(sinc(x)**2, (x, -oo, oo))` gives `pi`

### CODE REVIEW

**Comment by asmeurer** [comment]
Please add tests.

**Comment by shubhamtibra** [comment]
I am not familiar with writing test, can you explain a little about that?

**Comment by asmeurer** [comment]
Look at the tests in sympy/integrals/tests/test_meijerint.py. I think maybe that the tables are numerically tested automatically (but I'm not sure, so you should check). You should also add a test for `meijerint_definite(sinc(x)**2, x, -oo, oo)`.

**Comment by shubhamtibra** [comment]
Please review the PR.

**Comment by asmeurer** [comment]
@certik can you review?

**Comment by certik** [comment]
I tested that master fails, and in this PR, these work:
```
In [1]: integrate(sinc(x)**2, (x, -oo, oo))
Out[1]: π

In [2]: meijerint.meijerint_definite(sinc(x)**2, x, -oo, oo)
Out[2]: (π, True)

In [3]: meijerint.meijerint_definite(sinc(x), x, -oo, oo)
Out[3]: (π, True)
```
This one still hangs:
```
integrate(sinc(x)**2, x)
```
but it should work I think: http://www.wolframalpha.com/input/?i=integrate%28sinc%28x%29**2%2C+x%29, is there some other table that this must be added to in order to work for indefinite integrals?

**Comment by jksuom** [comment]
To make the indefinite integral work ``sinc(x)**2`` should probably be also added to the Meijer G table. I think it should be possible. One could start with a representation of ``sin(x)**2`` and shift the parameters to get ``x**2`` in the denominator. In Prudnikov 8.4.5 (11) there is an expression for powers of ``sin`` as sums of G-functions. In the square case it looks like there would be only one term in the sum.

**Comment by certik** [comment]
Ok. Let me merge this, as the fix is correct, and we can improve the indefinite integral in a new PR.

**Comment by shubhamtibra** [comment]
I will look into adding sinc(x)**2

**Pull request merged**
