### PR TITLE
Skip the slowest of the slow tests on travis

### PR DESCRIPTION
**Pull request by pbrady**
The following tests never actually run to completion on Travis due to the specified timeout of 180s.  Rather than waste 3 minutes on these tests (most of which are xfailed anyway) which are not run to completion, this PR ~~skips them~~  checks to see if we are running on travis via the TRAVIS_BUILD_NUMBER environment variable and if so, skips them. 

6745.05s call     sympy/physics/mechanics/tests/test_kane3.py::test_bicycle
2083.29s call     sympy/solvers/tests/test_ode.py::test_1st_exact2
1522.66s call     sympy/integrals/tests/test_failing_integrals.py::test_issue_4540
1221.33s call     sympy/core/tests/test_wester.py::test_W25
1090.84s call     sympy/integrals/tests/test_failing_integrals.py::test_issue_4941
963.31s call     sympy/solvers/tests/test_solvers.py::test_issue_6528
437.72s call     sympy/integrals/tests/test_heurisch.py::test_pmint_WrightOmega
411.27s call     sympy/core/tests/test_wester.py::test_W24
(The times are from py.test --durations)

Because of this we can restore the split to halves instead of thirds and use fastcache to further speed things along.  Furthermore, we will no longer be relying on the timeout signal to kill these tests which should reduce the frequency of timeouts in the slow tests.

There is some discussion of this issue on the mailing list: https://groups.google.com/forum/#!topic/sympy/xDM4NHWP9cA

### CODE REVIEW

**Comment by moorepants** [comment]
This PR may ultimately need to be reverted. At least for the bicycle test (test_kane3.py) the slowness was due to changes in SymPy that were not good for performance and thus the tests were slowed. Instead of turning the tests off, we should have addressed the slowness. The result of turning of the bicycle tests is that we now have a regression in the code due to it never being tested (plus the fact that it is slowed). See #9641 for more info.

**Comment by asmeurer** [comment]
+1 to that.

**Comment by pbrady** [comment]
The regression happened because the test became too slow to fit in our 3 min time limit not because of this pr.  This pr skipped tests that were already not running to completion on travis and we're causing build/timeout errors on travis.  If the larger cache size allows them all to run in under 3 min than I would be fine with reverting this.

**Comment by moorepants** [comment]
The regression happened because this test was turned off and could not longer catch regressions on CI (and no one ran it locally to completion).

This test got slow because of potentially the change in caching and potentially one other change as noted in the referenced issue in my last note.

The point I'm hoping to make is that we shouldn't disable tests because they become slow due to changes in the code base. Instead, if you make a change to codebase that slows the current tests such that they timeout, the committer should investigate why they tests were slowed instead of turning off the tests.

At some point in the history many of the slow tests ran to completion on Travis. We now need to figure out why they no longer run to completion in the previously allotted time, fix those issues, and re-enable the tests.

Ondrej and I talked about the slow tests at SciPy some. He seemed to think that we should remove all "slow" tests from Travis. There are reasons to do that, i.e. development efficiency, but every slow tests that is removed likely needs either new tests that implement the test in a fast way or we need to ensure that all slow tests are run before a release.

**Comment by certik** [comment]
I understand Jason's arguments, and I think that performance needs to be tested, especially for the bike. However, it is important to realize that we are **not** testing functionality, we are testing performance. And the problem is, that Travis is not a good way to do that. Let me explain.

From practical perspective, if a test runs more than 10s, we better not have many of those, otherwise we quickly fill the 50 minutes allocated on Travis. So if the bike used to run for ~4 minutes, that's a lot of time and makes it really impractical for Travis.

Now let's say we dedicate one full Travis 50 minute test just for the bike and a few other tests. Due to different speeds of the various Travis VM, we better not make it run more than ~30 min or so, from my experience 30 min is safe, but 40 or 45 minutes sometimes can fail, since some Travis VM runs slower and it will go over 50 minutes.

And now the problem, that essentially happened with this: as long as Travis runs, nobody is looking at the times, in fact, they are not even printed.... We only look at the total time, and we don't know if something got slower just become some tests now finished in 35 min instead of 30min. Over time, things get slower (perhaps), but nobody noticed until you start hitting the 50 min threshold. But then it is too late, the slow down has been typically introduced before.

Conclusion: I still think what I told Jason at scipy --- Travis tests should just test functionality and run fast. The bike is an important example, since as Jason explained, it exercises a lot of things from PyDy.  We need to figure out how to test the same things and faster. If it is not possible, then ~4 min test is ok (we can perhaps split it into several faster running ones). However, as I described above, this is not a solution for slow down. For that, the only thing that really works are the ASV graphs that you Jason started doing. We can probably configure it so that it sends results for each PR as well. I think that's really the only robust way to test performance.

As to Travis, I firmly think we need get rid of the slow tests. Either skip them or rework them. And reduce the number of tests on Travis to make it run faster overall.

**Comment by moorepants** [comment]
I agree with you, but this bicycle test is (maybe oddly) a nice test for both functionality and performance.

We could try to write a bunch of smaller unit tests that fully cover the KanesMethod class in the mechanics package or we can pick a single benchmark problem that exercises everything in one test. Either way we may have 4 minutes total test time for covering the functionality. It will take some time to see if I can come up with a way to break apart the test_kane3.py file into smaller, faster unit tests that cover the same functionality. That is unfortunately a bit harder than the test we already have implemented.

And secondly, I'm not advocating for running long tests on travis with every commit. But I do want to ensure that **all** tests are run before a release. And we should also examine the asv benchmarks before each release. It will also be possible to run the benchmarks at every commit, at least while the # of benchmarks is small and we stick with one permutation of dependencies.

**Comment by certik** [comment]
I don't mind running the "bicycle 4 min functionality" test on each commit, hopefully we can later get this number down, possibly with SymEngine.

The "bicycle 4 min benchmark" test needs to be run as parts of our benchmarks, we just need to figure out some way to automate it.

**Comment by asmeurer** [comment]
Ondrej makes a good point. Travis is not a good place for performance tests, because it has time limits, and even if it didn't, we always have to wait on it to merge pull requests.  I think the test suite is a good place for what I will call "performance regression tests", that is, things that should run very fast, and if the slow down, it should be investigated (for example, if you fix something to run in milliseconds instead of minutes, you can add a test that runs in milliseconds with a comment that it should be fast). If we can make the bicycle test run in milliseconds (or even less than a minute) a performance regression test for it could be useful (although I prefer more directed and very fast, i.e., < 1 sec. performance regression tests), but as it is now, it isn't. 

Obviously, functionality was broken too. But that's why we the Travis test suite should focus on unit tests, that is, tests that are small fast, and test just one part of the code. 

Up till now, Travis is the only thing we've had, so something either ran there or it didn't run at all. But if we can get a ASV benchmark machine set up, then that won't be the case.

**Pull request merged**
