### PR TITLE
Laplace and inverse  transform square wave

### PR DESCRIPTION
**Pull request by bharatAmeria**
#### Release Notes

* solvers
  * Added a new Laplace transform for square waves

### CODE REVIEW

**Comment by hanspi42** [comment]
Thank you for your contribution!

You solve the problem in the wrong place, though. The proper way is to define a rectangle function in sympy.functions.special and then add a rule for it in laplace.py

**Comment by bharatAmeria** [comment]
@hanspi42 can u please guide me little bit. how should I approach

**Comment by hanspi42** [comment]
> @hanspi42 can u please guide me little bit. how should I approach

We already have a `Heaviside` function in sympy, so it might make sense to implement the rectangular function https://en.wikipedia.org/wiki/Rectangular_function under the name `rect` or `HeavisidePi` (I would prefer `rect`) in the same style as `Heaviside`, which is in `delta_functions.py`

So the first step is to study that code, and then write a `rect` function in a similar fashion.

The second step is then to write a transform rule for it in `laplace.py`

The last step is to extend it to a rextangular wave.

**Comment by oscarbenjamin** [comment]
It is better not to have too many functions in SymPy because each one creates a bunch of work in solve, laplace, integrate, printing, lambdify etc. The rectangular function is just a difference of Heavisides or a Piecewise which can already be done now so a new function is not needed.

**Comment by bharatAmeria** [comment]
@hanspi42 thank you for guiding me. I'll follow the process step by step suggested by you.

**Comment by hanspi42** [comment]
> @hanspi42 thank you for guiding me. I'll follow the process step by step suggested by you.

You should react to @oscarbenjamin first. I agree with him that having `rect()` in sympy is not really necessary. Do you have good arguments why this should be in sympy?

**Comment by bharatAmeria** [comment]
The Problem is I am new to contributor. I really don't know much about the codebase. It takes sometime in understanding the proper code structure. That's why I am asking for guidance

**Comment by oscarbenjamin** [comment]
Here is how to compute the Laplace transform of a rectangle function:
```python
In [7]: rect = Heaviside(t) - Heaviside(t-1)

In [8]: plot(rect)
Out[8]: <sympy.plotting.backends.matplotlibbackend.matplotlib.MatplotlibBackend at 0x7a26631408f0>

In [9]: rect
Out[9]: θ(t) - θ(t - 1)

In [10]: laplace_transform(rect, t, s)
Out[10]: 
⎛     -s         ⎞
⎜1   ℯ           ⎟
⎜─ - ───, 0, True⎟
⎝s    s          ⎠

In [11]: F, _, _ = laplace_transform(rect, t, s)

In [12]: F
Out[12]: 
     -s
1   ℯ  
─ - ───
s    s 

In [13]: inverse_laplace_transform(F, s, t)
Out[13]: θ(t) - θ(t - 1)
```

**Comment by oscarbenjamin** [comment]
> Here is how to compute the Laplace transform of a rectangle function:

It might be that the documentation could be improved to show examples like this somewhere.

**Comment by hanspi42** [comment]
> The Problem is I am new contributor in this project. I really don't know much about the codebase. It takes sometime in understanding the proper code structure. That's why I am asking for guidance

Ah, if you don't have a mathematical opinion on this, and your goal is to start contributing to SymPy, then we have a list of issues that are considered "Easy to Fix" which are most suitable for new contributors:

https://github.com/sympy/sympy/labels/Easy%20to%20Fix

You write "It takes sometime in understanding the proper code structure." This is completely true. Contributing to sympy is interesting and rewarding, but not low-effort.

I close this PR for now as we see no good reason to teach sympy what a "square wave" is.

**Comment by hanspi42** [comment]
> > Here is how to compute the Laplace transform of a rectangle function:
> 
> It might be that the documentation could be improved to show examples like this somewhere.

This is a very good idea. @bharatAmeria: do you want to pursue this in a new PR? If you don't want to do it, I can.

**Comment by oscarbenjamin** [comment]
Is there anything in the tutorial about Laplace transforms?

I'm not sure where they are documented.

**Comment by hanspi42** [comment]
> Is there anything in the tutorial about Laplace transforms?
> 
> I'm not sure where they are documented.

They are just documented with the commands. But if you want I can write a tutorial; would that be under Calculus?

**Comment by bharatAmeria** [comment]
No, I don't want to do it. Actually in know the solution of this problem, I just wanted to know where did I go wrong and improve it but you can proceed with the issue in new PR. 
I should start with easy fix issues first

**Comment by oscarbenjamin** [comment]
It could be mentioned briefly in the tutorial but also there could a longer guide or explanation somewhere like "Using Laplace transforms and solving differential equations" or something.

The "how to guides" and "explanations" parts of the docs are not very well organised at the moment:
https://docs.sympy.org/latest/index.html

It is supposed to follow the Diataxis framework:
https://diataxis.fr/

Some documents are in the wrong sections though.

**Comment by oscarbenjamin** [comment]
There could also be an "explanations" document that explains how the Laplace transform implementation works.

**Comment by hanspi42** [comment]
> It could be mentioned briefly in the tutorial but also there could a longer guide or explanation somewhere like "Using Laplace transforms and solving differential equations" or something.

So maybe the best would be a guide to using the Laplace transform (including using `Heaviside` etc. to model switching waveforms) and an explanation of the implementation of the Laplace transform?

**Comment by oscarbenjamin** [comment]
Yeah, maybe. Ideally there would be explanation sections that cover different algorithms and implementations and guide sections that cover common use cases.

The tutorial is a good place to have a short example of something that some users might like but it needs to be kept short so possibly just one example of `laplace_transform` and one of `inverse_laplace_transform` is already as much as we would want to have there. Ideally the tutorial would link out to longer guides for more information on each topic.

Another possibility would be a guide for using transforms in general e.g. Laplace is only one type of transform in SymPy.

**Comment by hanspi42** [comment]
If it is a guide, it should show how to solve a specific problem, so "Using Laplace transforms to analyze systems and solve differential equations" would be a nice guide that does not require the use of other transforms.

**Comment by oscarbenjamin** [comment]
Yes, sounds good. There could also be a short section in the tutorial with a link to the guide. Other things like dsolve could perhaps be mentioned as well.

**Comment by hanspi42** [comment]
Do we edit the `.md` files as text, or is there some editor I could use?

**Comment by oscarbenjamin** [comment]
I just edit them using vim which I use for all text editing.

It does highlight things a bit but I type all the characters manually:
image

I don't recommend vim in particular but I think most code editors will do the same.

To view the html you need to build the docs:
https://docs.sympy.org/latest/contributing/new-contributors-guide/build-docs.html

A web search suggests that there are specialised mark-down editors but I have never used any and can't recommend one. Note that many of the doc files are .rst (restructured text) files which use a different syntax from the .md (markdown) files. The two syntaxes are frustratingly similar but not the same which makes it difficult to switch from one to the other.

If you are creating a new file then I guess you can choose which format to use.

**Pull request closed without merging**
