### PR TITLE
Allow Float to accept unicode input under Python 2

### PR DESCRIPTION
**Pull request by dqnykamp**
Fixes bug: 

In [22]: Float(u"123.455",20)
Out[22]: 123.45499999999999829

In [23]: Float("123.455",20)
Out[23]: 123.45500000000000000

### CODE REVIEW

**Comment by pelegm** [comment]
Can you squash these? Then: +1.

**Comment by pelegm** [comment]
Oh, and I'd add a couple of tests as well.

**Comment by skirpichev** [comment]
Do we have some bugs about that?

**Comment by pelegm** [comment]
#8312 seems related, but not really the same thing.

**Comment by dqnykamp** [comment]
Sorry, I'm a bit of a git newbie.  I searched the web for "git squash" and
see that you mean combining the two commits into one using git rebase.
However, the instructions I find have warnings about doing that to commits
that have been pushed, so I'm uncertain what is the safe way to do this.

Any pointers on how to do this safely?


On Tue, Jan 6, 2015 at 7:11 AM, Peleg <notifications@github.com> wrote:

> Can you squash these? Then: +1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sympy/sympy/pull/8713#issuecomment-68863089>.
>



-- 
Duane Nykamp
School of Mathematics
University of Minnesota
202 Vincent Hall
206 Church St. SE
Minneapolis, MN 55455
www.math.umn.edu/~nykamp

**Comment by pelegm** [comment]
See https://github.com/sympy/sympy/pull/8104#issuecomment-57464937.

**Comment by sylee957** [comment]
I guess this can be no issue in the current version, since there is no instance check for `str` now.
Though I'm unsure which version had it been already fixed, though.

**Comment by czgdp1807** [comment]
The bug is not reproduced in master and looks like has been fixed. Can we close this?

```python
>>> Float(u"123.455",20)
123.45500000000000000
>>> Float("123.455",20)
123.45500000000000000
```

**Comment by czgdp1807** [comment]
Closing this in accordance with the last two comments. Please let me know if there is still a issue in the master with other use cases. We will re-open/continue it if needed. Thanks.

**Pull request closed without merging**
