### PR TITLE
Support float format for Expr

### LINKED ISSUE #23290: String formatting of `sympy.core.numbers.Zero`
Given

```
>>> import sympy as sy
>>> x = sy.Symbol('x')
>>> y=x
```

you can avoid this

```
>>> '{:1.2f}'.format(y.subs(x,3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported format string passed to Integer.__format__
```

using `evalf()` or `float()`:

```
>>> '{:1.2f}'.format(y.subs(x,3).evalf())
'3.00'
>>> '{:1.2f}'.format(float(y.subs(x,3)))
'3.00'
```

But if the numeric result is zero, I discovered the hard way that only `float()` works:

```
>>> '{:1.2f}'.format(y.subs(x,0).evalf())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported format string passed to Zero.__format__
>>> '{:1.2f}'.format(float(y.subs(x,0)))
'0.00'
```

Is that behavior intentional?

### PR DESCRIPTION
**Pull request by eagleoflqj**
#### References to other Issues or PRs

Fixes #23290
#### Release Notes

* core
  * support string-`format` for `Expr` with float precision.

### CODE REVIEW

**Comment by oscargus** [comment]
Looks good! Out of curiosity (and laziness): will this also evaluate a more complicated expression to that precision? Would it be worth testing something like  `"{:50:48f}".format(exp(sin(1)))`?

**Comment by eagleoflqj** [comment]
Sure, the result is the consistent with [Wolfram|Alpha](https://www.wolframalpha.com/input?i=e%5Esin%281%29)

**Review by oscargus — APPROVED** [review]
Looks good! I updated the release note to hopefully make it a bit clearer for a user.

**Comment by eagleoflqj** [comment]
Thanks for reviewing!

**Pull request merged**
