### PR TITLE
Changes to ohm to cgs(gauss) conversion

### LINKED ISSUE #24281: Numerical error in sympy.physics.units conversion
Conversion from Ohm to CGS units of resistance (sec/cm) is 4 orders of magnitude off 

``` import sympy as sy
from sympy.physics.units import convert_to
from sympy.physics.units.systems.cgs import cgs_gauss
from sympy.physics.units import ohm, centimeter as cm, second as sec

convert_to(1*ohm, sec/cm, unit_system='cgs_gauss').n()
```

The output is $1.11265005605362\cdot 10^{−8} cm/sec$
It must be $1.11265005605362\cdot 10^{−12} cm/sec$

### PR DESCRIPTION
**Pull request by Vaani-pathariya**
#### References to other Issues or PRs

fixes #24281

#### Brief description of what is fixed or changed
Their was a numerical error in the conversion of ohm to cgs_gauss .This PR fixes that

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscargus** [comment]
Can you please add a test for this? Also, can you please provide some motivation why this is the correct place to change the orders of magnitude? (To get the conversion in #24286 one can theoretically modify it in several places.)

Finally, you will need to add your info based on:
```
This author is not included in the .mailmap file:
Vaani <vaanipathariya@gmail.com>

The .mailmap file needs to be updated because there are commits with
unrecognised author/email metadata.

For instructions on updating the .mailmap file see:
https://github.com/sympy/sympy/wiki/Development-workflow#add-your-name-and-email-address-to-the-mailmap-file
```

**Comment by Vaani-pathariya** [comment]
Actually I don't know how to write test cases and where to write them ,So can you please guide me with the same. Thank you !

**Comment by oscarbenjamin** [comment]
Take a look at the files in `sympy/physics/units/tests/`.

See here for how to run the tests:
https://docs.sympy.org/latest/contributing/dev-setup.html#run-the-tests

**Comment by oscarbenjamin** [comment]
I'm going to mark this PR as draft. Feel free to mark it as "ready for review" when the .mailmap file is updated and some tests have been added.

If you are unsure how to write the tests then feel free to ask but please ask a specific question.

**Comment by Vaani-pathariya** [comment]
ready for review

**Pull request closed without merging**
