### PR TITLE
made changes to add root_notation flag in printing.

### PR DESCRIPTION
**Pull request by shiksha11**
Made changes to fix the issue #14033.

* printing
    * changes made in latex.py and pretty.py

### CODE REVIEW

**Comment by shiksha11** [comment]
Just reviewed #14058.
I don't think in that code in pretty.py in line 2486 root_notation is added
as an argument and similar differences in latex.py.

**Comment by shiksha11** [comment]
Few more changes have to be made as mentioned in #!4058.
Can I go ahead and try to make them now ?

**Comment by oscarbenjamin** [comment]
I think you should ask in #14058 first. It looks as if the author there has stopped working on this. They might say that it's okay for you to take their work so far and continue with it.

**Comment by shiksha11** [comment]
Sure, let ask the author.

**Pull request closed without merging**
