### PR TITLE
Suggested changes to the old assumptions

### PR DESCRIPTION
**Pull request by asmeurer**
These are the changes that I think should be made to the old assumptions. 

Because these changes are likely to be contentious, I have split each change into a separate commit. I have also only made the change to assumptions.py. I don't want to waste time propagating the change throughout the code-base until we agree that the change should be made. 

If you think it would be even better to make each change a separate pull request, let me know. I don't know if that will make things easier or harder when propagating the changes throughout the code-base, however.

### CODE REVIEW

**Comment by pelegm** [comment]
How exactly should I do so, if I wish? Checkout your branch, merge master, solve conflicts (and commit), push to my own repo, create a new PR? Or is there a better workflow?

**Comment by asmeurer** [comment]
This branch is only really useful from a guide point of view (maybe you can cherry-pick some commits to start). It's not really mergable or rebasable due to https://github.com/sympy/sympy/pull/8293 (and even before that it wasn't in a good state). 

I would not try to replicate this branch. It's too much work, and any work like it will be difficult to get merged. Work on one fix at a time. I suggest starting with making `S.Zero.is_imaginary` give `True`. That one looked easy to fix, as there are only a few uses of `is_imaginary` in the code. Fixing the infinity positive issue will be harder (and I'm not even convinced what the right solution is yet honestly).

**Comment by asmeurer** [comment]
So probably this should be closed.

**Comment by skirpichev** [comment]
On Thu, Jan 01, 2015 at 11:33:24AM -0800, Aaron Meurer wrote:
>    This branch is only really useful from a guide point of view (maybe you
>    can cherry-pick some commits to start). It's not really mergable or
>    rebasable due to [1]#8293 (and even before that it wasn't in a good
>    state).

Changes in the assumptions.py - are important.  This was discussed
in depth and we shoud reuse that.

Maybe everything else should be removed and only these changes - rebased.

**Comment by asmeurer** [comment]
Those are the core of this pull request. Any one of those changes requires changing code all throughout SymPy to fix the change in behavior (especially the ones that change the definition of real).

**Pull request closed without merging**
