### PR TITLE
Fix #8984 - Use \left \| instead of \lvert in latex(Abs)

### LINKED ISSUE #8984: Use \left \| instead of \lvert in latex(Abs)
See https://groups.google.com/forum/#!topic/sympy/4kVZq27x6T0. It looks like `\lvert` isn't supported by matplotlib. Is there any good reason to use `\lvert` over `\|`?

### PR DESCRIPTION
**Pull request by leosartaj**
I have changed \lvert and \rvert to | for Abs and changed the corresponding tests. Please review.

### CODE REVIEW

**Comment by leosartaj** [comment]
Please review @asmeurer

**Comment by leosartaj** [comment]
This was my first contribution to sympy. Happy to be part of the community.

**Comment by asmeurer** [comment]
So did you determine that the latex output looks the same for both?

**Comment by cbm755** [comment]
I'm confused by this!  Isn't `\lvert` just `|` and `\lVert` is '\|` (i.e. "||").  Do all our abs look like norms now!?  Unless my latex setup is highly non-standard (its not).

Please revert!

**Comment by leosartaj** [comment]
@cbm755 is correct. \lvert should have been replaced with |. That's mistake on my part. I am sending a new pull request with the changes.

**Comment by leosartaj** [comment]
@cbm755 is correct \lvert should have been replaced by |. That's a mistake on my part. I am sending a new pull request with the changes.

**Pull request merged**
