### PR TITLE
Added leading term and nseries methods for Mod Class

### LINKED ISSUE #25230: Invalid calculation of the limit of the mod function
The limit of the function `mod(x, a)` as x approaches to `m * a` (where m is an integer) is undefined, since it matters if we approach it to the positive or the negative one. By approaching x to the positive one, the result should be 0; but when x approaches to the negative one, it should be `a`. However, SymPy outputs 0 to both of them. Interesting that when I used the floor-definition of the mod function (`mod(x, a) = x - a * (floor(x / a))`), SymPy could calculate both correctly.

Example of the issue and the result being incompatible with the expectation:
Code:
```print(sympy.limit(sympy.Mod(x, 3), x, 3, '-'))```
Result:
```0```
Expected:
 ```3```

### PR DESCRIPTION
**Pull request by anutosh491**
#### References to other Issues or PRs

Fixes #25230 

#### Brief description of what is fixed or changed
The `Mod` class lacked the leading term and nseries methods and hence was returning wrong results . This has been fixed in this Pr.
```
>>> x = Symbol('x')
>>> y = Symbol('y', positive=True)
>>> z = Symbol('z', negative=True)
>>> n = Symbol('n', integer=True)
>>> limit(Mod(x, y), x, n*y, '+')
0
>>> limit(Mod(x, y), x, n*y, '-')
y
>>> limit(Mod(x, z), x, n*z, '+')
z
>>> limit(Mod(x, z), x, n*z, '-')
0
```

#### Release Notes

* series
  * Added leading term and nseries methods for Mod Class.

### CODE REVIEW

**Comment by jksuom** [comment]
This looks good to me but py2-import is failing.

**Comment by anutosh491** [comment]
Thanks for the review . Though I am not wrong the failing tests (including py2-import) is unrelated to the change . Maybe @oscarbenjamin could guide us here .

**Comment by oscarbenjamin** [comment]
See #25274

**Comment by anutosh491** [comment]
> See #25274

I did go through it . I guess we are still pondering on an appropriate way to fix the issue . Would you recommend merging anything in this case ?

**Comment by oscarbenjamin** [comment]
It's fine to merge things even though the python 2 and 3.12 tests are failing

**Comment by faze-geek** [comment]
Looks good to me. Enabling auto-merge. Thanks @anutosh491 !

**Comment by anutosh491** [comment]
@jksuom @faze-geek This is now ready !

**Pull request merged**
