### PR TITLE
init_printing: don't print builtin container subtypes that have custom printers

### PR DESCRIPTION
**Pull request by asmeurer**
For example, sys.flags should print like

sys.flags(debug=0, py3k_warning=0, division_warning=0, division_new=0,
inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=0,
no_site=0, ignore_environment=0, tabcheck=0, verbose=0, unicode=0,
bytes_warning=0, hash_randomization=0)

but before this it would print as

(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0)

with init_printing() used.

There is a test failure here that I'm not yet sure how to fix.

- interactive
  - `init_printing()` no longer LaTeX prints builtin container types that have custom printers (like `sys.flags`).

### CODE REVIEW

**Comment by asmeurer** [comment]
This is ready for review. I have tested IPython 0.13 manually on my computer (I'm not quite sure why we still support it, but that's for another PR).

**Comment by jksuom** [comment]
It looks like something was changed after this was opened. `sys.flags` now prints flag names in current master.

**Comment by asmeurer** [comment]
This only affects the LaTeX printer in the notebook. Sorry if that wasn't clear before. Here is master vs. this branch

**master**
screen shot 2018-07-24 at 1 31 40 pm

**this branch**
screen shot 2018-07-24 at 1 32 10 pm

**Comment by asmeurer** [comment]
I think sys.flags is only a namedtuple in Python 3

**Comment by jksuom** [comment]
It seem to be its own type in Python 2:
```
In [2]: type(sys.flags)
Out[2]: sys.flags
```

**Comment by jksuom** [comment]
So this PR should have no effect on `sys.flags` in Python 2.

**Pull request merged**
