### PR TITLE
solvers/ode: Added new test cases to test_systems.py

### LINKED ISSUE #19312: Adding new test cases to test_systems.py
PR #11510 modified some of the old solvers and added some new test cases. The old solvers will be removed soon, but we need the test cases.

The new test cases need to be added in ```test_sysode_linear_neq_order1``` in ```test_systems.py```. But, only those test cases which are of the form: Linear, n equations, Constant coefficient, Homogeneous(have a look at [this](https://docs.sympy.org/dev/modules/solvers/ode.html#linear-n-equations-order-1-type-1), but note that defective matrices can be handled now) and among them, those which are not already in ```test_systems.py```. Just the new test cases have to be added without modifying the old ones.

### PR DESCRIPTION
**Pull request by jnkrs**
#### References to other Issues or PRs
Closes #19312. 

#### Brief description of what is fixed or changed

Test cases for homogeneous linear differential equations with rhs = 0 and defective coefficient matrices were first included in #11510 and were now added to `test_systems.py` in `test_sysode_linear_neq_order1()`

#### Release notes

NO ENTRY

### CODE REVIEW

**Comment by mijo2** [comment]
@najkr Nice done, you have added the correct test cases. But, I think you should update your PR description according to the format which is used for this library. Have a look at some examples(in the Pull Requests section, go through some merged PRs to get a good idea) to get a rough idea and then update yours.

**Comment by mijo2** [comment]
Correct me if I am wrong but I think the below test case isn't in `test_systems.py` as of now:
https://github.com/sympy/sympy/blob/2e20fe12ab0af03d20f3c1a0a623d8d69f7cb62c/sympy/solvers/tests/test_ode.py#L54

Add this test case in your next commit if this test case isn't there.

**Comment by najkr** [comment]
No, it isn't literally included in `test_systems.py` like this, but I thought that
>     eq2 = [Eq(x(t).diff(t), 2*x(t)), Eq(y(t).diff(t), 3*y(t))]
would be similar enough to not include it.

**Comment by mijo2** [comment]
@najkr Yup it is very similar, in fact, there is more general test case too but add this one too for now.

**Comment by najkr** [comment]
Okay, will do

**Comment by mijo2** [comment]
@najkr Add the release notes in the description.

**Comment by mijo2** [comment]
I hope you have gone through [this](https://github.com/sympy/sympy/wiki/Writing-Release-Notes) page about how to write release notes. It is important to write good release notes. 

I think your release note should be short and simple without referencing the underlying test functions in `test_systems.py`. Adding just that you have added some new test cases in `test_systems.py` should be fine.

**Comment by oscarbenjamin** [comment]
The release notes are for end users. They don't need to know about test cases so this should not have a release note.

**Comment by najkr** [comment]
I got that from the wiki and that's why I didn't include them in the beginning....  (:

**Comment by mijo2** [comment]
@najkr Thanks for your contribution. @oscarbenjamin I can this can be merged now.

**Comment by oscarbenjamin** [comment]
Looks good. Thanks for this

**Comment by najkr** [comment]
Thanks a lot for your help and guidance!

**Pull request merged**
