### PR TITLE
Epiphany is still not pre-installed in Ubuntu. While firefox comes wi…

### PR DESCRIPTION
**Pull request by ShubhamKJha**
NO ENTRY

### CODE REVIEW

**Comment by bjodah** [comment]
I'd recommend `xdg-open` instead.

**Comment by ShubhamKJha** [comment]
```xdg-open``` will open the file in user's default application. It needn't be a web-browser. My default has been set to vscode for example.

**Comment by bjodah** [comment]
OK, what about `x-www-browser` ?

**Comment by ShubhamKJha** [comment]
Yeah, it will work. I simply meant that since ubuntu comes with the latest firefox installed, the docs won't be a problem to follow.

**Pull request merged**
