### PR TITLE
Update Jupyter notebook format

### LINKED ISSUE #26964: Ruff tests failing in Code quality tests.
While running the code quality tests `ruff` check fails with the following logs 
https://github.com/sympy/sympy/actions/runs/10409986962/job/28830805313?pr=26962

```
examples/advanced/identitysearch_example.ipynb:1:1: This file does not match the schema expected of Jupyter Notebooks: unknown field `worksheets`, expected one of `cells`, `metadata`, `nbformat`, `nbformat_minor` at line 6 column 14

examples/beginner/plot_advanced.ipynb:1:1: This file does not match the schema expected of Jupyter Notebooks: unknown field `worksheets`, expected one of `cells`, `metadata`, `nbformat`, `nbformat_minor` at line 6 column 14

...........................
Found [15](https://github.com/sympy/sympy/actions/runs/10409986962/job/28830805313?pr=26962#step:8:16) errors.
```

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

Fixes gh-26964

#### Brief description of what is fixed or changed

Jupyer's nbconvert command can update notebooks to latest format. Ruff also complained about some other things.

#### Other comments

We should not run ruff on fails outside of the SymPy directory. At least flake8 should be expected to pass first before attempting ruff there.

The notebooks I looked at were broken i.e. they don't actually work if you try to run the code. Someone should fix them or otherwise we should just remove from the sympy repo.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
An alternative to this PR could be to disable the ruff checks and then consider just removing all of the notebooks. They could go in a separate repo somewhere.

**Comment by oscarbenjamin** [comment]
> consider just removing all of the notebooks.

Worth noting here that the diff in this PR alone is 1 megabyte which is then permanently in the history once this is merged.

**Comment by asmeurer** [comment]
I already made https://github.com/sympy/sympy-notebooks for notebooks a long time ago.

**Comment by asmeurer** [comment]
The notebooks aren't even included in the sdist. There should be no issue with just moving them.

**Comment by oscarbenjamin** [comment]
Okay, better not to update them then. I'll close this.

**Pull request closed without merging**
