### PR TITLE
Heaviside(0) undefined rather than 1/2. (fixes #9907)

### LINKED ISSUE #9907: Heaviside(0) should be undefined
I am working on an optimal-control problem that involves the derivative of a Max(0,x) function, which gives Heaviside(x) as it's derivative.  In the subsequent analysis, any line `y=mx` is tangent to Max(0,x) at x=0, so long as m is in [0,1].  Thus, in the subsequent analysis, it's very useful to treat Heaviside(x) as a generalized function where Heaviside(0) returns the whole interval [0,1].

Currently, Heaviside(0) returns 1/2, and some justification of this case is given.  However, reasonable 
arguements have been made for Heaviside(0) = 1 or 0 as well, and my example above provides a 4th possibility.  The situation reminds me of the argument we had some-time back over how to evaluate 1**oo, which we decided to leave as nan because there was no universally satisfactory convention.

I propose leaving Heaviside(0) as un-defined.  This is the conservative choice, and avoids possibly incorrect assumptions.  A `.subs(Heaviside(0),k)` can then be used if a specific value is desired.

### PR DESCRIPTION
**Pull request by zanzibar7**

### CODE REVIEW

**Comment by jksuom** [comment]
I am not quite sure which would be the best way to return an undefined value in SymPy, but  ``nan`` (or ``S.NaN`` as it is usually written in internal code) seems to be recommended. Its docstring says: "This serves as a place holder for numeric values that are indeterminate."

**Comment by zanzibar7** [comment]
Returning Heaviside(0) as itself is consistent with the behavior of DiracDelta.
```
In [12]: DiracDelta(0), DiracDelta(1)
Out[12]: (DiracDelta(0), 0)
```
You can then define Heaviside(0) to be whatever you think it should be and use `.subs(Heaviside(0),val)` or some other work-around.  Sympy propagates NaN evaluations,
so `1+x*Heaviside(0)` would return `NaN`.  This is less useful than the original to me -- I need to be able to use my own definition, in the math problem I'm currently on.

**Comment by zanzibar7** [comment]
Also, the previous behavior of Heaviside can be recovered by rewriting in terms of the sign function.

```
In [21]: (1+Heaviside(x)).rewrite(Heaviside,sign).subs(x,0)
Out[21]: 3/2
```

**Comment by jksuom** [comment]
I have no objection. And it really seems to be more convenient in computations.
Merging.

**Pull request merged**
