### PR TITLE
dsolve() converts floats to integers/rationals #10379

### PR DESCRIPTION
**Pull request by shubhamtibra**
I am having problem in adding tests. After the changes are made 
`dsolve(f(t).diff(t)-(1-51.05*y*f(t)), rational=False)` 
gives solution 
`Eq(f(t), (0.019588638589618*exp(y*(C1 - 51.05*t)) + 0.019588638589618)/y)`
But adding 
`eq = f(t).diff(t)-(1-51.05*y*f(t))`
`sol = Eq(f(t), (0.019588638589618*exp(y*(C1 - 51.05*t)) + 0.019588638589618)/y)`
`assert dsolve(eq, rational=False) == sol`  
raises assertion error.
@asmeurer

### CODE REVIEW

**Comment by smichr** [comment]
This looks ok but perhaps a more flexible change would be to name `kwargs` as `solve_flags` and pass that instead of just the `rational` flag. This might also benefit from having a short explanation in the docstring about when `solve` will/might be used by `ode`.

**Comment by shubhamtibra** [comment]
@smichr Do you have any idea about that problem in adding tests as I mentioned?

**Comment by smichr** [comment]
I thought you had it solved by passing the flags along. Sometimes we get around the issue by testing strings as in

```
sol =  dsolve(f(t).diff(t)-(1-51.05*y*f(t)), rational=False)
ans =  Eq(f(t), (0.019588638589618*exp(y*(C1 - 51.05*t)) + 0.019588638589618)/y) 
assert str(sol) == str(ans)
```

**Comment by shubhamtibra** [comment]
Tests are added, Can someone review the PR now please?

**Comment by shubhamtibra** [comment]
@asmeurer @smichr Can you please take a look at it?

**Comment by smichr** [comment]
> This might also benefit from having a short explanation in the docstring about when solve will/might be used by ode.

Please add a note in the ode docstsring explaining what the new kwargs is for.

**Comment by shubhamtibra** [comment]
@smichr Is this Okay? I can't figure out the cases where ode will use `solve`. Can you help me with that?
Thanks.

**Comment by shubhamtibra** [comment]
Ping @smichr

**Comment by smichr** [comment]
> Can you help me with that

look in the function for the call to `solve` and then see under what circumstances that is required.

Also, are floats always converted to Rational by the routine or is that only when `solve` is called?

**Comment by smichr** [comment]
How about just doing this automatically:

```
-            eqsol = solve(eq, func, force=True)
+            floats = any(i.is_Float for i in eq.atoms(Number))
+            eqsol = solve(eq, func, force=True, rational=False if floats else None)
```

If you like this, start over from master, add those lines and your test and you're done.

**Comment by shubhamtibra** [comment]
That'd be better. Creating a new pull request for this. It got all messy when I tried to revert this branch to master.
Thanks @smichr !

**Comment by shubhamtibra** [comment]
#10619 is the new pull request.

**Comment by smichr** [comment]
BTW, github will allow you to delete and recreate a branch with the same name and push it here with the `-f` option:

```
git checkout issue_10379
git branch -D 10379
git checkout -b 10379
git branch -D issue_10379
git push -f shubhamtibra 10379
```

**Comment by smichr** [comment]
other branch committed

**Pull request closed without merging**
