### PR TITLE
floor and ceil for Latex parsing

### PR DESCRIPTION
**Pull request by bhpayne**
#### References to other Issues or PRs
no issues appear to reference lfloor or floor in Latex parsing

#### Brief description of what is fixed or changed
added tokens for Latex parsing of "floor" and "ceil" functions

#### Other comments
In collaboration with @iammosespaulr and @msgoff

#### Release Notes

* parsing
  * support for lfloor rfloor and lceil rceil in Latex

### CODE REVIEW

**Comment by bhpayne** [comment]
I don't understand the warning about

        NameError: name 'expr' is not defined

I didn't make any changes involving expr (that I'm aware of)

**Comment by iammosespaulr** [comment]
> I don't understand the warning about
> 
> ```
>     NameError: name 'expr' is not defined
> ```
> 
> I didn't make any changes involving expr (that I'm aware of)

did you try running the tests locally ... try this 
Screen Shot 2020-08-18 at 12 45 10 PM

Screen Shot 2020-08-18 at 12 45 41 PM

if both of these pass successfully locally, then you might have to rebuild, test and push again.

**Comment by czgdp1807** [comment]
@bhpayne Does the above work for you?

**Comment by oscargus** [comment]
Closing and restarting to see current status. Makes sense to merge if possible.

**Comment by oscargus** [comment]
OK! This seems to have been extended and merged in #19982, so closing for now.

**Pull request closed without merging**
