### PR TITLE
ufuncify: Multiple output argument support

### PR DESCRIPTION
**Pull request by richardotis**
This PR lets ufuncify (with the default language and backend) accept a list or tuple of expressions as output arguments, allowing users to construct ufuncs with multiple (up to `NPY_MAXARGS` minus the number of input arguments) return values. The PR includes a test. Note that the current ufuncify test is also modified since output arguments now start at 0 in the generated code, instead of 1 (i.e., `out0` instead of `out1`), to be consistent with the input arguments.
## Example

``` python
from sympy import symbols
from sympy.utilities.autowrap import ufuncify
x, y, z = symbols('x y z')
var_symbols = (x, y, z)
expr = x + y**3 + 10*y*z**2
# Compute the gradient of the expression
grads = [expr.diff(var_symbols[i]) for i in range(len(var_symbols))]
func = ufuncify(var_symbols, grads)
func(5, [2, 3, 4], 4)
```

```
(array([ 1.,  1.,  1.]),
 array([ 172.,  187.,  208.]),
 array([ 160.,  240.,  320.]))
```

CC @moorepants @asmeurer

### CODE REVIEW

**Comment by asmeurer** [comment]
CCing @markdewing as he may be interested.

**Comment by markdewing** [comment]
The error message should be retained for the backends that do not support this feature.

**Comment by richardotis** [comment]
@markdewing If you mean here: https://github.com/sympy/sympy/pull/11112/files#diff-f7dd73dfc61cbfbaf581db637bc99b14L780

That error message only affects the default backend that creates actual ufuncs ("NUMPY"). The Cython and Fortran backends use completely different code paths and I haven't changed the error handling for those at all.

(IMO since the Fortran and C backends only create 1-D vectorized functions which do not support broadcasting, reduction or other ufunc features, it is misleading to include them in ufuncify, but that is a future PR and discussion.)

**Comment by markdewing** [comment]
Sorry, I missed that, but now I see it - the other backends should have checks and error messages added (as a separate issue)

Thinking of other boundary conditions - it's now possible to pass an empty list, and this condition should be checked.
```python
func = ufuncify(var_symbols, [])
```
Previously, this lines raises an error about 'No expression given'.

Regarding the other backends - do you think it would be better to add features to make them more ufunc-compatible, or to create a separate top-level function for simple vectorization?

**Comment by richardotis** [comment]
I'll take a look at error handling for the case you mentioned.

I think the concept of different backends in ufuncify should go away -- the output of ufuncify should always be a ufunc. We should retain the language keyword argument (default='C') and use it to control the source output language of the compiled extension. I am not familiar enough with the NumPy C API to know exactly how it would work -- it might be that you'd generate the same setup.py and wrapped_module.c for all languages, but then you'd write out the actual function definition in the user-specified language. Then you'd have to compile and link in two steps -- but, again, I am not very familiar with writing Python extensions and have no idea how easy that would be.

I think the functionality currently offered by the other ufuncify backends should be spun off into a new "vectorize()" function.

**Comment by richardotis** [comment]
@markdewing I added a check for empty iterables -- now it'll raise ValueError. Anything else you'd like for me to check?

**Comment by richardotis** [comment]
One useful thing to add, which I currently have in my forked ufuncify, might be to check if the length of expr plus the length of var_symbols exceeds NPY_MAXARGS, since you can segfault the interpreter if that's the case (rel: #9593). The reason I haven't added it here yet is because

1. I don't know how to check the value of NPY_MAXARGS from inside Python. (In my fork it's hardcoded as 32, but in the future NumPy may raise it or remove the limit altogether, e.g., numpy/numpy#4398)
2. I don't know whether ufuncify should raise an error or try to work around it by chunking the output arguments as I do in my fork. In my fork I do the chunking by map()'ing to a list of lambdas, but this may incur an unacceptable and hard-to-debug performance hit for some users. (I have no idea how chunking a ufunc might work from inside C.) If the number of input arguments exceeds NPY_MAXARGS, there's probably no way to work around it and so we should raise.

**Comment by moorepants** [comment]
I like the idea of moving the non-numpy backends out of ufuncify in a "vectorize" function. We could keep it backwards compatible for deprecation by simply sending the args of ufuncify to vectorize.

**Comment by markdewing** [comment]
The error check for a zero length expression looks good.  Thanks.

**Comment by richardotis** [comment]
I went ahead and hard-coded 32 as the value for NPY_MAXARGS, while explaining where the number comes from in a comment where it's defined. That should be enough of a hint for a future person to modify the code if the restriction goes away or changes.

**Comment by richardotis** [comment]
@asmeurer @moorepants Anything else you'd like to see in this PR before it can be merged? I'd like to put the ufuncify/vectorize refactoring into a separate PR to keep master's commit history more atomic.

**Comment by asmeurer** [comment]
On a somewhat tangential note, if you have any comments on how the code generators and sympy.codegen.ast should handle this sort of thing in the more general case, I'd love to hear them.

**Comment by richardotis** [comment]
@asmeurer I have a few thoughts but my comments would probably be better informed after hearing your overview of the system. How about we chat over lunch after your codegen talk at SciPy next month?

**Pull request merged**
