### PR TITLE
Moved all plotting *Series classes to a new file

### PR DESCRIPTION
**Pull request by Davide-sd**
#### References to other Issues or PRs

Another PR related to Issue #23036 

#### Brief description of what is fixed or changed

All `*Series` classes have been moved into the `series.py` file. As the number of `*Series` classes is going to increase, this split makes the code more organized.

#### Other comments

The following PR breaks back-compatibility! Before this PR, any user was able to write `from sympy.plotting.plot import Line2DBaseSeries, Line3DBaseSeries, SurfaceBaseSeries, BaseSeries` and then creates their custom codes. Unfortunately, I can't import these bases classes into `sympy.plotting.plot.py`, otherwise flake8 gives warnings _"F401 .... imported but unused"_, which I believe is considered an error here on sympy. 

How should this break be documented?

#### Release Notes

* plotting
  * Moved all plotting `*Series` classes from `sympy.plotting.plot` to `sympy.plotting.series`.

### CODE REVIEW

**Comment by smichr** [comment]
I would favor this breaking change.

**Comment by smichr** [comment]
Documented in release notes

**Comment by sylee957** [comment]
> otherwise flake8 gives warnings "F401 .... imported but unused"

In fact, this is technically solvable by `__all__ = ...`, but it isn't as elegant as things like in javascript where you can do `export function ...`

**Comment by smichr** [comment]
Is this still a breaking change? If not please update r.n.

**Comment by Davide-sd** [comment]
Yes, it is a breaking change. I edited the release notes to make it clear.

**Comment by oscarbenjamin** [comment]
> otherwise flake8 gives warnings _"F401 .... imported but unused"_, which I believe is considered an error here on sympy.
> 
> How should this break be documented?

I don't know how significant a compatibility break this is but we don't ever need to break compatibility because of flake8: you can use use `# noqa: F401` to stop flake8 from complaining.

**Comment by Davide-sd** [comment]
Thanks for the tip, @oscarbenjamin . Now there is no breaking change. :)

**Comment by Davide-sd** [comment]
`test / optional-dependencies` are failing. I don't think it is related with this PR...

**Comment by oscarbenjamin** [comment]
> `test / optional-dependencies` are failing. I don't think it is related with this PR...

No, it fails regularly. The PR can still be merged anyway though.

**Pull request merged**
