### PR TITLE
Fixed a bug in Probability method in ContinuousPSpace

### LINKED ISSUE #9970: Wrong Probability for Exponential Distribution
```
import sympy.stats as stats
X = stats.Exponential('x',3)
a = stats.P(X > x)
b = stats.P(X < x)
```

`a` yields (correctly): `exp(-3x)` but `b` gives `oo - exp(-3x)` instead of the CDF `1 - exp(-3x)`.

I am working on:
- Python 3.4.3
- SymPy 0.7.6.1

### PR DESCRIPTION
**Pull request by Smit-create**
Fixed a bug in probability method of ContinuousPspace which initially assumed `set=Interval(-oo,oo)`
#### References to other Issues or PRs

Fixes #9970

#### Release Notes

* stats
  * Fixed domain bug in probability method of ContinuousPspace in `sympy/stats/crv.py`

### CODE REVIEW

**Comment by smichr** [comment]
There is a comment on the issue page:

> The same problem occurs with all distributions defined from [0, oo), like gamma distributions.

Should a PR fixing that issue check all such distributions?

**Comment by smichr** [comment]
(and if not, then write "fix partially 9970" in the OP so it doesn't close the issue and then add a note to the issue when this is closed indicating that this part of the issue has been fixed)

**Comment by Smit-create** [comment]
> There is a comment on the issue page:
> 
> > The same problem occurs with all distributions defined from [0, oo), like gamma distributions.
> 
> Should a PR fixing that issue check all such distributions?

Yes, it fixes for all such distributions. The results produce by all other distributions will be as per their pdf so its not necessary to check all distributions

**Comment by czgdp1807** [comment]
@Smit-create Can you test your code(not necessarily including it in the test files) locally for other distributions and show a python session or code here?

**Comment by Smit-create** [comment]
```
>>> from sympy.stats import Cauchy, Normal,P, Die
>>> from sympy.abc import x
>>> N=Normal('N',1,2)
>>> P(N>x)
-sqrt(2)*(-sqrt(2)*pi*(1 - x)*exp((1 - x)**2/8)*erf(sqrt(2)*(1 - x)/4)/4 - sqrt(2)*pi*(1 - x)*exp((1 - x)**2/8)/4)*exp(-x**2/8 + x/4 - 1/8)/(pi*(1 - x))
>>> P(N<x)
sqrt(2)*(-sqrt(2)*pi*(1 - x)*exp((1 - x)**2/8)*erf(sqrt(2)*(1 - x)/4)/4 + sqrt(2)*pi*(1 - x)*exp((1 - x)**2/8)/4)*exp(-x**2/8 + x/4 - 1/8)/(pi*(1 - x))
>>> D=Die('D')
>>> P(D>x)
Piecewise((1/6, x < 1), (0, True)) + Piecewise((1/6, x < 2), (0, True)) + Piecewise((1/6, x < 3), (0, True)) + Piecewise((1/6, x < 4), (0, True)) + Piecewise((1/6, x < 5), (0, True)) + Piecewise((1/6, x < 6), (0, True))
>>> P(D<x)
Piecewise((1/6, x > 1), (0, True)) + Piecewise((1/6, x > 2), (0, True)) + Piecewise((1/6, x > 3), (0, True)) + Piecewise((1/6, x > 4), (0, True)) + Piecewise((1/6, x > 5), (0, True)) + Piecewise((1/6, x > 6), (0, True))
>>> C=Cauchy('C',0,1)
>>> P(C>x)
-(-I*log(x - I)/2 + I*log(x + I)/2)/pi
>>> P(C<x)
(-I*log(x - I)/2 + I*log(x + I)/2)/pi

```

**Comment by czgdp1807** [comment]
What are the results on `master`? It would be good if you can edit your comment and add the results from `master`.

**Comment by Smit-create** [comment]
@czgdp1807  Is it good to merge?

**Comment by czgdp1807** [comment]
Please merge master as this one is also 2 days old.

**Comment by czgdp1807** [comment]
Merging.

**Pull request merged**
