### PR TITLE
changed year in licenses to 2023

### PR DESCRIPTION
**Pull request by asTejaswinis**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by 1e9abhi1e10** [comment]
> #### References to other Issues or PRs
> #### Brief description of what is fixed or changed
> #### Other comments
> #### Release Notes

@asTejaswinis  you should add the release notes If there is no release notes entry, write `NO ENTRY`

**Comment by asTejaswinis** [comment]
#### Brief description of what is fixed or changed
changed the years in the license file from 2022 to 2023
#### Release Notes

NO ENTRY

**Comment by sylee957** [comment]
You should make edit to the original post or the bot won't recognize

**Comment by ThePauliPrinciple** [comment]
> #### Brief description of what is fixed or changed
> 
> changed the years in the license file from 2022 to 2023
> #### Release Notes
> 
> NO ENTRY

You will have to edit your original( the first) post

**Pull request merged**
