### PR TITLE
Modifies the docstring of collect_const()

### PR DESCRIPTION
**Pull request by arighnac**
Fixes issue #13683 .

Cleans up the problems of the last PR. 
@gxyd  @jksuom  please review.

### CODE REVIEW

**Comment by ArighnaIITG** [comment]
I tried a lot, and then understood that two of my Travis Builds were failing because I was developing on that branch. So,I created another new branch.
I have closed my last PR #13725 . 
What can I do else?

**Comment by gxyd** [comment]
First of all, can you please close this PR? so that comments stay on the original PR.

**Comment by gxyd** [comment]
And re-open the original one.

**Comment by ArighnaIITG** [comment]
Great.

**Pull request closed without merging**
