### PR TITLE
[DOC] Added docstring for ExprWithIntLimits class

### PR DESCRIPTION
**Pull request by jremes-foss**
Hi. 

ExprWithIntLimits class was missing a docstring. This has been now added.

```./bin/test quality``` executed locally - all green.

Thank you.

### CODE REVIEW

**Comment by moorepants** [comment]
You may need to merge in maser for the docutils error to be fixed.

**Comment by gxyd** [comment]
@Newman101 can you please address the comment?

**Comment by Newman101** [comment]
Sure thing, I check what is the problem with this one. The error in question is: 

```AssertionError: len(context) = 1```

**Comment by gxyd** [comment]
@asmeurer here tests fail with a different error. You may want to look over the failing job (just one) https://travis-ci.org/sympy/sympy/jobs/183227136 .

**Comment by jksuom** [comment]
> AssertionError: len(context) = 1

This looks like the issue with docutils-0.13.1 (https://github.com/sympy/sympy/pull/11935).
The current error in Travis is probably random and a restart could help.

**Comment by gxyd** [comment]
I have restarted the failing job.

**Pull request closed without merging**
