### PR TITLE
test case for syntax error on lambdify

### PR DESCRIPTION
**Pull request by divyanshu132**
#### References to other Issues or PRs
#13881  #14581  

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by divyanshu132** [comment]
@sidhantnagpal all tests are cleared in my system but I don't know why the tests are failing can you please help me to resolve this??

**Comment by sidhantnagpal** [comment]
It seems the test you added is failing on Travis. Going through the referenced issues, it seems the output differs depending on whether you have NumPy installed or not. See https://github.com/sympy/sympy/pull/13966#issuecomment-359237371.
I think #13966 is the right fix for it.

**Comment by divyanshu132** [comment]
So changing the result of assert in matrix form(i.e [14]) should work.

**Comment by oscargus** [comment]
What is the difference between this and #14581? Seems to be exactly the same code? Any advantages over #13966 ?

**Comment by sidhantnagpal** [comment]
The test was first included in #13934 (which is closed). There have been attempts to solve issue #13881 in PRs: #13934, #13966, #14581 and #15963 (this PR). 
However, as pointed out before, fixing issue #13984 is a prerequisite to solving issue #13881.

**Pull request closed without merging**
