### PR TITLE
Add coverage.py testing and Codecov reporting

### LINKED ISSUE #10519: Try codecov (code coverage)
See https://github.com/cloudpipe/cloudpickle/pull/48#issuecomment-169821928 for an example of why this is cool. We could also try coveralls (see my ancient attempt to get it working at https://github.com/sympy/sympy/pull/1960).

### PR DESCRIPTION
**Pull request by ylemkimon**
* Added coverage testing using coverage.py, enabled if `TEST_COVERAGE == "true"`
* Added coverage test reporting to Codecov.io: [Example 1](https://codecov.io/gh/ylemkimon/sympy/branch/coverage), [Example 2](https://codecov.io/gh/ylemkimon/sympy/tree/520a2882dd4d7c73768aebe16a872bac733baec0) _Note: sympy/sympy's Codecov is not fully working, since its webhook is not enabled._

It seems to double the build time, maybe we should trigger coverage testing manually(or by a bot), i.e., after getting positive review, or test only on one Python version.

Fixes #10519.

### CODE REVIEW

**Comment by moorepants** [comment]
FYI:
- https://github.com/sympy/sympy/pull/11974
- https://github.com/sympy/sympy/pull/10937

**Comment by ylemkimon** [comment]
Restarted `TEST_SPHINX`.

**Comment by gxyd** [comment]
Is this PR complete? How do we test if this working on actual PR's?

**Comment by ylemkimon** [comment]
@gxyd It's complete, but as said above, it doubles the build time, so we may need to trigger coverage testing manually(or by a bot), i.e., after getting positive review, or test only on one or two Python version(s). Also this must be merged and Codecov webhook must be enabled to test on actual PRs, but you can see the example output in the links above.

**Comment by skirpichev** [comment]
70% coverage is too bad, even for sympy.  @ylemkimon, are you sure - it's all?

**Comment by moorepants** [comment]
If you check the work here #11974, I was only getting ~70% and noticed that it was because the tests are run with `subprocess` that many are not being run. That was the main remaining issue in that PR to get things working.

**Comment by ylemkim** [comment]
@skirpichev Currently external modules(optional dependencies) testing and slow tests are not included, but not [omitted or excluded](https://github.com/ylemkimon/sympy/blob/520a2882dd4d7c73768aebe16a872bac733baec0/.coveragerc#L5-L13). Leaving out these modules, most modules have coverage >85%.

**Comment by ylemkimon** [comment]
@skirpichev @moorepants Currently external modules(optional dependencies) testing and slow tests are not included, but not omitted nor excluded. Leaving out these modules, most modules have coverage >85%. Also integrals module has RUBI integrator which has 25k lines of rules, but doesn't have all tests yet–I'm not sure about its status.

**Comment by ylemkimon** [comment]
@moorepants This PR hooks coverage.py to python process using pth file, so subprocess tests are supported.

**Comment by ylemkimon** [comment]
Including doctests, optional dependencies tests, and slow tests and excluding RUBI rules and pygletplot, coverage is about 87%: https://codecov.io/gh/ylemkimon/sympy/branch/coverage

**Pull request closed without merging**
