### PR TITLE
Update .mailmap

### PR DESCRIPTION
**Pull request by Peter230655**
added Peter Stahlecker

#### Release Notes

* sympy
  * added Peter Stahlecker to mailmap

### CODE REVIEW

**Comment by Peter230655** [comment]
I am at a loss on how to put my name on this mailmap list.

**Comment by moorepants** [comment]
You seem to have done it, but you should do it in the branch of the original PR.

**Comment by Peter230655** [comment]
> You seem to have done it, but you should do it in the branch of the original PR.

I seem to be too stupid for this! :-(
- I went to this file
- I selected to update in my fork
- It apparently created a new branch patch-1
- I made a commit
- I made a PR
- it failed the test because
  - my name was not in the list
  - the description what I did was wrong
 I closed the PR
Now it tells me I can delete this branch patch-1
**I just do not know what to do.**
-

**Comment by moorepants** [comment]
> I selected to update in my fork

I guess the default for that is to make a new branch for a new PR, but you need to work on the same branch in the other PR. So don't select "update in my fork". Do these things from the command line in git so we can help you.

**Comment by Peter230655** [comment]
> > I selected to update in my fork
> 
> I guess the default for that is to make a new branch for a new PR, but you need to work on the same branch in the other PR. So don't select "update in my fork". Do these things from the command line in git so we can help you.

I cannot find a copy of mailmap in my local directory of sympy, but I would need it there, correct?

**Comment by moorepants** [comment]
FIles that start with a `.` are "hidden" files on most operating systems. Maybe you are missing it because of that.

**Comment by Peter230655** [comment]
> FIles that start with a `.` are "hidden" files on most operating systems. Maybe you are missing it because of that.

I thought with ls -a I could see them, too?
let me look again.

**Comment by moorepants** [comment]
Yes, `ls -a` will show them.

**Comment by Peter230655** [comment]
> Yes, `ls -a` will show them.

I found the file! :-). Even saw it, using cat .mailmap
Would I type:  echo "Peter Stahlecker <peter.stahlecker@gmail.com>   Peter230655 <peter.stahlecker@gmail.com>" >> .mailmap 
?
Thanks!

**Comment by moorepants** [comment]
yes that should work

**Comment by Peter230655** [comment]
> yes that should work

I succeeded to add the line at the end of .mailmap. I saw it was there by using cat .mailmap.
All in my local branch KanesMethodComplex
I did 
git add .mailmap
git commit -m "added Peter Stahlecker to .mailmap"
all worked, but now I cannot push it:

image

**Comment by moorepants** [comment]
It gives you a hint of what to do.

**Comment by Peter230655** [comment]
> It gives you a hint of what to do.

They are close to Chinese for me. The tip of my current branch? Is this what was called HEAD in the lecture?
So I should do git pull origin KanesMethodComplex?

Sorry about the trouble - it is really hard for me - maybe because of age...

**Comment by moorepants** [comment]
>  So I should do git pull origin KanesMethodComplex?

Yes, that's the hint.

**Comment by Peter230655** [comment]
> > So I should do git pull origin KanesMethodComplex?
> 
> Yes, that's the hint.

I am so glad you translate **git Chinese** for me! Now it worked!
image
That's all, no PR needed?

**Pull request closed without merging**
