### PR TITLE
Added configuration option for imaginary_unit in the LaTeX and pretty printers

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed
It is possible to change the LaTeX used for the imaginary unit. Earlier it was always `i`, now it can be anything the user wants. Most likely, people will use `j` (this is what I will use most of the time) or `\mathrm{i}`. Set by `imaginary_unit` as an optional argument.

#### Other comments
Should one add a check that it is actually a string (`ininstance in string_types`)? Is it possible to break something serious by sending in e.g. a lambda there?

#### Release Notes

* printing
  * Representation of the imaginary unit, `I` in sympy, can be redefined in the LaTeX-printer through the optional argument `imaginary_unit`. Default is `"i"`.

### CODE REVIEW

**Comment by oscargus** [comment]
Unrelated test failure, but I will add a test for it.

**Comment by asmeurer** [comment]
Tertiarily related to https://github.com/sympy/sympy/issues/7194.

**Comment by oscargus** [comment]
I added configurability to the pretty printer as well. There one can choose between "i" leading to ⅈ or "j" leading to ⅉ. As there is a conversion to Unicode characters involved I didn't include an option for a general string as most users do not know how to get a Unicode character in the first place.
Admittedly, the way it is implemented is not very nice, but I couldn't really figure out a different way since `pretty_atom` is a static function. Not sure if this is enough to close #7194 but maybe worth considering at least.

I also added some checks for the arguments in both cases. For MathML it seems like there is more or less well defined that it should be `imaginaryi` in the content printer and `&ImaginaryI;` in the presentation printer.

**Comment by oscargus** [comment]
As an additional bonus, I threw in some tests for the MathML printer option `root_notation`. It made more sense when I thought that I was going to add `imaginary_unit` to that printer as well. Now it is sort of non-related...

**Pull request merged**
