### PR TITLE
Tweak solve an equation algebraically guide

### PR DESCRIPTION
**Pull request by bertiewooster**
Remove suggestion to filter using inequalities. Remove spaces around `**` to make e.g. `x**2` not `x ** 2`. Limit line width globally.

#### Brief description of what is fixed or changed
Fix changes suggested after #23638 merged

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Looks good.

**Comment by bertiewooster** [comment]
Thanks @oscarbenjamin. I was considering if it's worth backporting this to 1.11, partly so we can have one sub-page in the latest (not dev) docs build so we can start assessing its performance in Google Search Console sooner--that's one of the [metrics in the Season of Docs proposal](https://github.com/sympy/sympy/wiki/Season-of-Docs-2022-Organization-Application#measuring-your-projects-success). What do you think? Do you have a timeframe in mind for the 1.11 release?

**Comment by oscarbenjamin** [comment]
We can do. You can cherry pick the commits from here into a new PR against the 1.11 branch if you want to do that.

**Comment by bertiewooster** [comment]
Great!

I've never done a backport before. This backport would comprise two pull requests, first #23638 and then this one #23805. Any guidance on how to best accomplish that would be appreciated. (I learned that there's now a [GitHub Action for backporting](https://github.com/sqren/backport), but it seems like the pull request has to be tagged as backport before it's merged.)

**Comment by oscarbenjamin** [comment]
There are a number of ways to do it. Basically you just want to open a PR with the same diff as whatever PR is intended to be backported.

If you create a new branch from the release branch (1.11) then you can use `git cherry-pick` to select the commits that you want to include. This works particularly well if the PR was rebased with squashed commits so that it is just a single commit to cherry-pick.

What makes it a little harder is if the PR contains lots of commits and what makes it a lot harder is if it has merge commits. Then you don't want to cherry-pick those commits. Instead you need to figure out the right `git diff` incantation to get the diff that you want and then do
```
git diff commit_base commit_merge > backport.patch
git apply backport.patch
```
That will apply the diff on the branch that you have created. The commits you need for the diff are those that give the diff seen in the "files changed" tab on a PR. The merge commit for the PR has two parents: one is the commit that merged the previous PR to master and the other is the final commit in the PR. You want the diff between the merge commit itself and the parent that was the previous merge commit. Note that your own local branch for the PR won't contain the merge commit itself (although you should be able to see it on master). The `-m` option to cherry-pick can be used to combine the diff/apply steps:
https://stackoverflow.com/questions/37995545/backporting-a-git-branch-with-rebase

Generally if you follow the rebase and squash type patterns rather than making merges in the PR then this kind of stuff is a lot easier. I would have squashed both of those PRs (especially #23638). There is no need to have merge commits apart from the ones that actually merge the PR to master.

**Pull request merged**
