### PR TITLE
Update to antlr 4.11

### PR DESCRIPTION
**Pull request by xhochy**
#### Release Notes

* other
  * Update ANTLR version to 4.11

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
CC @eagleoflqj 

Is there a way that we can make this more future proof rather than just periodically regenerating the files and pinning the version?

**Comment by eagleoflqj** [comment]
As ANTLR tends to break compatibility when it upgrades, my answer would be no.
One possible approach is, since everything works fine, we don't need to track it and upgrade. But if anyone makes a PR and CI passes, we can merge it.
Or, as discussed before, replace ANTLR with lark or something else. But the baseline should be passing all existing tests.

**Comment by asmeurer** [comment]
The way to fix this is to move to a parser that doesn't require pinning. Ideally one that's more featureful and less of a heavy dependency (i.e., pure Python).

**Comment by asmeurer** [comment]
I guess the tests pass so this works.

**Pull request merged**
