### PR TITLE
geometry - projection method returns EmptySet when there is no projection

### LINKED ISSUE #22807: let some sort of EmptySet represent null object in geometry
Projections and intersections that are non-existant could be represented by EmptySet. Currently, projections raise an error and intersections return `[]`:

```python
>>> s
Segment2D(Point2D(0, 0), Point2D(0, 1))
>>> t
Segment2D(Point2D(1, 0), Point2D(2, 1/2))
>>> s.projection(t)
Segment2D(Point2D(0, 0), Point2D(0, 1/2))
>>> t.projection(s)
Traceback (most recent call last):
...
AttributeError: 'EmptySet' object has no attribute 'direction'

>>> s.intersection(t)
[]
```

Alternatively a geometric "Null" object -- not sure what it should be called, maybe GeometricEmptySet? -- could be created and used instead, so all geometric methods with it could return a null result (rather than giving EmptySet geometry related methods. e.g.
`GeometricEmptySet.projection(Line(Eq(x,0))) -> GeometricEmptySet`.

### PR DESCRIPTION
**Pull request by praneethratna**
#### Brief description of what is fixed or changed
Partially Fixes #22807 and now `projection` method returns EmptySet when there is no projection of one entity onto another.

#### Release Notes

* geometry
   * `projection` method of `line.py` now returns EmptySet when there is no projection of one entity onto another.

### CODE REVIEW

**Comment by praneethratna** [comment]
CC @smichr

**Comment by smichr** [comment]
Looks good.

**Comment by asmeurer** [comment]
Please write your release notes so that they make sense to an end-user reading the release notes file. "Made changes in `line.py`" is meaningless to someone who just wants to know what changed in the release. It's not even particularly helpful for people reviewing this PR.

**Comment by praneethratna** [comment]
> Please write your release notes so that they make sense to an end-user reading the release notes file. "Made changes in `line.py`" is meaningless to someone who just wants to know what changed in the release. It's not even particularly helpful for people reviewing this PR.

Sorry for that vague release note. I've updated the Release notes now which looks much better to the end user.

**Pull request merged**
