### PR TITLE
[Do Not Merge]Discussion on GSoC proposal for improving Series expansion

### PR DESCRIPTION
**Pull request by shivamvats**
I am applying for GSoC to add series expansion to CSymPy and improve Sympy's series expansion by making it faster and giving it a class representation. The present PR covers only the part, related to Sympy. You are most welcome to see and comment on the whole proposal at https://github.com/sympy/sympy/wiki/GSoC-2015-Application--Shivam-Vats-:-Series-expansions.

I have sent it in the form of a PR, as I like the PR workflow  and it makes really easy for others to comment on specific points.
@certik @asmeurer @goodok @pernici

### CODE REVIEW

**Comment by jcrist** [comment]
Closing. Please post on the mailing list, or create wiki pages in sympy's wiki for discussion.

**Comment by toolforger** [comment]
Do we have a policy that PRs must only contain stuff that's supposed to go in?
Because I'm seeing other PRs for that purpose, and have done so myself without being told it shouldn't be done.

**Comment by shivamvats** [comment]
This pull request was inspired by #2948 and no one seemed to have an issue with it, then. 
That said, this should probably be closed as the Gsoc deadline is already over, unless of course anyone wants to comment on something.

**Comment by toolforger** [comment]
Oh dammit, `C` was part of the `sympy` namespace. By normal rules, it should have been deprecated for 0.7.7 and scheduled for removal in a later version.
Do we risk breaking compatibility anyway, under the assumption that no user should ever have had a reason to use it?
Or we could instate a `C` that's just an alias of `all_classes`.

**Comment by jcrist** [comment]
@toolforger : good point, I thought someone had already thought this through when I merged. We can always add it back in (just don't use it internally). You should open an issue for discussing. IMO, `C` wasn't public api, but others may disagree.

**Comment by jcrist** [comment]
@shivamvats : I was just cleaning up our huge list of pull requests - a PR does make it nice for discussion. I was not aware that we had such a precedent. Either way, GSoC proposal period is over (as you said).

**Pull request closed without merging**
