### PR TITLE
 Remove `_print_GeometricEntity` method from `StrPrinter` class

### PR DESCRIPTION
**Pull request by namannimmo10**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
The PR title "completes one todo task" is very uninformative (and should be changed). Without any reference to any issue I don't know what the purpose of this is

**Comment by oscarbenjamin** [comment]
Does this test all geometry entities?

**Comment by namannimmo10** [comment]
Nope. Some of them are still left (for instance -- `Parabola`). But why do we have to check for all of them?

**Comment by oscarbenjamin** [comment]
> But why do we have to check for all of them?

That's a good question. Right now 2 of them are checked. This PR checks 3 more. If checking 2 is insufficient then is it sufficient to check 5?

I guess if we check all of them then at least we know that we don't need any more checks.

**Comment by namannimmo10** [comment]
OK. I'll update soon. 
Just on a side note -- which debugger do you use?

**Comment by oscarbenjamin** [comment]
> which debugger do you use?

I use pdb.

**Comment by sylee957** [comment]
I don't think that the printer doesn't do much things much special for geometry, so it would be abundant than necessary.

But I'd not call `str` like this because it can cause bugs applying the printer settings consistently

```
    def _print_GeometryEntity(self, expr):
        # GeometryEntity is special -- it's base is tuple
        return str(expr)
```

**Comment by namannimmo10** [comment]
> But I'd not call `str` like this because it can cause bugs applying the printer settings consistently
> 
> ```
>     def _print_GeometryEntity(self, expr):
>         # GeometryEntity is special -- it's base is tuple
>         return str(expr)
> ```

Maybe we can use `expr.__repr__()` instead of `str(expr)`. Please refer this [discussion](https://bugs.python.org/issue1534769#msg29448). 
So that would be:
```
>>> expr.__repr__()
'Polygon(Point2D(5, 6), Point2D(-2, -3), Point2D(0, 0), Point2D(4, 7))'
```

**Comment by sylee957** [comment]
I meant that it should use self._print(expr)

**Comment by namannimmo10** [comment]
> I meant that it should use self._print(expr)

Using this, I get:
>   File "/home/namannimmo/sympy/sympy/printing/printer.py", line 289, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "/home/namannimmo/sympy/sympy/printing/str.py", line 161, in _print_GeometryEntity
    return self._print(expr)
  File "/home/namannimmo/sympy/sympy/printing/printer.py", line 289, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "/home/namannimmo/sympy/sympy/printing/str.py", line 161, in _print_GeometryEntity
    return self._print(expr)
RecursionError: maximum recursion depth exceeded

**Comment by sylee957** [comment]
Okay, to correct, what about deleting the _print_GeometricEntity such that it gets propagated down to basic?

**Comment by namannimmo10** [comment]
That would be great.

**Comment by sylee957** [comment]
I see some printing options are working after the fix.
Can you add some tests like
```
A = Triangle(Point(0, 0), Point(1, 0), Point(0, 1))
sstr(A, sympy_integers=True)
```

**Comment by namannimmo10** [comment]
Ping @sylee957

**Pull request merged**
