### PR TITLE
Added custom set support for JointRV

### PR DESCRIPTION
**Pull request by supreet11agrawal**
This PR is not yet completed. I made this PR to get opinions of other members
as well. The tests are passing with this change. However, it is not giving
desired results. Test cases are to be added to overcome such vulnerabilities.

#### Release Notes

* stats
  * Custom set support for joint distributions

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Can you explain what is currently working and not working with this PR and how it differs from master?

**Comment by supreet11agrawal** [comment]
Currently, `JointRV` has no option of choosing the domain on which the random variables are defined. This change tackles with that. Also, `JointRV` only takes indexed symbols; it cannot take any random symbols, say `x` and `y` as random variables. This PR will change that as well. I have changed the second issue locally and it needs some minor changes before I commit them.

**Comment by oscarbenjamin** [comment]
Are you still working on this? The OP says that this is not yet completed.

It's not clear to me from the OP or the release note what would be changed by this.

**Comment by supreet11agrawal** [comment]
I need suggestions from other members on this. The basic idea is to increase the functioning of multivariate distributions. Currently they use indexed symbols, but I thought it might be better to have functionality for any random symbols as well. I thought @Upabjojr @jksuom  might be able to suggest their views on this as well.

**Comment by Upabjojr** [comment]
I don't see a great advantage in adding support for arbitrary symbols as joint random variables (is that what you mean with this PR?).

**Comment by supreet11agrawal** [comment]
> I don't see a great advantage in adding support for arbitrary symbols as joint random variables (is that what you mean with this PR?).

Yes, precisely.

**Comment by czgdp1807** [comment]
@supreet11agrawal Would you still like to work on this PR? It looks like a good work. Thanks for the contribution.

**Comment by czgdp1807** [comment]
Due to no response and in reference to https://github.com/sympy/sympy/pull/16593#issuecomment-506521526 closing this PR for now. Please let us know if there is a need to re-open it.

**Pull request closed without merging**
