### PR TITLE
Run flake8 in the test_travis.sh script

### PR DESCRIPTION
**Pull request by asmeurer**
See #18494.

Hopefully this also causes the errors that I get locally to appear on Travis.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
OK, well it definitely is being run, but still doesn't give those errors I see locally. @oscarbenjamin do you know what is going on here? The errors in question definitely are pyflakes errors that aren't skipped with any noqa comments.

**Comment by oscarbenjamin** [comment]
https://github.com/sympy/sympy/pull/18489#discussion_r371502565

**Comment by asmeurer** [comment]
The reason was explained on the issue. I have pushed a fix here to make `flake8 sympy` pass in Python 3.7.  We can remove the duplicated noqa lines when we support 3.8+ only. 

This is ready for review.

**Comment by oscarbenjamin** [comment]
Looks good

**Pull request merged**
