### PR TITLE
Change default value of rref simplify flag to True

### LINKED ISSUE #10120: Default value of simplify flag of rref() should be True
The default value of the `simplify` flag of `rref()` is False, which is confusing because it means some symbolic calculations do not work by default. This was recently highlighted in #10056 , which was caused by `linsolve` not setting the flag correctly. I notice in matrices.py both `rank` and `QRDecomposition` call `rref` without simplify by default, which also risks causing problems. 

In [this stackoverflow question] (http://stackoverflow.com/questions/19072700/why-does-sympy-give-me-the-wrong-answer-when-i-row-reduce-a-symbolic-matrix) about this issue @asmeurer says:

> The option is off by default because in general such simplification can be expensive, through this can be controlled by passing in a less general simplify function than simplify (for rational functions, use cancel). The defaults here could probably be smarter.

Indeed, you would think it should be an option which you could turn off for speed if you knew it was safe, rather than the other way around, as users (like the stackoverflow user) might not know about the flag.

@aktech

### PR DESCRIPTION
**Pull request by MooVI**
Fixes #10120 . See discussion in that issue. 

To summarise:

Without `simplify=True`, `rref` will silently return wrong results for symbolic matrices. Although simplification is slow, until a better zero-testing method is implemented (which is the real solution, see #10279) the default value of the flag should be true.

The other possible solution, put forth by @moorepants is to leave the default value, but have `rref` output a warning when run that if you suspect the results to be wrong to rerun with `simplify=True`.

I favour changing the default value of the flag because:

a) It is more new-user friendly. Most new users will probably be using small matrices and won't be affected by the slowness of simplification, but will be confused by wrong answers, e.g [this stackoverflow question](http://stackoverflow.com/questions/19072700/why-does-sympy-give-me-the-wrong-answer-when-i-row-reduce-a-symbolic-matrix). 'Power' users with large expressions are more likely to look at the docs when their code runs slowly.

b) It is more dev-friendly! Several functions like `gauss_jordan_solve` use `rref` internally. I only ran into this problem because `linear_solve` was not working because the flag was not set correctly. Also, in some functions (which only deal with numerics, say) it might be known that the simplify flag is not needed -- do we then add another to suppress the warning?

### CODE REVIEW

**Comment by MooVI** [comment]
An example which illustrates the dire speed problem:

```python

from sympy import *
J, J2 = symbols('J J2')
m = Matrix([[2*J2, -2*I*J, 0, 0, 0, -2*I*J, 0, 0, 2*J2, 0, 0, 0, 0, 0, 2*I*J, -2*J2, 0], [2*J2, -2*I*J, -2*I*J, 0, 0, 0, 0, 0, 0, -2*J2, 0, 0, 0, 0, 2*I*J, -2*J2, 0], [0, 0, -2*J2, -2*I*J, -2*I*J, -2*J2, 0, 0, 0, 0, 0, 2*J2, 0, 0, 0, 2*I*J, 0], [0, 0, -2*I*J, 2*J2, 2*J2, -2*I*J, 0, 0, 0, 0, 0, 0, 2*J2, 0, 2*I*J, 0, 0], [0, 2*I*J, 2*I*J, -2*J2, -2*J2, 2*I*J, 0, 0, 0, 0, -2*J2, 0, 0, 0, 0, 0, 0], [2*I*J, 0, 2*J2, 2*I*J, 2*I*J, 2*J2, -2*J2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [-2*J2, 0, 0, 0, 0, 0, -2*I*J, 2*I*J, -2*J2, 2*J2, 0, 0, 0, -2*I*J, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 2*I*J, -2*J2, 2*J2, 0, -2*I*J, 0, -2*I*J, 0, 2*J2, 0], [0, 0, 0, 0, 0, 0, 0, -2*J2, -2*I*J, 2*I*J, 0, 0, -2*I*J, 2*J2, 2*J2, 0, 0], [0, 0, -2*J2, 0, 0, 0, 2*J2, 0, 0, 2*I*J, -2*I*J, 2*J2, -2*I*J, 0, 0, 0, 0], [0, 0, 0, 2*J2, 0, 0, 2*I*J, 0, 0, 0, 2*J2, 2*I*J, 2*J2, 2*I*J, 0, 0, 0], [0, 0, 0, 0, -2*J2, 0, -2*I*J, 2*I*J, 0, 0, -2*J2, -2*I*J, -2*J2, 0, 0, 0, 0], [0, 0, 0, 0, 0, 2*J2, -2*J2, 0, 2*I*J, 0, 2*I*J, -2*J2, 2*I*J, 0, 0, 0, 0], [0, -2*J2, 0, 0, 0, 0, 0, -2*J2, -2*I*J, 2*I*J, -2*I*J, 0, 0, 2*J2, 0, 0, 0], [-2*I*J, -2*J2, 0, -2*I*J, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*J2, 2*J2, 2*I*J, 0], [-2*I*J, -2*J2, 0, 0, -2*I*J, 0, 0, -2*J2, 0, 0, 0, 0, 0, 0, 2*J2, 2*I*J, 0]])

%timeit m.rref(simplify=False)
%timeit m.rref(simplify=True)

```

Here `m.rref(simplify=False)` correctly finds the answer (which is just the identity plus a zero column), so a timing comparison is fair. On my machine simplify=False takes about 2s while simplify=True takes about 5 minutes 20s, which is a slow down of 160x ! Note that `m` while large does not even have any complex elements -- they are all proportional to J xor J2. I assume the `rref` algorithm necessarily makes it complicated as it runs.

**Comment by MooVI** [comment]
OK, so the change I thought would be harmless isn't, because #10119 hasn't been merged yet, so this commit currently changes the behaviour of `linsolve`. When that commit is merged in this will work.

You might ask why setting `simplify=True` should cause a test to fail when it worked before, given it should only give the same results unless the `simplify=False` doesn't work. The problem is that `test_formal` requires solution of:

```python
m = Matrix([
[sin(x)*cos(x),          0, -4*sin(x)*cos(x),            0],
[            0, -sin(x)**2,                0, -4*sin(x)**2],
[            0,  cos(x)**2,                0,  4*cos(x)**2]])
```

Comparing the results of `rref` by hand:

```python
>>m.rref(simplify=False)
(Matrix([
[1, 0, -4, 0],
[0, 1,  0, 4],
[0, 0,  0, 0]]), [0, 1])

>>m.rref(simplify=True)
(Matrix([
[1, 0, -8*sin(x)*cos(x)/sin(2*x), 0],
[0, 1,                         0, 4],
[0, 0,                         0, 0]]), [0, 1])
```

we see they are the same, but the answer with `simplify=True` is (ironically), much more complex, necessitating a further `simplify` on the answers to get the solution in simplest form, which is of course even slower.

Given `linsolve` is used internally like this, we *really* need a solution to #10279.

**Comment by MooVI** [comment]
Pinging everyone involved in #10120 now that this PR is ready to discuss @asmeurer @aktech @moorepants

**Comment by bjodah** [comment]
What about using the default `simplify=None` which could trigger a heuristic using `simplify=False` if it is known to work (only integers in the matrix for example) and `simplify=True` if no such guarantees can be made. That 160x slowdown is quite horrific in my book and it would essentially "break" existing code.

**Comment by MooVI** [comment]
@bjodah 

That's certainly possible. It's worth noting though that:

a) The ridiculous slowdown is only for matrices with hard-to-simplify expressions. For integers or floats there seems to be no measurable overhead:

```python
 %timeit randMatrix(30).rref(simplify=True)
1 loops, best of 3: 1.13 s per loop

In [16]: %timeit randMatrix(30).rref(simplify=False)
1 loops, best of 3: 1.13 s per loop
```

b) The algorithm used in `rref` is as far as I am aware naive Gauss-Jordan, which is fine for symbolic expressions, but is highly un-optimal for numeric calculations anyway.

**Comment by bjodah** [comment]
@MooVI yes I was refering to sympy integers (which are unfortunately not always used automatically see e.g. #10295).

I see, in that case I am +1 for changing the default (unless there is some class of expressions which actually are expensive to simplify but cheap to classify and guaranteed to be correct).

**Comment by bjodah** [comment]
@moorepants how do you feel about merging this? (you were undecided in #10120)
This appeared in #10718, there a default of `simplify=True` would have been less confusing for a user.
I'm thinking: people working on large problems (using sympy as an underlying library) are more likely to read the docs thoroughly than people just passing in small, say 3x3 matrices, interactively.

**Comment by moorepants** [comment]
Sure, it is better to have correct results than incorrect ones. But this is going to cause some major issues. It needs to be deprecated to give people a warning to fix their code and documented clearly.

**Comment by jksuom** [comment]
There might be other possibilities. The issue seems to be that is_zero in the default iszerofunc may return None. One possibility could be applying simplify (in iszerofunc) in that case..

**Comment by MooVI** [comment]
To reiterate, I'm not claiming this PR is anything more than a stopgap; a proper solution will only be possible once we have a solution to #10279. But it is a clearly needed stopgap, given issues like #10718.

**Comment by smichr** [comment]
Just adding some thoughts that occur to me that haven't come to me before regarding this issue:

1. our ultimate goals in matrix inversion are 1) to not divide by an expression that is *identically* zero and 2) to not let symbolic explosion bog us down. The former requires testing for zero and the latter requires simplification. It has been shown above that the matrix involving J and J2 can be solved quickly without simplification, but one has **no assurance that the result has any meaning** unless zero pivots were avoided
1. if an element is symbolic it *could* be zero, e.g. if we had to divide by `x`, unless assumptions told us that it was not zero then it might be zero; to report a result obtained by dividing by such "possible zeros" *it would be wise to report the assumptions that were used in the inversion process*
1. simplification is one means to distinguish between **identically zero** and **possible zero** expressions since it will change things like `cos(x)**2 + sin(x)**2 -> 1` and `x*(1-x) + x**2-x -> 0`. Selecting the simplification necessary for the expressions involved is important
1. rather than looking at trying to prove that something is zero or not, we might think of whether we could show that the expression is possibly *not* zero. This is part of the strategy of the `equals` method which uses `is_constant` -- if something is not constant it can't be identically zero.
1. perhaps we need a `could_be_nonzero` function which, instead of working hard to prove that something is zero, works to show that something could not be zero:

```
def could_be_nonzero(expr):
    # try to show that something is non-zero without using simplify
    if expr is a number: conclude based on being able to compute expr with precision
    elif expr is a polynomial in symbols: use random evaluation
    elif expr is a polynomial in trig functions whose arguments are identical:
       rewrite in terms of exp and then into symbols and check that *as a polynomial*
    else: use random numerical testing with values **in the domain** of the expression
```

Finally, I think we should raise an error (as @moorepants has said?) if at any point the matrix inversion cannot conclude find a pivot that is affirmatively not zero.

_____

Regarding the trig rewrite, here's an example showing that the transformed expression can evaluate

```
>>> eq=cos(x)**2 + sin(x)**2 - 1
>>> eq.subs(x,1).n()
-0.e-124  <-- evalf is not sure if this is zero
>>> eq.rewrite(exp).subs(x,1).n()
-0.e-131 + 0.e-135*I  <-- ditto
>>> eq.rewrite(exp).subs(exp(I*x),y).subs(y,1).n()
0  <-- evalf is sure that it's zero
>>> eq.rewrite(exp).subs(exp(I*x),y).subs(y,1)._random()
0 <-- even at a random point
```

**Comment by smichr** [comment]
> One possibility could be applying simplify (in iszerofunc) in that case..

That seems like a good idea.

**Comment by smichr** [comment]
> But this is going to cause some major issues

I assume that you think this because people who were formerly happily inverting matrices in short order will now find that it takes a long time to do so. But did they have any reason to be confident that the matrix inversion was valid? Even if the inversion exists, one must watch out for division by zero. But if, under some conditions, we know that *can't* occur then we should be able to check for those conditions and not use simplification when trying to test for zero if those conditions are met.

Are there conditions that guarantee that a zero pivot will not be encountered?

**Comment by siefkenj** [comment]
This is handled dynamically by the new `rref`code, which should make this moot.

**Comment by moorepants** [comment]
Closing.

**Pull request closed without merging**
