### PR TITLE
Backport solve equation algebraically guide from master into 1.11 release

### PR DESCRIPTION
**Pull request by bertiewooster**
#### References to other Issues or PRs

Mirrors  and #23638 and #23805 on master branch

#### Brief description of what is fixed or changed
Add solve equation algebraically guide from master into 1.11 release branch

#### Release Notes

* other
  * A new, user-friendly page on solving an equation algebraically was added to the Guides section.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I have a PR to fix the CI failure #23864

**Comment by bertiewooster** [comment]
Good deal. And thanks for your guidance on backporting with for. 

I realized I forgot to make a branch off 1.11--I just used my local 1.11 branch. If that's a problem, I can re-make the changes on a branch off my 1.11 branch.

**Comment by oscarbenjamin** [comment]
If your local 1.11 branch is tracking the upstream 1.11 branch then that's basically the same (although your branch might be out of date if you haven't updated it with git pull).

Did you mean to mark this as draft?

**Comment by bertiewooster** [comment]
> If your local 1.11 branch is tracking the upstream 1.11 branch then that's basically the same (although your branch might be out of date if you haven't updated it with git pull).

OK, good deal. I pulled the upstream branch just before doing the git operations.

> Did you mean to mark this as draft?

I just wanted to manually check that my git operations produced the desired result. They did, so I marked this as ready for review.

FYI, patching (determining the diff and then applying it per your helpful instructions) worked for the first pull request #23638, but when I created a second patch for the second pull request #23805 and tried to apply it, I got the following error, so I used git cherry-pick to add the three (non-merge) commits from the second pull request.

```
--patch failed:
error: patch failed: doc/src/guides/solving/solve-equation-algebraically.md:1
error: doc/src/guides/solving/solve-equation-algebraically.md: patch does not apply
```

**Comment by oscarbenjamin** [comment]
Looks good, thanks.

**Pull request merged**
