### PR TITLE
fix(printer) Add isnan and isinf support for tensorflow printer

### LINKED ISSUE #26784: How to cast nan to not-nan in an expression
Hi, I'm new to Sympy and I wonder how to cast null value to a default value in a Sympy expression
For example
```
import sympy as sp
x = sp.symbols("x")
# Return 0 if x is of nan value, and 1 otherwise
exp = sp.Piecewise((0.0, sp.Eq(x, sp.nan)), (1.0, True))
sp.lambdify((x), exp)(x=float('nan'))
Out[28]: 1.0
```
The above expression returns 1.0 instead of 0.0
I found that the problem comes from the expression
```
In [29]: sp.Eq(x, sp.nan)
Out[29]: False
```
It seems that `sp.Eq` does symbolic evaluation on variable `x` instead of waiting for the input from the actual calculation

Maybe I'm using sympy in a wrong way. But would appreciate someone to shed some light on how to do this

Thank you

### PR DESCRIPTION
**Pull request by zexuan-zhou**
#### References to other Issues or PRs

A further improvement for the fix #26784. Specifically to address this [comment](https://github.com/sympy/sympy/issues/26784#issuecomment-2237483117)

#### Brief description of what is fixed or changed
Add isnan and isinf support for tensorflow printer

#### Release Notes

- printing
  - Add `_print_isnan` and `_print_isinf` in TensorflowPrinter.

### CODE REVIEW

**Comment by zexuan-zhou** [comment]
@oscarbenjamin PR is ready. Please take a look when you have a chance. Thank you

**Comment by oscarbenjamin** [comment]
@bjodah can you review this?

**Comment by bjodah** [comment]
This looks good. Thank you!

**Comment by zexuan-zhou** [comment]
Thanks guys. When will 1.14 be released?

**Comment by oscarbenjamin** [comment]
No sure. 1.13 was only released recently so not for a while.

**Comment by zexuan-zhou** [comment]
@oscarbenjamin Hi Oscar. If I need this patch, what's the fastest way to get a package? Is it possible to build a temporary release for it? Thanks

**Comment by oscarbenjamin** [comment]
You can install directly from git:
```
pip install git+https://github.com/sympy/sympy.git@master
```

**Comment by zzhou4-sc** [comment]
Hi. Curious when 1.14 will be released. Thanks

**Comment by zexuan-zhou** [comment]
Hi. Curious when 1.14 will be released. Thank you

**Comment by bjodah** [comment]
@zexuan-zhou, new major releases have historically been released with a frequency on the order of once per year.

**Pull request merged**
