### PR TITLE
Inconsistencies draw function for beams fixed

### LINKED ISSUE #18964: Inconsistencies in draw function of beam class
In Sympy continuum mechanics Beam Class, the draw function produces wrong diagrams.
`E, I = symbols('E, I')`
`b = Beam(10, E, I)`
`b.apply_support(0,'pin')`
`b.apply_support(8.3, 'roller')`
`b.apply_load(-1, 2, 2)`
`b.apply_load(-2, 4, -2)`
`b.apply_load(3, 6.3, -1)`
`b.draw().show()`
image

Here the point load is positive and parabolic load is negative but they have same directions.
`b.apply_load(1, 2, 2)`
`b.apply_load(2, 4, -2)`
`b.apply_load(-3, 6.3, -1)`

image

Changing the signs of all the loads changes the direction of unit load and moment load but parabolic load acts on the same direction.
There is also an inconsistency with sign convention of point load and moment load.
See [this](https://groups.google.com/forum/#!msg/sympy/MhRJ1Ahl8i0/roNHvKt6AQAJ).
 Upward forces and clockwise moments should have same signs(positive or negative) as discussed [here](https://github.com/sympy/sympy/issues/18045). 
The draw function assigns downward direction to positive point loads and clockwise direction to positive moment loads, regardless of the sign convention user chooses.

### PR DESCRIPTION
**Pull request by Psycho-Pirate**
#### References to other Issues or PRs

Fixes #18964

#### Brief description of what is fixed or changed
beam.py is modified. 
- A note regarding sign convention is added.
- The draw function shows correct directions for loads with n>-1.
- Moment loads and point loads follow proper sign convention.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by moorepants** [comment]
Can you paste in an image showing this works?

**Comment by Psycho-Pirate** [comment]
```
>>> from __future__ import print_function, division
>>> from sympy import *
>>> from sympy.external import import_module
>>> numpy = import_module('numpy')
>>> from beam import Beam
>>> from sympy import symbols, Piecewise
>>> init_printing(use_unicode=True, wrap_line=False)
>>> E, I = symbols('E, I')
>>> R_0, R_8 = symbols('R_0, R_8.30000000000000')
>>> b = Beam(8.3, E, I)
>>> b.apply_support(0,'pin')
>>> b.apply_support(8.3, 'roller')
>>> b.apply_load(-30, 1, 0, 4)
>>> b.apply_load(12, 2, -2)
>>> b.apply_load(40, 3, -1)
>>> b.apply_load(-30, 1, 0, 4)
>>> b.apply_load(20, 0, 1, 4)
>>> b.apply_load(56, 4.5, 2)
>>> b.draw().show()
```
image



```
>>> from __future__ import print_function, division
>>> from sympy import *
>>> from sympy.external import import_module
>>> numpy = import_module('numpy')
>>> from beam import Beam
>>> from sympy import symbols, Piecewise
>>> init_printing(use_unicode=True, wrap_line=False)
>>> E, I = symbols('E, I')
>>> R_0, R_8 = symbols('R_0, R_8.30000000000000')
>>> b = Beam(8.3, E, I)
>>> b.apply_support(0,'pin')
>>> b.apply_support(8.3, 'roller')
>>> b.apply_load(30, 1, 0, 4)
>>> b.apply_load(-12, 2, -2)
>>> b.apply_load(-40, 3, -1)
>>> b.apply_load(30, 1, 0, 4)
>>> b.apply_load(-20, 0, 1, 4)
>>> b.apply_load(-56, 4.5, 2)
>>> b.draw().show()
```
image

Do you want me to add more? @moorepants

**Comment by Psycho-Pirate** [comment]
Please review @moorepants

**Comment by moorepants** [comment]
It looks good. I don't think we have an easy way to write a unit test for this, so I'm going to merge as is based on the output shown above.

**Pull request merged**
