### PR TITLE
Changes to PR #12000

### PR DESCRIPTION
**Pull request by nilabja-bhattacharya**
PR as per discussion in #13381

### CODE REVIEW

**Comment by gxyd** [comment]
This PR wouldn't work either. Let's redo all that.
```
[sympy{master}]$ git fetch ayodejiige
[sympy{master}]$ git checkout -b new_branch ayodejiige/11668_bare_excepts 
Branch new_branch set up to track remote branch 11668_bare_excepts from ayodejiige.
Switched to a new branch 'new_branch'
[sympy{new_branch}]$ # make some changes to file and commit that change
[sympy{new_branch}]$ git push origin new_branch
```

**Comment by nilabja10201992** [comment]
@gxyd I tried it but it doesn't say this` Branch new_branch set up to track remote branch 11668_bare_excepts from ayodejiige.` I do not know what to do.

```
neil@neil-HP-Pavilion-15-Notebook-PC:~/sympy$ git fetch https://github.com/ayodejiige/sympy
From https://github.com/ayodejiige/sympy
 * branch                HEAD       -> FETCH_HEAD
neil@neil-HP-Pavilion-15-Notebook-PC:~/sympy$ git checkout -b new_brnch ayodejiige/11668_bare_excepts
Switched to a new branch 'new_brnch'
neil@neil-HP-Pavilion-15-Notebook-PC:~/sympy$ git add sympy/
neil@neil-HP-Pavilion-15-Notebook-PC:~/sympy$ git push origin new_brnch
Username for 'https://github.com': nilabja10201992
Password for 'https://nilabja10201992@github.com': 
Counting objects: 1, done.
Writing objects: 100% (1/1), 196 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To https://github.com/nilabja10201992/sympy
 * [new branch]          new_brnch -> new_brnch
```

**Comment by gxyd** [comment]
Have you found a way to fix this?

**Comment by nilabja10201992** [comment]
@gxyd Sorry for disappointing but I wasn't successful in finding a solution, I tried but I couldn't, I guess it can only be done by someone who has write access to main branch.

**Comment by gxyd** [comment]
There is a way to do that (even for the ones without write access).
Follow the below commands:
```bash
$ git fetch ayodejiige
$ git checkout -b a_new_branch ayodejiige/11668_bare_excepts

# now make changes on this branch and commit the changes
# make sure you are doing this step the right way.

$ git push origin a_new_branch
```

If this doesn't work, I will ping someone else who can help you out. But I am sure there is a way.

**Comment by gxyd** [comment]
I am closing this PR in favor of #12000 , when I have addressed the changes.

**Pull request closed without merging**
