### PR TITLE
Update setup.py Python versions

### PR DESCRIPTION
**Pull request by drhagen**
The supported Python versions in setup.py were a little out of date. This brings them in line with .travis.yml.

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I think Python 3.5 is still tested.

What effect does this change to setup.py have? I guess this metadata is stored in the released wheels and used somewhere in by pip/PyPI. What does it do?

**Comment by oscargus** [comment]
Yes, 3.5 is still tested. But, without knowing exactly how it affect things, it seems to make sense to update it.

**Comment by drhagen** [comment]
> I think Python 3.5 is still tested.

You are correct. Python 3.5 should not have been removed. I have put it back.

> What effect does this change to setup.py have?

This is metadata that is displayed in PyPI indicating which Python versions sympy is compatible with.

**Comment by oscarbenjamin** [comment]
> > What effect does this change to setup.py have?
> 
> This is metadata that is displayed in PyPI indicating which Python versions sympy is compatible with.

Okay but does it affect e.g. whether or not pip install will download a particular wheel?

**Comment by drhagen** [comment]
No, that is what [python_requires](https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=python_requires#new-and-changed-setup-keywords) is for, which sympy does not use.

**Comment by oscarbenjamin** [comment]
Should SymPy use `python_requires`? Maybe once support for a particular Python version is dropped it would be better for users to get an older release that supports their version?

**Comment by drhagen** [comment]
> Should SymPy use `python_requires`?

NumPy and SciPy both use `python_requires='>=3.5'`. This would probably be a good thing for SymPy to do also.

**Comment by oscargus** [comment]
Since we still support 2.7 (until the end of the year), I think that it can (should) wait. I'll merge this now. Thanks!

**Comment by oscarbenjamin** [comment]
I think you can specify the version like `python_requires='>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*'`.

**Comment by asmeurer** [comment]
We definitely need to add python_requires once we drop 2.7 support so that pip in Python 2 will continue to work to install the last 2.7 compatible release.

**Pull request merged**
