### PR TITLE
[skip ci] PEP8 amendments to exprtools.py

### PR DESCRIPTION
**Pull request by jremes-foss**
Couple of amendments to exprtools.py. Just E301 this time.

Thank you.

### CODE REVIEW

**Comment by aktech** [comment]
Please don't skip ci from future, or check for trailing whitespaces.
See this: https://travis-ci.org/sympy/sympy/jobs/72456739

**Comment by Newman101** [comment]
Ok, I will leave the [skip ci] tag out from now on then. Thanks for notifying me about this. :+1:

**Comment by aktech** [comment]
It's fixed now here: https://github.com/sympy/sympy/commit/4c068e54a04e8f2ac00f3113b6cf70f765c50734

**Comment by moorepants** [comment]
@aktech I don't understand why [skip ci] should be avoided here. Or why you shouldn't check for trailing whitespace?

**Comment by aktech** [comment]
I didn't pulled this on my machine, so this was my bad, though I thought such trivial PR's could be reviewed just by looking at the diff, but the diff doesn't shows information about the trailing white-space, so one could just merge such PR's by just looking if test passes, without pulling on to the local machine.

**Comment by moorepants** [comment]
I see now. You meant: "either check for trailing whitespace or leave out [skip ci]". But why would leaving out "[skip ci]" do anything to help find trailing whitespace?

**Comment by aktech** [comment]
>  But why would leaving out "[skip ci]" do anything to help find trailing whitespace?

Leaving out `[skip ci]` would run `sympy/utilities/tests/test_code_quality.py` on Travis & checks for trailing whitespaces, so that the reviewer don't have to run this locally.

**Comment by moorepants** [comment]
I see. Well, it sure is a lot of overhead just to run that file. The whole test suite seems to take a day to run.

Too bad travis doesn't have a way to signal running a single item from the test matrix.

**Comment by aktech** [comment]
Indeed.

**Comment by Newman101** [comment]
I recall the reason for [skip ci] was to avoid Travis becoming stuck.

**Pull request merged**
