### PR TITLE
[WIP] Merge prde_special_denom with special_denm in rde.py

### PR DESCRIPTION
**Pull request by gxyd**
We had a [#TODO](https://github.com/sympy/sympy/blob/master/sympy/integrals/prde.py#L107), so I tried to see if I could get the two methods merged merged. It isn't a priority that it be necessarily merged, was just seeing if they could be merged cleanly.

My intention is either we improve upon this PR and eventually separate the two methods, or reach a conclusion they it is better that the two methods remain separated.

### CODE REVIEW

**Comment by gxyd** [comment]
**DON'T MERGE THIS**

**Comment by czgdp1807** [comment]
@gxyd Any updates on this? It looks like it can be closed.

**Comment by czgdp1807** [comment]
Closing this for now. Please let us know if there is a need to re-open this.

**Comment by oscarbenjamin** [comment]
Same comment as #12885

@czgdp1807 is there an issue somewhere that tracks progress in Risch? We should reference closed PRs there rather than just closing them. These represent substantial work that will be lost otherwise.

**Comment by asmeurer** [comment]
It would be helpful to have such an issue, not just for tracking abandoned PRs but also to give a high level overview of what remains to be done in Risch.

**Pull request closed without merging**
