### PR TITLE
Diofant import: Removed is_Mul heuristic in Limit.doit()

### PR DESCRIPTION
**Pull request by Upabjojr**
Second round of imports from @skirpichev 's fork.

### CODE REVIEW

**Comment by Upabjojr** [comment]
https://github.com/diofant/diofant/pull/61

**Comment by czgdp1807** [comment]
@Upabjojr Please update this PR.

**Comment by czgdp1807** [comment]
Current status of the tests added in this PR when executed on master,
```python
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(SymPyConsole)
>>> n = symbols('n', integer=True)
>>> x = symbols('x', real=True)
>>> limit((Pow(6, n + 1) + n + 1)/(Pow(6, n) + n), n, oo)
6
>>> (6**(x + 1)).as_leading_term(x)
6
>>> (6**(x + n)).as_leading_term(x)
 n⋅log(6)
ℯ        
>>> limit((x**100/((x + 1)**100 + exp(-x))), x, oo)
1
>>> limit((x**1000/((x + 1)**1000 + exp(-x))), x, oo)
1
>>> limit((6**(x + 1) + x + 1)/(6**x + x), x, oo)
6
```
I am adding `Could Close` label. Please remove this PR is required to be merged. ping @Upabjojr

**Comment by czgdp1807** [comment]
Closing this for now. Please re-open this if there is a need to re-open this. Thanks for the contributions and stay safe.

**Pull request closed without merging**
