### PR TITLE
Add support for sympy.sign in .printing.pycode

### PR DESCRIPTION
**Pull request by bjodah**
Python doesn't have a `math.sign` function, it does have a `copysign` function though, however, just wrapping copysign would not give the right answer for `sign(0)` (hence the use of the ternary operator).

### CODE REVIEW

**Comment by ylemkimon** [comment]
`math.copysign(1, S.NaN)` returns `-1.0` and `math.copysign(1, float('nan'))` returns `1.0`.

**Comment by bjodah** [comment]
Nice catch! (I'm surprised that copysign isn't returning NAN here). But isn't that a "bug" in `math.copysign`?

**Comment by ylemkimon** [comment]
It's probably because it just copies the sign bit and NaN has a sign bit.

**Comment by bjodah** [comment]
I tracked down the issue. The problem does not lie in `sympy`, but rather `mpmath`:
```
>>> import math
>>> from mpmath.libmp.libmpf import fnan
>>> from mpmath.libmp import to_float
>>> math.copysign(1.0, to_float(fnan))
-1.0
>>> math.copysign(1.0, float('nan'))
1.0
```
One possible work-around would be to define the method `__float__` in `sympy.core.numbers.NaN` to return `float('nan')`. But I think that is a separate issue.

**Comment by bjodah** [comment]
@ylemkimon since the `nan` issue is mpmaht related, I think this PR is as good as it gets in that respect. What do you think? (and do you have any other comments?)

**Review by ylemkimon — APPROVED** [review]
I meant a discrepancy between SymPy's `sign` returning NaN for NaN and Python's `copysign` returning +-1 for NaN, but it's an implementation issue, not a code printer should handle. LGTM 😄

**Pull request merged**
