### PR TITLE
[WIP] Add Rubi

### PR DESCRIPTION
**Pull request by certik**
TODO
- [ ] Add more stuff from Rubi:
  - [x] at least `cos`, `sinh` and `cosh` rules
  - [ ] hopefully some rational expressions like `sqrt(x)/(x+1)`
- [ ] Add pattern matching, so that one can pass a SymPy expression and it will determine if it matches any of the functions like `intsin12`, so that the interface is just like `integrate`
- [ ] Integrate this into `integrate` as an optional method (by default turned off for now), so that people can easily start playing with that and use it when it works
- [ ] Refactor the `is_zero()` into `sympy.utilities.randtest.test_numerically`, per the [comment](https://github.com/sympy/sympy/pull/8036#issuecomment-55971979).

### CODE REVIEW

**Comment by isuruf** [comment]
Anything I can do to help get this PR done?

**Comment by certik** [comment]
@isuruf you can work on the last 3 items in the TODO list. I think the most pressing is the

* Add pattern matching, so that one can pass a SymPy expression and it will determine if it matches any of the functions like intsin12, so that the interface is just like integrate

everything else can be done later I think.

**Comment by isuruf** [comment]
@certik, do you think we should do it using pattern matching or using the if else statement structure in Rubi 5?

**Comment by certik** [comment]
@isuruf here is the upper level routine: https://github.com/sympy/sympy/pull/8036/files#diff-0268646296029918a01c4126d7d89586R11, which is able to integrate the expression in the comment. Now we need to connect it to sympy, i.e. if you have a sympy expression, we need to extract the relevant parameters.

I would start by simply pattern matching. Hopefully that will work. It doesn't have to be perfect, just work in most cases, then we can improve upon that.

**Comment by isuruf** [comment]
I had a look and it seems SymPy's pattern matching is not powerful enough to be useful. One option would be to wait until Rubi 5 comes in which is supposed to be using if else constructs instead of pattern matching.

**Comment by asmeurer** [comment]
What is lacking? Did you also look at the system in sympy.rules?

**Comment by isuruf** [comment]
Following gives me None.

```
from sympy import *
a, b, c, d, x, n = symbols("a, b, c, d, x, n", cls=Wild)
y = symbols("y")
pattern = (a+b*sin(c+d*x))**n
term = (1 + 3 * sin(5 + 4 * y))** 10
term.matches(pattern)
```

**Comment by isuruf** [comment]
`pattern.matches(term)` works

**Comment by isuruf** [comment]
```Python
term = (3 * sin(5 + 4 * y))** 10
pattern = (a+b*sin(c+d*x))**n
pattern.matches(term)
```
gives, `{a_: 59049*sin(4*y + 5)**10, n_: 1, b_: 0}`

Is there a way for me to say that `a, b, c, d` cannot have free_symbols?

**Comment by asmeurer** [comment]
You can use the `exclude` parameter of Wild. I think to avoid any symbols you'd need to extract all free_symbols from the expression and exclude all of them.

**Comment by isuruf** [comment]
I tried that. It doesn't work.
```
from sympy import *
y = symbols("y")
a, b, c, d, x, n = symbols("a, b, c, d, x, n", cls=Wild, exclude=(y,))
pattern = (a+b*sin(c+d*y))**n
term = (3 * sin(5 + 4 * y))** 10
pattern.matches(term)
```

**Comment by asmeurer** [comment]
It isn't smart enough to know that a should be 0.

**Comment by isuruf** [comment]
I tried the following as well.
```Python
from sympy import *
y = symbols("y")
a, b, c, d, x, n = symbols("a, b, c, d, x, n", cls=Wild, exclude=(y,))
pattern = (b*sin(c+d*y))**n
term = (3 * sin(5 + 4 * y))** 10
pattern.matches(term)
```
Now the problem is that `term == 59049*sin(4*y + 5)**10` which is a different form than the pattern.

**Comment by ankibues** [comment]
Hi @certik  and @asmeurer  ! This is how I am trying to use the pattern matching to use the function defined in https://github.com/sympy/sympy/pull/8036/files#diff-2bc19e12c496825694e36430bcc2fcdb
Please let me know your views on it !

```
def integrate(expr):
    a,b,c,d,n= Wild('a'),Wild('b'), Wild('c'),Wild('d'),Wild('e'),Wild('f'),Wild('m'), Wild('n')     
    arg= ((a+b*sin(c+d*x))**n).matches(expr)                             # for integrand of form ((a+b*sin(c+d*x))**n
    arg1= arg.values()
    if all(isinstance(n,Number) for n in arg1):
       return intsin6(arg[a],arg[b],arg[c],arg[d],arg[n],x)
    
    arg= ((a+b*sin(e+f*x))**m)*(c+d*sin(e+f*x))**n)).matches(expr)       # for integrand of form ((c+sin(a+b*x))**m)*((c+d*sin(e+f*x)**n)
    arg2= arg.values()
    if all(isinstance(n,Number) for n in arg2):
       return intsin9(arg[a],arg[b],arg[c],arg[d],arg[e],arg[f],arg[m],arg[n],x)
```
Similarly, other rules can be added in this function. As for ```c*sin(a+b*x))**n``` types cases are concerned, where the integer gets evaluated, we can avoid solving them from matching algorithm for now.

Also, I would like to work on the points on the TO DO list in this PR, and want to complete and run the Rubi Integrator for atleast all these defined Trignometric functions. Kindly guide me through it.

**Comment by asmeurer** [comment]
@ankibues your isinstance(n, Number) can be loosened. You only need that the expressions don't depend on x, which you can do by seeing if `x` is in `n.free_symbols`. Better, if you do `Wild('a', exclude=[x])` (and so on), then the match won't even happen if they contain x. You should also check if the match is None for that case.

**Comment by clavoirr** [comment]
https://github.com/sympy/sympy/wiki/GSoc-2017-@-GAGAN-ARORA-:--Rule---Based-Integration

**Comment by czgdp1807** [comment]
@certik Can you please update on the status of this? Whether it should be continued or closed?

**Comment by certik** [comment]
I am going to close this one, as I do not have time to pursue this. The latest status of implementing Rubi and what to do is here:

https://github.com/symengine/symengine/issues/1597#issuecomment-521721092

**Pull request closed without merging**
