### PR TITLE
Use _sympify instead of sympify in replace()

### PR DESCRIPTION
**Pull request by asmeurer**
This fixes some major performance issues when calling replace with non-SymPy
types such as functions or classes. This was seen in particular, in diff
(issue #15416), but likely other places are affected as well. The problem is
that sympify() as a final attempt converts the input to a string and tries to
parse it. This of course fails, but it takes a lot of time, especially since
diff can be called many times recursively. String parsing is skipped entirely
with _sympify().

The downside to this of course is that string inputs to replace() will no
longer work. However, string inputs to library functions have always been
considered an antipattern (see
https://github.com/sympy/sympy/wiki/Idioms-and-Antipatterns#strings-as-input)
and unsupported behavior that could be removed at any time.

We might want to consider making sympify() more conservative in what sorts of
things it tries to parse as strings. Obviously a function will never parse
(the string form of a function is '<function blah at 0x11d729488>'), and
classes wouldn't unless they are doing something strange with metaclasses.
IMHO the string parsing fallback behavior of sympify shouldn't be there in the
first place, but removing it would likely be too much of a backward
incompatible change to make at this point.

More generally though, we should prefer _sympify in library code, *especially*
any code that accepts non-SymPy types such as functions.

#### References to other Issues or PRs

Probably fixes issue #15416 but I'd like confirmation from @moorepants before marking it as such.

#### Other comments

I'm not sure if this should be tested somehow. We do have our benchmarks, but they are in a separate repo and run separately from the test suite. 

#### Release Notes

- core
  - `replace` no longer accepts string inputs. This fixes some performance issues that occurred when calling `replace` with non-SymPy inputs such as Python functions.

### CODE REVIEW

**Comment by moorepants** [comment]
I'll run the benchmarks on monday when I get back to my office.

**Comment by moorepants** [comment]
I ran the benchmarks: http://www.moorepants.info/misc/sympy-asv/. Seems to be some improvements but didn't fix all regressions.

**Comment by asmeurer** [comment]
@moorepants if you can benchmark the 1.4 release branch vs. 1.3 some time in the next week that would help as well.

**Comment by moorepants** [comment]
I currently only have the system setup to benchmark all merge commits on master, which I manually run when I remember. It would take some tweaking to benchmark branches or PRs and produce other websites. I see how that would be useful, but I don't have much time at the moment.

**Comment by asmeurer** [comment]
Master would work too. There are almost no differences between the 1.4 branch and master right now.

**Pull request merged**
