### PR TITLE
[WIP] Fix #7259 - LambertW has no series expansion at x=0 (nan)

### LINKED ISSUE #7259: LambertW has no series expansion at x=0 (nan)
With sympy version 0.7.5:

```
>>> series(LambertW(x),x)
nan
```

This is probably due to the chosen representation of the derivative

```
>>> LambertW(x).diff(x)
LambertW(x)/(x*(LambertW(x) + 1))
```

which requires a 0/0 limiting form with numerator `LambertW(x)`, which requires the derivative at 0 which has a limiting form of 0/0 and so on...

One mathematical solution is to replace `x = LambertW(x)*exp(LambertW(x))` in the derivative `1/(LambertW(x) + 1)/exp(LambertW(x))` which may be safely evaluated at `x=0` where `W(0) = 0`.  Not sure if this type of thing is easy to do in the code though.

### PR DESCRIPTION
**Pull request by leosartaj**
I Have made the following changes:
- `fdiff` of `LambertW` now returns the derivative mentioned in issue #7259.
- `_eval_heurisch_derivative` method has been added in Function class. It checks if heurisch specific derivative exists and evaluates accordingly.
- `fdiff_heurisch` method (returns heurisch specific derivative) added in `LambertW` to be used by `_eval_heurisch_derivative`.
- `heurisch_diff` function added in heurisch. To be used when differentiating a function.
- Added tests in `test_series` for series expansion of `LambertW`.

### CODE REVIEW

**Comment by leosartaj** [comment]
Please review @smichr @asmeurer

**Comment by asmeurer** [comment]
What is the relationship between this pull request and https://github.com/sympy/sympy/pull/8350/? Should one closed in favor of the other?

**Comment by leosartaj** [comment]
That was an earlier attempt but it never got merged. I am still working on this approach.

**Comment by czgdp1807** [comment]
Closing this PR as the issue is fixed in current master and in favour of https://github.com/sympy/sympy/pull/17390,
```python
>>> from sympy import *
>>> x = symbols('x', real=True)
>>> series(LambertW(x),x)
x - x**2 + 3*x**3/2 - 8*x**4/3 + 125*x**5/24 + O(x**6)
>>> y = symbols('y')
>>> series(LambertW(y),y)
y - y**2 + 3*y**3/2 - 8*y**4/3 + 125*y**5/24 + O(y**6)
```
Thanks for the contributions.

**Pull request closed without merging**
