### PR TITLE
Implementation of columnspace of a matrix

### PR DESCRIPTION
**Pull request by sumith1896**
Better and more efficient implementation of columnspace as compared to the closed PR #8962. 
More cleaner commits.
Documentation of columnspace will be added once approved.

### CODE REVIEW

**Comment by Sumith1896** [comment]
@moorepants A columnspace implementation which is much more effcient than the one I previously suggested. Waiting for test results.
P.S. The old PR is closed

**Comment by vramana** [comment]
@Sumith1896  Just a small advice There is no need to close the PR if you think you have better implementation. Implement your new way in the same branch . Once you think you have finished, squash the commits and force push to the remote branch. This is sane(git) way of doing things.

**Comment by vramana** [comment]
I highly suggest you to take a look at this article https://help.github.com/articles/about-git-rebase/

**Comment by Sumith1896** [comment]
Thanks @vramana. I now feel that I could've rectified the old PR with this information. I'm praticising rebase on some repos and I must say that working now has become a lot easier.

**Comment by vramana** [comment]
@Sumith1896 Don't rebase too many times. It is not worth it. You can make as many commits as you want. Just before the PR is about to be merged you can squash those commits into a few commits with a good commit messages.

**Comment by Sumith1896** [comment]
Yeah, sure. I'll take care of that.

**Comment by moorepants** [comment]
@vramana Actually we don't recommend rebases and force pushes, especially for new comers. The problem with rebasing is that you are changing the history and if you've shared code publicly which others have cloned, rebasing will cause issues for them.

**Comment by Sumith1896** [comment]
@moorepants Your views on the PR

**Comment by Sumith1896** [comment]
The documentation error is fixed. Will have to wait for the Travis test results.

**Comment by vramana** [comment]
@moorepants I understand the problems with rebasing. I only suggested him rebasing because he left his original PR and created new one. I thought he should know about it.

**Comment by Sumith1896** [comment]
@moorepants Travis tests pass(except the pypy issue)

**Comment by Sumith1896** [comment]
@moorepants @asmeurer Does anything else needs to be updated? The PR is ready for merge as of now. Travis tests pass except the Pypy issue.

**Comment by Sumith1896** [comment]
@moorepants @asmeurer How do I re-run the build? I think it will pass the next time as other PRs have their build passing.

**Comment by Sumith1896** [comment]
The details show it has passed, but why is it showing here that the build failed?

**Comment by moorepants** [comment]
It seems to have passed. I'm not sure what the red failed at the bottom is. Looks like Travis has introduced a a new github integration.

**Comment by Sumith1896** [comment]
Any other work that I can do before it can be merged?

**Comment by moorepants** [comment]
One quick note. Your docstring is sparse. Ideally it would include an explanation of the parameters and what is returns plus at least one example. See other functions for examples.

**Comment by Sumith1896** [comment]
Turned out the function which I was comparing mine to also had sparse docstring. Updated both in two different commits.

**Comment by Sumith1896** [comment]
@moorepants Ready to merge.

**Comment by Sumith1896** [comment]
@moorepants ping

**Comment by moorepants** [comment]
Looks good. Thanks for the contribution.

**Pull request merged**
