### PR TITLE
Faster implementation of sample function in drv_types

### PR DESCRIPTION
**Pull request by Subhash-Saurabh**
#### Brief description of what is fixed or changed
Related to #13943
The above mentioned PR used linear search to find integer n where `CDF(n) >= u` .
This PR tries to implement a more optimized search so that sample method can work for larger value of lambda.

### CODE REVIEW

**Comment by Subhash-Saurabh** [comment]
@normalhuman Can you please take a look at this PR.

**Review by normalhuman — COMMENTED** [review]
I tried to sample `X = Poisson("X", 1000)` and every execution of `sample(X)` returned the same number, 1024.  Doesn't look right.

**Comment by Subhash-Saurabh** [comment]
@normalhuman I have made some changes and now it is not returning constant value. Can you please take a look and suggest if any other changes are required.

**Comment by Subhash-Saurabh** [comment]
@normalhuman Can you please review this PR. I am awaiting your reply.

**Comment by normalhuman** [comment]
This improves the current situation, at least while there is no clear road forward on sampling in general (issue #14261),

**Pull request merged**
