### PR TITLE
[Please review] factorials: extend ff and rf to polynomials of 1 variable.

### PR DESCRIPTION
**Pull request by postvakje**
implement ff and rf for polynomials as defined in Peter Paule, "Greatest
Factorial Factorization and Symbolic Summation", Journal of Symbolic
Computation, vol. 20, pp. 235-268, 1995.   Currently ff(p(x),2) returns
p(x)_(p(x)-1).  To be able to use the gff factors in gff_list(f) to
reconstitute f, ff(p(x),2) should be p(x)_p(x-1).  Current doctest in
gff_list works because the factors are all of order 1.  Added doctest to
gff_list to illustrate the case when the factors are higher order.  This
also addresses issue #8926.

### CODE REVIEW

**Comment by certik** [comment]
This looks good to me. I am sorry that nobody reviewed it so far.

**Comment by asmeurer** [comment]
I'm -1 to this. This changes the output of `rf` in a backwards incompatible way. We should revert this back to be compatible with the way it was before.

**Comment by postvakje** [comment]
This patch corrects the way ff and rf of a polynomial of order > 1 is evaluated as described in Paule's paper and addresses the issue of gff_list being incorrect in issue #8926. It is breaking some other part of the code?

**Comment by asmeurer** [comment]
It's a backwards incompatible change. Previously `rf(x**3, 2)` gave `x**3*(x**3 + 1)`. Now it gives `Poly(x**6 + 3*x**5 + 3*x**4 + x**3, x, domain='ZZ')`. These are not the same polynomial (as a side note: SymPy functions should not return instances of `Poly`). 

If an algorithm in the polys needs the behavior described in Paule's paper, a new function should be used, or an option added to rf.

**Comment by postvakje** [comment]
Paule's definition of `ff` is only needed to verify the result of `gff_list`, so reverting it back is fine except that the examples in the test and doctest for `gff_list` which use `ff` will now fail and need to be changed.

**Comment by asmeurer** [comment]
I opened https://github.com/sympy/sympy/issues/11105 so we don't forget to fix this.

**Comment by asmeurer** [comment]
How about the following: if the input is a SymPy expression, the old form is used, but if it is a `Poly`, the "polynomial" definition is used (and the return type is the respective type for each).

**Pull request merged**
