### PR TITLE
added boilerplate index method for FracField

### LINKED ISSUE #20501: Utility for getting generator index of FracField
FracField don't have any utility to get the index of the generator
```
R, x, y, z = ring('x y z', QQ)
R.index(x)
F, x, y, z = field('x y z', QQ)
F.index(x)
# AttributeError: 'FracField' object has no attribute 'index'
```
So a boilerplate is needed to get the index like `F.ring.index(x.numer)`

### PR DESCRIPTION
**Pull request by wsdookadr**
#### References to other Issues or PRs
Fixes #20501 

#### Brief description of what is fixed or changed

PolyRing has an index method but FracField does not. This PR adds an index method to the FracField class.

#### Release Notes

* polys
  * added boilerplate index method for FracField

### CODE REVIEW

**Comment by wsdookadr** [comment]
@sylee957 please help with a review of this pull request

**Comment by oscarbenjamin** [comment]
It's more efficient to do:
```
In [31]: x, y = symbols('x, y')                                                                                                   

In [32]: K, xf, yf = field([x, y], QQ)                                                                                            

In [33]: K.gens.index(xf)                                                                                                         
Out[33]: 0

In [34]: K.symbols.index(x)                                                                                                       
Out[34]: 0
```
The `index` method of a ring only works for `xf` so we can do the same for field.

**Comment by wsdookadr** [comment]
> The `index` method of a ring only works for `xf` so we can do the same for field.

The `index` method for ring currently [works for `int` and `str` too](https://github.com/sympy/sympy/blob/78891c0/sympy/polys/rings.py#L397).

**Comment by oscarbenjamin** [comment]
What does it mean to ask for the index of an int?

I don't think it does work for str:
```python
In [7]: K, xf, yf = ring([x, y], QQ)                                                                                              

In [8]: K.index('x')                                                                                                              
---------------------------------------------------------------------------
ValueError 
```
I'm also not sure that there is any particular value in making it work for str.

**Comment by oscarbenjamin** [comment]
> What changes should be made to the current method so it can pass review?

It's not the changes are needed. I'm just trying to understand what this index method does :)

**Comment by wsdookadr** [comment]
> I'm also not sure that there is any particular value in making it work for str.

I just pushed a commit where the only allowed type is `FracElement`. Anything else will raise an exception.

**Pull request merged**
