### PR TITLE
WIP - Pytest doctest fix

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### Brief description of what is fixed or changed

(Still working on this and will tidy up later. I'm just about to go away for a bit and wanted to put this up for feedback on the general idea.)

Makes it possible to run Sympy's doctests using pytest and the doctestplus plugin:
[https://github.com/astropy/pytest-doctestplus](https://github.com/astropy/pytest-doctestplus)

~~Well, *almost* makes it possible. Right now `pytest --doctest-modules` gives 20 collection errors and 450 test fails. With this patch I'm down to 0 collection errors and about 8 test fails (all due to missing dependencies).~~

EDIT: This patch now successfully runs all doctests with no fails.

In general to use pytest with this patch you would do:
```console
$ pip install pytest pytest-doctestplus
$ pytest --doctest-plus --doctest-rst
```
However in getting this to work I have submitted some PRs to doctestplus that have been accepted but aren't released so install doctestplus with:
```console
$ git clone https://github.com/astropy/pytest-doctestplus.git
$ pip install -e pytest-doctestplus
```

To get this to work a few doctests were slightly modified. Also The `_doctest` function in `runtests.py` was rearranged so that the list of blacklisted modules could be used also under pytest. Some pytest and doctestplus configuration options are added to `conftest.py`.

I've added a hack to `conftest.py` that changes `sys.__display_hook__`. The stdlib doctest module resets `display_hook` before each doctest example is executed meaning that Sympy's pretty printing is disabled:
[https://github.com/python/cpython/blob/v3.7.2/Lib/doctest.py#L1470](https://github.com/python/cpython/blob/v3.7.2/Lib/doctest.py#L1470)
I've replaced `sys.__display_hook__` instead (monkey-patching the monkey-patch prevention). There are probably better ways to do this but it works for now...

#### Other comments

The standard pytest doctest plugin is unsuitable for Sympy. In particular it doesn't support inexact float comparison or running tests in rst files. The Astropy project wrote a pytest plugin to improve on this and then released it as a separate project. The comments in the code indicated that some parts were actually extracted from Sympy's doctest runner. While working on this I have submitted a few PRs to doctestplus.

~~Currently there are around 8 fails due to running doctests with missing dependencies. I sent a PR to doctestplus to add a decorator that could be used like sympy's `@doctest_depends_on` but the main doctestplus author isn't so keen on that idea so I'm discussing what would be a better approach for conditional skipping of doctests here: [https://github.com/astropy/pytest-doctestplus/pull/41](https://github.com/astropy/pytest-doctestplus/pull/41)~~

EDIT: I've used the doctestplus directives to skip doctests due to missing Python libraries. What is still missing is that doctestplus doesn't have a way to skip doctests based on missing command-line programs as is done by Sympy's `doctest_depends_on` decorator. This could lead to fails if you have certain Python libraries but not the needed command line utilities to run some tests.

#### Release Notes

* utilities
    * Make doctests runnable under pytest with doctestplus

### CODE REVIEW

**Comment by bjodah** [comment]
This looks really good! Do you think we should we wait for a new upstream release of doctestplus before merging?

**Comment by oscarbenjamin** [comment]
I'm going away for a bit but I'll just respond quickly before I do. I will
tidy this up when I get back.

Without this patch running doctests under pytest doesn't work (450 fails
plus 20 collection errors). Since it's not currently possible to run the
doctests with pytest at all I don't see any need to wait for doctestplus.

On 13 Jan 2019 09:43, "Björn Dahlgren" <notifications@github.com> wrote:

This looks really good! Do you think we should we wait for a new upstream
release of doctestplus before merging?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sympy/sympy/pull/15768#issuecomment-453815494>, or mute
the thread

**Comment by oscarbenjamin** [comment]
Thanks for reviewing!

**Comment by asmeurer** [comment]
Our doctest runner also runs each doctest as an independent module, requiring all names to be imported in the doctest. Does the pytest runner support this?

**Comment by oscarbenjamin** [comment]
Note that this patch uses the pytest-doctestplus runner rather than the doctest runner that comes with pytest. Neither of these two doctest plugins supports running the tests as an independent module but I don't think it would be hard to add that feature to doctestplus.

I'll open a separate issue fot that.

**Pull request merged**
