### PR TITLE
Solves issue #18891

### LINKED ISSUE #18891: Improper docstring in codegen.array_utils.recognize_matrix_expression
Docstring of code example under heading 
*Recognize some more complex traces* 
is not proper here: https://docs.sympy.org/latest/modules/codegen.html#sympy.codegen.array_utils.recognize_matrix_expression
resulting in a broken code formatting.

### PR DESCRIPTION
**Pull request by Arpan612**
#### References to other Issues or PRs

Fixes #18891 

#### Brief description of what is fixed or changed
Space is given

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by mohitacecode** [comment]
I think `NO ENTRY` in release note will do fine here.

**Comment by mohitacecode** [comment]
you have a trailing white space at line 1292.

**Comment by Arpan612** [comment]
@mohitacecode I didn't get you. I just added the space as required. Can you tell me why is Travis CI built failing?

**Comment by mohitacecode** [comment]
It means that you have left some spaces at line no. 1292. (Means the curson at that point should be at starting of that line but it isn't at the moment. You can see it just by clicking at that line).

**Comment by mohitacecode** [comment]
Also I think this does not solves the issue you should write something like
`Related to #issue_no`

**Comment by mohitacecode** [comment]
It will be better to remove the previous commit and open a new pr for the migrations of test.

**Comment by Arpan612** [comment]
@mohitacecode Is it fine now or some other changes are required?

**Comment by mohitacecode** [comment]
IMO It look fine!

**Comment by Sc0rpi0n101** [comment]
You can build the docs locally to see if they render correctly now. 
Refer to https://docs.sympy.org/latest/documentation-style-guide.html#build-the-documentation for how to do that.

**Comment by Arpan612** [comment]
@Sc0rpi0n101 I have done that, it seems fine. Thanks.

**Comment by Sc0rpi0n101** [comment]
Can you squash your commits into one with a useful description like `fixed the documentation/docstring for...`?

**Comment by Arpan612** [comment]
@sylee957 Could you please review this PR and merge it?

**Comment by oscarbenjamin** [comment]
In future can you try to use better names for the PR title and better commit messages. "Solve issue #18891" does not immediately tell me anything about what this does and "Space is given" is not a good description either. Following angularjs commit message guidelines something like `"doc(codegen): fix docstring formatting in recognize_matrix_expression"` is a better commit message because it tells you:

- what part of the codebase this is changing
- what kind of change the commit is
- the reason for making the change

Similar principles apply to the title that you give to a PR and the description. These don't have to be long but they should give some context.

**Pull request merged**
