### PR TITLE
Defining ImageSet union

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

Closes #17079 
Closes #12011 

#### Brief description of what is fixed or changed

Adds ImageSet union for linear ImageSets.

#### Release Notes

* sets
    * Unions of linear ImageSets will evaluate when possible.

### CODE REVIEW

**Comment by gschintgen** [comment]
Just a quick observation: if the linear maps involve complex numbers, execution will still pass on to `_unify_img_linear` where no particular provisions are made to handle such a case. E.g. it hits `lcm` and also the modulo operator `%` (which is currently undefined for complexes).

So even with this PR, we'd still get:
```
In [1]: solveset(sinh(x), x)
Out[1]: {2⋅n⋅ⅈ⋅π | n ∊ ℤ} ∪ {ⅈ⋅(2⋅n⋅π + π) | n ∊ ℤ}
```
That being said I don't want to belittle what is currently achieved by this PR! It's highly useful for trig equations.

IMO it should even be feasible to generalize the current algorithm to arbitrary linear complex maps (first check if both lines in the complex plane coincide, then apply an adapted version of the proposed algorithm.)

**Comment by oscarbenjamin** [comment]
Feel free to work on this. I just rebased it from #17079 by @jmig5776, resolved conflicts and fixed up a few tests. I haven't since found time to think about improving it.

On the other hand if you think this is good to merge and improve later then go ahead.

**Comment by gschintgen** [comment]
Ok, I'll think about it. (To be honest I'm a bit bothered by the somewhat "heuristic" approach of the main algorithm. But computing imageset unions is a much needed improvement.)

**Comment by oscarbenjamin** [comment]
I haven't checked it completely but if I understand correctly this is all based on pairwise unions so it won't work for unifying mod 3:
```julia
In [1]: ImageSet(Lambda(n, 2*n), Integers) | ImageSet(Lambda(n, 2*n+1), Integers)                                                 
Out[1]: ℤ

In [2]: ImageSet(Lambda(n, 3*n), Integers) | ImageSet(Lambda(n, 3*n+1), Integers) | ImageSet(Lambda(n, 3*n+2), Integers)          
Out[2]: {3⋅n | n ∊ ℤ} ∪ {3⋅n + 1 | n ∊ ℤ} ∪ {3⋅n + 2 | n ∊ ℤ}
```
Also I'm not sure that this belongs in auto-evaluation. Maybe there should be a special `simplify_union_of_imagesets` function that is specifically used by `solveset` since that is where these come from.

**Comment by gschintgen** [comment]
Yes, pairwise simplification has unfortunate limitations, but since these sets often do come in pairs it's useful nonetheless. I'm not sure I know enough about Sympy's internals to rework the PR to such an extent. (Though having a separate simplifying function could be simpler than the whole dispatching...)

Anyway, for future reference:
- The `base` set in this PR's code must inherently be `S.Integers`, else the results will be quite wrong (e.g. `2*n+5` and `2*n` both over the `Naturals` returns `S.Naturals` instead of unevaluated.)
- If I'm not mistaken, in pairwise "unification" of linear map-imagesets there are only two cases possible that result in a new linear map-imageset: either one imageset is a subset of the other or their union is composed of a strictly alternating sequence of elements of set1 and set2. A simpler algorithm should be possible.

**Comment by jmig5776** [comment]
I agree with your view points here.

**Comment by oscarbenjamin** [comment]
Closing in favour of #18489

**Pull request closed without merging**
