### PR TITLE
Add the Moyal distribution

### PR DESCRIPTION
**Pull request by raoulb**
Add an implementation of the Moyal distribution.

### CODE REVIEW

**Comment by ethankward** [comment]
If the mean and variance cannot currently be computed then they should be left out for now (the stats module needs more work to efficiently compute moments of continuous distributions).

**Comment by raoulb** [comment]
Hmm, ok, then this is probably finished now.

**Comment by asmeurer** [comment]
I think there are ways to add statistical data explicitly if the integrals cannot be computed. @Upabjojr @akash9712

**Comment by akash9712** [comment]
You can add the expectation for random variables explicitly by overriding `expectation`, as all continuous random variables inherit from `SingleContinuousDistribution`.

**Comment by raoulb** [comment]
Overriding `expectation` might help, but then I'd need to special case on the expression `expr` term?
What is the best sympy way to check if this is `x` or `x**2` etc?

**Comment by Upabjojr** [comment]
> What is the best/correct way to add further knowledge about the Moyal distribution to sympy?
For example mean and variance which (as of now) can not be computed by the generic integral approach but for which we know the symbolic solutions.

The only supported trick to keep pre-computed quantities is to add `_cdf`, for the cumulative distribution function. There is no support for other types of pre-computed statistical properties.

**Comment by czgdp1807** [comment]
Closing in favour of https://github.com/sympy/sympy/pull/18446

**Pull request closed without merging**
