### PR TITLE
Make dynamicsymbols real by deafult

### PR DESCRIPTION
**Pull request by sidhu1012**
#### Brief description of what is fixed or changed
dynamicsymbols have `real = True` unless `commutative` assumption is used.

#### Release Notes

* physics.vector
    * Make dynamicsymbols real by default unless commutative property is used.

### CODE REVIEW

**Comment by sidhu1012** [comment]
@moorepants Please review.

**Comment by sidhu1012** [comment]
@moorepants Please review this PR.

**Comment by moorepants** [comment]
I'm -1 to this change. Sorry if that wasn't clear in the other PR. I think we should simply document this as a "gotcha".

**Comment by sidhu1012** [comment]
> I'm -1 to this change. Sorry if that wasn't clear in the other PR. I think we should simply document this as a "gotcha".

@moorepants I was thinking that `dynamicsymbols` should be real by default as `real=False` doesn't make sense for dynamicsymbols and we should add gotchas for other symbols used in physics.

Like:

``` 

l, g = Symbols('l g', real = True)
x = dynamicsymbols ('x') # real by default

```

**Comment by moorepants** [comment]
I don't think we should add any assumptions automatically at this point, as it is backwards incompatible. Adding a gotcha section in the documentation explaining that it may be useful to add certain assumptions to symbols when doing mechanics (and why) is a good thing to add.

**Comment by sidhu1012** [comment]
> I don't think we should add any assumptions automatically at this point, as it is backwards incompatible. Adding a gotcha section in the documentation explaining that it may be useful to add certain assumptions to symbols when doing mechanics (and why) is a good thing to add.

@moorepants Where should `gotchas` go?

**Comment by moorepants** [comment]
This page is probably best: https://docs.sympy.org/latest/modules/physics/vector/advanced.html

**Comment by sidhu1012** [comment]
> This page is probably best: https://docs.sympy.org/latest/modules/physics/vector/advanced.html

I'll add that.

**Comment by sidhu1012** [comment]
@moorepants I don't think adding `real=True` by default would break backward compatibility as dynamicsymbols aren't supposed to be used in any way that breaks compatibility.

**Comment by moorepants** [comment]
All code in the wild is written with no assumptions set on any of the symbols. If we then introduce assumptions, then all existing code is affected. It may not cause issues for most cases, but it could for some.

**Comment by sidhu1012** [comment]
@moorepants Currently if we have a `dynamicsymbol` with `real=False` then the result in some cases the result may be incorrect, I think we should make `dynamicsymbols` real by default for the correctness of result irrespective of backwards incompatibility in this case or at least we should give a warning to `use dynamicsymbols with real=True, it would be made default in subsequent release`, something like that.

```
>>> g = dynamicsymbol('g', real=True)  #default behavior
>>> diff(Abs(g), t)
sign(g(t))*Derivative(g(t), t)

>>> f2 = dynamicsymbol('f2', real=False)
>>> diff(Abs(f1), t)
(re(f2(t))*Derivative(re(f2(t)), t) + im(f2(t))*Derivative(im(f2(t)), t))*sign(f2(t))/f2(t)   #Incorrect for dynamicsymbols
```

**Comment by sidhu1012** [comment]
@moorepants What's your view.

**Pull request closed without merging**
