### PR TITLE
latex print with parenthesis

### LINKED ISSUE #14041: Latex output of vector error
The latex output drops the B.x parenthesis squared in a vector expression i.e. L*(phi' + theta')**2*B.x. 
See code,
```python
import sympy as sp
import sympy.physics.mechanics as me


N_frame = me.ReferenceFrame('N')
A_frame = me.ReferenceFrame('A')
B_frame = me.ReferenceFrame('B')

R_length = sp.symbols('R')
L_length = sp.symbols('L')

theta, phi  = me.dynamicsymbols('theta, phi')
thetad, phid  = me.dynamicsymbols('theta, phi', 1)
t = sp.Symbol('t')

A_frame.orient(N_frame, 'Axis', (theta, N_frame.z))
B_frame.orient(A_frame, 'Axis', (phi, A_frame.z))

O_point = me.Point('O')
O_point.set_vel(N_frame, 0)

O_point = me.Point('O')
O_point.set_vel(N_frame, 0)

Q_point = O_point.locatenew('A', R_length*A_frame.x)
P_point = Q_point.locatenew('B', L_length*B_frame.x)

r = P_point.pos_from(O_point)
print(r)
r_dot = r.diff(t,N_frame).simplify()
print(r_dot)
print(sp.latex(r_dot))
r_ddot = r_dot.diff(t,N_frame).simplify()

# These two should be the same, r_ddot is correct:
print(r_ddot)
print(sp.latex(r_ddot))
```

### PR DESCRIPTION
**Pull request by vishalg2235**
Fixes #14041 .

If `term` is of class `Pow` then, `_needs_mul_brackets` returns False and no parenthesis were added. So I split `term` in base and power, then added latex form of base(which came with parenthesis) with latex form of power separately.

@moorepants please review!

### CODE REVIEW

**Comment by asmeurer** [comment]
There are several test failures.

**Comment by asmeurer** [comment]
Please add tests for whatever was fixed here.

**Comment by vishalg2235** [comment]
@asmeurer in my PC [this](https://github.com/sympy/sympy/pull/14091/files#diff-6f54e989a699924826fcb002496bfad0R1687) test is passed!
```
>>> test("latex")
======================== test process starts =========================
executable:         /usr/bin/python  (2.7.12-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              None
random seed:        86086409
hash randomization: on (PYTHONHASHSEED=906531821)

sympy/printing/tests/test_latex.py[115] ..............................
......................................................................
...............                                                   [OK]

============ tests finished: 115 passed, in 6.31 seconds =============
True
```
And please review.

**Comment by vishalg2235** [comment]
I don't know why this error is coming. In my pc it's `True`. Please review @gxyd @jksuom @Upabjojr

**Comment by jksuom** [comment]
I could not reproduce the error. The raw string seems to be equal to the string printed by `latex(r_ddot)` in my system. However, I would try to rewrite the string in non-raw form for the test.

**Comment by vishalg2235** [comment]
Okay @jksuom ! Will it make any change if I write it in `r'...'` form?

**Comment by jksuom** [comment]
I really don't know. But the only difference between the output of `latex` and the string on the rhs seems to be that the latter is raw. So I would test if making it look exactly the same as the (non-raw) latex output would help. I cannot think of anything else for now.

**Comment by vishalg2235** [comment]
Ping @asmeurer @jksuom @certik !

**Comment by smichr** [comment]
If this passes, it is not quite ready to go.

```
>>> latex((phid + thetad)**2*A_frame.x)
'\\dot{\\phi} + \\dot{\\theta}^{2}\\mathbf{\\hat{a}_x}'
```
should be 
```
'\\left(\\dot{\\phi} + \\dot{\\theta}\\right)^{2}\\mathbf{\\hat{a}_x}'
```

**Comment by smichr** [comment]
See, perhaps, logic after "#fixes issue #12886, adds parentheses before superscripts raised to powers" in latex.py where it is determined whether the base needs parentheses.

**Comment by smichr** [comment]
All latex tests pass with only this mod to master:
```diff
diff --git a/sympy/printing/latex.py b/sympy/printing/latex.py
index 5659b6a..1580af1 100644
--- a/sympy/printing/latex.py
+++ b/sympy/printing/latex.py
@@ -532,8 +532,9 @@ def _print_Pow(self, expr):
                         return tex[1:].strip()
                 tex = r"%s^{%s}"
                 #fixes issue #12886, adds parentheses before superscripts raised to powers
+                rbase = self._print(expr.base)
                 base = self.parenthesize(expr.base, PRECEDENCE['Pow'])
-                if '^' in base and expr.base.is_Symbol or not expr.base.is_Symbol:
+                if '^' in base and expr.base.is_Symbol or self._needs_mul_brackets(expr.base) and base == rbase:
                     base = r"\left(%s\right)" % base
                 exp = self._print(expr.exp)

diff --git a/sympy/printing/tests/test_latex.py b/sympy/printing/tests/test_latex.py
index e44757c..3595504 100644
--- a/sympy/printing/tests/test_latex.py
+++ b/sympy/printing/tests/test_latex.py
@@ -1759,3 +1759,16 @@ def test_WedgeProduct_printing():
     from sympy.diffgeom import WedgeProduct
     wp = WedgeProduct(R2.dx, R2.dy)
     assert latex(wp) == r"\mathrm{d}x \wedge \mathrm{d}y"
+
+
+def test_issue_14041():
+    import sympy.physics.mechanics as me
+
+    A_frame = me.ReferenceFrame('A')
+    thetad, phid  = me.dynamicsymbols('theta, phi', 1)
+    L = Symbol('L')
+
+    assert latex(L*(phid + thetad)**2*A_frame.x) == \
+        r"L \left(\dot{\phi} + \dot{\theta}\right)^{2}\mathbf{\hat{a}_x}"
+    assert latex((phid + thetad)**2*A_frame.x) == \
+        r"\left(\dot{\phi} + \dot{\theta}\right)^{2}\mathbf{\hat{a}_x}"
```

So it looks like there is a problem with `self.parenthesize(expr.base, PRECEDENCE['Pow'])` not putting parentheses around the base of `(phid + thetad)**2`, hence `rbase == base` and the parentheses are only added in that `if-block`.

**Comment by jksuom** [comment]
> it looks like there is a problem with self.parenthesize(expr.base, PRECEDENCE['Pow']) not putting parentheses around the base of (phid + thetad)**2,

It seems that `self.parenthesize`, in this case, is the special one in [`physics.vector.printing`](https://github.com/sympy/sympy/blob/master/sympy/physics/vector/printing.py#L155).

**Pull request closed without merging**
