### PR TITLE
make dsolve work with dynamicsymbols

### LINKED ISSUE #12044: dsolve doesn't work with dynamicsymbols
Reported from the mailing list. First, if you use dynamicssymbols with dsolve, it fails:

```

    from sympy import *;
    init_printing()
    
    Ex,Ey,Ez,Bx,By,Bz,c,m0,t,u,we,wb,q=symbols('E_x E_y E_z B_x B_y B_z c m_0 t u omega_E omega_B q')
    tau=dynamicsymbols('tau')
    
    u0=Function('u^0')(tau) 
    u1=Function('u^1')(tau)
    u2=Function('u^2')(tau)
    u3=Function('u^3')(tau)
    
    u=Matrix([u0,u1,u2,u3])
    Emat=Matrix([[0,Ex/c,Ey/c,Ez/c],[Ex/c,0,Bz,-By],[Ey/c,-Bz,0,Bx],[Ez/c,By,-Bx,0]])
    RHS=q/m0*Emat*u
    
    odesys=[Eq(u0.diff(),RHS[0]),Eq(u1.diff(),RHS[1]),Eq(u2.diff(),RHS[2]),Eq(u3.diff(),RHS[3])]
    odesys
    dsolve(odesys,[u0, u1, u2, u3])
```

This fails with

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-44-bf3106e3938d> in <module>()
----> 1 dsolve(odesys,[u0,u1,u2,u3])

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/ode.py in dsolve(eq, func, hint, simplify, ics, xi, eta, x0, n, **kwargs)
    582     """
    583     if iterable(eq):
--> 584         match = classify_sysode(eq, func)
    585         eq = match['eq']
    586         order = match['order']

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/ode.py in classify_sysode(eq, funcs, **kwargs)
   1381                     max_order = order_
   1382                     eq_no = i
-> 1383             if eq_no in func_dict:
   1384                 list_func = []
   1385                 list_func.append(func_dict[eq_no])

UnboundLocalError: local variable 'eq_no' referenced before assignment

```

If you use a normal Symbol, `dsolve` hangs and eventually returns `None`.

### PR DESCRIPTION
**Pull request by priyank-p0**
Fixes  #12044

### CODE REVIEW

**Comment by pspbot7** [comment]
@asmeurer can you review it?

**Comment by pspbot7** [comment]
@asmeurer can you take a look

**Comment by gxyd** [comment]
Thanks for your contribution. Can you please add test cases for the made changes?
See this https://github.com/sympy/sympy/wiki/Writing-test-cases-in-SymPy for guidelines on how to write test cases.

**Comment by czgdp1807** [comment]
The associated issue has been closed and that prompts to close this PR.
Refer, https://github.com/sympy/sympy/issues/12044#issuecomment-471189245

**Pull request closed without merging**
