### PR TITLE
[GSoC] [WIP] Added nyquist plot to control plots.

### PR DESCRIPTION
**Pull request by abhiphile**
This release introduces the `nyquist_plot` function to the control module, providing users with the ability to generate Nyquist plots for Single-Input Single-Output (SISO) Linear Time-Invariant (LTI) systems. It plots the complex values of a system's frequency response as a function of frequency, showing how the output of the system changes in magnitude and phase as the frequency varies.

#### Release Notes

* physics.control
  * Added Nyquist plot to control.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Who reviews control stuff these days? Is it @faze-geek ?

**Comment by faze-geek** [comment]
> Who reviews control stuff these days? Is it @faze-geek ?

Hi, I do review stuff when I get time. I did have a look at PRs where @abhiphile tagged me this summer.

**Comment by abhiphile** [comment]
Control PR are currently reviewed by @Sc0rpi0n101.

**Comment by Sc0rpi0n101** [comment]
> Who reviews control stuff these days? Is it @faze-geek ?

Can't say I review all the control stuff, but I do review the GSoC contributions.

**Comment by oscarbenjamin** [comment]
Okay, well this PR has been around for a month without review which is why I highlighted it. I'm not going to review it but it looked as if it had been forgotten by anyone who might review it.

We either need it to be reviewed or if no one can do that then it should be closed.

**Comment by Sc0rpi0n101** [comment]
Yes, we decided to prioritize working on some of the other changes before the plots, so this is still in draft mode. Abhishek is currently working on the plots and will finish it this coming week. I will review it.

**Pull request closed without merging**
