### PR TITLE
maint(ci): drop testing for Python 3.6

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

#21884 describes adopting NEP 29 which would mean dropping support for Python 3.6 now.

#### Brief description of what is fixed or changed

Drop testing in CI for Python 3.6 and PyPy 3.6

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Some other places in the codebase and release notes to be updated if 3.6 is dropped...

**Comment by oscarbenjamin** [comment]
I'm not sure what's going on with this PR. It removes the Python 3.6 jobs from CI but GitHub says "Required statuses must pass before merging" and shows that the 3.6 jobs are required even though they won't run. Maybe it's just that this has to be merged without CI send off...

**Comment by oscargus** [comment]
Ah, you made it work! Great! With #22383 this should be solved.

**Comment by oscargus** [comment]
https://stackoverflow.com/questions/60776412/github-actions-is-there-a-way-to-make-it-mandatory-for-pull-request-to-merge

Is it only @asmeurer that have access to the settings?

**Pull request closed without merging**
