### PR TITLE
Remove Support for Python 2.6 and 3.2

### LINKED ISSUE #10463: Dropping Python 2.6 and 3.2 support
Once SymPy 1.0 is out, we should drop Python 2.6 and 3.2 support. Python 2.6 reached its end-of-life in 2013 and 3.2 will reach it on February 20 of this year (which will likely be before 1.0 goes out at the rate we are going). See https://docs.python.org/devguide/#status-of-python-branches. I don't think we should support Python versions that have reached end-of-life. 

Additionally, with https://github.com/sympy/sympy/pull/10084, we now support 7 Python versions (including PyPy), resulting in a total of 44 builds on Travis. This is too much. Travis only runs 10 builds at a time for all of SymPy, meaning every push to every pull request has 44 builds and only 10 of those, globally, can run at once. If we drop these two Python versions we can remove 9 of those builds. 

Finally, this will open up a lot of syntactic features in the language that we've heretofore been unable to use. See https://docs.python.org/dev/whatsnew/2.7.html for a full list, but the main ones are set and dictionary comprehensions, set literals, and unicode literals (no more `u()`). 

Please **DO NOT DO ANYTHING** on this issue until after SymPy 1.0 is released.

### PR DESCRIPTION
**Pull request by AnishShah**
Fixes #10463

### CODE REVIEW

**Comment by AnishShah** [comment]
@asmeurer lots of changes for dict & set comprehensions.

**Comment by asmeurer** [comment]
Everything looks good so far.

**Comment by asmeurer** [comment]
What else is left? If you don't want to fix the release script can you add a TODO note to the top of the release README?

**Comment by AnishShah** [comment]
I might be missing some set & dict comprehensions.
I am not sure what & where is the release script.

**Comment by asmeurer** [comment]
You also need to remove the `u()` function and replace it with unicode literals.

**Comment by asmeurer** [comment]
The release script is in the release directory. If you do decide to do any work on it, you should wait until the 1.0 branch is merged (https://github.com/sympy/sympy/pull/10632), as there are some changes there. Basically, we need a newer VM, which has Python 3.3 or newer. There are also things to workaround the lack of apt packages for Python 3 in the repos for the VM we had (see the `apt_prepare` function). In all it's probably not a difficult fix, but it would need to be tested (all the info is there in the README if you want to give it a go, otherwise just add a TODO so I remember that it needs to be done when we do the next release).

**Comment by asmeurer** [comment]
Can you make the TODO a little more specific?

**Comment by AnishShah** [comment]
I will try to work on release script. I might be able to do it :+1:

**Comment by AnishShah** [comment]
@asmeurer I'm having some problem with vagrant & VM. For now, updating the README. I will try to update the script in a separate PR.

**Comment by AnishShah** [comment]
@asmeurer The tests are passing for this. Is there anything else remaining to remove support for Python 2.6 & 3.2?

**Comment by asmeurer** [comment]
That's fine. I can't think of anything else. If you feel this is everything then I'm +1 to merge.

**Comment by AnishShah** [comment]
@asmeurer I too can't think of anything. You can merge this.

**Pull request merged**
