### PR TITLE
parse_latex support \lg

### PR DESCRIPTION
**Pull request by eagleoflqj**
#### Brief description of what is fixed or changed

Simply add \lg.
#### Release Notes

* parsing
  * Latex parser supports \lg as base 10 log defined in ISO 80000-2:2019
  * BREAKING: \log is parsed as base E to be consistent with printer default

### CODE REVIEW

**Comment by asmeurer** [comment]
Doesn't lg usually mean the base 2 logarithm?

**Comment by eagleoflqj** [comment]
There seems to be an ISO standard https://en.m.wiktionary.org/wiki/lg#Usage_notes but non-

**Comment by eagleoflqj** [comment]
I also find this confusing

https://github.com/sympy/sympy/blob/6a04cdb14427489fe49974f33a84001a299d3688/sympy/parsing/latex/_parse_latex_antlr.py#L432-L433

as our latex printer uses `log` as base E

**Comment by asmeurer** [comment]
`log` can mean either base-10 or base-e depending on the context. We should probably default to e since SymPy does. I've honestly never seen anyone actually use `lg`.

**Comment by eagleoflqj** [comment]
I think we can provide some config like `log_base` and `lg_base` to `parse_latex`.

**Comment by asmeurer** [comment]
Ideally we'd be using a parser that is way more user customizable an runtime extensible than the current one, to the point that having specific options like that would be unnecessary. 

For instance, could we have a parser where the flag can be something along the lines of `parse_latex(funcs={r'\lg': lambda x: log(x, 2)})`, where `funcs` is a mapping that lets you define or redefine any latex name.

**Comment by eagleoflqj** [comment]
> parse_latex(funcs={r'\lg': lambda x: log(x, 2)})

If the purpose is restricted to "for **FUNCTION** patterns that are already defined in LaTeX.g4, use a mapping to control the parser", then I believe it's doable.

**Comment by asmeurer** [comment]
My point is just that we shouldn't lock ourselves into any public customization APIs for parse_latex if we are likely to switch to another parser in the future which would have much more general customizability.

**Comment by eagleoflqj** [comment]
If a new parser can't handle simple configuration, I doubt whether it's worth to switch.
I think ANTLR is good enough, as it is easy to use. It has a simple DSL and the API is not confusing. I didn't read any its documentation to be able to work on it.

**Comment by oscargus** [comment]
I think that the change is OK, but that the release note probably can be expanded to clarify what the different options are, i.e., which "log"-command is using what base.

Does this support providing a base?

**Comment by eagleoflqj** [comment]
> Can the ANTLR parser be extended at runtime?

I don't think so.
What I understand the biggest problem of our latex parser is it doesn't have a way to handle ambiguity like `a(b+c)`. Maybe there's a way to fix it in without changing the parser, but a new candidate should be able to solve that in a more elegant way.

**Pull request merged**
