### PR TITLE
Use dotprodsimp by default in rref

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

This will fix a number of issues. I can fill in the numbers later...

#### Brief description of what is fixed or changed

Use dotprodsimp by default in rref. Remove dotprodsimp parameter from a number of functions where it isn't needed any more as a result.

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
@sylee957 @Pristine-Cat this is an example of what I mean for how we can remove the dotprodsimp parameter. This removes it from rref by making dotprodsimp the default based on the simplify parameter.

I don't know why the simplify parameter has default False given that it simplifies with that default...

**Comment by Pristine-Cat** [comment]
> @sylee957 @Pristine-Cat this is an example of what I mean for how we can remove the dotprodsimp parameter. This removes it from rref by making dotprodsimp the default based on the simplify parameter.
> 
> I don't know why the simplify parameter has default False given that it simplifies with that default...

This is what I mean by the use of `simplify` being inconsistent or unapplicable to dotprodsimp usage. In this case if the simplify parameter previously was anything other than `FunctionType` (be it False, True, None, whatever) then the standard `simplify` function was used. However this function is not used to simplify the matrix as it is being `rref`d but rather for zero-testing in `_find_reasonable_pivot` only, so does not contribute to controlling blowup during the actual `rref` operations, and is not a good flag for disabling dotprodsimp in the three separate places in `_row_reduce_list` where it is used.

In this case if you really want to go the default way then just enabling dotprodsimp regardless of the `simplify` argument would be the way to go.

**Comment by oscarbenjamin** [comment]
> This is what I mean by the use of `simplify` being inconsistent

It is messy. Going through it though I think that the dotprodsimp parameter makes it worse so we should fix that before next release.

**Comment by Pristine-Cat** [comment]
> It is messy. Going through it though I think that the dotprodsimp parameter makes it worse so we should fix that before next release.

In this particular case if you want to eliminate the function arg then I think the cleanest route would be to simply always use dotprodsimp in `rref`.

**Comment by sylee957** [comment]
I'm fine with going forward this direction.
You should resolve some timeout issues of `dotprodsimp`, rather than making it an optional parameter because of timeouts.
I'd not find logical that `dotprodsimp` should be introduced in a really messy way like before, if it fails the test. 
If it fails the test, it means that there is a flaw.

**Comment by Pristine-Cat** [comment]
> I'm fine with going forward this direction.

Well if you guys are decided on this then next PR I will spend pulling the argument out of functions and making it default. So just waiting on #18564 then.

Keep in mind that there may be cases where dotprodsimp does worse than current but there seem to be many more cases where it does much better, so it is a tradeoff.

**Comment by oscarbenjamin** [comment]
> Keep in mind that there may be cases where dotprodsimp does worse than current but there seem to be many more cases where it does much better, so it is a tradeoff.

That's why this should done carefully. For example I think after fixing tests from making rref do this by default we can see the result of the benchmarks on Travis and consider whether any improvements need to be made.

If we accept that change then we should reprofile before enabling it by default for anything else. We need to see what else still benefits in terms of either improved output or speed.

**Comment by sylee957** [comment]
I think that we should first eliminate the `dotprodsimp` usage like
https://github.com/sympy/sympy/blob/def3cde298d10995597c5da17ca6396236fe5c34/sympy/matrices/matrices.py#L1549
For example, I would rather give up the explicit matrix output, and represent like 
`MatMul(P, eJ, Inverse(P))` than using dotprodsimp.
(I'd note that matrix expression supports all the indexing and does multiplications, inverse in lazy operatoins.)

**Comment by Pristine-Cat** [comment]
Guys, when I started working on matrices I mentioned to @oscarbenjamin that I had a block of free time for this, well that block might be coming to an end, I will know by the weekend. If this is the case then I will not be able to contribute nearly as much (or at all maybe), though I will be available for consult on anything I touched. This is not guaranteed but giving you a heads-up in case it goes through.

Taking that into account I would like to leave what I have done so far in a good state. I will try to do the dotprodsimp removal by end of week and leave it default for some ops and fix the tests. I will start on this now based on the branch from PR #18564 and hopefully it will be in a state for merge asap. Please keep this potential deadline in mind when making requests or suggestions for code changes.

**Comment by Pristine-Cat** [comment]
Ok, well `multiply`, `pow` and `rref` default to dotprodsimp on and it seems to work. I had to change a number of tests (but not as many as I expected). All of the tests except for two fail because the structure of the answer changes but I checked that in all cases it is equivalent so I changed those tests to expect the new structure. Of the two tests I could not fix:

* The last part of `geometry/tests/test_line.py:test_intersection_2d` now hangs. This test normally takes a very long time anyway and the module is full of simplifies so I am guessing something in the change of structure of the answer causes a simplify to go forever (in an equals I believe).

* The other test I could not fix is `physics/vector/tests/test_fieldfunctions.py:test_scalar_potential_difference`, and it is again the last test in this function. I can not fix this because I can not deterministically reproduce it. If I run the test by itself it works fine, however if it runs after `physics/vector/tests/test_dyadic.py` then it fails. The important thing is if I run the test expression manually in a clean shell it works fine as it should, so this is some test global state crap.

BTW, the `vector` and `physics/vector` modules seem to be basically the same thing...

This now calculates #16823 correctly and also the `rref` of #18531, though the `solve_linear_system` still hangs. Now the important part, a **rough** assessment of performance: The total time for the control test suite I did in #18551 was 2697.67 seconds, this test suite with dotprodsimp enabled as mentioned is 2790.01 seconds.

I can not push this since like I said it is based off PR #18564 so unless you want to see a whole mess of changed files and not be able to isolate the changes I did here then merge that one once you are satisfied with it and then I will rebase off the new merged master and push this for review.

I would also say that in my mind I should leave a simple hook mechanism to allow disabling of the dotprodsimp functionality to allow potential legacy user code to run as before. I would not put in a method to control this behavior on the user side (global var, context manager, environment var), you guys could decide that if it were needed after this was incorporated, but it would act as a sort of emergency backup should a lot of user code break that you could just turn this off in an easy way.

**Comment by sylee957** [comment]
Okay, should I merge #18564?

**Comment by oscarbenjamin** [comment]
> Okay, should I merge #18564?

Are you asking me or @Pristine-Cat? I have no objection to merging. I went through some of it and it looks good but it's large so I haven't been through it all...

**Comment by sylee957** [comment]
@Pristine-Cat I'd certify that #18564 is the right PR to merge.

**Comment by oscarbenjamin** [comment]
> * The other test I could not fix is

https://github.com/sympy/sympy/issues/18423

**Comment by Pristine-Cat** [comment]
> > * The other test I could not fix is
> 
> #18423

The weird thing is that it fails even if I comment out everything in `test_dyadic.py`, and I don't see any cache control being done.

**Comment by oscarbenjamin** [comment]
> I don't see any cache control being done.

Have you tried turning the cache off?

If you push up the branch I can take a look

**Comment by Pristine-Cat** [comment]
#18572

There are docs to change since returns changed. I have also not yet removed `dotprodsimp` arg from function sigs since this is trivial and I will do it at the end. The important thing is that multiplies, powers and rref now have it on by default so have a look at results.

I will continue to assess which functions work best with this on default and change it to that in those functions, as well as I will add a single place where this behavior can be turned off in case of emergency.

**Comment by oscarbenjamin** [comment]
The idea here was used in #18572 so this PR is not needed any more.

**Pull request closed without merging**
