### PR TITLE
Unit system: remove dimension and scale_factor arguments from Quantity

### PR DESCRIPTION
**Pull request by Upabjojr**
#### References to other Issues or PRs

https://github.com/sympy/sympy/issues/14318

### CODE REVIEW

**Comment by Upabjojr** [comment]
Better merge this before too many people get accustomed to SI as absolute unit system, which it isn't.

**Comment by schymans** [comment]
This is an extensive refactoring. Could you expand a bit more on the rationale and how Quantities are supposed to be used? I use them in the sense of physical variables with associated dimensions, allowing dimensional analysis, checking for unit consistency etc. I don't see how to adapt my code to work with this new system.

**Comment by Upabjojr** [comment]
Simple, after defining the `Quantity`, there are two methods:
- `set_dimension( )`
- `set_scale_factor( )`

The two parameters of quantity go there. For exmaple:
```python
km = kilometer = kilometers = Quantity("kilometer", abbrev="km")
kilometer.set_dimension(length)
kilometer.set_scale_factor(kilo*meter)
```
This replaces:
```python
kilometer = Quantity("kilometer", length, kilo*meter, abbrev="km")
```

There is a deprecation process, so the old API will still work but raise a warning when used. Sorry for this change but it needed to be done. Just think about the electric charge, what are the dimensions of the charge? They are different in the `SI` and `cgs`.

**Comment by schymans** [comment]
Thanks, but why not instead require setting the dimension system in Quantity? I still don't see the point at this stage, other than using three lines for something that was possible in one line before. What am I missing?

**Comment by schymans** [comment]
Trying to answer my own question: Is the idea to enable changing the dimensions and scale factors of a quantity without having to re-define the quantity? Thinking of physical variable rather than units, one could define a variable and then deduce its dimensions from an empirical equation where it was used. One could then also change the scale_factor if one was going to use it in a different system. Is this one of the potential use cases?

**Comment by Upabjojr** [comment]
> Thanks, but why not instead require setting the dimension system in Quantity? One could even default it to SI if no other information is provided and it would not break anything.

SymPy standard is that the arguments passed to the class constructor are the definition of the object. Arguments that are not part of the definition of the object should not be put there. This has to do with how the internal core of SymPy works, and it makes the code more logic.

> I still don't see the point at this stage, other than using three lines for something that was possible in one line before.

You can create a function that calls the lines.

> One could then also change the scale_factor if one was going to use it in a different system. Is this one of the potential use cases?

Yes, the idea to to store the scale factor in the `UnitSystem` class in the future, so that scale factors will be in unit system objects.

> Is the idea to enable changing the dimensions and scale factors of a quantity without having to re-define the quantity?

That's the point. I want to define `speed_of_light` and `meter` only once, for example. In natural units, `speed_of_light` will be dimensionless, and its scale factor will be 1.

As of `meter`, this quantity is usually used only in SI or length based unit systems, it could potentially be defined with an inherent dimension. Still, the difference between units and constants is psychological: the meter could still be used in natural units and have a scale factor of `1/299792458` (the reciprocal of the speed of light in meters).

**Comment by schymans** [comment]
Thanks, this helps! I will try to use the new formulations and see how it goes.

**Comment by schymans** [comment]
I have two more questions. I am still thinking of quantities as physical variables, not units. A scale factor for `density` can be defined e.g. as `kilogram/meter**3`, which results in a scale factor of `1000`. (a) Does it make sense to allow changing the dimension without changing the scale factor?
(b) When defining a scale factor for a unit, we have some intrinsic base unit in mind, when defining it for a physical variable, we have some units related to dimension in mind. How can we get to the information about the units the scale factor refers to? I guess they are encoded in the dimensions.

**Comment by Upabjojr** [comment]
> (a) Does it make sense to allow changing the dimension without changing the scale factor?

The problem is with potential dimensional contractions, for example if you consider `time` and `length` to be the same dimension by setting the speed of light to unity, you need only one reference unit instead of two (`meter` and `second`).

My idea is to put the scale factor for the units in an instance of the class `UnitSystem`. So if you create `SI = UnitSystem("SI", ... )`, there will be a dict mapping quantities to their scale factor for the `SI` unit system.

Another unit system with a different dimension system will have another dict mapping quantities to other scale factors. I believe that's the simplest solution.

> (b) When defining a scale factor for a unit, we have some intrinsic base unit in mind, when defining it for a physical variable, we have some units related to dimension in mind. How can we get to the information about the units the scale factor refers to?

So far, the unit quantity for the scale factor has been chosen to match the conventional SI base units (except for `kilogram` that has a scale factor of 1000). The scale factor should only be used internally in SymPy. End users should not.

To find the reference unit, you can look up the quantity-scale factor mapping dict, looking for which quantities are mapped to unity.

`convert_to` can be used to simplify divisions of units with the same dimension.

There is another PR where the function `quantity_simplify` is being introduced. It will allow to simplify units in cases like `kilometer/meter`.

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/pull/14286

**Comment by schymans** [comment]
For the dimensions, would it not be adequate to define the dimensions once in a specified UnitSystem, and then do the conversions within different unit systems? For example, if I define a velocity in the SI unit system as length per time, and then want to use it in the natural unit system, then the conversion could be done through the mapping of time and length in the natural unit system. Not sure how to deal with the scale_factor, though. 

Here is how I am currently using it. I would define the speed of light e.g. as `v_c = Quantity('v_c', dimension=length/time, scale_factor = 299792458*meter/second)`. Then, I can use `v_c` in a system of equations along with other physical variables, where I automatically get a warning if I define an equation with inconsistent units. At the end, after solving my system of equations for the desired target variables, I want to calculate their magnitude by substituting the correct scale_factors and using the `convert_to` function to obtain the result in the desired units. In this approach, the scale factor is used internally by translating e.g. `299792458*meter/second` to the appropriate `scale_factor` in the SI UnitSystem and performing algebraic operations using the scale factors of all other variables, but I as the user still want to interact with the scale factor, preferably in an intuitive way, i.e. I want to be able to convert the internal `scale_factor` of `299792458` back to `299792458*meter/second` in the SI system. Do you see what I mean?

After your refactoring, the above workflow could actually become more robust than before, as I could attach dimensions to quantities, and dynamically change their scale_factor. For example, I could have an equation of pressure as a function of temperature and then substitute different scale_factors for temperature to calculate the P(T) curve. At present, I do e.g. `equation.xreplace(temperature, 300*kelvin)`. The problem is that in the old system, temperature would already have a scale_factor, so if I forgot to include temperature in the xreplace, `convert_to` would still return a result, but based on `temperature = 1*kelvin`. Leaving scale_factor un-assigned could avoid such errors.

**Pull request merged**
