### PR TITLE
Add workflow for marking (and unmarking) merge conflicts

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed

Using this action, PRs with merge conflicts will be automatically marked (and unmarked when fixed). It is not so obvious to test without actually merging, but Matplotlib uses it since a week at I think it really helps.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Will this apply retrospectively?

**Comment by oscargus** [comment]
Yes. It goes through all the PRs and updates the flags every time it is executed. (So seemingly a bit inefficient after the first run, but I guess that PRs actually can un-conflict without being modified).

**Comment by oscargus** [comment]
253 PRs marked

**Comment by asmeurer** [comment]
I'm unclear what exactly this does. I found a few PRs that had merge conflicts, and I didn't see any labels or additional checks on them.

**Comment by oscargus** [comment]
That's weird... My experience is that it works pretty well. Here are all that it has marked anyway: https://github.com/sympy/sympy/labels/Merge%20conflict

**Comment by asmeurer** [comment]
Here's two random PRs I found without the label https://github.com/sympy/sympy/pull/22845 https://github.com/sympy/sympy/pull/22831

**Comment by asmeurer** [comment]
The newest PR with the label is #20033 so maybe it just ran into some API limit or something and stopped there. Hopefully it is able to mark them in future runs.

**Comment by oscargus** [comment]
The newest in that list is from Sep 1 2020 though, so maybe unlikely that there are no after that...

OK, there was a warning about maximum retries: `Warning: reached maximum allowed retries`

I guess that GitHub may have been slow when it was run. Took 14 minutes to not process all 574 open PRs. For Matplotlib it often takes 4 minutes to process about 340 open PRs (but recently sometimes 8 minutes). Let's give it a few more pushes to master to hopefully get through.

**Comment by oscargus** [comment]
I restarted it and it seems to have passed #20033 already after a minute...

**Comment by asmeurer** [comment]
More likely that was the script running into the API rate limits https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting. Scripts can only make 5000 requests per hour, so if each PR takes n requests it will only be able to mark 5000/n PRs. If it's able to only handle new PRs since each run, it won't be a problem, but if it has to go through every PR every time it runs it will never get to the newest PRs.

**Comment by oscargus** [comment]
Now it finished in 6 minutes. I think it waits for 120 seconds each time it fails and retries five times in total before giving up. Probably to not hit that limit too often.

402 PRs with merge conflicts in total.

**Comment by asmeurer** [comment]
I guess it is working. I noticed a similar issue reported upstream https://github.com/eps1lon/actions-label-merge-conflict/issues/86. If it repeatedly gets rate limited we'll have to figure something out. Otherwise I guess it will be fine. Although I'm a little unclear just which account this gets rate limited against. Is it @eps1lon's account, or @sympy, or something else?

**Comment by ThePauliPrinciple** [comment]
Would it make sense to similarly mark PRs that have not passed the tests (yet)? Or can we already somehow search for that?

**Comment by oscargus** [comment]
I think that can make sense. Didn't find any dedicated action from a quick check though. Seems like one can, sort of, mimic that running dedicated flows for `success()` and `failure()` though: https://stackoverflow.com/questions/60453924/running-a-github-actions-step-only-if-previous-step-has-run

**Pull request merged**
