### PR TITLE
continuum_mechanics: statically indeterminate beam problem can be solved

### LINKED ISSUE #14466: continuum_mechanics: beam can not solve statically indeterminate problems.
```>>> from sympy.physics.continuum_mechanics.beam import Beam
>>> from sympy import symbols, linsolve, limit
>>> E = symbols('E',positive=True)
>>> I = symbols('I',positive=True)
>>> R1, R2 = symbols('R1, R2')
>>> M1, M2 = symbols('M1, M2')
>>> p = symbols('p')
>>> l = symbols('l',positive=True)
>>> b = Beam(l, E, I)
>>> b.apply_load(R1, 0, -1)
>>> b.apply_load(R2, l, -1)
>>> b.apply_load(M2, l, -2)
>>> b.apply_load(M1, 0, -2)
>>> b.apply_load(p, l/2, -1)
>>> b.bc_deflection = [(0, 0), (l, 0)]
>>> b.bc_slope = [(0, 0), (l, 0)]
>>> b.solve_for_reaction_loads(R1,R2,M1,M2)
>>> b.reaction_loads
{M2: M2, M1: M1, R2: (M1 + M2 - l*p/2)/l, R1: -(M1 + M2 + l*p/2)/l}
```
`M2` and `M1` are also unknowns
It is also unable to solve statically indeterminate problems.

### PR DESCRIPTION
**Pull request by rushyam**
Fixes #14466
I will add the documents for solving the statically indeterminate beam problems.

### CODE REVIEW

**Comment by rushyam** [comment]
@moorepants  please review.

**Comment by rushyam** [comment]
@moorepants could you please suggest me any book from where I can solve beam problem add it as documentation? 
I am using this [book](http://civil-team.weebly.com/uploads/2/5/8/2/25829430/structural_analysis_hibbeler_8th.pdf)

**Comment by rushyam** [comment]
@moorepants, please review

**Comment by rushyam** [comment]
@moorepants, please review

**Comment by rushyam** [comment]
@moorepants, please review

**Comment by rushyam** [comment]
@moorepants, please review

**Comment by rushyam** [comment]
ping @moorepants

**Comment by Abdullahjavednesar** [comment]
@moorepants @oliverlee can anyone please review this, thanks!

**Comment by rushyam** [comment]
@moorepants thankyou at least do not ignore this pull request.

**Comment by moorepants** [comment]
@rushyam I am not ignoring anything. We are all volunteers and we get to things when we can. I don't always have extra time due to work/family/etc. If I am not responsive you are welcome to approach other SymPy developers to get a review.

**Comment by moorepants** [comment]
@jashan498 have you looked at this PR? Is it needed anymore? If so, can you review?

**Comment by jashan498** [comment]
@rushyam the issue was solved through commits taken from [#14681](https://github.com/sympy/sympy/pull/14681). If its okay, you can add another test case to the master after solving merge conflicts.

**Comment by moorepants** [comment]
@rushyam Do you plan to add the test cases? If not, we will close this PR. Thank you.

**Comment by moorepants** [comment]
Going to close this PR since there is no response. @rushyam please reopen if you want to finish in the future.

**Pull request closed without merging**
