### PR TITLE
Make ccode respect 'Max' in user_functions.

### PR DESCRIPTION
**Pull request by bjodah**
Fixes gh-11926

### CODE REVIEW

**Comment by bjodah** [comment]
@jhncls does this work for your purposes?
also cc:ing @moorepants & @jcrist (based on `git blame`) for review.

**Comment by asmeurer** [comment]
Printing Expr the same as Function seems like a good idea to me.

**Review by asmeurer — APPROVED** [review]

**Comment by jhncls** [comment]
Hi Björn,
Yes, this solves my problem with Max and Min.
I also notice that in your new version de standard ccode("Max(x,x*x)") without user_functions now prints out "not supported in C". I suppose that's an intended behaviour. In our code we only use Max with two arguments, while sympy supports an arbitrary number of arguments.
Many thanks for looking into this issue.
Johan

**Comment by bjodah** [comment]
I just checked master and this is what I get:
```
>>> ccode(Max(x, x*x))
'Max(x, pow(x, 2))'
```
where `Max` is just the name of the sympy class, it is not defined in the C standard (to my knowledge).
C++ does have 2 argument std::min and std::max in algorithm. But as you point out, that does not map well
to sympy's version with arbitrary number of arguments. We could supple a "support library" with sympy for e.g. C++ and then we could have variadic versions of min and max (see e.g. here for an example http://stackoverflow.com/questions/23815138/implementing-variadic-min-max-functions). But that is quite ambitious for now. Please feel free to open a separate issue for it though to track it.

**Pull request merged**
