### PR TITLE
Finite Set domains for `function_range`

### PR DESCRIPTION
**Pull request by akash9712**
Added functionality for `function_range` if the domain is a finite set.
New tests were added and one previously incorrect test was corrected.
Also made changes to the existing `function_range` due to which the incorrect test passed.

Example:
```
In [2]: function_range(sin(x), x, Union(Interval(pi, 3*pi/2), FiniteSet(pi/2)))
Out[2]: [-1, 0] ∪ {1}
```

### CODE REVIEW

**Comment by akash9712** [comment]
Ping @smichr

**Comment by smichr** [comment]
Nice catch! I see that this definition of range agrees with what [is given here](http://www.analyzemath.com/DomainRange/find_range_rational.html), so that's good. Looks like a couple of tests to adjust. Also, instead of doing `if instance(a, b) or isinstance(a, c)` you can write `if isinstance(a, (b, c))`.

**Comment by akash9712** [comment]
@smichr This commit (1e10d0a) should should handle one of the failing tests out of two. The other test failing needs to be modified for the build to pass without failures, but I could not find the location of the test.

**Comment by smichr** [comment]
If you click on the failing run it will give a log that tells the location:

```
File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/sympy/calculus/util.py", line 103, in sympy.calculus.util.function_range
Failed example:
    function_range(1/x, x, S.Reals)
Expected:
    Interval(-oo, oo)
Got:
    Union(Interval.open(-oo, 0), Interval.open(0, oo))
```

**Comment by smichr** [comment]
@akash9712 any chance you could look at #13487?

**Pull request merged**
