### PR TITLE
Fixing simpify (evaluate = False) for Unary Operators - Issue #10560

### PR DESCRIPTION
**Pull request by sanyagithub**
`>>> sympify('4*-3', evaluate=False)`
`(-3)*4`

### CODE REVIEW

**Comment by AnishShah** [comment]
Hi @sanyagithub, this pull request has commits related to other issues (10612) too. It is generally a good practice to create a branch from 'master', commit your changes to the new branch and submit a pull request.

**Comment by sanyagithub** [comment]
@AnishShah Thank you ! Should I close this one? And then submit a new pull request again?

**Comment by AnishShah** [comment]
@sanyagithub You can remove old commits (related to issue 10612) and force push into your master branch. But, you will face the above issue again if you want to work on multiples issues at the same time.

**Comment by smichr** [comment]
This has orphaned commits: the first two. I recommend that you do the following:

```
git checkout master
git checkout -b plot3d
git cherry-pick  4e50d7b
git cherry-pick  7fc02b1
git reset head~1
git commit --amend
git push sanyagithub plot3d
```

In the ammend step you can just delete the note about fixing whitespace when you are given the editor session with the commit message.

Then open a new PR with this branch and let's get that fix in if it looks ok.

**Comment by smichr** [comment]
The only reason this build failed was because it was based on an old master so the doctest vesion was wrong in the string of one of the tests: https://travis-ci.org/sympy/sympy/jobs/110584432

**Comment by debugger22** [comment]
@AnishShah You should really refrain from using or suggesting someone to use force push. :)

A good read: http://randyfay.com/content/avoiding-git-disasters-gory-story

**Pull request closed without merging**
