### PR TITLE
Fix the Derivative.subs(Derivative) algorithm

### LINKED ISSUE #9135: Incorrect subsitution of partial derivatives by .subs()
With sympy 0.7.6, the subs() method does a wrong substitution:

    from sympy import *
    init_printing()

    x,y,z=symbols('x,y,z')
    f=Function('f')

    expr = diff(f(x,y),x,x,y)
    pprint(expr)

    e2 = expr.subs(diff(f(x,y),y,2), z)
    pprint(e2)

The call to subs() method incorrectly substitutes a `df/dy` with `z`, while we asked to substitute `d2f/dy2` instead !

### PR DESCRIPTION
**Pull request by asmeurer**
The algorithm was not properly handling some cases where the derivative was
not a sub-derivative. It now uses collections.Counter to check if the one
derivative's variable multiset is a subset of the other's.

Fixes #9135.

### CODE REVIEW

**Comment by asmeurer** [comment]
Oh apparently Python 2.6 doesn't have collections.Counter. 

I think I might just wait until the release when we drop 2.6 support.

**Comment by asmeurer** [comment]
Merged with master.

**Comment by cklb** [comment]
hey,
I just stumbled over this issue today and since it looks like it has been fixed a while ago I'am wondering where the fix ended up since the current master still shows the flawed behavior. 
@asmeurer what can be done to fix this?

**Comment by asmeurer** [comment]
I just need someone to review this. If you can check out the branch and verify that it fixes the problem for you, that would help.

**Comment by cklb** [comment]
Hey,

thank you for your prompt reaction. I checked out the branch and played a little with the new code. As your extended testcase and the snippet below are suggesting, the problem of "fuzzy" substitution is fixed.


```
In [1]: from sympy import Function, symbols, Integral
In [2]: f = Function("f")
In [4]: x, y, z = symbols("x y z")
In [5]: q = f(x, y).diff(x, x)

In [6]: q.subs(f(x, y).diff(x), 100)       # substitude sub-derivatvie
Out[6]: Derivative(100, x)                 # ok.

In [7]: q.subs(f(x, y).diff(x, x), 100)    # substitude whole derivatvie
Out[7]: 100                                # ok.

In [8]: q.subs(f(x, y).diff(y), 100)       # don't substitute anything
Out[8]: Derivative(f(x, y), x, x)          # ok.

In [9]: q.subs(f(x, y).diff(y, y), 100)    # don't substitute anything
Out[9]: Derivative(f(x, y), x, x)          # ok.
```
But while testing I discovered another issue that might be connected:
```
In [10]: p = Integral(q, (x, 0, 1)); p     # what about derivatives in integrals
Out[10]: Integral(Derivative(f(x, y), x, x), (x, 0, 1))

In [11]: p.subs(f(x, y).diff(y), 100)      # again, nothing should be substituted
Out[11]: Integral(Derivative(f(x, y), x, x), (x, 0, 1)) # ok.

In [12]: p.subs(f(x, y).diff(y, y), 100)   # again, nothing should be substituted
Out[12]: Integral(Derivative(f(x, y), x, x), (x, 0, 1)) # ok.

In [13]: p.subs(f(x, y).diff(x), 100)      # substitude sub-derivatvie
Out[13]: Integral(Derivative(f(x, y), x, x), (x, 0, 1)) # no substitution occurs.

In [14]: p.subs(f(x, y).diff(x, x), 100)   # substitude whole derivative
Out[14]: Integral(Derivative(f(x, y), x, x), (x, 0, 1)) # no substitution occurs.
```
Short story: Derivative objects in Integrals are not subtituted the way I would expect them to be. 
If I got it right, the Integral class will call `_subs()` on its arguments in its `_eval_subs()` routine or in `fallback()`. Though this error might also be related to the `_eval_subs()` of Derivative.

Greetings,
Stefan

**Comment by asmeurer** [comment]
The relevant code is [here](https://github.com/sympy/sympy/blob/e6d1d55baaeb5b6cb170234f109fecfe8bafeec5/sympy/concrete/expr_with_limits.py). I'm not sure if there's a bug in the logic or if the behavior is intentional.

**Comment by cklb** [comment]
hey,
it looks like ``_eval_subs()`` of ``ExprWithLimits`` should not only check whether its first argument is an instance of ``AppliedUndef`` or ``UndefinedFunction`` but rather if one of this classe is contained in the expression. I would propose to change line 317 in ``expr_with_limits.py`` from
```
if isinstance(old, AppliedUndef) or isinstance(old, UndefinedFunction):
```
to something like
```
if old.atoms(AppliedUndef, UndefinedFunction):
```
which fixed the problems of lines 13 and 14 above.
I added a test-case to check the functionality but I'm not sure whether it belongs into together with the other subs tests in core or better

Another problem is the substitution of derivatives for variables wich do not coincide with the integration variable. This rises a ``ValueError: substitution can not create dummy dependencies`` which not completely correct in my opinion (see the 2nd assert in the new test case.)

Since both issues don't seem to be related to the original problem I would propose to handle them seperately.

The changes can be found here 41b2fa654525c78615deb52d9b996162977396b1

Stefan

**Comment by asmeurer** [comment]
Yes, please open a new pull request with your changes. If you see no issues with my changes, I'd like to merge this.

**Comment by cklb** [comment]
Hey,
allright I'll do that. As stated above, from point of view (which is quite limited though) I can't see any problems with merging this PR.

Stefan

**Pull request merged**
