### PR TITLE
Fixes bug in limits #10610

### LINKED ISSUE #10610: limit(3**n*3**(-n - 1)*(n + 1)**2/n**2, n, oo) is wrong
```
In [41]: limit(3**n*3**(-n - 1)*(n + 1)**2/n**2, n, oo)
Out[41]: 1
```

From https://stackoverflow.com/questions/35428617/sympy-fails-limit-test. If you expand the expression first the terms cancel and it gets the answer right. The answer should be 1/3.

### PR DESCRIPTION
**Pull request by govindlahoti**
Fixes #10610 

There was bug in condition testing whether the limit can be computed using leading term approach. Fixed.

### CODE REVIEW

**Comment by govindlahoti** [comment]
@asmeurer Can you please review it

**Comment by jksuom** [comment]
The criterion for the leading-term approach is still too loose:
```
In [1]: limit((3**n + n)/(3**(n + 1) + n), n, oo)
Out[1]: 1
```

**Comment by gxyd** [comment]
@govindlahoti can you resolve merge conflicts and address requested changes.

**Comment by gxyd** [comment]
May be the bug has been fixed?
```python
In [1]: limit((3**n + n)/(3**(n + 1) + n), n, oo)
Out[1]: 1/3
```

**Comment by govindlahoti** [comment]
@gxyd Yes, the underlying issue has been closed.

**Comment by gxyd** [comment]
Yes, can you please close the PR then?

**Comment by gxyd** [comment]
The correspnding issue has been fixed by https://github.com/sympy/sympy/pull/12121

**Pull request closed without merging**
