### PR TITLE
[PEP8] Improve code quality in sets and fancysets

### PR DESCRIPTION
**Pull request by madan96**
Made some minor fixes in code quality.

### CODE REVIEW

**Comment by madan96** [comment]
@jksuom Can you please review this?

**Comment by jksuom** [comment]
It is seldom necessary to add whitespace around the multiplication operator `*`. (That should be done only when its priority is lowest in the expression.) There are examples in PEP8:
```
 Yes:

i = i + 1
submitted += 1
x = x*2 - 1
hypot2 = x*x + y*y
c = (a+b) * (a-b)

No:

i=i+1
submitted +=1
x = x * 2 - 1
hypot2 = x * x + y * y
c = (a + b) * (a - b)
```

**Comment by madan96** [comment]
Thanks for that info. I didn't know that there were such provisions in PEP8. I have removed the unnecessary changes.

**Comment by madan96** [comment]
@jksuom Can this be merged or are there any other changes needed?

**Comment by jksuom** [comment]
I seems to me that there are rather too many changes. Most of the expressions with a single multiplication or division operator do no need extra space. That is generally useful only in some complicated expressions to make it easier to visually distinguish the principal components.

**Pull request closed without merging**
