### PR TITLE
sympify handles iterable contents

### LINKED ISSUE #13425: N(<string>, 30) and sympify: implement a decimal precision kwarg?
Passing a string to `N` is not explicitly documented, but it does work.  The implementation is `sympify(<input>).evalf(n)`.  Should we change `N` to `sympify(<input>, evaluate=False).evalf(n)`?  This improves accuracy in some very specific cases.

This came up downstream https://savannah.gnu.org/bugs/?51748

- - - - -

Here's the background.  The current code generally DTRT, for example:
````
>>> N('sqrt(2)', 30)
1.41421356237309504880168872421
>>> _**2
2.00000000000000000000000000000
````

In general if you put floats in the string, its not going to possible to get more than 15 digits of accuracy and you shouldn't be doing that.  But people do it anyway and then think its a bug:
````
>>> N('2**0.5', 30)
1.41421356237309514547462185874
>>> _**2
2.00000000000000027343234630648
````
But it is possible to get full precision in this case:
````
>>> sympify('2**0.5', evaluate=False).evalf(30)
1.41421356237309504880168872421
>>> _**2
2.00000000000000000000000000000
````

1.  In the current implementation `'2**0.5'` is evaluated to a Float with default precision.  Of course, this cannot be magically re-evaluated in higher precision.
2.  Deferring the evaluation works better in this specific case b/c the float `0.5` is exact in binary.
3.  Deferring will not help at all with `'2**0.1'` because `0.1` is not an integer power of 2 so will be inexact in binary.
4.  I worry this might make some other calculation worse (due to additional rounding error), but I have no concrete example.

### LINKED ISSUE #16769: sympify does not convert dict to Dict
#### Problem
sympify does not convert to dict to Dict which causes hashing problems.

#### Example of problem
```
>>> from sympy import *
>>> d = {1:1}
>>> type(d)
<class 'dict'>
>>> type(sympify(d))
<class 'dict'>
>>> type(Dict(d))
<class 'sympy.core.containers.Dict'>

```
As seen in the above example, dict hasn't been converted to Dict.

#### Other comments/references
Please see [this line's](https://github.com/sympy/sympy/pull/16765/files#diff-d7e4f5f281e7cc9d7e638ad224e148b3R31) comment for issues regarding not converting dict to Dict. 
Reasons for not doing so are awaited.
Thanks in advance.

### LINKED ISSUE #16772: sympify does not use rational flag with recognized objects
Each of the following should have a 1/2 in the output
```python
>>> S([.5],rational=True)
[0.500000000000000]
>>> S((.5,),rational=True)
(0.5,)
>>> S({1: .5}, rational=True)
{1: 0.5}
>>> S({1,.5}, rational=True)
{0.5, 1}
>>> S(.5, rational=True)
0.500000000000000
```
The converter takes control of the return value before the arguments can be sympified *with the stated flags*. In the case of a float, processing can use `'%s/%s'%a.to_integer_ratio()` instead of the float -- not `str(a)` which will truncate.

### PR DESCRIPTION
**Pull request by smichr**
#### References to other Issues or PRs

closes #16769 
closes #16772
fix #13425 
#### Brief description of what is fixed or changed

```python
"""
dict is now converted to Dict, keys and values
"""
>>> isinstance(S({1:2}), Dict)  # converter added for Dict
True
"""
All handled containers get their contents sympified according
to the settings (rational and xor were formerly missed):
"""
>>> all(list(sympify(_([.5])))[0] is S.Half for _ in (list, set, tuple))  # formerly Float(.5)
True
"""
raw Python numbers are converted with regard to rational setting, too
"""
>>> S(.1, rational=True) == Rational(.1)  # formerly Float(.1)
True
```
#### Other comments

The order of events is more strictly ordered according to desired outcomes:
1. deal quickly with Python primitives
1. if a routine doesn't want to be sympified, honor that quickly
1. if a routine wants to handle sympification, let it

There was an interesting test failure that highlights the corner cases for `sympify`. Formerly,
```python
>>> srepr(sympify(('x', 'y'), strict=True))
"Tuple(Symbol('x', Symbol('y'))"
```
But now this raises a SympificationError. The test that gave the error checked whether `tuple('HT')` was in a set rather than `Tuple(*'HT')` in set.

The addition of `iwalk` has allowed new handling in `sympify` and `nfloat`. It could probably be used as a decorator so all SymPy functions would just work when fed an iterable (but that won't be part of this PR). 

`nfloat` formerly gave
```python
>>> nfloat(Line((1,2),(3,4)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\leslie\sympy\sympy\core\function.py", line 3123, in nfloat
    rv = rv.n(n)
AttributeError: 'Line2D' object has no attribute 'n'
```
But now gives
```python
>>> nfloat(Line((1,2),(3,4)),2)
Line2D(Point2D(1.0, 2.0), Point2D(3.0, 4.0))
```
#### Release Notes

- core 
    - `sympify`
        - honor `rational` and `convert_xor` flags for floats and iterable contents
        - when specifying `rational=''` the conversion to Rational will use the string form of the number so S(.1, rational='') and S('.1') will both give 1/10.
        - dict is now converted to Dict; to avoid sympification of keys and values, pass only items and rebuild dict locally
        - if `strict` is False then defaultdict can also be processed but it is not returned as Dict
        - when `strict` is true, passing a tuple with strings will no longer return a Tuple of sympified objects; use `Tuple(*map(sympify, tuple))` instead (or `Tuple(*'abc')` or `symbols('a:c')` to create a list of Symbols).
    - `nfloat` in `functions` should now work on any Basic object
    - `N`, when given a string, will parse it with `evaluate=False` before make the evaluation so `0.5` and `1/2` will behave the same during evaluation. Other non-binary-exact decimals will suffer from precision loss, however, and it is better to sympify input first -- passing strings to SymPy functions is generally an anti-pattern -- as `N(S('0.1*pi', rational=True), 22)`. 
- utilities
    - `iwalk` has been added to `iterables` to traverse, from top down, an arbitrary Python expression, apply a function to the arguments and (optionally) to the iterable itself.

### CODE REVIEW

**Comment by smichr** [comment]
ping @czgdp1807

**Comment by czgdp1807** [comment]
@smichr Thanks a lot for making this PR. This solves the issue though [one of the baseline tests](https://travis-ci.org/sympy/sympy/jobs/530268197) are failing which I think can be solved and may be is unrelated to the conversion of `dict` to `Dict` by `sympify`. 
PS - Apologies for the late response.

**Comment by smichr** [comment]
> Apologies for the late response.

No problem. The dust has only now settled. I learned how to use pip and installed numpy on my system and that helped a lot. From my perspective, this is a lot more robust at doing what it is supposed to be doing. With the changes here, if so desired, the `rational=True` flag of `nsimplify` could be deprecated in favor of `S(expr, rational=True)`...or that call could be made in `nsimplify` when the flag there is used. Just aa thought, but I won't try that with this PR.

The tests should pass this time around. I'll leave this alone for a while to see if anyone (including you) has comments.

**Comment by smichr** [comment]
Even though I haven't run a profiler on this I can see that tests for this branch are taking longer than others. This is to be expected given what this is trying to do. But perhaps we shouldn't try to do it: the `rational` and `convert_xor` could be only for *string input*. That way there would not have to be a double traversal of iterable input...and updating the docstring will be easy in comparison.

**Comment by czgdp1807** [comment]
@smichr From my side, the part which handles `dict` is fine. So, I think as soon as this is merged, I will be able to make changes to [PR #16765](https://github.com/sympy/sympy/pull/16765).

**Pull request closed without merging**
