### PR TITLE
TypeError with too many functions

### LINKED ISSUE #16146: Dsolve: TypeError with too many functions
This is invalid since I'm asking to solve for 3 functions from 2 ODEs but the error should be detected properly rather than failing in this way:
```julia
In [2]: dsolve([f(t).diff(t), g(t).diff(t)], [f(t), g(t), h(t)])                                                                                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-a1291c436ca5> in <module>
----> 1 dsolve([f(t).diff(t), g(t).diff(t)], [f(t), g(t), h(t)])

~/current/sympy/sympy/sympy/solvers/ode.py in dsolve(eq, func, hint, simplify, ics, xi, eta, x0, n, **kwargs)
    606                     pass
    607                 else:
--> 608                     if eq[i].coeff(diff(func[i],t,ode_order(eq[i], func[i]))).is_negative:
    609                         eq[i] = -eq[i]
    610         match['eq'] = eq

~/current/sympy/sympy/sympy/solvers/deutils.py in ode_order(expr, func)
    109     """
    110     a = Wild('a', exclude=[func])
--> 111     if expr.match(a):
    112         return 0
    113 

~/current/sympy/sympy/sympy/core/basic.py in match(self, pattern, old)
   1605         """
   1606         pattern = sympify(pattern)
-> 1607         return pattern.matches(self, old=old)
   1608 
   1609     def count_ops(self, visual=None):

~/current/sympy/sympy/sympy/core/symbol.py in matches(self, expr, repl_dict, old)
    478             return None
    479         repl_dict = repl_dict.copy()
--> 480         repl_dict[self] = expr
    481         return repl_dict
    482 

~/current/sympy/sympy/sympy/core/basic.py in __hash__(self)
    124         h = self._mhash
    125         if h is None:
--> 126             h = hash((type(self).__name__,) + self._hashable_content())
    127             self._mhash = h
    128         return h

TypeError: unhashable type: 'list'
```

### PR DESCRIPTION
**Pull request by divyanshu132**
#### References to other Issues or PRs
Fixes #16146

#### Brief description of what is fixed or changed
In an attempt to solve an ode with different number of equations and functions an unexpected error was generating. That has been fixed.

#### Release Notes

*  solvers
   *  check for variable number of functions and equations in ode.py

### CODE REVIEW

**Comment by divyanshu132** [comment]
@oscarbenjamin please review.

**Comment by oscarbenjamin** [comment]
Looks good. Can you add a test for this?

Is there a test for the other case? If so they should go together. Otherwise we should add a test for teh other case as well.

**Comment by divyanshu132** [comment]
I couldn't find the test for the other case. So, I added tests for both the cases.

**Comment by oscarbenjamin** [comment]
Looking again it's probably best to combine these into a single `!=` case.

**Comment by sharma-kunal** [comment]
@divyanshu132 As @oscarbenjamin said it would be better to use just one `!=` case maybe like, 

```
if len(funcs) != len(eq):
    raise ValueError("Number of functions given is not equal to number of equations %s" % funcs)
```

**Comment by divyanshu132** [comment]
I should have done that only in the beginning.

**Comment by divyanshu132** [comment]
@oscarbenjamin can this be merged.

**Comment by oscarbenjamin** [comment]
Yes it can. Thanks for this!

**Pull request merged**
