### PR TITLE
Added changes to the drv_types.py file

### PR DESCRIPTION
**Pull request by safiya03**
#### References to other Issues or PRs
Fixes #20031 

#### Brief description of what is fixed or changed

Fixed issue with geometric random variable

#### Release Notes

* stats
  * Added changes to stats/drv_types.py file to correct density for Geometric random variable.

### CODE REVIEW

**Comment by safiya03** [comment]
### Todo

- [ ] Add tests to support changes

**Comment by Smit-create** [comment]
Hi @safiya03,
Thanks for the PR!
I request you to make similar changes to all the `pdf` methods of the distribution classes to make sure all of them work fine. For example, you will notice a similar issue with `Gamma`. So, this requires changes in all the classes. In this PR you can limit the changes to Discrete RVs, and open a new PR for similar changes in continuous RV.

**Comment by safiya03** [comment]
Hi @Smit-create, 
Sure, I will do that too. Currently, I'm trying to figure out how to correct/pass the failing tests, seems that the return type for a few functions will change to piecewise. So, do I need to rewrite the tests accordingly? Can you please help.

**Comment by Smit-create** [comment]
> So, do I need to rewrite the tests accordingly?

Yes, because the previous tests didn't bother about the set on which the distribution is defined, and now after fixing it there should be necessary changes in tests too.

**Comment by safiya03** [comment]
Hi @Smit-create 
I'm trying to assert the following with the same output, but it's giving false, any reason for this behavior?

```
In [9]: X = Geometric('X', Rational(1, 5))

In [10]: Y = Geometric('Y', Rational(3, 10))

In [11]: coskewness(X, X + Y, X + 2*Y)
Out[11]: sqrt(5)*Sum(Piecewise((3*(7/10)**(Y - 1)*(60*Y - 20)/10, (X >= 1) & (Y >= 1) & (X < oo) & Eq(X, floor(X)) & Eq(Y, floor(Y))), (0, True)), (Y, 1, oo))/(10*sqrt(Sum(Piecewise((3*(7/10)**(Y - 1)*(Y**2 - 20*Y/3 + 280/9)/10, (X >= 1) & (Y >= 1) & (X < oo) & Eq(X, floor(X)) & Eq(Y, floor(Y))), (0, True)), (Y, 1, oo)))*sqrt(Sum(Piecewise((3*(7/10)**(Y - 1)*(4*Y**2 - 80*Y/3 + 580/9)/10, (X >= 1) & (Y >= 1) & (X < oo) & Eq(X, floor(X)) & Eq(Y, floor(Y))), (0, True)), (Y, 1, oo))))

In [13]: coskewness(X, X + Y, X + 2*Y) == sqrt(5)*Sum(Piecewise((3*(7/10)**(Y - 1)*(60*Y - 20)/10, (X >= 1) & (Y >= 1) & (X < oo) & Eq(X, floor(X)) &
    ...: Eq(Y, floor(Y))), (0, True)), (Y, 1, oo))/(10*sqrt(Sum(Piecewise((3*(7/10)**(Y - 1)*(Y**2 - 20*Y/3 + 280/9)/10, (X >= 1) & (Y >= 1) & (X < oo
    ...: ) & Eq(X, floor(X)) & Eq(Y, floor(Y))), (0, True)), (Y, 1, oo)))*sqrt(Sum(Piecewise((3*(7/10)**(Y - 1)*(4*Y**2 - 80*Y/3 + 580/9)/10, (X >= 1)
    ...:  & (Y >= 1) & (X < oo) & Eq(X, floor(X)) & Eq(Y, floor(Y))), (0, True)), (Y, 1, oo))))
Out[13]: False

**Comment by amy12xx** [comment]
I can look at this issue, but I'd like to re-ask the question that was in the original? issue #20031 if piecewise is the correct fix for discrete RVs. I see that in some other cases (e.g. NegativeBinomialDistribution) we are performing a check for the value (line 341). Is that a different case? if not, a consistent solution should be used across all drvs, where possible. 
```
_value_check(r > 0, 'r should be positive')
```

**Comment by oscarbenjamin** [comment]
I think that we don't need to use Piecewise for the pdf of a discrete random variable. The pdf should be called pmf. Even if we don't rename it we should understand that that's what it means. A pmf function has no implied domain and the expression for it should only be expected to be valid over the range of possible values for the random variabe.

**Comment by amy12xx** [comment]
Ok, so then I see 2 options:
1. To leave it as it is, and assume the user is aware of what the allowable support is.
2. We can add a check in the pdf (really pmf) function to assert this. Something like this
```
    def pdf(self, k):
        _value_check((k > 1), "k must be non-negative")
        return (1 - self.p)**(k - 1) * self.p
```
and add a test for it. This should then be done for other discrete distributions as well, which have such conditions. not sure if this is overkill.

**Comment by oscarbenjamin** [comment]
The problem is that someone can pass a symbol for `k` and then substitute it for a different number afterwards. That's what the Piecewise is for.

**Comment by amy12xx** [comment]
ah ok, makes sense.

**Comment by czgdp1807** [comment]
Closing in favor of https://github.com/sympy/sympy/pull/20512

**Pull request closed without merging**
