### PR TITLE
asserts related to addition and multiplication of even/odd integers

### PR DESCRIPTION
**Pull request by aka001**
Inspired from the pull request: https://github.com/asmeurer/sympy/pull/57
@asmeurer Please review this pull request.

### CODE REVIEW

**Comment by pelegm** [comment]
Looks ok to me. Perhaps we can think about a more systematic way to achieve this goal?

**Comment by skirpichev** [comment]
> Perhaps we can think about a more systematic way to achieve this goal?

Could you explain for me this "goal".  I don't see clear reasons for new tests from this pr.

**Comment by pelegm** [comment]
Actually I can't, not really. I guess it is simply "testing assumptions" properly.

**Comment by aka001** [comment]
@skirpichev @pelegm Thanks for the reply.
In this PR https://github.com/asmeurer/sympy/pull/57 there were also facts added along with the tests for multiplication and addition(which I think are correct).
I used grep to searching for the pattern in the repo but didn't find any fact variable which contains all these facts.
Hence I just wrote the tests for the facts.

**Comment by skirpichev** [comment]
Please remove redundant test first and explain why we should have remaining test.

**Comment by aka001** [comment]
@skirpichev 
I have removed the redundant test: Q.even(x+y+z), Q.even(x) & Q.even(y) & Q.even(z) is true
(since there is already test for Q.even(x+y), Q.even(x) & Q.even(y) is true, and this test also means to conclude the same result).
For the test:
1. assert ask(Q.odd(x+y+z), Q.odd(x) & Q.even(y) & Q.even(z)) is True
Since y and z are even => (y+z) is also even.
Since x is even => x+(y+z) => odd+ even = odd. Hence it's true.

2. assert ask(Q.odd(2*x+1), Q.integer(x)) is True
2*x is even and 2*x+1 => even + odd = odd = True. 
Please correct me if I am wrong.

**Comment by skirpichev** [comment]
> I have removed the redundant test:

And add another...

> assert ask(Q.odd(x+y+z), Q.odd(x) & Q.even(y) & Q.even(z)) is True.
> Since y and z are even => (y+z) is also even.

I'm not about the truth of such a statement.  It's clear, we can have uncountable number of such valid statements.  Should we try to add all of them?

**Comment by aka001** [comment]
I am sorry, I didn't see that assert ask(Q.odd(2*x+1), Q.integer(x)) is True is already present.
According to me, ((Q.odd(x+y+z), Q.odd(x) & Q.even(y) & Q.even(z)) is True.), needn't be added since it finally leads to odd+even+even=odd+even(which is already present).
IMHO, the test:
    ask(Q.odd(x + y), Q.even(x) & Q.even(y)) is False
can be added since no such case is covered.

**Comment by skirpichev** [comment]
On Sun, Jan 11, 2015 at 09:38:32AM -0800, Akash Agrawall wrote:
>    ask(Q.odd(x + y), Q.even(x) & Q.even(y)) is False
>    can be added since no such case is covered.

Can you explain why do you think so?

**Comment by aka001** [comment]
In the file: sympy/assumptions/tests/test_query.py
in test_odd()
ask(Q.odd(x+y)) the cases covered are:
Q.odd(x) & Q.odd(y) and
Q.odd(x) & Q.even(y). 
There is no case for Q.even(x) & Q.even(y), so I thought we can add this.

**Comment by skirpichev** [comment]
> There is no case for Q.even(x) & Q.even(y)

There is no literally such a case.

**Pull request closed without merging**
