### PR TITLE
Removed #doctest: +SKIP

### PR DESCRIPTION
**Pull request by ghost**
Removed #doctest: +SKIP

#### References to other Issues or PRs
Helps #6959 

#### Brief description of what is fixed or changed
Removed #doctest: +SKIP in `stats/rv.py`

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by faze-geek** [comment]
Not sure about the motivation behind this pr but seems straight forward . Should go in !

**Comment by oscargus** [comment]
Can you please merge the commits? 10 for two lines is a bit much...

**Comment by KuldeepBorkar** [comment]
> Can you please merge the commits? 10 for two lines is a bit much...

@oscargus  I was also trying to do the same thing ; ) 
But I don't know how to clean my commit history,

I tried to rebase but it shows just 1 commit and not the others,
I am stuck with "How to remove the old commits"

**Comment by anutosh491** [comment]
Maybe you can try squashing if you can approach it that way ?

**Comment by KuldeepBorkar** [comment]
> Maybe you can try squashing if you can approach it that way ?

I messed up everything now ; )
I am just closing this PR here maybe I need to learn moreover git first

**Comment by eagleoflqj** [comment]
Hi! When you are the only one that is working on a branch, it's generally safe to use `git push -f`, so you can always rebase to master instead of merging master, and use `git commit --amend --no-edit` to do small changes. Try `git config --global pull.ff only` to avoid unwanted merge commit when `git pull`.
For this time, since the change is small and CI passed, you can
1. checkout from the latest master branch locally
2. copy and paste your changes
3. commit, push and make another pull request

**Comment by oscargus** [comment]
An option is to do
* `git rebase -i master`
* An editor will open where you can change status of some commits to `fixup`, in that way they will be absorbed by others (keep the ones with "good" commit messages).
* Do `git push -f` as mentioned above (possible with branch name etc, but git will tell you if you need it).

**Comment by oscargus** [comment]
Oh yeah, now I see that you (probably) made a merge commit. Maybe then the best thing is try to remember what you changed and redo that change in a clean PR.

**Pull request closed without merging**
