### PR TITLE
Solveset without specifying any independent variable

### PR DESCRIPTION
**Pull request by KTaruneshwar**

### CODE REVIEW

**Comment by czgdp1807** [comment]
@jksuom @smichr What do you think on this PR?

**Comment by jksuom** [comment]
There is no example or test case to show how this could be useful. I would expect that the user usually knows which variable should be solved.

**Comment by smichr** [comment]
One might want to see all the different arrangements of `F=ma`, for example. But it would not be too hard to just do that as 
```python
for s in expr.free_symbols:
    print(s, solveset(expr, s))
```
The approach of `solve` is to just pick the first one that can be solved.

Please explain more about the use case.

**Comment by czgdp1807** [comment]
Closing this as of now as the use case is not very critical. Thanks for your contributions.

**Pull request closed without merging**
