### PR TITLE
Combinatorics: Cycle is not a Basic instance and is mutable

### LINKED ISSUE #17661: Cycle is not a Basic instance and is mutable
I'm not sure whether this is a problem or what the fix should be but I find this surprising. The Cycle class from combinatorics is a subclass of dict rather than Basic and is therefore mutable. It also implements `__missing__` which means it can be unintentionally mutated:
```julia
In [1]: from sympy.combinatorics.permutations import Cycle                                               

In [2]: c1 = Cycle(1, 2)                                                                                 

In [3]: c2 = Cycle(1, 2)                                                                                 

In [4]: c1 == c2                                                                                         
Out[4]: True

In [5]: srepr(c1)                                                                                        
Out[5]: 'Cycle(1, 2)'

In [6]: c1 == c2                                                                                         
Out[6]: False

In [7]: c1.keys()                                                                                        
Out[7]: dict_keys([1, 2, 0])

In [8]: c2.keys()                                                                                        
Out[8]: dict_keys([1, 2])

In [9]: c2                                                                                               
Out[9]: Cycle(1, 2)

In [10]: c1                                                                                              
Out[10]: Cycle(1, 2)
```
I don't really know what this class is used for: it isn't used outside of the permutations module as far as I can tell but it does have e.g. printing support which suggests it is supposed to be seen by users.

Maybe this should be made a proper immutable Basic subclass.

### PR DESCRIPTION
**Pull request by sachin-4099**
Fixes #17661 

The Cycle class from combinatorics was a subclass of dict rather than Basic and was therefore mutable. It also implemented __missing__ which meant it can be unintentionally mutated:

**Before the Change:**

In [1]: from sympy.combinatorics.permutations import Cycle                                               

In [2]: c1 = Cycle(1, 2)                                                                                 

In [3]: c2 = Cycle(1, 2)                                                                                 

In [4]: c1 == c2                                                                                         
Out[4]: True

In [5]: srepr(c1)                                                                                        
Out[5]: 'Cycle(1, 2)'

**In [6]: c1 == c2                                                                                         
Out[6]: False**

**In [7]: c1.keys()                                                                                        
Out[7]: dict_keys([1, 2, 0])**

In [8]: c2.keys()                                                                                        
Out[8]: dict_keys([1, 2])

In [9]: c2                                                                                               
Out[9]: Cycle(1, 2)

In [10]: c1                                                                                              
Out[10]: Cycle(1, 2)

**After the Change:**

In [1]: from sympy.combinatorics.permutations import Cycle

In [2]: c1 = Cycle(1, 2)

In [3]: c2 = Cycle(1, 2)

In [4]: c1 == c2
Out[4]: True

In [5]: srepr(c1)
Out[5]: 'Cycle(1, 2)'

**In [6]: c1 == c2
Out[6]: True**

**In [7]: c1.keys()
Out[7]: dict_keys([1, 2])**

In [8]: c2.keys()
Out[8]: dict_keys([1, 2])

In [9]: c2
Out[9]: Cycle(1, 2)

In [10]: c1
Out[10]: Cycle(1, 2)

Now, Cycle can be regarded as a sparse representation of a permutation. It is made unique by omitting all keys that coincide with their values.

* combinatorics
   * Cycle class is no longer mutable and can be regarded as a sparse representation of a permutation

### CODE REVIEW

**Comment by jksuom** [comment]
Can you add a test showing the new behaviour.

**Comment by sachin-4099** [comment]
Please review @jksuom @smichr @oscarbenjamin. 
If any changes are required please suggest.

**Comment by sachin-4099** [comment]
Please review @jksuom @smichr @oscarbenjamin.
If any changes are required please suggest, otherwise the PR is ready to be merged.
The required testcase showing the behaviour has been added.

**Comment by jksuom** [comment]
Thanks, this looks good to me.

**Pull request merged**
