### PR TITLE
When p is an integer, Mod(p, 1) is zero.

### PR DESCRIPTION
**Pull request by drufat**
When p is an integer, Mod(p, 1) is zero.

### CODE REVIEW

**Comment by leosartaj** [comment]
In master

```
>>> p = Symbol('p', integer=True)
>>> Mod(p, 1)
0
```
This appears to work correctly.

**Comment by drufat** [comment]
You are right. I left only the test.

**Comment by leosartaj** [comment]
This case is already take care by [this](https://github.com/drufat/sympy/blob/mod_int_1/sympy/core/tests/test_arit.py#L1585) line.

``Mod(4*i, 4)`` simplifies to ``4*Mod(i, 1)`` which evaluates to ``0``.

IMO there is not really a need to add this test.

**Comment by drufat** [comment]
Alright. I am closing this pull request.

**Pull request closed without merging**
