### PR TITLE
Fix a typo in sympy.this

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by gxyd** [comment]
It could be some valid error https://travis-ci.org/sympy/sympy/jobs/289209025

**Comment by aktech** [comment]
Why are we removing `rot13` as of now, without having a new encryption?

**Comment by asmeurer** [comment]
Yeah I'm working on the Travis issue.

**Comment by smichr** [comment]
I will post some suggestions for a SymPy-ish encryption.

**Comment by asmeurer** [comment]
Thanks. I was thinking maybe finding an interpolating polynomial (like for `[ord(i) for i in s]`), but it seems that `interpolate` is too slow and I wasn't able to compute it. Granted, it isn't a big deal if the "encryption" is slow as long as the "description" (importing) is fast.

**Comment by ylemkimon** [comment]
Restarted `TEST_SPHINX`.

**Comment by smichr** [comment]
The following takes about 2 seconds on my old machine:

```python
from sympy import factorint, S
from sympy.combinatorics import Permutation
from sympy.abc import x
kv = S("""
2378815221410795426435212912670939967415259800290077619871082251005320
4313370717191102735092248266278517257224847374852658132275677916667213
3523789670195158349608606735775554337147647782444674777226355644176393
27999113
""")
m = [(f, _) for f, _ in factorint(kv).items()]
vk = S("""
1523100013998573940860468907567216015289583573636861722994405774489302
6618846990823517684817780996061502639617301302959589961094041381521350
5559895132429347072112515921246567850413692577849781773027869698668005
0697544053539334798988496026268629380762842947081520265547831470119304
8049403062794992027631189667507860895985997279854789585085118996167850
2836051131257190992573474185275499784219278554814191363611168923904103
9629695753443113253495876455257729066317993227673474948080349192287221
2001430929272486856740985275005948198006836006372997407771188446145081
4496531891894258260635591772924612996575888246297836303710937500000000
0000000000000000000000000000000
""")
m += [(_, f) for f, _ in factorint(vk).items()]
i = S("""
46995738679758407253582526408277430599*x**20/3725985841653990850695001
5132260172638972175187968000000000 - 124868907537513843122268248789868
144965567*x**19/549105864939169675907679805217338258500216624906240000
00000 + 1856294644494515652297193073093650770826928639*x**18/958674239
493797410643525683461799971310966436895129600000000 - 3851016920279408
8821252134954432708230625275823*x**17/37208817514599442878858302782763
925827137966728806400000000 + 1057461743365027467734618303132534624032
6514834609597*x**16/27162436785657593301566561031417665853810715712028
672000000000 - 1151009073890153821663363540075635593171049976383293*x*
*15/10511778941817954064073746529186403194199193387008000000000 + 1297
34145260248893151152521453214112784093130276242988611*x**14/5432487357
131518660313312206283533170762143142405734400000000 - 7176934045008940
354924378109381758831451471048049932077*x**13/173635862682660941625185
7726278563766491202794291200000000 + 263247610574075535714372863439878
0125716478812255334167239*x**12/45686987192740962045693924138962209890
91284320256000000000 - 44056786287026509925425009347010770934670279566
973043422101*x**11/674876684199403530649139361742637295115551473664000
000000 + 4505824173069001980935347698005136989138460927328020427926283
*x**10/746220790814769046746334094269716094884909772308480000000 - 174
72100030275273518836019365919213417103619756990476809824793*x**9/38295
788384922165155603655864281617772685985382400000000 + 1616612080033037
9346329144674256636052204091531510553686094717473*x**8/575865773101628
080511502735571100446357927317504000000000 - 8890659684576415239465203
80321090329321636342972123763983163488358739*x**7/63661961216384984300
5466274173851543448688649500672000000000 + 883267307832276865440220897
590700470608270020994384500592943293963941*x**6/1591549030409624607513
6656854346288586217216237516800000000 - 241458180348220063642411008100
09764614677587940350646069303539569053*x**5/13960956407101970241347944
609075691742295803717120000000 + 3014138696350636032952781471859039128
73571120254201414746015439821*x**4/73316244260623945435492246426876214
23538426496000000 - 28369158582392814435661457942154578482544867801466
8598325845923231*x**3/397211997207153990095254488727819920790087257600
000 + 161876583906764016504697390618331248561230156113914447963082381*
x**2/19146054650932337912481799904120244281234880000 - 152398365504726
60287969645073149321002601382715912070219*x/25438610362985237400419272
0429064988000 + 15451699633724617344105431715401683254112861786/832044
62941407556637122714545""")
m += [(_, i.subs(x, _)) for _ in
(10, 40, 44, 66, 68, 80, 85, 90, 98, 100, 102, 104, 105, 110, 111,
112, 116, 117, 118, 119, 121)]
p = Permutation([113, 228, 172, 14, 117, 173, 291, 15, 318, 217, 16,
111, 490, 271, 105, 491, 0, 1, 116, 292, 174, 481, 118, 264, 468, 119,
412, 175, 163, 17, 242, 381, 18, 150, 176, 413, 414, 177, 352, 19,
415, 229, 120, 293, 20, 178, 482, 121, 265, 469, 122, 416, 179, 164,
86, 2, 114, 230, 180, 21, 470, 382, 181, 353, 22, 243, 294, 417, 182,
354, 218, 123, 158, 183, 23, 272, 124, 418, 419, 184, 355, 383, 87, 3,
106, 356, 244, 295, 420, 245, 296, 223, 24, 273, 125, 421, 422, 185,
357, 384, 88, 4, 107, 471, 358, 186, 25, 108, 492, 423, 231, 319, 297,
26, 159, 126, 298, 27, 151, 187, 28, 219, 127, 385, 424, 29, 188, 299,
320, 472, 224, 232, 89, 5, 104, 220, 30, 246, 425, 81, 386, 31, 426,
321, 322, 32, 387, 266, 323, 485, 85, 33, 247, 427, 82, 388, 34, 83,
345, 359, 324, 152, 128, 153, 267, 493, 84, 35, 494, 325, 473, 360,
36, 221, 129, 474, 268, 428, 90, 6, 103, 326, 160, 475, 274, 189, 300,
429, 130, 430, 248, 327, 301, 37, 275, 131, 431, 432, 190, 361, 389,
91, 7, 100, 328, 362, 363, 191, 161, 433, 302, 192, 390, 391, 38, 249,
392, 39, 276, 329, 364, 193, 40, 250, 277, 346, 330, 365, 434, 132,
303, 435, 41, 436, 233, 133, 304, 42, 393, 347, 194, 195, 165, 92, 8,
109, 476, 394, 234, 43, 251, 437, 44, 252, 305, 45, 306, 331, 486, 46,
134, 307, 166, 47, 253, 278, 348, 366, 332, 483, 196, 48, 477, 349,
333, 308, 49, 254, 438, 50, 269, 135, 439, 197, 367, 93, 9, 101, 334,
484, 198, 368, 136, 225, 199, 51, 154, 495, 52, 440, 200, 395, 441,
255, 309, 226, 53, 279, 137, 442, 443, 201, 369, 396, 94, 10, 112,
280, 138, 370, 444, 54, 445, 202, 397, 446, 398, 55, 139, 371, 203,
56, 155, 204, 447, 448, 205, 372, 57, 449, 235, 140, 310, 58, 373,
141, 311, 167, 335, 281, 59, 450, 206, 399, 451, 400, 95, 11, 99, 478,
452, 60, 374, 142, 312, 168, 336, 282, 61, 453, 207, 401, 454, 402,
62, 403, 337, 283, 208, 455, 256, 284, 209, 404, 63, 222, 257, 313,
169, 64, 487, 236, 143, 456, 65, 496, 338, 479, 375, 66, 405, 285,
144, 376, 457, 210, 406, 458, 67, 459, 211, 407, 460, 68, 286, 258,
408, 409, 212, 170, 96, 12, 115, 237, 213, 69, 110, 497, 461, 238,
339, 314, 70, 488, 145, 498, 71, 259, 410, 72, 350, 377, 340, 156,
146, 157, 270, 499, 73, 462, 239, 214, 74, 378, 260, 227, 240, 463,
75, 489, 147, 500, 97, 13, 102, 341, 287, 288, 480, 315, 261, 464,
501, 76, 262, 411, 77, 289, 342, 379, 215, 78, 263, 290, 351, 343,
380, 465, 148, 316, 466, 79, 467, 241, 149, 317, 80, 162, 344, 171,
216, 98])
a = ''.join([chr(i)*j for i, j in sorted(m)])
print(''.join(p(a)))
```

**Comment by smichr** [comment]
It takes about a second more when defining `p` like this:
```
p = Permutation(range(502)) + S("""69352994545726419831775263410278524
3876434402943301299722229447442254246020734838858796663802699447046158
0068037934736078732931926828160008975120087758273693927977776400849362
6092590525195272613182395728283477975470182915360565707171009277384242
0817233003941515469902475554650185601352751632612401070444548954444141
5256301823049484020815466860603580600961715372887406023020555730932896
4609066535299445178328323839392458601218227000091666422186510427085869
2121274507719043270884726089771652851884913177038356111765846185768906
3529543320543150552308993207482785717395229225558070258292248574896288
1757513452277306425804544079958096840975295588907004019092441949985817
0635971828814431799350932010773106969373871075534563258939412935066126
4264311741114866934315304089324839700917853111724146974541225735574679
6845415874067629319111672040835734728832310407449797918812130674795626
8896866480321919822342663012498158431337474744431546292138909710750986
1340531099892381792142138453449908297948811194950706445400013944897988
7132871041882880339126191873785838390760142090300036397101963045156151
596990065860495000535909262973534576587977872560411165""")
```

**Comment by asmeurer** [comment]
That's not particularly transparent. 

How about something simple for each line, using a different thing for each line (that is, for each term in `[[ord(i) for i in j] for j in s.splitlines()]`). 

Some thoughts:

- `p = interpolate(l, x)` (translated back with `[p.subs(x, i) for i in range(1, len(l)+1)]`)
- `L = map(prime, l)` (translated back with `map(primepi, L)`)
- `Permutation.from_sequence(l)` (translated back with `Permutation.from_sequence(sorted(l))`) (maybe there is a better Permutation one. Unfortunately, each line has duplicate letters, so we can't interpret as a permutation directly)
- Use `nsimplify` on `'.' + ''.join(["%03d" % i for i in j])` to get some interesting number in terms of some constants like `pi`, `E` and so on (I'm having trouble getting the `tolerance` to be set low enough to give all the digits back with `evalf`). 
- `L, U, _ = Matrix(a, b, l).LUdecompose()`, where `a*b = len(l)` (translated back with `list(L*U)`). This seems to work well enough for the "If it's too slow..." line, which has 45=5*9 characters. 
- ???

For the empty line, maybe a set that reduces to the empty set, like `imageset(x, (2*x + 1)**2, S.Integers).intersect(x, 8*x + 3, S.Integers)`. Or maybe something like `solveset(x**2 + 1, x, S.Reals)`. 

It would be cool to have all the major submodules represented somehow.

**Comment by asmeurer** [comment]
For integration, maybe something like this `diff(Poly(l, x)*exp(x))` (`Poly(integrate(p))*exp(-x), x).coeffs())`).

For geometry, maybe something involving the pairwise points (for one of the lines w/ an even number of characters)? 

Also, it occurs to me that if we are going to do all this we should add some tests for it.

**Comment by asmeurer** [comment]
For the printing one we could do something like

```py
from sympy.printing.str import StrPrinter

class ThisStrPrinter(StrPrinter):
    def _print_Mul(self, expr):
        return ''.join([self._print(i) for i in expr.args])

    def _print_Symbol(self, expr):
        return chr(int(expr.name))

    def _print_Pow(self, expr):
        return self._print(expr.base)*expr.exp

ThisStrPrinter().doprint(Mul(*[Symbol(str(i), commutative=False) for i in l[4]]))
```

(where `l = [[ord(i) for i in j] for j in s.splitlines()]`)

**Comment by asmeurer** [comment]
(except the `Mul(*[Symbol(str(i), commutative=False) for i in l[4]]` would be written out explicitly obviously)

**Comment by smichr** [comment]
> It would be cool to have all the major submodules represented somehow.

I was thinking the same. If you don't mind leaving this open I can continue working on it.

**Comment by asmeurer** [comment]
I'm going to merge this for now. If you want to discuss how to be more clever with it, please open an issue or pull request.

**Pull request merged**
