### PR TITLE
fixed a bug in `rs_nth_root` in `ring_series`

### PR DESCRIPTION
**Pull request by pernici**

### CODE REVIEW

**Comment by shivamvats** [comment]
Looks great
+1

**Comment by shivamvats** [comment]
@pernici Do you want to add anything else to this?

**Comment by pernici** [comment]
> Do you want to add anything else to this?

No

**Comment by shivamvats** [comment]
@certik We should merge this if you are fine with it.

**Comment by certik** [comment]
This looks good, thanks!

**Pull request merged**
