### PR TITLE
matrices: trace of MatAdd

### LINKED ISSUE #9028: Trace of MatAdd can fail with error: "mix of Matrix and Scalar symbols"
````
In [18]: X = Matrix([[1, 2], [3, 4]])

In [19]: q = MatAdd(X, 2*X)

In [20]: Trace(q).doit(deep=False)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-038504dfa7f5> in <module>()
----> 1 Trace(q).doit(deep=False)

/home/cbm/work/octsympy/octsympy.git/inst/sympy/matrices/expressions/trace.pyc in doit(self, **kwargs)
     42             arg = self.arg
     43         try:
---> 44             return arg._eval_trace()
     45         except (AttributeError, NotImplementedError):
     46             return Trace(arg)

/home/cbm/work/octsympy/octsympy.git/inst/sympy/matrices/expressions/matadd.pyc in _eval_trace(self)
     52     def _eval_trace(self):
     53         from trace import Trace
---> 54         return MatAdd(*[Trace(arg) for arg in self.args]).doit()
     55 
     56     def doit(self, **kwargs):

/home/cbm/work/octsympy/octsympy.git/inst/sympy/matrices/expressions/matadd.pyc in __new__(cls, *args, **kwargs)
     34         obj = Basic.__new__(cls, *args)
     35         if check:
---> 36             validate(*args)
     37         return obj
     38 

/home/cbm/work/octsympy/octsympy.git/inst/sympy/matrices/expressions/matadd.pyc in validate(*args)
     64 def validate(*args):
     65     if not all(arg.is_Matrix for arg in args):
---> 66         raise TypeError("Mix of Matrix and Scalar symbols")
     67 
     68     A = args[0]

TypeError: Mix of Matrix and Scalar symbols
````

I will look into this.

### PR DESCRIPTION
**Pull request by cbm755**
```
matrices: trace of MatAdd

Earlier trace(MatAdd(X, Y)) was failing with type error
'mix of Matrix and Scalar symbols'. This was because
trace(MatAdd(X, Y)) evaluated to MatAdd(trace(X), trace(Y))
and since validate function would reject trace(X) as Matrix
object it was throwing an exception.

It has been fixed by evaluating trace(MatAdd(X, Y)) to
trace(Z) where Z is what we have after evaluating
MatAdd(X, Y).

Fixes #9028.  Adds tests.
```

This is a squash of the work of @lokeshh in #9031.  It looks like the squashed commit remains attributed @lokeshh, so I'm +1 for merging this.  But as it also has some tests added by me, someone else should +1 one before I merge.

### CODE REVIEW

**Comment by lokeshh** [comment]
There needs to be little change in the summary.

Instead of 
> It has been fixed by evaluating trace(MatAdd(X, Y)) to
trace(Z) where Z is what we have after evaluating
MatAdd(X, Y).

it should be

> It has been fixed by evaluating trace(MatAdd(X, Y)) to
Add(trace(X), trace(Y)).

**Comment by cbm755** [comment]
Ok, I rewrote your commit msg.

I'm still +1 for merging this.

**Comment by cbm755** [comment]
@lokeshh  now that #9072 is in, do you want to remove the duplicated test here?  (or prefer I do?)

**Comment by lokeshh** [comment]
I might mess things up and I don't know how to do it either. So, I prefer you do it please. I will learn from this.

**Comment by cbm755** [comment]
Merged with master after fix for #9043.  This is @lokeshh's fix for #9028 and some other tests from me.  I'm +1, but needs second review.

**Comment by kevinventullo** [comment]
This looks great to me. +1

**Comment by cbm755** [comment]
Ok, I will merge in 24 hours.

**Pull request merged**
