### PR TITLE
LaTeX and pretty printing for symbolic statistics

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Related to #22654 

#### Brief description of what is fixed or changed
`Covariance`, `Expectation`, `Probability` and `Variance` now have dedicated LaTex and pretty printing.
image
image

#### Other comments
Also changed so that a random domain prints using the `\in` symbol rather than the text `in`.

Added some rudimentary ASCII pretty-printing option for `Differential` (`d`), `WedgeProduct` (`/\`), and `TensorProduct` (`.*`). The last is a bit doubtful, but probably better than an error...

#### Release Notes

* printing
   * Dedicated LaTeX and pretty printing for `Covariance`, `Expectation`, `Probability` and `Variance`.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
See here for the test failure: https://github.com/sympy/sympy/pull/22657#issuecomment-992342721

**Comment by oscarbenjamin** [comment]
Looks good to me

**Comment by bjodah** [comment]
I think "E" should be written either using `\operatorname` or simply `{\rm E}` since it's not a variable here, would you agree?

**Comment by oscargus** [comment]
> I think "E" should be written either using `\operatorname` or simply `{\rm E}` since it's not a variable here, would you agree?

Yes, you are correct. I also changed P. Used `\operatorname` (`\rm` is TeX and should not be used, ever, as far as I understand it).

**Comment by oscargus** [comment]
Merging this and restarting the ones that builds on it.

**Pull request merged**
