### PR TITLE
[Retracted] Remove sympy.abc imports in assumptions

### PR DESCRIPTION
**Pull request by toolforger**
This is a toe-in-the-water commit to apply
https://github.com/sympy/sympy/wiki/Idioms-and-Antipatterns#creating-symbols

If this is +1, I'll apply this to the other SymPy modules.

### CODE REVIEW

**Comment by debugger22** [comment]
From the discussions on the mailing list, it looks like it should be replaced. I personally like `sympy.abc` method.

If we are concerned about the gotcha `from sympy.abc import *` will pollute the namespace, we can overcome this by introducing `__all__ = []` in `sympy/abc.py`.
It will result in following behavior:
```
In [1]: from sympy.abc import *

In [2]: a
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-60b725f10c9c> in <module>()
----> 1 a

NameError: name 'a' is not defined

In [3]: from sympy.abc import a

In [4]: a
Out[4]: a
```

**Comment by toolforger** [comment]
@debugger22 I like that approach.
However, it seems that people are doing `from sympy.abc import *; from sympy import *`, which would then break (e.g. as reported by @smichr in #9218).

**Comment by debugger22** [comment]
> However, it seems that people are doing from sympy.abc import *; from sympy import *, which would then break (e.g. as reported by @smichr in #9218).

True that but I think there should be very little populace(people who know sympy very well) who would do that.

I'm +0.5 to this change.

**Comment by toolforger** [comment]
It seems that importing from `sympy.abc` is fine, so I'm retracting this in favor of #9282.

**Pull request closed without merging**
