### PR TITLE
13483

### LINKED ISSUE #13483: lambdify doctests are not run
The `doctest_depends_on` decorator for `lambdify` is written incorrectly, and the doctests are not run. It uses `modules=('numpy')` instead of `modules=('numpy',)`. So you get, with `./bin/doctest -v lambdify`

```
sympy/utilities/lambdify.py[4]
sympy.utilities.lambdify.implemented_function ok
sympy.utilities.lambdify._imp_namespace ok
sympy.utilities.lambdify.lambdastr ok
Could not import None s
```

We should also check if other doctests have the same problem.

### PR DESCRIPTION
**Pull request by cchaffin2013**
line 156 @doctest_depends_on(modules=('numpy',)) added the comma after numpy, lambdify doctests now run

Fixes #13483

### CODE REVIEW

**Comment by gxyd** [comment]
For PR title see this: https://github.com/sympy/sympy/wiki/Development-workflow#writing-pull-request-title-and-description

See this for commit message: https://github.com/sympy/sympy/wiki/Development-workflow#writing-commit-messages

Just have one commit which fixes this issue. A commit message like "0" isn't informative at all.

**Comment by gxyd** [comment]
Something wrong has happened with travis here? It doesn't even show the button to see the status.

**Comment by ylemkimon** [comment]
Closed and reopened PR to trigger the Travis build.

**Comment by gxyd** [comment]
There are failing tests here. Also I think it is better if you take a look at this comment by @asmeurer  https://github.com/sympy/sympy/issues/13483#issuecomment-345063448

**Comment by czgdp1807** [comment]
The associated issue is fixed by https://github.com/sympy/sympy/pull/13485 , so closing this PR. Thanks for the contribution.

**Pull request closed without merging**
