### PR TITLE
Cleaned up in geometry

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed
Adds explicit arguments to geometry.polygon and geometry.util.convex_hull according to #14030

#### Release Notes

* geometry
   * Added explicit optional parameters to Polygon and convex_hull

### CODE REVIEW

**Comment by oscargus** [comment]
This will not work while keeping 2.7 compatibility. If there is a flag related to "dropping Python 2 support", it can be saved until that...

**Comment by asmeurer** [comment]
I made a new label for it. We plan to drop support in a year, so we can revisit this then. Actually when we drop Python 2 I would like to move a lot of the function signatures in SymPy to use keyword-only arguments.

**Comment by czgdp1807** [comment]
@asmeurer I think we are dropping Python 2 support in SymPy 1.6, so it's time to decide upon this PR.

**Comment by sylee957** [comment]
This still gets syntax error in the test. I see py27 import test is still there

**Comment by oscarbenjamin** [comment]
I'm sure I fixed that in .travis.yml #18244 and the fix was supposed to be carried over to #17968.

**Comment by czgdp1807** [comment]
What all needs to be done to complete this PR?

**Comment by oscarbenjamin** [comment]
I think the tests will pass now

**Pull request merged**
