### PR TITLE
Added test cases for syntax error in lambdify

### LINKED ISSUE #13881: test case for syntax error on lambdify
See this issue https://github.com/sympy/sympy/issues/11044 . That issue was fixed in PR https://github.com/sympy/sympy/pull/11566. Though no test case was added for the `lambdify`.

#### What needs to be done?

Add test case that this works just fine:
```python
>>> from sympy import MatrixSymbol, lambdify
>>> x = MatrixSymbol('x', 3, 1)
>>> f = lambdify(x, x.T*x)
```

Test case needs to be added in appropriate file

### PR DESCRIPTION
**Pull request by arighnac**
Fixes #13881 
Closes #13934 .

This PR adds tests for syntax error in `test_lambdify.py`.

@gxyd, @smichr , @jksuom please review.

### CODE REVIEW

**Comment by gxyd** [comment]
Thanks for the PR. Though you should look for the reference PR's on the issue as well, to see if a PR has already been submitted for it. See https://github.com/sympy/sympy/pull/13934 .

I've marked the PR as 'duplicate' for now. Let's wait if #13934 fixes it or not.

**Comment by ArighnaIITG** [comment]
Great.!!
Should I close the issue?

**Comment by gxyd** [comment]
No need to close this PR right now. Let's wait to see if the other PR actually gets addressed. I've marked this PR 'duplicate' as a reminder.

**Comment by ArighnaIITG** [comment]
@gxyd , Has the concerned issue been fixed? It seems there was some existing problems with Circle CI builds.

**Comment by gxyd** [comment]
The problem persists. See https://github.com/sympy/sympy/issues/13984

**Comment by gxyd** [comment]
I haven't given a look at that issue. But I don't think anyone is currently working on the referenced issue (I'm not talking about the issue this PR fixes).

**Pull request closed without merging**
