### PR TITLE
Edited the link provided in coupled_cluster.py

### PR DESCRIPTION
**Pull request by mamakancha**
I tried multiple times, but the link mentioned was not working So I have deleted the previous link. And included a new link to a lecture series on Coupled Cluster Theory. 
Any suggestions to other good resources are appreciated :)

### CODE REVIEW

**Comment by mamakancha** [comment]
@jksuom Could you let me know what is it that I am missing here? What is causing the problem here?

**Comment by jksuom** [comment]
It looks like travis is having some problems. I've restarted the failing job.

**Comment by mamakancha** [comment]
@jksuom Thanks! The checks have passed. Kindly review :)

**Comment by jksuom** [comment]
There is another reference to the broken link in the main code.

**Comment by mamakancha** [comment]
Thanks for pointing out! Submitted a new Pull Request for the same!

**Comment by jksuom** [comment]
There is no need for a new PR. New commits can be added to here.

**Pull request closed without merging**
