### PR TITLE
[matrices] binary operators

### PR DESCRIPTION
**Pull request by yukoba**
1. Add Matrix + scalar. There is Matrix \* scalar, but Matrix + scalar was missing.
2. Add <, <=, >, >=, &, |, ^ to Matrix.

### CODE REVIEW

**Comment by moorepants** [comment]
I don't think Matrix + scalar is a valid mathematical operation. Why do you think it is?

Is this just a shortcut for Matrix + eye * scalar?

**Comment by jksuom** [comment]
> I don't think Matrix + scalar is a valid mathematical operation.

I concur.

> Is this just a shortcut for Matrix + eye * scalar?

The scalar is added to every entry of a matrix, not just to the diagonal entries. This is a valid operation for multiplication but addition does not make sense.

**Comment by moorepants** [comment]
> The scalar is added to every entry of a matrix, not just to the diagonal entries.

Oh yeah, that was a mistake on my part. I meant to write:

Matrx + ones * scalar

**Comment by yukoba** [comment]
NumPy can do this, and I think it is convenient.
Also Mathematica and MATLAB can do the same things too.

**Comment by moorepants** [comment]
NumPy has a generic ndarray object which defaults to elementwise operations. These operations make sense for that object but SymPy has a mathematical Matrix object in which these do no make sense. NumPy arrays and SymPy matrices are distinctly different. You could create a SymPy ndarray that behaves more like a NumPy array if you want.

**Pull request closed without merging**
