### PR TITLE
Add Pastafarianist to AUTHORS/aboutus. Welcome to SymPy!

### PR DESCRIPTION
**Pull request by aktech**
@Pastafarianist  Please verify details.

### CODE REVIEW

**Comment by Pastafarianist** [comment]
Wow, this is surprising! Being listed in `authors` for correcting a typo is an overkill, I think, but since it seems to be your standard policy, I don't mind.

My email address for talking to people is `pastafariant@gmail.com`, the one you listed is for registration. Could you change that?

**Comment by aktech** [comment]
@Pastafarianist 
We appreciate each & every patch, doesn't matter small or large. Welcome to SymPy! :)

**Comment by aktech** [comment]
> My email address for talking to people is pastafariant@gmail.com, the one you listed is for registration. Could you change that?

Yes, I have changed that. Please have a look at other details.

**Comment by Pastafarianist** [comment]
Actually, you know, I've changed my mind. It's too small.

**Comment by aktech** [comment]
> Actually, you know, I've changed my mind. It's too small.

Alright, you don't want to be mentioned in the `AUTHORS`?

**Comment by Pastafarianist** [comment]
Only when I do something bigger than correcting a typo I accidentally found. I hope you understand :)

**Comment by aktech** [comment]
@Pastafarianist 
No problem, as you like, I am closing this for now.

**Pull request closed without merging**
