### PR TITLE
Fixes issue #14987

### PR DESCRIPTION
**Pull request by czgdp1807**
I have added a mechanism to check if the equations passed
to linear_eq_to_matrix method are linear or not. If they
are not linear then appropriate error messages are raised.

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
Several comments on this over at https://github.com/sympy/sympy/pull/14999, which I think has the actual changes.

**Comment by asmeurer** [comment]
@czgdp1807 please avoid opening multiple pull requests for the same change. This pollutes the pull request list and makes reviews harder. You can push new commits to the same branch and the pull request will be updated automatically.

**Comment by czgdp1807** [comment]
I apologize for opening multiple pull requests for the same issue. I was unaware about release notes and hence the bot gave an error. 
I am a learner. I will surely try not to repeat the mistake again.
What should I do know. Should I reopen #14999?
Please help me.

**Comment by Yathartha22** [comment]
> What should I do know. Should I reopen #14999?

Let it be as it is. Start working on this PR (this branch itself), but address @asmeurer [comments](https://github.com/sympy/sympy/pull/14999#issuecomment-408983569)

Also edit the description accordingly for `sympy-bot` check to be passed.

**Comment by czgdp1807** [comment]
@Yathartha22 Actually this PR doesn't shows the changes I have made for solving the issue. 
I apologize for the random actions of mine while making the PR for solving the issue. I was unaware of the release notes and hence got confused. I have reopened the [PR](https://github.com/sympy/sympy/pull/14999). 
Really sorry for the troubles. :-(
I will try my best not to make such mistakes again. :-)

**Comment by asmeurer** [comment]
The release notes bot had a bug, which has since been fixed. It's still very new, so if it does something that doesn't make sense, let us know (even if it's not a bug we want to improve the messaging to new contributors).

The mistakes are fine, we understand that new contributors have to learn how things work. The main thing is to not open a bunch of pull requests, because that pollutes the list as I mentioned. In almost every scenario an issue with a pull request can be fixed on the same pull request, by pushing to the same branch.

**Pull request closed without merging**
