### PR TITLE
Allow velocity constraints to be formulated with qdots

### PR DESCRIPTION
**Pull request by oliverlee**
Replace qdot expressions in the velocity constraints when initializing
constraint matrices. This allows the velocities of all points/frames to
be defined in terms of qdots; u terms only appearing in the kd_eqs
argument of the KanesMethod constructor.

@moorepants

### CODE REVIEW

**Comment by moorepants** [comment]
I'm guessing there should be at least a regression test for this.

This also seems like a behavior change.

I think it seems like a good change. So if you form up your velocities all with qdots instead of making an apriori assumption of what the udots are, then once you form the constraints in KanesMethod, all qdots will be replaced with udots?

That seems reasonable, especially if it only happens in the KanesMethod class. But will the orginal vectors be affected after you run KanesMethod since they are mutable?

**Comment by moorepants** [comment]
@jcrist @hazelnusse @gilbertged

**Comment by oliverlee** [comment]
Yes this allows you to define your reference frame orientations and point locations using just q terms and u terms are defined in the kde argument.

The original vectors shouldn't be affected as the constraints don't involve vectors directly. The same qdot/u substitution occurs when forming dynamic differential equations.

**Comment by moorepants** [comment]
Ok, that sounds good. If you can make a small test that shows how providing velocities and accelerations with only qdots and qddots along with the kde's, that you'll get constraints with udots properly subbed in. You can either check just that matrix somehow or check the resulting kdes from KanesMethod.kindiffs().

**Comment by jcrist** [comment]
Looks good to me (once a test is added). As an asied, while the constraints should be small in size (and thus this probably shouldn't matter), we may get a speed boost by using `msubs` instead of `expr.subs`. There are a few spaces still in the code where we use `expr.subs`, but I think they all can be replaced.

**Comment by moorepants** [comment]
The failures are some weird pydy issue. See Issue #8949.

**Comment by oliverlee** [comment]
@jcrist It looks like msubs but I think it would be better to put it in a separate PR that is labelled as replacing subs/improving efficiency instead of appending it to this fix/feature.

Anyways, I've added a rolling disc test.

**Comment by jcrist** [comment]
That's fine. You have test failures though. The PyPy ones are a different issue, but the new test seems to fail universally.

**Comment by oliverlee** [comment]
It passed the all tests when I ran it locally but I'll take a look at it later today.

**Comment by oliverlee** [comment]
This no longer fails test in physics/mechanics.

**Comment by moorepants** [comment]
Ok, looks good. Merging.

**Pull request merged**
