### PR TITLE
Use Meijerg G-function methods for integrating sinc

### LINKED ISSUE #11856: integration can take a _long_ time (possibly forever)
Hello,

When I do

```
t = symbols('t', real=True)
def nsinc(t):
    "normalized sinc function"
    return sinc(pi * t)

nsinc(t).integrate()
```

the process either takes a long time, or doesn't return.

### PR DESCRIPTION
**Pull request by rohitrango**
Fixes #11856

Uses Meijerg G-function methods first for functions
like sinc(x) since this method finds the integral quicker.

This will not check using the G-functions if it is explicitly mentioned `meijerg=False`
Examples-
```
In [3]: sinc(t*x).integrate()
Out[3]: 
Si(π⋅t)
───────
   π   
```
The above example is quick since it uses the 'hack'. 
```
In [3]: nsinc(t).integrate(meijerg=False)
Out[3]: 
Si(π⋅t)
───────
   π   
```
The above example will NOT utilise the hack and will take a longer time to evaluate.

### CODE REVIEW

**Comment by rohitrango** [comment]
One more optimization that can be done is to maintain a flag inside the `if isinstance(f,sinc) ...` clause and skip the same algorithm later if the flag is `True`. The reason I didn't do that is that I'm not sure whether the form of the function `g` helps in speeding up the G-method algorithm in any way. Plus, can I put some tests for this? 
@jksuom , your opinion ?

**Comment by jksuom** [comment]
There are two problems:

- `sinc` is only one of the great number of functions that `meijerint` can integrate, and it should be treated by `integrate` in the same way as the others, not by adding a separate piece of code for it. The only reliable way to find out which functions can be integrated by`meijerint` is to actually try it.

- This takes no account of the possibility that a definite integral is expected.

**Comment by rohitrango** [comment]
Right. I will try to find out which functions are actually integrable quicker by meijerint functions. Regarding definite integrals for meijerint functions, there was already a piece of code above it, so I only considered the possibility of the indefinite case. In any case, I'm working on it.

**Comment by rohitrango** [comment]
@jksuom, it seems like I'm stuck. I tried to use the `meijergint` method first, but that poses a different problem. Here is an example (this code is after the algorithm order is changed) - 

```
In [5]: integrate(f(x),y)
Out[5]: 
⎧                                                             │1│             
⎪                        y⋅f(x)                           for │─│ < 1 ∨ │y│ < 
⎪                                                             │y│             
⎨                                                                             
⎪     ╭─╮1, 1 ⎛1  2 │  ⎞        ╭─╮0, 2 ⎛2, 1       │  ⎞                      
⎪f(x)⋅│╶┐     ⎜     │ y⎟ + f(x)⋅│╶┐     ⎜           │ y⎟        otherwise     
⎩     ╰─╯2, 2 ⎝1  0 │  ⎠        ╰─╯2, 2 ⎝      1, 0 │  ⎠                      

 
1
 

In [6]: integrate(f(x),y) == y*f(x)
Out[6]: False

In [7]: integrate(f(x),y,meijerg=False) == y*f(x)
Out[7]: True
```

From what I can see, the result in `Out[5]:` is **almost** equivalent to `y*f(x)`.  

There are many other tests breaking as well. How should I convert the final expression into something 'simpler'? Or perhaps we could use the `meijergint` functions first only for some special class of functions? A little guidance would be really helpful.

**Comment by jksuom** [comment]
Can you give more details on the changes you have made and also on the particular test in question?

**Comment by rohitrango** [comment]
Here are the changes that I made ( in integrals.py )

1. Removed the following code in current implementation of `_eval_integral()` - 
```
            if meijerg is not False and h is None:
                # rewrite using G functions
                try:
                    h = meijerint_indefinite(g, x)
                except NotImplementedError:
                    from sympy.integrals.meijerint import _debug
                    _debug('NotImplementedError from meijerint_definite')
                    res = None
                if h is not None:
                    parts.append(coeff * h)
                    continue
```

2. Added the following code after checking of `risch` and `manual` and before `if isinstance(f,Poly)`:
```
if meijerg is not False:
            try:
                meij_f = meijerint_indefinite(f, x)
            except NotImplementedError:
                from sympy.integrals.meijerint import _debug
                _debug('NotImplementedError from meijerint_definite')
            if meij_f is not None:
                return meij_f
``` 

This evaluates the antiderivative using the Meijerg G methods first. But this breaks almost every test in `test_integrals.py` And the problem lies in the `meijerint_indefinite` function. Here are some examples of the results given by the function-
```
In [6]: from sympy.integrals.meijerint import meijerint_indefinite as mi

In [7]: mi(f(x),y)
Out[7]: 
⎧                                                             │1│             
⎪                        y⋅f(x)                           for │─│ < 1 ∨ │y│ < 
⎪                                                             │y│             
⎨                                                                             
⎪     ╭─╮1, 1 ⎛1  2 │  ⎞        ╭─╮0, 2 ⎛2, 1       │  ⎞                      
⎪f(x)⋅│╶┐     ⎜     │ y⎟ + f(x)⋅│╶┐     ⎜           │ y⎟        otherwise     
⎩     ╰─╯2, 2 ⎝1  0 │  ⎠        ╰─╯2, 2 ⎝      1, 0 │  ⎠                      

 
1
 
In [8]: mi(x**2,x)
Out[8]: 
⎧                      3                                             
⎪                     x                             │1│              
⎪                     ──                        for │─│ < 1 ∨ │x│ < 1
⎪                     3                             │x│              
⎨                                                                    
⎪╭─╮1, 1 ⎛1  4 │  ⎞   ╭─╮0, 2 ⎛4, 1       │  ⎞                       
⎪│╶┐     ⎜     │ x⎟ + │╶┐     ⎜           │ x⎟        otherwise      
⎪╰─╯2, 2 ⎝3  0 │  ⎠   ╰─╯2, 2 ⎝      3, 0 │  ⎠                       
⎩                                                                    

In [9]: mi(log(x),x)
Out[9]: 
⎧                       x⋅log(x) - x                          for │x│ < 1
⎪                                                                        
⎪                             ⎛1⎞                                 │1│    
⎪                      - x⋅log⎜─⎟ - x                         for │─│ < 1
⎨                             ⎝x⎠                                 │x│    
⎪                                                                        
⎪  ╭─╮2, 1 ⎛ 1    2, 2 │  ⎞   ╭─╮0, 3 ⎛2, 2, 1          │  ⎞             
⎪- │╶┐     ⎜           │ x⎟ + │╶┐     ⎜                 │ x⎟   otherwise 
⎩  ╰─╯3, 3 ⎝1, 1   0   │  ⎠   ╰─╯3, 3 ⎝         1, 1, 0 │  ⎠             

In [10]: 
```

I think that, for most functions, the other methods give the correct answer before `meijerint` even comes to play. But with the reversed implementation, the potential bug is seen.
I hope I was able to give the complete details of the problems I'm facing. You can certainly ask me if I missed something.

**Comment by jksuom** [comment]
I don't understand why `# fall back to heurisch` comes before meijerint_indefinite is tried. I would have moved that piece of code to the end of `_eval_integral()`.

**Comment by rohitrango** [comment]
Moving that code into the last works well, except for a few cases. And I believe that is due to the difference in the answers given by the functions. I think even one of the test case is wrong. After changing the order, here is the current order of algorithms -

1. risch_integrate (if `risch` is `True`)
2. manualintegrate (if `manualintegrate` is `True`)
3. simple heuristics (poly, exp, pow functions)
4. risch_integrate (if `risch` is not `False`)
5. G-functions (if `meijerg` is not `False`)
6. manualintegrate (if `manualintegrate` is not `False`)
7. heurisch

The problem is different integrators give different answers. For example- 
```
In [11]: meijerint_indefinite(sin(acos(x)),x)
Out[11]: 
⎧        3                                               
⎪     ⅈ⋅x             ⅈ⋅x        ⅈ⋅acosh(x)      │ 2│    
⎪───────────── - ───────────── - ──────────  for │x │ > 1
⎪     ________        ________       2                   
⎪    ╱  2            ╱  2                                
⎪2⋅╲╱  x  - 1    2⋅╲╱  x  - 1                            
⎨                                                        
⎪             __________                                 
⎪            ╱    2                                      
⎪        x⋅╲╱  - x  + 1    asin(x)                       
⎪        ─────────────── + ───────            otherwise  
⎪               2             2                          
⎩                                                        

In [12]: manualintegrate(sin(acos(x)),x)
Out[12]: 
⎧     __________                              
⎪    ╱    2                                   
⎨x⋅╲╱  - x  + 1    asin(x)                    
⎪─────────────── + ───────  for x > -1 ∧ x < 1
⎩       2             2                       

```
Another example is - 
```
In [13]: R = symbols('R',positive=True)

In [14]: meijerint_indefinite(sqrt(R**2-x**2),x)
Out[14]: 
⎧                        2      ⎛x⎞                                 
⎪          2          ⅈ⋅R ⋅acosh⎜─⎟            3            │ 2│    
⎪       ⅈ⋅R ⋅x                  ⎝R⎠         ⅈ⋅x             │x │    
⎪- ──────────────── - ───────────── + ────────────────  for ──── > 1
⎪       ___________         2              ___________        2     
⎪      ╱    2    2                        ╱    2    2        R      
⎨  2⋅╲╱  - R  + x                     2⋅╲╱  - R  + x                
⎪                                                                   
⎪              2     ⎛x⎞        _________                           
⎪             R ⋅asin⎜─⎟       ╱  2    2                            
⎪                    ⎝R⎠   x⋅╲╱  R  - x                             
⎪             ────────── + ──────────────                otherwise  
⎩                 2              2                                  

In [15]: manualintegrate(sqrt(R**2-x**2),x)
Out[15]: 
⎧   ⎛    ⎛x⎞        _________⎞                    
⎪   ⎜asin⎜─⎟       ╱  2    2 ⎟                    
⎪ 2 ⎜    ⎝R⎠   x⋅╲╱  R  - x  ⎟                    
⎨R ⋅⎜─────── + ──────────────⎟  for x > -R ∧ x < R
⎪   ⎜   2              2     ⎟                    
⎪   ⎝               2⋅R      ⎠                    
⎩                                                 
```
This difference in answers leads to some breaking test cases. I think that the G-functions give *more* correct answers here since all cases are considered and no assumptions regarding the value of the dummy variable is made. Simply changing the order of integrators does not help here. 

As it turns out, certain test cases fail because they consider the answer of a different integrator. I think changing the order of the integrators isn't sufficient.

**Comment by jksuom** [comment]
It is to be expected that some tests will break. In those cases it is generally ok to make the tests conform to the new expressions (if they are mathematically correct). A new `test_issue_11856` should be added.

**Comment by rohitrango** [comment]
So I tried to shuffle the order of integrators and saw that different integrators give *more correct* answers for different functions, but I was unable to generalize it. For example, 
```
In [39]: meijerint_indefinite(cos(asin(x)),x)
Out[39]: 
⎧        3                                               
⎪     ⅈ⋅x             ⅈ⋅x        ⅈ⋅acosh(x)      │ 2│    
⎪───────────── - ───────────── - ──────────  for │x │ > 1
⎪     ________        ________       2                   
⎪    ╱  2            ╱  2                                
⎪2⋅╲╱  x  - 1    2⋅╲╱  x  - 1                            
⎨                                                        
⎪             __________                                 
⎪            ╱    2                                      
⎪        x⋅╲╱  - x  + 1    asin(x)                       
⎪        ─────────────── + ───────            otherwise  
⎪               2             2                          
⎩   
...
In [55]: manualintegrate(cos(asin(x)),x)
Out[55]: 
⎧     __________                              
⎪    ╱    2                                   
⎨x⋅╲╱  - x  + 1    asin(x)                    
⎪─────────────── + ───────  for x > -1 ∧ x < 1
⎩       2             2                       
```
[This](https://in.mathworks.com/help/matlab/ref/asin.html?requestedDomain=www.mathworks.com) link gives another definition of `asin(x)` defined for all values of `x`.

But for the function `x*cos(n*x)`, the results are different -
```
In [40]: meijerint_indefinite(x*cos(n*x),x)
Out[40]: 
x⋅sin(n⋅x)   cos(n⋅x)
────────── + ────────
    n            2   
                n    

In [41]: heurisch_wrapper(x*cos(n*x),x)
Out[41]: 
⎧          2                     
⎪         x                      
⎪         ──            for n = 0
⎪         2                      
⎨                                
⎪x⋅sin(n⋅x)   cos(n⋅x)           
⎪────────── + ────────  otherwise
⎪    n            2              
⎩                n               
```
The second solution is more correct in this case (`manualintegrate` is unable to solve it). Although `meijerint` methods give the correct answer in some places, I do not find it very useful to solve definite integrals. For example, 
```
In [54]: integrate(sqrt(R**2-x**2),x)
Out[54]: 
⎧                        2      ⎛x⎞                                 
⎪          2          ⅈ⋅R ⋅acosh⎜─⎟            3            │ 2│    
⎪       ⅈ⋅R ⋅x                  ⎝R⎠         ⅈ⋅x             │x │    
⎪- ──────────────── - ───────────── + ────────────────  for ──── > 1
⎪       ___________         2              ___________        2     
⎪      ╱    2    2                        ╱    2    2        R      
⎨  2⋅╲╱  - R  + x                     2⋅╲╱  - R  + x                
⎪                                                                   
⎪              2     ⎛x⎞        _________                           
⎪             R ⋅asin⎜─⎟       ╱  2    2                            
⎪                    ⎝R⎠   x⋅╲╱  R  - x                             
⎪             ────────── + ──────────────                otherwise  
⎩                 2              2                                  
...
In [57]: integrate(sqrt(R**2-x**2),(x,0,R))
Out[57]: 
R                
⌠                
⎮    _________   
⎮   ╱  2    2    
⎮ ╲╱  R  - x   dx
⌡                
0                
```
So, I tried shuffling around with the different integrators, but could not find a general ordering to correctly solve both definite and indefinite cases. Changing the order also messes up an ODE test and a Fourier test (will have to look into it separately).
Writing more tests or code isn't a problem, the problem is being unable to decide which solutions are *acceptable*.

**Comment by jksuom** [comment]
It seems that the only change should be moving heurisch to the end.

**Comment by rohitrango** [comment]
I think I tried that, but to be sure, I will just stash the changes and try doing it again.

**Comment by rohitrango** [comment]
@jksuom, what should be done now?

**Comment by jksuom** [comment]
Now the failing tests should be fixed. In most cases the assertion result should be changed.

**Comment by rohitrango** [comment]
@jksuom The current implementation gives a wrong answer for `integrate(x*cos(n*x),x)` -
```
In [1]: integrate(x*cos(n*x),x)
Out[1]: 
x⋅sin(n⋅x)   cos(n⋅x)
────────── + ────────
    n            2   
                n    
```
whereas the correct answer is- 
```
⎧          2                     
⎪         x                      
⎪         ──            for n = 0
⎪         2                      
⎨                                
⎪x⋅sin(n⋅x)   cos(n⋅x)           
⎪────────── + ────────  otherwise
⎪    n            2              
⎩                n               

```

**Comment by jksuom** [comment]
The correct piecewise result is produced by `heurisch_wrapper`. A similar 'wrapper' should be created for `meijerint_indefinite` as well.

**Comment by jksuom** [comment]
Instead of a separate 'wrapper' for each integrator, it might be possible to have a wrapper for all integrators. It would inspect the result of _eval_integral and derive a piecewise expression calling _eval_integral again if necessary.

**Comment by rohitrango** [comment]
I'm looking into it. Any starting points for implementing a universal wrapper?

**Comment by jksuom** [comment]
I would look at where _eval_integral is called in doit (antideriv = self._eval_integral(...)). Then, if antideriv is not None, it should be handled in the same way as in heurisch_wrapper, creating a piecewise if necessary. It is probably not be necessary to define a new wrapper function for that. The same functionality could exist inside doit.

**Comment by rohitrango** [comment]
So I made a wrapper inside `doit()` and it works well, but there is still a problem with definite integration which needs to be resolved first. For example, 
```
In [96]: R=symbols('R',positive=True)

In [97]: integrate(sqrt(R**2-x**2),x)
Out[97]: 
⎧                        2      ⎛x⎞                                 
⎪          2          ⅈ⋅R ⋅acosh⎜─⎟            3            │ 2│    
⎪       ⅈ⋅R ⋅x                  ⎝R⎠         ⅈ⋅x             │x │    
⎪- ──────────────── - ───────────── + ────────────────  for ──── > 1
⎪       ___________         2              ___________        2     
⎪      ╱    2    2                        ╱    2    2        R      
⎨  2⋅╲╱  - R  + x                     2⋅╲╱  - R  + x                
⎪                                                                   
⎪              2     ⎛x⎞        _________                           
⎪             R ⋅asin⎜─⎟       ╱  2    2                            
⎪                    ⎝R⎠   x⋅╲╱  R  - x                             
⎪             ────────── + ──────────────                otherwise  
⎩                 2              2                                  


In [98]: integrate(sqrt(R**2-x**2),(x,0,R))
Out[98]: 
R                
⌠                
⎮    _________   
⎮   ╱  2    2    
⎮ ╲╱  R  - x   dx
⌡                
0 
```
This should actually return `pi*R**2/4`
The above function is returned by `meijerint_indefinite`. But for an interval defined like this, definite integration does not work. The reason is that the method `_eval_interval` cannot evaluate intervals like the one defined above. What should be done?

**Comment by jksuom** [comment]
It is a known issue that meijerint_definite does not work (well) over finite intervals. Therefore it is currently not attempted at all. There is a pending fix https://github.com/sympy/sympy/pull/11889 to _eval_interval that should make the evaluation of the definite integral possible.

**Comment by czgdp1807** [comment]
The associated issue has been fixed https://github.com/sympy/sympy/pull/14059
Thanks for the contribution. Closing this.

**Pull request closed without merging**
