### PR TITLE
Simple fix for B-Splines of higher than 1 degree with repeated knots.

### LINKED ISSUE #8474: b splines of degree > 1?
Looking at the spline_basis function:

```
knots = [0,0,0,2.5,5,7.5,10,10,10] 
sy.bspline_basis_set(2,knots,x)
```

This seems to break while the following is fine:

```
knots = [0,0,2.5,5,7.5,10,10]
sy.bspline_basis_set(1,knots,x)
```

I can tweak in extra knots, i.e. placing them at (0.1,0.2, 10.1,10.2 in the example) but this is still not really giving the desired basis matrix. 

Or am I just missing something very obvious?

I always generated knots for bspline basis matrix by taking the list of knots and:

```
 nknots = np.concatenate((np.repeat(knots[0],(degree+1)),np.array(knots[1:-1]),np.repeat(knots[-1],(degree+1))))
```

### PR DESCRIPTION
**Pull request by Saintis**
A quick (and fairly ugly) fix for full B-Spline functionality.
Supports B-Splines with repeated knots at higher than degree 1. 
Handled with nested Piecewise expressions.

Fixes #8474.

### CODE REVIEW

**Comment by jksuom** [comment]
Please add unit tests for the new functionality.

**Comment by Saintis** [comment]
Will do once I have some spare time.

**Comment by gxyd** [comment]
@Saintis can you please add test cases for the functionality?

**Comment by Saintis** [comment]
Sorry for the delay. I have added a basic unit test for the functionality.

**Comment by jksuom** [comment]
Is it possible to have the basic splines as Piecewise expressions, not as sums of such expressions?

**Comment by Saintis** [comment]
It's possible but would require more work to get a working method to "merge" the Piecewise expressions.

**Comment by jksuom** [comment]
I think that it should be done if possible within reason. Expressions having several Piecewise subexpressions are hard to deal with.

**Comment by Saintis** [comment]
I'm looking into merging the Piecewise expression currently, but the current definition of the basis B-Splines means that for higher orders you get a mix of Piecewise interval conditions, such as `[a, b]` and `(a, b]`, which means that combining those two conditions becomes messy.

Easiest fix / workaround would be to make all B-Splines defined on closed intervals `[a, b]` always so that the conditions can always be easily "merged".

Any objections to doing this or other suggestions?

**Comment by Saintis** [comment]
Concrete example: a second degree B-Spline with knots `[0, 0, 1, 2, 2, 3, 4, 4]` has as second basis-spline:

```(Piecewise((-x**2 + 3*x - 2, And(x <= 2, x >= 1)),  # 1.1
                                    (0, True))
                          + Piecewise((x**2/2, And(x < 1, x >= 0)),
                                      (-x**2/2 + x, And(x < 2, x >= 1)),  # 2.2
                                      (0, True)))
```

In this case, the first part of the first Piecewise (1.1) cannot be easily merged with the second part of the second Piecewise (2.2)

**Comment by jksuom** [comment]
I believe that it is possible to use closed intervals. The intervals in a Piecewise expression need not be disjoint.

**Comment by Saintis** [comment]
Changed all B-Spline Piecewise functions to be on closed intervals and made it so that higher-order Piecewise expressions are "merged" together so there are no "sums-of-Piecewise".

Let me know if anything else needs fixing up 😄

**Comment by jksuom** [comment]
Some tests and examples in doctrings have to be fixed.

**Comment by Saintis** [comment]
The Python 3 version seems to have a problem with `TypeError: '<' not supported between instances of 'And' and 'And'`. I do not need to check ordering of `And` elements, but if I do not the "merge" algorithm will run in O(n^2) instead of faster than that, since you can no longer exit early when looking for a match in a Piecewise's list of conditions.

Should I just cut out the comparison bit and just brute-force check all conditions and lose partial-order of the Piecewise clauses?

**Comment by jksuom** [comment]
> TypeError: '<' not supported between instances of 'And' and 'And'

There should probably be a custom comparison function for the conditions. It would look at the arguments of the `And` objects.

**Comment by Saintis** [comment]
Should be fixed now.

**Comment by jksuom** [comment]
This looks good to me. Thanks!

**Pull request merged**
