### PR TITLE
Add 'whats_new' to keep track of changes in this version

### PR DESCRIPTION
**Pull request by gxyd**
See discussion on https://groups.google.com/forum/#!topic/sympy/6eJW2qNT6dk , I have made a few 'headings' that I saw fit. But we discuss on this PR for what is the best solution.

We can slowly mention all the 'changes' from version 1.1.1 to 1.2 .
From this issue onwards any bug fixed or new feature introduced would require to make a new entry to doc/whats_new/v1.2rst file.

### CODE REVIEW

**Comment by gxyd** [comment]
We can include
```
:issue:`xxxx` by :user:`Gaurav Dhingra <gxyd>`.
```
after every new entry made to the .rst file.

**Comment by asmeurer** [comment]
The problem with having a single file is that the merge conflicts will be a nightmare. That's why I suggested a method where each PR adds a new file and they are amalgamated into one file for the release.

**Comment by ylemkimon** [comment]
Maybe we can include the important changes in the PR description and fetch them. That way, the content can be easily modified by author or maintainers.

**Comment by asmeurer** [comment]
@ylemkimon I like that idea. We should still have some kind of test that makes sure it is included, but we could add something to the PR template, like 

```
---
# Changes
- Please list major changes for this PR here. If there are no major changes, add "NO MAJOR CHANGES".
```

(or something like that, we can work on the wording)

I'm then unsure how to do it. The docs build should look at the PRs, I guess. But we don't want to require an internet connection to build the docs. At some point, they should be downloaded from the PR into the repo itself. Or maybe we could have a separate docs build that only does the release notes, which does pull in PR changes. That build could be done in a way that makes it look seamless from the main docs, but it would be run separately on Travis. 

And probably we do want to download the release notes from the PR descriptions into somewhere more permanent periodically. I'm unsure how that should work.

**Comment by asmeurer** [comment]
Another, maybe simpler idea: add a test for each PR that a release notes entry for that PR has been added to the wiki. That is, the release notes still live where they are now, but the PRs actually test that they have been added.  The test could be simply checking that a link back to the PR has been added somewhere (and at the top of the in-progress release notes page can be a little guide on how to add things to the page). 

For including the changes in the docs themselves, we can add something to the release script that imports the release notes from the wiki. We'd need to use RST instead of Markdown in the wiki release notes, but that's not a big deal.

**Comment by ylemkimon** [comment]
@asmeurer Doesn't importing from wiki require an Internet connection?

**Comment by asmeurer** [comment]
Wiki import would only be done at release time, so that's fine. Basically, the release script would just copy the wiki contents into the docs. 

Actually, importing the content into the docs is optional. It's less important to me than just finding some way to make sure the release notes are written. Others have mentioned that they'd like to have the release notes in the docs, but I personally think having them on the wiki is just fine. For me, what's more important is that the release notes are actually kept updated. But if we do want to put them in the docs, doing it at release time seems to be the most reasonable. That way, it is easier to modify them during development, and we don't have to worry so much about the issues that would come from tracking the notes in git.

**Comment by asmeurer** [comment]
Let's move the discussion over to https://github.com/sympy/sympy/issues/10942, the existing issue for this. This PR should be closed for now, because regardless of what we do, we need more tooling before we can just add the release notes to the docs.

**Pull request closed without merging**
