### PR TITLE
Added state_space_lambdify to simplify scipy ode integration.

### PR DESCRIPTION
**Pull request by jgoppert**

### CODE REVIEW

**Comment by czgdp1807** [comment]
@moorepants Do we still need this? I am not aware this part of SymPy, please let me know if someone can pick this up.

**Comment by moorepants** [comment]
This could go along with the work people are doing on the control package. Once a control package is implemented, it could be nice to have convenience functions that lambdify them.

**Comment by namannimmo10** [comment]
Thanks, @moorepants. I can include this as a part of my project. I think I can work on adding this portion in the third part i.e. just before adding those plots (as mentioned in the thread). Tho I'm not sure if that would turn out to be too much work for three months. What do you think?

**Comment by czgdp1807** [comment]
Closing in favour of the work done in https://github.com/sympy/sympy/issues/18460
Please feel free to re-open this if needed. Thanks for your contributions.

**Pull request closed without merging**
