### PR TITLE
DOC: Use README.rst for pypi.org page

### PR DESCRIPTION
**Pull request by MartinThoma**
#### Brief description of what is fixed or changed

Currently, the [Sympy PyPI page looks empty](https://pypi.org/project/sympy/). When this PR gets merged, the README will be used and the content will directly be rendered.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
I didn't realize you could put this in the cfg file. How is that different from having it in setup.py?

**Comment by asmeurer** [comment]
This is good. One issue is that I've noticed that the PyPI upload will fail if it cannot parse the rst. Is there any way to test if the RST builds correctly so we can know about that before we upload?

**Comment by MartinThoma** [comment]
> I didn't realize you could put this in the cfg file. How is that different from having it in setup.py?

You can actually put everything from setup.py in setup.cfg (or well, almost everything). See https://github.com/MartinThoma/hwrt as an example.

There is no big difference. I prefer having most things in setup.cfg, because it is a configuration file and not code. Hence one can read it without executing code.

For `long_description` and `packages` the advantage is the special values `file: README.md` and `find:`. So you don't need to write code to read a text file and you don't need to import `find_packages`. Again, in the end it is very similar.

**Comment by MartinThoma** [comment]
> One issue is that I've noticed that the PyPI upload will fail if it cannot parse the rst.

I'm not sure about that. I always use Markdown and I didn't ever have issues with that. The worst thing that happened to me with Markdown is that things were not shown in the way I wanted to. 

But even if that happens (and I'm not convinced that it can happen at all): Is that really an issue? It will be detected immediately when it happens, right? Even on Github it should then break the start page, right?

**Comment by asmeurer** [comment]
It would be an annoyance when doing the release, because we wouldn't notice that a release is broken until the very last step, which is uploading to PyPI. GitHub doesn't give any error messages on bad RST. 

I recently had this issue with another project, which is why I'm wondering about it. I don't know if there's some sort of command we can run to test the upload without doing it. Maybe `twine check` does it? We should probably add that to the sdist stage in the release script.

**Comment by oscarbenjamin** [comment]
The release instructions could say to check the formatting of the README on github before running the release script. (There are other things it should suggest to do first)

Are we sure that both github and pypi use the same format of rst?

**Comment by MartinThoma** [comment]
> It would be an annoyance when doing the release, because we wouldn't notice that a release is broken until the very last step, which is uploading to PyPI

If that is a big concern, would switching to Markdown be an option?

> Are we sure that both github and pypi use the same format of rst?

I don't know that

**Comment by MartinThoma** [comment]
Another option would be to use [pre-commit](https://pre-commit.com/) with [rst-linter](https://github.com/Lucas-C/pre-commit-hooks-markup) (seems to use the same linter as pypi.org)

pre-commit is super nice. It is a plugin system which allows developers to run scripts over the commited files before they are commited. If pre-commit changes any of those, the commit is aborted and you can review the changes. I use it in all my projects to make sure the style is good:

* Remove trailing spaces
* Make sure the last character of a file is a newline (makes diffs nicer and the output of some tools nicer)
* Apply [black code formatter](https://github.com/psf/black): supported by the python software foundation; acceptable style and it removes many discussions about coding style.
* [isort](https://github.com/timothycrosley/isort): Sort the order of imports. Again, removes discussions around style. I think this looks pretty nice and professional.
* [pyupgrade](https://github.com/asottile/pyupgrade): Make sure to use modern Python syntax. It's especially nice if you had to support Python 2 for a while but don't support it anymore or if you switched to Python 3.6+.

**Comment by asmeurer** [comment]
I asked on Twitter and apparently `twine check dist/*` checks it. So we just need to make sure that is run in the release script. It is a separate issue to run the release script on the CI, so you don't need to worry about that here (although it would be good to run it once locally just to ensure the current README will work).

**Comment by MartinThoma** [comment]
@asmeurer I'm not good at bash scripting and I have no idea how your release process works. Do you want me to adjust `rever.xsh`? Should I change `test_tarball`?

Would switching to Markdown be an option? This would avoid the problem.

**Comment by asmeurer** [comment]
We can just open an issue to add it to the release script the next time we do a release. 

I also don't have any objections to switching to markdown for the readme. At a glance it doesn't look like we use any RST specific things. But we should do the twine check thing in the release script regardless.

**Comment by asmeurer** [comment]
This looks good to me. Here is the rendered README in markdown https://github.com/sympy/sympy/blob/42074229344ac296b5d531c90bde4e5fd33c6591/README.md

**Comment by oscarbenjamin** [comment]
Looks good. Merging.

Thanks for this.

**Comment by oscarbenjamin** [comment]
Note: this won't show up on PyPI until the next release (1.6)

**Comment by moorepants** [comment]
I see that this is merged, but I am -1 to changing the readme to markdown. All of the documentation is in restructuredtext and I think it is a good idea to stick with that.

**Pull request merged**
