### PR TITLE
Remove BasicMeta/ordering of classes (redux)

### PR DESCRIPTION
**Pull request by asmeurer**
I have a lull in my work and will have little more time to work on SymPy, so I thought I would try a redux of #13059.

This removes the deprecated ordering of classes in the core. See #4269. 

The ordering of classes is non-pythonic, and unnecessarily restricted to only a subset of SymPy classes. In Python 3, it is not expected for arbitrary types to be comparable, and for places where this is used in actual comparisons like Add and Mul args ordering, we can use other orderings like `default_sort_key`. It also unnecessarily adds a metaclass to the core. This PR won't remove all metaclasses from the core because we will still have the ManagedProperties, which handles the old assumptions.

I ended up giving up on previous pull request because it was too much work. However, now that we have dropped Python 2 support, I expect this to be much easier to fix, since far fewer places in the code will actually be making use of this behavior. 

We need to be very careful about performance here, as this affects the deep core.

This is still a work in progress, so please don't merge until it is complete. 

#### References to other Issues or PRs

Closes #13059
Fixes #4269

#### Release Notes

- core
  - Remove the deprecated sorting of classes.

### CODE REVIEW

**Comment by asmeurer** [comment]
I'm already being sucked down some rabbit holes. We are doing way too much at import time. There is a lot of code that runs either at the module level or class level that causes code to be executed. This not only makes the imports slower, but makes it so that if that code breaks, you can't even import SymPy. We are also importing some submodules that aren't included in `__init__.py` indirectly. For example, `sympy.codegen` is imported by `sympy.printing` because all the code printers import from it at the top level.

**Comment by asmeurer** [comment]
So far most of the fixes here can be done independently. Being done here, they are impossible to test, because cce6bcb completely breaks everything. Should I make each commit as a separate PR? I will have to keep everything merged together locally in order to test things, but I think I can manage it.

**Comment by asmeurer** [comment]
OK, I am going to split out changes that can be done independently into separate PRs. This PR will have only those changes that cannot be done independently.

**Comment by asmeurer** [comment]
I thought that I had backported all the changes from #13059 that could be made independently, but apparently I didn't. So I'm going to start by doing that.

**Comment by asmeurer** [comment]
OK, instead of starting by removing the metaclass, which instantly breaks everything, we should start by removing the places where the ordering is used, as I did in #13059. Then once it isn't actually used anywhere, we can remove the metaclass.

**Comment by oscarbenjamin** [comment]
The changes here don't seem too big that anything needs to be split out.

**Comment by sylee957** [comment]
I think that this can be closed at the moment now because the metaclass issue is fixed

**Pull request closed without merging**
