### PR TITLE
ImageSet docs edited, example added how to put values at lamda var

### PR DESCRIPTION
**Pull request by Shekharrajak**
~~We need `put_values` attribute, because we can't do `subs` to put finite values in `ImageSet`.~~

```
In [1]: imgset = ImageSet(Lambda((n, m), n**2), S.Reals)

In [2]: imgset.subs(n,1)
---------------------------------------------------------------------------
TypeError: variable is not a symbol: 1

In [3]: imgset.subs(n,x)
Out[3]: 
⎧ 2           ⎫
⎨x  | x, m ∊ ℝ⎬
⎩             ⎭

```

Using this branch : 

```
In [1]: img = ImageSet(Lambda((n, m), n**2) , S.Reals)

In [2]: img.put_values({n: 1, m: 2})
Out[2]: {1}

In [3]: img = ImageSet(Lambda((n, m), n**2 + m) , S.Reals)

In [4]: img.put_values({n: 1, m: 2})
Out[4]: {3}

```

### CODE REVIEW

**Comment by smichr** [comment]
What about making image set callable so `img(*args) -> FiniteSet`?

**Comment by smichr** [comment]
It also seems to me that the result should still be a set, e.g. `{1}` instead of `1`. Just curious: in what context is this needed?

**Comment by Shekharrajak** [comment]
Thanks @smichr  for comments. 

> Just curious: in what context is this needed?

I want to use this in ImageSet [_union](https://github.com/sympy/sympy/pull/11188/files#diff-c1c17bdd28aafd400bf9415c7d048382R473) PR https://github.com/sympy/sympy/pull/11188
I am already using something like this in the PR.

>It also seems to me that the result should still be a set, e.g. {1} instead of 1

Thanks, I will do that.

> What about making image set callable so img(*args) -> FiniteSet?

After this PR that implementation seems easy. It is good idea.

**Comment by Shekharrajak** [comment]
Ping @sympy/sympy-solvers I want to use this in https://github.com/sympy/sympy/pull/11188 and https://github.com/sympy/sympy/pull/11257. Please share your thoughts on this.

**Comment by kshitij10496** [comment]
```python
In []: n, m = symbols('n, m')
In []: iset1 = ImageSet(Lambda((n, m), n**2) , S.Reals)
In []: iset.lamda(1, 2)
Out[]: 1

In []: iset2 = ImageSet(Lambda((n, m), n**2 + m) , S.Reals)
In []: img.lamda(1, 2)
Out[]: 3
```
@Shekharrajak I think what you are looking for can be obtained this way.
You can use the `FiniteSet` constructor to "setify" the result.

Does this help your cause ?

**Comment by Shekharrajak** [comment]
Thanks @kshitij10496 . `iset.lamda(1, 2)` is faster way.
But in this way we will use SymPy `Lambda` that will not check the `base_set` and if we want to put only some of the values then it will not help. Also [`img(*args) -> FiniteSet`](https://github.com/sympy/sympy/pull/11343#issuecomment-230304449) this is good idea.

**Comment by Shekharrajak** [comment]
After the discussion Harsh told that it is better to use `imageset.lamda(values_for_lambda_var)` directly, also don't make lambda variables public , it should be local and before doing `imageset.lamda(values_for_lambda_var)` this one need to check whether values are in ` base_set` or not. I have edited the docs accordingly.

**Comment by hargup** [comment]
The changes in the docs looks good, thanks!

**Pull request merged**
