### PR TITLE
Add factoring to compute certain sums with negative exponents

### LINKED ISSUE #14640: Can't compute closed form for certain sums with negative exponents
For example:

```
>>> from sympy import symbols, Sum
>>> a, b = symbols("a b")
>>> n, i = symbols("n i", integer=True)
>>> Sum(a**-i/(a-b), (i, 0, n)).doit()
Sum(a**(-i)/(a - b), (i, 0, n))
```

The issue is that `expand` is called in `eval_sum` which results in:

```
>>> expand((a**(-i)/(a - b)))
1/(a*a**i - a**i*b)
```

In this form, `eval_sum_symbolic` isn't able to separately evaluate `a**(-i)` and `1/(a - b)` to allow the sum to be computed. 

But adding factoring allows separation of the summation variable:

```
>>> Sum(a**-i/(a - b), (i, 0, n)).doit()
Piecewise((n + 1, Eq(1/a, 1)), ((-a**(-n - 1) + 1)/(1 - 1/a), True))/(a - b)
```

### PR DESCRIPTION
**Pull request by ehren**
#### References to other Issues or PRs

Fixes #14640.

#### Brief description of what is fixed or changed

Factoring added in `eval_sum_symbolic` to allow computing a closed form for sums like `Sum(a**-i/(a - b), (i, 0, n))`.

#### Other comments

The last testcase, `Sum(i*(a**(n - i) - b**(n - i))/(a - b), (i, 0, n)).doit()`, requires factoring as the last step of `eval_sum_symbolic`: The sum body first needs to be expanded to `a**n*i/(a*a**i - a**i*b) - b**n*i/(a*b**i - b*b**i)`, then each term in the `Add` needs separate factoring so that `a**n*i/(a*a**i - a**i*b)` becomes `a**(-i)*a**n*i/(a - b)` which can then be handled by `gosper_sum`.

### CODE REVIEW

**Comment by Abdullahjavednesar** [comment]
@asmeurer, @jksuom can you please review!

**Comment by jksuom** [comment]
It seems that `factor` will be helpful but I think that `eval_sum_symbolic` should not call itself recursively. Instead, I would add `eval_sum_symbolic(f.factor(), (i, a, b))` after the [original call](https://github.com/sympy/sympy/blob/master/sympy/concrete/summations.py#L951) if that returns `None`.

**Comment by ehren** [comment]
@jksuom that will work for the first two testcases added in the pull but it won't work for the third test case mentioned above, `Sum(i*(a**(n - i) - b**(n - i))/(a - b), (i, 0, n)).doit()`. In that case we need to rely on the original call in `eval_sum` expanding the expression before calling `eval_sum_symbolic`. Once expanded, we rely on the `if f.is_Add:` branch of `eval_sum_symbolic` to recurse over the terms `a**n*i/(a*a**i - a**i*b)` and `b**n*i/(a*b**i - b*b**i)` individually (these are produced by the `as_two_terms` [call](https://github.com/sympy/sympy/blob/a7286e3be89702ceec702c3e13ecdf5c14e14504/sympy/concrete/summations.py#L995)).  It's only when processing these individual terms recursively that factoring will help (by transforming e.g. `a**n*i/(a*a**i - a**i*b)` to `a**(-i)*a**n*i/(a - b)`).

Perhaps an alternative fix would be to add separate factor calls in both the `is_Mul` branch and the `is_Add` branch of `eval_sum_symbolic` (if the recursive applications of `eval_sum_symbolic` return `None`). On the other hand, I'm not sure this would be much of a performance improvement for the cost of duplication.

**Comment by jksuom** [comment]
In the third case, would it suffice to call `eval_sum_symbolic(f.expand().factor(), (i, a, b))` (after the previous calls have failed)?

**Comment by ehren** [comment]
Unfortunately just adding that to `eval_sum` doesn't work because, when `f` is `i*(a**(n - i) - b**(n - i))/(a - b)`, `f.expand().factor()` produces `-a**(-i)*b**(-i)*i*(a**i*b**n - a**n*b**i)/(a - b)` which needs expansion before it can be handled by `eval_sum_symbolic`.

**Comment by ehren** [comment]
That will produce `a**n*i/(a*a**i - a**i*b) - b**n*i/(a*b**i - b*b**i)` (same as just calling `expand`); the individual terms in the `Add` still need factoring.

**Comment by jksuom** [comment]
What else is needed than `factor` and `expand`? Or is it necessary to repeat them several times?

**Comment by ehren** [comment]
Yes the terms in the expanded form `a**n*i/(a*a**i - a**i*b)` and `- b**n*i/(a*b**i - b*b**i)` (produced by `as_two_terms` in the `is_Add` branch) have to be factored separately.

**Comment by jksuom** [comment]
If `eval_sum_symbolic` would call itself, is there something that would prevent infinite recursion?

**Comment by ehren** [comment]
Yes, I check that the factored expression differs from the original one before recurring. Eventually the terms that `eval_sum_symbolic` is applied to won't factor further (I don't think there's a possibility for this to 'flip flop' because there's no additional call to `expand` the full expression in `eval_sum_symbolic`).

**Pull request merged**
