### PR TITLE
Fix Mul.is_irrational

### LINKED ISSUE #17142: Nondeterministic exception from (atan(I/(I + I*tan(1)))).as_real_imag() (InconsistentAssumptions)
Sometimes this works:

```
>>> from sympy import *
>>> e = atan(I/(I + I*tan(1)))
>>> e.as_real_imag()
(atan(I/(I + I*tan(1))), 0)
```

Sometimes it gives this exception:

```
>>> e.as_real_imag()
Traceback (most recent call last):
  File "/home/e/se/sympy/core/assumptions.py", line 262, in getit
    return self._assumptions[fact]
KeyError: 'extended_real'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/e/se/sympy/core/assumptions.py", line 262, in getit
    return self._assumptions[fact]
KeyError: 'rational'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testing.py", line 114, in <module>
    print(c, e.as_real_imag())
  File "/home/e/se/sympy/core/expr.py", line 1921, in as_real_imag
    return (re(self), im(self))
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/function.py", line 462, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/function.py", line 277, in __new__
    evaluated = cls.eval(*args)
  File "/home/e/se/sympy/functions/elementary/complexes.py", line 58, in eval
    elif arg.is_extended_real:
  File "/home/e/se/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/e/se/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/e/se/sympy/core/assumptions.py", line 309, in _ask
    a = evaluate(obj)
  File "/home/e/se/sympy/functions/elementary/trigonometric.py", line 2269, in _eval_is_rational
    if s.args[0].is_rational:
  File "/home/e/se/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/e/se/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/e/se/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/e/se/sympy/core/assumptions.py", line 311, in _ask
    assumptions.deduce_all_facts(((fact, a),))
  File "/home/e/se/sympy/core/facts.py", line 522, in deduce_all_facts
    if not self._tell(k, v) or v is None:
  File "/home/e/se/sympy/core/facts.py", line 493, in _tell
    raise InconsistentAssumptions(self, k, v)
sympy.core.facts.InconsistentAssumptions: {
	algebraic: False,
	commutative: True,
	complex: True,
	composite: False,
	even: False,
	extended_negative: None,
	extended_nonzero: True,
	extended_positive: None,
	extended_real: True,
	finite: True,
	hermitian: True,
	imaginary: False,
	infinite: False,
	integer: False,
	irrational: False,
	negative: None,
	nonzero: True,
	odd: False,
	positive: None,
	prime: False,
	rational: False,
	real: True,
	transcendental: True,
	zero: False}, irrational=True
```

Another example is `log(I + I*pi/2)`.

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

Fixes #17142

#### Brief description of what is fixed or changed

I'd get to make the logic to correctly work by adding an additional check if every arguments are real.

#### Other comments

I'm not sure how to test out the original issue, unless it's getting run a thousand times.
But I would just post the original case on the travis and see if it gets failed for some other contributors' build. If it fails again, then the issue should get raised up again, right?

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
> I'm not sure how to test out the original issue, unless it's getting run a thousand times.

The obvious way would be to call `_eval_is_irrational`. I think this is fine though.

**Comment by asmeurer** [comment]
Maybe we should add a mode that evaluates all relevant `_eval` assumptions methods and checks their consistency. I also think we need a mode (IMO it should be default but other disagree) that disables the shuffling.

**Comment by oscarbenjamin** [comment]
> Maybe we should add a mode that evaluates all relevant `_eval` assumptions methods and checks their consistency.

That would be very useful.

> I also think we need a mode (IMO it should be default but other disagree) that disables the shuffling.

If we had a mode to evaluate all assumptions and check their consistency then the shuffling would not be as useful. Otherwise though the shuffling is needed because as it stands it is the main thing that picks up on these kind of bugs.

**Comment by oscarbenjamin** [comment]
I tried this:
```diff
diff --git a/sympy/core/assumptions.py b/sympy/core/assumptions.py
index 3455ec1b9c..2b432452b4 100644
--- a/sympy/core/assumptions.py
+++ b/sympy/core/assumptions.py
@@ -306,7 +306,18 @@ def _ask(fact, obj):
     else:
         a = evaluate(obj)
         if a is not None:
+            prev_assumptions = dict(assumptions)
             assumptions.deduce_all_facts(((fact, a),))
+            for fact, val in dict(assumptions).items():
+                new_val = assumptions.get(fact, None)
+                if new_val is not None:
+                    try:
+                        evaluate = handler_map[fact]
+                    except KeyError:
+                        pass
+                    else:
+                        assert evaluate(obj) in (None, new_val), '%s %s %s %s' % (
+                                obj, fact, new_val, evaluate(obj))
             return a
 
     # Try assumption's prerequisites
```
And got a bunch of failures from the core tests:
```console
$ pytest sympy/core/ -n4 -d --tb=line
============================================================= test session starts =============================================================
platform darwin -- Python 3.8.1, pytest-5.3.2, py-1.8.1, pluggy-0.13.1
architecture: 64-bit
cache:        yes
ground types: gmpy 2.0.8

rootdir: /Users/enojb/current/sympy/sympy, inifile: pytest.ini
plugins: instafail-0.4.1.post0, xonsh-0.9.13.dev1, xdist-1.31.0, forked-1.1.3, doctestplus-0.5.0, cov-2.8.1
gw0 [1844] / gw1 [1844] / gw2 [1844] / gw3 [1844]
...s....s..................................................s......s........s...........s..............s...................s............ [  7%]
s.............................................s..s........s.......xs.ss.........s..s.......s.....s.....................s.......s.s..s.. [ 14%]
.........s..s.......s....................................................s...............s........s........s.s......s....s............s [ 21%]
............................................................x.s.................................x..................s..............s..s. [ 29%]
x..s................................................................s..........s..s..........sx..........................x............. [ 36%]
......x.xxxs...........s...sx..........s.....s.............................x........s..s.x..s.......s......s.......sx.x...s.s........... [ 43%]
.........s..............s......................s....s...s...........s....x.x...........x.....x................x...................s.... [ 51%]
..........s...s.................F...................................................F......x.......X........FF.F..............F.....Fx. [ 58%]
x.......FF......................FF........X...........................................x...........................F.................... [ 65%]
......................F.....Fx.....................................................x.......F..x.........................F...x....x..... [ 73%]
............x.........x...F......................................F....Fx...............x.................x...............x..........F.. [ 80%]
...............................................................................x.............................................x......... [ 87%]
........................x...F............................................................x.................F............F.............. [ 95%]
................F.......x.................................x.......................F..F.F                                                [100%]
================================================================== FAILURES ===================================================================
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: 1/z algebraic False True
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: im(Z) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(A) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: oo*I finite True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(B) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(x) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/tests/test_arit.py:409: assert None is True
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(A) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: im(A) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: 2**(-oo) positive False True
/Users/enojb/current/sympy/sympy/sympy/core/tests/test_arit.py:1213: assert None is True
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(m) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(C) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: im(n1) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(B) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/power.py:75: TypeError: iroot() requires 'mpz','int' arguments
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: oo*I finite True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(B) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: oo*I imaginary False True
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(A) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: oo*I imaginary False True
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(x) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(A) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: oo*I imaginary False True
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(x) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(B) commutative True False
/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py:319: AssertionError: re(y) commutative True False
                                                               DO *NOT* COMMIT!                                                               
================================ 27 failed, 1709 passed, 65 skipped, 41 xfailed, 2 xpassed in 66.27s (0:01:06) ================================
```
Some of those are the issue here. Another is the iroot issue which is dealt with elsewhere. The others are mostly to do with commutative=True/False which is probably inconsistently handled.

So looks like you can find bugs with that...

**Comment by oscarbenjamin** [comment]
> So looks like you can find bugs with that...

I've almost completed the whole test suite and I think I just got a lot more of the same so I'd say this exercise found some bugs but not many.

**Pull request merged**
