### PR TITLE
Tests for making Antisymmetric Tensor Canonical

### PR DESCRIPTION
**Pull request by arighnac**
Fixes issue #13707 .
And also adds a test to it.

@jksuom , @smichr  please review.

### CODE REVIEW

**Comment by ArighnaIITG** [comment]
Consider the last commit. 
I don't know why my other commits are also showing up.

**Comment by ylemkimon** [comment]
It's probably because new branch was created on not master, but the branch for the other PR.

**Comment by gxyd** [comment]
I think the PR https://github.com/sympy/sympy/pull/13708 was merged fixing the issue #13707. Thanks for attempting this. You should be careful when contributing to new issues that others aren't about to submit a PR also.

**Comment by ArighnaIITG** [comment]
@gxyd,
Closing this issue, since it has alrady been merged by PR #13708

**Pull request closed without merging**
