### PR TITLE
Make wigner_9j work for certain half-integer argument combinations

### PR DESCRIPTION
**Pull request by certik**
This is #9941 rebased on top of the latest master (conflicts were resolved by using the version in #9941, instead of master).

### CODE REVIEW

**Comment by certik** [comment]
The code in master was recently changed in #13580. I think the solution implemented in #13580 is not as nice as the one implemented by @Rufflewind in here.

@Trave11er and @jksuom, you were the author/reviewer for #13580. Can you please review this PR? The tests and doctests for wigner pass on my machine.

**Comment by jksuom** [comment]
The formula defining 9-j symbols in terms of 6-j symbols in [Wikipedia](https://en.wikipedia.org/wiki/9-j_symbol) is a sum of terms multiplied by a power of -1. Racah symbols differ from 6-j symbols by different ordering of arguments and varying sign. I wonder if those differences would suffice to make it possible to take all terms with no sign factor. I hope someone could work this out on pencil and paper. In any case, more test examples are needed.

**Comment by Trave11er** [comment]
The code seems good to me. 
Also, the conversion of wigner6j to racah is correct - I have looked at the `(-1)` factor in #13580 and think it is redundant. This factor has the form 
`(-1)**(2*(j+j_1+j_2+j_4+j_6+j_8+j_9))` 
where `j` plays the role of `kk/2` in the present PR. However the tuples `j_1, j_2, j; j_4, j_8, j; and j_6, j_9, j` are each bound by triangle a relation and hence the above will always evaluate to 1.

**Comment by Rufflewind** [comment]
I've verified the results to be correct up to `2 j_max = 10`.

> However the tuples `j_1, j_2, j; j_4, j_8, j; and j_6, j_9, j` are each bound by triangle a relation and hence the above will always evaluate to 1.

I believe the triangular tuples should be `(j_1, j_9, j)`, `(j_4, j_8, j)`, and `(j_6, j_2, j)`.

**Comment by jksuom** [comment]
> the triangular tuples should be (j_1, j_9, j), (j_4, j_8, j), and (j_6, j_2, j).

It seems to me too that these should give the triangular conditions. It then follows that `j+j_1+j_2+j_4+j_6+j_8+j_9` is an integer and hence the power of -1 is always 1.

**Comment by jksuom** [comment]
@Rufflewind , could you add a few more test cases? Otherwise, I think this is good to go.

Since there is no sign factor, in contrast to the wikipedia formula, it would be good to add an explanation to the docstring, but that can also be done in another PR.

**Comment by Rufflewind** [comment]
I've added some random tests here: https://github.com/Rufflewind/sympy/commit/b2230fd428d7bfbac244b5f2e1d75a40a9f3b212

**Comment by jksuom** [comment]
It would suffice to choose a few, 2 - 3, with half-integer arguments, and add those to `test_wigner` in test_clebsch_gordan.py.

**Comment by Rufflewind** [comment]
Updated: https://github.com/Rufflewind/sympy/commit/4f97fc780f9ed028af32ee54c5ea742583a5c515

**Comment by jksuom** [comment]
Those would suffice. Only the lines should be shorter (70 or less). `half` could be used instead of `Rational( , 2)`.

**Comment by certik** [comment]
@Rufflewind can you please send a PR with your changes? I'll close this one in favor of yours.

**Comment by Rufflewind** [comment]
➡  #13602

**Comment by certik** [comment]
Closing this in favor of #13602.

**Pull request closed without merging**
