### PR TITLE
Update shor.py [Tuple to List]

### PR DESCRIPTION
**Pull request by RDxR10**
#### Brief description of what is fixed or changed
period_find(a, N) has been changed

#### Release Notes

* physics.quantum
     * Minor error fix in `period_find`

### CODE REVIEW

**Comment by czgdp1807** [comment]
@RDxR10 Is the release notes entry for the correct module? The diff shows changes in `physics.quantum` module and the release notes entry is for `functions` module.

**Comment by eric-wieser** [comment]
This should have a test, to confirm that it is now fixed.

**Comment by RDxR10** [comment]
> 
> 
> @RDxR10 Is the release notes entry for the correct module? The diff shows changes in `physics.quantum` module and the release notes entry is for `functions` module.

Oh, is it? Okay I'll edit that

**Comment by oscargus** [comment]
I'll merge this and add a test later. Thanks! (Too much of a hassle to set things up to push to this PR and so on...)

**Comment by oscargus** [comment]
Oh yeah, I should really try to remember that... Thanks!

**Comment by oscargus** [comment]
Turns out that it is not possible to add a test since the `CMod`-gate is not functional. Still, this PR fixes an obvious code problem (not possible to add lists and tuples), so better with than without.

**Pull request merged**
