### PR TITLE
Improved handling of radicals by solveset

### LINKED ISSUE #21004: Infinte recursion error  when using maximum
```
>>> sympy.__version__
'1.8.dev'
````

```
>>> from sympy import *
>>> from sympy.abc import x,y
>>> f = x/sqrt(x**2+1)
>>> maximum(f,x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\2acha\Desktop\NewFinal\sympy\sympy\calculus\util.py", line 795, in maximum
    return function_range(f, symbol, domain).sup
  File "C:\Users\2acha\Desktop\NewFinal\sympy\sympy\calculus\util.py", line 194, in function_range
    solution = solveset(f.diff(symbol), symbol, interval)
  File "C:\Users\2acha\Desktop\NewFinal\sympy\sympy\solvers\solveset.py", line 2117, in solveset
    rv = solveset(f.xreplace({symbol: x}), x, domain)
  File "C:\Users\2acha\Desktop\NewFinal\sympy\sympy\solvers\solveset.py", line 2141, in solveset
    return _solveset(f, symbol, domain, _check=True)
  File "C:\Users\2acha\Desktop\NewFinal\sympy\sympy\solvers\solveset.py", line 1083, in _solveset
    result += _solve_radical(equation,
  File "C:\Users\2acha\Desktop\NewFinal\sympy\sympy\solvers\solveset.py", line 858, in _solve_radical
    result = solveset_solver(eq, symbol) - \
  File "C:\Users\2acha\Desktop\NewFinal\sympy\sympy\solvers\solveset.py", line 1013, in <lambda>
    solver = lambda f, x, domain=domain: _solveset(f, x, domain)
  File "C:\Users\2acha\Desktop\NewFinal\sympy\sympy\solvers\solveset.py", line 1083, in _solveset
    result += _solve_radical(equation,
  File "C:\Users\2acha\Desktop\NewFinal\sympy\sympy\solvers\solveset.py", line 858, in _solve_radical
    result = solveset_solver(eq, symbol) - \
  File "C:\Users\2acha\Desktop\NewFinal\sympy\sympy\solvers\solveset.py", line 1013, in <lambda>
    solver = lambda f, x, domain=domain: _solveset(f, x, domain)
  File "C:\Users\2acha\Desktop\NewFinal\sympy\sympy\solvers\solveset.py", line 1083, in _solveset
    result += _solve_radical(equation,
  File "C:\Users\2acha\Desktop\NewFinal\sympy\sympy\solvers\solveset.py", line 858, in _solve_radical
    result = solveset_solver(eq, symbol) - \
```

EDIT: I have found this to more of a solveset issue than an issue pertaining to the calculus module. 
The reason why this function goes into infintire recursion  is because of this equation: 
```
eq = x/sqrt(x**2+1)
dif = eq.diff(x)
solveset(dif,x) # solveset cannot solve this. It  calls unrad, which returns none, 

```

This expression keeps on going in loops between solveset  ->unrad -> solveset and so forth.

### PR DESCRIPTION
**Pull request by ghost**
#### References to other Issues or PRs
Fixes #21004 

#### Brief description of what is fixed or changed
Earlier unrad used to return None whenever the passed expression got simplified to the form ``(number)/(some weird expression)``. 
This led to a loop between _solveset and unrad (as is visible in the original issue). This pr changes this. Now for such expressions, unrad returns the numerator and an empty list. This translates into solveset returning ``EmptySet`` as the solution, which is  the correct answer, for such expressions.

#### Other comments
I am not exactly familiar with  **how** tests should be added. I have added tests in the calculus and solvers module. It would be very helpful if someone could guide where the tests would make the most sense.
If you want  to reproduce the error, this might help:
```
f = 1/sqrt(x**2+1)
solveset(f,x) # leads to infinite recursion
````

#### Release Notes

* solvers
    * Fixed a bug in solveset, which led to infinite recursion for solving some expressions involving radicals.

### CODE REVIEW

**Comment by almighty123789** [comment]
@oscarbenjamin please review the pr

**Comment by oscarbenjamin** [comment]
Looks good but can you write a better release note?

From a "user" perspective what functions (e.g. maximize etc) have been improved and how have they improved (no longer raise exception)?

**Comment by almighty123789** [comment]
@oscarbenjamin  thanks for  reviewing the pr.
Actually this issue is completely related to the solveset module, that is why I am not in favor of adding these in the review notes.
The changes I have made have virtually no effect on the calculus module.

**Comment by oscarbenjamin** [comment]
If this has fixed a bug in solveset or solve then you can mention that. The current release note is too vague to be of much use to anyone. If someone was reading the release notes then how would they know if it was potentially relevant:
https://github.com/sympy/sympy/wiki/Release-Notes-for-1.8

**Comment by almighty123789** [comment]
@oscarbenjamin are the review notes fine now?

**Comment by oscarbenjamin** [comment]
I edited it a bit.

Thanks!

**Pull request merged**
