### PR TITLE
Crypto : Improve speed of RSA

### PR DESCRIPTION
**Pull request by sylee957**
#### Brief description of what is fixed or changed

https://github.com/sympy/sympy/blob/cf7322f5dba866c85ab3cfa2ad237e573b008a43/sympy/crypto/crypto.py#L1218

It is slow to compute Euler Totient in this way, if the numbers are large.

```
from sympy import *
from sympy.crypto import rsa_public_key, rsa_private_key
import cProfile

p = S(24516021043835088623)
q = S(30129830626086539899)
e = S(65537)

cProfile.run('rsa_public_key(p, q, e)')
``` 

Using special formula improves the speed from
`39508155 function calls (39507218 primitive calls) in 24.688 seconds`
to 
`651 function calls in 0.001 seconds`

Though the `totient` seems to get cached after subsequent computation.

#### Release Notes

- crypto
  - Improved speed for `rsa_public_key` and `rsa_private_key`
  - Raise deprecation warning if same prime numbers are given to `rsa_public_key` and `rsa_private_key`

- [ ] When deprecation is complete, return False when the primes are the same and consider allowing a keyword that would override the checks so, for educational purposes, non-prime or `p==q` values could be used.

### CODE REVIEW

**Comment by asmeurer** [comment]
Indeed, isn't the whole point of RSA that `n` is difficult to factor?

**Review by asmeurer — APPROVED** [review]

**Comment by sylee957** [comment]
SymPy's RSA allows creating key from same primes.
I've added a trivial case, but is it having any practical sense?

**Comment by asmeurer** [comment]
It's not cryptographically meaningful. You can check if a number is a square very quickly, even for large numbers. Actually in practice the primes cannot even be close to one another https://www.johndcook.com/blog/2018/10/28/fermat-factoring/. 

Of course the SymPy implementation isn't intended for practical use. Even so, it could be better to simply return False if p == q.

**Comment by sylee957** [comment]
This may be a backward incompatible change.
Though I haven't followed deprecation cycle here.

**Comment by smichr** [comment]
> but is it having any practical sense?

It was educational purposes that drove the addition of this module in the first place. I think it would be good to have an option (like default `safe=False`) that allowed one to feed in equal values to see what the result is. (Mind you, I am only talking from a rather uninformed-about-crypto-educational point of view. Or maybe default to `safe=True` and then the normal case would be checked but one could override that if one wanted to do so. This would also make deprecation unnecessary.

**Comment by smichr** [comment]
I just looked closer at the function and see that it does enforce the condition that the numbers be prime...I wonder if that could be relaxed -- again with `safe=True` which would raise an error -- so the function is as lenient as possible yet functional (though not necessarily "safe").

So instead of returning False...use the non-trivial totient in this case and return the computed value when safe=False.

**Comment by smichr** [comment]
Would it make sense to put this optimization into the totient function itself?
```python
if isprime(n):
    return n - 1
...
```

**Comment by asmeurer** [comment]
`totient` calls `factorint`, which should already have such optimizations.

**Pull request merged**
