### PR TITLE
Added Communication Classes to Discrete Markov Chains

### PR DESCRIPTION
**Pull request by Maelstrom6**
#### Brief description of what is fixed or changed

Added the ability to identify the communication classes in a Markov chain, whether they are recurrent or transient and what periodicity they have.

#### Other comments

The algorithms used are as suggested from #20026. The overall algorithm complexity is technically O(n^2) where n is the number states in the chain. This is because of the definition of `E` in the source code. However, the major parts of the algorithm have complexity roughly O(n*m) where m is the average number of states in each recurrence class. This means, as the transition matrix approaches the identity matrix (or becomes more sparse), the algorithm approaches O(n).

There will be more functions added that directly and indirectly follow from this one.

The matrices used in the tests are from [this tutorial](https://drive.google.com/file/d/1mE9IgOdO-Nu9-xAaei74n28v5jVD7yvW/view?usp=sharing).

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by czgdp1807** [comment]
LGTM. @Upabjojr @Smit-create @sylee957 Any thoughts/comments on the APIs or algorithm?

**Comment by Smit-create** [comment]
LGTM.

**Comment by Maelstrom6** [comment]
Currently, the function returns a 3-tuple, each containing a list on the various information about the chain. Should I add a boolean argument to have it zipped? So instead of 
```
[[A, B], [C], ...], [True, False, ...], [2, 1, ...]
``` 
we can have 
```
([A, B], True, 2), ([C], False, 1), ...
```

**Comment by sylee957** [comment]
We don't necessarily have to add any additional keywords to return zipped parameters, but a tutorial example should be sufficient.
If we'd try to return zipped argument, you'd also have hard time deciding whether it should be a prebuilt list of tuples, or the `zip` generator object itself

**Comment by czgdp1807** [comment]
> ([A, B], True, 2), ([C], False, 1), ...

This seems better. May be a `Tuple` of such values would be great. All the information of one class in a single tuple. 

> [[A, B], [C], ...], [True, False, ...], [2, 1, ...]

Here the information is a bit scattered and I would be required to see three different lists to gather information of one class.

**Comment by Maelstrom6** [comment]
> If we'd try to return zipped argument, you'd also have hard time deciding whether it should be a prebuilt list of tuples, or the zip generator object itself

I could always just do `return list(zip(classes, recurrence, periods))`. But as you say, so can the user.

I agree with @czgdp1807 and I think its much more user friendly to have an option to receive a zipped or unzipped object. It's also user friendly to have a zipped object, so that should probably be default. The unzipped object will be more useful for other functions in `DiscreteMarkovChain` that will use `communication_classes`.

**Comment by czgdp1807** [comment]
> I think its much more user friendly to have an option to receive a zipped or unzipped object.

Let's keep it less ambiguous. Always a list/tuple of tuples should be returned as the following case is, 

> ([A, B], True, 2), ([C], False, 1), ...

**Comment by czgdp1807** [comment]
LGTM. Will merge tomorrow if no objections.

**Comment by Maelstrom6** [comment]
I realized that I need to change the "Returns" section in the docstring to match the zipped return type. Will do so in a few hours.

**Pull request merged**
