### PR TITLE
speeding up parts of factorials

### PR DESCRIPTION
**Pull request by postvakje**
precompute factorials for n < 20 and use str.count to compute number of
nonzero bits in n.

### CODE REVIEW

**Comment by asmeurer** [comment]
Wouldn't computing once and memoizing the first 20 factorials be just as fast?

**Comment by postvakje** [comment]
Sure. Maybe memoization might be slightly slower than hardcoding the numbers.  But memoization is more flexible and can be done by the end-user. The current algorithm in factorials.py computes n! directly when n < 20 and uses a different algorithm when n >= 20. The first part of the patch was just to replace that small piece of code to compute n! directly when n < 20 with a slightly longer piece of code that precompute the numbers.  The other part of the patch is to replace the nonzero bit counting part with the faster str.count().

**Comment by asmeurer** [comment]
I would just rather see that than hard-coded numbers (although to be fair hard-coded numbers are quite common in the ntheory module). You could just have some class attribute on `factorial` like `_small_values` which defaults to None and is set equal to the first 20 factorials (computed) in `eval` the first time it is called.

**Comment by asmeurer** [comment]
Regarding the bit counts, I'd like to see some timings of other methods. For example is `format` faster than `bin`? What about `int.to_bytes`? No doubt any of them will be faster than what's there, since they are written in C, but we might as well use the best method for counting bits if we can.

**Comment by postvakje** [comment]
Not quite clear how to use `int.to_bytes` to count nonzero bits without a loop.  `bin` appears faster than `format` so `bin` seems to be the best option.

`>>> timeit.timeit("[format(d,'b').count('1') for d in range(10000)]", number = 1000)`
`8.653980755934128`
`>>> timeit.timeit("[bin(d).count('1') for d in range(10000)]", number = 1000)`
`4.996242619234238`

Maybe it is also a good idea to set the default class attribute `_small_factorials` to `[]` rather than `None`. This way after the first instance precomputes it, all other instances will see it as well.

**Comment by smichr** [comment]
See this [thread](http://stackoverflow.com/questions/9829578/fast-way-of-counting-non-zero-bits-in-python); my read is that for number for which you would want to calculate the factorial, counting '1's in 'bin' is good.

**Comment by asmeurer** [comment]
For what it's worth I don't really see any speed differences in this branch, even for very large factorials (I tested up to factorial(1000000) and it took 8.85 seconds both in this branch and master. If you use `%timeit` be sure to test with the cache off (`./bin/isympy -C`) because otherwise as soon as it computes the value once it will be cached.

**Comment by postvakje** [comment]
The bit counting probably takes a small fraction of the total computation time. But I think it is more pythonic to use `str.count()` than an explicit loop.

**Comment by asmeurer** [comment]
I agree the code reads better even if it's not faster.

**Pull request merged**
