### PR TITLE
Added a bunch of constants to sympy/physics/units

### PR DESCRIPTION
**Pull request by ShikharJ**
Please review and suggest improvements.
For CODATA values refer: http://physics.nist.gov/cuu/Constants/Table/allascii.txt

### CODE REVIEW

**Comment by ShikharJ** [comment]
@bjodah Can you please take a look? I'd like to have this merged as I'm still short on the patch requirement.

**Comment by smichr** [comment]
Should this wait for #12246 ?

**Comment by smichr** [comment]
OK, the unification of units is complete. You can make your mod on top of the new master and repush here with the `-f` option. I made some comments about how to do that easily (if you don't already know)  [here](https://github.com/sympy/sympy/pull/12424#issuecomment-290398966).

**Comment by ShikharJ** [comment]
Updated @smichr. Can you please take a look here?

**Comment by smichr** [comment]
double checked it; looks good. I see that you (rightly) didn't use the abbreviation for Faraday's constant (F) which is already used for the Farad.

**Comment by ShikharJ** [comment]
@smichr Thank you very much for the quick review and merge.

**Pull request merged**
