### PR TITLE
Implemented homogeneous option to Quaternion.to_rotation_matrix

### PR DESCRIPTION
**Pull request by evbernardes**
#### Brief description of what is fixed or changed
Added a bool parameter called `homogeneous` defaulting to `False`.

When `homogeneous == True`, a slightly different but equivalent definition of the rotation matrix is given.

#### Other comments
This is another one in a series of small quality-of-life contributions I'm making to `Quaternion`.

The "homogeneous" version of the rotation matrix can be slightly better for symbolic manipulation (its formula can be seen [here](https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation)). 

To demonstrate this, the test function I implemented shows that the homogeneous version is equivalent to the original non-homogeneous version after being passed to `simplify`.

As an interesting observation, the homogeneous version also has the property of being equivalent to a rotation + a scaling when the quaternion norm is ignored. If the norm is ignored in the non-homogeneous version, the rotation does not correctly represent anything.

#### Release Notes

* algebras
  * Implemented homogeneous option to Quaternion.to_rotation_matrix

### CODE REVIEW

**Comment by smichr** [comment]
Either the parameter description or the docstring proper should probably have a description of what this option does.

**Comment by evbernardes** [comment]
> Either the parameter description or the docstring proper should probably have a description of what this option does.

You're right, I completely forgot about is somehow. I added a line to explain this, but maybe it needs some more work!

**Comment by smichr** [comment]
> (its formula can be seen [here](https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation))

Can you help me find it on the page? I don't find the word "homogeneous" there. Are you using something that is common nomenclature when working with quaternions?

Also, there is a table of conventions near the discussion of JPL convention. Which method does SymPy use?

**Comment by evbernardes** [comment]
@smichr As an extra reasoning for using the formula I presented here, declaring the following:
```
from sympy.abc import a, b, c, d, x, y, z
q = Quaternion(a, b, c, d)
v = Quaternion(0, x, y, z)
```
And then using the product to find the rotation (supposing `|q| = 1`):
```
v_rotated = Matrix((q * v * q.conjugate()).args[1:])
```
We can symbolically differentiate `v_rotated` w.r.t. to each variable to find the rotation matrix:
```
R = Matrix([[
    v_rotated.diff(x),
    v_rotated.diff(y),
    v_rotated.diff(z)]])
```
Once again, this gives the same formula as the one I'm proposing (minus the normalization):
```math
\[
\left[
   \begin{matrix} % or pmatrix or bmatrix or Bmatrix or ...
      a^{2} + b^{2} - c^{2} - d^{2} & - 2 a d + 2 b c & 2 a c + 2 b d \\
      2 a d + 2 b c & a^{2} - b^{2} + c^{2} - d^{2} & - 2 a b + 2 c d \\ 
     - 2 a c + 2 b d & 2 a b + 2 c d & a^{2} - b^{2} - c^{2} + d^{2}
   \end{matrix}
\right]
\]
```
So it would make the symbolic formula more consistent with the calculation of a rotation by the product with `q` and `q.conjugate()`.

**Comment by smichr** [comment]
So this option is just giving an equivalent form of the expression: the rhs below.

image

That would be what `simplify(lhs)` would give but since it may not actually be the same in general (e.g. if `b = 1/(x + 1)`, for example) I am hesitant to make it `simplify=True`.

On the page you reference they say that the non-homogeneous form is "more efficient calculation in which the quaternion does not need to be unit normalized". Perhaps the flag could be called `normal=False` since the elements of the matrix will be expressed over a denominator (and that is what the `normal()` method would do). The docstring could say that `normal=True` gives an expression that may be more efficient for symbolic calculations but less so for direct evaluation.

image

**Comment by evbernardes** [comment]
> That would be what `simplify(lhs)` would give but since it may not actually be the same in general (e.g. if `b = 1/(x + 1)`, for example) I am hesitant to make it `simplify=True`.
> 

This is actually the same in general (except, of course, if the norm is zero)! 

By simply multiplying and dividing that lone `1` by $a^2 + b^2 + c^2 + d^2$ and assembling the elements, you arrive at the form on the right. It wouldn't be the same if one of the forms was not being normalized at the end, but they are.

**Comment by evbernardes** [comment]
> 
> > That would be what `simplify(lhs)` would give but since it may not actually be the same in general (e.g. if `b = 1/(x + 1)`, for example) I am hesitant to make it `simplify=True`.
> > 
> 
> This is actually the same in general (except, of course, if the norm is zero)! 
> 
> By simply multiplying and dividing that lone `1` by $a^2 + b^2 + c^2 + d^2$ and assembling the elements, you arrive at the form on the right. It wouldn't be the same if one of the forms was not being normalized at the end, but they are.

I didn't really understand the `b = 1/(1+x)` example though, what do you mean by that?

**Comment by evbernardes** [comment]
Just changed the parameter from `homogeneous` to `normal`.

As a last step, I'd personally prefer that `normal` should be `True` by default! But that's a different discussion :)

**Comment by smichr** [comment]
> what do you mean by that?

image

[21] simplifies to [22] and this is not the same as [23]

(But for that matter, the normal of [21] is not [23], either.)

But if there is no denominator on any of the arguments then the normal form is consistent with what `normal` does.

I am not opposed to changing the default value since there is no guarantee of the format of the result, only the equivalency of it. And since it is the same for numbers and better for symbolic expressions, I don't think there would be any complaint. We can see if anyone else has an opinion.

**Comment by evbernardes** [comment]
Ah alright, you meant in the context of sympy simplifications! I see what you mean!

Alright! In the meantime, I think this is finished! So feel free to merge it or tell me to change the default value whenever you feel like it :)

**Comment by evbernardes** [comment]
@smichr If you're curious, I found where I had read the word homogeneous, [it was in a different page](https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles#Quaternion_to_Euler_angles_conversion).

**Comment by smichr** [comment]
Thanks for the ref to the use of "homogeneous". Given some precedence of the term use, I think it makes sense to change `normal` back to `homogeneous`. And let's go ahead and try making the default True.

**Comment by evbernardes** [comment]
> Given some precedence of the term use, I think it makes sense to change `normal` back to `homogeneous`. And let's go ahead and try making the default True.

I'm not sure about the name anymore tbh, because it can be misinterpreted as a homogeneous 4x4 matrix...

I agree with making it by default though!

**Comment by smichr** [comment]
ok, if you want to change the function parameter and docstring we can see what fails (if anything) with the change.

**Comment by evbernardes** [comment]
Switched it back to `homogeneous` and is now `True` by default.

**Pull request merged**
