### PR TITLE
Add simplification for log(exp())

### LINKED ISSUE #17208: missing simplifications for log(exp( ))
Output from current master:
```
>>> log(exp(I*pi/3))
log(exp(I*pi/3))
>>> simplify(log(exp(I*pi/3)))
log(exp(I*pi/3))
```
Expected output: `I*pi/3`. (As far as I know, `log` refers to the principal value, though this isn't mentioned in its docstring.)
```
>>> log(exp(5*I))
log(exp(5*I))
>>> log(exp(2 + 5*I))
log(exp(2 + 5*I))
>>> simplify(log(exp(2 + 5*I)))
log(exp(2 + 5*I))
```
Expected/proposed outputs: `5*I - 2*pi*I`  and `2 + 5*I - 2*pi*I`, respectively. Or maybe `2 + I*(5 - 2*pi)` ?

Similar simplifications are already implemented for `asin(sin())` etc.:
```
>>> asin(sin(5))
5 - 2*pi
>>> asin(sin(3))
-3 + pi
>>> acos(cos(10))
-10 + 4*pi
```
Relevant code that could potentially be adapted can be found [here](https://github.com/sympy/sympy/blob/a2d65f2a9c6c774404d602a941c09008e100025a/sympy/functions/elementary/trigonometric.py#L2062).

### PR DESCRIPTION
**Pull request by gschintgen**
#### References to other Issues or PRs

Fixes #17208

#### Brief description of what is fixed or changed
Before:
```
>>> log(exp(19*I*pi/4))
log(exp(3*I*pi/4))
>>> x = Symbol('x', real=True)
>>> log(exp(x + 7*I))
log(exp(x + 7*I))
```

After:
```
>>> log(exp(19*I*pi/4))
3*I*pi/4
>>> x = Symbol('x', real=True)
>>> log(exp(x + 7*I))
x - 2*I*pi + 7*I
```
(Update: expressions with variables will no longer be simplified.)

#### Other comments

I've factored out some code as a new helper: `_match_real_imag`.
Some feedback about this would be appreciated.
Should I move it to elementary/complexes.py ?
(I do intend to add some tests for it.)

#### Release Notes

* functions
  * Added automatic evaluation for `log(exp()`.

### CODE REVIEW

**Comment by jksuom** [comment]
The combination `exp(log())` is currently automatically simplified, but the simplification is not necessarily beneficial and might be removed in the future. (See, e.g., https://github.com/sympy/sympy/issues/15323). I have doubts about this PR as well.

**Comment by gschintgen** [comment]
> The combination `exp(log())` is currently automatically simplified, but the simplification is not necessarily beneficial and might be removed in the future. (See, e.g., #15323). I have doubts about this PR as well.

Hmm, that's a pity, but given the sensitivity of some important and complex algorithms (Risch, Gruntz) I do understand your reservations.

Would this PR be acceptable if the changes were limited to purely numeric evaluation instead of enabling symbolic simplification? I.e. if a check for `arg.is_numeric` were added? So that the first example given in the description above would still evaluate, while the second example (containing a variable) would stay untouched?

**Comment by jksuom** [comment]
>  the changes were limited to purely numeric evaluation instead of enabling symbolic simplification

That seems acceptable to me.

**Comment by smichr** [comment]
Looks like a good compromise. Glad to have @jksuom watching for features we probably shouldn't be supporting in light of trying to limit autosimplification. I wonder if it might be good to distinguish between canonicalization vs simplification. `sqrt(16) -> 4` would be an example of the former. I'll have to think more about what differentiates the two.

**Pull request merged**
