### PR TITLE
Reorder CI tests for ruff first

### PR DESCRIPTION
**Pull request by Skylion007**
#### Brief description of what is fixed or changed
* Reorders the CI tests to run ruff first. Ruff provides many of the same checks as flake8 does and runs 10-50x faster. This allows users to get feedback even sooner on the CI test than waiting for the equivalent slower flake8 checks.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Review by haru-44 — APPROVED** [review]

**Comment by VascoSch92** [comment]
Why `flake-8` is still active? I believe it can be replaced with `Ruff`

**Comment by oscarbenjamin** [comment]
> Why `flake-8` is still active? I believe it can be replaced with `Ruff`

Ruff does not do all the same checks as flake8. I'm not sure exactly what the differences are but I have seen cases where flake8 picks up on something that ruff does not.

**Comment by VascoSch92** [comment]
> > Why `flake-8` is still active? I believe it can be replaced with `Ruff`
> 
> 
> 
> Ruff does not do all the same checks as flake8. I'm not sure exactly what the differences are but I have seen cases where flake8 picks up on something that ruff does not.

Are you sure? With the new release i believe that they are reaching equality (or perhaps they have already reach it). It is worth to give a look ;)

**Comment by haru-44** [comment]
> Why `flake-8` is still active? I believe it can be replaced with `Ruff`

Unfortunately, we lack the resources to verify whether this is possible. We hope you understand that this is an improvement to the extent possible. Of course, someone is welcome to verify it and create the PR.

This PR merely changes the order of tests, and there are no concerns about it having a negative impact. It seems that merging it should not pose any problems.

**Pull request merged**
