### PR TITLE
MathML presentation printer: Added more printing methods

### PR DESCRIPTION
**Pull request by pragyanmehrotra**
#### References to other Issues or PRs

This has reference to #16036 

#### Brief description of what is fixed or changed

Some new methods have been added that required MathML presentation printer's support

#### Other comments
I haven't added the tests yet because the functions may require some changes, thus I'll add the tests once the functions are reviewed.

#### Release Notes

* printing
    * Added printing methods for elliptic_e, elliptic_f, elliptic_pi, Ei, expint, jacobi, gegenbauer, chebyshevt, chebyshevu, legendre, assoc_legendre, laguerre, assoc_laguerre and hermite type objects for MathML presentation printer

### CODE REVIEW

**Comment by oscargus** [comment]
I will run my printing script on this later on today and will post the output here once done.

**Comment by oscargus** [comment]
Here is the output:
after16284

So most of them look good! For the problematic ones, I've looked at elliptic_f which currently prints as `<mi>&#x1d5a5;<mfenced separators="|"><mi>x</mi><mi>y</mi></mfenced></mi>`
This should be 
`<mrow><mi>&#x1d5a5;</mi><mfenced separators="|"><mi>x</mi><mi>y</mi></mfenced></mrow>`, so the `<mfenced>`should not be within the `<mi>` and it can be enclosed in an `<mrow>` just in case (if it would end up inside an `<mfenced>` there will be a separator between the two parts if not).

So if you can please fix those and add some tests and it should be good to go.

**Comment by pragyanmehrotra** [comment]
Yes, definitely, on it.

**Comment by oscargus** [comment]
Oh, and I think it is the best to always encapsulate text in a tag, either `<mo>` or `<mi>`. While it renders OK, I believe that it should be encapsulated. This holds for most of the methods.

**Comment by pragyanmehrotra** [comment]
I have updated the functions pls have a look at it and let me know if they need any change so that I could start working on the tests.

**Comment by oscargus** [comment]
Looks good!
after16284_2

I think it would be good to rewrite the release notes. While it is a good idea to list it like you have done, it will show up in a non-ideal way in the actual release note (see the first comment). Probably better to write a single (long) entry listing all methods or name a few and write "etc" or something.

**Comment by pragyanmehrotra** [comment]
Oh yeah, Thanks for pointing that out.

**Pull request merged**
