### PR TITLE
fix(core): disallow `(x**z*y**z) -> (x*y)**z` in as_base_exp, with fix to laplace_transform

### PR DESCRIPTION
**Pull request by hanspi42**
Without assumptions on x, y and z it does not hold that `(x**z)*(y**z)`
is equal to `(x*y)**z` so as_base_exp should not return `(x*y, z)`.

#### Release Notes

* core
   * `Mul.as_base_exp` no longer allows `(x**z*y**z) -> (x*y)**z` unless `z` is an integer. Previously this could lead to incorrect results if the bases are not positive and the exponent is not an integer.
* integrals
   * rules containing `sqrt(a*t)` and `sqrt(a/t)` and their test cases have been removed from the rule-based `laplace_transform` method, they will be re-instated after a mathematical investigation into the validity of the respective table entries in Bateman54

### CODE REVIEW

**Comment by hanspi42** [comment]
Hi @oscarbenjamin, I will have to look into what Bateman did in 1954, for the time being I have commented out all rules with `sqrt(a*t)` and `sqrt(a/t)`. I consider that Bateman's tables could be wrong in these cases. I have also commented out all test cases because they test whether said rules trigger and are not mathematically necessary. This PR bases on #26885 by @oscarbenjamin

**Comment by oscarbenjamin** [comment]
> I consider that Bateman's tables could be wrong in these cases

Possibly or perhaps they use a different convention or something. There are conceptually different ways of thinking about the an expression like `sqrt(x)` that are often not spelled out. SymPy has one particular convention and it is not always easy to confirm whether other sources match that convention in all cases.

**Comment by oscarbenjamin** [comment]
Thanks Hanspeter. I guess more investigation will be needed for the rule-base Laplace method but I expect that most of those rules could be restored.

For now we remove a longstanding bug in a basic operation like `as_base_exp` and it is always important to get these kinds of basic bugs fixed so that other things don't depend on them.

**Comment by hanspi42** [comment]
> Thanks Hanspeter. I guess more investigation will be needed for the rule-base Laplace method but I expect that most of those rules could be restored.

Probably yes, I'll look into it, but it may not be worth the effort. I don't see any actual apptlication for any of these transforms, they might just turn up in student exercises, and possibly not even that.

**Pull request merged**
