### PR TITLE
Simplify Linsolve output

### LINKED ISSUE #10056: linsolve does not find solutions that solve_linear_system does
For some overdetermined systems, `linsolve` does not find solutions which `solve_linear_system` does. For example:

```python
In [12]: from sympy.solvers.solveset import linsolve
from sympy import *

A, B, J1, J2 = symbols('A B J1 J2')

augmatrix = Matrix([
    [ 2*I*J1,  2*I*J2,-2/J1],
    [-2*I*J2, -2*I*J1, 2/J2],
    [ 0,  2, 2*I/(J1*J2)],
    [2, 0,  0],
])

linsolve(augmatrix, A, B)
solve_linear_system(augmatrix, A, B)

Out[16]: EmptySet()

Out[17]: {A: 0, B: I/(J1*J2)}
```
On the other hand:

```python
In [23]: augmatrix = Matrix([
    [2*I*J2,-2/J1],
    [-2*I*J1, 2/J2],
    [ 2, 2*I/(J1*J2)],
])

linsolve(augmatrix, A)
solve_linear_system(augmatrix, A)

Out[24]: {(I/(J1*J2),)}

Out[25]: {A: I/(J1*J2)}
```

works fine.

I understand that this issue is problematic because `solve_linear_system` is being deprecated in favour of  `linsolve`: #10000.

### PR DESCRIPTION
**Pull request by aktech**
Fixes #10056 

@Moovi  @asmeurer  @hargup

### CODE REVIEW

**Comment by MooVI** [comment]
I think this fixes my issue, but one wonders whether the default behaviour of `rref` in general shouldn't be changed to avoid these sorts of issues. I notice in matrices.py both `rank` and `QRDecomposition` call rref without simplify, which risks confusing users. You would think it should be an option which you could turn off for speed if you knew it was safe, rather than the other way around.

**Comment by aktech** [comment]
@MooVI  I agree there is some issue with the default behavior of `rref`. Thought currently setting the simplify flag `True` seems like the best option to avoid the overhead of lot of pre-processing. We can remove that flag when we have the issue with `rref` fixed. Can you open an issue for the current behavior of `rref`?

**Comment by MooVI** [comment]
Agreed about the flag.

Will open the issue now.

**Comment by moorepants** [comment]
simplification should almost always be an optional thing. If the expressions in these matrices are large, you may get super slow simplification.

**Comment by aktech** [comment]
@moorepants  There are some problem with flags, see https://github.com/sympy/sympy/issues/10056#issuecomment-154123365

**Comment by MooVI** [comment]
@aktech You need to add `simplify` to the results [here](https://github.com/aktech/sympy/blob/d3dcc6040ec530730baef113ae07a9a5895ac1d3/sympy/solvers/solveset.py#L1255) as well, else it is not simplifying all the results! This will fix the failure in `test_formal.py`.

**Comment by aktech** [comment]
@MooVI  Yes, Indeed.

**Comment by MooVI** [comment]
@aktech Great, it worked. Could we get this merged so I can fix #10280 ? Cheers

**Comment by aktech** [comment]
Will commit in 24hr if no objection.

**Comment by MooVI** [comment]
Cool, thank you.

**Pull request merged**
