### PR TITLE
Added gcd to Rational

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed
Based on discussions in #21900, it seems to be slightly faster to explicitly mention the gcd of rational numbers on creation.

#### Other comments
Moved some computation to speed things up slightly.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by smichr** [comment]
LGTM

**Comment by oscarbenjamin** [comment]
I think `Rational(1, 2, 1)` seems quite cryptic. Doesn't look like the gcd parameter is documented anywhere.

It would be better to have a different constructor for this I think.

If we really want to make Rational faster then we should have it use `MPF` internally (https://github.com/sympy/sympy/issues/20598)

There is a `MPQ` class now that can be used:
https://github.com/sympy/sympy/blob/81f1401300956b27e5dff870c37022421c7e37bb/sympy/external/gmpy.py#L86

**Comment by oscarbenjamin** [comment]
Maybe there could be a function like `rat_no_gcd` or something that makes it clearer what this is doing. Perhaps some of these files files could do:
```
from sympy.core.numbers import Rational

R = Rational.no_gcd

half = R(1, 2)
```

**Comment by robinechuca** [comment]
Maybe I'm wrong but it seems to me that for better performances, we shouldn't rebuild a rational each time from a class but just use an instance.
```
sqrt(4 - 2*sqrt(2)): S.Pi*Rational(3, 8, 1),
2/sqrt(2 + sqrt(2)): S.Pi*Rational(3, 8, 1),
```
Could be
```
pi_rat_3_8 =  S.Pi*Rational(3, 8, 1)
sqrt(4 - 2*sqrt(2)): pi_rat_3_8,
2/sqrt(2 + sqrt(2)): pi_rat_3_8,
```

**Comment by oscargus** [comment]
I think that you are correct @robinechuca 

There are many instances in the code where the same thing is computed again.

Another, semi-related, question: Rational uses standard integers (non-sympified). Wouldn't these be sympified every time they are used?

**Comment by smichr** [comment]
> Doesn't look like the gcd parameter is documented anywhere.

I add documentation in #21944. The additions here, at least, mark where future code should focus on using a better Rational construction. This, at least, is doing no harm and is easy to find and undo. Except for large primes, however, I doubt that any of this has an impact on the overall runtime of code in which it is used.

**Comment by oscargus** [comment]
Not sure how to properly benchmark it. Just a simple `%timeit` seems to implicate that not using the last 1 is actually slightly faster, which seems unintuitive.

**Pull request closed without merging**
