### PR TITLE
[1.4] Added CDF and corrected PDF for Gumbel Distribution

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References
[1] Fixes https://github.com/sympy/sympy/issues/16521
[2] https://en.wikipedia.org/wiki/Gumbel_distribution
[3] Conitnued #16523 

#### Brief description of what is fixed or changed
PDF for GumbelDistribution has been corrected with changes made at appropriate places(docs, tests, code)
CDF for GumbelDistribution has been added. Associated test have also been added.

#### Other comments
Code:
```
from sympy import *
import sympy.stats as ss
beta, mu = symbols('beta, mu', real=True)
x = symbols('x', real=True)
X = ss.Gumbel('X', beta, mu)
print(ss.cdf(X).doit())
```
Outputs:
Prior to this addition:
`Lambda(_z, exp(b/eta)*Integral(exp(-_x/eta)*exp(exp(-_x/eta)*exp(b/eta)), (_x, -oo, _z))/eta)`

With this addition:
`Lambda(_z, exp(-exp(_z - b)/eta))`
#### Release Notes

* stats
  * PDF of Gumbel distribution corrected.
  * CDF of Gumbel distribution added.

### CODE REVIEW

**Comment by czgdp1807** [comment]
@sidhantnagpal Please see this for merging into 1.4.

**Comment by czgdp1807** [comment]
The tests are passing on my local system for `Python 3.6.7` and `Python 2.7.15`. I think they will pass here too. Though let's wait.
I apologise for the delay caused due to my mistakes.

**Comment by czgdp1807** [comment]
@sidhantnagpal The tests are passing. Please provide your comments/reviews on any changes to make.

**Comment by sidhantnagpal** [comment]
You can make changes to existing pull requests by force-pushing if you run into troubles, but it is OK if it was your first time.

The changes here look fine to me.

**Comment by czgdp1807** [comment]
@sidhantnagpal Actually, I later searched on google, and got to know that, `git cherry-pick` would have worked there. I would have applied my commits on `1.4` from `stats_simple`.
Thanks for telling about, `force-pushing`. I will look more about it.

**Pull request merged**
