### PR TITLE
More improvements for symengine backend

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
New timings with #11676 and FLINT integer enabled.

n | SymEngine + SymPy | SymPy only | Speedup
------------ | ------------- | ------------- | -------
10|0.120 s|4.145 s|34.54x
15|0.267 s|14.827 s|55.53x
20|0.541 s|36.166 s|66.85x
30|1.627 s|131.874 s|81.05x
40|3.735 s|347.113 s|92.93x
50|7.368 s|756.875 s|102.72x
60|11.856 s|1671.174 s|140.95x

**Comment by isuruf** [comment]
Ping

**Comment by isuruf** [comment]
@certik, ping

**Comment by certik** [comment]
@isuruf sorry, I missed this PR. Nice! Great job. I assume it's not this PR that brings the speedup, but the overall improvements that were done since the last benchmarks.

**Review by certik — APPROVED** [review]
The changes are great.

**Comment by isuruf** [comment]
Yes.
Thanks for the review

**Pull request merged**
