### PR TITLE
Add rewriting method for permutation group to finite set

### PR DESCRIPTION
**Pull request by sylee957**
#### Brief description of what is fixed or changed

I think that it is sometimes useful to rewrite `PermutationGroup` to show all its members.

#### Release Notes

- combinatorics
  - Added rewriting method for `PermutationGroup` to `FiniteSet`

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Does it make sense that rewrite returns a different type of object? In this case we go from a group to a set. Is that really a "rewrite"?

I don't know the combinatorics module at all but is there a method/attribute to get the set associated with a group? That would seem like something generally useful and I expect it would solve the same problem.

**Comment by oscarbenjamin** [comment]
Rather than `as_finite_set` could there be an attribute to get the set for any group (including infinite groups)?

**Comment by sylee957** [comment]
For any other groups in combinatorics module, for example, `free_group` elements may not work with `Set` or almost every other sympy objects because it doesn't have any support for `Basic`, `sympify`.

For other set representations for groups, I guess `ImageSet` can be used, but I anticipate that things may grow out of the scope.
For example, there should be other changes to make `FreeGroupElement` compatible with `Basic`, and also some new symbolic nodes to notate an abstract product would have to be made to build up a compatible lambda notation.

So I had narrowed down the concerns only with permutation groups and the representation to the finite sets. I don't know if there would be any easier idea though.

**Comment by oscarbenjamin** [comment]
I wasn't suggesting you should add this to all groups but just that if we wanted to do that *eventually* then maybe `as_finite_set` isn't a good name since many groups won't have finite sets.

I haven't used any of SymPy's group features but since the definition of a group is a set with an operation it seems natural to me that there would be an API to get the set as some kind of Set.

**Comment by sylee957** [comment]
But having a unified method like `as_set` may turn out to be more ambiguous for use, because it won't be clear which kind of set should be returned.
For example, there can also be an `ImageSet` representation, for this `PermutationGroup` case.

And it would still make things not confusing in any mathematical context, if infinite groups have `as_finite_set` downright not implemented.

**Comment by oscarbenjamin** [comment]
How would you write the permutation group as an image set?

**Comment by sylee957** [comment]
I may be wrong if it is possible or not, but I had expected some definitions like 
image
from https://proofwiki.org/wiki/Definition:Word_(Abstract_Algebra)#Definition
where `S` is the set of the generator of the group.

**Comment by sylee957** [comment]
And I would also want to revert to using `rewrite` instead of `as_finite_set` or other way.
I don't think that it can lose the context. I see groups are often compatible with set operations like union, intersection, subset in various materials.
And the resulting union or intersection can be reduced to a set if it loses any property to be considered a group.

And other thing can be a programmatic advantage of using a more well-designed rewriting scheme than having a bunch of `as_`.

**Comment by oscarbenjamin** [comment]
I don't know how you would write that as an ImageSet in SymPy. I would probably call it the Closure of a the generator set under composition. Maybe it makes sense to have a class that represents closures for different operations in that way.

If there was a Group.set attribute then you could rewrite the Set as FiniteSet: `G.set.rewrite(FiniteSet)`. Then there's no ambiguity about whether you are handling a Set or a Group.

**Comment by sylee957** [comment]
`Permutation` already uses the name `list` to return python list object, so I had just used a more longer name `underlying_set` instead to reserve `set`.
`_contains`, `_measure`, `_boundary` may have to be defined for a set notation to work, but I'd bet other things may not make sense with permutation groups

**Comment by oscarbenjamin** [comment]
I didn't expect `SetOf` to be a symbolic object. Maybe it is necessary to have a new `Set` class to represent the set corresponding to a permutation group. Did you add this because the existing Set classes cannot represent this kind of Set (except as a FiniteSet)?

**Comment by sylee957** [comment]
I'm closing this. I guess this is not a difficult change to begin from scratch because there already is `PermutationGroup.set`. 

And I'd expect a more generalized patch to align groups, sets, and ring classes that were made in sympy.

**Pull request closed without merging**
