### PR TITLE
Enable an indexed summation of matrices

### PR DESCRIPTION
**Pull request by zanzibar7**
- on AddWithLimits.expand() distribute sum to each matrix entry
- Sum.doit() recognizes matrix summands and distributes
- Matrix.doit() maps to matrix entries
- includes 1 new test

### CODE REVIEW

**Comment by cbm755** [comment]
I think this is a good change, I'd like to see it merged.

1.  @zanzibar7 can you fix the merge conflict?

2.  Also, have we really tested the bit where "Matrix.doit() maps to matrix entries"?  How about an explicit test of that:
````
M = Matrix([[Add(x, x, evaluate=False)]])
assert M[0] != 2*x
assert M.doit() == Matrix([[2*x]])
````

Other than that, I'm +1.  Can someone else merge this (or give further review if that's necessary).

**Comment by zanzibar7** [comment]
I'll address this in the next few days.

**Comment by zanzibar7** [comment]
@smichr - Is there some particular reason this pull request hasn't gotten any consideration?  I can do some more work if needed.

**Comment by moorepants** [comment]
@zanzibar7 I think it is just that we have a finite amount of volunteer time. Have you take care of @cbm755's concerns. Seems like you may need to merge in the upstream master branch and fix conflicts.

**Comment by zanzibar7** [comment]
Thanks, just checking.  Very sympathetic to issues of limited time.

I have fixed the merge conflict and included @cmb755's test.

**Comment by moorepants** [comment]
Ok, I'll merge when Travis finishes. Remind me if I haven't.

**Pull request merged**
