### PR TITLE
Use the proper theano printer-related function wrappers in test cases

### PR DESCRIPTION
**Pull request by craymichael**
#### References to other Issues or PRs
Amends https://github.com/sympy/sympy/pull/15885

#### Brief description of what is fixed or changed
`test_complexfunctions` uses `theano_code` instead of `theano_code_` and `test_constantfunctions` uses `theano_function` instead of `theano_function_`, which may yield unexpected results due to how the wrapper handles cache. This PR uses the correct definitions.

#### Other comments
--

#### Release Notes

* printing
  * Amended a test case of `TheanoPrinter` constant and complex functions

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This looks good.

I'm going to close and reopen to restart the tests.

**Comment by craymichael** [comment]
I just took care of the merge conflict. This should still be good to merge once the tests finish

**Comment by oscarbenjamin** [comment]
Sorry I forgot abut this. Are you aware that in the mean time sympy has now moved to supporting aesara? I'm not sure if that affects this patch or not.

**Comment by oscarbenjamin** [comment]
See here:
https://groups.google.com/g/sympy/c/Z6WWUuVFH6c/m/rGIiS-p6AwAJ
and also here:
https://github.com/sympy/sympy/pull/21087

**Comment by oscarbenjamin** [comment]
CC @brandonwillard

**Comment by craymichael** [comment]
No worries - and I have not, thanks for pointing that out. The move makes sense.

I am not familiar with aesara beyond what Theano was, but the fixes in this PR simply ensure that the theano printer uses the correct wrappers in test functions (just making sure that the cache for `theano_code` and `theano_function` is empty by default).

**Comment by oscarbenjamin** [comment]
Okay, thanks. I'm reassured to hear from someone who is (I assume) using sympy with theano.

**Pull request merged**
