### PR TITLE
.github/workflows/ci-sage.yml: Fixup 'on' specification

### PR DESCRIPTION
**Pull request by mkoeppe**
#### Brief description of what is fixed or changed
Fix up the `on push` specification so that the workflow actually runs on release branches

#### Other comments
@oscarbenjamin 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Looks like it's running now.

Will the tests potentially pass now or there still doctests to update?

**Comment by oscarbenjamin** [comment]
I was about to put out the release candidate but I'll wait now to see the CI report.

**Comment by mkoeppe** [comment]
> Will the tests potentially pass now or there still doctests to update?

Still need to update some doctests on the Sage side.

**Comment by oscarbenjamin** [comment]
There's a couple of new failures that I didn't see before:
```
 sage -t --random-seed=0 src/sage/functions/min_max.py
**********************************************************************
File "src/sage/functions/min_max.py", line 236, in sage.functions.min_max.MaxSymbolic._evalf_
Failed example:
    r
Expected:
    sqrt(2) - cos(1)
Got:
    0.873911256505000
**********************************************************************
File "src/sage/functions/min_max.py", line 238, in sage.functions.min_max.MaxSymbolic._evalf_
Failed example:
    r.n()
Expected:
    0.873911256504955
Got:
    0.873911256505000
```
I'm not sure the cause of those.

**Comment by oscarbenjamin** [comment]
> There's a couple of new failures that I didn't see before:

I'm having trouble reproducing these.

**Comment by oscarbenjamin** [comment]
Maybe those failures are from a change in sage rather than sympy.

**Comment by mkoeppe** [comment]
> There's a couple of new failures that I didn't see before:
> 
> ```
>  sage -t --random-seed=0 src/sage/functions/min_max.py
> **********************************************************************
> File "src/sage/functions/min_max.py", line 236, in sage.functions.min_max.MaxSymbolic._evalf_
> ```

I cannot reproduce them locally either. They are not caused by the sympy upgrade. They are already present in 9.5.beta1 when built on `archlinux-latest-standard` (https://github.com/sagemath/sage/runs/3593004931)

**Pull request merged**
