### PR TITLE
Added Gitpod Badge in README

### LINKED ISSUE #18328: Add an open with gitpod badge in the readme.
Gitpod launches ready-to-code dev environments for your GitHub or GitLab project with a single click. Thus, having a direct Open with Gitpod badge would be good for the first time contributors and beginners with Sympy.

### PR DESCRIPTION
**Pull request by iamabhishek0**
#### References to other Issues or PRs

Fixes #18328 

#### Brief description of what is fixed or changed
Added the Gitpod Badge to README.md

#### Other comments
Gitpod launches ready-to-code dev environments for your GitHub or GitLab project with a single click.

#### Release Notes

* other
  * README.rst - Added the Gitpod Badge in readme.rst

### CODE REVIEW

**Comment by asmeurer** [comment]
Not sure what this is. Is this just a text editor? I don't think we should have badges and config files for random things that are used by very few people. Couldn't gitpod users configure this themselves? The configuration isn't even SymPy specific.

**Comment by iamabhishek0** [comment]
Many open-source organisation have this badge as it helps beginners and first-time contributors who face difficulty in setting up Sympy for contribution.
If it is not required then I guess I have to close it.

**Comment by moorepants** [comment]
This seems interesting...if it actually sets up a full development environment that someone can work in. If it sets up all this somehow: https://github.com/sympy/sympy/wiki/Development-workflow then that would be a nice way for newcomers to get going.

**Comment by iamabhishek0** [comment]
Yes, we can set it up as mentioned in Development-Workflow, and I think it would a good addition for newcomers.

**Comment by asmeurer** [comment]
Then somebody should test this to see what it is. Do you want to do that @moorepants? I don't want to recommend something that none of the SymPy developers have actually tried.

**Comment by moorepants** [comment]
If someone sets it all up I can click it and see what it does.

**Comment by sylee957** [comment]
Should I be able to set up the `conda` environmnt and download the packages?

I'd specify the common things that are needed for sympy development workflow are:
1. A basic environment with `mpmath` installed.
2. A environment to test out optional dependencies sympy is using (`numpy`, `matplotlib`, `tensorflow`, ...).
3. A environment to test out IPython workflow.
4. A environment to test out documentation build (Sphinx, TeXLive)

And this may sound better if we can be able to share some environment that does this.

**Comment by iamabhishek0** [comment]
I am not sure about `conda` but it comes with pre-installed `virtualenv`
We can create virtual environment using virtualenv and then install the packages.

**Comment by sylee957** [comment]
`virtualenv` can be an alternative to try out after, but if it supports the linux commands, than it can be grab `conda` using `curl`

**Comment by iamabhishek0** [comment]
Yes, it supports Linux Commands. I will try to add conda environments to the scripts

**Comment by czgdp1807** [comment]
Gitpod is itself very nice, looks like its developed on top of VSCode. However, it is used by very few people, so probably we can wait until it gets mature and stable because with the increase in their users they may make certain changes due to which the badge may not work. Let's see what others have to say.

**Comment by czgdp1807** [comment]
Is it possible to obtain about which projects are using it right now on Github or Gitlab?

**Comment by iamabhishek0** [comment]
**freeCodeCamp** - https://github.com/freeCodeCamp/freeCodeCamp
**Gitpod** - https://github.com/gitpod-io/gitpod
**Gatsby** - https://github.com/gatsbyjs/gatsby
**Theia** - https://github.com/eclipse-theia/theia
**Code Institute** - https://github.com/Code-Institute-Org/gitpod-full-template
**4GeeksAcademy** - https://github.com/4GeeksAcademy

**Comment by czgdp1807** [comment]
So, what should we do? Should we add gitpod badge? IMO, -1 for it.

**Comment by czgdp1807** [comment]
Github is launching codespace(or something like that). So, closing it for now. Thanks for contributions.

**Pull request closed without merging**
