### PR TITLE
[PDF] Improve TOC and Index

### PR DESCRIPTION
**Pull request by jfbu**
#### Brief description of what is fixed or changed

Avoid page numbers like this in TOC from PDF:

Capture d’écran 2024-07-27 à 13 27 13

or like this

Capture d’écran 2024-07-27 à 13 27 21

and try to avoid (untested because I did not build the PDF docs locally; but we do use that for our (Sphinx) own docs) things like that in index:

Capture d’écran 2024-07-27 à 13 29 33

Not sure the index will be free of all such glitches but it can only improve it.

Screenshots on 1.13.1 PDF docs as available today.

#### Other comments

None

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by jfbu** [comment]
Sorry I had to force-push, but I succeeded in authoring a typo in such a small commit 😞

**Comment by sylee957** [comment]
Thanks for the PR. However, we'd need someone to verify the PDF builds
I am trying to, but not very familiar with PDF build, and it is quite slow to build and difficult to get it working, so it may take some time.

**Comment by jfbu** [comment]
I tried to build the Sympy PDF Docs but there is a dependency on Chrome for svg to pdf conversion, and I don't have it installed on the macos I currently have access to.  I tried usings [sphinxcontrib.svg2pdfconverter](https://pypi.org/project/sphinxcontrib-svg2pdfconverter/) but one conversion triggered an internal crash of Inkscape 0.92.2, I then tried to install more recent Inkscape but could not see how to use it as a command line binary, which does not seem provided by the dmg.

This being said I am sure the TOC will be fixed by this PR because this can be tested with minimal document where you set manually the LaTeX page counter to 1000 or more, which I did to confirm.  As per the index it works well for Sphinx own docs but Sympy has probably longer full function names so I expect not all overlapping will be fixed but  it is worth a try.

**Comment by jfbu** [comment]
I managed to build locally, here is how TOC and start of general Index look with this PR:

TOC:
Capture d’écran 2024-07-30 à 11 37 25

Index (as expected not all problems are solved, long names flow in margin, but situation is improved)

Capture d’écran 2024-07-30 à 11 35 42

Looking again at index I wonder if it wouldn't be better to not reduce fontsize but rather drop 2-column display in favor of 1-column display.

Maybe I will push a commit to that effect later. The `\raggedright` definitely should be kept even with 1-column I think.

**Comment by jfbu** [comment]
I have pushed a commit to render the general index on one-column, this is the only way to  make it ok.

The screenshot here is not exactly what this PR does, because it was with an index generated by xindy, not makeindex, so the frirst heading differs, but it gives the idea.

Capture d’écran 2024-07-31 à 00 26 13

I browsed the index and there are only  a few places (at letter S ... for `sympy`...) where some lines are short and page looks not filled.  I do not see other ways to have a readable index.

The module index is still on two columns.

**Comment by asmeurer** [comment]
Unfortunately, Chrome is literally the only software that converts the SVGs in our docs to PDF correctly (see https://github.com/sympy/sympy/pull/22468). Unless that's changed or there's some way to fix the SVGs we have to stick with it. At any rate, Chrome is much easier to install the Inkscape for most users.

**Comment by jfbu** [comment]
> Unfortunately, Chrome is literally the only software that converts the SVGs in our docs to PDF correctly (see #22468). Unless that's changed or there's some way to fix the SVGs we have to stick with it. At any rate, Chrome is much easier to install the Inkscape for most users.

On building locally I had warnings from chromium which later I have seen in the GitHub actions as well, for example [there](https://github.com/sympy/sympy/actions/runs/10170020818/job/28128916368?pr=26868)  (I am not sure this will open up, it was too slow and I need sleep now, basically take any test/sphinx and you should see it).

**Comment by asmeurer** [comment]
Looks like the svg-to-pdf extension is incorrectly printing the Chrome command as an error https://github.com/sympy/sympy/blob/1a7afca81a3b4bcf5c60a41f04c27eb677309d6d/doc/ext/convert-svg-to-pdf.py#L68. There isn't actually anything wrong with it. The code would actually fail the CI if it wasn't functioning, and I also just verified locally that the PDFs are being generated correctly.

**Comment by jfbu** [comment]
> logger.error(command)

!!!!!

**Comment by asmeurer** [comment]
I fixed the Chrome `logger.error` thing at https://github.com/sympy/sympy/pull/26902

**Pull request merged**
