### PR TITLE
Passing printer parameters on from init_session() to init_printing()

### PR DESCRIPTION
**Pull request by hansenms**
This commit makes sure that init_session is able to pass printers on to init_printing.

### CODE REVIEW

**Comment by asmeurer** [comment]
Can you copy the documentation for these options from the `init_printing` docstring into the `init_session` docstring?

**Comment by asmeurer** [comment]
+1 otherwise

**Comment by hansenms** [comment]
@asmeurer, done

**Comment by hansenms** [comment]
It's a little unclear to me what is failing in the tests. Any hints would be appreciated.

**Comment by jksuom** [comment]
Two jobs were failing but passed after restart. The failures seemed unrelated to this PR.

**Comment by hansenms** [comment]
@jksoum, thanks! Thought I had broken something. Let me know if any other fixes are needed for the PR.

**Pull request merged**
