### PR TITLE
Fixed typo in diophantine

### LINKED ISSUE #18114: ImageSet of n**2-1 returns EmptySet as intersection with Integers (diophantine bug)
```
In [1]: ImageSet(Lambda(n, n**2 - 1), S.Integers).intersect(S.Integers)
Out[1]: ∅
```

### LINKED ISSUE #18122: diophantine gives wrong result depending on alphabetic order of variables (_diop_quadratic)
```
In [1]: diophantine(x**2 - y)
Out[1]:
⎧⎛    2⎞⎫
⎨⎝t, t ⎠⎬
⎩       ⎭

In [2]: diophantine(y**2 - x)
Out[2]: {(0, 0)}
```
Both cases end up (correctly AFAICT) in `_diop_quadratic` with a discriminant of 0. Source link:
https://github.com/sympy/sympy/blob/4ff82aaf85967bcf040871912fe872e16a9895cd/sympy/solvers/diophantine.py#L946
Then the algorithm ensures that it's the first variable that's having a nonzero coefficient for the quadratic term. It does so by calling itself with the variables switched if necessary:
https://github.com/sympy/sympy/blob/4ff82aaf85967bcf040871912fe872e16a9895cd/sympy/solvers/diophantine.py#L975-L976
It's in this "inverted" solver call that the incomplete `(0,0)` solution arises.

I'll leave it up to someone more familiar with this part of the codebase to find the actual error.

### PR DESCRIPTION
**Pull request by Smit-create**
Fixed typo in diophantine
#### References to other Issues or PRs

Fixes #18122 
Fixes #18114

#### Brief description of what is fixed or changed
It now correctly provides the output of 
```
>>> diophantine(x**2-y)
(t, t**2)
>>> diophantine(y**2-x)
(t**2, -t)

```
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by jksuom** [comment]
Please add a test.

**Comment by gschintgen** [comment]
This also fixes #18114.

**Comment by Smit-create** [comment]
> Please add a test.

Okay, I will add it.

**Comment by jksuom** [comment]
Thanks!

**Pull request merged**
