### PR TITLE
FIX: ensure autoscale_view gets called

### LINKED ISSUE #19051: Plots are displaying incorrectly on the development documentation website
See: https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam.html#sympy.physics.continuum_mechanics.beam.Beam.plot_bending_moment

Other possible related issues:

- #18901
-  #19023
- #18974

Here are a couple of examples:

image

image

### PR DESCRIPTION
**Pull request by tacaswell**
#### References to other Issues or PRs

#19051

Alternative to #19087

#### Brief description of what is fixed or changed

In mpl <=3.1 the view limits were implicitly and unconditionally
autoscaled as part of setting the scale.  It was by co-incident that
by unconditionally setting the x and y scales when plotting also
triggered the auto-scale logic.  In mpl 3.2+ the view limits are
only autoscaled if changing the scale would could change the
acceptable limits.  As in the default case sympy is changing from
linear -> linear, this autoscaling was no longer applied.

This adds an explicit call to autoscaling to sympy will ensure it
behaves as desired independent of Matplotlib version.

#### Other comments

It is still possible (but unlikely) that we will revert this change on the Matplotlib side.  I think it is best if sympy is explicit about autoscaling and does not rely on unexpected side-effects.

NO ENTRY

### CODE REVIEW

**Comment by moorepants** [comment]
Will this work in for prior versions of matplotlib as well as 3.2+?

**Comment by tacaswell** [comment]
Yes

**Comment by sylee957** [comment]
Unfortunately, this breaks some 3D plots using Line3DCollection #19106

**Comment by oscarbenjamin** [comment]
This PR is now changed so that it looks like it shouldn't affect 3D plots.

@sylee957 can you confirm if this is working now?

**Comment by moorepants** [comment]
This needed to be reverted: https://github.com/sympy/sympy/pull/19087/files to see any effect on the dev build of the docs.

**Comment by oscarbenjamin** [comment]
Thanks @tacaswell

**Pull request merged**
