### PR TITLE
Use upright ``\LaTeX``

### PR DESCRIPTION
**Pull request by ghost**
The ``\LaTeX`` symbol in doc resulted in italic,
whose letterspace is incorrect.
image

I replaced it with ``\mathrm{\LaTeX}``,
which resulted in upright "LaTeX" with correct letterspace.
image

NO ENTRY

### CODE REVIEW

**Comment by normalhuman** [comment]
I wonder, does it make sense for SymPy docs specifically to use a different rendering of `\LaTeX` trademark, compared to any other MathJax-enabled site. If letter spacing is wrong, or if upright font should be used, isn't it an issue with MathJax, to be fixed [at their end](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/input/TeX/jax.js#L972)?

**Comment by TitanSnow** [comment]
It's not a bug of MathJax.

If you have LaTeX installed in your computer, you could try these three LaTeX docs:
```latex
\documentclass{article}
\begin{document}
\LaTeX
\end{document}
```
```latex
\documentclass{article}
\begin{document}
abc $abc$\\
$abcdefghijk$\\
$\mathit{abcdefghijk}$
\end{document}
```
```latex
\documentclass{article}
\begin{document}
$\LaTeX$
\end{document}
```

The first one shows that in LaTeX *text mode*, the `\LaTeX` is upright:
texput-1

The second one shows the difference between LaTeX *text mode* and *math mode*.
In *math mode*, the font is italic with wider letterspace — that’s why I said it’s “wrong”.
That’s by design for math, but not text.
image

The third one will result in compilation error because in LaTeX you can’t use `\LaTeX` in *math mode*.

MathJax is not LaTeX. It’s just *math mode* of LaTeX.
In this way, it should not provide `\LaTeX` command because in math mode you can’t use `\LaTeX`.
But it provides `\LaTeX` maybe because of the common use, which is not compatible with LaTeX though.
In *math mode*, the font is italic with wider letterspace, which is right, not considered a bug of MathJax.

So for trademark use, `\LaTeX` should be upright, as the same as `\LaTeX` in LaTeX *text mode*,
which is the original style.

For other MathJax-enabled sites which use `\LaTeX`, I think they should also be corrected.

**Comment by czgdp1807** [comment]
@normalhuman What should be done to this PR? Should we close it or merge it? @TitanSnow Are you still interested to work on it?

**Comment by jksuom** [comment]
It would probably suffice to remove the backticks around `\LaTeX`.

**Comment by asmeurer** [comment]
I've wondered why mathjax renders the latex logo so poorly. Your explanation makes sense. I think we should clean this up and merge it. It will need a merge conflict resolution and a release notes entry. 

We could also possibly fix this by adding something to the preamble so that \LaTeX does the right thing on its own.

**Comment by czgdp1807** [comment]
I will continue this.

**Comment by czgdp1807** [comment]
Closing in favour of https://github.com/sympy/sympy/pull/18151
Thanks for the contributions.

**Comment by czgdp1807** [comment]
ping @jksuom @asmeurer Let me know if we can merge this once the tests pass.

**Comment by jksuom** [comment]
+1

**Comment by czgdp1807** [comment]
I think some changes were made to `compatibility`. Will update in a new commit. Please don't merge until then.

**Comment by czgdp1807** [comment]
@jksuom @asmeurer I am unable to figure out why [this job](https://travis-ci.org/sympy/sympy/jobs/637293197?utm_medium=notification&utm_source=github_status) is failing. Is it okay to merge even in this case?

**Comment by jksuom** [comment]
It seems that `sympy_benchmarks` was not updated after `range` was removed from `compatibility`. I think it is OK to merge.

**Pull request merged**
