### PR TITLE
Changes to pull request  #12000

### PR DESCRIPTION
**Pull request by nilabja-bhattacharya**
Changes to pull request #12000

### CODE REVIEW

**Comment by gxyd** [comment]
This is not exactly what I had in mind. You would need to use `git cherry-pick` command to use the commits of ayodejiige . That way, ayodejiige will retain the owndership of the commits that he committed in his PR.

As you can see in commits list, that all the commits are authored by you, which shouldn't be the case. Since you are using ayodejiige 's code with a few modifications.

**Comment by nilabja10201992** [comment]
@gxyd I knew I misunderstood, btw should I use `git cherry-pick <adijiiyge_commit_hash>`, to bring the changes to my local repository?

I had done that way but there were branch conflicts, how should I resolve the conflicts?

I'm closing this pull request.

**Comment by gxyd** [comment]
You don't necessarily need to close this PR. You can force push commits to this PR itself, when you do make the changes.

**Comment by nilabja10201992** [comment]
@gxyd Did I do it correctly?

**Comment by gxyd** [comment]
Okay (please don't be mad at me after reading this).
Don't think about `git cherry-pick` for a moment (leave all `git cherry-pick` things for a moment).
i.e leave this branch for a moment.
Can you try to run the commands you ran on https://github.com/sympy/sympy/pull/12000#issuecomment-333450924 with replacing `ayodejiige` with `upstream` i.e run `git push upstream 11668_bare_excepts` .

Let me know how it goes, sorry for all the trouble.

**Comment by gxyd** [comment]
This is how your commits should look like https://github.com/gxyd/sympy/tree/new .

**Comment by nilabja10201992** [comment]
@gxyd return this
```
remote: Permission to sympy/sympy.git denied to nilabja10201992.
fatal: unable to access 'https://github.com/sympy/sympy/': The requested URL returned error: 403
```

**Comment by gxyd** [comment]
Oh, now try that with `origin`, please. i.e. `git push origin 11668_bare_excepts`.

**Comment by nilabja10201992** [comment]
@gxyd what after that?

**Comment by gxyd** [comment]
Visit https://github.com/nilabja10201992/sympy/tree/11668_bare_excepts and click on 'Compare and Pull Request' :dancer:

**Comment by gxyd** [comment]
I am closing this PR in favor of #12000 , when I have addressed the changes.

**Comment by nilabja10201992** [comment]
@gxyd Should I delete this branch?

**Comment by gxyd** [comment]
Yes, you can.

**Pull request closed without merging**
