### PR TITLE
Revived: Travis Code Coverage

### LINKED ISSUE #10519: Try codecov (code coverage)
See https://github.com/cloudpipe/cloudpickle/pull/48#issuecomment-169821928 for an example of why this is cool. We could also try coveralls (see my ancient attempt to get it working at https://github.com/sympy/sympy/pull/1960).

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

Closes #10937
Closes #11974
Closes #13488

Fixes #10519 

Closess #16186

#### Brief description of what is fixed or changed

I've rebased some abandoned projects.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I am definitely in favour of coverage testing so +1 to the general idea.

It does look though as if this has doubled the time taken to run the tests on Travis. Does it actually increase run time locally?

**Comment by sylee957** [comment]
Unfortunately, we only have 50 minutes to build, and the slowdown is critical

**Comment by oscarbenjamin** [comment]
Maybe we should only do coverage testing for the non-slow tests on one Python version.

**Comment by sylee957** [comment]
Still, 45 minutes doesn’t guarantee that it will pass.
I wonder how pypy tests are twice faster

**Comment by oscarbenjamin** [comment]
Are you sure that PyPy is actually doing the coverage measurement?

**Comment by sylee957** [comment]
I see coverage report is not collected in pypy and optional dependencies test

**Comment by oscargus** [comment]
Good idea! Maybe one can do a separate run on a single version split into four just for code coverage? Sort of a waste of CPU cycles to double test things, but could still be worthwhile. For the slow tests (if required) one can run one version (preferably 3.7) split by four as part of the regular tests?

**Comment by oscargus** [comment]
Or run the baseline test split in four with coverage...

**Comment by asmeurer** [comment]
We should only measure coverage for one Python version. The slow tests probably shouldn't be counting toward coverage anyway. We can also skip the external dependency tests if it isn't worth it.  That will result in some lines that aren't marked as covered that actually are, but there wouldn't be very many, and it should be obvious that is the reason. 

Also IMHO doctests shouldn't count toward coverage, since doctests aren't supposed to be tests. If a line is only covered by a doctest that isn't good.

**Comment by smichr** [comment]
Between 3-stage testing and this, testing is improved a lot! Thanks for reviving these. I will let someone else commit when ready since I am not up to speed about all the nuances of testing. (Or just leave a comment saying this is ready to go.)

**Comment by oscarbenjamin** [comment]
So how do I see the coverage?

I note that pytest has some kind of bot for their repo. Here's an example:
[https://github.com/pytest-dev/pytest/pull/4877#issuecomment-469019191](https://github.com/pytest-dev/pytest/pull/4877#issuecomment-469019191)

**Comment by oscargus** [comment]
@oscarbenjamin If you go to https://codecov.io/gh/sympy/sympy (and log in etc) there is a link offering this. Should I click it?

**Comment by oscarbenjamin** [comment]
Oh yeah, looks like it's already reading the coverage from the commits here. I think it would be really good to have the coverage be very visible like it is on pytest.

How would we otherwise see the results of coverage measurement?

**Comment by oscarbenjamin** [comment]
@oscargus can you try clicking it to see what happens? Hopefully it will only apply to this PR since it looks like it can tell which builds have coverage testing.

**Comment by oscargus** [comment]
I clicked it and eventually it lead to a request to the "@sympy account". Not sure if it is exactly what we are looking for but let us see. I guess @asmeurer is the one handling the request?

An alternative is to have the results among the checks. See an arbitrary PR for https://github.com/JabRef/jabref/ There will be a red cross for the check if the code coverage decreases but I assume that one can configure if it prohibits merging.

I think the pattern thing looks quite cool, but also quite confusing (as in more cool than useful). Will it update if more commits are pushed or will a new one be posted?

**Comment by asmeurer** [comment]
I didn't know you could request applications to be installed. I have approved it.

**Comment by asmeurer** [comment]
By the way, please make sure that the comments are disabled for codecov. I've contributed to a few projects that have that and it's extremely annoying.

**Comment by asmeurer** [comment]
And yes, I can configure which status checks are required for merging. Coverage should not be a required status check.

**Comment by asmeurer** [comment]
I guess you should add codecov.yml with

```yaml
comment: off
```

See https://docs.codecov.io/docs/pull-request-comments. 

I'm also curious how it determines whether the status should fail or not. https://docs.codecov.io/docs/commit-status says the default threshold is "auto", but it doesn't say what that means.

**Comment by asmeurer** [comment]
We can also add gitter integration if that interests anyone https://docs.codecov.io/docs/notifications#section-gitter

**Comment by oscarbenjamin** [comment]
What is gitter? Is it what some contributors are describing as "chat"? If so how do you access it?

**Comment by asmeurer** [comment]
Yes, I didn't know you weren't aware of it. https://gitter.im/sympy/sympy

**Comment by asmeurer** [comment]
Maybe we should move the coverage out of the baseline, since it requires more splits. How about doing it in Python 3.6?

**Comment by oscarbenjamin** [comment]
The tests have just passed. Doesn't look like the code coverage bot is still showing in the same place. It says that the comment is "edited". Does that mean that it has updated the comment in place?

**Comment by oscargus** [comment]
@oscarbenjamin I think so. Which makes sense. So that is good!

**Comment by oscargus** [comment]
I think that this can/should be merged now. We can always remove it, but it would be a good addition, both for the PRs and to be able to increase the total test coverage. (Although the rubi integration stands for 8% or so of the missing lines.)

**Comment by sylee957** [comment]
I think the bot comment should be disabled with
```comment: off```

Though it didn't get deleted.
I'm not sure it works as intended with subsequent PRs

**Comment by oscargus** [comment]
Or should we try it for a while and see how it works? I guess it can make contributors more aware about testing and coverage. While they will learn about it from the additional tests, it is not a visually striking as the square thing, so easier to ignore...

**Comment by oscarbenjamin** [comment]
If the bot is turned off and doesn't comment how would we see the coverage results?

**Comment by oscargus** [comment]
There are results in the checks, so the comment is not formally needed.

**Comment by oscarbenjamin** [comment]
Ah okay. Well this looks good to me.

**Comment by sylee957** [comment]
I've added an experiment PR #16186 to check if it uploads any comment

**Comment by asmeurer** [comment]
Looks like we won't be able to see how this really works until we merge this and a report is made for master.

**Comment by oscargus** [comment]
> I'm also curious how it determines whether the status should fail or not. https://docs.codecov.io/docs/commit-status says the default threshold is "auto", but it doesn't say what that means.

Based on some PRs now using it it seems like for the patch, "auto" means that the coverage of the new code should be at least as high as the average coverage:

codecov/patch — 97.61% of diff hit (target 72.94%) 

It seems like it doesn't handle merge commits that cleanly, but I guess it is hard to sort that out in general.

**Comment by asmeurer** [comment]
The bot is still posting comments on PRs https://github.com/sympy/sympy/pull/16189#issuecomment-470539839.

**Comment by oscargus** [comment]
Weird. It only seems to happen to some PRs. Not my last PR #16192 though.

**Comment by asmeurer** [comment]
I wrote an email to their support about it.

**Pull request merged**
