### PR TITLE
Allow a reference frame to be oriented to more than one other reference frame

### PR DESCRIPTION
**Pull request by shattar**
#### References to other Issues or PRs
none

#### Brief description of what is fixed or changed
Allow a frame to be oriented with more than one other frame without clearing the orientation of the previous frame.

### CODE REVIEW

**Comment by shattar** [comment]
@moorepants Thoughts on this change?

**Comment by moorepants** [comment]
@shattar can you explain more clearly what this solves? What is the current behavior? What is the use case?

This will also need release notes as per: https://github.com/sympy/sympy/wiki/Writing-Release-Notes

**Comment by moorepants** [comment]
Merge conflicts also need to be addressed.

**Comment by czgdp1807** [comment]
@shattar Any updates? Please respond. This PR will be closed if no response is received. However, feel free to re-open it if you want to continue and complete it. Thanks for the contribution.

**Comment by czgdp1807** [comment]
It looks like no issue is fixed by this and it is not referenced by any other PR/issue. So, for now I am closing this but if you think it can be re-opened please let us know by commenting below. Thanks for your contributions.

**Pull request closed without merging**
