### PR TITLE
Partial cleanup in plotting.pygletplot

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed
Made some optional argument explicit according to #14030

#### Release Notes

* plotting
  * Added explicit optional arguments to parts of plotting.pygletplot

### CODE REVIEW

**Comment by asmeurer** [comment]
See also https://github.com/sympy/sympy/pull/14748. Actually I'd like to remove the pygletplot module, because as far as I can tell, it doesn't even work (https://groups.google.com/d/msg/sympy/VN3lSNZ0kOw/O9TVBeyXAAAJ). Are you able to get a working plot with the pygletplot module?

**Comment by oscargus** [comment]
I spent some time today and actually made it work. This PR can sort of be neglected (stupid typo clearly showing that I had not been that careful before posting it).

You are completely correct in that it will not work directly as there are fundamental issues with the code (functions not returning values which should be returning values, imports not working, among others).

I got it to the state where I can get a window up and rotate the plot, both from the command line and from Spyder. I had to disable some things and it still throws a few exceptions. One at startup which seems to be "OK" in the sense that it still works, one at closing which is annoying but I guess one can live with, and sometimes one when right-clicking. All these seems to come from the pyglet part of the code. Some probably because of sympy

`  File "/nobackup/local/anaconda3/lib/python3.7/site-packages/sympy/plotting/pygletplot/plot.py", line 255, in show
    self._window.activate()
  File "/nobackup/local/anaconda3/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 593, in activate
    xlib.RevertToParent, xlib.CurrentTime)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type`

Some not obvioulsy so:

`Uncaught exception in event loop: name 'c_double' is not defined`

`File "/nobackup/local/anaconda3/lib/python3.7/site-packages/pyglet/gl/gl_info.py", line 170, in <listcomp>
    imajor, iminor, irelease = [int(v) for v in ver.split('.', 3)[:3]]
ValueError: invalid literal for int() with base 10: ''`

I do not have time to look at it more today and it will take some time to get a PR as I started trying out in a non-git-version of the source (plus that it is rather messed up after trying lots of stuff), but hopefully I can get a PR that brings it up to almost acceptable operation for digging up the final issues. (Most of the remaining issues happens in the threaded part of the code, so pretty tedious to dig into it...)

Related to the email-thread: I do not think it has been working since the code was moved to Github. Trying to look back here didn't really give much clues of what was wrong. And there were wrong things in there...

**Comment by asmeurer** [comment]
Be sure to start off of my branch from https://github.com/sympy/sympy/pull/14748 for any changes you make. I have already fixed some of the issues you described. If you want, you can make a pull request to my fork to my pyglet-fixes and I will merge it, so that it becomes part of that PR. Or you can make a new pull request here based on my pyglet-fixes branch. The second way is probably better since I don't intend to work on this myself anymore.

I know for a fact that pyglet has never worked in Python 3, because there is code that I fixed in that PR that cannot work in Python 3 (for instance, absolute instead of relative imports). But I've never been able to tell if it works in Python 2 because pyglet support has always been shaky on macOS anyway, and I don't have easy access to a Linux machine (and running in Docker has its own issue because it needs access to the GUI).

**Comment by oscargus** [comment]
OK! I'll consider #14748. I solved the imports in a different way which works (at least) for Python 3. Not so good at the import formalities though, so we'll see what you think. There are quite a few things more I have changed, but also some which I haven't (and I now better understand some of the original code, seeing what you changed).

**Comment by oscargus** [comment]
I'll close this as everything is also in #15772

**Pull request closed without merging**
