### PR TITLE
Fixed 'simplify' changing state of internal random generator

### LINKED ISSUE #22592: `simplify` changes state of internal random generator
I'm afraid [`sympy.core.ramdom`](https://github.com/sympy/sympy/blob/4489b4c7c51a65966b1a95f2af6f7e0c8c461794/sympy/core/random.py#L1-L10) brings back an old issue with `random` in `sympy`. 

See
```
>>> from sympy import I, simplify
>>> from sympy.core.random import rng
>>> rng.getstate()[1][-1]
624
>>> simplify(-I)
-I
>>> rng.getstate()[1][-1]
497
```
actually this comes from an lazy import inside of `simplify`

```
>>> from sympy.core.random import rng
>>> rng.getstate()[1][-1]
624
>>> from sympy.physics.units.quantities import Quantity
>>> rng.getstate()[1][-1]
489
```
The actual problem seems to be deep in the units system when it comes to multiply when it comes to multiply two units like `mass * time`

https://github.com/sympy/sympy/blob/52f606a503cea5e9588de14150ccb9f7f9ed4752/sympy/physics/units/systems/length_weight_time.py#L102

### PR DESCRIPTION
**Pull request by mohajain**
#### Brief description of what is fixed or changed
Fixes #22592

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by mohajain** [comment]
I applied the diff you suggested. Please have a look @oscarbenjamin

**Comment by oscarbenjamin** [comment]
There should be a test for this.

Need to test that something like this outputs a consistent result:
```python
from sympy import *
from sympy.core.random import seed, randint

seed(4)
prod(symbols('x:10')) # invoke the assumptions system
print(randint(0, 5))
```
That will need to be run in a subprocess though to avoid interactions with the cache.

**Comment by mohajain** [comment]
Okay. How can we test something like this? What would you like me to do?

**Comment by mohajain** [comment]
@oscarbenjamin could you please help?

**Comment by oscarbenjamin** [comment]
We can just have a test along these lines using subprocess:
https://docs.python.org/3/library/subprocess.html

We should make sure that the test is something that currently fails but that doesn't fail with this PR.

**Comment by sylee957** [comment]
This is already fixed in #22592

**Pull request closed without merging**
