### PR TITLE
Fixed typo in sympy/polys/factortools

### LINKED ISSUE #19360: factor(extension=sqrt(2)) hangs
```julia
In [1]: e = (sqrt(2)*x - y)**2                                                                                                    

In [2]: e                                                                                                                         
Out[2]: 
          2
(√2⋅x - y) 

In [3]: expand(e)                                                                                                                 
Out[3]: 
   2               2
2⋅x  - 2⋅√2⋅x⋅y + y 

In [4]: expand(e).factor(extension=[sqrt(2)]) # hangs
```

### PR DESCRIPTION
**Pull request by vaish3496**
#### References to other Issues or PRs

Fixes #19360

#### Brief description of what is fixed or changed
Fixed typo in `sympy/polys/factortools.py`

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by namannimmo10** [comment]
Please add a regression test and write "NO ENTRY" in release notes.

**Comment by vaish3496** [comment]
@namannimmo10 Can you please tell me why the Travis CI build failed?
Also what regression test do you want me to put? Sorry for bothering but I am new to open source.

**Comment by oscarbenjamin** [comment]
It seems the change here has broken something or exposed another problem:
```julia
In [2]: expand(factor(expand((x - I*y)*(z - I*t)), extension=[I]))                                                                
Out[2]: x - ⅈ⋅y
```

**Comment by jksuom** [comment]
`dmp_sqf_part` gives a wrong result for `f = expand((x - I*y)*(z - I*t)`. It works by dividing `f` by the gcd of `f` and its derivative wrt the first generator `x`. That will erase factors like `z - I*t` that are independent of `x`. It may be possible to fix the algorithm by taking the gcd of `f` and all of its derivatives.

**Comment by jksuom** [comment]
This is a patch for `dmp_sqf_part`. It handles all variables.
```
--- a/sympy/polys/sqfreetools.py
+++ b/sympy/polys/sqfreetools.py
@@ -17,7 +17,7 @@
     dmp_raise, dmp_inject,
     dup_convert)
 from sympy.polys.densetools import (
-    dup_diff, dmp_diff,
+    dup_diff, dmp_diff, dmp_diff_in,
     dup_shift, dmp_compose,
     dup_monic, dmp_ground_monic,
     dup_primitive, dmp_ground_primitive)
@@ -252,7 +252,9 @@ def dmp_sqf_part(f, u, K):
     if K.is_negative(dmp_ground_LC(f, u, K)):
         f = dmp_neg(f, u, K)
 
-    gcd = dmp_gcd(f, dmp_diff(f, 1, u, K), u, K)
+    gcd = f
+    for i in range(u + 1):
+        gcd = dmp_gcd(gcd, dmp_diff_in(f, 1, i, u, K), u, K)
     sqf = dmp_quo(f, gcd, u, K)
 
     if K.is_Field:
```

**Comment by vaish3496** [comment]
@jksuom Can I make the given changes in `sqfreetools.py`
`gcd = f`
`for i in range(u + 1):
     gcd = dmp_gcd(gcd, dmp_diff_in(f, 1, i, u, K), u, K)`

which will then resolve the issue?

**Comment by jksuom** [comment]
> which will then resolve the issue

I hope so. But there may be other issues.

**Comment by jksuom** [comment]
BTW, the notebooks should not be included in the PR.

**Comment by vaish3496** [comment]
@jksuom Can you tell me how to discard the notebooks from the commit? Or do I have to make a new commit?

**Comment by jksuom** [comment]
How did the notebooks get there? Did you run `git commit -a`?

**Comment by vaish3496** [comment]
@jksuom 

> How did the notebooks get there? Did you run git commit -a?


No
`git commit -m [Message]`

**Comment by vaish3496** [comment]
@jksuom I have deleted the .ipyng files in the new commit. Sorry for the inconvenience.

**Comment by vaish3496** [comment]
@oscarbenjamin @jksuom How to deal with "The Travis CI build could not complete due to an error"?

**Comment by jksuom** [comment]
Looks like a network error. I'll try to restart the build.

**Comment by oscarbenjamin** [comment]
It's not enough just to add a commit that deletes the file. They mustn't be there in any commit on sympy's master branch because they increase the size of the repo and can interfere when doing something like git bisect.

There are ways to remove the commits using force-push but a lot of contributors have trouble running the necessary git commands. The simplest way is just to make a new branch from master manually make the changes again, then commit, push and open a new PR.

**Comment by jksuom** [comment]
No luck. Job # 6 is failing on other branches as well. Will have to wait.

**Comment by jksuom** [comment]
Looks better now on second restart.

**Comment by jksuom** [comment]
The last two commits should be replaced by a single one (i.e. squashed). I would do that as follows

    git reset HEAD~2
    git add sympy/polys/sqfreetools.py
    git commit

Then a couple of tests should be added.

**Comment by vaish3496** [comment]
@jksuom Well, first I had to merge because `Updates were rejected because the tip of your current branch is behind its remote counterpart.` I hope now it's fine.

**Comment by Sc0rpi0n101** [comment]
You should also squash your commits. As Oscar said, the commits with the notebooks shouldn't be in the history.

YOu should do 
`git rebase -i HEAD~<n>`
and squash the required commits, then force push to the branch. 

You can find more details about it at https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Or if it gets too messy, you can just create close this PR, make a new branch and create a new PR with the changes

**Comment by vaish3496** [comment]
@jksuom I closing this PR and making a clean and fresh new PR.

**Pull request closed without merging**
