### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by benharvie**
To let the repository confirm oscar.j.benjamin@gmail.com as its security contact.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Although not mentioned above this comes from gh-24990.

I don't think that we really want "email Oscar" as a security policy going forwards. Probably we need a dedicated email address or something that goes to more than just one person. We should look at how other similar projects handle this.

I just suggested in gh-24990 to email me as a way of handling something right now since there is not yet a policy in place. Deciding on a policy going forwards probably needs some discussion among contributors.

**Comment by 1e9abhi1e10** [comment]
>We should look at how other similar projects handle this.

We can take idea from how `node.js` or `atomist` to handle the security issues
https://github.com/nodejs/node/blob/main/SECURITY.md
https://github.com/atomist/samples/blob/master/SECURITY.md

**Comment by 1e9abhi1e10** [comment]
> To let the repository confirm [oscar.j.benjamin@gmail.com](mailto:oscar.j.benjamin@gmail.com) as its security contact.

@benharvie Read [here](https://docs.sympy.org/dev/contributing/new-contributors-guide/workflow-process.html#writing-pull-request-title-and-description) for writing the release notes.
For the first pull request, you need to add your name and email in the `.mailmap` file , read [here](https://docs.sympy.org/dev/contributing/new-contributors-guide/workflow-process.html#add-your-name-and-email-address-to-the-mailmap-file) for instructions.

**Comment by asmeurer** [comment]
We can create a private sympy-security google group with relevant core developers.

Although I'd like to know just what sorts of security issue we are anticipating here. Did the developer from the linked issue ever reach out to you? 

I appreciate that (real) security issues are important, but I've also seen security reports and CVEs used as a social attack against open source projects. If this ends up just being a way for people to spam the core development team with useless reports, I'm -1 to it.

**Comment by asmeurer** [comment]
One option would be to use Tidelift, which acts as a go-between for security responses. This is what NumPy does (see the link in their README). https://github.com/numpy/numpy/#readme

It also seems like most security emails I've seen allow using a PGP key. I have no idea how to do that in a way that allows multiple people to view the reports.

**Comment by asmeurer** [comment]
Oh, GitHub has a native way to do vulnerability reports https://github.com/sympy/sympy/settings/security_analysis. If anything, we should just use that.

**Comment by asmeurer** [comment]
BTW I noticed that @benharvie has opened dozens of similar issues/PRs to other repos, including many issues that seem to use the same template as the one used by @psmoros in #24990. I guess this is somehow related to @huntr-helper. This isn't exactly alleviating my concerns about security "researchers" spamming OSS projects.

**Comment by asmeurer** [comment]
SymPy is listed at https://www.huntr.dev/bounties/ as a "boosted project" that is "guaranteed to get reviewed and have boosted rewards" of up to $75.

My question is, what does "reviewed" mean here? Does someone at Huntr review the reports and only submit them to the project if they pass some bar of legitimacy? I noticed that @psmoros's GitHub profile says they are the cofounder of Huntr but it isn't clear what @benharvie's affiliation is. OTOH, if "guaranteed review" means that they somehow guarantee that the open source project will review the report, I find that to be very problematic, as they are shifting the reponsitiliby of sifting through potentially many bogus claims to volunteer open source maintainers. My (limited) experience with seeing reports in other projects is that, if not filtered properly, a significant number are illegitimate, meaning they don't actually constitute a real vulnerability. 

(again, I would really like to see what the reported vulnerability from https://github.com/sympy/sympy/issues/24990 actually is. Oscar, did you receive any emails about it?)

**Comment by oscarbenjamin** [comment]
> Oscar, did you receive any emails about it?

No. I just checked spam and I have not received any emails.

**Comment by psmoros** [comment]
Hi team! To shed some light on what we do; a company that depends on SymPy is sponsoring security research into your project: up to $1040 per valid vulnerability for the researcher and $260 for the maintainer.
We triage at a basic level to make sure that no report will waste the maintainer's valuable time.
We don't actually guarantee the review of boosted projects, this is something we use to do in the past.

**Comment by psmoros** [comment]
By the way @benharvie works with us. He opened that PR in order to make sure that the email is accepted as a security point of contact by your org but let me go ahead and send you the report.

Feel free to close this :)

**Comment by asmeurer** [comment]
Thanks for responding @psmoros. It may be worth us setting up a security contact system. As Oscar noted, just using his email isn't really appropriate. I will enable the built in GitHub thing unless anyone objects.

For reference, we did receive the report and are looking into it.

**Comment by ready-research** [comment]
Hi @oscarbenjamin, new version 1.12 is released with patch for this issue. Can you please validate this [huntr](https://www.huntr.dev/bounties/692bf03d-973b-4fbc-b9e4-dd158bdd422b/) issue as valid and add the [patch](https://github.com/sympy/sympy/commit/2c3de5f49f294b7f84b3d58fe15e90b49b9316dc)?

**Comment by oscarbenjamin** [comment]
I've validated the issue. I'm not sure how to add the patch though.

**Comment by ready-research** [comment]
Hi @psmoros, can you please help Benjamin to add the patch and also adjust the bounty as per comments in https://github.com/sympy/sympy/pull/24997#issuecomment-1493015185

**Comment by psmoros** [comment]
On it :)

**Pull request closed without merging**
