### PR TITLE
Remove exception handler for ints in evalf.py

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

From #16164 

This is following up from [https://github.com/sympy/sympy/pull/16164#discussion_r262651639](https://github.com/sympy/sympy/pull/16164#discussion_r262651639)

#### Brief description of what is fixed or changed

This removes code that was added in #10346 but no longer appears to be necessary. I'm splitting this change out to be reviewed separately from the rest of #16164.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by smichr** [comment]
In master, the following raises a PrecisionExhausted. That test could be added near that others that were added:

```
ceiling(x-3.5-I).evalf(subs={x: 3.5+I})
```
If you can see why the imaginary part is not evaluating to 0, that would be great: `ceiling(x - I).evalf(subs={x: I}) == 0` shouldn't fail.
```diff
diff --git a/sympy/core/evalf.py b/sympy/core/evalf.py
index 6f40e66..e563b67 100644
--- a/sympy/core/evalf.py
+++ b/sympy/core/evalf.py
@@ -360,12 +360,12 @@ def calc_part(re_im, nexpr):
                 is_int = (p == 0)
                 nint = int(to_int(nexpr, rnd))
         if not is_int:
-            # if there are subs and they all contain integer re/im parts
-            # then we can (hopefully) safely substitute them into the
-            # expression
+            # if there are subs they can (hopefully) be substituted them
+            # into the expression; in general this is a bad idea because
+            # they cannot be re-substituted later with higher precision.
             s = options.get('subs', False)
             if s:
-                re_im = re_im.subs(s)
+                re_im = re_im.subs(options.get('subs', {}))
 
             re_im = Add(re_im, -nint, evaluate=False)
             x, _, x_acc, _ = evalf(re_im, 10, options)
diff --git a/sympy/core/tests/test_evalf.py b/sympy/core/tests/test_evalf.py
index b1aa33b..fbf8144 100644
--- a/sympy/core/tests/test_evalf.py
+++ b/sympy/core/tests/test_evalf.py
@@ -256,6 +256,8 @@ def test_evalf_integer_parts():
     assert ceiling(x).evalf(subs={x: 3.}) == 3
     assert ceiling(x).evalf(subs={x: 3.*I}) == 3*I
     assert ceiling(x).evalf(subs={x: 2. + 3*I}) == 2 + 3*I
+    assert ceiling(x - 4.2).evalf(subs={x: 4.2}) == 0
+    assert ceiling(x - I).evalf(subs={x: I}) == 0
 
     assert float((floor(1.5, evaluate=False)+1/9).evalf()) == 1 + 1/9
     assert float((floor(0.5, evaluate=False)+20).evalf()) == 20
```

**Comment by oscarbenjamin** [comment]
I've added the suggested changes. Haven't had a chance to look into `ceiling(x - I).evalf(subs={x: I}) == 0` yet.

**Comment by smichr** [comment]
This is passing and gets at the heart of what the code you removed was trying to do. Would be intereseted to see if it passes the full suite. It passes evalf and ode.
```diff
diff --git a/sympy/core/evalf.py b/sympy/core/evalf.py
index e563b67..6d0506c 100644
--- a/sympy/core/evalf.py
+++ b/sympy/core/evalf.py
@@ -365,9 +365,9 @@ def calc_part(re_im, nexpr):
             # they cannot be re-substituted later with higher precision.
             s = options.get('subs', False)
             if s:
-                re_im = re_im.subs(options.get('subs', {}))
+                re_im = re_im.subs(s)
 
-            re_im = Add(re_im, -nint, evaluate=False)
+            re_im = Add(re_im, -nint, evaluate=False)  # trying it unevaluated this time
             x, _, x_acc, _ = evalf(re_im, 10, options)
             try:
                 check_target(re_im, (x, None, x_acc, None), 3)
@@ -1288,7 +1288,19 @@ def _create_evalf_table():
 
 
 def evalf(x, prec, options):
-    from sympy import re as re_, im as im_
+    from sympy import re as re_, im as im_, Number, Dict
+    if not x.is_number:
+        s = Dict(options.pop('subs', {}))
+        if s:
+            # put in numbers that are exact
+            undone = dict()
+            for k, v in s.items():
+                if all(i.is_Rational for i in v.atoms(Number)):
+                    x = x.subs(k, v)
+                else:
+                    undone[k] = v
+            if undone:
+                options['subs'] = undone
     try:
         rf = evalf_table[x.func]
         r = rf(x, prec, options)
```

It fails this test in expr....hmm
```
  File "sympy\core\tests\test_expr.py", line 1593, in test_equals
    assert diff.equals(0) is False
AssertionError
```

**Comment by oscarbenjamin** [comment]
I've pushed that suggested change on.

I'm not sure I understand what any of these changes are doing. I don't know why `test_equals` fails. I guess this needs a careful look.

**Comment by smichr** [comment]
```
______ sympy/polys/tests/test_numberfields.py:test_minpoly_fraction_field ______
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/utilities/runtests.py", line 1306, in _timeout
    function()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/polys/tests/test_numberfields.py", line 733, in test_minpoly_fraction_field
    assert minimal_polynomial(a, y) == y
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/polys/numberfields.py", line 654, in minimal_polynomial
    result = _minpoly_compose(ex, x, domain)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/polys/numberfields.py", line 533, in _minpoly_compose
    res = _minpoly_add(x, dom, *ex.args)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/polys/numberfields.py", line 361, in _minpoly_add
    mp = _minpoly_op_algebraic_element(Add, a[0], a[1], x, dom)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/polys/numberfields.py", line 278, in _minpoly_op_algebraic_element
    res = _choose_factor(factors, x, op(ex1, ex2), dom)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/polys/numberfields.py", line 69, in _choose_factor
    if abs(f.as_expr().evalf(prec1, points)) < eps:
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/core/expr.py", line 360, in __lt__
    raise TypeError("Invalid NaN comparison")
TypeError: Invalid NaN comparison

__________________ sympy/core/tests/test_expr.py:test_equals ___________________
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/utilities/runtests.py", line 1306, in _timeout
    function()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/core/tests/test_expr.py", line 1593, in test_equals
    assert diff.equals(0) is False
AssertionError
________________________________________________________________________________
________________ sympy/geometry/tests/test_plane.py:test_plane _________________
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/utilities/runtests.py", line 1306, in _timeout
    function()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.4.dev0-py3.7.egg/sympy/geometry/tests/test_plane.py", line 193, in test_plane
    assert pl8.equals(Plane(p1, normal_vector=(0, 12, 0))) is False
AssertionError

```

**Comment by czgdp1807** [comment]
@oscarbenjamin Any news on this?

**Pull request closed without merging**
