### PR TITLE
empty dimensions are represented as dimension objects instead of 1

### PR DESCRIPTION
**Pull request by abentkamp**
This resolves the following problem:

```
>>> dim_simplify(Dimension({"length":-2})*Dimension({"length":2})+1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Miniconda\lib\site-packages\sympy\physics\unitsystems\simplifiers.py", line 34, in dim_simplify
    return reduce(lambda x, y: x.add(y), args)
TypeError: reduce() of empty sequence with no initial value
```

@melsophos I can understand that it makes sense to return simple numbers instead of quantities or units if they are dimensionless. This is because both are a combination of a dimension and a number, if there is no dimension all that rests is a number. But for dimensions, representing the "empty dimension" as 1 does imho not make sense, because other numbers like 0 or 2 would also be plausible representatives of the empty dimension.

So I propose the approach followed in this pull request: dimensionless units or quantities are represented as simple numbers like before, but the empty dimension is represented as a dimension object.

### CODE REVIEW

**Comment by melsophos** [comment]
I totally agree with your comment and as I said in the previous discussion I have hesitated a long time before choosing the other option, so I don't have anything a priori against this.
I see that you have a test using sin and operators Mul/Add, etc. Did you test what happens with the same thing but using the operators *, +, etc.?

To answer your previous question « What exactly do you mean by "avoid magic in simplifications"? »: in a previous version there was a lot of automatic simplifications, but the behaviour could not be foreseen straightforwardly by the user, so we decided to avoid as much as possible simplifications and let the user decide when to use the simplifying methods.

**Comment by benti** [comment]
Now I tried to use *,+ etc. I didnt know they behave a bit different from Mul, Add etc., but they seem to work fine as well. I could not find any combination that leads to a different simplification behaviour using dim_simplify.

I could add that as a unit test if you like!?

**Comment by melsophos** [comment]
Where I am surprised is that sin() works with a Dimension object. But since everything seems to work fine then your modification is fine to me. If you could add a unit test to check that everything is similar for * / Mul, etc. it would be cool (I don't know why I did not try it), because I don't know how user do in general but I never use directly Add, Mul, etc.

**Comment by benti** [comment]
Closed in favor of #10133

**Pull request closed without merging**
