### PR TITLE
0.7.6.1 bugfix release

### PR DESCRIPTION
**Pull request by asmeurer**
This is a bugfix release for 0.7.6.1, which is just a backport of https://github.com/sympy/sympy/pull/9418 to fix SymPy in IPython/Jupyter 4.0. 

Do not merge. I will merge once the release is finished.

### CODE REVIEW

**Comment by moorepants** [comment]
Can we include this: https://github.com/sympy/sympy/pull/9513?

**Comment by asmeurer** [comment]
Sure. Can you send a PR?

**Comment by asmeurer** [comment]
I guess I'll need to backport some PyPy fixes as well, so that Travis passes.

**Comment by leosartaj** [comment]
As this is a bugfix, maybe we can also add #9880?

**Comment by asmeurer** [comment]
I only want to backport essential bugfixes into this release, so that we can get it out as fast as possible with minimal impact.

**Comment by leosartaj** [comment]
Understood.

**Comment by asmeurer** [comment]
OK, Travis is passing. @moorepants are you going to send the PR with the https://github.com/sympy/sympy/pull/9513 fixes? If not, then I think this is ready to be released.

**Comment by moorepants** [comment]
Yes, I'd like to sent the PR. I am hoping to have time today.

**Comment by asmeurer** [comment]
That would be great if you could. I'd like to push this out tomorrow.

**Comment by asmeurer** [comment]
OK, it's been released. 

Now, as to this branch. Should it be merged? The commits are all technically duplicates, but I think it is good to have it in the history. OTOH, it technically already is because of the git tag.

**Comment by moorepants** [comment]
The tag should be in the main history. So I guess merge it.

**Comment by asmeurer** [comment]
Alright, it should merge cleanly, and the diff should prove that I did the merge correctly.

**Pull request merged**
