### PR TITLE
Simplifications in Dirac Delta function

### LINKED ISSUE #12257: Simplifications in Dirac Delta function
It seems that the Dirac Delta function might be more useful if certain simplifications can be done.
For Example:

- For using the symmetry property of the dirac delta function i.e DiracDelta(x)==DiracDelta(-x) . The existing provision for this is `DiracDelta(-x).expand(diracdelta=True, wrt=x)` . As of now we have this
```
>>> DiracDelta(-x)
DiracDelta(-x)

```
What I hope after this issue would be 
```
>>> DiracDelta(-x)
DiracDelta(x)

```
- Also we can include the property like DiracDelta(m*x) = DiracDelta(x)/m , where m is an integer . This feature is also presently implemented like `DiracDelta(2*x).expand(diracdelta=True, wrt=x)`

We can have the existing way when more than one variables are involved . For constants, we can include it in basic cases.

I have read the code regarding this and it would be really nice , if someone could guide me in this.

### PR DESCRIPTION
**Pull request by mohit3011**
Fixes #12257

### CODE REVIEW

**Comment by mohit3011** [comment]
@jksuom , @asmeurer , I checked the changes made on the local machine (by running tests) and they were working fine but in the Travis test, these are failing why ?

**Comment by jksuom** [comment]
It seems to me that these automatic modifications are unexpected and not useful in some connections. In general, such changes are avoided in SymPy.

**Comment by mohit3011** [comment]
@jksuom ,So should I close this pull request and issue ?

**Comment by jksuom** [comment]
It seems that the only case where automatic simplification could be thinkable is the one with a negated variable:
```
>>> DiracDelta(-x).expand(diracdelta=True, wrt=x)
DiracDelta(x)
```
But I doubt that an implementation would be of much use since negated arguments are not created by SymPy code. So, I would close this unless somebody gives a good reason for adding this special case.

**Comment by mohit3011** [comment]
@jksuom , I think I should close this P.R

**Pull request closed without merging**
