### PR TITLE
Made parts of boolalg a bit more pythonic and faster

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Cleaning up badly written code, partly from #16133.

#### Brief description of what is fixed or changed
Improved the code quality of functions related to `simplify_logic`, primarily by using list comprehensions. Some fundamental changes in `_rem_redundancy` to speed things up.

#### Other comments
There are other aspects taking much more time than the actual simplification, so the improvement may not be substantial in many cases.

One may reconsider if the heuristic checking which form to use should be implemented the way it currently is. If a truth table have more than half ones, SOP/dnf form is selected. However, the complexity is roughly quadratic to the number of ones for SOP/dnf, while it is roughly quadratic to the number of zeros for POS/cnf. Now, one may expect that more ones/zeros leads to fewer terms, but there are exceptions, and considering the run time, it may make sense to change this. The documentation should probably be clearer here as well:
```
    form : string ('cnf' or 'dnf') or None (default).
        If 'cnf' or 'dnf', the simplest expression in the corresponding
        normal form is returned; if None, the answer is returned
        according to the form with fewest args (in CNF by default).
```

For example, the test
https://github.com/sympy/sympy/blob/287a520f2b9058fabd018778fdf92a708dd71b3c/sympy/logic/tests/test_boolalg.py#L308-L314

has a truth table of either two or 510 items, and the complexity when performing 
https://github.com/sympy/sympy/blob/287a520f2b9058fabd018778fdf92a708dd71b3c/sympy/logic/boolalg.py#L2234
will scale quadratically with that (then it is iterated a few times, but with much fewer elements). The result is the same in both forms (clearly a special case), but the question is if one should go for the faster case, at least when there are many variables involved?

Replacing the `zip` in `_check_pair` halves the self time (in the test above, from about 45 second to about 25 seconds, so significant).

Edit: after some reading and thinking, the current approach has reduced the self time for the large example to about 10 seconds.

Edit 2: better code avoiding redundant comparisons reduce self time to about 8 seconds.

Temporary(?) return. Work and life often taking too much time...

#### Release Notes

*  logic
   * `simplify_logic` faster in most cases, especially for larger expressions.

### CODE REVIEW

**Comment by oscargus** [comment]
Before:
```
In [2]: %timeit test_simplification()
1.46 s ± 33.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [3]: %timeit test_simplification()
1.45 s ± 27.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [4]: %timeit test_simplification()
1.46 s ± 80.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [5]: %timeit test_issue_14700()
1.77 s ± 61 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [6]: %timeit test_issue_14700()
1.8 s ± 102 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [7]: %timeit test_issue_14700()
1.74 s ± 50 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

After:
```
In [2]: %timeit test_simplification()
1.42 s ± 11.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [3]: %timeit test_simplification()
1.41 s ± 17.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [4]: %timeit test_simplification()
1.42 s ± 34 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [5]: %timeit test_issue_14700()
1.45 s ± 24.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [6]: %timeit test_issue_14700()
1.42 s ± 21.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [7]: %timeit test_issue_14700()
1.49 s ± 99.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

So a marginal improvement for small problems (`test_simplification`), but more for larger problems ( `test_issue_14700`). (Partly because `xreplace` takes a fair chunk of the time.) 

For the nine variable problem, it is reduced from
```
In [2]: a, b, c, d, e, f, g, h, j = symbols('a b c d e f g h j')
   ...: expr = a & b & c & d & e & f & g & h & j | \
   ...:     a & b & c & d & e & f & g & h & ~j

In [3]: %timeit simplify_logic(expr, force=True)
53.4 s ± 4.28 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

to

```
In [3]: %timeit simplify_logic(expr, force=True)
15.5 s ± 416 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by oscarbenjamin** [comment]
I don't know much about these things but would it make more sense to use the Quine McCluskey algorithm in `simplify_logic`? Is that implemented somewhere?

**Comment by oscargus** [comment]
This is sort of Quine McCluskey now. With the last change in `_simplified_pairs` of only testing prime implicators where the number of ones differ by one, one may claim that it is pretty close. The behavior was like that even before, but more efficient now (as I believe it is described). 

One could possibly think of adding a heuristic here for larger problems. Either like Espresso https://en.wikipedia.org/wiki/Espresso_heuristic_logic_minimizer or just a greedy heuristic for the set covering problem that `_rem_redundancy` effectively implements. However, it seems like `_simplified_pairs` is the limiting factor from a speed perspective, so not sure it makes much sense.

There is https://pypi.org/project/pyeda/ which implements Espresso, but the actual Espresso part is written in C as far as I understand.

> Due to the complexity of this operation, PyEDA uses a C extension to the famous Berkeley Espresso library 

I also found https://github.com/dreylago/logicmin but is seems pretty rudimentary (not sure about performance though, but browsing the code doesn't indicate that something especially clever has been done).

**Comment by oscarbenjamin** [comment]
> This is sort of Quine McCluskey now.

Okay fair enough. As I said I don't know so much about these things but I recently saw this question on SO:
https://stackoverflow.com/questions/63967849/python-sympy-using-simplfy-on-boolean-expression-results-with-non-simplified-e/63968017?noredirect=1#comment113121586_63968017

**Comment by oscargus** [comment]
I saw that as well when searching for possible related work. The general problem of logic minimization is not straightforward, but as is stated in the reply, the results will be minimal subject to the selected form.

**Comment by czgdp1807** [comment]
ping @asmeurer Is this PR good to go? The tests are passing.

**Comment by oscarbenjamin** [comment]
Resolved the merge conflicts. The problem with putting tests and the end of the test file is that any two PRs with new tests at the end will conflict.

**Comment by oscarbenjamin** [comment]
Looks good. Thanks @oscargus !

**Pull request merged**
