### PR TITLE
Reducing matrix expressions involving transpose and powers

### PR DESCRIPTION
**Pull request by sidhantnagpal**
#### Brief description of what is fixed or changed
- Reduction of matrix expressions with intermixed transpose and powers
```
>>> A = MatrixSymbol('A', n, n)
>>> B = MatrixSymbol('B', n, n)
>>> ((A.T)**5).T
A**5
>>> ((A**5).T**5).T
A**25
```
Here `A` can be `MatrixExpr` (of square shape) as well.
- `deep=False` is passed to `MatPow.doit()` from `MatrixExpr.__pow__`
Motivation:
```
# old behaviour
>>> Transponse(A*B)**5
(B.T*A.T)**5

# new behaviour
>>> Transponse(A*B)**5
(A*B).T**5
>>> _.doit()
(B.T*A.T)**5
```
- Documentation improvements

#### Release Notes

* matrices
     * matrix expressions involving transpose and powers are now automatically reduced
     * `Transponse(A*B)**5` now requires invocation of `.doit()` method to carry out reductions

### CODE REVIEW

**Comment by asmeurer** [comment]
I think it would make more sense to leave deep flag defaulting to True, but set deep=False in the `doit` call in `__pow__`.

**Comment by asmeurer** [comment]
The reason being that most people don't know about the deep flag, so they just call `doit()` expecting it to simplify the expression fully. Default values should generally be what end-users expect, as they are the least likely to want to deal with or even know about keyword arguments. Library code can easily change the defaults for its specific uses.

**Comment by sidhantnagpal** [comment]
There seems to be one other issue due to the `deep=True` as the default. `Transpose(A*B)**5` works as expected if `deep=False` is passed from the `MatrixExpr.__pow__` method. However, `(Transpose(A*B)**5).T` (which is shorthand for `Transpose(Transpose(A*B)**5).doit()` with default value being `deep=True`) gives `((B.T*A.T)**5).T` as the reductions are carried out in innermost to outermost fashion.

An obvious solution to this would be to have usage like `Transpose(Transpose(A*B)**5).doit(deep=False)` which might be a bit challenging to write/interpret as expressions become complicated.

A better alternative (while retaining `deep=True` behavior for `MatPow.doit()` and `Transpose.doit()`) could be to always canonicalize expressions like `A.T**5` to `(A**5).T`, that way deep reductions due to transpose are prevented.

**Comment by asmeurer** [comment]
Probably .T should call deep=False as well. 

doit as called by users should default to deep=True to simplify the whole expression, but doit as called by a function to perform canonicalization should use deep=False to only canonicalize the top-level expression and not change anything deeper in the expression tree.

**Comment by sidhantnagpal** [comment]
I suppose that could be done.

One good thing by choosing the canonicalization - transpose first and exponentiate later, would be that shorthand notations could be used everywhere without having to use `Transpose` (unevaluated) for inner expressions. Of course, if the unevaluated expressions are desired, the reductions can still be carried out by calling the `doit()` method.

Another advantage is `((A*B).T)**5 == ((A*B)**5).T` will now give `True`.

(This will also remove the need for special case handling in `MatPow.doit` method and the fix will be confined to the `MatPow._eval_transpose` method.)

```
In [17]: ((A.T * B.T * C.T)**7).T                                               
Out[17]: 
       7
(C⋅B⋅A) 

In [18]: Transpose((A * B * C)**7)                                              
Out[18]: 
          T
⎛       7⎞ 
⎝(A⋅B⋅C) ⎠ 

In [19]: _.doit()                                       
Out[19]: 
          7
⎛ T  T  T⎞ 
⎝C ⋅B ⋅A ⎠ 

In [20]: Transpose((A * B * C)**7)**6                                           
Out[20]: 
             6
⎛          T⎞ 
⎜⎛       7⎞ ⎟ 
⎝⎝(A⋅B⋅C) ⎠ ⎠ 

In [21]: _.doit()                                                               
Out[21]: 
          42
⎛ T  T  T⎞  
⎝C ⋅B ⋅A ⎠
```

**Comment by asmeurer** [comment]
I think it makes sense for .T to do some evaluation, so long as the class Transpose doesn't evaluate by default (that is generally the way things work in the matrix expressions module, as far as I remember).

**Pull request merged**
