### PR TITLE
collect_const() changed argument 

### PR DESCRIPTION
**Pull request by vishalg2235**
@gxyd Here `collect_const` argument is changed to `collect_const(expr, *vars, Numbers=True)`.
I think docstring also should be changed with more examples to show all working aspects of `collect_const`.
https://github.com/sympy/sympy/issues/13683

### CODE REVIEW

**Comment by vishalg2235** [comment]
ps: only check commit https://github.com/sympy/sympy/pull/13702/commits/ee35c02d37576ee7cc18fadf4e4828c6ab6aeb74 due to some mistake two commits has done.

**Comment by gxyd** [comment]
There is already a PR #13684, focusing on trying to improve the documentation for `collect_const`. If you want to fix this issue, please try to improve the documentation for some other function satisfying the conditions described in the issue.

**Comment by vishalg2235** [comment]
yup sure !

**Comment by gxyd** [comment]
I think what you are doing wrong is that, you are checking out (using `git checkout`) a new branch, instead of checking out from the master branch. i.e. to say, that when you create a new branch, make sure you are present on the (updated) master branch.

**Comment by vishalg2235** [comment]
yes @gxyd  I realised the same thing when I was last pushing my commit. When I checkout from master branch and then push commit ,then it is not stacked with previous commit.

**Comment by vishalg2235** [comment]
@gxyd should I delete this branch ?

**Pull request closed without merging**
