### PR TITLE
Partial solution to #8578 + test

### PR DESCRIPTION
**Pull request by pelegm**
Fixed the logic a little bit. This provides a solution to `binomial(S.Half, S.Half)`, for example (the solution that has existed for `binomial(x, x)` was not applied, since `S.Half` is a `Number`), but does not provide a solution for `binomial(-1, -1)`, as when `k` is a negative integer, there's a line that returns 0, which is not true in all cases.

### CODE REVIEW

**Comment by pelegm** [comment]
See #8578 (just to create a reference; the title does not create it...)

**Comment by pelegm** [comment]
`test_gosper` fails. I'll fix that.

**Comment by pelegm** [comment]
@smichr, I might need help with that. The failing test is
```python
    assert g is not None and simplify(g - g1h).rewrite(gamma) == 0
```
which was earlier
```python
    assert g is not None and simplify(g - g1h) == 0
```

The second part of that test was enabled by you in 6c96b1848a385b7f5044380399e46965ecc332cf; and the second part is what fails. I am not familiar with gosper at all, so perhaps you can enlighten me here?

**Comment by smichr** [comment]
I'm not into gosper, either, but for a test like that it is just trying to show that g and g1h agree. Does g.equals(g1h) work? or else `assert g is not None and 0 in [simplify(g - g1h), simplify(g - g1h).rewrite(gamma)]`?

**Comment by smichr** [comment]
:key: If you can solve `(factorial(-S.Half)**2).simplify()` which in this branch gives 0 instead of pi (or being unevaluated, as in master) the gosper problem will go away.

**Comment by smichr** [comment]
:information_source: could you please change the title of the PR? Including the issue number there isn't as useful as putting it in the Description (first paragraph above) because 

1. it doesn't create a clickable link in the Title
1. the number itself doesn't tell the reviewer what they are going to be seeing
1. when there are lots of Issue ### titles it's hard to remember what's what

:eyeglasses: See also: **Writing pull request title and description** at [the wiki](https://github.com/sympy/sympy/wiki/Development-workflow)

**Comment by smichr** [comment]
BTW, by "self-assigning" I was not trying to take this over...just to mark which PRs I was following. I have since found that one can just put a list into the Search box like `is:pr is:open sort:updated-desc 1234 5678` and only those PRs will show up. Are you willing to take a look at #8947 where I added to what you have already done?

**Comment by pelegm** [comment]
@smichr, sorry for not being available; I have not checked yet, #8947 makes this PR obsolete?

**Pull request closed without merging**
