### PR TITLE
Matrix can now be symbolically indexed

### PR DESCRIPTION
**Pull request by Upabjojr**
``` python
In [3]: M = Matrix([[2, 3], [4, 5]])

In [4]: M
Out[4]: 
⎡2  3⎤
⎢    ⎥
⎣4  5⎦

In [5]: ;var i,j
Out[5]: (i, j)

In [6]: M[i, j]
Out[6]: 
⎡2  3⎤[i, j]
⎢    ⎥      
⎣4  5⎦   
```

### CODE REVIEW

**Comment by jksuom** [comment]
This looks good to me. In addition to symbols, indices can be expressions like `3*i + 2`, for example. Perhaps there could be tests for those.
It is seems also possible to construct `MatrixElement[i, j]` objects where `i` is an expression but `j` is a number that is not an integer. Maybe such cases should also be tested.

**Comment by Upabjojr** [comment]
> It is seems also possible to construct MatrixElement[i, j] objects where i is an expression but j is a number that is not an integer. Maybe such cases should also be tested.

Right.

**Comment by Upabjojr** [comment]
Derivatives fixed as well.

**Comment by jksuom** [comment]
I think this is good to go.

**Pull request merged**
