### PR TITLE
example of symbolic solving

### PR DESCRIPTION
**Pull request by aayu-sha**

### CODE REVIEW

**Comment by smichr** [comment]
This is misplaced here. Please look at the [tutorial file](https://github.com/sympy/sympy/blob/master/doc/src/tutorials/intro-tutorial/solvers.rst) and see what you might like to change there, instead.

**Comment by smichr** [comment]
This is now placed in the middle of the lambdify discussion. That, too, is misplaced. Please look at the [tutorial file](https://github.com/sympy/sympy/blob/master/doc/src/tutorials/intro-tutorial/solvers.rst) and see what you might like to change there, instead.

**Comment by shishir-11** [comment]
@aayu-sha you should try to keep the commit messages a little more descriptive and can you please squash the commits so its easier to track later

**Comment by oscarbenjamin** [comment]
I don't think this change is needed. It doesn't make sense in the tutorial here and there are already other places that show how to use solve.

**Pull request closed without merging**
