### PR TITLE
 Fail a Travis test if a newer commit on the same branch exists.

### PR DESCRIPTION
**Pull request by toolforger**
This prevents hogging Travis resources with tests of versions that have already been superseded.

Note that this makes rerunning tests after another commit fail, always.
The workaround is checking the old commit out as a throwaway branch and test that.

### CODE REVIEW

**Comment by asmeurer** [comment]
Someone on that issue pointed to https://github.com/grosser/travis_dedup. I wonder if it works.

**Comment by toolforger** [comment]
I did some investigation, here's what I found out:

It needs a Travis access token, which is unavailable for PRs by third parties (because these could easily add a print command that would display the token on the log).
So usage is restricted to people who can directly push to SymPy's `master` branch, which is exactly the group of persons who can cancel Travis builds anyway, and for whom that script is merely nice to have.

**Comment by toolforger** [comment]
I added #9658 to track this issue in the future.

**Comment by asmeurer** [comment]
I see. So it's only useful for the model where people create branches on the same repo, without forks.

**Comment by toolforger** [comment]
Ah, so that's the use case this was for.

**Pull request closed without merging**
