### PR TITLE
remove sympy/subresultants_pg_amv.py [ci skip]

### PR DESCRIPTION
**Pull request by jksuom**
This duplicate version seems to have been left in the file system. I think this would be the way to remove it. Ping @asmeurer

### CODE REVIEW

**Comment by jksuom** [comment]
[ci skip] does not seem to work the way indicated in https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build

**Comment by gxyd** [comment]
It's [skip ci] i guess.

**Comment by jksuom** [comment]
Apparently so.

**Comment by jksuom** [comment]
I've cancelled the build.

**Pull request merged**
