### PR TITLE
Expand gamma functions in case of gamma(n*z)

### PR DESCRIPTION
**Pull request by raoulb**
TODO: rebase with master

Expand gamma functions in case of gamma(n*z).

Can someone in the review show me how to do this correctly?
For example gamma(3_z_*2) does not work ...

### CODE REVIEW

**Comment by czgdp1807** [comment]
@raoulb Would you still like to work on this PR? I see that tests aren't added for the changes made in the code.

**Comment by czgdp1807** [comment]
```python
In [1]: gamma(4*x).expand(func=True)                                            
Out[1]: Γ(4⋅x)

In [2]: gamma(5*x).expand(func=True)                                            
Out[2]: Γ(5⋅x)
```
Results on `master`. Any thoughts? @asmeurer

**Comment by jksuom** [comment]
There is an implementation of the multipilication formula of the gamma function in `gammasimp`:
https://github.com/sympy/sympy/blob/1872e360395c06b96112a03ee2c5c11af91a7ac7/sympy/simplify/gammasimp.py#L34-L35 where it is used to reduce the number of gammas. This PR will act in the opposite direction. It will probably be seldom needed.

**Comment by oscarbenjamin** [comment]
It's maybe better to add a rewrite for Product rather than using expand for this:
```python
In [20]: n = symbols('n', positive=True, integer=True)

In [21]: factorial(5*n).rewrite(Product)
Out[21]: 
 5⋅n   
─┬─┬─  
 │ │  i
 │ │   
i = 1  

In [22]: gamma(5*n).rewrite(Product)
Out[22]: Γ(5⋅n)

In [23]: gamma(5*n).rewrite(factorial).rewrite(Product)
Out[23]: 
5⋅n - 1  
 ─┬─┬─   
  │ │   i
  │ │    
 i = 1
```
In any case I'm closing this PR as stale.

**Pull request closed without merging**
