### PR TITLE
Linear programing function

### PR DESCRIPTION
**Pull request by orielmalihi**

### CODE REVIEW

**Comment by orielmalihi** [comment]
Hi Oscar,
I did what you asked and opened a new PR from a different branch (not the master branch as before).
is it better now?

**Comment by oscarbenjamin** [comment]
This is still messed up. Take a look at the files changed tab:
https://github.com/sympy/sympy/pull/21679/files

Something funny has happened with a lot of those files.

**Comment by orielmalihi** [comment]
Ok.
I will try forking the library again, then i will insert the new code and
generate a new PR.
I Hope this would work.. :)

בתאריך יום ב׳, 28 ביוני 2021, 20:32, מאת Oscar Benjamin ‏<
***@***.***>:

**Comment by Abdullahjavednesar** [comment]
@orielmalihi When you plan to reopen a new PR for the same, please do close this one.

**Pull request closed without merging**
