### PR TITLE
tweaking of canonical-related items

### LINKED ISSUE #19326: subs dict result changed (and inconsistent) in 1.6 with functions
This code

```
from sympy import Function
from sympy.abc import t

x, y = Function('x')(t), Function('y')(t)
(x*y).subs({x: x + 1, y: x})
```

produces the expected result `(x(t) + 1)*x(t)` with 1.5.1 and earlier, but with 1.6rc1 produces (x(t) + 1)**2. Note that this is even inconsistent with substituting in the ordered dict items order (I believe dict substitution should be independent of order and not make any re-substitutions). I don't see anything in the change log that could justify this behaviour, so assuming a bug (and a tricky one to isolate, took me half a day to figure out why a complex unit test was failing with 1.6rc1). If dict substitute is unsupported (it does seem to be undocumented) then it should raise an error, though not sure if there's another way to do this kind of variable substitution consistently.

### PR DESCRIPTION
**Pull request by smichr**
#### Brief description of what is fixed or changed

- anticipate Lambda(x,x+1) != Lambda(y,y+1)
These changes are not necessary yet, but they anticipate the removal of the equality behavior that makes Lambdas with different variables compare the same. A visible change is that matrix expressions `applyfunc` will no longer create a new Lambda with Dummy symbols when applying a Lambda.
- as_dummy copies symbol commutativity
This keeps the important commutativity attribute of the dummy intact.
- make canonical_variables more canonical
Calling `as_dummy` on an expression should return a canonical expression regardless of
whether clashing symbols are already used. Most importantly, calling the method twice
on the same object will not return a different object than when calling it once.
- Sum shows in count_ops
Sum, unlike Integral, did not appear in visual count_ops expressions. Now it does.

before:
```python
>>> Sum(x, (x, 1, 2)).count_ops()
0
```
now:
```python
    >>> Sum(x, (x, 1, 2)).count_ops(visual=1)  # output is 1 if not visual
    SUM
```
- use xreplace in dummy_eq
This is a small optimization that can be used safely in the function.

#### Release Notes

* core
  - `as_dummy` is now indempotent and should return a more canonical result
  - `Symbol.as_dummy` copies the commutativity of the Symbol
  - `count_ops` will now count/show `Sum` in expressions
  - higher order derivatives will now have a higher value from the `_node` function

### CODE REVIEW

**Comment by smichr** [comment]
@oscarbenjamin , here is a set of relatively small changes that includes the fix for #19326. Please see what you think.

**Comment by oscarbenjamin** [comment]
Do the other changes need to go together with the fix for #19326?

To close that issue we need a PR against 1.6 and I'm wondering if the change to subs ordering can just be cherry-picked.

**Comment by smichr** [comment]
Each commit should be atomic. I think you can just cherry pick 73a0427.

**Comment by oscarbenjamin** [comment]
Thanks. I've opened #19345 for 1.6 with that commit

**Pull request closed without merging**
