### PR TITLE
property is_empty for matrices is added

### PR DESCRIPTION
**Pull request by aravindkanna**
The property `is_empty` checks whether the given matrix is empty or not.

### CODE REVIEW

**Comment by moorepants** [comment]
Is this necessary when all you need is:

```python
In [1]: from sympy import Matrix

In [2]: a = Matrix([])

In [3]: if a: print("Not Empty")

In [4]: b = Matrix([1])

In [5]: if b: print("Not Empty")
Not Empty
```

**Comment by leosartaj** [comment]
IMHO, I don't think this function is of much practical use, when as pointed by @moorepants it is very easy to check if a matrix is empty or not.

**Comment by aravindkanna** [comment]
Yeah, it is easy to check if a matrix is empty or not. Why I tried to do this is for other reason where I use this property. I am looking into [this](https://github.com/sympy/sympy/issues/10701) issue. Then I want to return an empty dict from function eigenvals. For that I have to check whether the given matrix may be an empty one or not. I don't know, may be in future there may be another bug, for which we need to check the same. So to generalise it I want to create a property for a matrix which returns whether it is empty or not.

**Comment by leosartaj** [comment]
Why not do something like this,

```
if not self:
  return {}
```

**Comment by aravindkanna** [comment]
Yeah that is fine. I think to have a clear property for a matrix that it is empty or not is good to see.

**Comment by aravindkanna** [comment]
The issue [10719](https://github.com/sympy/sympy/issues/10719) has been fixed here. Now the eigenvals() function when applied to an empty matrix will return an empty dict and the eigenvects() function returns an empty list for the same with this fix. It also solves the [issue](https://github.com/sympy/sympy/issues/10768) with this fix.

**Comment by aravindkanna** [comment]
Sir what does that mean if it says 
**All checks have failed**

**Comment by leosartaj** [comment]
> Sir what does that mean if it says 
All checks have failed

It means that some tests have failed.

**Comment by aravindkanna** [comment]
So what should I do now and how to find and rectify my code?

**Comment by leosartaj** [comment]
There are some code quality issues. You have trailing white spaces.

**Comment by leosartaj** [comment]
> So what should I do now and how to find and rectify my code?

You can click on the details, and see which tests have failed. After you have fixed, push a commit to the same branch from which you made the PR.

**Comment by leosartaj** [comment]
Also, you opened #10772, which is just a variant of the current fix. It is always good to maintain a single PR for an issue.

**Comment by aravindkanna** [comment]
Sorry sir, that was my mistake. Due to lack of knowledge, I have done that.

**Comment by aravindkanna** [comment]
`sympy/utilities/tests/test_code_quality.py[6] F.....                      [FAIL]`

This is what it is saying. How to understand this?

**Comment by aravindkanna** [comment]
One thing is, I have used some extra spaces which are of no use. So now I have removed them. Now how can I check my code against the code quality issue.

**Comment by leosartaj** [comment]
> Sorry sir, that was my mistake. Due to lack of knowledge, I have done that.

NP. Please no 'sir' is required :smile:

> ``sympy/utilities/tests/test_code_quality.py[6] F..... [FAIL]``
>
> Sir, this is what it is saying. How to understand this?

You can scroll down to the end of file. The error message will be written there. You can also test your changes locally. For eg. to check code quality you can run ``bin/test sympy/utilities/tests/test_code_quality.py``.

**Comment by leosartaj** [comment]
There is another PR fixing the same issue(partially), #10750.

**Comment by aravindkanna** [comment]
This is another one using the property `is_empty`. I have done using that.

**Comment by aravindkanna** [comment]
Yeah obviously I think this is redundant if that was merged previously. If not considering this generalizes the situation.

**Comment by leosartaj** [comment]
Closing in favor of #10750.

**Comment by aravindkanna** [comment]
Sir, So what about the property? Should I add it or not?

**Comment by leosartaj** [comment]
I am not really sure. +0

ping @moorepants

**Comment by leosartaj** [comment]
> Sir, I really worked hard to find and complete the issue sir, this is slightly discouraging!!! Sorry to say that.

Please don't be discouraged if your PR didn't get merged. There are still plenty of issues to work on. Everybody in the community is happy too help. Thanks for all your work. :smile:

**Comment by aravindkanna** [comment]
Thank you. Sir, I want to fork it again. How can I do that?

**Comment by debugger22** [comment]
Did you delete the sympy repo? :)

**Comment by aravindkanna** [comment]
No, I have forked it once. And then made some changes. It is saying 18 commits behind master. So I want to update it. How can I do it?

**Comment by aravindkanna** [comment]
Oh thank you sir, @moorepants . Sir I would now again want to fork it, so what should I do?

**Comment by aravindkanna** [comment]
When I use git pull it is saying already up to date

**Comment by aravindkanna** [comment]
I tried using `git fetch upstream` but it is saying I have no rights!!!

**Comment by aravindkanna** [comment]
Yeah I got it, Thank you everyone for helping. So nice guys :smiley:

**Pull request closed without merging**
