### PR TITLE
Fixes products with arrays with only one element convert to float

### PR DESCRIPTION
**Pull request by yeshsurya**
By change the order to iteration in the for loop, while only one element is present considering int first will resolve the issue.

This change fixes the issue #13637

### CODE REVIEW

**Comment by jksuom** [comment]
Changing the order will convert all floats to integers,  which is probably not correct in general.
```
 >>> Rational(1, 2) * numpy.array([6.6])
3
```

**Comment by yeshsurya** [comment]
Thanks @jksuom . I'm new to sympy. What should be the output of sympy.Rational(1,2) *   numpy.array([1,1.0]) . is it [1/2 0.5] of [0.5 0.5].

**Comment by Abdullahjavednesar** [comment]
@yeshsurya you can try [here](http://live.sympy.org/).

**Comment by jksuom** [comment]
The conversion of NumPy arrays with one element was fixed in https://github.com/sympy/sympy/pull/13927.

**Comment by Abdullahjavednesar** [comment]
Ok, so the issue seems to be fixed, I'll close this.

**Pull request closed without merging**
