### PR TITLE
Solving (-2)**x=4

### PR DESCRIPTION
**Pull request by arihantparsoya**
This is fix for #11096. Previously transcendental equation with only positive bases were being evaluated and hence the equation ((-2)**x=4) could not be solved.
- To account for the problem solve(Eq((-2)**x,4)), function _tsolve can not evaluate transcendental equation with negative bases by re-evaluating it after making the base positive.
- I am not quite sure if the fix is robust. This change is done only for the sake of solving the equations of similar type.
- test case is added.

### CODE REVIEW

**Comment by parsoyaarihant** [comment]
@asmeurer , can you review this?

**Comment by asmeurer** [comment]
Better for @aktech @hargup @Shekharrajak @kshitij10496 to review. They are working on solvers.

**Comment by asmeurer** [comment]
By the way, avoid using special characters in your branch names. It makes it annoying to use them in the command line.

**Comment by asmeurer** [comment]
I believe this fix is wrong. What about `(-2)**x = 8`? This gives `3` for that, but that's the wrong answer.

**Comment by parsoyaarihant** [comment]
yeah, you are right. I will try to make the fix more robust.

Thanks for pointing out.

**Comment by asmeurer** [comment]
A more robust fix may require some work. For complex numbers, the correct thing is to parameterize all the branches of `log` (i.e., add `2*pi*n*I` to the logs in the solution). For the real case, it will need to determine if any of those branches are real (I believe at most one can be). 

I wouldn't worry about `solve`. It's better to direct development effort to `solveset`, unless `solve` is giving wrong answers (it isn't in this case).

**Comment by Shekharrajak** [comment]
`_invert` method need to be improved. I tried to fixed some these types of cases here : https://github.com/sympy/sympy/pull/10971 . I did small modification in the PR for this issue( complex solution fixed). @parsoyaarihant  feel free to add something  or get idea from that PR.

**Pull request closed without merging**
