### PR TITLE
Added inplace row multiplication and row addition methods to matrices

### PR DESCRIPTION
**Pull request by philwillnyc**
#### Brief description of what is fixed or changed

I added two methods to the MutableRepMatrix class: row_add and row_mult. These allow the three basic row operations to be done in-place (row_swap was already supported) in a straightforward way when one creates a matrix in sympy. 

#### Other comments

The motivation for this change came from the use of sympy in teaching linear algebra. I wanted a natural way to demonstrate row reduction in an interactive notebook.

#### Release Notes

* matrices 
  * added row_add and row_mult methods to MutableRepMatrix.

### CODE REVIEW

**Comment by sylee957** [comment]
Unfortunately, I think that there is already `elementary_row_op, elementary_col_op` implemented.

**Comment by philwillnyc** [comment]
Yes, but I believe these are not in-place and also the user has to enter a string as an argument. I think if we have M.row_swap(i,j) available on a matrix M (which we do) it makes sense to have M.row_mult(i,factor) and M.row_add(s,t,factor) as well. At least, this is what I would find most useful for teaching purposes; I understand if that's not a good enough reason.

**Comment by sylee957** [comment]
> I think if we have M.row_swap(i,j) available on a matrix M (which we do) it makes sense to have M.row_mult(i,factor) and M.row_add(s,t,factor) as well.

I think that you can better make it more symmetric, by adding `M.col_mult` and `M.col_swap` as well. I'd defer for other reviewers to vote though.

**Comment by smichr** [comment]
For a given ordering of variables,  only row ops conserve ordering so I think adding these two completes the inplace primitive ops. But for routi es that might implement full pivoting and have the capability of tracking variable order, the other ops make sense. Perhaps handled by doing transpose the row up and transpose again.

**Comment by sylee957** [comment]
I didn’t like the string argument for elementary_row_op anyway. 
So if this was suggested first, I would more strongly agree too.

**Comment by sylee957** [comment]
However, I would suggest to implement same thing with immutable matrix though, before merging this

**Comment by oscarbenjamin** [comment]
> I would suggest to implement same thing with immutable matrix

The exact same thing does not make sense with immutable matrix because these are mutating operations.

**Comment by oscarbenjamin** [comment]
Thanks @philwillnyc and @sylee957

**Pull request merged**
