### PR TITLE
Better support for complex numbers in nsolve

### PR DESCRIPTION
**Pull request by asmeurer**
- Fixes a regression that prevented nsolve from returning a complex number.

- Allow converting SymPy expressions of the form `Number + Number*I` to `mpmath.mpc`.

- Allow SymPy complex numbers as initial point arguments to nsolve (like `nsolve(x**2 + 2, I)`).

Fixes https://github.com/sympy/sympy/issues/12062.

### CODE REVIEW

**Comment by asmeurer** [comment]
Worth noting that this is important because the secant solver of findroot (the default) won't find complex roots of real functions unless the initial point is nonreal.

**Comment by asmeurer** [comment]
Looks like I have some test failures (plus the Python 3.5 tests are failing completely due to some installation error).

**Comment by asmeurer** [comment]
Ah, the pickling tests don't like an attribute raising ValueError. Probably should be AttributeError.

**Comment by asmeurer** [comment]
CC @scopatz

**Comment by scopatz** [comment]
LGTM!

**Pull request merged**
