### PR TITLE
WIP - Use connected components to split systems in solve

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### Brief description of what is fixed or changed

Uses the new connected_components function from #16225 to split systems of equations in solve. As an example a system like
```
solve([a-b, a+b+1, c-d, c-d+e, e-2], [a, b, c, d, e])
```
would be split into two parts:
```
solve([a-b, a+b+1], [a, b])
solve([c-d, c-d+e, e-2], [c, d, e])
```
The solution set for the full system is then the Cartesian product of the solution sets for the individual subsystems. Where it is possible to split the system like this solve should be faster as a result of this PR.

#### Other comments

I'm putting this up now as a work in progress to see how it fairs on the whole test suite.

I'm still working on making it as fast as possible. I'll show some example timings in the comments below.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This example generates a large block diagonal system of linear equations:
```python
from sympy import *
import time

def make_sys(N):
    xs = symbols('x:%d' % N)
    ys = symbols('y:%d' % N)
    eqs = []
    for xi, yi in zip(xs, ys):
        eqs.append(xi + yi - 1)
        eqs.append(xi - yi)
    syms = xs + ys
    return eqs, syms

for n in range(1, 10):
    n = 2**n
    eqs, syms = make_sys(n)
    start = time.time()
    solve(eqs, syms)
    print('n=%2d, %.2f secs' % (n, time.time()-start))
```
Running on master I get:
```
$ python tmp/linsys.py 
n= 2, 0.04 secs
n= 4, 0.04 secs
n= 8, 0.10 secs
n=16, 0.25 secs
n=32, 1.02 secs
n=64, 4.12 secs
n=128, 24.14 secs
n=256, 121.45 secs
Traceback (most recent call last):
 ...
RecursionError: maximum recursion depth exceeded in comparison
```

With this PR I get:
```
$ python tmp/linsys.py 
n= 2, 0.02 secs
n= 4, 0.03 secs
n= 8, 0.07 secs
n=16, 0.15 secs
n=32, 0.47 secs
n=64, 1.55 secs
n=128, 5.70 secs
n=256, 21.30 secs
n=512, 79.19 secs
```
So this is significantly faster and can handle larger systems without RecursionError.

The example there with n=512 is actually a system of 1024 linear equations in 1024 unknowns. It turns out profiling these larger examples that the time is dominated by the code in solve that prepares the system before reaching this point. Somehow something in there is quadratic... it's here:
[https://github.com/sympy/sympy/blob/master/sympy/solvers/solvers.py#L1047](https://github.com/sympy/sympy/blob/master/sympy/solvers/solvers.py#L1047)
This PR has the potential to make solve linear rather than quadratic for cases like this. However that call to any is still quadratic and takes the majority of the time under test script above.

**Comment by smichr** [comment]
Very nice, @oscarbenjamin . I suspect this would be able to be used to address #15441, too.

**Comment by oscarbenjamin** [comment]
This example is a mixed linear polynomial system the number of solutions goes like `2**n` so generating the full product of solutions takes the most time.
```python
from sympy import *
import time

def make_polysys(N):
    xs = symbols('x:%d' % N)
    ys = symbols('y:%d' % N)
    eqs = []
    for xi, yi in zip(xs, ys):
        eqs.append(xi**2 + yi**2-1)
        eqs.append(xi + yi - 2)
    syms = xs + ys
    return eqs, syms

for n in range(1, 10):
    eqs, syms = make_polysys(n)
    start = time.time()
    solve(eqs, syms)
    print('n=%2d, %.2f secs' % (n, time.time()-start))
```

Timings on master:
```
$ python tmp/polysys.py 
n= 1, 0.27 secs
n= 2, 0.22 secs
n= 3, 0.60 secs
n= 4, 1.55 secs
n= 5, 3.97 secs
n= 6, 10.01 secs
n= 7, 23.04 secs
n= 8, 58.22 secs
n= 9, 136.50 secs
```
Timings with this PR:
```
$ python tmp/polysys.py 
n= 1, 0.27 secs
n= 2, 0.06 secs
n= 3, 0.10 secs
n= 4, 0.15 secs
n= 5, 0.30 secs
n= 6, 0.69 secs
n= 7, 1.62 secs
n= 8, 4.02 secs
n= 9, 9.90 secs
```
This performance actually is linear in a different sense: the number of solutions is growing exponentially. The time taken is linear in the number of solutions.

This time the limiting factor is also elsewhere in solve in postprocessing the solutions. The majority of the time for the above test script is spent on this line:
[https://github.com/sympy/sympy/blob/14a5477a0cac3b2c5513f82a4585d38c0f4a9123/sympy/solvers/solvers.py#L1233](https://github.com/sympy/sympy/blob/14a5477a0cac3b2c5513f82a4585d38c0f4a9123/sympy/solvers/solvers.py#L1233)
For `n=9` we have that `len(symbols)==18` and `len(solutions)==512` so calling `subs` `18*512` times seems to be the slowest part of solving this system.

**Comment by oscarbenjamin** [comment]
> I suspect this would be able to be used to address #15441, too.

Actually right now this just separates the system into uncoupled parts so I don't think it would do anything for #15441 

Define the graph such that
1. The vertices are the equations you're solving
2. Two equations are connected if they have any unknown symbols in common
then this PR splits a system into the connected components of that graph. Splitting the system in this way should be always valid for any types of equations and should lead to quicker solutions almost always.

To use this kind of idea to solve for one variable and substitute that into another equation we would somehow need to define a directed graph between either the equations or the unknowns and then find the strongly connected components of that.

I'm not sure how to define what the vertices/edges of that graph would be. If the vertices were the symbols then these equations:
```
[A-2, A+B+C, B-C, D+C], 
```
Should lead to a graph with these edges (or perhaps the reverse):
```
    A -> B
    B -> C -> B
    C -> D
```

**Comment by oscarbenjamin** [comment]
I've just pushed some changes to get better linear performance for large systems.

Comparing linsys.py (as show above) I get approximately linear performance for this PR:
```console
$ python tmp/linsys.py  # PR
n= 2, 0.03 secs
n= 4, 0.02 secs
n= 8, 0.05 secs
n=16, 0.09 secs
n=32, 0.17 secs
n=64, 0.35 secs
n=128, 0.82 secs
n=256, 2.07 secs
n=512, 4.33 secs
```
For master
```console
$ python tmp/linsys.py # master
n= 2, 0.02 secs
n= 4, 0.03 secs
n= 8, 0.08 secs
n=16, 0.24 secs
n=32, 0.94 secs
n=64, 3.98 secs
n=128, 20.77 secs
n=256, 117.76 secs
^CTraceback
```

The polysys.py example above is now significantly faster with this PR (performance is linear in the number of solutions which goes like `2**n`):
```console
$ python tmp/polysys.py # PR
n= 1, 0.26 secs
n= 2, 0.05 secs
n= 3, 0.07 secs
n= 4, 0.09 secs
n= 5, 0.11 secs
n= 6, 0.13 secs
n= 7, 0.17 secs
n= 8, 0.23 secs
n= 9, 0.36 secs
n=10, 0.60 secs
n=11, 1.10 secs
n=12, 2.23 secs
n=13, 4.95 secs
```
Comparable timings for master are much worse:
```console
$ python tmp/polysys.py # master
n= 1, 0.26 secs
n= 2, 0.22 secs
n= 3, 0.57 secs
n= 4, 1.49 secs
n= 5, 3.90 secs
n= 6, 9.42 secs
n= 7, 22.84 secs
n= 8, 54.20 secs
n= 9, 132.20 secs
n=10, 297.15 secs
^CTraceback
```

**Comment by oscarbenjamin** [comment]
I'm finding it hard to reproduce the test added in #5849 which is:
```python
    e = (
        I1 - I2 - I3,
        I3 - I4 - I5,
        I4 + I5 - I6,
        -I1 + I2 + I6,
        -2*I1 - 2*I3 - 2*I5 - 3*I6 - dI1/2 + 12,
        -I4 + dQ4,
        -I2 + dQ2,
        2*I3 + 2*I5 + 3*I6 - Q2,
        I4 - 2*I5 + 2*Q4 + dI4
    )
    # This system is overdetermined. We need I1 = I2 + I3 and I1 = I2 + I6 but
    # those two are most likely inconsistent. I don't know how this works
    # without this PR but this fails with the PR because e.g.:
    #
    # In [1]: solve([x-y, x-z], [x])
    # Out[1]: []
    assert solve(e, I1, I4, Q2, Q4, dI1, dI4, dQ2, dQ4) == {
        dI4: -I3 + 3*I5 - 2*Q4,
        dI1: -4*I2 - 8*I3 - 4*I5 - 6*I6 + 24,
        dQ2: I2,
        I1: I2 + I3,
        Q2: 2*I3 + 2*I5 + 3*I6,
        dQ4: I3 - I5,
I4: I3 - I5}
```

If you just take the two equations for I1 you can see that they are overdetermined. A solution only exists if I3==I6 but we have no way of knowing if that is true. Solve normally returns the empty set in such situations:
```
In [10]: solve([x-y, x-z], [x])                                                                          
Out[10]: []
```
So what should happen here is the test from #5849 wrong? Is it a bug that the last example returns an empty set?

Should solve really return piecewise solutions for this sort of thing (e.g. conditional on y=z)?

I can't see a clear policy describing the ideal behaviour of solve for overdetermined systems.

**Comment by oscarbenjamin** [comment]
Apart from #16385 this PR is waiting for some confirmation about how overdetermined systems should be handled by solve.

What is the general principle that solve should use when faced with overdetermined system having symbols meaning that it may or may nor be consistent? For example what should
```
solve([x-y, x+y], [x])
```
return? Currently that gives an empty list but there is a solution `x=0` if `y=0`. Should the solution be a Piecewise or something? Should it return `x=0,y=0` with the y equation as an auxiliary constraint equation? Is the current empty list correct?

**Comment by asmeurer** [comment]
Did you intend to push this branch up to the main repo instead of your fork?

**Comment by oscarbenjamin** [comment]
> Did you intend to push this branch up to the main repo instead of your fork?

No I intended to push to my fork and send this as a PR to sympy/sympy:master. I'm not sure how this happened...

**Comment by oscarbenjamin** [comment]
I've pushed this to my fork now. Do I need to close this PR and open a new one (and then delete this branch)?

**Comment by smichr** [comment]
> Piecewise or something? Should it return `x=0,y=0` with the y equation as an auxiliary constraint equation?

or just return `[-y]`?

**Comment by oscarbenjamin** [comment]
It could return `[-y]` or instead `[+y]` or indeed `[0]` since if a solution exists those should all be equal. As a user I would prefer the explicit `[0]` but I would also like to know in some way that my solution is not always valid and to know when it would be valid. The API of solve doesn't seem to have a way to deal with this. The solveset API doesn't seem to solve this problem either.

**Comment by oscarbenjamin** [comment]
I've opened #16550 as a replacement for this. That one is a PR from a branch on my fork rather than this branch I accidentally created in sympy/sympy.

**Pull request closed without merging**
