### PR TITLE
Possibility to switch rules/integration off in Laplace transform

### PR DESCRIPTION
**Pull request by hanspi42**
#### References to other Issues or PRs

Part of  #24561

#### Brief description of what is fixed or changed

`laplace_transform` and `LaplaceTransform.doit` now have a named keyword `inhibit` that makes it possible to switch simple rules, program rules, all rules and integration off. Tests have been added for this.

#### Release Notes

* integrals
  * Rules and integration can now be switched off in `laplace_transform`

### CODE REVIEW

**Comment by asmeurer** [comment]
I would rather make this work with boolean flags like the way the hints to `integrate` work.

**Comment by hanspi42** [comment]
> I would rather make this work with boolean flags like the way the hints to `integrate` work.

OK, I'll do that. But I will still make it a named argument. If I remember correctly, @oscarbenjamin ultimately wants to get rid of the integrate's `**hints` mechanism because it is not a good API, so I'd rather not add anything to the `**hints` themselves.

**Comment by hanspi42** [comment]
I have changed it, and added a function `_laplace_process_inhibit` such that there is only one place where a decision on valid arguments is made. What do you think?

**Comment by asmeurer** [comment]
I haven't heard @oscarbenjamin's arguments about integral hints. I like them and don't think we should get rid of them.

The issue I have with this still is that it's an inverted API. You list as True the hints you want to turn off. It would be simpler if you simply listed the hints don't want directly as `prog_rule=False`, etc. Further, we can follow the integrate() API and enable a hint and only that hint if it is set to True (e.g., `integrate(meijerg=True)` will only run the meijerg algorithm and skip the rest).

**Comment by sylee957** [comment]
I think that if you have to use collected options, it is better to use finite and annotated dictionary like `TypedDict` with defaults than `dict`.
I'm also unsure if we should commit the options now though, if it is not critically needed for usage though. I'm not sure why would some people want to turn off `integrate` or `prog_rules` now unless for debugging purpose

**Comment by hanspi42** [comment]
> Why would some people want to turn off `integrate` or `prog_rules` now unless for debugging purpose

Oh, if you yourself forgot why, then I close this PR immediately; this work step is in my list because of you ;))))

https://github.com/sympy/sympy/pull/24492#discussion_r1082468950

**Comment by hanspi42** [comment]
I have another important question: On my list I have `LT: Make simplify default to False.` I will ask whether we should really do this at the end of #24561

**Pull request closed without merging**
