### PR TITLE
New exponential function represented as power

### PR DESCRIPTION
**Pull request by Upabjojr**
Splitting the work in https://github.com/sympy/sympy/pull/13211 - that PR is huge.

This PR introduces a new E constant (`S.Exp1New` or `_E_new`) whose exponential evaluates to `Pow` (and not `exp`, unlike `S.Exp1`).

This is a first step into removing the class `exp` in order to represent the exponential as a `Pow` object.

#### Release Notes

* core
  * Introduce a second E constant whose exponent is evaluated into Pow.
* functions
  * Introduce an second hidden exponential functions evaluating to Pow.

### CODE REVIEW

**Comment by Upabjojr** [comment]
First step to solve https://github.com/sympy/sympy/issues/4898

**Comment by asmeurer** [comment]
Is the goal to remove this once the second phase is done? I don't think we should have two exponential constants.

**Comment by Upabjojr** [comment]
> Is the goal to remove this once the second phase is done?

Yes, that's my intention.

> I don't think we should have two exponential constants.

We need this anyway. RUBI integration rules are designed to match expressions like `Pow(E, x)`, not `exp(x)`. There is currently a makeshift exponential inside `sympy.integrals.rubi` to circumvent this limitation, but I would recommend moving this functionality to SymPy's core.

**Comment by Upabjojr** [comment]
Replacing `exp(x)` with `Pow(E, x)` should be done one step at the time. Indeed, #13211 is an example of how complicated it is to do it in a single PR.

**Comment by asmeurer** [comment]
But we should only have one way of representing it. I agree that Pow(E, x) is the better way. 

> Replacing exp(x) with Pow(E, x) should be done one step at the time. Indeed, #13211 is an example of how complicated it is to do it in a single PR.

This is probably fine, as long as you intend to finish the work. Otherwise we would be left with both in place which would be worse than what we have now. How many additional PRs do you anticipate? How close was https://github.com/sympy/sympy/pull/13211 to being finished at the time?

My concern is that this intermediate step adds what is apparently a public API that will soon be removed. So I'd be happier if the new Exp1New constant were instead `_Exp1New` (and is it necessary to add it to `S`?), and we shouldn't mention such details in the release notes either. Eventually just `E` will be the one exponential constant and `E**x` or `exp(x)` will seamlessly work as before but by creating a `Pow` object instead of an `exp` object.

**Comment by oscarbenjamin** [comment]
> Otherwise we would be left with both in place which would be worse than what we have now

I can see the advantage in building this one PR at a time but I'm not sure I see the advantage in merging this one PR at a time. Ultimately until the final PR is merged no real benefit is gained.

I don't see an approach in this PR that can deliver the benefits of this change without the backwards compatibility break. If we're happy to break compatibility for this then why not just change everything at once. If there is a way to get the benefit of the change without breaking anything then that is different.

I'm happy to review/merge a large PR if that is what is needed. I'd be interested though to know about the knock on impact for downstream projects before merging. I presume that the reason #13211 is so large is because it resolves all the internal compatibility problems within the sympy codebase. That seems like a straight-forward indication of how problematic this could be for some downstream codebases.

**Comment by asmeurer** [comment]
I'm also interested to know what the backwards compatibility breaks are. This should be apparent from the sorts of changes that are needed in library code. 

Just from a glance, some things I can see are:

- `isinstance(expr, exp)` will stop working. We can workaround this by making `exp` a dummy class with a metaclass that defines `__instancecheck__` (https://docs.python.org/3/reference/datamodel.html#customizing-instance-and-subclass-checks) and gives a deprecation warning when used. Same with ExpBase, although IMO base classes should not be considered part of the public API.
- `exp.inverse` is defined as `log`. `Pow.inverse` can't be defined because it is a two-argument function. We could make this a deprecation as well, though I'm unsure how much user code makes use of `inverse`. Most use-cases should be using `solve` directly.
- ExpBase has `unbranched`. The whole ExpBase base class would need to be removed, as it would only be needed for `exp_polar`. 
- `exp` would no longer be a subclass of Function, so some methods from Function may be gone. We should consider if adding those methods to Pow or Expr makes sense. Some others, like `fdiff` are IMO implementation details that really should be used outside of library code anyway.

What else is there?

It's possible, but seems doubtful, that some code could implicitly assume that Pow.base is never Exp1. But even if that somehow happened, could it happen that non-updated code produces a wrong answer?

**Comment by oscarbenjamin** [comment]
I think that to some extent the details don't matter. The full change would break some things simply because `exp(x)` changes from being an instance of `exp` to an instance of `Pow` (which is the desired effect). I have written code that does e.g. `expr.collect(expr.atoms(exp))` which would break as a result of the change of class and there's really no way to mitigate that at the same time as achieving the desired effect of the change.

The fundamental questions are:

1. Are we sure we want this change?
2. Is it worth the breakage?
3. Is there a better way of mitigating the breakage?

I think that we want the change and that the breakage is, in the long run, worthwhile. If the breakage can be minimised then that's better but we may need to think about this as a change for a future breaking 2.0 release. We can't afford to have too many breaking releases so if that's what we want then we should make a broader plan. This isn't the only thing that needs fixing but can't be fixed without a breaking change.

**Comment by asmeurer** [comment]
I agree that `isinstance` is most likely the biggest source of problems, but fortunately, it can be deprecated. `atoms` uses `isinstance` under the hood, so a deprecation warning in `type(exp).__instancecheck__` would guard against that. User code that incorrectly uses `type(expr) is exp` instead of `isinstance(expr, exp)` would have no protections, but there's nothing we can do about that. `isinstance` should almost always be preferred over a direct type check anyway.

I think it's worth the change. Most of the code in `exp` is completely unnecessary as a duplication of the general case in `Pow`. That means any time some code is added or fixed in `Pow`, the same fix has to be applied to `exp`. Here's an example inconsistency that I just found:

```py
>>> 2**(log(2, 2)*y)
2**y
>>> exp(log(2)*y)
exp(y*log(2))
```

If you look through the cross references in https://github.com/sympy/sympy/issues/4898, you can see some of the history of this sort of thing. And the flip side to the above example is that `atoms(Pow)` doesn't give base-e exponentials, nor does any other place that uses `isinstance(Pow)`.

> If the breakage can be minimised then that's better but we may need to think about this as a change for a future breaking 2.0 release. We can't afford to have too many breaking releases so if that's what we want then we should make a broader plan. This isn't the only thing that needs fixing but can't be fixed without a breaking change.

Well I would make a distinction between "breaking" changes that can be deprecated and those that can't. Deprecated code can continue to work. It just spits out annoying errors until you fix your code. That's much different from a change that cannot be deprecated. To me those are the real "breaking" changes. 

I think most of the issues in this PR can be successfully deprecated, though I could be wrong if there is some other issue I didn't think about above.

**Comment by Upabjojr** [comment]
> So I'd be happier if the new Exp1New constant were instead `_Exp1New` (and is it necessary to add it to `S`?), and we shouldn't mention such details in the release notes either.

Yes, sure. I can rename it.

> I don't see an approach in this PR that can deliver the benefits of this change without the backwards compatibility break.

Well, actually having a SymPy release with both modes could actually improve compatibility and avoid complications. For example, the next SymPy release could be endowed with a global parameter to select which way `exp(x)` should be represented.

For example, once `S.Exp1New` is ready and behaves exactly like `S.Exp1`, we could have a period to let users sync their code to tune with the new behaviour or roll back in case of inconsistencies. I was also planning on adding some conversion expressions to switch between the old `Exp1` and the new `Exp1New`.

I'm not going to prepare a single PR for this change... I've already tried and came to the conclusion that's way better to split the work into smaller PRs.

**Comment by asmeurer** [comment]
Is there a reason we need two constants? Can't we just disable Pow(E, x) -> exp(x) so that it is possible to create both as separate objects? In fact, exp(x) doesn't even make use of S.Exp1. It is only used as the return value if x = 1.

**Comment by Upabjojr** [comment]
> Is there a reason we need two constants? Can't we just disable Pow(E, x) -> exp(x) so that it is possible to create both as separate objects? In fact, exp(x) doesn't even make use of S.Exp1. It is only used as the return value if x = 1.

Do you mean a general parameter (maybe similar to _global evaluate_) to control the behaviour of `S.Exp1` when passed as base of `Pow`?

**Comment by Upabjojr** [comment]
Or maybe with a context manager:

```python
with NewExp1():
    print(type(exp(x)))  # prints Pow
print(type(exp(x)))  # prints exp
```

**Comment by oscargus** [comment]
This is somehow related to #21911. Maybe it is better in the long run to only have Pow(E, x) (and let exp(x) map to Pow(E, x) and possibly still print as Pow(E, x)) and let `log(x) always be represented as `LogWithBase(x, E)` (which then can be called `log(x, E)` but print as `log(x)`). I guess the main problem for the latter case is then to deal with optional arguments in functions.

**Comment by Upabjojr** [comment]
I am closing this PR as the approach that has been merged into master is completely different. There is now a global parameter that tells SymPy whether `exp(x)` should be a function or should be represented as `Pow(E, x)`. No new constant is necessary right now.

**Comment by Upabjojr** [comment]
> May require some more changes since many methods only work for exp and not Pow, but may also be good since some do work for Pow and there is no need to have a separate exp (and some may actually work with Pow although that is not covered yet).

@oscargus you can put the decorator `@_both_exp_and_pow` in front of the unit testing functions in order to test the code twice, both with the representation `exp(x)` and `Pow(E, x)`.

**Pull request closed without merging**
