### PR TITLE
Fixed beam markdown

### LINKED ISSUE #16712: fix beam markdown
from #16677: the markdown for example 11 should be corrected, to fix table of contents

### PR DESCRIPTION
**Pull request by arooshiverma**
#### References to other Issues or PRs

Fixes #16712 

#### Brief description of what is fixed or changed
Fixed indentation of Example 11 of Table of Contents for Beam

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by Abdullahjavednesar** [comment]
Looks good!

**Comment by Sc0rpi0n101** [comment]
Is it supposed only to be format change for example 11? 

That's a very small patch.

You can try exploring the file more and maybe fix some other mistakes or wrong formatting for other parts of the file too

**Comment by sylee957** [comment]
This was already fixed in https://github.com/sympy/sympy/issues/16712
see https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam_problems.html

**Comment by arooshiverma** [comment]
@sylee957 I saw that just now. I have corrected a few grammatical errors as well.

**Comment by smichr** [comment]
+1

**Pull request merged**
