### PR TITLE
Fixed syntax error

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed
Found a typo...

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Is this already fixed on master?

**Comment by oscargus** [comment]
I think I changed it in another PR that should go to master, but I cannot seem to recall which one right now... (Can be one branch where there is no PR yet). Thought it was important to get it into 1.9 though so made a separate one.

**Comment by oscarbenjamin** [comment]
It gets very confusing if a fix is made on the release branch but not on master. Effectively it is an immediate regression. I think it's better that something gets fixed on master and then the fix is "backported" to the release branch.

Can you open a PR for master as well so both can be merged at once?

**Comment by oscargus** [comment]
Sure! Wasn't sure exactly how the different branches were handled. If one could "forward-port" or not. #22095

**Pull request merged**
