### PR TITLE
Implemented Partial Pivoting

### PR DESCRIPTION
**Pull request by ahhda**
Solves Part - I of #9060 
Sympy currently uses trivial pivoting i.e. it selects the first non-zero term in the column.
However that is numerically unstable.
This PR implements partial pivoting i.e. swap with the largest term in the column.
Also added support for symbolics.

### CODE REVIEW

**Comment by ahhda** [comment]
@moorepants This is in reference to PR [9109] (https://github.com/sympy/sympy/pull/9109/).
Is this fine ?

**Comment by moorepants** [comment]
You are going to need to write unit tests for this. I'd suggest creating matrices that have mixed types and ones that have uniform types to make sure it works.

**Comment by smichr** [comment]
:information_source: could you please change the title of the PR? Including the issue number there isn't as useful as putting it in the Description (first paragraph above) because it doesn't create a clickable link in the Title.

:eyeglasses: See also: **Writing pull request title and description** at [the wiki](https://github.com/sympy/sympy/wiki/Development-workflow) 

Note, also, that github conveniently has a syntax for referring to issues: just prefix the issue/PR number with `#` as in #9060.

**Comment by smichr** [comment]
There are errors that need to be fixed. (The [skip ci] in commit messages is keeping testing from being done.)

**Comment by cbm755** [comment]
This may be more controversial than I thought: I'm new at all this and I don't want to lead you on a wild goose chase for something that might not get merged...  Just a warning.

1.  My preference---I think---would be to have a different implementation for Floats (rather than try: except: as you've done it).  But maybe your way is more pythonic?  (i.e., if the matrix has a mix of Floats and non-Floats I'm not sure what I expect).

2.  What you've implemented doesn't look like partial pivoting to me: it should always find the largest pivot, rather than only when it detects a zero.

3.  As others said, this needs tests.  In particular, it needs a convincing test where the current pivoting strategy is far from optimal.

**Comment by ahhda** [comment]
@smichr Yes, there are errors and I will try to solve them by tomorrow(I have an exam today) and will also add tests.
@cbm755 Sir, I maybe wrong but what I'm reading from [This Source](http://mathfaculty.fullerton.edu/mathews/n2003/PivotingMod.html) says that If  ,  do not switch rows.  If  ,  locate row u below p in which   and  and then switch rows u and p.

**Comment by cbm755** [comment]
I don't know that source, but e.g., Burden & Faires say "to reduce roundoff error, it is often necessary to perform row interchanges even when the pivot elements are not zero".

They give this example to play with:
````
AA = Matrix([[Float('0.003000'), Float('59.14'), Float('59.17')], [Float('5.291'), Float('-6.130'), Float('46.78')]])
````

**Comment by moorepants** [comment]
Yes, @cbm755 warnings are good. You fundamentally can't create this for symbolics, that's why it only looked for zero entries in the original implementation. So you'll have to make clever solution to handle mixed types.

**Comment by ahhda** [comment]
Modified so that it performs row interchange with the maximum element even if the pivot elements are not zero. Also added tests.
The code fails some test in heurisch and integrals.
According to me it fails if there are some complex functions involved.
For example what it should print:
```
>>> M = Matrix([[S(1)/4, 1], [1, 1]])
>>> M.eigenvects(simplify=True)
[(5/8 + sqrt(73)/8, 1, [Matrix([
[8/(3 + sqrt(73))],
[               1]])]), (-sqrt(73)/8 + 5/8, 1, [Matrix([
[8/(-sqrt(73) + 3)],
[                1]])])]
```
And what it prints
```
[(5/8 + sqrt(73)/8, 1, [Matrix([
[8/(3 + sqrt(73))],
[               1]])]), (-sqrt(73)/8 + 5/8, 1, [Matrix([
[-sqrt(73) - 3],
[            8]])])]
```

**Comment by cbm755** [comment]
How do those tests check this issue?  Surely those examples take the "no inequality" route?

If you want to pursue this you will need some convincing examples that sympy needs this sort of change (hint: see my example above)...

**Comment by cbm755** [comment]
> According to me it fails if there are some complex functions involved.

fails?  If you change pivoting of course precise form of some answers are going to change...

complex?  All of that looks real to me.

**Comment by ahhda** [comment]
Pardon me by complex I meant complicated.
Yes you are right I should add some convincing tests.
Using the example given by you
```
>>> AA = Matrix([[Float('0.003000'), Float('59.14'), Float('59.17')], [Float('5.291'), Float('-6.130'), Float('46.78')]])
```
What sympy normally gives:
```
>>> AA.rref()
(Matrix([
[1.0,   0, 10.0000000000036],
[  0, 1.0,              1.0]]), [0, 1])
```
This is what partial pivoting gives:
```
(Matrix([
[1.0,   0, 10.0],
[  0, 1.0,  1.0]]), [0, 1])
```
Is this test good enough ?
Also It is giving wrong results for some integrals. For example:
```python
print expand_func(integrate(sin(x**2), x))
#output
0
```
What it should give:
```python
sqrt(2)*sqrt(pi)*fresnels(sqrt(2)*x/sqrt(pi))/2
```

**Comment by moorepants** [comment]
What is the status here? @ahhda Do you plan on working on this more?

**Comment by tokencolour** [comment]
I am a newbie and I will like to work on it. What are some things which I should keep in mind (as the solution that I have in my mind is mostly what @ahhda did)?

**Comment by moorepants** [comment]
What is the status here? Did we abandon trying to do numerical row reduction?

**Comment by ahhda** [comment]
@moorepants I will be working on this issue and will try to find a good fix. According to me only implementing partial pivoting doesn't solve the original issue. But I believe improving the numerical stability should decrease the growth in error.
And also I cannot find a convincing example that sympy needs partial pivoting. Maybe only when we find the solution for the original issue in which partial pivoting is used, we can be sure that sympy needs this kind of change.
I checked out the `rref` in Octave and found out that it doesn't give correct output for:
```octave
octave:14> AA = [0.003 59.14 59.17; 5.291 -6.13 46.78]
AA =

   3.0000e-03   5.9140e+01   5.9170e+01
   5.2910e+00  -6.1300e+00   4.6780e+01
```
On applying rref gives:
```octave
octave:15> rref(AA)
ans =

    1    0   10
    0    1    1
```
Whereas the ans should be something like
```
[1   0   10.006468605217]
[0   1   1.0055832610442]
```
So I suppose looking at `rref` code of Octave as pointed out in https://github.com/sympy/sympy/issues/9060#issuecomment-77054902 wouldn't help.
Should I make use of `iszerofunc` keyword by calculating the precision of `Float`s inside the Matrix as pointed out by https://github.com/sympy/sympy/issues/9060#issuecomment-77054902 and https://github.com/sympy/sympy/issues/9060#issuecomment-76320507 ?

**Comment by siefkenj** [comment]
This should be resolved as of PR #11554, so perhaps we can close this?

**Pull request closed without merging**
