### PR TITLE
[WIP] handling linear modular equations in solveset

### LINKED ISSUE #13178: Ability to solve modular equations with integer solutions
See for instance https://www.johndcook.com/blog/2017/08/22/predicting-a-lcg-output/. It would be cool if you could just write

```py
n = symbols('n', integer=True)
a = 742938285
z = 1898888478
m = 2**31 - 1
x = 20170816
solveset(x – Mod(a**n*z, m), n, S.Integers)
```

and it produced the answer {100}.

### PR DESCRIPTION
**Pull request by jmig5776**
#### Brief description of what is fixed or changed
Fixes #13178

This PR basically implements `_solve_modular` which will be solving linear modular equations.
Currently it is incomplete.
Solves below example
```
>>> n = symbols('n', integer=True)
>>> a = 742938285
>>> z = 1898888478
>>> m = 2**31 - 1
>>> x = 20170816
>>> solveset(x - Mod(a**n*z, m), n, S.Integers)
{100}
```
#### Other comments
@smichr @aktech @Yathartha22 

#### Release Notes

* solvers
  * implementing `_solve_modular` for handling linear modular equations.

### CODE REVIEW

**Comment by jmig5776** [comment]
I want to clear here that it is just a basic code structure to show you how the modular equations will be handled. If everybody agrees with the approach then I will further work upon this approach.

All the documentation and rest work will be done if all of you @smichr @Yathartha22 @aktech agrees with my approach.

**Comment by jmig5776** [comment]
This unexpected error has occurred of which i dont know. Can someone please explain?

Screenshot from 2019-03-25 02-45-31

**Comment by oscarbenjamin** [comment]
I ran this test locally and entered the debugger with:
```
$ pytest sympy/geometry/tests/test_line.py -k test_basic_properties_2d --pdb
```
Then in the debugger:
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /Users/enojb/current/sympy/sympy/sympy/logic/boolalg.py(157)as_set()
-> return self.subs(reps)._eval_as_set()
(Pdb) p self
(2*Mod(x, 2*pi)/pi > 1) & (2*Mod(x, 2*pi)/pi < 3)
(Pdb) p reps
{2*Mod(x, 2*pi)/pi > 1: False, 2*Mod(x, 2*pi)/pi < 3: (-oo < x) & (x < oo)}
(Pdb) p self.subs(reps)
False
(Pdb) self.subs(reps)._eval_as_set()
*** AttributeError: 'BooleanFalse' object has no attribute '_eval_as_set'
```
Since self is an And and one of the conditions is evaluated as False the whole relation evalutes to False. Then is doesn't have an `_eval_as_set` method.

Maybe that line should be modified to do
```python
sefsubs = self.subs(reps)
if selfsubs is S.False:
    selfset = S.EmptySet
else:
    selfset = selfsubs._eval_as_set()
return selfset
```

**Comment by jmig5776** [comment]
What you suggested is good, but i analysed my code and its need to be changed. I will soon fix it.

**Comment by jmig5776** [comment]
@smichr , @oscarbenjamin , @Yathartha22 Please review this PR. This handles most of the modular equations.

**Comment by jmig5776** [comment]
@smichr @oscarbenjamin @Yathartha22 Please review it.

**Pull request closed without merging**
