### PR TITLE
fix of #11726: pde_separate() allows expressions as input

### PR DESCRIPTION
**Pull request by guoyicong**
The problem is described in #11726. I did a little modification so that pde_separate() will accept either an Equality or an expression as input, with the expression assumed to be equal to 0.

### CODE REVIEW

**Comment by smichr** [comment]
Adding a test from the issue would make this complete and ready to merge.

**Comment by guoyicong** [comment]
@smichr Test added! Let me know if I did it correctly. Thanks a lot for reviewing :)

**Comment by guoyicong** [comment]
@smichr @asmeurer @jksuom Hi, I was wondering if you could review this. Thanks!

**Comment by smichr** [comment]
Thanks for the additional test. This is now committed.

**Pull request merged**
