### PR TITLE
Update test split density

### LINKED ISSUE #19536: Slow coverage job on Travis
The coverage, Python 3.6 split 3/4 job on Travis has slowed down from taking around 39 minutes to around 49 minutes. This is very close to the 50 minute cutoff on Travis meaning that the job can fail sporadically.

On the master build the first commit showing this slowdown is #19472 but I don't see anything there that would explain it.

Rather I think what has happened is that some slow ODE tests have moved from SPLIT 4/4 to SPLIT 3/4 making one job slower and the other faster.

This issue can be fixed by rerunning the splits i.e.:
https://github.com/sympy/sympy/blob/e339db350473e9fe923cef84915f1385de4066e3/sympy/testing/runtests.py#L47-L67

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

Fixes #19536

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This looks good.

I think that part of the problem is that there are too many slow tests that aren't marked as slow (especially in ode).

If the timings here come out closer to even then we should merge it. Afterwards though the slow markers should be reviewed and the splits rerun. I think anything above 10 seconds should be marked as slow.

**Comment by sylee957** [comment]
Actually, it became worse after running the script as done in the file.
Had I missed something.

**Comment by oscarbenjamin** [comment]
> Had I missed something.

I'm not sure.

Maybe the problem is that we need to fix the slow markers first.

**Comment by sylee957** [comment]
I'm not sure if everything should be marked as slow, or some tests functions should be splitted.
I think that only a few singleton tests that really run slow should be identified as slow, and most of the slow tests can also be splitted if it is not a single procedure.

**Comment by oscarbenjamin** [comment]
The ODE tests should certainly be rearrange and split into multiple tests. I've been meaning to do it or some time to identify a subset of the tests that are fast(er) and give maximum coverage.

**Comment by oscarbenjamin** [comment]
Maybe it would work better to do the split timings with coverage recording enabled.

**Comment by sylee957** [comment]
Actually, the test method does not work with windows because there of some unix specific commands in test script.
I'm trying with unix again.

**Comment by oscarbenjamin** [comment]
Is gmpy2 installed on Travis when running the tests? That would speed things up a lot if not. Also it would possibly explain why the timings work out differently when running the test split locally vs on Travis.

**Comment by gschintgen** [comment]
> Is gmpy2 installed on Travis when running the tests?

It doesn't seem so:
https://travis-ci.org/github/sympy/sympy/jobs/701162520#L376

AFAICS there is only one of the baseline tests (the fourth one) that runs with a large (complete?) collection of optional dependencies. From the look of it the rest of the test suite uses python integers.

**Comment by sylee957** [comment]
I haven’t splitted up using gmpy for local environment.

And I have some doubts whether gmpy can actually help with solvers or ode.

After reading the travis log, It is just strange that the tests containing few ode test and way fewer overall tests is now failing.

**Comment by gschintgen** [comment]
I'm not sure this can be properly fixed without a split up of the ODE tests. If I understand the densities correct, there's one chunk of tests (probably one module? ODE I guess) that has a whopping 0.2806, i.e. 28%. And the testrunner is not trying to solve the knapsack problem, it just splits when the alotted cumulative density for a given `SPLIT` has been reached. So this huge block of tests will only jump around between splits 3/4 and 4/4. (But I'm probably just restating the obvious here.)

**Comment by gschintgen** [comment]
> there's one chunk of tests (probably one module? ODE I guess)

Wait, I don't think I got this one right. The script to update the split densities is it the one from the comments here?
https://github.com/sympy/sympy/blob/fdf99fa4b9b8ecb4c59a6d86ada7cdf203204d0b/sympy/testing/runtests.py#L47-L65
If so, aren't those densities computed per 1/30th of the whole testsuite and not per module? Wouldn't it be possible to split up the test suite into, let's say, 60 equal parts and then compute the timings? That could result in finer-grained timings, no?

**Comment by gschintgen** [comment]
Hmm, `split_list` in the testrunner is a bit more sophisticated after all.
But the better the density is known, the easier it will be to correctly split the tests. It's unfortunate though that many of the slower tests are concentrated in the solvers. Anyway, before I continue "spamming" in this thread I'll test out the idea of creating timing densities using 60 splits instead of 30, with one more digit of precision. (If it works out, it will still have the disadvantage that the data will go stale faster. But it could buy some time to further split up the slower tests in order to have a more uniform distribution.)

**Comment by oscarbenjamin** [comment]
Using gmpy2 makes the test suite something like twice as fast in general. If we're not using it on Travis then I think we should.

**Comment by sylee957** [comment]
I have just updated the densities to be more granular
But I see you have already opened up an another PR #19626

I think that containing a chunk of ODE tests adds more than 10 minutes, and a chunk of integrals add about 5 minutes.
But when I see how ODE tests are organized, I see multiple tests are , so they should be splitted to multiple files because we cannot divide any more than a single file.

I'll also try with gmpy and see how it is faster, but I'm afraid that it can hide issues for modules which are using gmpy optionally. I find a key places like `core`, `ntheory` and `polys`, so these modules should also be tested with python ground types separately.

**Comment by gschintgen** [comment]
> I have just updated the densities to be more granular
> But I see you have already opened up an another PR #19626
> 
> I think that containing a chunk of ODE tests adds more than 10 minutes, and a chunk of integrals add about 5 minutes.
> But when I see how ODE tests are organized, I see multiple tests are , so they should be splitted to multiple files because we cannot divide any more than a single file.

That's what I also now noticed while running the script with `num_splits=60`: each part was composed of 8 or 9 test *files*. Those are treated as "atomic". It will remain a huge indivisible chunk either way. That will have to change. At least there are various slow ODE test functions in test_ode.py, so they could be split up by groups of test functions as test_ode1, test_ode2, test_ode3 (while taking care not to group the slow ones again). For reference here are the timings on my admittedly slow dev machine:
```
sympy/solvers/ode/tests/test_systems.py::test_sysode_linear_neq_order1_type2 - Took 10.259 seconds                           
sympy/solvers/ode/tests/test_ode.py::test_unexpanded_Liouville_ODE - Took 11.079 seconds                                     
sympy/solvers/ode/tests/test_single.py::test_nth_order_linear_euler_eq_homogeneous - Took 11.903 seconds                     
sympy/solvers/ode/tests/test_ode.py::test_1st_homogeneous_coeff_ode2 - Took 11.955 seconds                                   
sympy/solvers/ode/tests/test_ode.py::test_nonlinear_2eq_order1 - Took 13.971 seconds                                         
sympy/solvers/ode/tests/test_single.py::test_almost_linear - Took 14.263 seconds                                                                                                                           
sympy/simplify/tests/test_trigsimp.py::test_trigsimp_groebner - Took 14.529 seconds                                            
sympy/solvers/ode/tests/test_single.py::test_nth_order_linear_euler_eq_nonhomogeneous_undetermined_coefficients - Took 14.673 seconds                                                                      
sympy/solvers/ode/tests/test_ode.py::test_1st_homogeneous_coeff_ode_check7 - Took 17.895 seconds                                                                                                           
sympy/solvers/ode/tests/test_single.py::test_Liouville_ODE - Took 19.033 seconds                                               
sympy/solvers/ode/tests/test_ode.py::test_nth_linear_constant_coeff_homogeneous_rootof - Took 19.586 seconds                 
sympy/solvers/ode/tests/test_ode.py::test_issue_9446 - Took 20.690 seconds                                                   
sympy/solvers/ode/tests/test_ode.py::test_issue_11290 - Took 21.720 seconds                                                  
sympy/solvers/ode/tests/test_single.py::test_nth_order_linear_euler_eq_nonhomogeneous_variation_of_parameters - Took 22.157 seconds
sympy/solvers/ode/tests/test_systems.py::test_linear_neq_order1_type2_big_test_cases - Took 22.607 seconds                   
sympy/solvers/ode/tests/test_systems.py::test_linear_new_order1_type2_de_lorentz - Took 22.752 seconds                       
sympy/solvers/ode/tests/test_ode.py::test_linear_2eq_order1_type6_path2_broken_check - Took 22.917 seconds                   
sympy/solvers/ode/tests/test_systems.py::test_sysode_linear_neq_order1_type1 - Took 27.069 seconds                                                                                                         
sympy/solvers/ode/tests/test_ode.py::test_2nd_linear_bessel_equation - Took 27.337 seconds                                              
sympy/solvers/ode/tests/test_ode.py::test_issue_15996 - Took 28.715 seconds                                                          
sympy/solvers/ode/tests/test_ode.py::test_exact_enhancement - Took 28.722 seconds                                            
sympy/solvers/ode/tests/test_ode.py::test_linear_2eq_order1_type6_path1_broken - Took 28.736 seconds                         
sympy/solvers/ode/tests/test_ode.py::test_linear_2eq_order1_type6_path2_broken - Took 29.929 seconds                         
sympy/solvers/ode/tests/test_ode.py::test_solve_ics - Took 34.591 seconds                                                    
sympy/solvers/ode/tests/test_single.py::test_nth_algebraic - Took 45.023 seconds                                             
sympy/solvers/ode/tests/test_ode.py::test_2nd_2F1_hypergeometric - Took 81.381 seconds                                       
sympy/solvers/ode/tests/test_single.py::test_factorable - Took 90.096 seconds                                                
sympy/solvers/ode/tests/test_systems.py::test_linear_3eq_order1_type4_long - Took 90.570 seconds                             
sympy/solvers/ode/tests/test_single.py::test_separable - Took 171.573 seconds                                                
====================== tests finished: 196 passed, 26 skipped, 17 expected to fail, in 1237.18 seconds ======================
```
This list may be more complete than one created on a faster machine.

**Comment by gschintgen** [comment]
> But I see you have already opened up an another PR #19626

That one seems to hang and may have to be canceled :-/
https://travis-ci.org/github/sympy/sympy/builds/701262434

**Comment by oscarbenjamin** [comment]
We probably don't need many of these ODE tests to be run as part of the test suite at all. Many of them should at least be marked as slow or should be refactored somehow with some being disabled. Given how slow some of these tests are it isn't sustainable to add a regression test that runs multiple times on Travis every time anyone makes a commit to any part of the codebase.

Ideally we would choose a minimal set of fast tests that gives reasonable line coverage of the module and everything else should be marked as slow at least if not just skipped by default. I would rather have some way to run a really slow test suite locally than have all these tests run all the time on Travis. That slow test suite can be checked before merging a PR that makes significant changes to the ode module.

**Comment by sylee957** [comment]
Unfortunately, I see the integrals and ODE tests are only marginally faster if gmpy is used.
- python bin/test integrals
  - With gmpy - `387.09s`
  - Without gmpy - `399.92s`
- python bin/test solvers/ode
  - With gmpy - `570.60s`
  - Without gmpy - `589.93s`

**Comment by gschintgen** [comment]
Great, SPLIT 3/4 is down to 41 minutes!

**Comment by smichr** [comment]
This seems a little fluid right now but if this is a partial fix it is better than nothing. I see that #19626 was closed (I assume in favor of this). So I will commit this and it can be changed if needed with other commits.

**Pull request merged**
