### PR TITLE
Quantum IdentityOperator operates from right and IdentityGate speed up

### PR DESCRIPTION
**Pull request by Costor**
#### Brief description of what is fixed or changed
1.) The IdentityOperator has the following unexpected behavior with qapply:
``` 
from sympy.physics.quantum.operator import *
from sympy.physics.quantum.state import *
Id = IdentityOperator()
x = qapply(Id * Ket(1)) # ->  |1>
x = qapply(Bra(1) * Id, dagger = True) #  ->  <1|
x = qapply(Bra(1) * Id) # -> <1|*I   unexpected for Identity
```
`qapply` has the `dagger=True` option that invokes `Dagger(Dagger(b)*Dagger(a))` if the product `a*b` doesn't compute. Most `operators` in quantum have code only for operating on `kets` from the right, and require the dagger=True in qapply option to compute  `bra*op`. However for IdentityOperator this makes no sense: no options should be required to make the identity act as identity.
The change is just to add the method  `_apply_from_right_to()` to the` IdentityOperator` that mimics the already existing `_apply_operator()` for operation from the left.

2.) The implementation of `IdentityGate` (i.e. the quantum gate that implements identity on a qubit, see sympy.physics.quantum.gate.py) just invokes the generic gate application method `gate._apply_operator_Qubit` which creates a huge overhead. 
The change is to override the generic method by a short cut that just returns the input.
#### Release Notes

* physics.quantum
  * IdentityOperator applied more stringently in qapply and speed up of IdentityGate

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Looks good to me. The mypy failure is unrelated.

**Comment by oscarbenjamin** [comment]
Actually if the behaviour is changed there should be tests for the changed behaviour.

**Comment by Costor** [comment]
I've added a test case for qapply(Bra*IdentityOperator)==Bra  and a test case for the IdentityGate.

I'assume I've nothing to do for the mypy test failure?

**Comment by oscarbenjamin** [comment]
Looks good to me.

> I'assume I've nothing to do for the mypy test failure?

That's correct. We just need a fix for #24231

**Pull request merged**
