### PR TITLE
Added evalf in Vector and Dyadic

### LINKED ISSUE #18064: Add .evalf() method to sympy.physics.vector.Vector and Dyadic
These two classes are missing many of the core SymPy methods because they do not inherit from the core SymPy classes. It would be nice to add them, starting with `.evalf()`.

### PR DESCRIPTION
**Pull request by Smit-create**
Added evalf in Vector and Dyadic classes.
#### References to other Issues or PRs

Fixes #18064
Closes https://github.com/sympy/sympy/pull/18113

#### Brief description of what is fixed or changed
Now the vector and dyadic classes inherit from EvalfMixin with some necessary changes.

#### Release Notes

* physics.vector
   * Added inheritance in Vector
   * Added inheritance in Dyadic

### CODE REVIEW

**Comment by moorepants** [comment]
Thanks for the contribution. You are going to need some unit tests to show that the new functionality works.

**Comment by Smit-create** [comment]
> Thanks for the contribution. You are going to need some unit tests to show that the new functionality works.

Can you please suggest what type of test I need to add ?

**Comment by moorepants** [comment]
You need to create vectors and dyadics and then use the evalf() method on them.

**Comment by moorepants** [comment]
FYI this is also being worked on in #18113.

**Comment by Smit-create** [comment]
> FYI this is also being worked on in #18113.



> You need to create vectors and dyadics and then use the evalf() method on them.

Yes, I got to add that. 
Actually I found that making it inherit directly from EvalfMixin would not make it work as it may require other methods for it which may give a complex expansion . So what I am thinking is to add evalf method in vector class itself

**Comment by Smit-create** [comment]
> FYI this is also being worked on in #18113.

Okay, then I would let it proceed there.

**Comment by czgdp1807** [comment]
Closing in favour of https://github.com/sympy/sympy/pull/18113/
Thanks for the contributions.

**Pull request closed without merging**
