### PR TITLE
Remove the notebooks from the examples directory.

### PR DESCRIPTION
**Pull request by oscarbenjamin**
These were already copied to the sympy-notebooks repo:

https://github.com/sympy/sympy-notebooks/pull/4

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
I guess this removes all the examples. They're definitely outdated, but I do think people look at them, especially since they are included with the source code. We should at least make sure people are pointed to somewhere where they can find examples.

**Comment by asmeurer** [comment]
Although to be fair, the examples aren't great. Many of them date back to the earliest versions of SymPy and I don't think they've changed at all except for whatever was required to keep them running without errors. And notebooks really are the better way to do this nowadays (the example scripts all predate *notebooks*), though notebooks can be large so keeping them in a separate repo is the best.

Perhaps in the future we could have a season of docs project to make high quality example notebooks showing how to use SymPy, and maybe somehow integrate them into the docs with juypterlite.

**Comment by oscarbenjamin** [comment]
Everything removed here is already copied to the notebooks repo:
https://github.com/sympy/sympy-notebooks

The examples are dated and don't really show things that are that useful. The notebooks I looked at were broken.

It would be great for someone to improve them or make better examples or maybe migrate some to be part of the docs or something. That is still possible with them being in the other repo though. We can delete them here without losing anything.

**Comment by oscarbenjamin** [comment]
Thanks, Chris.

I think that this is a good move. Someone should step up to improve these examples/notebooks but in the meantime they should not be a maintenance burden in the main sympy repo.

**Pull request merged**
