### PR TITLE
Added code and tests to make is_scalar for a matrix as False

### LINKED ISSUE #16510: is_scalar is true for matrix symbols and expressions?
```python
>>> from sympy import *
>>> A = MatrixSymbol('A', 3, 3)
>>> A.is_scalar
True
```

I see `is_scalar` was introduced in #15049

Edit
See current status at https://github.com/sympy/sympy/issues/16510#issuecomment-592611393

### PR DESCRIPTION
**Pull request by arooshiverma**
#### References to other Issues or PRs

Fixes #16510

#### Brief description of what is fixed or changed
Added is_scalar for matrices to be False always
Added test

#### Release Notes

* matrices
  * Set is_scalar = False for matrices

### CODE REVIEW

**Comment by Sc0rpi0n101** [comment]
That build fail is odd. But it's probably an internal fault, not necessarily your patch.
Also, I'd suggest you to atleast add a test for a 1*1 matrix

**Comment by Sc0rpi0n101** [comment]
Wow, how is codecov -62% ?

**Comment by arooshiverma** [comment]
I don't know. Let me check.

**Comment by Upabjojr** [comment]
What about matrices of shape `(1, 1)`?

**Comment by asmeurer** [comment]
This looks good to me. I don't think that 1x1 matrices should be considered scalars (see the discussion at https://github.com/sympy/sympy/issues/16504). 

As noted in the OP issue, use of is_scalar is to indicate for which expressions `x.diff(x)` should give `1`. Is it correct for dA/dA to equal the scalar 1 if A is a 1x1 matrix?

**Comment by Sc0rpi0n101** [comment]
https://en.wikipedia.org/wiki/Matrix_calculus#Vector-by-vector_identities defines dx/dx (x being a vector) as I,  so, I guess dA/dA will be a 1x1 Identity matrix, not scalar.
But that depends if you consider 1x1 a vector.

This patch does not consider a 1x1 a scalar as seen from the test:
```python
B = MatrixSymbol('B', 1, 1)
assert B.is_scalar == False
```

Also, from what I know, a scalar can be multiplied to any matrix, but a 1x1 matrix has to follow the rules of matrix multiplication and can only be multiplied by a 1xn matrix. So, 1x1 matrix should not be considered a scalar.

Wolfram also thinks the same as apparent from [Matrix](https://www.wolframalpha.com/input/?i=%7B%7B4,5,6%7D,%7B6,5,4%7D,%7B4,6,5%7D%7D*%7B%7B1%7D%7D) and [Scalar](https://www.wolframalpha.com/input/?i=%7B%7B4,5,6%7D,%7B6,5,4%7D,%7B4,6,5%7D%7D*5)

**Comment by arooshiverma** [comment]
So does it need any changes? Or is it to be merged?

**Comment by Sc0rpi0n101** [comment]
Looks good to me if the 1x1 matrix issue is resolved.

@asmeurer  @sylee957  Thoughts on having a 1x1 matrix(and all other matrices for this matter) as not scalar?

**Comment by arooshiverma** [comment]
@asmeurer, @sylee957 ? Should 1x1 matrix be considered as not scalar?

**Comment by oscarbenjamin** [comment]
I don't think a 1x1 matrix should be considered a scalar.

It would be good to add a couple of tests for things that are scalar. Otherwise +1

**Comment by czgdp1807** [comment]
@oscarbenjamin Can we merge this? It looks like a good fix. Reviews are also in favour. We can re-start the build to check if it's fine with the current master.

**Comment by oscarbenjamin** [comment]
It could have a test for `Vector.is_scalar` as well as tests for things that are scalar.

**Comment by czgdp1807** [comment]
@arooshiverma Would you still like to continue this PR? Please do not close this PR.

**Comment by smichr** [comment]
Issue was closed via #23033

**Pull request closed without merging**
