### PR TITLE
New vector

### PR DESCRIPTION
**Pull request by BMaxV**
This is a new module that I would like to someday replace the sympy.vector module, in some form or way.

**Why is this change necessary?**

It's not necessary, what you have works.

**If it's not necessary, why should sympy.vector be touched at all?**

Because frankly, things are a bit messy: You have sympy.matrices, there is a sympy.physics.vector module, a sympy.liealgebras (wich I believe stands for linear algebras?), sympy.tensor and finally sympy.vector module. Most of which implement some common functions, like the dot and cross products and all of which aren't very pythonic in the way they use classes. In short, to clean things up and to provide a nice, clean standard that can be use by everyone.

**Why is this implementation even good or better than the ones we have?**

Unlike the others, it only depends on sympy and I only use very basic functions that are already defined for sympy expressions, like basic math operations and substitution. That would enable me or someone else to maybe prune some other parts of sympy without impacting this module.

**What can this module do then?**

I have looked at what the old vector class did and tried to reach feature parity. Meaning, these are vectors you can treat like you would expect and they should just "work". I have also included the differential field and vector field functions, gradient, divergence and curl. 

One thing I have not added are reference frames, because in my opinion they're not required for vector operations. Since they seem to be used elsewhere (sympy.physics), I would write a replacement to accomodate that use.

Another thing I have added, but that I'm not sure about are dyadics, since it wasn't really clear on wikipedia if that reference to the sum of the parts or the matrix form. I have included both, but maybe renaming is required.

Lastly these vectors only support three dimensios. If you need them to be larger, I'll have to rewrite a few bits and pieces.

If this module doesn't support something that's used somewhere else in sympy, just tell me and I'll add that.

I would of course also write the new documentation if this gets accepted and you point me the right way.

### CODE REVIEW

**Comment by Upabjojr** [comment]
Hi, thanks for sharing the code.

I had a quick view, it looks like you are trying to create a version of `sympy.vector` without coordinate system, am I right?

I know we have many modules (vectors, matrices, tensors, differential geometry, N-dim arrays, etc...). We are aware that these modules don't really cooperate with one another, and that's an open issue.

I would also take into consideration adding a _Vector_ class directly in `sympy.matrices` and making the operators (_gradient_, _divergence_, _curl_) independent of the module they operate on.

**Comment by BMaxV** [comment]
> I would also take into consideration adding a Vector class directly in `sympy.matrices` and making the operators (gradient, divergence, curl) independent of the module they operate on.

Yes, that would be ideal. We will see where the code ends up, I don't really have a preference. This was just to get started and to give an idea of how I would rewrite things.

**Comment by Upabjojr** [comment]
Also take into account that we have _sympy.tensor.array_ for arrays of generic order (vectors, matrices, higher order).

> This was just to get started and to give an idea of how I would rewrite things.

I believe it's much easier to just extend the current `gradient`, `divergence`, and `curl` that are in `sympy.vector` to support generic arrays.

**Comment by BMaxV** [comment]
A little bit more detailed comment about the latest step.

Since the suggestion was to integrate the field functions with `tensor/array`, I took a look at array. You don't need four different classes for a datatype with a few varying properties. So I did the natural thing, combined what was there and introduced the attributes `immutable` and `sparse` to handle the previous behavior in old getter and setter methods.

So all the old classes are still there, they just define those immutable and sparse bools and give those and everything else to a general `NDimArray` class. Meaning when I'm done, this entire change will break nothing and change nothing about the interface, it'll just have simplified things.

Unfortunately simply copying the code wasn't possible in many cases. You can look at the tests that I copied and changed to test the new module. The tests at the end that are commented out broke in the process. Mostly some functions relating to conversions.

With most of them, I'm sure I can rewrite the functions that break them currently.

What I'm unsure about are the arrayoperations like tensorproduct. I think I can fix those too, to reproduce the behavior shown in the examples, but it would be nice to have a good reference to make sure they do what you want them to do.

Finally there are some things I simply didn't understand and that's the functions that are implemented as classes and that inherit from "Function". The behavior they are meant to produce are covered by `Array.function()` but `function(Array)` (an example would be `transpose`) doesn't work and I don't know how it broke because that depends on how sympy handles those usually.

A fun fact at the end: there is a `MutableNDimArray` class that inherits from `NDimArray`, which returns an `ImmutableDenseNDimArray` object.

**Pull request closed without merging**
