### PR TITLE
tm_sympy - Run script with /usr/bin/env python

### PR DESCRIPTION
**Pull request by mardukbp**
#### Brief description of what is fixed or changed

Execute the script using the Python interpreter currently in $PATH. For example, one installed by Anaconda or the Nix package manager.

#### Release Notes

* other
  * The script tm_sympy is now executed by the Python interpreter in $PATH

### CODE REVIEW

**Comment by sidhantnagpal** [comment]
+1. The prior behaviour will cause this script to run outside the virtual environment.

**Comment by asmeurer** [comment]
+1 but please add a release notes entry.

**Comment by mardukbp** [comment]
Release notes added

**Comment by sidhantnagpal** [comment]
Thanks, this looks ready.

**Pull request merged**
