### PR TITLE
[DOC] Improve math mark-up in three doc files

### LINKED ISSUE #26907: [DOC] Be it for HTML or LaTeX (at least, currently) `\mathbf{\omega}` (and all lowercase Greek) mark-up does not work
Here is a screenshot of current HTML docs:

Capture d’écran 2024-08-03 à 19 31 34

We see that alpha and omega are not bold. Well a doubt can arise but I assure you they are not bold.

Further examination of the MathJax reveals that the mark-up is with U+1D714 MATHEMATICAL ITALIC SMALL OMEGA (and no bold-variant seems added, and if one uses the pop-up to export to MathML there is no bold for that character):

Capture d’écran 2024-08-03 à 19 36 48

The source mark-up is

```
.. math::
  ^{\mathbf{N}}\mathbf{v}^P &= ^\mathbf{B}\mathbf{v}^P +
  ^\mathbf{N}\mathbf{v}^S + ^\mathbf{N}\mathbf{\omega}^\mathbf{B} \times
  \mathbf{r}^{SP}\\

  ^{\mathbf{N}}\mathbf{a}^P &= ^\mathbf{B}\mathbf{a}^S +
  ^\mathbf{N}\mathbf{a}^O + ^\mathbf{N}\mathbf{\alpha}^\mathbf{B}
  \times \mathbf{r}^{SP} + ^\mathbf{N}\mathbf{\omega}^\mathbf{B} \times
  (^\mathbf{N}\mathbf{\omega}^\mathbf{B} \times \mathbf{r}^{SP}) +
  2 ^\mathbf{N}\mathbf{\omega}^\mathbf{B} \times ^\mathbf{B} \mathbf{v}^P \\
```

i.e. using `\mathbf{\omega}` and `\mathbf{\alpha}`.

Math mode in LaTeX has always been very poorly documented (imho), and there is wide-spread misguided belief that `\mathbf` can work with Greek.  This is explained in part because it does work with **uppercase** Greek, but only in the default TeX math font configuration.  Now it seems that MathJax, like default LaTeX, does not understand `\mathbf{\omega}`.  But MathJax, like default LaTeX does understand `\mathbf{\Gamma}`.  Here is a screenshot of an HTML rendering (which uses MathJax) of ``.. math:: \mathbf{\alpha\Gamma}` in a minimal Sphinx document:

Capture d’écran 2024-08-03 à 19 48 32

The Gamma is bold, the alpha is not bold.

In fact for the last 30 years or so, 99% of people seem to have understood that `\mathbf` will bolden its argument, but this is not the case. `\mathbf` in LaTeX (MathJax is not LateX Math at all but seems to follow it very closely) means to use a certain font.  Furthermore only very few TeX math commands will react to `\mathbf`.  In particular lowercase Greek letters ignore it completely.  Here is a screenshot of 1.13.1 PDF docs:

Capture d’écran 2024-08-03 à 19 27 16

We see that in PDF as in HTML-MathJax the lowercase Greek is not boldened.  No warnings are emitted during PDF build, because core TeX sees no error: `\mathbf{...}` is a command where one can put many things inside, some will react (Latin letters and **uppercase** Greek) others will not (in particular all non-letter symbols).

When a document is produced with xelatex or lualatex, chances are it uses `fontspec` which by default will change the target font of `\mathbf` from an "Old TeX font" of original Knuth TeX with only 128 glyphs to the document body text font in bold.  As anyhow `\omega` does not react, again no error arises.  When one adds usage of `unicode-math` then the `\omega` is rendered as a Unicode letter so here U+1D714, and it is configured by `unicode-math` to be of "type `\mathalpha`" which means that now it *will react* to `\mathbf`.  But then maybe the glyph is not available in the Bold variant of the body text font, and so a Missing character warning is emitted which one sees in LaTeX log.  This is not yet an error, so one has to pay attention, but with recent Latexmk used by Sphinx, this is summarized at end of run.  This is how I ended up finding the above occurrences in the SymPy documentation.

Options:
- `\bm` in LaTeX if one uses eponymous package (but appears to be incompatible with `unicode-math`)  and not supported by MathJax (maybe I am not well informed and some additional setting enacts it; I tested adding it to SymPy docs and MathJax displays a red string `\bm`),
- `\symbf` if one uses `unicode-math`, but <strike>I encountered at least one case during prior investigation, now lost, where a `\mathbf` with a more complex argument using super- or subscript caused a breakage if transformed into `\symbf`,</strike> (edit) unicode-math option `mathbf=sym` then causes build crash when `\mathbf{\hat{p_3}}` is encountered  (such mark-up is frequent in kinematics.rst),
- `\boldsymbol` works both in LaTeX (+amsmath, which Sphinx uses automatically) and MathJax (at least this is what I see on a small project compiled with current Sphinx and thus using MathJax3, there is no need for additional configuration it seems).  And the good thing is that despite its name `\boldsymbol` accepts a multi-character expression; it will bolden everything inside its argument, **if** the math font set-up for as "bold math version" as the bold glyphs; in MathJax it seems to work well.

It seems the fix here is to use `\boldsymbol` in kinematics.rst.

Here is in HTML+MathJax with `\boldsymbol` used in place of `\mathbf` for `\alpha` and `\omega`:

Capture d’écran 2024-08-03 à 20 52 19

Now we see how bold alpha and omega look like.  We also see many instances of faulty mark-up  such as ``\times ^\mathbf{B} \mathbf{v}^P`` which causes the bold B to be a superscripting the `\times` multiplication symbol.  This should be (at minimal) ``\times {}^\mathbf{B} \mathbf{v}^P`` which renders as:
Capture d’écran 2024-08-03 à 20 59 42

Replacing globally `s/mathbf/boldsymbol/` is preferably to be avoided from LaTeX point of view because `\boldsymbol` is a bit costly (it tells TeX to prepare all four versions for display size, normal size, script size and script script size at each usage).

Some testing has to be done to see how usage of `\boldsymbol` will interact with `unicode-math` for PDF output: there are good arguments to use `unicode-math` as it will allow to set-up the TeXGyre DejaVu Math font which fits much better with the DejaVu Serif body fonts.

### PR DESCRIPTION
**Pull request by jfbu**
#### References to other Issues or PRs

Fixes #26907

#### Brief description of what is fixed or changed

See discussion at #26907 for rationale of changes.

#### Other comments

This regards HTML-MathJax output (for example to really obtain a bold omega) or a bold alpha), and also fixes PDF problems.  These problems may turn into Missing glyphs if usage of `unicode-math` is activated (which this PR does not because I discovered bad impact on placement of math accents which may not have easy solution).

Regarding the replacements `s/^/{}^` they were done by some search/replace and those at start of a math expression are probably not needed, besides one could perhaps negative math skips.

I.e. use this refined mark-up:
```rest
2\, {}^\mathbf{N}\!\boldsymbol{\omega}^\mathbf{B} \times {}^\mathbf{B}\mskip-1mu\mathbf{v}^P 
```
in replacement of the original
```rest
2 ^\mathbf{N}\boldsymbol{\omega}^\mathbf{B} \times ^\mathbf{B} \mathbf{v}^P
```

(this PR does not have the `\,`, `\!`, `\mskip-1mu`).

The latter gives  the current HTML rendering (apart from bold omega)
Capture d’écran 2024-08-03 à 23 58 30

The former would give
Capture d’écran 2024-08-03 à 23 55 31

This PR gives

Capture d’écran 2024-08-04 à 00 03 40

(I discover that MathJax renders rather faithfully what one would expect from pure TeX)

I am bit worried about the bold omega.  Did the `\mathbf` try to make an *upright*  omega? I am assuming not.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by moorepants** [comment]
> I am bit worried about the bold omega. Did the \mathbf try to make an upright omega? I am assuming not.

Upright omega isn't needed.

**Comment by moorepants** [comment]
This looks good to me. Did you mean to include the changes to the files with operatorname and imath changes?

**Comment by jfbu** [comment]
Yes, I pushed separate commits for them.  These additional commits solve similar problems as the `\mathbf{\omega}` ones.

**Comment by jfbu** [comment]
There are some `\mathbf{\Lambda_c}` in lagrange.rst (causing missing character currently due to fontspec modifying the default math set-up) which arguably would also benefit from `\boldsymbol` for clarity; those are fixed in #26833 via passing `no-math` option to fontspec.  But unicode-math reverts that option if one attempts to use it. I am postponing such additional changes to a unicode-math PR if I ever propose one, I saw problems with math accents, it is not clear at this stage I can reach a satisfactory situation with unicode-math.

And mark-up such as `\mathbf{\hat{p_3}}` combined with `mathbf=sym` unicode-math option cause a build crash so letting `\mathbf` (which MathJax understands) en-masse behave in LaTeX as `\symbf` (which MathJax does not understand but will not see as the mark-up will still be `\mathbf`) in unicode-math context forces me to investigate all other potential breakages.  As one knows, TeX is very inconvenient at error recovery (from user point of view) and one has to fix errors one by one and when the LaTeX build takes minutes this is somewhat frightening prospect.  Maybe though this is the sole type of breakage, will see.

**Comment by moorepants** [comment]
LGTM

**Pull request merged**
