### PR TITLE
Updated gitignore

### PR DESCRIPTION
**Pull request by czgdp1807**
#### Brief description of what is fixed or changed
I have added an update for `pyc` file.

#### Other comments
While working, I observed that files of `sympy/integrals/__pycache__/meijerint.cpython-36.pyc.140589556619184` are also being added to git. I have updated the gitignore for the same. I don't know the right way to ignore such files but still made an attempt.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscargus** [comment]
Should make sense and be OK to merge.

**Comment by Upabjojr** [comment]
Just wait a few days in case anyone has an objection, given that it's modifying a basic file.

I'd say, let's merge on Wednesday.

**Comment by asmeurer** [comment]
I don't know what those files are, but really `__pycache__` should be in .gitignore

**Comment by oscarbenjamin** [comment]
Are those files created by something like vscode or are they new to Python 3.8?

**Comment by czgdp1807** [comment]
May be vscode bect i dont have python 3.8

**Comment by oscarbenjamin** [comment]
I think it would be better to add `__pycache__` rather that `*.pyc.*`

**Comment by oscarbenjamin** [comment]
Looks good, thanks.

**Pull request merged**
