### PR TITLE
[WIP] Implemented fourier sine/cosine series expansion

### LINKED ISSUE #9077: Fourier Series Implementation
As of now, there is no representation of Fourier Series in Sympy. Fourier series has various applications, so representing Fourier Series may help Sympy.

### PR DESCRIPTION
**Pull request by leosartaj**
- Added module `fourier` in `sympy.series`
- Added `SeqFormula` class, that knows how to generate coefficients based on
  a formula
- Added `FourierSeries` Class,
  This Class represents a fourier series expansion.
  Contains methods for getting the general representation of series
  and for getting the first n terms.
- Added `fourier_series` function.
  It is a wrapper that returns the first n terms of a series or an
  infinite generator of terms

I have placed everything in a single file. I think it can be structured better.

May close #9077

### CODE REVIEW

**Comment by leosartaj** [comment]
please review @smichr @asmeurer

**Comment by moorepants** [comment]
Any reason this was closed?

**Comment by leosartaj** [comment]
I will be working this summer, on improving the series infrastructure. Once I get it in. It will be better to implement it using the new infrastructure. This was made when I was working on my proposal. Not very well implemented. [Details](https://github.com/sympy/sympy/wiki/GSoC-2015-Application-Sartaj-Singh:-Improving-the-series-package-and-limits-in-SymPy).

**Comment by moorepants** [comment]
ok

**Pull request closed without merging**
