### PR TITLE
Corrected paramateric_region_list and the tests using the method

### LINKED ISSUE #20748: sympy.vector  Implicit_Region result wrong for perimeter of unit circle  version 1.7.1
Using vector_integrate in the examples in the documentation:

from sympy.vector import ImplicitRegion
c2 = ImplicitRegion((x, y), (x - 2)**2 + (y - 1)**2 - 9)
vector_integrate(1, c2)
12*pi

should this not be 6*pi since the radius of the circle is 3?

It seems like you always get the correct answer multiplied by a factor of 2 for any given radius.

### PR DESCRIPTION
**Pull request by ghost**
#### References to other Issues or PRs

Fixes #20748 

#### Brief description of what is fixed or changed
The paramteric_region_method  was earlier substituting `tan (t)` rather that `tan(t/2)`  , when parametrizing ImplicitRegion object to ParametricRegion objects. This resulted in the value of final computed answer becoming twice of what it should have been, as can be seen from the OP.

#### Other comments
The earlier tests had wrong answers, this pr fixes them also.

#### Release Notes

- vector 
  - Fixed a bug with integral over ImplicitRegion objects

### CODE REVIEW

**Review by friyaz — APPROVED** [review]

**Comment by friyaz** [comment]
Thanks for making this PR @almighty123789. This looks good to me. Just improve the release notes.

**Comment by almighty123789** [comment]
@friyaz thanks for commenting and reviwing the PR.  Can you tell me what more should I add to the release  notes ? Thanks.

**Comment by friyaz** [comment]
How about "Fixed a bug with integral over `ImplicitRegion` objects."

**Comment by faisal-deepsource** [comment]
Thanks, I do not have merging rights yet. @oscarbenjamin Can you merge this please it looks good to you?

**Comment by friyaz** [comment]
Thanks, I do not have merging rights yet. @oscarbenjamin Can you merge this please it looks good to you?

**Comment by asmeurer** [comment]
@friyaz I have given you push access. Please read https://github.com/sympy/sympy/wiki/Pushing-patches.

**Comment by friyaz** [comment]
Thanks, @asmeurer for this!

**Pull request merged**
