### PR TITLE
Removed possible failures from Codecov and changed precision

### LINKED ISSUE #16232: Make codecov not give a failing status
It's kind of annoying that codecov can make the status for a PR an :x:. I use the status as a basic check whether to look at a PR, as a failing status automatically means the author needs to do something to fix it.  So I think we should configure it to never give a failing status.

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Closes #16232 

#### Brief description of what is fixed or changed
This should remove the failing statuses by allowing a coverage range of 0 to 100%. 

I also changed the precision to 3 digits instead of 2 as the changes will be small anyway...

#### Other comments
Not obvious how to test it. I guess this will give some idea and then one can merge and see...

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
The validation described at https://docs.codecov.io/docs/codecov-yaml#section-validate-your-repository-yaml fails for me.

```
$curl --data-binary @codecov.yml https://codecov.io/validate
Invalid value {'threshold': None, 'precision': 3, 'target': 0} (dict): additional properties: ['threshold', 'target'] (at coverage)
```

**Comment by oscargus** [comment]
Good link! Yes, considering that the comment showed up it was apparently completely wrong somehow.

I just pushed a modified version after seeing how others solved it. Let us see. It passes the validation if nothing else... (I think that the problem either was indentation or that 0 didn't count as 0% despite the documentation indicating it.)

**Comment by oscargus** [comment]
It seems like this "works". In the sense that the coverage can go down without a failure, see #16246 

The not so good thing is that it doesn't report the difference. I am tempted to use the comment function for that...

**Comment by asmeurer** [comment]
`comment: off` is still broken I see. I still haven't received any response from codecov support. I'm tempted to block the codecov bot and see if that fixes it.

**Comment by oscargus** [comment]
I turned comments back on in #16246 as the checks does not say if the coverage increases or decreases (I think that is still important information when judging a PR: is the new code sufficiently covered). Just pushed a version where only the coverage diff is included.

(The reason that there is a comment here is the completely failed file from earlier.)

**Comment by oscargus** [comment]
I seem to have messed up with my recent rebase... Once this is in a shape that is acceptable, I'll just create a new PR with the changes in codecov.yml

**Comment by oscargus** [comment]
What do you think of the current comment style? Ideally the numbers should be in the checks, but it is not obvious how to obtain that without introducing failures...

**Comment by oscargus** [comment]
Thanks @smichr

**Comment by asmeurer** [comment]
Is it possible to make codecov not give two statuses, since the relevant info isn't there anyway?

**Comment by asmeurer** [comment]
I'm still not a huge fan of the comment, but if everyone else likes it then we should keep it. I like that it edits the comment rather than posting a new one. I know there was some iteration of it that didn't do that (I could also be thinking of coveralls).

**Comment by asmeurer** [comment]
Did the commit history get messed up here? I see a lot of commits, but the diff doesn't show any changes? If the commits in the history are supposed to be here, it got messed up somehow. If they aren't, you should rebase them out.

**Comment by oscargus** [comment]
Yes, it is possible to reduce it to one check.

I rebased to reduce the amount of commits and force pushed but somehow it got out of sync. @smichr then merged with master and everything looks fine except the commit log.

I can start a new PR and copy-and-paste. I doubt I will manage the rebase approach... And remove one check.

**Comment by asmeurer** [comment]
The merge cleaned up the diff, but the duplicate commits are still in the history. 

You have to be careful when you rebase. If you rebase too far back, you will rewrite commits that are already in master. Something like `git rebase HEAD~20` is usually wrong, as it will redo all the last 20 commits, even if some of them are in `master`. 

I usually recommend avoiding rebasing, unless you know what you are doing (even then I avoid it), as it can lead to issues like this, and the only way to fix it is to do another history rewrite.

A new PR is fine if you can't figure out the git stuff. You can also delete your branch locally and redo it there with the same name, then force push it. That will update this PR (git branches are compared by name only, so if you delete a branch and recreate a new one with the same name it will be the same as if you fixed it manually).

**Comment by oscargus** [comment]
I thought I had a decent idea about rebasing, but apparently not... I moved one of the first commits in the branch to after the merged commits as I wanted to amend the rest of the commits from here in that. But somehow I must have missed something...

I'll restart this I think so that there is no need to open a new PR. Hopefully with only one Codecov check.

**Comment by oscargus** [comment]
Now, I _think_ that it is working as expected...

**Comment by smichr** [comment]
> I usually recommend avoiding rebasing, unless you know what you are doing (even then I avoid it), as it can lead to issues like this, and the only way to fix it is to do another history rewrite.

When I get in this state, I make a diff relative to master; delete the branch and create a new one from master by applying the diff:
```
git checkout foo
git merge master
git diff master > work
git checkout master
git branch -D foo
git checkout -b foo
git apply work
git commit 'one commit' # or git add -p to add pieces a little at a time
```

I don't like my commits getting separated from each other in the history so that's why I tend to *like* rebase instead of merge.

**Pull request merged**
