### PR TITLE
Docs: change the wording of definition of O(x)

### PR DESCRIPTION
**Pull request by certik**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by certik** [comment]
(These changes were proposed to me in private correspondence.)

**Comment by asmeurer** [comment]
CC @jksuom I know that the definition of limit/big-O has been discussed in the past. Do you recall if the current definition is the one we settled on, or if this one is better?

**Comment by oscarbenjamin** [comment]
The authors check failed because "Eric Demer <demer@mailbox.org>" is not in the .mailmap file.

**Comment by jksuom** [comment]
The order terms are *local*. In particular `f(x) = O(g(x))` as `x -> 0` means  that there exists a neighborhood of 0, given by `|x| < delta` for some `delta > 0`, such that `|f(x)| < M|g(x)|` for some `M > 0` in that neighborhood. Hence "for any delta > 0" should be replaced by "there exists a delta > 0" in the definition. (There are two occurrences.)

This can also be expressed by saying that $\limsup_{x \to 0} |f(x)/g(x)| < \infty$, which is an abbreviation of $\lim_{\delta \to 0+}\sup_{|x| < \delta} |f(x)/g(x)| < \infty$.

Similarly `f(x) = O(g(x))` as `x -> a` or `x -> oo` are defined by neighborhoods of the type `|x - a| < delta` and `x > 1/delta` (where `1/delta` may be big).

**Comment by certik** [comment]
@jksuom so the change is roughly correct, but should be polished. Do you want to submit a PR or push into this PR to get this done?

**Comment by asmeurer** [comment]
My question is, would this definition change affect the implementation in any way? Or does the current implementation already match the proposed new definition?

**Comment by asmeurer** [comment]
Some of the previous discussions around this were at https://github.com/sympy/sympy/pull/2356 and https://github.com/sympy/sympy/pull/2427 (just searching the issue tracker for "limsup").

**Comment by jksuom** [comment]
> Do you want to submit a PR or push into this PR to get this done?

I don't think that would be needed. This PR looks good to me, only the text on these lines https://github.com/sympy/sympy/blob/ebde7f21887fdadb49df2d29f47f40d80b43625c/sympy/series/order.py#L23-L24 should be changed to ',,, if and only if there exists a `\delta > 0` and an `M > 0` such that ...'.

**Comment by oscarbenjamin** [comment]
@jksuom does this look good to you?

**Comment by jksuom** [comment]
This look good. Sorry I didn't notice this before.

**Pull request merged**
