### PR TITLE
remove fastcache and backported lru_cache

### LINKED ISSUE #18070: fastcache vs functools.lru_cache performance
As of Python 3.5, `functools.lru_cache` was rewritten in C.  It's able to use an internal dictionary API and is therefore more performant than `fastcache`.  I'm not sure if this will actually make a difference but its probably worth investigating

### PR DESCRIPTION
**Pull request by pbrady**
Drop support for the backported lru_cache as well as fastcache. 

The backported lru_cache is only necessary for versions < 3.3 and fastcache is no longer necessary since the standard functools.lru_cache is now written in C for performance.  Benchmarks show that is faster than fastcache.

Fixes #18070

* core
  * Remove optional dependency on fastcache

### CODE REVIEW

**Comment by pbrady** [comment]
looks like there are some explicit mentions of fastcache in the testing suite.  I'll remove those in a bit.

**Comment by pbrady** [comment]
travis failed with a network error and I don't know how to restart it.

**Comment by oscarbenjamin** [comment]
Restarted

**Comment by pbrady** [comment]
Thanks!

**Comment by asmeurer** [comment]
Nice. We should also make sure the conda-forge recipe is updated.

**Comment by smichr** [comment]
conda forge can be done independently from this so I will commit this as is. I had to restart a travis test (I did quality run) to get it to trigger the update here.

**Comment by pbrady** [comment]
Thanks for merging!

**Pull request merged**
