### PR TITLE
Rename SI.py to si.py

### PR DESCRIPTION
**Pull request by asmeurer**
Uppercase filenames cause some issues on case insensitive filesystems (e.g., the doctests fail for SI.py on macOS).

CC @schymans @Upabjojr

### CODE REVIEW

**Comment by Upabjojr** [comment]
The unit systems modules had been created by the original author of the new units module, I left them there when refactoring. I don't really think that this code is really useful now.

**Comment by asmeurer** [comment]
This file appears to be new since 1.1.1 (otherwise I would be more careful about renaming it). It was added in https://github.com/sympy/sympy/pull/12897

Anyway, I don't care what happens to it as long as the filenames are lowercase.

**Comment by Upabjojr** [comment]
Oh, I see. +1 for the renaming.

**Comment by schymans** [comment]
Thanks for picking this up, I wasn't aware that file name capitalization could cause problems on a mac. Will keep it in mind. I added SI.py a couple of months ago and use it a lot, but it is not a problem to rename references to it.

**Comment by Upabjojr** [comment]
@schymans in which way are you using the class `DimensionSystem` and `UnitSystem`? When I refactored the code I was a bit skeptical about that class, but I decided to keep it in order not to break compatibility with previous versions of SymPy.

It would be nice to add support to dimensional contractions, and reverting dimensional contractions. For example when you set the speed of light to be one, you are contracting spacial and temporal dimensions, thus identifying a unique dimension for space and time.

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/issues/13153

**Comment by schymans** [comment]
@Upabjojr interesting point about dimensional contractions. I haven't been doing anything fancy with the UnitSystem, just converting expressions involving quantities to SI base units (kg, m, s, mol) in this project: [https://github.com/environmentalscience/essm](https://github.com/environmentalscience/essm). I came from SageMath and I'm still exploring the intended use of various Sympy components. I found the documentation of UnitSystem a bit sparse, so I just followed the pattern in mks and mksa.

**Comment by schymans** [comment]
@Upabjojr interesting point about dimensional contractions. I haven't been doing anything fancy with the UnitSystem, just converting expressions involving quantities to SI base units (kg, m, s, mol) in this project: [https://github.com/environmentalscience/essm](https://github.com/environmentalscience/essm). I came from SageMath and I'm still exploring the intended use of various Sympy components. I found the documentation of UnitSystem a bit sparse, so I just followed the pattern in mks and mksa.

**Comment by Upabjojr** [comment]
> I found the documentation of UnitSystem a bit sparse, so I just followed the pattern in mks and mksa.

The documentation could need reviewing, it was written by the original author of the new units module, I made some modifications when I unified those modules, some parts may be not up-to-date.

Also, I decreased the importance of `UnitSystem` and `DimensionSystem` after the refactoring. Most of the module is now independent of those classes.

**Pull request merged**
