### PR TITLE
CI: Bump Python versions in Github Actions

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
@eagleoflqj the pyodide jobs have failed here even though I have not made any significant changes to them. I have wasted time on these jobs when trying to make CI changes before and @brocksam wasted a bunch of time on them as well when switching to pytest. I am not personally going to spend any time making these work because I have already wasted time on them before and I have never seen anything useful come from having these jobs in CI.

Do you have any suggestion that can make these more reliable?

Otherwise I am just going to remove the pyodide jobs from CI.

Or maybe I will just remove them now and we can consider adding them back later if they can be made more reliable. Note that just making the jobs work now is not good enough. They need to be reliable enough that changes can be made in CI without having these jobs randomly break again or otherwise anyone trying to make other CI improvements is going to waste time wrestling with irrelevant pyodide problems.

**Comment by eagleoflqj** [comment]
Feel free to remove them.

**Comment by oscarbenjamin** [comment]
Thanks @eagleoflqj. I've removed the pyodide CI job.

I do see the value of testing under pyodide but the problem is that somehow running pyodide in CI is flakey. The tests pass but then pyodide does not exit and the job times out. If there is a way to fix that then we can add the CI job back. Debugging problems with pyodide that show up in CI is also very frustrating. Previous attempts to fix this have always resulted in it being flakey so that a small changes cause it to fail again.

Alternatively we could add the CI job to a different workflow that runs on merge to master rather than on each PR. Then it is less problematic if the CI job fails since it does not bother every contributor.

Another possibility is that it mgiht be better to use something like pytest-pyodide:
https://pypi.org/project/pytest-pyodide/

Really though we need someone who knows how to use pyodide, node etc to maintain any CI testing of pyodide.

Also in this PR I have removed the PyPy optional dependency job. Most of SymPy's optional dependencies do not really support PyPy properly and so most of the issues picked up there were really just issues with e.g. compatibility between SciPy and PyPy. If e.g. SciPy itself does not even test that it even builds correctly under PyPy then I don't think that it is worthwhile for SymPy to test that in its own CI and for me to spend time reporting these problems upstream. We can still test that SymPy's main tests pass under PyPy but compatibility of other projects with PyPy should be for those other projects to manage.

**Comment by brocksam** [comment]
I agree with the removal of the Pyodide job and everything @oscarbenjamin has said above regarding it would be good to have it back but would require someone with knowledge of Pyodide and Node to help set up and support it.

**Review by brocksam — APPROVED** [review]
Looks good to me.

**Comment by oscarbenjamin** [comment]
Thanks @brocksam.

I've also renamed the various jobs to make them easier to read in the GitHub web UI and updated the list of required jobs.

This will mean that CI needs to rerun on any open PRs.

**Pull request merged**
