### PR TITLE
factor_list() collects factors from partially factored input

### LINKED ISSUE #24652: factor_list should collect factors identified from partially factored input
From [this SO](https://stackoverflow.com/questions/75337159/how-do-i-store-factors-of-polynomials-in-a-list-in-sympy/75339700#75339700): Note that the expanded polynomial returns a factor with multiplicity of 2. Expansion should not be necessary to get the same from a partially factored input. This requires that the results of individual factors be combined before returning:
```python
>>> factor_list((x+1)*(x**6-1))
(1, [(x - 1, 1), (x + 1, 1), (x + 1, 1), (x**2 - x + 1, 1), (x**2 + x + 1, 1)])
>>> factor_list(expand((x+1)*(x**6-1)))
(1, [(x - 1, 1), (x + 1, 2), (x**2 - x + 1, 1), (x**2 + x + 1, 1)])

# prefer this

>>> [(b,e*c) for (b,e),c in Counter(factor_list((x+1)*(x**6-1))[1]).items()]
[(x - 1, 1), (x + 1, 2), (x**2 - x + 1, 1), (x**2 + x + 1, 1)]
```

### PR DESCRIPTION
**Pull request by Ishanned**
#### References to other Issues or PRs

fixes #24652 

#### Brief description of what is fixed or changed
factor_list() now collects duplicate/recurring factors from partially factored inputs. The corresponding test has also been added.

#### Release Notes

* polys
  * duplicate factors are now collected by factor_list

### CODE REVIEW

**Comment by Ishanned** [comment]
The test that fails here belongs to inverse mellin transform test
Instead of returning `(x**c - d**c)/(x - d)`
The test returns `d**c*((x/d)**c - 1)/(-d + x)`
I don't understand why this is happening, can someone take a look?

**Comment by smichr** [comment]
In this branch, what does the following produce?
```python
eq=S('d**c*((x/d)**c - 1)/(-d + x)');simplify(powsimp(expand_mul(eq, deep=False), force=True))
```

**Comment by Ishanned** [comment]
> In this branch, what does the following produce?
> 
> ```python
> eq=S('d**c*((x/d)**c - 1)/(-d + x)');simplify(powsimp(expand_mul(eq, deep=False), force=True))
> ```

I got the following output
> ```python
>(d**c - x**c)/(d - x)
>```

**Comment by smichr** [comment]
You might check the result locally:
```python
from sympy import re, pi
from sympy.functions.special.gamma_functions import gamma
from sympy.core.function import expand_mul
from sympy.functions.elementary.miscellaneous import (Max, Min)
from sympy.simplify.powsimp import powsimp
from sympy.simplify.simplify import simplify
IMT = inverse_mellin_transform
var('a:d s')
def simp_pows(expr):
        return simplify(powsimp(expand_mul(expr, deep=False), force=True)).replace(exp_polar, exp)
eq = IMT(d**c*d**(s - 1)*sin(pi*c)
                         *gamma(s)*gamma(s + c)*gamma(1 - s)*gamma(1 - s - c)/pi,
                         s, x, (Max(-re(c), 0), Min(1 - re(c), 1)))
print(eq)
print(eq.factor())
print(simp_pows(eq))
print(simp_pows(eq.factor()))
```

**Comment by Ishanned** [comment]
> You might check the result locally:
> 
> ```python
> from sympy import re, pi
> from sympy.functions.special.gamma_functions import gamma
> from sympy.core.function import expand_mul
> from sympy.functions.elementary.miscellaneous import (Max, Min)
> from sympy.simplify.powsimp import powsimp
> from sympy.simplify.simplify import simplify
> IMT = inverse_mellin_transform
> var('a:d s')
> def simp_pows(expr):
>         return simplify(powsimp(expand_mul(expr, deep=False), force=True)).replace(exp_polar, exp)
> eq = IMT(d**c*d**(s - 1)*sin(pi*c)
>                          *gamma(s)*gamma(s + c)*gamma(1 - s)*gamma(1 - s - c)/pi,
>                          s, x, (Max(-re(c), 0), Min(1 - re(c), 1)))
> print(eq)
> print(eq.factor())
> print(simp_pows(eq))
> print(simp_pows(eq.factor()))
> ```

I still get the same result.
Should I change the test for that?

**Comment by smichr** [comment]
My guess is that the `simplify` step is doing this extra factoring. It might be worth seeing if the logic somewhere that factors `(d**c-x**c)` into `x**c*((d/x)**c -1)` can be fixed. This is not a very helpful factoring.

**Comment by oscarbenjamin** [comment]
The test in question uses a simplification routine that calls `powsimp` with force=True. Generally force=True should be avoided since by definition it performs invalid simplifications. If `force=True` is not used then the expected result is obtained:
```python
In [20]: expr
Out[20]: 
       ⎛                 -c  c               ⎞         
 c - 1 ⎜Γ(c)⋅Γ(1 - c)   d  ⋅x ⋅Γ(-c)⋅Γ(c + 1)⎟         
d     ⋅⎜───────────── + ─────────────────────⎟⋅sin(π⋅c)
       ⎜        x                   x        ⎟         
       ⎜    1 - ─               1 - ─        ⎟         
       ⎝        d                   d        ⎠         
───────────────────────────────────────────────────────
                           π                           

In [21]: powsimp(expand_mul(expr, deep=False), force=True).replace(exp_polar, exp).simplify()
Out[21]: 
   ⎛   c    ⎞
 c ⎜⎛x⎞     ⎟
d ⋅⎜⎜─⎟  - 1⎟
   ⎝⎝d⎠     ⎠
─────────────
    -d + x   

In [22]: powsimp(expand_mul(expr, deep=False)).replace(exp_polar, exp).simplify()
Out[22]: 
   c    c
- d  + x 
─────────
  -d + x 

In [23]: signsimp(_)
Out[23]: 
 c    c
d  - x 
───────
 d - x 
```
It is unsurprising that `simplify` cannot undo the change performed by `force=True` because that change was not generally valid.

**Comment by oscarbenjamin** [comment]
> Even with `force=True` I don't like the symbolic (do-nothing?) factoring that results.

It's not a factoring. Basically what is happening is this:
```python
In [8]: x, y, z = symbols('x, y, z')

In [9]: expr = y**(z-1)*(x**z/y**z + 1)/(1 + x/y)

In [10]: expr
Out[10]: 
 z - 1 ⎛ z  -z    ⎞
y     ⋅⎝x ⋅y   + 1⎠
───────────────────
       x           
       ─ + 1       
       y           

In [11]: powsimp(expr)  # no change
Out[11]: 
 z - 1 ⎛ z  -z    ⎞
y     ⋅⎝x ⋅y   + 1⎠
───────────────────
       x           
       ─ + 1       
       y           

In [13]: powsimp(expr, force=True)  # powers combined
Out[13]: 
       ⎛   z    ⎞
 z - 1 ⎜⎛x⎞     ⎟
y     ⋅⎜⎜─⎟  + 1⎟
       ⎝⎝y⎠     ⎠
─────────────────
      x          
      ─ + 1      
      y          

In [12]: powsimp(expr).simplify()  # powers can cancel
Out[12]: 
 z    z
x  + y 
───────
 x + y 

In [14]: powsimp(expr, force=True).simplify()  # cannot cancel
Out[14]: 
   ⎛   z    ⎞
 z ⎜⎛x⎞     ⎟
y ⋅⎜⎜─⎟  + 1⎟
   ⎝⎝y⎠     ⎠
─────────────
    x + y 
```
Here `simplify` cannot separate the power that was combined by `powsimp` because the combined and expanded forms are not equivalent given the (lack of) assumptions on the symbols. Using `force=True` has created an invalid result that cannot subsequently be simplified to the expected form.

**Comment by Ishanned** [comment]
I have made a commit for the test in discussion, please have a look

**Pull request merged**
