### PR TITLE
Make `CRootOf` lazy on irreducibles.

### LINKED ISSUE #23418: `CRootOf` should have a `lazy` option
When you construct a `CRootOf`, it makes an initial approximation of the roots
right then, at construction time. It would be good if `CRootOf` offered a `lazy` option, so
that these approximations wouldn't be computed until they were needed.

I imagine this might have many applications, but at the moment I just have one application in mind:
When you form an `AlgebraicNumber` whose root is given by a `CRootOf`, it can be extremely slow, due
to this approximation of roots.

This is not good, because there are many things you can do with an `AlgebraicNumber` that do not
require these approximations at all. For many applications, it is just wasted time.

For example, just forming a field:

```python
>>> import time
>>> from sympy import QQ
>>> t0 = time.time(); k = QQ.cyclotomic_field(47); t1=time.time();
>>> print(t1-t0)
39.494821071624756
```

can take 40 seconds. This should be instantaneous.

### PR DESCRIPTION
**Pull request by skieffer**
#### References to other Issues or PRs

Resolves #23418
Replaces #23419 

#### Brief description of what is fixed or changed

If `f` is irreducible, and you construct `CRootOf(f, n)`, then the index `n` need not be adjusted.
This means we are free to postpone calculation of the isolating intervals until they are needed,
and this PR makes this so.

If `f` is composite, then the index `n` may need to be adjusted, which requires calculation of the
isolating intervals at construction time, so we cannot postpone it.

#### Release Notes

* polys
  * Lazy interval calculation for `CRootOf` on irreducible polys

### CODE REVIEW

**Comment by oscargus** [comment]
Looks good!

Do you know if the current tests cover the newly added code or should one add some specific test for this?

**Comment by skieffer** [comment]
Yeah, good question. I ran pytest with a coverage report, and all the new lines do have coverage, just from existing tests.

When I thought about adding new tests I could only think of ones that would involve timings, and I figured I shouldn't add those, due to differences in machines.

**Comment by skieffer** [comment]
On second thought, I could add a test showing the intervals cache is being used in the expected way.

**Comment by oscarbenjamin** [comment]
Looks good

**Comment by asmeurer** [comment]
I expect the code here could be simplified by making the caches special objects that automatically call the init methods when they are accessed.

**Comment by skieffer** [comment]
> making the caches special objects that automatically call the init methods when they are accessed

I like the idea of this design, but it would be hard to give time to it right now. Something to keep in mind though.

**Pull request merged**
