### PR TITLE
[skip ci] PEP8 amendments to compatibility.py

### PR DESCRIPTION
**Pull request by jremes-foss**
Couple of PEP8 amendments to compatibility.py.
- E302
- E265

Thank you.

### CODE REVIEW

**Comment by toolforger** [comment]
I'm pretty sure that adding empty lines around functions that are inline with executable code is a bad idea, PEP8 be damned.
The reasoning: `def func(...): ...` is just a shorthand for `func = lambda(...): ...`; when the code is modified, it may go from named (`def`) to unnamed (`lambda`) form or vice versa, with no real change in overall structure. Vertical empty space should reflect program structure, but here it's getting added or removed for something not necessarily structure-changing.

**Comment by toolforger** [comment]
BTW PEP8 mandates blank lines around a `def` only if it's a top-level function or a method.
For functions inside function bodies, no rule exists; what applies is this general rule: "Use blank lines in functions, sparingly, to indicate logical sections." Local functions aren't regulate

**Comment by toolforger** [comment]
P.S.: On re-reading the pertinent section of PEP8, I see that it mandates blank lines around a `def` only if it's a top-level function or a method.
For functions inside function bodies, no rule exists; what applies is this general rule: "Use blank lines in functions, sparingly, to indicate logical sections."

**Comment by sylee957** [comment]
I think that this should be closed because some `compatibility.py` pointing here are obsolete after python 2.7 is dropped.
There can be some other PEP8 issues in the module, but it would be more easy to begin from the scratch than working on this.

**Pull request closed without merging**
