### PR TITLE
Rename is_zero to is_zero_matrix

### LINKED ISSUE #17131: Matrices should not use is_zero for a zero matrix
Integrating a zero matrix returns the scalar zero. I think this is because matrices define is_zero as True for a zero matrix:
```julia
In [1]: M = Matrix([[0, 0]])                                                                                                      

In [2]: M                                                                                                                         
Out[2]: [0  0]

In [3]: integrate(M, t)                                                                                                           
Out[3]: 0

In [4]: M.is_zero                                                                                                                 
Out[4]: True
```
I think the error here is in Matrix.is_zero (which should always be False) rather than integrate. In the assumptions system is_zero means the scalar zero so is_zero can never be True for a matrix.

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

Fixes #17131

#### Brief description of what is fixed or changed

This is a problem in assumptions consistency, so I would consider this as a fix rather than deprecation. (Although I'm going to add a stub method to lock is_zero=False for mutable matrix)

#### Release Notes

- matrices
  - **Not backwards compatible**: The `Matrix.is_zero` property has been renamed to `Matrix.is_zero_matrix`. `Matrix.is_zero` is now always `False`. This is because in general `is_zero` means the number zero so a matrix can never be zero. To get the old behavior of `M.is_zero` in both old and new versions of sympy use `from sympy.core.logic import fuzzy_and; fuzzy_and(m.is_zero for m in M)`.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
The release notes should clearly indicate that this is not a backward compatible change.

This looks good to me. Are you done with it?

**Comment by sylee957** [comment]
I'm done with the code part. But I'm not sure what would be the best way to convey that it's backward incompatible change in the release notes. Can you take a look?

**Comment by oscarbenjamin** [comment]
I've updated the release note.

**Comment by sylee957** [comment]
I've edited the wiki for release notes, since it also have a section for manually adding the major deprecations.

**Pull request merged**
