### PR TITLE
[WIP] Atoms() return value changed, tests are remaining

### PR DESCRIPTION
**Pull request by darkcoderrises**
I ran the full suite of tests, some failed, I am looking over them one by one. 
http://pastebin.com/KRxzTXmR

### CODE REVIEW

**Comment by scopatz** [comment]
Tests are failing.

**Comment by darkcoderrises** [comment]
@asmeurer Please review

**Comment by mijo2** [comment]
This can be closed now.

**Comment by oscarbenjamin** [comment]
So it can. If you use "Closes #10246" in the OP of a PR then this would get closed automatically when merging.

**Pull request closed without merging**
