### PR TITLE
Fix not enough powers in series for Pow

### LINKED ISSUE #10761: (1/(x**-2 + x**-3)).series(x, 0) gives wrong result
`(1/(x**-2 + x**-3)).series(x, 0)` returns `x**3 - x**4 + O(x**6)` which is incorrect. Wolfram Alpha gives `x**3 - x**4 + x**5 - x**6 + x**7 + O(x**8)`.

### PR DESCRIPTION
**Pull request by vovapolu**
Fixes #10761

### CODE REVIEW

**Comment by smichr** [comment]
This looks like the right modification. +1 if it works.

**Comment by smichr** [comment]
As this test is right and nothing else failed, I would commit this but when I looked at #10503 I couldn't see what was wrong with those results -- probably something obvious but I just don't see it. The problem you had here was that another term appears before the O term but was not showing up. With #10503 it doesn't seem to be the same. Could you comment on this and see if, perhaps, these also pass in this PR and could be added as tests to close the issue? If what you have is correct, it is not necessary to root out the cause of the other issue's failure, I would just like to know what is right here and what is wrong there.

Perhaps @jksuom could commit this as is if he doesn't see a problem.

**Comment by vovapolu** [comment]
@smichr Unfortunately, my fix doesn't do anything with #10503. My PR changes only `Pow` class and it seems that the problem lies in some other place, perhaps in the multiplication of series. #9549 also has this problem: `(x**2 + x + 1)` and `(x**3 + x**2)**-1' gives the right series, but the result of multiplication is wrong.

**Comment by smichr** [comment]
OK, merging as is.

**Comment by jksuom** [comment]
Sorry for the delay, I only now found some time to look into this. I am not yet sure how to fix issue, but it seems that this PR is only a partial solution.
```
>>> f = 1/(x**-2 + x**-3)
>>> f.series(x, 0)
x**3 - x**4 + x**5 + O(x**6)
>>> f.series(x, 0, n=10)
x**3 - x**4 + x**5 - x**6 + O(x**10)
>>> f.series(x, 0, n=20)
x**3 - x**4 + x**5 - x**6 + x**7 - x**8 + x**9 + O(x**20)
```

**Pull request merged**
