### PR TITLE
Dimension divided by same Dimension returns empty Dimension, not 1

### PR DESCRIPTION
**Pull request by abentkamp**
also adapted and improved the dim_simplify function.

it's my first pull request for this project, so please tell me, if you expect me to do something differently...

### CODE REVIEW

**Comment by asmeurer** [comment]
@melsophos

**Comment by asmeurer** [comment]
It looks like there are some test failures.

**Comment by asmeurer** [comment]
Be sure that `./bin/test units` and `./bin/doctest units` pass before committing.

**Comment by melsophos** [comment]
I will try to review this soon, but before I should explain why the division of two Dimensions give 1 and not an empty Dimension. One reason is that if one wants to perform the dimensional analysis of an expression which involves a call of a function on a dimensionless quantity. I was assuming that the function needs a number for its argument, but apparently this is not the case as you have a test for this.
The second point is that if after computations you get a quantity without dimension then it is easier to just keep track of the number (but we had a discussion saying that we should avoid magic in simplifications and let the user decide).

So why do you think it is better to change this point?

**Comment by benti** [comment]
Sorry for the failing tests. I only ran those, that I thought might be influenced by my changes and apparently I was wrong... I'll try to fix that.

@melsophos I was hoping for someone to discuss this topic. My problem is basically this error:
```
>>> from sympy.physics.unitsystems.quantities import Quantity as Q
>>> from sympy.physics.unitsystems.systems import mks
>>> from sympy.physics.unitsystems.simplifiers import qsimplify
>>> m = mks["m"]
>>> b = (Q(1122,m)/Q(0.002,m))**(-1.0)
>>> qsimplify(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Miniconda\lib\site-packages\sympy\physics\unitsystems\simplifiers.py", line 83, in qsimplify
    return args[0].pow(args[1])
AttributeError: 'Float' object has no attribute 'pow'
```
Similar things can happen in dim_simplify, for example:
```
>>> dim_simplify(Dimension({"length":-2})*Dimension({"length":2})+1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Miniconda\lib\site-packages\sympy\physics\unitsystems\simplifiers.py", line 34, in dim_simplify
    return reduce(lambda x, y: x.add(y), args)
TypeError: reduce() of empty sequence with no initial value
```
Now that I think about it, I am not even sure if my pull request resolves this. Maybe I sent it in a bit too early, but I really needed this discussion first.

I can see that in some cases it could be useful to get a number instead of a dimensionless quantity. But as you can see in the code of the simplifiers, it also is a great advantage if you can rely more on which type of return value you get.

What exactly do you mean by "avoid magic in simplifications"?

**Comment by benti** [comment]
Closed in favor of https://github.com/sympy/sympy/pull/10110

**Pull request closed without merging**
