### PR TITLE
Move diophantine utility functions to their own file [WIP]

### PR DESCRIPTION
**Pull request by ethankward**
Continuation of #18493.

#### Brief description of what is fixed or changed
Continuing to refactor diophantine module. Created `util.py` for utility functions. Created `test_util.py` and moved tests. Removed mention of "internal functions" from documentation.

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This should reference the previous PR. Did the previous PR have a release note?

**Comment by oscarbenjamin** [comment]
If this will need multiple PRs then I think it would be good to open an issue that explains what the overall plan is and the purpose of it.

**Comment by oscarbenjamin** [comment]
I think that the internal functions can still be documented although perhaps it should be on a separate page of the docs. Does this just remove them completely from the docs?

**Comment by asmeurer** [comment]
I agree that we should keep the internal functions in the docs. If anything it is easier to read the documentation in Sphinx, especially for the functions that have a lot of math. But we should in general make it clearer in the docs when things are internal and shouldn't be considered public API. Having them on a completely separate page is a good idea. It might even make sense to have a completely separate "Internal docs" section of the documentation for internal documentation. This is definitely an issue with a lot of modules, not just diophantine.

**Comment by ethankward** [comment]
Still thinking about how best to organize this, here is a summary of the 61 functions currently in `diophantine.py`. Functions with `x` are mentioned on the `diophantine.rst` page.

1. Utility functions that have no wider use outside of this module:
- 	_is_int
- 	_sorted_tuple
- 	_remove_gcd
- 	_rational_pq
- 	_nint_or_floor
- 	_odd
- 	_even
- 	dot
- 	norm
- 	divisible x

2 Utility functions that may be useful outside of this module:
- 	partition x
- 	gaussian_reduce x
- 	prime_as_sum_of_two_squares x
- 	sum_of_three_squares x
- 	sum_of_four_squares x
- 	square_factor x

3. Public functions:
- 	diophantine x
- 	classify_diop x
- 	diop_solve x

4. Internal functions that should not appear in documentation, and could potentially be removed entirely:
- 	merge_solution x

5. Linear equations and helper functions:
- 	diop_linear x
- 	_diop_linear
- 	base_solution_linear x

6. Binary quadratic equations and helper functions:
- 	diop_quadratic x
- 	_diop_quadratic
- 	is_solution_quad
- 	check_param

7. Ternary quadratic equations:
- 	diop_ternary_quadratic x
- 	_diop_ternary_quadratic
- 	parametrize_ternary_quadratic x
- 	_parametrize_ternary_quadratic

8. Ternary quadratic normal equations:
- 	diop_ternary_quadratic_normal x
- 	_diop_ternary_quadratic_normal
- 	holzer x
- 	descent x
- 	ldescent x
- 	reconstruct x
- 	transformation_to_normal x
- 	_transformation_to_normal
- 	sqf_normal x

9. General sum of even powers:
- 	diop_general_sum_of_even_powers x
- 	_diop_general_sum_of_even_powers


10. General pythagorean:
- 	diop_general_pythagorean x
- 	_diop_general_pythagorean

11. General sum of squares:
- 	diop_general_sum_of_squares x
- 	_diop_general_sum_of_squares
- 	power_representation / sum_of_powers x
- 	pow_rep_recursive
- 	sum_of_squares x
- 	_can_do_sum_of_squares

12. Generalized Pell equation *:
- 	diop_DN x
- 	_special_diop_DN
- 	transformation_to_DN x
- 	_transformation_to_DN
- 	find_DN x
- 	_find_DN
- 	diop_bf_DN x
- 	equivalent x
- 	cornacchia x
- 	PQa x
- 	length

* the generalized Pell equation is not listed as a specific equation type that can be solved, but all the infrastructure is there already.

**Comment by oscarbenjamin** [comment]
I think that the most important way to think about how to separate those function is if you can figure out which functions call which other functions. Ideally the code is organised into files with no cyclic dependencies (files can correspond to strongly connected components). After that it's largely about creating an understandable organisation: would you know where to look for something without just grepping?

Can you summarise what this PR does? It's not clear from the OP (and I'm not sure if the OP is up to date after recent commits).

**Comment by oscarbenjamin** [comment]
@ethankward I'm unclear what the status of this PR is.

**Comment by ethankward** [comment]
Sorry, I've been unexpectedly busy- I'm still working on this.

**Comment by ethankward** [comment]
I'm going to keep working in a single file until things are easier to disentangle.

**Pull request closed without merging**
