### PR TITLE
Max/Min know when they are positive/non-negative/negative

### LINKED ISSUE #8643: Max should be positive if any of its args is positive
At the moment,
```python
>>> x = Symbol('x', real=True, positive=True)
>>> y = Symbol('y', real=True)
>>> Max(x, y).is_positive
```
returns `None`, while it should return `True`. Do you think that implementing `_eval_is_positive` is enough here? Or `_eval_is_nonnegative` as well? Or just the latter? Will it conclude `is_nonpositive` and `is_negative` automatically?

### PR DESCRIPTION
**Pull request by leosartaj**
This works now

```
>>> x = Symbol('x', real=True, positive=True)
>>> y = Symbol('y', real=True)
>>> Max(x, y).is_positive
True
```

```
>>> z = Symbol('x', real=True, negative=True)
>>> Min(z, y).is_positive
False
```

closes #8643 

ping @aktech @jksuom

### CODE REVIEW

**Comment by debugger22** [comment]
I think we should add these in new assumptions too. @asmeurer

**Comment by asmeurer** [comment]
Once you have finished the "ask calls assumptions on Expr" branch and finish making the old and new assumptions consistent, we should have a discussion, probably on the mailing list, about where newly added assumption facts should go. For now, let's leave pull requests like this be. Adding things to the old assumptions is, at present, the right thing to do.

**Comment by asmeurer** [comment]
I think this logic could be simplified by using `fuzzy_or`.

**Comment by leosartaj** [comment]
I didn't know there was something like this. It will be greatly simplified. Thanks!

**Comment by leosartaj** [comment]
@asmeurer

**Comment by asmeurer** [comment]
Looks good.

**Comment by aktech** [comment]
Thanks for working on this, +1 Merging.

**Comment by leosartaj** [comment]
Thanks!

**Pull request merged**
