### PR TITLE
vector : Scalar condition of vectors made False

### LINKED ISSUE #16510: is_scalar is true for matrix symbols and expressions?
```python
>>> from sympy import *
>>> A = MatrixSymbol('A', 3, 3)
>>> A.is_scalar
True
```

I see `is_scalar` was introduced in #15049

Edit
See current status at https://github.com/sympy/sympy/issues/16510#issuecomment-592611393

### PR DESCRIPTION
**Pull request by faze-geek**
#### References to other Issues or PRs

Closes #16510

#### Brief description of what is fixed or changed
The issue #16510 has already been resolved on master by some other commit .
This fix is for [16510( comment )
](https://github.com/sympy/sympy/issues/16510#issuecomment-592611393)

Earlier on master -
```
>>> from sympy.vector import CoordSys3D
>>> C = CoordSys3D('C')
>>> v = 3*C.i + 4*C.j + 5*C.k
>>> v.is_scalar
True
```
On my branch -
```
>>> from sympy.vector import CoordSys3D
>>> C = CoordSys3D('C')
>>> v = 3*C.i + 4*C.j + 5*C.k
>>> v.is_scalar
False
```

#### Release Notes

* vector
  * Scalar condition of vectors made False

### CODE REVIEW

**Comment by anutosh491** [comment]
Nice catch ,looks good . Could go in after set of reviews !

**Comment by faze-geek** [comment]
> Nice catch ,looks good . Could go in after set of reviews !

Thanks ,seems straight forward to me . @oscarbenjamin @czgdp1807 is it good to go ?

**Comment by czgdp1807** [comment]
I don't know much about this part of SymPy. Can't say much whether this is the right change or not. @sylee957 Any thoughts from your side?

**Comment by faze-geek** [comment]
> I don't know much about this part of SymPy. Can't say much whether this is the right change or not. @sylee957 Any thoughts from your side?

Thanks . @oscarbenjamin @sylee957  would appreciate any suggestions / response to this !

**Comment by sylee957** [comment]
Is there any nontrivial issues that this can solve or is it only solves `is_scalar`?

**Comment by faze-geek** [comment]
> Is there any nontrivial issues that this can solve or is it only solves `is_scalar`?

None that I came across of as of now .Seemed direct when I read your comment on the issue  !

**Pull request merged**
