### PR TITLE
Update .mailmap and AUTHORS

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by aktech** [comment]
+1

**Comment by moorepants** [comment]
It's be nice if this ran automatically on each push, if there is a new Author, it'd make a new commit.

**Comment by certik** [comment]
There is manual work in figuring out the .mailmap, and checking for duplicates. E.g. @bjodah name was misspelled and I had to correct it.

**Comment by bjodah** [comment]
Thanks @certik, it's a pain with these non-ascii names of ours, isn't it Ondřej?

**Comment by certik** [comment]
In your case the misspelling was g -> h. I actually have no issues with unicode mostly.

**Pull request merged**
