### PR TITLE
Bump version to 1.6rc1

### PR DESCRIPTION
**Pull request by oscarbenjamin**
Bump version on the 1.6 release branch from 1.6.dev to 1.6rc1

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Bumping the version has somehow caused a test failure from doctests. The failed example is:
```
>>> from sympy import sqrt, Symbol
>>> x = Symbol('x')
>>> sqrt(x).has(sqrt)
/Users/enojb/current/sympy/sympy/sympy/core/sympify.py:383: SymPyDeprecationWarning: 

String fallback in sympify has been deprecated since SymPy 1.6. Use
sympify(str(obj)) or sympy.core.sympify.converter or obj._sympy_
instead. See https://github.com/sympy/sympy/issues/18066 for more
info.

  SymPyDeprecationWarning(
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/sympy/sympy/core/sympify.py", line 406, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/Users/enojb/current/sympy/sympy/sympy/parsing/sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/Users/enojb/current/sympy/sympy/sympy/parsing/sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 1
    <Symbol ('function' )sqrt Symbol ('at' )Integer (0x1117a3f70 )>
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1233, in has
    return any(self._has(pattern) for pattern in patterns)
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1233, in <genexpr>
    return any(self._has(pattern) for pattern in patterns)
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1242, in _has
    pattern = sympify(pattern)
  File "/Users/enojb/current/sympy/sympy/sympy/core/sympify.py", line 408, in sympify
    raise SympifyError('could not parse %r' % a, exc)
sympy.core.sympify.SympifyError: Sympify of expression 'could not parse '<function sqrt at 0x1117a3f70>'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)
```
The doctest is
https://github.com/sympy/sympy/blob/bbc9bde9799fde640fe586cc815529b6e96e7cbc/sympy/functions/elementary/miscellaneous.py#L129-L135

It seems that this now fails on Travis because of the deprecation warning. I'm not sure why that didn't fail before though. The related PR #19244 bumps the version on master from 1.6.dev to 1.7.dev and apparently the doctests passed fine there. Both PRs have the same parent commit.

Why does changing the version to 1.6 affect this?

**Comment by oscarbenjamin** [comment]
The doctest that failed seems to fail on master when I run it locally:
```
$ bin/doctest sympy/functions/elementary/miscellaneous.py
============================================================= test process starts =============================================================
executable:         /Users/enojb/current/sympy/38venv/bin/python  (3.8.1-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 2.0.8
numpy:              1.18.3
hash randomization: on (PYTHONHASHSEED=2558226336)

sympy/functions/elementary/miscellaneous.py[8] ......F.                                                                                  [FAIL]

_______________________________________________________________________________________________________________________________________________
________________________________________________ sympy.functions.elementary.miscellaneous.sqrt ________________________________________________
File "/Users/enojb/current/sympy/sympy/sympy/functions/elementary/miscellaneous.py", line 129, in sympy.functions.elementary.miscellaneous.sqrt
Failed example:
    sqrt(x).has(sqrt)
Expected:
    Traceback (most recent call last):
      ...
    sympy.core.sympify.SympifyError: Sympify of expression 'could not parse
    '<function sqrt at 0x7f79ad860f80>'' failed, because of exception being
    raised:
    SyntaxError: invalid syntax
Got:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/doctest.py", line 1329, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest sympy.functions.elementary.miscellaneous.sqrt[16]>", line 1, in <module>
        sqrt(x).has(sqrt)
      File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1233, in has
        return any(self._has(pattern) for pattern in patterns)
      File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1233, in <genexpr>
        return any(self._has(pattern) for pattern in patterns)
      File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1242, in _has
        pattern = sympify(pattern)
      File "/Users/enojb/current/sympy/sympy/sympy/core/sympify.py", line 383, in sympify
        SymPyDeprecationWarning(
      File "/Users/enojb/current/sympy/sympy/sympy/utilities/exceptions.py", line 185, in warn
        warnings.warn(self, stacklevel=stacklevel)
    sympy.utilities.exceptions.SymPyDeprecationWarning: 
    <BLANKLINE>
    String fallback in sympify has been deprecated since SymPy 1.6. Use
    sympify(str(obj)) or sympy.core.sympify.converter or obj._sympy_
    instead. See https://github.com/sympy/sympy/issues/18066 for more
    info.
    <BLANKLINE>

============================================= tests finished: 7 passed, 1 failed, in 0.20 seconds =============================================
DO *NOT* COMMIT!
```

**Comment by oscarbenjamin** [comment]
Looking at the travis log for the doctests in #19244 I see
```
sympy/functions/elementary/miscellaneous.py[8] ....../home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/sympy-1.7.dev0-py3.8.egg/sympy/core/sympify.py:383: SymPyDeprecationWarning: 
String fallback in sympify has been deprecated since SymPy 1.6. Use
sympify(str(obj)) or sympy.core.sympify.converter or obj._sympy_
instead. See https://github.com/sympy/sympy/issues/18066 for more
info.
  SymPyDeprecationWarning(
```
So it looks like the doctest runner is inconsistent in whether it fails for a DeprecationWarning.

**Comment by Sc0rpi0n101** [comment]
There was also a similar error reported in #19141 
So, I also think the doctest runner is just inconsistent with these.

**Comment by oscarbenjamin** [comment]
I have a fix for the test runner coming. It is complicated by the fact that some of the tests now fail so those need to be fixed.

**Pull request merged**
