### PR TITLE
Lazy evaluation for series in test_fourier

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### Brief description of what is fixed or changed

The tests in test_fourier.py precompute some series for general use. This patch delays computing them until the tests run. Previously these series were computed during import which adds around 3 seconds to test collection even if the tests are skipped.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by bjodah** [comment]
There is a `lru_cache` function in `sympy.core.compatibility`:
https://github.com/sympy/sympy/blob/a70b14b882f1ef1532835cc32f6edf76b2d7ac10/sympy/core/compatibility.py#L775
Does it not work here?

**Comment by oscarbenjamin** [comment]
Good point. I've updated the patch to use that instead.

**Comment by jksuom** [comment]
It would probably be better to import `lru_cache` from `sympy.core.cache`. That will automatically use `fastcache` when it is available.

**Comment by oscarbenjamin** [comment]
> It would probably be better to import lru_cache from sympy.core.cache. That will automatically use fastcache when it is available.

I could change it to that. This cache only contains one entry and is used 4 times during the whole test suite though so I would be very surprised if you could tell the difference.

What is noticeable is that if you just import this module without running the tests (e.g. during test collection) then previously it took 3 seconds to import whereas with this patch it is basically instantaneous.

**Comment by oscarbenjamin** [comment]
I've changed it to `sympy.core.cache.lru_cache` as suggested.

**Comment by asmeurer** [comment]
+1

**Comment by bjodah** [comment]
+1

**Comment by asmeurer** [comment]
Yes. The tests weren't done when I commented or else I would have merged it myself.

**Pull request merged**
