### PR TITLE
added levy distribution

### PR DESCRIPTION
**Pull request by ritesh99rakesh**
#### Brief description of what is fixed or changed
Added Levy distribution to `crv_types.py` and added tests for the same.

#### Release Notes

stats
* added levy distribution

### CODE REVIEW

**Comment by ritesh99rakesh** [comment]
Please review @oscargus @asmeurer

**Comment by oscarbenjamin** [comment]
Some functions are untested: set, _characteristic_function, and _moment_generating_function.

**Comment by ritesh99rakesh** [comment]
@oscarbenjamin I have added function for set and characteristic_function but I am not able to get how to write the test for _moment_generating_function. I could not find any similar example.

**Comment by oscarbenjamin** [comment]
I think you should call the moment_generating_function which calls _moment_generating_function and test that it returns the correct result.

Also this needs a release note.

**Comment by ritesh99rakesh** [comment]
I tried but still I am not able to get. When I call `moment_generating_function(X)` I get `Lambda(_t, None)`. But I am not able to figure out how I should use it in test.

**Comment by oscarbenjamin** [comment]
This is how it works with Exponential:
```julia
In [10]: from sympy.stats import Exponential, E, moment_generating_function                                                                    

In [11]: X = Exponential('x', 't')                                                                                                             

In [12]: E(X)                                                                                                                                  
Out[12]: 
1
─
t

In [13]: moment_generating_function(X)                                                                                                         
Out[13]: 
      t   
t ↦ ──────
    -t + t
```
Note that expectation may use the moment_generating_function if it exists.

I think looking at the other code that your _moment_generating_function method should return None. Actually though I think the superclass already does that so maybe you can just delete that method.

**Comment by czgdp1807** [comment]
@ritesh99rakesh Are you planning to complete this PR, as you said on Facebook Messenger that you are going to take up your PRs after your exams? Please let us know about the updates.

**Comment by Smit-create** [comment]
@czgdp1807 I will take this over

**Comment by Smit-create** [comment]
#18096

**Comment by czgdp1807** [comment]
Closing this PR in favour of #18096

**Pull request closed without merging**
