### PR TITLE
converted the function to integrate into first its expansion and then integration was done

### LINKED ISSUE #16161: Integral of x*sec(x)**2 doesn't evaluate
This comes from #11131.

This integral doesn't evaluate but Wolfram gives an answer that differentiates back to a form equivalent to the integrand:
```julia
In [14]: f = x*sec(x)**2                                                                                                                                      

In [15]: F = x*tan(x) + log(cos(x))                                                                                                                           

In [16]: f                                                                                                                                                    
Out[16]: 
     2   
x⋅sec (x)

In [17]: F                                                                                                                                                    
Out[17]: x⋅tan(x) + log(cos(x))

In [18]: integrate(f, x)                                                                                                                                      
Out[18]: 
⌠             
⎮      2      
⎮ x⋅sec (x) dx
⌡             

In [19]: F.diff(x)                                                                                                                                            
Out[19]: 
  ⎛   2       ⎞   sin(x)         
x⋅⎝tan (x) + 1⎠ - ────── + tan(x)
                  cos(x)         

In [20]: simplify(F.diff(x)-f)                                                                                                                                
Out[20]: 0
```

### PR DESCRIPTION
**Pull request by drishyakumar**
References to other Issues or PRs

Fixes #16161 

Brief description of what is fixed or changed

used the expansion of such type of function to integrate as
expr = exp(tan(x))
 expr.series(x, 0, 4)
expr.series(x, 0, 4).removeO()

expo=exp(log(cos(x))
expo.series(x, 0, 4).removeO()
integrate(x*(expr.series(x, 0, 4)).removeO() + expo.series(x, 0, 4).removeO() ,x)

Other comments

Release Notes
* integrals
  * solved the problem with ∫xtan(x)dx
∫ x tan(x)dx

### CODE REVIEW

**Comment by drishyakumar** [comment]
someone please help

**Comment by oscarbenjamin** [comment]
There are no changes in this PR. Had you written some code that you wanted to send?

**Comment by drishyakumar** [comment]
No sir please guide me in this regard

**Comment by asmeurer** [comment]
series expansion can always be done manually by the user, but it shouldn't be done by an algorithm, unless it can be guaranteed to give an exact (nonseries) answer at the end.

**Comment by czgdp1807** [comment]
@drishyakumar The issue associated with this PR is still un-resolved. Would you like to work on it? Thanks for the contributions.

**Comment by czgdp1807** [comment]
Closing this diff doesn't exists.

**Pull request closed without merging**
