### PR TITLE
Use doctr to deploy dev docs to http://docs.sympy.org/dev/

### PR DESCRIPTION
**Pull request by asmeurer**
See https://drdoctr.github.io/doctr/ for more information about doctr.

Fixes https://github.com/sympy/sympy/issues/5628
Closes https://github.com/sympy/sympy/issues/8740

### CODE REVIEW

**Comment by asmeurer** [comment]
Unfortunately, the only way to test this is to merge it, since it doesn't deploy from pull requests.

**Comment by asmeurer** [comment]
Also, to be aware, this uses a deploy key at https://github.com/sympy/sympy_doc/settings/keys. If for whatever reason we want to disable this, or have reason to believe the encrypted environment variable has been leaked, we should revoke that deploy key.

**Comment by asmeurer** [comment]
I guess we also need to run the generate_indices script.

**Comment by asmeurer** [comment]
Support for this will need to be added upstream https://github.com/drdoctr/doctr/issues/91.

**Comment by asmeurer** [comment]
[It worked](http://docs.sympy.org/dev/) (I have run the generate_indexes.py script manually for now, which is why the version numbers are there, but as soon as another build happens they will go away on the dev docs index page).

**Comment by moorepants** [comment]
Nice work!

**Comment by asmeurer** [comment]
I am working on a release of doctr that will let us run generate_indices.py. It should be ready later tonight, or tomorrow.

**Comment by asmeurer** [comment]
Fixed at https://github.com/sympy/sympy/pull/11564

**Pull request merged**
