### PR TITLE
Second Quantization: Fixed TypeError in FermionState

### PR DESCRIPTION
**Pull request by hkve**
#### Brief description of what is fixed or changed

The base class ``FermionState``, which ``FermionStateBra``/``FermionStateKet`` inherits from, had a bug in its ``_negate_holes`` function. In the case where symbolic states were used, the index could not be compared to the fermi level, raising a ``TypeError``. Fixed by using the already existing ``_only_above_fermi`` function, making sure it is a number before negating. Added a test that fails before the patch.

#### Other comments
Since ``_sort_anticommuting_fermions`` uses the symbols hash to sort the indices, the ordering will differ per runtime. Something like ``default_sort_key`` can be used instead, but I think using something like the ``_sortkey`` functions for ``AntiSymmetricTensor`` might be better, as general, particle and hole indices are treated differently. This also makes testing the above more difficult.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by hkve** [comment]
After some investigation, this also fixes #14727. 

However, how should work be done patching secondquant? As mentioned in #5980, ``sympy.physics.secondquant`` was created before the new stuff in ``sympy.physics.quantum``, and should probably be refactored to fit the latter. Still, this issue has been open since 2011, so unsure when/if an effort will be made.

**Comment by oscarbenjamin** [comment]
This looks good. Thanks!

**Comment by oscarbenjamin** [comment]
> However, how should work be done patching secondquant?

The whole of quantum in SymPy is basically unmaintained.

What that means is that no one can answer your question. I'm happy to merge things if they look like improvements but I don't know much about quantum mechanics in general and I have no sense for any overall plan for SymPy's quantum code.

If you want to refactor it because that is what is needed then go ahead.

**Comment by hkve** [comment]
Alright, that makes sense!

Refactoring all of ``secondquant`` to fit ``physics.quantum`` sounds like a lot of work, and anyways, it's probably not that important if ``physics.quantum`` is unmaintained.

I have been using the ``secondquant`` code for the last two years, and a lot of it is very handy (however sometimes buggy). I’ll try to fix some of the parts which have annoyed me.

Thank you for the info!

**Pull request merged**
