### PR TITLE
Add example notebooks for `sympy.physics.quantum`

### PR DESCRIPTION
**Pull request by ellisonbg**
Took time to refactor and update these notebooks. Should help document the quantum stuff better.

### CODE REVIEW

**Comment by bjodah** [comment]
Just a small point: I think we are trying to avoid checking in any generated binary data (base64 encoded or not) into the sympy/sympy.git repo. @moorepants suggested a separate repository with `.ipynb` files *with* cell output included (for use with nbviewer), I don't know if that repo ever materialized though.

**Comment by ellisonbg** [comment]
More than willing to move these over to a separate repo if there is some
momentum behind that. +1

On Sun, May 15, 2016 at 3:00 PM, Björn Dahlgren <notifications@github.com>
wrote:

> Just a small point: I think we are trying to avoid checking in any
> generated binary data (base64 encoded or not) into the sympy/sympy.git
> repo. @moorepants <https://github.com/moorepants> suggested a separate
> repository with .ipynb files *with* cell output included (for use with
> nbviewer), I don't know if that repo ever materialized though.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sympy/sympy/pull/11113#issuecomment-219313314>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by moorepants** [comment]
@asmeurer Can we create a sympy-examples repo or sympy-notebooks repo for committing notebooks with output cells? I think you probably have the access to do that.

**Comment by asmeurer** [comment]
Here you go. Do whatever you want with it https://github.com/sympy/sympy-notebooks

**Comment by moorepants** [comment]
@ellisonbg Want to submit this to the new repo?

**Comment by ellisonbg** [comment]
We have moved these notebooks to a separate repo:

https://github.com/sympy/quantum_notebooks

Closing this one.

**Pull request closed without merging**
