### PR TITLE
Simplified hierarchy of Plot class and *Backend classes

### PR DESCRIPTION
**Pull request by Davide-sd**
#### References to other Issues or PRs

Another PR related to #23036 .

#### Brief description of what is fixed or changed

The `Plot` class used OOP composition with respect to a `*Backend` class. In other words, an instance of `*Backend` was saved into the `_backend` attribute of the `Plot` instance.

This PR changes it to inheritance: the `Plot` class becomes the base class for `*Backend` classes, holding the most common attributes expected to be used by most plotting libraries, like title, axis labels, etc. In doing so, the `BaseBackend` and `DefaultBackend` classes are no longer needed: their logic have been incorporated into the `Plot` class.

Previously, `MatplotlibBackend` had to keep track of all the axes required by the `PlotGrid` class. For example, a PlotGrid containing 4 plots created one instance of `MatplotlibBackend`, which created a figure with 4 subplots (hence, the `ax` attribute was a list containing 4 matplotlib's axes). This PR changes it: `MatplotlibBackend` is only going to deal with one axes (one subplot). As a consequence, `PlotGrid` was modified to create the overall figure and subplot-axes, which are then going to be fed to the backend.

This simplifies the overall structure, while allowing new behaviors to be implemented on future PRs, specifically:

1. interactive widget plots.
2. more complex grid layouts with PlotGrid.

**EDIT: information for users that created custom backends.**

To update a custom backend class:

1. make it subclass the `Plot` class.
2. Add a `__new__` method.
3. Modify the `__init__` method to call the base class `__init__`.
4. Replace occurrences of `self.parent` with `self`.

```py
class MyBackend(Plot):
    def __new__(cls, *args, **kwargs):
        return object.__new__(cls)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # your old code here
```

#### Release Notes

* plotting
  * BREAKING CHANGE: Changed relationship between `Plot` and `*Backend` classes. Moving from composition to inheritance.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
> The `Plot` class used OOP composition with respect to a `*Backend` class. In other words, an instance of `*Backend` was saved into the `_backend` attribute of the `Plot` instance.
> 
> This PR changes it to inheritance: the `Plot` class becomes the base class for `*Backend` classes

I don't oppose this change but I just want to note that from a high level this seems like a step backwards to me in design terms. My experience with the SymPy codebase has convinced me very firmly that composition is better than inheritance especially if it the intention is to share code between multiple classes.

**Comment by oscarbenjamin** [comment]
> * BREAKING CHANGE: Simplified hierarchy of `Plot` class and `*Backend` classes.

This needs to be more explicit. What exactly is breaking? Can you say explicitly what sort of downstream code would break?

**Comment by Davide-sd** [comment]
> This needs to be more explicit. What exactly is breaking? Can you say explicitly what sort of downstream code would break?

Most users won't note any difference because they use what's provided by the plotting module, which uses Matplotlib. Instead, anyone that implemented a custom backend class to use a different plotting library (hence, calling `plot(expr, backend=MyCustomBackend)` would have to adjust their code. I've written the steps in this PR first post.

Is the following release title better? Changed relationship between `Plot` and `*Backend` classes. Moving from composition to inheritance.

**Comment by oscarbenjamin** [comment]
> anyone that implemented a custom backend class to use a different plotting library (hence, calling `plot(expr, backend=MyCustomBackend)` would have to adjust their code.

Do we know of any examples of this besides spb?

**Comment by oscarbenjamin** [comment]
> * make it subclass the `Plot` class.

Could Backend be kept as an alias for Plot?

> * Add a `__new__` method.

Why is this needed?

> * Modify the `__init__` method to call the base class `__init__`.

I imagine most classes would do this already unless they use `__new__`.

> * Replace occurrences of `self.parent` with `self`.

Maybe `self.parent` could be an alias for `self`...

Just wondering if this can be made still compatible at all. I'm not sure it's worth trying to retain compatibility though: if code needs to be changed then it is better to have a clean break rather than subtle breakage.

**Comment by Davide-sd** [comment]
> I don't oppose this change but I just want to note that from a high level this seems like a step backwards to me in design terms. My experience with the SymPy codebase has convinced me very firmly that composition is better than inheritance especially if it the intention is to share code between multiple classes.

Usually, I would agree with you. But in this case there is no advantage is using composition: you just end up with wrappers methods (for example, `show`, `close`), a lot of cross-referencing... Here, inheritance makes things cleaner.

> Do we know of any examples of this besides spb?

I'm not aware of anyone. Besides, `spb` uses inheritance instead of composition. Worked great for multiple plotting libraries.

> Could Backend be kept as an alias for Plot?

I suppose it could, but it wouldn't stop the code from breaking because almost all of the aforementioned correction steps are still necessary.

> Why is this needed?

The `__new__` is needed to break recursion from the base class `Plot`. 

> Just wondering if this can be made still compatible at all. I'm not sure it's worth trying to retain compatibility though: if code needs to be changed then it is better to have a clean break rather than subtle breakage.

That's precisely my point: if I have to break it, I do it for good. `spb` uses inheritance, hence this break must happens for that module to be merged. I'm not inclined to spend weeks over it to change it back to composition: there is no guaranteed that would work.

**Comment by oscarbenjamin** [comment]
> Usually, I would agree with you. But in this case there is no advantage is using composition: you just end up with wrappers methods (for example, `show`, `close`), a lot of cross-referencing... Here, inheritance makes things cleaner.

Yes, boilerplate is the downside of composition over inheritance. Everything else is the upside though when it comes to making changes in future. I have come to the conclusion that only in extreme situations is the saving on boilerplate worthwhile compared to all of the problems of rigid structure and tight coupling that inheritance brings.

It is easy at one point in time to design an inheritance hierarchy and a set of methods that works just right for what you want those classes to do at that particular time. In future though as requirements change and as other unforeseen changes are made everything degrades into a big mess. Eventually major improvements will become impossible without rewriting everything because the code is so tightly coupled through the combinatorial explosion of different call graphs generated by each method of each node in the inheritance graph.

The worst place to have the tight coupling that inheritance brings is across the boundary between different codebases: you definitely want to avoid a situation where downstream codebases have classes inheriting from the classes in your codebase if at all possible. For example if other downstream code currently uses Backend subclasses then the changes in this PR would be impossible without breaking everything.

> I'm not inclined to spend weeks over it to change it back to composition

To be clear I am not suggesting to do that.

**Comment by sylee957** [comment]
Is it possible to avoid `__new__` by defining a function?
```
def construct_plot(cls, *args, **kwargs):
    backend = kwargs.pop("backend", "default")
    if isinstance(backend, str):
        if backend == "default":
            matplotlib = import_module('matplotlib',
                min_module_version='1.1.0', catch=(RuntimeError,))
            if matplotlib:
                return MatplotlibBackend(*args, **kwargs)
            return TextBackend(*args, **kwargs)
        return plot_backends[backend](*args, **kwargs)
    elif (type(backend) == type) and issubclass(backend, cls):
        return backend(*args, **kwargs)
    else:
        raise TypeError("backend must be either a string or a subclass of ``Plot``.")
```

**Comment by Davide-sd** [comment]
> Is it possible to avoid __new__ by defining a function?

I suppose it can be done. Just pushed a new commit, let's see what happens.

**Comment by sylee957** [comment]
I think that the previous `__new__` could defer to the factory and raise some deprecation warnings.
Maybe only `Plot` needs `__new__` and other subclasses doesn't need that.
However, since there are structural changes here, it may be optional if we can't do that.

**Comment by Davide-sd** [comment]
If you place a `__new__` into the base class `Plot`, you have to place a `__new__` also on subclasses, otherwise you end up with infinite recursion when creating a new instance of a subclass. It's either `__new__` everywhere, or no `__new__` at all.

**Comment by sylee957** [comment]
Maybe that can be guarded by `cls == Plot` statement in the `Plot.__new__ `

**Comment by Davide-sd** [comment]
Than you would remove `MatplotlibBackend` and `TextBackend` from the method of `Plot.__new__`, making it superfluous.

**Comment by Davide-sd** [comment]
bump.

**Comment by oscarbenjamin** [comment]
> bump.

Can you summarise what exactly you are waiting for? The PR cannot be merged because it has merge conflicts. Is there something else needed?

**Comment by sylee957** [comment]
See https://github.com/sympy/sympy/issues/25185

**Comment by Davide-sd** [comment]
Aside from that, is there anything else stopping this from getting merged?

**Comment by sylee957** [comment]
It is not possible to merge any PRs at the moment because of the issues of tests

**Comment by Davide-sd** [comment]
@sylee957 can you re-run the checks?

**Comment by Davide-sd** [comment]
this can be merged if there are no objection!

**Pull request merged**
