### PR TITLE
issue #7858 : Raised NotImplementedError when m dont have any primitiv root

### LINKED ISSUE #7858: Nth root mod giving wrong solutions
`nthroot_mod(9, 12, 36)` gives that there are no solutions, but 9 is a solution to `x ^ 12 = 9 mod 36`

### PR DESCRIPTION
**Pull request by rd13123013**
Fixed #7858

### CODE REVIEW

**Comment by smichr** [comment]
What happens without this check? In sympy.live it fails for other reasons (at that's the only option I have now to test this).

**Comment by rd13123013** [comment]
@smichr  ``is_nthpow_residue(a, n, m)`` shows wrong output when m do not have a primitive root , currently it is only implemented for m which have primitive roots. cases mentioned in #7858

**Comment by smichr** [comment]
OK. Then let's commit this as is and stop returning the wrong result.

**Comment by smichr** [comment]
Perhaps you would like to open a new issue indicating that cases where m does not have a primitive root *can* be solved. (At least that is how I understood your comments in the issue).

**Pull request merged**
