### PR TITLE
Adding support for Si(x) in lambdify() via SciPyPrinter

### LINKED ISSUE #24175: Bug on lambdify(): unable to plot Si(x)
Code:
```python
from sympy import *
import numpy as np
import matplotlib.pyplot as pyplot

x = symbols('x')
y = sin(x) / x

Y = integrate(y, x)
Y_func = lambdify(x, Y)

x_dots = np.linspace(0, 10, 100)
Y_dots = Y_func(x_dots)
pyplot.plot(x_dots, Y_dots)
pyplot.show()
```

Also not able to calculate a single value from the lambdified function:
```python
Y_func(1)
```

Issue: both local and live.sympy.org will give this error:
```python
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [54], line 12
      9 Y_func = lambdify(x, Y)
     11 x_dots = np.linspace(0, 10, 100)
---> 12 Y_dots = Y_func(x_dots)
     13 pyplot.plot(x_dots, Y_dots)
     14 pyplot.show()

File <lambdifygenerated-30>:2, in _lambdifygenerated(x)
      1 def _lambdifygenerated(x):
----> 2     return Si(x)

NameError: name 'Si' is not defined
```

### PR DESCRIPTION
**Pull request by sayan9800**
#### References to other Issues or PRs
Fixes #24175 
#24568 

#### Brief description of what is fixed or changed
Added print method for `Si` and `Ci` in `SciPyPrinter`

#### Other comments
Method name - `_print_Si` and `_print_Ci`

#### Release Notes

* printing
  * Added support for Si(x) and Ci(x) for using lambdify()

### CODE REVIEW

**Comment by bjodah** [comment]
@sayan9800 would you mind adding tests for this? (it's our policy to cover all code with tests whenever feasible)

perhaps you can create a duplicate of this line:
https://github.com/sympy/sympy/blob/c25ecf0ef7c63ec8b9cb416544a682c758fcc5f2/sympy/printing/tests/test_numpy.py#L348

and adapt for changes in this PR?

and then we should also test that `lambdify` actually can make use of this now, for that we add relevant tests here:
https://github.com/sympy/sympy/blob/c25ecf0ef7c63ec8b9cb416544a682c758fcc5f2/sympy/utilities/tests/test_lambdify.py#L1093

to run the tests you can for example do this:
```shell-session
$ cd /path/to/your/local/repo/of/sympy/
$ python3 -m pytest -ra sympy/utilities/tests/test_lambdify.py sympy/printing/tests/test_numpy.py
```

**Comment by sayan9800** [comment]
@bjodah, thank you for the references, I have added the tests in both the places (test_numpy.py and test_lambdify.py).

**Comment by bjodah** [comment]
@sayan9800 you're on the right track (but not quite there yet). I think I see a problem with the current tests of lambdify: try to use lambdify on an expression which contains one of these functions (and use `.evalf` to compute a reference value), and then try to use the callable object returned from `lambdify` to compute the corresponding (double precision floating point) value and compare these to make sure the results agree to ~1e-14 relative tolerance or so.

Do you encounter any problems doing so?

**Comment by sayan9800** [comment]
@bjodah, I don't think I fully understood the issue here. I have used  `.evalf` and the callable object returned by `lambdify` and they both seem to agree within ~1e-16. I understand that there will be a difference in floating point and double precision float, but the round off error seems to be negligible. Do you want me to explicitly typecast?
Kindly help me understand, thanks.

**Comment by bjodah** [comment]
@sayan9800 I'm sorry. I was mistaken. I checkout your branch locally and things do look good. Sorry about that. Let me take another look to see if there's anything else I can think of.

**Review by bjodah — APPROVED** [review]

**Comment by bjodah** [comment]
Looks great! Once again, sorry if I sent you on a wild-goose chase.

**Comment by sayan9800** [comment]
@bjodah Awesome! Thanks a lot for all the help.

**Pull request merged**
