### PR TITLE
Test pypy3 instead of pypy2 on Travis

### LINKED ISSUE #17050: Switch to pypy3 in Travis
In preparation for dropping Python 2 support later this year, we should migrate our PyPy support from PyPy2 to PyPy3. This basically means switching to testing PyPy3 in Travis.

### PR DESCRIPTION
**Pull request by asmeurer**
I'm hoping just replacing "pypy" with "pypy3" will do it.

Fixes #17050 (if it works)

#### Release Notes

- other
  - PyPy 3 is now tested and supported.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
```
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/14.04/x86_64/pypy3.tar.bz2
0.50s$ curl -sSf -o pypy3.tar.bz2 ${archive_url}
4.40s$ sudo tar xjf pypy3.tar.bz2 --directory /
Adding APT Sources
Disallowing sources: pypy3
To add unlisted APT sources, follow instructions in https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon
5.66s$ travis_apt_get_update
Installing APT Packages
0.35s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install pypy3
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package pypy3
apt-get.diagnostics
apt-get install failed
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install pypy3" failed and exited with 100 during .
```
I'm not sure why pypy3 is disallowed.

There are some precompiled binaries that can be dowloaded or Ubuntu PPAs listed here:
https://pypy.org/download.html

**Comment by asmeurer** [comment]
Going to try `pypy3.5` as suggested here https://travis-ci.community/t/confusing-pypy-versions/2505

**Comment by asmeurer** [comment]
Actually according to https://docs.travis-ci.com/user/languages/python/#pypy-support it should be supported directly. So maybe we just need to remove the apt installs.

**Comment by asmeurer** [comment]
Oh I think my original thing was right, I just need to change the package, but not the apt source (which is already the ppa @oscarbenjamin mentioned).

**Comment by asmeurer** [comment]
Yeah that works. Unless pypy3 has some unexpected test failures this should be ready to go once Travis finishes.

**Comment by asmeurer** [comment]
Looks like there are some test failures.

**Comment by oscarbenjamin** [comment]
One of the problems is an unnecessary `__init__` method in `VectorMul` and `VectorAdd`. This leads to:
```console
$ cat t.py 
from sympy import *
from sympy.vector.vector import VectorAdd, VectorMul
from sympy.vector.coordsysrect import CoordSys3D
C = CoordSys3D('C')
from sympy.abc import a, b, c, x, y, z
v1 = a*C.i + b*C.j + c*C.k
$ python t.py 
Traceback (most recent call last):
  File "t.py", line 7, in <module>
    v1 = a*C.i + b*C.j + c*C.k
  File "/Users/enojb/current/sympy/sympy/sympy/core/decorators.py", line 129, in binary_op_wrapper
    return func(self, other)
  File "/Users/enojb/current/sympy/sympy/sympy/vector/basisdependent.py", line 19, in __add__
    return self._add_func(self, other)
TypeError: object.__init__() takes no parameters
```
I've just pushed a commit that removes those `__init__` methods:
```diff
diff --git a/sympy/vector/basisdependent.py b/sympy/vector/basisdependent.py
index 580d37d2a2..0a0d0429d9 100644
--- a/sympy/vector/basisdependent.py
+++ b/sympy/vector/basisdependent.py
@@ -221,8 +221,6 @@ def __new__(cls, *args, **options):
 
         return obj
 
-    __init__ = Add.__init__
-
 
 class BasisDependentMul(BasisDependent, Mul):
     """
@@ -287,8 +285,6 @@ def __new__(cls, *args, **options):
 
         return obj
 
-    __init__ = Mul.__init__
-
     def __str__(self, printer=None):
         measure_str = self._measure_number.__str__()
         if ('(' in measure_str or '-' in measure_str or
```

**Comment by asmeurer** [comment]
Looks like all the tests are passing now.

**Comment by oscarbenjamin** [comment]
Yeah, looks good.

**Pull request merged**
