### PR TITLE
Improve coverage_report.py

### PR DESCRIPTION
**Pull request by sylee957**
#### Brief description of what is fixed or changed

Some refactorings:

1. `optparse` is deprecated, updated to `argparse`

2.  https://github.com/sympy/sympy/blob/967df3b9dc4a5b98a019d18883d72ac14a5955d6/bin/coverage_report.py#L44-L45 is unused

3. https://github.com/sympy/sympy/blob/967df3b9dc4a5b98a019d18883d72ac14a5955d6/bin/coverage_report.py#L65-L69 can be refactored with `path_hack()`

4. https://github.com/sympy/sympy/blob/967df3b9dc4a5b98a019d18883d72ac14a5955d6/bin/coverage_report.py#L82-L84 can be redundant check

5. https://github.com/sympy/sympy/blob/967df3b9dc4a5b98a019d18883d72ac14a5955d6/bin/coverage_report.py#L117-L118 was hardcoded, so it had given same information even if `report-dir` is specified else.

Some changes and fixes:

1. I had made the changes to how it handles `source_dir`. I think this module can support commands as much as `bin/test` can do.
It had previously taken the first argument and discarded all others
https://github.com/sympy/sympy/blob/967df3b9dc4a5b98a019d18883d72ac14a5955d6/bin/coverage_report.py#L109-L110
but now I made changes to properly handle multiple arguments like
`python bin/coverage_report.py algebras strategies`.

2. https://github.com/sympy/sympy/blob/967df3b9dc4a5b98a019d18883d72ac14a5955d6/bin/coverage_report.py#L87
I think there is a bug here for giving `PermissionError` for my system.
I have made it under exception catching statement, because I think that the HTML report can be generated regardless of `.save()` succeeding or failing.
Do anyone else experiencing similar issue for this?

3. There was a bug for deleting some html reports, after subsequently calling coverage report for the same test.
If you run `python bin/coverage_report.py sympy/algebras` twice, some html files are gone.
I have commented out this line, which could probably be causing the issue https://github.com/sympy/sympy/blob/967df3b9dc4a5b98a019d18883d72ac14a5955d6/bin/coverage_report.py#L91-L94

4. I have made `source_dir` hardcoded to `sympy/` now, so it may make report generating process more slower as it tracks down every files in sympy. 
I think there should be an improvement for how it handles source folders as well, it may cause false negatives for indicating the proper modules.

Any feedbacks are welcomed.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by smichr** [comment]
> 3\. some html files are gone.

I don't clearly understand the problem. The directory is refreshed so only the up-to-date results are listed. This is done by deleting the files from the old run.

**Comment by smichr** [comment]
Under Windows I can  confirm that those lines that you commented out are not needed. All files are deleted in the call to `coverage`. Furthermore, they wouldn't work as listed since they don't use the full path. So they can be deleted.

BTW: The following (which I tested by putting a file there after the coverage step was done deleting everything) would work *but is not necessary since there is never anything in the director*.
```diff
diff --git a/bin/coverage_report.py b/bin/coverage_report.py
index cf1f5ed..65df853 100755
--- a/bin/coverage_report.py
+++ b/bin/coverage_report.py
@@ -92,10 +92,11 @@ def make_report(

     covered_files = list(generate_covered_files(source_dir))

-    #if report_dir in os.listdir(os.curdir):
-    #    for f in os.listdir(report_dir):
-    #        if f.split('.')[-1] in ['html', 'css', 'js']:
-    #            os.remove(os.path.join(report_dir, f))
+    if report_dir in os.listdir(os.curdir):
+        fpath = os.path.join(os.curdir, report_dir)
+        for f in os.listdir(fpath):
+            if f.split('.')[-1] in ['html', 'css', 'js']:
+                os.remove(os.path.join(fpath, f))

     cov.html_report(morfs=covered_files, directory=report_dir)
```
Otherwise, everything appears to be working as normal with these mods that you made.

**Comment by sylee957** [comment]
I see the reason why `cov.save()` is failing, can be because of this configuration file

https://github.com/sympy/sympy/blob/880985471b4d20e113c704d713ec9e9508764e25/.coveragerc#L11
If it can be used locally, travis related environment variables should be removed

**Comment by sylee957** [comment]
HTML report is incremental.

> HTML reporting is now incremental: a record is kept of the data that produced the HTML reports, and only files whose data has changed will be generated. This should make most HTML reporting faster.

https://coverage.readthedocs.io/en/v4.5.x/changes.html#version-3-5b1-2011-06-05

So, I don't think it is a good idea to touch the files directly

**Comment by sylee957** [comment]
And coverage `3.4` would be too old to support.
I don't think that it would work with contemporary python versions.

**Pull request merged**
