### PR TITLE
.github/workflows/ci-sage.yml: Use ticket #34118

### PR DESCRIPTION
**Pull request by mkoeppe**
#### References to other Issues or PRs

To fix the failing Sage CI as reported in https://groups.google.com/g/sage-devel/c/fOTkNoU02Oo

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Thanks. I think I just got used to the idea that the Sage CI would always be red. I'm not sure if I've actually seen it go green yet (maybe briefly after the SymPy 1.10 release...).

**Comment by oscarbenjamin** [comment]
It looks to be running now but I still see one example of the same warning:
```
[sage_docbuild-9.7.beta3] successfully installed.
make[2]: Leaving directory '/sage/build/make'
real	136m5.584s
user	252m11.719s
sys	16m30.287s
Sage build/upgrade complete!
make[1]: Leaving directory '/sage'
make -j8 all-start
make[1]: Entering directory '/sage'
make -j8 build/make/Makefile --stop
make[2]: Entering directory '/sage'
make[2]: warning: -j8 forced in submake: resetting jobserver mode.
```
https://github.com/sympy/sympy/runs/7205831917?check_suite_focus=true

**Comment by mkoeppe** [comment]
That warning is harmless; what I fixed is an infinite Makefile recursion

**Comment by mkoeppe** [comment]
The plotting failure is unrelated to changes in sympy. It happens for some random seeds

**Comment by oscarbenjamin** [comment]
> It happens for some random seeds

I guess that test should be disabled or prevented from reporting a failure somehow.

**Comment by oscarbenjamin** [comment]
For something like the `rsolve` tests what workflow can we use to address the problem so that it is fixed and then shows as fixed rather than showing is failing most of the time?

**Comment by mkoeppe** [comment]
We would push updates to the doctests to the target ticket https://trac.sagemath.org/ticket/34118 as preparation for the upgrade to sympy 1.11.

**Comment by mkoeppe** [comment]
> > It happens for some random seeds
> 
> I guess that test should be disabled or prevented from reporting a failure somehow.

It would probably make sense and suffice to fix the random seed for the tests in sympy's CI

**Comment by mkoeppe** [comment]
That's now #23735 (untested)

**Comment by oscarbenjamin** [comment]
After merging #23735 on the first run at least the plotting fail has gone.

> We would push updates to the doctests to the target ticket https://trac.sagemath.org/ticket/34118 as preparation for the upgrade to sympy 1.11.

Is that something that I can do or is it something that you would need to do?

It would be good to get the sympy/sage CI green as we approach the release of 1.11. I'm trying to clean up CI and test failures and warnings before making a release branch.

**Comment by mkoeppe** [comment]
> > We would push updates to the doctests to the target ticket https://trac.sagemath.org/ticket/34118 as preparation for the upgrade to sympy 1.11.
> 
> Is that something that I can do or is it something that you would need to do?

Yes, commits to https://trac.sagemath.org/ticket/34118 are welcome!
See https://doc.sagemath.org/html/en/developer/trac.html

**Comment by mkoeppe** [comment]
> So I pushed a commit to the sage ticket and now the ubuntu tests run fine.

Great, thanks.

>  The archlinux job fails with what looks like an unrelated problem.

I've opened #23767 for this

**Pull request merged**
