### PR TITLE
modify powsimp to handle square roots

### PR DESCRIPTION
**Pull request by arun-y99**
#### References to other Issues or PRs

Addresses issue #17634 

#### Brief description of what is fixed or changed
Following the discussion in #17634 the changes were done
Before, `powsimp (sqrt(1-x**2)/sqrt(1-x))` would yield `sqrt(1-x**2)/sqrt(1-x)`
Now it yields `sqrt((1-x**2)/(1-x))`
#### Other comments
Added tests

#### Release Notes

* simplify
    * modified powsimp to better handle square roots

### CODE REVIEW

**Comment by arun-y99** [comment]
@oscarbenjamin The addition suggested seems to change the behavior of simplify in other places

For example
`(csch(acsch(I*sqrt(2 - 2/sqrt(5)))) / (I*sqrt(2 - 2/sqrt(5)))).simplify()` should be `1` but now it is
```
In [3]: simplify(csch(acsch(I*sqrt(2 - 2/sqrt(5)))) / (I*sqrt(2 - 2/sqrt(5))))  
Out[3]: 2*sqrt(5)/(sqrt(5 - sqrt(5))*sqrt(sqrt(5) + 5))
```

**Comment by oscarbenjamin** [comment]
It seems that with this PR powsimp fails for `1/e` here:
```julia
In [7]: e = sqrt(5-sqrt(5))*sqrt(5+sqrt(5))                                                                                                    

In [8]: powsimp(e)                                                                                                                             
Out[8]: 2⋅√5

In [9]: 1/e                                                                                                                                    
Out[9]: 
          1          
─────────────────────
  ________   ________
╲╱ 5 - √5 ⋅╲╱ √5 + 5 

In [10]: powsimp(1/e)                                                                                                                          
Out[10]: 
          1          
─────────────────────
  ________   ________
╲╱ 5 - √5 ⋅╲╱ √5 + 5 
```
We can fix that with:
```diff
diff --git a/sympy/simplify/powsimp.py b/sympy/simplify/powsimp.py
index e0208e17a5..ff4c57f2dd 100644
--- a/sympy/simplify/powsimp.py
+++ b/sympy/simplify/powsimp.py
@@ -471,6 +471,8 @@ def _terms(e):
                         return sum([_terms(ai) for ai in e.args])
                     if e.is_Mul:
                         return prod([_terms(mi) for mi in e.args])
+                    if e.is_Pow:
+                        return _terms(e.base)
                     return 1
                 xnew_base = expand_mul(new_base, deep=False)
                 if len(Add.make_args(xnew_base)) < _terms(new_base):
```
This happens because when we get to `_terms` the expression is a `Pow` rather than an `Add` or a `Mul` and `_terms` doesn't try to handle that case.

I'm not sure if this is the right approach (maybe we shouldn't have a `Pow` here) but the additional diff above seems to work for these cases:
```julia
In [2]: powsimp(1/e)                                                                                                                           
Out[2]: 
√5
──
10

In [3]: simplify(csch(acsch(I*sqrt(2 - 2/sqrt(5)))) / (I*sqrt(2 - 2/sqrt(5))))                                                                 
Out[3]: 1
```

**Comment by arun-y99** [comment]
@oscarbenjamin Also, 
Before,
<pre><font color="#008700">In [</font><font color="#8AE234"><b>18</b></font><font color="#008700">]: </font>e                                                                                                                                                           
<font color="#870000">Out[</font><font color="#EF2929"><b>18</b></font><font color="#870000">]: </font>(-8*I - 2*I*(-2 + (1 + I)**2))/(4*(1 + I)**2)

<font color="#008700">In [</font><font color="#8AE234"><b>19</b></font><font color="#008700">]: </font>simplify(e)                                                                                                                                                 
<font color="#870000">Out[</font><font color="#EF2929"><b>19</b></font><font color="#870000">]: </font>I*(-1 + I)/2
</pre>

Now,
<pre><font color="#008700">In [</font><font color="#8AE234"><b>40</b></font><font color="#008700">]: </font>e                                                                                                                                                           
<font color="#870000">Out[</font><font color="#EF2929"><b>40</b></font><font color="#870000">]: </font>(-8*I - 2*I*(-2 + (1 + I)**2))/(4*(1 + I)**2)

<font color="#008700">In [</font><font color="#8AE234"><b>41</b></font><font color="#008700">]: </font>simplify(e)                                                                                                                                                 
<font color="#870000">Out[</font><font color="#EF2929"><b>41</b></font><font color="#870000">]: </font>-1/2 - I/2
</pre>

Is this better or undesirable?

**Comment by oscarbenjamin** [comment]
> Is this better or undesirable?

I think it's better

**Comment by oscarbenjamin** [comment]
There are some other test failures. Feel free to ask for help if you're not sure what to do with them...

**Comment by espatatis** [comment]
Can I help with the issue ?

**Comment by arun-y99** [comment]
@espatatis You can work on this if you want.

**Comment by meganly** [comment]
@oscarbenjamin 

> I'm not sure if this is the right approach (maybe we shouldn't have a `Pow` here) but the additional diff above seems to work for these cases:
> 
> ```julia
> In [2]: powsimp(1/e)                                                                                                                           
> Out[2]: 
> √5
> ──
> 10
> ```

I'm also not sure this is the right approach since it doesn't work in this case:

```julia
 In [2]: powsimp(1/e, force=True)                                                                                                                           
 Out[2]: 1/(sqrt(5 - sqrt(5))*sqrt(sqrt(5) + 5))
```
It seems the issue is that powsimp combines the square roots, but autosimplifcation pulls them apart again.

**Comment by oscarbenjamin** [comment]
@meganly I guess you mean like the first example here:
```julia
In [11]: sqrt((5 - sqrt(5))*(sqrt(5)+5))                                                                                                       
Out[11]: 
  ________   ________
╲╱ 5 - √5 ⋅╲╱ √5 + 5 

In [12]: sqrt((5 - sqrt(x))*(sqrt(x)+5))                                                                                                       
Out[12]: 
  ___________________
╲╱ (5 - √x)⋅(√x + 5)
```
We should really disable that kind of autoevaluation...

**Comment by meganly** [comment]
Correct.  If you substitute x=5 in the second example, the output will be the same as the first example.

The first [commit](https://github.com/sympy/sympy/pull/17666/commits/12289d3f1e3440fdb6aa00ecb520c4d2f955d20e) gets powsimp to combine `1/(sqrt(5 - sqrt(5))*sqrt(sqrt(5)+5))` as `1/sqrt((5 - sqrt(5))*(sqrt(5)+5))` but then autosimplifcation undoes it.
 
> We should really disable that kind of autoevaluation...

Yes, I'm working on it but struggling a bit.

**Comment by meganly** [comment]
Disabling autosimplification causes an overwhelming amount of tests to fail so this PR seems like a good place to start and then we can iterate.

Any ideas why [this](https://github.com/sympy/sympy/blob/master/sympy/geometry/tests/test_line.py#L384) fails? I think it has to do with the fact that Sympy can't simplify `(sqrt(m**2+2*m+1)-abs(m+1)).equals(0)`

**Comment by oscarbenjamin** [comment]
> Disabling autosimplification causes an overwhelming amount of tests to fail so this PR seems like a good place to start and then we can iterate.

Disabling auto-simplification is one of the hardest changes you can make in SymPy because the simplification will be depended on in all of the rest of the codebase.

> Any ideas why [this](https://github.com/sympy/sympy/blob/master/sympy/geometry/tests/test_line.py#L384) fails? I think it has to do with the fact that Sympy can't simplify `(sqrt(m**2+2*m+1)-abs(m+1)).equals(0)`

Yes it comes down to this:
```python
from sympy import *

m = Symbol('m', real=True)
expr = sqrt((3 - (3*m**2 + 2*m + 5)/(m**2 + 1))**2 + (-(2 - 2*m)/(m**2 + 1) + 2)**2) - 2*Abs(m + 1)/sqrt(m**2 + 1)

print(simplify(expr))
```
On master this expression simplifies to zero but that fails under this PR.

**Comment by meganly** [comment]
> ```python
> from sympy import *
> 
> m = Symbol('m', real=True)
> expr = sqrt((3 - (3*m**2 + 2*m + 5)/(m**2 + 1))**2 + (-(2 - 2*m)/(m**2 + 1) + 2)**2) - 2*Abs(m + 1)/sqrt(m**2 + 1)
> 
> print(simplify(expr))
> ```
> 
> On master this expression simplifies to zero but that fails under this PR.

How would I go about fixing this?  On this branch it simplifies to 
```python
2*(-m**2 + sqrt(m**4 + 2*m**2 + 1) - 1)*Abs(m + 1)/(m**2 + 1)**(3/2)
```
If the expression inside the square root were factored, it would simplify to 0.

**Comment by oscarbenjamin** [comment]
> If the expression inside the square root were factored, it would simplify to 0.

You can factor it with `factor(expr, deep=True)`. I don't know whether it makes sense to add that somewhere.

These two lines are the one that simplify the expression on master:
https://github.com/sympy/sympy/blob/3f687d2f8bb2657c8ab04a65eb12ea895a3304dc/sympy/simplify/simplify.py#L599-L600

We should check what goes into and comes out of `powsimp` there to see if it is correct or not.

**Comment by czgdp1807** [comment]
@arun-y99 Any updates?

**Comment by arun-y99** [comment]
@czgdp1807 No sorry

**Pull request closed without merging**
