### PR TITLE
Issue #6405 : Class Complex Declared [WIP]

### PR DESCRIPTION
**Pull request by darkcoderrises**
We needed a set to represent the complex numbers and regions in the complex plane. We needed the equivalent of Interval for C. So I created a class Complex which returns two Real Number in the form of ImageSet(x+I*y)

Printers for class complex have not been written yet.

@hargup Please review and suggest

### CODE REVIEW

**Comment by aktech** [comment]
It looks there is inconsistent use of tabs and spaces in indentation.

**Comment by darkcoderrises** [comment]
@aktech The problem was that my editor showed me that they were same indented.Can you suggest me something?

**Comment by jcrist** [comment]
They're at the same indentation *level*, but they use a mix of tabs and spaces. Python doesn't allow this, and SymPy uses only spaces as a convention. There is usually a configuration in your editor to automatically use 4 spaces for tabs. You can google how to do this yourself.

Because of the mix of tabs and spaces, it's clear that the tests were never run on your machine, as this would never have loaded. Please read [this](https://github.com/sympy/sympy/wiki/Development-workflow)

**Comment by darkcoderrises** [comment]
@jcrist i was able to run ./bin/isympy so i sent the request.Sorry for not following the protocol

**Comment by jksuom** [comment]
I was also able to run bin/isympy but testing elements failed.
```
In [2]: from sympy.sets.fancysets import Complex

In [3]: C = Complex()

In [7]: 1 + I in C
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/jks/test/sympy/<ipython-input-7-1c1d32c4841c> in <module>()
----> 1 1 + I in C

/home/jks/test/sympy/sympy/sets/sets.py in __contains__(self, other)
    497 
    498     def __contains__(self, other):
--> 499         symb = self.contains(other)
    500         if symb not in (true, false):
    501             raise TypeError('contains did not evaluate to a bool: %r' % symb)

/home/jks/test/sympy/sympy/sets/sets.py in contains(self, other)
    266         """
    267         other = sympify(other, strict=True)
--> 268         ret = self._contains(other)
    269         if ret is None:
    270             if all(Eq(i, other) == False for i in self):

/home/jks/test/sympy/sympy/sets/fancysets.py in _contains(self, other)
    227         L = self.lamda
    228         if self._is_multivariate():
--> 229             solns = solve([expr - val for val, expr in zip(other, L.expr)],
    230                     L.variables)
    231         else:

TypeError: zip argument #1 must support iteration
```

**Comment by jcrist** [comment]
In Python 2 mixed tabs and spaces will be replaced by the closest multiple of 8 spaces, starting from left to right. In Python 3, this will error. You must be running Python 2, in Python 3, SymPy wouldn't even load. In general, one should only use spaces for Python. See [PEP 8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces).

**Comment by darkcoderrises** [comment]
@jcrist So do i send a commit again and then send a pull request or can i repair this?

**Comment by jcrist** [comment]
Well, if you read the [development workflow](https://github.com/sympy/sympy/wiki/Development-workflow), you'll see that the recommended process is:

1. Create a separate branch
2. Write the new code, and *add tests for it*
3. Run `./bin/test` to test your code. `./bin/test quality` will test your code quality (catch things like mixed spaces and tabs)
4. Send a PR.

Note that you can put up a PR before it's done if you want some help on it. This is very helpful when starting out.

As you created this on your `master` branch, your workflow is going to be impeded. Generally this is a bad idea, as you can't branch off master to work on other issues. Either way, it's generally acceptable to push many commits to a PR (don't force push!), and then squash them after everything works. We can always cleanup history later before merging.

**Comment by darkcoderrises** [comment]
I re-forked the code then doing every thing again. Is that acceptable?

**Comment by aktech** [comment]
> I re-forked the code then doing every thing again. Is that acceptable?

Since you have deleted your old  fork (as the branch says 'unknown repository'), you can close this PR and make a new PR with a new branch and this time do follow the Development workflow as suggested by jcrist.

**Pull request closed without merging**
