### PR TITLE
Enable PLR1736 useless enumerate check

### PR DESCRIPTION
**Pull request by Skylion007**
#### Brief description of what is fixed or changed
* Adds a new ruff lint that checks for useless index accesses 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Review by haru-44 — APPROVED** [review]

**Comment by oscarbenjamin** [comment]
In principle I like this rule but it seems to present an equals numbers of false positives and true positives.

**Comment by haru-44** [comment]
Does a false positive refer to cases where `# noqa` is added? If you have concerns, I think it’s okay not to add `PLR1736` to `pyproject.toml`.

**Comment by oscarbenjamin** [comment]
> Does a false positive refer to cases where `# noqa` is added?

Yes. I assume that @Skylion007 checked those cases and discovered that they cannot be changed in the way that the rule suggests. That means that if the rule flags up those cases then it is reporting a false positive.

**Comment by Skylion007** [comment]
One is that it triggers in assert (which is useless but checking the operator in the assert) not really a full false positive. 

The other was a really weird issue that was causing a test failure, that's the only real false positive so I left it as is.

**Pull request merged**
