### PR TITLE
sympy.vector .del print changed to .delop as it is accesed

### PR DESCRIPTION
**Pull request by SilentFlame**
pull request for Issue:
sympy.vector del prints as .del but is accessed as .delop
#10045

### CODE REVIEW

**Comment by asmeurer** [comment]
Did you check if any tests need to be changed?

**Comment by SpeedyiiiTH** [comment]
As I checked in the test file present inside vector directory and found there is no test yet regarding the .delop function.

**Comment by asmeurer** [comment]
The test failure is an unrelated PyPy issue (unfortunately, PyPy has had a lot of issues lately).

**Comment by asmeurer** [comment]
I also don't see any printing tests for the vector module (which is unfortunate).

**Comment by moorepants** [comment]
I don't even recall that we implemented printing for the vector module.

**Comment by asmeurer** [comment]
Apparently it is just `__str__` defined on Del. It would be nice to have pretty printing for the vector module.

**Comment by moorepants** [comment]
https://github.com/sympy/sympy/issues/10070

**Pull request merged**
