### PR TITLE
Fixes the old version of KanesMethod.linearize()

### PR DESCRIPTION
**Pull request by moorepants**
Fixes issue #8244.

I added a test that ensures that the old linearizer works and that the new
linearizer gives the same results. I fixed the the old linearizer by updating
the statements that used variables that used to be lists and are now matrices.

### CODE REVIEW

**Comment by moorepants** [comment]
In an ideal world we'd release a hotfix patch to 0.7.6 for this, because currently 0.7.6 fails on older code because this wasn't deprecated properly. It's been causing me headaches in lots of my code.

@asmeurer @jcrist @certik Do you think this warrants a hotfix, and if so could it go out before SciPy?

Are there any other bug fixes that should be applied to 0.7.6?

**Comment by moorepants** [comment]
Is it possible to have tests that issue warnings pass?

**Comment by toolforger** [comment]
> Is it possible to have tests that issue warnings pass?

The test harness explicitly turns warnings into failures at some point IIRC.
It should be possible to undo that from within the test (make sure that 
this is re-enabled using a context manager or a try-finally block).

More ideally, the old tests should be fixed to no more issue warnings; 
they're using an old interface that's been superseded (and I guess 
nobody noticed because the test is extremely slow and nobody let it run 
to completion, ever - and those who do have wasted so much time waiting 
for it that they don't want to waste more time fixing it).

**Comment by moorepants** [comment]
@jcrist Can you review this?

**Comment by jcrist** [comment]
Looks good to me.

**Pull request merged**
