### PR TITLE
Fixed the error in residue computation and added test

### LINKED ISSUE #21176: Incorrect residue of `x**2*cot(pi*x)/(x**4 + 1)`
```
x = Symbol('x')
residue(x**2*cot(pi*x)/(x**4 + 1), x, -sqrt(2)/2 - sqrt(2)*I/2)
```
~Gives `AttributeError: 'int' object has no attribute 'removeO'`~
Now it gives wrong result

### PR DESCRIPTION
**Pull request by akshanshbhatt**
#### References to other Issues or PRs

Fixes #21176

#### Brief description of what is fixed or changed
Changed the assignment value of variable `res` in `_eval_nseries()` in mul.py because the attribute `removeO()` is only there for sympyfied expressions. `res = 0` assigned the integer equivalent of `0` in python to `res`, to which `removeO()` could not be applied. Also, code credits to @oscarbenjamin .

#### Other comments
Also updated the test file.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by jksuom** [comment]
`res` probably means 'result', not 'residue'.

**Comment by akshanshbhatt** [comment]
> `res` probably means 'result', not 'residue'.

Yes, I know that. I have nowhere mentioned that `res` refers to residue. The residue in the title is in reference to the issue with which this PR is linked to. I am aware of the fact that `mul.py` is a core module file so it has nothing to do with residue which is a series module specific term.

**Comment by oscarbenjamin** [comment]
@akshanshbhatt I'm updating the AUTHORS file in #21188. Your commits are recorded as:
```
akshanshbhatt <53227127+akshanshbhatt@users.noreply.github.com>
```
Usually an entry there would show your full name and email address. I'm guessing that "akshanshbhatt" is not your full name. How should I record your name in the AUTHORS file?

**Comment by akshanshbhatt** [comment]
>  How should I record your name in the AUTHORS file?

My name is Akshansh Bhatt. Is the github noreply email fine or should I provide my personal email?

**Comment by oscarbenjamin** [comment]
You don't have to provide an email. I've gone with the one you suggested in #21188

**Pull request merged**
