### PR TITLE
Simplifies Expectation, Variance and Covariance in symbolic_probability

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References to other Issues or PRs
#15610

#### Brief description of what is fixed or changed
The methods, _eval_rewrite_as_Integral and _eval_rewrite_as_Sum in
Expectation, Variance and Covariance are now decoupled, by using alias
of similar methods.

#### Release Notes

* stats
   * Expectation, Variance and Covariance are now decoupled, by using alias of similar methods.

### CODE REVIEW

**Comment by czgdp1807** [comment]
Actually this PR is a continuation of #15610 . I discussed with @Upabjojr in the gitter chatroom of sympy and made that PR. I made both of the PRs with the aim of improving the design a little bit. This will not affect the `stats` module in a negative way. :-)
I was using `self._condition` to maintain similarity with `_eval_rewrite_as_Integral`. Just to maintain consistency.

**Comment by czgdp1807** [comment]
@oscarbenjamin This PR maybe, doesn't need tests, since, it was just an enhancement. It won't change the outputs in any case. Though if still tests are needed, I will think of some.
@Upabjojr Please review this.

**Comment by oscargus** [comment]
Wouldn't it be easier to just use: `_eval_rewrite_as_Sum = _eval_rewrite_as_Integral`?

**Comment by czgdp1807** [comment]
Thanks for the suggestion.
I will get back to you after experimenting with your approach.

**Comment by czgdp1807** [comment]
@oscargus Please check the changes I have made.

**Comment by czgdp1807** [comment]
@oscargus @jksuom Any views on this PR?

**Comment by Upabjojr** [comment]
We need some tests.

**Comment by Upabjojr** [comment]
Oh, this PR adds pre-computed values to `mgf`, `cf` and `entropy`. We don't need this.

**Comment by Upabjojr** [comment]
The values of those functions need to be computed somehow, I'm -1 on ad-hoc formulas in the stats module.

**Comment by czgdp1807** [comment]
@Upabjojr The purpose of the PR wasn't to add pre-computed values. I will remove that.
Please reopen the PR. I am updating.
Apologies from my side.

**Comment by czgdp1807** [comment]
Please read [this description](https://github.com/sympy/sympy/pull/15632/files#issue-238617697).

**Pull request closed without merging**
