### PR TITLE
Consolidate all warnings.simplefilter calls to sympy.utilities.exceptions

### PR DESCRIPTION
**Pull request by asmeurer**
This is the file where SymPyDeprecationWarning is defined, so the filter will
always be set when that warning is used.

This also changes the warning to once, rather than always, which matches the
default Python warning behavior.

This does cause the SymPyDeprecationWarning to show, which by default it
wouldn't, because Python hides DeprecationWarnings by default.  This is
intentional, as we want our users to know about deprecated behavior.

### CODE REVIEW

**Comment by jcrist** [comment]
I'm a little confused by how warnings work, but I just found that the `lambdify

**Comment by asmeurer** [comment]
I put a print statement in the code and the code that creates the warning is not being called.

**Comment by asmeurer** [comment]
It returns at [this line](https://github.com/sympy/sympy/blob/9242d31f6d31a1d9c3464264a5a6e61eab8acfb8/sympy/utilities/lambdify.py#L394)

**Comment by jcrist** [comment]
Hmmm, at one point this was working fine. Not sure what changed. I'll take a look.

**Comment by jcrist** [comment]
Drat. Looks like it never worked after the rewrite of how the deprecation worked. I thought it was tested after that, but I can't see how it would have ever worked, looking at the commit history. I'll open an issue to discuss how this should proceed. This is my mistake, and will have to be fixed :(

**Pull request merged**
