### PR TITLE
[issue 9969] Bug fixed: intervals are now evaluated in similar cases

### PR DESCRIPTION
**Pull request by kevalds51**

### CODE REVIEW

**Comment by kevalds51** [comment]
It would be great if someone would restart the job (It's a PyPy issue in Travis build)

**Comment by gxyd** [comment]
Also add the corresponding test which is present in the issue.

**Comment by leosartaj** [comment]
You have merge conflicts. Tests will not run until they are resolved.

**Comment by kevalds51** [comment]
Please see PR #9977

**Pull request closed without merging**
