### PR TITLE
Added outputs for plots examples.

### LINKED ISSUE #15327: Add example plot outputs to the Sphinx documentation
We enabled the [matplotlib plot directive](https://matplotlib.org/devel/plot_directive.html) in #15310. This allows us to display plot results in the documentation in a number of ways. The first example is at: https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam_problems.html with the source here: https://github.com/sympy/sympy/blob/master/doc/src/modules/physics/continuum_mechanics/beam_problems.rst.

The `sympy.plot()` command does not have any examples in the documentation of the resulting plots. Many of the docstrings could include these. There are also other modules that make use of `sympy.plot()` or `matpltolib.pyplot.plot()` that could use some sprucing up.

Pull requests that add in plots to relevant portions of the documentation would be helpful.

Potential documentation areas that could use improvement:

- [x] https://docs.sympy.org/dev/modules/plotting.html
- [ ] https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam_problems.html
- [ ] https://docs.sympy.org/dev/modules/geometry/index.html

### PR DESCRIPTION
**Pull request by TroublingStone**
New outputs of plots to Sphinx documentation.
#### References to other Issues or PRs

Fixes #15327 

#### Release Notes

* physics.continuum_mechanics
  * Added plots examples in beam.py

### CODE REVIEW

**Comment by sylee957** [comment]
I don't see any plot examples in pygletplot, but some code formatting changes.
Are you intending to make any PEP-8 cleanup for pyglet module?

**Comment by LilJohny** [comment]
I added part to display plots in Sphinx and changed formatting a bit in pygletplot.

**Comment by moorepants** [comment]
@LilJohny It is helpful if you provide screenshots of the rendered docs so we can see the results.

**Comment by LilJohny** [comment]
@moorepants , ok I`ll provide screenshots.

**Comment by asmeurer** [comment]
I would skip pyglet, at least until https://github.com/sympy/sympy/pull/15772 is merged.

**Comment by LilJohny** [comment]
Hi @moorepants , I have screenshots. Here you are.
Screenshot from 2019-03-31 04-54-33
Screenshot from 2019-03-31 04-54-26
Screenshot from 2019-03-31 04-54-19
Screenshot from 2019-03-31 04-54-08

**Comment by moorepants** [comment]
The plots look good. If tests pass I'm good with it.

**Comment by LilJohny** [comment]
@moorepants Travis tests are passed.

**Comment by LilJohny** [comment]
@sylee957 I removed pyglet modifications.

**Comment by LilJohny** [comment]
@moorepants @sylee957  Can you merge it ?

**Comment by sylee957** [comment]
The failed coverage report is blocking the merge now.
I guess you would have to separate the diff in `sympy/plotting/pygletplot/plot.py` to another PR, and clean from here.

@asmeurer Can you take a look at this?

**Comment by LilJohny** [comment]
@sylee957 @moorepants I removed modification in pygletplot, so it should be ready to merge. Is it ?

**Comment by moorepants** [comment]
I don't know anything about these codecov failures. Until that is addressed I will not merge.

**Comment by LilJohny** [comment]
@moorepants  This test appeared after reopening pull request, so this is comparing this pull request to closed before, so as they are the same, this test is failed. If you want, I can recreate pull request to pass all tests.

**Comment by LilJohny** [comment]
Screenshot from 2019-04-03 14-53-32
@moorepants What can I do with this error if I modified  documentation?

**Comment by LilJohny** [comment]
I can`t test dcoumentation with asserts or something like this.

**Comment by oscarbenjamin** [comment]
Don't worry about the codecov failure. I'm unable to reach codecov right now (the links below aren't working) so I can't see exactly what is causing this.

If codecov was working correctly here then it would recognise that the diff only changes docstrings and whitespace which should not be measured for coverage.

**Comment by LilJohny** [comment]
@oscarbenjamin Can you help me deal with this test? I want to merge.

**Comment by moorepants** [comment]
Merged. Thanks!

**Pull request merged**
