### PR TITLE
Fix HTML rendering of parameters and returns section

### LINKED ISSUE #16585: Sphinx rendering of parameters section changed?
https://docs.sympy.org/latest/modules/discrete.html#sympy.discrete.transforms.fft
https://docs.sympy.org/dev/modules/discrete.html#sympy.discrete.transforms.fft

image

image

I see the indentation changed, and it looks more disorganized in later one

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

Fixes #16585 

#### Brief description of what is fixed or changed

I've concluded that the sphinx field list rendering problem is an upstream problem.
https://github.com/sphinx-doc/sphinx/issues/6604
I also see that many projects are pinning down the sphinx version because of the issue https://github.com/numpy/numpydoc/issues/215

But somehow, I've tried out specifying the CSS theme like below with some basic trials and errors, and at least I can confirm that this works for almost every corners of sympy docs, without having any problem of overflowing or breaking other formats.

Also, I've fixed some bad formats in the cryptography module, so that I can also present how the changes look like.

<details><summary>check_and_join</summary>
<p>

</p>
</details>

<details><summary>decipher_gm</summary>
<p>

</p>
</details>

<details><summary>dh_private_key</summary>
<p>

</p>
</details>

<details><summary>dh_shared_key</summary>
<p>

</p>
</details>

<details><summary>elgamal_private_key</summary>
<p>

</p>
</details>

<details><summary>encipher_affine</summary>
<p>

</p>
</details>

<details><summary>encipher_bifid</summary>
<p>

</p>
</details>

<details><summary>encipher_bifid5</summary>
<p>

</p>
</details>

<details><summary>encipher_bifid6</summary>
<p>

</p>
</details>

<details><summary>encipher_elgamal</summary>
<p>

</p>
</details>

<details><summary>encipher_gm</summary>
<p>

</p>
</details>

<details><summary>encipher_hill</summary>
<p>

</p>
</details>

<details><summary>encipher_shift</summary>
<p>

</p>
</details>

<details><summary>gm_private_key</summary>
<p>

</p>
</details>

<details><summary>gm_public_key</summary>
<p>

</p>
</details>

<details><summary>lfsr_autocorrelation</summary>
<p>

</p>
</details>

<details><summary>lfsr_autocorrelation_polynomial</summary>
<p>

</p>
</details>

<details><summary>lfsr_sequence</summary>
<p>

</p>
</details>

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
The sphinx issue you refer to seems to have been closed. I can't tell if it's actually fixed though

**Comment by sylee957** [comment]
We've got a new build with today's sphinx release

image

But I only see the difference that the extra indentation had fixed

image

So, it looks more better, but what about colors?

**Comment by oscarbenjamin** [comment]
I think this PR is better than the current rendering. The comment indicates that it is a temporary workaround though and refers to a Sphinx issue that is now closed. That should probably be changed.

**Comment by sylee957** [comment]
Whatever, I think that Sphinx had somewhat switched to inheriting `classic.css` than `basic.css` in `default.css` but sympy doc still has the old version.

**Comment by oscarbenjamin** [comment]
Looks good. Merging

**Pull request merged**
