### PR TITLE
Replace the Travis Python 3.8-dev with just 3.8

### PR DESCRIPTION
**Pull request by asmeurer**
Python 3.8 was released earlier this week.

It's possible this won't work yet if Travis doesn't support 3.8 final yet, in which case we should wait to merge this until they do.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I expect that the tests will fail due to #17736. Maybe we can fix that here at the same time.

**Comment by asmeurer** [comment]
Seems to work.

**Comment by oscarbenjamin** [comment]
I guess at some point 3.8 can become the default rather than 3.7 but not yet...

**Comment by asmeurer** [comment]
We can probably do it already for the baseline tests. The optional dependency tests will require conda-forge to catch up, which could be a while.

**Comment by asmeurer** [comment]
The optional dependency build is still using 3.6 even though it doesn't pin a Python version. One of the dependencies must still not have 3.7 support. But it should start using the newer version automatically once it does.

**Comment by asmeurer** [comment]
I just played with it and the problem is with tensorflow. I'm not clear why, because `conda search tensorflow` shows 3.7 packages, but `conda create -n test --dry tensorflow python=3.7` fails. The output from conda isn't very easy to read.

**Comment by asmeurer** [comment]
https://github.com/conda-forge/tensorflow-feedstock/issues/98

**Pull request merged**
