### PR TITLE
added references to array expressions in array docstrings

### PR DESCRIPTION
**Pull request by Upabjojr**
NO ENTRY

### CODE REVIEW

**Comment by Upabjojr** [comment]
> I wonder, do we really want separate functions for symbolic and explicit arrays? Ideally you'd be able to mix and match the two, so shouldn't the same functions be used for both?

They can be mixed already.

**Comment by asmeurer** [comment]
The one that stood out to me specifically was `derive_by_array` and `array_derive`. What is the difference between these? The other ones make sense if they are just referencing the class vs. the function.

**Comment by Upabjojr** [comment]
> The one that stood out to me specifically was `derive_by_array` and `array_derive`. What is the difference between these? The other ones make sense if they are just referencing the class vs. the function.

`derive_by_array` acts on arrays, while `array_derive` only acts on array expressions. None of them is meant to create expressions, even if `array_derive` acts on array expressions only.

**Comment by asmeurer** [comment]
Well that's what I am talking about. Do we really need two separate functions for that? Especially given the functions have very similar names, I don't know how users are expected to remember which is which.

**Comment by Upabjojr** [comment]
> Well that's what I am talking about. Do we really need two separate functions for that? Especially given the functions have very similar names, I don't know how users are expected to remember which is which.

Probably not, the reason we have two functions of that the two algorithms are completely different, so two different implementations were more natural. Plus, the array expressions module was developed later.

**Pull request merged**
