### PR TITLE
deleted unused param "session" from process_split

### PR DESCRIPTION
**Pull request by smellslikekeenspirit**
#### Release Notes

* core
    * removed unused parameter from process_split function

### CODE REVIEW

**Comment by smichr** [comment]
I'm not sure that this change should be made since line 62 calls this using session. On the other hand, both functions were added in 2673cc456d20010f4d6436820e61309f54746742 so maybe it could be deleted from both places. I don't have a lot of experience with the testing files, so I don't have a good sense for how this is used and whether some other testing platform will call these functions. Perhaps @asmeurer , @oscarbenjamin or @oscargus would have some ideas on this.

There will be no controversy for something like #16598, however.

**Comment by oscargus** [comment]
No idea, but I share your analysis regarding line 62. One should probably check if `pytest_collection_modifyitems` is called (the comment, `""" pytest hook. """` seems to indicate that, if nothing else, session should be kept in that method, but not passed on). However, since the tests pass as is, with what seems like valid splits, it seem like maybe `pytest_collection_modifyitems` is not needed at all (and therefore, maybe, just maybe, not `process_split` either).

**Comment by oscarbenjamin** [comment]
git grep reveals that these are the only two places the function is referred to:
```
$ git grep process_split
sympy/conftest.py:def process_split(session, config, items):
sympy/conftest.py:    process_split(session, config, items)
```
So I think it's fine to change it provided it is changed in the call as well as the signature.

Note that in general some files used by pytest can have functions called `pytest_*` that are magic functions picked up by pytest. So even if they are never called in the SymPy code that argument could still be needed, I don't think that's the case here though.

**Comment by smichr** [comment]
So it looks like all that is needed is that the `session` in line 62 be deleted, too.

**Comment by oscarbenjamin** [comment]
Your new commits include unrelated files. Can you remove them please?

**Comment by smellslikekeenspirit** [comment]
Why are the deletions rejected by travis ci?

**Pull request closed without merging**
