### PR TITLE
Add Example 12 and 13 to the documentation

### LINKED ISSUE #27093: continuum_mechanics missing examples for newly added functions
Examples on [this]( https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam_problems.html) page don't have any examples that use ``apply_support()`` or ``apply_rotation_hinge()`` or ``apply_sliding_hinge(loc)``.

### PR DESCRIPTION
**Pull request by BorekSaheli**
#### References to other Issues or PRs

Fixes #27093 

#### Brief description of what is fixed or changed

Added examples 12 and 13 to the documentation of `continuum_mechanics` that demonstrate the use of the newly added functions:

- `apply_support()`
- `apply_rotation_hinge()`
- `apply_sliding_hinge(loc)`

#### Release Notes

- physics.continuum_mechanics
  - Added examples 12 and 13 to the documentation, demonstrating the use of `apply_support()`, `apply_rotation_hinge()`, and `apply_sliding_hinge(loc)`.

### CODE REVIEW

**Comment by moorepants** [comment]
You'll need to add your name to the authors file. There is explanation of how to do so in the documentation.

**Comment by BorekSaheli** [comment]
Seems like I have made some mistakes in the formatting I'll try to run the test on my machine first @moorepants

**Comment by moorepants** [comment]
It is best to check locally first. You can use `bin/doctests path/to/file.rst` to check a specific file.

**Comment by moorepants** [comment]
Also if you click "details" by the red x above you can dig in and find the error message there.

**Comment by BorekSaheli** [comment]
I can't find a way to run a test on the rst files only on py files. I assume if the html build is successful it passes the test here.

**Comment by BorekSaheli** [comment]
How can I run the test for the whitespace detection. The doctest runs with no problems even if there are whitespaces @moorepants

**Comment by moorepants** [comment]
There is a `bin/strip_whitespace` to strip a file, but you should set up your editor to automatically strip trailing whitespace. That's the easiest.

**Comment by moorepants** [comment]
LGTM, thanks!

**Pull request merged**
