### PR TITLE
Added apart to inverse_laplace_transform

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References
[1] https://groups.google.com/d/msg/sympy/UqjtordI3M4/p05zms55AgAJ

#### Brief description of what is fixed or changed
Added partial fraction decomposition to inverse laplace transform. It helps to give the output of the transfer function as shown in link in references.

#### Other comments
I think this `hint` should be added in `doit()` method, since, sometimes ad-hoc techniques are helpful when generic algorithm is unable to produce the output. This makes the code slower but since it is added as an optional parameter, so it will not affect the code in all cases. 
If there is a better way to solve this problem, then please mention in the comments.

#### Release Notes

* integrals
  * apart function added to sympy.stats.integrals.transforms.inverse_laplace_transfrom

### CODE REVIEW

**Comment by czgdp1807** [comment]
@sidhantnagpal Please review this PR.

**Comment by jksuom** [comment]
It is actually inverse Mellin transform that is applied for inverse Laplace transform. I would consider appending `apart(F)` to [this list](https://github.com/sympy/sympy/blob/master/sympy/integrals/transforms.py#L719).

**Comment by czgdp1807** [comment]
Thanks for the suggestion @jksuom. I will do it since, it will be more natural and consistent to have that there.

**Comment by czgdp1807** [comment]
@jksuom I have made the changes. Please review.

**Comment by oscarbenjamin** [comment]
This seems to have many test failures. Check the details link below.

**Comment by jksuom** [comment]
It seems that `apart` may raise `NotImplementedError`. One way to handle that could be using a private version that would catch the error. Maybe something like this:

    def _apart(f):
        try:
            return apart(f)
        except NotImplementedError:
            return f
    for g in [factor(F), expand_mul(F), expand(F), _apart(F)]:
        ...

**Comment by czgdp1807** [comment]
@jksuom We can also use, `apart(F, s)` since, we have to do partial fraction decomposition in terms of only the integration variable.
However, adding `apart` to [that list](https://github.com/sympy/sympy/blob/master/sympy/integrals/transforms.py#L719 ) is not helping. I am unable to understand that why, all the terms are not separately evaluated?

**Comment by czgdp1807** [comment]
Can we add the following logic to `_inverse_laplace_transform` too,
https://github.com/sympy/sympy/blob/e427271c7f9f93eeca92e5a15842840fb6af637e/sympy/integrals/transforms.py#L720_L731

**Comment by czgdp1807** [comment]
@jksuom Please provide your views on [this](https://github.com/sympy/sympy/pull/16383#issuecomment-479801699) comment.

**Comment by jksuom** [comment]
It is possible that `meijerint_inversion` would work better with some of the transformed expressions. Maybe the logic could be applied to all integral transformations in `doit`.

**Comment by sylee957** [comment]
I have other ideas like defining `apart` for integral transforms or integrals, and calling it when a user need. Currently, apart does not do anything for integrals itself.

image

I simply added apart for integral transforms.

```diff
diff --git a/sympy/integrals/transforms.py b/sympy/integrals/transforms.py
index b429e6e28a..c68fe651a5 100644
--- a/sympy/integrals/transforms.py
+++ b/sympy/integrals/transforms.py
@@ -174,6 +174,20 @@ def as_integral(self):
     def _eval_rewrite_as_Integral(self, *args, **kwargs):
         return self.as_integral

+    def apart(self, x=None):
+        from sympy.core.add import Add
+        func, others = self.args[0], self.args[1:]
+
+        func = func.apart(self.function_variable)
+        if isinstance(func, Add):
+            new_args = []
+            for arg in func.args:
+                new = self.func(arg, *others)
+                new_args.append(new)
+            return Add(*new_args)
+        return self
+
+
 from sympy.solvers.inequalities import _solve_inequality
:
```

**Comment by sylee957** [comment]
Since the original issue is closed, are you going to keep this PR open? @czgdp1807

**Comment by czgdp1807** [comment]
Thanks for reminding. Closed.

**Pull request closed without merging**
