### PR TITLE
Simplify "if(res): return True; return False"

### PR DESCRIPTION
**Pull request by MartinThoma**
#### Brief description of what is fixed or changed

The pattern

```
if res:
    return True
return False
```

was simplified to `return bool(res)`

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This is something that has come up in previous attempts at fixing formatting/flake8 etc: I think that the rubi code is automatically generated so there isn't really any point changing it without changing the code that generates it.

**Comment by smichr** [comment]
An advantage of the existing code is that coverage is easier to track: you know if the True and False conditions have been tested.

**Comment by MartinThoma** [comment]
> the rubi code is automatically generated

Ok. Could you point me to the documentation where it is described how the code is auto-generated?

**Comment by MartinThoma** [comment]
Close, as it is auto-generated code

**Comment by oscarbenjamin** [comment]
> Ok. Could you point me to the documentation where it is described how the code is auto-generated?

I don't know how it's generated. Personally I don't think that code should be in the main sympy repo. In any case it is blacklisted by flake8 and mypy.

**Pull request closed without merging**
