### PR TITLE
Edit README.rst and doc/README.rst to include link to style guide

### PR DESCRIPTION
**Pull request by lglattly**
This is to add a link to the new SymPy Documentation Style Guide to the contributing section of the README.rst and to replace the installation instructions on doc/README.rst with a link to the style guide which contains the full instructions.

CC @sympy/gsod

#### References to other Issues or PRs
This is related to #17715

#### Release Notes

- other
  - updated the README.rst and doc/README.rst with links to the SymPy Documentation Style 
    Guide.

### CODE REVIEW

**Comment by asmeurer** [comment]
+1

**Comment by oscarbenjamin** [comment]
It looks like this essentially deletes the doc/README in favour of linking to somewhere online. Is the style guide not included in the code somewhere?

**Comment by lglattly** [comment]
Yes that's correct. I think the idea was that since the doc/README only consisted of the installation instructions, which are now in the style guide that has been merged with documentation, we were looking to remove places where instructions could become out of date in favor of linking to the comprehensive document that contained all of this information that will hopefully stay up to date. But let me know if you have another suggestion for what to do here!

**Comment by asmeurer** [comment]
I guess Oscar's concern is that the README links to a website even though the resources are in a local file. Maybe the doc/README could also mention that the guide can be read at src/documentation-style-guide.rst.

**Comment by lglattly** [comment]
Got it, adding that mention here.

**Comment by oscarbenjamin** [comment]
Yeah that's what I meant , thanks.

This looks good.

**Pull request merged**
