### PR TITLE
Misc new functions to support planned numberfields extension.

### PR DESCRIPTION
**Pull request by skieffer**
#### Release Notes

* polys
  * Hermite normal form
  * Utilities for non-invertible matrices
  * Additions to DomainMatrix: columnspace, rowspace, is_upper, is_lower, is_square, rank
  * Supply setitem method in DDM class
  * IntegerPowerable class: supports powering for classes that define `__mul__`
* matrices
  * Access the Hermite normal form function from polys

### CODE REVIEW

**Comment by sylee957** [comment]
Will this replace https://github.com/sympy/sympy/pull/18534?

**Comment by skieffer** [comment]
Latest commits touch a lot more lines, only because I went ahead with the renaming `DDM*` --> `DM*` of error classes.

**Comment by oscarbenjamin** [comment]
> I think people would look for it under Matrices, not Polys, so, best to put it there, no?

Yes, I think so but we can also leave that for a future PR.

**Comment by oscarbenjamin** [comment]
> Will this replace #18534?

Yes, I think so. The implementation here is more efficient because it is implemented for DomainMatrix over ZZ and Hermite Normal Form is only defined for matrices of integers. It also provides the option to work modulo D which is a significant improvement. Also #18534 is incomplete e.g. it needs more tests.

**Comment by oscarbenjamin** [comment]
TODO comments are very useful if they make sense to other readers of the code. There are a lot in the codebase already. Unfortunately some of them I don't actually understand what they mean: it needs to be more than just a note from the author to themselves!

**Comment by oscarbenjamin** [comment]
This is excellent work. Thanks for the contribution. Merging now.

**Pull request merged**
