### PR TITLE
Build docs on Python3 : Update numpydoc

### LINKED ISSUE #7186: Docs don't build in Python 3
```
The problem is in the numpydoc extension. There's probably a fix for all the issues upstream.

Exception occurred:
  File "/Users/aaronmeurer/anaconda3/lib/python3.3/site-packages/sphinx/application.py", line 247, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "ext/numpydoc.py", line 41
    title_re = re.compile(ur'^\s*[#*=]{4,}\n[a-z0-9 -]+\n[#*=]{4,}\s*',
                                                                     ^
SyntaxError: invalid syntax
The full traceback has been saved in /var/folders/wc/dppcpmxs1tlb36nqcw853wkm0000gq/T/sphinx-err-w1e793.log, if you want to report the issue to the developers.
```
Original issue for #7186: http://code.google.com/p/sympy/issues/detail?id=4087
Original author: https://code.google.com/u/asmeurer@gmail.com/

### PR DESCRIPTION
**Pull request by aktech**
TODO
- [x] Update `numpydoc.py`
- [x] Update `docscrape.py`
- [x] Update `docscrape_sphinx.py`
- [x] Make it work with SymPy
- [x] Fixes #7186 

@asmeurer  @hargup @moorepants @certik

### CODE REVIEW

**Comment by aktech** [comment]
#### Building docs on Python3
```
(python3)amit@amit-UDell:~/Desktop/myrepo/sympy/doc$ make html
Makefile:121: warning: overriding commands for target `_build/cheatsheet/cheatsheet.pdf'
Makefile:116: warning: ignoring old commands for target `_build/cheatsheet/cheatsheet.pdf'
rm -rf _build/logo
mkdir -p _build/logo
python ./generate_logos.py -d
INFO:root: File saved: ./_build/logo/sympy-notail.svg
INFO:root: File saved: ./_build/logo/sympy-notailtext.svg
INFO:root: File saved: ./_build/logo/sympy-notext.svg
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: convert ./_build/logo/sympy-16px.png ./_build/logo/sympy-32px.png ./_build/logo/sympy-48px.png ./_build/logo/sympy-64px.png ./_build/logo/sympy-favicon.ico
DEBUG:root:return code: 0
DEBUG:root:command: convert ./_build/logo/sympy-notail-16px.png ./_build/logo/sympy-notail-32px.png ./_build/logo/sympy-notail-48px.png ./_build/logo/sympy-notail-64px.png ./_build/logo/sympy-notail-favicon.ico
DEBUG:root:return code: 0
DEBUG:root:command: convert ./_build/logo/sympy-notailtext-16px.png ./_build/logo/sympy-notailtext-32px.png ./_build/logo/sympy-notailtext-48px.png ./_build/logo/sympy-notailtext-64px.png ./_build/logo/sympy-notailtext-favicon.ico
DEBUG:root:return code: 0
DEBUG:root:command: convert ./_build/logo/sympy-notext-16px.png ./_build/logo/sympy-notext-32px.png ./_build/logo/sympy-notext-48px.png ./_build/logo/sympy-notext-64px.png ./_build/logo/sympy-notext-favicon.ico
DEBUG:root:return code: 0

Logo generated.
mkdir -p src/.static
mkdir -p _build/html
mkdir -p _build/doctrees
mkdir -p src/modules
PYTHONPATH=..: sphinx-build -b html -d _build/doctrees  src _build/html
Running Sphinx v1.3.1
loading pickled environment... failed: 'str' object has no attribute '__dict__'
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 217 source files that are out of date
updating environment: 217 added, 0 changed, 0 removed
reading sources... [ 39%] modules/physics/mechanics/examples/lin_pend_nonmin_exareading sources... [ 40%] modules/physics/mechanics/examples/rollingdisc_examplereading sources... [ 40%] modules/physics/mechanics/examples/rollingdisc_examplereading sources... [ 41%] modules/physics/mechanics/examples/rollingdisc_examplereading sources... [100%] wiki                                                  
/home/amit/Desktop/myrepo/sympy/sympy/combinatorics/util.py:docstring of sympy.combinatorics.util._base_ordering:21: SEVERE: Unexpected section title or transition.

========
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 39%] modules/physics/mechanics/examples/lin_pend_nonmin_examwriting output... [ 40%] modules/physics/mechanics/examples/rollingdisc_example_writing output... [ 40%] modules/physics/mechanics/examples/rollingdisc_example_writing output... [ 41%] modules/physics/mechanics/examples/rollingdisc_example_writing output... [100%] wiki                                                   
generating indices... genindex py-modindex
highlighting module code... [100%] sympy.geometry.util                          
writing additional pages... search
copying images... [100%] modules/physics/vector/kin_2pt.svg                     
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.
cp -r src/pics _build/html/

Build finished. The HTML pages are in _build/html.
(python3)amit@amit-UDell:~/Desktop/myrepo/sympy/doc$
```

**Comment by moorepants** [comment]
Why not just make numpydoc a dependency instead of being included in SymPy? numpydoc supports 2.6, 2.7 and >= 3.3.

**Comment by aktech** [comment]
> Why not just make numpydoc a dependency instead of being included in SymPy?

Supporting it externally would not work directly. We have some patches to make it work with SymPy.

**Comment by aktech** [comment]
ping @asmeurer

**Comment by asmeurer** [comment]
If it works merge it.

**Comment by aktech** [comment]
It works on my system. @debugger22  can you please test it on your system for both Python 3 & 2.

**Comment by debugger22** [comment]
Works fine.

**Pull request merged**
