### PR TITLE
Fix if statement returning bool

### PR DESCRIPTION
**Pull request by haru-44**
#### Brief description of what is fixed or changed
before
```python
if condition:
    return True
else:
    return False
```
after
```python
return condition
```

Supplementary information on `holonomic.recurrence`.

original
```python
        if self.recurrence == other.recurrence:
            if self.n == other.n:
                if self._have_init_cond and other._have_init_cond:
                    if self.u0 == other.u0:
                        return True
                    else:
                        return False
                else:
                    return True
            else:
                return False
        else:
            return False
```

`self.recurrence == other.recurrence` -> `self.recurrence != other.recurrence`
```python
        if self.recurrence != other.recurrence:
            return False
        if self.n == other.n:
            if self._have_init_cond and other._have_init_cond:
                if self.u0 == other.u0:
                    return True
                else:
                    return False
            else:
                return True
        else:
            return False
```

`self.n == other.n` -> `self.n != other.n`
```python
        if self.recurrence != other.recurrence:
            return False
        if self.n != other.n:
            return False
        if self._have_init_cond and other._have_init_cond:
            if self.u0 == other.u0:
                return True
            else:
                return False
        else:
            return True
```
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by haru-44** [comment]
Maybe the changes in `sympy/solvers/simplex.py` should not have been made together.
The process is to append to `c` when either `lo` or `hi` is not `None`. Before the change, each of the four patterns was processed, but after the change, only two patterns are used.

**Comment by oscarbenjamin** [comment]
> Maybe the changes in `sympy/solvers/simplex.py` should not have been made together.
> The process is to append to `c` when either `lo` or `hi` is not `None`. Before the change, each of the four patterns was processed, but after the change, only two patterns are used.

I don't understand what this means. Is the new code not equivalent?

**Comment by smichr** [comment]
> only two patterns are used.

I confirm that both give the same result as follows:
```python
bounds  = [(None, None), (1, None), (None, 2), (3, 4)]
x=IndexedBase('x')
c=[]
for i, (lo, hi) in enumerate(bounds):
	if lo is None and hi is None:
		continue
	if lo is None:
		c.append(x[i]<=hi)
	elif hi is None:
		c.append(x[i]>=lo)
	else:
		c.append(x[i]>=lo)
		c.append(x[i]<=hi)
c1=c[:]
c=[]
for i, (lo, hi) in enumerate(bounds):
	if lo is not None:
		c.append(x[i]>=lo)
	if hi is not None:
		c.append(x[i]<=hi)
assert c == c1
```

**Comment by smichr** [comment]
> new code not equivalent?

it is, as I indicated above.

**Comment by haru-44** [comment]
Sorry for the confusion.
I thought it might have been better to separate the PRs since the changes are different from the description in the PR. As you say, the code is equivalent before and after the fix.

**Pull request merged**
