### PR TITLE
 Remove unused arguments from contour in plot.py

### PR DESCRIPTION
**Pull request by ylemkimon**
Removed unused arguments, fill and contours, from contour.

I'm not sure why it has `contours` and `fill` arguments in the first place, as it is not documented in matplotlib anywhere. If I remove them, test seems to pass.

See #13355.

Depends on #13405.

### CODE REVIEW

**Comment by gxyd** [comment]
You can link to specific comment on the issue, i.e here https://github.com/sympy/sympy/issues/13355#issuecomment-334653255 .

**Comment by gxyd** [comment]
Merging this. Tests pass. Thanks @ylemkimon @Upabjojr

**Comment by asmeurer** [comment]
Were they supposed to be something else then? Did you test that contour plots still work?

**Comment by ylemkimon** [comment]
@asmeurer Those arguments were never used, but unused kwargs warning was added recently in matplotlib 2.1.0 by https://github.com/matplotlib/matplotlib/commit/96f28243ecd163ff7ce4736dce951b6b62dcf21a, which caused test failures. In my guess, `fill=false` means not-filled contour plot, which is what `contour` does, compared to `contourf`, and `contours=(0, 0)` means contour levels, which is automatically determined to be 0, since `zarray` is consisted of 1 and -1s.

**Pull request merged**
