### PR TITLE
adding ELLIPSIS to doctests

### PR DESCRIPTION
**Pull request by Davide-sd**
#### References to other Issues or PRs

Issue #25477

#### Brief description of what is fixed or changed

After #25117 was implemented and merged, some doctests were not updated. Fixing them to make doctest pass.

#### Other comments

Reason to add ELLIPSIS: prior to #25117, numerical data was added directly to Matplotlib's axis, with no easy way to test if the data was actually there. After that PR, the numerical data has been added to a `GenericDataSeries`. Doctests failed because they detected more data series than when they were written. The continuum mechanics module clearly add many GenericDataSeries (probably to add scatters), which makes the output of doctests very long and tedius, and IMHO, unnecessary to the scope of a documentation, which is informing users about useful stuff and not about testing. Hence, the ellipsis.

#### Release Notes

* physics.continuum_mechanics
  * fixed doctests in `beam.py` and `truss.py`

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Is this a difference somehow between `bin/doctest` and `pytest --doctest-plus`?

**Comment by Davide-sd** [comment]
With gmpy2 installed:

* `bin/doctest` passes everything except a few tests about `sympy.ntheory` module.
* `pytest --doctest-plus`: this is the first time I ever executed this line of code. It is muuuch slower than `bin/doctest`... Tests about the `physics.continuum_mechanics` passes. There are failure on `sympy.ntheory`, `sympy.solvers`, `sympy.integrals`, `sympy.parsing`, `sympy.physics.units` and more...

**Comment by Davide-sd** [comment]
Quick report about `pytest --doctest-plus`:

```text
=============================================== short test summary info ================================================
FAILED sympy/algebras/quaternion.py::sympy.algebras.quaternion.Quaternion._eval_evalf
FAILED sympy/codegen/ast.py::sympy.codegen.ast
FAILED sympy/codegen/ast.py::sympy.codegen.ast.FloatType
FAILED sympy/codegen/ast.py::sympy.codegen.ast.Type
FAILED sympy/codegen/ast.py::sympy.codegen.ast.Type.cast_check
FAILED sympy/core/sympify.py::sympy.core.sympify.sympify
FAILED sympy/functions/combinatorial/numbers.py::sympy.functions.combinatorial.numbers.catalan
FAILED sympy/functions/special/bessel.py::sympy.functions.special.bessel.jn
FAILED sympy/functions/special/bessel.py::sympy.functions.special.bessel.yn
FAILED sympy/functions/special/beta_functions.py::sympy.functions.special.beta_functions.betainc_regularized
FAILED sympy/functions/special/hyper.py::sympy.functions.special.hyper.appellf1
FAILED sympy/integrals/integrals.py::sympy.integrals.integrals.Integral.as_sum
FAILED sympy/integrals/integrals.py::sympy.integrals.integrals.Integral.transform
FAILED sympy/ntheory/ecm.py::sympy.ntheory.ecm.ecm
FAILED sympy/ntheory/modular.py::sympy.ntheory.modular.crt1
FAILED sympy/ntheory/tests/test_generate.py::test_prime - assert 263 == 269
FAILED sympy/ntheory/tests/test_generate.py::test_primepi - assert 17 == 16
FAILED sympy/parsing/latex/__init__.py::sympy.parsing.latex.parse_latex
FAILED sympy/physics/units/util.py::sympy.physics.units.util.convert_to
FAILED sympy/polys/numberfields/exceptions.py::sympy.polys.numberfields.exceptions.ClosureFailure
FAILED sympy/printing/preview.py::sympy.printing.preview.preview
FAILED sympy/printing/theanocode.py::sympy.printing.theanocode.theano_function
FAILED sympy/solvers/solvers.py::sympy.solvers.solvers.nsolve
FAILED sympy/stats/frv_types.py::sympy.stats.frv_types.RobustSoliton
FAILED sympy/utilities/matchpy_connector.py::sympy.utilities.matchpy_connector.Replacer
```

Some tests failed because I don't have `matchpy` installed in this environment.

**Comment by oscarbenjamin** [comment]
So if CI uses `bin/doctest` then why did these plotting failures not show up?
https://github.com/sympy/sympy/blob/b68285262a06a914d9d920aba980d726be2efc39/.github/workflows/runtests.yml#L116-L119
Oh, maybe it's because these tests would be skipped without matplotlib and the optional dependency tests don't cover the `continuum_mechanics` module.

The ntheory failures are particularly worrying. It looks like wrong results are being returned with gmpy2.

**Pull request merged**
