### PR TITLE
Fix minor doc formatting

### PR DESCRIPTION
**Pull request by aktech**
@asmeurer

### CODE REVIEW

**Comment by gxyd** [comment]
You can use `[skip ci]` (forgot? :) )

**Comment by aktech** [comment]
I thought it would be merged pretty quickly. Though I should have skipped ci.

**Comment by aktech** [comment]
I have stopped the build now.

**Comment by aktech** [comment]
Will commit in a few hours.

**Comment by aktech** [comment]
Closing in favor of #10516

**Pull request closed without merging**
