### PR TITLE
Add support for ITE in ccode

### PR DESCRIPTION
**Pull request by bjodah**
See e.g. http://stackoverflow.com/questions/34121023/generate-c-code-for-sympy-expression-e1-op-e2-where-op-is-an-arithmetic-compar

### CODE REVIEW

**Comment by asmeurer** [comment]
The Piecewise definition (just above this) notes some caveats of using the ternary operator. 

Maybe it would be better to rewrite the ITE as a Piecewise and just use `_print_Piecewise`.

**Comment by asmeurer** [comment]
Other than concerns about that, +1 here.

**Comment by bjodah** [comment]
Yes, I agree. I updated the code accordingly. Note that I had to defer the import of Piecewise to the body of the `_print_ITE` method, is that alright?

**Comment by asmeurer** [comment]
Yeah that's fine. Sometimes you have to do that because of circular imports.

**Pull request merged**
