### PR TITLE
Fix sympify when evaluate=False and using undefined functions

### LINKED ISSUE #17811: sympify("abs(x)*5",evaluate=False) crashes
Long story short: The following program crashes:
```
import sympy
sympy.sympify("abs(x)*5",evaluate=False)
```
with the message:
> Traceback (most recent call last):
>   File "bugreport2.py", line 3, in <module>
>     sympy.sympify("abs(x)*5",evaluate=False)
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/core/sympify.py", line 384, in sympify
>     expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 964, in parse_expr
>     code = compile(evaluateFalse(code), '<string>', 'eval')
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 974, in evaluateFalse
>     node = EvaluateFalseTransformer().visit(node)
>   File "/usr/lib/python3.7/ast.py", line 262, in visit
>     return visitor(node)
>   File "/usr/lib/python3.7/ast.py", line 317, in generic_visit
>     value = self.visit(value)
>   File "/usr/lib/python3.7/ast.py", line 262, in visit
>     return visitor(node)
>   File "/usr/lib/python3.7/ast.py", line 326, in generic_visit
>     new_node = self.visit(old_value)
>   File "/usr/lib/python3.7/ast.py", line 262, in visit
>     return visitor(node)
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 1047, in visit_BinOp
>     new_node.args = self.flatten(new_node.args, sympy_class)
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 996, in flatten
>     if isinstance(arg, ast.Call) and arg.func.id == func:
> AttributeError: 'Call' object has no attribute 'id'

sympy.\_\_version\_\_ is '1.4' and sys.version is '3.7.3 (default, Oct  7 2019, 12:56:13) \n[GCC 8.3.0]'

### PR DESCRIPTION
**Pull request by ethankward**
#### References to other Issues or PRs
Addresses part of #17811.

#### Brief description of what is fixed or changed
Update `flatten` in in `sympy_parser` to go one level deeper when extracting a function.

#### Release Notes

* core
  * fix sympify(evaluate=False) with undefined functions

### CODE REVIEW

**Comment by asmeurer** [comment]
You can add release notes for fixes like this.

**Comment by asmeurer** [comment]
In the original issue, why is `abs(x)` treated as an undefined function? It should be using the built in `abs`. Or am I misunderstanding the problem here?

**Comment by ethankward** [comment]
I think I'll close this until the issue scope is clarified further- we can comment there.

**Comment by asmeurer** [comment]
I think your fix here might still be legitimate if it fixes a crash. I believe there are two issues:

- A crash with an undefined function and evaluate=False
- `abs` being parsed as an undefined function instead of the builtin `abs`

**Comment by oscarbenjamin** [comment]
Looks good

**Pull request merged**
