### PR TITLE
fix ``print_gtk()`` in python3

### PR DESCRIPTION
**Pull request by ghost**
``print_gtk()`` doesn't work in python3.
Calling it will raise a exception:
```Python traceback
Traceback (most recent call last):
  ...
  File ".../sympy/printing/gtk.py", line 16, in print_gtk
    file.write( c2p(mathml(x), simple=True) )
TypeError: a bytes-like object is required, not 'str'
```
It's because the temp file is opened with the mode 'wb',
which accepts ``str`` in python2, but ``bytes`` in python3.

I fixed it by using mode 'w' which works in both python2 and python3.
I also used ``subprocess`` to replace ``os.system()``,
which avoids hacking like space in file path.

* printing
    * `print_gtk` now works with python3.

### CODE REVIEW

**Comment by czgdp1807** [comment]
@asmeurer @certik This PR looks good and valid. Since we are dropping `Python 2` from SymPy 1.6, I think this PR fixes a potential issue. Can we merge this? The tests are passing.

**Comment by oscarbenjamin** [comment]
@czgdp1807 have you tested the PR? Can you reproduce the original issue and does this fix it? 

The PR doesn't have any tests. Maybe this isn't something that can be tested easily but if so that means that you should test it manually.

**Comment by czgdp1807** [comment]
ping @oscarbenjamin 
Some updates:-
In this PR,
```python
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> from sympy.abc import x
>>> print_gtk(x**2 + 2*exp(x**3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gagandeep/sympy/sympy/printing/gtk.py", line 18, in print_gtk
    subprocess.check_call(('mathmlviewer', file.name))
  File "/usr/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mathmlviewer': 'mathmlviewer'
>>> 

 In the master,
```python
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> from sympy.abc import x
>>> print_gtk(x**2 + 2*exp(x**3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gagandeep/sympy/sympy/printing/gtk.py", line 16, in print_gtk
    with open(tmp, 'wb') as file:
TypeError: expected str, bytes or os.PathLike object, not tuple
```
```

**Comment by czgdp1807** [comment]
ping @oscarbenjamin Can you please verify the code in above comment. Thanks.

**Comment by oscarbenjamin** [comment]
@czgdp1807 The way to resolve a PR like this is to take the time to find out how to test it properly. I guess in this case that means finding out with mathmlviewer is, installing it and then comparing the PR with master.

You might think that I am somehow more able to do those things than you are but the truth is you can test this just as easily as I can. You can also then merge it just as easily as I can.

**Comment by czgdp1807** [comment]
@oscarbenjamin Please accept my apologies. I tried to install `mathmlviewer` on my system but wasn't able to do so and therefore asked for help. I will try again and will comment here about the problems I faced.

**Comment by czgdp1807** [comment]
I installed `mathmlviewer` using `sudo apt-get install libgtkmathview-bin` which I got to know from [here](https://ubuntu.pkgs.org/16.04/ubuntu-universe-amd64/libgtkmathview-bin_0.8.0-13_amd64.deb.html).

Code snippets are given below,

In the master,
```python
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> from sympy.abc import x
>>> print_gtk(x**2 + 2*exp(x**3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gagandeep/sympy/sympy/printing/gtk.py", line 16, in print_gtk
    with open(tmp, 'wb') as file:
TypeError: expected str, bytes or os.PathLike object, not tuple 
```

In this PR,
```python
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> from sympy.abc import x
>>> print_gtk(x**2 + 2*exp(x**3))
```
The generated code of the file is given below,
```xml
<?xml version="1.0"?>
<math xmlns="http://www.w3.org/1998/Math/MathML" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/1998/Math/MathML         http://www.w3.org/Math/XMLSchema/mathml2/mathml2.xsd">
  <mrow>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
    <mo> + </mo>
    <mn>2</mn>
    <mo>&#x2062;</mo>
    <msup>
      <mn>e</mn>
      <msup>
        <mi>x</mi>
        <mn>3</mn>
      </msup>
    </msup>
  </mrow>
</math>
```
Screenshot,
14202_result

IMO, this PR successfully fixes the issue. If no objection is raised for 72 hours then this PR will be merged. Thanks.

**Comment by czgdp1807** [comment]
Some more testing,
```python
>>> print_gtk(Integral(x**2, x))
>>> print_gtk(Derivative(x**2, x))
>>> print_gtk(Sum(x**2, (x, 0, 10)))
```

Generated Codes(in order they were produced),
```xml
# print_gtk(Integral(x**2, x))
<?xml version="1.0"?>
<math xmlns="http://www.w3.org/1998/Math/MathML" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/1998/Math/MathML         http://www.w3.org/Math/XMLSchema/mathml2/mathml2.xsd">
  <mrow>
    <mo>&#x222B;</mo>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
    <mrow>
      <mo>d</mo>
      <mrow>
        <mi>x</mi>
      </mrow>
    </mrow>
  </mrow>
</math>

# print_gtk(Derivative(x**2, x))
<?xml version="1.0"?>
<math xmlns="http://www.w3.org/1998/Math/MathML" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/1998/Math/MathML         http://www.w3.org/Math/XMLSchema/mathml2/mathml2.xsd">
  <mrow>
    <mfrac>
      <mo>d</mo>
      <mrow>
        <mo>d</mo>
        <mi>x</mi>
      </mrow>
    </mfrac>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
  </mrow>
</math>

# print_gtk(Sum(x**2, (x, 0, 10)))
<?xml version="1.0"?>
<math xmlns="http://www.w3.org/1998/Math/MathML" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/1998/Math/MathML         http://www.w3.org/Math/XMLSchema/mathml2/mathml2.xsd">
  <mrow>
    <munderover>
      <mo>&#x2211;</mo>
      <mrow>
        <mrow>
          <mi>x</mi>
        </mrow>
        <mo> = </mo>
        <mrow>
          <mn>0</mn>
        </mrow>
      </mrow>
      <mrow>
        <mn>10</mn>
      </mrow>
    </munderover>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
  </mrow>
</math>
```

**Comment by oscarbenjamin** [comment]
You don't need to wait 72 hours to merge if it is good. Have you tested this with both Python 2 and 3 though?

**Comment by czgdp1807** [comment]
> Have you tested this with both Python 2 and 3 though?

Thanks for pointing this out.

Results for Python 2,

In master,
```python
Python 2.7.15+ (default, Jul  9 2019, 16:51:35) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> from sympy.abc import x
>>> print_gtk(x**2 + 2*exp(x**3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/printing/gtk.py", line 16, in print_gtk
    with open(tmp, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, tuple found
```

In this PR,
```python
Python 2.7.15+ (default, Jul  9 2019, 16:51:35) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> from sympy.abc import x
>>> print_gtk(x**2 + 2*exp(x**3))
>>> print_gtk(Integral(x**2, x))
>>> print_gtk(Derivative(x**2, x))
>>> print_gtk(Sum(x**2, (x, 0, 10)))
```

Generated Code,
```xml
# print_gtk(x**2 + 2*exp(x**3))
<?xml version="1.0"?>
<math xmlns="http://www.w3.org/1998/Math/MathML" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/1998/Math/MathML         http://www.w3.org/Math/XMLSchema/mathml2/mathml2.xsd">
  <mrow>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
    <mo> + </mo>
    <mn>2</mn>
    <mo>&#x2062;</mo>
    <msup>
      <mn>e</mn>
      <msup>
        <mi>x</mi>
        <mn>3</mn>
      </msup>
    </msup>
  </mrow>
</math>

# print_gtk(Integral(x**2, x))
<?xml version="1.0"?>
<math xmlns="http://www.w3.org/1998/Math/MathML" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/1998/Math/MathML         http://www.w3.org/Math/XMLSchema/mathml2/mathml2.xsd">
  <mrow>
    <mo>&#x222B;</mo>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
    <mrow>
      <mo>d</mo>
      <mrow>
        <mi>x</mi>
      </mrow>
    </mrow>
  </mrow>
</math>

# print_gtk(Derivative(x**2, x))
<?xml version="1.0"?>
<math xmlns="http://www.w3.org/1998/Math/MathML" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/1998/Math/MathML         http://www.w3.org/Math/XMLSchema/mathml2/mathml2.xsd">
  <mrow>
    <mfrac>
      <mo>d</mo>
      <mrow>
        <mo>d</mo>
        <mi>x</mi>
      </mrow>
    </mfrac>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
  </mrow>
</math>

# print_gtk(Sum(x**2, (x, 0, 10)))
<?xml version="1.0"?>
<math xmlns="http://www.w3.org/1998/Math/MathML" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/1998/Math/MathML         http://www.w3.org/Math/XMLSchema/mathml2/mathml2.xsd">
  <mrow>
    <munderover>
      <mo>&#x2211;</mo>
      <mrow>
        <mrow>
          <mi>x</mi>
        </mrow>
        <mo> = </mo>
        <mrow>
          <mn>0</mn>
        </mrow>
      </mrow>
      <mrow>
        <mn>10</mn>
      </mrow>
    </munderover>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
  </mrow>
</math>
```

**Pull request merged**
