### PR TITLE
Revert "[GSOC 2.2] Add method to evaluate system response of Transfer Functions. "

### PR DESCRIPTION
**Pull request by oscarbenjamin**
Reverts sympy/sympy#25335

@moorepants 

* physics.control
  *  XXX: REMOVE BOTH RELEASE NOTES LATER. Reverted evalfr method to TransferFunction and TransferFunctionMatrix class.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I'm seeing what looks like a new ruff failure:
```
Run ruff check .
bin/sympy_time_cache.py:56:13: F402 Import `time` from line 3 shadowed by loop variable
Found 1 error.
Error: Process completed with exit code 1.
```

**Comment by faze-geek** [comment]
Closing and Reopening did not correct the checks. The code quality failure has been corrected in master by #25413.

**Comment by faze-geek** [comment]
If I'm right, the failing checks are not due to this pr. This can be merged now.

**Comment by oscarbenjamin** [comment]
Yes, that's correct so I'll merge this now.

**Pull request merged**
