### PR TITLE
Defined Singularity Functions for Exponents -3 and -4.

### PR DESCRIPTION
**Pull request by mvg2002**
#### References to other Issues or PRs

These functions are necessary to implement the mechanics described in this issue #26570.

#### Brief description of what is fixed or changed
Defined Singularity Functions for exponents -3 and -4 and their (anti)derivative. 

#### Other comments
It is now possible to use Singularity Functions with exponents -3 and -4. Untill now the lowest possible exponent was -2. 

#### Release Notes

* functions
  * Defined singularity functions for exponents -3 and -4.

### CODE REVIEW

**Comment by moorepants** [comment]
Is there any reason we can't enable for any negative integer?

**Comment by mvg2002** [comment]
That must also be possible. I thought there might have been a reason not to do this as it was only done till -2 for now. I will try to implement this and make a new pull request.

**Comment by moorepants** [comment]
As long as the math is correct, we can support it. I can't remember why we limited it before.

**Comment by mvg2002** [comment]
I see that it is possible right now to create singularity functions with non-integer exponents. For example: 
```
from sympy.functions.special.singularity_functions import SingularityFunction
from sympy import Symbol

x = Symbol('x')
print(SingularityFunction(6, 4, 0.8))
```
Returns: 1.74110112659225

Shouldn't it also be possible to create non-integer negative exponents or am I missing something here?

**Comment by moorepants** [comment]
This object should do whatever the mathematical definition of a singularity function is. But, that I do not know. Maybe you can find a formal definition.

**Comment by mvg2002** [comment]
I am unable to find a clear mathmatical definition of the singularity function. The singularity function is used differently in differnt fields. In the field of continuum mechanics singularity funcitons only have meaning if the exponent is an integer. In other fields there are also singularity functions used with non-integer exponents, for example in [this paper](https://www.sciencedirect.com/science/article/pii/S0926580517300341?casa_token=DQsWxgQvweoAAAAA:Cw-DhaOyUHnFAGsMDHZsfkjSJEBiGSbAgYkEM4-S_ne4iBS4OmX5heISAlopDJrat5sDIQQWdFo).  
I think for the reason that the singularity function is also used in some fields with non-integer exponents it would be best for the SymPy application to also be able to handle these non-integer exponents.

**Comment by mvg2002** [comment]
There are some different mathmatical definitions across different fields. In the field of continuum mechanics the singularity function only has meaning when the exponent is an integer. This definition showing _n_ can only be an integer is given in [this paper](http://www.engineeringmechanics.cz/pdf/19_6_381.pdf).

In other fields the mathmatical definition doesn't specify that _n_ should be an integer. For example in [this paper](https://www.sciencedirect.com/science/article/pii/S0926580517300341?casa_token=DQsWxgQvweoAAAAA:Cw-DhaOyUHnFAGsMDHZsfkjSJEBiGSbAgYkEM4-S_ne4iBS4OmX5heISAlopDJrat5sDIQQWdFo). In this paper there are also a few singularity functions used with non-integer exponents. 

To keep the possibilities of the SymPy implementation as large as possible, I think it would be best to give the Singularity Function in SymPy the option to have non-integer values as exponents.

**Comment by moorepants** [comment]
If you confident that enabling n < 0  where n is real that the singularity function and any of its defined mathematical properties are correct, then you can do so.

**Comment by moorepants** [comment]
Or said a bit differently: it is better that singularity functions raise "NotImplemented" errors than generate incorrect results.

**Comment by mvg2002** [comment]
I understand your concern and have to admit that it might be better to only implement the singularity functions for negative integers. In the article I mentioned there is a mention of a singularity function with a negative non-integer exponent, but this is the only one I could find after some research and doesn't include a clear definition if this is possible for all negative exponents. 

I get that it's important that we are sure that everything that is implemented is correct. As I can't clearly prove at this point that singularity functions can take negative non-integer exponents, it might be better to go with the 'safe' choice here and only implement the singularity functions for negative integers.

**Comment by moorepants** [comment]
Sounds good. You can always change it later if you learn more.

**Pull request merged**
