### PR TITLE
Add another CSE test (gh-15082)

### PR DESCRIPTION
**Pull request by bjodah**
#### Brief description of what is fixed or changed
@mmohrhard reported that plain integers do not work in CSE:
https://github.com/sympy/sympy/pull/15112#issuecomment-414181638

I cannot reproduce the failure, but I've added this test to the test suite as
a regression test just to be safe.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by mmohrhard** [comment]
Even with 4b146a79fe78dce6f08a90a2be2becd263e84a2b for me the following test fails:


     def test_issue_15082():
         exprs = [1]
         cse_eq = cse(exprs)[1][0]
         assert cse_eq == 1
         exprs = 1
         cse_eq = cse(exprs)[1][0]
         assert cse_eq == 1

fails with:

> python3 bin/test sympy/simplify/tests/test_cse.py 
> =============================================================================================== test process starts ===============================================================================================
> executable:         /usr/bin/python3  (3.6.5-final-0) [CPython]
> architecture:       64-bit
> cache:              yes
> ground types:       gmpy 2.0.8
> numpy:              1.13.3
> random seed:        41199369
> hash randomization: on (PYTHONHASHSEED=2345804990)
> 
> sympy/simplify/tests/test_cse.py[43] .........f.fff....................f.......E                                                                                                                             [FAIL]
> 
> ___________________________________________________________________________________________________________________________________________________________________________________________________________________
> ________________________________________________________________________________ sympy/simplify/tests/test_cse.py:test_issue_15082 ________________________________________________________________________________
> Traceback (most recent call last):
>   File "/home/moggi/devel/sympy/sympy/simplify/tests/test_cse.py", line 545, in test_issue_15082
>     cse_eq = cse(exprs)[1][0]
>   File "/home/moggi/devel/sympy/sympy/simplify/cse_main.py", line 697, in cse
>     for e in exprs:
> TypeError: 'int' object is not iterable

I don't see how this could actually ever work as the only line that would make the exprs input an iterable object is line 692 in sympy/simplify/cse_main.py

Maybe I'm missing something.

**Comment by bjodah** [comment]
You're right. I messed up testing locally. Will try to address it here...

**Comment by bjodah** [comment]
cc @mmohrhard: this was the simplest patch I could come up with.

**Comment by mmohrhard** [comment]
@bjodah What about using `numbers.Number`? That should work in python 2.6+ and would cover all numeric python types.

**Comment by bjodah** [comment]
That's probably even better, ideally there should be a test case which covers that as well then (i.e. a use-case not covered by the `isinstance` test).

Maybe numbers wrapped as a numpy array? 0-d array should arguably behave the same as a scalar, with higher dimension arrays I don't know (haven't thought it through and I feel like I'm speculating).

Here's a start (tests failing)
```diff
diff --git a/sympy/simplify/cse_main.py b/sympy/simplify/cse_main.py
index e3e6372..c9e2cdb 100644
--- a/sympy/simplify/cse_main.py
+++ b/sympy/simplify/cse_main.py
@@ -1,6 +1,7 @@
 """ Tools for doing common subexpression elimination.
 """
 from __future__ import print_function, division
+import numbers
 
 from sympy.core import Basic, Mul, Add, Pow, sympify, Symbol
 from sympy.core.containers import Tuple, OrderedSet
@@ -688,7 +689,7 @@ def cse(exprs, symbols=None, optimizations=None, postprocess=None,
     from sympy.matrices import (MatrixBase, Matrix, ImmutableMatrix,
                                 SparseMatrix, ImmutableSparseMatrix)
 
-    if isinstance(exprs, (int, float)):
+    if isinstance(exprs, numbers.Number):
         exprs = sympify(exprs)
 
     # Handle the case if just one expression was passed.
diff --git a/sympy/simplify/tests/test_cse.py b/sympy/simplify/tests/test_cse.py
index 6cd8301..3d86854 100644
--- a/sympy/simplify/tests/test_cse.py
+++ b/sympy/simplify/tests/test_cse.py
@@ -8,17 +8,20 @@
     IndexedBase, Idx, Piecewise, O
 )
 from sympy.core.function import count_ops
+from sympy.external import import_module
 from sympy.simplify.cse_opts import sub_pre, sub_post
 from sympy.functions.special.hyper import meijerg
 from sympy.simplify import cse_main, cse_opts
 from sympy.utilities.iterables import subsets
-from sympy.utilities.pytest import XFAIL, raises
+from sympy.utilities.pytest import XFAIL, raises, skip
 from sympy.matrices import (eye, SparseMatrix, MutableDenseMatrix,
     MutableSparseMatrix, ImmutableDenseMatrix, ImmutableSparseMatrix)
 from sympy.matrices.expressions import MatrixSymbol
 
 from sympy.core.compatibility import range
 
+numpy = import_module('numpy')
+
 
 w, x, y, z = symbols('w,x,y,z')
 x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12 = symbols('x:13')
@@ -92,6 +95,15 @@ def test_cse_single2():
     subst_half, (red_half,) = cse(0.5)  # issue 15082
     assert len(subst_half) == 0 and red_half == 0.5
 
+
+def test_cse_single_numpy():
+    if not numpy:
+        skip("numpy not installed.")
+    for val in (42, 0.5, [42], [0.5]):
+        subst, (red,) = cse(numpy.array(val))
+        assert len(subst) == 0 and red == val
+
+
 def test_cse_not_possible():
     # No substitution possible.
     e = Add(x, y)
```
I will probably not finish that line of work since I don't know of any real world applications for it. Feel free to work on it though.

**Pull request merged**
