### PR TITLE
Add a missing True in boolalg docs

### PR DESCRIPTION
**Pull request by debugger22**

### CODE REVIEW

**Comment by toolforger** [comment]
Heh. I guess it meant to say "returns *whether* the two are equal", but this works, too.
+1

**Comment by debugger22** [comment]
Ooh! How did I miss that. :smile:

**Comment by toolforger** [comment]
It's a false friend, at least in German: both "if" and "whether" translate to the same word, "ob".
Something to watch out from German contributors, and possibly other Germanic languages.

**Comment by asmeurer** [comment]
Yes, as written, "returns if the given formulas have the same truth table" would literally mean that it returns anything at all in that situation. "if" -> "whether" or this change makes it clearer.

**Pull request merged**
