### PR TITLE
Adding a test case for Euler totient function #8922

### PR DESCRIPTION
**Pull request by aka001**
Please review it.
https://github.com/sympy/sympy/issues/8922

### CODE REVIEW

**Comment by aka001** [comment]
@smichr I don't think that any additional code is covered by adding this test case, since factorint() returns the factors of the number irrespective of whether it's product of 2 relatively prime numbers or not. The test case is to ensure that this property holds good.
> totient(m*n) = totient(m) * totient(n)
m and n are relatively prime.

**Comment by smichr** [comment]
I understand what you are saying, but I believe this is a property of the function and has nothing to do with the code itself. The tests that are there, I believe, are sufficient to test the code. But the docstring is sometimes a good place to give a little education to the interested reader. How about adding the code there? Perhaps see some of the other ntheory docstrings as examples.

**Comment by aka001** [comment]
@smichr I have updated the pr, by adding the code in docstring. 
I understand that adding another test case will just increase the runtime of testing the code without causing any additional benefits. 
Thanks.

**Comment by pelegm** [comment]
From Travis:
```
File "/home/travis/virtualenv/pypy-2.5.0/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/combinatorics/util.py", line 337, in sympy.combinatorics.util._remove_gens
Failed example:
    len(strong_gens)
Expected:
    26
Got:
    24
```

I have no idea what it means, but it has to be fixed before we merge this.

**Comment by aka001** [comment]
@pelegm Sorry for replying late. I will soon fix it and update the pr.

**Comment by smichr** [comment]
Don't worry about the combinatorics error. Rebasing will fix this. But do tell more of a story instead of giving a single test. The reader of the docstring should know what you are trying to show. See, for example, the `pollard_rho` docstring and others in the file.

**Comment by czgdp1807** [comment]
Thanks for the contributions. Closing in favour of https://github.com/sympy/sympy/pull/18019

**Pull request closed without merging**
