### PR TITLE
group theory: PermutationGroup methods for FpGroup

### PR DESCRIPTION
**Pull request by valglad**
This PR implements some of the methods from the `PermutationGroup` class for the `FpGroup` class. This is done by using coset tables to find an isomorphism from an `FpGroup` to a `PermutationGroup`, applying the method in the latter and then using the isomorphism to go back. Additionally, homomorphisms can now invert or be applied to a list of elements.

### CODE REVIEW

**Comment by jksuom** [comment]
It would be possible to make `_perm_group_list` work also with methods that return a single group.
```
from sympy.core.compatibility import is_sequence
...

single = False
if not is_sequence(perm_result):
    perm_result, single = [perm_result], True

...
return result[0] if single else result
```
Then it should not be necessary to define `method` arguments as lambda expressions, the name (and `getattr`) would suffice.

**Comment by valglad** [comment]
It seems that a single `PemutationGroup` is a sequence. Iterating over it is the same as iterating over its generators. It's a strange set-up. I could remove its `__getitem__` method but it probably has to be deprecated first. Alternatively, I can do something like `hasattr(perm_result, 'generators')` to check if `single` is `True.

**Comment by jksuom** [comment]
Would it be possible to use `isinstance(perm_result, PermutationGroup) `?

**Comment by valglad** [comment]
Yes, that would be clearer. Is there any other reason to use `isinstance` as opposed to `hasattr` in general?

**Comment by valglad** [comment]
That would require importing `PermutationGroup` inside the function, but I suppose that's not a problem?

**Comment by jksuom** [comment]
Why should if be imported inside the function?

**Comment by jksuom** [comment]
> Is there any other reason to use isinstance as opposed to hasattr in general?

I think it is generally safer to use isinstance.

**Comment by valglad** [comment]
>Why should if be imported inside the function?
Because it's not imported at the beginning of the file. It has to be imported somewhere, and it's only used in this function.

**Comment by jksuom** [comment]
Imports should be at the top of the file also when they are used in only one function. Sometimes that may lead to circular imports, and then they have to be placed inside functions.

**Comment by valglad** [comment]
I see, will change it then.

**Pull request merged**
