### PR TITLE
enable `sympy.plotting.plot_contour`

### PR DESCRIPTION
**Pull request by zaz**
instead of `from sympy.plotting.plot import plot_contour`

Improve: issue #12034

* plotting
  * Enable `sympy.plotting.plot_contour`

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I guess it should probably be imported at top-level like `from sympy import plot_contour`.

@Davide-sd what do you think?

**Comment by zaz** [comment]
Why at the top level and not with the other plot functions under `sympy.plotting.`?

Is there something special about `plot_contour` vs `plot3d`?

What is the rationale behind putting some plot commands in the top level while others are under `plotting`?  Is this just an inconvenience that has developed out of the need for backwards-compatibility?

It seems most sensible to have:

    sympy.plot.plot()
              .3d()
              .contour()
              .
              .
              .

The way plotting commands are currently structured is just all around odd for me.

**Comment by Davide-sd** [comment]
I think it should be available both at the top level, `from sympy import plot_contour`, as well as `from sympy.plotting import plot_contour`. The last one is justified from by the fact that I have seen a couple of questions at StackOverflow about people importing plot functions from `sympy.plotting`. As a matter of fact, reading [the documentation](https://docs.sympy.org/latest/modules/plotting.html) it is implied to use `from sympy.plotting import plot_function_name`.

**Comment by zaz** [comment]
It would be nice to have consistency with this: Either expose all the plotting functions at the top level, or keep them all in `plotting`, IMO.  Personally, I think that changing the name of `plotting` to `plot` and removing `plot_` gives us the best of both worlds; the user can do:

    from sympy import plot
    plot.3d(...)
    plot.parametric()

Which has the same level of succinctness, but more versatility than importing from the top-level.  Better yet, it allows the user to just `import sympy as sp` and still have a succinct way to make various kinds of plots, obviating the need to import plot functions explicitly.

The current `sympy.plot()` could be either retained permanently or deprecated using `__call__`:

```
>>> import sympy as sp
>>> class CallableModule(sp.__class__):
...     def __call__(self, **args):
...         sp.plotting.plot(**args)
... 
>>> sp.plotting.__class__ = CallableModule
>>> sp.plot = sp.plotting
>>> sp.plot()
>>> sp.plot.parametric()
```

**Comment by asmeurer** [comment]
This looks good. We should discuss the other changes in a new issue as they are more controversial since they would break compatibility.

**Comment by zaz** [comment]
Thank you.  I created a new issue for that: #23599

**Pull request merged**
