### PR TITLE
whitespace corrections to docs

### LINKED ISSUE #16879: solvers.rst in tutorials is using tabs
There may be other rst files in documentation that should be using spaces instead of tabs, too.

### PR DESCRIPTION
**Pull request by smichr**
#### References to other Issues or PRs

closes #16879 
does not address #4801 or #7469
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by czgdp1807** [comment]
@smichr How https://github.com/sympy/sympy/pull/16897 and this PR related? I think the two PRs are solving different issues and the files which are changed in https://github.com/sympy/sympy/pull/16897 are not changed in this PR.

**Comment by smichr** [comment]
> How #16897 and this PR related?

not at all. These are changes to spacing in rst files.

**Comment by czgdp1807** [comment]
@smichr Then why is this PR closing https://github.com/sympy/sympy/pull/16897? I think `closes #16897` needs to be removed or modified from [the description](https://github.com/sympy/sympy/pull/16905#issue-282362623) of this PR.

**Comment by czgdp1807** [comment]
@smichr I think you wanted to close issue https://github.com/sympy/sympy/issues/16879, am I right? May be you interchanged 7 and 9 in 16879 and wrongly wrote `closes #16897`.

**Pull request merged**
