### PR TITLE
fix_holonomic caching error

### LINKED ISSUE #19222: 'sympy/holonomic/tests/test_holonomic.py' fails on master
The Complete Logs
```python3
(sympy-dev-py35) mosespaul@eiphohch0aYa sympy2 % git checkout master
Already on 'master'
Your branch is up to date with 'upstream/master'.
(sympy-dev-py35) mosespaul@eiphohch0aYa sympy2 % python             
Python 3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:11) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> test('sympy/holonomic/tests/test_holonomic.py')
====================================================================================== test process starts ======================================================================================
executable:         /Users/mosespaul/opt/anaconda3/envs/sympy-dev-py35/bin/python  (3.5.5-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              1.18.2
random seed:        2125066
hash randomization: on (PYTHONHASHSEED=4270562452)

sympy/holonomic/tests/test_holonomic.py[27] .............E.....E.......                                                                                                                    [FAIL]

_________________________________________________________________________________________ slowest tests _________________________________________________________________________________________
test_integrate - Took 10.437 seconds
_________________________________________________________________________________________________________________________________________________________________________________________________
________________________________________________________________ sympy/holonomic/tests/test_holonomic.py:test_expr_to_holonomic _________________________________________________________________
Traceback (most recent call last):
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/holonomic/tests/test_holonomic.py", line 489, in test_expr_to_holonomic
    p = expr_to_holonomic(besselj(2, x))
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/holonomic/holonomic.py", line 2390, in expr_to_holonomic
    sol = _convert_meijerint(func, x, initcond=False, domain=domain)
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/holonomic/holonomic.py", line 2820, in _convert_meijerint
    sol = fac_list[0] * coeff * from_meijerg(m, initcond=initcond, domain=domain)
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/holonomic/holonomic.py", line 2252, in from_meijerg
    r2 *= x * Dx - b[i]
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/holonomic/holonomic.py", line 288, in __sub__
    return self + (-1) * other
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/holonomic/holonomic.py", line 276, in __add__
    list_other = [((self.parent).base).from_sympy(sympify(other))]
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/polys/domains/old_polynomialring.py", line 251, in from_sympy
    rep[k] = self.dom.from_sympy(v)
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/polys/domains/pythonrationalfield.py", line 40, in from_sympy
    raise CoercionFailed("expected `Rational` object, got %s" % a)
sympy.polys.polyerrors.CoercionFailed: expected `Rational` object, got nan
_________________________________________________________________________________________________________________________________________________________________________________________________
____________________________________________________________________ sympy/holonomic/tests/test_holonomic.py:test_to_meijerg ____________________________________________________________________
Traceback (most recent call last):
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/holonomic/tests/test_holonomic.py", line 718, in test_to_meijerg
    assert hyperexpand(expr_to_holonomic(besselj(2, x), lenics=3).to_meijerg()) == besselj(2, x)
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/holonomic/holonomic.py", line 2390, in expr_to_holonomic
    sol = _convert_meijerint(func, x, initcond=False, domain=domain)
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/holonomic/holonomic.py", line 2820, in _convert_meijerint
    sol = fac_list[0] * coeff * from_meijerg(m, initcond=initcond, domain=domain)
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/holonomic/holonomic.py", line 2252, in from_meijerg
    r2 *= x * Dx - b[i]
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/holonomic/holonomic.py", line 288, in __sub__
    return self + (-1) * other
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/holonomic/holonomic.py", line 276, in __add__
    list_other = [((self.parent).base).from_sympy(sympify(other))]
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/polys/domains/old_polynomialring.py", line 251, in from_sympy
    rep[k] = self.dom.from_sympy(v)
  File "/Users/mosespaul/Desktop/Coding/GSoC/sympy2/sympy/polys/domains/pythonrationalfield.py", line 40, in from_sympy
    raise CoercionFailed("expected `Rational` object, got %s" % a)
sympy.polys.polyerrors.CoercionFailed: expected `Rational` object, got nan

=================================================================== tests finished: 25 passed, 2 exceptions, in 45.79 seconds ===================================================================
DO *NOT* COMMIT!
False
>>> 
```

### PR DESCRIPTION
**Pull request by iammosespaulr**
#### References to other Issues or PRs

Fixes #19222

#### Brief description of what is fixed or changed

Fixes a cache mismatch due to using`is` instead of `==` in `holonomic.py`

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by iammosespaulr** [comment]
the tests pass now, @oscarbenjamin @jksuom

**Comment by jksuom** [comment]
There is another case a few lines earlier. Maybe that should be changed as well.

**Comment by smichr** [comment]
@oscarbenjamin, this could be included in the 1.6 release.

**Comment by oscarbenjamin** [comment]
> @oscarbenjamin, this could be included in the 1.6 release.

Yes, it could. To make that happen do this:

1. Leave this unmerged for now.
2. Open a new PR from the same branch but against the 1.6 branch - add the release note there.
3. I'll merge it into 1.6.
4. Remove the release note here and merge it into master.

**Comment by iammosespaulr** [comment]
@smichr @oscarbenjamin I've done this https://github.com/sympy/sympy/pull/19236#issuecomment-623158406

**Pull request merged**
