### PR TITLE
fix(printer) Add isnan and isinf support for tensorflow printer

### LINKED ISSUE #26784: How to cast nan to not-nan in an expression
Hi, I'm new to Sympy and I wonder how to cast null value to a default value in a Sympy expression
For example
```
import sympy as sp
x = sp.symbols("x")
# Return 0 if x is of nan value, and 1 otherwise
exp = sp.Piecewise((0.0, sp.Eq(x, sp.nan)), (1.0, True))
sp.lambdify((x), exp)(x=float('nan'))
Out[28]: 1.0
```
The above expression returns 1.0 instead of 0.0
I found that the problem comes from the expression
```
In [29]: sp.Eq(x, sp.nan)
Out[29]: False
```
It seems that `sp.Eq` does symbolic evaluation on variable `x` instead of waiting for the input from the actual calculation

Maybe I'm using sympy in a wrong way. But would appreciate someone to shed some light on how to do this

Thank you

### PR DESCRIPTION
**Pull request by zexuan-zhou**
#### References to other Issues or PRs

A further improvement for the fix #26784. Specifically to address this [comment](https://github.com/sympy/sympy/issues/26784#issuecomment-2237483117)

#### Brief description of what is fixed or changed
Add isnan and isinf support for tensorflow printer

#### Release Notes

- printing
  - Add `_print_isnan` and `_print_isinf` in TensorflowPrinter.

### CODE REVIEW

**Comment by zexuan-zhou** [comment]
@bjodah @oscarbenjamin 
Please take a look. Thank you

**Comment by zexuan-zhou** [comment]
The tensorflow test failure in test / Tests (pull_request) is confusing
Local test `./bin/test test_tensorflow` works

**Comment by oscarbenjamin** [comment]
> And need some help on test / NumPy/SciPy nightly (pull_request)

That is unrelated (gh-26862).

> Local test `./bin/test test_tensorflow` works

That is because you have tensorflow installed. The tests need to check if it is installed.

**Comment by zexuan-zhou** [comment]
Good catch. Updated

**Comment by zexuan-zhou** [comment]
Please move to this [PR](https://github.com/sympy/sympy/actions/runs/10153610482/job/28077295875?pr=26876) as the email I used in this PR is messed up.

**Pull request closed without merging**
