### PR TITLE
Union with subset of S.Complexes now evaluated

### PR DESCRIPTION
**Pull request by kevalds51**

### CODE REVIEW

**Comment by gxyd** [comment]
You can change the commit message to something more descriptive, current commit message does not seem correct. Change it to "Union with subset of S.Complexes now evaluated", also the PR description message. Rest of PR looks good.

**Comment by aktech** [comment]
@kevalds51 

You could change the commit message through this:

```
$ git commit --amend -m "New Commit message"
```
Then you have to force that push (`git push -f`).

Ping us when you are done with changes.

**Comment by aktech** [comment]
@kevalds51  Thanks for your work. @gxyd  Thanks for reviewing.

**Comment by gxyd** [comment]
@kevalds51 for future work you add to your commit message "fixed #issue_number" this will automatically close the corresponding issue, when the PR gets merged.

**Pull request merged**
