### PR TITLE
General function decomposition

### PR DESCRIPTION
**Pull request by aktech**
Computes General functional decomposition of `f`.
Given an expression `f`, returns a list `[f_1, f_2, ..., f_n]`,
where::
              `f = f_1 o f_2 o ... f_n = f_1(f_2(... f_n))`

**TODO**
- [x] General Decomposition
- [x] Tests
- [x] Support Polys' `decompose`
- [x] Doc strings
- [x] Add reference to sphinx docs
- [x] Update release notes

@hargup @flacjacket

### CODE REVIEW

**Comment by hargup** [comment]
This should handle most of our usecases. @aktech you can recursively apply the rule for get decompositions of more than two functions and you should call `decompose` from poly for polynomials. Also can you add `Xfailed` tests for more a few complicated cases (whatever they might me).

**Comment by aktech** [comment]
Yes, thanks, I am working on it.

**Comment by aktech** [comment]
@hargup

**Comment by smichr** [comment]
> Can you give an example of a complex case it can't decompose?

```
>>> A=lambda x:1*x**2+2*x+3
>>> B=lambda x:4*x**2+5*x+6
>>> A(x*exp(x))
x**2*exp(2*x) + 2*x*exp(x) + 3
>>> decompogen(_,x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\decompogen.py", line 54, in decompogen
    result += decompose(f)
  File "sympy\polys\polytools.py", line 5437, in decompose
    result = F.decompose()
  File "sympy\polys\polytools.py", line 2869, in decompose
    result = f.rep.decompose()
  File "sympy\polys\polyclasses.py", line 715, in decompose
    raise ValueError('univariate polynomial expected')
ValueError: univariate polynomial expected
```

Perhaps the following is expected

```
>>> decompogen(A(B(x)),x)
[16*x**4 + 40*x**3 + 81*x**2 + 70*x + 51]
>>> decompogen(A(1/x),x)
[x**2 + 2*x + 3, 1/x]
>>> decompogen(A(1/x+1/x**2),x)
[2*x**2 + 2*x + (x**2 + x)**2 + 3, 1/x]  <-- only identified 1/x
>>> decompogen(A(1/x+2/(x+1)),x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\decompogen.py", line 54, in decompogen
    result += decompose(f)
  File "sympy\polys\polytools.py", line 5437, in decompose
    result = F.decompose()
  File "sympy\polys\polytools.py", line 2869, in decompose
    result = f.rep.decompose()
  File "sympy\polys\polyclasses.py", line 715, in decompose
    raise ValueError('univariate polynomial expected')
ValueError: univariate polynomial expected
```

**Comment by aktech** [comment]
@smichr  Thanks for the examples.
I have added some XFAIL's here https://github.com/aktech/sympy/commit/38d07cc48c5e3fb0737522e1fa69beb59fd6f250 .

**Comment by aktech** [comment]
ping @hargup  @smichr

**Comment by aktech** [comment]
This could also be useful in fixing issues like #9824

**Comment by hargup** [comment]
+1

**Pull request merged**
