### PR TITLE
Travis benchmark

### LINKED ISSUE #17807: Enable benchmark run on Travis
@bjodah and @oscarbenjamin suggested that we could make a "allowed failure" travis matrix entry to run the HEAD of the pull request against MASTER for reporting performance degradation. The necessary asv command is:

```
asv compare --factor 1.5 HEAD master
```

Which would report any benchmark that becomes slower than a factor of 1.5.

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

Fixes #17807

#### Brief description of what is fixed or changed

Run benchmark on travis

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This looks good except I'm not sure where the benchmark should go in the travis stages. Ideally it would display prominently while still being an allowed failure but maybe there's no way to do that.

**Comment by sylee957** [comment]
I think that making a bot that can post a comment would be better than making a build fail.

**Comment by asmeurer** [comment]
If you need access to the @sympy-bot user let me know.

**Comment by oscarbenjamin** [comment]
A bot would be great. I don't know how difficult it is to create one. I imagine it would take me a while to figure out how to do it...

**Comment by oscarbenjamin** [comment]
Is this ready to be merged? Maybe we should open a couple of test PRs based off of this to see what happens...

**Comment by sylee957** [comment]
Yes, regardless of figuring a way how to set up a bot, at least benchmarks can be exposed publically after this progress

**Comment by oscarbenjamin** [comment]
Is the benchmark here an allowed failure? Does it run before the baseline tests?

**Comment by oscarbenjamin** [comment]
Looks like this stops the flake8 job from being an allowed failure

**Comment by sylee957** [comment]
I'm not sure about the way how to check if `allowed_failures` is actually enabled for travis or not.

**Comment by oscarbenjamin** [comment]
> I'm not sure about the way how to check if `allowed_failures` is actually enabled for travis or not.

It's not very well documented.

If you look here
https://travis-ci.org/sympy/sympy/builds/605655720?utm_source=github_status&utm_medium=notification
then at the bottom it says "Your build matrix was set to allow the failure of job 37113.30 so we continued this build to the next stage."

The only way to check is to open a new PR that fails the job and look at that message.

It might be better to have a stage called "allowed failures". Then it would have its own stage header and it would be more obvious to contributors which jobs are allowed to fail. The allowed failures did used to show like that before we switched to multiple stages.

**Comment by asmeurer** [comment]
You can reuse the infrastructure from the existing bot. You would set it up so that Travis posts something to the bot and the bot makes a comment. The hard part would be setting up shared secret so that only Travis builds can post to the bot.

**Comment by sylee957** [comment]
The ideas I have so far are:

1. Uploading the benchmark report to the sympy bot from travis ci can be done via using `requests.post` to `https://sympy-bot.herokuapp.com/` or any specific path for better.
2. From the sympy bot, `app.router.add_post` can be added to register a handler for the `POST` request.
3. For the authentication between the travis build and the sympy bot, a GPG signing process can be used, and the private key can be stored in the travis server and the public key can be stored in the heroku server as environment variables.

But I'm not sure about how safe storing the private keys in the travis repository settings is. For example, if there is a `printenv` command from one of the pull requests

**Comment by oscarbenjamin** [comment]
What exactly is the risk if someone obtains this private key? Does it just enable them to fake the stats in the profile report or is there something worse that can happen?

**Comment by asmeurer** [comment]
Travis does not allow encrypted environment variables in pull requests, because anyone could easily extract it by making a pull request. I'm not even sure if it's worth bothering with shared secrets. 

I think the risk is that someone could spam the bot using up all its API limits and potentially spamming GitHub. The bot does have push access, but presumably it would be set up so that the requests could only result in the bot commenting something. 

I'm not sure how to do it. Something like Codecov can do it because users can't change what code actually runs that produces the comment. I guess we have to make it so that the bot only posts one comment per PR build, and only accepts requests from travisci.org. That way even if someone does something screwy they can't force the bot to comment a bunch.

**Comment by sylee957** [comment]
Codecov reveals their upload script files in https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py and https://codecov.io/bash but I didn't find much things special there.

One possible way to verify that the request was really made from the travis is crawling the travis log. that the build was already there, and collect some signatures. But would there be a better idea?

**Comment by asmeurer** [comment]
You might be able to detect it from the information in the request. I'm not sure how to do it in a way that can't be faked. Services like Heroku and GitHub webhooks typically use shared secrets, so maybe that's a best practice because doing it some other way is not possible.

**Comment by moorepants** [comment]
Could we merge this as is and build the bot in another PR?

**Comment by oscarbenjamin** [comment]
> Could we merge this as is and build the bot in another PR?

The benchmark tests are run as a stage in between the quality tests but before running any of the actual tests. That doesn't seem right to me: if a PR has issues it's much better to see the failures from the main test suite than the benchmarks. Probably we should only run the benchmarks in the final stage along with coverage, flake8 etc.

Also from my own experience editing travis.yml I don't trust that I understand the rules well enough to know that Github will treat this as an allowed failure. Once the travis.yml is finished we need to see  a test failing PR based off of this to see whether it can be merged or not.

**Comment by sylee957** [comment]
What about moving pypy, flake8, and other allowed failing tests into a separate stage?
And I'd also suggest to move the optional dependency test to the baseline because it is one of the places where the test fails frequently.

**Comment by sylee957** [comment]
I have the showcase that the allowed failings are working as expected
 https://travis-ci.org/sympy/sympy/builds/608601030?utm_source=github_status&utm_medium=notification
Though this can not be merged immediately before I remove the lines triggering `exit 1`
But I'm willing to progress if anyone comment about the idea above

**Comment by asmeurer** [comment]
I guess it depends on how it affects the timing different stages. The point of the baseline is to have a separate queue so you can see if tests are failing faster. If moving the optional dependency tests there doesn't mess with that too much, I don't see a problem with it.

**Comment by asmeurer** [comment]
By the way, in the long term, I think we should do the benchmarks on GitHub Actions. The reason is that they have support for user-run workers, meaning we could at some point move the benchmarks to a dedicated machine for less variant performance across runs.

**Comment by oscarbenjamin** [comment]
I think it would be good to move the 3.x optional dependency test to baseline.

I think it would be good to put allowed failures in to their own stage just because it isn't clear to contributors that they are allowed failures.

I don't think that the pypy tests need to be in allowed failures any more.

**Comment by oscarbenjamin** [comment]
Looks good

**Pull request merged**
