### PR TITLE
Added required sections in sympy.assumptions.handlers

### PR DESCRIPTION
**Pull request by Soumi7**
# Updates sympy.assumptions.handles to follow latest docstring style guide

#### References to other Issues or PRs

#19591

#### Brief description of what is fixed or changed
- Required sections in :
  - sympy/assumptions/handlers/calculus.py
  - sympy/assumptions/handlers/common.py
  - sympy/assumptions/handlers/matrices.py
  - sympy/assumptions/handlers/ntheory.py
  - sympy/assumptions/handlers/order.py
  - sympy/assumptions/handlers/sets.py

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
The test failure seems unrelated.

**Comment by asmeurer** [comment]
I restarted the Travis job. We may also have to manually start the other jobs if it passes.

**Comment by Soumi7** [comment]
@asmeurer The first six test cases passed. Could you restart the rest?

**Comment by oscarbenjamin** [comment]
Looks good. Thanks @Soumi7!

**Pull request merged**
