### PR TITLE
The Zen of SymPy: from sympy import this

### PR DESCRIPTION
**Pull request by aktech**
Source: https://github.com/sympy/sympy/wiki/The-Zen-of-SymPy

Idea inspired from: https://github.com/python/cpython/blob/master/Lib/this.py

Usage:

``` python
>>> from sympy import this
The Zen of SymPy

Unevaluated is better than evaluated.
The user interface matters.
Printing matters.
Pure Python can be fast enough.
If it's too slow, its (probably) your fault.
Documentation matters.
Correctness is more important than speed.
Push it in now and improve upon it later.
Coverage by testing matters.
Smart tests are better than random tests.
But random tests sometimes find what your smartest test missed.
The Python way is probably the right way.
Community is more important than code.
```

ping @certik @asmeurer @moorepants 

Feel free to agree or disagree to add this.

### CODE REVIEW

**Comment by asmeurer** [comment]
I'm +0 to add it. I think if we do, though, we should use something more mathematically clever than the rot13 from `import this`.

**Comment by certik** [comment]
Yeah, I am also not super convinced about the text. I would like it to be more witty.

**Comment by smichr** [comment]
+1 and "Push it in now and improve upon it later." ;-)  Honestly, I think about this list often when working on SymPy things, especially the random testing.

**Comment by aktech** [comment]
> "Push it in now and improve upon it later." ;-)

That's what I thought while proposing this. :)

**Comment by moorepants** [comment]
I'm not sure "push it in now and improve later" will work well for this. My guess is that it is unlikely to get changed if we commit it. You could facilitate a discussion here and get some input to improve it before committing. I also like Aaron's idea about having a more clever import statement, like:

from sympy import ontology

or

from sympy import apriori

**Comment by aktech** [comment]
> I also like Aaron's idea about having a more clever import statement, like:

I think, what Aaron means to say is we should use something more mathematically clever for encrypting the text, instead of the rot13 logic for swapping the Alphabets. `from sympy import this` was suggested because it's analogous to Python's `import this` & it would probably be intuitive for users to try it out.

**Comment by asmeurer** [comment]
Yes, I think if it is there it should be sympy.this.

**Comment by moorepants** [comment]
Sorry I misunderstood. I didn't know that it was stored in some kind of cipher.

**Comment by smichr** [comment]
Leave a comment

> mathematically clever...than rot13

We have a crypto module that could be used.

**Comment by asmeurer** [comment]
Or something like this maybe

```py
In [40]: ''.join([chr(primepi(j)) for j in [prime(ord(i)) for i in 'This is a message']])
Out[40]: 'This is a message'
```

**Comment by aktech** [comment]
Do you mean this:

* Converting to Cipher text
```python
In [41]: cipher_text = ''.join([chr(i) for i in [prime(ord(i)) for i in 'This is a message']])

In [42]: cipher_text
Out[42]: 'ƱȹȻɷ\x83Ȼɷ\x83ǽ\x83ɗȣɷɷǽȳȣ'
```
* Converting to Original Text
```python
In [42]: ''.join([chr(primepi(ord(j))) for j in cipher_text])
Out[42]: 'This is a message'
```

**Comment by hargup** [comment]
> We have a crypto module that could be used.

We can encrypt the message with a 128 bit AES with first 128 bits of Pi as a key.

**Comment by gxyd** [comment]
I am merging this PR as is. I will open an issue to improve the encryption of the message.

**Comment by gxyd** [comment]
I have opened issue https://github.com/sympy/sympy/issues/13450

**Pull request merged**
