### PR TITLE
exp.as_leading_term() returns wrong results

### LINKED ISSUE #4615: exp.as_leading_term returns wrong results
```
as_leading_term is implicitly understood (at least by me) to obey the
following mathematical contract: expr.as_leading_term(x) ~ expr as x -> 0.
However, it fails on the common pitfall that f(x) ~ g(x) doesn't imply
exp(f(x)) ~ exp(g(x)). Concretely, we have:

>>>exp((x+1)/x**2).as_leading_term(x)
exp(x**(-2))

but, of course,

>>>limit(exp((x+1)/x**2)/exp(x**(-2)), x, 0)
oo

Obtaining a correct answer requires performing a full asympotic expansion
to order o(1) which might be outside the scope of this method, so maybe it
should return the expression unchanged unless it can easily get a correct
answer.
```

Original issue for #4615: http://code.google.com/p/sympy/issues/detail?id=1516
Original author: https://code.google.com/u/101272611947379421629/

### PR DESCRIPTION
**Pull request by maurogaravello**
#### References to other Issues or PRs

Fixes #4615 

#### Brief description of what is fixed or changed

`as_leading_term` does not work properly on exponential functions.
As noted in the issue #4615 , `exp((x+1)/x**2).as_leading_term(x)`
returns `exp(x**(-2))`, which is not the correct result.
Indeed when the argument of `exp` tends to `oo`, then it is not
correct doing the leading term of the `arg` and then applying the exponential.

Also SymPy in the case
`exp((2*x + 3) / (x+1)).as_leading_term(x)`
returns `S(1)`, which is not correct here, since the argument is closed to `3`.

In `test_exponential.py` the following tests are added
```
    assert exp((x + 1) / x**2).as_leading_term(x) == exp((x + 1) / x**2)
    assert exp((2*x + 3) / (x+1)).as_leading_term(x) == exp(3)
```
#### Release Notes

- functions
   - remove a bug for `as_leading_term()` for exponential functions.

### CODE REVIEW

**Comment by jksuom** [comment]
How about doing something like this.

        arg = self.args[0].as_leading_term(x)
        if Order(x, x).contains(arg):
            return S.One
        if Order(1, x).contains(arg):
            return exp(arg)

Otherwise return nothing to indicate that there is no leading term. (I think that `exp((x + 1) / x**2)` has none at  x = 0.)

**Comment by maurogaravello** [comment]
> How about doing something like this.
> 
> ```
>     arg = self.args[0].as_leading_term(x)
>     if Order(x, x).contains(arg):
>         return S.One
>     if Order(1, x).contains(arg):
>         return exp(arg)
> ```
> 
> Otherwise return nothing to indicate that there is no leading term. (I think that `exp((x + 1) / x**2)` has none at x = 0.)

I agree that `exp((x + 1) / x**2)` has not a leading term. It seems that the code you proposed works.
However if the function returns `None`, then `as_leading_term()` in `expr.py` executes the line
```
raise NotImplementedError('as_leading_term(%s, %s)' % (self, x))
```
In this case the test
```
    assert exp(1/x).as_leading_term(x) == exp(1/x)
```
in `test.exponential.py` fails. It is not a test I added before. Probably it is not formally correct.
How to proceed? Do I Remove such a test?

**Comment by jksuom** [comment]
I think that those tests where no leading term exists should be changed to `raises(NotImplementedError, lambda: ...)`. The tests need not be totally removed.

**Comment by jksuom** [comment]
This looks fine. There could be yet another test for the case where `arg.is_Add` like in `exp(x + 1/x)`. (That should also raise.)

**Comment by maurogaravello** [comment]
Also the test for `exp(x + 1/x)` works.

However this produces some errors in various limit procedures based on leading terms.

**Comment by jksuom** [comment]
It seems that many examples of asymptotic series fail. Not sure that the examples are correct. Asymptotic series code should probably not rely on non-existent leading terms and catch the NotImplementedError.

There are also limit and order tests that fail. It is possible to edit the tests but it would probably be better to have the code catch the error. I don't think it makes sense to return orders like  `O(exp(1/x))`.

**Comment by jksuom** [comment]
> However there are some errors in various limit procedures based on leading terms.

It will be too hard to fix all those errors in a single PR. I think that we should let the wrong result pass for now. That is, return `exp(arg)` but with a comment that actually `None` should be returned. That will hopefully be changed in the future.

The essential fix and test (`exp(3)`) will stay. The two tests with `raises` could be commented out for now with a comment added.

**Comment by maurogaravello** [comment]
Ok. I modified the code accordingly.

It seems to me that other functions, such as `cos`, have the same problem. 
When the series expansion does not admit the leading term, the return value is the original function.

**Comment by jksuom** [comment]
This looks good, thank you.

Can you open an issue pointing out some consequences of the false leading term for functions that have an essential singularity, like exp and many trigonometric functions at infinity. I think that the expression in an `Order` should be a power of the variable, not something like `O(exp(1/x), (x, 0))`.

**Comment by maurogaravello** [comment]
Thank you.

I opened a new issue about `as_leading_term()`. 

However I am not completely convinced that `O`, different from `as_leading_term()`, should be a power of a variable. From mathematical point of view, also an expression like `O(exp(1/x), (x, 0))` makes sense.

**Comment by oscarbenjamin** [comment]
The new issue is #17463

**Pull request merged**
