### PR TITLE
Fixes a Typo

### PR DESCRIPTION
**Pull request by Abdullahjavednesar**

### CODE REVIEW

**Comment by Abdullahjavednesar** [comment]
Ping @jksuom
I think "under-" in [this line](https://github.com/sympy/sympy/blob/master/sympy/solvers/solvers.py#L2107) could be better written as underdetermined.

**Comment by jksuom** [comment]
I think it is customary to use constructions like 'under- and overdetermined' with no repetition of 'determined'.

**Comment by Abdullahjavednesar** [comment]
Yah! may be you're right.

**Comment by Abdullahjavednesar** [comment]
Thanks @jksuom  :)

**Pull request merged**
