### PR TITLE
ruff-PIE802: optimize any all with generators

### PR DESCRIPTION
**Pull request by Skylion007**
#### References to other Issues or PRs
Optimize code to remove unnecessary list comprehensions in any/all builtin functions call. The builtin function calls will shortcircuiting when reading a generator, but the entire list has to be generated first when using a list comprehension. I've also enabled the proper ruff check. There is a flake8 plugin, but it is deprecated and recommends transitioning into the ruff plugin (although not all rules are ported over to it). As such, I have enabled the ruff rule corresponding to this fix.

#### Brief description of what is fixed or changed
* All any/all builtins that previously used a list comprehension now use a generator.

#### Other comments
* This is more performant than the existing code and the check encourages better coding style going forward.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Review by brocksam — COMMENTED** [review]
Currently we're running both flake8 and Ruff. At the moment (I think) we've got the same linting configuration when run on just `sympy/`. Introducing this would bring the two out of alignment. I'm all for it but it should probably be conditional on agreement from all that we're migrating towards Ruff from flake8.

Are there any other ["PIE"](https://beta.ruff.rs/docs/rules/#flake8-pie-pie) rules that we'd want to consider enforcing too?

**Comment by Skylion007** [comment]
Quite a few, many are duplicated with native flake8-rules or other plugins. Full list of rules here: https://github.com/sbdchd/flake8-pie some controversial ones though
* PIE787 PIE788 could be false positive occasionally
* PIE803 is more performant, but people would much rather use fstrings
* Many other rules are opinionate so I decided just to enable one that is obviously better and I would prefer it was in flake8-comprehension (but I also why it's not since it is theoretically not faster in every case, but is in almost every case).

**Review by brocksam — APPROVED** [review]

**Comment by oscarbenjamin** [comment]
> it should probably be conditional on agreement from all that we're migrating towards Ruff from flake8.

I'm not sure that it means that we have to migrate towards ruff. There's no reason we can't use both at least in CI. It isn't hard to install ruff but I guess perhaps it should be described somewhere in the development docs.

**Comment by Skylion007** [comment]
@brocksam This old issue discusses some additional flake8-plugin / ruff checkers that can be enabled: https://github.com/sympy/sympy/issues/20068 if you are interested.

**Pull request merged**
