### PR TITLE
Matrix Cleanup Step 3

### PR DESCRIPTION
**Pull request by siefkenj**
The matrix cleanup work is starting to pay off. Many methods that were duplicated across `MatrixBase` and
`DenseMatrix` and `SparseMatrix` were deleted.  Appropriate `_eval_...` functions (mostly in `SparseMatrix`) were overridden to provide optimized behavior.

This PR also declutters the `ImmutableMatrix` classes by switching inheritance to happen in the correct order.

### CODE REVIEW

**Comment by siefkenj** [comment]
@moorepants @smichr @jksuom this might interest you.  It is mostly deleting stuff :-)

**Comment by moorepants** [comment]
One quick comment: If you are renaming public API you need to go through a deprecation cycle.

**Comment by siefkenj** [comment]
Both `ImmutableMatrix` and `ImmutableDenseMatrix` have existed and have been equal to each other  (see the `__init__.py` where it is defined that `ImmutableMatrix == ImmutableDenseMatrix`).  I just changed the class declaration to be `ImmutableDenseMatrix` and the set `ImmutableMatrix=ImmutableDenseMatrix` instead of the other way around.

I assume that this doesn't count as an API change?

The only difference is that you cannot do `import ImmutableMatix from sympy.matrices.immutable`.  You now have to do `import ImmutableMatrix from sympy.matrices`.  Of course, I could change the aliasing to happen in `immutable.py` and then both imports would work from `sympy.matrices.immutable`.

**Comment by moorepants** [comment]
Ok, all previous imports should work as were before or you need to deprecate that import. We don't want to throw errors in people's code without a warning first.

**Comment by siefkenj** [comment]
I understand.  All previous imports should now work as they did before.

**Comment by asmeurer** [comment]
Looks good to me.

**Pull request merged**
