### PR TITLE
solveset is now able to solve XFAIL

### LINKED ISSUE #10214: solveset is not solving equations like sqrt(x) - const
There is an XFAIL test that indicates that solveset is doing something wrong: the following fails in master

```
solveset(x**(S(3)/2) + 4, x, S.Reals) == S.EmptySet
```

### PR DESCRIPTION
**Pull request by ishanaj**
Fixes #10214
closes #10460
Below is the `XFAIL` to which `solveset` currently gives  `{2*2**(1/3)}` which is wrong.
```
solveset(x**(S(3)/2) + 4, x, S.Reals) == S.EmptySet
```
Rational exponents with denominators divisible by `2` should return `EmptySet` for a -ve `rhs`(as in the above case).
 
ping @smichr @ylemkimon @Yathartha22

### CODE REVIEW

**Comment by smichr** [comment]
Please confirm, but I believe that #2 and #4 of the main issue are not resolved by this PR:

```
1.
>>> solveset(x**(S(3)/2) + 4, x, S.Reals)
EmptySet()
2.
>>> solveset(x**(S(3)) + 4, x, S.Reals)
{-2**(2/3)}
3.
>>> (x**(S(3)) + 4).subs(x,list(_)[0])
0
4.
>>> (x**(S(3)) + 4).subs(x,-(-2)**(2/S(3)))
0
```

(You might just open a new issue with those examples of the unresolved failure, otherwise if this is committed the issue will be closed with identified issues unresolved.)

**Comment by ishanaj** [comment]
@smichr  The above four cases give the correct result as you mentioned. I have added them to the test file.

**Comment by smichr** [comment]
As mentioned in the issue, case #2 should give two answers, u and v below:

```
>>> solveset(x**(S(3)) + 4, x, S.Reals)
{-2**(2/3)}
>>> v=list(_)[0]
>>> u=-(-2)**(2/S(3))
>>> (x**(S(3)) + 4).subs(x, u)  # so u is a solution...
0
>>> u == v  # and it was not found by solveset
False
```

**Comment by ishanaj** [comment]
@smichr solveset gives:
```
>>>solveset(x**(3) + 4, x)
{-2**(2/3), 2**(2/3)/2 - 2**(2/3)*sqrt(3)*I/2, 2**(2/3)/2 + 2**(2/3)*sqrt(3)*I/2}
```
Now, since the (total)number of solutions of an equation is equal to its degree. In the above example the degree is `3` and so there are 3 solutions for the equations(2 complex + 1 Real). Would it not be contradictory to have `-(-2)**(2/S(3))` as the fourth solution?

Also if we take the `u` and `v` as two real solutions for the equation, then the remaining one solution cannot be complex(as complex solutions occur in pair). Then again  a fourth solution would come out for a `3` degree equation.
[wolframalpha](http://www.wolframalpha.com/input/?i=solve+(x**(3)+%2B+4,+x)) gives it in other way, and the no. of sol =3.
[symbolab](https://www.symbolab.com/solver/step-by-step/x%5E%7B3%7D%2B4%3D0) also gives `3` solutions.

**Comment by ylemkimon** [comment]
`2**(2/3)/2 - 2**(2/3)*sqrt(3)*I/2 == -(-2)**(2/S(3))`

**Comment by smichr** [comment]
sorry for missing the Real restriction

**Comment by ishanaj** [comment]
Thanks

**Pull request merged**
