### PR TITLE
taylor term for asech

### PR DESCRIPTION
**Pull request by meghana-madhyastha**
The taylor_term function has been written for the other hyperbolic functions  (except for asech). There was a todo below it. In this PR, I've written the taylor_term function for asech.

### CODE REVIEW

**Comment by aktech** [comment]
Cool! Looks good to me. +1

**Comment by jksuom** [comment]
I wonder if this method should be named something else. Taylor series exists only at points where the function and its derivatives have been defined. There is no ``taylor_term`` method for ``asec`` which has a similar singularity at the origin.

**Comment by meghana1995** [comment]
@jksuom What do you suggest ?

**Comment by jksuom** [comment]
It is not easy to say... What we have here is a series expansion though not a power series. (Taylor series is a power series.) Maybe we could say ``expansion_term``.

**Comment by aktech** [comment]
I see this as a special case of Taylor series i.e. Maclaurin Series.

**Comment by jksuom** [comment]
In fact, it seems that the name ``taylor_term`` refers in SymPy to terms of a power series that is traditionally known as Maclaurin series. But maybe it is too late to change it... Anyway, this series is not a power series because it starts with the log term.

**Comment by meghana1995** [comment]
The problem with changing the name of the function 'taylor_term' to 'expansion_term' is that the function taylor_term is called in series. So the following will not work if I change the name.
 `assert asech(x).series(x, 0, 8) == log(2) - log(x) - x**2/4 - 3*x**4/32 - 5*x**6/96 + O(x**8)`

**Comment by jksuom** [comment]
The documentation is incomplete, but it seems that ``series`` is expected to produce only terms of a power series expansion (if that exists). So it should not be applied to ``asech(x)`` at all.

**Comment by meghana1995** [comment]
@jksuom Oh okay, I was not aware of that. I changed the name to `expansion_term()`

**Comment by aktech** [comment]
@jksuom 
This link: http://mathworld.wolfram.com/InverseHyperbolicSecant.html says `asech` has a Maclaurin series (special case of power series), I usually follow Wolfram's documentation though I am not sure if it's right.

**Comment by jksuom** [comment]
So it says, in fact. But I don't think that is a generally accepted term. The name 'Maclaurin series' has traditionally been used for the Taylor series centred at zero. It is always a power series and its coefficients are calculated from the values of the function and its derivatives at zero. The general Taylor series is calculated in the same way but in an arbitrary point where the function and its derivatives are defined. So, in this case, I don't agree with Wolfram's terminology.

**Comment by aktech** [comment]
@jksuom  I agree with your comment.

**Comment by meghana1995** [comment]
@jksuom @aktech . So what should be done now wrt the PR ? Should the name of the function be `expansion_term` or is this function altogether unnecessary due to the reasons discussed ?

**Comment by jksuom** [comment]
The series itself is valid (I think) even though it is not a power series. I don't see any reason why it could not be included as ``expansion_term``.

**Comment by aktech** [comment]
> The series itself is valid.

Yes, Indeed.

**Comment by meghana1995** [comment]
Oh okay that makes sense.  I changed the name and removed the series test in my last commit. Thank you for the feedback.

**Comment by leosartaj** [comment]
The series expansion of ``asech(x)`` can also be seen as a Formal Power Series. Here's what I get.

```
>>> fps(asech(x))
Limit(x**2/4 + log(x) + asech(x), x, 0) - log(x) - x**2/4 - 3*x**4/64 + O(x**6)
```
Apparently SymPy is not able to compute this limit.

The limit for 0+ should compute to log(2). Wolfram gives the same. However, terms do not appear to be correct. For eg. coefficient of ``x**4`` should be ``3/32`` and not ``3/64``.

**Comment by aktech** [comment]
I am not sure about `fps`, but simply getting the terms of the series through the function `expansion_term` gives correct results:

```ipython
In[28]: series = [asech(x).expansion_term(i, x) for i in range(12) if asech(x).expansion_term(i, x) != 0] 

In [29]: series
Out[29]: 
⎡          2       4       6        8        10   ⎤
⎢   ⎛2⎞  -x    -3⋅x    -5⋅x    -35⋅x    -63⋅x    ⎥
⎢log⎜─⎟, ────, ──────, ──────, ───────, ───────⎥
⎣   ⎝x⎠   4      32      96      1024     2560    ⎦
```

**Comment by jksuom** [comment]
I suspect that ``fps`` is wrong in this case. To reliably compute the power series expansion of
``log(x) + asech(x)``
one should first rewrite ``asech(x)`` as ``log(1/x + sqrt(1/x**2 - 1))`` and then combine the two logarithms so that the singularity at zero is cancelled. However, even the rewrite formula seems to be missing in SymPy and ``fps`` tries to work directly with the singular function ``asech``.

**Comment by meghana1995** [comment]
@jksuom @aktech The function `eval_rewrite_as_log` doesn't appear to exist in any of the hyperbolic functions. I have added it for asech along with a test.

**Comment by jksuom** [comment]
Where did the formula for the terms come from? They don't seem to agree with those given by [wikipedia](https://en.wikipedia.org/wiki/Inverse_hyperbolic_function). For example, it gives ``-35*x**6/288`` (unless I made a mistake in the computation).

**Comment by meghana1995** [comment]
I referred to this link. 
http://ddmf.msr-inria.inria.fr/1.9.1/ddmf?service=P0&rendering=jsMath&mac=&sf_id=sf_arcsech

**Comment by aktech** [comment]
@jksuom 
> For example, it gives -35*x**6/288 (unless I made a mistake in the computation).

Which formula are you using? It gives me `-5*x**6/96`

asech

**Comment by jksuom** [comment]
Oh, I see. It is the same after all, only not simplified.

**Comment by jksuom** [comment]
The failure of the PyPy test is puzzling. I'll restart it.

**Comment by jksuom** [comment]
Ok. +1

**Comment by aktech** [comment]
I am also +1 to this.
@leosartaj due you have any other issues with this?

**Comment by leosartaj** [comment]
I am +1 for this change. Although I will look into ``fps(asech(x))``, it calculates wrong coefficients.

**Comment by aktech** [comment]
Alright, Thanks @meghana1995  for your work. Merging.

**Comment by ArifAhmed1995** [comment]
@jksuom Naming the method as `expansion_term` does cause a lot of issues.
It's not possible to compute `asech.series()` or any limits involving `asech`. This is because of the `taylor_term` call in calculating series in `function.py`:
```
for i in range(nterms):
            g = self.taylor_term(i, arg, g)
            g = g.nseries(x, n=n, logx=logx)
            l.append(g)
```  
Would it be better to change it to `g = self.expansion_term(i, arg, g)` instead ?
Of course , all the `def taylor_term(n, x, *previous_terms)` would be changed as well.

**Pull request merged**
