### PR TITLE
feat(core): allow is_ge to take assumptions

### PR DESCRIPTION
**Pull request by JSS95**
#### Brief description of what is fixed or changed
Allow `is_ge`, `is_le`, `is_gt`, `is_lt` to take assumptions
Allow corresponding predicates to take assumptions

#### Other comments

Now, this behavior is possible.
```python
>>> is_ge(x, S(0), Q.positive(x))
True
```

This change does what #21203 does to `is_eq` and `is_neq`.

#### Release Notes

* core
  * `is_ge`, `is_le`, `is_gt`, `is_lt` now takes assumptions

### CODE REVIEW

**Comment by JSS95** [comment]
It seems that attempting to run `test_N6()` in `test_wester.py` takes extremely long time. Something is going wrong in SAT solver when inequality is passed...

**Comment by JSS95** [comment]
I am still working on this to fix the issue with `satask()`. `test_N6` in `test_wester` is taking extremely long time, which is apparently triggered by `satask(Q.extended_real(k*x**n), (x > y) & (y > 0) & (k > 0) & (n > 0))`...

**Comment by JSS95** [comment]
Done. Waiting for review...

**Comment by oscarbenjamin** [comment]
Can you run performance benchmarks comparing with master?

**Comment by JSS95** [comment]
@oscarbenjamin Running the benchmark showed no relevant performance change.

**Comment by oscarbenjamin** [comment]
This looks good to me.

What is the plan with this then? It makes it possible to use assumptions with `is_ge` etc so does that mean that you can use inequalities with `ask/refine`?

I would say that the most useful way to extend this would be making it possible to refine a Piecewise so that Integral/Sum could refine their integrand/summand and so that the Piecewise results returned by integrate can be simplified.

**Comment by JSS95** [comment]
@oscarbenjamin 
This change allows relation to be refined with unary predicate assumptions, which was impossible in master.

```python
In [1]: ask(Gt(x, 0), Q.positive(x))
Out[1]: True

In [2]: p = Piecewise((1, Gt(x,0)), (0, True))

In [3]: refine(p, Q.positive(x))
Out[3]: 1
```

Relation in assumption is not supported yet.

```python
In [4]: print(ask(Gt(x,0), Gt(x, -1)))
None
```

**Pull request merged**
