### PR TITLE
Simplified the algorithm of _af_pow

### PR DESCRIPTION
**Pull request by clueless-skywatcher**
Simplified the algorithm of the power calculating function by taking products iteratively.

### CODE REVIEW

**Comment by asmeurer** [comment]
There are lots of test failures. 

Anyway, what is the point of this change? It looks like it is less efficient than the current version.

**Comment by sanyamg123** [comment]
Can I look into this issue, or is it resolved?

**Comment by smichr** [comment]
> Can I look into this issue, or is it resolved?

Until someone documents that this is an issue, let's leave it alone.

**Comment by clueless-skywatcher** [comment]
Can you explain me the algorithm specified in the synpy library?

**Comment by asmeurer** [comment]
@clueless-skywatcher see https://en.wikipedia.org/wiki/Exponentiation_by_squaring

**Pull request closed without merging**
