### PR TITLE
py-dy license added

### LINKED ISSUE #15214: PyDy examples need to include the PyDy license
There is a new directory in `sympy/parsing/autolev/tests`:

```
│   ├── pydy-example-repo
│   │   ├── chaos_pendulum.al
│   │   ├── chaos_pendulum.py
│   │   ├── double_pendulum.al
│   │   ├── double_pendulum.py
│   │   ├── __init__.py
│   │   ├── mass_spring_damper.al
│   │   ├── mass_spring_damper.py
│   │   ├── non_min_pendulum.al
│   │   └── non_min_pendulum.py
```

These examples are copied from PyDy, but the PyDy license isn't included. I don't care personally, but we should probably follow protocol and include the PyDy license.

### PR DESCRIPTION
**Pull request by friyaz**
#### References to other Issues or PRs

Fixes #15214 

#### Brief description of what is fixed or changed
Added pydy license in  sympy/parsing/autolev/test-examples/pydy-example-repo as `pydy-license`
All files in `parsing/autolev/test-examples/pydy-example-repo` have pydy-license .

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by Abdullahjavednesar** [comment]
@certik if available, can you please have a look.

**Comment by certik** [comment]
@FrackeR011 what files does this license apply to?

**Comment by moorepants** [comment]
It should apply to some specific examples added in the autolev parser tests.

**Comment by certik** [comment]
Let's clarify which exact files have this license, I think that's important.

**Comment by moorepants** [comment]
Agreed, someone needs to look through them and figure out which ones cam from pydy.

**Comment by FrackeR011** [comment]
@NikhilPappu  should i write at top of pydy-license that this license is apllicabe to files in this folder or i need to do something else .

**Comment by czgdp1807** [comment]
@certik Please review this PR.

**Comment by certik** [comment]
Let's add the license to https://github.com/sympy/sympy/blob/c614f154d715d9f144a69b6ae479309be2fa5d14/LICENSE, and mention which files are covered by it.

**Comment by czgdp1807** [comment]
Closing this in favour of https://github.com/sympy/sympy/pull/17927

**Pull request closed without merging**
