### PR TITLE
1.4 release branch

### PR DESCRIPTION
**Pull request by asmeurer**
This is the release branch for the 1.4 release. Any changes that should go in 1.4 should be made as a PR to the `1.4` branch. 

**DO NOT MERGE THIS PR. I will merge it after the release is made.**

[List of open PRs against this branch](https://github.com/sympy/sympy/pulls?utf8=✓&q=is%3Apr+is%3Aopen+base%3A1.4).

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by Upabjojr** [comment]
Hi, I have just come round to fix some urgent bugs with matrix derivatives. Am I still on time for the 1.4 release?

**Comment by asmeurer** [comment]
If you can get them in within the next week or so that is fine. Make PRs against the `1.4` branch.

**Comment by asmeurer** [comment]
Also please mark any issues or pull requests with the 1.4 milestone so I am aware of them when I do the final checks before releasing.

**Comment by oscarbenjamin** [comment]
@Upabjojr there is plenty of time to get these PRs reviewed properly.

Self-merging should generally be frowned upon but here you are self-merging PRs immediately e.g. #16401 and #16397. I don't know if you intend to do the same with #16408.

I can see why you want to get these merged quickly so they go into 1.4. That's a good reason to request a review - it's not a good reason to self-merge like this. The fact that a new version is about to be released means it is the worst time for new unreviewed and not widely tested code to suddenly land in master.

Actually if you had waited for review then someone might have explained that it was already too late to merge into master since this branch had already been created. Those PRs should have been opened against this branch rather than master if you wanted them to get into 1.4. (I think it would be easy to fix that if they weren't already merged)

**Comment by Upabjojr** [comment]
> there is plenty of time to get these PRs reviewed properly.

The number of people reviewing the derivatives of matrices is fairly limited. I have cross-checked the results on http://www.matrixcalculus.org/

**Comment by oscarbenjamin** [comment]
> > there is plenty of time to get these PRs reviewed properly.
> 
> The number of people reviewing the derivatives of matrices is fairly limited. I have cross-checked the results on http://www.matrixcalculus.org/

This is an even stronger reason for *not* including last minute unreviewed patches in the next release.

**Comment by asmeurer** [comment]
Should #16401 and #16397 be backported to this branch? If they were based off a commit before I bumped the version in master we can do it with a simple merge commit (otherwise we have to cherry-pick).

**Comment by asmeurer** [comment]
The release script works again. I will probably try to merge https://github.com/sympy/sympy/pull/15121 first before making the release candidate.

**Comment by asmeurer** [comment]
@Upabjojr can you confirm that I fixed the merge conflicts with the matrix expressions code in https://github.com/sympy/sympy/pull/16388/commits/26632462ee5543206631465c676646bafa5d228e correctly?

**Comment by asmeurer** [comment]
Please merge this as soon as the tests pass.

**Pull request merged**
