### PR TITLE
now is_eq symifies the arugments passed

### LINKED ISSUE #21073: Bug in is_eq
I found this issue while workin on issue #21063 . 
```
>>> from sympy.core.relational import is_eq
>>> a = S.Zero
>>> b = 0
>>> is_eq(a,b)
Traceback (most recent call last):
  File "C:\Users\2acha\Desktop\GSOC\sympy\sympy\multipledispatch\dispatcher.py", line 234, in __call__
    func = self._cache[types]
KeyError: (<class 'sympy.core.numbers.Zero'>, <class 'int'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\2acha\Desktop\GSOC\sympy\sympy\core\relational.py", line 1314, in is_eq
    retval = _eval_is_eq(lhs, rhs)
  File "C:\Users\2acha\Desktop\GSOC\sympy\sympy\multipledispatch\dispatcher.py", line 238, in __call__
    raise NotImplementedError(
NotImplementedError: Could not find signature for _eval_is_eq: <Zero, int>
```

### PR DESCRIPTION
**Pull request by ghost**
#### References to other Issues or PRs
Fixes #21073

#### Brief description of what is fixed or changed
Now ``is_eq`` sympifies it's arguments
#### Release Notes

* core 
  * fixes a  bug in is_eq which led to a NotImplementedError

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Calling sympify all the time in internal code slows things down. It is deliberate that `is_eq` does not sympify the arguments.

**Comment by almighty123789** [comment]
> Calling sympify all the time in internal code slows things down. It is deliberate that `is_eq` does not sympify the arguments.

https://github.com/sympy/sympy/blob/b564d9ba2705ee2978766e1ee2102750834df68b/sympy/core/relational.py#L1222-L1234

Okay, in the worst case the expression can be pretty ugly and might be already sympified.  Is this behavior ( the error encountered)  intentional?

**Comment by oscarbenjamin** [comment]
> Okay, in the worst case the expression can be pretty ugly and might be already sympified. Is this behavior ( the error encountered) intentional?

I don't understand what you mean by this.

**Comment by almighty123789** [comment]
@oscarbenjamin, what I mean to say is
Is the above 'error' not an error, since is_eq explicitly makes clear that the argument passed mustalready  be sympified?

**Comment by oscarbenjamin** [comment]
> Is the above 'error' not an error, since is_eq explicitly makes clear that the argument passed mustalready be sympified?

Yes, exactly.

You would also get an error using `x.is_positive` if `x` was not sympified and was an `int` for example. It's important in each part of the codebase to know whether some object is expected to be sympified or not and we shouldn't just call sympify more times unnecessarily just in case.

**Pull request closed without merging**
