### PR TITLE
Add `parenthesize_super` option to LatexPrinter

### LINKED ISSUE #18215: Un-parenthesize superscripted symbol
Let's think of these superscripted symbols, x^{i}, x^{\*}

Currently, SymPy parenthesizes these symbols when they are taken to power:
\left(x^{i}\right)^{2}, \left(x^{*}\right)^{2}

However, LaTeX has its own way to represent these symbols without parentheses by nesting them:
 {x^{i}}^{2}, {x^{\*}}^{2}

These are distinguised from 'powered superscription's, which are:
 x^{i^{2}},  x^{\*^{2}}

Then, shouldn't it be better to print them without parentheses? As far as I know, that is the conventional way to print power of superscripted symbols.

In [this link](https://en.wikipedia.org/wiki/Non-dimensionalization_and_scaling_of_the_Navier–Stokes_equations#Non-dimensionalized_Navier%E2%80%93Stokes_equation), you can see that nabla sign is superscripted then powered without any parenthesis:
{\nabla^{\*}}^{2}

### PR DESCRIPTION
**Pull request by mcpl-sympy**
#### References to other Issues or PRs
Fixes #18215

#### Brief description of what is fixed or changed
 Added `parenthesize_super` option to `LatexPrinter`. With this option, user can choose whether the superscripted symbol will be parenthesized  or not when powered.

#### Other comments
This feature is expected to be useful when complex formula with various superscripted symbols is printed.  
This type of printing is conventional in some field of engineering, where dimensional analysis is done.

#### Release Notes

* printing
    * Added `parenthesize_super` option to `LatexPrinter`.

### CODE REVIEW

**Comment by ethankward** [comment]
Please add a test.

**Comment by mcpl-sympy** [comment]
@ethankward I have added a test. Could you please review it?

**Comment by mcpl-sympy** [comment]
Woops, tests have failed. I will fix and commit.

**Comment by mcpl-sympy** [comment]
@ethankward 
I have added the test. Could you review this?

**Comment by mcpl-sympy** [comment]
@ethankward
Please re-review this commit. Currently, this is ready to be merged.

**Comment by czgdp1807** [comment]
@mcpl-sympy Please resolve the conflicts.

**Comment by mcpl-sympy** [comment]
@czgdp1807
I have resolved the conflict. Please review it!

**Comment by mcpl-sympy** [comment]
ping @ethankward @czgdp1807

**Pull request merged**
