### PR TITLE
adding latex string option for bosonic operators

### PR DESCRIPTION
**Pull request by rajeev2010**
the bosonic operators did not have the option of latex output like the fermionic ones. i have added them now.

### CODE REVIEW

**Comment by moorepants** [comment]
This needs a unit test.

**Comment by rajeev2010** [comment]
@moorepants i have no idea how to do this. could you point me to the unit test for the corresponding fermionic operators in the same file.

**Comment by moorepants** [comment]
You should add a unit test like the ones found here: https://github.com/sympy/sympy/blob/master/sympy/printing/tests/test_latex.py that ensure that the correct latex form is produced. You can add the test to a new function in this file: https://github.com/sympy/sympy/blob/master/sympy/physics/tests/test_secondquant.py

**Comment by gxyd** [comment]
This PR has been inactive for quite sometime, so we are going to close it and open an issue to reference it. We try to keep our pull request queue small and focused on active work.  We encourage you to reopen the pull request if and when you continue to work on this. Please contact us if you have any questions.

Thanks for contributing.

see https://github.com/sympy/sympy/wiki/Closing-pull-requests for our policies on closing pull request.

I've opened https://github.com/sympy/sympy/issues/13526 for this pull request so that we don't forget about it.

**Pull request closed without merging**
