### PR TITLE
Added method and test for rewriting asinh as log

### PR DESCRIPTION
**Pull request by sandeepveethu**
Issue #10429 fixed. PR #10436 got a bit messy , so closed that and started afresh.

### CODE REVIEW

**Comment by sandeepveethu** [comment]
@aktech can you please review and merge this?

**Comment by leosartaj** [comment]
Please try to keep one PR per issue. Other than that this looks good.

**Comment by leosartaj** [comment]
Thanks @sandeepveethu

**Comment by sandeepveethu** [comment]
@leosartaj it was my first time , that's why it got all clumsy. I will take care of this next time. Thanks a lot for suggestions and support.

**Pull request merged**
