### PR TITLE
Trim some evaluations for min, max when evaluate=False

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

#16249

#### Brief description of what is fixed or changed

I've trimmed out some evaluations, for min, max. if `evaluate=False`

#### Release Notes

- functions
  - Unnecessary evaluations will be trimmed out, if `evaluate=False` is passed to Min, Max.

### CODE REVIEW

**Comment by smichr** [comment]
+1

**Comment by oscargus** [comment]
If only the tests had passed I would have merged it.

**Comment by sylee957** [comment]
I see the test failings are because of some output changes from the integrals.
I'm not sure if they are easy to change.

**Comment by sylee957** [comment]
Should the integrals pass `evaluate=True` to its sub expressions?

**Comment by smichr** [comment]
> integrals pass `evaluate=True` to its sub expressions?

yes: `integrate(foo)` and `Integral(foo).doit()` should pass along `evaluate=True` if necessary.

**Pull request merged**
