### PR TITLE
Added `.diff` to expr_with_intlimit

### LINKED ISSUE #20848: diff(Product(...)) does not evaluate the derivative
Usually Derivative gives an unevaluated derivative and doit is used to evaluate it:
```python
In [4]: Derivative(x**2, x)
Out[4]: 
d ⎛ 2⎞
──⎝x ⎠
dx    

In [5]: Derivative(x**2, x).doit()
Out[5]: 2⋅x

In [6]: diff(x**2, x)
Out[6]: 2⋅x
```
The diff function is used to create the derivative and call doit but it doesn't work with a Product:
```python
In [8]: Derivative(Product(x, (y, 1, z)), x)
Out[8]: 
  ⎛  z    ⎞
∂ ⎜─┬─┬─  ⎟
──⎜ │ │  x⎟
∂x⎜ │ │   ⎟
  ⎝y = 1  ⎠

In [9]: Derivative(Product(x, (y, 1, z)), x).doit()
Out[9]: 
 z  
x ⋅z
────
 x  

In [10]: diff(Product(x, (y, 1, z)), x)
Out[10]: 
  ⎛  z    ⎞
∂ ⎜─┬─┬─  ⎟
──⎜ │ │  x⎟
∂x⎜ │ │   ⎟
  ⎝y = 1  ⎠
```
Here `Out[10]` should be the same as `Out[9]`.

### PR DESCRIPTION
**Pull request by sidhu1012**
#### References to other Issues or PRs

Fixes #20848

#### Brief description of what is fixed or changed
Added `.diff` to `Expr_with_Intlimits` class.

#### Release Notes

* concrete
    * Derivative of Product is evaluated.

### CODE REVIEW

**Comment by asmeurer** [comment]
See the original issue. I'm not sure if recursively calling doit() is a good idea. It would be better to implement the derivative formulas directly, since they exist.

**Comment by sidhu1012** [comment]
> I'm not sure if recursively calling doit() is a good idea. It would be better to implement the derivative formulas directly, since they exist.

But I'm not sure for infinite terms in `Product`. `doit` seems quite reasonable .

**Comment by Maelstrom6** [comment]
This PR would have trouble with products that that consists of lots of terms. 

What about adding the following to sympy/concrete/products.py in `Product`:

```python
    def _eval_derivative(self, x):
        from sympy import Sum
        return self * Sum(self.function.diff(x) / self.function, self._args[1:], **self.assumptions0)
```
This works for infinite products as well. The result is correct as long as `self.function != 0`. I think adding a piecewise might be overkill though. 

I think the convention for `Integral`, `Sum` and `Product` is to leave the thing unevaluated as long as possible. Only doit when the user calls doit. I could be wrong about this, but if it is the case, then we should not call doit.

**Comment by sidhu1012** [comment]
@Maelstrom6 Yes it seems reasonable to me, I'll give it a try asap. I'm a bit occupied these days because of exams.
Thanks for the help!

**Comment by asmeurer** [comment]
> What about adding the following to sympy/concrete/products.py in Product:

The actual formula is more complicated than that. It should handle the case where the differentiation variable is in the limits (I guess it should be unevaluated. What does Sum do?), and it should handle there being multiple variables.

**Comment by Maelstrom6** [comment]
> The actual formula is more complicated than that. 

I think if the variable is not in the limit then it simplifies to that.

>It should handle the case where the differentiation variable is in the limits (I guess it should be unevaluated. What does Sum do?), 

Currently, I think Sum returns None if the arguments are in the limits:

https://github.com/sympy/sympy/blob/ef14666d718f147878b51ed7ba9a5192e16c04f3/sympy/concrete/summations.py#L299-L301

> and it should handle there being multiple variables.

I'm not sure I fully understand. Do you mean for example, `.diff(x, 2)` and `.diff(x, y)`? Or do you mean `Product(f(x, y), (x, 1, n), (y, 1, m))`?

**Comment by asmeurer** [comment]
I mean like `Product(f(x, y), (x, 1, n), (y, 1, m))`. Actually some corner cases like if the variable is a dummy variable may already be handled by diff itself, so it might not be as bad as I had thought.

**Comment by sidhu1012** [comment]
Closing in favor of #20925

**Pull request closed without merging**
