### PR TITLE
polys/domains: Improve `ANP.__init__()`.

### PR DESCRIPTION
**Pull request by skieffer**
#### Brief description of what is fixed or changed

In `ANP.__init__()`, ensure that the elements of the incoming `rep` are converted to the underlying domain whether
or not `rep` is a list.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
The test failure in the optional dependency tests has been seen in other PRs:
```
_____________ sympy/polys/tests/test_ring_series.py:test_nth_root ______________
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/polys/tests/test_ring_series.py", line 232, in test_nth_root
    assert rs_nth_root(8*x, 3, x, 3) == 2*x**QQ(1, 3)
  File "/home/runner/work/sympy/sympy/sympy/polys/ring_series.py", line 988, in rs_nth_root
    const = R(c**Rational(1, n))  # exponentiation with mpq object
TypeError: unsupported operand type(s) for ** or pow()
```
I think maybe it's a bug in an updated library or something.

**Comment by oscarbenjamin** [comment]
Yes, I just updated gmpy2 and I can see the failure on SymPy master:
```
$ pytest sympy/polys/tests/test_ring_series.py::test_nth_root
======================================== test session starts ========================================
platform linux -- Python 3.8.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
architecture: 64-bit
cache:        yes
ground types: gmpy 2.1.0

rootdir: /home/oscar/current/sympy/sympy.git, configfile: pytest.ini
plugins: forked-1.3.0, instafail-0.4.2, xdist-2.4.0
collected 1 item                                                                                    

sympy/polys/tests/test_ring_series.py F                                                       [100%]

============================================= FAILURES ==============================================
___________________________________________ test_nth_root ___________________________________________

    def test_nth_root():
        R, x, y = ring('x, y', QQ)
        assert rs_nth_root(1 + x**2*y, 4, x, 10) == -77*x**8*y**4/2048 + \
            7*x**6*y**3/128 - 3*x**4*y**2/32 + x**2*y/4 + 1
        assert rs_nth_root(1 + x*y + x**2*y**3, 3, x, 5) == -x**4*y**6/9 + \
            5*x**4*y**5/27 - 10*x**4*y**4/243 - 2*x**3*y**4/9 + 5*x**3*y**3/81 + \
            x**2*y**3/3 - x**2*y**2/9 + x*y/3 + 1
>       assert rs_nth_root(8*x, 3, x, 3) == 2*x**QQ(1, 3)

sympy/polys/tests/test_ring_series.py:232: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

p = 8, n = 3, x = x, prec = 2

    def rs_nth_root(p, n, x, prec):
        """
        Multivariate series expansion of the nth root of ``p``.
    
        Parameters
        ==========
    
        p : Expr
            The polynomial to computer the root of.
        n : integer
            The order of the root to be computed.
        x : :class:`~.PolyElement`
        prec : integer
            Order of the expanded series.
    
        Notes
        =====
    
        The result of this function is dependent on the ring over which the
        polynomial has been defined. If the answer involves a root of a constant,
        make sure that the polynomial is over a real field. It cannot yet handle
        roots of symbols.
    
        Examples
        ========
    
        >>> from sympy.polys.domains import QQ, RR
        >>> from sympy.polys.rings import ring
        >>> from sympy.polys.ring_series import rs_nth_root
        >>> R, x, y = ring('x, y', QQ)
        >>> rs_nth_root(1 + x + x*y, -3, x, 3)
        2/9*x**2*y**2 + 4/9*x**2*y + 2/9*x**2 - 1/3*x*y - 1/3*x + 1
        >>> R, x, y = ring('x, y', RR)
        >>> rs_nth_root(3 + x + x*y, 3, x, 2)
        0.160249952256379*x*y + 0.160249952256379*x + 1.44224957030741
        """
        if n == 0:
            if p == 0:
                raise ValueError('0**0 expression')
            else:
                return p.ring(1)
        if n == 1:
            return rs_trunc(p, x, prec)
        R = p.ring
        index = R.gens.index(x)
        m = min(p, key=lambda k: k[index])[index]
        p = mul_xin(p, index, -m)
        prec -= m
    
        if _has_constant_term(p - 1, x):
            zm = R.zero_monom
            c = p[zm]
            if R.domain is EX:
                c_expr = c.as_expr()
                const = c_expr**QQ(1, n)
            elif isinstance(c, PolyElement):
                try:
                    c_expr = c.as_expr()
                    const = R(c_expr**(QQ(1, n)))
                except ValueError:
                    raise DomainError("The given series cannot be expanded in "
                        "this domain.")
            else:
                try:                              # RealElement doesn't support
>                   const = R(c**Rational(1, n))  # exponentiation with mpq object
E                   TypeError: unsupported operand type(s) for ** or pow()

sympy/polys/ring_series.py:988: TypeError
                                          DO *NOT* COMMIT!                                          
====================================== short test summary info ======================================
FAILED sympy/polys/tests/test_ring_series.py::test_nth_root - TypeError: unsupported operand type(...
========================================= 1 failed in 0.33s =========================================
```

**Comment by oscarbenjamin** [comment]
With gmpy2 version 2.0.8 this works:
```
In [2]: from gmpy2 import mpq

In [3]: mpq(8, 1) ** Rational(1, 3)
Out[3]: 2
```
However with gmpy2 2.1.0 that gives:
```
In [2]: from gmpy2 import mpq

In [3]: mpq(8, 1) ** Rational(1, 3)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-04f112056598> in <module>
----> 1 mpq(8, 1) ** Rational(1, 3)

TypeError: unsupported operand type(s) for ** or pow()
```

**Comment by oscarbenjamin** [comment]
Looks like a bug in `mpq.__pow__`:
```python
In [1]: from gmpy2 import mpq

In [2]: mpq(8, 1).__pow__(Rational(1, 3))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-9b167a58b29f> in <module>
----> 1 mpq(8, 1).__pow__(Rational(1, 3))

TypeError: unsupported operand type(s) for ** or pow()
```
That should return `NotImplemented`

**Comment by oscarbenjamin** [comment]
A workaround is
```diff
diff --git a/sympy/polys/ring_series.py b/sympy/polys/ring_series.py
index 538db6d..573a0d7 100644
--- a/sympy/polys/ring_series.py
+++ b/sympy/polys/ring_series.py
@@ -985,7 +985,7 @@ def rs_nth_root(p, n, x, prec):
                     "this domain.")
         else:
             try:                              # RealElement doesn't support
-                const = R(c**Rational(1, n))  # exponentiation with mpq object
+                const = R(Rational(c)**Rational(1, n))  # exponentiation with mpq object
             except ValueError:                # as exponent
                 raise DomainError("The given series cannot be expanded in "
                     "this domain.")
```

**Comment by skieffer** [comment]
@oscarbenjamin -- Okay, now that the gmpy2 thing is patched, are you happy with this PR as a resolution of [this discussion](https://github.com/sympy/sympy/pull/22646#discussion_r767149498)?

**Pull request merged**
