### PR TITLE
Parsing:Improved variable naming in autolev parser

### LINKED ISSUE #15187: Improve variable naming in autolev parser
Here is an example output from #15165:

```python
import sympy.physics.mechanics as me
import sympy as sm
import math as m
import numpy as np

frame_c = me.ReferenceFrame('c')
frame_d = me.ReferenceFrame('d')
frame_f = me.ReferenceFrame('f')
fd, dc = me.dynamicsymbols('fd dc')
fdd, dcd = me.dynamicsymbols('fd dc', 1)
fdd2, dcd2 = me.dynamicsymbols('fd dc', 2)
r, l = sm.symbols('r l', real=True)
point_o = me.Point('o')
point_e = me.Point('e')
frame_d.orient(frame_f, 'Axis', [fd, frame_f.x])
frame_c.orient(frame_d, 'Axis', [dc, frame_d.y])
frame_c.set_ang_vel(frame_f, (frame_c.ang_vel_in(frame_f)).express(frame_f))
point_e.set_pos(point_o, r*frame_d.y-l*frame_c.x)
point_e.set_pos(point_o, (point_e.pos_from(point_o)).express(frame_d))
point_e.set_vel(frame_f, ((point_e.pos_from(point_o)).dt(frame_f)).express(frame_d))
point_e.set_acc(frame_f, ((point_e.vel(frame_f)).dt(frame_f)).express(frame_d))
```

Name clashes will vary likely happen with the primary import names: `me, sm, np`. There should at least be changed to `_me, _sm, _np` and even better there should be a check to ensure the Autolev code doesn't contain and reserved words and the properly handles them by adding underscores or some kind of pre/post fix. For example in autolev you might declare `MASS ME` as the mass of body E. This will clash with the output code `me`.

The automatic declaration of the time derivatives is currently:

```python
fd, dc = me.dynamicsymbols('fd dc')
fdd, dcd = me.dynamicsymbols('fd dc', 1)
fdd2, dcd2 = me.dynamicsymbols('fd dc', 2)
```

A simple improvement would be:

```python
fd, dc = me.dynamicsymbols('fd dc')
fd_d, dc_d = me.dynamicsymbols('fd dc', 1)
fd_dd, dc_dd = me.dynamicsymbols('fd dc', 2)
```

Where `_d, _dd, _ddd`, etc is dot, double dot, triple dot, etc.

### PR DESCRIPTION
**Pull request by ayushmankoul**
Fixes #15187

#### Brief description of what is fixed or changed
Added underscore in prefix of all occurences of `me.`,`sm.`,`np.` and `"d"` and in `str_func(z)`,
changed `"d" + str(z)` to `"_d" * z` in `sympy/parsing/autolev/_listener_autolev_antlr.py`
to avoid name clashes which very likely happen with the primary import names: me, sm, np

#### Release Notes

* parsing
   *  Improved variable naming in autolev parser

### CODE REVIEW

**Comment by ayushmankoul** [comment]
@NikhilPappu I have raised new PR for this issue.Should I close my earlier pull request now ?

**Comment by NikhilPappu** [comment]
@ayushmankoul This new PR isn't required. As far as I know, you should be able to push these changes to the previous one by reforking. This is better as the whole discussion took place in the old one.

**Comment by ayushmankoul** [comment]
@NikhilPappu Could you please review this code ? If any amendments are supposed to be done,please let me know.

**Comment by NikhilPappu** [comment]
@ayushmankoul Try to rerun the tests. Close the PR and open it again to do this.

**Comment by NikhilPappu** [comment]
@ayushmankoul Please do not create duplicate PRs. Reopen this one to rerun the Travis tests.

**Comment by ayushmankoul** [comment]
@NikhilPappu  Should I close the new PR ?

**Comment by NikhilPappu** [comment]
@ayushmankoul Yes and reopen this one.

**Comment by ayushmankoul** [comment]
@NikhilPappu  Sorry I am not able to reopen this pull request since I have created new branch with changes in code to create the PR.

**Pull request closed without merging**
