### PR TITLE
Hint for how to tweak docstring output in lambdify

### PR DESCRIPTION
**Pull request by bjodah**
#### References to other Issues or PRs

see gh-24754

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by brocksam** [comment]
The `lambdify` tests that I wrote for `docstring_limit` explicitly test the docstring. So if the replacement messages are changed (like they are in this PR), they also need to be changed in those tests.

**Comment by bjodah** [comment]
@brocksam I see , thanks. I was missing the docstring the other day and couldn't remember what the new option was called, so I think this might be helpful for others too. Worth noting, perhaps, was that the source code of my generated function wasn't very long, maybe 10 lines or so (thanks to passing `cse=True`).

**Comment by moorepants** [comment]
LGTM to merge once required tests pass.

**Review by brocksam — COMMENTED** [review]
LGTM too, I agree it's helpful to point users to `docstring_limit`. And thank you for fixing the inconsistency in single vs double quotes in those two modules that I introduced by mistake in my last PR.

**Comment by brocksam** [comment]
See #24873 for why the non-required mypy job in CI is failing.

**Comment by bjodah** [comment]
Thanks!

**Pull request merged**
