### PR TITLE
Various fixes to code generation code

### PR DESCRIPTION
**Pull request by asmeurer**
These are various fixes to the code generation code that I see as I go over it. This can be merged at any time, but I will probably end up adding more stuff until I finish going over the code.

### CODE REVIEW

**Comment by moorepants** [comment]
Looks fine to me, +1.

**Comment by bjodah** [comment]
Look good to me.

**Comment by scopatz** [comment]
Also looks good to me.

**Comment by asmeurer** [comment]
OK, nothing new here for a while, so I'll merge. Any additional changes will go in a new PR.

**Pull request merged**
