### PR TITLE
maint(ci): run benchmarks in GitHub Actions

### PR DESCRIPTION
**Pull request by oscarbenjamin**
This commit adds a benchmarks job to run in GitHub Actions for each push
to a PR. Significant benchmark differences will be reported to the PR in
a comment from the GitHub Actions bot.

#### References to other Issues or PRs

See https://github.com/sympy/sympy/issues/20374 and related PRs. Benchmarks are one of the features that sympy used with Travis that did not get migrated to Actions.

#### Brief description of what is fixed or changed

Runs the benchmarks in GitHub Actions. This will compare timings for a PR against current master and also master vs the previous release. The results of running the benchmarks are stored as an artifact in Actions and can be downloaded from the Actions web UI. Any particularly slow/fast differences (threshold 1.5x) between either the PR and master or between master and the previous release (currently 1.8) are reported to the PR in a comment by the GitHub Actions bot.

The workflow that adds the PR comment won't run until after this is merged but I have already merged it to my fork. You can open a PR against my fork to test this out. I've already opened one here and the comment looks like this: https://github.com/oscarbenjamin/sympy/pull/31#issuecomment-881923642 (which I've also copied into the comment below in this PR).

#### Other comments

Later I would also like to extend this to reporting diff coverage on the PR.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Benchmark results from GitHub Actions

Lower numbers are good, higher numbers are bad. A ratio less than 1
means a speed up and greater than 1 means a slowdown. Green lines
beginning with `+` are slowdowns (the PR is slower then master or
master is slower than the previous release). Red lines beginning
with `-` are speedups.

Significantly changed benchmark results (PR vs master)
```diff

```
Significantly changed benchmark results (master vs previous release)
```diff
       before           after         ratio
     [ed9a550f]       [ba1ad57f]
+      1.05±0.04s       2.12±0.01s     2.03  dsolve.TimeDsolve01.time_dsolve
+        78.4±3μs      2.93±0.05ms    37.38  matrices.TimeDiagonalEigenvals.time_eigenvals
-      5.51±0.2ms       3.27±0.1ms     0.59  solve.TimeRationalSystem.time_linsolve(10)

```
Full benchmark results can be found as artifacts in GitHub Actions
(click on checks at the top of the PR).

**Comment by oscarbenjamin** [comment]
Any opinions on this?

I'll merge this if I don't hear back soon.

**Comment by moorepants** [comment]
Looks good to me. Thanks!

**Comment by moorepants** [comment]
The concept and results are good, but I don't know all the details of how actions work yet, so I can't comment on the implementation.

**Comment by oscarbenjamin** [comment]
We can always disable it later if it turns out to be problematic

**Pull request merged**
