### PR TITLE
Pull request template Improvements, round 2

### PR DESCRIPTION
**Pull request by asmeurer**
People still aren't getting the "fixes #NNNN" thing. See for instance https://github.com/sympy/sympy/pull/13757.

Reading the current template, it's not surprising, as it's a bit ambiguous. This simplies the text a great bit and also adds a link to https://github.com/blog/1506-closing-issues-via-pull-requests. 

CC @smichr @gxyd

### CODE REVIEW

**Review by gxyd — APPROVED** [review]
Yay. Having a blog link is good. +1

**Comment by ylemkimon** [comment]
Also I think there should be a checklist or reminder that tests, at least code quality tests, pass.

**Comment by asmeurer** [comment]
I'm not as worried about that, because Travis will fail.

**Comment by smichr** [comment]
> This simplies the text a great bit

The first part of the sentence was to guide them in referring to the issue -- put `#` before issues numbers that your refer to. The second part was to guide them in how to close an issue by putting `fix` before it.

Put '#' before an issue or PR that you want to refer to, e.g. In #123 there was a problem...
Put 'Fixes' before an issue if it is fixed by your PR, e.g. fixes #234

Your call...may the odds be ever in your favor!

**Comment by asmeurer** [comment]
When I read it myself it was confusing. It wasn't really clear that you need "fixes #NNNN" exactly.  And you can see from my example that it wasn't being done. 

We don't have to tell people how to do everything in the PR template. Every extra word in the template adds to the chance that it won't be read at all. I'd rather have very little text there, for only the most important stuff, and leave the less critical things to the development guide. People referring to issues without using # isn't as big of a deal as not using the fixes format. The former just means the issue won't be cross-referenced correctly. The latter means the issue won't be closed. Both can be fixed, even by maintainers, and for each, you really just have to teach people to do it.

**Comment by smichr** [comment]
Not sure if I or you are misunderstanding...you don't have to have the fixes keyword alone on a line by itself. The only requirement us that there be nothing but space  between the fixes and the hash sign. Unless it has been changed, the issue you cite as havi g an error not the format looks fine to me. See also the end of the discussion at https://help.github.com/articles/closing-issues-using-keywords/ where a sentence like example is given.

**Comment by asmeurer** [comment]
The linked issue has since been fixed (I guess I should have taken a screenshot). It originally said "fixes issue #NNNN". Look at your email notifications if you get them.

**Pull request merged**
