### PR TITLE
unset_show now works with TextBackend too

### PR DESCRIPTION
**Pull request by jashan498**
#### Brief description of what is fixed or changed
Also added `unset_show` in `utilities/runtests` to stop showing up of plots in doctest.

Based on conversation happened on Gitter.
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
I'm curious why this didn't already show up in the Travis tests? Are the plotting doctests skipped if matplotlib isn't installed?

**Comment by jashan498** [comment]
Plotting doctests are not skipped by default. `doctest_depends_on` decorator is used ( [like here](https://github.com/sympy/sympy/blob/246edcd4edc061b4bc34dd3f37e9164e2aeb9472/sympy/plotting/plot.py#L221)) to skip `doctest` in such cases.

**Comment by jashan498** [comment]
yeah they are skipped due to [doctest_depends_on](https://github.com/sympy/sympy/blob/246edcd4edc061b4bc34dd3f37e9164e2aeb9472/sympy/plotting/plot.py#L221) decorator used for those methods.

**Comment by asmeurer** [comment]
So should remove those decorators since the plotting still does work with textplot?

**Comment by jksuom** [comment]
This looks good to me. There should be no reason to treat the two plotting backends differently in general. There is an `unset_show()` concerning `matplotlib` alone in `runtests`. That could probably be removed now.

**Comment by jksuom** [comment]
Thanks, merging.

**Pull request merged**
