### PR TITLE
Use already imported constants

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

One may argue if one should import more constants, but I went with the ones already imported.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by smichr** [comment]
Comment [here](https://github.com/sympy/sympy/issues/8062#issuecomment-56119599) might explain error -- didn't look real close but recall similar issues in the past.

**Comment by oscargus** [comment]
Hmm, I seem to recall having tested something like `S.EulerGamma == EulerGamma` but will look into it.

**Comment by oscargus** [comment]
Strange, `EulerGamma == S.EulerGamma`, and this line, which has been around for 12 or so years uses it (so probably not tested?):

https://github.com/sympy/sympy/blob/170f32e377ea8b72cd20f5941e262924c09259a8/sympy/functions/special/error_functions.py#L1790

Anyway, changed that and all the others back to `S.EulerGamma`, which I hope should fix all tests (only tested a few locally).

**Comment by oscargus** [comment]
Ahh, importing `EulerGamma` from `core` is not the same as importing from `core.numbers`...

**Comment by smichr** [comment]
Did you search for `from sympy.core import.*((pi)|I|etc...)` to see if there are other instances that should be changed to an import from numbers?

**Comment by oscargus** [comment]
No. We both spent quite some time last year(?) to specify the import locations, so just fixed some in functiions.

**Pull request merged**
