### PR TITLE
ReferenceFrame and Body should be analagous

### LINKED ISSUE #21964: Make `Body` and `ReferenceFrame` analogous
`Body` and `ReferenceFrame` are analogous in dynamics, and all the joint classes , jointsmethod and class body follow it, but rest of physics module doesn't.

Example - 

```
>>> A = Body('A')
>>> N = ReferenceFrame('N')
>>> A.dcm(N) # Works
>>> A.dcm(A) # Works

>>> N.dcm('A') # Error but should work

```

So where ever ReferenceFrame works on being passed as arg, passing body to same arg should also work.

It can be done simply by - 
```
if isinstance(frame, Body):
    frame = Body.frame
```

cc - @moorepants

### PR DESCRIPTION
**Pull request by rari459**
#### References to other Issues or PRs
Fixes #21964

#### Brief description of what is fixed or changed
Made the ReferenceFrame and Body objects identical whenever these objects are passed into the function

#### Release Notes

physics.mechanics
- ReferenceFrame and Body should be analagous

### CODE REVIEW

**Comment by faze-geek** [comment]
What is the motivation behind this pull request ? I would like to report that there is already a PR opened with similar code diff #21974 which has passed checks ,has added tests and is also partially reviewed /under review.

As far as the checks this pull request is failing -
1 . Your release notes should be in the format as per -https://github.com/sympy/sympy/wiki/Writing-Release-Notes
      in this case it should be -

* physics.mechanics
  *  ReferenceFrame and Body should be analagous 
 
2 . You will need to add yourself to the .mailmap file as described here to get rid of failing authors test:
https://github.com/sympy/sympy/wiki/Development-workflow#add-your-name-and-email-address-to-the-mailmap-file

**Comment by moorepants** [comment]
Yes, I think we'd rather see #21974 go in. If that author hasn't worked on it, you could possibly take it over.

cc/ @mohajain @sidhu1012

**Comment by sidhu1012** [comment]
@moorepants I will be active from next month most probably. 

Until then @mostlyaman  you can take over if you want.

**Comment by sidhu1012** [comment]
@rari459 You planning to finish it?

**Comment by tjstienstra** [comment]
Closing as `Body` has been deprecated.

**Pull request closed without merging**
