### PR TITLE
check for reality of expression

### LINKED ISSUE #11581: conjugate of real expression should not change expression
The square root of a real quantity does not seem to be detected as real. The last two expressions are not evaluated as 0.
```
x, y = symbols("x, y", real=True)
r = sqrt(x**2+y**2)
simplify(conjugate(r)-r)
simplify(conjugate(re(r))-r)
```

### PR DESCRIPTION
**Pull request by mzaffalon**
following suggestion by smichr
added tests
addresses #11581
[cps adds that this fixes #11581]

### CODE REVIEW

**Comment by smichr** [comment]
:warning: The issue will not be automatically closed with the format you have in the opening paragraph. A variant of 3 words (fix, close, resolve) must be used as [documented here](https://help.github.com/articles/closing-issues-via-commit-messages/). The reference can be in a commit message or the opening paragraph.

Other than that, this looks fine to me.

**Review by smichr — APPROVED** [review]
A simple test for a real argument leaves a real argument unmodified by the `conjugate` function.

**Comment by smichr** [comment]
Thanks for working on this and having the grit to get past git :smile: . This is in.

**Comment by mzaffalon** [comment]
You did most of the work. And thank you for the encouragement.

**Pull request merged**
