### PR TITLE
Lambert touchUp

### PR DESCRIPTION
**Pull request by MaqOwais**
Tried to make a better version according to the latest updates as well as removing some errors accordingly

#14972,#18759
* solvers
  * improve solving of Lambert 

From #14792 here's the finishing touch up. 
Herewith cases we are going to discuss more below accordingly.

### Case(1):
**Here we see an error message specifically in `.subs` case so, here I modified accordingly and finally arrived to required solution.**
### Input :
```
solveset_real((x**2 - 2*x + 1).subs(x, log(x) + 3*x), x)
solveset_real((x**2 - 2*x + 1).subs(x, (log(x) + 3*x)**2 - 1), x)
solveset_real((x**2 - 2*x - 2).subs(x, log(x) + 3*x), x) 
```

### After Modification :
```
FiniteSet(LambertW(3*E)/3)

FiniteSet(LambertW(3*exp(sqrt(2)))/3, LambertW(3*exp(-sqrt(2)))/3)

FiniteSet(LambertW(3*exp(1 + sqrt(3)))/3, LambertW(3*exp(1 - sqrt(3)))/3)
```

### Case(2):
**Here, It was returning the complex solutions, but the requirement is only to get real solution hence accordingly modified.**
### Input:
```
solveset_real((a/x + exp(x/2)).diff(x, 2), x)

solveset_real(3*x + 5 + 2**(-5*x + 3), x)     
```
### Output:

> Complement(FiniteSet(6*LambertW((-a)**(1/3)/3), 6*LambertW(-(-a)**(1/3)/6 - sqrt(3)*I*(-a)**(1/3)/6), 6*LambertW(-(-a)**(1/3)/6 + sqrt(3)*I*(-a)**(1/3)/6)), FiniteSet(0))
> FiniteSet(-5/3 + LambertW(-10240*2**(1/3)*log(2)/3)/(5*log(2)), -5/3 + 
> LambertW(-5*(-1024*2**(1/3) - 1024*2**(1/3)*sqrt(3)*I)*log(2)/3)/(5*log(2)), -5/3 + 
> LambertW(-5*(-1024*2**(1/3) + 1024*2**(1/3)*sqrt(3)*I)*log(2)/3)/(5*log(2)))

### After Modification:
```
Complement(FiniteSet(6*LambertW((-a)**(1/3)/3)), FiniteSet(0))
FiniteSet(-5/3 + LambertW(-10240*2**(1/3)*log(2)/3)/(5*log(2)))
```
### Input:
```
`p = symbols('p', positive=True)`
`eq = 3*log(p**(3*x + 5)) + p**(3*x + 5)`
`solveset(eq, x)`
`solveset_real(eq, x)`
```
### After Modification: 
```
FiniteSet(-5/3 - LambertW(1/3)/(3*log(p)))
FiniteSet(-5/3 - LambertW(1/3)/(3*log(p)))
```
### Input :
```
solveset_real(2*x + 5 + log(3*x - 2), x)
```

### After Modification:
```
FiniteSet(LambertW(2*exp(-19/3)/3)/2 + 2/3)
```

**I'm really fascinated by the work on Lambert equations(obviously huge credit specifically goes to  @smichr 
 @Yathartha22 @jmig5776 and others) as it solves more such varieties of problems, hence increasing the domain of solving the equations in a more specific manner.**

_But some more such equations are to be solved in `solveset_real,` where the solutions are obtained by `solve` method but instead we are not getting it with `solveset_real` so more work has to be done considering all cases ._

I'm really glad to have further discussions and also to work on it.

NO ENTRY

### CODE REVIEW

**Comment by MaqOwais** [comment]
I think everything is all right!?

**Comment by sidhu1012** [comment]
> I think everything is all right!?

This test failed

`Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/testing/runtests.py", line 1343, in _timeout
    function()
  File "/home/runner/work/sympy/sympy/sympy/testing/pytest.py", line 174, in func_wrapper
    func()
  File "/home/runner/work/sympy/sympy/sympy/solvers/ode/tests/test_systems.py", line 1315, in test_sysode_linear_neq_order1_type4
    assert dsolve(eqs7, simplify=False, doit=False) == sol7
AssertionError`

**Comment by MaqOwais** [comment]
> Traceback (most recent call last):
> File "/home/runner/work/sympy/sympy/sympy/testing/runtests.py", line 1343, in _timeout
> function()
> File "/home/runner/work/sympy/sympy/sympy/testing/pytest.py", line 174, in func_wrapper
> func()
> File "/home/runner/work/sympy/sympy/sympy/solvers/ode/tests/test_systems.py", line 1315, in test_sysode_linear_neq_order1_type4
> assert dsolve(eqs7, simplify=False, doit=False) == sol7
> AssertionError

But locally there's no such problem!

**Comment by oscarbenjamin** [comment]
I get the same failure locally:
```console
$ pytest sympy/solvers/ode/tests/test_systems.py::test_sysode_linear_neq_order1_type4/Users/enojb/current/sympy/38venv/lib/python3.8/site-packages/_pytest/compat.py:333: PytestDeprecationWarning: The TerminalReporter.writer attribute is deprecated, use TerminalReporter._tw instead at your own risk.
See https://docs.pytest.org/en/latest/deprecations.html#terminalreporter-writer for more information.
  return getattr(object, name, default)
====================================================== test session starts =======================================================
platform darwin -- Python 3.8.1, pytest-5.4.3, py-1.8.1, pluggy-0.13.1
architecture: 64-bit
cache:        yes
ground types: gmpy 2.0.8

rootdir: /Users/enojb/current/sympy/sympy, inifile: pytest.ini
plugins: doctestplus-0.7.0, instafail-0.4.2, xonsh-0.9.13.dev1, cov-2.10.0, profiling-1.7.0, forked-1.1.3, xdist-1.32.0
collected 1 item                                                                                                                 

sympy/solvers/ode/tests/test_systems.py F                                                                                  [100%]

============================================================ FAILURES ============================================================
______________________________________________ test_sysode_linear_neq_order1_type4 _______________________________________________

        eqs7 = [Eq(Derivative(f(x), x), (f(x) + g(x) + h(x))*log(x) + sin(x)), Eq(Derivative(g(x), x), (f(x) + g(x)
                + h(x))*log(x) + sin(x)), Eq(Derivative(h(x), x), (f(x) + g(x) + h(x))*log(x) + sin(x))]
        sol7 = [Eq(f(x), -C1/3 - C2/3 + 2*C3/3 + (C1/3 + C2/3 +
                    C3/3)*exp(x*(3*log(x) - 3)) + exp(x*(3*log(x) -
                        3))*Integral(exp(3*x)*exp(-3*x*log(x))*sin(x), x)),
                Eq(g(x), 2*C1/3 - C2/3 - C3/3 + (C1/3 + C2/3 +
                    C3/3)*exp(x*(3*log(x) - 3)) + exp(x*(3*log(x) -
                        3))*Integral(exp(3*x)*exp(-3*x*log(x))*sin(x), x)),
                Eq(h(x), -C1/3 + 2*C2/3 - C3/3 + (C1/3 + C2/3 +
                    C3/3)*exp(x*(3*log(x) - 3)) + exp(x*(3*log(x) -
                        3))*Integral(exp(3*x)*exp(-3*x*log(x))*sin(x), x))]
        with dotprodsimp(True):
>           assert dsolve(eqs7, simplify=False, doit=False) == sol7
E           assert [Eq(f(x), -C1...log(x) - x)))] == [Eq(f(x), -C1...)*sin(x), x))]
E             At index 0 diff: Eq(f(x), -C1 - C2 + C3*exp(x*(3*log(x) - 3)) + exp(x*(3*log(x) - 3))*Integral(exp(-3*x_)*sin(E*exp(LambertW(x_*exp(-1))))/(log(exp(LambertW(x_*exp(-1)))) + 1), (x_, x*log(x) - x))) != Eq(f(x), -C1/3 - C2/3 + 2*C3/3 + (C1/3 + C2/3 + C3/3)*exp(x*(3*log(x) - 3)) + exp(x*(3*log(x) - 3))*Integral(exp(3*x)*exp(-3*x*log(x))*sin(x), x))
E             Use -v to get the full diff

sympy/solvers/ode/tests/test_systems.py:1315: AssertionError
                                                         DO *NOT* COMMIT!                                                         
==================================================== short test summary info =====================================================
FAILED sympy/solvers/ode/tests/test_systems.py::test_sysode_linear_neq_order1_type4 - assert [Eq(f(x), -C1...log(x) - x)))] == ...
================================================= 1 failed in 746.93s (0:12:26) ==================================================
```
I'm guessing that the form of the solution has now changed because it either can or can't solve some equation as part of the process

**Comment by MaqOwais** [comment]
> I'm guessing that the form of the solution has now changed because it either can or can't solve some equation as part of the process

But what it has to do with lambert! 
I mean there is no such dependency with the modification made over here!

**Comment by oscarbenjamin** [comment]
> But what it has to do with lambert!

Inside `dsolve` it calls `solveset` here:
https://github.com/sympy/sympy/blob/425353e982439dc64f3d33876cce291aac628ed8/sympy/solvers/ode/systems.py#L325-L330

For this particular system of ODEs that calls:
```
solveset(Eq(y, x*log(x) - x), x)
```
This PR has changed the output of that meaning that a different solution is returned for the system of ODEs.

The new solution is
```
_x = Dummy('x')

I1 = Integral(exp(-3*_x)*sin(E*exp(LambertW(_x*exp(-1))))/(log(exp(LambertW(_x*exp(-1)))) + 1), (_x, x*log(x) - x))

sol7 = [
    Eq(f(x), -C1 - C2 + C3*exp(x*(3*log(x) - 3)) + I1*exp(x*(3*log(x) - 3))),
    Eq(g(x), C1 + C3*exp(x*(3*log(x) - 3)) + I1*exp(x*(3*log(x) - 3))),
    Eq(h(x), C2 + C3*exp(x*(3*log(x) - 3)) + I1*exp(x*(3*log(x) - 3))),
]
```

That integral looks quite messy:
```
In [27]: I1                                                                                                                       
Out[27]: 
x⋅log(x) - x                          
     ⌠                                
     ⎮                ⎛    ⎛   -1⎞⎞   
     ⎮        -3⋅x    ⎜   W⎝x⋅ℯ  ⎠⎟   
     ⎮       ℯ    ⋅sin⎝ℯ⋅ℯ        ⎠   
     ⎮       ────────────────────── dx
     ⎮            ⎛  ⎛   -1⎞⎞         
     ⎮            ⎜ W⎝x⋅ℯ  ⎠⎟         
     ⎮         log⎝ℯ        ⎠ + 1     
     ⌡
```

Is the output given here by `solveset` correct though? We get:
```
In [1]: solveset(Eq(y, x*log(x) - x), x)                                                                                          
Out[1]: 
⎧  ⎛   -1⎞    ⎫
⎨ W⎝y⋅ℯ  ⎠ + 1⎬
⎩ℯ            ⎭
```
Plotting that function shows that for `-1 < y < 0` there should be two real roots. For `y < -1` there are no real roots. There are probably infinitely many complex roots.

**Comment by MaqOwais** [comment]
Finally, I got this 

```
>>> dsolve(eqs7, simplify=False, doit=False)

[
Eq(f(x), -C1 - C2 + C3*exp(x*(3*log(x) - 3)) + exp(x*(3*log(x) - 3))*Integral(exp(-3*x_)*sin(E*exp(LambertW(x_*exp(-1))))/(log(exp(LambertW(x_*exp(-1)))) + 1), (x_, x*log(x) - x))), 


Eq(g(x), C1 + C3*exp(x*(3*log(x) - 3)) + exp(x*(3*log(x) - 3))*Integral(exp(-3*x_)*sin(E*exp(LambertW(x_*exp(-1))))/(log(exp(LambertW(x_*exp(-1)))) + 1), (x_, x*log(x) - x))), 


Eq(h(x), C2 + C3*exp(x*(3*log(x) - 3)) + exp(x*(3*log(x) - 3))*Integral(exp(-3*x_)*sin(E*exp(LambertW(x_*exp(-1))))/(log(exp(LambertW(x_*exp(-1)))) + 1), (x_, x*log(x) - x)))

]
```

I think the solution should be modified as per this new solution by considering the lambert part!

**Comment by oscarbenjamin** [comment]
> I think the solution should be modified as per this new solution by considering the lambert part!

The solution returned by `dsolve` does appear to be correct so we could change the test but there are two problems. The first is that this test now takes too long and so it should be marked as "too slow for Travis".

The second is that the output from `solveset` is not really correct in this case. You can see that the intention of calling solveset in dsolve is to see if the function is invertible. If you plot `x*log(x) - x` though you can see that it is not invertible for real `x` with `0 < x < E`. The domain in this example is not even the Reals though so in fact there are most likely infinitely many solutions over the complex numbers but `solveset` only returns the solution for a single branch.

Maybe that's a more general problem though e.g.:
```
In [38]: solveset(x*exp(x)-10, x)                                                                                                 
Out[38]: {W(10)}
```
There should be infinitely many values there like
```
In [49]: ImageSet(Lambda(n, LambertW(10, n)), Integers)                                                                           
Out[49]: {W(10, n) | n ∊ ℤ}
```

**Comment by MaqOwais** [comment]
> The second is that the output from solveset is not really correct in this case. You can see that the intention of calling solveset in dsolve is to see if the function is invertible. If you plot x*log(x) - x though you can see that it is not invertible for real x with 0 < x < E. The domain in this example is not even the Reals though so in fact there are most likely infinitely many solutions over the complex numbers but solveset only returns the solution for a single branch.

So the conclusion is lambert equations should be modified further for imaginary terms !?

**Comment by MaqOwais** [comment]
> There should be infinitely many values there like
> 
> In [49]: ImageSet(Lambda(n, LambertW(10, n)), Integers)                                                                           
> Out[49]: {W(10, n) | n ∊ ℤ}

I think this is not the correct way of representation for imaginary roots for lambert solutions .

**Comment by oscarbenjamin** [comment]
> I think this is not the correct way of representation for imaginary roots for lambert solutions .

Why not?

The situation here is analogous to this:
```python
In [40]: solveset(exp(x)-1, x)                                                                                                    
Out[40]: {2⋅n⋅ⅈ⋅π | n ∊ ℤ}

In [41]: solveset(exp(x)-1, x, Reals)                                                                                             
Out[41]: {0}
```

You can check numerically that this generates solutions:
```python
In [32]: eq = x*exp(x)-10                                                                                                         

In [33]: for n in range(-5, 5): 
    ...:     print(eq.subs(x, LambertW(10, n)).n(chop=True)) 
    ...:                                                                                                                          
0
0
0
0
0
0
0
0
0
0
```
The general principle of `solveset` is that unless it's possible to find a complete solution set then we should end up with a `ConditionSet`.

**Comment by MaqOwais** [comment]
> In [32]: eq = x*exp(x)-10                                                                                                         
> 
> In [33]: for n in range(-5, 5): 
>     ...:     print(eq.subs(x, LambertW(10, n)).n(chop=True)) 
>     ...:                                                                                                                          
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0

AWESOME!!

> So the conclusion is lambert part should be modified further for imaginary terms !?


Any other suggestions?

**Comment by oscarbenjamin** [comment]
We do not necessarily need to make sure that `solveset` returns the complete solution set in all cases but we should make sure that it returns a `ConditionSet` unless we are certain that what we would return is the complete solution set. That's part of the guarantee of `solveset` so anything else is a bug. Returning a ConditionSet is not a bug but it is often not the ideal result.

The current code seems to be only valid for Reals and is not always valid in that case either. We need to guard the results from Lambert somehow to make sure that we only return Lambert solutions over the Reals and we only return one or two solutions in the cases where there are definitely only one or two solutions. If we have that then we can consider how to extend it to get all solutions over the complex numbers.

**Comment by MaqOwais** [comment]
> https://github.com/sympy/sympy/blob/425353e982439dc64f3d33876cce291aac628ed8/sympy/solvers/ode/systems.py#L316-L330

At line 324, 
`if not _is_lambert(f,x):
`

will better to exclude the lambert solutions as it's non-invertible and it'll have complex solutions.

What will be your opinion on this ? is OK?

**Comment by oscarbenjamin** [comment]
> What will be your opinion on this ? is it OK?

I'm not sure what you are suggesting. I don't think anything needs to change in the dsolve code. The change should be in solveset to make sure it doesn't return a FiniteSet when there are infinitely many solutions.

**Comment by MaqOwais** [comment]
> What will be your opinion on this ? is it OK?


@oscarbenjamin please do comment on the updated comment!

**Comment by oscarbenjamin** [comment]
I'm sorry I don't understand what you want me to comment on. It looks like you are suggesting a change in the dsolve code but I don't think that anything should be changed there.

**Comment by MaqOwais** [comment]
image


Not able to edit the file, why?

**Comment by oscarbenjamin** [comment]
I'm not sure why you couldn't edit the file. I haven't used the github editor before.

The changes in this PR are good though. I hope you are still planning to submit them.

**Comment by MaqOwais** [comment]
> The changes in this PR are good though. I hope you are still planning to submit them.

I'm planning to submit another PR by referencing this.
I've tried a lot but couldn't able to know the reason behind it.

**Pull request closed without merging**
