### PR TITLE
Fix O.contains expr.is_Add heuristics (was invalid for point != 0)

### LINKED ISSUE #9351: order-1 series wrong with non-zero expansion point
This looks wrong:

```
f = exp(x)
f.series(x, 10, 1)
Out[51]: O(x - 10, (x, 10))
```

Surely it should be `exp(10) + O(x - 10, (x, 10))`?

Other orders/points work:

```
f.series(x, 10, 2)    # yes good
Out[52]: exp(10) + (x - 10)*exp(10) + O((x - 10)**2, (x, 10))

f.series(x, 10, 0)   # yes good
Out[53]: O(1, (x, 10))

f.series(x, 0, 1)   # yes good
Out[9]: 1 + O(x)
```

### PR DESCRIPTION
**Pull request by cbm755**
Closes sympy/sympy#9351.  Also fixes broken test in test_issue_5654().

[Cherry-picked from skirpichev/omg/commit/ec0542034fb2332fdbff6bc48c6374846682ea4f]

### CODE REVIEW

**Comment by cbm755** [comment]
I cherry-picked (with very minor rebase) this from https://github.com/skirpichev/omg/commit/ec0542034fb2332fdbff6bc48c6374846682ea4f

License-wise its ok ("New BSD License").  More importantly on a personal level, I hope its ok  @skirpichev

**Comment by asmeurer** [comment]
There is still a decision to be made about including Sergey's patches (see https://github.com/sympy/sympy/pull/10531, and the mailing list thread).

**Comment by smichr** [comment]
I updated the OP of #10531 with a TODO so it's clear what needs to be done.

**Comment by cbm755** [comment]
Given the various `+1`s I've seen at #10531, may I merge this now?

**Comment by cbm755** [comment]
Marked this for 1.1, but I don't feel that strongly.

**Comment by asmeurer** [comment]
If it's ready to merge merge it and it will go in 1.1 :)

**Comment by asmeurer** [comment]
(we already added the license in another PR, so it's not an issue for that any more)

**Pull request merged**
