### PR TITLE
Replaces ast.Name to ast.NameConstant for booleans

### LINKED ISSUE #18789: Use NameConstant instead of Name for True and False
https://github.com/sympy/sympy/blob/f469375c923d8dc50c6632b21f39b7da3d252548/sympy/parsing/sympy_parser.py#L1088

I've stumble over this bug with python3 debug build.
If you clone default python and build it without ```-DNDEBUG``` and run something like this:
```
from sympy.parsing.sympy_parser import parse_expr

parse_expr('2*2', False)
``` 
you will get:
```
.../python3/src/Python/compile.c:3173: int compiler_nameop(struct compiler *, identifier, expr_context_ty): Assertion `!_PyUnicode_EqualToASCIIString(name, "None") && !_PyUnicode_EqualToASCIIString(name, "True") && !_PyUnicode_EqualToASCIIString(name, "False")' failed.
```

This occurs due to the ```assert```-block in python source:
https://github.com/python/cpython/blob/master/Python/compile.c#L3526

This issue doesn't happen if you build python with ```-DNDEBUG``` option. But ideologically ```NameConstant``` and ```Name``` are very different things. 

I've tried to replace  this four ```ast.Name(id='False', ...)```  to ```ast.NameConstant(id='False', ...)``` and it completely solved the problem. But this fix will work only for python3.* 

If you allow, I can send a pool request with it. But with this we should agree to bury python2, IMHO.

Otherwise we should invent a more ~~dirty~~ complex solution. For example:
1) Create a dummy variable ```__False = False```.
2) Put it to ```globals```.
3) Replace ```ast.Name(id='False', ...)``` to  ```ast.Name(id='__False', ...)```.

As I see it, ```NameConstant``` should be used instead of  ```Name``` for ```True``` and ```False```.

### PR DESCRIPTION
**Pull request by w495**
## References to other Issues or PRs

Fixes #18789 — Replace ast.Name to ast.NameConstant for booleans

#### Brief description of what is fixed or changed

If you clone default python and build it without ```-DNDEBUG``` and run something like this:
```
from sympy.parsing.sympy_parser import parse_expr

parse_expr('2*2', False)
``` 
you will get:
```
.../python3/src/Python/compile.c:3173: int compiler_nameop(struct compiler *, identifier, expr_context_ty): Assertion `!_PyUnicode_EqualToASCIIString(name, "None") && !_PyUnicode_EqualToASCIIString(name, "True") && !_PyUnicode_EqualToASCIIString(name, "False")' failed.
```

This occurs due to the ```assert```-block in python source:
https://github.com/python/cpython/blob/master/Python/compile.c#L3526

This issue doesn't happen if you build python with ```-DNDEBUG``` option. But ideologically ```NameConstant``` and ```Name``` are very different things. 

I've tried to replace  this four ```ast.Name(id='False', ...)```  to ```ast.NameConstant(id='False', ...)``` and it completely solved the problem. 

#### Other comments
This fix will work only for python3.* But as @oscarbenjamin says, Python 2 support is already removed in master. The next release will not support Python 2.

Otherwise we should invent a more complex solution. For example:
1) Create a dummy variable ```__False = False```.
2) Put it to ```globals```.
3) Replace ```ast.Name(id='False', ...)``` to  ```ast.Name(id='__False', ...)```.

As I see it, ```NameConstant``` should be used instead of  ```Name``` for ```True``` and ```False```.

## Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Is there any way to test this?

**Comment by oscarbenjamin** [comment]
Normally when something is fixed in sympy a test is added to confirm the correctness of the code and prevent it from being broken in future.

Is there a simple way to test the correctness of the code that is changed here?

**Comment by czgdp1807** [comment]
The bug arises if we use, debug build of python3. So, to add test, we should modify tests to clone the python3 source and build it in DEBUG mode. If the current tests are passing then I think the change shouldn't make a difference. A maintainer can test locally whether it works for the debug build of python3. 
@asmeurer Any thoughts?

**Comment by oscarbenjamin** [comment]
If it's not easy to test then we can just merge this

**Comment by oscarbenjamin** [comment]
It seems this is causing problems with Python 3.9. I'll merge this now to see where it gets us...

See also #19638 and #18466

**Pull request merged**
