### PR TITLE
Added code to remove pdfs during setup.py clean

### LINKED ISSUE #8966: python setup.py clean should remove the pdfs generated by the docs.
```
	doc/src/modules/physics/vector/kin_1.pdf
	doc/src/modules/physics/vector/kin_1pt.pdf
	doc/src/modules/physics/vector/kin_2.pdf
	doc/src/modules/physics/vector/kin_2pt.pdf
	doc/src/modules/physics/vector/kin_3.pdf
	doc/src/modules/physics/vector/kin_4.pdf
	doc/src/modules/physics/vector/kin_angvel1.pdf
	doc/src/modules/physics/vector/kin_angvel2.pdf
	doc/src/modules/physics/vector/kin_angvel3.pdf
	doc/src/modules/physics/vector/kin_rolling.pdf
	doc/src/modules/physics/vector/simp_rot.pdf
	doc/src/modules/physics/vector/vec_add.pdf
	doc/src/modules/physics/vector/vec_cross.pdf
	doc/src/modules/physics/vector/vec_dot.pdf
	doc/src/modules/physics/vector/vec_fix_notfix.pdf
	doc/src/modules/physics/vector/vec_mul.pdf
	doc/src/modules/physics/vector/vec_rep.pdf
	doc/src/modules/physics/vector/vec_simp_der.pdf
```

It would also be nice if they were included in the `.gitignore` file.

### PR DESCRIPTION
**Pull request by jayesh92**
Corresponding Issue: #8966 
Added *.pdf in the corresponding dir in .gitignore and also wrote the
corresponding code in setup.py.
#8968 addresses the same issue

### CODE REVIEW

**Comment by jayesh92** [comment]
@moorepants Could you please review this PR ?

**Comment by smichr** [comment]
:information_source: could you please change the title of the PR? Including the issue number there isn't as useful as putting it in the Description (first paragraph above) because 

1. it doesn't create a clickable link in the Title
1. the number itself doesn't tell the reviewer what they are going to be seeing
1. when there are lots of Issue ### titles it's hard to remember what's what

:eyeglasses: See also: **Writing pull request title and description** at [the wiki](https://github.com/sympy/sympy/wiki/Development-workflow)

**Comment by moorepants** [comment]
FYI: This is being dealt with in ##8968, please check in with that pr author.

**Comment by moorepants** [comment]
#8968 was merged. Closing this one.

**Pull request closed without merging**
