### PR TITLE
Pulled MatrixReductions and MatrixSubspaces function implementations out of Matrix API

### PR DESCRIPTION
**Pull request by tom-pytel**
#### References to other Issues or PRs
Continues #18342

#### Brief description of what is fixed or changed
Relocated the implementations of several matrix functions from `matrices.py` into two new files `reductions.py` and `subspaces.py`. For a rationalization of this change see the description of #18342.

One minor change to a function here is that `_row_reduce` has been renamed to `_row_reduce_list` and changed to take an explicit list of elements and `rows`, `cols` and `one` arguments. This is how it works internally anyway and the function `_row_reduce`  now just takes these arguments from the matrix and calls `_row_reduce_list` with these instead of the code in `_row_reduce_list` reading them from the matrix as it was doing it before. 

This is done to allow this function to eventually be used in other parts of the codebase to solve linear systems of equations without creating intermediate un-sympifiable `RawMatrix` instances which are currently causing problems with attempts to add caching to matrices due to use of elements subclassed from `CantSympify` which throw an exception when a sympification attempt is made (the full explanation for this is too long for this brief description).

#### Release Notes

* matrices
  * Pulled relevant MatrixReductions and MatrixSubspaces function implementations out of matrices/matrices.py into separate matrices/reductions.py and matrices/subspaces.py source files for easier maintenance and future matrix class overhaul.

### CODE REVIEW

**Comment by Pristine-Cat** [comment]
Note that I have done two classes here since they both had only four methods to deal with, less than the single class `MatrixDeterminant`. If you want to merge this after reviewing then go for it and I will do one more PR for the `MatrixEigen` stuff I have waiting but if you feel the changes here are simple enough then I can add the `MatrixEigen` changes to this PR so you can merge it all together.

**Comment by Pristine-Cat** [comment]
Hmm, this is some kind of configuration error...

**Comment by jksuom** [comment]
That may be a transient failure. I have restarted the job.

**Comment by jksuom** [comment]
No, it was not...

**Comment by jksuom** [comment]
https://github.com/pypa/pip/issues/7620

**Comment by Pristine-Cat** [comment]
Revert to previous version until fix?

**Comment by jksuom** [comment]
I have restarted the whole build. Maybe a new version of pip will be used.

**Comment by Pristine-Cat** [comment]
Looks like someone reverted:
```
pip 19.3 from /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by jksuom** [comment]
Now there was another issue: /home/travis/build/sympy/sympy/sympy/matrices/dense.py:docstring of sympy.matrices.dense.GramSchmidt:34: WARNING: py:obj reference target not found: matrices.MatrixSubspaces.orthogonalize

**Comment by Pristine-Cat** [comment]
Yes I am looking at it.

**Comment by Pristine-Cat** [comment]
Apparently at least in Python 3.6 you can not assign to a `classmethod` docstring like you can with other methods.

**Comment by oscarbenjamin** [comment]
> Apparently at least in Python 3.6 you can not assign to a `classmethod` docstring like you can with other methods.

I have to say that I dislike assigning to `__doc__` in general. I can see why you've done it here in transition but I hope that the end state is that we have each docstring in one place in the public API. Wrapper methods should just use a (html-linkable) references to the functions that they call.

**Comment by Pristine-Cat** [comment]
> I have to say that I dislike assigning to `__doc__` in general. I can see why you've done it here in transition but I hope that the end state is that we have each docstring in one place in the public API. Wrapper methods should just use a (html-linkable) references to the functions that they call.

Like you said, I did it this way for practical considerations currently, however you want to do it eventually is fine by me. Though to point out - the functions they link to are private internal functions which I am guessing we do not document publicly? So what would you link to?

**Comment by oscarbenjamin** [comment]
> the functions they link to are private internal functions

Yes, but hopefully in the end these docstrings can be in public functions.

**Comment by Pristine-Cat** [comment]
> Yes, but hopefully in the end these docstrings can be in public functions.

That would work, so either the methods or the eventual top-level functions and one of them links to the other.

**Comment by Pristine-Cat** [comment]
Next step #18425.

**Pull request merged**
