### PR TITLE
Handling regression in `factor()` from `1.3`

### LINKED ISSUE #16240: regression: `factor(f, x, deep=True)`
Consider the factorable expression f:
```
>>> g = (x+3)*(x+4)*(y+5)*(y+6)
>>> f = g.expand()

 2  2       2         2        2                        2              
x ⋅y  + 11⋅x ⋅y + 30⋅x  + 7⋅x⋅y  + 77⋅x⋅y + 210⋅x + 12⋅y  + 132⋅y + 360
```

Good:
```
>>> f.factor(x)
                ⎛ 2            ⎞
(x + 3)⋅(x + 4)⋅⎝y  + 11⋅y + 30⎠
```

Regression:
```
>>> f.factor(x, deep=True)
(x + 3)⋅(x + 4)⋅(y + 5)⋅(y + 6)
```
(I think this should do the same as above)

This is a regression from 1.3, bisected to 9b879cc1dd0acee7d2f741dadea22ebd4f010732

CC @normalhuman

### PR DESCRIPTION
**Pull request by Yathartha22**
#### References to other Issues or PRs
fixes: #16240

#### Release Notes

* polys
   * handling regression in `factor()` with `deep=True` from `1.3`

### CODE REVIEW

**Comment by Yathartha22** [comment]
Another thing that I think needs to be covered here is:
```python
>>> f = 5*x + 3*exp(-7*x + 2)
>>> factor(f, deep=True)
(5*x*exp(7*x) + 3*exp(2))*exp(-7*x)
```
instead of `5*x + 3*exp(2)*exp(-7*x)` in `1.3`
@jksuom your view on what might be causing this.

**Comment by smichr** [comment]
> what might be causing this.

expansion followed by cancel or together, e.g. `cancel((5*x + 3*exp(-7*x + 2)).expand())`

**Comment by smichr** [comment]
What you have here looks good, however. The other issue is another issue.

**Comment by jksuom** [comment]
That form is created by `together` in `_symbolic_factor` on [this line](https://github.com/sympy/sympy/blob/master/sympy/polys/polytools.py#L5964). It [calls `gcd_terms`](https://github.com/sympy/sympy/blob/master/sympy/polys/rationaltools.py#L68), which actually computes the factors and their gcd's. There is a keyword `fraction` to control its output. It is `True` by default, but if it is `False`, then no common factor `1/exp(7*x)` would appear. It might be possible to add `fraction` to `together` and pass it to `gcd_terms`.

**Comment by Yathartha22** [comment]
> It might be possible to add fraction to together and pass it to gcd_terms

Just passing `fraction=False` in `gcd_terms` seems to work fine as of now. So do we need an extra `fraction` parameter in `together()`, or is it okay the way it is.

**Comment by jksuom** [comment]
> passing fraction=False in gcd_terms seems to work fine 

I think that this would be the preferable solution if it breaks no tests.

**Comment by Yathartha22** [comment]
Alright! I will check if that breaks any tests.

**Comment by Yathartha22** [comment]
Well it seems that this approach won't come handy as it breaks a lot of tests in the `polys` itself (it might break much more in the whole codebase). eg:
```python
In [3]: together(1/x + 1) 
Out[3]: 1 + 1/x    # this isn't justified to `together()`
```
The other way seems right: to use `fraction` in `together()`.

**Pull request merged**
