### PR TITLE
In function _gamma_rewrite the pole c is considered always at the left of the strip in case a_=None and b_=oo

### PR DESCRIPTION
**Pull request by jfosorio**
This is related with issue #8514. I am not sure this is the best way to test the function, but this corresponds with the hand calculations.

### CODE REVIEW

**Comment by certik** [comment]
I restarted the failing tests. Otherwise I am +1 to merge this.

**Comment by jfosorio** [comment]
I fixup all the commits in one and push forward.

**Comment by aktech** [comment]
Could you please change the title of the PR? It's not very useful to have an issue number that can't be clicked there, and the number itself doesn't tell the reviewer what they are going to be seeing.

**Comment by jfosorio** [comment]
I change name already. Is there any other objection or feedback to this PR ?

**Comment by aktech** [comment]
Looks good, Merging.
@jfosorio  Thanks for working on this.

**Pull request merged**
