### PR TITLE
Add CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by certik**
A link to this file will appear at GitHub everytime you open a new issue or a
pull request.

### CODE REVIEW

**Comment by certik** [comment]
@asmeurer let me know what you think.

**Comment by asmeurer** [comment]
I don't know. I've always thought these CONTRIBUTING files just raise the barrier to entry, because it becomes more things that a potential contributor has to read/do when submitting a pull request. I guess put me as -0

**Comment by certik** [comment]
That's fine, we don't need to put this in.

**Comment by moorepants** [comment]
I'm +1 for this and think that we could add info from PR #10506.

**Pull request closed without merging**
