### PR TITLE
migrate all the determinant-related tests to test_determinant.py

### PR DESCRIPTION
**Pull request by mohitacecode**
#### References to other Issues or PRs

Partial fix for #18666

#### Brief description of what is fixed or changed
migrate all the `determinant-related tests` from `test_matrices.py` and `test_commonmatrix.py` to a new created file`test_determinant.py`.
#### Release Notes

*   matrices
     *  Added `test_determinant.py` file which contain all the determinant-related tests.

### CODE REVIEW

**Comment by sylee957** [comment]
You should import lots of stuff.
Test files operates basically as same as an ordinary python module. There is no much magic automatically done for imports.
At least flake8 indicates the tests are failing because of this.

**Comment by mohitacecode** [comment]
I have added the imports.
Probably we will squash all the commits once we are finalised with all the changes.

**Comment by sylee957** [comment]
I'd also move other stuff like `adjugate`, `cofactor` to the determinant test. You should check which methods `MatrixDeterminant` have.

**Comment by mohitacecode** [comment]
Sure I agree with you.I will add those tests now.

**Comment by mohitacecode** [comment]
Thanks :) @sylee957

**Pull request merged**
