### PR TITLE
doc/src/modules/polys/literature.rst: Fixed link to reference [Bruce97]

### PR DESCRIPTION
**Pull request by hanweiz**
#### References to other Issues or PRs
#24140 

#### Brief description of what is fixed or changed
The link to reference [Bruce97] has been fixed to one that points to an available version of the article.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by hanweiz** [comment]
Hi @asmeurer, I might need some advise here. My MR for a broken link fix (from #24140) in the documentation resulted in failing a `test/tests-slow (3)`. The logs reflected that a test in `sympy/solvers/ode/tests/test_single.py` failed.

Any advise on a direction on how I can proceed to resolve this will be very much appreciated. 

Thank you.

image

**Comment by oscarbenjamin** [comment]
The test failure in the slow tests is unrelated to the changes here and just happens randomly sometimes gh-20456. A rerun of the tests would make it pass.

The change to .mailmap was correct but has now been reverted meaning that the authors CI check will fail again.

**Comment by hanweiz** [comment]
> The test failure in the slow tests is unrelated to the changes here and just happens randomly sometimes [gh-20456](https://github.com/sympy/sympy/issues/20456). A rerun of the tests would make it pass.
> 
> The change to .mailmap was correct but has now been reverted meaning that the authors CI check will fail again.

Thanks @oscarbenjamin. 

Being new to this, I didn't know about the randomness. So I `git revert`-ed to an earlier state to trigger the tests again, while trying to separate the effects of the document changes and that in `.mailup`. On hindsight that wasn't smart...

**Comment by oscarbenjamin** [comment]
This looks good. Thanks.

It is still marked as being a "draft" pull request. Do you intend to make further changes or is this suitable for merging now?

**Comment by hanweiz** [comment]
> This looks good. Thanks.
> 
> It is still marked as being a "draft" pull request. Do you intend to make further changes or is this suitable for merging now?

Thanks @oscarbenjamin. I don't think more further changes are required. Are you able to review and merge the MR?

**Comment by oscarbenjamin** [comment]
Thanks @hanweiz !

**Pull request merged**
