### PR TITLE
Removed Dangling topics from assumptions page.

### LINKED ISSUE #23185: Unfinished documentation on assumptions page
Scroll to the bottom of https://docs.sympy.org/latest/guides/assumptions.html to see:

image

These dangling unfinished topics should be removed.

### PR DESCRIPTION
**Pull request by hey-sagar**
#### References to other Issues or PRs

Fixes #23185

#### Brief description of what is fixed or changed
Removed Dangling topics from the end of https://docs.sympy.org/latest/guides/assumptions.html.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by AdvaitPote** [comment]
The authors test is failing because you haven't added yourself to the `.mailmap` file yet. 
[See this](https://github.com/sympy/sympy/wiki/Development-workflow#add-your-name-and-email-address-to-the-mailmap-file)  for instructions on how to do the same

**Comment by hey-sagar** [comment]
I'll do that.

**Comment by faze-geek** [comment]
> I'll do that.

@hey-sagar Yes , what is the motivation behind closing this pr ? You need not open a new pr for the suggested changes, you can make more commits in the same branch if you were uncertain about that in any manner !

**Comment by hey-sagar** [comment]
> > I'll do that.
> 
> @hey-sagar Yes , what is the motivation behind closing this pr ? You need not open a new pr for the suggested changes, you can make more commits in the same branch if you were uncertain about that in any manner !
Thanks for the input. I was messing with the git commands trying to revert back for a clean and undoing the commit closed the pr. I am still inexperienced with git commands so I didn't know this would happen. I will be more careful from now on.

**Pull request closed without merging**
