### PR TITLE
"Projects Using SymPy" docs

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes https://github.com/sympy/sympy/issues/10273.

### CODE REVIEW

**Comment by asmeurer** [comment]
Question: how can we make this more prominent? @moorepants

**Comment by moorepants** [comment]
I think it would be nice to have this list on the webpage instead of just the docs. Seems like a more appropriate place that would also make it more prominent.

**Comment by asmeurer** [comment]
It should only have one source. Would you recommend just moving it to the webpage? We can add a link (the page that this is currently on already has an outbound link to the papers page on the wiki).

**Comment by asmeurer** [comment]
Here is a pull request adding it to the website https://github.com/sympy/sympy.github.com/pull/87. If we merge that, we should remove it from the docs.

**Comment by asmeurer** [comment]
I merged sympy/sympy.github.com#87 so https://github.com/sympy/sympy/pull/10668 is the pull request to remove it from the docs (new PR so that it is agains the release branch).

**Pull request closed without merging**
