### PR TITLE
Removed even more Python 2-support

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

There was still a bit of Python 2-related code left. Now, it is primarily the antlr-parsers for autolev and latex that should be updated.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
> * BREAKING: `quality_unicode.py` removed as it was Python 2 only.

This isn't really a breaking change since this is just part of sympy's tests. I'm not sure why it should be removed though. The intention is to prevent contributors from adding unnecessary or accidental non-ascii text in code files.

**Comment by oscargus** [comment]
> The intention is to prevent contributors from adding unnecessary or accidental non-ascii text in code files.

But that is only a Python 2 issue, right? Anyway, that was the reason that I removed it. If you check the comments, they all say "remove when Python 2 is not supported". 

Well, since it was deprecated when moved, it made change to note it here (otherwise I would not have done it).

**Comment by oscarbenjamin** [comment]
> But that is only a Python 2 issue, right?

Currently unicode in the codebase will fail CI and that was done deliberately. There needs to be an agreement on whether unicode can be included in the sympy source. One place where some have wanted to use it is in docstrings. It would help the pretty printing in docstrings but it's not clear how many other things it would stop working e.g. because of editors/terminals/browsers that don't support enough of unicode etc.

**Comment by oscarbenjamin** [comment]
The only difference with Python 2 is that the default encoding is not unicode if there is no encoding cookie at the top of the file.

**Comment by asmeurer** [comment]
The Unicode code quality thing came from https://github.com/sympy/sympy/pull/16272. The original motivation was https://github.com/sympy/sympy/issues/10974. 

I think it is a least partially valuable. We should not allow non-printing Unicode characters, or characters that look exactly the same as ASCII equivalents. We should also not use non-ASCII variable names, at least without discussion. Incorrect encoding lines should be disallowed too, although I believe those will already raise an error on import. 

The coding header bits are indeed outdated. That was required for Unicode characters to work in Python 2 but isn't for Python 3 (UTF-8 is now the default encoding).

**Comment by oscargus** [comment]
OK! So the message is to restore `quality_unicode`, but get rid of the header checking and the Python 2-comments?

**Comment by oscarbenjamin** [comment]
The encoding cookies were just there for Python 2 compatibility so that part can definitely go. I think it's probably best to keep the quality check that prevents non-ASCII being added to non-whitelisted files.

**Comment by oscargus** [comment]
This is updated.

**Comment by oscarbenjamin** [comment]
Looks good!

**Pull request merged**
