### PR TITLE
dsolve() converts floats to integers/rationals #10379

### LINKED ISSUE #10379: dsolve() converts floats to integers/rationals
Unlike `solve()`, `dsolve()` doesn't allow a `rational=False` flag and **by default converts floats to rationals**. This causes bugs when solving ODEs with floats. This works:

    dsolve(x1(t).diff(t)-(1-41.05*y*x1(t)))

```x1(t) == (0.0243605359317905*exp(y*(C1 - 41.05*t)) + 0.0243605359317905)/y```

but this doesn't (just 41.05 changed to 51.05):

    dsolve(x1(t).diff(t)-(1-51.05*y*x1(t)))

```
Traceback (most recent call last):
...
OverflowError: Python int too large to convert to C long
```

Using Python 2.7.11, SymPy 0.7.6.1

### PR DESCRIPTION
**Pull request by shubhamtibra**
If the equation has floats then forcing `solve` not to convert floats to rationals. Fixes #10379

### CODE REVIEW

**Comment by smichr** [comment]
BTW, github will allow you to delete and recreate a branch with the same name as the branch of the old PR and push it there with the `-f` option:

```
git checkout issue_10379
git branch -D 10379
git checkout -b 10379
git branch -D issue_10379
git push -f shubhamtibra 10379
```

**Comment by shubhamtibra** [comment]
Thanks for the information @smichr .
So if my new commits will be added in the same old PR, What will happen to the previous commits in the PR?

**Comment by smichr** [comment]
> What will happen to the previous commits

They are archived, I believe, but in terms of the history in sympy they will be gone.

**Comment by smichr** [comment]
Trailing whitespace in ode.py; running `bin/test quality` before pushing is a good idea.

**Comment by smichr** [comment]
OK, it's in!

**Pull request merged**
