### PR TITLE
contiguous numbers in rsolve

### PR DESCRIPTION
**Pull request by smichr**
* solvers
  * `rsolve_poly` will return results with contiguously numbered constants

### CODE REVIEW

**Comment by smichr** [comment]
blocked by #23840

**Comment by smichr** [comment]
@oscarbenjamin , any idea why the optional dependency test is marked as being required? Or is there some other problem?

**Comment by oscarbenjamin** [comment]
> any idea why the optional dependency test is marked as being required?

That job does not usually fail. I've made it not required for now.

> Or is there some other problem?

See #23847

**Comment by oscarbenjamin** [comment]
Looks good.

**Pull request merged**
