### PR TITLE
Define a meta-hint to expand multinomials up to a certain degree

### PR DESCRIPTION
**Pull request by meganly**
#### Brief description of what is fixed or changed
Expansion of high degree polynomials can be slow and produce unwieldy output.  The ``max_degree=n`` meta-hint for the ``expand`` function only expands multinomials of degree less than or equal to n where n is a positive integer.

#### Release Notes

* core
  * Added a max_degree meta-hint for the expand function.

### CODE REVIEW

**Comment by smichr** [comment]
This seems reasonable to me. Under what circumstances would you use this?

**Comment by meganly** [comment]
You can use this to expand polynomials of unknown degree and avoid timeouts.  This allows me to quickly determine if a polynomial that a student enters as the answer to their Calculus homework is equivalent to the correct answer.

**Comment by smichr** [comment]
I'm just not sure this is something that should get an additional keyword when it can be handled with existing tools:
```python
limexpand = lambda eq, m: expand_mul(eq.replace(
lambda x: x.is_Pow and x.exp.is_Integer and x.exp <= m,
lambda x:expand_multinomial(x)))
```
Anyone else have thoughts? I am +0

**Comment by smichr** [comment]
Also, if one entered `(1+x)**4 - x**4` as an example of a cubic and you only expanded through exponent 3 then this might look like a wrong answer. So I'm not sure that this limited expansion would work. What sort of expressions are you working with and running into problem with in the real-world application?

**Comment by oscarbenjamin** [comment]
I think that in general we should think about having ways to limit potentially expensive operations. I'm not sure about this change in particular but it's an important problem that we should think about across the codebase.

There are many examples of calculations that are so slow no one could ever realistically want sympy to try and actually perform the computation.

Other examples:

1. `Pow(a, b)` where `a` and `b` are large integers:
```julia
In [7]: x = S(100)                                                                                                                             

In [8]: x**x                                                                                                                                   
Out[8]: 
100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000

In [9]: x**x**x**x**x                                                                                                                          
^C---------------------------------------------------------------------------
KeyboardInterrupt
```
There should be some max size for attempting to evaluate an integer pow.

2. Using `evalf` with really large/small numbers attempts to create an enormous integer for the mantissa:
```julia
In [11]: exp(exp(exp(exp(100)))).n()                                                                                                           
^C---------------------------------------------------------------------------
KeyboardInterrupt
```
There should be a max/min exponent for evalf same as max/min prec.

3. As noted here `expand` can be really slow and should have some kind of limitation. It's not hard to define something that really shouldn't be expanded:
```julia
In [18]: x = Symbol('x')                                                                                                                       

In [19]: e = (x+1)**10**20                                                                                                                     

In [20]: e                                                                                                                                     
Out[20]: 
       100000000000000000000
(x + 1)                     

In [21]: expand(e)                                                                                                                             
^C---------------------------------------------------------------------------
KeyboardInterrupt
```

4. Converting to `Poly` also leads to expansion e.g.:
```julia
In [22]: Poly(e)                                                                                                                               
^C---------------------------------------------------------------------------
KeyboardInterrupt 
```

5. Many other functions use `poly` e.g. `cancel` etc so this is really slow:
```julia
In [24]: cancel(e/(e - 1))                                                                                                                     
^C---------------------------------------------------------------------------
KeyboardInterrupt

In [31]: factor(e/(e-1))                                                                                                                       
^C---------------------------------------------------------------------------
KeyboardInterrupt
```

6. Many calculations use expand unnecessarily in a way that slightly simplifies the result in simple cases but can lead to enormous slowdowns in more complicated cases. It would be useful if such calculations could have a way of limiting the expansion. We could have a `safe_expand` function to be used in those cases. Or perhaps `expand` could have a max limit by default with `force=True` to override.

7. Calculating roots of cubics/quartics can lead to enormous expressions that are very slow. This leads to things like eigenvects being very slow. Most users don't want the enormous complicated answers and would rather have a quick approximate answer so we should give them a way to get that, possibly by default. RootOf should be more usable but that's also slow (I think it can be made faster).

8. I can't think of any more right now but there are lots of these...

I think mathematica handles a lot of this with timeouts:
https://reference.wolfram.com/language/ref/TimeConstraint.html

It's not clear how to use timeouts in a Python library like sympy but we could perhaps use optional timeouts. I think though that a "fail fast" approach to absurdly expensive operations is better but we need to think about how we would want to handle that across sympy. Should there be a global flag that prevents/enables expensive operations?

If we were going to try and tackle this in general would the flag here make sense as part of that?

**Comment by smichr** [comment]
> would the flag here make sense as part of that

I suspect so. For any given function we could think/anticipate when it would be slow and make sure there is a way to avoid that. For `expand_multinomial` this would be the right thing. Let's see what @meganly has to add by way of comment.

**Comment by meganly** [comment]
> I'm just not sure this is something that should get an additional keyword when it can be handled with existing tools

In a similar vein to `frac,` `numer`, `denom`, and `modulus`, `max_degree` is a keyword to target a specific part of an expression in expansion.

> Also, if one entered `(1+x)**4 - x**4` as an example of a cubic and you only expanded through exponent 3 then this might look like a wrong answer.

Perhaps naming the hint `max_multinomial_degree` would make it more clear that the max degree only applies to multinomials.

> What sort of expressions are you working with and running into problem with in the real-world application?

In chain rule questions checking that 100(x^3+1)^99 is not equivalent to 300x^2(x^3+1)^99 by comparing their expanded forms takes too long.

**Comment by meganly** [comment]
> I think that in general we should think about having ways to limit potentially expensive operations.
> 
> There are many examples of calculations that are so slow no one could ever realistically want sympy to try and actually perform the computation.
> 
Exactly.  @oscarbenjamin has nice examples.

>  Many calculations use expand unnecessarily in a way that slightly simplifies the result in simple cases but can lead to enormous slowdowns in more complicated cases. It would be useful if such calculations could have a way of limiting the expansion. We could have a `safe_expand` function to be used in those cases. Or perhaps `expand` could have a max limit by default with `force=True` to override.
> 
That would be incredibly useful.

**Comment by oscarbenjamin** [comment]
You can see the slowdown caused by expansion because it's much quicker to check this when the exponent is a symbol (which prevents expansion):
```julia
In [10]: e1 = 100*(x**3 + 1)**99                                                                                                               

In [11]: e2 = 300*x**2*(x**3 + 1)**99                                                                                                          

In [12]: %time e1.equals(e2)                                                                                                                   
CPU times: user 1.13 s, sys: 9.37 ms, total: 1.14 s
Wall time: 1.15 s
Out[12]: False

In [13]: e1 = 100*(x**3 + 1)**n                                                                                                                

In [14]: e2 = 300*x**2*(x**3 + 1)**n                                                                                                           

In [15]: %time e1.equals(e2)                                                                                                                   
CPU times: user 85.2 ms, sys: 850 µs, total: 86.1 ms
Wall time: 101 ms
Out[15]: False
```
Using larger exponents (e.g. 999) makes it really slow:
```julia
In [16]: e1 = 100*(x**3 + 1)**999                                                                                                              

In [17]: e2 = 300*x**2*(x**3 + 1)**999                                                                                                         

In [18]: %time e1.equals(e2)                                                                                                                   
CPU times: user 42.1 s, sys: 427 ms, total: 42.5 s
Wall time: 44.1 s
```

**Comment by oscarbenjamin** [comment]
I wonder if it makes sense to limit the number of total terms in the expansion rather than have a limit on the exponent. The total number of terms is given by
```julia
In [39]: f = lambda n, m: factorial(n + m - 1) / (factorial(m - 1) * factorial(n))                                                             

In [40]: f(5, 5)                                                                                                                               
Out[40]: 126

In [41]: len(expand(Add(*symbols('x:5'))**5).args)                                                                                             
Out[41]: 126
```
Increasing the number of terms in the inner Add can have a more significant effect than increasing the exponent.

**Comment by czgdp1807** [comment]
@meganly Any thoughts on the above two comments?

**Comment by meganly** [comment]
In many ways @oscarbenjamin 's idea to limit the total number of terms in the expansion makes sense for a truly safe expand. 

A downside to this approach is that it's harder tell which expressions will get expanded.

Another concern is that ``f`` doesn't account for the fact that terms in the expansion can often be combined.  While expanding ``(v+w+x+y+z)**5`` has 126 terms, expanding ``(x**4+x**3+x**2+x+1)**5`` only has 21 terms.

**Comment by oscarbenjamin** [comment]
> While expanding `(v+w+x+y+z)**5` has 126 terms, expanding `(x**4+x**3+x**2+x+1)**5` only has 21 terms.

That's a good point. In some cases we would want to prevent producing large expressions but some expansions might actually simplify down to simple expressions. If the goal is to prevent producing overly complex expressions then the measure I suggested is possibly too simple.

If the goal though is to limit the computational expense then those cases are similar since both of those examples will internally compute 126 terms before flattening down to a smaller number of terms.

**Comment by meganly** [comment]
I created the multinomial hint as a quick and dirty way to limit the computational expense, but preventing unwieldy output would also be useful.

**Comment by asmeurer** [comment]
For polynomial expansion cancellation is also possible. A typical example is `(x - 1)*(1 + x + x**2 + ... + x**n)` which is degree `n+1` but only has two terms when expanded.

**Comment by asmeurer** [comment]
This is a good idea, but it may be too simplistic. You can write something like `(((((x1 + x2)**2 + x3)**2 + x4)**2 + x5)**2 + x6)**2` only ever expands a degree 2, but has 1827 terms when expanded (the number of terms in general seems to follow https://oeis.org/A125792). There's https://github.com/sympy/sympy/issues/6322 about bounding the degree of a polynomial without expanding it, although there is also the problem that for multivariate polynomials, the number of multinomials below a certain total degree explodes (see the docstring of `itermonomials`), so it isn't very useful by itself as a bound on the number of terms.

**Comment by oscarbenjamin** [comment]
There is also some discussion about limiting expansion of multivariate expressions in https://github.com/sympy/sympy/issues/8191#issuecomment-633126334

**Comment by czgdp1807** [comment]
As far as I can understand, the problem is to avoid timeouts when expanding polynomials of large degrees. One way suggested here is to limit the number of terms. But the problem with this is the non-deterministic expansion of some terms. It will be hard to tell which term will be expanded. Other approach suggested is to expand terms only with degrees less than maximum degree.

So what are we going to use to improve performance? @meganly @oscarbenjamin @asmeurer Please share your thoughts.

**Comment by meganly** [comment]
Expanding multinomials with degree less than the maximum degree is probably too simplistic.  I'm fine with closing this PR and thinking about how to limit the number of terms.  Perhaps ``term_limit`` would be a better meta-hint for ``expand``?

**Comment by czgdp1807** [comment]
@meganly Thanks for the update. Did you open any issue regarding this problem? If not I will open a new one and will close this PR afterwards.

**Comment by meganly** [comment]
Thanks.  I haven't opened an issue regarding this problem.

**Pull request closed without merging**
