### PR TITLE
Remove args and func overriding of AppliedPredicate

### PR DESCRIPTION
**Pull request by JSS95**
#### References to other Issues or PRs

Required for #20635

#### Brief description of what is fixed or changed

Previously, `AppliedPredicate.func` and `AppliedPredicate.args` were overridden. This PR makes `AppliedPredicate` just inherit `Basic.func` and `Basic.args`.

#### Release Notes

- assumptions
    - `func` property of `AppliedPredicate` returns `AppliedPredicate` class instead of unapplied predicate object. User must use `function` property to get the predicate. This breaks backwards compatibility.
    - `args` property of `AppliedPredicate` returns unapplied predicate object and arguments. User must use `arguments` property to get the arguments without unapplied predicate. This breaks backwards compatibility.

### CODE REVIEW

**Comment by JSS95** [comment]
@oscarbenjamin 

I had to introduce `_find_freepredicate()` in order to replace `expr.atoms(Predicate)` used in sathandlers.py. `Q.positive(x).atoms(Predicate)` refers to `Q.positive(x).args`. Previously, `.args` returned `(x,)`, so `Q.positive(x).atoms(Predicate)` returned empty set. Now, it returns `(Q.positive, x)`, therefore `{Q.positive}` is returned. This raised error in `UnevaluatedOnFree`.

**Comment by JSS95** [comment]
There are a lot of other errors which cannot be easily resolved.

```
__________________________________________________________________________________________________________________________________________________________________________________________________
_______________________________________________________________________ sympy/assumptions/tests/test_query.py:test_bounded _______________________________________________________________________
Traceback (most recent call last):
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/tests/test_query.py", line 591, in test_bounded
    assert ask(Q.finite(a),
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/ask.py", line 417, in ask
    res = key(*args)._eval_ask(assumptions)
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/assume.py", line 161, in _eval_ask
    return self.function.eval(self.arguments, assumptions)
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/assume.py", line 355, in eval
    result = func(*args, assumptions)
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/handlers/calculus.py", line 95, in _
    _bounded = ask(Q.finite(arg), assumptions)
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/ask.py", line 397, in ask
    raise ValueError("inconsistent assumptions %s" % assumptions)
ValueError: inconsistent assumptions Q.finite(x) & Q.finite(y) & Q.positive(x) & ~Q.positive(y)
__________________________________________________________________________________________________________________________________________________________________________________________________
_____________________________________________________________________ sympy/assumptions/tests/test_query.py:test_issue_6732 ______________________________________________________________________
Traceback (most recent call last):
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/tests/test_query.py", line 2131, in test_issue_6732
    raises(ValueError, lambda: ask(Q.positive(x), Q.positive(x) & Q.negative(x)))
  File "/home/jisoosong/codes/sympy/sympy/sympy/testing/pytest.py", line 104, in raises
    raise Failed("DID NOT RAISE")
sympy.testing.pytest.Failed: DID NOT RAISE
__________________________________________________________________________________________________________________________________________________________________________________________________
_______________________________________________________________ sympy/assumptions/tests/test_sathandlers.py:test_UnevaluatedOnFree _______________________________________________________________
Traceback (most recent call last):
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/tests/test_sathandlers.py", line 33, in test_UnevaluatedOnFree
    assert b.rcall(x) == UnevaluatedOnFree(Q.positive(x) | Q.negative(x))
  File "/home/jisoosong/codes/sympy/sympy/sympy/core/basic.py", line 609, in rcall
    return Basic._recursive_call(self, args)
  File "/home/jisoosong/codes/sympy/sympy/sympy/core/basic.py", line 628, in _recursive_call
    return type(expr_to_call)(*args)
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/sathandlers.py", line 86, in __new__
    obj.pred = arg.xreplace(Transform(lambda e: e.func, lambda e:
  File "/home/jisoosong/codes/sympy/sympy/sympy/core/basic.py", line 1142, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/jisoosong/codes/sympy/sympy/sympy/core/basic.py", line 1164, in _xreplace
    return self.func(*args), True
  File "/home/jisoosong/codes/sympy/sympy/sympy/core/operations.py", line 489, in __new__
    _args = frozenset(cls._new_args_filter(args))
  File "/home/jisoosong/codes/sympy/sympy/sympy/logic/boolalg.py", line 834, in _new_args_filter
    args = BooleanFunction.binary_check_and_simplify(*args)
  File "/home/jisoosong/codes/sympy/sympy/sympy/core/operations.py", line 482, in <genexpr>
    args = (_sympify_(arg) for arg in args)
  File "/home/jisoosong/codes/sympy/sympy/sympy/core/sympify.py", line 512, in _sympify
    return sympify(a, strict=True)
  File "/home/jisoosong/codes/sympy/sympy/sympy/core/sympify.py", line 352, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: <class 'sympy.assumptions.assume.AppliedPredicate'>
__________________________________________________________________________________________________________________________________________________________________________________________________
____________________________________________________________________ sympy/assumptions/tests/test_sathandlers.py:test_AllArgs ____________________________________________________________________
Traceback (most recent call last):
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/tests/test_sathandlers.py", line 60, in test_AllArgs
    assert a.rcall(x*y) == to_NNF(And(Q.zero(x), Q.zero(y)))
  File "/home/jisoosong/codes/sympy/sympy/sympy/core/basic.py", line 609, in rcall
    return Basic._recursive_call(self, args)
  File "/home/jisoosong/codes/sympy/sympy/sympy/core/basic.py", line 628, in _recursive_call
    return type(expr_to_call)(*args)
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/sathandlers.py", line 88, in __new__
    applied = obj.apply(obj.expr)
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/sathandlers.py", line 97, in apply
    return self._eval_apply(expr, pred)
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/sathandlers.py", line 134, in _eval_apply
    return AND(*[pred.rcall(arg) for arg in expr.args])
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/sathandlers.py", line 134, in <listcomp>
    return AND(*[pred.rcall(arg) for arg in expr.args])
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/cnf.py", line 35, in rcall
    lit = self.lit(expr)
  File "/home/jisoosong/codes/sympy/sympy/sympy/assumptions/assume.py", line 118, in __new__
    raise TypeError("%s is not a Predicate." % predicate)
TypeError: x is not a Predicate.
```

**Comment by oscarbenjamin** [comment]
This can fix some of the errors:
```diff
diff --git a/sympy/assumptions/ask.py b/sympy/assumptions/ask.py
index fb00dac5b3..a42d669e84 100644
--- a/sympy/assumptions/ask.py
+++ b/sympy/assumptions/ask.py
@@ -290,7 +290,7 @@ def _extract_all_facts(expr, symbols):
             if isinstance(literal.lit, AppliedPredicate):
                 if literal.lit.arg in symbols:
                     # Add literal if it has 'symbol' in it
-                    args.append(Literal(literal.lit.func, literal.is_Not))
+                    args.append(Literal(literal.lit.function, literal.is_Not))
                 else:
                     # If any of the literals doesn't have 'symbol' don't add the whole clause.
                     break
```

**Comment by oscarbenjamin** [comment]
Also this:
```diff
diff --git a/sympy/assumptions/satask.py b/sympy/assumptions/satask.py
index d672f75cfc..e72d2f2df8 100644
--- a/sympy/assumptions/satask.py
+++ b/sympy/assumptions/satask.py
@@ -92,7 +92,7 @@ def find_symbols(pred):
             req_keys |= tmp_keys
         keys |= {l for l in lkeys if find_symbols(l) & req_keys != set()}
 
-        exprs = {key.args[0] if isinstance(key, AppliedPredicate) else key for key in keys}
+        exprs = {key.arguments[0] if isinstance(key, AppliedPredicate) else key for key in keys}
         return exprs, relevant_facts
 
     for expr in exprs:
```

**Comment by oscarbenjamin** [comment]
Also this:
```diff
diff --git a/sympy/assumptions/sathandlers.py b/sympy/assumptions/sathandlers.py
index 135e561f5a..6d856709dc 100644
--- a/sympy/assumptions/sathandlers.py
+++ b/sympy/assumptions/sathandlers.py
@@ -83,7 +83,7 @@ def __new__(cls, arg):
             raise ValueError("The AppliedPredicates in arg must be applied to a single expression.")
         obj = BooleanFunction.__new__(cls, arg)
         obj.expr = predicate_args.pop()
-        obj.pred = arg.xreplace(Transform(lambda e: e.func, lambda e:
+        obj.pred = arg.xreplace(Transform(lambda e: e.function, lambda e:
             isinstance(e, AppliedPredicate)))
         applied = obj.apply(obj.expr)
         if applied is None:
```

**Comment by JSS95** [comment]
@oscarbenjamin 
This PR is resolved now, which means that #20635 can be fixed as well.

**Comment by oscarbenjamin** [comment]
Looks good

**Pull request merged**
