### PR TITLE
Reduce the Travis test splits to 2 ways

### PR DESCRIPTION
**Pull request by asmeurer**
I'm not sure yet if it will make the builds too long so we should check how long they take here before merging.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
What is the potential advantage of this?

**Comment by asmeurer** [comment]
Travis only runs a certain number of builds at a time (I think it's 15 or 20). This applies across all SymPy builds, both all PR builds and builds against `master` whenever a PR is merged. Thus by splitting fewer ways, the total build queue can finish faster. Also each test build has setup time where it has to boot the machine and install SymPy. Based on the timings on the right of the build, this takes about a minute for each build.

**Comment by oscarbenjamin** [comment]
Having recently interacted with pytest I notice that their travis setup uses a two-stage approach with a quick check and then a more comprehensive check that only runs if the first step succeeds. The equivalent for SymPy could be a first stage that runs non-slow tests and doctests on only one version of Python followed by a second stage that includes slow tests and runs over all the versions and does optional dependencies. With that most travis runs would be down from 40 jobs to 5 jobs which could significantly improve throughput at busy times.

**Comment by asmeurer** [comment]
Is there some way to make Travis jobs not run if another one has already failed? 

We could also make the tests stop on the first failure. But there are advantages to showing all the test failures, especially since people rarely run the full test suite on their computer before pushing.

**Comment by oscarbenjamin** [comment]
I've never configures anything for Travis so I don't know much about but you can see their config here:
[https://github.com/pytest-dev/pytest/blob/master/.travis.yml](https://github.com/pytest-dev/pytest/blob/master/.travis.yml)

When you click through to Travis from the PR it's clearly running in two stages and the second doesn't run if the first fails.

What you say about people rarely running the full test suite locally makes sense. That's why I'd propose that the first stage runs the full not slow test suite plus doctests and code quality tests on a single Python version. With the current 4-split I think that would be 5 jobs.

**Comment by asmeurer** [comment]
Interesting. The tests definitely used to take longer. Compare the latest build from [master](https://travis-ci.org/sympy/sympy/builds/494077018) to the build for [1.2](https://travis-ci.org/sympy/sympy/builds/401842735). The optional dependency build used to almost run over the Travis time limit (50 min.). And now it finishes in under 25 minutes. I wonder if SymPy has gotten faster or if Travis has. I hope we didn't somehow remove tests from Travis.

**Comment by oscargus** [comment]
Seems like two is a good number yes. :-)

**Comment by oscarbenjamin** [comment]
I've opened #16023 for the two-stage Travis tests idea.

**Comment by asmeurer** [comment]
I've also removed the split for slow tests. 

Any objections?

**Comment by asmeurer** [comment]
As to why the tests are faster these days, I think Travis is simply faster. I ran the doctests on my computer on `master` vs. `sympy-1.2` and they ran faster on 1.2, presumably since there are more doctests on master. I pushed up a branch that is just `sympy-1.2` plus a backport of some .travis.yml pip fixes to my fork, and the build on my fork is comparable to master. 

Compare

The build of `sympy-1.2` from 8 months ago: https://travis-ci.org/sympy/sympy/builds/401842735
The build of `sympy-1.2` on my fork (today): https://travis-ci.org/asmeurer/sympy/builds/495730393
The build of `master` (4 days ago): https://travis-ci.org/sympy/sympy/builds/494077018

You can see the Python 2 doctests in `sympy-1.2` took 19:46 8 months ago, but today they take 9:30 (again, on the same commit). In `master` they take 10:21, but again, there are more doctests in `master` than `sympy-1.2`. The other jobs are similar, all between 2-3x faster. 

Comparing `master` to the sympy-1.2 build from today, it looks like the master tests are slightly slower. I'm not clear if this is due to some performance regressions or there simply being more tests than 8 months ago (or if it's just variance in Travis build times). This is why we need [real performance regression testing](https://github.com/sympy/sympy/wiki/GSoC-2019-Ideas#benchmarks-and-performance).

**Pull request merged**
