### PR TITLE
Revert kg

### PR DESCRIPTION
**Pull request by Upabjojr**
#### Release Notes

- physics.units
  - make kilogram definition resistant against spurious editing.

### CODE REVIEW

**Comment by smichr** [comment]
I would (upon consensus of those interested) offer the following diff to master:
```diff
diff --git a/sympy/physics/units/definitions.py b/sympy/physics/units/definition
s.py
index a118ded..92255e5 100644
--- a/sympy/physics/units/definitions.py
+++ b/sympy/physics/units/definitions.py
@@ -52,16 +52,14 @@
 # gram; used to define its prefixed units
 g = gram = grams = Quantity("gram", abbrev="g")
 gram.set_dimension(mass)
-gram.set_scale_factor(One)
-
-# NOTE: the `kilogram` has scale factor 1000. In SI, kg is a base unit, but
-# nonetheless we are trying to be compatible with the `kilo` prefix. In a
-# similar manner, people using CGS or gaussian units could argue that the
-# `centimeter` rather than `meter` is the fundamental unit for length, but the
-# scale factor of `centimeter` will be kept as 1/100 to be compatible with the
-# `centi` prefix.  The current state of the code assumes SI unit dimensions, in
-# the future this module will be modified in order to be unit system-neutral
-# (that is, support all kinds of unit systems).
+# Although the kilogram is the base unit in SI we
+# are free to make any choice for the value of that
+# base. By setting the scale factor of gram to 1 -+
+# we then get a scale factor for kg that is 1000, |
+# a value that matches the scale factor for kilo. |
+# This value should not be changed.               |
+gram.set_scale_factor(One)  # <-------------------+
+
 kg = kilogram = kilograms = Quantity("kilogram", abbrev="kg")
 kilogram.set_dimension(mass)
 kilogram.set_scale_factor(kilo*gram)
```
Anyone making a kilogram change would have to change this and this will be visible to anyone that reviews the change.

**Comment by Sc0rpi0n101** [comment]
Why is this ValueError being thrown?

```python
>>> pref = {k : PREFIXES["k"]}
>>> g.scale_factor
1
>>> k.scale_factor
1000
>>> prefix_unit(g,pref)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sc0rpi0n101/Github/sympy/sympy/physics/units/prefixes.py", line 145, in prefix_unit
    quantity.set_scale_factor(unit.scale_factor*prefix)
  File "/home/sc0rpi0n101/Github/sympy/sympy/physics/units/quantities.py", line 113, in set_scale_factor
    raise ValueError("`scale_factor` for kilogram is 1000 and it's not"
ValueError: `scale_factor` for kilogram is 1000 and it's not going to change. Close your PR.
```
Also occurs when importing MKS

```python
>>> from sympy.physics.units.systems import MKS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sc0rpi0n101/Github/sympy/sympy/physics/units/systems/__init__.py", line 1, in <module>
    from sympy.physics.units.systems.mks import MKS, _mks_dim
  File "/home/sc0rpi0n101/Github/sympy/sympy/physics/units/systems/mks.py", line 30, in <module>
    all_units.extend(prefix_unit(u, PREFIXES))
  File "/home/sc0rpi0n101/Github/sympy/sympy/physics/units/prefixes.py", line 145, in prefix_unit
    quantity.set_scale_factor(unit.scale_factor*prefix.scale_factor)
  File "/home/sc0rpi0n101/Github/sympy/sympy/physics/units/quantities.py", line 113, in set_scale_factor
    raise ValueError("`scale_factor` for kilogram is 1000 and it's not"
ValueError: `scale_factor` for kilogram is 1000 and it's not going to change. Close your PR.

```


I tried
```python 
if (quantity == 'kilogram' or quantity == 'kg'):
            quantity.set_scale_factor(1000)
        else:
            quantity.set_scale_factor(unit.scale_factor*prefix.scale_factor)
```
and still got the exception
```python
>>> prefix_unit(g,pref)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sc0rpi0n101/Github/sympy/sympy/physics/units/prefixes.py", line 148, in prefix_unit
    quantity.set_scale_factor(unit.scale_factor*prefix.scale_factor)
  File "/home/sc0rpi0n101/Github/sympy/sympy/physics/units/quantities.py", line 113, in set_scale_factor
    raise ValueError("`scale_factor` for kilogram is 1000 and it's not"
ValueError: `scale_factor` for kilogram is 1000 and it's not going to change. Close your PR.
```



It occurs even when i manually set scale factor to 1000
```python
>>> p = prefix_unit(g,pref)
>>> p
[kilogram]
>>> p[0].set_scale_factor(1000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sc0rpi0n101/Github/sympy/sympy/physics/units/quantities.py", line 113, in set_scale_factor
    raise ValueError("`scale_factor` for kilogram is 1000 and it's not"
ValueError: `scale_factor` for kilogram is 1000 and it's not going to change. Close your PR.
```

The exception was gone and the doctests passed when I commented out the line
`# quantity.set_scale_factor(unit.scale_factor*prefix.scale_factor)`

**Comment by czgdp1807** [comment]
@Upabjojr Is this still needed? I think I can extend this. Please let me know if a new PR is needed for this. Thanks.

**Comment by Upabjojr** [comment]
No, the code has been changed a lot.

**Pull request closed without merging**
