### PR TITLE
Create geometry_obj

### PR DESCRIPTION
**Pull request by darknight009**
input equation in the form a*x**2+b*y**2+g*x+h*y+c
Call using:

from sympy.geometry.geometry_obj import *
function_eq(a*x**2+b*y**2+g*x+h*y+c)

issue #11028 

<!-- If this pull request fixes an issue please indicate which issue by typing "Fixes #NNNN" below.>
#11028

### CODE REVIEW

**Comment by siefkenj** [comment]
I would suggest that methods be added to the Geometry objects themselves.  Like, `Circle.from_equation()` or something like that.  It would be easy to make sure that each of these methods work separately.  Then, you could have one function that detects what the equation should correspond to and dispatches to the appropriate method call.

**Comment by dranknight09** [comment]
Should I add methods to geometry object class or their module?

**Comment by siefkenj** [comment]
I would propose adding a `from_equation` method in `GeometrySet`.  Then, `Line`, `Ellipse`, etc. would have their own `_from_equation` private methods.  The `GeometrySet.from_equation` method would detect how many variables the equation has, whether it is a 2d or 3d equation, etc. and what form it takes and then dispatch it to the appropriate `_from_equation` method.  

I'm not sure how complicated you want to get in your equation parsing.  You might start by assuming every equation is in some standard form, since recognizing that `y/x=1` is a line could be hard.  You might also look at the solveset work to see if you could leverage that at all.

**Comment by gxyd** [comment]
@darknight009 can you please merge master branch? And also please address the requested changes.

**Comment by gxyd** [comment]
This PR has been inactive for quite sometime, so we are going to close it and open an issue to reference it. We try to keep our pull request queue small and focused on active work.  We encourage you to reopen the pull request if and when you continue to work on this. Please contact us if you have any questions.

Thanks for contributing.

see https://github.com/sympy/sympy/wiki/Closing-pull-requests for our policies on closing pull request.

We already have issue #11028 keeping track of what needs to be fixed.

**Pull request closed without merging**
