### PR TITLE
fix inequalities with oo and inf

### PR DESCRIPTION
**Pull request by skoslowski**
This fixes the issue discussed on the mailing list:
https://groups.google.com/forum/#!topic/sympy/X5-mfRAzQI4

### CODE REVIEW

**Comment by Upabjojr** [comment]
There was some discussion a while ago about what exactly is infinite, maybe it needs some opinion.

**Comment by Upabjojr** [comment]
@asmeurer this looks good to me.

I didn't read all the details of discussions about the _infinite_ assumption, so please check. If there are no problems, I'm +1 to merge this.

**Comment by bjodah** [comment]
+1
I restarted a stalled test job, if no one has any objects I will merge this in a few days.

**Comment by hargup** [comment]
@skoslowski Thanks for your work.

**Pull request merged**
