### PR TITLE
Remove Azure Pipelines

### LINKED ISSUE #15385: Add missing things to Azure pipelines
See https://github.com/sympy/sympy/pull/15297

The following are missing from Azure pipelines

- [ ] PyPy (couldn't figure out how to get it working, waiting for https://github.com/Microsoft/vsts-tasks/issues/8514 which should make it easier)
- [ ] The optional dependency build is currently an allowed failure, and fails due to libgfortran issues. It should (hopefully) start to work once the compiler migration on conda forge is finished. We should also move the 3.6 build to 3.7 when that happens.
- [ ] The Sphinx docs are not built on Azure. We will always need them on Travis because doctr only runs on Travis, so I didn't bother adding another job for it.
- [ ] The rigorous setup.py install test from Travis (TEST_SETUP).
- [ ] The slow tests

### LINKED ISSUE #15526: Test data is not published to Azure Pipelines
Tests are running in the pipeline, but they aren't getting published to Azure Pipelines which provides excellent reporting capabilities that help you with:

- Easy analysis and troubleshooting for failed tests - the test reports show all relevant details (error message, stack trace, failing for how long, etc.) to make it easy to analyse failed tests.
- Timing analysis - Test duration information helps you figure out long running tests, so that you can improve test collateral to speed up the pipelines.
- Build-on-build trends/analytics help you get rich insights, detailed scenarios @ https://blogs.msdn.microsoft.com/devops/2018/10/25/test-analytics-in-azure-pipelines-is-now-at-your-fingertips/ 

image

The fix required is to use an XML reporter and update the YAML file to publish these test reports.

I am a Program Manager on the Azure Pipelines team and will be happy to raise a PR to address this.

### PR DESCRIPTION
**Pull request by asmeurer**
See the discussion at
https://groups.google.com/forum/#!msg/sympy/jyYrYz8ys9o/p7IY4MCSAwAJ.

This is still open for discussion if anyone wants to object. 

#### References to other Issues or PRs

Closes #15857
Closes #15526
Closes #15385

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
I've removed the Azure merge requirement so this can be merged.

**Comment by oscarbenjamin** [comment]
How does removing the Azure requirement affect existing PRs e.g. #16012 that have failures on Azure? Would closing and reopening remove the block?

**Comment by asmeurer** [comment]
The requirement applies globally. Notice how it says "Required" to the right of Travis and the sympy-bot, but not Azure. So you can merge pull requests where Azure fails now, if you want. I would still investigate any Azure failures for the PRs that still have it to make sure nothing is wrong (it looks like for that PR the conda install failed for Sage, which can be ignored).

**Comment by asmeurer** [comment]
I haven't heard any objections, so I'm going to merge this. The existing pull requests still have Azure builds, but they aren't required to merge, so it shouldn't be a problem. Eventually I'll go in and delete the oauth token so that there won't be any builds anymore even on old branches.

**Pull request merged**
