### PR TITLE
Printing of Stieltjes and Mathieu functions, improved printing of integer polynomials

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed
Added LaTeX, pretty and MathML presentation printing of `stieltjes` and Mathieu functions.
Improved printing of integer polynomials for pretty and MathML presenation.
MathML printing of Euler

Before:
beforestieltjes

After:
afterstieltjes

#### Other comments
Not convinced about the rendering of `mathieusprime(x, y, z)**2`.

#### Release Notes

* printing
    * Added LaTeX, pretty and MathML presentation printing of `stieltjes` and Mathieu functions.
    * Improved printing of integer polynomials (`bell(n, x)` etc) for pretty and MathML presentation printers.
    * Added MathML presentation printing of `euler`.

### CODE REVIEW

**Comment by smichr** [comment]
> Not convinced about the rendering of `mathieusprime(x, y, z)**2`.

Why so?

**Comment by oscargus** [comment]
It looks quite bad with the prime and the power in the same superscript. This is for LaTeX. Not so clear original comment.

**Comment by smichr** [comment]
> looks quite bad with the prime and the power in the same superscript

The magnification on my screen was so small that I didn't notice that. I see [here](https://tex.stackexchange.com/questions/2635/why-isnt-prime-automatically-set-to-be-a-superscript?rq=1) some discussion about prime. Would this suggestion help at all? "There are situations where you need the big \prime instead of small ' e.g. $J^{v\prime h}$ looks great, but $J^{v ' h}$ wont serve as good as the previous one."

**Comment by oscargus** [comment]
I use the big prime here. Which may be the problem... 

Thinking more about it, I think either `{C^{\prime}}^{2}` or `C'^{2}` may be the way to go. Will make some experiments...

**Comment by oscargus** [comment]
image

First: as now `C^{\prime 2}`
Second: `{C^{\prime}}^{2}`
Third: `C'^{2}`

looks like first and third are identical.

I'd probably say that the second is the better, but no major difference.

**Comment by jksuom** [comment]
I don't think that a superscript denoting power should be attached to the function in these cases. That kind of notation is used in mathematics when there are no parentheses around a single argument, like `sin x`, but otherwise the superscript could come after the arguments.

**Comment by oscargus** [comment]
I've updated this and now prints the exponent in the end of the LaTeX expressions for the Stieltjes and Mathieu functions (so looks like MathML).

**Pull request merged**
