### PR TITLE
Added simplify before plotting of expression

### LINKED ISSUE #19013: Error in plot of trigo expressions which can be simplified
Problems with the plot of `exp = csc(x)**2 - cot(x)**2`: 
1. The plot is along `f(x) = 0` but it should be around `f(x) = 1`
2. There are spikes at x = multiples of pi

It should be a straight line along `f(x) = 1` because it can be simplified to `exp = 1`

```
from sympy.functions import *
from sympy.abc import *
from sympy import plot

exp = csc(x)**2 - cot(x)**2
plot(exp)
```
The above code returns this plot:
Figure_1

### PR DESCRIPTION
**Pull request by dhruv-kothari**
#### Fixes #19013
Issue: Error in plot of trigonometric expressions, shows incorrect plot of expressions which reduce to a constant like `csc(x)**2 - cot(x)**2`

#### Brief description of what is fixed or changed
Added simplify the expression before plotting
Fixes both the problems discussed in #19013

The plot of `exp = csc(x)**2 - cot(x)**2`:
Previously:
Figure_3
Now:
Figure_2

#### Other comments
Still there is a issue with plotting constants as discussed in #18901

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by Smit-create** [comment]
I think you need to fix the y-axis also to produce the correct result which is a horizontal line at `y=1` parallel to x-axis instead of shifting the axis as a whole. See issue #18901

**Comment by Smit-create** [comment]
On a side note: 
Please mention the issue you provide a fix for a `Fixes #issue_number`, so that it gets automatically closed once your PR gets merged.
Also, I see that you are working on master branch. You are suggested to create a new branch  and commit on it

**Comment by DhruvKothari22** [comment]
@Smit-create 
Yes, I am aware of that issue as well and had mentioned that as comments on my PR as well.
btw thanks for advice, I am new to open source.

**Comment by DhruvKothari22** [comment]
@sylee957 Just a small fix for #19013 
Pl. review

**Comment by sylee957** [comment]
Unfortunately, I don’t think that plot should rely on simplify because it can make things much slower in general

**Comment by moorepants** [comment]
You may want to ensure that this is not related to  #19051, which is a change in matplotlib 3.2

**Comment by oscarbenjamin** [comment]
This does not seem like the right fix because full simplify is not something that we want to use in general in library code. If you have other ideas for this then feel free to open a new pull request. Or if you would like help coming up with a fix then please discuss at issue #19013.

Thank you for the contribution but I'm going to close this now.

**Pull request closed without merging**
