### PR TITLE
Improve Travis testing

### LINKED ISSUE #12814: Replace 3.5 builds in Travis with 3.6
The builds that are just Python 2.7 and 3.5 should be changed to 2.7 and 3.6. We will need to find a 3.6 build of tensorflow to install. Otherwise this is easy to fix.

### LINKED ISSUE #13395: fix TEST_SAGE=yes Travis script
As discovered in #13392 the Travis testing of the SymPy --> Sage interface is non-functional. The test that should have failed was in #12826, the job log is https://travis-ci.org/sympy/sympy/jobs/257302234.

I'm not suggesting the fix is important, as we will have that testing in official Sage soon, but it may bite folks installing newer SymPy versions with Sage.

### LINKED ISSUE #13412: TEST_ASCII is not tested
https://github.com/sympy/sympy/blob/e97e23abe86bf8bb8136c827de89b1c74550b587/bin/test_travis.sh#L35-L46

`TEST_ASCII`, ASCII-only environment testing was added in #8364, but has several issues.

* `LC_ALL` environment variable is set to UTF-8(Unicode) in Travis, which overrides `LANG` variable. As a result, Python's stdout encoding is set to UTF-8(Unicode) during `TEST_ASCII`.
* Test failure does not raise Exception and therefore does not fail the Travis build.

Is `TEST_ASCII` necessary?

### PR DESCRIPTION
**Pull request by ylemkimon**
* Moved Tensorflow testing to optional dependencies testing and use latest version, as all builds use trusty distribution by https://github.com/sympy/sympy/commit/143c7a5d7ec764523ea0cbba4eb9a93a3a9b81c3, see https://github.com/sympy/sympy/pull/11439#r72668938
* Replaced 3.5 builds—optional dependencies, Sphinx(docs), and slow—with 3.6: Fixes #12814 
* Added quiet flag(`-q`) to `wget Miniconda` to hide the progress bar. (It takes about 1K lines of log and may exceed Travis view log limit)
* Test installation without setuptools only once in TEST_SETUP builds.
* Removed invalid escape error message, as compile can fail from various reasons, e.g., `SyntaxError`.
* Fixed TEST_ASCII:  Fixes #13412.

**Needs decision/Blocked by:**
* Added sage doctest of sympy/external/tests/test_sage.py to TEST_SAGE build, but does not work. Move sage interface into sage and remove `TEST_SAGE`?: #13395, #13430

### CODE REVIEW

**Comment by smichr** [comment]
> Alternative: Fix TEST_ASCII

Is there a reason not to fix it?

**Comment by ylemkimon** [comment]
@smichr I’m not sure TEST_ASCII is necessary.

**Comment by asmeurer** [comment]
Invalid escape stuff is too bad. It would be really nice to test that, but it's such a pain to get a good test for it. I'm fine with removing it for now at least. 

The TEST_ASCII was added at some point when I found a bug that only appeared when Unicode support didn't work. Perhaps we should just split it into a separate test as part of one of the builds, that just runs the printing tests.

**Comment by asmeurer** [comment]
Oh that's already what it was doing. Why remove it then? It shouldn't take that long. Although there's no need to clutter the Travis interface with the environment variable for it.

**Comment by asmeurer** [comment]
c.f. https://github.com/sympy/sympy/pull/8364

**Comment by ylemkimon** [comment]
@asmeurer Invalid escape sequence still fails Travis build and raises `SyntaxError: invalid escape sequence`. This PR just removes its error message, since other `SyntaxError`, e.g., `invalid syntax`, can fail compilation.

Instead of removing `TEST_ASCII`, fixed its issues.

**Pull request merged**
