### PR TITLE
Fixing a printing error in dmp_integrate

### LINKED ISSUE #12325: string formatting error in dmp_integrate_in
```pycon
>>> from sympy.polys import ring, QQ
>>> R, x, y = ring("x, y", QQ)
>>> R.dmp_integrate_in(x, 1, -1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sympy/polys/compatibility.py", line 457, in dmp_integrate_in
    return self.from_dense(dmp_integrate_in(self.to_dense(f), m, j, self.ngens-1, self.domain))
  File "/usr/lib/python3/dist-packages/sympy/polys/densetools.py", line 138, in dmp_integrate_in
    raise IndexError("0 <= j <= u expected, got %s" % (u, j))
TypeError: not all arguments converted during string formatting
```
Found using [pydiatra](https://github.com/jwilk/pydiatra).
Tested with sympy 1.0.

### PR DESCRIPTION
**Pull request by valglad**
Fixes #12325

### CODE REVIEW

**Comment by asmeurer** [comment]
Does this have more changes than you intended? I think only the sympy/polys/densetools.py changes should be there.

**Comment by valglad** [comment]
It is the only change. The other commits are from running `git pull` in my master branch a couple of times, they tagged along accidentally but should do no harm. Not sure about what the first one is. Considering I ran `git pull` afterwards, it should have no effect either.

**Comment by valglad** [comment]
Okay, not sure what this `fg` was but I have now reverted it. Sorry about that

**Comment by jksuom** [comment]
This looks good. A unit test is probably not necessary. I've checked that IndexError is raised instead of TypeError.

**Pull request merged**
