### PR TITLE
Corrected prior form leading to dead code in sympy.polys.polyroots.roots() function

### LINKED ISSUE #22768: Dead code in sympy.polys.polyroots.roots() function
While messing around with `roots()` method I saw things...

https://github.com/sympy/sympy/blob/27613158382a668605a21616706a8d64a3573997/sympy/polys/polyroots.py#L891

Here `f` is a `Poly` instance, and `Poly.length()` is a function.
So this expression is always `False` and followed block of code is dead.
Not sure if this can affect `roots()` correct behavior.

### PR DESCRIPTION
**Pull request by faze-geek**
#### References to other Issues or PRs

Fixes #22768

#### Brief description of what is fixed or changed
Made appropriate changes which handle dead code in` sympy.polys.polyroots.roots() ` function .
#### Release Notes

NO ENTRY

``

### CODE REVIEW

**Comment by faze-geek** [comment]
@smichr I have opened this pull request and made the code changes you had asked for .I will further add tests to check the functionality of that code snippet.
I am a new contributor and facing this issue on git-hub that, commits of a previous pull requests automatically get committed to a newer pull request although they have no relation with the newly created branch .Can you suggest how to get this thing corrected .I'll look into some tutorials till then and try to fix it from my side !

**Comment by oscargus** [comment]
I think you started from the branch where you had your previous changes. What you can do now is:

git rebase -i master

you will now get a list with different commits (from this and the previous branch). Simply remove the ones that you do not want (from the previous branch, only keeping "Fix for 22768"), save the file and close. Now, you can do

git push origin Fix_for_22768 --force

to overwrite this one. (Assuming that you have named your own fork origin.)

**Comment by oscargus** [comment]
Great that you figured it out!

**Comment by smichr** [comment]
Let's just get rid of the dead code -- the equation is being reduced to a the desired form in `preprocess_roots` so I don't think this code is necessary.

**Comment by smichr** [comment]
The case that Poly roots can handle is the case where powers have non-Add bases like `x**n` vs `(1 + x)**n`. The latter are expanded and the special code wouldn't handle that case and the roots preprocessing doesn't use `factor` to recover such expressions. The only place code might be useful is in `solve`:

Here is what the factored roots result looks like for the roots of `2*x**3 - 16*(y-1)**6*(z)**3`:

```python
>>> for k,v in roots(Poly(2*x**3 - 16*(y-1)**6*(z)**3, x)).items():factor(k)
...
2*(z**3*(y - 1)**6)**(1/3)
-I*(z**3*(y - 1)**6)**(1/3)*(sqrt(3) - I)
I*(z**3*(y - 1)**6)**(1/3)*(sqrt(3) + I)
```
Compare that to the simpler form that can be obtained from `solve` if the code is moved there:
```python
>>> solve(2*x**3 - 16*(y-1)**6*(z)**3, x, simpplify=False)  # simplification is not necessary
[2*z*(y - 1)**2, -z*(y - 1)**2 - sqrt(3)*I*z*(y - 1)**2, -z*(y - 1)**2 + sqrt(3)*I*z*(y - 1)**2]
```

**Comment by smichr** [comment]
This is the diff I used:
```diff
diff --git a/sympy/polys/polyroots.py b/sympy/polys/polyroots.py
index 2cd75a733c..845bad4c40 100644
--- a/sympy/polys/polyroots.py
+++ b/sympy/polys/polyroots.py
@@ -888,28 +888,6 @@ def roots(f, *gens,
                 raise PolynomialError("generator must be a Symbol")
             else:
                 f = F
-            if f.length == 2 and f.degree() != 1:
-                # check for foo**n factors in the constant
-                n = f.degree()
-                npow_bases = []
-                others = []
-                expr = f.as_expr()
-                con = expr.as_independent(*gens)[0]
-                for p in Mul.make_args(con):
-                    if p.is_Pow and not p.exp % n:
-                        npow_bases.append(p.base**(p.exp/n))
-                    else:
-                        others.append(p)
-                    if npow_bases:
-                        b = Mul(*npow_bases)
-                        B = Dummy()
-                        d = roots(Poly(expr - con + B**n*Mul(*others), *gens,
-                            **flags), *gens, **flags)
-                        rv = {}
-                        for k, v in d.items():
-                            rv[k.subs(B, b)] = v
-                        return rv
-
         except GeneratorsNeeded:
             if multiple:
                 return []
diff --git a/sympy/solvers/solvers.py b/sympy/solvers/solvers.py
index 2e294b94cf..418de1a123 100644
--- a/sympy/solvers/solvers.py
+++ b/sympy/solvers/solvers.py
@@ -1630,7 +1630,33 @@ def _expand(p):
                 flags['tsolve'] = True
                 hints = ('cubics', 'quartics', 'quintics')
                 solvers = {h: flags.get(h) for h in hints}
-                soln = roots(poly, **solvers)
+
+                if f_num.is_Add and deg != 1:
+                    # check for foo**n factors in the constant
+                    # which Poly will have expanded
+                    n = deg
+                    npow_bases = []
+                    others = []
+                    expr = f_num
+                    con, dep = expr.as_independent(gens[0])
+                    for p in Mul.make_args(con):
+                        if p.is_Pow and not p.exp % n:
+                            npow_bases.append(p.base**(p.exp//n))
+                        else:
+                            others.append(p)
+                    if npow_bases:
+                        b = Mul(*npow_bases)
+                        B = Dummy(positive=True)
+                        d = roots(Poly(dep + B*Mul(*others), gens[0],
+                            composite=True), gens[0], **solvers)
+                        rv = {}
+                        restore = {B**(S.One/n): b}
+                        for k, v in d.items():
+                            rv[k.xreplace(restore)] = v
+                        soln = rv
+
+                if soln is None:
+                    soln = roots(poly, **solvers)
                 if sum(soln.values()) < deg:
                     # e.g. roots(32*x**5 + 400*x**4 + 2032*x**3 +
                     #            5000*x**2 + 6250*x + 3189) -> {}
```

**Pull request merged**
