### PR TITLE
Re-added a deprecated version of ClassRegistry and C

### PR DESCRIPTION
**Pull request by toolforger**

### CODE REVIEW

**Comment by toolforger** [comment]
I had to move this into a separate package to avoid import cycles.

**Comment by toolforger** [comment]
Anybody got an idea why it's not finding the new module?
It's working just fine locally.

**Comment by debugger22** [comment]
You'll have to add this module to setup.py. On travis, the installed sympy is used which is done via `setup.py`.
```diff
diff --git a/setup.py b/setup.py
index 0c390bc..73c384d 100755
--- a/setup.py
+++ b/setup.py
@@ -126,6 +126,7 @@
     'sympy.utilities',
     'sympy.utilities.mathml',
     'sympy.vector',
+    'sympy.deprecated',
 ]
 
 class audit(Command):
@@ -300,6 +301,7 @@ def run(self):
     'sympy.unify.tests',
     'sympy.utilities.tests',
     'sympy.vector.tests',
+    'sympy.deprecated.tests',
     ]
 
```

**Comment by debugger22** [comment]
It looks like they are ordered. Perhaps, last line is not the good place.

**Comment by toolforger** [comment]
Ah, I had some dim memories of something like that but I couldn't recall what exactly it was.
Thanks. Fixed. Travis seems happy now.
Now on to investigating that unexpected failing test...

**Comment by debugger22** [comment]
I think `sympy.deprecated.tests` should be added in `setup.py` in order to let travis run these tests.

**Comment by toolforger** [comment]
Aw dangit. Fixed.

**Comment by toolforger** [comment]
Somebody please restart the test suite.

**Comment by toolforger** [comment]
The failure is a stalled test.

**Comment by toolforger** [comment]
Squashed the commits. This should be ready to go in.

**Comment by jcrist** [comment]
Looks good to me. Merging. Please create an issue to remove the deprecation (similar to #7853 for lambdify), and update the release notes.

**Comment by toolforger** [comment]
Issue is already in `@deprecate`: #7124

**Comment by jcrist** [comment]
Yes - need an issue to *remove the deprecation* after next release. Read the example I posted.

**Comment by toolforger** [comment]
Ah... I've been assuming that that's also done in the original issue.
#7124 can be closed then.

**Comment by toolforger** [comment]
Deprecation issue is #9371.

**Comment by toolforger** [comment]
https://github.com/sympy/sympy/wiki/Release-Notes-for-0.7.7 updated, too.

**Pull request merged**
