### PR TITLE
Coherent state support for 1d quantum harmonic oscillator

### PR DESCRIPTION
**Pull request by zasdfgbnm**
This pull request is used to satisfy the requirement that each applicant of GSoC 2015 must send a patch to sympy.

In this patch, I implement coherent state support for 1d quantum harmonic oscillator.

See http://en.wikipedia.org/wiki/Coherent_states for more detail about coherent state of quantum harmonic oscillator.

In my application, I also proposed a more systematic way of implementing sympy.physics.quantum, this patch will be migrated to the new structure if I'm approved for GSoC.

### CODE REVIEW

**Comment by moorepants** [comment]
@zasdfgbnm Can you please write a unit test to test your new function?

**Comment by zasdfgbnm** [comment]
Hi, I've finished the unit test. Is there something else for me to do?

**Comment by debugger22** [comment]
You should also fix formatting issues such as:

* Space around `+`, `=`(except for arguments), `==`.
* Space after `,`.
* Give reference as shown in development workflow.

**Comment by debugger22** [comment]
I did not mention spaces around `*` and `**`. It is avoided to do so in SymPy.

**Comment by zasdfgbnm** [comment]
OK, but I'm confused because the codes that have already been in sympy in the same file sometimes have spaces around *, sometimes have space only on the right of * and sometimes no space at all...

**Comment by debugger22** [comment]
Perhaps they slipped in for some reason.

**Comment by toolforger** [comment]
There are formatting mistakes in the SymPy code, so following that as an example isn't always the easiest route. I see that fixing these is easy enough.

However, you need to fix the failing unit test before this can go in.
You can check your test code locally, try ```bin/test --help``` for the possibilities.

**Comment by zasdfgbnm** [comment]
Fixed

**Comment by certik** [comment]
That looks good, thanks!

**Pull request merged**
