### PR TITLE
Add Determinant Hint for doit method

### PR DESCRIPTION
**Pull request by mgreminger**
#### Brief description of what is fixed or changed
The evaluation of determinants can be expensive when performed on symbolic matrices of even modest size. Because of this, it is desirable to be able to delay the evaluation of determinants in some cases by passing a hint to the `doit` method similar to the `inv_expand` hint for matrix inverse. This change adds the `determinant` hint to achieve this goal.

Old Behavior:
```python
>>> import sympy as sp
>>> a,b,c,d = sp.symbols('a,b,c,d')
>>> sp.Determinant(sp.Matrix([[a,b],[c,d]])).doit(determinant=False)
a*d - b*c
```

New Behavior:
```python
>>> import sympy as sp
>>> a,b,c,d = sp.symbols('a,b,c,d')
>>> sp.Determinant(sp.Matrix([[a,b],[c,d]])).doit(determinant=False)
Determinant(Matrix([
[a, b],
[c, d]]))
```

#### Release Notes

* matrices
  * Add determinant hint for doit method to allow the evaluation of matrix determinants to be skipped when set to False .

### CODE REVIEW

**Comment by mgreminger** [comment]
Refactored the change to be lest nested, better matches other hint checks in the code such as the [one for `inv_expand`](https://github.com/sympy/sympy/blob/fc41017343b33a7cf73902fbf9aedf158da5e7f1/sympy/matrices/expressions/inverse.py#L62C1-L63C1)

**Comment by oscarbenjamin** [comment]
I don't necessarily object to this change but ultimately it would be better to have a more general way of controlling what `doit` does rather than unspecified keyword arguments. Ideally it would be something like:
```python
e.doit(Integral) # only do integrals
e.doit(exclude=Determinant) # do everything except determinants.
```
Probably the first form is more useful: usually you know which part of the expression you actually wanted to "do it" and anything else is an unwanted side effect.

Prior art is `rewrite`:
```python
In [177]: e = sin(x) + cos(x) + tan(x)

In [178]: e.rewrite(exp)
Out[178]: 
  ⎛   ⅈ⋅x    -ⅈ⋅x⎞     ⎛ ⅈ⋅x    -ⅈ⋅x⎞    ⅈ⋅x    -ⅈ⋅x
ⅈ⋅⎝- ℯ    + ℯ    ⎠   ⅈ⋅⎝ℯ    - ℯ    ⎠   ℯ      ℯ    
────────────────── - ──────────────── + ──── + ─────
    ⅈ⋅x    -ⅈ⋅x             2            2       2  
   ℯ    + ℯ                                         

In [179]: e.rewrite(sin, exp)
Out[179]: 
    ⎛ ⅈ⋅x    -ⅈ⋅x⎞                  
  ⅈ⋅⎝ℯ    - ℯ    ⎠                  
- ──────────────── + cos(x) + tan(x)
         2                          

In [180]: e.rewrite([sin, cos], exp)
Out[180]: 
    ⎛ ⅈ⋅x    -ⅈ⋅x⎞    ⅈ⋅x             -ⅈ⋅x
  ⅈ⋅⎝ℯ    - ℯ    ⎠   ℯ               ℯ    
- ──────────────── + ──── + tan(x) + ─────
         2            2                2
```

**Comment by sylee957** [comment]
I kind of believe that everything has to be added to keyword in the end, and it complicates the things a lot.
But unlike the ideas of @oscarbenjamin, I support other way of dependency inversion control though
I think that SymPy evaluators should rely on callback functions to do `det = (Matrix) -> Expr`, and sympy should be written to use callbacks that abstracts add, multiply, determinant, ... such than pulling out the actual add, multiply, determinant somewhere.
For example, Add can just be typed as `(Expr, Expr) -> Expr` function.
It should allow users to write callbacks as much as they want, such that they have full control.

**Comment by oscarbenjamin** [comment]
> I can take a shot at implementing @oscarbenjamin's suggested approach, I'll have a chance to take a look at it later this week or early next week.

To be clear making that approach work is more complicated than you might think. There are many classes in SymPy with `doit` methods and the current structure would mean that *every* one of those should be changed if the signature of `doit` is to be changed.

The first step in this approach is to separate `doit` into a `doit` method and an `_eval_doit` method (similar to `subs` and `_eval_subs`). The idea would be that `Basic` defines a `doit` method that calls `_eval_doit`. Then `Basic.doit` handles recursion and options like `deep` and so on and then subclasses can define `_eval_doit` which should not need to process any options. That separation means that there can be one place where the behaviour of `doit` is controlled which then makes it possible to change the signature in one place.

We might also need some backwards compatibility code in case of downstream code with classes that have defined their own `doit` methods.

There are a lot of `doit` methods in the codebase that would need to be renamed to `_eval_doit` and simplified (e.g. to remove `deep` handling):
```console
$ git grep 'def doit'
doc/src/guides/custom-functions.md:...     def doit(self, deep=False, **hints):
doc/src/guides/custom-functions.md:...     def doit(self, deep=True, **hints):
doc/src/guides/custom-functions.md:...     def doit(self, deep=False, **hints):
doc/src/guides/custom-functions.md:...     def doit(self, deep=True, **hints):
sympy/combinatorics/tests/test_prufer.py:    def doit(t, b):
sympy/concrete/products.py:    def doit(self, **hints):
sympy/concrete/summations.py:    def doit(self, **hints):
sympy/core/basic.py:    def doit(self, **hints):
sympy/core/basic.py:    def doit(self, **hints):
sympy/core/expr.py:    def doit(self, **hints):
sympy/core/function.py:    def doit(self, **hints):
sympy/core/function.py:    def doit_numerically(self, z0):
sympy/core/function.py:    def doit(self, **hints):
sympy/core/operations.py:    def doit(self, **hints):
sympy/functions/elementary/complexes.py:    def doit(self, **hints):
sympy/functions/elementary/piecewise.py:    def doit(self, **hints):
sympy/functions/special/beta_functions.py:    def doit(self, **hints):
sympy/functions/special/tensor_functions.py:    def doit(self, **hints):
sympy/integrals/integrals.py:    def doit(self, **hints):
sympy/integrals/laplace.py:    def doit(self, **hints):
sympy/integrals/laplace.py:    def doit(self, **hints):
sympy/integrals/transforms.py:    def doit(self, **hints):
sympy/integrals/transforms.py:    def doit(self, **hints):
sympy/matrices/common.py:    def doit(self, **hints):
sympy/matrices/expressions/adjoint.py:    def doit(self, **hints):
sympy/matrices/expressions/applyfunc.py:    def doit(self, **hints):
sympy/matrices/expressions/determinant.py:    def doit(self, expand=False, **hints):
sympy/matrices/expressions/determinant.py:    def doit(self, expand=False, **hints):
sympy/matrices/expressions/diagonal.py:    def doit(self, **hints):
sympy/matrices/expressions/dotproduct.py:    def doit(self, expand=False, **hints):
sympy/matrices/expressions/hadamard.py:    def doit(self, **hints):
sympy/matrices/expressions/inverse.py:    def doit(self, **hints):
sympy/matrices/expressions/kronecker.py:    def doit(self, **hints):
sympy/matrices/expressions/matadd.py:    def doit(self, **hints):
sympy/matrices/expressions/matexpr.py:    def doit(self, **hints):
sympy/matrices/expressions/matmul.py:    def doit(self, **hints):
sympy/matrices/expressions/matpow.py:    def doit(self, **hints):
sympy/matrices/expressions/permutation.py:    def doit(self, **hints):
sympy/matrices/expressions/permutation.py:    def doit(self, deep=True, **hints):
sympy/matrices/expressions/special.py:    def doit(self, **hints):
sympy/matrices/expressions/trace.py:    def doit(self, **hints):
sympy/matrices/expressions/transpose.py:    def doit(self, **hints):
sympy/physics/control/lti.py:    def doit(self, **hints):
sympy/physics/control/lti.py:    def doit(self, cancel=False, **kwargs):
sympy/physics/control/lti.py:    def doit(self, **hints):
sympy/physics/control/lti.py:    def doit(self, **hints):
sympy/physics/control/lti.py:    def doit(self, cancel=False, expand=False, **hints):
sympy/physics/control/lti.py:    def doit(self, cancel=True, expand=False, **hints):
sympy/physics/quantum/anticommutator.py:    def doit(self, **hints):
sympy/physics/quantum/cg.py:    def doit(self, **hints):
sympy/physics/quantum/cg.py:    def doit(self, **hints):
sympy/physics/quantum/cg.py:    def doit(self, **hints):
sympy/physics/quantum/cg.py:    def doit(self, **hints):
sympy/physics/quantum/commutator.py:    def doit(self, **hints):
sympy/physics/quantum/density.py:    def doit(self, **hints):
sympy/physics/quantum/innerproduct.py:    def doit(self, **hints):
sympy/physics/quantum/spin.py:    def doit(self, **hints):
sympy/physics/quantum/tensorproduct.py:    def doit(self, **hints):
sympy/physics/quantum/trace.py:    def doit(self, **hints):
sympy/physics/secondquant.py:    def doit(self, **hints):
sympy/physics/secondquant.py:    def doit(self, **hints):
sympy/physics/vector/dyadic.py:    def doit(self, **hints):
sympy/physics/vector/vector.py:    def doit(self, **hints):
sympy/physics/wigner.py:    def doit(self, **hints):
sympy/polys/rootoftools.py:    def doit(self, **hints):
sympy/sandbox/indexed_integrals.py:    def doit(self):
sympy/series/limits.py:    def doit(self, **hints):
sympy/sets/fancysets.py:    def doit(self, **hints):
sympy/simplify/hyperexpand.py:    def doit(C):
sympy/stats/rv.py:    def doit(self, evaluate=True, **kwargs):
sympy/stats/symbolic_probability.py:    def doit(self, **hints):
sympy/stats/symbolic_probability.py:    def doit(self, **hints):
sympy/stats/symbolic_probability.py:    def doit(self, **hints):
sympy/stats/symbolic_probability.py:    def doit(self, **hints):
sympy/tensor/array/array_comprehension.py:    def doit(self, **hints):
sympy/tensor/array/expressions/array_expressions.py:    def doit(self, **hints):
sympy/tensor/array/expressions/array_expressions.py:    def doit(self, *args, **kwargs):
sympy/tensor/tensor.py:    def doit(self, **hints):
sympy/tensor/tensor.py:    def doit(self, **hints):
sympy/tensor/tensor.py:    def doit(self, **hints):
sympy/tensor/toperators.py:    def doit(self, **hints):
sympy/vector/basisdependent.py:    def doit(self, **hints):
sympy/vector/operators.py:    def doit(self, **hints):
sympy/vector/operators.py:    def doit(self, **hints):
sympy/vector/operators.py:    def doit(self, **hints):
sympy/vector/operators.py:    def doit(self, **hints):
sympy/vector/vector.py:    def doit(self, **hints):
sympy/vector/vector.py:    def doit(self, **hints):
```

**Comment by sylee957** [comment]
> The situation I'm in is that I have fairly complex symbolic expressions where evaluating a matrix inverse or determinant is very expensive (if not impossible) until I sub in the numerical values at the end.

However, as far as I also have went through this details at work before,
It's just more easy to devise your own SymPy evaluator (like presented in SymPy tutorials about advanced expression manipulation) than doing anything to the core.

Although it's one case of the usage, but it is not everyone needs now, and I just want to make sympy to remain simple and see more cleanups going on there, and defer adding something more going on there.

**Comment by mgreminger** [comment]
@sylee957, thanks for the clarification. That makes sense, walk the expression tree and call the `doit` method on the particular entities that I'm wanting to evaluate. I'll go ahead and try that for my project and I'll close this pull request if I can get that working.

However, in the long term, I would argue that what @oscarbenjamin is suggesting would be a good approach to this issue and would simplify the core by making each classes `doit` method simpler and more consistent.

**Comment by oscarbenjamin** [comment]
Many SymPy methods have top-level associated functions e.g. `simplify(expr)` vs `expr.simplify()` (`factor`, `trigsimp`, `collect`, ...). If we added a top-level `doit` function then it would be easier to adapt the signature of that function to do e.g. `doit(expr, Integral)` or `doit(expr, exclude=Determinant)`. It could recursively call `.doit(deep=False)` but otherwise control which expressions are asked to "do it". That would be easier than adapting all `.doit()` methods (although we definitely should introduce an `_eval_doit` method in the end for other reasons as well as this).

**Comment by sylee957** [comment]
Anyway, I would favor someone to split the logic for the `deep=True` in `doit` for consistency cleanups first of all, if he wants to get into contribution of SymPy.

**Comment by oscarbenjamin** [comment]
> I would favor someone to split the logic for the `deep=True` in `doit` for consistency cleanups

Yes, we need `_eval_doit` regardless of the issue discussed here. The different `doit` methods are a mess.

**Comment by mgreminger** [comment]
Thanks for the discussion, will close this pull request in favor of implementing fix for the original issue with user code using expression manipulation as suggested by @sylee957

**Pull request closed without merging**
