### PR TITLE
Fixes print order of sympy.vector object.

### LINKED ISSUE #23058: display bug while using pretty_print with sympy.vector object in the terminal
The following code jumbles some of the outputs in the terminal, essentially by inserting the unit vector in the middle -
```python
from sympy import *
from sympy.vector import CoordSys3D, Del

init_printing()

delop = Del()
CC_ = CoordSys3D("C")
x,    y,    z    = CC_.x, CC_.y, CC_.z
xhat, yhat, zhat = CC_.i, CC_.j, CC_.k

t = symbols("t")
ten = symbols("10", positive=True)
eps, mu = 4*pi*ten**(-11), ten**(-5)

Bx = 2 * ten**(-4) * cos(ten**5 * t) * sin(ten**(-3) * y)
vecB = Bx * xhat
vecE = (1/eps) * Integral(delop.cross(vecB/mu).doit(), t)

pprint(vecB)
print()
pprint(vecE)
print()
pprint(vecE.doit())
```

Output:
```python
⎛     ⎛y_C⎞    ⎛  5  ⎞⎞    
⎜2⋅sin⎜───⎟ i_C⋅cos⎝10 ⋅t⎠⎟
⎜     ⎜  3⎟           ⎟    
⎜     ⎝10 ⎠           ⎟    
⎜─────────────────────⎟    
⎜           4         ⎟    
⎝         10          ⎠    

⎛     ⌠                           ⎞    
⎜     ⎮       ⎛y_C⎞    ⎛  5  ⎞    ⎟ k_C
⎜     ⎮ -2⋅cos⎜───⎟⋅cos⎝10 ⋅t⎠    ⎟    
⎜     ⎮       ⎜  3⎟               ⎟    
⎜  11 ⎮       ⎝10 ⎠               ⎟    
⎜10  ⋅⎮ ─────────────────────── dt⎟    
⎜     ⎮             2             ⎟    
⎜     ⎮           10              ⎟    
⎜     ⌡                           ⎟    
⎜─────────────────────────────────⎟    
⎝               4⋅π               ⎠    

⎛   4    ⎛  5  ⎞    ⎛y_C⎞ ⎞    
⎜-10 ⋅sin⎝10 ⋅t⎠⋅cos⎜───⎟ k_C ⎟
⎜                   ⎜  3⎟ ⎟    
⎜                   ⎝10 ⎠ ⎟    
⎜─────────────────────────⎟    
⎝           2⋅π           ⎠    ```

### PR DESCRIPTION
**Pull request by wermos**
#### References to other Issues or PRs

Fixes #23058 

#### Brief description of what is fixed or changed
The algorithm for placing the vector string assumed that there was only one pair of parentheses and didn't account for the possibility of multiple pairs. I added support for multiple pairs of parentheses.

#### Release Notes

* printing
  * Fixed a bug in pretty_print, where sympy.vector objects were being incorrectly printed in certain cases.

### CODE REVIEW

**Comment by wermos** [comment]
This bug was really hard to find. The code for `_print_BasisDependent` is extremely cryptic. I am working on a rewrite of the portion which uses the `flag` hack. I made sure to add comments explaining what I am doing and why 😁

I tried to figure out how to add a test for this, but I was unable to figure it out. I tried adding a test by testing the `_print_BasisDependent` function specifically, but I couldn't figure out how to work with the `prettyForm` function.

**Comment by oscargus** [comment]
Would it be possible to use the failing cases from #23058 as tests? What do they look like now?

**Comment by wermos** [comment]
Thank you for your suggestion. While fixing the test errors for #23194, I got a glimpse at how the pretty printer for `sympy.vector` is tested, so now I know how to add the tests and am adding them now.

I expected all printer-related tests to be in `sympy/pretty/tests/`, but it appears that the vector-related tests are actually in `sympy/vector/tests/`.

**Comment by oscargus** [comment]
Yes, it it possible to edit the release notes until it is merged (and in the file linked in sympy-bot reply afterwards).

**Comment by oscargus** [comment]
Looks good! I guess one ideally would like to vertically align the unit vector better as well, but that could go in a later PR.

**Comment by oscargus** [comment]
Are you happy with this now? (Just though I'd check in case you had other things you wanted to implement.) Looks good to me as is.

**Comment by wermos** [comment]
Yes, I am happy with the way this PR is.

It seems that there was a small misunderstanding. When I said I was working on a rewrite, I meant that I was doing it in a different branch, and the end result would be a different PR whose goal would be to merge a more well-explained approach to pretty-printing `sympy.vector` objects. This branch was supposed to be a hot-fix type thing. That is why I tried to keep the changes to a minimum.

From what I have understood of the SymPy way of doing things, one should keep PRs small. Do I have the right idea, or should I just move over my rewrite work (which is still incomplete) over to this branch?

**Comment by oscargus** [comment]
Yes, I was unsure about that.

> From what I have understood of the SymPy way of doing things, one should keep PRs small. Do I have the right idea, or should I just move over my rewrite work (which is still incomplete) over to this branch?

It is probably easier to get small PRs in, yes, as it is easier as a reviewer to (hopefully) understand what is happening and that can avoid stalling reviews (and PRs). Although I do not think that there is a particular preferred way as such.

Thanks for this!

**Pull request merged**
