### PR TITLE
Fix of Matrix expressions sometimes gives Add and Mul instead of MatA…

### LINKED ISSUE #15665: Matrix expressions sometimes gives Add and Mul instead of MatAdd and MatMul
```
>>> A = MatrixSymbol("A", n, n)
>>> B = MatrixSymbol("B", n, n)
>>> type(Mul(A, B))
<class 'sympy.matrices.expressions.matmul.MatMul'>
>>> type(Mul(-1, Mul(A, B)))
<class 'sympy.core.mul.Mul'>
```

In https://github.com/sympy/sympy/pull/15373, MatAdd and MatMul were made to subclass Add and Mul.

However, the code in Mul.flatten doesn't handle this case correctly. The problem is that in order to return the right type, it puts the args in the c_part, not the nc_part (the `nc_part` is a list of args, which are passed to Mul._make_args). But it doesn't take this logic into account when processing an arg that is itself a Mul. 

I don't know if there is a simple fix here. Mul.flatten was not designed to be able to return subclasses of Mul, and the current behavior of keeping the MatMul in c_part is a bit of a hack. 

This issue prevents some simplifications from working (in conjunction with other fixes at https://github.com/sympy/sympy/pull/15121), because the Mul/Add types that should be MatMul/MatAdd cause type checks in the matrix expressions module to fail. 

I would suggest reverting https://github.com/sympy/sympy/pull/15373 (CC @Upabjojr). It was also merged without any review.

### PR DESCRIPTION
**Pull request by jmig5776**
…dd and MatMul

#### References to other Issues or PRs

Fixes #15665 

#### Brief description of what is fixed or changed
Modified Mul.flatten such that it returns the correct return type in case of matrices i.e

>>> A = MatrixSymbol("A", n, n)
>>> B = MatrixSymbol("B", n, n)
>>> type(Mul(A, B))
<class 'sympy.matrices.expressions.matmul.MatMul'>
>>> type(Mul(-1, Mul(A, B)))
<class 'sympy.matrices.expressions.matmul.MatMul'>

#### Release Notes

* core
       * fixed a bug in the flatten function

### CODE REVIEW

**Comment by jmig5776** [comment]
@asmeurer , @smichr  Please review it.

**Comment by jmig5776** [comment]
@smichr I think it can merge into master.

**Comment by asmeurer** [comment]
I'll take a look. Can you add tests.

**Comment by jmig5776** [comment]
Yeah sure I will add some tests

**Comment by jmig5776** [comment]
@asmeurer I had added the test cases .

**Comment by asmeurer** [comment]
This doesn't seem to fix the error from https://github.com/sympy/sympy/issues/15120 (you may need to merge in the branch from https://github.com/sympy/sympy/pull/15121 first). The following should work without giving an exception

```py
import sympy as sy
n = sy.symbols('n')
A = sy.MatrixSymbol("A",n,n)
B = sy.MatrixSymbol("B",n,n)
C = sy.MatrixSymbol("C",n,n)
M = A.inverse()*B.inverse() - A.inverse()*C*B.inverse()
a = B.inverse()*M.inverse()*A.inverse()
factor(a)
```

**Comment by jmig5776** [comment]
Ohh I was unaware about #15120 . Should I merge into branch of #15121 ?. Or I should work to solve this here explicitly.

**Comment by asmeurer** [comment]
Sorry, I mean to test merge against that branch to test, but don't actually push the merge up here. You could create a new branch first before merging, or use a detached HEAD.

**Comment by asmeurer** [comment]
To clarify, merging my branch will be necessary to avoid other bugs unrelated to this one.

**Comment by jmig5776** [comment]
> This doesn't seem to fix the error from #15120 (you may need to merge in the branch from #15121 first). The following should work without giving an exception
> 
> ```python
> import sympy as sy
> n = sy.symbols('n')
> A = sy.MatrixSymbol("A",n,n)
> B = sy.MatrixSymbol("B",n,n)
> C = sy.MatrixSymbol("C",n,n)
> M = A.inverse()*B.inverse() - A.inverse()*C*B.inverse()
> a = B.inverse()*M.inverse()*A.inverse()
> factor(a)
> ```

I tested the merge with your branch but it is does not seems to fix above error.

**Pull request closed without merging**
