### PR TITLE
Update diophantine to use enum instead of set of strings

### PR DESCRIPTION
**Pull request by ethankward**
#### Brief description of what is fixed or changed
Instead of using magic strings everywhere in the file (and tests), use an enum.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I guess we need to drop Python 2.7 first

**Comment by ethankward** [comment]
I'll do something else with this.

**Comment by oscarbenjamin** [comment]
I just looked at this and it looks good. Sorry it didn't get reviewed...

**Comment by ethankward** [comment]
It's fine, I'm planning on making much larger changes to diophantine, so this was unnecessary.

**Comment by asmeurer** [comment]
Wouldn't this break API? It doesn't seem like Enum entries compare equal to their values.

**Pull request closed without merging**
