### PR TITLE
 And/Or are more aware of arg interactions … 

### LINKED ISSUE #8373: Simplification of Relational and BooleanFunction
Consider the following:

``` python
In [6]: x = Symbol('x', real=True)

In [7]: simplify(Or(x<1, x>= 1))
Out[7]: Or(x < 1, x >= 1)
```

I'd expect the result to be `True` or somehow else to designate "all `x`".

Even if I force the symbol to be a positive integer, this does not simplify:

``` python
In [3]: r = Symbol('r', integer=True, positive=True)

In [4]: Or(r<1, r>= 1)
Out[4]: Or(r < 1, r >= 1)

In [5]: simplify(Or(r<1, r>= 1))
Out[5]: Or(r < 1, r >= 1)
```

which is a bit odd. All of this causes over-complicated outputs sometimes. For example, trying to sum the PMF of a negative binomial distribution with `p=1/2`, I get

``` python
In [3]: k = Symbol('k', integer=True, nonnegative=True)

In [4]: r = Symbol('r', integer=True, positive=True)

In [5]: Sum(binomial(k+r-1,k)*(S.Half)**r*S.Half**k, (k, 0, oo)).doit()
Out[5]: Piecewise((1, Or(r < 1, r >= 1)), (Sum(2**(-k)*2**(-r)*binomial(k + r - 1, k), (k, 0, oo)), True))
```

### PR DESCRIPTION
**Pull request by smichr**
strong/weak interaction

```
And(x<=0, x<0) -> x<0
Or(x<=0, x<0) -> x<=0
```

In/Unequality and noncomplementary True/False

```
>>> Or(x<0,x>0)
Ne(x, 0)
>>> Or(x<=0,x>=0)
True
>>> And(x<0,x>0)
False
>>> And(x<=0,x>=0)
Eq(x, 0)
 ```

closes #8373 

Future (a different PR) enhancements might look for interactions between `Eq` and other elements, but it is not my impression that those are encountered as often:

```
And(Eq(x, 1), x > 1) -> False
And(Eq(x, 1), x>0) -> Eq(x, 1)
And(Eq(x,0), Eq(x, 1)) ->False
```

### CODE REVIEW

**Comment by smichr** [comment]
> In/Unequality and noncomplementary True/False
> >>> Or(x<0,x>0)
> Ne(x, 0)
> >>> Or(x<=0,x>=0)
> True
> >>> And(x<0,x>0)
> False
> >>> And(x<=0,x>=0)
> Eq(x, 0)

On second thought, this is probably not the right thing to do since returning Eq, Ne, True or False would give a different implication than the originals if x were imaginary, e.g. `Or(x<0,x>0)` would raise an error if `x->I`, but `Ne(x, 0)` would yield True.  Is there no way around this?

**Comment by jksuom** [comment]
Maybe some of these expressions should be left unchanged. `Or(x >= 0, x <= 0)` is True if and only if `x` is  real or `oo` or `-oo`, or, in other words, when `Q.extended_real(x)` is True. But for nonreal arguments `Q.extended_real(x)` does not raise an error. So, strictly speaking, the two expressions are not functionally equivalent. I have no clear view of what should be done (other than that a plain True does not seem appropriate).

The same problem appears in even simpler contexts. Should `x > 0` and `Q.positive(x)` have the same meaning?

**Comment by asmeurer** [comment]
The error raising in inequalities is there because they are used in contexts outside of the assumptions system. As far as the assumptions are concerned, I think `x > 0` should be equivalent to `Q.positive(x) | Eq(x, oo)`. 

It's right that `Or(x >= 0, x <= 0)` is logically equivalent to `Q.extended_real(x)`. For logical equivalence, we should minimize automatic simplification to only trivial stuff (like short circuiting), and leave more complex things to the assumptions system and logic module routines. I already think the inequalities are being too smart in this regard, and I don't like seeing that bleed into the logic classes. So I'm -1 to this.

**Comment by smichr** [comment]
How do the two of you feel about only the first modification?  It still retains the inequality (as opposed to the True or False result). I'm not too concerned if this is not passed since if expressions like this are generated by SymPy it could mean that better construction at the point of generation is needed rather than cleanup at instantiation.

In order to get the existing relationships working better, however, I think we need to denest the args as I have done in this PR.

```
And(x<=0, x<0) -> x<0
Or(x<=0, x<0) -> x<=0
```

**Comment by jksuom** [comment]
And(x<=0, x<0) -> x<0
    Or(x<=0, x<0) -> x<=0

I think these simplifications are good. Maybe also `Or(x == 0, x < 0) -> x <= 0` could be added.

**Comment by asmeurer** [comment]
I would personally rather see that upward in the chain, in a simplification function. I don't much like automatic simplification in general, but having And and Or know about inequalities feels like a broken abstraction.

**Comment by asmeurer** [comment]
And we desperately need some kind of simplification function that can simplify conditionals with inequalities, of which this sort of thing would just be part of. It would help a lot with the conditions returned by the meijerg algorithm. 

So to be clear, I'm not opposed to the simplification, just to having And and Or do it automatically. Why not start a simplify_inequalities (or some better name) with this logic?

**Comment by jksuom** [comment]
I also think that there should be a simplification function for inequalities (`compsimp`?). If that is implemented, then these automatic simplifications won't be needed. They are, in fact, a little out of place in the boolalg module.

**Comment by asmeurer** [comment]
Took me a moment to figure out what the "comp" in "compsimp" meant, plus it's very close to `combsimp`, so I'm not a fan of that specific name.

**Pull request closed without merging**
