### PR TITLE
Extend factorial2 to real numbers

### LINKED ISSUE #20253: Complex and real arguments for factorial2
Currently, `factorial2` does not support complex and real-valued arguments:

```julia
In [1]: factorial(1.5)
Out[1]: 1.32934038817914

In [2]: factorial2(1.5)
...
ValueError: argument must be nonnegative integer or negative odd integer
```

This identity from [Wolfram](https://functions.wolfram.com/GammaBetaErf/Factorial2/02/0001/) should work well enough:

image

### PR DESCRIPTION
**Pull request by weakit**
#### References to other Issues or PRs
Closes #20253 

#### Brief description of what is fixed or changed
- `factorial2` returns for real valued inputs. (using this [extension](https://functions.wolfram.com/GammaBetaErf/Factorial2/02/0001/))
- rewriting `factorial2` as `gamma` (or `cos`) gives the new identity.
- `factorial` has a rewrite as `factorial2` method.
- additional tests for `factorial2`

#### Other comments

This is a neater version of #20345

#### Release Notes

* functions
     * factorial2 accepts real valued arguments.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
The diff here shows a lot of unrelated changes. I think that you are using an editor that automatically formats files. It's hard to see what you have actually changed because of this.

I suggest starting again with a new PR to avoid unintentionally making all of these changes in the history.

**Comment by weakit** [comment]
They're mainly just formatting, but ok. I'll make another PR.

**Comment by jksuom** [comment]
In the new PR, do not make `factorial2.eval` depend on `cos`.

`factorial2` is actually a combination of two functions:

    2**k*factorial(k)                             for even arguments n = 2*k and
    factorial(2*k + 1)/2**k*factorial(k)          for odd arguments n = 2*k + 1.

These can be efficiently implemented in `factorial2.eval`. The values can also be rewritten in terms of `gamma` but the two expressions are different and `Piecewise` is needed to combine them.

The formula from Wolfram is intended for languages that do not implement piecewise functions. It is based on the observation that `(1 - cos(pi*n))/2`, restricted to the set of integers, is the characteristic function of the set of odd integers: 1 for odd `n` and 0 for even `n`. It can be used to compute the values of `factorial2` for integer arguments but otherwise its values have no useful meaning. It is not needed in SymPy as the test `n.is_even` is more efficient than the computation of `cos(pi*n)` though it could be returned by `_rewrite_as_gamma` in case `piecewise=False` (cf. https://github.com/sympy/sympy/issues/20253#issuecomment-708013095).

**Comment by weakit** [comment]
Thanks for the advice! I'll make sure to look into implementing that.

Apparently `mpmath` has a built in factorial2 method, [also using the same definition](http://mpmath.org/doc/current/functions/gamma.html#fac2). I'll be using this to calculate the factorial for real inputs.

**Comment by weakit** [comment]
See #20392.

**Pull request closed without merging**
