### PR TITLE
Fix 10198 - Solving abs with negative powers

### PR DESCRIPTION
**Pull request by akki**
This should solve the issue. Please let me know if anything else is required.
Relevant tests have also been added.

### CODE REVIEW

**Comment by smichr** [comment]
The notes I added seem to have been lost: 

1. this is a duplicate of #10286 
1. if @Curious72 responds to the notes I left by Monday, then let's go with his version otherwise
1. if you make those changes that I suggested there, then I will commit this one on Tuesday

**Comment by smichr** [comment]
FYI - I stopped the tests since although they will pass, they are wrong as indicated in the duplicate PR.

**Comment by akki** [comment]
Why is it a problem if n is an integer or not ?

**Comment by smichr** [comment]
> Why is it a problem if n is not an integer ?

That routine is not set up to handle that case and an error from Poly will occur.

**Pull request closed without merging**
