### PR TITLE
imageset of first interval of singularities included

### LINKED ISSUE #10113: imageset(lambda x: x**2/(x**2 - 4), S.Reals) returns (1, ∞)
```
>>> f = x**2/(x**2 - 4)
>>> imageset(x, f, S.Reals)
(1, ∞)                 # this is wrong

>>> imageset(x, f, Interval(1, oo))
(-∞, -1/3] ∪ (1, ∞)                              # this is correct
```

Since `[1, ∞).is_subset(S.Reals)`

### PR DESCRIPTION
**Pull request by gxyd**
fixes #10113

### CODE REVIEW

**Comment by gxyd** [comment]
@jksuom please review.

**Comment by gxyd** [comment]
Can someone review this?

**Comment by jksuom** [comment]
Sorry, I missed this. I'll review.

**Comment by jksuom** [comment]
This is fine. A misplaced parenthesis and an one-off loop count both corrected. I'll merge in a few hours.

**Comment by gxyd** [comment]
Thanks @jksuom  for the review :)

**Pull request merged**
