### PR TITLE
Series: Fixes series for expressions of type Pow having unspecified exponents  

### LINKED ISSUE #14384: An unspecified power of x is reported to be `O(log(x)**6)`
```
>>> var('x a')
>>> series(x**a, x, 0)
O(log(x)**6)
```
This should probably return the expression `x**a` itself, as `x**a` is not `O(log(x)**6)` when a is negative.

### PR DESCRIPTION
**Pull request by anutosh491**
#### References to other Issues or PRs

Fixes #14384 
#### Brief description of what is fixed or changed

Changes made are as follows
On **Master**
```
>>> x, a = symbols('x a')
>>> series(x**a, x)
O(log(x)**6)
>>> series(x**(-2*a), x)
O(log(x)**6)
>>> series(exp(a*log(x)), x)
O(log(x)**6)
>>> series(x**I, x)
nan
>>> series(x**(I + 1), x)
O(log(x)**6)
>>> series(exp(I*log(x)), x)
nan
```

On **Committed Branch**
```
>>> x,a = symbols('x a')
>>> series(x**a, x)
x**a
>>> series(x**(-2*a), x)
x**(-2*a)
>>> series(exp(a*log(x)), x)
exp(a*log(x))
>>> series(x**I, x)
x**I
>>> series(x**(I + 1), x)
x**(1 + I)
>>> series(exp(I*log(x)), x)
exp(I*log(x))
```

All these end up in the `_eval_nseries()` method of `exponential.py` where we can check if the series is decisive enough which is not as these depend on sign of `sign(a)` or `sign(I + 1)`. and Hence if it isn't decisive enough we return self rather than `O(log(x)**6`) which was being returned as default for all cases !
#### Release Notes

* series
  * Fixes series for expressions of type Pow having unspecified exponents

### CODE REVIEW

**Comment by anutosh491** [comment]
ping @oscarbenjamin  @smichr for review

**Comment by anutosh491** [comment]
ping @jksuom @0sidharth for review !

**Comment by anutosh491** [comment]
CC: @oscarbenjamin , I have made changes for all group of functions as you had pointed out in the issue reported above . Actually as pointed above , all of them would end up in the same place (not accidently though, it works out mathematically ) where I've added an if-else block to fix these .
Would be glad if you could have a look !

**Comment by oscarbenjamin** [comment]
I don't know the series code so well but hopefully someone else will take a look.

**Comment by anutosh491** [comment]
> I don't know the series code so well but hopefully someone else will take a look.

Cool No worries, I had some idea that you weren't much familiar with the series code (from the series module) though I thought you had some idea regarding the core module .Nonetheless, thanks for your time !

**Comment by anutosh491** [comment]
ping @jksuom @0sidharth  for review ! I am satisfied with the changes here , I would be glad if you'll could have a look ! You could refer to the OP and also a comment on the mentioned issue https://github.com/sympy/sympy/issues/14384#issuecomment-1013659520 which is acts as a guidance for the change .

**Comment by jksuom** [comment]
Looks good. Returning the unevaluated expression instead of a spurious order term is definitely an improvement when a series expansion does not exist. There could be other choices like nan or NotImplementeError but let us be satisfied with this for now. Thanks!

**Comment by anutosh491** [comment]
> Looks good. Returning the unevaluated expression instead of a spurious order term is definitely an improvement when a series expansion does not exist. There could be other choices like nan or NotImplementeError but let us be satisfied with this for now. Thanks! 

@jksuom 
Thanks for the merging ! It's been hard to get reviews for the series/concrete module lately (which are the domains I work on) specially this vacation period of December/January . Glad to here from you today !

**Pull request merged**
