### PR TITLE
Fix addition of a quantity and a number

### LINKED ISSUE #12918: Addition of a quantity and a number does not raise an error
If I add two quantities with inconsistent units, sympy rightly returns an error:
```
>>> from sympy.physics.units import kilogram, kelvin
>>> try: print kilogram + kelvin
>>> except Exception, error: print error
summation of quantities of incompatible dimensions
```
However, if one of the terms is a number, no error is raised:
```
>>> try: print kilogram + 1.1
>>> except Exception, error: print error
kilogram + 1.1
```

If I add two quantities, one of which does not have a dimension, an error is raised:
```
>>> from sympy.physics.units import Quantity, mass
>>> try: print Quantity('x', mass, kilogram) + Quantity('y', S.One, 1.1)
>>> except Exception, error: print error
summation of quantities of incompatible dimensions
```

If I add a quantity and a number, no error is raised:
```
>>> try: print Quantity('x', mass, kilogram) + Number(1.1)
>>> except Exception, error: print error
x + 1.1
```
I believe that this is a bug, as numbers should be treated like dimensionless quantities whenever they are used alongside with quantities.

### PR DESCRIPTION
**Pull request by jirikuncar**
closes #12918

cc @schymans

### CODE REVIEW

**Comment by schymans** [comment]
I wanted to test it, but now I can't even import units, e.g.:
```
from sympy.physics.units import kilogram
```
Returns:
```
...
--> 166 planck_time = Quantity("planck_time", time, sqrt(hbar*G/speed_of_light**5), "t_P")
...
ValueError: summation of quantities of incompatible dimensions
```
Interestingly, if I keep trying, the error eventually disappears!

**Review by schymans — APPROVED** [review]
I confirm that this solves the problems.

**Comment by Upabjojr** [comment]
+1

**Comment by Upabjojr** [comment]
I'm OK for merging. This should be fixed on the master branch too.

**Comment by asmeurer** [comment]
1.1.1 will be merged into master once it is released. There's no need to do it twice, unless it is needed more immediately for something else.

**Comment by jirikuncar** [comment]
@asmeurer it would be nice to regularly merge `1.1.1` to `master`.

```
o master (tag: 1.1)
| \
o   o 1.1.1
|   |
o   o
| / |
o   o
| / |
o   o (tag: 1.1.1)
| / 
o   
```

**Pull request merged**
