### PR TITLE
Geometry `equal` -> `equals`

### PR DESCRIPTION
**Pull request by siefkenj**
Indexing is also added to points so you can now
do `Point(1,2)[0] == 1`.

### CODE REVIEW

**Comment by debugger22** [comment]
It should be deprecated properly. Here's SymPy's [deprecation policy](https://github.com/sympy/sympy/wiki/Deprecating-policy).

**Comment by siefkenj** [comment]
I can add the deprecation stuff, but I think this was just a misspelling. Before I used `.equal` in a previous pull request for methods I added to `geometry`, it was not referenced anywhere in the code, nor was it consistent with any other `GeometryEntity`.  Do you really think it needs to be deprecated?

**Comment by moorepants** [comment]
How many releases has it been in as `equal`?

**Comment by siefkenj** [comment]
Seems it was new in 0.7.6, added by @akshayah3

**Comment by moorepants** [comment]
I think you should support them both if it was just a spelling mistake. Make equals the default method and have equal be an alias with a deprecation warning.

**Comment by siefkenj** [comment]
I don't know how to add labels, but I think it's sympy's turn.

**Comment by debugger22** [comment]
You should have split this PR in two when you planned to fix something else.
Looks good to me. I'll leave it for someone else to merge.

**Comment by siefkenj** [comment]
Is there an easy way to do that?  Do I need to do multiple branches?

**Comment by debugger22** [comment]
Yes.

```
$ git reset --hard HEAD~4
$ git push -f  # It will update this PR
$ git checkout -b fix-plane
$ git reset --hard HEAD~3
$ git cherry-pick 3cc785e...018a66b
```
And then create a new pull request from the `fix-plane` branch.

You can leave it as it is if you are uncomfortable. You shouldn't use your master branch to send pull requests.

**Comment by siefkenj** [comment]
@debugger22 Thanks.  I will leave it as is right now and work on branches in the future.

**Comment by debugger22** [comment]
@siefkenj Do you mind updating this change in the release notes? https://github.com/sympy/sympy/wiki/Release-Notes-for-0.7.7

**Pull request merged**
