### PR TITLE
[DON'T MERGE] Fix tensor index structure abc meta

### PR DESCRIPTION
**Pull request by Upabjojr**
#### Release Notes

* core
  * `ABCMeta` is now metaclass to all SymPy objects.

* tensor
  * Tensor module: refactory to allow mixing PartialDerivative and TensAdd.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I wonder why using `ABCMeta` slows things down so much. I guess it must make instance creation a lot slower...

**Comment by Upabjojr** [comment]
> I wonder why using `ABCMeta` slows things down so much. I guess it must make instance creation a lot slower...

The metaclass interferes with the object creation by adding complexity to the constructor.

Actually, old-style assumptions that use metaclass are a probable bottleneck in SymPy's performance.

**Comment by oscarbenjamin** [comment]
Neither of ManagedProperties or BasicMeta interferes with object creation: they just post-process the class. I'm not sure what makes things slower with ABCMeta but I think that it might be `isinstance`. I know that `isinstance` can be a lot slower for metaclasses that override `__instancecheck__` (which `ABCMeta` does).

**Comment by czgdp1807** [comment]
Any news on this?

**Comment by czgdp1807** [comment]
@Upabjojr Is the purpose of this PR fulfilled?

**Comment by Upabjojr** [comment]
Well, we proved that adding `ABCMeta` to sympy/core will slow down SymPy. So we won't do it. The purpose of this PR is fulfilled.

**Comment by czgdp1807** [comment]
Closing since the above comment shows that the purpose of this PR is fulfilled and it is needed anymore. Thanks.

**Pull request closed without merging**
