### PR TITLE
Add dependabot for updating GitHub Actions workflow versions

### PR DESCRIPTION
**Pull request by asmeurer**
Note that this only enables dependabot for GitHub Actions workflow versions (e.g., things like `actions/checkout@v3`). This does not enable it for things like Python packages. We could do that later, but that's a separate discussion.

This will run dependabot one a week (I believe on Mondays). The updates are grouped, so there should only be at most one PR.

I have also added a workflow that enables auto-merge on these PRs, so that if the checks pass, they will merge automatically. We can remove this if you want to merge them manually, but I've found that the actions updates rarely break anything so this just makes it so you can ignore dependabot.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
Unfortunately, I don't know if there's any way to tell if this works without merging it. 

A rather annoying feature of the auto-merge thing is that it is skipped for normal PRs, which makes GitHub always keep the checks UI open when all checks pass. I think maybe that can be fixed by changing the `if` conditions (https://stackoverflow.com/questions/60589373/how-to-force-job-to-exit-in-github-actions-step).

**Comment by oscarbenjamin** [comment]
> This will run dependabot one a week (I believe on Mondays).

I think monthly would be better and without automerge. We can change the frequency later but I would prefer not to have automerge yet.

**Comment by asmeurer** [comment]
OK. I will say it can get pretty annoying without the automerge. Monthly would help with that.

**Comment by oscarbenjamin** [comment]
I'd like to see what it does first before giving it the automerge.

**Comment by oscarbenjamin** [comment]
Relatedly the code quality tests now fail because of a ruff update. It was previously discussed that it might be better to pin the ruff version and then use dependabot to keep it up to date.

**Comment by oscarbenjamin** [comment]
However there were objections to using dependabot.

**Comment by oscarbenjamin** [comment]
ruff check is fixed in gh-27040

**Comment by oscarbenjamin** [comment]
Okay, let's see how this plays out.

**Pull request merged**
