### PR TITLE
Fix for Mul.is_real

### LINKED ISSUE #16313: For non-real expressions isn't the is_positive property always False?
Consider the following code using master
```py
In [1]: from sympy import Q, ask, symbols
In [2]: x,y = symbols('x y', real=False)
In [3]: (x).is_positive
Out[3]: False
In [4]: (x*y).is_positive
In [5]: (-x).is_positive
In [6]:
```
First two results I understand. Should not the third result be `False`? Since `x` is not-real therefore `(-x)` should also be not real.

### PR DESCRIPTION
**Pull request by ShubhamKJha**
#### References to other Issues or PRs

Fixes #16313 

#### Brief description of what is fixed or changed
Consider the following code:
```py
>>> from sympy import symbols
>>> x = symbols('x', real=False)
>>> (-x).is_real
>>>
```
Apparently the negation of a non-real should be non-real but I still don't know what non-real numbers do sympy support and what symbols with `real=False` could imply.

`Are there any non-real numbers when multiplied by -1 produces real numbers?`

But by understanding the code in `sympy.core.Mul.is_eval_real_imag()`, I could infer that since `complex = None` would mean either `complex=True` or `complex=False` in both of these cases the present code was giving result `False` with `real=False`. So the desired result is also `False`.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by jksuom** [comment]
Can you add a unit test?

**Comment by ShubhamKJha** [comment]
@jksuom I added tests.

**Comment by jksuom** [comment]
Thanks, looks ok.

**Comment by ShubhamKJha** [comment]
Thanks @jksuom

**Comment by asmeurer** [comment]
Please include release notes entries in the future.

**Pull request merged**
