### PR TITLE
Fix expand for relationals in matrix

### PR DESCRIPTION
**Pull request by mph-**

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
We should not allow relationals in a matrix.

I think it would be good to add a class called e.g. `ContainerMatrix` that can contain arbitrary objects but does not have most matrix methods and only supports printing, slicing and indexing and any methods that can be applied to the elements.

**Comment by mph-** [comment]
Yes, a `ContainerMatrix` would be a sensible idea.  However, at the moment things fail ungracefully with the wrong number of args.

**Comment by oscarbenjamin** [comment]
> at the moment things fail ungracefully

That's because the elements of a Matrix should be instances of Expr and Relational is not a subclass of Expr. I don't want to add a test that explicitly uses an Eq in a Matrix because that should be disallowed.

It would make sense for the Relational.expand method to have the same signature as the Expr.expand method though (instead of the change here).

**Comment by oscargus** [comment]
It is very hard to tell what the original changes were as you have used the master branch for your changes. Please use another branch and create a new PR. Closing this one.

**Pull request closed without merging**
