### PR TITLE
[feature] make Curve callable with parameter value

### LINKED ISSUE #17997: [feature] make Curve callable with parameter value
Given `xy = Curve(f(t), g(t), (t, lo, hi))` it seems that a more natural syntax than `xy.subs(t,42)` would be `xy(42)` which would require giving Curve a `__call__` routine:

```python
def __call__(self, v):
  return self.subs(self.parameter, v)

Curve.__call__ = __call__

e.g.

>>> Curve((t,t**2),(t,0,10))
Curve((t, t**2), (t, 0, 10))
>>> _(2)
Point2D(2, 4)

```

### PR DESCRIPTION
**Pull request by namannimmo10**
#### References to other Issues or PRs

Closes #17997

#### Release Notes

*  geometry
    *  Add `__call__ `method in `Class Curve`.

### CODE REVIEW

**Comment by namannimmo10** [comment]
Hi @smichr, Please review this PR!

**Comment by smichr** [comment]
It looks ok to me. Let's see if others have any feedback.

**Comment by namannimmo10** [comment]
Does that look okay to you? @oscarbenjamin @asmeurer

**Comment by oscarbenjamin** [comment]
Does it matter that you can substitute points outside of the range?
```julia
In [6]: Curve((t, t**2), (t, 0, 10))                                                                                                           
Out[6]: Curve((t, t**2), (t, 0, 10))

In [7]: c.subs(t, 20)                                                                                                                          
Out[7]: Point2D(20, 400)

In [8]: c(20)                                                                                                                                  
Out[8]: Point2D(20, 400)
```
Maybe that's an unrelated point though. Adding `__call__` seems fine to me.

**Comment by namannimmo10** [comment]
> Does it matter that you can substitute points outside of the range?

I don't think that matters. Those are the limits and we can substitute points outside that range. 
```
>>> a
Curve((t, t**2), (t, 0, 10))
>>> a(20)
Point2D(20, 400)
>>> a.limits
(t, 0, 10)
```
@smichr It's ready now. Please merge this.

**Comment by smichr** [comment]
> Does it matter that you can substitute points outside of the range?

That was part of the rational for issue #18254 - with such a change then using parameter from 0 to 1 on the arbitrary point would recreate the curve.

**Pull request merged**
