### PR TITLE
refactor(dsolve): move Riccati_special_minus2 and bernoulli test to single.py

### PR DESCRIPTION
**Pull request by Mohitbalwani26**
#### References to other Issues or PRs

SEE #18377

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I'm surprised there are such a small number of tests for these methods. This is why we need #18377 implemented properly so that we can systematically run all the examples on all of the solvers. I'm sure that will show up bugs in these methods.

**Comment by oscarbenjamin** [comment]
If you run the ODE tests with this diff then you can see lots of failures coming particular from Bernoulli:
```diff
diff --git a/sympy/solvers/ode/ode.py b/sympy/solvers/ode/ode.py
index f580db0a9e..c713ed2fdb 100644
--- a/sympy/solvers/ode/ode.py
+++ b/sympy/solvers/ode/ode.py
@@ -290,13 +290,13 @@
 #: ``best``, and ``all_Integral`` meta-hints should not be included in this
 #: list, but ``_best`` and ``_Integral`` hints should be included.
 allhints = (
+    "Bernoulli",
+    "Riccati_special_minus2",
     "factorable",
     "nth_algebraic",
     "separable",
     "1st_exact",
     "1st_linear",
-    "Bernoulli",
-    "Riccati_special_minus2",
     "1st_homogeneous_coeff_best",
     "1st_homogeneous_coeff_subs_indep_div_dep",
     "1st_homogeneous_coeff_subs_dep_div_indep",
```
An example from there:
```julia
In [1]: eq = f(x)*f(x).diff(x) - 1                                                                                                                            

In [3]: classify_ode(eq)                                                                                                                                      
Out[3]: 
('Bernoulli',
 'separable',
 '1st_exact',
 '1st_power_series',
 'lie_group',
 'separable_Integral',
 '1st_exact_Integral',
 'Bernoulli_Integral')

In [4]: dsolve(eq, hint='separable')                                                                                                                          
Out[4]: 
⎡          __________           __________⎤
⎣f(x) = -╲╱ C₁ + 2⋅x , f(x) = ╲╱ C₁ + 2⋅x ⎦

In [5]: dsolve(eq, hint='1st_exact')                                                                                                                          
Out[5]: 
⎡          __________           __________⎤
⎣f(x) = -╲╱ C₁ + 2⋅x , f(x) = ╲╱ C₁ + 2⋅x ⎦

In [6]: dsolve(eq, hint='lie_group')                                                                                                                          
Out[6]: 
⎡          __________           __________⎤
⎣f(x) = -╲╱ C₁ + 2⋅x , f(x) = ╲╱ C₁ + 2⋅x ⎦

In [7]: dsolve(eq, hint='Bernoulli')                                                                                                                          
Out[7]: 
         __________
f(x) = ╲╱ C₁ + 2⋅x 
```
That's a but where either the Bernoulli solver should not match or it should return both solutions correctly like the other solvers.

**Comment by Mohitbalwani26** [comment]
I think the Bernoulli solver should match this equation but the problem is it always returns one solution. I guess this has to do something with `general_solutions` of Bernoulli.

**Comment by oscarbenjamin** [comment]
It's possible that the general solution is only applicable to certain cases. Potentially restricting the Bernoulli solver to those when matching might help.

**Comment by oscarbenjamin** [comment]
This is why I think it would be good to fix #18377 properly before rewriting everything else. We can improve test coverage significantly and fix bugs at the same time as refactoring.

**Comment by Mohitbalwani26** [comment]
I guess found the fix so should I make a separate PR now?

**Comment by oscarbenjamin** [comment]
> I guess found the fix so should I make a separate PR now?

Yes, but try the diff I showed above and investigate all of the failures. That was just one example.

**Pull request merged**
