### PR TITLE
Use S.true in the conditions in integral transforms

### PR DESCRIPTION
**Pull request by asmeurer**
S.true should be used anywhere that a full symbolic condition can be used,
which is the case. Among other things, this makes transforms with
noconds=False pretty print properly, as the _can_print_latex ignores bool.

- integrals
  * fix pretty printing of integral transforms `noconds=False`

### CODE REVIEW

**Comment by cbm755** [comment]
I'm wondering if I should do it in `meijreint` too.

I can try to review but can you give an example (or a test)?  I get the same results for `pprint(Piecewise((6, Eq(im(z), 0)), (42, true)))` and `pprint(..., True)))`

**Comment by asmeurer** [comment]
I think it only affects the LaTeX printing in the notebook.

**Comment by smichr** [comment]
Any reason not to use `S.true` instead of `S(True)`?

**Comment by asmeurer** [comment]
I don't know why I did that.

**Comment by smichr** [comment]
+1

**Pull request merged**
