### PR TITLE
[WIP] dsolve fixes for systems

### LINKED ISSUE #9274: Wrong Jordan form: complex eigenvalues w/ geo. mult. > alg. mult.
Consider the following matrix:

````
In [172]: L = Matrix([[2, 4], [-4, 2]])

In [173]: Z = zeros(2,2);  I = Identity(2)

In [174]: A = Matrix(BlockMatrix([[L, I], [Z, L]]))

In [175]: pprint(A)
⎡2   4  1   0⎤
⎢            ⎥
⎢-4  2  0   1⎥
⎢            ⎥
⎢0   0  2   4⎥
⎢            ⎥
⎣0   0  -4  2⎦
````

Compute its Jordan form:

````
In [177]: pprint(A.jordan_form())
⎛⎡0  ⅈ  ⅈ  0⎤, ⎡2 - 4⋅ⅈ     1        0        0        0        0        0        0        0        0   ⎤⎞
⎜⎢          ⎥  ⎢                                                                                        ⎥⎟
⎜⎢0  1  1  0⎥  ⎢   0     2 - 4⋅ⅈ     0        0        0        0        0        0        0        0   ⎥⎟
⎜⎢          ⎥  ⎢                                                                                        ⎥⎟
⎜⎢0  0  0  ⅈ⎥  ⎢   0        0     2 - 4⋅ⅈ     1        0        0        0        0        0        0   ⎥⎟
⎜⎢          ⎥  ⎢                                                                                        ⎥⎟
⎜⎣0  0  0  1⎦  ⎢   0        0        0     2 - 4⋅ⅈ     0        0        0        0        0        0   ⎥⎟
⎜              ⎢                                                                                        ⎥⎟
⎜              ⎢   0        0        0        0     2 - 4⋅ⅈ     0        0        0        0        0   ⎥⎟
⎜              ⎢                                                                                        ⎥⎟
⎜              ⎢   0        0        0        0        0     2 + 4⋅ⅈ     1        0        0        0   ⎥⎟
⎜              ⎢                                                                                        ⎥⎟
⎜              ⎢   0        0        0        0        0        0     2 + 4⋅ⅈ     0        0        0   ⎥⎟
⎜              ⎢                                                                                        ⎥⎟
⎜              ⎢   0        0        0        0        0        0        0     2 + 4⋅ⅈ     1        0   ⎥⎟
⎜              ⎢                                                                                        ⎥⎟
⎜              ⎢   0        0        0        0        0        0        0        0     2 + 4⋅ⅈ     0   ⎥⎟
⎜              ⎢                                                                                        ⎥⎟
⎝              ⎣   0        0        0        0        0        0        0        0        0     2 + 4⋅ⅈ⎦⎠
````

This is wrong.  The J matrix is too big.  And there is a zero (generalized) eigenvector.

So far, I've traced it back to here:
````
In [178]: pprint(A._jordan_block_structure())
⎧2 - 4⋅ⅈ: ⎧1: ⎡⎡⎡ⅈ⎤⎤⎤, 2: ⎡⎡⎡0⎤, ⎡ⅈ⎤⎤, ⎡⎡ⅈ⎤, ⎡0⎤⎤⎤⎫, 2 + 4⋅ⅈ: ⎧1: ⎡⎡⎡-ⅈ⎤⎤⎤, 2: ⎡⎡⎡0⎤, ⎡-ⅈ⎤⎤, ⎡⎡-ⅈ⎤, ⎡0 ⎤⎤⎤⎫⎫
⎪         ⎪   ⎢⎢⎢ ⎥⎥⎥     ⎢⎢⎢ ⎥  ⎢ ⎥⎥  ⎢⎢ ⎥  ⎢ ⎥⎥⎥⎪           ⎪   ⎢⎢⎢  ⎥⎥⎥     ⎢⎢⎢ ⎥  ⎢  ⎥⎥  ⎢⎢  ⎥  ⎢  ⎥⎥⎥⎪⎪
⎪         ⎪   ⎢⎢⎢1⎥⎥⎥     ⎢⎢⎢0⎥  ⎢1⎥⎥  ⎢⎢1⎥  ⎢0⎥⎥⎥⎪           ⎪   ⎢⎢⎢1 ⎥⎥⎥     ⎢⎢⎢0⎥  ⎢1 ⎥⎥  ⎢⎢1 ⎥  ⎢0 ⎥⎥⎥⎪⎪
⎨         ⎨   ⎢⎢⎢ ⎥⎥⎥     ⎢⎢⎢ ⎥  ⎢ ⎥⎥  ⎢⎢ ⎥  ⎢ ⎥⎥⎥⎬           ⎨   ⎢⎢⎢  ⎥⎥⎥     ⎢⎢⎢ ⎥  ⎢  ⎥⎥  ⎢⎢  ⎥  ⎢  ⎥⎥⎥⎬⎬
⎪         ⎪   ⎢⎢⎢0⎥⎥⎥     ⎢⎢⎢0⎥  ⎢0⎥⎥  ⎢⎢0⎥  ⎢ⅈ⎥⎥⎥⎪           ⎪   ⎢⎢⎢0 ⎥⎥⎥     ⎢⎢⎢0⎥  ⎢0 ⎥⎥  ⎢⎢0 ⎥  ⎢-ⅈ⎥⎥⎥⎪⎪
⎪         ⎪   ⎢⎢⎢ ⎥⎥⎥     ⎢⎢⎢ ⎥  ⎢ ⎥⎥  ⎢⎢ ⎥  ⎢ ⎥⎥⎥⎪           ⎪   ⎢⎢⎢  ⎥⎥⎥     ⎢⎢⎢ ⎥  ⎢  ⎥⎥  ⎢⎢  ⎥  ⎢  ⎥⎥⎥⎪⎪
⎩         ⎩   ⎣⎣⎣0⎦⎦⎦     ⎣⎣⎣0⎦  ⎣0⎦⎦  ⎣⎣0⎦  ⎣1⎦⎦⎦⎭           ⎩   ⎣⎣⎣0 ⎦⎦⎦     ⎣⎣⎣0⎦  ⎣0 ⎦⎦  ⎣⎣0 ⎦  ⎣1 ⎦⎦⎦⎭⎭
````

### PR DESCRIPTION
**Pull request by cbm755**
Solving systems of equations is a mess: lots of things silently give wrong answers.  Here's my slow attempts to clean it up.
- [ ] current implementation uses formulas that assume e.g., bits are nonzero.
- [x] above "fixed" for "type1".
- [ ] actually there are other cases in type1
- [x] fixes to "linear_2eq_order1_type2".
- [ ] nonhomog/forcings/rhs are almost totally ignored
- [x] nonhomog silently ignored given wrong answers
- [ ] nonhomog in `..._2eq_...order2`, as above.
- [ ] All of the above for 3x3 and nxn systems.
- [ ] Wrong statements in docs.

Instead---or as well as---I want:
- [x] expm/jordan solver
- [ ] which special case real jordan blocks for real matrices (get sin/cos pairs)
- [x] fix #9274
- [ ] decide whether I trust the jordan code after seeing (#9274).

I reserve the right to frequently rebasing ;-)

### CODE REVIEW

**Comment by cbm755** [comment]
@KDMOE are you still interested in this code?  Want to help?  Good stuff here but buggy: and you probably understand it better than me blundering through it...

**Comment by vishalg2235** [comment]
@cbm755 I must add my commits to this PR? Instead of opening new one.

**Comment by vishalg2235** [comment]
@skirpichev should I did you wiped out sin & cos? did you used the results of this(#9235) PR?

**Comment by skirpichev** [comment]
> should I wipe out sin & cos?

Sorry, I don't care.

> did you used the results of this(#9235) PR?

Yes.

**Comment by cbm755** [comment]
I suggest a new PR.

**Comment by vishalg2235** [comment]
Can I copy the changes you made here in the new PR?

**Comment by vishalg2235** [comment]
@cbm755 @skirpichev  I'am getting and AttributeError. while running the `test("test_ode")`. error is as following : please help - 
```
File "sympy/utilities/runtests.py", line 2301, in test_exception
    self._exceptions.append((self._active_file, self._active_f, exc_info))
AttributeError: 'PyTestReporter' object has no attribute '_active_file'
```

**Comment by mijo2** [comment]
Some of the tasks mentioned here are being taken care of by PR #18720: expm solver, other cases in type1, for all nxn systems. You can check the matrix exponential code in the PR mentioned.

**Comment by oscarbenjamin** [comment]
This PR is not needed any more. The cases it is intended to fix are already fixed and the relevant code has changed a lot after the GSOC project by @mijo2. There are also many test cases for "type1" and "type2" systems (constant coefficient homogeneous and nonhomogeneous respectively) as can be found here:
https://github.com/sympy/sympy/blob/6b24daab9d779a1e50a4e01b3cd4afce9d1fd68c/sympy/solvers/ode/tests/test_systems.py#L519-L1282

**Pull request closed without merging**
