### PR TITLE
Use u_decode instead of u, hopefully solves #9799

### PR DESCRIPTION
**Pull request by bjodah**
See #9799 
I hope this does the right thing.

### CODE REVIEW

**Comment by jksuom** [comment]
This looks good, though I have tested with python2.7 only. The example in #9799 yields no error, but there appears a short-lived "ghost" version of the result on the screen. It goes away with ``init_printing(use_latex='png')``.

It is my understanding that the behaviour with python3 would be critical here. Perhaps somebody would be able to test that.

**Comment by bjodah** [comment]
I tried the example in #9799 and the example provided by @thisch in #9692 and both now work for me in ipython and ipython3 notebooks, and tests are passing so I think this is an improvement.

**Comment by jksuom** [comment]
Testing with Python-3.4 succeeded (had to compile from source). It would be nice to have more extensive tests, but, in any case, I  believe this is an improvement.

+1

**Comment by bjodah** [comment]
Great, thanks for reviewing @jksuom

**Pull request merged**
