### PR TITLE
Added test for univariate conditions in Piecewise.as_expr_set_pairs

### LINKED ISSUE #16715: Piecewise.as_expr_set_pairs should test for univariate conditions
It would be good to add this diff to check whether the conditions are univariate:
```diff
diff --git a/sympy/functions/elementary/piecewise.py b/sympy/functions/elementar
y/piecewise.py
index edd4dab..2c79a87 100644
--- a/sympy/functions/elementary/piecewise.py
+++ b/sympy/functions/elementary/piecewise.py
@@ -961,7 +961,12 @@ def as_expr_set_pairs(self, domain=S.Reals):
         exp_sets = []
         U = domain
         complex = not domain.is_subset(S.Reals)
+        cond_free = set()
         for expr, cond in self.args:
+            cond_free |= cond.free_symbols
+            if len(cond_free) > 1:
+                raise NotImplementedError(filldedent('''
+                    multivariate conditions are not handled.'''))
             if complex:
                 for i in cond.atoms(Relational):
                     if not isinstance(i, (Equality, Unequality)):
```
This tests as
```python
>>> Piecewise((x,x<0),(0,y>1)).as_expr_set_pairs()
Traceback (most recent call last):
...
NotImplementedError:
multivariate conditions are not handled.
```

### PR DESCRIPTION
**Pull request by mohitacecode**
#### References to other Issues or PRs

Fixes #16715

#### Brief description of what is fixed or changed
Added a test for univariate conditions in Piecewise.as_expr_set_pairs

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by smichr** [comment]
I think a NO ENTRY would be fine for the release notes.

And a test that `raises(Piecewise((x, x<0), (0, y>1)).as_expr_set_pairs(), NotImplementedError)` should be added to the tests.

**Comment by mohitacecode** [comment]
Ping @smichr

**Comment by oscarbenjamin** [comment]
What is going on in the commit history here? It looks like you've deleted the entire codebase in the first commit

**Comment by oscarbenjamin** [comment]
This has wiped the git blame from the whole codebase

**Comment by oscarbenjamin** [comment]
> This has wiped the git blame from the whole codebase

Actually it looks like the blame still works.

I don't understand what is happening in these commits though

**Comment by mohitacecode** [comment]
I tried with git blame as well and it seems like the pr do not break anything but if you suggest we can revert this pr and I'll open a new pr with appropriate changes

**Comment by oscarbenjamin** [comment]
Reverting doesn't restore the history.

**Comment by gschintgen** [comment]
Just stumbled over this too: If I browse the repository in github all top-level files show this crazy huge "first" commit as last modification. :-/
Is it too late to rewrite/fix the history?

**Comment by oscarbenjamin** [comment]
I think it's too late. I don't understand what this has done to the history but it seems the blame still works. It's just github that gets confused about which commit last modified the files.

In future we should try to check the commits from newer contributors. The changes in this PR are small and do not justify having more than one commit so should have been squashed.

**Comment by mohitacecode** [comment]
I am extremely sorry :( 
I do understand my responsiblity of making right commits for pr maybe this is a hard lesson for me as well.sorry again

**Comment by oscarbenjamin** [comment]
It's okay @mohitacecode. You don't need to be sorry. If you are new to git and github then it can be difficult to know what the effect of the git commands is. I don't even understand git well enough to know what happened in that commit. It looks like the history is still intact though.

I have seen other PRs where files are deleted in one commit and added again in another which won't show if a reviewer only looks at the "Files changed". If one of those PRs got merged it would remove all the history for those files. This is one reason I think we should encourage squashing commits more. (Or perhaps a reviewer can squash the commits)

**Comment by mohitacecode** [comment]
Thank you so much @oscarbenjamin your words are really encouraging for me. :)
I am really loving open source.

**Comment by oscarbenjamin** [comment]
If you find yourself here because you are trying to chase the origin of a change in the codebase you can see the commit immediately before the "first" commit here:
https://github.com/sympy/sympy/tree/d5df2bd6a274db8b8d3a5cf2622d16dfb3f3d8a4/sympy

**Pull request merged**
