### PR TITLE
Added Tests in Limits.py for issue which has been fixed in Master

### LINKED ISSUE #18707: There is a problem or limitation when the Limit is calculated
I would like to know the limit when p>1 , if I write the next code. 
```
from sympy import Symbol, Limit, S

n = Symbol('n')
p = Symbol('p', positive=True, real=True, nonzero=True)

Limit(1/(p**n),n,S.Infinity).doit()
```
The anwser is a Error message.
I think that it could have a option in the assumption names like p = Symbol('p', positive=True, real=True, nonzero=True, p>1) or for  
p = Symbol('p', positive=True, real=True, nonzero=True) the answser could be {1 , 0} for p=1 and p>1

### PR DESCRIPTION
**Pull request by faze-geek**
#### References to other Issues or PRs

Closes #18707 

#### Brief description of what is fixed or changed
This is my first pull request for Sympy and an initial attempt to close an issue .Issue reported above seems to be fixed in latest release of Sympy  (correction made some time ago ) and thought it will be a good initial experience to close this issue by making this pull request .I have added the necessary regression test .

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by anutosh491** [comment]
@smichr This looks fine for a first pr by @faze-geek but I have always been skeptical about the applications of `oo *0`,  in between evaluations in sympy , hence I thought of asking you whether this answer works fine 
```
>>> limit(1/(p**n),n,S.Infinity)
exp(-oo*sign(log(p)))
>>> limit(1/(p**n),n,S.Infinity).subs(p, 1)
nan
```

**Comment by smichr** [comment]
@anutosh491 , are you suggesting that ` assert limit(1/(p**(-n)), n, S.Infinity) == exp(oo*sign(log(p)))` be replaced with `assert limit(1/(p**n),n,S.Infinity).subs(p, 1) is S.NaN`? If so, I'm not sure that it is testing anything related to the series calculation. In fact, the second test is probably not needed since the first one confirms that the original issue has been resolved. So perhaps simplest is best?

**Comment by anutosh491** [comment]
No, no I thought of pointing out something which has been mentioned on certain other limit issues too .
So basically we have 
```
>>> limit(1/(1**n), n, oo)
1
>>> limit(1/(2**n), n, oo)
0
>>> limit(1/(0.5**n), n, oo)
oo

>>> limit(1/(p**n),n, oo).subs(p, 1)
nan
>>> limit(1/(p**n),n, oo).subs(p, 2)
0
>>> limit(1/(p**n),n, oo).subs(p, 0.5)
oo
```
If I remember correctly, this point has been brought up on other limit issues too where symbolic answers for limits don't exactly replicate what the numerical expression would return and maybe a piecewise implementation was proposed for the same . Just thought of putting this out , rest seems to be fine and yeah the second test seems to follow the same code flow so can surely be removed !
I'll try to track down the commit that might have fixed this issue on master (gave `NotImplementedError` earlier) and try to suggest a better test along with the first one . Then this could go in .

**Comment by faze-geek** [comment]
@smichr @anutosh491  Thank you guys for your responses to the pull request .The tests I have added are basic and complementary .Are you guys suggesting I could look for some other edge cases !

**Pull request merged**
