### PR TITLE
Add support for scalar multiplication by Symbol in waves module

### PR DESCRIPTION
**Pull request by RushabhMehta2005**
#### Brief description of what is fixed or changed
This PR implements multiplication operation of a transverse wave (TWave) with a symbolic scalar (Symbol) i.e amplitude scaling by a Symbol.
Example Usage:

```python
>>> A, f, phi= symbols('A, f, phi')
>>> s = symbols('s') # scaling factor
>>> w = TWave(A, f, phi)
>>> w2 = w*s
>>> w2
TWave(A*s, f, phi, 1/f, n)
```

Tests have also been added. 

#### Other comments
Any feedback and suggestions on improving/enhancing this implementation are appreciated.

#### Release Notes

* physics.optics
  * Symbolic amplitude scaling of waves is now supported.

### CODE REVIEW

**Comment by RushabhMehta2005** [comment]
Not sure why the authors test is failing, I have clearly setup my .mailmap file a couple months ago and everything worked in my last PR as well.

**Comment by oscarbenjamin** [comment]
Have you changed your GitHub username?

**Comment by RushabhMehta2005** [comment]
Not at all, I have merged PRs from this very account and even the AUTHORS file has me exactly as well.

**Comment by RushabhMehta2005** [comment]
If you see the failing test, the name that it's looking for is actually present at line 55 too.

**Comment by RushabhMehta2005** [comment]
Some assistance would really help out here, the mailmap check runs fine locally too. I'm not sure how to fix this.

**Comment by oscarbenjamin** [comment]
You should merge or rebase with master and then try running the check.

**Comment by RushabhMehta2005** [comment]
@oscarbenjamin I am still facing the same issue, I rebased with master and then ran the mailmap check locally. Here is my output:
image

**Pull request closed without merging**
