### PR TITLE
[GSoC] Rename doit to expand in symbolic_probability.py

### PR DESCRIPTION
**Pull request by Smit-create**
Rename doit to expand in symbolic_probability.py
#### References to other Issues or PRs

Related to discussions in #19267 

#### Brief description of what is fixed or changed
Following the discussions and the documentation, the current `doit` is performing the `expand` and hence rename it to `expand`.

#### Release Notes

* stats
   * `expand` added in `sympy.stats.symbolic_rv` API.

ping @czgdp1807 @Upabjojr @jmig5776

### CODE REVIEW

**Comment by Smit-create** [comment]
@czgdp1807 @Upabjojr See if it looks good to merge

**Comment by czgdp1807** [comment]
LGTM. Let's wait for @Upabjojr @jmig5776

**Comment by czgdp1807** [comment]
@Upabjojr Is it ready to go in?

**Comment by czgdp1807** [comment]
Will be merged tonight.

**Pull request merged**
