### PR TITLE
bugfix_in_get_general_solutions_of_bernoulli

### PR DESCRIPTION
**Pull request by Mohitbalwani26**
#### References to other Issues or PRs

SEE #18852 

#### Brief description of what is fixed or changed
currently, the Bernoulli solver returned only one solution whereas other hints provided more than one solution when possible. This fixes this problem and returns all possible solutions when Bernoulli solver matches the problem.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Another one:
```
In [1]: eq = f(x).diff(x) - t*f(x)                                                                                                                            

In [2]: dsolve(eq)                                                                                                                                            
Out[2]: 
           t⋅x
f(x) = C₁⋅ℯ   

In [3]: dsolve(eq, hint='Bernoulli')                                                                                                                          
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-606f5b9a2198> in <module>
----> 1 dsolve(eq, hint='Bernoulli')

~/current/sympy/sympy/sympy/solvers/ode/ode.py in dsolve(eq, func, hint, simplify, ics, xi, eta, x0, n, **kwargs)
    651             # The key 'hint' stores the hint needed to be solved for.
    652             hint = hints['hint']
--> 653             return _helper_simplify(eq, hint, hints, simplify, ics=ics)
    654 
    655 def _helper_simplify(eq, hint, match, simplify=True, ics=None, **kwargs):

~/current/sympy/sympy/sympy/solvers/ode/ode.py in _helper_simplify(eq, hint, match, simplify, ics, **kwargs)
    684             sols = solvefunc(eq, func, order, match)
    685         if iterable(sols):
--> 686             rv = [odesimp(eq, s, func, hint) for s in sols]
    687         else:
    688             rv =  odesimp(eq, sols, func, hint)

~/current/sympy/sympy/sympy/solvers/ode/ode.py in <listcomp>(.0)
    684             sols = solvefunc(eq, func, order, match)
    685         if iterable(sols):
--> 686             rv = [odesimp(eq, s, func, hint) for s in sols]
    687         else:
    688             rv =  odesimp(eq, sols, func, hint)

~/current/sympy/sympy/sympy/core/multidimensional.py in wrapper(*args, **kwargs)
    135                     result = apply_on_element(wrapper, args, kwargs, n)
    136                     return result
--> 137             return f(*args, **kwargs)
    138         return wrapper

~/current/sympy/sympy/sympy/solvers/ode/ode.py in odesimp(ode, eq, func, hint)
   2409 
   2410     # Get the f(x) on the left if possible.
-> 2411     if eq.rhs == func and not eq.lhs.has(func):
   2412         eq = [Eq(eq.rhs, eq.lhs)]
   2413 

AttributeError: 'Symbol' object has no attribute 'rhs'
```

**Comment by Mohitbalwani26** [comment]
this fix was done to return more than 1 solution if there are any. But the example which you gave just now is different and I don't understand why these errors are showing. I guess if the classify_ode works then `get_general_solutions` is called and I verified it for various equations even.

**Comment by oscarbenjamin** [comment]
In this example n=1.

**Comment by Mohitbalwani26** [comment]
here the Bernoulli shouldn't have matched as if we closely analyze P(x) will be` log(f(x))` which makes the ODE non-linear.

**Comment by Mohitbalwani26** [comment]
@oscarbenjamin in case of n=1 we can apply general solution of separable solver as mentioned in the docstring.

**Comment by oscarbenjamin** [comment]
The OP should explain what you are doing and why and so should the title of the PR

This follows from discussion elsewhere but makes no reference to it. It's important to reference previous discussion.

This is intended to fix a case that was found to be failing but there is no test added for that case. Each time a bug is found and fixed there should be a regression test added to ensure that the bug does not come back.

**Comment by oscarbenjamin** [comment]
Also in future try to use better commit messages. The messages should give some context for which part of the codebase you are changing and why.

**Comment by Mohitbalwani26** [comment]
okay, I will add the tests and will reference the PR where the discussion took place.

**Comment by oscarbenjamin** [comment]
Looks good merging.

In future can you try to write commit messages that give context to what you are doing. Imagine that someone is looking at the list of commits and trying to understand what they mean without reading any of the discussion in any of the PRs/issues. Currently it isn't easy:
https://github.com/sympy/sympy/commits/master

**Pull request merged**
