### PR TITLE
Fix Bspline _add_bsplines

### PR DESCRIPTION
**Pull request by Corwinpro**
#### References to other Issues or PRs

#12214

#### Brief description of what is fixed or changed

This pull fixes a bug with bsplines _add_splines. 

Here's an example of a wrong behaviour:
```
import sympy
from sympy.functions.special.bsplines import bspline_basis
x = sympy.var("x")
kv = [0, 0, 0, 0, 1, 2, 2, 2, 2]
basis = bspline_basis(3, kv, 2, x)
```
The expected basis function should be continuous at x == 1, while in the current version it is not.
I computed the expected analytical formula by hand and compared to the one the old version produces. They do not match.
```
assert basis = sympy.Piecewise((-x**3 + 3*x**2/2, (x >= 0) & (x <= 1)), (x**3 - 9*x**2/2 + 6*x - 2, (x >= 1) & (x <= 2)), (0, True))
```
With this change we fix the wrong behaviour of the middle basis function, which is only reproducible when the number of control points is small.

#### Other comments

The function _add_splines is used in basis functions generation. The removed bit in _add_splines does the summation wrong, while the part implemented by @Saintis is correct.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by jksuom** [comment]
The fix looks good to me, but is there an explanation for the failure of `interpolating_spline` doctest?

**Comment by Corwinpro** [comment]
> The fix looks good to me, but is there an explanation for the failure of `interpolating_spline` doctest?

Is the current doc wrong? B-spline presumes continuity at all points (at least C0, I guess for degree = 3 it should also be C1 and C2). We can check if this condition is satisfied at x = 1:

-x**3/36 - x**2/36 - 17*x/18 + 2 = 1   at   x = 1
5*x**3/36 - 13*x**2/36 - 11*x/18 + 7/3 = 3/2   at   x = 1

This means that the spline is not continuous at x = 1, which is exactly the bug I'm trying to fix.

Hope this makes sense!

**Comment by jksuom** [comment]
> Is the current doc wrong?

That seems to be the explanation. Using `knots = [-2, -2, -2, -2, 1, 4, 4, 4, 4]`, as in the example, I see that `bspline_basis(3, knots, 2, x)` given by the current code is discontinuous.

Your fix looks fine. There is only some trailing space in the fixed example.

BTW, you could consider adding `@cacheit` to `bpspline_basis` as it seems to do quite a lot of recursive work. It might save some time.

**Comment by Corwinpro** [comment]
> Your fix looks fine. There is only some trailing space in the fixed example.
> 

Fixed that.

> BTW, you could consider adding `@cacheit` to `bpspline_basis` as it seems to do quite a lot of recursive work. It might save some time.

Added lru_cache from functools. Thanks!

**Comment by jksuom** [comment]
It seems that lru_cache cannot be used with the current version of bspline_basis that returns a list. A tuple would probably work.

**Comment by jksuom** [comment]
On closer inspection, it seems that the offending item is not Piecewise but the `knots` argument of `bspline_basis`. If that is a list, `lru_cache` cannot handle the call. If that is changed to a tuple in the examples and tests, and some internal calls, the tests appear pass. These changes seem to suffice though I didn't test everything.

```
@@ -5,7 +5,7 @@
 from sympy.functions import Piecewise, piecewise_fold
 from sympy.sets.sets import Interval
 
-from functools import lru_cache
+from sympy.core.cache import lru_cache
 
 
 def _add_splines(c, b1, d, b2):
@@ -134,7 +134,7 @@ def bspline_basis(d, knots, n, x):
     .. [1] https://en.wikipedia.org/wiki/B-spline
 
     """
-    knots = [sympify(k) for k in knots]
+    knots = tuple(sympify(k) for k in knots)
     d = int(d)
     n = int(n)
     n_knots = len(knots)
@@ -256,7 +256,7 @@ def interpolating_spline(d, x, X, Y):
 
     knots = [X[0]] * (d + 1) + list(interior_knots) + [X[-1]] * (d + 1)
 
-    basis = bspline_basis_set(d, knots, x)
+    basis = bspline_basis_set(d, tuple(knots), x)
 
     A = [[b.subs(x, v) for b in basis] for v in X]
```

**Comment by Corwinpro** [comment]
Yes you are right. I completely forgot I didn't add caching initially because of the list hashing problem. I can write a pre contract for bspline basis function that replaces list to tuple when called.

**Comment by Corwinpro** [comment]
Finally, I changed all the calls of bspline basis to tuple(kv). I assume we could do something better with a new decorator before this cached function. If anybody supports this idea I can implement it.

**Comment by jksuom** [comment]
Thanks, this looks good to me. I don't think that another decorator is necessary (at least for now). The examples show that a tuple must be used to avoid the 'list' error.

**Comment by jksuom** [comment]
I'll add a release note entry.

**Comment by Corwinpro** [comment]
Thanks! Great job.

**Pull request merged**
