### PR TITLE
Implemented Partial Pivoting #9060

### PR DESCRIPTION
**Pull request by ahhda**
Sympy currently uses trivial pivoting i.e. it selects the first non-zero term in the column.
However that is numerically unstable.
This PR implements partial pivoting i.e. swap with the largest term in the column.

### CODE REVIEW

**Comment by moorepants** [comment]
I'm pretty sure the reason this isn't already implemented is because for symbolics there is no way to know which symbol is greater than the other. How does this affect symbolic matrices?

**Comment by ahhda** [comment]
Yes, you are right.
It raises a TypeError("cannot determine truth value of Relational").

**Comment by moorepants** [comment]
You can try to make the partial pivoting optional. If it can determine whether one thing is greater than the other, then do the pivot. If it can't then you have to stick with the old alg.

**Comment by moorepants** [comment]
Please avoid opening mutliple PRs for the same thing. It is nice to keep the conversations in one place.

**Comment by ahhda** [comment]
Sorry I didn't create a branch last time.
And I coudn't push to master after creating new branch.

**Comment by moorepants** [comment]
Got it. That's fine then.

**Pull request closed without merging**
