### PR TITLE
`solveset_real(Eq(x, 1), x)` fixed

### LINKED ISSUE #9686: solveset_real(Eq(x, 1), x) gives NotImplementedError
```python
In [2]: solveset_real(Eq(x, 1), x)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-ea6b87ce2d43> in <module>()
----> 1 solveset_real(Eq(x, 1), x)

NameError: name 'solveset_real' is not defined

In [3]: from sympy.solvers.solveset import *

In [4]: x, y, z, a, b, c = symbols('x y z a b c')

In [5]: solveset_real(Eq(x, 1), x)
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-5-ea6b87ce2d43> in <module>()
----> 1 solveset_real(Eq(x, 1), x)

/home/amit/Desktop/myrepo/sympy/sympy/solvers/solveset.pyc in solveset_real(f, symbol)
    443                         result += _solve_as_rational(equation, symbol,
    444                                                      solveset_solver=solveset_real,
--> 445                                                      as_poly_solver=_solve_as_poly_real)
    446                 else:
    447                     result += solveset_real(equation, symbol)

/home/amit/Desktop/myrepo/sympy/sympy/solvers/solveset.pyc in _solve_as_rational(f, symbol, solveset_solver, as_poly_solver)
    463     g, h = fraction(f)
    464     if not h.has(symbol):
--> 465         return as_poly_solver(g, symbol)
    466     else:
    467         valid_solns = solveset_solver(g, symbol)

/home/amit/Desktop/myrepo/sympy/sympy/solvers/solveset.pyc in _solve_as_poly_real(f, symbol)
    566     return _solve_as_poly(f, symbol,
    567                           solveset_solver=solveset_real,
--> 568                           invert_func=invert_real)
    569 
    570 

/home/amit/Desktop/myrepo/sympy/sympy/solvers/solveset.pyc in _solve_as_poly(f, symbol, solveset_solver, invert_func)
    556         return result
    557     else:
--> 558         raise NotImplementedError
    559 
    560 

NotImplementedError: 
```

### PR DESCRIPTION
**Pull request by gxyd**
Fixes #9686

### CODE REVIEW

**Comment by gxyd** [comment]
@aktech  @hargup  please have a look

**Comment by aktech** [comment]
Looks good. +1

**Comment by aktech** [comment]
Thanks for working on this, Merging!

**Comment by gxyd** [comment]
Thanks

**Comment by hargup** [comment]
Sorry for being late but this is a -1 from me, see https://github.com/sympy/sympy/issues/9686#issuecomment-122189448.

**Comment by aktech** [comment]
Sorry, I didn't saw anything like that in docs, as:

`solveset_real` docs says:
```
    f : Expr
        The target equation
```

`solveset` docs says
```
    f : Expr or a relational.
        The target equation or inequality
```

**Comment by aktech** [comment]
We could expect `Eq()` in `invert_real` as `invert_real(Eq, 0, symbol)`.
As a naive user would expect `Eq` in `solveset_real`, and that can be fixed by handling it in `invert_real` & then we don't need this fix.

**Comment by hargup** [comment]
> Sorry, I didn't saw anything like that in docs, as:
>
> `solveset_real` docs says:
> ```
>     f : Expr
>         The target equation
> ```
>
> `solveset` docs says
> ```
>     f : Expr or a relational.
>         The target equation or inequality
> ```

I should have made it explicit but `Eq` is also a relational and `solveset_real` wasn't/doesn't expect it as input.

> We could expect `Eq()` in `invert_real` as `invert_real(Eq, 0, symbol)`.
As a naive user would expect `Eq` in `solveset_real`, and that can be fixed by handling it in `invert_real` & then we don't need this fix.

This is about "how to" to support `Eq` in `solveset_real` but my point is that we(I) don't want to support more than one input interface in `solveset_real` or `solveset_complex`. We have the `solveset` method for the "naive" user.

**Comment by aktech** [comment]
Alright, I am reverting this.

**Comment by aktech** [comment]
@gxyd 
Sorry for the miscommunication.

**Pull request merged**
