### PR TITLE
add _monotonic_sign and use in Add._eval_is_(pos, neg, npos, nneg)

### LINKED ISSUE #8632: (n-1) is not known to be positive for a positive even n
If `n` is positive and even, it must be at least 2, so `(n-1).is_positive` should return `True` (currently it returns `None`).

### LINKED ISSUE #8633: n - 1/2 is not known to be positive for a positive integer n
If `n` is a positive integer, it must be at least 1, so `(n-S.Half).is_positive` should return `True` (currently it returns `None`).

### LINKED ISSUE #8675: If p is prime, it is larger than 1
Currently, if
```python
>>> p = Symbol('p', integer=True, prime=True)
```
then `p>0` resolves to `True`. However, `p>1` does not simplify at all. It would be nice if it would.

In general, it would be nice if reals would have a more general assumption mechanism, so that a symbol would "have it in mind" that it is larger than, say, `k`. So the assumption `prime` would suggest the assumption *is larger or equal than 2*, and together with the assumption `odd` it would suggest *is larger or equal than 3*.

Speaking of that, it would be nice if the system would somehow "know" that the only even prime is 2.

### LINKED ISSUE #8992: [enhancement] (p + 2)**3 > 1 should be True when p is positive
Similar to issues #8632, #8633, #8638 and #8675, when values of variables in a polynomial put one in a domain where the polynomial is monotonic, then inequalities like the one of this issue should be known. For (x+2)**3 there is an inflection at x = -2 and the function is monotonically rising to the right (and falling to the left) so it should be safe to say that it is greater than 1 if x is positive.

Some work is in progress in my `geno` branch if anyone is interested in using that as a starting point.

### PR DESCRIPTION
**Pull request by smichr**
Fixes #8632
Fixes #8633
Fixes #8638
Fixes #8675
Fixes #8992

Despite fixing several issues I am not sure this is as it should be and am open to better suggestions/implementations.

### CODE REVIEW

**Comment by smichr** [comment]
ping @pelegm, @aktech

**Comment by pelegm** [comment]
This requires a lot of attention, I guess it will take me a while...

**Comment by aktech** [comment]
I think this is an important PR and this will need some time.
I will try to help.

**Comment by smichr** [comment]
Thanks to both of you for taking a look. Like I said, I'm open to any suggestions on how to do this right.

**Comment by smichr** [comment]
:memo: all added lines are covered

**Comment by aktech** [comment]
@smichr 
I think it's better to push and report issues later than blocking it.
Do you have any other TODO for this?

**Comment by smichr** [comment]
OK, I will commit this. It is adding a private function which is totally open to being changed. For the meanwhile, several issues will be resolved.

**Comment by pelegm** [comment]
I'll try to have a look soon... Thanks for that.

**Pull request merged**
