### PR TITLE
Implemented product between Matrix and quaternion

### PR DESCRIPTION
**Pull request by evbernardes**
#### Brief description of what is fixed or changed
Implemented `_matrix_mul`: treats quaternion as a vector and multiplies it with matrix.

Modified `__rmul__` to call `_matrix_mul` if called with a matrix as argument.

If `Matrix.shape == (3, 3)`, only imaginary parts of the quaternion are multiplied.

#### Other comments

I have done this operation multiple times. If there's interest from others, this could be a useful and simple implementation.

For example, this can be useful to implement a very straight forward implementation of the Hamilton product in the same way as a cross product can be rewritten as a multiplication between a skew-symmetric matrix and a vector:
```
q1 * q2 == Q1 * q2
```
Where `Q1` represents the Hamilton product from the left:
```
Q1 = Matrix([
            [+q1.a,-q1.b,-q1.c,-q1.d],
            [+q1.b,+q1.a,-q1.d,+q1.c],
            [+q1.c,+q1.d,+q1.a,-q1.b],
            [+q1.d,-q1.c,+q1.b,+q1.a]])
```

Alternatively, if there is interest, a `product_left` (or something with a better name) could be added as a property to return this matrix, and this could be a cleaner / more readable implementation of the quaternion product:
 ```
q1 * q2 == q1.product_left * q2
```
Equivalently, a `product_right` could also be defined:
 ```
q1 * q2 == q2.product_right * q1 
```

#### Release Notes

* algebras
  * Implemented product between Matrix and quaternion

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I'm not sure we really have a coherent idea for how quaternion algebra is supposed to fit with everything else in SymPy. There could be other interpretations of what multiplying a matrix with a quaternion might mean like perhaps a quaternion would be considered a scalar in that context.

**Comment by evbernardes** [comment]
> There could be other interpretations of what multiplying a matrix with a quaternion might mean like perhaps a quaternion would be considered a scalar in that context.

I see what you mean! I do think that the operation, as I defined it, could be a good addition (maybe if defined somehow differently, if this way is problematic). I have used it a lot during my studies, since applying transformations to the Quaternion elements can have many uses.

It also leads to easier and straightforward implementations of many different things.
For example:
```
q.to_rotation_matrix
```
Could be implemented instead as (considering unit quaternions):
```
(q.product_left * q.product_right.T)[1:,1:]
```

**Comment by evbernardes** [comment]
In order to remove ambiguities, maybe it could be placed into `__matmul__` instead of `__rmul__`.

**Comment by oscarbenjamin** [comment]
> In order to remove ambiguities, maybe it could be placed into `__matmul__` instead of `__rmul__`.

I don't think there's any way to remove the ambiguity. The question is how mixed matrix/quaternion multiplication should be interpreted. We already have the problem that quaternions just don't have a well defined interaction with the rest of Expr which is mostly defined around complex numbers.

**Comment by oscarbenjamin** [comment]
Maybe there could be a `quaternion.to_Matrix` method. Then it's just:
```
M * q.to_Matrix()
```
Perhaps also a `Quaternion.from_Matrix` so:
```
q2 = Quaternion.from_Matrix(M * q.to_Matrix())
```

**Comment by evbernardes** [comment]
> Maybe there could be a `quaternion.to_Matrix` method. Then it's just:
> 
> ```
> M * q.to_Matrix()
> ```
> 
> Perhaps also a `Quaternion.from_Matrix` so:
> 
> ```
> q2 = Quaternion.from_Matrix(M * q.to_Matrix())
> ```

To be fair this can already be implemented by:
```
q2 = M * Matrix(q.args)
q2 = Quaternion(*q2)
```
I still think having a single function that already returns a quaternion (and takes care of both the `4x4` matrix and the `3x3` matrix) could be pretty useful.

**Comment by oscarbenjamin** [comment]
> I still think having a single function that already returns a quaternion (and takes care of both the `4x4` matrix and the `3x3` matrix) could be pretty useful.

The ambiguity about whether it is applying a `4x4` or a `3x3` transformation makes it seem less useful to me. I would expect those to be two separate functions with different names.

**Comment by evbernardes** [comment]
> The ambiguity about whether it is applying a `4x4` or a `3x3` transformation makes it seem less useful to me. I would expect those to be two separate functions with different names.

Ok, I see what you mean. What would you propose then? 
Maybe a function that could be called by `sympy.Quaternion.matmul(M, q)` in the same vein as `numpy.matmul` was before the introduction of the `@` operator?

**Comment by oscarbenjamin** [comment]
> What would you propose then?

How in words what you describe what you are doing with these quaternions and matrices?

What does it mean to transform only the pure part of a quaternion with a 3x3 matrix? I guess that if we think in terms of unit quaternions and axis and angle and the 3x3 matrix is an orthogonal matrix then this transforms the axis of the quaternion. What would it mean more generally if we don't have a unit quaternion or if the matrix is not orthogonal?

In what context would it be useful to call a function with either a 3x3 matrix or a 4x4 matrix to do some operation on a quaternion? Why wouldn't you know ahead of time what size of matrix you have?

The example from the OP suggests that it might be useful to have a way of getting a matrix to represent the Hamilton product but if you actually want to compute the Hamilton product then isn't it better to compute that directly rather than constructing a matrix?

**Comment by evbernardes** [comment]
To be fair, though, I completely get that maybe this is all a bit too niche!

**Comment by oscarbenjamin** [comment]
> > How in words what you describe what you are doing with these quaternions and matrices?
> 
> Quaternions are usually thought of as a scalar + a vector part, and sometimes it's convenient to apply matrices to this vector part the same way as someone else would apply it to any other vector.

My question is really what does this operation even mean. If I multiply a quaternion by `Matrix([[3, 0, 0], [0, 2, 0], [0, 0, 1]])` then how can we interpret what that does? When would anyone ever want to do that and if they did then can we meaningfully describe what effect that operation has? In all of your examples you refer to unit quaternions but this matrix would turn a unit quaternion into a non-unit quaternion.

> Using matrix products can be a convenient/cleaner way of implementing the Hamilton product.

The Hamilton product is already implemented in SymPy so we don't need matrix multiplication for that:
```
In [27]: Quaternion(x, y, t, z) * Quaternion(a, b, c, d)
Out[27]: 
(a*x - b*y - c*t - d*z) + (a*y + b*x - c*z + d*t)*i + (a*t + b*z + c*x - d*y)*j + (a*z - b*t + c*y + d*x)*k
```
I can understand why it is useful to be able to turn a quaternion into a matrix reflecting the transformation that  it represents. I don't see why we would do that to then subsequently multiply a quaternion by the matrix: we could have just used the original quaternion for that.

In the OP you say:

> a product_left (or something with a better name) could be added as a property to return this matrix, and this could be a cleaner / more readable implementation of the quaternion product:
```
q1 * q2 == q1.product_left * q2
```
Here adding something like `product_left` which gives a matrix representing the rotation makes sense to me. I can see that it is useful to get a matrix so that you can then use that to do operations on matrices. I don't see why afterwards you would want to use that matrix to act on a quaternion. Reversing the point above why use `q1.product_left * q2` rather than `q1 * q2`?

**Comment by evbernardes** [comment]
> My question is really what does this operation even mean. If I multiply a quaternion by `Matrix([[3, 0, 0], [0, 2, 0], [0, 0, 1]])` then how can we interpret what that does? When would anyone ever want to do that and if they did then can we meaningfully describe what effect that operation has? In all of your examples you refer to unit quaternions but this matrix would turn a unit quaternion into a non-unit quaternion.

The non-linear control I talked about can be an example. Non-unit quaternions can a step on the definition of a non-linear control law. The angular velocity quaternion is not a unit-quaternion, for example. Also, a matrix could imply different controller parameters, for example.

Since the `Quaternion` class is a general construct to work with general quaternions, I gave a general example not supposing anything is unit. In particular, the original quaternion `Quaternion(a, b, c, d)` is not supposed to be unit.

I'd suppose someone using this would have their own interpretation of what this all means.

> 
> The Hamilton product is already implemented in SymPy so we don't need matrix multiplication for that:
> 
> I can understand why it is useful to be able to turn a quaternion into a matrix reflecting the transformation that it represents. I don't see why we would do that to then subsequently multiply a quaternion by the matrix: we could have just used the original quaternion for that.
> 
> Here adding something like `product_left` which gives a matrix representing the rotation makes sense to me. I can see that it is useful to get a matrix so that you can then use that to do operations on matrices. I don't see why afterwards you would want to use that matrix to act on a quaternion. Reversing the point above why use `q1.product_left * q2` rather than `q1 * q2`?

Indeed, it is already implemented. I gave it as an example of the usefulness of having matrix to quaternion multiplication implemented. 

If there was any interest, for example, the current implementation of the Hamilton product could be replaced by something like:
```
def __mul__(self, q2):
    return self.matmul(self.product_left, q2)
``` 
I'm not saying we should do it though, I really meant it more as an example.

**Comment by oscarbenjamin** [comment]
> In essence, I'm supposing that the person using this would have **their own interpretation** of what this operation means.

This is the problem I have with this. We don't seem to be able to come up with words to describe what this does apart from saying that it's like matrix multiplication but with the quaternion being thought of as a column matrix. If that's the only way to describe the operation then I would have thought that the clearest way to perform the operation in SymPy would be something like:
```python
q_result = Quaternion(*(Q_matrix * q_quaternion.as_Matrix()))
```
That's explicit about the fact that we're:
1. Treating the quaternion as a matrix.
2. Performing matrix multiplication.
3. Converting the result to a quaternion.

I don't necessarily mind having quaternion methods like `transform3x3` and `transform4x4` or whatever but if we can't come up with good names for them then it suggests that they are not generally meaningful operations so I'm not sure they should be added. The user can always make their own function if it has some meaning for them (and presumably choose a more meaningful name for it in context):
```python
def matmul(Q: Matrix, q: Quaternion) -> Quaternion: 
    return Quaternion(*(Q*q.as_Matrix()))
```

**Comment by evbernardes** [comment]
Alright, I see what you mean. Indeed, if its just more confusing than useful, then it shouldn't be added.
Feel free to close this PR if you prefer, and thanks for your time! :)

**Comment by oscarbenjamin** [comment]
Fair enough. I'll close this.

To be clear some of the other ideas discussed here seem reasonable to me e.g.:

1. Adding a `to_Matrix()` method to turn a quaternion into a 4x1 column matrix.
2. Adding something equivalent to make a 3x1 matrix from the vector part.
3. Adding a method to turn a quaternion into a 4x4 matrix that is equivalent to left-multiplication.
4. Likewise for right-multiplication

I know that implementing quaternions using matrices is common in a numeric context and I don't see any reason why SymPy shouldn't have operations to help e.g. by deriving the relevant equations for the matrices.

**Comment by evbernardes** [comment]
> To be clear some of the other ideas discussed here seem reasonable to me e.g.:

Alright! I'll implement all of that in another PR.

What do you think would be good names? Do you agree with:
- `to_Matrix` with a parameter, maybe called `vector_only`?
- `from_Matrix`, that acts different according to the size of the input (accepting 3x1 and 4x1)?
- `product_matrix_left` and `product_matrix_right`?

**Pull request closed without merging**
