### PR TITLE
Cache replacement tuples, do not lookup true/false, new replacements

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Another part of #22753

#### Brief description of what is fixed or changed

Use `true`/`false` rather than `S.true` and `S.false` since they are defined here anyway.

Cache the replacement tables to avoid rebuilding them.

Add two more patterns for or.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
Everything looks good here.

I noticed the replacement tuples have several uses of ITE where one of the arguments is `true`, but those always simplify to a simple OR:

```
>>> to_cnf(ITE(x, y, True))
y | ~x
>>> to_cnf(ITE(x, True, z))
x | z
```

(the former also being equivalent to `Implies(x, y)`).

It's not clear if ITE is used here intentionally. But either way, this is unrelated to the changes here.

**Comment by oscargus** [comment]
In general, the idea is that if the `ITE`-condition evaluates it should pick the right form of it and if it doesn't evaluate the previous expression should be kept. So getting the simplified logic form of it will rarely be useful as far as I can see. Or at least not better than what was before.

**Comment by oscargus** [comment]
``` python
https://github.com/sympy/sympy/blob/2cb26131cdb15ac51ebac90c524d577930f29387/sympy/logic/boolalg.py#L3116-L3121
```

**Comment by oscarbenjamin** [comment]
Looks good

**Pull request merged**
