### PR TITLE
printing of Permutations for max element taken care

### PR DESCRIPTION
**Pull request by gxyd**

### CODE REVIEW

**Comment by gxyd** [comment]
@jksuom please review.

**Comment by jksuom** [comment]
This looks ok. +1

**Comment by jksuom** [comment]
I restarted the Python 3.5 job.

**Comment by gxyd** [comment]
Ya, i didn't started it myself since, @asmeurer mentioned about some changes in `.travis.yml` file so thought may be he is interested in seeing failures happening. I don't have knowledge `travis` infrastructure in SymPy.

**Comment by jksuom** [comment]
It looked like having nothing to do with the ``.travis.yml`` file. Anyway, it is easy to remember that it was the slow job split 3/3.

**Comment by smichr** [comment]
I'm not sure what the issue was, but on the basis of the +1 I am committing this.

**Pull request merged**
