### PR TITLE
Mechanices linearize hotfix

### PR DESCRIPTION
**Pull request by moorepants**
@asmeurer I think this takes care of the hotfix.

### CODE REVIEW

**Comment by asmeurer** [comment]
What's going on with Travis? Did you restart a built?

**Comment by moorepants** [comment]
The SciPy install timed out. I restarted it.

**Comment by asmeurer** [comment]
Great. What should the entry for the release notes be?

**Comment by moorepants** [comment]
The deprecated linearization method in the mechanics module no longer fails to execute.

**Pull request merged**
