### PR TITLE
Balance tests

### PR DESCRIPTION
**Pull request by siefkenj**
This PR balances `SPLIT=i/X` based on time.

### CODE REVIEW

**Comment by jksuom** [comment]
I think that we should first try tagging some of the slowest tests before attempting to modify `runtests`. (That may lead to annoying repeated rebalancing.)

**Comment by jksuom** [comment]
It looks like there would have to be different balancing densities for slow tests with (pseudo)randomly shuffled test file lists. Another complication is that the random modules of Python 2.7 and 3.5 seem to work differently.

**Comment by siefkenj** [comment]
With balancing, the slow tests shouldn't need to be random.

**Comment by jksuom** [comment]
I'm also having doubts about the usefulness of the shuffle. It looks like a small change in the seed might have big consequences, different in versions 2.7 and 3.5.

**Comment by jksuom** [comment]
These are the results of running the code with `slow=True`and no shuffle (and `TRAVIS_BUILD_NUMBER=1` in the environment to imitate Travis).

[0.3616, 0.0003, 0.0004, 0.0004, 0.0255, 0.0005, 0.0674, 0.0337, 0.1057, 0.0329, 0.0002, 0.0002, 0.0184, 0.0028, 0.0046, 0.0148, 0.0046, 0.0083, 0.0004, 0.0002, 0.0069, 0.0004, 0.0004, 0.0046, 0.0205, 0.1378, 0.1451, 0.0003, 0.0006, 0.0006]

Those 0.000x entries indicate that there were no tests, only some time was spent to find that out. These numbers should probably be rounded to 3 or 2 decimals. It might also be practical to not demand that their sum be equal to one. They could be integers considered as weights. Then they could be modified on demand without having to recompute the whole list.

**Comment by jksuom** [comment]
This seems to work as expected. Only test_pow2 in split 1/3 was problematic. It will normally take about 5 minutes, but Travis interrupted the test twice after giving the 10 minute warning. Apparently, it uses the wall clock time, not cpu time. If the timeouts persist, I think that test_pow2 should be further divided into two tests.

Anyway, this will now balance the slow tests fairly evenly, ca. 20 minutes each.

**Pull request merged**
