### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by hanspi42**
#### Brief description of what is fixed or changed

I wrote most of the Laplace transform code and would like to be involved if someone intends to change it.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by hanspi42** [comment]
@oscarbenjamin: This is not urgent whatsoever.

**Comment by oscarbenjamin** [comment]
Yes, absolutely. It looks like I enabled automerge 3 months ago!

**Comment by asmeurer** [comment]
All checks on the original commit passed, but the automerge didn't happen. Now some checks are failing? I'm not sure what happened here, but it may be necessary to manually merge or rebase this on top of master.

**Comment by oscarbenjamin** [comment]
Not sure why the mypy check failed but I rebase onto master should fix the author check. I think it gets confused somehow if the PR was branched before the AUTHORS file was updated.

**Comment by hanspi42** [comment]
There seems to be a new version of mypy; this particular error now turns up everywhere.

**Comment by hanspi42** [comment]
I tried a manual rebase but failed. I think I will just make a new pull request, it is a one-line change after all.

**Comment by hanspi42** [comment]
Replaced by #25046

**Pull request closed without merging**
