### PR TITLE
Fix dev team section on about us page

### LINKED ISSUE #11245: Dev team section shrinks after loading on about us page in documentation
Here's the picture of it

screenshot 2016-06-17 13 13 58

Page source has contents, though.

### PR DESCRIPTION
**Pull request by kritkaran94**
Fixes #11245

### CODE REVIEW

**Comment by debugger22** [comment]
Tests take more than 2 days to run!

**Comment by kritkaran94** [comment]
@debugger22 Any idea why does it happen ?

**Comment by jksuom** [comment]
Travis occasionally forgets to create the tests for a PR. Maybe too long queue momentarily. I'll try to 'wake it up' by closing and reopening.

**Comment by kritkaran94** [comment]
@jksuom Still the same.

**Comment by jksuom** [comment]
No, not the same. In fact, travis has almost finished the tests.

**Comment by kritkaran94** [comment]
@jksuom Thanks for that.

**Comment by kritkaran94** [comment]
@debugger22 Please review this PR.

**Comment by debugger22** [comment]
+1

I looked here http://www.sphinx-doc.org/en/stable/markup/code.html#includes

**Comment by debugger22** [comment]
@kritkaran94 Since you are at this, could you also correct the year in `conf.py`.

**Comment by kritkaran94** [comment]
@debugger22 I have corrected conf.py too.

**Comment by debugger22** [comment]
Thanks!

**Comment by kritkaran94** [comment]
@debugger22 @jksuom Ready for merge ?

**Comment by debugger22** [comment]
Looks good to me although I haven't built docs on my system. If anyone else can confirm that, it should be good to go.

**Pull request merged**
