### PR TITLE
Passing tests in test_eval_power.py

### LINKED ISSUE #10096: unxfail tests in test_eval_power.py
[These lines in test_eval_power.py](https://github.com/sympy/sympy/blob/master/sympy/core/tests/test_eval_power.py#L338-L344) now pass in master. So `@XFAIL` can be removed.

### PR DESCRIPTION
**Pull request by kshitij10496**
fixes #10096 

Ping @gxyd @asmeurer

### CODE REVIEW

**Comment by gxyd** [comment]
I think it will be good if you figure out using `git bisect` that which PR fixed this issue.

**Comment by kshitij10496** [comment]
@gxyd I think #8605 fixed this

**Comment by gxyd** [comment]
I suspect PR #8605 fixed that issue for the first time. Later on this issue failed because of some of new introduced commits, then `@XFAIL` tag was introduced(since it may have failed tests). But later on again "some"(this is to be spotted) introduced commit fixed this issue.

After you spot the issue, may be you can then put that in a comment above this.(like "fixed by PR #pr_number").

**Comment by kshitij10496** [comment]
Okay.
Cool
I am looking into it

**Comment by leosartaj** [comment]
+1

**Comment by kshitij10496** [comment]
@gxyd I think `XFAIL` was introduced in #9731 but the tests were still passing.
I checked out the commit `53fe332` to verify this.
```
sympy git:(53fe332) ✗ ./bin/test sympy/core/tests/test_eval_power.py 
======================= test process starts ========================
executable:         /home/kshitij10496/anaconda2/bin/python  (2.7.10-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
random seed:        73628201
hash randomization: on (PYTHONHASHSEED=2464220829)

sympy/core/tests/test_eval_power.py[22] ........X.............  [OK]

__________________________ xpassed tests ___________________________
sympy/core/tests/test_eval_power.py: test_issue_8582

 tests finished: 21 passed, 1 expected to fail but passed, 
in 5.42 seconds 
```

**Comment by gxyd** [comment]
Yes, it seems that is the case. I also commented on the issue(i remember now). Thanks for figuring this.
+1 to merge.

**Comment by kshitij10496** [comment]
@gxyd Yeah.
I saw your comment regarding this issue and figured it out from there.
So, thanks to you

**Comment by leosartaj** [comment]
Thanks @kshitij10496

**Pull request merged**
