### PR TITLE
Expose polys dup_transform as Poly.transform

### LINKED ISSUE #12003: Better way to compose rational functions
I have a degree 17/degree 17 rational function in one variable with floating point coefficients with 1000 digits of precision. I would like to compose this with the Möbius transformation `(t - c)/(t + c)`. Here `c = 51/5` but in general it will be a similar fraction. I want the final rational function in expanded form (expanded polynomial/expanded polynomial)

The problem is that if you try just about any naive and even not so naive way of doing this, you lose a ton of precision as soon as you expand the polynomials. I finally figured out the following method for doing it without losing precision. 

Write `(t - c)/(t + c)` as `1 - 2*c/(t + c)`. Then the composition corresponds to a shift by 1, a composition with `-2*c*t`, an inversion (replacing `t` with `1/t`), and a shift by c. For the inversion we can make use of the fact that `P(1/t) == t**d*P'(t)`, where `d = deg(P)` and `P'` is `P` with the terms reversed. The `t**d` will cancel in the numerator and denominator because the numerator and denominator have the same degree. In other words, we just need to reverse the terms. 

The result is something like this

```py
mpmath.mp.dps = 1000 # This is needed to make Poly use full precision. I'll open a separate issue. 

frac = map(Poly, fraction(D))
for i in range(len(frac)):
    # Shift by 1
    frac[i] = frac[i].shift(1)
    # Compose with -2*c*t
    frac[i] = frac[i].compose(Poly(2*c*t))
    # Invert
    # XXX: Is there a better way than rep.rep
    frac[i] = Poly(reversed(frac[i].rep.rep), t)
    # Shift by c
    frac[i] = frac[i].shift(c)

n, d = frac
```

The resulting rational function, from what I can tell, does not lose precision. I believe the key here is that `shift` uses the Taylor shift algorithm. 

It would be nice to have some more direct support for this somehow.

### PR DESCRIPTION
**Pull request by asmeurer**
This seems to be the first method on DMP that requires unifying three
polynomials. I hope I did the unification correctly. The tests that I've added
seem to indicate that I did.

This fixes #12003.

### CODE REVIEW

**Comment by jksuom** [comment]
The unification looks a bit tricky, but the three steps are probably necessary. (Maybe there could be a `unify` that would accept several `*args`.)
It would seem more 'user friendly' to allow polynomial expressions for p and q, turned to `Poly`s at entry.

**Comment by asmeurer** [comment]
Oh that's a good point. I think the other methods handle that by calling `f.unify(g)` where `f` is `self`. So I should reorder the calls.

**Comment by asmeurer** [comment]
And I agree it would be better if it could take multiple arguments. I wasn't quite up to figuring that out. It probably should be modeled after `parallel_poly_from_expr`.

**Comment by asmeurer** [comment]
Actually it apparently doesn't work with the other methods:

```
In [5]: Poly(x).gcd(x + 1)
---------------------------------------------------------------------------
CoercionFailed                            Traceback (most recent call last)
/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/polytools.py in _unify(f, g)
    351             try:
--> 352                 return f.rep.dom, f.per, f.rep, f.rep.per(f.rep.dom.from_sympy(g))
    353             except CoercionFailed:

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/domains/gmpyintegerring.py in from_sympy(self, a)
     38         else:
---> 39             raise CoercionFailed("expected an integer, got %s" % a)
     40

CoercionFailed: expected an integer, got x + 1

During handling of the above exception, another exception occurred:

UnificationFailed                         Traceback (most recent call last)
<ipython-input-5-20d2c91f3f51> in <module>()
----> 1 Poly(x).gcd(x + 1)

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/polytools.py in gcd(f, g)
   2754
   2755         """
-> 2756         _, per, F, G = f._unify(g)
   2757
   2758         if hasattr(f.rep, 'gcd'):

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/polytools.py in _unify(f, g)
    352                 return f.rep.dom, f.per, f.rep, f.rep.per(f.rep.dom.from_sympy(g))
    353             except CoercionFailed:
--> 354                 raise UnificationFailed("can't unify %s with %s" % (f, g))
    355
    356         if isinstance(f.rep, DMP) and isinstance(g.rep, DMP):

UnificationFailed: can't unify Poly(x, x, domain='ZZ') with x + 1
```

Otherwise I believe 

```diff
diff --git a/sympy/polys/polytools.py b/sympy/polys/polytools.py
index dbab1ec..efbb0d9 100644
--- a/sympy/polys/polytools.py
+++ b/sympy/polys/polytools.py
@@ -2959,8 +2959,8 @@ def transform(f, p, q):
         Poly(4, x, domain='ZZ')

         """
-        P, Q = p.unify(q)
-        F, P = f.unify(P)
+        F, P = f.unify(p)
+        P, Q = P.unify(q)
         F, Q = F.unify(Q)

         if hasattr(F.rep, 'transform'):
diff --git a/sympy/polys/tests/test_polytools.py b/sympy/polys/tests/test_polytools.py
index 238fb7b..2682a5b 100644
--- a/sympy/polys/tests/test_polytools.py
+++ b/sympy/polys/tests/test_polytools.py
@@ -2122,22 +2122,26 @@ def test_shift():
 def test_transform():
     # Also test that 3-way unification is done correctly
     t = Poly(x**2 - 2*x + 1, x).transform(Poly(x + 1), Poly(x - 1))
+    t1 = Poly(x**2 - 2*x + 1, x).transform(x + 1, x - 1)
     assert t == Poly(4, x) == \
         cancel((x - 1)**2*(x**2 - 2*x + 1).subs(x, (x + 1)/(x - 1)))
     assert t.domain == ZZ

     t = Poly(x**2 - x/2 + 1, x).transform(Poly(x + 1), Poly(x - 1))
+    t1 = Poly(x**2 - x/2 + 1, x).transform(x + 1, x - 1)
     assert t == Poly(3*x**2/2 + S(5)/2, x) == \
         cancel((x - 1)**2*(x**2 - x/2 + 1).subs(x, (x + 1)/(x - 1)))
     assert t.domain == QQ

     t = Poly(x**2 - 2*x + 1, x).transform(Poly(x + S(1)/2), Poly(x - 1))
-    assert t == Poly(S(9)/4, x) == \
+    t1 = Poly(x**2 - 2*x + 1, x).transform(x + S(1)/2, x - 1)
+    assert t == t1 == Poly(S(9)/4, x) == \
         cancel((x - 1)**2*(x**2 - 2*x + 1).subs(x, (x + S(1)/2)/(x - 1)))
     assert t.domain == QQ

     t = Poly(x**2 - 2*x + 1, x).transform(Poly(x + 1), Poly(x - S(1)/2))
-    assert t == Poly(S(9)/4, x) == \
+    t1 = Poly(x**2 - 2*x + 1, x).transform(x + 1, x - S(1)/2)
+    assert t == t1 == Poly(S(9)/4, x) == \
         cancel((x - S(1)/2)**2*(x**2 - 2*x + 1).subs(x, (x + 1)/(x - S(1)/2)))
     assert t.domain == QQ
```

would do the trick. Perhaps this should be pushed to a separate issue?

**Comment by scopatz** [comment]
The code here looks good to me as is,  and so

> Perhaps this should be pushed to a separate issue?

seems right to me.

**Comment by jksuom** [comment]
I think this looks good and is ready to be merged. If a `unify` with multiple arguments is ever implemented, it is possible to return to this.

**Comment by asmeurer** [comment]
Somehow this implementation is losing precision. It wasn't happening when I tested it directly with `dup_transform`.

**Comment by jksuom** [comment]
Can you give an example. I'll try to look into it tomorrow.

**Comment by asmeurer** [comment]
Here is a simplified version from the original issue (using 128 digits of precision instead of 1000):

```
In [1]: E = S("(-0.00048022638432249848414963044314602901523716206994947989566203658006946760289478819923599331759726034528393582837644889283207807881*t**17 + 0.0059253291404526833333784923554163942588363001023786369587164524158031135197967746685321281528819960310906725962979525717488121124*t**16 - 0.034314463530358204583201393753294294857227246182255985301109091537137940207181473742126818661508693475991502493882624857871850256*t**15 + 0.12388498895587189975963640155126501174055699232906660437840440714410672415310487689292460597876781060244020763601023748726060912*t**14 - 0.3123183533335927661067345206987383842922707737557028899011031141083526432990052461254687583701772341831883640169568290481854528*t**13 + 0.58353430848907600631165116107441784369604316341466123316178918227441130914125394794058373189165796184152198998179227030577888999*t**12 - 0.83680600287509308498425446855387037905114068396203752997562489341619351729256432891017452208406736632073132243653117401269900777*t**11 + 0.94087324279042836446098884087597575336801067474279097352804385991739908534175108699904768270306185429353057805005595436608575624*t**10 - 0.83982454078123996589480332259140670747939998689469713284660405928567317117853488614006522080522890402488715172001757194302968815*t**9 + 0.59858503244600748402826923129499625606291789442943666251501458858420746315364380233910563362366740266178597312615159897438579983*t**8 - 0.34072059997833393894329969638380861458512585764253368346350914029641182545233454411780198273811500130038911418145188006789313641*t**7 + 0.15402380141512055936311172836540783872248914243839567456395009012197324080739132354751153752126889044096342325954811668786534386*t**6 - 0.054626104338016166656551314514345995137581408090075370392266932346424587426088993055818930729605062963264049681457816868506569011*t**5 + 0.014882791533883519138843701700264832794535894121600656832162882309433851151547995726920832487637882770798861430559219111019314102*t**4 - 0.0030084688498445199874290226416454809708388306801947439013895121489670248251409666044604743526624715749565763050648391178515651753*t**3 + 0.00042523809822955295545244379534654709124091053603176325860707867239201492999692892045870784254116037043991872493479193295875525505*t**2 - 0.000037530222736793361860249322226726920586394483306960473504211532776865471539602839547117539186552910566366142255440792633634848231*t + 0.0000015574244678542025243291914051129737009836134874443028733912233314457601576123183521208958443383527211284904674377064073944312315)/(0.000047036402392419786028207449812151129010118844895252481612331612530241627662893418867502312368954699819584630950583241193558904782*t**17 + 0.00052206476765258590725341615632021509485084204644259352854367468709086282363794785488407734728366294888944136994504636641854701598*t**16 + 0.0027416120452891201751055572429982850824721890932582719226325619728124432137818871785394897139923204024143963681324213153762942565*t**15 + 0.0093282803294357654362995350293189883400970692376198027811462150988110999163919943141689327067639193602562852151146608767710233875*t**14 + 0.021697665484382739784608855197156671605797557131048606340605317605882440890244832854087050461586089302792780523914803810557052061*t**13 + 0.045073296055554905941424542947858858676104081774883736369250695237950703755914127401943528446831183164650617641268432919107815521*t**12 + 0.049310440241848804300108383395026431374243862924314550658795626624620902505733280756196978626196670910458042065359694207440453485*t**11 + 0.12712842029908519966085454421017643159670212035401904553193990843509579183810927194376850002059749297142929822170718629238362919*t**10 - 0.035662978958874016637269778583749344570903625224040895425326893356859806360048059079348992050142338427254444563386737327776693114*t**9 + 0.36558753736104874085888243075805580346173702238745177626332630526695695760278884840342722914817905047284712305373361974696032253*t**8 - 0.42618130005889277912944283219502441370912159107761556075551716894145063699732504845955284723837577713013529026835434348979167815*t**7 + 0.81897925906335932652164297394417971220277545410830635920051508509555317791741292193575182115831265779057476182558284498202669907*t**6 - 0.87063808518087318470764327933941924317676786929157494668890580915289021063779700615320569982853089955279393915853994693209496116*t**5 + 0.93521829605259467494885855636322001767038908604733237014671977226589531089375234706413346718919759362194855753339960193934310742*t**4 - 0.67094676082563793931321938025403583942641740006130816958324565007235008444077201948094565121193170909228563178839871610413859437*t**3 + 0.41597428706298248904775611825367785545689112560478559973441145954072652569957387867394729731756425445052697720781258469558399167*t**2 - 0.15492908848967377449358215963968830306507208953642895763410925806411197692977423337154977536732391762201072454595718305058957796*t + 0.041899680255323453153707952202493671852283069313058989196740758997857756989685091755274001337441684381233533429111216007760610214)")

In [2]: c = 0.6*17

In [3]: inv = solve(-c*(t + 1)/(t - 1) - y, t, rational=True)[0].subs(y, t)

In [4]: n, d = map(Poly, fraction(E))

In [5]: p, q = map(lambda i: Poly(i, t), fraction(inv))

In [6]: n, d = n.transform(p, q), d.transform(p, q)

In [7]: import mpmath

In [8]: mpmath.mp.dps = 128

In [9]: mpmath.plot(lambdify(t, n/d - exp(-t), 'mpmath'), (0, 100))
```

Here is the "correct" answer (as computed with the method outlined on the issue)

```
In [1]: rat_func = S("(-0.000000000000000000000000000000000022774706078188437602712956452098577018250022013771621699583950329887099377431456695235908975070687709092079618566120816413338121*t**17 + 0.00000000000000000000000000000036381008264169349243812635423771863164772445380510046504953691543046969067162865628825852710244361448964478316358885011303994453*t**16 - 0.00000000000000000000000000096311299616434657122861893645313400335959697907516286070694147824762576058572687168675312742946407633700246303192717481383181299*t**15 + 0.0000000000000000000000010077964568000473112561227437696611056694519797226635412439813624684902542175892086759246007642080015105024537845044320531515213*t**14 - 0.00000000000000000000055478662451290864179048338055903658064093247307235185068928690798980645943811152010114126926094452109151697142602184896238212611*t**13 + 0.00000000000000000018540997178336935538261642412839586141953662470894334980464371808193541123148517121948097336560398086215689717659869834368873675*t**12 - 0.000000000000000040934546068922329038450253360443397405562815712105120829290668925401266685637121168668469780780499803592219512628810042913188552*t**11 + 0.0000000000000063018857979045448318721341618243014578525522189854393008006168707013249615548460611155633566309344239656536183404166767844410701*t**10 - 0.00000000000070111135292795387525015077432921669919827194090818407310168876095947165821652630860341502667777696949947132648797491267545987291*t**9 + 0.000000000057694610687453000687645865100608927788420482264580486985779863937380641450272119693671739990793132878391678274033460317324712042*t**8 - 0.000000003560033175252346257226418438080953133192631484999216440324519760500948215786850815680880720913931433453567031429307548976503313*t**7 + 0.0000001655896923150252977492241540596439609649052221832321291327252110963055912144643943271462102732027876385539397878548104056238078*t**6 - 0.0000057867107664997448463499028244089449711571964804965971815969033830405123907539224808148514326235873144513304794471647300065550649*t**5 + 0.00014986697693060245132886758513156507875795698573229743950605833398697692696248715896971370299018021777263564892165851359766919555*t**4 - 0.0027955519228564120075507462040537734442459068320505595271307514152688502024805859123534489874654472671841622393512182019085199761*t**3 + 0.035585465335003458110584261542533193333573474234519755371503282621521946664136598005408848503227914858011889828830794381570863172*t**2 - 0.27729414537863365693728896610447758129999393435393763747878449480297318845078853811312008553752422326131998385937835501509294004*t + 1.0000000000000000228814856324789196040522086126924090340140735044280766632196133323750457994158912037287280059600740194492395169)/(0.00000000000000000099533336444995010636513174177509762112407572485535715930802770539826474163291014366131735605353964293297288925960750843102377074*t**17 + 0.000000000000000010076443559489818369705067762712488983919508148296521528897241222001481598614429668622543574738119577635674636355102710347692439*t**16 + 0.00000000000000099803140529347369231907590202428347602932466584112499192937014272193513957051204488765730073852466901985158305961630171580863645*t**15 + 0.000000000000021929711332561360156114430877474397789692589236715623366621686613923416334988551490354440884938953229749501932824069500794302897*t**14 + 0.000000000000656921469821669775765142398471394339129019336165976775230048260429362358475184860965349731202569967080235433009563435615998057*t**13 + 0.000000000014763544085912781412150655215674761576586217367545699428125237785779504795496585535892969558255554247629452943586015131497634531*t**12 + 0.00000000030690410653109898958736353818491297052113461785403715122950973287395922858877041608381883032879357697342178507229734380970435438*t**11 + 0.0000000055866285320057224635005145365210242215936316920275892416979293912827638152434036623098687851415107530988716869254091089745868205*t**10 + 0.000000089952033533504590178046844658685834015581997220603434219600125505947321549697701003553029626333577170318643785443862326238281232*t**9 + 0.0000012701896118955897646302833888356512240918605007253670980853627264945364743721543063760655157898958748359645124161185035282119519*t**8 + 0.000015592669068294270481977040909671598251522948350854045602870433844318817969425583271458965550966406151412303580141705501453452322*t**7 + 0.00016421910387421514908684360193094096813508535292271798665024884226446774469309995046032408207901770314633385628172069853063168792*t**6 + 0.0014566258090943959607737158640889148115666799945972947693853578219794889012346100742061068551264919802988141176838137637398098015*t**5 + 0.010598023489381217368305228196171031169811157296623726778973768298763642944339883600422605133405635162427970037618244396452792321*t**4 + 0.060809507390072969544948374061678245548718844034838210999013096234072798947904080235858584019321520171945089344172013937912689768*t**3 + 0.2582913199563004656458388599275823004674373938925706940539179046095982677829727529969437951764330218791899943550828768336385311*t**2 + 0.72270585462136953086709807011614574642770975007753508750132582366499300564340730527153757420697660780649806480050951229848890164*t + 1.0)")

In [2]: import mpmath

In [3]: mpmath.mp.dps = 128

In [4]: mpmath.plot(lambdify(t, rat_func - exp(-t), 'mpmath'), (0, 100))
```

The plot call is what tells you if the precision is lost or not. The correct answer should look like this

correct

The incorrect answer will look like this

incorrect

The function in question is a best rational function approximation to `exp(-t)` on `[0, oo)`, which is computed by first applying the Mobius transformation `c*(t + 1)/(t - 1)` to translate `[0, oo)` to `[-1, 1)` (`c` is chosen for numerical purposes, I'm here using `1.6*17 = 10.2`). `E` is the approximation  on `[-1, 1)` which we want to translate back to `[0, oo)` using the inverse transformation `(t - c)/(t + c)`. 

By the theory, the best rational approximation should equioscillate and have error ~10^-degree. The invalid graph with lost precision is even more pronounced in higher degrees, as the error near 0 is always on the order of 1e-17, even though the total error should be orders of magnitude smaller (17 is one of the first orders where this issue becomes noticeable, and also the only order I've thus far [OCRed digits from a paper](https://github.com/ergs/transmutagen/blob/master/transmutagen/tests/crv_coeffs.py) for).

**Comment by jksuom** [comment]
The precision of the coefficient domain RR is fixed by the Poly calls:
```
In [64]: n.domain.precision
Out[64]: 429   # corresponding to dps=128
```
Increasing the precision might help:
```
In [68]: n, d = fraction(E)

In [69]: n = Poly(n, domain=RealField(prec=440))

In [70]: n.domain.precision
Out[70]: 440
```

**Comment by asmeurer** [comment]
That doesn't seem to help.

**Comment by jksuom** [comment]
No effect at all?

**Comment by jksuom** [comment]
I would have expected that increasing the precision during the intermediate calculation would improve accuracy.

**Comment by asmeurer** [comment]
It does give some different digits near the ends of the coefficients , but when you compare it against the correct answer you see differences within the first 16 digits or so.

**Comment by jksuom** [comment]
16 digits of the coefficients of the transformed n and d?

**Comment by asmeurer** [comment]
The unification must be wrong somehow. If I use this I get the correct answer:

```
In [92]: p = Poly(t - 51/5, domain=n.domain)

In [94]: q = Poly(t + 51/5, domain=n.domain)
```

(previously `p` and `q` were `Poly(5*t - 51)` and `Poly(5*t + 51)`)

**Comment by asmeurer** [comment]
But if I use 

```
In [92]: p = Poly(5*t - 51, domain=n.domain)

In [94]: q = Poly(5*t + 51, domain=n.domain)
```

I get the wrong answer.

**Comment by jksuom** [comment]
That seems to explain some of your early results.

**Comment by jksuom** [comment]
Now we know where to look.

**Comment by jksuom** [comment]
Is it possible that the way Python reads 51/5 as a float will make the difference.
```
In [71]: dom = RealField(prec=329)

In [72]: p = Poly(t - 51/5, domain=dom)

In [73]: p.rep
Out[73]: DMP([1.0, -10.199999999999999289457264239899814128875732421875], RR, None)
```
That would seem to lose precision.

**Comment by asmeurer** [comment]
That's a possibility. The actual calculation is done with `0.6*17`, which gives the same thing as `51/5`.

**Comment by asmeurer** [comment]
Aha, I think this is the key. If I change the solve call to `rational=False` for `inv`, I get the right answer.  Meaning Poly.transform is probably fine. I wonder if my other, more naive methods that I tried before were failing simply because of this.

**Pull request merged**
