### PR TITLE
Speed up GCD evaluation of unity DMP

### PR DESCRIPTION
**Pull request by tschijnmo**
Using cancel on large polynomials could be very slow due to the evaluation of the GCD of the numerator and the denominator (issue #9341).  Now in the existing trivial case treatment function of GCD computation for DMPs, unity is added as a special case as well to speed it up.  Different from the flawed solution in PR #10108, this solution does not seem to affect the result in any way, and does pass all the tests.

### CODE REVIEW

**Comment by tschijnmo** [comment]
Could any core developer please have a review of this tiny patch please?  This three line change does not break any of the tests, while could speed up things like that in issue #9341 by orders of magnitude.  Although I do not have any actual benchmark, it could probably have similar speed up for simplification of anything without an actual denominator.  Thank you in advance.

**Comment by moorepants** [comment]
Can you point me to the tests that would be affected by this code? I'll merge the change if I feel confident that there exists sufficient tests. If there are not sufficient tests, you should add one to the PR.

**Comment by tschijnmo** [comment]
Thank you for helping!  In the failed attempt to fix this problem in commit cb515f9, the tests broken are the tests that are affected by this patch.  Basically it is all tests involving calling the `cancel` directly or indirectly, like the `test_cancel` in `sympy/core/tests/test_noncommutative.py`.  Since it does not add any new semantics to any function, it just speed things up for computing polynomial GCD with one, I guess maybe just the current tests can be used to test its correctness.

**Comment by asmeurer** [comment]
But are there actually existing test cases that hit this line of code? If so, I am +1 to merge.

**Comment by tschijnmo** [comment]
Yes, since the previous failed fix broke about a dozen tests, I guess all these tests will hit this code, or they won't be broken.  At least the `test_cancel` really hit the new code.

**Pull request merged**
