### PR TITLE
Update evalf.py - issue #13111 

### PR DESCRIPTION
**Pull request by Itay4**
Regarding issue #13111, changing func is sin / cos to isinstance(func, sin / cos)

### CODE REVIEW

**Comment by asmeurer** [comment]
`v.func is cos` needs to be replaced with `isinstance(v, cos)`, not `isinstance(v.func, cos)`.

**Comment by gxyd** [comment]
Looks good, merging. Thanks for the contribution.

**Comment by smichr** [comment]
ping @Itay4: What name and address would you like to have added to the AUTHORS file? Right now it appears as 'Itay4 <31018228+Itay4@users.noreply.github.com>'.

**Comment by Itay4** [comment]
@smichr Itay Keren etkeren@gmail.com

**Pull request merged**
