### PR TITLE
sample student-t from scipy

### LINKED ISSUE #19095: Sampling from Student T distribution fails
Hello,
trying to sample from a Student-T distribution fails.

Code:
```
from sympy.stats import StudentT, sample_iter
samples = list(sample_iter(StudentT("", 2), numsamples=1))
```

Error message

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-6e39a94cf726> in <module>
----> 1 samples = list(sample_iter(StudentT("", 2), numsamples=1))

~/anaconda3/envs/causalpy/lib/python3.7/site-packages/sympy/stats/rv.py in sample_iter_subs(expr, condition, numsamples, **kwargs)
   1178     count = 0
   1179     while count < numsamples:
-> 1180         d = ps.sample()  # a dictionary that maps RVs to values
   1181 
   1182         if condition is not None:  # Check that these values satisfy the condition

~/anaconda3/envs/causalpy/lib/python3.7/site-packages/sympy/stats/crv.py in sample(self)
    506         Returns dictionary mapping RandomSymbol to realization value.
    507         """
--> 508         return {self.value: self.distribution.sample()}
    509 
    510     def compute_expectation(self, expr, rvs=None, evaluate=False, **kwargs):

~/anaconda3/envs/causalpy/lib/python3.7/site-packages/sympy/stats/crv.py in sample(self)
    172     def sample(self):
    173         """ A random realization from the distribution """
--> 174         icdf = self._inverse_cdf_expression()
    175         return icdf(random.uniform(0, 1))
    176 

~/anaconda3/envs/causalpy/lib/python3.7/site-packages/sympy/stats/crv.py in _inverse_cdf_expression(self)
    189         except NotImplementedError:
    190             inverse_cdf = None
--> 191         if not inverse_cdf or len(inverse_cdf) != 1:
    192             raise NotImplementedError("Could not invert CDF")
    193 
```

Sympy version: 1.5.1
Python version: 3.7
OS: ubuntu 19.04

### PR DESCRIPTION
**Pull request by maichmueller**
Made the StudentT distribution sample via Scipy (analogous to InverseGaussian)

Fixes #19095

Added the `sample` method to the student-t distribution and appended .tolist() to the scipy call of InverseGaussian to maintain consistency with the datatypes (without tolist the sample method would return a numpy.float64, with tolist it returns a python float).

* stats
  * Added sample method for student-t distribution.

### CODE REVIEW

**Comment by Smit-create** [comment]
@maichmueller Thanks for the PR!, Actually sampling API is undergoing significant changes in #18754. Following the discussions there, It is decided to make the sampling design to avoid code repetitions and make it clearer and compact.

**Comment by czgdp1807** [comment]
I suspect that this can be closed. Thanks for the contributions though. Attaching `Could Close` label.

**Comment by sylee957** [comment]
@Smit-create Can you clarify that it works with your branch? I don't think that it works. You don't even have anything added to the rv_map

**Comment by Smit-create** [comment]
I have locally added but not pushed yet, because I am trying to resolve errors related to `'python'`.
I have added this to `scipy_rv_map`, and it works as above. 
```
'StudentTDistribution': lambda dist, size: scipy.stats.t.rvs(df=float(dist.nu),
            size=size),
```

**Comment by sylee957** [comment]
Okay, if it works as a simple addition to your branch, then this can be closed. But we'd hear the response from the original author.

**Comment by maichmueller** [comment]
Hey thanks for the respones. I just discovered this repo a few days ago, so I may be unaware of specifics, but I thought I'd add my 2cents:
Is there a reason as to why the stats module isn't using scipy wherever possible? I understand it would add a dependency to the module, however seeing as how scipy is the defacto python standard for stats it allows to take the burden of this module off sympy and onto a well developed package instead. This would specifically defer worries of numerical stability and performance.
So I'd suggest, wherever possible, to defer all calls to scipy (including pdf, cdf etc.), unless there is a reason underneath the hood for not doing so.
The only thing that may need to be adressed is the change of return type, if one seeks consistency. (stdlib random -> python float, scipy -> numpy float / array (.tolist would convert that to float))

With that said, if your refactor pr takes care of what I've done in this PR @Smit-create, then i'm happy with closing it.

**Comment by asmeurer** [comment]
See the discussion at https://github.com/sympy/sympy/issues/14261

**Comment by czgdp1807** [comment]
Closing this as the discussion on what should be done is still going on which will affect the public APIs.

**Pull request closed without merging**
