### PR TITLE
Update sage ci to use python 3.8

### PR DESCRIPTION
**Pull request by eagleoflqj**
#### References to other Issues or PRs

Related to #21884

#### Brief description of what is fixed or changed
Re-pick the first commit of #21941 to run on ubuntu groovy instead of debian buster.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I'm not really sure why this is needed.

**Comment by eagleoflqj** [comment]
> I'm not really sure why this is needed.

Originally at https://github.com/sympy/sympy/pull/21941/commits/1e835fb708f1d8fa7fde04311f53ce0c07d8ef0c all supported python versions of sympy were tested, which was then considered unnecessary, so finally only the oldest and newest python version are tested. That's why we have debian-buster and arch-latest.
As we decide to drop python 3.7 support, 3.8 becomes the oldest version we support, this should be reflected on sage ci.

**Comment by eagleoflqj** [comment]
@mkoeppe What do you think?

**Comment by mkoeppe** [comment]
`ubuntu-groovy` is past EOL (https://fridge.ubuntu.com/2021/07/25/ubuntu-20-10-groovy-gorilla-end-of-life-reached-on-july-22-2021/). I'd suggest to use `ubuntu-focal`, which is an LTS and also has 3.8 as the default python3.

**Comment by eagleoflqj** [comment]
I think @mkoeppe approves this change. Could we move on dropping python 3.7? @oscarbenjamin

**Comment by oscarbenjamin** [comment]
Looks good. Thanks both.

**Pull request merged**
