### PR TITLE
Fixes Quantity Add postprocessor (ordered dict in Python 3.6)

### PR DESCRIPTION
**Pull request by jirikuncar**
Fixes issue with ordered dictionaries in Python 3.6.

### CODE REVIEW

**Comment by asmeurer** [comment]
Is there an issue for this fix? Can you add a test. 

Also, this should be against master, not 1.1. You will need to wait until 1.1 is merged, or else cherry-pick to a new PR.

**Comment by jirikuncar** [comment]
> Is there an issue for this fix?

Consider this PR a bug report :wink:

> Can you add a test.

 It happens when new quantity is created manually from derived units. I would have to deeply investigate how the internals of the solvers work or artificially create an ordered dict. Please note that it's anyway not safe comparison since `items` will not produce consistent tuples. Alternatively we can build a set of tuples (dimension, size) for each quantity.

@asmeurer I have found this code *only* in 1.1 which is the only branch which "almost" works for our use-case.

**Comment by jirikuncar** [comment]
@asmeurer I have added a test case. You can check that it is failing on Python 3.6 if you don't apply 7e67d21. Cheers 🍻

**Comment by asmeurer** [comment]
Sorry this came in too late for the 1.1 release. Once I merge the 1.1 branch I can change the base of this PR to `master` and merge it (the test failure is unrelated https://github.com/sympy/sympy/issues/12898).

**Comment by jirikuncar** [comment]
@asmeurer I hope you will be able to release a minor version 1.1.1 quickly so we can use it on Python 3.6 soon. Thanks!

**Comment by asmeurer** [comment]
I'm thinking I might, as a lot of other little issues have come up.

**Comment by asmeurer** [comment]
Can you merge this with master to trigger Travis again. I don't want to restart the Travis build, as  #12898 references it.

**Comment by asmeurer** [comment]
Actually never mind, I am creating a separate release branch. I'll just merge this manually.

**Pull request merged**
