### PR TITLE
Fix test failures from repeated test runs

### PR DESCRIPTION
**Pull request by asmeurer**
If you run the test or doctests multiple times in the same process, you get some failures. See #15149. 

To reproduce the errors, run

```
from sympy import *
test(subprocess=False)
test(subprocess=False)
doctest(subprocess=False)
doctest(subprocess=False)
```

Unfortunately, we can't really test this on CI, as it would require running all the tests twice. Plus we split the tests up and some failures are cross-failures (e.g., doctest failures that come from running the tests).

I intend to push as many fixes here as I can, but feel free to review at any time. 

#### References to other Issues or PRs

Address many issues in #15149, but not all of them yet.
#### Release Notes

* printing
  * Keyword arguments to the `dotprint` function no longer affect consecutive calls.
* core
  * Singleton classes with the same name that are defined twice now properly re-register on the `S` object.

### CODE REVIEW

**Comment by timokau** [comment]
Thanks! Regarding travis testing: couldn't you set the `PYTHONHASHSEED` outside of python? Or alternatively just always run in a subprocess (even if `PYTHONHASHSEED` is set). The second one only if it is a simple doctest failure and not revealing any real issues of course.

**Comment by asmeurer** [comment]
There's no functional difference between setting it outside of Python and setting it in Python. The only difference is if we set it outside of Python, we have to do it in a shell language. Also doing it that way would make it not enabled by default (e.g., when users run the tests on their own machines). 

Actually, so far these have been revealing real bugs, which could also occur when using these functions multiple times in the same session. For instance, the `dotprint` failure was due to mutating a global value that should have been function local.

**Comment by timokau** [comment]
I just mean setting it outside of python on the travis build to test the behaviour.

**Comment by asmeurer** [comment]
Well the only difference is that the tests don't run in a subprocess, which can also be done with `./bin/test --no-subprocess` or `test(subprocess=False)`. But the only difference that makes is when it is run alongside something else in the same session, if the tests are modifying some global state. Actually it's kind of nice that `test()` does run in a subprocess by default because it means any such bugs don't affect any end users who might run the tests from within a Python session.

**Comment by timokau** [comment]
Yes but running it without subprocesses on travis may help catch those bugs.

**Comment by asmeurer** [comment]
We would have to run the tests twice. Just running them once and nothing else with subprocess=False is no different from running them with subprocess=True. Unfortunately, we already have too many Travis builds (the full test suite is split into 5 builds for each Python version), so we don't have the resources to run tests like this. We'll just have to occasionally do it manually.

**Comment by timokau** [comment]
Alright I thought running it without subprocesses would always expose more bugs. But now thinking about it I realized that it may also hide bugs where the tests rely on some global state so I guess you can't have your cake and eat it too.

**Pull request merged**
