### PR TITLE
Elliptic functions now use visually distinct symbols

### PR DESCRIPTION
**Pull request by shishir-11**
#### References to other Issues or PRs

Makes some of the required Changes in #26143

#### Brief description of what is fixed or changed
The elliptical functions in special functions module now use visually different variables that used to earlier use same variable if given inside the function .

#### Release Notes

* functions
   * Fixed usage of visually same variable when converting to integral in elliptical functions.

### CODE REVIEW

**Comment by sylee957** [comment]
See https://github.com/sympy/sympy/issues/26143#issuecomment-1919673724 I don't think that you should add commented out code

**Comment by shishir-11** [comment]
I'll remove the lines i commented. anything else i need to add or any tests you would recommed?

**Comment by sylee957** [comment]
I don’t think that you need any tests.

**Comment by sylee957** [comment]
I notice that I didn’t commit review suggestions before

**Comment by shishir-11** [comment]
@sylee957 I Made the changes you suggested in a new commit . New to contributing so i just made a new comitt instead of resolving the conversation , Hope that's okay.

**Pull request merged**
