### PR TITLE
Came across a bare "except": converted it to "except Exception:"

### PR DESCRIPTION
**Pull request by nilabja-bhattacharya**
https://github.com/sympy/sympy/issues/11668 As stated in issue, I came across a "bare except:", changed it to "except Exception:"

<!-- If this pull request fixes an issue please indicate which issue by typing "Fixes #NNNN" below.>

### CODE REVIEW

**Comment by asmeurer** [comment]
`except Exception` is better, but it would be better to except the actual error that this is expecting, or rewrite the code to not use a try block.

**Comment by nilabja10201992** [comment]
Should I change it to `except NotImplementedError:` ?

**Comment by gxyd** [comment]
@nilabja10201992 can you please fix the merge conflicts here?

**Comment by nilabja10201992** [comment]
@gxyd sure I'll try, can you please guide me in which file?
Is it in sympy/calculus/util.py?

**Comment by nilabja10201992** [comment]
@gxyd should I change to what it initially was i.e. except: ?

**Comment by gxyd** [comment]
First you would need to resolve merge conflicts, here is the link https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ . Let me know if you still have any problem.

Secondly, I think you are right, it should be `NotImplementedError`, seems like the only possible error that can be raised is `NotImplementedError` which can be raised by `solveset`.

**Comment by nilabja10201992** [comment]
@gxyd I had deleted my local repository, I there any other to resolve merge conflict?

**Comment by ylemkimon** [comment]
You may see 'Restore branch' button here somewhere.

**Comment by gxyd** [comment]
I don't know if there is any of getting around that. You deleted your local repository? Also seems like there is no branch with these changes on github as well on your sympy repository.

You can get a fresh copy of sympy (if you don't have one locally), send in a new pull request and then close this one. Also make sure to send the PR against 'master' branch of sympy, currently you sent it against 'Upabjojr-patch-2'.

**Comment by nilabja10201992** [comment]
@gxyd I've deleted the pull request, will this resolve the merge conflict? or should I send another pull request?

**Comment by gxyd** [comment]
You will need to send another one. Create a new branch in your local sympy repository, then make the changes (`except NotImple...`) that you made in this PR (the one you closed). Then send it against the master branch of SymPy.

**Comment by nilabja10201992** [comment]
@gxyd I've made the changes, thank you for guiding.

**Pull request closed without merging**
