### PR TITLE
Sample from a list instead of a set for python 3.9 compatibility

### PR DESCRIPTION
**Pull request by jamesjer**
#### Brief description of what is fixed or changed

The Fedora project is rebuilding all of its python packages with the current alpha release of python 3.9 in order to find and fix problems prior to the release of 3.9.  The sympy package failed its tests due to the deprecation of sampling from a set.  See:

https://bugs.python.org/issue40325
https://github.com/python/cpython/commit/4fe002045fcf40823154b709fef0948b2bc5e934

This commit changes the sympy code to sample from a list instead.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Thanks this looks good.

See also #18466

**Comment by oscarbenjamin** [comment]
I think maybe this should go into sympy 1.6 as well...

**Comment by oscarbenjamin** [comment]
I've opened #19293 for 1.6

**Comment by asmeurer** [comment]
Thank you for this. We've attempted to run the tests against 3.9-dev on Travis but ran into issues https://github.com/sympy/sympy/pull/18466. We should probably do this manually before releasing to make sure there aren't any errors, as 3.9 will likely be released before 1.7.

**Comment by jamesjer** [comment]
Thanks for the quick action on this.  For what it's worth, we got a good build with python 3.9 (as in, the build passed all of its tests) after applying just this change.

**Comment by oscarbenjamin** [comment]
That's good to know. I've installed the current alpha so I can give it a try myself. Obviously it's still a moving target at this stage with 5 months to go before final release of 3.9 but it's good to fix anything we can before the (imminent) release of sympy 1.6.

**Pull request merged**
