### PR TITLE
TODO: rebase Addressing Piecewise issues

### PR DESCRIPTION
**Pull request by flacjacket**
This push is to address a couple open issues with Piecewise and its syntax, notably changing the otherwise syntax. Other major changes with this commit are getting rid of the ExprCondPair class and changing how evaluation is handled. The use of True as the condition to specify otherwise conditions is deprecated. Additionally, the use of numbers as conditions is deprecated and the use of Interval's as conditions is dropped entirely. To implement the same functionality, either the '.as_relational()' or '.contains()' methods of Interval can be used.

As before, evaluation strips any bools out of the args by dropping expressions with False, but now expressions with condition=True are promoted to the otherwise statement by evaluation. Evaluation is not performed by default, but it is called when subs is called to allow for evaluation in that case. When bools end up in the args and evaluate is the default value of False, a deprecation warning is raised and evaluate is set to True to get clear the args of the bool.

The properties '.exprcondpairs' and '.otherwise' are implemented to easily access the expr/cond pairs and otherwise statement, respectively.

**TODO:**
## 

**This addresses the following issues:**

#5200 (closed) latex printing with piecewise function : reversed expr and cond

#5666 (now doesn't raise an error but perhaps could be better than Piecewise()) Piecewise does not work when not given an "otherwise" condition

#5725 Piecewise should use a different syntax for "otherwise"

#5809 (closed) Cannot simplify Piecewise

#5825 (closed) Piecewise((1,Interval(0,1,False,True)),(0,True)) syntax should not be allowed

Also, the following also seems like it has been handled, but not closed:

#4315 (no error but discussion about what the result should be) series expansion of piecewise fails

### CODE REVIEW

**Comment by smichr** [comment]
I happened across this after working rather intensely on getting more Piecewise issues to work. These are concerning to me. But they are old and maybe the understanding has changed. But let me tell you what it looks like to me.

> expr, cond doesn't work because not every expression has a condition.

If there is no condition, then it shouldn't be in a Piecewise. The only exception that I can think of is the condition "not any of the preceding" which is what is meant by `(cond, True)`.

> In [2]: Piecewise((1, x < 0), (2, 1 > 0), (3, True), nan)
> Out[2]: 
> ⎧1  for x < 0
> ⎨            
> ⎩2  otherwise
>
> I think these are wrong. They should both evaluate to 2.

I believe this is fundamentally the wrong way to view Piecewise. The expr,cond pairs are *prioritized* by their position in the arg list (as I understand it). Stepping through these args we have an enevaluated condition followed by a True condition at which point -- and current behavior supports this -- anything past that is ignored because the True means "not any previous condition."  So the current print out is correct: the expression is 1 (if x < 0 happens to evaluate) otherwise it is 2.

I tend to agree that there is no need to change the internal representation of the Piecewise args. One can allow an alternate input syntax without too much harm, though. And the printer could be made to show it this way. On the other hand, having a keyword to extract the Expr,Cond pairs and one to extract the default value would be fine -- one ends up having to watch for the True, anyway, so it might as well be stored as a separate value.

How serious do we want to pursue the changes of this PR?

**Comment by asmeurer** [comment]
FWIW, I now think that Piecewise is correct. It should be thought of as an if-then-else chain. This works well for things like code generation, and also with the basic fact that it's impossible in general to ensure that two (expr, cond) pairs agree with each other where both conditions are true.

**Comment by smichr** [comment]
@asmeurer , do you still favor the True-less printing and entry for Piecewise? I have some modest mods that allow for the following:

```
>>> p = Piecewise
>>> p()
Piecewise()
>>> p(2)
2
>>> p(default=2)
2
>>> p((1, x< 0), 2)
Piecewise((1, x < 0), 2)
>>> p((1, x< 0), default=2)
Piecewise((1, x < 0), 2)
>>> p((1, x< 0), (2, True))
Piecewise((1, x < 0), 2)
>>> p((1, x< 0), (2, True), default=3)  # or should this raise an error?
Piecewise((1, x < 0), 3)
>>> p((1, x< 0), (2, True), (3, True))
Piecewise((1, x < 0), 2)
>>> _.ec, _.default  # or similar names
(((1, x < 0),), 2)
```

**Comment by asmeurer** [comment]
It could be useful, but on the other hand, it leads to some ambiguity. Also, what would `Piecewise()` with no arguments mean?

**Comment by smichr** [comment]
> It could be useful, but on the other hand, it leads to some ambiguity. 

I'm going to close this. I can't see a compelling reason to not use the `(otherwise, True)` condition as the default arg. The pretty printing looks good, so all we would be doing is simplifying the output of `str`. And that can be done without changing the internals. #12654 does this by allowing a `default` arg go be given.

> Also, what would Piecewise() with no arguments mean?

It means that there is no definition for the expression. It is Piecewise's way of saying "undefined".

If anyone desires to comment on this, please do so on #12654 after reopening it.

**Pull request closed without merging**
