### PR TITLE
RTM of thick lens

### LINKED ISSUE #17830: SymPy optics module CurvedRefraction radius of curvature sign convention
Inside optics module Ray Transfer Matrix (RTM) parameter R is said to be positive if surface is concave. It is not always true. 

In case of describing Thick Lens you build a lens using  CurvedRefraction * FreeSpace * CurvedRefraction. 

Thick lens surfacaces are said to be convex or concave regarding center axis of lens.
Surface radius of curvature sign is determined using Cartesian sign convention. It means that:
 if radius of concave ar convex surface is to the left, the sign is negative. 
 if radius of concave or convex surface is to the right, the sign is positive.   

Here is illustration of what I mean:
diagram-20191031

```
class CurvedRefraction(RayTransferMatrix):
    """
    Ray Transfer Matrix for refraction on curved interface.

    Parameters
    ==========

    R : radius of curvature (positive for concave)
    n1 : refractive index of one medium
    n2 : refractive index of other medium

    See Also
    ========

    RayTransferMatrix

    Examples
    ========

    >>> from sympy.physics.optics import CurvedRefraction
    >>> from sympy import symbols
    >>> R, n1, n2 = symbols('R n1 n2')
    >>> CurvedRefraction(R, n1, n2)
    Matrix([
    [               1,     0],
    [(n1 - n2)/(R*n2), n1/n2]])
    """
    def __new__(cls, R, n1, n2):
        R, n1, n2 = map(sympify, (R, n1, n2))
        return RayTransferMatrix.__new__(cls, 1, 0, (n1 - n2)/R/n2, n1/n2)
```

### LINKED ISSUE #20149: Gaussian Optics
Gaussian optics is missing few Ray Transfer Matrix , mainly-

Thick Lens(partially states in issue #17830)
Single Prism
Multiple Prism

### PR DESCRIPTION
**Pull request by sidhu1012**
#### References to other Issues or PRs

Partial fix #20149 
Fixes #17830

#### Brief description of what is fixed or changed
Added Ray Transfer Matrix for thick lens

#### Release Notes

- physics.optics
    -  Added RTM for thick lens

### CODE REVIEW

**Comment by sidhu1012** [comment]
Can someone pls review this PR

**Comment by oscarbenjamin** [comment]
@oscarlazoarjona can you review this?

**Comment by oscarlazoarjona** [comment]
@oscarbenjamin @sidhu1012 I'll look at this on the weekend.

**Comment by sidhu1012** [comment]
@oscarlazoarjona Review pls

**Comment by sidhu1012** [comment]
@oscarlazoarjona Please review when free

**Comment by oscarlazoarjona** [comment]
@sidhu1012 Apologies. I've had a series of commitments I did not expect. I can review this weekend.

**Comment by sidhu1012** [comment]
> @sidhu1012 Apologies. I've had a series of commitments I did not expect. I can review this weekend.

Yes sure, no worries 😁

**Comment by sidhu1012** [comment]
@oscarlazoarjona Eagerly waiting for review

**Comment by czgdp1807** [comment]
@oscarlazoarjona Please review this PR as well. Thank you.

**Comment by sidhu1012** [comment]
Closing and opening to restart tests.

**Pull request closed without merging**
