### PR TITLE
[WIP] Added functions for Perfect Numbers in ntheory/factor_.py

### LINKED ISSUE #15926: Function for perfect, deficient, abundant numbers
There should be a separate function for checking whether a number is perfect, deficient or abundant. If you liked this idea then I can add a pull request.

- [x] perfect
- [ ] deficient
- [ ] abundant

### PR DESCRIPTION
**Pull request by jhanwar**
#### References to other Issues or PRs
About issue #15926 

#### Brief description of what is fixed or changed
Functions of Perfect Numbers is added. There are only 51 perfect numbers. So i created a list and added perfect_number, perfect_numberpi,  next_perfect_number,   prev_perfect_number, perfect_number_range

#### Other comments
This PR need some changes. Please suggest changes.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
This doesn't fully fix the issue, so the "fixes" should not be there. 

Please add a release notes entry. 

This also needs tests and documentation.

**Comment by asmeurer** [comment]
The c list should be factored out so it isn't written multiple times. It would also help to have a comment indicating what it is.

**Comment by asmeurer** [comment]
These functions need some caveats. Odd numbers have only been tested up to 10^1500 according to MathWorld, and according to Wikipedia, it is not known if any additional Mersenne primes exist between the known 47th (M_43112609) and 51st (M_82589933). I'm also not really sure if we need all these functions, given that there are only 51 of them. 

Some of these functions, if we keep them, should be made more efficient. For instance, we can check if a number is less than or greater than a given perfect number without computing it explicitly.

**Comment by asmeurer** [comment]
How about we just have the functions

```
MERSENNE_PRIME_EXPONENTS - Your list c. Add a comment that it should be updated whenever new Mersenne primes are found.
mersenne_prime(n) - Returns the nth *known* Mersenne prime, with caveats that there may exist not-yet-found primes before them. 
perfect_number(n) - Returns the nth *known* perfect number, with caveats that other perfect numbers may exist not returned by it.
is_perfect(n) - Returns True if n is perfect and False otherwise (mainly for consistency with a future is_abundunt(n) and is_deficient(n))
```

I'd also like to hear others' opinions on the API.

**Comment by jhanwar** [comment]
I will factor out the c.  Should I make a different class of Perfect numbers (in which i will include all three - abundant, deficient and perfect)?
We can add definitely comments for caveats or any other solution? 
And yes, definitely we can check if a number is greater than or less than than a given perfect number without computing it explicitly. We can do it by comparing no. of digits.
Which functions can be added more and which are useless?

**Comment by jhanwar** [comment]
I have added some comments and also added functions ( Mersenne prime(n), ischeck, isless and isgreater for Perfect Numbers). Solution does not require to calculate explicitly.
I have commented caveats. Is that ok or I need to add more for caveats.
Please review changes

**Comment by jhanwar** [comment]
@asmeurer 
Any comments?

**Comment by Abdullahjavednesar** [comment]
>This doesn't fully fix the issue, so the "fixes" should not be there.
>
>Please add a release notes entry.
>
>This also needs tests and documentation.

 I don't see the above comments addressed.

**Comment by jhanwar** [comment]
I was little busy in previous weak. I have added tests. Can you guide me how to write documentation?

**Comment by oscarbenjamin** [comment]
The main issue to be resolved before writing documentation is the API. I don't think it makes sense to have this many functions.

Including the Mersenne prime exponents makes sense (with a better name than `c` e.g. `MERSENNE_PRIME_EXPONENTS` as suggested). From there getting the nth Mersenne prime or even perfect number with the caveats above is trivial so I'm not sure even that those functions are adding much.

Does `isprime` work efficiently for all of these Mersenne primes (except the largest ones I guess)? If not it might be worth using this list there somehow.

Can you explain what someone might want to use any of these functions for? That might help in thinking about which are useful and what their signatures should be.

**Comment by jhanwar** [comment]
`is prime` work effectively for Mersenne Primes. There is no need to mention it separately. I also feel now that these many functions are not required. Can you please tell me which function should we keep?

**Comment by jhanwar** [comment]
`isperfect_number` is necessary for future. Implementing functions for abundant and deficient numbers will require this function

**Comment by jhanwar** [comment]
@oscarbenjamin  Can you guide me in this?

**Comment by oscarbenjamin** [comment]
Why not add is_perfect, is_abundant and is_deficient?

**Comment by jhanwar** [comment]
I have added isperfect in new pull request. I deleted this branch by mistake. 
New PR #16055

**Comment by sidhantnagpal** [comment]
Closing this, as #16101 has been merged.

**Pull request closed without merging**
