### PR TITLE
Simplification of singularity-function to calculate shear_force, bending_moment, deflection etc at any point on beam

### PR DESCRIPTION
**Pull request by divyanshu132**
#### Brief description of what is fixed or changed
Singularity-function has been simplified to calculate shear_force, bending_moment, deflection etc at any point on beam.

Previously:

```
>>> b.shear_force()
−8⟨x⟩^0+6⟨x−10⟩^0+120⟨x−30⟩^−1+2⟨x−30⟩^0

>>> b.shear_force(15)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: shear_force() takes exactly 1 argument (2 given)

```
Now:
```
>>> b.shear_force(15)
-2

```
#### Release Notes

*  physics.continuum_mechanics
   *  calculate shear_force, bending_moment, deflection etc at any point on beam

### CODE REVIEW

**Comment by divyanshu132** [comment]
ping @moorepants @jashan498 @oscarbenjamin

**Comment by jashan498** [comment]
I am not sure if this change is really required. You can always do something like `b.shear_force().subs(x, 15)` to get the numeric value.

**Comment by divyanshu132** [comment]
The thing is that I've tried directly passing the value `b.shear_force(15)` so, I thought it would be worth including it.

**Comment by czgdp1807** [comment]
Closing this due to inactivity and https://github.com/sympy/sympy/pull/16195#issuecomment-470851425
IMHO, this change was too trivial to be included. However, if someone supports this PR then please comment below, it will be re-opened and will be completed.
Thanks for the contributions. Apologies for inconveniences.

**Pull request closed without merging**
