### PR TITLE
Update Code of Conduct to Contributor Covenant version 1.4

### PR DESCRIPTION
**Pull request by asmeurer**
The main difference is that it lists some examples of positive things.

### CODE REVIEW

**Comment by asmeurer** [comment]
[Here's](https://github.com/sympy/sympy/pull/10508/files?short_path=a1ee87d#diff-a1ee87dafebc22cbd96979f1b2b7e837) a readable diff.

**Comment by certik** [comment]
I think this nicely clarifies the issue that @hargup raised.

+1 to merge

**Comment by asmeurer** [comment]
Yep. I was also thinking that you or I (or both) should write a blog post on what our standards of acceptable behavior are, since the CoC says "project maintainers are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behavior."

**Comment by certik** [comment]
Yes, I definitely plan to write a blog post about this.

**Comment by moorepants** [comment]
+1

**Pull request merged**
