### PR TITLE
Revert "DOC: Use README.rst for pypi.org page"

### PR DESCRIPTION
**Pull request by moorepants**
The README was converted to markdown. It isn't clear what the reason for this conversion was. The README has been in RestructuredText, like the rest of the SymPy documentation, since the project's inception. I'd like to revert this PR, as there is no benefit to this change. We should keep our documentation in a common format. RestructuredText offers more features than markdown and Python developers are very familiar with RestructuredText as it is by far the most widely used documentation format.

This reverts PR https://github.com/sympy/sympy/pull/19179

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
I don't feel strongly either way. I prefer Markdown, and I think your statement that most Python developers know RST better than Markdown is false. Just look at how many people erroneously use single backticks for code in SymPy docstrings. 

The original concern here is that PyPI uploads can fail on bad RST in the long description. There were some suggestions on the original PR on how to add a check before uploading.

**Comment by moorepants** [comment]
>  I think your statement that most Python developers know RST better than Markdown is false

That's stretching what I stated. RestructuredText is the most common documentation format for Python projects (for a long time now). Whether people get confused about a single formatting character (backticks) doesn't seem to negate that Python developers are most familiar with  RestructuredText for Python documentation.

> The original concern here is that PyPI uploads can fail on bad RST in the long description. There were some suggestions on the original PR on how to add a check before uploading.

This seems like something readily repairable.

Just for purposes of discussion I would have -1 the original PR, but of course maybe no one else would have.

**Comment by oscarbenjamin** [comment]
I don't have any strong feelings about rst vs markdown.

We use rst for the docs but I don't see the README as being part of the docs. The docs are rendered as html etc whereas I always thought the point of a README was that you open it in a text editor after unzipping the code. Before github I would just have a plain text file README with whatever ASCII formatting I wanted. Then github made it possible to have a README that renders as a landing page if you call it README.md and that seemed worth doing because someone can see it before they even download the code.

If this is going to change then I guess it should happen for 1.6 so adding the milestone.

**Comment by moorepants** [comment]
Just gonna close this. I'd like to keep it the way it was, but there's little to gain trying to undo this.

**Pull request closed without merging**
