### PR TITLE
`real_bound` added to Function class

### PR DESCRIPTION
**Pull request by gxyd**

### CODE REVIEW

**Comment by jksuom** [comment]
It might not be necessary to add ``real_bound`` to the dictionary of all functions. (I sometimes feel that the dictionary is too big already.) There are probably not many functions for which it would be needed. It could be better to add it just to those functions, and then test for its existence in the code of ``order``. (Maybe using ``try:...except...``.)

**Comment by asmeurer** [comment]
Is it really necessary to get a number, rather than a "yes" or "no" on whether it is bounded? I don't see a number being useful unless you can guarantee tight bounds (which is not simple to do in general).

**Comment by jksuom** [comment]
Maybe "yes" or "no" would suffice, but I was thinking of possible generalizations where the bound would not be constant (such as the bound of ``x*sin(x)``). In any case, it is important to realize that this should apply to the restriction of the function to (positive) real axis only. (An analytic function bounded
in the complex plane is constant.)

**Comment by gxyd** [comment]
This PR probably did not went anywhere, so closing..

**Pull request closed without merging**
