### PR TITLE
fix(core): don't extract Float from Pow of Add

### LINKED ISSUE #20927: sqrt() automatically pulls out a floating point factor
```py
>>> sqrt(4*x + 16)
sqrt(4*x + 16)
>>> sqrt(4.*x + 16.)
4.0*sqrt(0.25*x + 1)
```

I don't think the second instance should be automatically rewritten as it is. It's not simpler than the original, and doing such an automatic simplification can change the behavior of an expression when evaluated on floating point inputs.

### LINKED ISSUE #27195: Pow of Add should not extract Floats
I don't know if there is an existing issue about this but this behaviour should be changed:
```python
In [4]: (x**2 + 10)**2
Out[4]: 
         2
⎛ 2     ⎞ 
⎝x  + 10⎠ 

In [5]: (x**2 + 10.0)**2
Out[5]: 
                  2
      ⎛     2    ⎞ 
100.0⋅⎝0.1⋅x  + 1⎠ 
```
The behaviour comes from gh-16762 which links various issues but I don't see any good justification for applying this transformation especially automatically. The example above with 10.0 becoming 100.0 might seem reasonable (I don't consider it reasonable) but there are many situations where this is clearly a bad idea:
```python
In [15]: (x**2 + 7.0)**1000
Out[15]: 
                                                1000
                      ⎛                   2    ⎞    
1.25325663996572e+845⋅⎝0.142857142857143⋅x  + 1⎠ 
```
This behaviour should not be expected and anything that it was intended to address should be handled some other way.

The code that handles this is here:
https://github.com/sympy/sympy/blob/30c23fec32d6babaab813e8c67a133d1ce08a42a/sympy/core/add.py#L490-L503
There is a comment with a question "should this always be done" I think that the answer is that it should never be done automatically like this. There can be some other function for doing things like this if desired. Otherwise it is generally a bad idea to special case floats like this in low-level expression manipulation. Especially with floats it is important to avoid performing any unnecessary arithmetic that can introduce additional rounding errors.

Actually I'm unsure about the whole of `Add._eval_power`. It is no wonder that anything with SymPy expressions is slow when you see stuff like this:
https://github.com/sympy/sympy/blob/30c23fec32d6babaab813e8c67a133d1ce08a42a/sympy/core/add.py#L454-L503

### PR DESCRIPTION
**Pull request by oscarbenjamin**
Fixes gh-27195
Fixes gh-20927

Reverts gh-16762

This fixes e.g.
```
    In [4]: (x**2 + 10)**2
    Out[4]:
             2
    ⎛ 2     ⎞
    ⎝x  + 10⎠

    In [5]: (x**2 + 10.0)**2
    Out[5]:
                      2
          ⎛     2    ⎞
    100.0⋅⎝0.1⋅x  + 1⎠
```
Extracting a float like this was added in gh-16762 commit c1e25a445f1c27829ea8cf0e04dbdd6d749834ce.

This commit reverts this change because there is no reason to do this and in general it is better to preserve the basic form of the expression if it cannot be substantively simplified by simple rules.

#### Release Notes

* core
   * Floats are no longer extracted from a power of an Add e.g. an expression like `(x**2 + 10.0)**2` will be kept as is. Previously a float was extracted to `100.0*(0.1*x**2 + 1)**2`. This reverts gh-16762 that introduced this change in SymPy 1.5.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I remember there was already an issue about this gh-20927.

**Comment by bjodah** [comment]
FWIW, I think this change is for the better. Is there a way for a user to achieve the extraction of floats? (perhaps using `powsimp` with some flag or something simliar). If so, we could add an instruction to the changelog for how to achieve that.

**Comment by bjodah** [comment]
No you're right. I cannot come up with a counter-example where the old behavior is preferable.

**Comment by oscarbenjamin** [comment]
Code that wants to optimise (for speed or accuracy) floating point expressions will work better with the change here. The output of any optimiser will be some form of expression and the change here means that the resulting optimised form will be preserved rather than transformed into a different expression.

**Comment by bjodah** [comment]
OK, if I try *really* hard I can come up with one "potential" regression:

master:
```python
>>> ccode(Float('1e200')*sqrt(Float('1e-400')*exp(x) - Float('1e-400'))) 
'0.99999999999999998*sqrt(exp(x) - 1)'
```
this branch:
```python
>>> ccode(Float('1e200')*sqrt(Float('1e-400')*exp(x) - Float('1e-400')))
'1.0e+200*sqrt(9.9999999999999993e-401*exp(x) - 9.9999999999999993e-401)'
```
the e-401 floats underlow to zero for 64-bit double fp. Just to be clear: I don't consider this a problem.

**Comment by bjodah** [comment]
I know and I agree.

**Review by bjodah — APPROVED** [review]

**Comment by sylee957** [comment]
Looks good

**Comment by oscarbenjamin** [comment]
Thanks both for the reviews.

**Pull request merged**
