### PR TITLE
Unpin the symengine version

### PR DESCRIPTION
**Pull request by sidhu1012**
#### References to other Issues or PRs

All comments from here https://github.com/sympy/sympy/pull/21710#issuecomment-875713566

#### Brief description of what is fixed or changed
Unoin the symengine version on Travis

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by moorepants** [comment]
I guess this can't be tested until merged to master. I'm going to do that, but if things go haywire I'll revert.

**Comment by moorepants** [comment]
Actually, you could test this locally first. By running the tests with symengine (latest) installed. Oh well...

**Comment by sidhu1012** [comment]
Issue still persists

**Comment by sidhu1012** [comment]
#21674 might solve it

**Comment by oscarbenjamin** [comment]
Have you tested locally? Can you reproduce the issue and confirm that it depends on the symengine version?

**Comment by sidhu1012** [comment]
> Have you tested locally? Can you reproduce the issue and confirm that it depends on the symengine version?

How can I test optional dependencies locally? I think the issue is related to Travis, but I'm not sure.

**Comment by moorepants** [comment]
You can test anything that travis is testing locally. For this case, install symengine, set the proper environment variable so sympy tries to use symengine as a backend, run the tests that are failing on travis. The only difference you may encounter is a different OS. Travis is running some version of ubuntu by default. It is always possible that things fail on one OS and not on others. Regardless, we have to make it work on all three main OSes.

**Pull request merged**
