### PR TITLE
Fix the "is_symmetric()" function of SparseMatrix

### PR DESCRIPTION
**Pull request by laituan245**
I found some error in the "is_symmetric()" function of SparseMatrix. For example:

``` python
>>> from sympy import *
>>> aMatrix = SparseMatrix (3,3,{(0,1):3, (1,0):3})
>>> aMatrix.is_symmetric()

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    aMatrix.is_symmetric()
  File "/usr/lib/python2.7/dist-packages/sympy/matrices/sparse.py", line 602, in is_symmetric
    for k in self._smat)
  File "/usr/lib/python2.7/dist-packages/sympy/matrices/sparse.py", line 602, in <genexpr>
    for k in self._smat)
AttributeError: 'int' object has no attribute 'simplify'
>>> 
```

So my solution is that before the return statement, if there is some value in self._smat that has Python number type (long,int,...), I convert it to SymPy number type. I also have added one test of symmetry for SparseMatrix to the file test_matrices.py

### CODE REVIEW

**Comment by smichr** [comment]
The contents of SparseMatrix should have been sympified at instantiation:

```
>>> type(SparseMatrix (3,3,{(0,1):3, (1,0):3L})[0,1])
<type 'int'>
>>> type(Matrix ([1])[0,0])
<class 'sympy.core.numbers.One'>
```

**Comment by smichr** [comment]
If you look through the different instantiation cases there is only one that doesn't sympify its value. You can either split the handle from dict from Dict or else use `self._sympify(value)` in the assignment within that section (any time taken to redundantly sympify is miniscule compared to anything one would do with the matrix, so for simplicity's sake I would suggest the following:

```diff
diff --git a/sympy/matrices/sparse.py b/sympy/matrices/sparse.py
index 4a0c3b2..8a1df45 100644
--- a/sympy/matrices/sparse.py
+++ b/sympy/matrices/sparse.py
@@ -63,7 +63,7 @@ def __init__(self, *args):
                 for key in args[2].keys():
                     v = args[2][key]
                     if v:
-                        self._smat[key] = v
+                        self._smat[key] = self._sympify(v)
             elif is_sequence(args[2]):
                 if len(args[2]) != self.rows*self.cols:
                     raise ValueError(
```

**Comment by smichr** [comment]
I added a NeedsBetterPatch to just indicate to myself that this has been reviewed and needs changes. Are you able to remove the label? If so, please do so when you have made the changes. If not, I will see when you have some recent activity on this. Thanks for fixing some of these corner cases with the matrices.

**Comment by laituan245** [comment]
Thank you for your instructions. It should work now.

**Comment by smichr** [comment]
Thanks for updating. Note, also, that a better name for the commit might be "sympify dict values for SparseMatrix" or something to that effect. Although the 'is_symmetric" attempt raised the error, the underlying problem isn't with that routine, it's with the non-sympification. So perhaps a better test would have been: `assert SparseMatrix(1, 1, {(0, 0): 1})[0, 0] is S.One`. And such a test should have been done in some test function like "test_init_SparseMatrix()" or something like that. But what you have will test the code so I'm not going to block this on that. I'll commit whatever is here tomorrow.

**Comment by laituan245** [comment]
I have changed the name of the commit message, and also I have removed the old test in the function `test_diagonal_symmetrical()` and added your test to the function `test_sparse_matrix()` (I used the name Singleton instead of S because there is a matrix named S defined before that point). 
Thank you for taking your time.

**Comment by smichr** [comment]
I sent a [PR to you](https://github.com/laituan245/sympy/pull/1). Could you look it over and if it's ok to you merge it with this PR?

**Comment by laituan245** [comment]
The code looks cleaner now. I have merged it with this PR. Thank you.

**Comment by smichr** [comment]
OK, it's in.

**Pull request merged**
