### PR TITLE
More MathML presentation printer support

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Relates to #16036 

#### Brief description of what is fixed or changed
Added MathML presentation printer for `re`, `im`, `Abs`, `Determinant`, `Interval`, and `Tuple`

#### Release Notes

* printing
   * Added MathML presentation printer for `re`, `im`, `Abs`, `Determinant`, `Interval`, and `Tuple`

### CODE REVIEW

**Comment by oscargus** [comment]
I've fixed the merge conflicts for this one @smichr if you (or anyone else would like to have a look). I'll wait with fixing the merge conflicts in #16037 as there will be new ones from this anyway.

**Comment by asmeurer** [comment]
Is there a website where you can paste the examples from the tests and see how they render?

**Comment by oscargus** [comment]
I use https://www.tutorialspoint.com/online_mathml_editor.php but I have opened #16066 with a suggestion to simplify that process. (Github doesn't support MathML it seems which is a bit annoying.)

**Comment by oscargus** [comment]
I made a small hack to better see this. For the tests added in this PR, before the PR:
before16065
After:
after16065

(This is rendered by Firefox, so no MathJax. The LaTeX output is obtained through `preview`, hence the unusual font.)

**Comment by smichr** [comment]
shouldn't LaTex im(x) have parentheses around the x like re(x)?

**Comment by smichr** [comment]
And maybe the 2nd example for `im(x)` in your before and after demo should be `im(x) + 1`? I know that probably doesn't impact the PR itself, but you just might want to check what happened.

**Comment by jksuom** [comment]
> shouldn't LaTex im(x) have parentheses around the x like re(x)?

Maybe not necessarily if `operatorname{im}` is used. That will add a little space around `im`.

**Comment by smichr** [comment]
> Maybe not necessarily

It's just the asymmetry of Re vs Im that has me confused/concerned.

**Comment by smichr** [comment]
see, for example, [this page](https://texblog.org/2013/11/27/complex-number-symbols-in-latex/) that puts parens around the argument of Im

**Comment by jksuom** [comment]
I think that it is always safe to add the parentheses. In printed matter they are often omitted if there is no danger of confusion.

**Comment by smichr** [comment]
> they are often omitted

OK. Since this is not different than it was in master, I will leave that as an optional issue to address at another time if anyone has preferences for it.

**Comment by oscargus** [comment]
The idea is to fix that in another PR (now that it was made very clear from the tables). I was also confused by the inconsistency.

I actually have almost every latex string tested in a similar table and there are some more things that can be modified for better appearance. 610 equations and counting...

**Comment by oscargus** [comment]
And you are right about `im(x) + 1`. The test actually says `im(x + 1)` which may or may not make sense to test as such, but since the left hand column is the string representation rather than the actual input that is the consequence. I'll change it to `im(x + I)`.

**Comment by oscargus** [comment]
The im LaTeX printing issue reason is the difference in precedence:
https://github.com/sympy/sympy/blob/7c01430b56a298b4d18ae1f014a44d07256a2e33/sympy/printing/latex.py#L887-L893

I can add that to #16056 if it is not merged before I get around to it (as I said, I have some more things I have found in the LaTeX printer, e.g. printing of Domain which simply prints Domain meaning it renders as a multiplication between those letters rather than a single term, so there will be more related PRs later).

**Comment by oscargus** [comment]
Historically it seems like printing of re has been changed (at least) twice since the 'Func' precedence was introduced for both methods in #10331, most recently in #12652 with the explicit PR name "Printing: Change latex printer to print re(x) with parentheses"

**Comment by jksuom** [comment]
This is not connected with MathML, but as `im` was discussed above, I would like to point out that the "gothic" letters for `\Re` and `\Im` in LaTeX are practically never used in mathematical publications. They come from the original fonts of  TeX (and I think that they are perhaps its only bad choices). Instead of them, `\operatorname{Re}` and `\operatorname{Im}` are used, often redefined.

**Comment by smichr** [comment]
@oscargus , let's commit this and further refinement can be done in a new PR

**Comment by oscargus** [comment]
@jksuom I can try to make it configurable.

**Comment by asmeurer** [comment]
I agree the gothic re and im look terrible. That always bugs me when I'm using the notebook. Even Re and Im capitalized look bad to me, although they are commonly used (maybe I'm too used to SymPy and programming languages in general, but to me, mathematical functions should not be capitalized).

**Pull request merged**
