### PR TITLE
Used _symbol_converter for optimizing code

### PR DESCRIPTION
**Pull request by Ayush-Malik**
#### References to other Issues or PRs
NaN

#### Brief description of what is fixed or changed
Replaced some lines of code in changed file for optimization as there is already a function named ```_symbol_converter``` for task performed by deleted lines

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by Ayush-Malik** [comment]
@oscarbenjamin @sylee957 please help me out , the travis ci is showing an unexpected baseline error

**Comment by Maelstrom6** [comment]
Last line says
> An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

So maybe just try to restart the test on your side by clicking the little circle icon on the right hand side on the list of jobs in travis.org.

**Comment by Maelstrom6** [comment]
Looks like all the other tests need to be restarted as well (since they were canceled when one failed).

**Comment by Ayush-Malik** [comment]
@oscarbenjamin @sylee957 Please review this PR

**Comment by Smit-create** [comment]
This just reduces a few lines of code though I am fine with it. There can be many places where a similar change can be made. Please have a look at them wherever necessary.

**Comment by Ayush-Malik** [comment]
@Smit-create I founded that there is one more instance where ```_symbol_converter``` can be used 
Do I have to look in other files of stats too

**Comment by Ayush-Malik** [comment]
@Smit-create I have applied the suggested changes

**Comment by Ayush-Malik** [comment]
@Smit-create Please review the changes

**Review by Maelstrom6 — COMMENTED** [review]
Please do the same for `JointPSpace` in `joint_rv.py`.

**Comment by Smit-create** [comment]
Please make the changes wherever necessary across all `stats` files

**Comment by Maelstrom6** [comment]
> Please make the changes wherever necessary across all `stats` files

I think those were the only 3 ones. I couldn't find any other on my fork.

**Review by Maelstrom6 — APPROVED** [review]

**Comment by Ayush-Malik** [comment]
> Please make the changes wherever necessary across all `stats` files

I had only applied _symbol_converter wherever required

**Comment by Ayush-Malik** [comment]
@Smit-create @Maelstrom6 Is it good to go for now

**Comment by Maelstrom6** [comment]
Seems good to me. I'm also very new here, so I'm sure I don't have much of a say in these matters though.

**Comment by Ayush-Malik** [comment]
@oscarbenjamin @sylee957 @Smit-create I think this PR is ready to merge

**Comment by oscarbenjamin** [comment]
Looks good

**Comment by oscarbenjamin** [comment]
Thanks

**Pull request merged**
