### PR TITLE
Min max piecewise

### LINKED ISSUE #12639: implement Piecewise rewriting for Min and Max
This was mention in #10158. I am just puttng this here as a separate issue.

```
>> Max(a, b).rewrite(Piecewise)
Piecewise((a, a>b), (b, True))
```

### PR DESCRIPTION
**Pull request by Yathartha22**
Fixes #12639 

ping @smichr @asmeurer

### CODE REVIEW

**Comment by asmeurer** [comment]
This is only correct if the Min or Max have two arguments. You should implement the general case for n arguments.

**Comment by smichr** [comment]
Not sure, but this might help since it writes all but the extremes in terms of 2-arg min/max:

```
def minmaxsort(v):
    """return a sorted list of the elements in v using the
    Min and Max functions.

    Examples
    ========

    >>> minmaxsort(3,2,1)
    [1, 2, 3]
    >>> minmaxsort(1, x, y)
    [Min(1, x, y), Max(Min(1, x), Min(y, Max(1, x))), Max(1, x, y)]
    >>> minmaxsort(1, y, x)
    [Min(1, x, y), Max(Min(1, y), Min(x, Max(1, y))), Max(1, x, y)]
    """
    from sympy import Min, Max
    v = list(v)
    v0 = Min(*v)
    for j in range(len(v)):
        for i in range(len(v) - j - 1):
            w = v[i:i + 2]
            v[i:i + 2] = [Min(*w), Max(*w)]
    v[0] = v0
    return v
```
`piecewise_fold` could flatten the whole thing out. (I don't have time to think a lot about it now but just wanted to let you know about this if it's helpful.)

**Comment by smichr** [comment]
My pwargs branch #13204 has some updates to ITE and Piecewise that may make this easier:

```
def pwmin(*args):
 assert args
 if len(args) == 1:
    return args[0]
 if len(args) == 2:
    a, b = args
    return Piecewise((a, a < b), (b, True))
 else:
    pw = [(i, i < pwmin(*[j for j in args if j != i])) for i in args]
    pw[-1] = pw[-1][0], True
    return Piecewise(*pw)

>>> pwmin(x)
x
>>> pwmin(x,y)
Piecewise((x, x < y), (y, True))
>>> pwmin(x,y,z)
Piecewise((x, ITE(y < z, x < y, x < z)), (y, ITE(x < z, x > y, y < z)), (z, ITE(x < y, x > z, y > z)))
>>> pwmin(a,b,c,d)
Piecewise((a, ITE(((c >= d) | (b < c)) & ((b < d) | (c < d)), a < b, ITE(((b >=
d) | (b > c)) & ((b < d) | (c < d)), a < c, a < d))), (b, ITE(((c >= d) | (a < c
)) & ((a < d) | (c < d)), a > b, ITE(((a >= d) | (a > c)) & ((a < d) | (c < d)),
 b < c, b < d))), (c, ITE(((b >= d) | (a < b)) & ((a < d) | (b < d)), a > c, ITE
(((a >= d) | (a > b)) & ((a < d) | (b < d)), b > c, c < d))), (d, True))
```

**Comment by Yathartha22** [comment]
@smichr should I wait for the PR to be merged and then make the necessary changes?

**Comment by asmeurer** [comment]
It occurs to me that the general case here is actually not so straightforward. I think to implement this properly one needs to generate a [sorting network](https://en.wikipedia.org/wiki/Sorting_network). The maximum and minimum would then be the top and bottom outputs of the sorting network, respectively.  @smichr's code looks inefficient. It's probably equivalent the bubble/insertion sorter network.

Here is [some code](https://github.com/conda/conda/blob/3ef79312b9351a9a82f379039005e1c9091aca0c/conda/logic.py#L303-L348) I've implemented in conda for an even-odd merge sort sorter network (from an old version because I guess they've since removed it).

This is a lot to implement here, so I would be fine with the partial solution you have, but please make it raise NotImplementedError if there are more than two args rather than just giving the wrong answer. Also, without the full implementation, it shouldn't be tagged as fixing #12639.

**Comment by asmeurer** [comment]
Actually, maybe it's simpler since we only care about max and min. For example, take the sorter network for 4 nodes on the [Wikipedia article](https://en.wikipedia.org/wiki/Sorting_network). This reduces to `Max(a, b, c, d)` = `Max(Max(a, c), Max(b, d))` (read right to left from the top-most node, and work your way in to out). This is, with some rearrangement, just what you'd expect from denesting. As a Piecewise, it's `Piecewise((Max(a, c), Max(a, c) > Max(b, d)), (Max(b, d), True))`, and each Piecewise can be recursively rewritten, and then the whole thing denested (maybe this actually is equivalent to @smichr's code).

**Comment by smichr** [comment]
@Yathartha22 I think you can go ahead with what you have here. This has made me think that converging to ITE is not necessary for conditions and can be delayed until folding (and then be returned as a Boolean function rather than ITE).

**Comment by Yathartha22** [comment]
So @smichr as @asmeurer suggested a partial solution will be fine, and for other cases `NotImplementedError`.

**Comment by Yathartha22** [comment]
@asmeurer have a look.

**Comment by smichr** [comment]
Rather than start a new commit, I added the general method here. It's just a binary reduction of the args to a final arg. I don't fold the result so this will hopefully pass when the other Piecewise mods are made.

**Comment by Yathartha22** [comment]
@smichr looks good. Also, I guess the result would be better if it is folded.

**Comment by smichr** [comment]
I don't know if presenting the folded result is really better. Here, for example, is the 4 arg Max as Piecewise:

```
>>> piecewise_fold(r)
Piecewise((a, (a >= d) & (((a >= b) & (a >= d) & (b >= c)) | ((a >= c) & (a >= d) & ~((a >= d) & (b >= c))) | ((b >= c) & (d >= b) & (a < d) & ~((a >= d) & (b >= c))) | ((d >= c) & (a < d) & (b < c) & ~((a >= d) & (b >= c))))), (d, ((a >= b) & (a >= d) & (b >= c)) | ((a >= c) & (a >= d) & ~((a >= d) & (b >= c))) | ((b >= c) & (d >= b) & (a < d) & ~((a >= d) & (b >= c))) | ((d >= c) & (a < d) & (b < c) & ~((a >= d) & (b >= c)))), (b, b >= c), (c, True))
>>> simplify(_)
Piecewise((a, (a >= d) & ((a >= b) | (b < c)) & ((a >= c) | (b >= c) | (d >= c)) & ((a >= c) | (b >= c) | (a < d))), (d, ((a >= b) | (a < d) | (b < c)) & ((a >= c) | (b >= c) | (d >= c)) & ((a >= c) | (b >= c) | (a < d)) & ((a >= d) | (b >= c) | (d >= c)) & ((a >= d) | (d >= b) | (d >= c)) & ((a >= d) | (d >= b) | (b < c))), (b, b >= c), (c, True))
```

**Comment by Yathartha22** [comment]
Sorry for my late reply. I am too not sure, but I guess folding would give a better representation of the result and also would make it better to understand(mostly for larger arguments).
Otherwise, if you think it wouldn't be a great idea, I am okay with the current result.

**Comment by smichr** [comment]
I think the following makes more sense that what I originally did?

```
def _minmax_as_Piecewise(op, *args):
    # helper for Min/Max rewrite as Piecewise
    from sympy.functions.elementary.piecewise import Piecewise
    ec = []
    for i, a in enumerate(args):
        c = []
        for j in range(i + 1, len(args)):
            c.append(Relational(a, args[j], op))
        ec.append((a, And(*c)))
    return Piecewise(*ec)
```

Here is the Piecewise version of `Min(a,b,c,d)`:
```
Piecewise((a, (a <= b) & (a <= c) & (a <= d)), (b, (b <= c) & (b <= d)), (c, c <= d), (d, True))
```

If you agree, could you make the update? If I do it online, it will take two commits (one for the code and one for the tests).

**Comment by Yathartha22** [comment]
@smichr yes this is more convincing. I will make the necessary changes.

**Comment by Yathartha22** [comment]
@smichr I was thinking if the result would be as:

for Max(x,y,z).rewrite(Piecewie)
`Piecewise((x, (x >= y) & (x >= z)), (y, (y >= x) & (y >= z)), (z, (z >= x) & (z >= y)))`
or 
`Piecewise((x, (x >= y) & (x >= z)), (y, (y >= x) & (y >= z)), (z, True)`.

Do you think this would be better result.

**Comment by smichr** [comment]
The alternatives have redundancy. If x is not less than or equal to y then we know his less than x. Preceding tests make  subsequent tests necessarily shorter.

**Comment by Yathartha22** [comment]
Okay, @smichr Thanks for the clarification. I will update the branch.

**Comment by Yathartha22** [comment]
Thanks @smichr

**Pull request merged**
