### PR TITLE
fix is_nthpow_residue(a, n, m) 

### LINKED ISSUE #18234: is_nthpow_residue(a, n, m) does not work
`is_nthpow_residue(36010, 8, 87382)` should return true because it has roots like [40208, 47174], but it returns False. I saw through the code and the implementation it for both prime and composite moduli, but i suspect the for composite moduli part has some error.

### PR DESCRIPTION
**Pull request by abh2k**
Fixes #18234 
 
* ntheory
    * Fixed is_nthpow_residue for numbers that are not powers of a primitive root.

### CODE REVIEW

**Comment by abhinav28071999** [comment]
`    f = totient(m)`
   ` k = f // igcd(f, n)`
    `return pow(a, k, m) == 1`
Only works when gcd(a, m) == 1

**Comment by smichr** [comment]
I don't think release notes are necessary if this is correcting a recent PR. And I will let someone who knows the math better double check this.

**Comment by abhinav28071999** [comment]
@oscarbenjamin @jksuom Could you please check this pr?

**Comment by jksuom** [comment]
Looks good. Maybe release notes could indicate that the fix is for numbers that are not powers of a primitive root.

**Comment by abhinav28071999** [comment]
> Looks good. Maybe release notes could indicate that the fix is for numbers that are not powers of a primitive root.

Done.

**Comment by jksuom** [comment]
Thanks.

**Pull request merged**
