### PR TITLE
irregular block detection and handling

### LINKED ISSUE #14505: Using `BlockMatrix` to concatenate two matrices
Hi there,

My colleague and I are trying to concatenate two matrices together in a `numpy.hstack` manner.   Here is our attempts:

``` python
Python 2.7.14 (default, Sep 27 2017, 12:15:00) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.1.1'
>>> X = sympy.MatrixSymbol('X', 2, 2)
>>> Y = sympy.MatrixSymbol('Y', 2, 1)
>>> X.shape
(2, 2)
>>> Y.shape
(2, 1)
>>> B = sympy.BlockMatrix([X, Y])
>>> B.shape
(4, 2)
>>> B = sympy.BlockMatrix([[X], [Y]])
>>> B.shape
(4, 2)
```

The correct output should have shape `(2, 3)`.  Is concatenating matrices columnwise is impossible using `sympy.BlockMatrix`?

### LINKED ISSUE #16278: BlockMatrix not forming a single matrix in some cases
Consider the following code:
https://github.com/sympy/sympy/blob/3d8300a569cfeed57bd36908240862ca330204b0/sympy/utilities/tests/test_wester.py#L1322-L1343

The comments are incorrect. However, the resulting matrix is
image

so the BlockMatrix consists of several BlockMatrices. Note that A22 is a single matrix, so something (do not) happen when merging in two dimensions.

### PR DESCRIPTION
**Pull request by smichr**
#### References to other Issues or PRs

closes #16278 
closes #14505 

#### Brief description of what is fixed or changed

There is now more checking that well formed block matrix is being formed.
When it is not a size-symmetric block matrix, a ValueError is raised directing user to use alternatives for construction

#### Other comments

I'm not sure whether the default for matrix creation should be evaluate=True or evaluate=False?
I think evaluate=True is the expectation, but unevaluated block matrices were being formed by passing all matrices and then the sub-matrices didn't evaluate.

To maintain backward compatibility, perhaps evaluate could be False if all elements are matrices, else True.

On the other hand, perhaps the following should just be considered a bug in master -- handling the first case but not the second -- and evaluate should default to True:
```python
master:

>>> Matrix([ones(2),ones(2)*2])
Matrix([
[1, 1],
[1, 1],
[2, 2],
[2, 2]])
>>> Matrix([[ones(2),ones(2)*2]])
Matrix([[Matrix([
[1, 1],
[1, 1]]), Matrix([
[2, 2],
[2, 2]])]])
```
#### Release Notes

- matrices
    - matrices comprised of blocks that are not size-symmetry are detected in BlockMatrix and can be handled with Matrix
    - Matrix creation involving matrices expands the matrices unless evaluate is False

### CODE REVIEW

**Comment by smichr** [comment]
- [ ] fix wester test

**Comment by oscarbenjamin** [comment]
The change made to Matrix looks good. That's consistent with Matlab now I think where you can do e.g.:
```matlab
M = [A B; C D]
```
and it is fine if A does not have the same number of columns as B (provided the other dimensions all match).

Also having BlockMatrix properly raise for inconsistent inputs is good and the error messages there should be helpful.

I think that Matrix.irregular looks a bit weird. I can't imagine wanting to use that.

This
```julia
In [22]: Matrix([[ones(2),ones(2)*2]])                                                                                                         
Out[22]: 
⎡⎡1  1⎤  ⎡2  2⎤⎤
⎢⎢    ⎥  ⎢    ⎥⎥
⎣⎣1  1⎦  ⎣2  2⎦⎦
```
is a bug in master and should not be maintained for backward compatibility.

**Comment by smichr** [comment]
> should not be maintained for backward compatibility

Matrix currently is used to hold more than Expr: `laplace_transform` uses it to hold tuples. For display purposes, one might want a Matrix like the following to emphasize the blocks and minimize the visual noise of the 0s
```python
>>> pprint(Matrix([[0,ones(2)],[ones(2),0]]))
⎡        ⎡1  1⎤⎤
⎢  0     ⎢    ⎥⎥
⎢        ⎣1  1⎦⎥
⎢              ⎥
⎢⎡1  1⎤        ⎥
⎢⎢    ⎥    0   ⎥
⎣⎣1  1⎦        ⎦
```

**Comment by smichr** [comment]
@oscargus , can you give an up or down vote for `irregular` matrix construction method? My only positive inclination is that such a matrix might be constructed for demonstration purposes -- but it wouldn't be done very often so perhaps should just be relegated to construction by assignment:
```python
>>> a = zeros(4)
>>> a[:2,:2]=ones(2)  # fills top left 2x2 with ones
...
```
The only thing I don't like about that is having to count...I should be able to look at what I want to create (in an orderly way, of course) and give Matrix the pieces and it should be able to assemble them.

**Comment by oscargus** [comment]
Hard to say. Maybe, if someone suggested to write such a function, it might not have been encouraged, but now that it it exists, I think that there's no harm to include it. I'm sure that one of us three will miss it at one stage if not.

I agree that it makes sense have evaluate=True for all matrix input and I think that the general Matrix construction improvement is great! Thanks!

**Comment by smichr** [comment]
OK, then here goes.

**Pull request merged**
