### PR TITLE
Added functionality to calculate argmax and argmin

### LINKED ISSUE #13432: Argmax/Argmin as operators
The last few days I have been trying to write my equations in Sympy. It works all well up to the point where I want to write an argmax operator defined over a discrete space.

Normally, if argmax is the terminal operation, one can just use solveset or differentiate and find the argument maximizing the value. 

However, in this case argmax is just part of a much larger equation. I have tried subclassing Function and have it evaluate directly which argument maximizes (e.g. max(domain, key=func)). Another thought I had was inversing the function and using the maximum, but unfortunately my function is non-injective.

I am at a loss at how to proceed, as I can't quite follow all the intricaties of the Sympy code. I am desparetely looking for information on how I could contribute.

My thoughts are: allowing the operator to be part of a larger equation, and having it delay evaluation until there is just, say, one free symbol. I'm just wondering why Argmax/Argmin have not yet been implemented; pardon me.

### PR DESCRIPTION
**Pull request by akash9712**
This PR adds functions to calculate argmax and argmin to sympy.calculus.util.py. The functions `argmax` and `argmin` use the helper function `_argMaxMin` to avoid the repetition of code. `_argMaxMin` returns a `FiniteSet` or an `ImageSet` if more than one argmax or argmin exist; else, a single value is returned.
 As of this PR, `_argMaxMin` uses `function_range` to calculate the extrema of the function, and `solveset` to calculate the critical points, and raises error in case either of these cannot be calculated for the given function. 

Examples:
```
>>> from sympy import *
>>> from sympy.calculus.util import argmax, argmin
>>> x = Symbol('x')
>>> argmax(sin(x), x, Interval(0, pi))
pi/2
>>> argmin(sin(x), x, Interval(0, pi))
{0, pi}
>>> argmax((x-1)**2)
EmptySet()
>>> argmin((x-1)**2)
1
```   

Fixes #13432

### CODE REVIEW

**Comment by asmeurer** [comment]
We should add some warnings to the docstring that the current implementation uses derivatives so won't find minimums/maximums at nondifferentiable points.

**Comment by asmeurer** [comment]
Not sure if returning a number when there is only one answer is a good idea. It's hard to deal with functions that return different types in a uniform way. Then again, having to deal with sets even when the argmax is unique could be annoying. I'm not sure how to deal with this.  Perhaps we need some functions that make it easier to go from {a} -> a.

**Comment by akash9712** [comment]
@asmeurer Do you think that a method could be added to the FiniteSet class to return the single element when the finite set is of length one, and the entire set otherwise? For example, if the method is named `elements`, at  the end of the function, instead of adding an `if` clause, we could do the following:
```
return solns.elements()
```

**Comment by akash9712** [comment]
Ping @asmeurer

**Comment by ArifAhmed1995** [comment]
> Not  sure if returning a number when there is only one answer is a good  idea. It's hard to deal with functions that return different types in a  uniform way. Then again, having to deal with sets even when the argmax  is unique could be annoying. I'm not sure how to deal with this.   Perhaps we need some functions that make it easier to go from {a} ->  a.

I feel this could be resolved on the Google Groups page.
@akash9712 Could you make a post detailing the problem and the part which requires decision ?
Here is the link : [https://groups.google.com/forum/#!forum/sympy](https://groups.google.com/forum/#!forum/sympy)

**Comment by czgdp1807** [comment]
https://github.com/sympy/sympy/issues/16520 is tracking the purpose of this PR. So, this can be safely closed.

**Comment by oscarbenjamin** [comment]
To me this PR looks reasonable. There are some code quality issues (e.g. bare except) that would need to be fixed but the main problems are

1. This should always return a set.
2. There are merge conflicts.

I wonder whether more generally this can be implemented as something like:
```
     f = lambda(x, F)
     image = ImageSet(f, domain)
     return solveset(F - image.sup, x, domain)
```
Then in principle as capabilities are added to `ImageSet` and `solveset` the improvements would translate to `argmax` and `argmin` as well. This could also mean that `argmax` and `argmin` would be able to work with non-continuous or complex domains.

Another question to consider is what the API would look like for multivariate functions. Even if that isn't implemented now we should think whether we want to implement something like that in future and make sure that the interface would generalise to that situation. In the same way that sometimes returning a set and sometimes returning a value is bad I think it's also bad to sometimes return a set of values and sometimes a set of tuples.

A function with a name like argmax in the main namespace should be considered carefully. We can only have one of those and there are different things it could do that the version here does not currently do.

**Comment by czgdp1807** [comment]
Closing in favour of https://github.com/sympy/sympy/pull/18550

**Pull request closed without merging**
