### PR TITLE
`limitinf(e, x)` raises error when `e` is periodic.

### LINKED ISSUE #13585: limit(tan(tan(x)), x, -oo) causes recursion error
>>> from sympy import *
    >>> from sympy.abc import x
    >>> limit(tan(tan(x)), x, oo)
    tan(tan(zoo))
    >>> limit(tan(tan(x)), x, -oo)
    Traceback (most recent call last):
      File "<pyshell#3>", line 1, in <module>
                        limit(tan(tan(x)), x, -oo)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\series\limits.py", line 49, in limit
                        return Limit(e, z, z0, dir).doit(deep=False)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\series\limits.py", line 180, in doit
                        r = gruntz(e, z, z0, dir)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\series\gruntz.py", line 650, in gruntz
                        r = limitinf(e.subs(z, -z), z)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\cache.py", line 93, in wrapper
                        retval = cfunc(*args, **kwargs)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\series\gruntz.py", line 428, in limitinf
                        c0, e0 = mrv_leadterm(e, x)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\cache.py", line 93, in wrapper
                        retval = cfunc(*args, **kwargs)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\series\gruntz.py", line 513, in mrv_leadterm
                        series = calculate_series(f, w, logx=logw)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\series\gruntz.py", line 472, in calculate_series
                        if t.simplify():
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\expr.py", line 3096, in simplify
                        return simplify(self, ratio, measure)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\simplify\simplify.py", line 515, in simplify
                        original_expr = expr = signsimp(expr)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\simplify\simplify.py", line 375, in signsimp
                        e = sub_post(sub_pre(expr))
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\simplify\cse_opts.py", line 25, in sub_pre
                        for a in sorted(e.atoms(Add), key=default_sort_key):
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\compatibility.py", line 461, in default_sort_key
                        return item.sort_key(order=order)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\cache.py", line 93, in wrapper
                        retval = cfunc(*args, **kwargs)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\expr.py", line 78, in sort_key
                        args = expr.as_ordered_terms(order=order)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\expr.py", line 944, in as_ordered_terms
                        terms, gens = self.as_terms()
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\expr.py", line 983, in as_terms
                        coeff *= complex(factor)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\expr.py", line 243, in __complex__
                        re, im = result.as_real_imag()
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\power.py", line 962, in as_real_imag
                        return expr.as_real_imag()
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\power.py", line 962, in as_real_imag
                        return expr.as_real_imag()
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\power.py", line 962, in as_real_imag
                        return expr.as_real_imag()
      [Previous line repeated 946 more times]
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\power.py", line 954, in as_real_imag
                        re, im = self.base.as_real_imag(deep=deep)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\functions\elementary\trigonometric.py", line 1061, in as_real_imag
                        re, im = self._as_real_imag(deep=deep, **hints)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\functions\elementary\trigonometric.py", line 61, in _as_real_imag
                        re, im = self.args[0].expand(deep, **hints).as_real_imag()
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\expr.py", line 1717, in as_real_imag
                        if hints.get('ignore') == self:
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\basic.py", line 321, in __eq__
                        other = _sympify(other)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\sympify.py", line 387, in _sympify
                        return sympify(a, strict=True)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\sympify.py", line 256, in sympify
                        raise SympifyError(a)
    RecursionError: maximum recursion depth exceeded

### PR DESCRIPTION
**Pull request by akash9712**
`limitinf(e, x)` in sympy.series.gruntz.py raises a `ValueError` when e is
a periodic function, as the limit for periodic functions does not exist at
infinity.

#### References to other Issues or PRs
TODO before merging this PR:
- [ ] Review and merge #13896 

Fixes #13585

### CODE REVIEW

**Comment by normalhuman** [comment]
This seems like a good idea, but tests are failing. Do you need help with this?

**Comment by akash9712** [comment]
@normalhuman The tests are failing because of an infinite recursion call while calculating periodicity. I have opened a seperate PR for it, as mentioned in the TODO list. The tests should pass once it gets merged (after appropriate changes are made).
I think users call `limit(f, z, z0)` function for calculating the limit, and `limitinf` is called as a subroutine for calculating the limit when `z0 -> oo`. Raising an error at this point fixes issue #13585, and an unevaluated object is returned. 
I checked, and although I am unable to reproduce the error mentioned in the issue on the current master, I think raising an exception at this point gives a clearer message for someone going through the code.

**Comment by asmeurer** [comment]
I'm not so sure periodicity is guaranteed to give a nonzero result for constant functions. So this could give false positives. Here's an example I found

```py
>>> periodicity(sec(x)*cos(x).rewrite(exp), x)
2*pi
```

**Comment by akash9712** [comment]
Thanks, I wasn't aware of this case. Rewriting the expression results in `(exp(I*x)/2 + exp(-I*x)/2)*sec(x)`. Unless SymPy can simplify this expression to 1, I don't know how this can be fixed. (Even if the period of `(exp(I*x)/2 + exp(-I*x)/2)` can be verified to be `2*pi`, `2*pi` will be returned.) 
Also, the recursion error for which I sent this PR no longer appears in the master branch. Should this PR be closed?

**Comment by czgdp1807** [comment]
Closing in reference to https://github.com/sympy/sympy/issues/13585#issuecomment-569612152
Thanks for the contributions. If you feel that this can be re-opened, please do so or just comment below.

**Pull request closed without merging**
