### PR TITLE
Properly handle mathtext exceptions to prevent notebook and qtconsole failures.

### PR DESCRIPTION
**Pull request by moorepants**
Issues this solves:
#9629
#9646
#9799

Some screenshots from IPython 4:
selection_009
selection_007

### CODE REVIEW

**Comment by moorepants** [comment]
@jksuom @bjodah

**Comment by moorepants** [comment]
BTW, to check this you need to have SymPy and matplotlib installed but not LaTeX (and dvi2png).

**Comment by jksuom** [comment]
I have also tested those patches and they seem to work. IPython will interpret a ``None`` returned by a formatter as a missing formatter with no ill effects (see [this](https://github.com/ipython/ipython/blob/master/IPython/core/formatters.py#L184)).

**Comment by moorepants** [comment]
I the first screenshot I share here, I don't have LaTeX installed so it falls back to pretty printing it seems.

**Comment by jksuom** [comment]
That happens with the matrix. Otherwise math fonts are used.

**Comment by moorepants** [comment]
I've tested on Python 2.7 and Python 3.4 with IPython 3 and 4 and it all seems to work in the notebook, but I'm not getting PNGs in the qtconsole:
ipython_011

But this error also happens on master for me, so I need to open a new issue.

**Comment by moorepants** [comment]
Ignore that last bit. I didn't have matplotlib or LaTeX installed in the environment. This seems to work in combinations of Python 2/3 and IPython 3/4.

**Comment by moorepants** [comment]
I'll merge in 24hrs if there are no objections.

**Comment by jksuom** [comment]
It seems that @derDavidT had problems with [this patch](https://github.com/derDavidT/sympy/blob/master/sympy/interactive/printing.py#L91) (https://github.com/sympy/sympy/issues/9799#issuecomment-141472276). Apparently he was using (a new version of) qtconsole. Regardless, I think this is an improvement and should be merged.

**Comment by moorepants** [comment]
I didn't realize you'd spelled out this fix in that thread already. I should have read the thread more carefully.

**Comment by moorepants** [comment]
Ok, thanks. I'm merging this.

**Pull request merged**
