### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ylemkimon**
Added CONTRIBUTING.md, excerpted from README.rst.

GitHub shows a link to it, like CODE_OF_CONDUCT.md, at the top of issues/PR page for first-time contributors and when submitting new issue/PR.

issue
pr
new

### CODE REVIEW

**Comment by asmeurer** [comment]
Doctr failed, but I'm not entirely clear why. Anyway, it should be unrelated.

**Comment by asmeurer** [comment]
+1

**Comment by ylemkimon** [comment]
@asmeurer I'm not sure, but `doctr` seems to fail when documentation is not changed.

**Comment by ylemkimon** [comment]
@asmeurer Restarted a build, but failed again.

**Comment by asmeurer** [comment]
I've made https://github.com/drdoctr/doctr/pull/263 which should provide more debugging info, and pushed a test commit to my fork on top of this branch which installs doctr from that PR.

**Comment by asmeurer** [comment]
I think the error is only reproducible in a pull request, so I'm testing it at https://github.com/sympy/sympy/pull/13469.

**Comment by asmeurer** [comment]
OK, I figured it out. There's a bug in doctr that will unfortunately affect any pull request that doesn't change the Sphinx documentation. I'll try to get a release with a fix out tomorrow.

**Comment by ylemkimon** [comment]
@asmeurer Thank you!

**Comment by asmeurer** [comment]
OK, I just did a doctr release which should fix the issue. Let me know if you still see problems on Sphinx builds with the doctr deploy.

**Comment by ylemkimon** [comment]
@asmeurer Thanks.

---
Restarted `TEST_SPHINX`. Will merge if test passes.

**Pull request merged**
