### PR TITLE
Fix latex printing of ZeroMatrix

### LINKED ISSUE #9420: Null MatrixSymbol printing using init_priting(use_unicode=True) for A*B*C-(A*B)*C produces '\bold0'
using `init_printing(use_unicode=True)` is necessary
```
In [1]: from sympy import *
In [2]: init_printing(use_unicode=True)     # this is necessary
In [3]: A = MatrixSymbol('A', 3, 2)
In [4]: B = MatrixSymbol('B', 2, 4)
In [5]: C = MatrixSymbol('C', 4, 3)
In [6]: A*B*C - (A*B)*C
Out [6]: \bold0
```
It is working fine on command line .Python 3.4.0 [GCC 4.8.2] on linux
This error is produced using IPython Notebook on Linux machine.  Sympy 0.7.6, Python 3.4

### LINKED ISSUE #9661: Zero matrix notebook display
A `ZeroMatrix` object has MathJax-incompatible LaTeX representation:

    >>> sympy.printing.latex(ZeroMatrix(n, n))
    '\\bold{0}'

Which results in the following in IPython notebook:

zeromatrix

A fix should probably replace `bold` with `mathbb`.

### PR DESCRIPTION
**Pull request by akhmerov**
Fixes #9420 and #9661 (duplicate).

### CODE REVIEW

**Comment by akhmerov** [comment]
Test failures are unrelated to my changes.

**Comment by moorepants** [comment]
Can you please add a small unit test for this change?

**Comment by akhmerov** [comment]
Are you sure it's useful? It's like checking if a constant string is equal to a given constant: no logic is involved.

One could check if the outputs of `LatexPrinter` are always legitimate latex, but the check that you propose, for example, wouldn't catch the issue that I'm fixing.

I'm happy to add the test if you say it's useful, but I don't think it helps.

**Comment by moorepants** [comment]
Yes it is useful for checking for regressions. The expected output is now what you've specified and we want to ensure that it stays the same.

**Comment by akhmerov** [comment]
Done.

**Comment by moorepants** [comment]
Thanks @akhmerov. Merging...

**Pull request merged**
