### PR TITLE
Enhance setup.py v2

### PR DESCRIPTION
**Pull request by skirpichev**
This is a second attempt to cleanup setup.py, see #7648.

This was [reverted](https://github.com/sympy/sympy/pull/8361) quickly (i.e. without explanation) by @asmeurer in the last release branch.  But I feel, that this could be useful.  Manually adding modules and tests - broken by design.

So, lets figure out what's wrong.

### CODE REVIEW

**Comment by skirpichev** [comment]
This pr seems to be in a good shape.
Feel free to pick up this work.

**Comment by smichr** [comment]
@asmeurer , is there a reason that these changes were removed? Perhaps it was unintentional. If we can use a more automated way of doing this, it seems like a good idea.

**Comment by asmeurer** [comment]
It was intentional. The changes broke the release process.

**Comment by asmeurer** [comment]
I did explain why here https://github.com/sympy/sympy/commit/89bc536adc91061f487e161992030758dd334b5b

**Comment by smichr** [comment]
OK, thanks for the verification. I will close this again, then.

**Comment by skirpichev** [comment]
> I did explain why here 89bc536

This "explanation" was already mentioned.  It doesn't explain anything.

Unsubscribed.

**Pull request closed without merging**
