### PR TITLE
Fix Travis build config warnings

### LINKED ISSUE #19224: Require the benchmarks to pass on Travis
For some time now the benchmark suite has been running on Travis as an allowed failure. They seem fairly stable and reliable. I haven't noticed any spurious failures from them and I've found them useful when investigating PRs that look like they might have performance implications. 

However the benchmarks are an allowed failure so even if they fail then Travis reports a successful build and the PR can still be merged. This also means that you won't see the benchmarks unless you explicitly go in to Travis to look for them.

In order to pick up on regressions like #19200 I think it would be good to make passing the benchmarks required for a successful Travis build. Then if a PR makes any benchmark fail (currently the threshold is set at a 50% increase in runtime) it will not be mergeable.

If it turns out to be problematic then we can try using a different threshold or make the benchmarks an allowed failure again.

I also think that we should use benchmarks for performance regressions in a similar way to regression tests. If a PR fixes a performance regression then a benchmark should be added if possible that demonstrates the fix.

Similarly if the purpose of any PR is to improve performance then I think we should normally expect relevant benchmarks to be added that demonstrate the improvement in performance before the PR is merged (if existing benchmarks don't already show the improvement).

### PR DESCRIPTION
**Pull request by iammosespaulr**
#### References to other Issues or PRs

Fixes #19224
#### Brief description of what is fixed or changed

Changes have been made to the `travis.yml` file to remove the build config validation warnings,
namely removing deprecated keys, fixing aliases ,and specifying `os` for future builds.
Removed the benchmark tests from `allowed_failures` and renamed it to `Benchmarks`.
Removed separate mpmath install from travis.

Below is a screenshot of the warnings thrown during build time
Screen Shot 2020-04-29 at 4 58 10 PM

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This looks good but can you use a better commit message?

There is some guidance on commit messages here:
https://gist.github.com/stephenparish/9941e89d80e2bc58a153
We don't need to follow those but the principles are good: use the short message to give context and explain what type of change, which part of the codebase etc. Give more context in an extended part of the message if appropriate.

**Comment by iammosespaulr** [comment]
> This looks good but can you use a better commit message?

Gotcha.
btw can I fix #19224 in this PR ?

**Comment by iammosespaulr** [comment]
mpmath Version 1.1.0 was released on December 11, 2018 so I'm removing manual install in travis.
This is for https://github.com/sympy/sympy/pull/15094#issuecomment-412997944 from https://github.com/sympy/sympy/pull/15094

I'm also removing allowed_failures for Benchmarks and renaming it. This is for https://github.com/sympy/sympy/issues/19224

**Comment by iammosespaulr** [comment]
@oscarbenjamin wdys ?

**Comment by oscarbenjamin** [comment]
I want to hear what other people think about requiring the benchmarks to pass.

Your next commit message is an improvement but you should bear in mind the two different contexts in which commits are important: the log and the blame. In the log you have no idea which part of the codebase any commit refers to unless the message clarifies that e.g.:
https://github.com/sympy/sympy/commits/master

**Comment by iammosespaulr** [comment]
> I want to hear what other people think about requiring the benchmarks to pass.
> 
> Your next commit message is an improvement but you should bear in mind the two different contexts in which commits are important: the log and the blame. In the log you have no idea which part of the codebase any commit refers to unless the message clarifies that e.g.:
> https://github.com/sympy/sympy/commits/master

Ahhh yeahh. Alright, if this is gets Okayed, I'll amend the commit messages before the merger. 😃 Thanks!

**Comment by asmeurer** [comment]
As with any Travis related change, we should manually verify that the Travis build is still functioning as expected before merging.

**Comment by iammosespaulr** [comment]
> As with any Travis related change, we should manually verify that the Travis build is still functioning as expected before merging.

Manually as in ?

**Comment by oscarbenjamin** [comment]
We should open a new deliberately failing PR starting from this branch to test that it fails when it should. After this is merged we should open a PR from master to test that it fails as it should. In this case the expected failure is that something slows down so that exactly one of the benchmarks fails

**Comment by iammosespaulr** [comment]
okay @oscarbenjamin I'll clone this branch and make an edit to binomial that will deliberately slow down a lot of operations. I'll reference this PR from that one.

**Comment by iammosespaulr** [comment]
@oscarbenjamin so what's the next step with this one ? any consensus about adding benchmarks as a prerequisite for passing travis tests ?

**Comment by oscarbenjamin** [comment]
I think we're agreed we want the benchmarks. We need to make a script that runs the benchmarks and reports a failure if any are too slow.

**Comment by iammosespaulr** [comment]
@oscarbenjamin this is mergeable right ?

**Comment by oscarbenjamin** [comment]
The benchmarks script still does not properly report a failure for slow benchmarks. We should make that happen and test it for some time before moving it out of allowed failures. So I think this PR should be changed to leave the benchmarks alone and then it can be merged.

You could also make a script that properly fails the benchmarks job when something is too slow either as part of this PR or a follow up.

**Comment by iammosespaulr** [comment]
> The benchmarks script still does not properly report a failure for slow benchmarks. We should make that happen and test it for some time before moving it out of allowed failures. So I think this PR should be changed to leave the benchmarks alone and then it can be merged.

Yeah that's reasonable
 
> You could also make a script that properly fails the benchmarks job when something is too slow either as part of this PR or a follow up.

sure!

**Comment by oscarbenjamin** [comment]
A related change that I think we should make is having the non-slow test jobs fail if any test exceeds 20 seconds. That would pick up on some regressions and also help to keep the list of slow tests up to date.

**Comment by iammosespaulr** [comment]
Okay I've brought back allowed failures and reverted the changes I made to benchmarks.
we can have another PR to do the things you've mentioned above

**Comment by oscarbenjamin** [comment]
I'm still seeing some travis warnings for sudo

**Comment by iammosespaulr** [comment]
@oscarbenjamin so there are no "sudo" commands on this current file, I'm gonna merge from master and fix up the travis tests, we might've added a few 'sudo' commands after this PR

**Comment by iammosespaulr** [comment]
Screen Shot 2020-09-03 at 12 27 48 PM
 😄

**Comment by czgdp1807** [comment]
@oscarbenjamin Any comments on the above update?

**Comment by oscarbenjamin** [comment]
Looks good.

**Pull request merged**
