### PR TITLE
Extend factorial2 to real numbers

### LINKED ISSUE #20253: Complex and real arguments for factorial2
Currently, `factorial2` does not support complex and real-valued arguments:

```julia
In [1]: factorial(1.5)
Out[1]: 1.32934038817914

In [2]: factorial2(1.5)
...
ValueError: argument must be nonnegative integer or negative odd integer
```

This identity from [Wolfram](https://functions.wolfram.com/GammaBetaErf/Factorial2/02/0001/) should work well enough:

image

### PR DESCRIPTION
**Pull request by weakit**
#### References to other Issues or PRs
Closes #20253 

#### Brief description of what is fixed or changed
factorial2 now accepts real numbers

#### Release Notes

* functions
     * factorial2 now accepts real number arguments

### CODE REVIEW

**Comment by weakit** [comment]
Should `factorial._eval_rewrite_as_gamma` also be updated?

**Comment by oscargus** [comment]
Where did you get the expression for the real-valued extension? To me it is not obvious that it automatically should be rewritten using the gamma function. It seems to make more sense to keep the old expressions, at least for integer inputs.

Also, please to not remove tests. And make sure you add tests for the new functionality. In this case, the documentation also should be updated as it currently says integers.

I believe someone else should provide input on if the extension is worthwhile in general.

**Comment by weakit** [comment]
> Where did you get the expression for the real-valued extension?

I got it from [Wolfram](https://functions.wolfram.com/GammaBetaErf/Factorial2/02/0001/).

> To me it is not obvious that it automatically should be rewritten using the gamma function. It seems to make more sense to keep the old expressions, at least for integer inputs.

I feel that it is better to have consistency. An Integer might not return a value, while the same Integer represented as a Float will. I don't think this should happen. I feel like we should get a few more comments on this before making a decision.

> Also, please to not remove tests. 

I had to, as the new extension adds support for all real numbers. Those tests checked for a ValueError on a few real-valued inputs.

> I believe someone else should provide input on if the extension is worthwhile in general.

Sure! Please consider taking a look at my comment [here](https://github.com/sympy/sympy/issues/20253#issuecomment-707836571) for more info on why I'm pushing this.

**Comment by jksuom** [comment]
> An Integer might not return a value, while the same Integer represented as a Float will.

Can you give an example?

**Comment by weakit** [comment]
> Can you give an example?

A negative even integer.

If we keep the current implementation for integers, that wouldn't work. The same integer as a float will work with the extension.

**Comment by jksuom** [comment]
`factorial2` is well defined only for positive integer arguments.

**Comment by weakit** [comment]
> factorial2 is well defined only for positive integer arguments.

Yes, I'm aware. The current implementaion does have support for negative odd integers, tho.

**Comment by jksuom** [comment]
> The current implementaion does have support for negative odd integers

That is because `gamma(x/2 + 1)` is finite for odd negative integers. However, those values are probably needed nowhere.

**Comment by weakit** [comment]
> That is because gamma(x/2 + 1) is finite for odd negative integers. However, those values are probably needed nowhere.

I guess we can restrict input to positive numbers. 

But I think that having a well documented function that accepts all values is better compared to raising an error. 
If someone is using the function, they'd probably know why they're using it, and what the result is supposed to be. 
This extension also gives the same results for all the inputs the current implementation accepts, so I don't think it'll be a big problem for people who are using the function.

**Comment by weakit** [comment]
I re-did everything in #20380

**Pull request closed without merging**
