### PR TITLE
Add support of \left and \right brackets for LaTeX

### LINKED ISSUE #19464: latex parsing of "\left" and "\right"
There seems to be an issue in the latex parser when dealing the "\left" and "\right" tags . Can you reproduce this issue ? 

```
from sympy import *
from sympy.parsing.latex import parse_latex
from sympy.printing import latex

x, y = symbols('x y')
expr = integrate(x**2 * exp(x),x)
expr_latex = latex(expr)
print(expr_latex)  # \left(x^{2} - 2 x + 2\right) \exp \left(x\right)
expr2 = parse_latex(expr_latex)
print(expr2)  # (exp*left(right*x))*left(2*right + x**2 - 2*x)
```

PS : sorry i can get the code to format properly despite using the "insert code" quotes (?)

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

Fixes #19464

#### Brief description of what is fixed or changed

For curly braces `{}`, it can have confusing behavior, and `{x+y}z` may not render up well in LaTeX too, so I've set up the requirement for `\left` and `\right` as must for that case.
But as I haven't found much use of curly braces because of the confusion with set notations, so I wonder if this can be removed.

#### Release Notes

- parsing
  - `parse_latex` supports `\left` and `\right` parenthesis notation.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
After merging #19475 this has conflicts...

**Comment by asmeurer** [comment]
See also https://github.com/sympy/sympy/issues/14005. I don't see why the parser should know about \left and \right. Can they ever affect the mathematical meaning of an expression for something we can parse? I think we should just ignore them.

**Comment by oscarbenjamin** [comment]
This looks good. I guess other tokens can also be skipped but this seems to fix the main issue. I still find that round-tripping doesn't work though because of implicit multiplication:
```
In [6]: from sympy.parsing.latex import parse_latex                                                                                            

In [7]: parse_latex(latex((x+y)*z))                                                                                                            
Out[7]: z(x + y)

In [8]: type(_)                                                                                                                                
Out[8]: z

In [9]: type(_)                                                                                                                                
Out[9]: sympy.core.function.UndefinedFunction
```
+1 to merge if you're done with this.

**Comment by sylee957** [comment]
I don't think that the current LaTeX parser is able to cope with the ambiguous expression like `z \left(x + y\right)` because it can either be parsed as an multiplication or a function.
But at least it looks like it's able to handle more obvious cases like `\left(x + y\right) z` or `z*\left(x + y\right)`
I think that such cases should be handled with user provided options, but it needs some discussion in other topic to see which option would be the best.

**Comment by asmeurer** [comment]
This looks good. There are other symbols that can be ignored that are mentioned in #14005, but they can be handled later. 

It's unfortunate that we have to regenerate the whole parser every time the grammar changes. How long does it take to generate the parser? I wonder if we couldn't generate it at runtime, or at least only generate a hard file for the release. That's for a separate issue, though.

**Pull request merged**
