### PR TITLE
Add .codegen.cfunctions.isinf, support isinf and isnan in lambdify

### LINKED ISSUE #26784: How to cast nan to not-nan in an expression
Hi, I'm new to Sympy and I wonder how to cast null value to a default value in a Sympy expression
For example
```
import sympy as sp
x = sp.symbols("x")
# Return 0 if x is of nan value, and 1 otherwise
exp = sp.Piecewise((0.0, sp.Eq(x, sp.nan)), (1.0, True))
sp.lambdify((x), exp)(x=float('nan'))
Out[28]: 1.0
```
The above expression returns 1.0 instead of 0.0
I found that the problem comes from the expression
```
In [29]: sp.Eq(x, sp.nan)
Out[29]: False
```
It seems that `sp.Eq` does symbolic evaluation on variable `x` instead of waiting for the input from the actual calculation

Maybe I'm using sympy in a wrong way. But would appreciate someone to shed some light on how to do this

Thank you

### PR DESCRIPTION
**Pull request by bjodah**
#### References to other Issues or PRs
Fixes #26784

#### Brief description of what is fixed or changed
Added `isinf`, made `isnan` a subclass of `BooleanFunction`

#### Release Notes

* codegen
  * Added `isinf` in `.codegen.cfunctions`.

### CODE REVIEW

**Comment by asmeurer** [comment]
I guess we should add basic evaluation. It seems like the other codegen functions do that.

**Comment by bjodah** [comment]
Not sure if we want to call `.simplify` in the true-branch of `.is_number` in `isnan.eval`?
```python
>>> omo = Add(oo, -oo, evaluate=False)
>>> omo
-∞ + ∞
>>> omo.simplify()
nan
>>> omo.is_number
True
>>> isnan(omo)  # with a call to simplify in isnan.eval, this would return the expected "true"
False
```
in general `.simplify` is too expensive to call. Do you think it is safe to assume that is always cheap to evaluate simplify when `.is_number` is True?

It is quite common throughout SymPy that subsequent operations on any expression built using `evaluate=False` do not work as expected, so I'm not too worried about this edge case.

**Comment by oscarbenjamin** [comment]
> Do you think it is safe to assume that is always cheap to evaluate simplify when `.is_number` is True?

No, it is not:
```python
In [30]: p = x**100 + x + 1

In [31]: r = RootOf(p, 0)

In [32]: e = p.subs(x, r)

In [33]: e.is_number
Out[33]: True

In [34]: simplify(e) # very slow
```

**Comment by bjodah** [comment]
Of course, thanks.

**Comment by oscarbenjamin** [comment]
Looks good.

**Pull request merged**
