### PR TITLE
Add a Zenodo badge to the README

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by asmeurer** [comment]
Here's what it looks like https://github.com/asmeurer/sympy/tree/doi

**Comment by moorepants** [comment]
+1

**Comment by certik** [comment]
Will it always point to the version 1.0? Or we just update it to the latest version? 

Otherwise +1.

**Comment by asmeurer** [comment]
I have no idea. This is just the badge that it said to use on their site.

**Comment by moorepants** [comment]
I think you will have to update the badge for each version because you will get new DOIs for the future uploads.

**Comment by certik** [comment]
In this case, I think we should rather have a section Releases and put this
there for every release. Alternatively, we can have a section "Latest
Release".

**Comment by bjodah** [comment]
They also provide url/badge for a dynamic "latest" doi. (I find their site unintuitive to browse by I have such a link [here](https://github.com/chemreac/chemreac/))

**Comment by debugger22** [comment]
The URL provided by @bjodah should work as it'll point the latest version.
And the search is amazingly horrible! It doesn't give anything even if you search `sympy: SymPy 1.0` or `SymPy 1.0`.

**Comment by asmeurer** [comment]
OK, I've updated it to use the links given by @bjodah.

**Comment by certik** [comment]
+1 now.

**Pull request merged**
