### PR TITLE
add test of issue 11407

### LINKED ISSUE #11407: Series expansion of the square root gives wrong result
Whenever the constant term on the square root is a sum of 2 or more symbols, the series() function gets the expansion wrong

```
In [1]: from sympy import *

In [2]: a,b,c,x = symbols('a b c x')

In [3]: sqrt(a+b + c*x).series(x,0,1)
Out[3]: 5*sqrt(a + b)/16 + 15*b/(16*sqrt(a + b)) - 5*b**2*sqrt(a + b)/(16*(a**2 + 2*a*b + b**2)) + b**3*sqrt(a + b)/(16*(a**3 + 3*a**2*b + 3*a*b**2 + b**3)) + 15*a/(16*sqrt(a + b)) - 5*a*b*sqrt(a + b)/(8*(a**2 + 2*a*b + b**2)) + 3*a*b**2*sqrt(a + b)/(16*(a**3 + 3*a**2*b + 3*a*b**2 + b**3)) - 5*a**2*sqrt(a + b)/(16*(a**2 + 2*a*b + b**2)) + 3*a**2*b*sqrt(a + b)/(16*(a**3 + 3*a**2*b + 3*a*b**2 + b**3)) + a**3*sqrt(a + b)/(16*(a**3 + 3*a**2*b + 3*a*b**2 + b**3)) + O(x)

In [4]: sqrt(a+b+c + c*x).series(x,0,1)
Out[4]: 5*sqrt(a + b + c)/16 + 15*c/(16*sqrt(a + b + c)) - 5*c**2*sqrt(a + b + c)/(16*(a**2 + 2*a*b + 2*a*c + b**2 + 2*b*c + c**2)) + c**3*sqrt(a + b + c)/(16*(a**3 + 3*a**2*b + 3*a**2*c + 3*a*b**2 + 6*a*b*c + 3*a*c**2 + b**3 + 3*b**2*c + 3*b*c**2 + c**3)) + 15*b/(16*sqrt(a + b + c)) - 5*b*c*sqrt(a + b + c)/(8*(a**2 + 2*a*b + 2*a*c + b**2 + 2*b*c + c**2)) + 3*b*c**2*sqrt(a + b + c)/(16*(a**3 + 3*a**2*b + 3*a**2*c + 3*a*b**2 + 6*a*b*c + 3*a*c**2 + b**3 + 3*b**2*c + 3*b*c**2 + c**3)) - 5*b**2*sqrt(a + b + c)/(16*(a**2 + 2*a*b + 2*a*c + b**2 + 2*b*c + c**2)) + 3*b**2*c*sqrt(a + b + c)/(16*(a**3 + 3*a**2*b + 3*a**2*c + 3*a*b**2 + 6*a*b*c + 3*a*c**2 + b**3 + 3*b**2*c + 3*b*c**2 + c**3)) + b**3*sqrt(a + b + c)/(16*(a**3 + 3*a**2*b + 3*a**2*c + 3*a*b**2 + 6*a*b*c + 3*a*c**2 + b**3 + 3*b**2*c + 3*b*c**2 + c**3)) + 15*a/(16*sqrt(a + b + c)) - 5*a*c*sqrt(a + b + c)/(8*(a**2 + 2*a*b + 2*a*c + b**2 + 2*b*c + c**2)) + 3*a*c**2*sqrt(a + b + c)/(16*(a**3 + 3*a**2*b + 3*a**2*c + 3*a*b**2 + 6*a*b*c + 3*a*c**2 + b**3 + 3*b**2*c + 3*b*c**2 + c**3)) - 5*a*b*sqrt(a + b + c)/(8*(a**2 + 2*a*b + 2*a*c + b**2 + 2*b*c + c**2)) + 3*a*b*c*sqrt(a + b + c)/(8*(a**3 + 3*a**2*b + 3*a**2*c + 3*a*b**2 + 6*a*b*c + 3*a*c**2 + b**3 + 3*b**2*c + 3*b*c**2 + c**3)) + 3*a*b**2*sqrt(a + b + c)/(16*(a**3 + 3*a**2*b + 3*a**2*c + 3*a*b**2 + 6*a*b*c + 3*a*c**2 + b**3 + 3*b**2*c + 3*b*c**2 + c**3)) - 5*a**2*sqrt(a + b + c)/(16*(a**2 + 2*a*b + 2*a*c + b**2 + 2*b*c + c**2)) + 3*a**2*c*sqrt(a + b + c)/(16*(a**3 + 3*a**2*b + 3*a**2*c + 3*a*b**2 + 6*a*b*c + 3*a*c**2 + b**3 + 3*b**2*c + 3*b*c**2 + c**3)) + 3*a**2*b*sqrt(a + b + c)/(16*(a**3 + 3*a**2*b + 3*a**2*c + 3*a*b**2 + 6*a*b*c + 3*a*c**2 + b**3 + 3*b**2*c + 3*b*c**2 + c**3)) + a**3*sqrt(a + b + c)/(16*(a**3 + 3*a**2*b + 3*a**2*c + 3*a*b**2 + 6*a*b*c + 3*a*c**2 + b**3 + 3*b**2*c + 3*b*c**2 + c**3)) + O(x)
```

As long as the constant term is only one, series() gives the correct result

```
In [5]: sqrt(a + c*x).series(x,0,1)
Out[5]: sqrt(a) + O(x)

In [6]: sqrt(a + (a+b)*x).series(x,0,1)
Out[6]: sqrt(a) + O(x)

In [7]: sqrt(a + (a+b+c)*x).series(x,0,1)
Out[7]: sqrt(a) + O(x)

In [8]: sqrt(a + (a+b+c)*x).series(x,0,2)
Out[8]: x*(sqrt(a)/2 + b/(2*sqrt(a)) + c/(2*sqrt(a))) + sqrt(a) + O(x**2)

```

### PR DESCRIPTION
**Pull request by 1124816**
#### References to other Issues or PRs

Fixes #11407 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Review by sachin-4099 — COMMENTED** [review]
Looks good to me.

**Comment by sachin-4099** [comment]
Due to the recent merges, the branch now has conflicts.

**Comment by jksuom** [comment]
@1124816 I merged this with the web editor but that left some invisible trailing whitespace.
Can you do the merge locally on the command line (in the same way but with no whitespace) and then push the result with the -f flag?

**Comment by jksuom** [comment]
Thanks, this looks good now.

**Pull request merged**
