### PR TITLE
Rust codegen

### PR DESCRIPTION
**Pull request by wdv4758h**
As mentioned in https://github.com/sympy/sympy/issues/10554, I have modified the code from C codegen and https://github.com/sympy/sympy/pull/10556 to make a Rust codegen.

It's not perfect yet, but it starts to work.

### CODE REVIEW

**Comment by bollu** [comment]
How's this coming along? I'd like to help and push this along :)

**Comment by wdv4758h** [comment]
@bollu with this PR, SymPy already can generate basic Rust code.

There're still a lot of things can be improved in the future, like :
* generate function in generic version
* find more functions mapping between SymPy and Rust
* make sure every generated code follows the Rust Style Guidelines

As this PR is two weeks ago, I'll rebase PR later to make sure there are no conflicts.

**Comment by moorepants** [comment]
@bollu, you can help here by reviewing the code in this pull request. Download it and try it out on your machine, for example.

**Comment by bollu** [comment]
Ah, thanks! I will do :)

**Comment by tokencolour** [comment]
@wdv4758h , I'd like to add support for generic functions. I'm not much acquainted with Rust. So this might take some time. @bollu Do you mind if I do this?

**Comment by bollu** [comment]
@tokencolour go ahead, I think I'll be reading through the code this week

**Comment by wdv4758h** [comment]
Hi @tokencolour @bollu, do you two have made some progress 😃❓
I have let this PR exist for a few months without making any progress. 😢 
Maybe I should make it merge to master first, then improve it later in another PR❓any opinion❓

**Comment by moorepants** [comment]
> Maybe I should make it merge to master first, then improve it later in another PR:question:

That's often a good strategy.

**Comment by tokencolour** [comment]
I'm sorry, @wdv4758h , I did not really get the time.

**Comment by bollu** [comment]
@wdv4758h - I've been busy with college and now a summer internship, though I'd still love to work on this when I do get the time. I do recommend merging and then improving later as well.

**Comment by wdv4758h** [comment]
I just rebase the PR to master. 

Who should review this PR❓ @moorepants ❓
I need someone to review the code to make this PR merged 😄
Then, me or someone can improve⬆️ it in the future.

**Comment by asmeurer** [comment]
Sorry for the review falling off on this one. I don't know Rust too well, but from my side everything here looks good. Can you fix the merge conflicts with master, and then we can merge it, and go from there.

**Comment by wdv4758h** [comment]
@asmeurer OK, I'll work on this.

**Comment by wdv4758h** [comment]
I've rebased to the master and update some functions according to newer Rust version.

* The rebase doesn't actually change anything, just some little conflict that can't solve automatically.
* The update for newer Rust version just delete some deprecated functions and some comments

I've run the test for things I think related to what this PR changed, but we may want to wait for the overall testing by CI.

**Comment by wdv4758h** [comment]
@asmeurer please check again 😺

**Comment by asmeurer** [comment]
Thanks for the PR. In the future, you can ping people on Gitter if no one is reviewing your PR.

**Pull request merged**
