### PR TITLE
Rebase physics-mechanics-devel branch on master

### PR DESCRIPTION
**Pull request by tjstienstra**
#### Brief description of what is fixed or changed
Rebase physics-mechanics-devel branch on master

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
Your branch here has way more commits than it should. Is it just the last commit, [`e5e5ef1` (#24491)](https://github.com/sympy/sympy/pull/24491/commits/e5e5ef174589d43bbf90527dd9e010358309ed5c), that should be part of this? If so, you can make a branch off master that is just that commit with `git cherry-pick`. It's also possible your own `master` branch has been messed up meaning you will need to `git reset` it back to the upstream master (check if `git show master` has the same SHA1 as shown at https://github.com/sympy/sympy/commits/master).

**Comment by TJStienstra** [comment]
This PR is meant for updating the `physics-mechanics-devel` branch, and not `master`. This would make the diff of #24238 normal. However I do have to get the latest commits from the master, as those will give a merge conflict in #24238, which has to be solved.

**Comment by oscarbenjamin** [comment]
> However I do have to get the latest commits from the master

It would be better to merge master into the physics-mechanics-devel branch or rebase that branch into master.

**Comment by TJStienstra** [comment]
Is there a method to directly rebase the branch. The advantage of rebasing is that the development stays on top.

**Comment by oscarbenjamin** [comment]
The problem is that you don't want to combine the big change (merge or rebase master into physics-mechanics-devel) with the other change which is your two commits that are at the end of the list of commits in this PR currently. This PR is basically asking to merge master plus a couple of extra commits by you into the physics-mechanics-devel branch. The extra commits are impossible to review because they are buried in an enormous diff.

If your intention is to update the physics-mechanics-devel branch to incorporate more recent changes from master then there are two ways to do that:

1. Merge master into the branch - basically that's like this PR except without the final two commits that are not present on master.
2. Rebase physics-mechanics-devel onto master. This is not something that can be done in a PR as it needs a force push.

Merging master into the branch just means opening a PR from master into physics-mechanics-devel.

I don't think there are any branch protection rules applying to the physics-mechanics-devel branch so anyone with permission to merge PRs should also have permission to push (or force push to it).

**However**: rebase and force-push is easy to get wrong. I have seen a lot of contributors mess things up in their own forks and PRs by doing this. No one should be using force-push in the sympy repo even in a feature branch unless they have a **VERY** clear idea how all of this works. The fact that your PR here currently shows such confusion about branch management, merging and rebasing clearly shows that you are **not** experienced enough with these tools to do any force-push to the sympy repo.

While rebasing (instead of merging) is preferred by some people in some contexts there are also others who don't like it and many situations where it should not be used. The main reason for not liking it is that rebasing becomes problematic when you have shared long-lived branches (i.e. precisely like physics-mechanics-devel) because any other branches based off of the long-lived branch will also have to be rebased and force pushed in precisely the right way.

Anyway this is all making me wonder why we have this branch at all. It sounds like you really just want to make PRs to master. What advantage does this branch really offer compared to a long lived PR (which would be a branch in your fork that you can rebase and force-push as much as you like)?

If you want to rebase the physics-mechanics-devel branch then I can do that for you right now. I do think that there needs to be some consideration about what the purpose of this branch is though. If the intention is not to ever actually merge this branch then the history does not matter and there is no reason to prefer rebase over merge.

**Comment by asmeurer** [comment]
I didn't realize this was about the shared branch that we discussed a while back. The shared branch is at https://github.com/sympy/sympy/pull/24234, and doesn't appear to require a rebase (or was this already done? I don't see any force pushes in the timeline). Unless you need updated changes that are only in master, or you have a merge conflict, rebasing/merging with master is unnecessary. Is that the case here? 

I guess the idea with this shared branch (IIRC) was that you wanted it to be a little bit of a testbed before things get merged into master, in case some changes need to be reverted. In that sense, using a model where there are PRs against the branch to review things makes sense to me. But what doesn't make sense is a "rebase PR". If you want to update the branch with master as a PR, you need to do it as a merge commit. Unless that merge commit contains merge conflict resolutions, I don't even see the point in doing that as PR. Just push the merge with master straight up to the shared branch. You should not rebase the branch and push that straight up, as that will be a force push and will break things for anyone else who is using the branch. 

But again, this is unnecessary unless you really need to update with master. Doing it more often than that is just unnecessary churn for the branch. master is updated whenever a PR is merged, which typically happens multiple times per day. It is unnecessary to constantly keep your branch synchronized with it, as the majority of changes there will have no effect on the mechanics stuff.

**Comment by TJStienstra** [comment]
Sorry for the mess and confusion I've caused, which probably increased by not having worked on the development lately due to being busy with an almost finished literature review.

I wanted to keep the development up to date with `master` by frequently rebasing `physics-mechanics-devel`. As I've mentioned earlier this would nicely keep the new development commits on top. However this is unnecessary, because `physics-mechanics-devel` is not meant to be merged ever. And it has the disadvantages that it easily creates a mess and is sensitive to mistakes.

However I've already applied this bad strategy in #24238 resulting in a mess. To it clean up I've created this PR. Because if the development branch is up to date, then the diff should also just be the new commits. Besides that there should also be a merge conflict that needs resolving (7eae1888dda79c4186feb85730cac0a955f5c2ad).

All in all this was not how I planned it. To fix it I'll follow your advise (thanks for teaching me) by creating a PR which merges `master` into `physics-mechanics-devel` in a normal fashion. This is a method I'll also be using in the future (not too frequently). Thank you for your patience.

**Comment by oscarbenjamin** [comment]
I've merged #24515. Now id you want you can rebase #24238 onto physics-mechanics-devel.

Is there a PR somewhere for merging physics-mechanics-devel into master? I know it isn't supposed to be directly merged but a PR would be a useful place to discuss things like this and to see what the ongoing diff is between the two branches.

**Comment by brocksam** [comment]
> Is there a PR somewhere for merging physics-mechanics-devel into master? I know it isn't supposed to be directly merged but a PR would be a useful place to discuss things like this and to see what the ongoing diff is between the two branches.

Thanks @oscarbenjamin. Yes, it's the draft PR #24234.

**Pull request closed without merging**
