### PR TITLE
Abs(1/x) is now evaluated to 1/Abs(x)

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed
Earlier `Abs(2/x)` became `2*Abs(1/x)`, now it becomes `2/Abs(x)`. Similarly `Abs(x/y)` becomes `Abs(x)/Abs(y)`.

I was conservative and only changed it for reciprocals, so higher negative powers stays as is. Not sure what the best setting is here.

The potential drawback with this is the series convergence testing. As far as I can tell, the matching expects `1/expression`, not `1/Abs(expression)`, but I cannot really tell the impact of it or possible changes. Adding a `piecewise_fold` got the tests back to before (I have only run the "relevant" ones, so anything may happen). I will not spend much time on it, if it doesn't work, but this behavior should be preferred in general.

Also improved the printing of an error message slightly.

#### Release Notes

* functions
   * `Abs(1/x)` is evaluated to `1/Abs(x)`.

### CODE REVIEW

**Comment by gschintgen** [comment]
Hi, I've only recently started to contribute some minor improvements, so my opinions are *definitely* not authoritative. Still, here's a minor thought:

Simplifying `Abs(1/x)` is welcome, no discussion about that!

But for symbolic `Abs(x/y)` this may potentially inhibit further simplification, e.g. `simplify(Abs((x**2-1)/(x-1)))` before and after this change. It reminds me of the trouble I had with the automatic splitting of `sqrt(x/y)` into `sqrt(x)/sqrt(y)`. (This splitting impairs ratsimp, radsimp, simplify and is cumbersome to undo.) Of course it all depends on how the `Abs` comes to be and there are surely also valid reasons to consider this change!

**Comment by smichr** [comment]
> may potentially inhibit further simplification

maybe it could be done only if the numerator is 1?

**Comment by oscargus** [comment]
> 
> 
> > may potentially inhibit further simplification
> 
> I _think_ nothing is being split, here. Just `abs(base**-1) -> 1/abs(base)`. I haven't looked at tests yet, though, to see what troubles arose.

@smichr is correct. The only thing that is added is `abs(base**-1)` -> abs(base)**-1`. The reason that `Abs(x/y)` changes is that `Abs` goes through all arguments of a multiplication and see if they are return an `Abs` or not, then it merges all that does into a single `Abs` and multiply with the rest. Now `Abs(Pow(x, -1))` becomes `Pow(Abs(x), -1)` so it doesn't stay in the same `Abs` as `y`.

I haven't looked into the test failures either, except for very briefly, but it seems to be a rather wide variety of failures, from printing to (probably) functions not working properly any more.

**Comment by gschintgen** [comment]
> @smichr is correct. The only thing that is added is `abs(base**-1) -> abs(base)**-1`. The reason that `Abs(x/y)` changes is that ...

Thanks for the explanations on the internals. It was actually the description of the PR that made me curious, so I checked out the code to try it. What prompted me to write my comment was this side effect:

Before this PR:
```
In [1]: simplify(Abs((z**2-1)/(z-1)))
Out[1]: │z + 1│
```
After:
```
In [1]: simplify(Abs((z**2-1)/(z-1)))
Out[1]:
│ 2    │
│z  - 1│
────────
│z - 1│

In [2]: ratsimp(_)
Out[2]:
│ 2    │
│z  - 1│
────────
│z - 1│

In [3]: factor(_)
Out[3]:
│ 2    │
│z  - 1│
────────
│z - 1│
```
I just wanted to highlight this, that's all.

**Comment by oscargus** [comment]
Thanks for hightlighting this! Clearly, this is a risk. I'm wondering if it is possible to handle this in `rat_simp`? I mean, even if one writes `Abs(z**2- 1)/Abs(z-1)` it would be nice if it could be simplified. But clearly, it is a valid concern, do not get me wrong.

In the meanwhile I took a look at the test failures, so here are some comments I started writing before your followup. :-)

```
__________________ sympy.integrals.transforms._simplifyconds ___________________
File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sympy-1.5.dev0-py3.7.egg/sympy/integrals/transforms.py", line 894, in sympy.integrals.transforms._simplifyconds
Failed example:
    simp(S(1) < abs(1/x), x, 1)
Expected:
    False
Got:
    1 < 1/Abs(x)
```
Is probably because there is a hardcoded test for rhs to be an Abs. Meaning that one had to write `abs(1/x)` for it to work, not `1/abs(x)`. With this fixed, I assume that the failing transform will pass.

The failing integral is a consequence of not rewriting `Abs(1/z**2)`, so can be fixed by doing that (hoping that more failures will not show up...).

The meijerint-ones are transforms, so hopefully related to the simplification.

Finally, there are some code generation and pretty printing ones (surprising that there are no LaTeX ones), which are expected.

I will change the code to do this for any negative integer power, so `Abs(Pow(z, -7))` becomes `Pow(Abs(Pow(z, 7)), -1)` (as `Abs(z**7)` remains in that form).

**Comment by smichr** [comment]
I see that `simplify(abs(x)*abs(y)) != abs(x*y)` so we wouldn't be able to get `abs(x)*abs(1/y)` to be anything but `abs(x)/abs(y)`...but it wouldn't have been able to do anything but be unchanged in master. (At least I don't know a method to combine these.)

**Comment by oscargus** [comment]
Seems like ratsimp doesn't play well with `Abs` at all, simplify better:

```
In [24]: ratsimp((x**2-1)/(x-1))
Out[24]: x + 1

In [25]: ratsimp(abs((x**2-1)/(x-1)))
Out[25]: 
│   2         │
│  x       1  │
│───── - ─────│
│x - 1   x - 1│

In [26]: ratsimp(abs(1/x+1/y))
Out[26]: 
│1   1│
│─ + ─│
│y   x│

In [27]: ratsimp(1/x+1/y)
Out[27]: 
x + y
─────
 x⋅y 

In [28]: (abs(1/x+1/y)).simplify()
Out[28]: 
│x + y│
│─────│
│ x⋅y │

In [29]: (abs((x**2-1)/(x-1))).simplify()
Out[29]: │x + 1│
```

Probably that should be solved first. 

Otherwise, I can imagine a step `abssimp` that "un-Abs" stuff to put it into a single Abs as far as possible and then perform `simplify` on the contents. Not clear which step does the "ratsimp" when calling simplify. Or maybe it is that simplify is applied on the arguments of Abs when doing just simplify and therefore it happens (with deep=True, which is the default).

Still, even without this PR one would like the simplify to perform better if one happened to write with multiple `Abs`.

**Comment by smichr** [comment]
In my `abs` branch I have a commit that adds `collect_abs` - not optimized, lightly tested - that solve the `transforms` errors.
```python
    >>> collect_abs(abs(x+1)/abs(x**2-1))
    Abs((x + 1)/(x**2 - 1))
    >>> collect_abs(abs(1/x))
    Abs(1/x)
```

**Comment by oscargus** [comment]
That is (more or less) exactly what I outlined in #17292.

**Comment by smichr** [comment]
> That is (more or less) exactly what I outlined in #17292!

It was written in response to that. If tests pass on my local branch you can cherry pick the commit which has has docstring and tests.

**Comment by smichr** [comment]
I noticed that a decision to re-collect needed to be made else 
```python
>>> abs(1/x+1/y).simplify()
Abs(x + y)/(Abs(x)*Abs(y))
```
instead of 
```python
Abs((x + y)/(x*y))
```
Tests are rerunning on my branch now.

**Comment by smichr** [comment]
This needs some more thought. I suspect we should only split factors that are independent of each other.

**Pull request closed without merging**
