### PR TITLE
pyupgrade examples

### PR DESCRIPTION
**Pull request by nschloe**
```
find examples/ -name "*.py" | xargs pyupgrade --py3-plus
```

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I fixed the release notes block in the OP. Use NO ENTRY in that block rather than deleting it.

The changes here seem reasonable to me.

I note that this changes `%`-style formatting to use `.format` which is not really necessary since `%`-style formatting is still available and not deprecated. It is not always semantically equivalent to switch between these because `.format` is overridable with `__format__`.

**Comment by smichr** [comment]
No harm done with the formatting change, though. I don't use this format but I am more likely to do so after seeing this diff.

**Comment by smichr** [comment]
Looks good to me. Do you want to commit, @oscarbenjamin ?

**Comment by oscarbenjamin** [comment]
Looks good

**Pull request merged**
