### PR TITLE
cse: watch for exponent of 1 on subexpressions

### LINKED ISSUE #11684: Test failure in Travis
```
______________ sympy/simplify/tests/test_cse.py:test_issue_11230 _______________
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/sympy-1.0.1.dev0-py3.5.egg/sympy/simplify/tests/test_cse.py", line 433, in test_issue_11230
    assert not any(i.is_Mul for a in C for i in a.args)
AssertionError
```

I was able to reproduce this locally on a 64-bit system running Ubuntu 16.04.

How to reproduce:

``` bash
conda create -n test_sympy python=3.5 matplotlib numpy scipy pip llvmlite
source activate test_sympy
python
```

``` Python
>>> import os
>>> os.environ['PYTHONHASHSEED'] = '736538842'
>>> import sympy
>>> sympy.test(split='4/4', seed=57601301)
```

### PR DESCRIPTION
**Pull request by smichr**
Fixes #11684 

Although I have work trying to address issue #12070 and others, this can at least fix the Travis error.

### CODE REVIEW

**Comment by smichr** [comment]
ping @isuruf @jksuom

**Comment by jksuom** [comment]
This looks good to me. Maybe multipliers of 1 should be treated similarly.

**Comment by smichr** [comment]
> Maybe multipliers of 1 should be treated similarly.

They resolve on their own so I'm not sure it's necessary to add that extra handling:

```
>>> Mul(Pow(a*b,1,evaluate=False),c)
c*(a*b)
>>> Mul(Mul(a*b,1,evaluate=False),c)
a*b*c
>>> _.args
(a, b, c)
```

But I suppose there might be a day this is different and this would perhaps help avoid future issues if I made that change.

**Comment by jksuom** [comment]
I mean `take = 1` in case of Add.

**Comment by smichr** [comment]
That's what I understood. I went ahead and made that change and will commit if all tests pass.

**Comment by smichr** [comment]
@jksuom - I now see the reason for the confusion. I showed a Mul example. I also tested that

```
>>> x*Mul(2, a + b, evaluate=False)
x*(2*a + 2*b)
```

So the unevaluated factor is distributed.

Thanks for looking this over (and for the hints on the issue page). They helped once I got PyWin running with Py3. (My PyWin 2.7 still doesn't run, though, and I don't know why.)

**Pull request merged**
