### PR TITLE
Fix flake8 in parsing/autolev

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by moorepants** [comment]
I don't think we should mess with these files. The parser generates some of them and some are tests for the parser.

**Comment by oscarbenjamin** [comment]
Oh okay. How are they generated?

**Comment by moorepants** [comment]
From the antlr commands. We have some open PRs about the numpy and math imports, but in general it will add them regardless if they are needed or now. I can't remember how all this works.

**Comment by moorepants** [comment]
It may be done by `python setupy.py antlr`.

**Comment by moorepants** [comment]
Yes, see instructions in this file: https://github.com/sympy/sympy/blob/ab14b02dba5a7e3e4fb1e807fc8a954f1047a1a1/sympy/parsing/latex/LaTeX.g4

I think this goes for both the LaTeX and Autolev parsers.

**Comment by oscarbenjamin** [comment]
@moorepants do you have any idea why the changes in this PR (removing unused imports) would cause the tests to fail? That suggests a problem somewhere

**Comment by moorepants** [comment]
The parser generates those ununsed import in every file and the tests should check whether the expected output is correct. The expected output is to have ununsed imports (currently).

**Pull request closed without merging**
