### PR TITLE
Added atan to rs_series

### LINKED ISSUE #10190: Make atan work with rs_series
See #10189

### PR DESCRIPTION
**Pull request by Krashcan**
Fixes #10190 
Added `atan` to `_convert_func` dict. Added tests for the same.

### CODE REVIEW

**Comment by Krashcan** [comment]
@shivamvats Is this alright and can this be merged?

**Comment by shivamvats** [comment]
@Krashcan Could you please add more test cases. For reference you can check the existing tests.

**Comment by oscargus** [comment]
More tests needed that tests against an expected result and not only other outputs from a similar function.

**Comment by iamabhishek0** [comment]
@czgdp1807 @oscarbenjamin Is this feature still required? Should I start working on it?

**Comment by czgdp1807** [comment]
Closing in favour of https://github.com/sympy/sympy/pull/10320

**Comment by czgdp1807** [comment]
@iamabhishek0 Please feel free to take over https://github.com/sympy/sympy/pull/10320
Thanks.

**Pull request closed without merging**
