### PR TITLE
[WIP] Add examples in docs for control package

### PR DESCRIPTION
**Pull request by namannimmo10**
#### Other comments
TODO:
- [ ] Obtain transfer function from a differential equation under the theory section.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by namannimmo10** [comment]
@moorepants, Sorry for the delay! :sweat_smile: 
Do we need examples from a control theory textbook and then show how that can be solved by the implemented functionality... Or just describe three basic types of interconnection like mentioned [here](https://www.tutorialspoint.com/control_systems/control_systems_block_diagram_algebra.htm) through images and code?

**Comment by moorepants** [comment]
I think the best addition would be textbook examples. The beam package has a page of textbook style examples that show how to exercise the library: https://docs.sympy.org/latest/modules/physics/continuum_mechanics/beam_problems.html

**Comment by namannimmo10** [comment]
Sounds good, I'll add around 3-4 examples.

**Comment by Juanito970** [comment]
Hello, I would like to participate developing some examples of how to obtain a transfer function based on the differential equation.

**Comment by namannimmo10** [comment]
@Juanito970, I think we only need one basic example for now:
Screenshot_2020-10-27-11-59-38-06

But If you are comfortable with control theory, please feel free to work on [sympy.physics.control](https://github.com/sympy/sympy/tree/master/sympy/physics/control). We would highly appreciate it if you find any bugs or add new features to it.

**Comment by czgdp1807** [comment]
ping @namannimmo10 Are you still working on this? If not then we will mark this PR as `Please Take Over`. Please do not close this PR. Thanks for your contributions.
@moorepants Any review comments for this PR? Thank you.

**Comment by moorepants** [comment]
Once it is no longer WIP, I will review it.

**Comment by czgdp1807** [comment]
Okay. Let's wait for @namannimmo10 's status.

**Comment by namannimmo10** [comment]
I have my end semester exams for the next 10 days, so I'll finish this one and the other PR once I'm done with them. I will be free from school. Sorry for the delay.

**Pull request closed without merging**
