### PR TITLE
Matrix expression conversion to index-summation

### PR DESCRIPTION
**Pull request by Upabjojr**
See tests for examples.

### CODE REVIEW

**Comment by asmeurer** [comment]
Can you add a docstring?

**Comment by asmeurer** [comment]
I would add a flag to accept a generator for the dummy symbols, with `numbered_symbols('i', Dummy)` as the default. That will make it easier to test, and will also allow users to get expressions without Dummys if they want.

**Comment by asmeurer** [comment]
I'm not sure about the name. You just happen to get a summation most of the time (and you won't with a single matrix), but the main point is that you're expanding out `expr[i, j]`. 

But I also don't have a better suggestion, so if no one comes up with one it's not the worst name.

**Comment by Upabjojr** [comment]
> (and you won't with a single matrix),

I haven't tested this case.

> but the main point is that you're expanding out expr[i, j].

This makes me think of calling getitem on the matrix expression API, by the way, in the current master:

```python
In [7]: (A*B*C)[i, j]
Out[7]: 
k - 1                                     
______                                    
╲                                         
 ╲               k - 1                    
  ╲               ___                     
   ╲              ╲                       
    ╲              ╲   (B)[k, k]⋅(C)[k, j]
    ╱  (A)[i, k]⋅  ╱                      
   ╱              ╱                       
  ╱               ‾‾‾                     
 ╱               k = 0                    
╱                                         
‾‾‾‾‾‾                                    
k = 0
```
This probably needs some improvements, but apparently some of this API is already there.

> I'm not sure about the name.

What about just using `__getitem__`?

**Comment by asmeurer** [comment]
> What about just using __getitem__?

+1. If you want an unevaluated expression you can create the MatrixElement object manually, but I think most people would expect and want expr[i, j] to just expand.  The only downside is not being able to modify the summation indices as I suggested, but it's not that big of a deal, since the dummy symbols are always bound by the Sum.

**Comment by Upabjojr** [comment]
> The only downside is not being able to modify the summation indices as I suggested, but it's not that big of a deal, since the dummy symbols are always bound by the Sum.

We can keep both APIs, `__getitem__` calling `to_index_summation` for `MatMul`.

**Comment by Upabjojr** [comment]
I guess this is now ready for merging.

**Pull request merged**
