### PR TITLE
Fix placement of free variables in gauss_jordan_solve

### LINKED ISSUE #19815: Wrong answer when using "linsolve" to solve a system of linear equations
result
[test3.zip](https://github.com/sympy/sympy/files/4956306/test3.zip)
I can get the correct answer when I use the function "solve".
However, when I use the "linsolve", it returns a wrong answer to me.
It is a very serious bug and I hope that your team can fix it.
The following part is my code: (I also upload it with the name "test3.zip".)

```
import sympy
sympy.init_printing()

x = sympy.symbols('x0:14')
print(x)
eqs = [x[0]+x[1]-1, x[0]+x[1]+x[2]+x[3]+x[4]+x[5]-2, x[1]+x[6]-1, x[1]+x[4]+x[5]+x[6]+x[7]-1, x[6]+x[8]-1,
       x[10]+x[5]+x[6]+x[7]+x[8]+x[9]-1, x[11]+x[12]-1, x[11]+x[12]+x[13]-2]
s1 = sympy.linsolve(eqs, x)
print("linsolve:")
print(s1)
s2 = sympy.solve(eqs, x)
print("solve:")
print(s2)
```

### PR DESCRIPTION
**Pull request by 1124816**
#### References to other Issues or PRs

Fixes #19815

#### Brief description of what is fixed or changed
Sometimes, gauss_jordan_solve swaps the numbering/placement of the free variables while calculating the rest of the results with the assumption that they will be placed ordinally, making the results incorrect. The free variables are still not numbered/placed ordinally because several tests expect that behavior. However, now the rest of the results reflect that and are correct.

#### Release Notes

* matrices
    * The ordering of parameters in a parametrised solution from `gauss_jordan_solve` was fixed. Previously incorrect results were returned for some underdetermined systems.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Is there a good reason for the ordering of the symbols in the solution from `gauss_jordan_solve` to be different from `linsolve`? 

Otherwise I think we should just fix the tests.

**Comment by sylee957** [comment]
I'm not sure that any changes are visible with tests, but you should better add some tests for this behavior.

**Comment by oscarbenjamin** [comment]
Yes, there should also be a regression test for the case that is fixed (from the issue).

**Comment by 1124816** [comment]
@oscarbenjamin I wouldn't know a good reason for the ordering. I was just following the tests. Originally, I changed gauss-jordan-solve to place the free variables in order. If that would be preferable, I can do that. 

I think the difference between linsolve and gauss-jordan is that linsolve is provided with symbols but gauss-jordan is just given a matrix.

**Comment by oscarbenjamin** [comment]
You can also use `linsolve` with just the matrix:
```julia
In [64]: M = Matrix([[1, 2], [3, 4]])                                                                                                          

In [65]: b = Matrix([1, 2])                                                                                                                    

In [66]: linsolve((M, b))                                                                                                                      
Out[66]: {(0, 1/2)}

In [67]: Maug = Matrix.hstack(M, b)                                                                                                            

In [68]: Maug                                                                                                                                  
Out[68]: 
Matrix([
[1, 2, 1],
[3, 4, 2]])

In [69]: linsolve(Maug)                                                                                                                        
Out[69]: {(0, 1/2)}
```
I think we should change it so that `gauss_jordan_solve` uses the symbols in order like `linsolve`. It's fine to change the tests for that.

**Comment by sylee957** [comment]
I'd use more smaller test example when possible, and try to follow the PEP8 for indentations, commas, ...

**Comment by 1124816** [comment]
I believe that `gauss_jordan_solve` now matches `linsolve`.
I also tried to clean up my test and changed one other test.

**Comment by oscarbenjamin** [comment]
This looks good. Clearly we don't have enough tests for this though if your change has only affected one.

Can you add the example from the original issue as a test?

**Comment by czgdp1807** [comment]
@oscarbenjamin Is this good to go?

**Comment by oscarbenjamin** [comment]
I've edited the OP to add a release note.

This looks good. Thanks!

**Pull request merged**
