### PR TITLE
series/limits : added some test cases for limits of some discontinuous functions with undefined limit as x approaches infinity

### LINKED ISSUE #14276: limit_seq(log(sin(n))) is log(<-1, 1>)

### PR DESCRIPTION
**Pull request by Xenon1019**
#### References to other Issues or PRs
closes #14276 

#### Brief description of what is fixed or changed
added the test cases for the limits in which function is periodically discontinuous for interval of non-zero length as `x` tends to `infinity`. See #23087 for the detailed discussion.

#### Release Notes

* series
  * added test cases for limits where function is discontinuous as `x` tends to `infinity`

### CODE REVIEW

**Comment by Xenon1019** [comment]
> You've added two lines to the .mailmap file but as I understand it there is only one author here:
> 
> ```
> Jatin Upadhyay <64680054+Xenon1019@users.noreply.github.com>
> Xenon1019 <jupadhyay02@gmail.com>
> ```
> 
> What do you want to be recorded as your name and email address in the AUTHORS file?

Any one would work. For some reason github test/authors does not accept any one of those lines. I had to add both of them and only then it passed the test.

**Comment by oscarbenjamin** [comment]
> Any one would work

Only you can answer these questions:

1. What name would you like to be used in the AUTHORS file?
2. What email address would you like to be recorded in the AUTHORS file?

If the answer is "Joe" and "joe@joe.com" then the lines to be added to .mailmap would be:
```
Joe <joe@joe.com> Jatin Upadhyay <64680054+Xenon1019@users.noreply.github.com>
Joe <joe@joe.com> Xenon1019 <jupadhyay02@gmail.com>
```
Those lines associate all commits from `Jatin Upadhyay <64680054+Xenon1019@users.noreply.github.com>` and `Xenon1019 <jupadhyay02@gmail.com>` with a single author `Joe <joe@joe.com>`.

The way that you have currently added these lines to the .mailmap file indicates that the commits are from two different authors.

**Comment by oscarbenjamin** [comment]
The AUTHORS test has failed again. I can tell you exactly what lines to add to the .mailmap file if you answer this question (which I have already asked twice but you have not answered):

What name and email address do you want to be recorded in the AUTHORS file for your contributions?

It does not need to be any of the names or email addresses that the test script asks about. You just need to decide what you want in the AUTHORS file and then it is possible to add lines in the .mailmap file to make it work.

**Comment by anutosh491** [comment]
Looks good if mailmap is fixed . Maybe the tests could be made to something like `assert isinstance(limit(sin(n)**cos(n), n, oo, dir='-'), Limit)`  as we only return the `Limit` object when we return `self`, so this could do otherwise the current tests don't look bad either .

**Comment by Xenon1019** [comment]
Closing due to unable to resolve .mailmap issue due to different authors. Will fix in a new pr

**Pull request closed without merging**
