### PR TITLE
Reduce LaTeX parsing test output

### PR DESCRIPTION
**Pull request by bollwyvl**
#### References to other Issues or PRs
- _Latex parsing tests print messages to the terminal #14084_

#### Brief description of what is fixed or changed
- adds `verbose=False` to `build_parser` and `check_antlr_version`: `setup.py antlr` sets it to `True`
- removes leftover debugging print output in tests

Here's what the output looks like now:
```bash
$ ./bin/test latex
=============================================================================================== test process starts ===============================================================================================
executable:         /home/weg/miniconda3/envs/sympy-dev/bin/python  (3.6.4-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 2.0.8
numpy:              1.13.3
random seed:        57768859
hash randomization: on (PYTHONHASHSEED=1503396959)

sympy/parsing/tests/test_latex.py[5] .....                                                                                                                                                                     [OK]
sympy/printing/tests/test_latex.py[117] .........f........................................................................................f..................                                                  [OK]

========================================================================= tests finished: 120 passed, 2 expected to fail, in 4.90 seconds =========================================================================
```

### CODE REVIEW

**Comment by bollwyvl** [comment]
Over on https://github.com/sympy/sympy/issues/14084#issuecomment-363312050, @gxyd (thanks!) pointed out some more issues related to building/checking in py2, specifically that `FileNotFoundError` isn't available. I've fixed that up, following the lead of [pandas](https://github.com/pandas-dev/pandas/pull/14116) by adding it to `sympy.core.compatibility`, with an `IOError` as a py2 fallback.

**Comment by asmeurer** [comment]
Why wasn't the test failure caught before?

**Comment by bollwyvl** [comment]
Not really sure: that code will only be parsed if the `antlr4` imports, but it appears that case is included in the py27 optional run [on travis](https://travis-ci.org/sympy/sympy/jobs/337847933#L6916).

**Comment by asmeurer** [comment]
The fix here looks fine, but I am worried that we aren't really testing Python 2 properly on Travis if a test failure got through.

**Comment by gxyd** [comment]
> The fix here looks fine, but I am worried that we aren't really testing Python 2 properly on Travis if a test failure got through.

Are we sure it is even tested python 3 as well?

**Comment by gxyd** [comment]
Even though the tests on travis pass. I tried this branch on my system, it is failing:
```
============================================================= test process starts =============================================================
executable:         /usr/bin/python  (2.7.6-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 1.15
numpy:              1.14.0
random seed:        98339257
hash randomization: on (PYTHONHASHSEED=2098537017)

sympy/parsing/tests/test_latex.py[5] ....E                                                                                               [FAIL]
sympy/printing/tests/test_latex.py[115] .......................................................................................................
............                                                                                                                               [OK]

_______________________________________________________________________________________________________________________________________________
___________________________________________ sympy/parsing/tests/test_latex.py:test_antlr_generation ___________________________________________
  File "/home/gxyd/dev/sympy/sympy/parsing/tests/test_latex.py", line 272, in test_antlr_generation
    if not check_antlr_version():
  File "sympy/parsing/latex/_build_latex_antlr.py", line 32, in check_antlr_version
    out = subprocess.check_output(["antlr4"]).decode("utf-8")
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

========================================== tests finished: 119 passed, 1 exceptions, in 3.94 seconds ==========================================
DO *NOT* COMMIT!
```

**Comment by moorepants** [comment]
This needs release notes as per: https://github.com/sympy/sympy/wiki/Writing-Release-Notes and also needs to be merged with master.

**Comment by oscargus** [comment]
I did a bit of a speculative merge, so not really sure if everything is correct.

**Comment by asmeurer** [comment]
I don't think we need both a verbose flag and `debug`, since `debug` only prints when the environment variable is set.

**Comment by oscargus** [comment]
Yes, I assumed it was something like that, but better safe than sorry... Let's see what happens with the tests.

**Comment by asmeurer** [comment]
Is this PR even needed anymore? I remember adding the debug calls to fix the original issue.

**Comment by oscargus** [comment]
No idea. I just fix the merge issues on some seemingly useful PRs to see if they pass etc. But I haven't noticed any excessive amount of output from the tests so probably both this and the issue can be closed.

**Comment by czgdp1807** [comment]
> Is this PR even needed anymore? I remember adding the debug calls to fix the original issue.

Will be closed if even after 24 hours no objections are raised.

**Comment by czgdp1807** [comment]
Closing in reference to, https://github.com/sympy/sympy/issues/14084#issuecomment-569393911

**Pull request closed without merging**
