### PR TITLE
Remove Python 3.3 build from Travis

### PR DESCRIPTION
**Pull request by ylemkimon**
Python 3.3's end-of-life is scheduled at September 29th. ([Status of Python branches](https://docs.python.org/devguide/#status-of-python-branches), [PEP 398](https://www.python.org/dev/peps/pep-0398/#x-end-of-life))

Also, [Google Trends](https://trends.google.com/trends/explore?date=2016-11-02%202017-09-02&q=python%203.3,python%203.4,python%203.5,python%203.6,python%202.7) show that there is almost no interest in Python 3.3 compared to other versions.

I think we can drop 3.3 testing from Travis.

### CODE REVIEW

**Comment by asmeurer** [comment]
I think 3.3 was needed for Ubuntu or something like that. @certik do you know? 

Anyway, should we do a last release to support it first? I don't feel strongly either way. We usually do this, but I'm also keen to cut down the Travis testing time.

**Comment by certik** [comment]
I would just remove it.

**Comment by jksuom** [comment]
It seems that 3.3 is not used by [Ubuntu](https://askubuntu.com/questions/445487/which-ubuntu-version-is-equivalent-to-debian-squeeze) or [Debian](https://wiki.debian.org/Python).

    Debian 9 Stretch contains Python 2.7.13 and 3.5.3
    Debian Jessie contains Python 2.7 (default), 3.4
    Debian Wheezy contains Python 2.7 (default), 3.2
    Debian Squeeze contains Python 2.5, 2.6 (the default), 3.1.

    17.04  zesty      stretch / sid
    16.10  yakkety    stretch / sid 
    16.04  xenial     stretch / sid
    15.10  wily       jessie  / sid
    15.04  vivid      jessie  / sid
    14.10  utopic     jessie  / sid
    14.04  trusty     jessie  / sid
    13.10  saucy      wheezy  / sid
    13.04  raring     wheezy  / sid
    12.10  quantal    wheezy  / sid
    12.04  precise    wheezy  / sid
    11.10  oneiric    wheezy  / sid
    11.04  natty      squeeze / sid
    10.10  maverick   squeeze / sid
    10.04  lucid      squeeze / sid

**Comment by smichr** [comment]
It's in and 3.3 is dropped.

**Pull request merged**
