### PR TITLE
[CI] Added PyPy 3.8 tests

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed

Added pypy 3.8 and used standard 3.10 distribution.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This is marked as WIP but it looks good to me

**Comment by oscargus** [comment]
> This is marked as WIP but it looks good to me

Yes, it was quite easy to get it running it turned out. The question is just if we want to run these tests. An additional hour of test time, but probably make sense. I'll unmark it.

**Comment by oscargus** [comment]
Oh, yeah, merge conflict... Well, quite easy to sort out.

**Comment by oscargus** [comment]
And proper 3.10 is released today(?), so maybe one should just create a new PR with that as well? (Seems as simple as solving the merge conflict in this...)

**Comment by oscargus** [comment]
Rebased and added 3.10 standard release.

**Comment by oscarbenjamin** [comment]
I don't think we need to test both pypy versions so we could just bump that version here (and remove the old one).

**Comment by oscargus** [comment]
OK! Finally got around to update this.

**Comment by oscarbenjamin** [comment]
Looks good

**Pull request merged**
