### PR TITLE
Cleanup docs preview CI job

### PR DESCRIPTION
**Pull request by asmeurer**
#### References to other Issues or PRs

https://github.com/sympy/sympy/issues/23784

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
I don't know if I can actually test this on a PR or if changes are only reflected from `master`.

**Comment by asmeurer** [comment]
I think what I have here will fix it, but I also don't think it will do anything until we merge this, so we'll just have to try it and see.

**Comment by oscarbenjamin** [comment]
Let's see what happens. It would be nice if we can prevent the whole workflow from running rather than just having it cancel itself after it starts. The actions list is so cluttered with these it's hard to see what's actually running once they start to queue.

**Comment by asmeurer** [comment]
I think that's what the `if` will do, but we won't know for sure until it runs.

**Comment by oscarbenjamin** [comment]
https://github.com/sympy/sympy/actions/runs/2683473547
```
[Invalid workflow file: .github/workflows/docs-preview.yml#L5](https://github.com/sympy/sympy/actions/runs/2683473547/workflow)
You have an error in your yaml syntax on line 5
```

**Pull request merged**
