### PR TITLE
subresultants_pg_amv.py contains functions for computing

### PR DESCRIPTION
**Pull request by akritas**
(a) euclidean/sturmian sequences in Q[x] and Z[x],
(b) subresultant polynomial sequences

It does NOT use the function prem which "messes up" the signs
in the euclidean/sturmian sequences. Instead it uses rem and remZ.

### CODE REVIEW

**Comment by asmeurer** [comment]
The Travis tests are failing because of code quality. You can run `./bin/test quality` to see the errors. There are also failures because of PyPy, but those are due to bugs in PyPy, so you can ignore those.

**Comment by asmeurer** [comment]
@mattpap

**Comment by akritas** [comment]
The Travis tests were complaining about the stmt from sympy import *,  
and so I commented it out in the file.  However, now when I import  
separately the module and sympy I cannot run any examples.  It tells  
me "global name 'degree' is not defined"


Quoting Aaron Meurer <notifications@github.com>:

**Comment by akritas** [comment]
everything worked out fine the 4th time.
the only thing I cannot make is define the assert polys.

Quoting Aaron Meurer <notifications@github.com>:

**Comment by asmeurer** [comment]
It wants you to import things manually like `from sympy import (degree, Poly, ...)`

**Comment by akritas** [comment]
I did it; now that I have the whole package working
I will make updates to the docstrings and other minor
tune ups.

will let you know when I am done.

Quoting Aaron Meurer <notifications@github.com>:

**Comment by akritas** [comment]
After today's changes I think I am done!   Let me know if there is  
anything else to be done.

Quoting Aaron Meurer <notifications@github.com>:

**Comment by asmeurer** [comment]
@jksuom do you have any thoughts on this?

**Comment by jksuom** [comment]
I believe the algorithms are useful. Some modifications would be needed: The file should probably be moved to polys. Its name should be changed, preferably to indicate that the algorithms are for polynomials with integer and rational coefficients. Test file should be created. I expect that to be the bulk of the remaining task.

**Comment by akritas** [comment]
Very good points both of them.  Regarding the name of the
file, I agree that it is rather cryptic and hard to decipher.

Maybe subresultants_qq_zz is better.  Any better suggestions?

I will also add some comments for the module as a whole.

As for the test file, it would help me a lot if I could see one.


Quoting Kalevi Suominen <notifications@github.com>:

**Comment by asmeurer** [comment]
Take a look at the files in the various `tests` directories. The basic idea is that you write a file `test_subresultants_qq_zz.py` in the `tests` directory next to your module with functions like

```
def test_some_func():
    assert some_func(input) == output
    assert some_func(input2) == output2
```

where "some_func" is the function you are testing. You can then run the tests with 


```
./bin/test subresultants
```

**Comment by akritas** [comment]
Thank you. Very helpful.  I did it and passed the travis test.
Let me know if it OK.


Quoting Aaron Meurer <notifications@github.com>:

**Comment by jksuom** [comment]
Thank you. That was quick. This looks good to me.

**Comment by jksuom** [comment]
I think this is ready. Thank you for your work.

**Comment by akritas** [comment]
It was a great pleasure and I learned a lot!

Quoting Kalevi Suominen <notifications@github.com>:

**Comment by asmeurer** [comment]
@akritas can you add something to https://github.com/sympy/sympy/wiki/Release-Notes-for-1.0 about this

**Comment by akritas** [comment]
done

**Pull request merged**
