### PR TITLE
Removing deprecated code

### LINKED ISSUE #6550: remove compile_rule
```
In sympy/logic/boolalg.py compile_rule(s) it asks:

    TODO: can this be replaced by sympify ?

It appears that sympify handles the expressions just fine so this can be removed from boolalg and logic's __init__ file. Is there any reason to keep it?
```
Original issue for #6550: http://code.google.com/p/sympy/issues/detail?id=3451
Original author: https://code.google.com/u/117933771799683895267/

### LINKED ISSUE #7057: Deprecate TransformationSet in favor of ImageSet
```
Transformation is too general a name; ImageSet is more descriptive and mathematically precise.  Fortunately this operation was rarely used.
```
Original issue for #7057: http://code.google.com/p/sympy/issues/detail?id=3958
Original author: https://code.google.com/u/109882876523836932473/

### LINKED ISSUE #7141: Deprecate GA_Printer.on()/off() in favor of context manager
```
The use of GA_Printer.on() and GA_Printer.off() is deprecated starting at 0.7.4: GA_Printer is now a context handler. If used in that way, it will clean up after itself even in the presence of exceptions.

Fixed at https://github.com/sympy/sympy/pull/2490 . Since this is a deprecation removal issue, leave this open once the pull request is merged, until we remove the deprecated feature.
```
Original issue for #7141: http://code.google.com/p/sympy/issues/detail?id=4042
Original author: https://code.google.com/u/102137482174297837682/

### LINKED ISSUE #7197: Removal of bool_equal
```
bool_equal will be deprecated from SymPy 0.7.4 onwards.
Instead, bool_map should be used, which returns the mapping and simplified form of the first boolean function, by default (hence, no 'info' parameter).
In case no such mapping exists, False will be returned.
```
Original issue for #7197: http://code.google.com/p/sympy/issues/detail?id=4098
Original author: https://code.google.com/u/106302547764750990775/

### LINKED ISSUE #7460: Remove deprecated Set.subset
The ``subset()`` method defined in ``sympy.core.sets`` checks if one set is subset of another. For eg. ``s1.subset(s2)`` checks if  ``s2`` is a subset of ``s1``. However, it is really asking a question and hence has been renamed as ``is_subset()``. 

With the renaming it makes more sense that the method call ``s1.is_subset(s2)`` is interpreted as check if ``s1`` is a subset of ``s2``.

### LINKED ISSUE #7717: Remove deprecated Basic.iter_basic_args method
use instead `iter(args)`

### PR DESCRIPTION
**Pull request by kshitij10496**
I have removed a few deprecated methods.
As suggested by @moorepants in #10392 , I have tried to remove the deprecated code which was introduced before 0.7.6
- [x] closes #6550
- [x] closes #7057
- [x] closes #7141
- [x] closes #7197
- [x] closes #7460
- [x] closes #7717

### CODE REVIEW

**Comment by kshitij10496** [comment]
I have removed all the code with `deprecated` decorator prior to 0.7.6 release.
 
Ping @moorepants @asmeurer

**Comment by asmeurer** [comment]
+1

**Comment by asmeurer** [comment]
We should also update the changelog with all of this.

**Comment by asmeurer** [comment]
@kshitij10496 can you add a list of things that were removed to the deprecations section of the changelog

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/wiki/Release-Notes-for-1.0

**Comment by kshitij10496** [comment]
@asmeurer Sure.
I will make the necessary changes

**Pull request merged**
