### PR TITLE
diophantine: Selection of integer-valued solutions

### LINKED ISSUE #9106: diophantine returns a non-integer solution
The following code:

    import sympy
    from sympy.solvers.diophantine import diophantine
    sympy.simplify(diophantine('-48 - 2 * m * (3*m - 1) + n * (3*n - 1)',
                               param=sympy.Symbol('t')).pop()[1].replace('t', 1))

returns -71816005847/3 on 0.7.6

### PR DESCRIPTION
**Pull request by jksuom**
Modifications to the treatment of general quadratic equations
of hyperbolic type.
- Include solutions derived from negative fundamental solutions
  of the generalized Pell equation.
- Check candidate solutions for integrality, not for satisfying
  the equation. (They always do.)
- Check all `k` derived candidate solutions for each fundamental
  solution.
- The periods of integral solutions are determined by the `k`-th
  power of the primitive solution of Pell's equation, not the `L`-th
  power.

Closes #9106

### CODE REVIEW

**Comment by asmeurer** [comment]
@thilinarmtb can you review?

**Comment by thilinarmtb** [comment]
Thank you very much @jksuom for fixing the bug !! Good job !

Looks like there is something wrong with the slow tests, I couldn't run them to completion. I did

```python
./bin/test --slow sympy/solvers/tests/test_diophantine.py
```

**Comment by thilinarmtb** [comment]
This is the test that doesn't finish:

https://github.com/jksuom/sympy/blob/dioph/sympy/solvers/tests/test_diophantine.py#L128

**Comment by jksuom** [comment]
I had run the slow test twice before sending the PR and now once again. It succeeds on my
computer but takes a really long time:
sympy dioph$ bin/test --slow diophantine
============================= test process starts ==============================
executable:         /usr/bin/python  (2.7.3-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 1.14
random seed:        66163060
hash randomization: on (PYTHONHASHSEED=1496215351)

sympy/solvers/tests/test_diophantine.py[1] .                                [OK]

================= tests finished: 1 passed, in 2078.44 seconds =================

I suspect that computers with more restricted resources may have trouble completing the test.

This appears to be caused by the second test equation ``5*x**2 - 13*x*y - 4*x + y**2 - 4*y - 15``.
It looks innocent enough with reasonably small coefficients but they grow quickly under the
course of the solution. To start with, we get:

In [26]: D, N = _find_DN(var, coeff)

In [27]: print(D)
149

In [28]: print(N)
5754380

In [29]: solns_pell = diop_DN(D, N)

In [30]: print(solns_pell)
[(803219813, 65802331), (94130508173, 7711471699), (10931334090127, 895529782049), (24883, 2029), (92423657, 7571641), (788657, 64609), (7003, 539), (2990387148047, 244982060639), (2936163008, 240539846), (215752, 17674), (25283512, 2071306), (344093250128, 28189217414)]

So there are 12 fundamental solutions of the generalized Pell equation. After adding the
negative solutions, their number becomes 24. The coefficients are growing but not
impossibly large.

 Each one one of those fundamental solutions generates a family of solutions of the
generalized Pell equation. The others are obtained by "multiplying" with powers of
the solution of Pell's equation  ``x**2 - D*y**2 = 1``;
In [31]: a = diop_DN(D, 1)

In [32]: print(a)
[(25801741449, 2113761020)]

They all correspond to solutions of the original equation *but only few of them are integer-valued*.

To get an idea of how many are integer-valued we can look at the denominators of the
transformation matrix:
In [24]: print(P)
Matrix([[1/1490, 13/1490], [0, 1/149]])

So we may expect that only something of the order of a few parts in 1490 would be integers,
and we have to compute with numbers like
``(25801741449 + 2113761020*sqrt(149))**1490``.

I can see the results on the screen but its buffer is far too small to contain them. So I would
not be surprised if not all small computers could deal with them.

To solve the problem I suggest that this particular equation be omitted from the tests.
It should not weaken the tests in any significant way. This is the output:
sympy dioph$ bin/test --slow diophantine
============================= test process starts ==============================
executable:         /usr/bin/python  (2.7.3-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 1.14
random seed:        34843103
hash randomization: on (PYTHONHASHSEED=217719423)

sympy/solvers/tests/test_diophantine.py[1] .                                [OK]

================= tests finished: 1 passed, in 104.78 seconds ==================

(BTW, the bug was caused by lack of integrality test.)

**Comment by thilinarmtb** [comment]
Ah, I see. I have a very modest laptop :). 

I too suggest that we omit that test. +1 to merge after removing it.

Thanks again for the work !!

**Pull request merged**
