### PR TITLE
Added _op_priority to N-dim arrays

### PR DESCRIPTION
**Pull request by Upabjojr**
To solve some problems arising with _op_priority.

### CODE REVIEW

**Comment by tokencolour** [comment]
@Upabjojr , I get your approach. Thank you.

**Comment by Upabjojr** [comment]
@jksuom what do you think?

This solves the issue of `expr*ndim_array` creating a `Mul` object instead of multiplying elementwise the elements of the array.

**Comment by jksuom** [comment]
MutableNdimArray seems to work as expected:
```
In [11]: a = MutableDenseNDimArray([[2, 3], [4, 5]])

In [12]: a*(1 + x)
Out[12]: [[2*x + 2, 3*x + 3], [4*x + 4, 5*x + 5]]

In [13]: (1 + x)*a
Out[13]: [[2*x + 2, 3*x + 3], [4*x + 4, 5*x + 5]]
```
Am I missing something?

**Comment by Upabjojr** [comment]
Mutable arrays are OK because they do not inherit `Basic`. The problem arises with the immutable arrays, `Expr.__mul__` realizes it's followed by a subclass of `Basic` and tries to determine whether to call `Mul( ... )` or `ImmutableDenseNDimArray.__rmul__` based on the static field `_op_priority`.

If immutable N-dim arrays don't have `_op_priority` defined or it is equal or less than 10.0 (the value for `Expr`), a `Mul` will be constructed.

I set `_op_priority` to 11.0, so it prevails over `Expr`.

It's the same as in the matrix module.

Example of this issue with the current master branch:

```
In [3]: ImmutableDenseNDimArray([[2,3], [4, 5]])
Out[3]: [[2, 3], [4, 5]]

In [4]: m = _

In [5]: ;var x
Out[5]: x

In [6]: (1+x)*m
Out[6]: (x + 1)*[[2, 3], [4, 5]]

In [7]: m*(1+x)
Out[7]: [[2*x + 2, 3*x + 3], [4*x + 4, 5*x + 5]]
```

**Comment by jksuom** [comment]
Yes, my mistake. There is a difference wrt immutable arrays. I just discovered that.

**Comment by jksuom** [comment]
This looks good to me.

**Comment by jksuom** [comment]
I'll merge in 12 hours.

**Pull request merged**
