### PR TITLE
Run sage and pypy tests as allowed failures

### PR DESCRIPTION
**Pull request by isuruf**
When adding tests that are allowed to fail, you need to add them to the matrix and then to allow_failures category as well.

### CODE REVIEW

**Comment by isuruf** [comment]
@certik

**Comment by certik** [comment]
It fails because Sage fails to install?

**Comment by isuruf** [comment]
Yes. I can add a `travis-retry` to retry 3 times, but even then it's not enough sometimes.

**Comment by certik** [comment]
I see. It makes sense to me. @asmeurer, what do you think?

**Comment by isuruf** [comment]
Closed via #10084

**Pull request closed without merging**
