### PR TITLE
Caught and fixed a potential bug in sympy.stats.joint_rv

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References to other Issues or PRs

N/A

#### Brief description of what is fixed or changed 
There was a potential bug with marginal_distribution in sympy.stats.joint_rv. The method wasn't working for joint distributions of three or more variables due to the invalid formats of limit passed to integrate and summation methods.
Discussion for adding tests is needed.

#### Other comments
Code:
```
from sympy import *
from sympy.stats import *
from sympy.stats.joint_rv_types import *
from sympy.stats.joint_rv import *
x = symbols('x', real=True)
t3 = MultivariateT('T', [0, 0, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]], 3)
print(marginal_distribution(t3, t3[0])(x))
```

Output Before Fix:
```
Traceback (most recent call last):
  File "/home/gagandeep/sympy_debug.py", line 236, in <module>
    print(marginal_distribution(t3, t3[0])(x))
  File "/home/gagandeep/sympy/sympy/stats/joint_rv.py", line 236, in marginal_distribution
    return prob_space.marginal_distribution(*indices)
  File "/home/gagandeep/sympy/sympy/stats/joint_rv.py", line 103, in marginal_distribution
    f = Lambda(sym, integrate(self.distribution(*all_syms), limits))
  File "/home/gagandeep/sympy/sympy/integrals/integrals.py", line 1474, in integrate
    integral = Integral(*args, **kwargs)
  File "/home/gagandeep/sympy/sympy/integrals/integrals.py", line 80, in __new__
    obj = AddWithLimits.__new__(cls, function, *symbols, **assumptions)
  File "/home/gagandeep/sympy/sympy/concrete/expr_with_limits.py", line 356, in __new__
    pre = _common_new(cls, function, *symbols, **assumptions)
  File "/home/gagandeep/sympy/sympy/concrete/expr_with_limits.py", line 38, in _common_new
    limits, orientation = _process_limits(*symbols)
  File "/home/gagandeep/sympy/sympy/concrete/expr_with_limits.py", line 123, in _process_limits
    raise ValueError('Invalid limits given: %s' % str(symbols))
ValueError: Invalid limits given: (((T[1], Reals), (T[2], Reals)),)

```
After Fix:
```
Integral(Piecewise(((x**2/polar_lift(x**2/3 + T[2]**2/3 + 1)**(7/2) + T[2]**2/polar_lift(x**2/3 + T[2]**2/3 + 1)**(7/2) + 3/polar_lift(x**2/3 + T[2]**2/3 + 1)**(7/2))/(6*pi), (Abs(arg(x**2/3 + T[2]**2/3 + 1)) < pi) | ((Abs(arg(x**2/3 + T[2]**2/3 + 1)) < pi) & Ne(Abs(arg(x**2/3 + T[2]**2/3 + 1)), pi) & Ne(1/(3*(x**2/3 + T[2]**2/3 + 1)), 0))), (Integral(4*sqrt(3)/(9*pi**2*(x**2/3 + T[1]**2/3 + T[2]**2/3 + 1)**3), (T[1], -oo, oo)), True)), (T[2], -oo, oo))
```

As is visible from the output of the marginal distribution of `MultivariateT` , it is quite complicated and hence most probably cannot be added to `sympy.stats.tests.test_joint_rv`. Can we discuss a good tests that can be added for avoiding this bug in feature.

#### Release Notes

* stats
   * removed bug in `marginal_distribution` for joint distributions of three or more variables

### CODE REVIEW

**Comment by czgdp1807** [comment]
@jksuom @Shekharrajak @Upabjojr Review and discussion requested.

**Comment by smichr** [comment]
> hence most probably cannot be added

It's ok to add it. (Please check my edit of release notes, too.)

**Comment by czgdp1807** [comment]
Thanks for the approval @smichr I am adding the same.
Thanks for the edit too.

**Comment by czgdp1807** [comment]
@smichr I have used `evalf` to avoid the complications. Please took a look and suggest changes, if any.

**Comment by smichr** [comment]
> Please took a look and suggest changes, if any.

That looks like a smart way to handle it. Now we know that code is tested. Did the tests pass locally? Sometimes we have difficulties with straight equality tests that involve floats. If so, you might consider `assert integral.subs(x,1).round(1) == 0.2` or similar.

**Comment by czgdp1807** [comment]
@smichr Tests were passing locally on `python` and `python3`. I was thinking of something similar like the one you suggested. Thanks for the suggestion. I will make the necessary changes.

**Comment by czgdp1807** [comment]
@smichr I have made the changes. If there are any more changes to make, then please suggest.

**Comment by czgdp1807** [comment]
@smichr All checks have passed. Any more changes needed?

**Comment by smichr** [comment]
Looks good.

**Comment by Upabjojr** [comment]
Thanks for your contribution.

**Pull request merged**
