### PR TITLE
 Add scaling to LaTeX output

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed
As discussed in #17244, adding scaling to the LaTeX output is also useful.
image

#### Release Notes

* interactive
    * The LaTeX output can be scaled by using `scale` in `init_printing`.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
LGTM

**Comment by oscarbenjamin** [comment]
From testing this out I found that: I kept trying to use "scale" rather than "scaling". Maybe that's fine but it would be nice if the error was picked by init_printing rather than the subsequent attempt to print something:
```
In [2]: init_printing(scale=2.0)

In [3]: x
---------------------------------------------------------------------------
TypeError
```
Also it doesn't seem to have any effect in the jupyter notebook. I don't know if that should be mentioned or is fixable.

**Comment by oscargus** [comment]
You are probably correct that scale is better. I'll update it.

If it is not working in Jupyter notebook it is either because it does it's own rendering (is forecolor working) or because it somehow rescales the png (which seems unlikely).

**Comment by sylee957** [comment]
I guess it may only work with people with `dvi` installed. My jupyter seems like using mathjax renderer and this option is not passed to other renderers.

**Comment by oscargus** [comment]
Correct. This is only when SymPy does the rendering.

**Comment by oscargus** [comment]
The thing is that it is not possible to send any settings to backend. Two or three things are sent: the result in plain text (or pretty printed), a png, and the latex string. (Where the png depends on the settings.) The only thing SymPy can control when it comes to color or size is the png.

**Pull request merged**
