### PR TITLE
Cleanups to the CircleCI docs build

### LINKED ISSUE #23697: Improving error diagnostics on Sphinx build
Originally from https://github.com/sympy/sympy/discussions/23680

A few things can be improved in the Sphinx error output.

- Make sure the warnings output on CI and in Docker is in color (see https://github.com/sympy/sympy/pull/23695 for an attempt to fix this on Circle).
- We can use the `-w` flag to sphinx-build, which writes the warnings to a file in addition to stderr, to make it so that the warnings are printed at the end of the build instead of just in the log.

### PR DESCRIPTION
**Pull request by asmeurer**
#### References to other Issues or PRs

Fixes https://github.com/sympy/sympy/issues/23697

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
Having this change is good regardless, but it seems I was wrong and this doesn't actually make it print the error messages in color. I don't know how to fix that. But we can use the idea from https://github.com/sympy/sympy/issues/23697 to extract the error messages and print them separately.

**Comment by asmeurer** [comment]
I can't figure out how to make the output colored in the Makefile. If anyone knows about Makefile syntax, please see https://stackoverflow.com/questions/72779459/printing-the-contents-of-a-file-including-ansi-colors-from-a-makefile.

**Comment by bertiewooster** [comment]
@asmeurer thanks--it's very helpful to have the Sphinx error in **test / sphinx (pull_request)**!

As a side note, it surprises me that CircleCI builds pages even when it fails--**Click here to see a preview of the documentation.** links to pages even for this failing build. I guess it's good, so you can see the pages that did build correctly.

**Comment by bertiewooster** [comment]
I confirmed that these changes also provide the error message when the docs are built locally using Docker:

```
(.venv) username@machine sympy % cd doc
(.venv) username@machine doc % docker build -f Dockerfile.htmldoc -t sympy_htmldoc .
(.venv) username@machine doc % docker run --rm -v /Users/username/Projects/sympy:/sympy sympy_htmldoc
...
make[1]: *** [Makefile:67: _html] Error 1
The docs build failed with the following errors:
/sympy/doc/src/index.rst:61: WARNING: toctree contains reference to nonexisting document 'doesntexist'
make[1]: *** [Makefile:75: printwarnings] Error 1
make: *** [Makefile:58: html] Error 2
```

Great job @asmeurer, this will be really helpful for anyone building the docs locally with Docker, or on GitHub via a pull request. Recommend merging.

If someone builds the docs locally without using Docker, would be an added bonus to have them check that this reports the Sphinx error with that setup.

**Comment by asmeurer** [comment]
Actually, thinking about it, the problem might be that sphinx itself is saving the file with color sequences on my machine, because it detects that it's a terminal, but not on CI. So it's not really a problem with the Makefile.

**Comment by asmeurer** [comment]
OK, I got the colors working. The output is a little messed up on Circle, but I don't think it's a huge deal with the errors printed at the end.

**Pull request merged**
