### PR TITLE
.github/workflows/ci-sage.yml: Avoid doctest failure in archlinux

### PR DESCRIPTION
**Pull request by mkoeppe**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by mkoeppe** [comment]
> Is there a trac ticket for the tachyon failure?

Yes, https://trac.sagemath.org/ticket/23712 (I included this link in the PR)

**Comment by oscarbenjamin** [comment]
@mkoeppe we're now seeing the Archlinux build time out after 6 hrs (it used to take about 3 hrs like the Ubuntu job):
https://github.com/sympy/sympy/actions/runs/2745803722

**Comment by oscarbenjamin** [comment]
Recently I have several times seen the archlinux `logging_backend` failure:
```
glp_free: memory allocation error
Error detected in file env/alloc.c at line 70
------------------------------------------------------------------------
/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/cysignals/signals.cpython-310-x86_64-linux-gnu.so(+0x6fc6)[0x7f4d7460bfc6]
/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/cysignals/signals.cpython-310-x86_64-linux-gnu.so(+0x72ab)[0x7f4d7460c2ab]
/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/cysignals/signals.cpython-310-x86_64-linux-gnu.so(+0x9eea)[0x7f4d7460eeea]
/usr/lib/libc.so.6(+0x3e8e0)[0x7f4d753da8e0]
/usr/lib/libc.so.6(+0x8e36c)[0x7f4d7542a36c]
/usr/lib/libc.so.6(raise+0x18)[0x7f4d753da838]
/usr/lib/libc.so.6(abort+0xcf)[0x7f4d753c4535]
/usr/lib/libglpk.so.40(+0x6026)[0x7f4d02b54026]
/usr/lib/libglpk.so.40(+0x59936)[0x7f4d02ba7936]
/usr/lib/libglpk.so.40(+0x1a71d)[0x7f4d02b6871d]
/usr/lib/libglpk.so.40(glp_delete_prob+0x1f)[0x7f4d02b6b72f]
/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/sage/numerical/backends/glpk_backend.cpython-310-x86_64-linux-gnu.so(+0x31b36)[0x7f4d58a26b36]
/usr/lib/libpython3.10.so.1.0(+0x14e5c7)[0x7f4d756f65c7]
/usr/lib/libpython3.10.so.1.0(+0x13b184)[0x7f4d756e3184]
/usr/lib/libpython3.10.so.1.0(+0x153712)[0x7f4d756fb712]
/usr/lib/libpython3.10.so.1.0(+0x161777)[0x7f4d75709777]
/usr/lib/libpython3.10.so.1.0(+0x13b240)[0x7f4d756e3240]
/usr/lib/libpython3.10.so.1.0(+0x1b9091)[0x7f4d75761091]
/usr/lib/libpython3.10.so.1.0(+0x130482)[0x7f4d756d8482]
/usr/lib/libpython3.10.so.1.0(+0x1f009b)[0x7f4d7579809b]
/usr/lib/libpython3.10.so.1.0(PyType_GenericAlloc+0x325)[0x7f4d756d6675]
/usr/lib/libpython3.10.so.1.0(_PyObject_MakeTpCall+0x1b0)[0x7f4d756f6cf0]
/usr/lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x5164)[0x7f4d756f1ba4]
/usr/lib/libpython3.10.so.1.0(_PyObject_FastCallDictTstate+0xdb)[0x7f4d756f60db]
/usr/lib/libpython3.10.so.1.0(+0x15dbfd)[0x7f4d75705bfd]
/usr/lib/libpython3.10.so.1.0(_PyObject_MakeTpCall+0x283)[0x7f4d756f6dc3]
/usr/lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x5164)[0x7f4d756f1ba4]
/usr/lib/libpython3.10.so.1.0(+0x160f36)[0x7f4d75708f36]
/usr/lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x4ebf)[0x7f4d756f18ff]
/usr/lib/libpython3.10.so.1.0(_PyFunction_Vectorcall+0x79)[0x7f4d756fd9c9]
/usr/lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x3095)[0x7f4d756efad5]
/usr/lib/libpython3.10.so.1.0(_PyFunction_Vectorcall+0x79)[0x7f4d756fd9c9]
/usr/lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x77a)[0x7f4d756ed1ba]
/usr/lib/libpython3.10.so.1.0(_PyFunction_Vectorcall+0x79)[0x7f4d756fd9c9]
/usr/lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x77a)[0x7f4d756ed1ba]
/usr/lib/libpython3.10.so.1.0(+0x161132)[0x7f4d75709132]
/usr/lib/libpython3.10.so.1.0(+0x240cc7)[0x7f4d757e8cc7]
/usr/lib/libpython3.10.so.1.0(+0x217628)[0x7f4d757bf628]
/usr/lib/libc.so.6(+0x8c54d)[0x7f4d7542854d]
/usr/lib/libc.so.6(clone+0x44)[0x7f4d754ad874]
------------------------------------------------------------------------
Attaching gdb to process id 194119.
Cannot find gdb installed
GDB is not installed.
Install gdb for enhanced tracebacks.
------------------------------------------------------------------------
Unhandled SIGABRT: An abort() occurred.
This probably occurred because a *compiled* module has a bug
in it and is not properly wrapped with sig_on(), sig_off().
Python will now terminate.
------------------------------------------------------------------------
sage -t --random-seed=0 src/sage/numerical/backends/logging_backend.py
    Killed due to abort```

**Comment by oscarbenjamin** [comment]
> we're now seeing the Archlinux build time out after 6 hrs

This happened a few times but I haven't seen this happen since. Not sure if something got fixed somewhere.

**Comment by mkoeppe** [comment]
> Recently I have several times seen the archlinux `logging_backend` failure:
> 
> ```
> glp_free: memory allocation error
> Error detected in file env/alloc.c at line 70
> ------------------------------------------------------------------------
> [...]
> ------------------------------------------------------------------------
> sage -t --random-seed=0 src/sage/numerical/backends/logging_backend.py
>     Killed due to abort```
> ```

Thanks, I've opened https://trac.sagemath.org/ticket/34256 for it. I've seen this error before

**Comment by mkoeppe** [comment]
> > we're now seeing the Archlinux build time out after 6 hrs
> 
> This happened a few times but I haven't seen this happen since. Not sure if something got fixed somewhere.

We see such sporadic hangs on random platforms from time to time on GH Actions, unfortunately it is not reproducible. If you restart the GH Actions workflow, it will likely just succeed within the normal time

**Pull request merged**
