### PR TITLE
Add checking if modules is an empty collection in lambdify

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Fixes #17737
Closes #20507 (couldn't continue there since it was built on master)

#### Release Notes

* utilities
  * Fixed issue with incorrect lamdifying behaviour of `Mod` when `modules = []`.

### CODE REVIEW

**Comment by oscargus** [comment]
Hmm, that test passes locally...

**Comment by bjodah** [comment]
Superficially this looks like the wrong fix. `modules=[]` should mean exactly that: no modules, `modules=None` should mean "default", and due to historic(?) reasons that means "import numpy if you can", which turns mod into a function call (so that operator precedence does not need to enter the picture). I think the precedence weights are either wrong for mod, or we are missing a `self.parenthesize(...)` call in a `_print_XXX` method...

**Comment by oscargus** [comment]
OK! Just thought that it seemed to fix it, so worth rebasing. But clearly something went wrong...

I'll close this in favor of your fix! (One should maybe fix the actual Python printing as well, maybe by simply adding brackets around a modulo-operation.)

**Comment by bjodah** [comment]
It's a bit unclear to me, exactly what are you referring to with "actual Python printing"? Are there other printers than subclasses of `CodePrinter` that also fail to parentesize unary minus and modulo operator correctly? (I wouldn't be surprised if that's the case, I just haven't found any)

**Comment by oscargus** [comment]
Basically, test `pycode(-Mod(x, y))` explicitly (the `python` printer uses `Mod` so that is not an issue, the `ccode` printer sprinkles brackets, most other printers do not seem to support it).

**Comment by bjodah** [comment]
Ah, I see. I added some tests in d11dd0c . Was it something like that, that you had in mind?

**Comment by oscargus** [comment]
Yes, exactly! Thanks!

**Pull request closed without merging**
