### PR TITLE
Refactor the release script

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

See #20320

#### Brief description of what is fixed or changed

Refactor of the release script into separate scripts along with a new master script to run the separate stages.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by czgdp1807** [comment]
Hi @oscarbenjamin . On the Google Groups you informed that you were busy. Can we mark it stalled so that it doesn't go out of notice? Or if you are going to get back in near future then let us know. Thank you.

**Comment by oscarbenjamin** [comment]
I only pushed this yesterday so it's not stalled yet! The reason I've been busy is because I've been working on this.

**Comment by oscarbenjamin** [comment]
Looks like the tests failed because of an unrelated timeout in
```
sympy/solvers/ode/tests/test_ode.py:test_issue_20192
```
I've seen this come up intermittently on other PRs.

**Comment by asmeurer** [comment]
Please update the release README file with instructions on how to do the release and how to run the individual scripts and so on.

**Comment by asmeurer** [comment]
Does this still use a Docker image to do the full release? 

Also, I can give you access to the sympy/ Docker organization on DockerHub if you want to be able to push updated images. I've pushed the release image there, though it isn't strictly necessary as you can just build it manually, but it's obviously faster to just pull it.

**Comment by asmeurer** [comment]
I guess this still uses rever? Are you wanting to remove rever entirely?

**Comment by oscarbenjamin** [comment]
This work is not yet finished but I think that it is good enough to get the release candidate out.

This does not use the docker image but it could be made to use a docker image when finished. For now it is setup to work in a fresh install of Ubuntu 20.04 after running the `release/aptinstall.sh` script (I've been working on this in a VM) so it should be possible to build a docker image on that. I should add that information to the README but I also think that I will make further changes so I'd rather get it all together first.

This doesn't use rever at all. What is currently done by the release script is done by running `release/releasecheck.py` in this PR (I think the only missing part is running the full test suite). Mostly this PR just refactors code from the rever script into separate scripts and then adds a script that runs them all. I can't get rever to work right now and I know that the release script in its current form has made the release process much more time consuming for me than it would be with the rearrangement here.

It would be possible to build a simpler rever script that runs those same scripts in order to get the benefits of rever along with the other improvements here. After the discussion in #20320 I still don't see what the benefits of rever are though.

**Comment by asmeurer** [comment]
I'm fine with removing rever. I think it's worth building your VM as a Docker image. The existing image should be pretty close to what is needed for a release. It may just be a question of rebuilding it so that it has the newest Python version and so on. 

That way, the whole release process is something that is easy to redo from scratch, especially for someone else who doesn't have your specific setup. That also puts us closer to being able to just run the whole thing on CI, which I think we should aim for.

**Pull request merged**
