### PR TITLE
Have added 4 new functions to subresultants_qq_zz

### PR DESCRIPTION
**Pull request by akritas**
to compute subresultant prs by determinant evaluations:
1. bezout(p, q, x) computes the bezout matrix to be used (instead of
   sylvester1 and sylvester2) in the two functions below due to smaller dimensions;
2. subresultants_bezout(p, q, x);
3. modified_subresultants_bezout(p, q, x);
4. process_bezout_output(poly_seq, x);

At the same time I added three new test functions in
test_subresultants_qq_zz for the cases 1, 2 and 3 above.

### CODE REVIEW

**Comment by jksuom** [comment]
As the number of functions grow if would be useful to have an overview and comparison of the main functions. It should be added to the Sphinx documentation eventually, but some text could exist even now in the module docstring at the top of the subresultant file.

**Comment by akritas** [comment]
You are right! will do.

Quoting Kalevi Suominen <notifications@github.com>:

**Comment by akritas** [comment]
Just added the comments in subresulltants_qq_zz.py added it but when I  
tried to commit strange things were happening.

Hope it goes through OK

Quoting Kalevi Suominen <notifications@github.com>:

**Comment by jksuom** [comment]
It appears that the module docstring cannot be divided into two parts. There should be only one pair of triple parentheses at the top of the file.

**Comment by akritas** [comment]
is there something wrong with travis tests??  they last forever !

**Comment by jksuom** [comment]
Only a limited number of tests on one repository is allowed to run and there is a huge backlog. But this will probably finish in a few hours. (Each new commit creates a new build job that is added to the queue.)

**Comment by jksuom** [comment]
I think this is ready for merging. Thank you!

There remains the task of adding these functions to the Sphinx documentation, but that need not be part of this PR. It is a rather mechanical process that does not presuppose deeper familiarity with the inner workings of this module.

**Comment by akritas** [comment]
Am I supposed to do it or is it done automatically??

Quoting Kalevi Suominen <notifications@github.com>:

**Comment by jksuom** [comment]
It is not done automatically. You can do it if you are interested in studying the workings of Sphinx. (The existing doc files could serve as examples.) But you are not necessarily expected to do it. Someone else could do that as well.

**Comment by akritas** [comment]
Let me run the whole thing by my students.
Would like to see how understandable the comments are, etc.

Will let you know in a couple of weeks.

Quoting Kalevi Suominen <notifications@github.com>:

**Pull request merged**
