### PR TITLE
Extended support for matrix power to non-diagonalizable matrices

### PR DESCRIPTION
**Pull request by Upabjojr**
Use the Jordan form instead of the diagonalizable form to perform power of matrix (except for integer power, which is a trivial case).

This also enables symbolic exponents, through the usage of some combinatorics.

The Jordan form always exists, while the diagonalized form may not exist.

### CODE REVIEW

**Comment by jksuom** [comment]
Looks good. Computation of powers of Jordan cells is very nice.
There could be a test case with a 3x3 matrix (having a single Jordan cell).
The TypeError could indicate that it concerns the exponent.
+1 if tests pass.

**Comment by jksuom** [comment]
Merging in 24 hours if there are no objections.

**Comment by jksuom** [comment]
Thank you, @Upabjojr . Nice work.

**Comment by Upabjojr** [comment]
You're welcome.

**Pull request merged**
