### PR TITLE
Dense N-dim arrays now support slicing

### PR DESCRIPTION
**Pull request by Upabjojr**
Added slicing support for dense N-dim arrays (still missing it in sparse ones).

_sympy.diffgeom_ doesn't use list of lists of lists anymore: they got replaced by N-dim arrays.

### CODE REVIEW

**Comment by Upabjojr** [comment]
@certik hi, this is an integration to the N-dim arrays to support slicing indexing (i.e. _a[1:3, 3]_).

I made some edits to use that in _sympy.diffgeom_. The output of some functions are slightly different now, but I think it's not a problem.

**Comment by Upabjojr** [comment]
@Krastanov for your information.

**Comment by jksuom** [comment]
Looks good to me. +1

**Comment by jksuom** [comment]
Merging in 24 hours if there are no new comments.

**Comment by certik** [comment]
That looks good to me as well.

**Pull request merged**
