### PR TITLE
Added a power function for polynomials.

### LINKED ISSUE #19076: modular exponentiation of poly
Introduce modular exponentiation in poly similar to `pow(base, exp, mod)`

### PR DESCRIPTION
**Pull request by danieljbruce**
#### References to other Issues or PRs

Fixes #19076 

#### Brief description of what is fixed or changed
Added a function to allow modular exponentiation in better runtime and test cases too

#### Other comments
None

#### Release Notes

* functions
  * Added a function to allow efficient modular exponentiation of polynomials.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I'm not sure if there is already a way to do this or not or whether it is needed.

If this is needed then it shouldn't be using the functions from the math module as they are primarily for 64-bit floating point whereas the polys module is generally for exact calculations.

If exp is expected to be an Integer then that should be checked.

**Comment by oscarbenjamin** [comment]
The Poly class already has a pow method so it would make more sense fo this to be included there rather than as a separate function.

**Comment by sylee957** [comment]
I think that the stuff should better be implemented first in `densearith`.

**Comment by oscarbenjamin** [comment]
@danieljbruce thank you for sending this PR but I don't think that this is the right approach so I'm going to close this.

Feel free to open a new PR for this. It would be better to open an issue to discuss the best approach first though. The first thing to establish is whether or not there already is a way to solve this in the current code. After that the question is what is the best way to implement it. This PR is not appropriate because it does not fit with the current design and implementation of the polys module.

**Comment by danieljbruce** [comment]
This PR was intended to fix issue #19076. Should I discuss the approach there? What is `densearith`? I have noted your comments `oscarbenjamin`.

**Comment by danieljbruce** [comment]
> This PR was intended to fix issue #19076. Should I discuss the approach there? What is `densearith` @sylee957 ? I have noted your comments @oscarbenjamin .

I see. `densearith` is a filename.

**Comment by oscarbenjamin** [comment]
Yes, it would be better to discuss at #19076. I expect that @abhinav28071999 will have a better idea than me what is actually needed.

**Pull request closed without merging**
