### PR TITLE
fixes periodicity computation of trigonometric functions

### LINKED ISSUE #18736: periodicity computation of trigonometric functions
The period of a sine or cosine function is computed correctly except when the argument is expressed as a product of pi with a frequency portion plus a constant phase portion. The use of the `periodicity` function at `sympy.calculus.util` doesn't fix it. Expanding the argument with `expand_mul` can help but not always (see last code example), although, at least in this case, `periodicity` does work.

```python
from sympy import *
x = Symbol('x')

e0 = cos(S.Pi*x/4)
print(e0.period(), '-> OK')

e1 = cos(S.Pi*x/4 + 10)
print(e1.period(), '-> OK')

e2 = cos(S.Pi*x/4 + S.Pi/4)
print(e2.period(), '-> OK')

e3 = cos(S.Pi*(x/4 + 1/4))
try:
    e3.period()
except NotImplementedError as e:
    print(e, '-> Not OK')

from sympy.calculus.util import periodicity
print(periodicity(e3, x), '-> Not OK')

e4 = expand_mul(e3)
print(e4.period(), '-> OK')

e5 = expand_mul(cos(S.Pi*(x/4 + 1)))
try:
    e5.period()
except AttributeError as e:
    print(e)
```

### PR DESCRIPTION
**Pull request by mohitacecode**
#### References to other Issues or PRs

Fixes #18736 #18747 
#### Brief description of what is fixed or changed
Now,
```
>>> e3 = cos(S.Pi*(x/4 + 1/4))
>>> e3.period()
8
>>> periodicity(exp(pi*I*(x/4+S.Half/2)), x)
8


```

#### Release Notes

* functions
  * periodicity of trigonometric functions with a non-zero phase component is now calculated.
* calculus
  * periodicity of exponential functions with a non-zero phase component is now calculated.

### CODE REVIEW

**Comment by czgdp1807** [comment]
@mohitacecode Please add regression test for the fix.

**Review by certik — DISMISSED** [review]
As @czgdp1807 suggested, please add tests that fail in master, and now are fixed with this patch.

Thanks for your contribution!

**Comment by mohitacecode** [comment]
I have added the test @certik @czgdp1807

**Comment by smichr** [comment]
With this,
```diff
diff --git a/sympy/calculus/util.py b/sympy/calculus/util.py
index 8404edb..55decbe 100644
--- a/sympy/calculus/util.py
+++ b/sympy/calculus/util.py
@@ -3,6 +3,7 @@
 from sympy.core.basic import Basic
 from sympy.core.compatibility import iterable
 from sympy.core.expr import AtomicExpr, Expr
+from sympy.core.function import expand_mul
 from sympy.core.numbers import _sympifyit, oo
 from sympy.core.sympify import _sympify
 from sympy.functions.elementary.miscellaneous import Min, Max
@@ -481,6 +482,7 @@ def _check(orig_f, period):
             # checked below

     if isinstance(f, exp):
+        f = f.func(expand_mul(f.args[0]))
         if im(f) != 0:
             period_real = periodicity(re(f), symbol)
             period_imag = periodicity(im(f), symbol)
```
the `exp` issue is fixed, too:
```python
>>> periodicity(exp(pi*I*(x/4+S.Half/2)), x)
8
```

**Comment by smichr** [comment]
A test for the other issue would make this complete.

**Comment by mohitacecode** [comment]
> A test for the other issue would make this complete.

Sorry It really just went of my mind to add test.

I have added it now. Thanks :)

**Comment by smichr** [comment]
Looks good, thanks.

**Comment by mohitacecode** [comment]
Thanks @smichr :)

**Pull request merged**
