### PR TITLE
#10388 solved

### PR DESCRIPTION
**Pull request by dhruvkhattar**

### CODE REVIEW

**Comment by leosartaj** [comment]
I see there are already open PR's for #10388. 
Duplicate of #10389 #10394

**Comment by leosartaj** [comment]
You should set the description of PR to something more informative. Please read
https://github.com/sympy/sympy/wiki/Introduction-to-contributing
https://github.com/sympy/sympy/wiki/Development-workflow

**Comment by pakhandibaba** [comment]
Hey, I am a newbie, can you tell me why did the code fail the test cases.

**Comment by gxyd** [comment]
Closing this, since the issue has been handled by PR #10478 .

**Pull request closed without merging**
