### PR TITLE
Fixed bug with wrong output sign in real Gaunt coefficients

### LINKED ISSUE #25321: The signs of real Gaunt coefficients are not consistent with the given documentation
The documentation of real_gaunt (https://docs.sympy.org/latest/modules/physics/wigner.html) says the definition of real spherical harmonics follows

Some Properties of the Coupling Coefficients of Real Spherical Harmonics and Their Relation to Gaunt Coefficients’, H. H. H. Homeier and E. O. Steinborn J. Mol. Struct., Volume 368, pp. 31-37 (1996)

where the real spherical harmonics Z(l,m) is defined as

Z(l,m)   
= sqrt(2) * Re Y(l, |m|)   if m > 0
= Y(l,0)                          if m = 0
= sqrt(2) * Im Y(l, |m|)   if m < 0

Following this definition, 

Z(1, -1) = sqrt(2) * (-sqrt(3/2/pi) / 2) * sin(theta) * sin(phi)
Z(1,  1) = sqrt(2) * (-sqrt(3/2/pi) / 2) * sin(theta) * cos(phi)
Z(2, -2) = sqrt(2) * ( sqrt(15/2/pi) / 4) * [sin(theta)]^2 * sin(2*phi)

and the real Gaunt coeffcient of the above three is calculated to be sqrt(15/pi) / 10. However, the result from sympy has an extra minus sign:

```
>>> from sympy.physics.wigner import real_gaunt
>>> real_gaunt(1,1,2,-1,1,-2)
-sqrt(15)/(10*sqrt(pi))
>>>
```

Similar problem happens to many real Gaunt coefficients with 2 negative m's.  Is there a bug or do I misunderstand something?

### PR DESCRIPTION
**Pull request by strawpants**
#### References to other Issues or PRs
Fixes #25321

#### Brief description of what is fixed or changed
When using sympy to validate real Gaunt coefficients with `real_gaunt(...)`, I've experienced incorrect signs similar to what is reported here in this issue https://github.com/sympy/sympy/issues/25321.

This fix uses the modifications of the code of @Sunethan provided in #25321.

#### Other comments
 The documentation is corrected and updated to use the Greek letter mu to better reflect the notation used in Homeier & Steinborn 1996, and reflects the updated code.

#### Release Notes

* physics.wigner
  * Fixed a bug with inconsistent signs of real Gaunt coefficients, occurring for certain combination of orders

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
You'll need to add a line like
```
Roelof Rietbroek <r.rietbroek@utwente.nl>
```
in the .mailmap file for the authors check.

If this is fixing a bug can you add a test for the case that is fixed somewhere in `sympy/physics/tests`?

**Comment by oscarbenjamin** [comment]
I don't know anything about Gaunt coefficients but I'm happy to merge this if it is finished.

Are you intending to add more tests?

**Comment by strawpants** [comment]
thanks, I think it's fine for now, the test covers a wide enough range of cases to have a decent confidence in its correctness.

**Comment by oscarbenjamin** [comment]
Okay, looks good. Thanks!

**Pull request merged**
