### PR TITLE
[WIP] make And and Or args canonical

### PR DESCRIPTION
**Pull request by smichr**
fixes #5463 

In addition, arrange the default presentation of 2 And args so
they look like a compound expression if possible, otherwise put
the 'x' on the outside as in And(x < y, z < x).

Also, for And  and Or args, simplify combinations like
`And(x<=a,x>=a)` with `Eq(x, a)`

TODO
- [x] add inline comments and rename variables as needed
- [x] replace `Or(x < big, x > small)` with `True` -- not sure about this one. I do it in the 2-arg And case because that is the case that gets a special presentation; since this is an "all pairs" test, perhaps it's best not to do this at instantiation.
- [ ] fix theano issue

### CODE REVIEW

**Comment by jksuom** [comment]
>  replace Or(x < big, x > small) with True -- not sure about this one.

I believe that inequalities involving comparisons (other than ``!=``) implicitly imply that arguments are real.

**Comment by smichr** [comment]
> implicitly imply that arguments are real

The point I was not sure about is whether to run through pertinent combinations, doing the tests to find out if this simplification applies.

**Comment by smichr** [comment]
@jksuom , the overlapping args case for And and Or is implemented for any number of args now.

**Comment by jksuom** [comment]
My comment was probably somewhat cryptic. What I meant was that ``Or(x < 2, x > 1)`` can only be satisfied by real values of ``x``. So perhaps it should be ``x.is_real`` instead of ``True``.

**Comment by smichr** [comment]
> What I meant was that Or(x < 2, x > 1) can only be satisfied by real values of x. So perhaps it should be x.is_real instead of True.

oh...that makes sense. So I think it should just be `And(-oo < x, x < oo)` I'll try it and see if anything breaks. I already special case things like `Or(x < 1, Ne(x, 1))` to give `Ne(x, 1)` rather than `x < 1` since if `x` were `I` the `Ne(x, 1)` would be True.

**Comment by smichr** [comment]
OK...now that this is working we should decide if this should be part of instantiation or only part of `_eval_simplify` for relational.  Thoughts, anyone?

**Comment by jksuom** [comment]
I think inequalities should usually be rewritten into this form. Maybe the rewrite could be prevented by a keyword, though that would probably be necessary only for debugging.

(The integral transforms with ``periodic_argument``, ``exp_polar``` and ``polar_lift`` should also be simplified, but that is another matter...)

**Comment by smichr** [comment]
> inequalities should usually be rewritten into this form

Do you think the simplifications like `Or(2*x < 2, x > 3)` should be simplified (via new modifications) to `Or(x < 1, x > 3)`? Basically, any linear relational will be simplified now -- so it shouldn't be too expensive -- and redundant conditions are simplified as in `And(x < 3, x < 4) -> x < 3`.

BTW, are Theano tests still failing and to be ignored?

**Comment by jksuom** [comment]
> Do you think the simplifications like Or(2*x < 2, x > 3) should be simplified (via new modifications) to Or(x < 1, x > 3)?

I would be nice to have the results as readable as possible, but I'm a little unsure about how far one can go with automatic simplification. Though linear inequalities such as ``2*x < 2`` certainly could be simplified.

**Comment by jksuom** [comment]
I tried to fix the theano test by replacing ``xt > 0`` with ``0 < xt`` but without avail. It appears that theano ``and_`` will again turn the inequality around.
```
In [9]: s = theano.tensor.and_(0 < xt, xt < 2)

In [10]: theano.printing.debugprint(s, file='str')
Out[10]: "Elemwise{and_,no_inplace} [@A] ''   \n |Elemwise{gt,no_inplace} [@B] ''   \n | |x [@C]\n | |TensorConstant{0} [@D]\n |Elemwise{lt,no_inplace} [@E] ''   \n   |x [@C]\n   |TensorConstant{2} [@F]\n"
```
So it seems that we should have a way of preventing the rewrite in SymPy for this kind of tests.

**Comment by smichr** [comment]
stale

**Pull request closed without merging**
