### PR TITLE
Fix test failure on Windows (floating point equality)

### PR DESCRIPTION
**Pull request by bjodah**
This supersedes gh-12755

### CODE REVIEW

**Comment by moorepants** [comment]
As a side note, I've always though we should have at least some tests run on appveyor. I've had to fix a number of codegen, autowrap bugs for windows and if we ran tests for them it'd help keep them from breaking.

**Comment by asmeurer** [comment]
But in my experience appveyor can be even slower than Travis.

**Comment by moorepants** [comment]
We only have to run a very small subset of tests on appveyor, not the whole suite, as the vast majority of sympy code is portable with little concern.

**Comment by bjodah** [comment]
Yes, I would say let's run 80% of the tests on appveyor (`--veryfastcheck`)—should only take a couple of minutes―and then all the codegen tests. (that will be a considerable effort to setup though).

**Comment by asmeurer** [comment]
I mean even for the startup time. It could have changed, but I remember the queue for AppVeyor is even worse than Travis. 

That isn't to say I'm against it, but we should be aware that it could be an issue.

**Comment by asmeurer** [comment]
I wonder if there's a reason that tan is defined that way.

**Review by asmeurer — APPROVED** [review]

**Comment by bjodah** [comment]
I don't know, do you remember @catchmrbharath ?
I'm thinking it's to save typing (sin and cos functions are quite lengthy)

About appveyor: if we have a private CI server (to avoid waiting time) that runs the quick 80% of the tests first, and upon success spawns linux/mac/windows builds on circleci/travis/appveyor I think waiting times would be considerably reduced. But there is always an overhead with additional infrastructure (handling login credentials, uptime etc.).

**Comment by catchmrbharath** [comment]
The interval math logic would take care of how to calculate intervals for tan, because it is defined for sin and cos and the operator '/'. Defining how tan works on intervals separately would involve some logic, which I avoided at that point.

**Comment by bjodah** [comment]
Thanks @catchmrbharath

**Pull request merged**
