### PR TITLE
geometry: Closest pair of points in 2-d plane using sweepline techniques

### PR DESCRIPTION
**Pull request by arafatkatze**
Calculating the closest pair of points in a given set of points in a 2-d plane using sweepline technique.
The upside of this is that the points are calculated _much_ faster because of **O(n log n)** algorithm. The downside is that the only geometry entity supported is  **point** on 2-d plane, otherwise the speed improvement is compromised on adding segments and polygon.

For 10000 points the time taken is **0.04 - 0.08** seconds whereas the brute force
takes around **30-34** seconds for the same.
For a _million points_ it calculates the result in **5-6** seconds on a 4gb ram, i3 processor.

Inside, [test.zip](https://github.com/sympy/sympy/files/73265/test.zip) I  have attached a files  **test.py** and **test2.py** which includes many randomly generated **test cases** that involve both sweep-line techniques as well as a brute force method(for **verification**).
It  shows the time taken by both the techniques to do time comparison as well as **verifies**  the tests easily using **brute force** method, you can also see a **plot** of the closest pairs on **running those files.**

**Note** 
If- Divide and conquer technique is used that the same objective could be accomplished for **n-d points** but that seems an overkill,especially since currently only 2-dimensional and 3-dimensional points are supported in sympy.

Sources 
https://en.wikipedia.org/wiki/Sweep_line_algorithm
http://www.cs.mcgill.ca/~cs251/ClosestPair/ClosestPairPS.html

It would be great if some could look into this and offer me some pointers for improvement.

### CODE REVIEW

**Comment by smichr** [comment]
Looks interesting...I'll be looking this over this week.

**Comment by Arafatk** [comment]
@smichr  Thanks. I  have also thought about a really cool  farthest pair of points algorithms that uses the upper and lower portions of the convex hull and rotating callipers technique.I would work on that if this gets done properly.

**Comment by smichr** [comment]
What is the answer for pts that form the vertices of an equilateral triangle?

**Comment by Arafatk** [comment]
@smichr  As of now,the answer would be any two points among the points of an equilateral triangle because the function always returns a pair(a group of 2 points ).But a very easy check statement could ensure that we get all the three points. Also in case of identical points the function only outputs a pair of points but a small change could answer all the identical points, if needed.I can make the required changes if you say so, And it would be great if you could tell me some further improvements to this.

**Comment by smichr** [comment]
If there are ties, my first thought is that they should be included. But I would not include duplicate points. Can you think of a case where that would be helpful?

**Comment by Arafatk** [comment]
@smichr  How about this 
1. If their are identical points then output a unique pair of identical points
2. If their is a unique closest pair of points then output the unique closest pair 
3.If their are ties(without identical points) then we pass a default argument *(set to None)* which outputs a single closest pair by default, but if the user gives an argument for example **'all'** then, it outputs all the closest pair of points. This way the user has the liberty to get the output as per his/her needs. 
An example of this is when the set of points contains a regular polygon with closest pair of points   ,then output is ((a,b),(b,c),(c,d)....) where a,b,c.. are the vertices of polygon.

In case 3 the use of **'all'** can be achieved by running the last sweep-line loop twice,and and using a deque for storing the best pairs so their would be no observable difference in performance.

Is this a good way?

**Pull request closed without merging**
