### PR TITLE
Doc creation now compatible with sphinx 1.3.1

### LINKED ISSUE #9273: Cannot `make html`
This is what I get (things get interesting with WARNING, at ~80% down):

```
(python2.6.9)jo@jodel:~/Projekte/sympy-workspace/sympy-project/sympy/doc$ git status
Auf Branch improve-sysode-docs
nichts zu committen, Arbeitsverzeichnis unverändert
(python2.6.9)jo@jodel:~/Projekte/sympy-workspace/sympy-project/sympy/doc$ git checkout master
Zu Branch 'master' gewechselt
Ihr Branch ist auf dem selben Stand wie 'origin/master'.
(python2.6.9)jo@jodel:~/Projekte/sympy-workspace/sympy-project/sympy/doc$ make html
Makefile:121: warning: overriding recipe for target '_build/cheatsheet/cheatsheet.pdf'
Makefile:116: warning: ignoring old recipe for target '_build/cheatsheet/cheatsheet.pdf'
rm -rf _build/logo
mkdir -p _build/logo
python ./generate_logos.py -d
INFO:root: File saved: ./_build/logo/sympy-notail.svg
INFO:root: File saved: ./_build/logo/sympy-notailtext.svg
INFO:root: File saved: ./_build/logo/sympy-notext.svg
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-160px.png -h 160 -w 160
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-500px.png -h 500 -w 500
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./src/logo/sympy.svg -f png -o ./_build/logo/sympy-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notail.svg -f png -o ./_build/logo/sympy-notail-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notailtext.svg -f png -o ./_build/logo/sympy-notailtext-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-16px.png -h 16 -w 16
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-32px.png -h 32 -w 32
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-48px.png -h 48 -w 48
DEBUG:root:return code: 0
DEBUG:root:command: rsvg-convert ./_build/logo/sympy-notext.svg -f png -o ./_build/logo/sympy-notext-64px.png -h 64 -w 64
DEBUG:root:return code: 0
DEBUG:root:command: convert ./_build/logo/sympy-16px.png ./_build/logo/sympy-32px.png ./_build/logo/sympy-48px.png ./_build/logo/sympy-64px.png ./_build/logo/sympy-favicon.ico
DEBUG:root:return code: 0
DEBUG:root:command: convert ./_build/logo/sympy-notail-16px.png ./_build/logo/sympy-notail-32px.png ./_build/logo/sympy-notail-48px.png ./_build/logo/sympy-notail-64px.png ./_build/logo/sympy-notail-favicon.ico
DEBUG:root:return code: 0
DEBUG:root:command: convert ./_build/logo/sympy-notailtext-16px.png ./_build/logo/sympy-notailtext-32px.png ./_build/logo/sympy-notailtext-48px.png ./_build/logo/sympy-notailtext-64px.png ./_build/logo/sympy-notailtext-favicon.ico
DEBUG:root:return code: 0
DEBUG:root:command: convert ./_build/logo/sympy-notext-16px.png ./_build/logo/sympy-notext-32px.png ./_build/logo/sympy-notext-48px.png ./_build/logo/sympy-notext-64px.png ./_build/logo/sympy-notext-favicon.ico
DEBUG:root:return code: 0

Logo generated.
mkdir -p src/.static
mkdir -p _build/html
mkdir -p _build/doctrees
mkdir -p src/modules
PYTHONPATH=..: sphinx-build -b html -d _build/doctrees  src _build/html
Running Sphinx v1.3
WARNING: the config value 'html_domain_indices' has type `list', defaults to `bool.'
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 203 source files that are out of date
updating environment: 203 added, 0 changed, 0 removed
reading sources... [100%] wiki                                                                                      
/home/jo/Projekte/sympy-workspace/sympy-project/sympy/doc/src/modules/core.rst:474: WARNING: error while formatting arguments for sympy.core.evalf.N: 'function' object has no attribute '__bases__'
/home/jo/Projekte/sympy-workspace/sympy-project/sympy/doc/src/modules/functions/elementary.rst:306: WARNING: error while formatting arguments for sympy.functions.elementary.miscellaneous.sqrt: 'function' object has no attribute '__bases__'
/home/jo/Projekte/sympy-workspace/sympy-project/sympy/doc/src/modules/polys/internals.rst:749: WARNING: error while formatting arguments for sympy.polys.modulargcd.modgcd_univariate: 'function' object has no attribute '__bases__'
/home/jo/Projekte/sympy-workspace/sympy-project/sympy/doc/src/modules/polys/internals.rst:750: WARNING: error while formatting arguments for sympy.polys.modulargcd.modgcd_bivariate: 'function' object has no attribute '__bases__'
/home/jo/Projekte/sympy-workspace/sympy-project/sympy/doc/src/modules/polys/internals.rst:751: WARNING: error while formatting arguments for sympy.polys.modulargcd.modgcd_multivariate: 'function' object has no attribute '__bases__'
/home/jo/Projekte/sympy-workspace/sympy-project/sympy/doc/src/modules/polys/internals.rst:752: WARNING: error while formatting arguments for sympy.polys.modulargcd.func_field_modgcd: 'function' object has no attribute '__bases__'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... 
Theme error:
unsupported theme option 'visitedlinkcolor' given
Makefile:50: recipe for target 'html' failed
make: *** [html] Error 1
```

### PR DESCRIPTION
**Pull request by debugger22**
- Updated sphinx version in `.travis.yml`
- Changed font to Open Sans
- Fixed missing inline code highlighting
- Fixed failing tests because of misleading `autoclass` for functions

Closes #9273
Closes https://github.com/sympy/sympy/pull/9297.

Sorry @AadityaNair for a new PR! This one fixes failing build and eliminates unnecessary merge commits.

### CODE REVIEW

**Comment by AadityaNair** [comment]
Sure. I have my exams going on. Couldn't do it even if I wanted to.

**Comment by toolforger** [comment]
The failed run seems to be related to Travis, not SymPy itself.
It should be restarted to make sure that that's indeed the case.

**Comment by debugger22** [comment]
Tests passed.

**Comment by toolforger** [comment]
Looks good to me. +1

**Comment by jksuom** [comment]
Looks good though I have not tried to actually run sphinx-build (1.3.1 is not installed). @debugger22 I trust you have seen the result?

**Comment by debugger22** [comment]
Yes.

Html: http://sympy-docs.s3-website-us-west-2.amazonaws.com/open-sans/new/
PDF: https://www.dropbox.com/s/rsujktfogzdn23x/sympy-0.7.6-git.pdf?dl=1

**Comment by jksuom** [comment]
Good. Merging.

**Comment by debugger22** [comment]
Thanks!

**Comment by debugger22** [comment]
@asmeurer Does this look good to you?

**Comment by toolforger** [comment]
It certainly looks good to me.

**Pull request merged**
