### PR TITLE
Temporarily disable pymc3

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed

Disable ~~aesara and~~ pymc3 as there is a bug when combined with newest NumPy.

~~Bug: https://github.com/aesara-devs/aesara/issues/715~~
~~Solution(?): https://github.com/aesara-devs/aesara/pull/716~~

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscargus** [comment]
The option is to limit NumPy to version 1.21.5.

**Comment by oscarbenjamin** [comment]
> The option is to limit NumPy to version 1.21.5.

That would make sense if we expect that numpy might fix this. Is there a numpy issue for this?

**Comment by oscargus** [comment]
I'd say it is an aesara issue. Basically they try to read directly from a file rather than querying:

https://github.com/aesara-devs/aesara/blob/ff4b91dddede43d63d348bdec8fe1079932146b0/aesara/link/c/cmodule.py#L2625-L2646

**Comment by oscargus** [comment]
Pushing again with only pymc3 removed (should pass if the providers are updated with the new aesara)-

**Comment by oscarbenjamin** [comment]
Okay looks good to me based on comments elsewhere (https://github.com/sympy/sympy/pull/22780#issuecomment-1003623031)

I'll merge this now

We need to make sure to remember to enable this again once there is a new version of pymc that we can use (CC @brandonwillard).

**Pull request merged**
