### PR TITLE
refactoring tests which are marked as slow

### PR DESCRIPTION
**Pull request by Mohitbalwani26**
#### References to other Issues or PRs

SEE #18377 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by Mohitbalwani26** [comment]
```
example_1 14.231575743000121
example_2 14.900866340999983
example_3 3.610595946000103
example_4 1.9300833219999731
example_5 3.0720553850001124
example_6 4.287057902000015
example_7 3.807014885999706
example_8 4.605062168999666
example_9 3.988571009000225
example_10 6.637001678000161
example_11 32.298094283999944
```
@oscarbenjamin 
These are time in seconds taken by each example for testing.
what threshold should be kept for marking them as slow in refactored test examples?

**Comment by oscarbenjamin** [comment]
Maybe anything above 1 second should be considered slow.

**Comment by Mohitbalwani26** [comment]
@oscarbenjamin does this approach looks correct?

**Comment by oscarbenjamin** [comment]
Yes, this looks good.

**Comment by oscarbenjamin** [comment]
Are you finished with this PR?

**Comment by Mohitbalwani26** [comment]
@oscarbenjamin in travis there is a test job which states that `test_sympy slow =True` so if we refactor the slow tests like this then it will not be tested on travis.

**Comment by oscarbenjamin** [comment]
We need to make sure that the slow tests are also tested on Travis. We just need to have a separate function marked as `@slow` that runs the slow examples.

**Comment by Mohitbalwani26** [comment]
```python3
@slow
def test_slow_examples():
    _ode_solver_test(_get_examples_ode_sol_nth_linear_undetermined_coefficients(),run_slow_test=True)
    _ode_solver_test(_get_examples_ode_sol_nth_order_reducible(), run_slow_test=True)
```
@oscarbenjamin something like this?

**Comment by oscarbenjamin** [comment]
Yes. They should be separate like:
```python
@slow
def test_slow_examples_nth_linear_xxx():
    _ode_solver_test(_get_examples_ode_sol_nth_linear_undetermined_coefficients(),run_slow_test=True)

@slow
def test_slow_examples_nth_linear_xxx():
    _ode_solver_test(_get_examples_ode_sol_nth_order_reducible(), run_slow_test=True)
```

**Comment by Mohitbalwani26** [comment]
@oscarbenjamin can you review this now?

**Comment by oscarbenjamin** [comment]
Looks good.

**Pull request merged**
