### PR TITLE
Revert "Update diophantine.rst" (fixes test failures in master)

### PR DESCRIPTION
**Pull request by asmeurer**
This reverts commit 3b9112c905a81195f8fd8720d4096c77686b7cc8.

See the [comments on the commit](https://github.com/sympy/sympy/commit/3b9112c905a81195f8fd8720d4096c77686b7cc8).

### CODE REVIEW

**Comment by asmeurer** [comment]
@smichr @jksuom

**Comment by jksuom** [comment]
+1

**Comment by smichr** [comment]
I really wish I knew how this happened. I suspect it came from online editing of the master and was totally unintended. Is there a way to protect against this, @asmeurer ?

**Comment by asmeurer** [comment]
See my comments here https://github.com/sympy/sympy/commit/3b9112c905a81195f8fd8720d4096c77686b7cc8. You can protect against accidental pushes from git, but there's no way to disable online editing of master, so my only suggestion is to not use the online editor.

**Pull request merged**
