### PR TITLE
B(1) = +½ set 2: generalised Bernoulli function

### LINKED ISSUE #23866: The value of bernoulli(1)
There are two conventions for the Bernoulli numbers, specifically $B_1$ can be defined to be 1/2 or -1/2 (see https://en.wikipedia.org/wiki/Bernoulli_number), depending on whether it is defined using the exponential generating function $\frac{x}{e^x-1}$ or $\frac{xe^x}{e^x - 1}$. SymPy uses the -1/2 definition.

Donald Knuth has recently written that he's been convinced that the -1/2 definition is wrong and historically inaccurate, and he updated *Concrete Mathematics* accordingly (https://www-cs-faculty.stanford.edu/~knuth/news22.html):

> The sequence of Bernoulli numbers plays a prominent role in mathematics, especially in connection with asymptotic expansions related to Euler's summation formula. When I learned about this fascinating sequence, during my undergraduate days, I was taught that $B_1$ is equal to minus one-half. So I duly taught the same to my students, and went on to write books that explained what I thought Bernoulli and Euler had done.
>
> But last year I took a close look at Peter Luschny's [Bernoulli manifesto](http://luschny.de/math/zeta/The-Bernoulli-Manifesto.html), where he gives more than a dozen good reasons why the value of $B_1$ should really be plus one-half. He explains that some mathematicians of the early 20th century had unilaterally changed the conventions, because some of their formulas came out a bit nicer when the negative value was used. It was their well-intentioned but ultimately poor choice that had led to what I'd been taught in the 1950s.
>
> Luschny's webpage cites, for example, recent treatments of the subject by leading mathematicians such as Terence Tao. And his most compelling argument, from my personal perspective, is the way he unveils the early publications: I learned from him that my own presentation of the story, in [The Art of Computer Programming](https://www-cs-faculty.stanford.edu/~knuth/taocp.html) and much more extensively in [Concrete Mathematics](https://www-cs-faculty.stanford.edu/~knuth/gkp.html), was a violation of history! I had put words and thoughts into Bernoulli and Euler's minds that were not theirs at all. This hurt, because I've always tried to present the evolution of ideas faithfully; in this case I'd fooled myself, by trying to conform what they wrote to what I'd learned.
>
> By now, hundreds of books that use the “minus-one-half” convention have unfortunately been written. Even worse, all the major software systems for symbolic mathematics have that 20th-century aberration deeply embedded. Yet Luschny convinced me that we have all been wrong, and that it's high time to change back to the correct definition before the situation gets even worse.
>
> Therefore I changed the definition of $B_1$ in all printings of The Art of Computer Programming during the latter half of 2021. And the new (34th) printing of Concrete Mathematics, released in January 2022, contains the much more extensive changes that are needed to tell a more comprehensive story.

Here is Luschny's page he cites http://luschny.de/math/zeta/The-Bernoulli-Manifesto.html.

So maybe we should reconsider SymPy's definition of `bernoulli`. At the very least, I think there should be a way to specify which convention is used, $B^+_n$ or $B^-_n$.

As an aside, [the docs for `bernoulli`](https://docs.sympy.org/dev/modules/functions/combinatorial.html#sympy.functions.combinatorial.numbers.bernoulli) state that the defining recurrence relation is $$0 = \sum_{k=0}^n \binom{n+1}{k} B_k$$ but for the -1/2 definition it should actually be $$\delta_{m,0} = \sum_{k=0}^n \binom{n+1}{k} B_k$$ (for the +1/2 definition it's $$n + 1 = \sum_{k=0}^n \binom{n+1}{k} B_k,$$ see https://en.wikipedia.org/wiki/Bernoulli_number#Recursive_definition).

### PR DESCRIPTION
**Pull request by Parcly-Taxel**
#### References to other Issues or PRs

Part 2 of the changes formerly included in #23926, building upon #23973. The changes here are also the actual changes that will fix #23866.

#### Brief description of what is fixed or changed

This PR generalises `bernoulli()` to the generalised Bernoulli function described in Peter Luschny's "[An introduction to the Bernoulli function](https://arxiv.org/abs/2009.06743)":
$$B(s,a)=\begin{cases}1&s=0\\\\-s\zeta(1-s,a)&s\ne0\end{cases}$$
In the process it also changes `bernoulli(1)` to `+1/2`.

#### Other comments

Since the Genocchi numbers are currently defined in terms of the Bernoulli numbers, this also changes `genocchi(1)` to `-1`; a later PR will generalise this integer sequence to the two-complex-argument generalised Genocchi function in the same vein as the generalised Bernoulli function, though.

Luschny also defines the _central Bernoulli numbers_ and _polynomials_, but I have not made a new SymPy function out of that because its generalisation to arbitrary complex arguments can be expressed as $2^s B(s,\frac{a+1}2)$.

#### Release Notes

* functions
    * BREAKING: `bernoulli(1)` is now `1/2` instead of `-1/2` and `genocchi(1)` is now `-1` instead of `1`.
    * `bernoulli()` now accepts complex arguments, implementing [Luschny (2020)](https://arxiv.org/abs/2009.06743).

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I think this looks good. Does anyone else have any opinions about this?

The discussion for the rationale for this change is in the linked issue and reference cited above.

Not a new problem but this should also get fixed:
```
In [1]: lambdify(x, bernoulli(x))(1.2)
Out[1]: array([ 1. , -0.5])
```
That's scipy's bernoulli function which is inconsistent with SymPy's.

**Comment by Parcly-Taxel** [comment]
> Not a new problem but this should also get fixed: … That's scipy's bernoulli function which is inconsistent with SymPy's.

I think I've got the solution for that. Put the following code in `sympy/printing/numpy.py`:

```python
    def _print_bernoulli(self, expr):
        return self._print(expr._eval_rewrite_as_zeta(*expr.args))
```

Does this make sense and should I commit it in this PR?

**Comment by oscargus** [comment]
I think that makes sense and could go into this. Possibly with a small comment of the type `# scipy's bernoulli in inconsistent with SymPy's so rewrite` and a test. Thanks!

**Comment by oscarbenjamin** [comment]
Okay let's get this in.

Thanks @Parcly-Taxel!

**Comment by asmeurer** [comment]
The lambdified bernoulli was already wrong anyway. `scipy.special.bernoulli(n)` returns the first `n` Bernoulli numbers. The equivalent for SymPy would be `scipy.special.bernoulli(n)[-1]`.

**Comment by fchapoton** [comment]
This is a **very wrong move** and should be undone. You have been tricked to do that by people with no authority whatsoever. This is not good to try changing the stable convention used by the large majority of mathematical papers.

**Comment by Parcly-Taxel** [comment]
> This is a **very wrong move** and should be undone. You have been tricked to do that by people with no authority whatsoever. This is not good to try changing the stable convention used by the large majority of mathematical papers.

You have no authority _here_ to decide what $B_1$ is. Meurer, Benjamin and I have already decided that it will change to $+\frac12$ in 1.12, and I layered my PRs in such a way to lock this change in. It's too late to turn back.

**Comment by edgarcosta** [comment]
@Parcly-Taxel, I think you have just agreed that you tricked them:
> I layered my PRs in such a way to lock this change in. It's too late to turn back.

**Comment by oscarbenjamin** [comment]
> I layered my PRs in such a way to lock this change in. It's too late to turn back.

It's not too late to revert anything. Nothing has been released yet.

**Comment by Parcly-Taxel** [comment]
> I think you have just agreed that you tricked them:

There was no trickery involved here. There is also no authority defining what the Bernoulli numbers are, just as there is no authority defining $\pi$ or the real numbers. I merely wrote code _illuminating mathematical truth_, which every CAS should strive to do.

**Comment by asmeurer** [comment]
Can we please keep the discussions here civil and within our [code of conduct](https://github.com/sympy/sympy/blob/master/CODE_OF_CONDUCT.md). Keep the discussion to the technical merits and specific mathematical details. Claiming that people are "playing tricks", especially without any arguments to back it up, is not a helpful avenue of discussion and is unnecessarily antagonistic.

Also, it would be best to have this discussion at https://github.com/sympy/sympy/issues/23866. There's a lot of PRs relating to this issue in SymPy, but that's the main issue for `bernoulli(1)` and related changes. And as I requested elsewhere, if there are relevant discussions happening on other forums (such as Sage forums), please cross-link them there as many of us are not subscribed to them.

As Oscar stated, this is not yet "locked in", because it hasn't been in a release. That was done on purpose because we knew this could be controversial.

**Pull request merged**
