### PR TITLE
Implemented function integer_log

### LINKED ISSUE #13908: [FEATURE REQUEST] integer_log
In a recent PR #13844, the following function may have been useful.

```python
def integer_log(y, x):
    """Returns (e, bool) where e is the largest nonnegative integer
    such that y >= x**e and bool is True if y == x**e"""
    assert x > 1
    y = as_int(y)
    x = as_int(x)
    if x == 2:
        e = y.bit_length() - 1
        return e, 2**e == y
    r = e = 0
    while y >= x:
        d = x
        m = 1
        while y >= d:
            y, r = divmod(y, d)
            e += m
            if y > d:
                d *= d
                m *= 2
    return e, y == 1 and r == 0
```
As tested in the following, it is much faster than `int(log(y, x))`

```
def go(n, b):
    a = [randint(1, 2**123) for i in range(n)]
    b = [randint(2, b) for i in range(n)]
    v1 = []
    t = time()
    for i in range(n):
        v1.append(int(log(a[i], b[i])))
    intlog = time() - t
    v2 = []
    t = time()
    for i in range(n):
        v2.append(integer_log(a[i], b[i]))
    this = time()-t
    for i in range(n):
        try:
            assert v1[i] == v2[i][0]
        except:
            print(a[i], b[i])
            print(v1[i], v2[i])
            return
    return this/intlog
>>> go(100, 42)
0.0016...
```

This fills in a gap left by 
* `multiplicity` - what is the power of x in y?
* `perfect_power` - can y be written as x**e?
* `integer_nthroot` - what is the largest integer x <= y**(1/n)?
* `is_square` - is x a square number

### PR DESCRIPTION
**Pull request by arighnac**
Fixes #13908 .

This PR implements a new function `integer_log(y, x)` in place of `integer_nthroot(y, x)` in solveset, which makes runtime fast.

@smichr , please review.

### CODE REVIEW

**Comment by smichr** [comment]
The intent of the code is to identify when the `-rhs` is a square number and an integer power of the base. Your change accidentally still works because only tests involving powers of 2 were involved. What is the answer for `solveset(Eq(3**(x - 3), -3**39), x, S.Reals)`?

The way the routine works now is quite efficient though less transparent than:

```
m = integer_log(-rhs, base)
if not m % 2:
    return expo, FiniteSet(m)
```

I think a better place for `integer_log` would be next to `integer_nthroot`. Also, a test function for it should be added that covers all cases:

```
# errors for these
integer_log(2, 1)
integer_log(0, 2)
integer_log(1.1, 2)
integer_log(1, 2.2)

integer_log(1, 2) == (0, True)  # see updated code on issue page
integer_log(1, 3) == (0, True)
integer_log(2, 3) == (0, False)
integer_log(3, 3) == (1, True)
integer_log(3*2, 3) == (1, False)
integer_log(3**2, 3) == (2, True)
integer_log(3*4, 3) == (2, False)
integer_log(3**3, 3) == (3, True)
```

**Comment by ArighnaIITG** [comment]
@smichr , please review.

**Comment by ArighnaIITG** [comment]
Ping @smichr .
I have implemented the new feature, and also other test cases as well.

**Comment by smichr** [comment]
> a better place for integer_log would be next to integer_nthroot

Also, there is no need to convert the result to a list before checking element `[0]` in the solveset code.

**Comment by smichr** [comment]
Looks like #13923 is ready so I am closing this.

**Pull request closed without merging**
