### PR TITLE
include the coefficient in L(A*x')

### LINKED ISSUE #23307: Laplace transform of derivatives rule does not handle coefficients
I believe there is new support for:
```
from sympy import Function, laplace_transform
from sympy.abc import s,t
x = Function('x')
laplace_transform(x(t).diff(t),t,s)
```
(which gives: `s*LaplaceTransform(x(t), t, s) - x(0)` as expected)

However the following result is incorrect in sympy 1.10.1

```
laplace_transform(10*x(t).diff(t),t,s)
```
(which also gives `s*LaplaceTransform(x(t), t, s) - x(0)` instead of 10 times that)

### PR DESCRIPTION
**Pull request by jackschmidt**
#### References to other Issues or PRs

Fixes #23307

#### Brief description of what is fixed or changed

Include the matched coefficient in the derivative rule, L(a*g'(t)), return a times the rule for the derivative,
not just the rule for the derivative.

#### Release Notes

* integrals
  * fix bug in Laplace transform of a derivative

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
@hanspi42 does this look good to you?

**Comment by oscarbenjamin** [comment]
A test for the changed behaviour should be added somewhere around here:
https://github.com/sympy/sympy/blob/92625c843417bcf6f1f38ad7e87eb4cb64cb016a/sympy/integrals/tests/test_transforms.py#L697

**Comment by jackschmidt** [comment]
I tried adding a test there, but I don't know how to use it. It seems to pass whether or not the fix is included, and it passes even if I assert that LT(10*...) = 9*oldanswer, which should always fail.

This should fail (notice the "9" on the right hand side):
```
index c16e0f942c..061ee5de71 100644
--- a/sympy/integrals/tests/test_transforms.py
+++ b/sympy/integrals/tests/test_transforms.py
@@ -699,6 +699,9 @@ def test_laplace_transform():
     assert LT(diff(f(t), (t, 3)), t, s) == s**3*LaplaceTransform(f(t), t, s)\
         - s**2*f(0) - s*Subs(Derivative(f(t), t), t, 0)\
             - Subs(Derivative(f(t), (t, 2)), t, 0)
+    # Issue #23307
+    assert LT(10*diff(f(t), (t, 1)), t, s) == 9*s*LaplaceTransform(f(t), t, s)\
+        - 10*f(0)
     assert LT(a*f(b*t)+g(c*t), t, s) == a*LaplaceTransform(f(t), t, s/b)/b +\
         LaplaceTransform(g(t), t, s/c)/c
     assert inverse_laplace_transform(
```

but I get:
```
$ bin/test sympy/integrals/tests/test_transforms.py
=================================== test process starts ===================================
executable:         /home/jack/Documents/devel/sympy/.venv/bin/python  (3.9.7-final-0) [CPy
thon]                                                                                      
architecture:       64-bit                                                                 
cache:              yes                                                                    
ground types:       python                                                                 
numpy:              None                                                                   random seed:        45242893                                                               
hash randomization: on (PYTHONHASHSEED=2243306423)
                                                                                           
sympy/integrals/tests/test_transforms.py[22] ...w..wwwww...........                    [OK]
                                                                                           
================= tests finished: 16 passed, 6 skipped, in 23.17 seconds ==================
```

**Comment by jackschmidt** [comment]
Ok, test added. It can be checked with:
```
$ bin/test --slow --verbose --pdb sympy/integrals/tests/test_transforms.py
```

**Comment by oscarbenjamin** [comment]
Okay well this looks good to me.

@hanspi42 ?

**Comment by hanspi42** [comment]
Looks good, thanks @jackschmidt for correcting this ;)

**Comment by oscarbenjamin** [comment]
Great, thanks both.

**Pull request merged**
