### PR TITLE
Complexanalysis 1

### PR DESCRIPTION
**Pull request by Teut2711**
#### Brief description of what is fixed or changed
Added function to display contour(broken)

#### Release Notes

* complexanalysis
   * module
* complexintegration 
  * function

### CODE REVIEW

**Comment by XtremeGood** [comment]
This is an update to #16315.I don't know how to merge it in the previous pull request.

**Comment by XtremeGood** [comment]
The function contour_cir is working in (0, pi) with radius = 1 and gives a semi-circle but I don't know why it gives me:
image

for 
```
x = Symbol("x")
eq = ComplexIntegral(1/(x**2 + 1)**2,shape="semi-circle", params=dict(z0=0+0*I, radius=oo, theta1=0, theta2=pi/4))
eq.contour_cir()
```.
It should give an arc with two lines. Also if the y-axis shows e.g. "3i" instead of 3 it would be great. Please tell how to do so.

**Comment by XtremeGood** [comment]
And yes I have used |z-z0|=r equation for the circle and then any point on the circle is (x+rcos(theta), y+rsin(theta)) where (x,y) is the centre. I would segregate the code as I build enough of it. I intend the module to solve a complex equation, draw simple curves like straight line circle etc, and perform contour integrate at the least. Please help me out here.

**Comment by sylee957** [comment]
Honestly, besides some modularization issues like using 
```
from sympy import *
import matplotlib.pyplot as plt
```
that is causing test failings,

I'm afraid that it can be too early to implement contour integrals.
Like we may need a lot of steps to improve geometry module, vector calculus, and to extend it to complex analysis, or such.

And even other CAS like Mathematica or Maple hadn't fully implemented contour integration yet, so it may be difficult to find a good design because there is no precedence.
And looking from the point in a future when it becomes technically possible, early implementations may not look good.

Though I don't have much information about the difficulty of implementing contour integrals for CAS.

**Comment by XtremeGood** [comment]
I agree contour integrations are tough but likewise, the current integral is unable to solve many integrals which are quite simple. With contour integration, we can at least solve those integrals which can be solved over the upper half plane semi-circle for which Jordan's lemma is valid. Obviously like there is no method to determine how to choose functions for implementing integration by parts or substitution similar is the case here but those libraries exist and are improving. I really feel the need. And also not only that but I'm implementing other things to which people have to do manually like solving a complex equation. The current solver does not separate the imaginary and real part.

**Comment by XtremeGood** [comment]
Else I can work with finite groups, odes, and linear algebra(I know that stuff). And most of the ideas regarding these are already taken up by people. This was the only one asked many times for but yet unimplemented. I really need to enter in this gsoc.

**Comment by asmeurer** [comment]
Can you give an example of an integral that `integrate` cannot solve which would be solvable with a contour integration module? `integrate` currently uses the Miejer G algorithm, which can solve a large class of integrals that would normally be solved using contour techniques.

**Comment by XtremeGood** [comment]
Yes, you are right, it's only branch cut problems that requires contour integration distinctively.Yet I could find only x^a/(e^x -1) integral.This is widely used in many important derivations.

**Comment by XtremeGood** [comment]
If it's not good enough I have no problem in switching to something else. I don't think optimization is implemented in sympy i.e, Lagrange Multipliers. Should I go for that?

**Comment by asmeurer** [comment]
The project can be good if you can demonstrate that it will be able to do useful things. It's quite possible that we may need to improve other modules first. I definitely think that in principle SymPy should be able to compute contour integrals. It remains an open question to me at least whether such a module could be implemented well enough that it would be usable outside of itself (for instance, computing non-contour integrals).

**Comment by XtremeGood** [comment]
Real integrals can be solved using contour integral and complex integrals can be solved using contour integration. There are integrals which are either real or imaginary part of computed complex integrals.  The only thing required is residue theorem or using substitution like z = exp(i*theta). If you try to solve f = x**2 +I*y**2 in sympy it will give x**2 = -I*y**2 whereas we know that in this case the real and imaginary parts are individually equated to 0 which gives the solution (0,0). I would add solver for these equations too. Graphs in the complex analysis are also important which I want to add. Eg |z-z0| = r is a circle. Solving equations like z+z_(i.e, z bar) = 2*Real(z)  Eg simplify(z*z_ +2*|z|) =|z|**2+2|z|) . These kinds of calculations can't be currently done by sympy which I plane to do(kind of a solver but for complex analysis).

**Comment by czgdp1807** [comment]
@XtremeGood Are you still working on it?

**Comment by XtremeGood** [comment]
well i wanted to but need to know if it should be.

**Comment by czgdp1807** [comment]
@asmeurer @sylee957 Please confirm on @XtremeGood 's following point,


> need to know if it should be.

**Comment by XtremeGood** [comment]
many of the things which I thought to make are already present but no solver of solving complex equations is available upto my knowlegde in codebase.  Yes you can do it with subs etc but that's now how we expect it to do. I gave info on it in gsoc proposal.

**Comment by XtremeGood** [comment]
You are free to delete it from my side.

**Comment by sylee957** [comment]
It may not look constructive at this state, but I don't think that it should be closed if there is no succeeding PR for this or there is any other better implementation in the codebase which can completely absorb this case.

I'm not very familiar with the integration module in general, but it looks like at least the inverse laplace transform can make use of residue summation formula without much concern of the geometry of the contour.
If you can make some inverse laplace transforms successful with the residue summation, where other implementations are failing or too slow, it can be worth considering. But I may not be able to tell that the previous implementation was already very mature or not.

**Comment by sylee957** [comment]
I think that contour integration is a fairly recently studied topic for symbolic computation
https://www.researchgate.net/publication/297731795_Contour_Integration_a_procedure_still_missing_in_Mathematica
and we may need some people to clarify that how much capable this is

**Pull request closed without merging**
