### PR TITLE
Upgrade pip for cache installation

### PR DESCRIPTION
**Pull request by OrkoHunter**
Travis-CI still has 6.x version of pip. However version 7.0.0 and later cache installed packages automatically in the form of wheels. Subsequent installs are therefore much faster.

### CODE REVIEW

**Comment by moorepants** [comment]
We can merge this but I don't think it helps anything because we only ever install things once on each Travis VM. Does it actually help caching across VM instances with Travis?

**Comment by debugger22** [comment]
@OrkoHunter I think you are confused with VM and VE. I don't think wheels are shared among VMs.

**Comment by asmeurer** [comment]
I agree. I don't think this will be an improvement.

**Comment by OrkoHunter** [comment]
Yes, I got confused between the two. The wheels cached in one env won't be
available for other env because Travis uses different VMs for them.

**Comment by OrkoHunter** [comment]
Well, after some further research I found how this *can work*. Source : http://docs.travis-ci.com/user/caching/

We need to set the cache option first
```yaml
cache:
  directories:
    - $HOME/.cache/pip
```

After this change, Travis will cache the wheels and upload them to [S3](http://docs.travis-ci.com/user/deployment/s3/). So that the builds on the commits after this change, would be able to use them.
See [this](https://github.com/nickstenning/travis-pip-cache) for an example of how `2 min 28 sec` drastically decreased to `16 sec`

So, it's not related to VM or vitualenv in any way.

Suggestions?

**Comment by asmeurer** [comment]
Cool, let's implement that.

**Comment by OrkoHunter** [comment]
I don't think this test failure https://travis-ci.org/sympy/sympy/jobs/71974617 has something to do with this PR.

**Comment by asmeurer** [comment]
Possibly. That is a failure coming from theano, a pip dependency. I would double check that this didn't change the theano version.

**Comment by debugger22** [comment]
@OrkoHunter Are you planning to work on in? You can either go the way Aaron suggested or probably make it work with the newer version of theano if that's the case.

**Comment by OrkoHunter** [comment]
I don't know which version of theano is SymPy incompatible with but seeing the log I can see the new build is installing version 0.6.

**Pull request closed without merging**
