### PR TITLE
Don't use parse_latex in the printing tests

### PR DESCRIPTION
**Pull request by asmeurer**
There is no reason for the tests to depend on parsing. They can just create
the expressions directly.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
What's going on with the test failure here?

```
__________ sympy/core/tests/test_function.py:test_subs_in_derivative ___________
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/core/tests/test_function.py", line 746, in test_subs_in_derivative
    assert (abstract.subs(f, F).doit() - concrete).simplify() == 0
            ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 997, in subs
    rv = rv._subs(old, new, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 1109, in _subs
    rv = self._eval_subs(old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/function.py", line 2[366](https://github.com/sympy/sympy/runs/7371909456?check_suite_focus=true#step:16:367), in _eval_subs
    expr = self.expr._subs(old, new)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/basic.py", line 1109, in _subs
    rv = self._eval_subs(old, new)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/sympy/sympy/sympy/core/function.py", line 1738, in _eval_subs
    ofree = old.xreplace(syms).free_symbols
            ^^^^^^^^^^^^^^^^^^
TypeError: Basic.xreplace() missing 1 required positional argument: 'rule'
```

**Comment by asmeurer** [comment]
Oh it's in a 3.11 alpha build.

**Comment by oscarbenjamin** [comment]
> What's going on with the test failure here?

See #23774

**Review by glenn-horton-smith — APPROVED** [review]
These changes all look good to me. I like that the tests of pycode and .python won't get skipped if antlr / parse_latex are not available.

**Pull request merged**
