### PR TITLE
assumptions that are wrong in master

### PR DESCRIPTION
**Pull request by AnishShah**
Addresses issue from #8046
I will try to solve two-three more issues.

Currently, solves 18th issue from the list.

### CODE REVIEW

**Comment by smichr** [comment]
When this is merged, are you able to check off the 18th issue from the list? If not, I will do so if I am the one to merge this.

**Comment by smichr** [comment]
+1 if tests pass

**Comment by AnishShah** [comment]
Nope, I can't check off

**Comment by AnishShah** [comment]
Some tests are failing ... I'll have a look at them.

**Pull request closed without merging**
