### PR TITLE
RUBI: documentation for utility functions

### PR DESCRIPTION
**Pull request by Abdullahjavednesar**
Documentation for utility functions

### CODE REVIEW

**Comment by Abdullahjavednesar** [comment]
ping @certik

**Comment by certik** [comment]
Thanks @Abdullahjavednesar, this looks very good, with lots of examples, I like it.

**Comment by Abdullahjavednesar** [comment]
@asmeurer , @certik ,why does [Job #23882.21](https://travis-ci.org/sympy/sympy/jobs/271336560) fail?

**Comment by parsoyaarihant** [comment]
there is an implicit import in line 267 in `utility_function.py` file:
```python
____________ sympy/utilities/tests/test_code_quality.py:test_files _____________
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/sympy/utilities/tests/test_code_quality.py", line 228, in test_files
    check_directory_tree(SYMPY_PATH, test, exclude)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/sympy/utilities/tests/test_code_quality.py", line 107, in check_directory_tree
    check_files(glob(join(root, pattern)), file_check, exclusions)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/sympy/utilities/tests/test_code_quality.py", line 123, in check_files
    file_check(fname)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/sympy/utilities/tests/test_code_quality.py", line 146, in test
    test_this_file(fname, test_file)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/sympy/utilities/tests/test_code_quality.py", line 180, in test_this_file
    assert False, message_implicit % (fname, idx + 1)
AssertionError: File contains an implicit import: /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/sympy/integrals/rubi/utility_function.py, line 267.
```

run `bin/test sympy/utilities/tests/test_code_quality.py` locally.

**Comment by certik** [comment]
@Abdullahjavednesar please ping me when the tests pass, so that I can merge this.

**Comment by Abdullahjavednesar** [comment]
@certik some

**Comment by Abdullahjavednesar** [comment]
@certik some

**Comment by Abdullahjavednesar** [comment]
ping @certik

**Comment by certik** [comment]
Thanks!

**Pull request merged**
