### PR TITLE
Fixed docstring of logcombine function

### LINKED ISSUE #15854: Simplify doesn't assume abs(x) is positive
SymPy doesn't simplify logs of symbols if it doesn't know that they are positive:
```julia
In [3]: x = Symbol('x')                                                                                                                        

In [4]: simplify(log(x**2)/log(x))                                                                                                             
Out[4]: 
   ⎛ 2⎞
log⎝x ⎠
───────
 log(x)

In [5]: x = Symbol('x', positive=True)                                                                                                         

In [6]: simplify(log(x**2)/log(x))                                                                                                             
Out[6]: 2
```

However `abs(x)` is always positive and `simplify` doesn't realise that:
```julia
In [8]: x = Symbol('x')                                                                                                                        

In [9]: simplify(log(abs(x)**2)/log(abs(x)))                                                                                                   
Out[9]: 
   ⎛   2⎞
log⎝│x│ ⎠
─────────
 log(│x│)
```

I would like to be able to simplify expressions like this:
```julia
In [11]: simplify(log(abs(x**2))/log(abs(x)))                                                                                                  
Out[11]: 
   ⎛│ 2│⎞
log⎝│x │⎠
─────────
 log(│x│)

In [17]: simplify(log(1+x)/log(1+2*x + x**2))                                                                                                  
Out[17]: 
    log(x + 1)   
─────────────────
   ⎛ 2          ⎞
log⎝x  + 2⋅x + 1⎠

In [20]: simplify(log(abs(1+x))/log(abs(1+2*x + x**2)))                                                                                        
Out[20]: 
    log(│x + 1│)   
───────────────────
   ⎛│ 2          │⎞
log⎝│x  + 2⋅x + 1│⎠
```

### PR DESCRIPTION
**Pull request by jmig5776**
#### References to other Issues or PRs

Fixes #15854 

#### Brief description of what is fixed or changed
No Entry
#### Release Notes

* simplify
  * fixed docstring of `logcombine` function of simplify

### CODE REVIEW

**Comment by jmig5776** [comment]
@oscarbenjamin In this PR earlier logcombine was returning
```
x = Symbol('x')
logcombine(log(x**2)/log(x))
   ⎛ 2⎞
log⎝x ⎠
───────
 log(x)
```
And now it is returning
```
x = Symbol('x')
logcombine(log(x**2)/log(x))
log((x**2)**(1/log(x)))
```
I tried to get it simplified to but dont know how this is solving here in `logcombine`
```
# in logcombine function
for k in list(log1.keys()):
            log1[Mul(*k)] = log(logcombine(Mul(*[
                l.args[0]**Mul(*c) for c, l in log1.pop(k)]),
                force=force), evaluate=False)
```

**Comment by oscarbenjamin** [comment]
In general we can't simplify `log(x**2)/log(x)` to 2 because `x` might be negative and:
```
In [17]: log(2**2)/log(2)                                                                                                                      
Out[17]: 
log(4)
──────
log(2)

In [18]: _.evalf()                                                                                                                             
Out[18]: 2.00000000000000

In [19]: log((-2)**2)/log(-2)                                                                                                                  
Out[19]: 
   log(4)   
────────────
log(2) + ⅈ⋅π

In [20]: _.evalf()                                                                                                                             
Out[20]: 0.0928406470908163 - 0.42078724841586⋅ⅈ
```

So we can't do this if `x` is negative. The point is that `abs(x)` is not negative. Note that "not negative" means "zero or positive". There are 3 different cases for a real number: negative, zero, or positive. We also say non-zero, non-negative and non-positive which combine pairs of cases. Also SymPy uses tri-value logic: True, False, or None (for don't know).

Your patch allows log rules when the symbol is possibly negative because you say `if a.is_positive is not False` meaning it will happen when `a.is_positive is None`. That's not what we want: we want to use what we *do* know. In the case of `abs(x)` we know it is not negative but it could be zero. The current test is for `is_positive` which is None for `abs(x)` but `is_nonnegative` is True:
```julia
In [22]: x = Symbol('x')                                                                                                                       

In [23]: print(x.is_positive)                                                                                                                  
None

In [24]: print(abs(x).is_positive)                                                                                                             
None

In [25]: print(abs(x).is_negative)                                                                                                             
False

In [26]: print(abs(x).is_nonnegative)                                                                                                          
True
```

The docstring for `logcombine` says:
```
    Takes logarithms and combines them using the following rules:

    - log(x) + log(y) == log(x*y) if both are not negative
    - a*log(x) == log(x**a) if x is positive and a is real

    If ``force`` is True then the assumptions above will be assumed to hold if
    there is no assumption already in place on a quantity. For example, if
    ``a`` is imaginary or the argument negative, force will not perform a
    combination but if ``a`` is a symbol with no assumptions the change will
    take place.
```

The first rule says "if both are not negative" so maybe going to `is_nonnegative` would be allowable.

The difference between `is_positive` and `is_nonnegative` is the case where the value is zero. So we need to consider how that affects each rule.

**Comment by jmig5776** [comment]
@oscarbenjamin I had changed the condition to `a.is_nonnegative` .You can now verify it.

**Comment by smichr** [comment]
Can you demonstrate that the simplification holds if the argument is 0?

**Comment by jmig5776** [comment]
Okk @oscarbenjamin I read the comment by @normalhuman. I will only change the docstring.

**Comment by jmig5776** [comment]
@oscarbenjamin , @smichr I had fixed the docstring of `logcombine` .

**Pull request merged**
