### PR TITLE
Fix XXE vulnerability for mathml parser

### PR DESCRIPTION
**Pull request by sylee957**
#### Brief description of what is fixed or changed

As well as the fix originally suggested, 
I also added `etree.XSLTAccessControl.DENY_ALL` to transformer because there may be additional vulnerability.
https://rules.sonarsource.com/python/RSPEC-2755

#### Other comments

I reopened the fix from #25005 in proper fork.

#### Release Notes

- utilities
  - Fixed XXE security vulnerability for mathml parsers `mathml.apply_xsl, mathml.c2p`.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Looks good.

**Comment by asmeurer** [comment]
Just to give an idea of the impact, this function is never used anywhere else in SymPy outside of the tests. It also isn't publicly documented. I used GitHub code search and wasn't able to find any instances of this function in open source code. Of course, that doesn't mean no one uses it or has used it. It's quite common for people to find and use internal or undocumented SymPy functions.

**Comment by sylee957** [comment]
I think that the impact raises the opposite side, that they found vulnerability in `lxml` and try to encourage users to update the code.

**Comment by asmeurer** [comment]
I agree. Unfortunately, there are a lot of Python libraries that are "vulnerable by default", and it's difficult to change them because of backwards compatibility concerns. Another example is pyyaml, where `yaml.load` is unsafe by default and most people should really use `yaml.safe_load`.

That's why in https://github.com/sympy/sympy/pull/12524 I set safe=True as the default in sympify.

**Pull request merged**
