### PR TITLE
Complex and constant Theano code generation (revived #9187)

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

CLoses #9187

#### Brief description of what is fixed or changed
I decided to revive #9187 as it seemed useful and easy.

Complex variables are explicitly supported for Theano.
Constant functions do no longer generate a crash.
Explicit support for complex variables in codegen. I updated the comment as it seemed like rust does not support complex variables (although I just found https://autumnai.github.io/cuticula/num/complex/struct.Complex.html but do not know the status of that (hadn't even heard of rust before...))

#### Other comments
It seems like `sympy.utilities.codegen.COMPLEX_ALLOWED` is used to control the code generation's use of complex variables. Probably better to pass it through `codegen` but there may be a reason it is not done (have not analyzed the code that much).

As the FIXME says, one should probably add en exception for the case of explicitly complex variables and code generation in c or rust(?).

#### Release Notes

* printing
   * Theano printing now supports complex variables, conjugates and constant functions

* codegen
   * Fortran code generation now supports complex variables by default (COMPLEX*16)

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Not sure why the azure tests failed when the Travis tests passed. Closing and reopening to re-run the tests.

**Comment by oscarbenjamin** [comment]
Why does this need a `COMPLEX_ALLOWED` global and a `complex_allowed` keyword argument? Wouldn't one or the other be enough?

I guess that the keyword argument is preferable but it's difficult to implement because it would need to be added to `codegen` and propagated through all functions...

**Comment by oscargus** [comment]
I guess that is the case as well. Clearly propagating it would be the solution. Not sure how tedious it is though...

I'm not sure how it is detected if the data is complex nor how it is handled if there is complex data, but the language cannot handle it. (Basically, I have very limited clues about what is going on in the codegen part...)

**Comment by oscarbenjamin** [comment]
I think the code can be improved but it might not be easy to do.

This seems useful so I'll probably merge this soon if no one objects.

**Comment by oscargus** [comment]
As long that we are a bit cautious when merging future PRs that make use of the global variable (so that there are not even more places to change), I agree that this probably can be merged as it would extend the functionality in a useful way.

**Pull request merged**
