### PR TITLE
added test for issue #6913

### LINKED ISSUE #6913: Relations on MatrixElements are broken.
```
In sympy 0.7.2 this works:

from sympy import MatrixSymbol
m = MatrixSymbol('m', 1, 1)
print m[0,0] > 0

Output:

m_00 > 0

In current git master (e0241473):

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    print m[0,0] > 0
  File "/home/martin/repos/sympy/sympy/core/decorators.py", line 74, in __sympifyit_wrapper
    return func(a, b)
  File "/home/martin/repos/sympy/sympy/core/expr.py", line 270, in __gt__
    return C.StrictGreaterThan(self, other)
  File "/home/martin/repos/sympy/sympy/core/relational.py", line 163, in __new__
    know = diff.equals(0, failing_expression=True)
  File "/home/martin/repos/sympy/sympy/core/expr.py", line 581, in equals
    diff = factor_terms((self - other).simplify(), radical=True)
  File "/home/martin/repos/sympy/sympy/core/expr.py", line 2848, in simplify
    return simplify(self, ratio, measure)
  File "/home/martin/repos/sympy/sympy/simplify/simplify.py", line 3662, in simplify
    expr2 = shorter(together(expr, deep=True), together(expr1, deep=True))
  File "/home/martin/repos/sympy/sympy/simplify/simplify.py", line 3656, in shorter
    return min(choices, key=measure)
  File "/home/martin/repos/sympy/sympy/core/function.py", line 2111, in count_ops
    if a.is_Rational:
AttributeError: 'str' object has no attribute 'is_Rational'
```

Original issue for #6913: http://code.google.com/p/sympy/issues/detail?id=3814
Original author: https://code.google.com/u/109245403590460788029/

### PR DESCRIPTION
**Pull request by RituRajSingh878**
#### References to other Issues or PRs

Fixes #6913

#### Brief description of what is fixed or changed

Issue is working fine in sympy master .
But it is not tested in sympy master
So I have to add test only.

#### Release Notes

- other
  - added test case for above issue.

### CODE REVIEW

**Comment by RituRajSingh878** [comment]
@asmeurer  you can check it now.

**Comment by oscarbenjamin** [comment]
Looks like the tests failed. If you click the details button below you can see the different test runs. Clicking through there you can see the test logs which tell you what failed.

Some failures are due to trailing whitespace. Others are due to missing imports.

**Comment by oscargus** [comment]
Should be possible to tick a box in #15121 once merged. Looks good to me.

**Comment by smichr** [comment]
box is ticked and this is merged

**Comment by asmeurer** [comment]
@RituRajSingh878 your release notes entries should be self contained. Right now, the release notes just has an entry that says

* other
  * added test case for above issue. (#15960 by @RituRajSingh878)

which makes no sense. Also `other` should only be used for changes that aren't related to a submodule, and tests only changes don't need a release notes entry. Please read https://github.com/sympy/sympy/wiki/Writing-Release-Notes.

**Comment by asmeurer** [comment]
Also reviewers, please check the release notes before merging.

**Pull request merged**
