### PR TITLE
LUsolve now propagates iszerofunc properly.

### PR DESCRIPTION
**Pull request by moorepants**
#### References to other Issues or PRs

Fixes an issue mentioned here https://github.com/sympy/sympy/issues/24679#issuecomment-1468017766. Implements @oscarbenjamin's suggestion.

#### Brief description of what is fixed or changed

LUsolve ignored the iszerofunc and now it does not.

#### Release Notes

* matrices
  * Fixed bug where LUsolve() ignored the iszerofunc kwarg.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This should solve the division by zero problems seen in mechanics problems if used there but it would make LUsolve slower because of slow `evalf` with large expressions.

**Comment by moorepants** [comment]
> This should solve the division by zero problems seen in mechanics problems if used there but it would make LUsolve slower because of slow evalf with large expressions.

I'm not completely sure that it will because A and b in A*x=b in the linear system have entries that are nonlinear functions of some variables, where some of the variables can certainly be zero and even simultaneously zero. We even know this up front. I'm thinking that we need to plug in zero for the variables we know can simultaneously be zero and then solve the linear system. Passing in random values only really checks that we don't have an expression that is always zero (i.e. didn't simplify symbolically).

**Comment by oscarbenjamin** [comment]
> Passing in random values only really checks that we don't have an expression that is always zero (i.e. didn't simplify symbolically).

It is checking whether the division is by something that is identically zero (for all possible values of the symbols) so the result is a solution that is valid for generic values of the symbols. Of course of you take the single division approach like Carmer's rule or dividing only by the determinant then you know the result would be valid for all values of the parameters such that the determinant is not zero.

> I'm thinking that we need to plug in zero for the variables we know can simultaneously be zero and then solve the linear system

We have e.g.:
```python
In [4]: M = Matrix([[x, y], [z, t]])

In [5]: M
Out[5]: 
⎡x  y⎤
⎢    ⎥
⎣z  t⎦

In [6]: M.LUsolve(Matrix([m, n]))
Out[6]: 
⎡      ⎛  m⋅z    ⎞⎤
⎢    y⋅⎜- ─── + n⎟⎥
⎢      ⎝   x     ⎠⎥
⎢m - ─────────────⎥
⎢           y⋅z   ⎥
⎢       t - ───   ⎥
⎢            x    ⎥
⎢─────────────────⎥
⎢        x        ⎥
⎢                 ⎥
⎢      m⋅z        ⎥
⎢    - ─── + n    ⎥
⎢       x         ⎥
⎢    ─────────    ⎥
⎢         y⋅z     ⎥
⎢     t - ───     ⎥
⎣          x      ⎦
```
Here there have been a division by `x` and then a division by `t - y*z/x`. The later is related to the determinant `x*t - y*z` but the intermediate division by x means that you have not *only* divided by the determinant but also by `x` which be valid apart from the degenerate case where `x=0`. The product of the two divisors is the determinant but only if you allow `x/x` to cancel.

The solver in gh-16861 can find all possible forms of the solution set (note that it is a lot faster if you remove the `simplify_logic` calls):
```python
In [32]: syms = symbols('x:2')

In [33]: sol = linsolve_cond(M*Matrix(syms)-Matrix([m, n]), syms)

In [34]: for sol, cond in sol.args:
    ...:     print(cond)
    ...:     pprint(sol)
    ...:     print()
    ...: 
Ne(x, 0) & Ne(t*x - y*z, 0)
⎧⎛    y⋅(-m⋅z + n⋅x)            ⎞⎫
⎪⎜m - ──────────────            ⎟⎪
⎨⎜      t⋅x - y⋅z     -m⋅z + n⋅x⎟⎬
⎪⎜──────────────────, ──────────⎟⎪
⎩⎝        x           t⋅x - y⋅z ⎠⎭

Ne(x, 0) & Eq(m*z - n*x, 0) & Eq(t*x - y*z, 0)
⎧⎛m - τ₀⋅y    ⎞ │       ⎫
⎨⎜────────, τ₀⎟ │ τ₀ ∊ ℂ⎬
⎩⎝   x        ⎠ │       ⎭

Eq(x, 0) & Ne(y, 0) & Ne(z, 0)
⎧⎛  m⋅t       ⎞⎫
⎪⎜- ─── + n   ⎟⎪
⎨⎜   y       m⎟⎬
⎪⎜─────────, ─⎟⎪
⎩⎝    z      y⎠⎭

Eq(m, 0) & Eq(x, 0) & Eq(y, 0) & Ne(z, 0)
⎧⎛n - t⋅τ₀    ⎞ │       ⎫
⎨⎜────────, τ₀⎟ │ τ₀ ∊ ℂ⎬
⎩⎝   z        ⎠ │       ⎭

Eq(x, 0) & Eq(z, 0) & Ne(y, 0) & Eq(m*t - n*y, 0)
⎧⎛    m⎞ │       ⎫
⎨⎜τ₀, ─⎟ │ τ₀ ∊ ℂ⎬
⎩⎝    y⎠ │       ⎭

Eq(m, 0) & Eq(x, 0) & Eq(y, 0) & Eq(z, 0) & Ne(t, 0)
⎧⎛    n⎞ │       ⎫
⎨⎜τ₀, ─⎟ │ τ₀ ∊ ℂ⎬
⎩⎝    t⎠ │       ⎭

(Eq(x, 0) & Eq(y, 0) & Ne(m, 0) & Ne(z, 0)) | (Eq(x, 0) & Eq(y, 0) & Eq(z, 0) & Ne(m, 0) & Ne(t, 0)) | (Eq(x, 0) & Eq(z, 0) & Ne(y, 0) & Ne(m*t - n*y, 0)) | (Eq(t, 0) & Eq(x, 0) & Eq(y, 0) & Eq(z, 0) & ~(Eq(m, 0) & Eq(n, 0))) | (Ne(x, 0) & Eq(t*x - y*z, 0) & Ne(m*z - n*x, 0))
∅

Eq(m, 0) & Eq(n, 0) & Eq(t, 0) & Eq(x, 0) & Eq(y, 0) & Eq(z, 0)
 2
ℂ 
```
If you only want the cases where there is a unique solution then that filters down to two cases (the method could be adjusted to avoid computing any of the other cases):
```python
Ne(x, 0) & Ne(t*x - y*z, 0)
⎧⎛    y⋅(-m⋅z + n⋅x)            ⎞⎫
⎪⎜m - ──────────────            ⎟⎪
⎨⎜      t⋅x - y⋅z     -m⋅z + n⋅x⎟⎬
⎪⎜──────────────────, ──────────⎟⎪
⎩⎝        x           t⋅x - y⋅z ⎠⎭

Eq(x, 0) & Ne(y, 0) & Ne(z, 0)
⎧⎛  m⋅t       ⎞⎫
⎪⎜- ─── + n   ⎟⎪
⎨⎜   y       m⎟⎬
⎪⎜─────────, ─⎟⎪
⎩⎝    z      y⎠⎭
```
The first case is valid provided `x != 0`. The second case is valid also if `x = 0` but provided that `y` and `z` are both nonzero. Note that if `x=0` and either `y` or `z` is zero then the determinant `t*x - y*z` is zero. These two cases therefore cover all possibilities for a unique solution but are computed using essentially the same operations as LUsolve and so have the same op counts etc. At the end if you want to substitute values for the symbols such as `x = 0` you can substitute those values into the conditions to see if they resolve to true or false and then that tells you which form of the solution is valid.

It can be a single case if just using Cramer's rule or the adjugate and determinant:
```python
In [35]: M.det()
Out[35]: t⋅x - y⋅z

In [36]: (M.adjugate() / M.det()) * Matrix([m, n])
Out[36]: 
⎡    m⋅t         n⋅y    ⎤
⎢ ───────── - ───────── ⎥
⎢ t⋅x - y⋅z   t⋅x - y⋅z ⎥
⎢                       ⎥
⎢     m⋅z         n⋅x   ⎥
⎢- ───────── + ─────────⎥
⎣  t⋅x - y⋅z   t⋅x - y⋅z⎦
```
The disadvantage of this though is that the op count doesn't scale in the same way for larger systems.

**Comment by oscarbenjamin** [comment]
You can see if you look at the conditions generated above that they are mostly about whether or not some particular symbol is zero so setting lots of symbols to zero is quite likely to lead to the generic case not being applicable. You might know ahead of time that there are say two cases:

1. A case where lots of things are set to zero.
2. A case where none of those things is zero.

In that case it is better just to do two separate solves.

**Comment by oscarbenjamin** [comment]
This is what it looks like if you apply the method from gh-16861 to a 3x3 system of arbitrary symbols (you could expect better results for a matrix that has some structure):
```python
In [72]: M = Matrix(symbols('M:9')).reshape(3, 3)
    ...: xs = Matrix(symbols('x:3'))
    ...: b = Matrix(symbols('b:3'))
    ...: sol3 = linsolve_cond(list(M*xs - b), list(xs), unique=True)

In [73]: for e, c in sol3.args:
    ...:     pprint(c)
    ...:     pprint(e)
    ...:     print()
    ...: 
M₀ = 0 ∧ M₃ = 0 ∧ M₄ = 0 ∧ M₁ ≠ 0 ∧ M₅ ≠ 0 ∧ M₆ ≠ 0
⎧⎛                ⎛  M₂⋅b₁     ⎞                  ⎞⎫
⎪⎜             M₇⋅⎜- ───── + b₀⎟                  ⎟⎪
⎪⎜     M₈⋅b₁      ⎝    M₅      ⎠    M₂⋅b₁         ⎟⎪
⎨⎜b₂ - ───── - ─────────────────  - ───── + b₀    ⎟⎬
⎪⎜       M₅            M₁             M₅        b₁⎟⎪
⎪⎜──────────────────────────────, ────────────, ──⎟⎪
⎩⎝              M₆                     M₁       M₅⎠⎭

M₀ = 0 ∧ M₃ = 0 ∧ M₄ ≠ 0 ∧ M₆ ≠ 0 ∧ M₁⋅M₅ - M₂⋅M₄ ≠ 0
⎧⎛                                ⎛  M₅⋅(-M₁⋅b₁ + M₄⋅b₀)     ⎞                                            ⎞⎫
⎪⎜                             M₇⋅⎜- ─────────────────── + b₁⎟                                            ⎟⎪
⎪⎜  M₈⋅(-M₁⋅b₁ + M₄⋅b₀)           ⎝     -M₁⋅M₅ + M₂⋅M₄       ⎠    M₅⋅(-M₁⋅b₁ + M₄⋅b₀)                     ⎟⎪
⎨⎜- ─────────────────── + b₂ - ───────────────────────────────  - ─────────────────── + b₁                ⎟⎬
⎪⎜     -M₁⋅M₅ + M₂⋅M₄                         M₄                     -M₁⋅M₅ + M₂⋅M₄         -M₁⋅b₁ + M₄⋅b₀⎟⎪
⎪⎜────────────────────────────────────────────────────────────, ──────────────────────────, ──────────────⎟⎪
⎩⎝                             M₆                                           M₄              -M₁⋅M₅ + M₂⋅M₄⎠⎭

M₀ = 0 ∧ M₁ = 0 ∧ M₂ ≠ 0 ∧ M₃ ≠ 0 ∧ M₃⋅M₇ - M₄⋅M₆ ≠ 0
⎧⎛     ⎛                b₀⋅(M₃⋅M₈ - M₅⋅M₆)⎞                                                     ⎞⎫
⎪⎜  M₄⋅⎜M₃⋅b₂ - M₆⋅b₁ - ──────────────────⎟                                                     ⎟⎪
⎪⎜     ⎝                        M₂        ⎠        M₅⋅b₀                  b₀⋅(M₃⋅M₈ - M₅⋅M₆)    ⎟⎪
⎨⎜- ─────────────────────────────────────── + b₁ - ─────  M₃⋅b₂ - M₆⋅b₁ - ──────────────────    ⎟⎬
⎪⎜               M₃⋅M₇ - M₄⋅M₆                       M₂                           M₂          b₀⎟⎪
⎪⎜──────────────────────────────────────────────────────, ──────────────────────────────────, ──⎟⎪
⎩⎝                          M₃                                      M₃⋅M₇ - M₄⋅M₆             M₂⎠⎭

M₀ = 0 ∧ M₁ ≠ 0 ∧ M₃ ≠ 0 ∧ M₁⋅(M₃⋅M₈ - M₅⋅M₆) - M₂⋅(M₃⋅M₇ - M₄⋅M₆) ≠ 0
⎧⎛                                                         ⎛  M₂⋅(M₁⋅(M₃⋅b₂ - M₆⋅b₁) - b₀⋅(M₃⋅M₇ - M₄⋅M₆))     ⎞                                                                                              ⎞⎫
⎪⎜                                                      M₄⋅⎜- ──────────────────────────────────────────── + b₀⎟                                                                                              ⎟⎪
⎪⎜  M₅⋅(M₁⋅(M₃⋅b₂ - M₆⋅b₁) - b₀⋅(M₃⋅M₇ - M₄⋅M₆))           ⎝    M₁⋅(M₃⋅M₈ - M₅⋅M₆) - M₂⋅(M₃⋅M₇ - M₄⋅M₆)        ⎠    M₂⋅(M₁⋅(M₃⋅b₂ - M₆⋅b₁) - b₀⋅(M₃⋅M₇ - M₄⋅M₆))                                              ⎟⎪
⎨⎜- ──────────────────────────────────────────── + b₁ - ────────────────────────────────────────────────────────  - ──────────────────────────────────────────── + b₀                                         ⎟⎬
⎪⎜    M₁⋅(M₃⋅M₈ - M₅⋅M₆) - M₂⋅(M₃⋅M₇ - M₄⋅M₆)                                      M₁                                 M₁⋅(M₃⋅M₈ - M₅⋅M₆) - M₂⋅(M₃⋅M₇ - M₄⋅M₆)          M₁⋅(M₃⋅b₂ - M₆⋅b₁) - b₀⋅(M₃⋅M₇ - M₄⋅M₆)⎟⎪
⎪⎜──────────────────────────────────────────────────────────────────────────────────────────────────────────────, ───────────────────────────────────────────────────, ───────────────────────────────────────⎟⎪
⎩⎝                                                      M₃                                                                                 M₁                          M₁⋅(M₃⋅M₈ - M₅⋅M₆) - M₂⋅(M₃⋅M₇ - M₄⋅M₆)⎠⎭

M₀⋅M₄ - M₁⋅M₃ = 0 ∧ M₀ ≠ 0 ∧ M₀⋅M₅ - M₂⋅M₃ ≠ 0 ∧ M₀⋅M₇ - M₁⋅M₆ ≠ 0
⎧⎛     ⎛                (M₀⋅M₈ - M₂⋅M₆)⋅(M₀⋅b₁ - M₃⋅b₀)⎞                                                                                          ⎞⎫
⎪⎜  M₁⋅⎜M₀⋅b₂ - M₆⋅b₀ - ───────────────────────────────⎟                                                                                          ⎟⎪
⎪⎜     ⎝                         M₀⋅M₅ - M₂⋅M₃         ⎠   M₂⋅(M₀⋅b₁ - M₃⋅b₀)                       (M₀⋅M₈ - M₂⋅M₆)⋅(M₀⋅b₁ - M₃⋅b₀)               ⎟⎪
⎨⎜- ──────────────────────────────────────────────────── - ────────────────── + b₀  M₀⋅b₂ - M₆⋅b₀ - ───────────────────────────────               ⎟⎬
⎪⎜                     M₀⋅M₇ - M₁⋅M₆                         M₀⋅M₅ - M₂⋅M₃                                   M₀⋅M₅ - M₂⋅M₃           M₀⋅b₁ - M₃⋅b₀⎟⎪
⎪⎜────────────────────────────────────────────────────────────────────────────────, ───────────────────────────────────────────────, ─────────────⎟⎪
⎩⎝                                       M₀                                                          M₀⋅M₇ - M₁⋅M₆                   M₀⋅M₅ - M₂⋅M₃⎠⎭

M₀ ≠ 0 ∧ M₀⋅M₄ - M₁⋅M₃ ≠ 0 ∧ (M₀⋅M₄ - M₁⋅M₃)⋅(M₀⋅M₈ - M₂⋅M₆) - (M₀⋅M₅ - M₂⋅M₃)⋅(M₀⋅M₇ - M₁⋅M₆) ≠ 0
⎧⎛     ⎛                (M₀⋅M₅ - M₂⋅M₃)⋅((M₀⋅M₄ - M₁⋅M₃)⋅(M₀⋅b₂ - M₆⋅b₀) - (M₀⋅M₇ - M₁⋅M₆)⋅(M₀⋅b₁ - M₃⋅b₀))⎞                                                                                                                                                                                                                                                      ⎞⎫
⎪⎜  M₁⋅⎜M₀⋅b₁ - M₃⋅b₀ - ───────────────────────────────────────────────────────────────────────────────────⎟                                                                                                                                                                                                                                                      ⎟⎪
⎪⎜     ⎝                         (M₀⋅M₄ - M₁⋅M₃)⋅(M₀⋅M₈ - M₂⋅M₆) - (M₀⋅M₅ - M₂⋅M₃)⋅(M₀⋅M₇ - M₁⋅M₆)         ⎠   M₂⋅((M₀⋅M₄ - M₁⋅M₃)⋅(M₀⋅b₂ - M₆⋅b₀) - (M₀⋅M₇ - M₁⋅M₆)⋅(M₀⋅b₁ - M₃⋅b₀))                       (M₀⋅M₅ - M₂⋅M₃)⋅((M₀⋅M₄ - M₁⋅M₃)⋅(M₀⋅b₂ - M₆⋅b₀) - (M₀⋅M₇ - M₁⋅M₆)⋅(M₀⋅b₁ - M₃⋅b₀))                                                                   ⎟⎪
⎨⎜- ──────────────────────────────────────────────────────────────────────────────────────────────────────── - ────────────────────────────────────────────────────────────────────── + b₀  M₀⋅b₁ - M₃⋅b₀ - ───────────────────────────────────────────────────────────────────────────────────                                                                   ⎟⎬
⎪⎜                                               M₀⋅M₄ - M₁⋅M₃                                                   (M₀⋅M₄ - M₁⋅M₃)⋅(M₀⋅M₈ - M₂⋅M₆) - (M₀⋅M₅ - M₂⋅M₃)⋅(M₀⋅M₇ - M₁⋅M₆)                                   (M₀⋅M₄ - M₁⋅M₃)⋅(M₀⋅M₈ - M₂⋅M₆) - (M₀⋅M₅ - M₂⋅M₃)⋅(M₀⋅M₇ - M₁⋅M₆)           (M₀⋅M₄ - M₁⋅M₃)⋅(M₀⋅b₂ - M₆⋅b₀) - (M₀⋅M₇ - M₁⋅M₆)⋅(M₀⋅b₁ - M₃⋅b₀)⎟⎪
⎪⎜────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────, ───────────────────────────────────────────────────────────────────────────────────────────────────, ─────────────────────────────────────────────────────────────────⎟⎪
⎩⎝                                                                                           M₀                                                                                                                                        M₀⋅M₄ - M₁⋅M₃                                             (M₀⋅M₄ - M₁⋅M₃)⋅(M₀⋅M₈ - M₂⋅M₆) - (M₀⋅M₅ - M₂⋅M₃)⋅(M₀⋅M₇ - M₁⋅M₆)⎠⎭
```
The final case here is the generic case where all conditions are `Ne` conditions. There are lots of other cases though corresponding to different combinations of different symbols being zero or not.

Essentially as the system grows in size with more and more symbols then the number of possible ways for things to be zero or not zero grows exponentially. If you happen to know ahead of time that there are only two cases (everything zero or everything not zero) then doing a separate solve for each will be better than trying to symbolically find all cases.

**Pull request merged**
