### PR TITLE
Fix the Circle CI status

### PR DESCRIPTION
**Pull request by asmeurer**
This is a continuation of https://github.com/sympy/sympy/pull/23732 and https://github.com/sympy/sympy/pull/23801 based on the instructions at https://github.com/larsoner/circleci-artifacts-redirector-action/pull/32.

Assuming it works this time, it will fix
https://github.com/sympy/sympy/issues/23784 (but there's no way to know if it works until merging it).

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
@brandonwillard we seem to be seeing an issue with Aesara 2.8.3 here:
```
__________ sympy/core/tests/test_args.py:test_all_classes_are_tested ___________
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/core/tests/test_args.py", line 64, in test_all_classes_are_tested
    mod = __import__(submodule, fromlist=names)
  File "/home/runner/work/sympy/sympy/sympy/printing/aesaracode.py", line 68, in <module>
    sympy.Transpose: DimShuffle((False, False), [1, 0]),
  File "/opt/hostedtoolcache/PyPy/3.8.13/x64/lib/pypy3.8/site-packages/aesara/tensor/elemwise.py", line 130, in __init__
    super().__init__([self.c_func_file], self.c_func_name)
  File "/opt/hostedtoolcache/PyPy/3.8.13/x64/lib/pypy3.8/site-packages/aesara/link/c/op.py", line 334, in __init__
    self.load_c_code(self.func_files)
  File "/opt/hostedtoolcache/PyPy/3.8.13/x64/lib/pypy3.8/site-packages/aesara/link/c/op.py", line [355](https://github.com/sympy/sympy/actions/runs/3048829005/jobs/4914325450#step:17:356), in load_c_code
    with open(func_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/PyPy/3.8.13/x64/lib/pypy3.8/site-packages/aesara/tensor/c_code/dimshuffle.c'
```

**Comment by oscarbenjamin** [comment]
To reproduce:
```console
$ pytest sympy/core/tests/test_args.py 
======================================== test session starts ========================================
platform linux -- Python 3.8.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
architecture: 64-bit
cache:        yes
ground types: gmpy 2.1.2

rootdir: /home/oscar/current/sympy/sympy.git, configfile: pytest.ini
plugins: benchmark-3.4.1, forked-1.3.0, cov-3.0.0, instafail-0.4.2, xdist-2.4.0, anyio-3.5.0, doctestplus-0.12.0
collected 985 items                                                                                 

sympy/core/tests/test_args.py F..s..s..sss................................................... [  6%]
.........................sss............s................s........s.ss....s...............s.. [ 15%]
........................ss...........sss.....s.s........................ss................... [ 25%]
............................................................................................. [ 34%]
....s...............................s...sss............s......s...sss..............sss....... [ 44%]
.......................s......s.....................ss..s............s....................... [ 53%]
s....s..s....s.............s.s.............ss........s....................................s.. [ 63%]
.......................................................................................s..... [ 72%]
..........................................s..s...s...................................s....s.s [ 81%]
......s....s.....s..............s...s.............s...s...s........s................s........ [ 91%]
.....................................................................................         [100%]

============================================= FAILURES ==============================================
____________________________________ test_all_classes_are_tested ____________________________________

    def test_all_classes_are_tested():
        this = os.path.split(__file__)[0]
        path = os.path.join(this, os.pardir, os.pardir)
        sympy_path = os.path.abspath(path)
        prefix = os.path.split(sympy_path)[0] + os.sep
    
        re_cls = re.compile(r"^class ([A-Za-z][A-Za-z0-9_]*)\s*\(", re.MULTILINE)
    
        modules = {}
    
        for root, dirs, files in os.walk(sympy_path):
            module = root.replace(prefix, "").replace(os.sep, ".")
    
            for file in files:
                if file.startswith(("_", "test_", "bench_")):
                    continue
                if not file.endswith(".py"):
                    continue
    
                with open(os.path.join(root, file), encoding='utf-8') as f:
                    text = f.read()
    
                submodule = module + '.' + file[:-3]
    
                if any(submodule.startswith(wpath) for wpath in whitelist):
                    continue
    
                names = re_cls.findall(text)
    
                if not names:
                    continue
    
                try:
>                   mod = __import__(submodule, fromlist=names)

sympy/core/tests/test_args.py:64: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
sympy/printing/aesaracode.py:68: in <module>
    sympy.Transpose: DimShuffle((False, False), [1, 0]),
38venv/lib/python3.8/site-packages/aesara/tensor/elemwise.py:130: in __init__
    super().__init__([self.c_func_file], self.c_func_name)
38venv/lib/python3.8/site-packages/aesara/link/c/op.py:334: in __init__
    self.load_c_code(self.func_files)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <aesara.tensor.elemwise.DimShuffle object at 0x7efc57119850>
func_files = ['/home/oscar/current/sympy/sympy.git/38venv/lib/python3.8/site-packages/aesara/tensor/c_code/dimshuffle.c']

    def load_c_code(self, func_files: List[str]) -> None:
        """Loads the C code to perform the `Op`."""
        func_files = [self.get_path(f) for f in func_files]
        for func_file in func_files:
>           with open(func_file) as f:
E           FileNotFoundError: [Errno 2] No such file or directory: '/home/oscar/current/sympy/sympy.git/38venv/lib/python3.8/site-packages/aesara/tensor/c_code/dimshuffle.c'

38venv/lib/python3.8/site-packages/aesara/link/c/op.py:355: FileNotFoundError
                                          DO *NOT* COMMIT!                                          
====================================== short test summary info ======================================
FAILED sympy/core/tests/test_args.py::test_all_classes_are_tested - FileNotFoundError: [Errno 2] N...
============================= 1 failed, 914 passed, 70 skipped in 7.80s =============================
```

**Comment by brandonwillard** [comment]
> @brandonwillard we seem to be seeing an issue with Aesara 2.8.3 here:

Looks like there might be some package data is missing?  @maresb have we seen anything like this elsewhere?

**Comment by oscarbenjamin** [comment]
> Looks like there might be some missing package data

Note that the errors only show for PyPy and for CPython 3.11 and not for CPython 3.9 or 3.10. You can see the configuration that sets this up here:
https://github.com/sympy/sympy/blob/81389e46355b5be5de575b10170466ac93d76e1b/.github/workflows/runtests.yml#L167-L225

**Comment by brandonwillard** [comment]
> Note that the errors only show for PyPy and for CPython 3.11 and not for CPython 3.9 or 3.10.

Oh, that does sound like a familiar issue.

**Comment by maresb** [comment]
This particular issue doesn't look familiar to me. Conda-forge doesn't build for CPython 3.11 yet, and the PyPy issues we had were more related to us building for PyPy 3.7 while the rest of conda-forge had moved on to 3.8/3.9.

**Comment by brandonwillard** [comment]
> This particular issue doesn't look familiar to me. Conda-forge doesn't build for CPython 3.11 yet, and the PyPy issues we had were more related to us building for PyPy 3.7 while the rest of conda-forge had moved on to 3.8/3.9.

Ah, I thought the PyPy issue might've been related, but it looks like the real problem/solution may be this: https://github.com/aesara-devs/aesara/issues/1182.

**Comment by asmeurer** [comment]
I'm not really sure this fixed it https://github.com/sympy/sympy/actions CC @larsoner

**Comment by brandonwillard** [comment]
FYI: We just cut a release that should provide a fix for the Aesara issue: https://github.com/aesara-devs/aesara/releases/tag/rel-2.8.4

**Comment by oscarbenjamin** [comment]
Thanks @brandonwillard and @maresb! Another CI job shows these tests as passing with Aesara 2.8.4 now.

**Comment by brandonwillard** [comment]
> Thanks @brandonwillard and @maresb! Another CI job shows these tests as passing with Aesara 2.8.4 now.

To be precise, @eganster generously provided this fix.

**Pull request merged**
