### PR TITLE
Make Function('f', real=True) work

### PR DESCRIPTION
**Pull request by asmeurer**
Also has some cleanups to the core to make things work. See the commit messages.

### CODE REVIEW

**Comment by smichr** [comment]
+1, but maybe others with more understanding want to comment.

**Comment by asmeurer** [comment]
Don't know who else would. I'll leave it open a bit and see if anyone comments.

**Comment by smichr** [comment]
How will this behave wrt commutativity? I know the same commutativity method will aaply as in master, but will that be overridden by a direct assumption now? Does `Function('f', commutative=True)(var('n', commutative=False)).is_commutative -> True`?

**Comment by asmeurer** [comment]
Weird behavior here

```py
>>> Function('f', commutative=False)(Symbol('x', commutative=False)).is_commutative
False
>>> Function('f')(Symbol('x', commutative=False)).is_commutative
False
>>> Function('f')(Symbol('x', commutative=True)).is_commutative
True
>>> Function('f')(Symbol('x')).is_commutative
True
```

Compare to `real`:

```py
>>> Function('f', real=True)(Symbol('x')).is_real
True
>>> Function('f', real=True)(Symbol('x', real=False)).is_real
True
>>> Function('f')(Symbol('x', real=False)).is_real
>>> Function('f')(Symbol('x', real=True)).is_real
>>>
```

With normal (not `commutative`) assumptions, the assumption on the function is the only thing that matter. 

But with commutative, apparently it takes it from the argument when it isn't defined. I would have expected it to default to `True`, like with Symbol. 

When you define it, it overrides it. That's expected, because setting `commutative=True` is basically equivalent to writing

```py
class f(Function):
    is_commutative = True
```

(see https://github.com/sympy/sympy/pull/12945/files#diff-df6e27def8b4f219ead0c9b48a032d66R793)

**Comment by asmeurer** [comment]
Oh, it's because it's [defined that way](https://github.com/sympy/sympy/blob/34d83416b3e0223b4e8abaa582416812719b81da/sympy/core/function.py#L565) in the `Function` superclass. So changing this would be a matter or removing that method. I think it's orthogonal to this change.

**Comment by smichr** [comment]
Note also that the [`is_commutative`](https://github.com/sympy/sympy/blob/34d83416b3e0223b4e8abaa582416812719b81da/sympy/core/function.py#L491) method is also explicitly defined.

> I think it's orthogonal to this change.

OK, so let's commit this.

**Comment by asmeurer** [comment]
> Note also that the is_commutative method is also explicitly defined.

It shouldn't be done that way, from what I know. The `is_assumption` methods can be assigned an explicit value, but it's better to put a computation in an `_eval_assumption` method. I would be happy to see them both go for `commutative`.

**Comment by moorepants** [comment]
This seems to have made a speed regression in subs:

http://www.moorepants.info/misc/sympy-asv/#large_exprs.TimeLargeExpressionOperations.time_subs

**Comment by moorepants** [comment]
Also seen here: http://www.moorepants.info/misc/sympy-asv/#logic.LogicSuite.time_load_file

**Comment by asmeurer** [comment]
I'm aware of speed regressions here in Python 2. They should be fixed when https://github.com/sympy/sympy/pull/13059 is finished, but I haven't had time to work on it.

**Pull request merged**
