### PR TITLE
Added condition for base_vectors() pretty printing 

### PR DESCRIPTION
**Pull request by manipalsingh013**
issue #10044. pprint for base_vectors() handled by adding condition for base_vectors() in which case output for pretty printing is first converted to string so that height function in https://github.com/manipalsingh013/sympy/blob/master/sympy/printing/pretty/stringpict.py#L47 does not have to evaluate for fake object.

Output getting after adding condition:

> > > from sympy.vector import *
> > > from sympy import *
> > > N=CoordSysCartesian('N')
> > > pprint(N.base_vectors())
> > > (N.i, N.j, N.k)

### CODE REVIEW

**Comment by moorepants** [comment]
For pretty printing it could be cool to use subscripts for i, j, and k. And since they are all vectors, maybe bold the main value or put a hat on them. Unit vectors often have a hat.

**Comment by manipalsingh013** [comment]
@moorepants  can you guide me how to that.

**Comment by moorepants** [comment]
Have a look at the pretty printing code in the sympy.physics.vector package for ideas.

**Comment by manipalsingh013** [comment]
I think that is related with issue #10070 but I was just trying it solve for issue #10044 in which error appeared on pretty printing base_vectors() of CoordSysCartesian

**Comment by manipalsingh013** [comment]
@asmeurer @moorepants was the issue #10044 not about solving it for error, and issue #10070 about adding printing packages to vectors.

**Comment by moorepants** [comment]
Seems like there is a fix in #10084

**Pull request closed without merging**
