### PR TITLE
Introduce evaluate option for xreplace

### LINKED ISSUE #11837: broken xreplace
xreplace ends up expanding the common factor 2.5 in the following example (and similarly in all analogous cases):

```
In [19]: Mul(2.5, a + b)
Out[19]: 2.5*a + 2.5*b

In [19]: Mul(2.5, a + b, evaluate=False)
Out[19]: 2.5*(a + b)

In [20]: Mul(2.5, a + b, evaluate=False).xreplace({a: c})
Out[20]: 2.5*b + 2.5*c
```

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References to other Issues or PRs

Fixes #11837
Closes #11848 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
There are also a couple more xreplace methods in functions and matrices.

**Comment by asmeurer** [comment]
Not all constructors support evaluate. I think this feature shouldn't be part of xreplace.

**Comment by oscarbenjamin** [comment]
> Not all constructors support evaluate.

That is something that should be fixed but it isn't a small task (#17280)

> I think this feature shouldn't be part of xreplace.

I can see the argument that there should be some version of xreplace that doesn't do any evaluation.

**Comment by asmeurer** [comment]
If so I would have a separate function to do it. Having it in xreplace would complicate the logic too much, and it's supposed to be a fast lower level operation. Unevaluated forms get messy really quick in SymPy.  

Anyway, can't the user just do

```py
with evaluate(False):
    expr.xreplace(repl)
```

**Comment by czgdp1807** [comment]
I am trying to fix the original issue in a different manner to keep the original API intact.

**Comment by czgdp1807** [comment]
I tried things out. The main problem is, that it is not possible to determine, whether the object was originally created using `evaluate=False` or `evaluate=True`, so we cannot pass evaluate to `self.func(*args)`. It is too costly to change the things. Using, `with evaluate` is a better option. 
I think that both PRs and issue can be closed.

**Comment by czgdp1807** [comment]
ping @oscarbenjamin @asmeurer Any objections on closing this PR, the other PR and the issue?

**Comment by oscarbenjamin** [comment]
I think they can be closed

**Comment by czgdp1807** [comment]
Closing the PR.

**Pull request closed without merging**
