### PR TITLE
printers: Extract common codes in LaTeXPrinter

### LINKED ISSUE #14044: Extract common codes from printers
(i) Printers have similar methods to print similar functions. For example, `_print_Min` and `_print_Max` in `LaTeXPrinter` have the exact same codes except the function name:
https://github.com/sympy/sympy/blob/5fcbde2ed7385df250510bd5207f270cba990265/sympy/printing/latex.py#L813-L831
This can be simplified to:
```python
def _hprint_variadic_function(self, expr, exp=None): 
    args = sorted(expr.args, key=default_sort_key) 
    texargs = [r"%s" % self._print(symbol) for symbol in args] 
    tex = r"%s\left(%s\right)" % (self._print(expr.func), ", ".join(texargs))
 
    if exp is not None: 
        return r"%s^{%s}" % (tex, exp) 
    else: 
        return tex 

_print_Min = _print_Max \
    = _hprint_variadic_function
```

(ii) Printers have different methods of printing the name of the function used and the function class. For example, in `LaTeXPrinter`, `gamma` function class is printed using:
https://github.com/sympy/sympy/blob/5fcbde2ed7385df250510bd5207f270cba990265/sympy/printing/latex.py#L794-L798
whereas the name of `gamma` is hard coded in `_print_gamma`:
https://github.com/sympy/sympy/blob/5fcbde2ed7385df250510bd5207f270cba990265/sympy/printing/latex.py#L984-L990
The latter can be changed to:
```python
def _hprint_one_args_func(self, expr, exp=None):
    tex = r"\left(%s\right)" % self._print(expr.args[0])

    if exp is not None:
        return r"%s^{%s}%s" % (self._print(expr.func), exp, tex)
    else:
        return r"%s%s" % (self._print(expr.func), tex)
```

### PR DESCRIPTION
**Pull request by lilithxxx**
Simplified _print_Max and _print_Min code to a
single function.

Fixes https://github.com/sympy/sympy/issues/14044

### CODE REVIEW

**Comment by asmeurer** [comment]
Please look at the test failures.

**Comment by lilithxxx** [comment]
Can anyone please tell me why the travis test is failing

**Comment by gxyd** [comment]
You can run tests locally as well. See: https://github.com/sympy/sympy/wiki/Development-workflow#be-sure-that-all-tests-of-sympy-pass 

In particular since you made changes on printing module. You can infact run tests just on printing module via `./bin/test sympy/printing` in sympy root directory.

Currently in particular a test failing is:
```
sympy/printing/tests/test_latex.py[114] .........E.............................................................................................
...........                                                                                                                              [FAIL]

_______________________________________________________________________________________________________________________________________________
___________________________________________ sympy/printing/tests/test_latex.py:test_latex_functions ___________________________________________
  File "/home/gxyd/dev/sympy/sympy/printing/tests/test_latex.py", line 310, in test_latex_functions
    assert latex(Min(x, 2, x**3)) == r"\min\left(2, x, x^{3}\right)"
  File "sympy/printing/latex.py", line 2207, in latex
    return LatexPrinter(settings).doprint(expr)
  File "sympy/printing/latex.py", line 186, in doprint
    tex = Printer.doprint(self, expr)
  File "sympy/printing/printer.py", line 235, in doprint
    return self._str(self._print(expr))
  File "sympy/printing/printer.py", line 259, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)
  File "sympy/printing/latex.py", line 803, in _hprint_variadic_function
    ", ".join(texargs)
TypeError: not enough arguments for format string

```

That fails (as the error message shows), is because `texargs = ['2', 'x', 'x^{3}']` while are formatting the elements into a string you are using only 2 `%s` (instead of 3). That's why it is failing tests.

**Comment by gxyd** [comment]
@lilithxxx can you please address the failing tests?

**Comment by lilithxxx** [comment]
@gxyd I think the issue has been fixed with https://github.com/rahilhastu/sympy/pull/1

**Comment by rahilhastu** [comment]
> issue has been fixed with rahilhastu#1

its #14222 ( [rahilhastu](https://github.com/sympy/sympy/pull/14222) )
the one mentioned by @lilithxxx  was my first attempt to contribute to Sympy repo, so there was a mistake done by me, I merged it with my forked repo.

**Comment by lilithxxx** [comment]
@gxyd I updated my PR but there still seems to be a conflict with my file though the changes in the file is correct.

**Comment by Abdullahjavednesar** [comment]
@lilithxxx PR #14222 seems to cover the same changes as in here. I am labelling SymPy's turn just because you pinged @gxyd.

**Comment by smichr** [comment]
closes #14222 if tests pass and this is committed

**Pull request merged**
