### PR TITLE
add required argumets to latex array environment when print NDimArray

### LINKED ISSUE #23620: the first element of `sympy.Array` object won't show in latex output
when the array length is greater than 10,  the latex environment will be `\begin{array} \end{array}`, and because of the missing mandatory arguments of `array` environment , the first element 0 is taken for the arguments.
image

it may be due to the method `sympy.printing.latex.LatexPrinter._print_NDimArray` 
image

one alternative solution is using `array` environment like `\beg{array}{} ... \end{array}`

and the same problem in matrix printing is handled properly
image

### PR DESCRIPTION
**Pull request by viocha**
#### References to other Issues or PRs

Fixes #23620

#### Brief description of what is fixed or changed
after adding `{}` for the required argumets, `Array` object can be normally displayed
in latex output
屏幕截图 2022-06-13 092124

#### Release Notes

* printing
  * Fixed a bug with `Array` printing

### CODE REVIEW

**Comment by eagleoflqj** [comment]
Could you please
1. Add an entry to mailmap according to https://github.com/sympy/sympy/wiki/Development-workflow#add-your-name-and-email-address-to-the-mailmap-file
2. Add a test at https://github.com/sympy/sympy/blob/master/sympy/printing/tests/test_latex.py. It should be a new `test_Array` function, containing the 2 cases in #23620.

**Comment by eagleoflqj** [comment]
Changes look good, thank you!
Ideally there doesn’t need to be merge commits. If you are familiar with git please squash commits, or I can do it for you.

**Comment by viocha** [comment]
> Changes look good, thank you! Ideally there doesn’t need to be merge commits. If you are familiar with git please squash commits, or I can do it for you.

i'm new to git and have no idea how to do it. thanks for your trouble.

**Comment by eagleoflqj** [comment]
Just a reminder: next time please avoid directly committing to `master` branch of your fork. Instead create a new branch to work on.

**Comment by viocha** [comment]
got it, thank you!



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 15, 2022 07:24 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sympy/sympy] add required argumets to latex array environment when print NDimArray (PR #23622)




 
Just a reminder: next time please avoid directly committing to master branch of your fork. Instead create a new branch to work on.

**Pull request merged**
