### PR TITLE
[WIP] Permutations: Use perm_cyclic flag in pprint/latex to print cyclic notation. print_cyclic is depreciated

### LINKED ISSUE #15201: Remove Permutation.print_cyclic flag
See the discussion at https://github.com/sympy/sympy/pull/15198. The Permutation printing should be handled in the SymPy printers, not on the object itself. The flag should be a flag to the printer. Any doctest that wants to change the printing should set the flag in `init_printing`. However, whichever is set as the default should be used everywhere. 

Since it is publicly documented, it will need to be deprecated https://github.com/sympy/sympy/wiki/Deprecating-policy.

Additionally, it would be best if the `str` printer printed a Python valid representation and the pretty printers only (pprint/latex) printed things like (1 2 3).

### PR DESCRIPTION
**Pull request by souravgl0**
`print_cyclic` is depreciated.
`str` printer prints only the array form of Permutation.
To print cyclic form, use `pprint` or `print_latex` with the flag `perm_cyclic=True`. or alternatively use `init_printing(perm_cyclic=True)` in an interactive session.
Default behavior for `pprint` etc. is to print cyclic form.

#### References to other Issues or PRs
Fixes #15201 

#### Other Comments

I have not updated the doctests to reflect these changes. Naturally, they are going to fail.
It would be better to get a review of these changes and decide on the intended behavior before all the tests are changed.

`print_cyclic` is used all over the place. What is the best way to change all those? Should that be a seperate pull request?

There will also be a need to change documentation. 

@asmeurer 

#### Release Notes

* combinatorics
    * `Permutations.print_cyclic` is depreciated.
    * To print cyclic form of permutations, use the new flag `perm_cyclic` with pprint or latex
    * `print Permutation(1,2,3)` only prints array form

### CODE REVIEW

**Comment by souravgl0** [comment]
There are so many tests dependent on this API change and they all use different objects or functions. I am finding it hard to change all of them. Perhaps that should be a different PR. 
I have changed the necessary API changes. But I can't change the tests.
I think Easy to fix label for this issue is misleading.

**Comment by asmeurer** [comment]
Are you referring to just the doctests, or are there other things as well? 

If you want, you can comment on the issue that someone else can pick up your work where you left off by making a new branch based off yours and fixing the tests.

**Comment by souravgl0** [comment]
Just the doctests and tests as well but those are few. 

Thanks, I'll do that. That's a good feature of open source. Good to learn that.

**Comment by oscarbenjamin** [comment]
What's the status of this? Are you still working on it?

**Pull request closed without merging**
