### PR TITLE
recreatable Dummy

### LINKED ISSUE #11847: Dummy fails when is re-evaluated in S and srepr
Hi all!

Well, i found this little problem, Dummy is a nice function but in the way is implemented exist this:
```
>>> alpha = Dummy("alpha")
>>> i = Integral(1/sqrt(1 - sin(alpha)**2), (alpha, 0, pi/2))
>>> N(i)
0.e+2
>>> i = S(srepr(i))
>>> N(i)
Integral(1/sqrt(-sin(_alpha)**2 + 1), (_alpha, 0, pi/2))
```
Basically, if you works with Dummy, and you get the expression with srepr or similar, when you eval it every Dummy will be interpreted as a new Dummy, so it fails, in the example you can see we can't eval the second expression because the 2 Dummy expression are interpreted as differents, other ex:
```
>>> m=Dummy("m")
>>> a=Matrix([m, m])
>>> a[0]==a[1]
True
>>> b=S(srepr(a))
>>> b[0]==b[1]
False
```

So thinking a solution can be use a hash or similar function, like:
```
>>> m=Dummy("m")
>>> srepr(m)
"Dummy('m', hash=987654321)"
>>> m=Dummy("m")
>>> srepr(m)
"Dummy('m', hash=754619474)"
```
Always will exist the hash collision, but at least to cover all possible can be sympy check the existents Dummy expressions and check the hash never by equal to other, the probability of the hash collision, to be equal, in the same context, with the same name, and in the same expression, i think is very low.

Maybe instead use a hash can be a random expression, with chars like ```8waerfn23jb89a```, that can help to avoid hash collision.

Thx. Cya.

### PR DESCRIPTION
**Pull request by cbm755**
Fixes #11847.

This is my suggestions for @latot's PR #11849, which I'm currently reviewing.

### CODE REVIEW

**Comment by cbm755** [comment]
I think this is ready for a wider review.

@latot what do you think of these modifications to your PR?

@asmeurer let us know what you think of all this.  Future improvements could check why some tests depend on the order of Dummy creation, but for now, this maintains the status quo.

**Comment by asmeurer** [comment]
Please use a `random.Random` class. Some people get very angry when SymPy "breaks" the random number generator.

**Comment by cbm755** [comment]
Ok, makes sense.  Hope I did that correctly: I cached the `random.Random` instance in a class to avoid instantiating it each time.

**Comment by latot** [comment]
what would be the differences between this pr and the other? (i don't understand completely this)

**Comment by cbm755** [comment]
> what would be the differences between this pr and the other?

First of all, it builds on your PR so your commits are here too.

Most notable change is probably using `dummy_index=16` instead of adding a new kwarg `shash=16`.  It uses shorter random numbers so as not to interfere with codegen.  Negative dummy_index is allowed so that existing code for chain rules doesn't have to change.  Does that help?  The changes can also be traced in the commits above.

**Comment by latot** [comment]
:D

**Comment by smichr** [comment]
Does this work?

```diff
diff --git a/sympy/core/symbol.py b/sympy/core/symbol.py
index d2940bc..7cc161b 100644
--- a/sympy/core/symbol.py
+++ b/sympy/core/symbol.py
@@ -223,17 +223,14 @@ def __new__(cls, name=None, dummy_index=None, **assumption
s):
         cls._sanitize(assumptions, cls)
         obj = Symbol.__xnew__(cls, name, **assumptions)

-        while dummy_index is None:
-            # The dummy_index that *we* generate will be a smallish positive
-            # integers (at least Codeprinter assumes this).  But we do not
-            # impose this if dummy_index was passed in.
-            dummy_index = Dummy._prng.randint(10**6, 10**7-1)
-            if dummy_index in Dummy._dummyorder:
-                dummy_index = None
-
-        # Store count but don't update it if we already made this Dummy
-        Dummy._dummyorder.setdefault(dummy_index, Dummy._count)
-        obj.dummy_index = dummy_index
+        # only store dummy_index if it is not equal to the count
+        di = dummy_index
+        if di is not None:
+            if di > Dummy._count:
+                raise ValueError('index must be less than %i' % Dummy._count)
+        else:
+            di = Dummy._count
+        obj.dummy_index = di

         Dummy._count += 1
         return obj
@@ -244,8 +241,9 @@ def __getstate__(self):
     @cacheit
     def sort_key(self, order=None):
         # some tests depend on order of creation of Dummys
-        return self.class_key(), (
-            2, (str(self), Dummy._dummyorder[self.dummy_index])), S.One.sort_ke
y(), S.One
+        return (self.class_key(), (
+            2, (str(self), self.dummy_index)),
+            S.One.sort_key(), S.One)
```

It passes symbol and repr tests but maybe there are other issues you will see.

**Comment by cbm755** [comment]
But then the `srepr` cannot be serialized to disk and restored in another session (because then quite likely  `di > Dummy._count`)...

I did have another thought on how to do this without keeping that `_dummyorder` dict around.  The current code guarantees that a new `Dummy()` is distinct from all previous ones this session, even if some previous ones had their `dummy_index` specified.  That is:
````
d0 = Dummy('d')
d1 = Dummy('d', dummy_index=187687531)    # could be d0 with low probability
d2 = Dummy('d')   # guaranteed different from d0, d1
````

We could relax that to each new `Dummy()` is distinctive from other `Dummy()` but accept a small chance that it is same as some manually specified:
````
d0 = Dummy('d')
d1 = Dummy('d', dummy_index=187687531)    # could be d0 with low probability
d2 = Dummy('d')   # guaranteed different from d0, but could be d1 with extremely low probability.
````
This is an easier problem and can simplify the code.

**Comment by cbm755** [comment]
@smichr please see #12286 for an implementation of my above comment, on top of this branch.  So I think I recommend #12286 instead of this PR.

**Pull request merged**
