### PR TITLE
add solver for f=g/h case

### LINKED ISSUE #10023: solveset fails with a solvable Abs
``` python
In [9]: solveset(-1 + 1/Abs(x - 1), x, domain=S.Reals)
Out[9]: ConditionSet(x, Eq((-Abs(x - 1) + 1)/Abs(x - 1), 0), (-oo, oo))
```

The answer should be `{0, 2}`.

ping @aktech

### PR DESCRIPTION
**Pull request by hargup**
fixes  #10023

### CODE REVIEW

**Comment by smichr** [comment]
Looks good. It is in.

**Comment by smichr** [comment]
In what case is there Inc recursion? It looked like all tests passed so I committed it.

**Comment by asmeurer** [comment]
Here are the test failures (some duplicate lines removed)

```
==================================================================== test process starts =====================================================================
executable:         /Users/aaronmeurer/anaconda/bin/python  (3.5.0-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python
random seed:        73682821
hash randomization: on (PYTHONHASHSEED=2270760423)

sympy/solvers/tests/test_solveset.py[65] .............fE..........ff.f.E.f.....s.....f..ff..f.........f...                                              [FAIL]

______________________________________________________________________________________________________________________________________________________________
___________________________________________________ sympy/solvers/tests/test_solveset.py:test_solve_sqrt_3 ___________________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/solvers/tests/test_solveset.py", line 443, in test_solve_sqrt_3
    assert solveset_real(eq, q) == unsolved_object
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 483, in solveset_real
    result = solveset_real(numer, symbol) - solveset_real(denom, symbol)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 506, in solveset_real
    solveset_real)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 684, in _solve_radical
    result = solveset_solver(eq, symbol) - \
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 512, in solveset_real
    as_poly_solver=_solve_as_poly_real)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 532, in _solve_as_rational
    return as_poly_solver(g, symbol)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 631, in _solve_as_poly_real
    invert_func=invert_real)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 577, in _solve_as_poly
    solns = poly.all_roots()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/polytools.py", line 3362, in all_roots
    roots = sympy.polys.rootoftools.RootOf.all_roots(f, radicals=radicals)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/rootoftools.py", line 149, in all_roots
    return cls._get_roots("_all_roots", poly, radicals)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/rootoftools.py", line 509, in _get_roots
    coeff, poly = cls._preprocess_roots(poly)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/rootoftools.py", line 488, in _preprocess_roots
    "sorted roots not supported over %s" % dom)
NotImplementedError: sorted roots not supported over ZZ[m]
______________________________________________________________________________________________________________________________________________________________
______________________________________________________ sympy/solvers/tests/test_solveset.py:test_units _______________________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/solvers/tests/test_solveset.py", line 580, in test_units
    assert solveset_real(1/x - 1/(2*cm), x) == FiniteSet(2*cm)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 483, in solveset_real
    result = solveset_real(numer, symbol) - solveset_real(denom, symbol)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 483, in solveset_real
    result = solveset_real(numer, symbol) - solveset_real(denom, symbol)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 483, in solveset_real
    result = solveset_real(numer, symbol) - solveset_real(denom, symbol)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 483, in solveset_real
    result = solveset_real(numer, symbol) - solveset_real(denom, symbol)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 483, in solveset_real
    result = solveset_real(numer, symbol) - solveset_real(denom, symbol)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 483, in solveset_real
    result = solveset_real(numer, symbol) - solveset_real(denom, symbol)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 483, in solveset_real
    result = solveset_real(numer, symbol) - solveset_real(denom, symbol)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 483, in solveset_real
    result = solveset_real(numer, symbol) - solveset_real(denom, symbol)
...
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 483, in solveset_real
    result = solveset_real(numer, symbol) - solveset_real(denom, symbol)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 473, in solveset_real
    if all([_is_finite_with_finite_vars(m) for m in f.args]):
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 473, in <listcomp>
    if all([_is_finite_with_finite_vars(m) for m in f.args]):
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 323, in _is_finite_with_finite_vars
    for s in f.free_symbols if s.is_finite is None])
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solveset.py", line 323, in <listcomp>
    for s in f.free_symbols if s.is_finite is None])
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/symbol.py", line 206, in __new__
    obj = Symbol.__xnew__(cls, name, **assumptions)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/symbol.py", line 122, in __new_stage2__
    obj._assumptions = StdFactKB(assumptions)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/assumptions.py", line 221, in __init__
    self.deduce_all_facts(facts)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/facts.py", line 524, in deduce_all_facts
    if not self._tell(k, v) or v is None:
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/facts.py", line 491, in _tell
    if k in self and self[k] is not None:
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by hargup** [comment]
The [travis job](https://travis-ci.org/sympy/sympy/builds/87496535) also failed but some reason github shows a tick.

**Pull request merged**
