### PR TITLE
Use autosummary for documentation

### PR DESCRIPTION
**Pull request by sylee957**
#### Brief description of what is fixed or changed

SymPy documentation had grown up too much and it is really annoying to scroll down thousands of lines.

One of the problem is that sympy classes have so many functions, attributes, keywords that have to be documented and I don't think that it's a good idea to paste all the docs in a single page using `autodoc`.

For example, I see numpy and scipy documents a class, a method in a single page and use redirectives to link them, instead of having all the class, functions documented in a single page.

I think that we should start to use `autosummary` and use templates to automatically generate stub pages for each `rst` files

I have an example to showcase for matrix documentation
Such that users can see the main page like below, only containing the classes, loose functions and summaries

Screenshot_2020-02-07 Matrices (linear algebra) — SymPy 1 6 dev documentation

And also each classes should list only the summaries for each methods, because sympy classes often have massive numbers of methods and properties.

image

And finally, it should have one doc under one separate page.

image

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by moorepants** [comment]
+1 to this idea! It will be a major improvement to have the docs structured like this.

**Comment by oscarbenjamin** [comment]
Yes, this looks much better!

**Comment by sylee957** [comment]
It is painful to resolve the documentation inheritance elegantly with sphinx, such that it correctly links and where the inherited methods are from, and where they are documented.

But I think that it did not get regressed using this, because the original sympy docs didn't have any pages for inherited methods.

For example, I had to all the matrix classes like below

image

I think that we should avoid trying to override the methods or docs in the subclasses, such that everything can be managed in one major place.

And also, I see a lot of irrelevant assumptions are added to stub pages, even if I have tailored the template script not to document inherited stuff

image

I'm not sure that it can be resolved, but I hope it doesn't slows the build down too much.

**Comment by asmeurer** [comment]
I think it's a good idea. It would also help if the sidebar table of contents were easier to see/navigate.

**Comment by sylee957** [comment]
Is there a way to silence the latex warnings?
I think that this is failing because of the log exceeding. 

Though I’m not sure why the pdf makes so many warnings.

**Comment by asmeurer** [comment]
I don't think the lot exceeding the limit causes it to fail. Rather, it is failing some some legitimate reason but you can't see it because the log has too many latex warnings. You will probably need to build locally to see the problem.

**Comment by sylee957** [comment]
I think that sphinx fails the build only because it exceeds the maximum log

- `https://api.travis-ci.org/v3/job/647792101/log.txt` 
  https://api.travis-ci.org/v3/job/647792101/log.txt
- `The job exceeded the maximum log length, and has been terminated.` 
  https://api.travis-ci.org/v3/job/647772415/log.txt

When I checked the logs locally, the one exploding the travis only had 5000 lines more
So someone should come up with an idea how to silence those latex warnings.

**Comment by sylee957** [comment]
Okay, the build look like succeeding if I haven't created much new stub `rst` pages.
Probably because the latex doesn't generate.

I've modified class template not to use autosummary inside, even if it doesn't look ideal, because it documents too much about `is_foo` stuff and it's probably the reason why latex log is exploding.
I'm not able to resolve this issue with sphinx because:

1. From the sphinx side, they have insufficiently provided variables for jinja template. So I cannot check if a `member` is in `undoc-member`, which sympy's undocumented variables comes up with.

2. From the sympy side, a lot of `is_foo` stuff is injected directly to the class probably due to some metaclasses, so it messes up with sphinx.

But I think that at least using the autosummary for having a clean list for functions, classes generally helps, so I'd halt at this moment.

**Comment by asmeurer** [comment]
There is an empty file here called `python` that has been added to the root directory.

**Comment by asmeurer** [comment]
So what is the status of this? Should it be merged? It looks like Travis is passing. It looks like getting autosummary working is non-trivial so we should probably document what is required.

**Comment by sylee957** [comment]
Yes, I've done with the PR.
But the only thing I'm concerned of is that the log file had grown bigger (`3.64MB` -> `3.86MB`)

Travis clearly mentions that they crash the build after the log exceeds `4MB` 
https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded
and it can probably crash after the doc cleanup is done for other modules.

**Comment by oscarbenjamin** [comment]
I've never seen any travis failures from running latex. If there was one then we would probably only be interested in seeing the end of the output so maybe we can do something like
```
make all 2>&1 | tail -n 100
```

**Comment by sylee957** [comment]
I opened up a new PR to silence the LaTeX build log in #18615

**Comment by oscarbenjamin** [comment]
I think this looks really useful. Can it be merged or does the log problem need solving first?

**Comment by asmeurer** [comment]
How hard would it be to not use autosummary for the pdf docs? It isn't really needed there anyway.

**Comment by czgdp1807** [comment]
This is a really good idea. @sylee957 Are you planning to complete this?

**Comment by sylee957** [comment]
I'd also mark this for the project under Docstring style guide that this can change the overall workflow of writing and organizing the docs significantly.
But regarding some issues or limitations of autosummary, I'd want to review how much it is capable or convenient of before moving on to changes.

**Pull request closed without merging**
