### PR TITLE
shift_transformation: addition of class in integers.py

### LINKED ISSUE #16405: shift_transformation: Addition of Shift Transformation

### PR DESCRIPTION
**Pull request by anubhav4sachan**
Shift Transformation of a variable 'x' is defined as the fractional part
of reciprocal of 'x'.
The transformation T(x) = frac(1/x)

Example:
"""
>>> from sympy import shift_transformation, Symbol
>>> x = Symbol('x')
>>> shift_transformation(x)
frac(1/x)

"""

#### References to other Issues or PRs

Fixes #16405 

#### Brief description of what is fixed or changed

I have added a class named `shift_transformation` which is a basic integral function for shift transformation as defined above.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by abhinavsagar** [comment]
Can you please explain what problem are you solving?

**Comment by Naba7** [comment]
What is ..ers.py? Please be more descriptive

**Comment by Naba7** [comment]
What is the issue here? Your issue description  is nil. As well why did you add this ``shift-transformation`` module in here? Plus try fixing `Easy-To-Fix`` bugs and what transformation you are referring here? Can you give an example?

**Comment by anubhav4sachan** [comment]
"""
    Shift Transformation of an argument is defined as the fractional part
    of reciprocal of the argument.
    The transformation T(x) = frac(1/x)

    For example
    ===========
    >> from sympy import Symbol
    >> shift_transformation(5.35)
    0.186915887850467
    >> x = Symbol('x')
    >> shift_transformation(x)
    frac(1/x)
    Reference
    ===========
    [1] Weisstein, Eric W. "Shift Transformation." From MathWorld-A
        Wolfram Web Resource.
        "http://mathworld.wolfram.com/ShiftTransformation.html"

**Comment by Naba7** [comment]
Try https://github.com/sympy/sympy/wiki/Writing-Release-Notes and your test code is not compatible.You can check the details of the tests via the link

**Comment by anubhav4sachan** [comment]
@Naba7 Made the changes in release notes.

**Comment by Naba7** [comment]
It fails still

**Comment by oscarbenjamin** [comment]
The tests have failed because you haven't added any new tests for this class.

I'm not sure if this addition to SymPy is needed though.

**Comment by czgdp1807** [comment]
Closing this as no edits were made to existing code and moreover the addition is just a one liner code without any branching. Thanks for the contributions.

**Pull request closed without merging**
