### PR TITLE
added more sympy projects 

### PR DESCRIPTION
**Pull request by Shekharrajak**
Added more projects using Sympy in [docs](http://docs.sympy.org/latest/outreach.html#projects-using-sympy)

### CODE REVIEW

**Comment by Shekharrajak** [comment]
https://github.com/sympy/sympy/issues/10273

**Comment by Shekharrajak** [comment]
For [#10273](https://github.com/sympy/sympy/issues/10273)

**Comment by moorepants** [comment]
Thanks for the additions. The papers likely also belong the papers page on the wiki.

**Comment by Shekharrajak** [comment]
Thanks :)

**Pull request merged**
