### PR TITLE
[WIP] Adds DomainMatrix to slow matrix methods

### PR DESCRIPTION
**Pull request by hyadav2k**
This PR implements `DomainMatrix `to slow Matrix Methods like `charpoly`, `inverse`, `determinant`, `LUdecomposition `etc.

Reference to Task 3, 4, 5, 6 in #20987

#### Brief description of what is fixed or changed
This PR is still under development, it has a lot of cases failing, so this has a WIP tag in the heading.

NO ENTRY

### CODE REVIEW

**Comment by hyadav2k** [comment]
@oscarbenjamin, there are multiple cases failing as of now, but I opened the issue for the below case.
```
File "c:\users\harshit yadav\sympy\sympy\matrices\tests\test_decompositions.py", line 51, in test_LUdecomp
    assert (L*U).permute_rows(p, 'backward') - M == zeros(3)
AssertionError
```
Output
```
In [1]: M = Matrix(((1, x, 1), (2, y, 0), (y, 0, z)))

In [2]: L, U, p = M.LUdecomposition()

In [3]: (L*U).permute_rows(p, 'backward') - M == zeros(3)
Out[3]: False

In [4]: (L*U).permute_rows(p, 'backward')
Out[4]:
⎡1           x                           1                ⎤
⎢                                                         ⎥
⎢2           y                           0                ⎥
⎢                                                         ⎥
⎢                                                  2      ⎥
⎢   x⋅y⋅(-2⋅x + y)           2⋅x⋅y        2⋅x⋅z + y  - y⋅z⎥
⎢y  ────────────── + x⋅y  - ─────── + y + ────────────────⎥
⎣      2⋅x - y              2⋅x - y           2⋅x - y     ⎦

In [5]: simplify((L*U).permute_rows(p, 'backward'))
Out[5]:
⎡1  x  1⎤
⎢       ⎥
⎢2  y  0⎥
⎢       ⎥
⎣y  0  z⎦

In [6]: simplify((L*U).permute_rows(p, 'backward')) == M
Out[6]: True

```

**Comment by hyadav2k** [comment]
There is one more interesting case failing.
```
In [1]: M = Matrix(( (x,   1),
   ...:                  (y, 2*y) ))

In [2]: M.det(method="bareiss") == 2*x*y - y
Out[2]: False

In [3]: s = M.det(method="bareiss")

In [4]: print(s)
2*x*y - y

In [5]: type(s)
Out[5]: sympy.polys.fields.FracElement
``` 
I am not sure what to use to convert it into a `sympy` object or element.

**Comment by oscarbenjamin** [comment]
> I am not sure what to use to convert it into a `sympy` object or element.

See here:
https://docs.sympy.org/dev/modules/polys/domainsintro.html

**Comment by oscarbenjamin** [comment]
I think it would be better to implement only one thing at a time. The first one to implement is charpoly.

**Comment by oscarbenjamin** [comment]
For some operations like LU decomposition we should make the use of `DomainMatrix` optional for now because it changes the output. For something like charpoly which always expands everything the output should be the same however we calculate it and `DomainMatrix` is pretty much definitely faster. We need to check that with timings for different kinds of Matrix before committing to using `DomainMatrix` all the time though so it could be made optional but with `DomainMatrix` as the default.

**Comment by hyadav2k** [comment]
Sure, will do as you instructed.
Thanks.

**Comment by sylee957** [comment]
My opinion is we should build more sophisticated parser to use DomainMatrix carefully for certain set of coefficients.

And I also suggest that we also have to keep expression tree schemes somewhere for other usage. 
Obviously, matrix operations without division can just be assumed as an 'concatenation' of expression tree, which I believe should also be done better if we can split lots of obvious polynomial matrix methods to DomainMatrix.

**Pull request closed without merging**
