### PR TITLE
Fix Latex printing of logarithm with base

### LINKED ISSUE #26897: Incorrect LaTeX Representation for Logarithms
When converting logarithmic expressions to LaTeX using SymPy's latex function, the output for log(b, a) is incorrectly represented as \frac{\log{a}}{\log{b}}.
This should instead be rendered as \log_{a}(b).
Natural logarithm should default as \ln(a) \ln(b)

There is a fix here but it seems like the latest version isn't there yet?
https://github.com/sympy/sympy/pull/19396/commits/7227e21411a48e46add398a78bc8415c7a6bf05b#diff-2a60b6b9791931a1418810380aae96f630bc05e34e3fb4b073f2a3a19f66dfa4

### PR DESCRIPTION
**Pull request by brutusyhy**
#### Brief description of what is fixed or changed
Fixes #26897, previously `latex(log(x, y, evaluate=False))` will return `\\log{\\left(x \\right)}`, which discards the base. This fix ensures that if a base is provided, it will be included in the latex printing.

#### Release Notes

* printing
  * Fix a bug where logarithm's base is not correctly printed in in Latex.

### CODE REVIEW

**Comment by haru-44** [comment]
It's fine to learn by imitation.
This test will be added to `sympy/printing/tests/test_latex.py`.
While it is possible to create a separate test for the issue, like `test_issue_3568`, it would be easier to add it to `test_latex_log`. If you add the issue number as a comment, like in `test_latex_limits`, it will be easier for others to understand.

https://github.com/sympy/sympy/blob/34f74f9366e38936ff927e7a79d3688f994d8d60/sympy/printing/tests/test_latex.py#L1413-L1415

https://github.com/sympy/sympy/blob/34f74f9366e38936ff927e7a79d3688f994d8d60/sympy/printing/tests/test_latex.py#L1401-L1405

https://github.com/sympy/sympy/blob/34f74f9366e38936ff927e7a79d3688f994d8d60/sympy/printing/tests/test_latex.py#L1384-L1388

**Comment by brutusyhy** [comment]
> It's fine to learn by imitation. This test will be added to `sympy/printing/tests/test_latex.py`. While it is possible to create a separate test for the issue, like `test_issue_3568`, it would be easier to add it to `test_latex_log`. If you add the issue number as a comment, like in `test_latex_limits`, it will be easier for others to understand.
> 
> https://github.com/sympy/sympy/blob/34f74f9366e38936ff927e7a79d3688f994d8d60/sympy/printing/tests/test_latex.py#L1413-L1415
> 
> https://github.com/sympy/sympy/blob/34f74f9366e38936ff927e7a79d3688f994d8d60/sympy/printing/tests/test_latex.py#L1401-L1405
> 
> https://github.com/sympy/sympy/blob/34f74f9366e38936ff927e7a79d3688f994d8d60/sympy/printing/tests/test_latex.py#L1384-L1388

Great! Also what should I do regarding the authors' test? I added my name to the .mailmap file but the test still fails, and it seems to say that a bot should also be added to it?

**Comment by haru-44** [comment]
> Also what should I do regarding the authors' test? I added my name to the .mailmap file but the test still fails, and it seems to say that a bot should also be added to it?

This error is unrelated to the current modification. The error should not occur if the check runs again.

**Comment by haru-44** [comment]
The process that ignores dependabot in the git log is failing.

@oscarbenjamin
In this case, is the only option to `rebase`?

**Comment by haru-44** [comment]
I thought the error would no longer occur, but I was wrong. The fix itself is fine, so once the issue with `authors` is resolved, we can merge it.

Sorry, I’m going to bed now, so I’ll take care of it tomorrow.

**Comment by oscarbenjamin** [comment]
I think that the problem is that this does not always get the right commit:
https://github.com/sympy/sympy/blob/34f74f9366e38936ff927e7a79d3688f994d8d60/bin/mailmap_check.py#L232-L242
It was added by @asmeurer in 5ccc741 but I don't remember why. In this case it is skipping commits that should not be skipped.

**Comment by oscarbenjamin** [comment]
Okay, that's better. Now you need to fix the .mailmap file.

**Comment by haru-44** [comment]
@oscarbenjamin 
thank you.

@brutusyhy 
The `.mailmap` needs to have the correct name as it appears in the git log. In this case, `brutusyhy <142066452+brutusyhy@users.noreply.github.com>` is required. If you wish to include `Hongyu Yang <brutusyhy@gmail.com>` in the `AUTHORS` file, please add the following line to `.mailmap`.

```
Hongyu Yang <brutusyhy@gmail.com> brutusyhy <142066452+brutusyhy@users.noreply.github.com>
```

Please refer to the [manual](https://docs.sympy.org/dev/contributing/new-contributors-guide/workflow-process.html#mailmap-instructions) for detailed explanations.

**Pull request closed without merging**
