### PR TITLE
Update .travis.yml

### LINKED ISSUE #12053: Install mpmath using pip in .travis.yml
It seems the tests weren't installing mpmath at all and we were relying on a mpmath installed in the environment. A change in the python 3.5 env makes the jobs fail now.

https://travis-ci.org/sympy/sympy/jobs/192727874

### PR DESCRIPTION
**Pull request by madan96**
Fixes #12053 .

### CODE REVIEW

**Comment by baoqchau** [comment]
@isuruf Can you help review and merge this? I believe this will help me resolve conflict in my PR at #12057. Thanks a lot.

**Comment by jksuom** [comment]
This --upgrade looks like a good fix. It seems to work also in Python 3.5 environment that contains setuptools 12.0.5.

+1

**Comment by isuruf** [comment]
This doesn't check that installing using distutils works. 

See, https://travis-ci.org/sympy/sympy/jobs/193163001#L210-L213

**Comment by madan96** [comment]
@isuruf I get what you're trying to say. I checked out some previous builds and figured that this problem has persisted since changing `${TEST_AUTOWRAP}` to `${TEST_SAGE}` in L209.

See, https://travis-ci.org/sympy/sympy/jobs/193163001#L209
and https://travis-ci.org/sympy/sympy/jobs/188066245#L209

So, should we revert back to AUTOWRAP?

**Comment by isuruf** [comment]
@madan96, see the solution in original issue https://github.com/sympy/sympy/issues/12053

**Comment by madan96** [comment]
@isuruf It worked. Thanks!

**Pull request merged**
