### PR TITLE
Added the comma decimal separator and semicolon separator for lists, sets, and tuples

### LINKED ISSUE #16565: [feature request] LatexPrinter: comma as decimal separator
Hi,

Normally I don't mind the use of a period as decimal separator (not at all in fact), but when using Sympy in LaTeX documents via PythonTeX, this is becoming quite problematic, since the generated documents have to be in French and decimal numbers are usually written with a comma as decimal separator.

Unfortunately LatexPrinter does not seem to have some kind of "decimal_separator" option, hence my request: it'd be very much appreciated if I could switch the decimal separator for latex'ed output.

(If this is implemented, it might be advisable to simultaneously replace the list item separator from comma to semicolon if decimal_separator='comma' is active.)

### PR DESCRIPTION
**Pull request by rimibis**
#### References to other Issues or PRs

Fixes #16565 

#### Brief description of what is fixed or changed
Added a comma decimal separator ('{,}' replace '.') when printing floats. 
Example: 2{,}5 in place of 2.5.

Added a semicolon list separator(";" in places of ",") for lists, sets, and tuples
Example : [1;2;3] in place of [1,2,3]

#### Release Notes

* printing
  * Added a new arg for latex in latex.py for decimal separator and list, set, and tuple element separator
  * print_float in latex.py now has a check to determine what type of decimal separator to print out
  * _print in printer.py now has a check to determine what type of decimal separator to print out

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Hi thanks for looking at the issue and sending a PR. I think something went wrong in git though because the PR says that 1805 files were modified... It looks as if you've accidentally included a virtual environment in one of your commits.

Also it seems you've opened a PR from your own master branch which you shouldn't do. To fix this situation you should:
1. Save your work somewhere else (outside of git)
2. Restore your master branch:
   a. `$ git reset master~2` (assuming you only have two commits since master)
   b. `$ git reset --hard` (this deletes all your changes locally)
   c. `$ git push --force` (this deletes your changes on github)
3. Open a new branch for your changes:
    a. `$ git checkout -b decimal_sep`
    b. Make your changes to the files, commit and push.
4. Open a PR from the new branch you created (make sure to reference this PR when you do).
5. Close this PR (leave a comment here linking to the new PR you created).

**Comment by rimibis** [comment]
Thank you! I'll try that now!

**Comment by rimibis** [comment]
Also, I'm not sure how to fix the checks that I'm failing in regard to 3.7. I had the virtual environment set up to test Python 3.7 and it seemed to work there.

**Comment by oscarbenjamin** [comment]
Let's get the code in the PR sorted first. Then we can see if the tests are passing!

**Comment by rimibis** [comment]
Sorry, but how do you remove the virtual environment safely. Should I just remove the "env" folder?

**Comment by oscarbenjamin** [comment]
If you follow the steps I described above then the virtual environment will still be there on your computer but will not be included in the commits. The mistake you made (I think) was addinf the virtual environment before committing. You should only `git add` the files you have changed or want to add.

**Comment by rimibis** [comment]
I got an error

`fatal: The current branch decimal_sep has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin decimal_sep`

Should I run this command?

**Comment by oscarbenjamin** [comment]
> Should I run this command?

Yes

**Pull request closed without merging**
