### PR TITLE
matrices: deprecate mixins and merge tests

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

Follow on from gh-25911

#### Brief description of what is fixed or changed

Deprecated the matrix mixin classes.

Merge tests from `test_matrices.py` and `test_commonmatrix.py` into new tests in `test_matrixbase.py`. Some tests in other test files were moved into `test_matrices.py` so that any tests for the deprecated mixin classes are in the two files `test_matrices` and `test_commonmatrix` which can be removed when the deprecated mixin classes are removed.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This is now ready for review.

**Comment by smichr** [comment]
With the number of added tests I was expecting to see a bunch of deletions from somewhere, but I don't. Where are they all coming from?

**Comment by oscarbenjamin** [comment]
> With the number of added tests I was expecting to see a bunch of deletions from somewhere, but I don't. Where are they all coming from?

I have copied all tests from `test_commonmatrix.py` and `test_matrices.py` into `test_matrixbase.py` and then merged them together because there were many tests duplicated in both files.

The previous tests in `test_commonmatrix.py` and `test_matrices.py` are still there so that they can continue to test what was being tested before with the deprecated matrix classes.

Also some other test files like `test_reductions.py` had tests for things like `RrefOnlyMatrix`. I have moved those tests to `test_matrices.py` and changed it so that the tests in `test_reductions.py` only test `Matrix`.

The idea is that we still test the old deprecated classes but all of the tests for them are in `test_commonmatrix.py` and `test_matrices.py` and in future when the deprecation period is over we can delete `common.py`, `matrices.py`, `test_matrices.py` and `test_commonmatrix.py`.

Everything that was previously being tested for any matrix types is now being tested in `test_matrixbase.py` for Matrix which is where all tests that we might ever need in future are located. Until we remove the deprecated classes and associated tests much of the test code is duplicated though.

**Comment by smichr** [comment]
> still there so that they can continue to test what was being tested before with the deprecated matrix classes

Thanks for the reminder. So we won't see the deletion until the deprecation.

Thanks for working on cleaning this up.

**Pull request merged**
