### PR TITLE
Update __init__.py: adding inflection point

### PR DESCRIPTION
**Pull request by che2712**
adding an inflection point when the function is neither decreasing nor increasing

### CODE REVIEW

**Comment by sidhu1012** [comment]
@che2712 What are you trying to achieve here?

**Comment by che2712** [comment]
@sidhu1012 I want to add all the mathematical possibilities.

**Comment by sidhu1012** [comment]
> @sidhu1012 I want to add all the mathematical possibilities.

Okay but how would changing `__init__` help?

**Comment by che2712** [comment]
> > @sidhu1012 I want to add all the mathematical possibilities.
> 
> Okay but how would changing `__init__` help?

I just wanted to point this out and that this should be added to the code, once it's added to the classes, it can be changed here as well. What do you suggest?

**Comment by sylee957** [comment]
I'd suggest to open up issues or discussions.

**Comment by che2712** [comment]
> I'd suggest to open up issues or discussions.

Ok sure, I'll do that

**Comment by sylee957** [comment]
I searched and there is already an existing issue for this in #16520

**Comment by che2712** [comment]
> I searched and there is already an existing issue for this in #16520

ok, I'm closing this then

**Comment by sidhu1012** [comment]
This PR can be closed.

**Pull request closed without merging**
