### PR TITLE
Make refine work with assumptions with reversed Relational objects (to fix 9697)

### PR DESCRIPTION
**Pull request by bjodah**
This is a PR for solving #9697 

~~The first commit here should be quite uncontroversial, it shows the desired behavior.
I expect the second commit to be more controversial and it will need to be discussed thoroughly
Currently it changes the behavior of `Eq.__eq__` to this:~~

```
>>> Eq(x, 0) == Eq(0, x)
True
```

~~it used to return `False`. I argue that it should be `True` just as:~~

```
>>> 1.0 == 1
True
```

~~Don't confuse this with checking identity:~~

```
>>> Eq(x, 0) is Eq(0, x)
False
>>> 1.0 is 1
False
```

Let's see from the test suite if there are any side effects.

### CODE REVIEW

**Comment by asmeurer** [comment]
I'm not sure about it. `==` is only structural equality in SymPy, so things that look different should generally compare different, even if they are mathematically the same. 

I think it would be better for the assumptions to canonicalize Eq, or else learn the fact `Equivalent(Eq(a, b), Eq(b, a))`.

**Comment by bjodah** [comment]
I see. Reading the Python docs it seems like objects which are `__eq__` should also give the same `hash`, which would be silly here. I will try to come up with another solution.

**Comment by bjodah** [comment]
`Eq` is now treated specially in `ask`'s helper function `_extract_facts`, which solves #9697.
`Equivalent(Equality(A, B), Equality(B, A)) == true` already worked (but I added an explicit test for it).

**Comment by bjodah** [comment]
In the end the changes needed to make this work were quite small and contained
to the private function `_extract_facts`, would you mind taking a look @asmeurer

**Comment by asmeurer** [comment]
Seems like a hacky place to put it, but I'm not sure if there's a better place with the current design. If you can't think of a better way I am +1

**Comment by bjodah** [comment]
Yes, I agree it's a bit hacky, but with my limited understanding of the assumptions system this was the sleekest change I could come up with.

Thank you for taking a look, I'll leave this open for now in case someone have any more pointers, if not I'll merge it in a few days.

**Pull request merged**
