### PR TITLE
Fix of fourier series of sin(x)

### LINKED ISSUE #15701: Fourier Series of sin(x)
Obviously the Fourier series of sin(x) is sin(x) but
Try the following:
```
from sympy import Function, sin, fourier_series, pi
from sympy.abc import x

f = Function('f')(x)
f = sin(x)

s = fourier_series(f) # or e.g: fourier_series(f, (x,-pi, pi))
s.truncate(2) # it works for n = 1 but for 2 the statement doesn't respond
```
*P.S*: I am using sympy 1.3.

### PR DESCRIPTION
**Pull request by jmig5776**
#### References to other Issues or PRs

Fixes #15701 

#### Brief description of what is fixed or changed
Previously FourierSeries.truncate gets stuck in an infinite loop in the following case due to rest of the terms are zero after first term in series.

```
from sympy import Function, sin, fourier_series, pi
from sympy.abc import x

f = Function('f')(x)
f = sin(x)

s = fourier_series(f) 
s.truncate(2)
```
But now i had added a ValueError if the number of terms of fourier series are less than the entered trucate number of terms

```
from sympy import Function, sin, fourier_series, pi
from sympy.abc import x

f = Function('f')(x)
f = sin(x)

s = fourier_series(f) 
s.truncate(2)

ValueError                                Traceback (most recent call last)
<ipython-input-8-1cb8defe24e5> in <module>()
----> 1 s.truncate(2)

~\Documents\GitHub\sympy\sympy\series\fourier.py in truncate(self, n)
    193                 break
    194             if len(terms) <n and self.args[0]==Add(*terms):
--> 195                 raise ValueError(("Given Fourier Series only contain {} number of terms").format(len(terms)))
    196             if t is not S.Zero:
    197                 terms.append(t)

ValueError: Given Fourier Series only contain 1 number of terms
```

#### Release Notes

* series
    * fixed fourier_series.truncate function

### CODE REVIEW

**Comment by adeak** [comment]
Your fix is superficial and doesn't work for non-trivial cases such as `sin(x) + cos(x)**3`. This is exactly why [I asked on the issue page](https://github.com/sympy/sympy/issues/15701#issuecomment-450251915) if there was a _robust_ way of fixing this. The solution should work for more than elementary functions.

You _could_ make it more robust by comparing the difference of the sum to the original function with an additional `simplify` call. That would fix the more complicated function but it could fail on something else. This is exactly what I meant by "_I suspect comparing the truncated series to s.function is both needlessly expensive and very fragile_".

Furthermore, a change like this should come with regression tests.

Finally, checking for `len(terms) < n` in a loop that breaks at `n` terms is superflouos. And you can probably use `self.function` instead of `self.args[0]` for clarity.

**Comment by jmig5776** [comment]
then i think fouries series should have a flag such that if a series is finite or infinite and a field should alse be initialised if containing the number of terms if the series is finite and it should pass through the ```truncate``` function. @adeak, @asmeurer  What do you think?

**Comment by smichr** [comment]
> What do you think?

fail gracefully: an error in python is not raised for `[1,2][:100]`; I think the same principle can be applied here. But reading briefly about the use of truncate working iwth non-zero terms instead of the order of terms, perhaps the flag would be better so truncate could be avoided. What do you think @adeak?

**Comment by adeak** [comment]
Honestly I'm not sure what the options are exactly. I'm certain an error should not be raised, your slicing example is exactly what I have in mind. And I don't think it matters whether non-zero terms or orders are being enumerated by `truncate`.

Anyway, the [suggestion by asmeurer on the issue](https://github.com/sympy/sympy/issues/15701#issuecomment-452055668) which @jmig5776 will probably follow would imply a different approach. Having a `FiniteFourierSeries` class would simplify most of the matter. And I'd still expect `FiniteFourierSeries.truncate` not to raise. The reason the user computes a Fourier series using sympy is that they don't want to do that by hand, which is to say I don't think they should have to know _a priori_ the number of nonzero orders in the finite series (or that the series is finite to begin with).

**Comment by jmig5776** [comment]
@smichr , @adeak I went through the trignometric functions in sympy I found out this function 
```
from sympy.simplify.trigsimp import trigsimp_groebner
trigsimp_groebner(sin(x) + cos(x)**3, hints=[3])
sin(x) + 3*cos(x)/4 + cos(3*x)/4
```
Should I use this function to handle above case and @smichr  Can you guide me what to add in subclass ```FiniteFourierSeries``` and how should i implement it.

**Comment by smichr** [comment]
> they should have to know _a priori_ the number of nonzero orders in the finite series

agree

@jmig5776 , I really don't have to background to provide much guidance here. I think, in light of the above quoted comment and my slicing example, I would modify truncate's docstring to read

> Return, at most, n nonzero leading terms of the series.

**Comment by jmig5776** [comment]
Yes I was also thinking that there are many examples that will stuck in infinite loop. @smichr its good that you changed the docstring , the previous one was very ambiguous.

So what should be done now?

**Comment by oscarbenjamin** [comment]
I would suggest that you should return the terms in this case rather than raising ValueError.

Then you can change the docstring to say that it returns either the first n non-zero terms or all terms it there are fewer then n non-zero terms.

(Then this would need tests)

**Pull request closed without merging**
