### PR TITLE
Fix unreferenced args in ReciprocalHyperbolicFunction Class

### PR DESCRIPTION
**Pull request by aktech**
The XFAIL in solveset [here](https://github.com/sympy/sympy/blob/master/sympy/solvers/tests/test_solveset.py#L506), and it gave this error:

``` python
NameError: global name 'args' is not defined
```

Though this PR doesn't aims to un-XFAIL the mentioned  test in `solveset`, but it certainly fixes the two unreferenced args in `ReciprocalHyperbolicFunction` class.

@hargup  @jksuom

### CODE REVIEW

**Comment by jksuom** [comment]
Looks OK to me. +1

**Comment by debugger22** [comment]
This PR duplicates some of the things from https://github.com/sympy/sympy/pull/9179 but I'm +1 as it has tests too.

**Comment by debugger22** [comment]
Thanks for adding tests!

**Comment by aktech** [comment]
> This PR duplicates some of the things from #9179 but I'm +1 as it has tests too.

Oh I see, though I couldn't guess anything from the title of #9179 , while creating this PR.
BTW, It doesn't have all the tests, for e.g. `is_finite`, maybe @shivamvats would add them, as well.

**Pull request merged**
