### PR TITLE
Fixed typos in ellipse.py

### LINKED ISSUE #11976: Typo in ellipse.py
Change focale -->focal in sympy/geometry/ellipse.py -- line 584
Change costructed -->constructed in sympy/geometry/ellipse.py -- line 1327

### PR DESCRIPTION
**Pull request by rajatthakur**
This Fixes #11976

### CODE REVIEW

**Comment by moorepants** [comment]
For simple typos like this you can include "[skip ci]" in your commit message so that you don't have to wait for all the tests to run before merging.

+1

**Comment by moorepants** [comment]
Please merge in the master branch and push the merge commit to this PR.

**Comment by rajatthakur** [comment]
Hey @moorepants ,
I have merged the typos branch with my master branch but I don't know how to push that merge commit into this PR. I am quite new to open source and I would be glad if you could help.

**Comment by moorepants** [comment]
The command line process is something like:

```
git checkout master
git pull upstream
git merge upstream master
git push origin master
```

where upstream point to the main sympy repo and origin points to your fork.

**Comment by rajatthakur** [comment]
Hi @moorepants,
Please review the changes that I have made and let me know if anything else needs to be done.

**Pull request merged**
