### PR TITLE
refactor(assump) : redesign get_relevant_facts()

### PR DESCRIPTION
**Pull request by JSS95**
#### Brief description of what is fixed or changed

In master, `get_relevant_facts()` has completely different two functionalities.

1. If *exprs* is not passed, it extracts the symbolic expressions from *proposition*, *assumptions*, and *context*. *relevant_facts* is not used here.

2. If *exprs* is passed, facts relevant to *exprs* are found and returned. Here, *proposition*, *assumptions*, and *context* are not used.

This design is very confusing. In this change, I introduced a new function named `extract_predargs()` which does the first functionality. `get_relevant_facts()` now does only the second one.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Looks good to me although are there no tests for these?

**Comment by JSS95** [comment]
@oscarbenjamin Added tests.

**Comment by oscarbenjamin** [comment]
Looks good

**Comment by JSS95** [comment]
@Soumi7 Let me know your thought on this.

**Comment by Soumi7** [comment]
Looks good me to. Once this is merged you can add docstrings as via a separate PR.

**Pull request merged**
