### PR TITLE
Typo in de docs of 3D harmonic oscillator

### PR DESCRIPTION
**Pull request by nicoguaro**

### CODE REVIEW

**Comment by scopatz** [comment]
Looks good to me.

**Comment by nicoguaro** [comment]
I changed a single character:

    -        mass-scaled frequency: nu = m*omega/(2*hbar) where `m' is the mass
    +        mass-scaled frequency: nu = m*omega/(2*hbar) where `m` is the mass

since the rendering in the documentation is not correct.

**Comment by leosartaj** [comment]
+1

**Comment by jksuom** [comment]
+1

**Comment by leosartaj** [comment]
Thanks @nicoguaro

**Pull request merged**
