### PR TITLE
Have `IdentityOperator` inherit from `UnitaryOperator` and `HermitianOperator` instead of `Operator`

### PR DESCRIPTION
**Pull request by vtomole**
#### Brief description of what is fixed or changed
The [Identity operator is unitary](https://en.wikipedia.org/wiki/Identity_matrix). This change is to reflect that.

#### Release Notes

* physics.quantum
  * Change the baseclass of `IdentityOperator` from `Operator` to `HermitianOperator` and `UnitaryOperator`

### CODE REVIEW

**Comment by sylee957** [comment]
What about HermitianOperator?

**Comment by sylee957** [comment]
It could be better to avoid subtyping relationship to model properties like `Unitary, Hermitian`, like logical programming because it would necessarily involve multiple inheritance, which is often the antipattern choice.

**Comment by sylee957** [comment]
> In what scenario would IdentityOperator have to inherit from HermitianOperator?

Then I would also raise an obvious question why would you want to change the design to achieve that.
I don't think that it fixes some nontrivial bug than changing the definitions.

**Comment by Costor** [comment]
I see vtomole's point - its about _consistency of properties_. If you write some more generic code and use classes as indicator of properties it is strange that you have to write code like `If instance(A, UnitaryOperator) or isinstance(A, IdentityOperator)` to check if `A` is unitary. Same goes with hermitian. 

But SymPy is actually not trying to use classes for that purpose (probably because of technical issues, and because more flexibility is needed, see below). As far as I can see it uses `.is_xxxx` properties instead, or more generally put the SymPy attribute system! So see _HermitianOperator_: it defines the `.is_hermitian` property. That could be a start:

I would rather vote for introducing the attributes `.is_hermitian` and `.is_unitary` into `Operator`. They would inherit to `HermitianOperator`, `UnitaryOperator`, and `IdentityOperator`, also `OuterProduct` etc. and be set there correctly. From `UnitaryOperator` they would be inherited to `Gate`, and `.is_hermitian` could be set to `True` for those gate classes that are both unitary and hermitian (as Hadamard and Pauli gates, and not to forget the `IdentityGate` :-) ). This is also a good example for flexibility - making these gates also inherit from `HermitianOperator` would become cumbersome.

**Comment by sylee957** [comment]
I also had in mind that other logical programing is better than inheritance though. 
If the subtyping test is used for testing some property of an object, the argument about uniqueness is needed, to avoid complicated diamond inheritance problems.

**Comment by vtomole** [comment]
> .is_hermitian could be set to True for those gate classes that are both unitary and hermitian

Fact check me on this: I'm pretty sure that every unitary matrix is hermitian. If that's true, there is no need for `is_hermitian = True` in the `Gate` classes. We can set it once in `UnitaryOperator`.

**Comment by sylee957** [comment]
> I'm pretty sure that every unitary matrix is hermitian. 

I'm sure that they are mathematically unrelated, and counterexamples are easily found
- `Matrix([[1, I], [-I, 1]]) / 2` Hermitian, but not Unitary
- `Matrix([[1, I], [I, 1]]) / sqrt(2)` Unitary but not Hermitian

**Comment by vtomole** [comment]
I've added `is_hermitian` and `is_unitary` to `Operator` as suggested by @Costor

**Comment by Costor** [comment]
In the current form  of the PR the new attributes `.is_hermitian` and `.is_unitary` are set in `HermitianOperator` and `UnitaryOperator` only. In all other classes that inherit from `Operator` the attributes are left unmodified which might be confusing if people rely on them. For instance all gates are unitary, the Pauli Gates X, Y, Z are even unitary and hermitian. In `OuterProduct` it is hermitian in case bra == ket. Is there a chance to add this?

**Comment by vtomole** [comment]
I've set the `is_hermitian` for `IdentityGate`, `T`, `S` and `Swap`.

> In OuterProduct it is hermitian in case bra == ket. Is there a chance to add this?

Unfortunately we can't access `self` in a class variable (`is_hermitian = self.bra == Dagger(self.ket)`). Maybe there is another way.

**Comment by Costor** [comment]
T and S are _not_ (in general) hermitian, so require `.is_hermitian=False`.
`Swap` is hermitian, so ok.
The three Pauli gates XGate, YGate, ZGate and the Hadamard gate all are hermitian, so should get `.is_hermitian=True` .

`CNot` is hermitian, but inherits from HermitianOperater already, so nothing to be done there.

**Comment by vtomole** [comment]
> T and S are _not_ (in general) hermitian, so require `.is_hermitian=False`.

This has already been done in this PR

> The three Pauli gates XGate, YGate, ZGate and the Hadamard gate all are hermitian, so should get `.is_hermitian=True` .

This is not neccessary because all these gates inherit from `HermitianOperator`

> CNot is hermitian, but inherits from HermitianOperater already, so nothing to be done there.

:+1:

**Comment by Costor** [comment]
It seems all questions have been answered a month ago. 
What keeps this PR from being merged into master?

**Pull request merged**
