### PR TITLE
Bug Fix #8626

### LINKED ISSUE #8626: bug in physics/mechanics/lagrange.py
When providing a `forcelist` with more than one force, not all terms are computed,
this comes from the fact that the iterator `flist = zip(*_f_list_parser(self.forcelist, N))` is consumed in the first iteration of the loop.

I propose a following PR that fixes the bug, let me know if I need to also provide a test case.

Best,
Guillaume

### PR DESCRIPTION
**Pull request by glyg**
Let me know if a test case is needed

### CODE REVIEW

**Comment by glyg** [comment]
bumb?

Is this ok? I'd like to go back to using master...

**Comment by jcrist** [comment]
Please look at how other tests are written in sympy. Tests should be enclosed in their own function. For example, see the [existing tests for lagrange](https://github.com/sympy/sympy/blob/master/sympy/physics/mechanics/tests/test_lagrange.py).

**Comment by glyg** [comment]
is it ok like that, or are the `assert` statements too dumb?

**Comment by jcrist** [comment]
If they thoroughly test the issue you're fixing, then they're fine. If you could fix my two inline comments, and then squash your commits, this is good to go.

**Pull request merged**
