### PR TITLE
replace has_Field/Ring with is_Field/Ring

### PR DESCRIPTION
**Pull request by valglad**
Replace `has_Field` and `has_Ring` attributes of domains with `is_Field`, `is_Ring`.

### CODE REVIEW

**Comment by jksuom** [comment]
There remains `has_Field` in sympy/polys/domains/field.py.

**Comment by jksuom** [comment]
Some information about deprecation should be added. [Wiki](https://github.com/sympy/sympy/wiki/Deprecating-policy) suggests that there should be also `issue` and `deprecated_since_version`, The version could be 1.1. Opening an issue with `Deprecation Removal` tag could also be useful as a place to record that the pickling tests were modified. Those tests can then be restored when the issue is closed. A deprecation note should also be added to the [release notes](https://github.com/sympy/sympy/wiki/Release-Notes-for-1.1).

**Comment by valglad** [comment]
> Wiki suggests that there should be also issue 

Does that mean I need to open an issue?

**Comment by valglad** [comment]
I'll add a deprecation note to the release notes after the PR is merged.

**Comment by jksuom** [comment]
I think the deprecation removal issue need not necessarily explain the reason for the change. Only it would be a convenient reminder of the temporary change in the pickling test. It is ok the edit later.

**Comment by valglad** [comment]
deprecation issue #12723

**Pull request merged**
