### PR TITLE
Implement lazy dictionary for trigonometric special angles

### PR DESCRIPTION
**Pull request by sylee957**
#### References to other Issues or PRs

#24172

#### Brief description of what is fixed or changed

I've implemented lazy dictionary based on functional approach
It should be more easier to implement, and have more robust behavior than object-oriented approach in the original suggestion.

This can solve some hidden slowdown issues with trig rewrites like `cos(x + pi/6).expand(trig=True)`
I'm trying to collect these issues though.

I'm also planning to make `trigonometric_special.py` to make the special angle formula more explicitly accessible for users, than having to access silently via `rewrite`.
It could be more easier to use for users who want more concrete input structure like `cos_special(1, 17), cos_special(2, 17), ...`.

#### Release Notes

- functions
  - Fixed slowdown issues of initial run caused by evaluating `cos(pi/257)` eagerly even if it is not needed. Now, `cos(x + pi/6).expand(trig=True)` gives more faster result.

### CODE REVIEW

**Comment by smichr** [comment]
Looks ok to me. Maybe someone else will have suggestions.

**Comment by asmeurer** [comment]
Isn't a function already a "lazy dictionary"? I don't see the need for the indirection here. You can just have `cst_table(n)` which returns the result for n = 3, 5, 7, 257 (and that caches the value 257). That would change the code that uses it from `cst_table[n]` to `cst_table(n)`, but it's all internal code so that doesn't matter.

**Comment by sylee957** [comment]
I would just want to keep the original context of using dictionary than functions though.
Because having functions involves making the logic sequential and make it look hierarchical than the mapping.
```
if x == 3:
    .... 
elif x == 5:
    ...
```

**Comment by asmeurer** [comment]
> Because having functions implies something more, like making the logic sequential and and hierarchical than the mapping,
which complicates the problems with more questions like "should 5 be checked first than 3?", or such

This reasoning really doesn't make any sense to me. An `if` chain doesn't imply any of those things, and I don't see why anyone reading the code would think that. Are you really saying that `if`/`elif` chains shouldn't be used if the conditions are mutually exclusive? 

The code here is unnecessarily complicated with indirections. 

```py
if pi_coeff.q in cst_table_some:
    rv = chebyshevt(pi_coeff.p, cst_table_some[pi_coeff.q]())
```

could just be

```py
fermat_primes = [3, 5, 17, 257] # defined above somewhere

if pi_coeff.q in fermat_primes:
    rv = chebyshevt(pi_coeff.p, cos_table(pi_coeff.q))
```

where `cos_table` is just a single cached functions that computes the various values.

**Comment by asmeurer** [comment]
By the way, it might be worth sympifying a string form of cos_257. It's a bit of a hack, but in my tests it's considerably faster. If we can speed up the actual construction that would be great, but I expect that would require a lot of cleaning up of assumptions use in constructors which will be harder due how it breaks things.

**Comment by asmeurer** [comment]
> By the way, it might be worth sympifying a string form of cos_257. It's a bit of a hack, but in my tests it's considerably faster. If we can speed up the actual construction that would be great, but I expect that would require a lot of cleaning up of assumptions use in constructors which will be harder due how it breaks things.

I should note that that's specifically with `sympify(evaluate=False)` (although it will appear to be fast without evaluate=False if you've already computed the expression because of the cache).

**Comment by sylee957** [comment]
> The code here is unnecessarily complicated with indirections.

It doesn't necessarily characterize the reason to use functions for me,
because we just completed the cos table which is too trivial to overview all about these,
so I'll let anyone else to change that if they don't like it.

> By the way, it might be worth sympifying a string form of cos_257. It's a bit of a hack, but in my tests it's considerably faster.

I'm not sure how you've done that, without an obvious nasty workaround of keeping the form of `str(cos_257())` somewhere and using that.
but I'm not sure if there is procedural capabiity in sympify. (like `sympify(r'x = 3; y = x ** 2; y')` to give `9`?)
I'm aware of some other workaround to build the huge strings procedurally, like storing some rules of strings instead of the string, and substituting strings by the rules.

**Pull request merged**
