### PR TITLE
Added methods to Weibull Distribution

### PR DESCRIPTION
**Pull request by Smit-create**
Added methods to Weibull Distribution
#### Brief description of what is fixed or changed
Added 4 methods to Weibull distribution

#### Release Notes

* stats
  * Added cdf to Weibull Distribution
  * Added moment generating function to Weibull Distribution
  * Added quantile function to Weibull Distribution
  * Added characteristic function to Weibull Distribution

### CODE REVIEW

**Comment by czgdp1807** [comment]
@Smit-create I am not sure whether we need ad-hoc methods to generate the results. The root cause for not generating results for functions like, `cdf` lies in the `integrate` module, so may be, we should focus there. @Upabjojr What do you say?

**Comment by its2smit** [comment]
@czgdp1807 Thanks for reviewing. Actually I used cdf(X) for Weibull distribution, but it didn't produce any results nor any error. So I thought to use these methods directly to find them.

**Comment by Smit-create** [comment]
@czgdp1807 Thanks for reviewing. Actually I used cdf(X) for Weibull distribution, but it didn't produce any results nor any error. So I thought to use these methods directly to find them.

**Comment by czgdp1807** [comment]
Yes that's a very popular problem across the stats module. I suggested a generic solution in my GSoC proposal. You can take a look at it, the link is available on the wiki. What I want to see is a generic solution rather than ad-hoc techniques. Though, for time being we can have the solution in this PR.

**Comment by Smit-create** [comment]
@czgdp1807 Yes surely, I will look at the link. Can you please suggest what error am I getting in my PR? and how can I rectify that, so it will help me in fixing other such issues.

**Pull request closed without merging**
