### PR TITLE
tm_sympy - LaTeX math output using dollar signs

### PR DESCRIPTION
**Pull request by mardukbp**
#### Brief description of what is fixed or changed

It is desirable to render SymPy expressions using the math mode in TeXmacs.
Therefore, we enclose SymPy's LaTeX output in dollar signs.

#### Release Notes

* other
  * In the TeXmacs plugin, SymPy now sends LaTeX inline math to TeXmacs for proper rendering

### CODE REVIEW

**Comment by asmeurer** [comment]
Someone who uses this plugin will need to comment on this. I tried downloading TeXmacs, but it segfaults when I open it. 

Also, this should have a release notes entry.

**Comment by mardukbp** [comment]
@asmeurer If you are on Linux you can get a TeXmacs AppImage [here](https://download.opensuse.org/repositories/home:/slowphil:/texmacs-devel/AppImage/). I just tried the SymPy plugin with it.

Release notes added.

**Comment by asmeurer** [comment]
I am on Mac. I downloaded the Mac release from their website, but it segfaulted when I opened it. But I just opened it again and it works this time. Now I need to figure out how to actually add this plugin. Apparently we need a README for the TeXmac plugin.

**Comment by mardukbp** [comment]
@asmeurer  While you are at it, better check my newest pull request #15470. It is more elegant. I would rather close this one if you agree.

**Comment by asmeurer** [comment]
How do you actually use the plugin? I tried installing the master version but TeXmacs just hangs whenever I try to do something. Do I need to use one of your pull requests to prevent this? 

If you want to close this that is fine. In the future you can just push new commits to the same branch instead of making a new pull request.

**Comment by mardukbp** [comment]
On macOS 10.9.5 I installed the plugin like I told you and...TeXmacs did not recognize it. I had to launch TeXmacs with `/Applications/TeXmacs-1.99.8.app/Contents/MacOS/TeXmacs` and then SymPy was available. It is probably because I am using Anaconda and TeXmacs is not aware of that. For such cases one would need a launcher script that sets up the PATH.

I only tried the plugin in the current master branch. Without the improved exception handling it is unusable because every unhandled exception hangs the TeXmacs session. I guess that is what you are experiencing.

Try the newest pull request and let's continue the discussion there.

**Pull request closed without merging**
