### PR TITLE
subs cannot target RootOf args

### LINKED ISSUE #10092: subs into inequality involving RootOf raises GeneratorsNeeded
If x is real then the following generates and error

```python
>>> from sympy import *
>>> var('x', real=True)
x
>>> eq=RootOf(x**3 - 17*x**2 + 81*x - 118, 0)
>>> (x<eq).subs(x,eq)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\core\basic.py", line 895, in subs
    rv = rv._subs(old, new, **kwargs)
  File "sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy\core\compatibility.py", line 880, in wrapper
    result = user_function(*args, **kwds)
  File "sympy\core\basic.py", line 1009, in _subs
    rv = fallback(self, old, new)
  File "sympy\core\basic.py", line 981, in fallback
    arg = arg._subs(old, new, **hints)
  File "sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy\core\compatibility.py", line 880, in wrapper
    result = user_function(*args, **kwds)
  File "sympy\core\basic.py", line 1009, in _subs
    rv = fallback(self, old, new)
  File "sympy\core\basic.py", line 986, in fallback
    rv = self.func(*args)
  File "sympy\polys\rootoftools.py", line 68, in __new__
    poly = PurePoly(f, x, greedy=False, expand=expand)
  File "sympy\polys\polytools.py", line 89, in __new__
    return cls._from_expr(rep, opt)
  File "sympy\polys\polytools.py", line 199, in _from_expr
    rep, opt = _dict_from_expr(rep, opt)
  File "sympy\polys\polyutils.py", line 366, in _dict_from_expr
    rep, gens = _dict_from_expr_no_gens(expr, opt)
  File "sympy\polys\polyutils.py", line 311, in _dict_from_expr_no_gens
    (poly,), gens = _parallel_dict_from_expr_no_gens((expr,), opt)
  File "sympy\polys\polyutils.py", line 272, in _parallel_dict_from_expr_no_gens

    raise GeneratorsNeeded("specify generators to give %s a meaning" % arg)
sympy.polys.polyerrors.GeneratorsNeeded: specify generators to give -17*RootOf(x
**3 - 17*x**2 + 81*x - 118, 0)**2 - 118 + RootOf(x**3 - 17*x**2 + 81*x - 118, 0)
**3 + 81*RootOf(x**3 - 17*x**2 + 81*x - 118, 0) a meaning
```

But a vanilla x does not raise:

```
>>> var('x')
x
>>> eq=RootOf(x**3 - 17*x**2 + 81*x - 118, 0)
>>> (x<eq).subs(x,eq)
False
```

### PR DESCRIPTION
**Pull request by smichr**
TODO
- [ ] check that `r = RootOf(..); r.subs(r, foo)` still works

closes #10092 

RootOf should be treated like a literal and should not allow subs to target any of its args. Even a change of variables is meaningless since RootOf caches the expression used at instantiation:

in master:

```
>>> RootOf(x**3-2*x**2+x-1,0)
RootOf(x**3 - 2*x**2 + x - 1, 0)
>>> RootOf((x**3-2*x**2+x-1).subs(x,var('y')),0)
RootOf(x**3 - 2*x**2 + x - 1, 0)
```

It would be possible to allow targetting of the root number with an integer (but if the integer is wrong, an error will be raised). Please feel free to make suggestions.

### CODE REVIEW

**Comment by smichr** [comment]
I suppose one could allow the integer to be replaced with another integer and then let any error raise on their own if the integer is out of range.  Any thoughts? Should I just commit this as is and let the user-base indicate via issue that the integer substitution (e.g. RootOf(eq,1).subs(1,2)) is a desired feature? ping @asmeurer

**Comment by asmeurer** [comment]
I don't like substituting integers (it would be confusing to change only the second argument and not instances of that integer in the expression). 

On the other hand, why shouldn't `RootOf((x**3-2*x**2+x-1), 0).subs(x, x + 1)` work?

**Comment by smichr** [comment]
> On the other hand, why shouldn't RootOf(x**3-2*x**2+x-1, 0).subs(x, x + 1) work

`x` in the RootOf expression is really like a dummy variable that retains the name of whatever was used to instantiate the particular RootOf object.  If you were to type `RootOf(x**3-2*x**2+x-1,0)` and then type the same thing but using `y` instead of `x` you would get the original object with the `x`. 

If we did allow such replacements, where do we draw the line? Should `subs(x**2, x**4)` work? If the replacement leads to a `RootOf` error should it be disallowed (returning the original expression unchanged) or should the error be raised? 

For reference, the replacement of `x` with a `RootOf` object is the source of the issue that motivated this PR. It was an expression like `(x < RootOf(...)).subs(x, RootOf(...))` where the desired result was `False`.

**Comment by asmeurer** [comment]
I guess it makes sense. The `x` in the RootOf is not free, so it shouldn't be expected to work with `subs`. There's still a lot of inconsistency here among the SymPy objects with dummy variables, but I agree now that this is the right fix.

**Pull request merged**
