### PR TITLE
Fixed error with Pyglet Plotting

### LINKED ISSUE #19059: Pyglet plotting returns error
Running something like this 
```
>>> from sympy import var
>>> from sympy.plotting.pygletplot import PygletPlot as Plot
>>> var('x y z')
>>> Plot(x*y**3-y*x**3)
```
returns
```
Traceback (most recent call last):
  File "/home/psychopirate/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/psychopirate/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/psychopirate/anaconda3/lib/python3.7/site-packages/sympy/plotting/pygletplot/managed_window.py", line 56, in __event_loop__
    clock.set_fps_limit(self.fps_limit)
AttributeError: 'Clock' object has no attribute 'set_fps_limit'
```

### PR DESCRIPTION
**Pull request by Psycho-Pirate**
#### References to other Issues or PRs

Fixes #19059

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by sylee957** [comment]
However, does `clock.fps_limit = self.fps_limit` work?
https://pyglet-current.readthedocs.io/en/latest/api/pyglet/clock/pyglet.clock.Clock.html#pyglet.clock.Clock.set_fps_limit
I think that it was deprecated, but I don't think that you have moved to switching
>  Deprecated. Use pyglet.app.run and schedule_interval instead.

**Comment by Psycho-Pirate** [comment]
> However, does `clock.fps_limit = self.fps_limit` work?

It is working fine on my machine. The code mentioned in the issue is giving the desired output.

**Comment by Psycho-Pirate** [comment]
It is working and giving the desired output. We can also do something like this
`
clock.schedule_interval(self.update, 1/self.fps_limit)
`
But i am not sure it will function the same way as 
`clock.set_fps_limit(self.fps_limit)`
used to do @sylee957

**Comment by Psycho-Pirate** [comment]
Ping @sylee957

**Comment by smichr** [comment]
If a new issue arises we can fix it. This at least fixes something that is not working.

**Pull request merged**
