### PR TITLE
Removed C from functions.special where the import would be non-cyclic

### PR DESCRIPTION
**Pull request by toolforger**

### CODE REVIEW

**Comment by jcrist** [comment]
For cyclic imports, would we want to do a local import to fix? Otherwise, `C` still exists. I'm not sure if there's overhead for function local imports after the first call.

**Comment by toolforger** [comment]
We ultimately want to get rid of ```C```, yes.
What I don't like about local imports is that they distribute the imports all over the code. However, the other approaches (factoring out the cycle into a common submodule, and bottom imports) do not always work, so it's the fix of last resort I think.
Performance-wise, ```C``` requires an additional lookup through ```C.__dict__``` for every use of one of its members, while the local import is a lookup in the module table and a write access to the local namespace. I.e. local imports would amortize after the second call that does not use ```C``` anymore assuming that memory writes take as much time as memory reads (usually they're slower, and they can be much slower, so the amortization is later).
Overall, I do not think that performance will suffer noticeably unless the change is in a piece of code that's called very, very often. In which case I'd want to shift the local import to a global one, and resolve the cycle by using local imports in some other module.

**Comment by jcrist** [comment]
Are you planning on handling that later? I'm just curious why you didn't fully remove `C` from some files, when adding a function local import could fix it now. Seems like fully fixing each file in a PR would make more sense than doing it halfway.

**Comment by toolforger** [comment]
Yes, I'll do whatever it takes to get C out.
Overall plan is:
1) Replace C with imports where that does not create a cycle.
2) Split modules where that allows more C->import changes without creating a cycle.
3) Analyze the remaining uses of C and do local imports.

**Comment by jcrist** [comment]
Ok, sounds like a reasonable plan. Merging.

**Pull request merged**
