### PR TITLE
Scipy translation dictionary added in lambdify.py with tests.

### PR DESCRIPTION
**Pull request by rajat974**
Debug to Issue topic 4130 i.e. Scipy Translation dictionary is added in lambdify.py

### CODE REVIEW

**Comment by moorepants** [comment]
@rajat974 Do you have interest in getting this PR in?

**Comment by czgdp1807** [comment]
Do we still need this?

**Comment by czgdp1807** [comment]
Adding `Could Close`.
```python
from sympy.utilities.pytest import XFAIL, raises
from sympy import (
    symbols, lambdify, sqrt, sin, cos, pi, atan, Rational, Float,
    Matrix, Lambda, exp, Integral, oo, I, Abs, Function, true, false)
from sympy.printing.lambdarepr import LambdaPrinter
from sympy.utilities.lambdify import implemented_function
from sympy.utilities.pytest import skip
from sympy.utilities.decorator import conserve_mpmath_dps
from sympy.external import import_module
from sympy.functions import *
from sympy.functions.special.bessel import *
from sympy.functions.special.hyper import *
from sympy.functions.special.gamma_functions import *

import math, sympy, numpy, scipy

w, x, y, z = symbols('w,x,y,z')

def test_scipy_besselj():
    f = lambdify((x, y), besselj(x,y), "scipy")
    print(f(1, 2) - 0.5767248077568734)
    print(f(3, 4) - 0.43017147387562199)

def test_scipy_bessely():
    f = lambdify((x, y), bessely(x,y), "scipy")
    print(f(1, 2) - -0.10703243154093754)
    print(f(3, 4) - -0.18202211595348544)

def test_scipy_besseli():
    f = lambdify((x, y), besseli(x, y), "scipy")
    print(f(1, 2) - 1.5906368546373291)
    print(f(3, 4) - 3.3372757784203437)

def test_scipy_besselk():
    f = lambdify((x, y), besselk(x, y), "scipy")
    print(f(1, 2) - 0.13986588181652243)
    print(f(3, 4) - 0.029884924416755554)

def test_scipy_loggamma():
    f = lambdify(x, loggamma(x), "scipy")
    print(f(10) - 12.801827480081469)
    print(f(13) - 19.987214495661885)

def test_scipy_digamma():
    f = lambdify(x, digamma(x), "scipy")
    print(f(10) - 2.2517525890667209)
    print(f(13) - 2.5259950133091453)

#Issue 3421
def test_scipy_factorial():
    f = lambdify(x, factorial(x), "scipy")
    print(f(0) - 1)
    print(f(1) - 1)
    print(f(3) - 6)
    print(f(5) - 120)

test_scipy_besselj()
test_scipy_bessely()
test_scipy_besseli()
test_scipy_besselk()
test_scipy_loggamma()
test_scipy_digamma()
test_scipy_factorial()
```
Outputs:
```python
2.220446049250313e-16
-5.551115123125783e-17
4.163336342344337e-17
4.996003610813204e-16
0.0
4.440892098500626e-16
2.7755575615628914e-17
1.1102230246251565e-16
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
```

**Comment by czgdp1807** [comment]
Closing this for know in reference to the above comment. However, please let us know if it can be re-opened. Thanks for the contributions.

**Pull request closed without merging**
