### PR TITLE
Option to make MatrixSymbol print in bold for LaTeX, pretty, and MathML printers

### LINKED ISSUE #15871: Print MatrixSymbol boldface?
What about printing `MatrixSymbol` objects boldface?

In LaTeX this would be `\mathbf{M}`, similar logic could be applied to the pretty printer.

Boldface matrix symbols are easier to distinguish from scalar symbols. Furthermore it's the convention usually employed in books and papers.

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Fixes #15871 
One part of #15877 

#### Brief description of what is fixed or changed
Added an option to print MatrixSymbol in bold for the LaTeX, pretty, and MathML printers. Option is `mat_symbol_style` with values `bold` for bold or `plain` (default) for normal output (basically, anything but `bold` will give plain...)

Example for LaTeX:
```
from sympy import latex, MatrixSymbol
A = MatrixSymbol("A_k", 3, 3)
latex(A, mat_symbol_style='bold')
Out[34]: '\\mathbf{A_{k}}'
```

Example for pretty printer:
```
from sympy import pretty, MatrixSymbol, Symbol
def boldpretty(expr):
    return pretty(expr, use_unicode=True, wrap_line=False, mat_symbol_style="bold")
B = MatrixSymbol("B", 3, 3)
a = Symbol('alpha')
b = Symbol('b')
c = MatrixSymbol("c", 3, 1)
d = MatrixSymbol("d", 3, 1)
boldpretty(a*B*c+b*d)
Out[27]: 'b⋅𝐝 + α⋅𝐁⋅𝐜'
```

For MathML, special cases for MatrixSymbol and RandomSymbol is added so that they use `_print_Symbol`, rather than `_print_Basic` or giving errors as earlier.

#### Other comments
In LaTeX, the super and subscripts will be in bold as well. Maybe not ideal in some situations.

#### Release Notes

* printing
   * New Latex, pretty, and MathML printer option `mat_symbol_style` which when set to 'bold' leads to `MatrixSymbol` printed as bold
   * `MatrixSymbol` and `RandomSymbol` now prints better for MathML

### CODE REVIEW

**Comment by asmeurer** [comment]
So are certain unicode characters not supported in 2.7?

**Comment by asmeurer** [comment]
This looks good to me. Thanks for using pretty_symbology. All the unicode character specific things should ideally be moved from specific printers to that module.

**Comment by oscargus** [comment]
I noted this code:
https://github.com/sympy/sympy/blob/084b39efe9fec1683c4958d37ff5b8ee16428b1d/sympy/printing/pretty/pretty_symbology.py#L56-L63

But obviously didn't pay enough attention to it to remember which letters when creating the first test.

I think I can make only the "main name" (not sub- and superscripts) bold for LaTeX (for the pretty printer it is straightforward, now the flag is passed although there are no bold sub-/superscripted letters in the lookup tables, if there even are in the Unicode standard). So I guess I need some input on that. I do not know what the most common approach is.

**Comment by Upabjojr** [comment]
Had a quick look. It looks like a nice PR.

**Comment by Upabjojr** [comment]
Good to have a switch to disable this.

**Comment by smichr** [comment]
Could `put_accent_in_middle_of_string(foo, accent)` just be `center_accent(foo, accent)`?

**Comment by oscargus** [comment]
Sure, I can change that!

**Comment by oscargus** [comment]
I have changed the name and added MathML support as well. It turned out that RandomSymbol and MatrixSymbol printed a bit weird (not falling back to Symbol), so I changed that as well.

**Comment by oscargus** [comment]
@smichr would you mind have a look at it?

**Comment by oscargus** [comment]
I merge this for now. Seems like a rather non-controversial piece of code in the sense that it is only optionally enabled and will not break anything (rather it also unbreaks a few other things). Do not want to get stuck in constant merge conflicts as there are several PR that changes about the same code.

**Pull request merged**
