### PR TITLE
Reorganize the solving main page

### PR DESCRIPTION
**Pull request by bertiewooster**
Move from guides/solving.md to guides/solving/index.md, to prepare for solving sub-pages to be added to solving directory

#### References to other Issues or PRs

Splits out part of #23638 so solving main page can be in its final location for SymPy 1.11 release. Solving main page was created in #23462.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by bertiewooster** [comment]
Docs build now--realized I had to fix relative links. Ready for review.

Goal is to merge into master before SymPy 1.11 release branch created.

**Comment by bertiewooster** [comment]
Request review so this can be merged into master before SymPy 1.11 branch is split off, so the solving main page will be be in its final location when 1.11 becomes the latest (release) version. Thanks!

**Comment by asmeurer** [comment]
Looks good. Right now there isn't an arrow on the left sidebar for this, but presumably it will show up once we have at least once guide.

**Comment by bertiewooster** [comment]
Yes, confirmed that the [arrow appears on the left sidebar](https://output.circle-artifacts.com/output/job/d167053a-2685-487e-815b-d3eaa82dbb34/artifacts/0/doc/_build/html/guides/solving/index.html) once we have at least one guide:

solving-left-navbar-arrow

**Pull request merged**
