### PR TITLE
Update Ei._eval_rewrite_as_Si

### LINKED ISSUE #17671: limit(Ei(-log(x)) - log(log(x))/x, x, 1) has spurious imaginary part
```
>>> from sympy import *
>>> x = Symbol('x')
>>> g = Ei(-log(x)) - log(log(x))/x
>>> limit(g, x, 1)
EulerGamma + I*pi
```

Can also be seen in integration:

```
>>> f = lambda a: integrate(log(log(x)) / x**a, [x, 1, oo])
>>> f(2)
-EulerGamma - I*pi
>>> f(3)
-log(2)/2 - EulerGamma/2 - I*pi/2
>>> f(10)
-2*log(3)/9 - EulerGamma/9 - I*pi/9
```

### PR DESCRIPTION
**Pull request by ethankward**
#### References to other Issues or PRs
Fixes #17671.

#### Brief description of what is fixed or changed
If argument is negative, return `Shi(z) + Chi(z) - I*pi`.

NO ENTRY

### CODE REVIEW

**Comment by czgdp1807** [comment]
LGTM. Let's wait for the tests to complete. @smichr @asmeurer Comments from your side?

**Comment by czgdp1807** [comment]
@asmeurer Can we merge this?

**Comment by jksuom** [comment]
This looks OK to me. Ei is real on the negative real axis while Chi has an imaginary part.

**Comment by czgdp1807** [comment]
Let's wait for 24 hours, if no one else objects then we will merge it. Thanks for the comment.

**Comment by oscarbenjamin** [comment]
Looks good.

**Pull request merged**
