### PR TITLE
Added Rail Fence Cipher

### PR DESCRIPTION
**Pull request by czgdp1807**
#### References to other Issues or PRs

Closes #15789 
Closes #15534 

#### Release Notes

* crypto
  * Rail fence cipher has been added to `sympy.crypto.crypto`

### CODE REVIEW

**Comment by czgdp1807** [comment]
@asmeurer Any reviews/comments?

**Comment by sylee957** [comment]
Looks good, but I think that the original credit should go to #15534 rather than #15789 because  #15789 is mostly copied from #15534.
If you can rebase, it would be possible to change the author information, alongside with dropping the redundant changes completely.

**Comment by czgdp1807** [comment]
Ah! I see. Will do that by tomorrow. Thanks for pointing out.

**Comment by sylee957** [comment]
I would also note that autodoc directive for this should be added in rst files.

**Comment by czgdp1807** [comment]
@sylee957 I have used #15534 in the latest commit. Please take a look.

**Review by sylee957 — APPROVED** [review]
I've pushed changes to the rst files.
I will merge once the tests pass.

**Pull request merged**
