### PR TITLE
remove delayed unit module import

### LINKED ISSUE #24077: latex of Mul in evaluate context is raising an exception
sympy 1.11.1, Ubuntu 2022.04 with system Python 3.10, PyCharm 2022.2.2

Executing this code:

```
from sympy import evaluate, latex
from sympy.abc import a
with evaluate(False):
    latex(a * a)
```

gives the below exception erroneously. Could you please fix?

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [6], line 2
      1 with evaluate(False):
----> 2     latex(a * a)

File lib/python3.10/site-packages/sympy/printing/printer.py:372, in _PrintFunction.__call__(self, *args, **kwargs)
    371 def __call__(self, *args, **kwargs):
--> 372     return self.__wrapped__(*args, **kwargs)

File lib/python3.10/site-packages/sympy/printing/latex.py:3140, in latex(expr, **settings)
   2928 @print_function(LatexPrinter)
   2929 def latex(expr, **settings):
   2930     r"""Convert the given expression to LaTeX string representation.
   2931 
   2932     Parameters
   (...)
   3138 
   3139     """
-> 3140     return LatexPrinter(settings).doprint(expr)

File lib/python3.10/site-packages/sympy/printing/latex.py:264, in LatexPrinter.doprint(self, expr)
    263 def doprint(self, expr) -> str:
--> 264     tex = Printer.doprint(self, expr)
    266     if self._settings['mode'] == 'plain':
    267         return tex

File lib/python3.10/site-packages/sympy/printing/printer.py:292, in Printer.doprint(self, expr)
    290 def doprint(self, expr):
    291     """Returns printer's representation for expr (as a string)"""
--> 292     return self._str(self._print(expr))

File lib/python3.10/site-packages/sympy/printing/printer.py:331, in Printer._print(self, expr, **kwargs)
    329     printmethod = getattr(self, printmethodname, None)
    330     if printmethod is not None:
--> 331         return printmethod(expr, **kwargs)
    332 # Unknown object, fall back to the emptyPrinter.
    333 return self.emptyPrinter(expr)

File lib/python3.10/site-packages/sympy/printing/latex.py:518, in LatexPrinter._print_Mul(self, expr)
    517 def _print_Mul(self, expr: Expr):
--> 518     from sympy.physics.units import Quantity
    519     from sympy.physics.units.prefixes import Prefix
    520     from sympy.simplify import fraction

File lib/python3.10/site-packages/sympy/physics/__init__.py:5
      1 """
      2 A module that helps solving problems in physics.
      3 """
----> 5 from . import units
      6 from .matrices import mgamma, msigma, minkowski_tensor, mdft
      8 __all__ = [
      9     'units',
     10 
     11     'mgamma', 'msigma', 'minkowski_tensor', 'mdft',
     12 ]

File lib/python3.10/site-packages/sympy/physics/units/__init__.py:213
     52 from .prefixes import (
     53     # 10-power based:
     54     yotta,
   (...)
     80     exbi,
     81 )
     83 from .definitions import (
     84     percent, percents,
     85     permille,
   (...)
    210     exbibyte, exbibytes,
    211 )
--> 213 from .systems import (
    214     mks, mksa, si
    215 )
    218 def find_unit(quantity, unit_system="SI"):
    219     """
    220     Return a list of matching units or dimension names.
    221 
   (...)
    240     ['L', 'l', 'cL', 'cl', 'dL', 'dl', 'mL', 'ml', 'liter']
    241     """

File lib/python3.10/site-packages/sympy/physics/units/systems/__init__.py:4
      2 from sympy.physics.units.systems.mksa import MKSA
      3 from sympy.physics.units.systems.natural import natural
----> 4 from sympy.physics.units.systems.si import SI
      6 __all__ = ['MKS', 'MKSA', 'natural', 'SI']

File lib/python3.10/site-packages/sympy/physics/units/systems/si.py:130
    125 SI.set_quantity_scale_factor(tesla, volt*second/meter**2)
    127 SI.set_quantity_scale_factor(weber, joule/ampere)
--> 130 SI.set_quantity_dimension(lux, luminous_intensity / length ** 2)
    131 SI.set_quantity_scale_factor(lux, steradian*candela/meter**2)
    133 # katal is the SI unit of catalytic activity

File lib/python3.10/site-packages/sympy/physics/units/dimensions.py:47, in _QuantityMapper.set_quantity_dimension(self, unit, dimension)
     45         dimension = Dimension(1)
     46     else:
---> 47         raise ValueError("expected dimension or 1")
     48 elif isinstance(dimension, Quantity):
     49     dimension = self.get_quantity_dimension(dimension)

ValueError: expected dimension or 1
```

### PR DESCRIPTION
**Pull request by cocolato**
#### References to other Issues or PRs

Fixes https://github.com/sympy/sympy/issues/24077

#### Brief description of what is fixed or changed
Remove the delayed import from `_print_Mul`. I don't think it's a good idea to judge a  concrete class type here. If the class type should always be printed at the end of a Mul or other latex expression, maybe use attributes of a class to judge would be better .

#### Other comments
Maybe it would be better to add an attribute (e.g. `_print_back_flag`) to `Quantity`/`Prefix`.

#### Release Notes

* printing
  * Fixed latex printing of multiplication with evaluate(False).

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I think this looks good although I don't know the units module so well myself.

**Comment by cocolato** [comment]
> I think this looks good although I don't know the units module so well myself.

Hi, can you tell me what to do next? Maybe we need otheroneto review this pr?  :）

**Comment by oscarbenjamin** [comment]
> Maybe we need otherone to review this pr?

Yes, ideally this would be reviewed by someone who knows the printing code or the units code because those are two parts of SymPy that I don't know so well myself.

**Comment by oscargus** [comment]
I think it makes sense, at least from a printing perspective. 

Can you please add a test that the code in #24077 works? Simply paste that code and add a comment about the issue, like `# Smoke test for #24077`. 

Also, please update the release note to tell a user what has been fixed. For example, "Fixed latex printing of multiplication with evaluate(False)".

**Comment by cocolato** [comment]
> I think it makes sense, at least from a printing perspective.
> 
> Can you please add a test that the code in #24077 works? Simply paste that code and add a comment about the issue, like `# Smoke test for #24077`.
> 
> Also, please update the release note to tell a user what has been fixed. For example, "Fixed latex printing of multiplication with evaluate(False)".

Thanks! I have updated the smoke test and the release note.

**Pull request merged**
