### PR TITLE
summation over poles of rational functions

### PR DESCRIPTION
**Pull request by gxyd**
For the issue #8746 
Example.
k, n = symbols('k n', integer=True)

> > > summation(1/(k_(k+3)), (k, -3, n))
> > > Sum(1/(k_(k+3)), (k, -3, n))
> > > summation(1/(k_(k+3)), (k, 0, n))
> > > Sum(1/(k_(k+3)), (k, 0, n))
> > > summation(1/((k+3)_(k+1)), (k, n, -2))
> > > Sum(1/((k+3)_(k+1)), (k, n, -2))

It's my first PR, please have a look and give suggestions.

### CODE REVIEW

**Comment by aktech** [comment]
You should add appropriate tests, and please rebase (squash commits).

**Comment by gxyd** [comment]
@aktech please now have a look. I have added all the different possible rational functions types.

**Comment by aktech** [comment]
> @aktech please now have a look. I have added all the different possible rational functions types.

Please add tests also, (in the test file).

**Comment by gxyd** [comment]
I have now added code for the tests. @aktech now have a look.

**Comment by aktech** [comment]
@asmeurer  @smichr 
Please have a look.

**Comment by gxyd** [comment]
@asmeurer @smichr please have a look the pull request.

**Pull request closed without merging**
