### PR TITLE
Make ring_series work with symbolic coefficients

### PR DESCRIPTION
**Pull request by shivamvats**
@certik @thilinarmtb This PR allows the use of symbolic coefficients.
The `EX` domain is around 20 times slower than `QQ`

```
In [37]: R,x  =ring('x', QQ[sin(a),cos(a),a])

In [38]: S,y=ring('y', EX)

In [39]: %timeit rs_sin(x+a,x,1000)
10 loops, best of 3: 113 ms per loop

In [40]: %timeit rs_sin(y+a,y,1000)
1 loops, best of 3: 2.34 s per loop

In [41]: %timeit rs_cos(x+a,x,1000)
10 loops, best of 3: 118 ms per loop

In [42]: %timeit rs_cos(y+a,y,1000)
1 loops, best of 3: 2.43 s per loop
```

What do you think?

### CODE REVIEW

**Comment by certik** [comment]
I think this looks good. I think this is still a lot faster than the series that we have in SymPy currently, isn't it? So it seems to me there is a place for the EX domain.

**Comment by shivamvats** [comment]
Yes. A whole lot faster :)

```
In [60]: %timeit sin(a+b).series(a,0,100)
1 loops, best of 3: 3.09 s per loop
```
Sympy's series takes more time to calculate one tenth of the order.

Another approach faster than `EX` is to let the function determine the domain of coefficients. Since, rs_sin/rs_cos knows it needs `sin(a), cos(a)` , it returns a series over `QQ[sin(a), cos(a)]`, irrespective of the domain of the input. But this might be less flexible.

**Comment by certik** [comment]
I would do EX. I think the other approach will not work in a all cases.

**Comment by shivamvats** [comment]
@jksuom What do you think of this ? `EX` is slower than `QQ`. Can we do better?

**Comment by jksuom** [comment]
It seems to me that the results of computing with either ring are essentially the same. They are elements of different polynomial rings, but ``as_expr`` they should be the same. Thus one could compute ``t = rs_sin(x + a, x, 5)`` with coefficients in ``QQ[sin(a), cos(a), a]`` and then take ``t.as_expr()``. If necessary, that can also be transformed to an element of ``R = PolyRing("x", EX)`` by ``R.ring_new(t.as_expr())``.

**Comment by shivamvats** [comment]
@certik @thilinarmtb @jksuom This PR is ready for review. All elementary functions work on the `EX` ring.

**Comment by certik** [comment]
There seems to be one failure:
```
_______________ sympy/polys/tests/test_ring_series.py:test_tanh ________________
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/polys/tests/test_ring_series.py", line 384, in test_tanh
    EX(tanh(a)**3 - tanh(a))*x**2 + EX(-tanh(a)**2 + 1)*x + EX(tanh(a))
AssertionError
```

**Comment by certik** [comment]
This looks good to me. After you fix the failure, I think we can merge it.

**Comment by shivamvats** [comment]
The call to `sympify` in `EX` converts `PythonRational` type to float. Is than intentional?
```
In [65]:sympify(PythonRational(1,2))
Out[65]: 0.500000000000000
```
But
```
In [66]:sympify(Rational(1,2))
Out[66]: 1/2
```
One solution is this:
```
In [67]: R(QQ(1,2))
Out[67]: EX(1/2)
```
But I think `QQ` should also work.

**Comment by certik** [comment]
That seems like a bug to me.

**Comment by thilinarmtb** [comment]
Looks good to me as well. +1 to merge after fixing failures.

**Comment by shivamvats** [comment]
The failure is fixed now.

**Comment by certik** [comment]
This looks good, thanks!

**Pull request merged**
