### PR TITLE
Remove evalf call from nsolve

### LINKED ISSUE #8564: nsolve loses accuracy when solving `x*x == pi`
It looks like sometimes nsolve is limited to double precision:

```
sympy.mpmath.mp.dps = 128
e1 = Eq(x*x, pi)
q = nsolve(e1, x, 3.0)

sin(q*q)   # i.e., sin(pi)
Out[30]: 0.00000000000000323108914886517363090877526387617491958104246375523750266199776312416052999856025822151250757371201176461629253175135549

q - N(sqrt(pi), 128)
Out[45]: mpf('-0.00000000000000091147342065195854887259993738062373324012048212675893913882065856629599443261056363296123272878981225608269284506517613253555513073')
```

But it often works properly, even on "harder" problems:

```
e2 = Eq(tan(x/4), 1)
q = nsolve(e2, x, 3.0)
sin(q)
Out[35]: -3.3218e-130
```

Other things that do work include `x*x == pi*pi` and `x*x == 2`.

### PR DESCRIPTION
**Pull request by asmeurer**
This removes precision if the mpmath.mp.dps is set higher. It should be
unnecessary at any rate, since the expression is lambdified to an mpmath
expression.

Note, this is based off of pull request #11861. Without it, the test for this
fix does not run.

Fixes #8564.

CC @cbm755

### CODE REVIEW

**Comment by asmeurer** [comment]
@scopatz

**Comment by scopatz** [comment]
This seems reasonable to me.

**Comment by asmeurer** [comment]
As a final change, I would like to add a `prec` argument to `nsolve`, so that people don't have to mess with `mpmath.mp.dps`. However, nsolve returns `mpf` objects, meaning that if the precision is reset after the call, the mpf object will also have its precision reset (actually the internal `_mpf_` representation isn't reset, but the `mpf` printer uses the current `mpmath.mp.dps`, and I'm sure other problems could arise by not resetting it). 

Ideally nsolve should return Float objects anyway. However, this would be an API break. Should we deprecate it somehow (I'm not sure how)? What do people think? @cbm755

**Comment by asmeurer** [comment]
I'll keep that change to a separate PR, in case it's controversial. This is ready to review again, although I'm not 100% confident that all the tests will pass with the latest changes.

**Comment by asmeurer** [comment]
OK, the latest commit is wrong (it doesn't set the `_prec` on the Float correctly).

**Comment by asmeurer** [comment]
OK, now it should be better (but let's see if the tests pass).

**Comment by asmeurer** [comment]
I've submitted the change to make nsolve return Float/Matrix at https://github.com/sympy/sympy/pull/11888. It depends on this PR, but I've submitted it separately as it may be controversial, and I don't want it to block these fixes.

**Comment by asmeurer** [comment]
@smichr if you are available I would love to hear your input on the changes I've made to the core.

**Comment by asmeurer** [comment]
There are some test failures. I'll take a look tomorrow.

**Comment by asmeurer** [comment]
Hopefully the last change. A lot of mistakes across the commits but I think I've got something right now.

**Comment by scopatz** [comment]
Thanks a ton @asmeurer! This looks good to me and the tests pass!

**Pull request merged**
