### PR TITLE
Plotting Piecewise with Eq or Ne now works

### LINKED ISSUE #11461: NameError: name 'Ne' is not defined plotting real_root((log(x/(x-2))), 3)
```
In [46]: plot(real_root((log(x/(x-2))), 3))
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/experimental_lambdify.py in __call__(self, args)
    193             #The result can be sympy.Float. Hence wrap it with complex type.
--> 194             result = complex(self.lambda_func(args))
    195             if abs(result.imag) > 1e-7 * abs(result):

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/experimental_lambdify.py in __call__(self, *args, **kwargs)
    310     def __call__(self, *args, **kwargs):
--> 311         return self.lambda_func(*args, **kwargs)
    312

<string> in <lambda>(x0)

NameError: name 'Ne' is not defined

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-46-6f7419bdd56c> in <module>()
----> 1 plot(real_root((log(x/(x-2))), 3))

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/plot.py in plot(*args, **kwargs)
   1293     plots = Plot(*series, **kwargs)
   1294     if show:
-> 1295         plots.show()
   1296     return plots
   1297

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/plot.py in show(self)
    194             self._backend.close()
    195         self._backend = self.backend(self)
--> 196         self._backend.show()
    197
    198     def save(self, path):

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/plot.py in show(self)
   1027
   1028     def show(self):
-> 1029         self.process_series()
   1030         #TODO after fixing https://github.com/ipython/ipython/issues/1255
   1031         # you can uncomment the next line and remove the pyplot.show() call

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/plot.py in process_series(self)
    906             # Create the collections
    907             if s.is_2Dline:
--> 908                 collection = self.LineCollection(s.get_segments())
    909                 self.ax.add_collection(collection)
    910             elif s.is_contour:

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/plot.py in get_segments(self)
    512                     list_segments.append([p, q])
    513
--> 514             f_start = f(self.start)
    515             f_end = f(self.end)
    516             sample([self.start, f_start], [self.end, f_end], 0)

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/experimental_lambdify.py in __call__(self, args)
    227                                                     use_evalf=True,
    228                                                     complex_wrap_evalf=True)
--> 229                 result = self.lambda_func(args)
    230                 warnings.warn('The evaluation of the expression is'
    231                         ' problematic. We are trying a failback method'

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/experimental_lambdify.py in __call__(self, *args, **kwargs)
    309
    310     def __call__(self, *args, **kwargs):
--> 311         return self.lambda_func(*args, **kwargs)
    312
    313

<string> in <lambda>(x0)

NameError: name 'Ne' is not defined
```

### LINKED ISSUE #11865: can't plot piecewise function
When I do

```
ω = sym.symbols('omega')
k = sym.symbols('k', real=True, k=integer)
f = sym.integrate(sym.exp(sym.I*ω*k), (ω,-π,π))
```

I cannot do

`sym.plot(f)`

However, just plotting the second piece works, via

`sym.plot(1 / (2 * π) * f.args[1][0])`

### LINKED ISSUE #16572: Problem with plotting discontinuities in the current master
I have tried plotting the discontinuities as mentioned [here](https://github.com/sympy/sympy/blob/d383496deb5bed647ed930fd0194c0f57dba495d/examples/beginner/plot_discont.ipynb)
But the current master doesn't give the output. It is simply displaying a blank plot.
Although SymPy version 1.3 gives the correct result.
```
>>> from sympy import LambertW, Symbol
>>> from sympy.plotting import plot
>>> x = Symbol('x')
>>> plot(LambertW(x))
```
Output from the current master:
image

Same goes for `sqrt()` plots and `plot(1/x,(x, 0, 3))`

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Fixes #11461
Fixes #11865
Closes #16572 (issue fixed in #17409 , but test added here).

#### Brief description of what is fixed or changed
Experimental lambdify didn't know about `Ne` (#11865) and even if it knew about `Eq`, the generated code lead to errors (#11461). 

#### Other comments
Not sure why I need to add the handling it twice. It seems like the `namespace` should possibly handle it, but it doesn't.

Added test for #16572, which I found while browsing, although the issue was fixed earlier.

#### Release Notes

* plotting
   * Plotting of `Piecewise` with `Eq` or `Ne` works.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
The examples in the tests don't work for me if I don't have show=False.

The LambertW example opens the plot Window but there is no plot line.

The real_root example fails with:
```
~/current/sympy/sympy/sympy/plotting/plot.py in get_segments(self)
    663                     list_segments.append([p, q])
    664 
--> 665             f_start = f(self.start)
    666             f_end = f(self.end)
    667             sample([self.start, f_start], [self.end, f_end], 0)

~/current/sympy/sympy/sympy/plotting/experimental_lambdify.py in __call__(self, args, kwargs)
    230                                                     use_evalf=True,
    231                                                     complex_wrap_evalf=True)
--> 232                 result = self.lambda_func(args)
    233                 warnings.warn('The evaluation of the expression is'
    234                         ' problematic. We are trying a failback method'

~/current/sympy/sympy/sympy/plotting/experimental_lambdify.py in __call__(self, *args, **kwargs)
    315 
    316     def __call__(self, *args, **kwargs):
--> 317         return self.lambda_func(*args, **kwargs)
    318 
    319 

<string> in <lambda>(x0)

AttributeError: 'bool' object has no attribute 'evalf'
```
The Piecewise example fails with
```
~/current/sympy/sympy/sympy/plotting/plot.py in get_segments(self)
    663                     list_segments.append([p, q])
    664 
--> 665             f_start = f(self.start)
    666             f_end = f(self.end)
    667             sample([self.start, f_start], [self.end, f_end], 0)

~/current/sympy/sympy/sympy/plotting/experimental_lambdify.py in __call__(self, args, kwargs)
    230                                                     use_evalf=True,
    231                                                     complex_wrap_evalf=True)
--> 232                 result = self.lambda_func(args)
    233                 warnings.warn('The evaluation of the expression is'
    234                         ' problematic. We are trying a failback method'

~/current/sympy/sympy/sympy/plotting/experimental_lambdify.py in __call__(self, *args, **kwargs)
    315 
    316     def __call__(self, *args, **kwargs):
--> 317         return self.lambda_func(*args, **kwargs)
    318 
    319 

<string> in <lambda>(x0)

NameError: name 'Ne' is not defined
```

**Comment by oscargus** [comment]
Hmm... Weird! 

```
from sympy import *
x = Symbol('x')
plot(LambertW(x))
k = Symbol('k', integer=True)
f = Piecewise((-I*exp(I*pi*k)/k + I*exp(-I*pi*k)/k, Ne(k, 0)), (2*pi, True))
plot(f)
plot(real_root((log(x/(x-2))), 3))
```
gives
image
image
image

**Comment by oscargus** [comment]
The failing test may be related to that Piecewise require numpy to evaluate, but that is just a guess.

**Comment by oscargus** [comment]
Are you sure that you have updated the experimental_lambdify? Those errors shouldn't really happen...

**Comment by oscarbenjamin** [comment]
How do I update the experimental_lambdify?

**Comment by oscarbenjamin** [comment]
Ah okay. The examples work when run in a script but they don't work in isympy.

**Comment by oscargus** [comment]
> How do I update the experimental_lambdify?

Nothing special. It was just that the errors were the same as before, so a failed merge or reload seemed like a likely cause for those.

I haven't tried isympy, but I do not think that there is something special with these plots.

**Comment by oscarbenjamin** [comment]
Thanks. Merging

**Pull request merged**
