### PR TITLE
Change the StrPrinter of set() to print using {}

### PR DESCRIPTION
**Pull request by asmeurer**
This matches the default Python 3 repr printing. Now that we don't support
Python 2.6, set literals are valid in all Python versions of Python that we
support.
- Change sstr(set) and sstr(frozenset) to print using {} (or 'set()' for the
  empty set).
- Change the str printer tests, and add a few extra tests.
- Add a custom printer for AssumptionsContext, so that it continues to print
  its name.
- Fix all doctests.
- Change a few instances of set literals to use {} in code.

### CODE REVIEW

**Comment by asmeurer** [comment]
Oops, looks like my regex missed the mark in one of the doctests. Fixed.

**Comment by asmeurer** [comment]
I've fixed the merge conflicts.

**Comment by asmeurer** [comment]
I just tried the new GitHub conflict resolution here. Hopefully it didn't screw up too bad.

**Comment by asmeurer** [comment]
Doctests fixed. The Sphinx Travis build will fail until https://github.com/sympy/sympy/pull/11935 is merged, at which point it can be restarted.

**Review by moorepants — APPROVED** [review]
Looks good to me.

**Comment by jksuom** [comment]
Looks good to me too.

**Pull request merged**
