### PR TITLE
Improved fluid mechanics pr 

### PR DESCRIPTION
**Pull request by ashishkg0022**
Improved fluid mechanics pr #12611  as mentioned in issue #13514

### CODE REVIEW

**Comment by moorepants** [comment]
It is preferable to include the commits from the previous PR so that all authors' contributions are included in the repository history.

**Comment by ashishkg0022** [comment]
thanks @moorepants  . i will try to update it .

**Comment by ashishkg0022** [comment]
@moorepants  please review it, I have added commits from the previous pr.

**Comment by Upabjojr** [comment]
This PR looks pretty useless.

**Comment by ashishkg0022** [comment]
@Upabjojr  i tried to this as mentioned in issue #13514 . can you please tell what this issue is asking for ?

**Comment by Upabjojr** [comment]
I just don't see why this code could be helpful to anyone.

**Comment by ashishkg0022** [comment]
so , do issue #13514 needs to be closed ?

**Comment by gxyd** [comment]
@ashishkg0022 on second thought let's just close this PR and the issue.

**Comment by ashishkg0022** [comment]
thanks @gxyd :)

**Comment by Upabjojr** [comment]
@ashishkg0022 maybe you could have a look at the units module: http://docs.sympy.org/latest/modules/physics/units/examples.html

I think that's the right approach to define dimensions and units.

**Pull request closed without merging**
