### PR TITLE
Minor correction on Poly.replace

### LINKED ISSUE #19161: When applying simplify on a Poly it fails:
Executing the code:

```python
sp.Poly('x**2').simplify()
```

Generates the error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-51-9795ccd009a0> in <module>
----> 1 sp.Poly('x**2').simplify()

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sympy/core/expr.py in simplify(self, **kwargs)
   3495         """See the simplify function in sympy.simplify"""
   3496         from sympy.simplify import simplify
-> 3497         return simplify(self, **kwargs)
   3498 
   3499     def nsimplify(self, constants=[], tolerance=None, full=False):

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sympy/simplify/simplify.py in simplify(expr, ratio, measure, rational, inverse, doit, **kwargs)
    578             x, handled),
    579         lambda x: x.func(*[simplify(i, **kwargs) for i in x.args]),
--> 580         simultaneous=False)
    581     if not isinstance(expr, handled):
    582         return done(expr)

TypeError: replace() got an unexpected keyword argument 'simultaneous'
```

### PR DESCRIPTION
**Pull request by jmgc**
#### References to other Issues or PRs

Fixes #19161

#### Brief description of what is fixed or changed

Poly.replace was expecting a variable number of arguments after a keyword argument, modified to accept a variable number of keyword arguments (**)

#### Release Notes

* polys
    * Solved bug in Poly.replace

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Is it possible to just remove the `Poly.replace` method?

**Comment by jmgc** [comment]
Poly.replace is called by Poly('x**2').simplify() (see #19161)

**Comment by oscarbenjamin** [comment]
Yes, but there already is a `Basic.replace` method in the superclass. Ideally `Poly` would not redefine this method.

**Comment by oscarbenjamin** [comment]
I'll merge this for now but I think it would be better to remove the replace method ultimately

**Pull request merged**
