### PR TITLE
Fixing Sum limits in case of set

### LINKED ISSUE #14587: Sum on open intervals
Expression with limits should handle limits differently for `Integral` and `Sum`:
```
In [1]: Integral(x, (x, Interval.open(2, 5)))
Out[1]: 
5     
⌠     
⎮ x dx
⌡     
2     
```
This is correct, as the integral does not really care about open/closed intervals (unless you put a Dirac delta in it).

On the other hand:
```
In [2]: Sum(x, (x, Interval.open(2, 5)))
Out[2]: 
  5    
 ___   
 ╲     
  ╲   x
  ╱    
 ╱     
 ‾‾‾   
x = 2  
```
This result is wrong. The limits should be `(3, 4)`, as the interval is open.

### PR DESCRIPTION
**Pull request by Upabjojr**
#### References to other Issues or PRs

Fixes  #14587

### CODE REVIEW

**Comment by asmeurer** [comment]
I don't remember what Sum does with noninteger limits, but we should check if this is correct for that case.

**Comment by Upabjojr** [comment]
Honestly,  I would suggest to leave the set notation unevaluated. We could leave the set unevaluated and just solve for the limits when .doit() is called.

**Comment by asmeurer** [comment]
We would need to have printing for that case.

**Comment by oscargus** [comment]
Here is an example of what `Sum`does in terms on noninteger limits (or rather su

```
>>> Sum(k, (k, 0.5, 1.5)).doit()
2.0
```
which sort of makes sense. However,

```
>>> Sum(k, (k, 0.5, 1.6)).doit()
2.205
```
Which to me is not obvious (without studiying the code), although I would guess that some closed form expression is used without checking that there are integer limits.

Hence, using open sets may lead to a different behaviour compared to the current one I guess. But not really obvious what should happen. One may even expect an error in the summation in case of non-integer limits.

Interestingly
```
>>> Sum(sin(k), (k, 0.5, 1.5)).doit()
```
is left unevaluated, while
```
>>> Sum(sin(k), (k, 1, 2)).doit()
sin(1) + sin(2)
```
so something in the code prohibits explicit evaluation when there are non-integer limits (something that happens for "small" sequences, <100(?), otherwise).

**Comment by oscargus** [comment]
https://www.sciencedirect.com/science/article/pii/S0377042704003851
#5822
https://math.stackexchange.com/questions/766440/summation-with-non-integer-induces

**Comment by czgdp1807** [comment]
I think that giving an `Interval` as input isn't a good idea. In fact, `Sum` now accepts `Range` as limits which is more intuitive. Summing over an interval isn't practically possible because an interval has infinite number points for start and end are not same. `Interval` should be passed to `Integral` and `Range` should be passed to `Sum`. @Upabjojr @asmeurer

**Comment by czgdp1807** [comment]
@Upabjojr What do you say on https://github.com/sympy/sympy/pull/14597#issuecomment-531456378 ?

**Comment by czgdp1807** [comment]
@Upabjojr You views on the above comment.

**Comment by asmeurer** [comment]
> I think that giving an Interval as input isn't a good idea. In fact, Sum now accepts Range as limits which is more intuitive. Summing over an interval isn't practically possible because an interval has infinite number points for start and end are not same. Interval should be passed to Integral and Range should be passed to Sum. @Upabjojr @asmeurer

I agree with this. I would expect a summation over a non-countable set to be meaningless. Even summing over a non-ordered infinite set should be done with care as it's only meaningful if the sum converges absolutely (it would be dangerous to implicitly assume there is an ordering to any set other than Range and Naturals).

**Comment by czgdp1807** [comment]
Closing this for now as in reference to the above comment. I will open a new issue for disallowing Interval and similar sets in `Sum`.

**Pull request closed without merging**
