### PR TITLE
Marked some tests as slow

### PR DESCRIPTION
**Pull request by siefkenj**
Travis seems to be failing often on SPLIT="1/4".  Two tests

    test_imaginary - Took 226.113 seconds
    test_real - Took 321.026 seconds

Seem to be taking ~5min a piece.  They should be marked as slow tests.

### CODE REVIEW

**Comment by gxyd** [comment]
On my system
```
________________________________________________________________ slowest tests ________________________________________________________________
test_odd - Took 13.618 seconds
test_even - Took 13.685 seconds
test_real - Took 17.410 seconds
test_zero_positive - Took 19.677 seconds
test_rational_irrational - Took 26.295 seconds
test_integer - Took 30.518 seconds
test_pow_pos_neg - Took 80.392 seconds
====================================== tests finished: 15 passed, 1 expected to fail, in 245.65 seconds =======================================
```
So shouldn't the test `test_pow_pos_neg` be marked as slow, since it is the one taking the longest time? Or some other criterion is used to mark them as slow or fast?

**Comment by siefkenj** [comment]
@gxyd I'm not really sure what the procedure is.  I also don't know how tests are split up by the `SPLIT` variable.  It seems like the tests splits need to be rebalanced.

**Comment by jksuom** [comment]
On my system it also looks like `test_pow_pos_neg` were the only one to be considered slow.
```
________________________________ slowest tests _________________________________
test_even - Took 12.880 seconds
test_odd - Took 13.057 seconds
test_real - Took 17.241 seconds
test_zero_positive - Took 20.586 seconds
test_rational_irrational - Took 27.695 seconds
test_integer - Took 30.445 seconds
test_pow_pos_neg - Took 67.659 seconds
================= tests finished: 15 passed, in 230.42 seconds =================
```

**Comment by jksuom** [comment]
These are the slowest tests in split 1/4 (>10 min. together).
```
test_real - Took 201.808 seconds
test_pow - Took 266.707 seconds
test_imaginary - Took 272.119 seconds
```
`test_pow` is in test_refine.py, the other two slow ones are in test_query.py (not in test_satask.py).

**Comment by jksuom** [comment]
Thanks, this looks good. Split 1/4 is no more on the verge of timing out. Slow tests take some more time but they are still safely below the 50 min bound.

**Pull request merged**
