### PR TITLE
Add fix in MatMul

### PR DESCRIPTION
**Pull request by mloubout**
#### Brief description of what is fixed or changed

Currently, MatMul hardcodes `sympy.Add` which prevents its usage with custom types with their own Add. `sum` does check if objects have their own add first and is safer. It also avoids local import.

#### Release Notes

* matrices
  * Switch Add to sum in matmul.

### CODE REVIEW

**Comment by sylee957** [comment]
Since sympy matrix can also contain block matrices, I don't think that using `sum` for the dot product is sturdy because it adds constant `0` term.
Have you tried replacing with `reduce(lambda a, b: a + b, vec)`?

**Comment by oscarbenjamin** [comment]
The reason `Add(*vec)` is used in general is because the cost of the `flatten` routine is linear in the number of terms. When you use `sum(vec)` (or `reduce`) then `flatten` is called once per arg making a quadratic cost over the whole sum.

In general I would like to deprecate having non-Expr in a Matrix so we don't have to work around issues like this.

What kind of object are you putting in the matrix that doesn't work in this case?

**Comment by mloubout** [comment]
I'm basically working with object that inherit from `Expr` and that need to stay that type after Add/Mul/.... 
The matrix itself is fine thanks to the very nice `classof` but  its coeffifient loose their type with explicit call to Add.

>In general I would like to deprecate having non-Expr in a Matrix so we don't have to work around issues like this.

That'd be nice but I assume quite the wrok

>because the cost of the flatten routine

That's a good point. Maybe a extra cummulative sum or something would be better (but maybe not as pretty). I could always have my own `_eval_matrix_mul` but trying to inherit as much as possible.

**Comment by oscarbenjamin** [comment]
> I'm basically working with an object that inherits from `Expr` and that need to stay that type after Add/Mul/....

This is a common problem in sympy that needs to be solved. Really you need to hook into Add to ensure that it handles your object correctly. I think that maybe the solution is to have some kind of `sympysum` function that can work out how to add objects. See #18769 and #19463

**Comment by mloubout** [comment]
>This is a common problem in sympy that needs to be solved

Yes we been running into it quite a bit indeed. Will check theses issues. Feel free to close this one uf you think it should be.

**Comment by oscarbenjamin** [comment]
See also #14490.

**Comment by mloubout** [comment]
Closing for now

**Pull request closed without merging**
