### PR TITLE
Replace dict comprehensions with fromkeys

### PR DESCRIPTION
**Pull request by Skylion007**
#### Brief description of what is fixed or changed
* Replaces dict comprehensions with dict.fromkeys. This is significantly more efficient than using a dict comprehension. It also can make certain bugs (like sharing the same mutable instance for all values in a dict) more apparent. They are otherwise semantically equivalent.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by haru-44** [comment]
looks good. but

> It also can make certain bugs (like sharing the same mutable instance for all values in a dict) more apparent.

What is the event? Do you have specific examples?

**Comment by Skylion007** [comment]
@haru-44 
For example:
```python
a = list()
d = {k: a for k in keys}
```
appending an element to to `keys[0]` appends it to the value of all keys. This behavior is sometime wanted, but using fromkeys make it a but more clear:
```python
d = dict.fromkeys(keys, a)
```
It's now explicit all keys will share the same value and mutating 1 value in the dict will affect the value stored in other keys. If you wanted them to be different, you should have written:
```python
d = {k: [] for k in keys}
```

**Comment by haru-44** [comment]
@Skylion007 
Thank you for the explanation.
I understood.

**Comment by sylee957** [comment]
I was also not very familiar with `fromkeys`, however, it looks like it was researched by the ruff community

Was the cases detected by running ruff and `RUF025`?
https://docs.astral.sh/ruff/rules/unnecessary-dict-comprehension-for-iterable/

**Pull request merged**
