### PR TITLE
Fix issue where solveset throws PolificationError when x cancels out (Edit)

### LINKED ISSUE #15351: Solveset throws PolificationError when x cancels out
Trying to solve
`solveset((2*x-2)/(1+x)-(2*x)/(2+x))`
gives
`sympy.polys.polyerrors.PolificationFailed: can't construct a polynomial from -2*x*(x + 1) + 2*(x - 1)*(x + 2)`.
The actual equation should have no solutions.

I haven't yet looked into how that function works but I suspect that the issues has something to do with the fact that
`>>> expand(-2*x*(x + 1) + 2*(x - 1)*(x + 2))`
`-4`
and trying to call `poly_from_expr(expr)` when the expr is a whole number throws a PolyficationError.

This was tested with both Sympy version 1.3 and 1.4.dev

### PR DESCRIPTION
**Pull request by JMSS-Unknown**
Fixes #15351

I deleted my fork so I could no longer edit #15443 
This is an update to address @asmeurer comment (https://github.com/sympy/sympy/pull/15443#issuecomment-434776485)

* solvers
  * Fixed a bug where solveset would not find the solution when the variable in a polynomial cancels out

### CODE REVIEW

**Comment by JMSS-Unknown** [comment]
Actually, a better fix might be to add `expand=False` to `p, _ = poly_from_expr(f)` on line 4454. That seems to also fix issue #6322

**Comment by asmeurer** [comment]
That's incorrect

```py
>>> a = poly_from_expr((x + 1)**1000, expand=False)
>>> a
(Poly((x + 1)**1000, x + 1, domain='ZZ'), {'expand': False, 'polys': False, 'domain': ZZ, 'gens': (x + 1,)})
```

**Comment by asmeurer** [comment]
The real bug here is `degree(-2*x*(x + 1) + 2*(x - 1)*(x + 2))`. So we should add a test for it directly. We can also add a test for solveset to make sure it works. 

I don't understand why `poly_from_expr` doesn't have the `gen` argument from degree passed to it. Based on the traceback, changing that should fix the solveset issue. 

Making `degree(-2*x*(x + 1) + 2*(x - 1)*(x + 2))` without a generator argument should work too. It looks like `PolyficationFailed` stores the expanded polynomial as `expr`. So you can check if it is a constant by inspecting that attribute from the exception. That would be better than calling `expand`, which is already done in `poly_from_expr`, so shouldn't be done again (`expand` can be expensive in general).

**Comment by JMSS-Unknown** [comment]
@asmeurer I have addressed your comments

**Comment by oscarbenjamin** [comment]
Can you rebase this branch to master?

**Comment by czgdp1807** [comment]
@JMSS-Unknown Please resolve the conflicts.

**Comment by czgdp1807** [comment]
Closing as the associated issue has been fixed.

**Pull request closed without merging**
