### PR TITLE
Fixes #26923: Updated reference image in SVG format to replace outdated PNG

### LINKED ISSUE #26923: Create an SVG figure for the MDoF Pendulum example
This example:

https://docs.sympy.org/dev/tutorials/physics/mechanics/multi_degree_freedom_holonomic_system.html

has a PNG as the figure:

image

I drew it on a Microsoft surface for a lecture a long time back and the surface gave wavy lines. This figure needs to be replaced with an SVG (pngs shouldn't be committed to the repo, this one was) and the figure should look better.

### PR DESCRIPTION
**Pull request by s-hanlon**
#### References to other Issues or PRs

Partially addresses #26923 

#### Brief description of what is fixed or changed
I created a new '.svg' version of the diagram for Multi Degree of Freedom Holonomic System example.
I added the new '.svg' file and then updated the 'multi_degree_freedom_holonomic_system.rst' file to  include the new image.

#### Release Notes

* physics.mechanics
  * Updated the reference image in 'multi_degree_freedom_holonomic_system.rst' to a better '.svg' image replacing the old '.png'.

### CODE REVIEW

**Comment by moorepants** [comment]
Thanks for the PR. This converts a png to svg strokes with no png embedding. This only partially solves the open issue, as the image is still the same, but we can merge because an Svg fixes half the issue. You need to add your name to the authors file.

**Comment by moorepants** [comment]
Also the png should be removed with `git rm`.

**Comment by moorepants** [comment]
Note that someone else has already opened a PR for this at https://github.com/sympy/sympy/pull/27121

**Comment by oscarbenjamin** [comment]
> This converts a png to svg strokes with no png embedding.

What advantage is it to have this svg file rather than the png file?

I agree that svg is usually better for diagrams but converting a raster format like png to svg does not generally give any benefit. In this case the svg image uses more bytes than the png image and it does not really make the image zoomable.

**Comment by moorepants** [comment]
This change isn't particularly helpful, I agree. The only thing this fixes, is that the figure becomes editable by SVG editing software or by manipulating the text in the SVG file. That is a positive, but I doubt anyone will ever edit it. We really just need a new figure drawn for this that aligns with the other better figures. I committed this PNG (or merged someone else's commit) and shouldn't have done that. We've tried to avoid committing bitmap images to the repository for git bloat reasons, but some have snuck in over the years.

**Comment by moorepants** [comment]
Solved by #27166

**Pull request closed without merging**
