### PR TITLE
[WIP] refactor: Remove Q.is_true wrapping of relationals 

### PR DESCRIPTION
**Pull request by JSS95**
#### Brief description of what is fixed or changed

Previously, relations needed to be wrapped by `Q.is_true` to be assumed by `ask` or `refine`.  Now, they are automatically converted to `Q.eq`, etc.

`Q.eq` and other predicates just wraps lhs and rhs. Evaluation by `ask` is delegated to corresponding `Relational` object.

Previous:
```python
>>> refine(Piecewise((1, x < 0), (3, True)), Q.is_true(x < 0))
1
```

Now:
```python
>>> refine(Piecewise((1, x < 0), (3, True)), x < 0)
1
```

#### Other comments

`Q.eq` and other predicates are needed to integrate `core/relational` with `assumptions` module in the future.  For example `x > y` implies that both `x` and `y` are comparable, which can be done with something like `Implies(Q.gt, AllArgs(Q.real))`.

#### Release Notes

- assumptions
  - `Q.eq`, `Q.ne`, `Q.le`, `Q.lt`, `Q.ge`, `Q.gt` are introduced.
  - `Q.is_true` on `Relational` objects now calls corresponding predicate.
- core
  - `Relational` objects do not need to be wrapped by `Q.is_true` to be assumed anymore.

### CODE REVIEW

**Comment by JSS95** [comment]
@asmeurer @oscarbenjamin

This PR is the minimal implementation of #20723. `Q.eq` and other predicates are introduced to replace `Q.is_true(Eq(...))`. Evaluation logic is delegated to `core/relational`, which I plan to enhance in the future.

**Comment by asmeurer** [comment]
I still think we need just one boolean equation class, meaning Eq should just be a predicate. I'm assuming that isn't easy to do now because of complications from not also having a separate symbolic non-boolean equation class?

**Comment by JSS95** [comment]
@asmeurer 
I plan to make `Eq` a predicate, but the diff will be quite large so I want to break it down to small PRs. Also, we need to discuss the overall design.

**Comment by JSS95** [comment]
Does this design agree with your idea?

1. `Q.eq` is a predicate.
2. `Q.eq(x, y)` returns `AppliedRelation(Q.eq, (x,y))` object. MRO is `AppliedRelation -> AppliedPredicate`.
3. For backwards compatibility, `Eq(x,y)` or `Equality(x, y)` will be aliased to `Q.eq(x, y)`. However, it will be evaluated to `True` or `False` if possible.

**Comment by asmeurer** [comment]
Yes, that might be a good solution. I forgot that Eq also auto-evaluates, which makes it more difficult to use in predicate contexts.

**Comment by JSS95** [comment]
Replaced by #20965

**Pull request closed without merging**
