### PR TITLE
matrices: Fix wrong result in Sum over matrix expression

### LINKED ISSUE #16860: MatrixExpr.from_index_summation
```python3
>>> from sympy import *

>>> k = Symbol('k', integer=True)
>>> a, b = symbols('a, b')
>>> A = MatrixSymbol('A', k, k)

>>> expr = Sum(A[a, a], (a, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
Trace(A)

>>> expr = Sum(A[a, a], (a, 0, k-1), (b, 0, 1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
Trace(A)
```

Both are giving `Trace(A)`, however, should the latter one give `2*Trace(A)`?

### PR DESCRIPTION
**Pull request by bytes-as**
#### References to other Issues or PRs

Fixes #16860 

#### Brief description of what is fixed or changed
On giving some index in Sum() which are independent to
Matrix Element indices, those indices were ignored and the
the result was corresponding to the summation without that
independent indices

Example:

Before:
```
>>> expr = Sum(A[a, a], (a, 0, k-1), (b, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
Trace(A)
```
After:
```
>>> expr = Sum(A[a, a], (a, 0, k-1), (b, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
k*Trace(A)
```

#### Release Notes

* matrices
    * fixed the wrong calculation for summation over a matrix expression

### CODE REVIEW

**Comment by solus9** [comment]
@sylee957 I wanted to ask this that,
before:
```
>>> expr = Sum(A[a, a], (b, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
k*A
```
now:
```
>>> expr = Sum(A[a, a], (b, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
k*A[a, a]
```
as the expression is not being operated on the `a`, the result should be another expression as in the current example above right?

**Comment by sylee957** [comment]
Yes, the symbols used for summation range specification are dummy symbols, and the symbols not used in there should be exposed.
There are some test failings though.

**Comment by solus9** [comment]
> s used for summation range specification are dummy symbols, and the symbols not used in there should be exposed.

but with that logic, 
```
>>> MatMul(A, B)[i, k]
Sum(A[i, _i_1]*B[_i_1, k], (_i_1, 0, N - 1))
```
here the result is just another expression with the Sum operation corresponding to a single element in the A*B Matrix not the whole matrix product.

for those errors, Making changes to the case where the expression is a Matrix Element type, also affecting the result in the case where the expression is MatMul somehow, I am still trying to figure that out.

**Review by bytes-as — COMMENTED** [review]
I have added the calculation related to the independent indices when the expression includes Matrix Multiplication
earlier:
```
>>> expr = Sum(A[a,b]*B[b,c], (b, 0, k-1), (d, 0 ,k-1))
>>> expr =  MatrixExpr.from_index_summation(expr)
A*B

>>> expr = Sum(A[a,b]*B[b,c], (b, 0, k-1), (d, 0 ,k-1), (e, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
A*B

>>> expr = Sum(A[a, a]*B[b, c]*C[c, d], (a, 0, k-1), (c, 0, k-1), (e, 0, k-1))
>>> expr =  MatrixExpr.from_index_summation(expr, b)
Trace(A)*B*C
```

after:
```
>>> expr = Sum(A[a,b]*B[b,c], (b, 0, k-1), (d, 0 ,k-1))
>>> expr =  MatrixExpr.from_index_summation(expr)
k*A*B

>>> expr = Sum(A[a,b]*B[b,c], (b, 0, k-1), (d, 0 ,k-1), (e, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
k**2*A*B

>>> expr = Sum(A[a, a]*B[b, c]*C[c, d], (a, 0, k-1), (c, 0, k-1), (e, 0, k-1))
>>> expr =  MatrixExpr.from_index_summation(expr, b)
(k*Trace(A))*B*C
```
@sylee957, let me know if there is anything else for this part.

**Comment by Upabjojr** [comment]
There is a method in `sympy/codegen/array_utils.py` which is supposed to replace`Matrix.from_index_summation`.

**Comment by solus9** [comment]
@Upabjojr, Thanks for the information, but then this method `Matrix.from_index_summation` is going to be removed or it is supposed to be what it was without my changes? I meant to ask that what should I do, close the PR leaving that module as it was or these changes are fine.

**Comment by Upabjojr** [comment]
That method was a stub and has been better rewritten in array_utils. There are two functions that combined work the same way.

What about trying to link this method to the code in array_utils?

**Comment by solus9** [comment]
@Upabjojr Thanks for the suggestion, I am a beginner here and not familiar with all the modules, and to be honest I am not sure how to do what you just suggest, can you guide me on that, I would be happy to it.
Thanks for the your time.

**Comment by Upabjojr** [comment]
```python
from sympy.codegen.array_utils import *
cg = parse_indexed_expression(expr)
result = recognize_matrix_expression(cg)
```

These expressions are supposed to replace `.from_index_summation`. I see there are bugs anyway, so maybe they should be fixed in `sympy/codegen/array_utils.py`.

**Comment by Upabjojr** [comment]
The advantage of these expressions is that the code is written in a cleaner way, and especially you have intermediate states (i.e. `cg` variable) to represent the parsed expression before converting it to a matrix expression.

**Comment by solus9** [comment]
Thankyou @Upabjojr, while I was going through the code what I found is this
```
def _codegen_array_parse(expr):
    if isinstance(expr, Sum):
        function = expr.function
```
below here we are getting all the variables out of that expression, no matter they are having any effect on results or not.
```
        summation_indices = expr.variables
```
then the variables involved in the function which will be affecting the results are getting stored in subindices
```
        subexpr, subindices = _codegen_array_parse(function)
        # Check dimensional consistency:
        shape = subexpr.shape
        if shape:
            for ind, istart, iend in expr.limits:
```
down here the function `_get_argindex(subindices, ind)` is raising an error because the dummy variables is not one of those that of in the function, any comments on that would be appreciated
```
                i = _get_argindex(subindices, ind)
```
another thing that is bugging me that why are we just assuming that the expression is always about finding the trace or anything which starts from 0 and end at the last element of the Matrix, I mean that the expression might be `Sum(A[a, a], (a, 0, k-3))` where the matrix element is `A = MatrixSymbol('A', k, k)`. In such a case, the code raises the error `ValueError: summation index and array dimension mismatch: a`
```
                if istart != 0 or iend+1 != shape[i]:
                    raise ValueError("summation index and array dimension mismatch: %s" % ind)
        contraction_indices = []
        subindices = list(subindices)
        ...
```

again thank you for your kind reply. I am working on another project, that's why I am not able to work here continuously. Sorry for any inconvenience I am causing.

**Comment by oscarbenjamin** [comment]
What's the status of this? @solus9 @Upabjojr

**Comment by czgdp1807** [comment]
@Upabjojr Please review this.

**Comment by Upabjojr** [comment]
@czgdp1807 we now have some new code at `sympy/codegen/array_utils.py` to parse summation expressions. We should check if this issue is still open.

**Pull request closed without merging**
