### PR TITLE
Replace deprecated np.asscalar

### LINKED ISSUE #16062: Don't use deprecated np.asscalar
Running the tests locally under pytest I see 143 warnings about np.asscalar being deprecated:
```
/Users/enojb/current/sympy/venv/lib/python3.7/site-packages/numpy/lib/type_check.py:546: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
    'a.item() instead', DeprecationWarning, stacklevel=1)
```
I haven't looked into the difference but this looks easy to fix. Grep shows the two places where this is used in SymPy:
```console
$ grep -r --include=\*.py asscalar sympy
sympy/core/sympify.py:            return converter[complex](np.asscalar(a))
sympy/core/sympify.py:            return sympify(np.asscalar(a), **sympify_args)
```

### PR DESCRIPTION
**Pull request by divyanshu132**
#### References to other Issues or PRs
Fixes  #16062

#### Brief description of what is fixed or changed

Replace deprecated ` np.asscalar ` with ` a.item() `.
#### Release Notes

*  core
   *  replace np.asscalar in sympify

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This looks good. I haven't had any time to think about why `np.asscalar` is deprecated. Is it always the case that `a.item()` works as a dropin replacement?

**Comment by rajat-np** [comment]
Looks like `np.asscalar` is deprecated since numpy 1.16. As per the docs [https://docs.scipy.org/doc/numpy/reference/generated/numpy.asscalar.html?highlight=asscalar#numpy.asscalar](url), we should use `a.item()`.

**Comment by oscarbenjamin** [comment]
That link gave me a 404. I tried this instead:
[https://docs.scipy.org/doc/numpy/reference/generated/numpy.asscalar.html](https://docs.scipy.org/doc/numpy/reference/generated/numpy.asscalar.html)

From there:
```
Convert an array of size 1 to its scalar equivalent.

Deprecated since version 1.16: Deprecated, use numpy.ndarray.item() instead.
```

Looking up item I found:
[https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.item.html](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.item.html)
which says
```
Copy an element of an array to a standard Python scalar and return it.
...
the method only works for arrays with one element (a.size == 1), which element is copied into a standard Python scalar object and returned.
```

So it seems pretty clear that the numpy folks think we should use `.item`. There must be some difference though or I don't think they'd bother deprecating it (they could just make one a reference to the other).

In any case the advice is clear and this PR is good so I'll merge it.

**Comment by oscarbenjamin** [comment]
Thanks for this.

**Pull request merged**
