### PR TITLE
Solves Unpickling simple expressions errors

### LINKED ISSUE #18438: Unpickling simple expressions errors
Unpickling SymPy expressions containing variables and constants appears to be broken when the the unpickling occurs in a separate process.

I ran the following script in a process on Python 3.7.6 or 3.8.1 using SymPy 1.5.1 on Ubuntu 18.04:

```
from sympy.parsing.sympy_parser import parse_expr
import pickle
from pathlib import Path
file = Path(f'temp1.pickle')
file.write_bytes(pickle.dumps(parse_expr('a/2')))
```

This prints out 15596. (I'll leave aside the observation that 15k seems like a lot of bytes to store this three-character expression.)

I then run the following script in a separate process:

```
import pickle
from pathlib import Path
file = Path(f'temp1.pickle')
pickle.loads(file.read_bytes())
```

This raises the following exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/anaconda/envs/old/lib/python3.7/site-packages/sympy/core/singleton.py", line 176, in __call__
    super(Singleton, self).__call__(*args, **kwargs)
TypeError: __new__() takes 1 positional argument but 3 were given
```

The variable and the constant are both needed to cause this exception. If I run enough commands in the second process, it suddenly starts working for reasons that are unclear.

### PR DESCRIPTION
**Pull request by mohitacecode**
#### References to other Issues or PRs

Fixes #18438 
#### Brief description of what is fixed or changed
Solves Unpickling simple expressions errors by:
- Adding `Zero.__getnewargs__()`,  `One.__getnewargs__()`,  `NegativeOne.__getnewargs__()`, 
  `Half.__getnewargs__()`.
- Adding  `__getnewargs__()` and `args()` in miscellaneous.py.

#### Release Notes

*   core
     * `__getnewargs__()` added to  `Zero`,  `One`,  `NegativeOne`, `Half`.
*   functions
     * `__getnewargs__()` and `args()` added to `IdentityFunction`.

### CODE REVIEW

**Comment by sylee957** [comment]
Can you add some tests in test_pickling?

**Comment by mohitacecode** [comment]
I have done the required changes but it seems that the issue is still unresolved.
ps:
I may have check something else wrong while opening a pr.

**Comment by oscarbenjamin** [comment]
> t seems that the issue is still unresolved

What does that mean?

**Comment by mohitacecode** [comment]
I mean that I think the issue is still not fixed after applying the suggested changes.

I tried the following lines to check it:
```
>>> import pickle
>>> s = b'csympy.core.numbers\nHalf\np0\n(L1L\nL2L\ntp1\nRp2\n(dp3\nb.'
>>> pickle.loads(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mohit/Documents/sympy-master/sympy/sympy/core/singleton.py", line 178, in __call__
    super(Singleton, self).__call__(*args, **kwargs)
TypeError: __new__() takes 1 positional argument but 3 were given
>>> 
```

**Comment by oscarbenjamin** [comment]
Does `pickle.dumps` give the same output after the changes here?

**Comment by mohitacecode** [comment]
I only tried with the following lines.
```
>>> import pickle
>>> s = b'csympy.core.numbers\nHalf\np0\n(L1L\nL2L\ntp1\nRp2\n(dp3\nb.'
>>> pickle.loads(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mohit/Documents/sympy-master/sympy/sympy/core/singleton.py", line 178, in __call__
    super(Singleton, self).__call__(*args, **kwargs)
TypeError: __new__() takes 1 positional argument but 3 were given
```

**Comment by jksuom** [comment]
> s = b'csympy.core.numbers\nHalf\np0\n(L1L\nL2L\ntp1\nRp2\n(dp3\nb.'

This is the pickle string that current master creates. In this branch we get a different string:
```
>>> import pickle
>>> from sympy import S
>>> s = pickle.dumps(S.Half, 0)
>>> s
b'csympy.core.numbers\nHalf\np0\n(tRp1\n(dp2\nb.'
>>> pickle.loads(s)
1/2
>>> 
```

**Comment by mohitacecode** [comment]
> This is the pickle string that current master creates. In this branch we get a different string: 

So is it ready then?

**Comment by mohitacecode** [comment]
> Can you add some tests in test_pickling?

Sure I will add test.
will this example will be sufficient ?
```
>>> import pickle
>>> from sympy import S
>>> s = pickle.dumps(S.Half, 0)
>>> s
b'csympy.core.numbers\nHalf\np0\n(tRp1\n(dp2\nb.'

```

**Comment by jksuom** [comment]
The test should have both `dumps` and `loads` combined. Explicit pickle string is not important in the test.

**Comment by mohitacecode** [comment]
> The test should have both `dumps` and `loads` combined. Explicit pickle string is not important in the test.

Okay I will add the test accordingly.

**Comment by mohitacecode** [comment]
> The test should have both `dumps` and `loads` combined.

By this you mean something like this:

```
>>> pickle.loads(pickle.dumps(s))
b'csympy.core.numbers\nHalf\np0\n(tRp1\n(dp2\nb.'

```

**Comment by jksuom** [comment]
The argument should be a SymPy object of interest like `S.Half`, not a string like `s`. (That kind of objects have surely been tested already in Python.)

**Comment by mohitacecode** [comment]
I have added the test please see if it's ready

**Comment by mohitacecode** [comment]
ping @oscarbenjamin @jksuom

**Comment by jksuom** [comment]
Can you add a release not entry telling that `__getnewargs__` was added to `Zero`, `One`, ...?
Otherwise the code looks good.

**Comment by mohitacecode** [comment]
> Can you add a release not entry telling that `__getnewargs__` was added to `Zero`, `One`, ...?

Sure I have updated it.

**Comment by jksuom** [comment]
Thanks. Merging.

**Comment by mohitacecode** [comment]
Thanks :)

**Pull request merged**
