### PR TITLE
Increase performance of matrix power for 2-dim matrices

### PR DESCRIPTION
**Pull request by Upabjojr**

### CODE REVIEW

**Comment by Abdullahjavednesar** [comment]
@Upabjojr Can you kindly add the relevant commits from my closed PR #11808  here ?

**Comment by Abdullahjavednesar** [comment]
I guess this PR is ready to get merged @jksuom @asmeurer 
If yes, kindly add the relevant commits from my closed PR #11808.
Thanks.

**Comment by jksuom** [comment]
How should singular matrices be treated. The recursive method will raise ValueError if the exponent is negative. The Jordan block method will return a formal expression for a non-numerical exponent, but later substitutions into the exponent may produce unexpected results. Should we raise ValueError whenever an eigenvalue `l` is zero? And maybe catch that and pass to the recursive method in case the exponent is a non-negative integer?

**Comment by Abdullahjavednesar** [comment]
Yes, @jksuom I think that's a good idea. I'll try to sort this.

**Comment by Abdullahjavednesar** [comment]
I'm opening a new PR

**Comment by Upabjojr** [comment]
> How should singular matrices be treated. The recursive method will raise ValueError if the exponent is negative.

This bug is already there in the SymPy master. I suggest merging this PR and open an issue for this other problem.

**Pull request merged**
