### PR TITLE
Fixed issue of simplify error in sinc

### LINKED ISSUE #13474: Cannot simplify x + csch(sinc(1))
>>> from sympy import *
    >>> x = Symbol('x')
    >>> print(simplify(x + csch(sinc(1))))
    ...
    File "C:\Users\E\Desktop\sympy-master\sympy\simplify\fu.py", line 433, in f
    rv = fmap[rv.func](S.Pi/2 - rv.args[0])
    KeyError: sinc

(I should have said: cannot apply the simplification function, since I'm not expecting any simplification to  actually take place).

### PR DESCRIPTION
**Pull request by Subhash-Saurabh**
Changed inheritance of sinc function.

#### References to other Issues or PRs
Fixes #13474 

For the code snippet
```
>>> from sympy import *
>>> x = Symbol('x')
>>> print(simplify(x + csch(sinc(1))))
```
Before --  `KeyError : sinc`
Now -- `x + csch(sinc(1))`

### CODE REVIEW

**Comment by ylemkimon** [comment]
I think `sinc` should not inherit `TrigonometricFunction`.

**Comment by Subhash-Saurabh** [comment]
@ylemkimon Inheriting `Function` instead of `TrigonometricFunction` for `sinc` perfectly solves this issue.
Should we keep the check for keys in fmap (as in my previous commit) as well ? I think that will prevent any future key error problems .
What do you suggest ?

**Comment by Subhash-Saurabh** [comment]
@ylemkimon  I have made the changes . Can you please review this PR.

**Comment by Subhash-Saurabh** [comment]
@smichr can you please take a look at this PR.

**Comment by Subhash-Saurabh** [comment]
@smichr this PR is only awaiting your review can you please take a look and suggest if any changes are required.

**Pull request merged**
