### PR TITLE
Removed repeated definition of some CustomConstraints in RUBI

### PR DESCRIPTION
**Pull request by ashishkg0022**
Before:
```
%time from sympy.integrals.rubi.rubi import rubi_integrate
CPU times: user 2min 12s, sys: 421 ms, total: 2min 13s
Wall time: 2min 15s
```
Now:
```
%time from sympy.integrals.rubi.rubi import rubi_integrate
CPU times: user 41.2 s, sys: 184 ms, total: 41.4 s
Wall time: 41.4 s
```
I have made a `constraints.py` which has definition of some CustomConstraints , which are used in many places in rules . So, instead of defining them every time, they can be imported from `constraints`.
More CustomConstraints (which are used many times) can be added in this.

### CODE REVIEW

**Comment by ashishkg0022** [comment]
ping @Upabjojr

**Comment by Upabjojr** [comment]
I'll check this later this week.

**Comment by Upabjojr** [comment]
If I forget, ping me again in Friday.

**Comment by ashishkg0022** [comment]
ping @Upabjojr

**Comment by Upabjojr** [comment]
How did you generate the differences? I believe the code generator needs to be updated to generate this new expressions, or am I missing something?

**Comment by ashishkg0022** [comment]
I just replaced all the occurences of those definition of CustomConstraints with the imported constraints. 
like I replaced `CustomConstraint(lambda a, x: FreeQ(a, x))` with `constraint_freeq_a` everywhere manually.

**Comment by ashishkg0022** [comment]
Do I need to update parsetools ? If yes then I have to regenerate whole rules . Is manual update of rules a problem ?

**Comment by Upabjojr** [comment]
I guess that those files are supposed to be automatically generated, that is not edited by hand.

For example, whenever there is a new version of RUBI we'd like to just update those files with a single command.

**Comment by ashishkg0022** [comment]
Ok I will try to update parsetools.
Is this replacement of CustomConstraints correct?
Also I have a doubt , assuming there is some error in rules .So to correct it do we need to change the parsetools ? Should we never edit the rules manually ?

**Comment by Upabjojr** [comment]
If there is an error in the rules, better email the author.

**Pull request closed without merging**
