### PR TITLE
Update FUNDING.yml to include new GitHub Sponsor button for NumFOCUS

### PR DESCRIPTION
**Pull request by Dr-G**
## Brief description of what is fixed or changed

- add NumFOCUS github sponsors button (recurring donations only)
- update custom link to point to the form located at numfocus.org, in case it provides more peace of mind for potential donors.

NO ENTRY

### CODE REVIEW

**Comment by Dr-G** [comment]
@asmeurer not sure if this change requires release notes...

**Comment by asmeurer** [comment]
It doesn't. I fixed the release notes.

**Comment by asmeurer** [comment]
Thanks Gina. I saw the announcement and was wondering how it worked with NumFOCUS. 

Do you know if it's possible to have an org-wide FUNDING.yml so that the sponsor button appears on all our repos?

**Comment by asmeurer** [comment]
Looks like you need a repo called `.github` https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file-for-your-organization. I'll move this file there.

**Comment by asmeurer** [comment]
I created the file but it doesn't seem to work. Maybe it takes a moment to update? https://github.com/sympy/.github/blob/master/FUNDING.yml

Anyway, once it works we can delete the file from this repo.

**Comment by asmeurer** [comment]
I also added CODE_OF_CONDUCT.md and it updated on other repos right away. So I think there is a bug on GitHub's side here. If the sponsor button doesn't show up on other repos by the time Travis passes we can merge this until they fix it.

**Comment by asmeurer** [comment]
@Dr-G do you see any issues with linking to https://www.sympy.org/en/donate.html instead of the numfocus page? It does require an additional button click, but that page provides more information about what the donations are used for. I noticed that NumPy does a similar thing on their sponsor button.

**Comment by Dr-G** [comment]
Yep, that link is fine. Thanks!

**Comment by asmeurer** [comment]
@Dr-G do you know what you did to make the sponsor button appear on github.com/numfocus? I can't get it to appear on github.com/sympy. I see numpy also has FUNDING.yml in .github and they have the same problem.

**Comment by Dr-G** [comment]
Hmmmmm.

The doc with all the instructions is here: https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository

Things I can think of: go to "Settings" and make sure the Sponsorships section is checked?
Might need to have it at the org level instead of within an individual repo, e.g. github.com/sympy/.github

**Comment by asmeurer** [comment]
I don't see the setting on the org level settings. I did enable it on the .github repo, and it isn't even showing up there. So I think there is a GitHub issue here. I will contact them to figure it out.

**Comment by asmeurer** [comment]
Actually, I suspect the problem is that because it's still in beta they have to actually enable it for our org. Do you know who we can contact at GitHub to get it enabled? I don't want to fill out the beta form.

**Comment by asmeurer** [comment]
In the meantime I'll just merge this.

**Comment by Dr-G** [comment]
This appears to be working.
Screen Shot 2019-11-14 at 11 59 08 AM

**Comment by asmeurer** [comment]
Yes, it works in this repo because I merged this pull request. But I'd like for the button to appear on https://github.com/sympy and also every other repo in the sympy org.

**Pull request merged**
