### PR TITLE
matrices: implementation of a refine() function for matrices

### PR DESCRIPTION
**Pull request by haruki-m**
As Issue #9923 suggested, I implemented a refine() function to matrices.py so that every element in a matrix would be refined under the assumption Q.

Example output:

```
>>> from sympy.abc import x
>>> from sympy.matrices import Matrix
>>> Matrix([[Abs(x)**2, sqrt(x**2)],[sqrt(x**2), Abs(x)**2]])
Matrix([
[ Abs(x)**2, sqrt(x**2)],
[sqrt(x**2),  Abs(x)**2]])
>>> _.refine(Q.real(x))
Matrix([
[  x**2, Abs(x)],
[Abs(x),   x**2]])
```

### CODE REVIEW

**Comment by moorepants** [comment]
Please add a unit test for this addition. You can probably use your example above for the test.

**Comment by harmor11** [comment]
I would be really grateful if the merge is accepted as soon as possible, as this is for the GSoC project.
Thank you!

**Comment by moorepants** [comment]
Looks good thank!

**Comment by WenyinWei** [comment]
Hi @moorepants , there still exists some trouble when using `sympy.refine`. If a matrix fed to the non-method function `sympy.refine`, the function would do nothing on it and just return it. 

```python
from sympy.abc import x
from sympy.matrices import Matrix
from sympy import Abs, sqrt, Q, refine
Matrix([[Abs(x)**2, sqrt(x**2)],[sqrt(x**2), Abs(x)**2]])
```

Let's see the difference.
```python
# _.refine(Q.real(x)) # it works well
refine(_, Q.real(x)) # it just returns what is fed.
```

```python
Matrix([
[ Abs(x)**2, sqrt(x**2)],
[sqrt(x**2),  Abs(x)**2]])
```

**Comment by WenyinWei** [comment]
One more thing, the `Matrix.simplify()` returns nothing while `Array.simplify()` returns the newly created and simplified `Array` (the original `Array` does not change). It is a misleading and subtle difference hidden in sympy.

**Pull request merged**
