### PR TITLE
Implement X21 Wester test

### PR DESCRIPTION
**Pull request by ghost**
This is first of two tests from `test_wester.py` module testing `fourier_series`. The second one (X22) is in preparation, but integral needed for test either does not evaluate, or evaluates to incorrect value - so far I'm making pull request with a single test.

### CODE REVIEW

**Comment by jksuom** [comment]
This looks good (though I personally think that the last formula would be more readable with fewer spaces to visually separate its principal components).

**Comment by jksuom** [comment]
There are some issues in the integration of `Abs`. I think that the implementation of X22 can wait until those have been resolved. As to the last expression, it would be easier to recognize its structure if the argument of sin were in one more closely spaced group, and maybe also the coefficient in front in another group. (Of course, this is a minor matter. There are no strict rules.)

**Comment by jksuom** [comment]
This should now be synchronized with the updated master to make the Sphinx doc test pass.

**Comment by flamyowl** [comment]
I've rebased branch with newest master; the tests are green now - can you merge it?

**Comment by jksuom** [comment]
Thanks! Merging.

**Comment by flamyowl** [comment]
Thanks for help!

**Pull request merged**
