### PR TITLE
Sets containment and simplification

### LINKED ISSUE #9543: ImageSet.is_subset(S.Reals) returns False
``` python
In [54]: x = Symbol('x', real=True)

In [55]: N = S.Naturals

In [56]: squares = ImageSet(Lambda(x, x**2), N) # {x**2 for x in N}

In [58]: squares.is_subset(S.Reals)
Out[58]: False
```

### LINKED ISSUE #16872: base_set of multivariate imageset is wrong
```python
>>> imageset(lambda x, y: (x, x + 2), S.Integers, S.Integers).base_set
S.Integers
```

The base set should be `S.Integers**2` (and imageset should allow entry of `S.Integers**2` for the base set since `ImageSet` does:
```python
>>> ImageSet(Lambda((x, y), x + y), S.Integers, S.Integers)
ImageSet(Lambda((x, y), x + y), Integers, Integers)
>>> ImageSet(Lambda((x, y), x + y), S.Integers**2)
ImageSet(Lambda((x, y), x + y), Integers x Integers)
```

### LINKED ISSUE #16873: imageset changes name of dummy variable (but need not do so)
Since we can inspect the lambda's arguments and get their names, it is not necessary to create a dummy argument for something like the following:
```python
>>> imageset(lambda y: x+y, S.Integers)
ImageSet(Lambda(_x, _x + x), Integers)
```

### LINKED ISSUE #16874: imageset evaluation problems with complex values
```python
>>> imageset(x, x + I*3, S.Integers).intersection(S.Reals) -> should be EmptySet
ImageSet(Lambda(_x, _x + Mod(3*I, 1)), Integers)

>>> q=imageset(x, x + I*y/x, S.Integers).intersection(S.Reals)
>>> q.subs(y,0) -> should be Integers
EmptySet()

>>> q.subs(y, I*i*x).intersection(S.Integers) is S.Integers  -> should evaluate
Traceback (most recent call last):
  File "\sympy\solvers\diophantine.py", line 191, in diophantine
    assert not any(g.is_number for g in p.gens)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\sets\sets.py", line 116, in intersection
    return self.intersect(other)
  File "\sets\sets.py", line 110, in intersect
    return Intersection(self, other)
  File "\sets\sets.py", line 1213, in __new__
    return simplify_intersection(args)
  File "\sets\sets.py", line 1966, in simplify_intersection
    new_set = intersection_sets(s, t)
  File "\multipledispatch\dispatcher.py", line 198, in __call__
    return func(*args, **kwargs)
  File "\sets\handlers\intersection.py", line 246, in intersection_sets
    solns_set = diophantine(f - g)
  File "\solvers\diophantine.py", line 196, in diophantine
    Equation should be a polynomial with Rational coefficients.'''))
TypeError:
Equation should be a polynomial with Rational coefficients.
```

### PR DESCRIPTION
**Pull request by smichr**
#### References to other Issues or PRs

cf #10777

#### Brief description of what is fixed or changed

1. Some trivial subset relationships were corrected.
```python
>>> S.Naturals.is_subset(S.Integers)
False --> now True
```
2. imageset will simplify to Range in more cases
```python
>>> imageset(n, 1 + 2*n, S.Naturals)  --> formerly unchanged
Range(3, oo, 2)
```
3. imageset over integers will not simplify its expression if it introduces Mod. This allows the following to work
```python
>>> 4 + y in imageset(x, 2*x + y, S.Integers)  --> now True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\sets\sets.py", line 555, in __contains__
    raise TypeError('contains did not evaluate to a bool: %r' % symb)
TypeError: contains did not evaluate to a bool: Contains(0.5*y - 0.5*Mod(y, 2) + 2.0, Integers)
```
4. Mod(a, b).rewrite(floor) is now defined to give `a - b*floor(a/b)`

#### Other comments

closes #16872 
closes #16873 
closes #16874 
fixed #9543

#### Release Notes

- sets
    - containment checks improved, especially for interactions between Integer-types
    - `imageset` simplifies to Range when possible
    - `imageset` over integers does not introduce symbolic `Mod`
- core
    - Mod(a, b).rewrite(floor) is now defined to give `a - b*floor(a/b)`

### CODE REVIEW

**Comment by smichr** [comment]
- [ ] this should work
```python
>>> q5=ImageSet(Lambda((x, y), x/y), S.Integers*Range(1,6))
>>> i = Dummy(integer=True)
>>> i in q5
False
>>> 0 in q5
False
```
This works as it should, however:
```python
>>> i/2 in q5
True
```

**Comment by oscargus** [comment]
Should be `a - b*floor(a/b)` in the release notes, right?

Looks good! The coverage can be increased by some trivial additions, but really just for the purpose of increasing coverage.

**Comment by oscarbenjamin** [comment]
Looks like this also fixes #9543:
```julia
In [1]: ImageSet(Lambda(x, x**2), S.Naturals).is_subset(S.Reals)
Out[1]: True
```

**Comment by smichr** [comment]
See if #16268 is affected

**Comment by oscarbenjamin** [comment]
No #16268 is not fixed by this PR

**Comment by oscarbenjamin** [comment]
```
In [1]: Naturals.is_subset(Reals)                                                                        
Out[1]: False
```

**Comment by smichr** [comment]
> No #16268 is not fixed by this PR

I was just thinking that we could have

Naturals in Naturals0 in Integers in Floats in Rationals in Reals

We don't define Floats but they are `imageset((x, y), x/2**y, S.Integers**2)`

**Comment by smichr** [comment]
see also #16268, #9609

**Comment by jmig5776** [comment]
@smichr The output of 
```
>>> Intersection(S.Integers, ImageSet(Lambda(n, 5*n + 3), S.Integers))
S.Integers
# ImageSet(Lambda(n, 5*n + 3), S.Integers) expected.
```
Is effected here.

**Pull request merged**
