### PR TITLE
Fix Sphinx build failure in master

### PR DESCRIPTION
**Pull request by Upabjojr**

### CODE REVIEW

**Comment by smichr** [comment]
OK, it looks like that one passed. Now we have

```
Warning, treated as error:
/home/travis/build/sympy/sympy/sympy/codegen/cfunctions.py:docstring of sympy.codegen.cfunctions.exp2.eval:15:Unexpected indentation.
make: *** [html] Error 2
```

Maybe there is a setting to ignore warnings? Or else maybe this one can be fixed like the last one.

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/pull/14182

**Comment by jksuom** [comment]
It looks like Sphinx is badly confused. `exp2.eval` does not even have a docstring.

**Comment by asmeurer** [comment]
In the future please make pull requests from forks.

**Comment by asmeurer** [comment]
I have figured out the problem. It doesn't like things like

```
.. automodule:: sympy.codegen.cfunctions
    :members:
```

You apparently have to use a 3-space indent, and add a newline before `:members:`. 

```
.. automodule:: sympy.codegen.cfunctions

   :members:
```

This requires a lot of changes. I am working on a fix now.

**Comment by asmeurer** [comment]
Opened an issue upstream https://github.com/sphinx-doc/sphinx/issues/4606.

**Comment by asmeurer** [comment]
We have warnings set to be raised as errors on purpose. This is because in many instances Sphinx will simply warn about something, but the resulting documentation will not be correct. It will render in a bad way, or in some cases, it will just not appear at all. This was an issue in the past, where some docs that were supposed to be in Sphinx did not appear at all, because of some issue that was only a "warning".  Also, having many ignored warnings from Sphinx pollutes the build log and makes it difficult to see any new issues that may have arised from new documentation.

**Pull request merged**
