### PR TITLE
zeta_functions.py:Removed the comment

### LINKED ISSUE #14069: Condition for TODO in zeta_functions.py is now satisfied
On line 162 it says:
> TODO use minpoly instead of ad-hoc methods when issue 5888 is fixed

Issue 5888 has now been fixed

### PR DESCRIPTION
**Pull request by abaokar-07**
Fixes #14069

### CODE REVIEW

**Comment by abaokar-07** [comment]
@gxyd Removed the comment

**Comment by gxyd** [comment]
Please use Fixes #14069  in the PR description, rather than something ad hoc so that GitHub knows to close the issue automatically when this is merged. I think following the default PR template is the best thing.

**Comment by abaokar-07** [comment]
Okay @gxyd I'll do it

**Comment by abaokar-07** [comment]
@gxyd Updated the description

**Review by gxyd — DISMISSED** [review]
LGTM.

**Comment by abaokar-07** [comment]
@gxyd Is it okay to be merged?

**Comment by Roland-Sands** [comment]
I think this is wrong
@gxyd, please get a 2nd opinion from a SymPy person whose pure mathematics is as good as possible

**Comment by skirpichev** [comment]
@gxyd, are you sure this pr actually uses minpoly where it's expected?!

**Comment by jksuom** [comment]
I think that we can now strike the tail part 'when issue 5888 is fixed', but the application of `minpoly` remains to be implemented and therefore not everything should be removed.

**Comment by skirpichev** [comment]
The "tail part" could be helpful for real developers.  Any reasons to touch this, before todo will be actually implemented?

**Comment by gxyd** [comment]
@abaokar-07 I'm sorry for your wasted efforts. I think I misunderstood the original issue that needed to be addressed.


@skirpichev 
> @gxyd, are you sure this pr actually uses minpoly where it's expected?!

I'm wrong on that. I really appreciate you guys taking over this. I'll try to be careful in the future.

I'm not really sure, what the protocol here should be for this PR. Opinions?

**Pull request closed without merging**
