### PR TITLE
Abs of base raised to exponent for complex non-symbol bases

### LINKED ISSUE #14260: abs(I**n)
```
>>> n  = symbols('n', positive = True, integer = True)
>>> abs(I**n)
   __________
  ╱  n     n 
╲╱  ⅈ ⋅(-ⅈ)  
>>> abs(abs(I**n))
│   __________│
│  ╱  n     n │
│╲╱  ⅈ ⋅(-ⅈ)  │
>>> abs(abs(abs(I**n)))
│   __________│
│  ╱  n     n │
│╲╱  ⅈ ⋅(-ⅈ)  │
```

### LINKED ISSUE #14262: log(I**I)
```
>> pprint(simplify(log(I**I)))
   ⎛ ⅈ⎞
log⎝ⅈ ⎠

>> pprint(simplify(log(I**I)).expand(complex=True))
               ⎛ ⅈ⎞      ⎛│ ⅈ│⎞      
- ⅈ⋅π⋅Heaviside⎝ⅈ ⎠ + log⎝│ⅈ │⎠ + ⅈ⋅π
```
#### Expected Result
```
 -π 
 ───
  2  
```
#### Related Issues
#7569 - simplify should call expand_complex
#13288 - Improve simplification

### LINKED ISSUE #14274: Abs((4 + 5*I)**(6 + 7*I))
```
>> z=(4 + 5*I)**(6 + 7*I)
>> pprint(simplify(Abs(z)))
         ______________________________________________________
        ╱          7⋅ⅈ ⎛  ⎛         7⋅ⅈ⎞       ⎛         7⋅ⅈ⎞⎞ 
68921⋅╲╱  (4 + 5⋅ⅈ)   ⋅⎝re⎝(4 + 5⋅ⅈ)   ⎠ - ⅈ⋅im⎝(4 + 5⋅ⅈ)   ⎠⎠ 
```

The evaluation of this without simplify gives an even complicated expression.

### PR DESCRIPTION
**Pull request by sidhantnagpal**
#### References to other Issues or PRs
Fixes #14274 
Fixes #14260
Helps with #14262

#### Brief description of what is fixed or changed
```
>> pprint((4+5*I)**(6+7*I))
       -7⋅atan(5/4)
68921⋅ℯ            

>> pprint(log(Abs(I**I)))
-π 
───
 2 
```
#### Other comments
As brought to my notice by @roland-sands, PR #14263 by @normalhuman fixes this for only real powers.

### CODE REVIEW

**Comment by Roland-Sands** [comment]
> Partially Fixed #14262

This will close #14262 upon this pull being merged

**Comment by sidhantnagpal** [comment]
> This will close #14262 upon this pull being merged
Okay so should I remove it? (Because it has the label simplify)

**Comment by Roland-Sands** [comment]
> Okay so should I remove it?

I think it is good to mention it
I think the way to go is to avoid the keywords fix, fixed, closes, ...
Perhaps "Partially resolves #14262" would work

**Comment by sidhantnagpal** [comment]
> I think the way to go is to avoid the keywords fix, fixed, closes, ...
Perhaps "Partially resolves #14262" would work

Thanks for the tip.
Tried it, but it would still close the issue, changed it to `Partial`.

**Comment by Roland-Sands** [comment]
> Tried it, but it would still close the issue

"Helps a bit with #14262" ?

**Comment by sidhantnagpal** [comment]
@normalhuman, @jksuom, @smichr 
Please review.

**Comment by normalhuman** [comment]
To have two issues closed automatically, "fixes" should be repeated, otherwise only the first one gets closed.
 
> Fixes #14274, fixes #14260

This example makes me wonder how much automatic evaluation is too much. 
```
z = S(-3307)/9559 + 9526*I/2225
w = S(-11619)/2395 + 9167*I/9320
Abs(z**w)
```
returns 
```
11254665638149425304312521484375*1253917919951507188764641247332094139458700988153614136795124036081073079677802574107138826966085816009876473471953085153623232254143620266772177677569196054346845075888741183092610640537079098319432190243682201780932997506433178815114871416961353866202974160085815222327223066909422875433316223417681617547186758496446653075416327382878694794493248377410314327755155508802976250562075841721698491803232057148065026610884351987487205343155970818119901889462154853734847139410076390125568020034219693235402683755860624765491331127858522080438622682925703038060753926330396172202917358708458017373566639198208964014192262399402194876174771905217469753113884212014734469010336242017546509786673453297337079902936444136008282878856819231418236997575787704139683221770934573291800485875425871516786931861595387842213944846958947058152409323194213028464005481566272673958653064826490136864661074747642170867442423280493846127703502607816614661811573253736595432433012603791007653201509137073965574667498301848462785977561216983018029384884619755730641338400181688141947295688943234108665986861126488487258119533853830207060783297888174369556009027092000192604391058403492696459633918829047730933628421994404459342773780959475407518164421331166847462201972075168208576236849678266525243161176609129761132199974557143382417799478389448475477570560875945613277250305938729324655829034712385954753061612187234219390315818741312139487490517463542768052048324495189356073741936302388289809483053769595597914480142622952615237421465743124993604517165263496730899471041975154519437186016752346413473330613799779322243213419341866564325914701192420453229130232679773363297573743844306517426420278502318086839519718193019551160369676812091739418132669506192304907101008112867521209620216645807756985033298250232470265327338296113573167829089563315303168884342781632296231651697208841924182232065816355982365471415011776783808954459635232442588731765150645885407494042660242267585333777146212455627154231428328115179586196514115530252151834910651003942534976767551575189320703554074393959494371119958548779792947298930168119788945111637381899292651435510101769886353702839849341832853947572793668791722235337967214923927301656059442160307111589152515261502045331460479481085923977422637285254568353685102042842308037348111276672932787115694119140265841168776812665475285921699087738869708665103732058515267678156457541950970109435274293180915386788661979540813520697496969156928295011302500239078702735803333667983826380103095790421149886603834473357160387336169840142998464326064365746199249439987762492667588393512223935254361267046729576449734980216698666213901199366135211166990852835047982378558221318226677576922306669207389616604062074521249178924091764986340784261263153970438141735518824704698956209562441367874783463603304151807592432967588092887711552071693808659823501229843390124220090062671894657583838033281623736858536435804180687817525873570752084650548555363503830525011567134800877387149489728328470737368010057667071794147366630229985995531068472590612513823615710095016685018373231435152637420896992951944808900655696273813320645176513339001233734533768552993622412763339214857850176340903417517418131636967751612007487757741854062185639459452675163522229757852869222293186437491497008504383476108376875823288951550895490150737943306368533146383745907455207883380962637808655484883578892851229393770011903115265687101180253000236782429478248902343073482641209898465548316584335582887919585726151213057796797666820793804659053926870440426920898292719580593082099922625173269070641789962610984042381535500047643487913923063756648890055871131514149412187209039455259634482522720907923959547811221932796063520104434276790142786830724688954489985492916170315909076811370415753503010722079978217539126481246008685423871973063067941035537769114415455483808705936498035311399453673885460919832614895674560954580519104461690014318647118006386404871264379689567825932247200590462805968081923879948042572679358642272679449146933283576571776164498834125387431175330680750758885961947465090760823531236104274817545987008251897023850741636341290738562173795259598965390060510327587257923593275326481968749343524996014277007050155206802231245115131342888204133976709150980306870098525506557622842326451420570430498133687709830952720823176705096361980480299463095291118986233674586731055455497911660566412555968431908056331115753530774721810765891509766607872890485758817216045126522287449026966204173964524772693164181243601467079824242017329543003083007477900668294151642156945124484908807511392493227190665246450052889292131612758642922520243846900818987669245236896526368395661191061110058879982158532199540294744104066483361597468449240663498030118653586201751810494622821979700343260637729469477011901442582270490185297405078736761846759021870145298036684149843646564280443442934766990891703587875371213507384731500416703870740879585886994271412546630936989631992366207551038076930066041043988740345707230947730488166060556675529321526832264383267976736067035765130111539409478395629633152782663080781488103360675809834324957794485349140859797365471560828665995522925052581149156027255382796111793352962071255194815574371229287084207072782793154150288230232023904099629587530310407428282367717176936303475026357509426521515568530669389991727786209529056081456406257754458106772211029135582996854528748156784313755433425509941454642161201613069606260466080520884761827310403686203269133809699735293902543015527405325181546595169907324025526293740523048986795043722266157276529834538270971300106474674217504426801887031244110730370454421686288966421344055535063483032246856790790735732101736760920742652630544479542589396739435853222504945828527268925503961541912504900002077892894428712443702547097660071917865888107667510595200557519598163372765562955588054717907012151974828467474440886641503591522623675133217713652510764510561650799385424302518548486791238793622971680068824961587352372570096914585641252637324639900335088428166956589309849347871460037420853055006522600222131815140524757774405962139727875777862530924293426680797466099436532306620026599757864055319534578631035752028032097714529417912996203179898655961805051259614376411565174789397888750771532926526436394705694657543444042788899855909427482003743348304290520722482865047886535535202215165166686836474954887543429996860923165222470397303702706366986102057621770614768886332085390364522289299369428523258518030875069974043321023891845797213292313774947161686500534364751337018554193100281891969188743716690756749315380125438160755181500121901840735763680566692026997173093190072548499729837336617008451948378834705519029598804347654847127698622758172681238805236084787536019544828827809676512557894041431131731199479304051050932523288763468598475509239336613148095417104724729153903102984221025955345529430903519029707327613186584991619643185429114206550678624325559510943095426621231943657931075432671908365119834214625235125572973513129324246573381215870052902000634334319145321690231392539764603476090989961472228346246949418812681982304974726977855160611063666157096913924007102445380512442826436050573174795204855172934760078686566938958436812522661742468594908466660584857216151396379431249953447660518129254318188155150185150640824864805341619095177919621294377813704872653191215636077073560590081732505435212366399481838270184646697150868917254255273529735562298246279360133400091499880418398912084306697420277716836246284273377480115178971362250259596729490779855278036387733160121320000610483842513797463469117272014878884492267142253132500470960088356170031730631960358395970143193627976331840651645698215870966073166386928303986426082595272733707924745025787102288397575962268021417133528395504613234853375836556588252284765537679723746694958710539066829318680166026758335323284071642971925146508114893064459288774868242738115252582066123849289208510059286064682835011412388390423791246446475405297196653677211437999825984619935785750963707050782034437109527349188519264239158468540445318957538276941269324669230373376543357095094923573807095753923812844392781713919681778186807903168296913192449444374214533178295020081140458499984916217072547933529831113983327298303598192862073168640665559052925306792369531383852422119626611178008464737676823571243993854683226203762150028538681134065641438317749109459345117501976061209857159898376628449947154575928201025585856138756151258527662150502850929443375337023237830719265499065427946140948345592635972768641150139057044444395780810556113101394258034207411217313443564213915547278366579284521201552909361688818179648107752218090822073808399032691462683641339582778374134578366969943279812380088779995461888242169472222872297115577124064220082157930310154868045702594175109734689606984542526932872750795049997031892672286916124715291508155008691393979622166995796138775528284305342541906445566673531878308852241638652949936589148656869520725071417288725157079182457947921461261404049917916703607927624568128202035458372450775385901196843666790810041856986276400261989662779255579670498171364039814417428415120103100990932717191384373983669907539767721947950233908964618876021620000765978764987085712732581412304051952341294605216791596038572820795851689813787958274214734675472354075524345492734513301172830169136987763270912013471014434590129434354601008854637863800997210347951954156184923495277908601882347747125501509539280947877528548286048785785533031521304205810914900584380813468104578788350187380239556969603860947287887648117180162063633328610157374880136835655195130508403531012141619897613696866877882444646715844633227845330933298764140108135093747764814897139528497209033570330982297231910533066984865331931813224110882939989784357492165987889259662321286747819317628880586801468544731185304180639076287492991092979560833014927336820967316124627158792321491844315243669846076928989804543267247727110131895045968235105110229733709026934803442074332977588089596490018397009615887126987013324219628474678970137673485576706852049695162463218346011819492066578983871597214841232583652382250102862866872039761357994025681929037153578898277576643494971671098574997213958646278502506026072362373149435422096059626095540005987751882056128260832085846288024843408986610149930667629208114327083404266251068925687048606237105463259380557772589854863159480150204608719895594950004394261412473979713087671514307453172872771137472680598467536444984699467512311404338221182584602148374009732346452185879669363840298230931945067286648199771692060630303208025135787438121381871910559643041923049858028763768468936614372309124672650410496213593905300833145258132330212486524974086519256074622655623618848887051492081712300574736218550242483615875244140625**(1/2395)*8345888940718781**(2751/4790)*exp(-9167*pi/9320 + 9167*atan(91059034/7358075)/9320)/581323398303566162635134472560621425733084373541
```
That's 10950 characters. Likely not the worst example, I just tried random numbers with 
```
z = random_complex_number(-5, -5, 5, 5, rational=True, tolerance=0.0001)
w = random_complex_number(-5, -5, 5, 5, rational=True, tolerance=0.0001)
```
Granted, the current behavior is to return a 695-character expression which is also opaque in addition to being long.
```
sqrt((-3307/9559 + 9526*I/2225)**(-11619/2395 + 9167*I/9320)*re((-7358075 + 91059034*I)**(9167*I/9320)/(66062456366715268994652444505961*21268775**(9167*I/9320)*(-3307/9559 + 9526*I/2225)**(2039/2395)/204630284329989550987500390625 + 94365471820467345378888*21268775**(9167*I/9320)*I*(-3307/9559 + 9526*I/2225)**(2039/2395)/874650896485958453125)) - I*(-3307/9559 + 9526*I/2225)**(-11619/2395 + 9167*I/9320)*im((-7358075 + 91059034*I)**(9167*I/9320)/(66062456366715268994652444505961*21268775**(9167*I/9320)*(-3307/9559 + 9526*I/2225)**(2039/2395)/204630284329989550987500390625 + 94365471820467345378888*21268775**(9167*I/9320)*I*(-3307/9559 + 9526*I/2225)**(2039/2395)/874650896485958453125)))
```

**Comment by sidhantnagpal** [comment]
> To have two issues closed automatically, "fixes" should be repeated, otherwise only the first one gets closed.

Thank you for the tip, will keep in mind.

> This example makes me wonder how much automatic evaluation is too much.

Yes, indeed a good observation, even for small range complex numbers the output can be too big.
So, maybe just express the result in the following format, could help resolve this issue?
`exp(a log(b) + c atan(d))`

**Comment by sidhantnagpal** [comment]
@normalhuman 
```
z = S(-3307)/9559 + 9526*I/2225
w = S(-11619)/2395 + 9167*I/9320
Abs(z**w)
```
now returns
```
exp_polar(-11619*log(sqrt(8345888940718781)/21268775)/2395 - 9167*pi/9320 + 9167*atan(91059034/7358075)/9320)
```
which is
```
            ⎛√8345888940718781⎞                     ⎛91059034⎞
   11619⋅log⎜─────────────────⎟            9167⋅atan⎜────────⎟
            ⎝     21268775    ⎠   9167⋅π            ⎝7358075 ⎠
 - ──────────────────────────── - ────── + ───────────────────
               2395                9320            9320       
ℯ                                                             
```

**Comment by sidhantnagpal** [comment]
> output is problematic because it won't act as exp in larger context; for example Abs(I**I)*exp(pi/2) will not simplify to 1.

Yes, that is correct.

> prevent exp(a log(b)) from simplifying to b**a

So, is there no way of doing this then?

> identify the situations where `Abs(z**w)` can be evaluated without creating a monstrous formula

Isnt expressing using exponential notation always beneficial (in terms of length of the formula as well as simplicity).

**Comment by normalhuman** [comment]
One can pass evaluate=False to exp, like `exp(999*log(999), evaluate=False)`, which returns `exp(999*log(999))`. But this won't make a difference when `Abs(z**w)` is a part of a larger formula, because the larger formula will want to evaluate its parts. For example, `exp(999*log(999), evaluate=False)*2` results in a huge integer. 

I think your original approach was probably best. The output is giant because this is how `exp(a*log(b))` works with integers a, b; this is not a fault of your PR. My [original comment](https://github.com/sympy/sympy/pull/14278#issuecomment-366859368) was more of thinking aloud than a demand for change. 

Let's see if anyone has other ideas for dealing with this computation.

**Comment by sidhantnagpal** [comment]
@normalhuman 
> I think your original approach was probably best. The output is giant because this is how exp(a*log(b)) works with integers a, b; this is not a fault of your PR. My original comment was more of thinking aloud than a demand for change.

Just a quick query to ask, is it possible to revert to the original PR or do I have to recommit to that?

> Let's see if anyone has other ideas for dealing with this computation.

Yes, I will also think about it.

**Comment by normalhuman** [comment]
I think git reset HEAD~2 (if reverting two commits) should do it, followed by git push -f

**Comment by sidhantnagpal** [comment]
@normalhuman 
> `exp(999*log(999),evaluate=False)*2` results in a huge integer.
The output is giant because this is how exp(a*log(b)) works with integers a, b; this is not a fault of your PR.

Actually you're right about this. This should be a separate issue (about exp) then I suppose, since even if we handle the expansion in this PR (about Abs) the former issue will persist.

So, I would request you tell your thoughts on this, so that we can revert/change this PR accordingly.

**Review by normalhuman — APPROVED** [review]

**Comment by normalhuman** [comment]
After some thought, I no longer consider the length of those expressions a problem. It's not surprising that when Pow is involved, long result may be returned from short inputs, like `999**9999`. SymPy evaluates such powers automatically, just as plain Python does, and I don't think anyone really objects to it.

**Comment by sidhantnagpal** [comment]
@normalhuman Yes, I agree with you, but I thought maybe symbolic expressions could help reduce the length of the output in such cases.

**Pull request merged**
