### PR TITLE
Issue 12564. limit(x**2 + x*sin(x) + cos(x), x, -oo)

### PR DESCRIPTION
**Pull request by maurogaravello**
This PR fix issue #12564.

In some situation, for example if `expr = x**2 + x*sin(x)`, `limit(expr, x, oo)` fails since `heuristics()` in `limits.py` calculates the limit of `x**2` and `x*sin(x)` separately. The second one returns all the real line as limit points. If such happens, then the procedure stops.
Instead, if `expr = x * (x + sin(x))`, then sympy gives the correct answer.
Therefore some lines to `limits.py` are added in order to check whether `factor(expr)` can help in solving the limit.

### CODE REVIEW

**Comment by smichr** [comment]
`factor` is expensive -- would `factor_terms` be better/sufficient?

**Comment by smichr** [comment]
Also, you might make the factoring conditional on the expression being an Add:

```
if l.has(S.Infinity) and l.is_finite is None:
    if e.is_Add:
        m = factor_terms(e)
        if m.is_Mul:
            return heuristics(m, z, z0, dir)
        return
```

**Comment by maurogaravello** [comment]
Using `factor_terms` instead of factor works for `limit(x**2 + x*sin(x), x, oo)`, but fails for `limit(x**2 + x*sin(x) + cos(x), x, oo)`. 

Following your suggestion, what you think about this piece of code?

```
            if l.has(S.Infinity) and l.is_finite is None:
                if isinstance(e, Add):
                    m = factor(e)
                    if isinstance(m, Mul):
                        return heuristics(m, z, z0, dir)
                    return

```

**Comment by smichr** [comment]
> fails for limit(x**2 + x*sin(x) + cos(x), x, oo)

This expression doesn't factor...what expression is encountered during the limit process that *does* factor?

Also, doing a conditional factor is good. You might do a full factor only after a `factor_terms` attempt fails to produce a `Mul` of the right variety (e.g. I don't know if factoring is only successful if at least two factors have the symbol of interest so `x*(x + 1)` is ok but `2*(x + 1)` is a hollow result for the process).

**Comment by maurogaravello** [comment]
> fails for `limit(x**2 + x*sin(x) + cos(x), x, oo)`
> This expression doesn't factor...what expression is encountered during the limit process that does factor?

Sympy does the substitution `x -> 1/x`. So at some point, we have the expression `cos(1/x) + sin(1/x)/x + x**(-2)`, which remains the same with `factor_terms`, while becomes `(x**2*cos(1/x) + x*sin(1/x) + 1)/x**2` with `factor`.

Now I try to add an additional conditional when `factor_terms` fails.

**Comment by gxyd** [comment]
@maurogaravello can you please squash the commits appropriately and with good commit messages? For ex. the first two commits have commit message "1" which doesn't look good. Also I wouldn't mind you using `git rebase` at all.

**Comment by maurogaravello** [comment]
@gxyd I tried to squash the commits, but I was not able to do it. Probably because I merged from master.
In the next days I will try again. However, in commits '1' I added a file with some tests for debugging purposes. At the end I deleted such file.

**Comment by maurogaravello** [comment]
@gxyd I opened a duplicate of this PR, since I was not able to squash the commits. The duplicate PR is    #13455

**Comment by smichr** [comment]
Since the factor is the only thing left to do and might be necessary for some function, I guess it doesn't hurt to leave it there. So let's merge as is.

**Pull request closed without merging**
