### PR TITLE
Fixes dsolve for system of equations

### PR DESCRIPTION
**Pull request by vishalg2235**
Fixes dsolve for solving system of equations.
As per commits [here](https://github.com/diofant/diofant/pull/286).

3 errors which were coming:
1) https://github.com/sympy/sympy/compare/master...vishalg2235:dsolve-system?expand=1#diff-472b116dfa6e4e86ea88b212aaffc929R51 here I have replaced `sol3` with the results which dsolve is giving but still it is creating assertion error.
2) [here](https://github.com/sympy/sympy/blob/master/sympy/solvers/tests/test_ode.py#L228) dsolve is giving a non-piecewise result.
3) same as 1st error [here](https://github.com/sympy/sympy/blob/master/sympy/solvers/tests/test_ode.py#L401) also I have changed `sol2` with the result of dsolve but assertion error is coming.

@cbm755  @asmeurer @skirpichev Please review!

### CODE REVIEW

**Comment by normalhuman** [comment]
There is a merge conflict.

**Comment by vishalg2235** [comment]
@jksuom @normalhuman Please review!

**Comment by normalhuman** [comment]
Does this resolve #14312?

**Comment by vishalg2235** [comment]
Yes! 
```
>>> k2, k3, t = symbols('k2 k3 t')
>>> x, y, z = symbols('x y z', cls=Function)
>>> eq1 = (Eq(Derivative(x(t),t), k3*y(t)), Eq(Derivative(y(t),t), -(k3+k2)*y(t)), Eq(Derivative(z(t),t), k2*y(t)))
>>> sol1 = dsolve(eq1)
>>> print([eqn.subs({e.lhs: e.rhs for e in sol1}).doit().simplify() for eqn in eq1])
[True, True, True]
>>> eq2 = (Eq(Derivative(z(t),t), k2*y(t)), Eq(Derivative(x(t),t), k3*y(t)), Eq(Derivative(y(t),t), -(k3+k2)*y(t)))
>>> sol2 = dsolve(eq2)
>>> print([eqn.subs({e.lhs: e.rhs for e in sol2}).doit().simplify() for eqn in eq2])
[True, True, True]
>>> sol1
[Eq(x(t), C1 + C2*(k3/(k2 + k3) - k3*exp(-t*(k2 + k3))/(k2 + k3))), Eq(y(t), C2*exp(-t*(k2 + k3))), Eq(z(t), C2*(k2/(k2 + k3) - k2*exp(-t*(k2 + k3))/(k2 + k3)) + C3)]
>>> sol2
[Eq(z(t), C1 + C3*(k2/(k2 + k3) - k2*exp(-t*(k2 + k3))/(k2 + k3))), Eq(x(t), C2 + C3*(k3/(k2 + k3) - k3*exp(-t*(k2 + k3))/(k2 + k3))), Eq(y(t), C3*exp(-t*(k2 + k3)))]

```

**Comment by vishalg2235** [comment]
Yes! As number of equation is 3. 
```
>>> k2, k3, t = symbols('k2 k3 t')
>>> x, y, z = symbols('x y z', cls=Function)
>>> eq1 = (Eq(Derivative(x(t),t), k3*y(t)), Eq(Derivative(y(t),t), -(k3+k2)*y(t)), Eq(Derivative(z(t),t), k2*y(t)))
>>> sol1 = dsolve(eq1)
>>> print([eqn.subs({e.lhs: e.rhs for e in sol1}).doit().simplify() for eqn in eq1])
[True, True, True]
>>> eq2 = (Eq(Derivative(z(t),t), k2*y(t)), Eq(Derivative(x(t),t), k3*y(t)), Eq(Derivative(y(t),t), -(k3+k2)*y(t)))
>>> sol2 = dsolve(eq2)
>>> print([eqn.subs({e.lhs: e.rhs for e in sol2}).doit().simplify() for eqn in eq2])
[True, True, True]
>>> sol1
[Eq(x(t), C1 + C2*(k3/(k2 + k3) - k3*exp(-t*(k2 + k3))/(k2 + k3))), Eq(y(t), C2*exp(-t*(k2 + k3))), Eq(z(t), C2*(k2/(k2 + k3) - k2*exp(-t*(k2 + k3))/(k2 + k3)) + C3)]
>>> sol2
[Eq(z(t), C1 + C3*(k2/(k2 + k3) - k2*exp(-t*(k2 + k3))/(k2 + k3))), Eq(x(t), C2 + C3*(k3/(k2 + k3) - k3*exp(-t*(k2 + k3))/(k2 + k3))), Eq(y(t), C3*exp(-t*(k2 + k3)))]
```

**Comment by normalhuman** [comment]
`_linear_neq_order1_type1` is the method replaced by this PR; it was previously an incorrect generalization from the n=2 case, and now is an application of matrix exponential. 

So there should be a test case for  #14312, so that that issue can get closed.

**Comment by vishalg2235** [comment]
@normalhuman can you please look at the errors coming? I also mentioned them in 1st comment. Thank You

**Comment by normalhuman** [comment]
It's the usual issue with 1/2, 1/4, 1/7 and so on. Type S(1)/2, S(1)/4, S(1)/7... instead.

> A common mistake is copying an expression that is printed and reusing it. If the expression has a Rational (i.e., <number>/<number>) in it, you will not get the same result, obtaining the Python result for the division rather than a SymPy Rational.  http://docs.sympy.org/latest/gotchas.html#python-numbers-vs-sympy-numbers

This is only needed when you have one integer divided by another. `I/2` is fine, and `sqrt(7)/4` is fine: in both cases, we already have a SymPy expression in the numerator, and then division happens by SymPy rules.

For example, line 51 of test_ode should be

```
    sol3 = [Eq(x(t), C1*(-2*sqrt(7)*I*(S(1)/4 + sqrt(7)*I/4)*exp(t*(3 - sqrt(7)*I)/2)/7 + 2*sqrt(7)*I*(S(1)/4 - sqrt(7)*I/4)*exp(t*(3 + sqrt(7)*I)/2)/7) + C2*((S(1)/4 + sqrt(7)*I/4)*(S(1)/2 + sqrt(7)*I/14)*exp(t*(3 - sqrt(7)*I)/2) + (S(1)/4 - sqrt(7)*I/4)*(S(1)/2 - sqrt(7)*I/14)*exp(t*(3 + sqrt(7)*I)/2))), Eq(y(t), C1*(-2*sqrt(7)*I*exp(t*(3 - sqrt(7)*I)/2)/7 + 2*sqrt(7)*I*exp(t*(3 + sqrt(7)*I)/2)/7) + C2*((S(1)/2 + sqrt(7)*I/14)*exp(t*(3 - sqrt(7)*I)/2) + (S(1)/2 - sqrt(7)*I/14)*exp(t*(3 + sqrt(7)*I)/2)))]
```

**Comment by vishalg2235** [comment]
Thanks :)

**Comment by vishalg2235** [comment]
@normalhuman an error is coming in line 210 of test_ode because dsolve is not giving a piecewise result.
And don't know what is wrong with following `sol2`. It is still giving error for 3rd error in line 380 of test_ode?
```
sol2 = [Eq(x(t), C1*((-S(21)/170 + 11*sqrt(179)*I/170)*(-S(21)/358 - 11*sqrt(179)*I/358)*exp(sqrt(179)*I*t) + S(49)/179 + (-S(21)/170 - 11*sqrt(179)*I/170)*(-S(21)/358 + 11*sqrt(179)*I/358)*exp(-sqrt(179)*I*t)) + C2*((-S(21)/170 + 11*sqrt(179)*I/170)*(-S(33)/358 + 7*sqrt(179)*I/358)*exp(sqrt(179)*I*t) + S(77)/179 + (-S(21)/170 - 11*sqrt(179)*I/170)*(-S(33)/358 - 7*sqrt(179)*I/358)*exp(-sqrt(179)*I*t)) + C3*(85*(-S(21)/170 + 11*sqrt(179)*I/170)*exp(sqrt(179)*I*t)/179 + S(21)/179 + 85*(-S(21)/170 - 11*sqrt(179)*I/170)*exp(-sqrt(179)*I*t)/179)), Eq(y(t), C1*((-S(33)/170 - 7*sqrt(179)*I/170)*(-S(21)/358 - 11*sqrt(179)*I/358)*exp(sqrt(179)*I*t) + S(77)/179 + (-S(33)/170 + 7*sqrt(179)*I/170)*(-S(21)/358 + 11*sqrt(179)*I/358)*exp(-sqrt(179)*I*t)) + C2*((-S(33)/170 - 7*sqrt(179)*I/170)*(-S(33)/358 + 7*sqrt(179)*I/358)*exp(sqrt(179)*I*t) + S(121)/179 + (-S(33)/170 + 7*sqrt(179)*I/170)*(-S(33)/358 - 7*sqrt(179)*I/358)*exp(-sqrt(179)*I*t)) + C3*(85*(-S(33)/170 - 7*sqrt(179)*I/170)*exp(sqrt(179)*I*t)/179 + S(33)/179 + 85*(-S(33)/170 + 7*sqrt(179)*I/170)*exp(-sqrt(179)*I*t)/179)), Eq(z(t), C1*((-S(21)/358 - 11*sqrt(179)*I/358)*exp(sqrt(179)*I*t) + S(21)/179 + (-S(21)/358 + 11*sqrt(179)*I/358)*exp(-sqrt(179)*I*t)) + C2*((-S(33)/358 + 7*sqrt(179)*I/358)*exp(sqrt(179)*I*t) + S(33)/179 + (-S(33)/358 - 7*sqrt(179)*I/358)*exp(-sqrt(179)*I*t)) + C3*(85*exp(sqrt(179)*I*t)/179 + S(9)/179 + 85*exp(-sqrt(179)*I*t)/179))]
```

**Comment by vishalg2235** [comment]
Ping @normalhuman @cbm755 @skirpichev Please review! Thanks

**Comment by normalhuman** [comment]
They are equal, just presented in different forms. I executed `s = dsolve(eq2)` and compared.
```
>>> sol2[0].rhs
C1*((-21/170 + 11*sqrt(179)*I/170)*(-21/358 - 11*sqrt(179)*I/358)*exp(sqrt(179)*I*t) + 49/179 + (-21/170 - 11*sqrt(179)*I/170)*(-21/358 + 11*sqrt(179)*I/358)*exp(-sqrt(179)*I*t)) + C2*((-21/170 + 11*sqrt(179)*I/170)*(-33/358 + 7*sqrt(179)*I/358)*exp(sqrt(179)*I*t) + 77/179 + (-21/170 - 11*sqrt(179)*I/170)*(-33/358 - 7*sqrt(179)*I/358)*exp(-sqrt(179)*I*t)) + C3*((-21/2 + 11*sqrt(179)*I/2)*exp(sqrt(179)*I*t)/179 + 21/179 + (-21/2 - 11*sqrt(179)*I/2)*exp(-sqrt(179)*I*t)/179)
```
versus
```
>>> s[0].rhs
C1*((-21/170 + 11*sqrt(179)*I/170)*(-21/358 - 11*sqrt(179)*I/358)*exp(sqrt(179)*I*t) + 49/179 + (-21/170 - 11*sqrt(179)*I/170)*(-21/358 + 11*sqrt(179)*I/358)*exp(-sqrt(179)*I*t)) + C2*((-21/170 + 11*sqrt(179)*I/170)*(-33/358 + 7*sqrt(179)*I/358)*exp(sqrt(179)*I*t) + 77/179 + (-21/170 - 11*sqrt(179)*I/170)*(-33/358 - 7*sqrt(179)*I/358)*exp(-sqrt(179)*I*t)) + C3*(85*(-21/170 + 11*sqrt(179)*I/170)*exp(sqrt(179)*I*t)/179 + 21/179 + 85*(-21/170 - 11*sqrt(179)*I/170)*exp(-sqrt(179)*I*t)/179)
```

Compare the parts with C3 coefficient: sol2 has
```
C3*((-21/2 + 11*sqrt(179)*I/2)*exp(sqrt(179)*I*t)/179 + 21/179 + (-21/2 - 11*sqrt(179)*I/2)*exp(-sqrt(179)*I*t)/179)
```
and s has
```
 C3*(85*(-21/170 + 11*sqrt(179)*I/170)*exp(sqrt(179)*I*t)/179 + 21/179 + 85*(-21/170 - 11*sqrt(179)*I/170)*exp(-sqrt(179)*I*t)/179)
```
That is, 85 is not distributed here. In the test, you should use the form that matches the output (`s`).

**Comment by vishalg2235** [comment]
>you should use the form that matches the output
>
@normalhuman how it works? What is form of output ?

**Comment by normalhuman** [comment]
There are two many issues here to explain in comments. The main one is that you've changed the logic of `dsolve` so that it uses generic solver for n equations even if n is 2. This was not a good move, because the solver for 2 equations is carefully optimized for that case, so it produces solutions in expected form, and correctly handles the presence of parameters.  For example, in one of the tests the 2eq solver returns
```
[Eq(f(x), exp(x)*cos(x)), Eq(g(x), exp(x)*sin(x))]
```
and this was changed to 
```
[Eq(f(x), exp(x*(1 - I))/2 + exp(x*(1 + I))/2), Eq(g(x), I*exp(x*(1 - I))/2 - I*exp(x*(1 + I))/2)] 
```
Not an improvement. 

So I changed dsolve to use 2eq solver when possible:
```
                if match['type_of_equation'] == 'type1' and match['order'] == 1:
                    if match['no_of_equation'] == 2:
                        solvefunc = globals()['sysode_linear_2eq_order1']
                    else:
                        solvefunc = globals()['sysode_linear_neq_order1']
```
Then the tests for 2eq had to be put back the way they were, so I mostly reversed the changes you've made. 
This is in the branch https://github.com/normalhuman/sympy/tree/dsolve-system  which passes all tests. 

But there is a merge conflict because you decided to correct some typos on a separate PR.

**Comment by vishalg2235** [comment]
Okay! I didn't knew that solvers of '2eq' handle them better.
Thanks @normalhuman for your help.
I regret that I made a new PR which created a conflict with this file. I will resolve it.

**Comment by vishalg2235** [comment]
@normalhuman I thought those commits of yours will be merged here after creating PR. But it created a new PR https://github.com/sympy/sympy/pull/14536 !

**Comment by czgdp1807** [comment]
@oscarbenjamin @mijo2 Is this somewhat related to your project?

**Comment by mijo2** [comment]
@czgdp1807 It is and this PR tried to implement exactly what is done in PR #18720 which is already merged.

**Comment by oscarbenjamin** [comment]
Thanks for the contributions. This can be closed now because this work was already done in #18720

**Pull request closed without merging**
