### PR TITLE
dsolve systems fixes and workarounds

### PR DESCRIPTION
**Pull request by cbm755**
The dsolve system code is a bit of a mess (see #9235).  Here are some work arounds, tests and fixes.  Not complete but I'm trying to obey a campsite rule here in case I drop this work ("...leave it in better condition than I found it").

### CODE REVIEW

**Comment by certik** [comment]
This looks good to me. Requires resolving conflicts.

**Comment by cbm755** [comment]
Ok, if that's a "+1", I'll merge in 24 hours or so if tests pass.

**Comment by certik** [comment]
Yes, it's +1.

**Comment by cbm755** [comment]
Just the usual slow test timeouts, so I'll merge.

**Pull request merged**
