### PR TITLE
Error functions in special functions will now use visually distinct symbols.

### PR DESCRIPTION
**Pull request by abhiphile**
#### Brief description of what is fixed or changed
Solves Issue https://github.com/sympy/sympy/issues/26143

#### Other comments
The error function in special functions module now use visually different variables that used to earlier use same variable if given inside the function .

#### Release Notes

* functions
  * Fixed usage of visually same variable when converting to integral in error functions.

### CODE REVIEW

**Comment by sylee957** [comment]
You should also look at `Si`

I think that `_eval_rewrite_as_sinc` and `_eval_rewrite_as_Integral` should be switched because it is more easy to search
```
    def _eval_rewrite_as_Integral(self, z, **kwargs):
        from sympy.integrals.integrals import Integral
        ...
        return Integral(sinc(t), (t, 0, z))

    _eval_rewrite_as_sinc =  _eval_rewrite_as_Integral
```

**Comment by abhiphile** [comment]
I've done as intended, but some doctests are failing. Should I push only the previous commit?

**Comment by abhiphile** [comment]
I have modified the doctest output as intended. As I'm new to contributing, I recognize there may be some issues. Thank you for your understanding.

**Comment by abhiphile** [comment]
@sylee957 Can you please review this PR again . I've made necessary changes in this.

**Pull request merged**
