### PR TITLE
Reverse noncommutative differentiation element order

### PR DESCRIPTION
**Pull request by red-hara**
#### References to other Issues or PRs

No relevant issues or pull-requests found

#### Brief description of what is fixed or changed

Changed order of elements being multiplied during function differentiation.
Now `_eval_derivative` provides proper order of multiplied elements, which is important in case of noncommutative elements.

#### Other comments

When differentiating something like `exp(t*n)` by `t` with noncommutative `n` one expects to get `n*exp(t*n)`, now this behavior is implemented.
A specific use-case is quaternion in exponential form differentiation for angular velocity estimation via `w = 2 * q.diff(t) / q`.

#### Release Notes

* core
  * Reverse order of elements during function differentiation

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
> When differentiating something like `exp(t*n)` by `t` with noncommutative `n` one expects to get `n*exp(t*n)`

Does `n` not commute with `exp(t*n)`?

For quaternions we have:
```
In [14]: q = Quaternion(1, 2, 3, 4)

In [15]: q*q.exp() - q.exp()*q
Out[15]: 0 + 0*i + 0*j + 0*k
```

Usually `exp(t*n)` is defined as
```
exp(t*n) = 1 + t*n + (t*n)^2/2 + (t*n)^3/3! + ...
```
Does that not always commute with `n` (if `t` is commutative)?

The formula `exp(B(t))' = B'(t)*exp(B(t))` depends on the premise that `B(t)` commutes with `B'(t)` which in turn implies that `B'(t)` commutes with `exp(B(t))` so the formula can equally be `exp(B(t))' = exp(B(t))*B'(t)`. On the other hand without some way to know that `B(t)` and `B'(t)` commute we cannot use either formula.

**Comment by oscarbenjamin** [comment]
> Rotation of vector `m` by such quaternion would be represented as `exp(alpha/2*v) * m * exp(-alpha/2*v)`. We can not rearrange multiplication elements, so, at least in quaternion case `v` and `n` vector components do not commute.

The question is not about whether some arbitrary quaternions `m` and `v` commute but specifically whether `q` and `exp(q*t)` commute. This relationship holds for any quaternion `q`:
```python
In [107]: a, b, c, d = symbols('a, b, c, d')

In [108]: t = symbols('t')

In [109]: q = Quaternion(a, b, c, d)

In [110]: q
Out[110]: a + b*i + c*j + d*k

In [111]: q*t
Out[111]: a*t + b*t*i + c*t*j + d*t*k

In [112]: (q*t).exp()
Out[112]: 
exp(a*t)*cos(sqrt(b**2*t**2 + c**2*t**2 + d**2*t**2)) + b*t*exp(a*t)*sin(sqrt(b**2*t**2 + c**2*t**2 + d ↪

↪ **2*t**2))/sqrt(b**2*t**2 + c**2*t**2 + d**2*t**2)*i + c*t*exp(a*t)*sin(sqrt(b**2*t**2 + c**2*t**2 +  ↪

↪ d**2*t**2))/sqrt(b**2*t**2 + c**2*t**2 + d**2*t**2)*j + d*t*exp(a*t)*sin(sqrt(b**2*t**2 + c**2*t**2 + ↪

↪  d**2*t**2))/sqrt(b**2*t**2 + c**2*t**2 + d**2*t**2)*k

In [113]: q*(q*t).exp() - (q*t).exp()*q
Out[113]: 0 + 0*i + 0*j + 0*k
```
This is not surprising from the series definition of the exponential function: if `q` commutes with `q*t` then `q` commutes with `exp(q*t)`.

**Comment by red-hara** [comment]
Thank you for your clarification!

After running more tests I came to conclusion that my suggestion, despite simplifying some corner cases a bit is essentially not a "game-changer", so it can be discarded.

Thank you for your questions and time!

**Comment by oscarbenjamin** [comment]
I don't necessarily object to this change. I just don't understand why it is needed. Theoretically it seems that the order should not matter but there may well be cases where it does.

I don't think either order is more mathematically correct because `n` should commute with `exp(t*n)`. On the other hand SymPy does not know that they commute so the order that is returned can still be relevant for some calculation with SymPy.

I would naturally tend to expect the existing order:
```python
In [11]: exp(t*n).diff(t)
Out[11]: 
   n⋅t
n⋅ℯ 
```
That is just because that is how I am used to seeing it in the context of matrix differential equations though:
https://en.wikipedia.org/wiki/Matrix_differential_equation
The matrix equation
```
x' = A*x
```
has the solution `exp(A*t)*x0` because
```
(exp(A*t)*x0)' = A*(exp(A*t)*x0)
```

**Comment by red-hara** [comment]
Frankly speaking, it's me who currently object to this change. In my sympy-related experiments around SLERP, Bezier curves in SO(3), and velocity estimations I supposed that there is something wrong with function differentiation, but, it seems, that there is a deeper flaw, either in power-related differentiation or in the velocity estimation concept in general.

I'll close the pull request.

Thank you kindly for your time!

**Pull request closed without merging**
