### PR TITLE
trig: write cos(pi/257) as a function of radicals

### PR DESCRIPTION
**Pull request by postvakje**
Implements `cos(pi/257).rewrite(sqrt)`.  A test for checking
`cos(pi/257).rewrite(sqrt)` would take quite a long time.  Is it
worthwhile to put in a test?

### CODE REVIEW

**Comment by smichr** [comment]
Some economy of representation can be obtained by letting cse optimize this from about 15k characters down to less than 3k:

```
x0 = sqrt(257)
x1 = 2*x0
x2 = sqrt(-x1 + 514)
x3 = 60*x0
x4 = x3 + 1028
x5 = sqrt(2)
x6 = sqrt(-x0 + 257)
x7 = x5*x6
x8 = 30*x7
x9 = sqrt(514)
x10 = x6*x9
x11 = 2*x10
x12 = sqrt(x11 + x4 + x8)
x13 = 72*x0
x14 = -x13
x15 = sqrt(x0 + 257)
x16 = x15*x5
x17 = 64*x16
x18 = 28*x7
x19 = 4*x10
x20 = x14 - x17 + x18 + x19 + 2056
x21 = 30*x0
x22 = -x21 + 514
x23 = 15*x16
x24 = x15*x9
x25 = sqrt(x22 + x23 - x24)
x26 = x25*x5
x27 = 64*x26
x28 = x21 + 514
x29 = 15*x7
x30 = sqrt(x10 + x28 + x29)
x31 = x30*x5
x32 = 34*x31
x33 = 2*x9
x34 = x30*x33
x35 = sqrt(-x10 + x28 - x29)
x36 = x35*x5
x37 = 32*x36
x38 = 4*x6
x39 = x30*x38
x40 = sqrt(x20 - x27 - x32 + x34 - x37 + x39)
x41 = sqrt(x1 + 514)
x42 = -x12/4 - x41/2 - sqrt(-x11 + x4 - x8)/4 + 1
x43 = 28*x16
x44 = 4*x24
x45 = 64*x7
x46 = x13 + x43 - x44 + x45 + 2056
x47 = sqrt(x22 - x23 + x24)
x48 = x47*x5
x49 = 32*x48
x50 = 34*x26
x51 = x25*x33
x52 = 64*x36
x53 = 4*x15
x54 = x25*x53
x55 = sqrt(x46 - x49 - x50 - x51 - x52 + x54)/4
x56 = sqrt(x46 + x49 + x50 + x51 + x52 - x54)
x57 = x56/4
x58 = -x57
x59 = x40/4
x60 = -x59
x61 = x14 + x17 - x18 - x19 + 2056
x62 = 64*x48
x63 = 32*x31
x64 = 34*x36
x65 = x33*x35
x66 = x35*x38
x67 = sqrt(x61 - x62 + x63 - x64 + x65 - x66)/4
x68 = -x67
x69 = x0/16
x70 = x2/16
x71 = x12/16
x72 = x69 + x70 + x71 - S(1)/16
x73 = x40/16
x74 = sqrt(x42 - x55 + x58 + x60 + x68 + (x72 + x73)**2)
x75 = -x3 + 1028
x76 = 30*x16
x77 = 2*x24
x78 = sqrt(x75 - x76 + x77)
x79 = sqrt(x75 + x76 - x77)
x80 = x0/4 - x78/8 + x79/8 + S(1)/4
x81 = x13 - x43 + x44 - x45 + 2056
x82 = 34*x48
x83 = x33*x47
x84 = 32*x26
x85 = 64*x31
x86 = x47*x53
x87 = sqrt(x81 - x82 - x83 + x84 + x85 - x86)
x88 = x87/8
x89 = x56/8
x90 = x2/2
x91 = -x90
x92 = x78/4
x93 = -x92
x94 = x79/4
x95 = x87/4
x96 = sqrt(x20 + x27 + x32 - x34 + x37 - x39)/4
x97 = -x69
x98 = x41/16
x99 = x78/16 + x97 - x98 - S(1)/16
x100 = x87/16
x101 = x90 + x92 + x94 + 1
x102 = sqrt(x81 + x82 + x83 - x84 - x85 + x86)/4
x103 = sqrt(x61 + x62 - x63 + x64 - x65 + x66)/4
x104 = -x79/16 + x97 + x98 - S(1)/16
x105 = x56/16
x106 = x0/32 + x12/32 + x2/32 - S(1)/32
x107 = x40/32
x108 = sqrt(x80 - x88 - x89 + (x106 + x107 - x74/2)**2 +
    2*sqrt(x101 - x102 + x103 + x58 + x68 + (x104 + x105)**2) +
    2*sqrt(x57 + x59 + x91 + x93 + x94 - x95 + x96 +
    (x100 + x99)**2 + 1))
x109 = sqrt(x42 + x55 + x57 + x59 + x67 + (x72 - x73)**2)
rv = -((x0 + 32*x108 + x12 + x2 + x40 - 16*x74 - sqrt(4096*x109 - 4096*x70
    - 4096*x71 + 4096*x73 + 4096*x97 - 4096*sqrt(4*x80 + 4*x88 + 4*x89 +
    (2*x106 - 2*x107 - x109)**2 + 8*sqrt(x101 + x102 - x103 + x57 + x67 +
    (x104 - x105)**2) + 8*sqrt(x58 + x60 + x91 + x93 + x94 + x95 - x96 +
    (-x100 + x99)**2 + 1)) + (x0 + 32*x108 + x12 + x2 + x40 - 16*x74 -
    1)**2 + 256) - 1)**2 - 32768)**2/536870912 + 1
```

This expression is only generated on demand with `rewrite(sqrt)` so I guess it's not too bad to add it. Let's see if anyone else has an opinion.

As far as testing it goes...I confirmed that the expression you use gives the same numerical result as the above to 15 digits (0.999925286669733). It seems like a test marked slow is needed but I don't know how many digits to include in the computation.

**Comment by smichr** [comment]
I would recommend adding the reference `http://math.stackexchange.com/questions/516142/how-does-cos2-pi-257-look-like-in-real-radicals`, too.

**Comment by smichr** [comment]
Computing 64 digits takes about 10% longer than computing 2 digits and gives

0.9999252866697325552128053591455562406916298296429212011881377100

**Comment by postvakje** [comment]
also added the reference `http://math.stackexchange.com/questions/516142/how-does-cos2-pi-257-look-like-in-real-radicals`

**Comment by smichr** [comment]
I'm not sure how you got your cse, but the one that I got from your original definition is about half the size (about 15k ops vs about 29k for your current expression). The former computes in about 60 sec on my computer but the other had not finished even after 2 minutes. I would recommend the version that I posted (which has been modified a bit to remove the use of S and was tested to see that it gave the same numerical answer).

**Comment by postvakje** [comment]
I simplified the equation a little bit more before applying cse.  In the new cse expression there is only one division (/256) and there are no large terms such as 2**29.  Even though the resulting equation is longer and thus takes longer to evaluate numerically, I believe it is simpler in that sense.  There is a tradeoff in unwinding the nested expression resulting in a longer final expression.  Using the original equations from http://www.susqu.edu/brakke/constructions/257-gon.m.txt results in an even smaller set of cse equations and faster evaluation.  Let me try to use that instead.

**Comment by smichr** [comment]
> Using the original equations

The ones in the other reference I gave are said to be smaller in case you want to check them.

**Comment by smichr** [comment]
Here is a translation of the stackexchange expressions which computes for me in about 45 seconds and the expression is 16k ops.

```python
def f(a, b, s1=1, s2=None):
    r1 = (a + s1*sqrt(b))/2
    if s2 is not None:
        return r1, (a + s2*sqrt(b))/2
    return r1

t1, t2 = f(-1, 257, 1, -1)
z2, z4 = f(t2, t2**2 + 64, 1, -1)
z1, z3 = f(t1, t1**2 + 64, 1, -1)
y4, y8 = f(z4, z4**2 + 4*(5 + t2 + 2*z4), -1, 1)
y3, y7 = f(z3, z3**2 + 4*(5 + t1 + 2*z3), 1, -1)
y2, y6 = f(z2, z2**2 + 4*(5 + t2 + 2*z2), -1, 1)
y1, y5 = f(z1, z1**2 + 4*(5 + t1 + 2*z1), 1, -1)
x8, x16 = f(y8, y8**2 - 4*(t2 + y8 + y2 + 2*y5), 1, -1)
x7, x15 = f(y7, y7**2 - 4*(t1 + y7 + y1 + 2*y4), -1, 1)
x6, x14 = f(y6, y6**2 - 4*(t2 + y6 + y8 + 2*y3), 1, -1)
x5, x13 = f(y5, y5**2 - 4*(t1 + y5 + y7 + 2*y2), 1, -1)
x4, x12 = f(y4, y4**2 - 4*(t2 + y4 + y6 + 2*y1), 1, -1)
x3, x11 = f(y3, y3**2 - 4*(t1 + y3 + y5 + 2*y8), 1, -1)
x2, x10 = f(y2, y2**2 - 4*(t2 + y2 + y4 + 2*y7), 1, -1)
x1, x9 = f(y1, y1**2 - 4*(t1 + y1 + y3 + 2*y6), 1, -1)
v6 = f(x16, x16**2 - 4*(x16 + x1 + x2 + x5), -1)
v5 = f(x10, x10**2 - 4*(x10 + x11 + x12 + x15), -1)
v4 = f(x9, x9**2 - 4*(x9 + x10 + x11 + x14), -1)
v3 = f(x8, x8**2 - 4*(x8 + x9 + x10 + x13), -1)
v2 = f(x2, x2**2 - 4*(x2 + x3 + x4 + x7), -1)
v1 = f(x1, x1**2 - 4*(x1 + x2 + x3 + x6), -1)
u2 = f(v4, v4**2 - 4*(v5 + v6), 1)
u1 = f(v1, v1**2 - 4*(v2 + v3), 1)
w1 = u1 + sqrt(u1**2 - 4*u2)
c257 = sqrt(sqrt(2)*sqrt(w1 + 4)/8 + S(1)/2)
```

**Comment by smichr** [comment]
Hmm...squares appear to be worse to calculate than square roots. The form you are using takes about 150 s to compute (compared to 45 s for the form I last posted). I also tried printing this and it took about 280 s (compared to about 120 s for the form I gave). 

Perhaps it's better to just cite the reference to 257 and 65537 work by brakke -- maybe in the trignometry docstring? And the inline comment "add if you like" should be changed to something like "intentionally not added". 

I don't see a lot of value in adding such a large expression. Do you have other thoughts? It doesn't help one compute the value. It does demonstrate that angles involving Fermat primes can be re-written, but we already have the smaller ones showing that.

**Comment by postvakje** [comment]
I agree that the expression doesn't help in finding its value numerically and most likely there is no need to manipulate this large expression symbolically (but you'll never know, see e.g. http://mathforum.org/kb/thread.jspa?forumID=79&threadID=235793&messageID=787071).  On the other hand, it only adds a few kbytes of code and memory, but I am okay with just leaving it out and pointing to the reference by Brakke.  
As a final thought, I don't know if other CAS systems compute this expression, It looks like Maple doesn't and requires additional code to compute cos(pi/257): http://paul.barbaroux.free.fr/#cos

**Comment by smichr** [comment]
Would you be willing to use the last 2 lines I gave above (for w1 and cos257) to finish the computation so the more quickly evaluating expression in terms of sqrt is obtained?

**Comment by smichr** [comment]
:parking: A [pull request](https://github.com/postvakje/sympy/pull/1) was sent.

**Comment by smichr** [comment]
BTW, I tried the cos(pi/65537) expression and it takes 1000 s to just compute the symbolic expression (not evaluate it). I was never able to do more than that with it.

**Comment by smichr** [comment]
:parking: [PR again](https://github.com/postvakje/sympy/pull/2)

**Comment by smichr** [comment]
[This run](https://travis-ci.org/smichr/sympy/builds/52488462) passed so I will commit this.

**Pull request merged**
