### PR TITLE
Test case added for Lambdify #11044

### LINKED ISSUE #13881: test case for syntax error on lambdify
See this issue https://github.com/sympy/sympy/issues/11044 . That issue was fixed in PR https://github.com/sympy/sympy/pull/11566. Though no test case was added for the `lambdify`.

#### What needs to be done?

Add test case that this works just fine:
```python
>>> from sympy import MatrixSymbol, lambdify
>>> x = MatrixSymbol('x', 3, 1)
>>> f = lambdify(x, x.T*x)
```

Test case needs to be added in appropriate file

### PR DESCRIPTION
**Pull request by tanayag**
fixes #13881

### CODE REVIEW

**Comment by gxyd** [comment]
I think this comment https://github.com/sympy/sympy/issues/13967#issuecomment-359172561 explains the error.

On travis, numpy is not installed, so it actually return matrix array [14], instead of number 14. While locally, you probably do have numpy installed and it passes the tests.

We'll probably need to check whether numpy is installed on the environment or not and then accordingly write the test case for whether it should be equal to a matrix [14] or number 14.

You'll need to use `from sympy.external import import_module` to check whether numpy is installed or not.

**Comment by gxyd** [comment]
I think @ylemkimon opened issue, https://github.com/sympy/sympy/issues/13984. I think we should wait, before that is merged.

I think we'll just need to change the number 14 to matrix [14] here, after that issue is fixed.

**Comment by tanayag** [comment]
ohh! I see, I updated the code, can we stop the bot!

**Comment by gxyd** [comment]
I've cancelled the build, thanks for mentioning that. I'm sorry, I requested wrong changes.

**Comment by czgdp1807** [comment]
Is this ready to go now? What all is to be done to turn it in?

**Comment by czgdp1807** [comment]
Closing due to my mistake of force pushing the changes. Apologies.

**Pull request closed without merging**
