### PR TITLE
Empty intersection returns Universal set

### LINKED ISSUE #12178: Empty intersection should be UniversalSet
```
In [46]: Intersection()
Out[46]: ∅
```

It should be `S.UniversalSet`. See https://en.wikipedia.org/wiki/Intersection_(set_theory)#Nullary_intersection

### PR DESCRIPTION
**Pull request by madan96**
Made changes to `__new__` method in `Intersection` class.

Fixes #12178

### CODE REVIEW

**Comment by madan96** [comment]
@asmeurer Is this alright?

**Comment by madan96** [comment]
Apparently another PR related to this issue got merged. Closing this for now.

**Comment by madan96** [comment]
@asmeurer @jksuom Can you please tell me the issues with my PR, so that I can rectify them in future PRs?

**Comment by Abdullahjavednesar** [comment]
@madan96 your changes seems good, except for a missing test case.

**Pull request closed without merging**
