### PR TITLE
Fixed summation in summation(x**y*y, (y, -oo, oo)).doit() to prevent infinite loop

### LINKED ISSUE #15852: summation(x**y*y, (y, -oo, oo)).doit() hangs in infinite loop
```
from sympy import symbols, summation, oo
y = symbols('y', integer=True)
x = symbols('x')
summation(x**y*y, (y, -oo, oo)).doit()
```

Hangs. The reason seems to be that `And(Abs(x) < 1, Abs(1/x) < 1)` is not evaluated to `False` here (which it should be possible to do as far as I can tell) and that instead the code goes into an infinite loop.
https://github.com/sympy/sympy/blob/1e999fc5159b830a9872b86675bc5f3692a9c1be/sympy/concrete/summations.py#L1176-L1179

### PR DESCRIPTION
**Pull request by jmig5776**
#### References to other Issues or PRs

Fixes #15852 

#### Brief description of what is fixed or changed
Earlier 
```
from sympy import symbols, summation, oo
y = symbols('y', integer=True)
x = symbols('x')
summation(x**y*y, (y, -oo, oo)).doit()
```
stucked in infinite loop due to condition in `eval_sum_hyper`

Now 
```
from sympy import symbols, summation, oo
y = symbols('y', integer=True)
x = symbols('x')
summation(x**y*y, (y, -oo, oo)).doit()
Sum(x**y*y, (y, -oo, oo))
```

#### Release Notes

* concrete
  * fixed a bug in `eval_sum_hyper`

### CODE REVIEW

**Comment by jmig5776** [comment]
@oscargus , @smichr Please review it.

**Comment by asmeurer** [comment]
Is it possible to get an answer here, instead of the unevaluated Sum?

**Comment by jmig5776** [comment]
I think there might be a way, I am trying to get the answer in Piecewise form .

**Comment by jmig5776** [comment]
The solution to this `summation(x**y*y, (y, -oo, oo)).doit()` actually does'nt exist because no value of x exist to converge the `summation(x**y*y, (y, -oo, oo)).doit()`. 
In this commit I had added to return the piecewise solution but don't know it is nested twice.
Moreover I think as no value of x doesn't exist then it should return the unevaluated integral.

**Comment by oscargus** [comment]
@oscarbenjamin as I wrote in #15852 I believe a good way to solve is to make sure that `And(Abs(x) < 1, Abs(1/x) < 1)` evaluates to `False`. Probably more complicated, but also probably more useful in other situations as well. I do not know if there is a way to manually add this type of "rules" in the logic methods though, but it can be quite useful.

**Comment by jmig5776** [comment]
@oscarbenjamin I forgot to update the test. And I also think that the unevaluated result should be returned.
@asmeurer do you think that the result here should be simplified because that will be specific.

@oscargus See in my previous commit i had added a new condition which was satisfied by the `cond` because cond gives the set of `x` that is possible so `And ` is unable to solve in a set way so I applied this condition `cond._eval_as_set() == S.EmptySet` which is equivalent to `And`.

**Comment by asmeurer** [comment]
Ah I didn't think about the convergence conditions. So this probably shouldn't have an answer. 

Simplification of conditions is something that needs to be improved in general. However, I don't the summation algorithms shouldn't rely on a condition simplifying to not infinitely recurse.

**Comment by jmig5776** [comment]
@asmeurer Please review it.

**Comment by asmeurer** [comment]
How did this result in an infinite loop? It seems like this doesn't address the core issue. If another convergence condition doesn't reduce to False or EmptySet, will it also result in an infinite loop?

**Comment by jmig5776** [comment]
Infinite loop occured because when the cond was unable to get false then the piecewise returned the same function with condition which involves no x possible. 
I dont think so because cond can be direct true or false or might give the conditions of variable and we want to return None if no possible summation is there.
I am not saying that its not possible, there might be any example for which it is failing, but upto now I think its good.

**Comment by jmig5776** [comment]
@asmeurer I think this is okk and can be merged into master.

**Comment by jmig5776** [comment]
@smichr Please review it.

**Comment by asmeurer** [comment]
How does that create an infinite loop?

**Comment by jmig5776** [comment]
Here
https://github.com/sympy/sympy/blob/3b1895477e50a792e21a0aa7c02d5cf31f03eb6d/sympy/concrete/summations.py#L1176-L1179

the `cond==False` is passed over because it was returning `False` and then `return Piecewise((res1 + res2, cond), (old_sum, True))` this returns the `Sum(x**y*y, (y, -oo, oo))` which when again calculated returns `Sum(x**y*y, (y, -oo, oo))` and then goes on.

**Comment by oscargus** [comment]
Just to add a bit detail that may not have been clear earlier. For the specific example
`cond = And(Abs(x) < 1, Abs(1/x) < 1)`. Now `cond == False` does not evaluate to `True` (which it should as `cond` can never be `True`), and, hence, it is called again and again and again  with the same arguments.

To some extent, #15912 alleviates adding a pattern for this so that it can be simplified to `False` (that particular pattern is still not there though). However, there may be other cases where evaluating it as a set shows that it is in fact `False`although `And` didn't evaluate it like that. So I still think it makes sense to add this piece of code.

**Comment by oscarbenjamin** [comment]
I'm not familiar with the sets code in sympy but calling `_eval_as_set` looks like calling into a private method. Is there a public function that should be used in this situation?

**Comment by jmig5776** [comment]
I don't know, I called set function because equation involving more than one variable may give solutions w.r.t other variables, thats y i called set function if some values of other variable (here x) exists or not.

**Comment by jmig5776** [comment]
@asmeurer What do you think of it after above discussion?

**Comment by oscarbenjamin** [comment]
I'm not sure I understand what `_eval_as_set` does. I thought maybe it was the implementation for `as_set` but trying this it seems that `_eval_as_set` can return incorrect results:
```julia
In [2]: And(x<1,y>1)._eval_as_set()                                                                                                                           
Out[2]: ∅

In [3]: And(x<1,y>1).as_set()                                                                                                                                 
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-3-86183a55ad19> in <module>
----> 1 And(x<1,y>1).as_set()

~/current/sympy/sympy/sympy/logic/boolalg.py in as_set(self)
    157             return self.subs(reps)._eval_as_set()
    158         else:
--> 159             raise NotImplementedError("Sorry, as_set has not yet been"
    160                                       " implemented for multivariate"
    161                                       " expressions")

NotImplementedError: Sorry, as_set has not yet been implemented for multivariate expressions
```
I don't think that the empty set is correct there.

It does seem to work for the case at hand though:
```julia
In [4]: And(x<1,x>1).as_set()                                                                                                                                 
Out[4]: ∅
```

Maybe `.as_set()` is the right way to go here.

**Comment by jmig5776** [comment]
It worked as you suggested @oscarbenjamin. I am commiting the changes.

Sorry for the late response. I was having my exams going in the previous week.

**Comment by oscarbenjamin** [comment]
This looks good. I'll merge soon.

**Pull request merged**
