### PR TITLE
Improves Floor and Ceiling classes

### PR DESCRIPTION
**Pull request by sidhantnagpal**
#### References to other Issues or PRs
#7951

#### Brief description of what is fixed or changed
The following changes are to be covered:
- [x] Add rewrite methods for `floor`, `ceil`, `frac`.
- [x] Add equality methods for `floor(x) == -ceiling(-x)` and similar.
- [ ] Handle reversed relations `floor(x) <= x` as `x >= floor(x)` and similar.

### CODE REVIEW

**Comment by Abdullahjavednesar** [comment]
@jksuom, @smichr can anyone please review, Thanks!

**Comment by asmeurer** [comment]
What is here so far looks good.

**Comment by sidhantnagpal** [comment]
In `relational.py` module, usage of `_eval_Eq` is suggested. 
However I found its usage in Matrix modules (for instance) and not primarily for Functions (at least `Trigonometric`).
For example:
`Eq(sin(x), x*sinc(x))`, `Eq(sin(x), 1/csc(x))` remain unevaluated.

As a natural extension, I think it would be good if `rewrite` methods imply `Eq`.

**Comment by asmeurer** [comment]
I wouldn't try to do too much advanced logic in the constructors. It's better if `simplify` takes care of complicated cases like that. See also https://github.com/sympy/sympy/wiki/Automatic-Simplification

**Comment by sidhantnagpal** [comment]
Ah, I see your point. So, I think it would suffice to just check for equality by trying to expressing floor as frac/ceiling and returning `None` in all other cases.

**Comment by smichr** [comment]
looks good
```
>>> assert all(floor(i)==-ceiling(-i) for i in n)
>>> assert all(floor(i)==i-frac(i) for i in n)
>>> assert all(ceiling(i)==i+frac(-i) for i in n)
>>> assert all(ceiling(i)==-floor(-i) for i in n)
>>> assert all(frac(i)==i-floor(i) for i in n)
>>> assert all(frac(i)==i+ceiling(-i) for i in n)
>>> n
(-1.9, -1.1, 1.1, 1.9)
```

**Pull request merged**
