### PR TITLE
Created SVG images to replace beam ascii art

### LINKED ISSUE #15331: Create SVG images to replace beam ascii art
See: https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam_problems.html

It would be nicer if each beam ascii diagram was replaced with a nicer looking SVG diagram. Example diagrams can be found in solid mechanics textbooks.

### PR DESCRIPTION
**Pull request by death-angel-141**
Created SVG images to replace beam ascii art  for documentation

#### References to other Issues or PRs

Fixes  #15331

#### Brief description of what is fixed or changed

SVG images to replace beam ascii art  for documentation was added 

[Binder1.svg.zip](https://github.com/sympy/sympy/files/4313194/Binder1.svg.zip)

* other 
  * New Added SVG Files for Beams Documentation

### CODE REVIEW

**Comment by asmeurer** [comment]
The file needs to be added to the documentation. Also I don't think it should be zipped.

**Comment by death-angel-141** [comment]
@asmeurer thnx for the suggestion,I shall take care of it

**Comment by asmeurer** [comment]
You should checkout the code locally and use git to add the files. If you are new to git you can use the GitHub client.

**Comment by death-angel-141** [comment]
Yeah,will check it out

**Comment by czgdp1807** [comment]
@moorepants Is the SVG image okay in this patch. If yes, then I will make a PR to fix this issue.

**Comment by moorepants** [comment]
No idea, looks like they committed a zip file. We also have the new .draw() method that may supersede the need for any figures.

**Comment by eric-wieser** [comment]
I think the way forward is to:
* Improve the draw method to look more like the diagrams
* Use it in the examples

**Comment by moorepants** [comment]
I agree. We can close this in favor of that.

**Pull request closed without merging**
