### PR TITLE
[skip ci] PEP8ify facts.py

### PR DESCRIPTION
**Pull request by jremes-foss**
Just one amendment on this PR. Amended the extra white space on line 298. Thanks.

### CODE REVIEW

**Comment by leosartaj** [comment]
On executing ``flake8 sympy/core/facts.py`` in your branch.

I get

```
sympy/core/facts.py:77:1: E302 expected 2 blank lines, found 1
sympy/core/facts.py:96:1: E302 expected 2 blank lines, found 1
sympy/core/facts.py:137:81: E501 line too long (89 > 80 characters)
sympy/core/facts.py:378:81: E501 line too long (82 > 80 characters)
sympy/core/facts.py:441:81: E501 line too long (82 > 80 characters)
```

If you want you can take a look at these too. Otherwise this looks ok.

**Comment by Newman101** [comment]
Hi. I'll sort these out as well. Thanks for notifying me.

**Comment by leosartaj** [comment]
@Newman101 are you planning to work on this further?

**Comment by Newman101** [comment]
I will review that file and commit the changes as soon as I can if that's OK.

**Comment by leosartaj** [comment]
:+1:

**Comment by leosartaj** [comment]
Looks good. Merging.

**Comment by leosartaj** [comment]
Thanks @Newman101 for your work.

**Comment by Newman101** [comment]
Happy to help as always. =)

**Pull request merged**
