### PR TITLE
Use <cn> tag for integer root degree in MathML

### PR DESCRIPTION
**Pull request by ashleypeak**
#### Brief description of what is fixed or changed
The MathML for the rational base of a root element was being formatted as a `<ci/>` element, instead of a `<cn/>` element. 

```python
from sympy import Rational
from sympy.printing import mathml

print(mathml(2 ** Rational(1, 3)))
```

Previously output:

```xml
<apply><root/><degree><ci>3</ci></degree><cn>2</cn></apply>
```

It now outputs:

```xml
<apply><root/><degree><cn>3</cn></degree><cn>2</cn></apply>
```

From [The W3C documentation for the `<ci/>` element](https://www.w3.org/TR/MathML3/chapter4.html#contm.ci), 

> Content identifiers represent "mathematical variables" which have properties, but no fixed value.

#### Release Notes

- printing
  - Fix the tag for the degree of a root with a rational base in MathML output.

### CODE REVIEW

**Comment by sylee957** [comment]
I think that you should modify the test cases in test_mathml.
Probably the string output change may have affected the tests.

**Comment by asmeurer** [comment]
Based on my reading of the document you linked to this looks correct.

**Comment by czgdp1807** [comment]
```python
In [1]: from sympy import Rational
   ...: from sympy.printing import mathml
   ...: 

In [2]: mathml(2 ** Rational(1, 3))
Out[2]: '<apply><root/><degree><ci>3</ci></degree><cn>2</cn></apply>'
```
This PR still has a scope to be merged.

**Comment by czgdp1807** [comment]
I have merged master to this branch. Please let us know if this can be merged. @asmeurer @sylee957

**Comment by czgdp1807** [comment]
I have updated one failing test to match with the changes introduced.

**Comment by czgdp1807** [comment]
@sylee957 @asmeurer The tests are passing. Can we merge this?

**Comment by czgdp1807** [comment]
Will merge this in a couple of days if no objections raised.

**Pull request merged**
