### PR TITLE
Updates to Line3D and Plane

### PR DESCRIPTION
**Pull request by mcdaniel67**
There was a bug in `Plane.are_concurrent()`. The bug causes the function to return False when we call the function with a single argument which is not a plane. 

Here is an example of the bug:

```
> from sympy.geometry import Point, Plane
> Plane.are_concurrent(Point(0, 0))
False
```

With the updated implementation, the function raises a ValueError, which seems to be the desired behavior. I think this is the desired behavior, because if we called `Plane.are_concurrent` with two Point3D arguments, we get the raised ValueError.

I also removed a try/except block from the Line3D and Ray3D constructor. The block was checking for a NotImplementedError in Point3D. Point3D does not have a NotImplementedError, despite what the documentation states. I updated the documentation for Point3D to reflect this as well.

I also added a significant number of tests for Line3D.

### CODE REVIEW

**Comment by mcdaniel67** [comment]
The error on this build is due to a PyPy failure as well as a Travis timeout.

**Comment by toolforger** [comment]
The Travis timeout has been plagueing us for a while. A restart should fix this.
The PyPy crash is PyPy itself. I haven't seen something like that in a while; I hope it goes away after a restart, but if it doesn't, this will require a closer look.

**Comment by mcdaniel67** [comment]
Would it be a good idea to just pull the recent changes (splitting the slow tests) into my fork so that the tests rerun and the likelihood of the timeout decreases? Or should I just wait and let someone with the authority on Travis rerun this fork?

**Comment by debugger22** [comment]
You'll have to pull those changes from the master in order to make use of that.

**Comment by mcdaniel67** [comment]
Yeah, that's no big deal. I'll probably want to pull those changes into my fork at some point anyway, because pretty much all the pull requests I've submitted have had a timeout issue at some commit or another. I just wasn't sure if it is bad at all to do something like that (just pulling changes from master) to trigger a new build.

**Comment by toolforger** [comment]
> I just wasn't sure if it is bad at all to do something like that (just pulling changes from master) to trigger a new build.

There are no fundamental problems with that. If you want to pull in 
everything anyway, the full test run will happen now instead of later, 
that's all.

**Comment by mcdaniel67** [comment]
Would it be possible to get an update on the status of this pull request?

**Comment by asmeurer** [comment]
It looked good to me. Merged.

**Pull request merged**
