### PR TITLE
test imageset args; modify ImageSet._contains

### PR DESCRIPTION
**Pull request by smichr**
closes #10476 and also handles non-linear expressions as added in tests
- [x] correct the following

```
>>> Tuple(S(1)/3,1,0) in imageset(Lambda((a,y,z),(1/y,a,z)),x)
False  <-- should be True
>>> Tuple(1,1/S(3),0) in imageset(Lambda((a,y,z),(y,1/a,z)),x)
True  <-- ok
```

Changes here also make possible a Rationals class:

```
>>> Rationals = imageset((x, y), x/y, S.Integers*S.Integers)
>>> S.Half in Rationals
True
>>> 1/pi in Rationals
False
```

### CODE REVIEW

**Comment by smichr** [comment]
If there is no objection to being able to write `imageset(f(x), set)` instead of `imageset(Lambda(x, f(x)), set)` then I will commit this.

**Comment by jksuom** [comment]
I'm +1 for dropping ``Lambda`` but not sure if the argument ``x`` should be omitted as well. Perhaps we could write ``imageset(expr, set, x=None)``. It would then not be necessary to consider only univariate expressions. (Actually I would prefer ``imageset(expr, x, set)`` but that would probably be harder to implement without breaking the current API.)

**Comment by smichr** [comment]
Sorry, the changes were made in the wrong place. ImageSet just receives the Lambda and set and should not actually be called directly. `imageset` is where the variety of inputs are handled. I see that args can be (x, f(x), set), (Lambda, set), (lambda, set); I have extended this to include (FunctionClass, set) and (univariate Expr, set).

**Comment by smichr** [comment]
Should we add a Rationals class as mentioned in the OP?

**Comment by kshitij10496** [comment]
+1
It sounds like a nice idea to me.

**Pull request merged**
