### PR TITLE
Fix/silence flake8 warnings in sets

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

See #17795 

#### Brief description of what is fixed or changed

Use #noqa to silence flake8 warnings in sets. These are spurious warnings but there isn't a good way to ignore them.

Also fix some imports in sets.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This is ready for review

**Comment by sylee957** [comment]
I still see those F811 warnings out there.

**Comment by oscarbenjamin** [comment]
Looks like it depends whether you run flake8 under Python 3.7 or 3.8. For 3.7 you need to do:
```
@dispatch() # noqa
def union_sets(A, B):
     pass
```
However 3.8 needs
```
@dispatch()
def union_sets(A, B): # noqa
     pass
```

**Comment by oscarbenjamin** [comment]
Okay looks like that's fixed it.

**Pull request merged**
