### PR TITLE
feat: introduce symbolic equation

### PR DESCRIPTION
**Pull request by JSS95**
#### References to other Issues or PRs

Derived from #19479

#### Brief description of what is fixed or changed

Introduce `sympy/equation` module.
Introduce `Eqn` class.
Support side proxy object of `Eqn` object for symbolic manipulation.

#### Other comments

This is a minimal implementation of what @gutow is working in #19479. Here, only the `Eqn` class, its printing, and side proxy object is implemented from his design.

There are some differences with #19479, though:

- `Eqn` is introduced in its own module (`sympy/equation`), rather than in `core`.
- `SymbolicRelation` class is base class of `Eqn`. Other classes that will be introduced in future (i.e. symbolic `x>y`) will subclass `SymbolicRelation` as well.
- `Eqn` does not subclass `EvalfMixin`. Also, `Eqn` allows non-`Expr` lhs and rhs. (Still, every item in `args` will be `Basic` since it is sympified.)
- Applying methods to `Eqn` and applying `Eqn` to some other function both use `apply` property. `Eqn(x, y).apply.method()` returns `Eqn(x.method(), y.method())`, and `Eqn(x, y).apply(f)` returns `Eqn(f(x), f(y))`.

#### Release Notes

I will manually edit the release note for this time since equation module is not registered in SymPy bot.

NO ENTRY

### CODE REVIEW

**Comment by JSS95** [comment]
@gutow Here is how I made a minimal implementation of your work. I have changed a few things, though. Please take a look and let me know if this suits your intention.

**Comment by gutow** [comment]
A quick check lead to the following issues. I have not tracked down the responsible code.
1. I think it is a mistake to not require each side of the equation be a valid sympy expression. This is because the ultimate goal is to provide an equation that can be manipulated as a valid mathematical equation.
2. The following result is not at all what is expected:
```
[0]: t = Eqn(a,b/c)
a=b/c
[1]: exp(t)
exp(a=b/c)
```
Should give: `exp(a)=exp(b/c)` or throw an error at this simple stage since you have not defined the `pow` operation for this type yet.

As most of my goal is to allow manipulations of equations as one would do on paper and to use them as input and output for solve, I would not say that this addresses my goals. At this point it produces output that looks like an equation and appears to implement the `apply` in a way that is compatible with what I have, but it does not behave as an equation where the two sides are assumed to be equal nor properly distribute sympy operations across the two sides. I think this will have to include at least the binary operations to be a first step.

**Comment by JSS95** [comment]
Valid mathematical expression can be non-`Expr`. For example `NDimArray` is `Basic` but not `Expr`.

Passing equation to function needs more discussion so I deliberately not included that in this PR. We need something more than just adding a one-line hook in `Function.__new__`.

I think binary operation on equations must be dealt by classes like `AddSides`, `MultiplySides` as @sylee957 suggested in #19479. It will need some discussion so I did not implement it in this PR.

**Comment by gutow** [comment]
> NDimArray



> Valid mathematical expression can be non-`Expr`. For example `NDimArray` is `Basic` but not `Expr`.

I am worried about allowing entities which do not have well defined behavior as part of an equation. That is why I am initially inclined to allow only valid sympy expressions as the lhs and rhs. The general NDimArray can hold a lot of different things.

**Comment by JSS95** [comment]
But what would that well defined behavior be? Some students may want to express that two coordinates are same, which allows `Tuple` to be in equation. A mathematician may want to show every component of Christoffel symbol or curvature tensor, which needs `NDimArray`.

To me, equation is more like a container that helps symbolic manipulation than a mathematical equality. It's very disputable and restrictive to check the type of  its arguments. It will be better to let user decide what to put in at own discretion.

**Comment by gutow** [comment]
> But what would that well defined behavior be? Some students may want to express that two coordinates are same, which allows `Tuple` to be in equation. A mathematician may want to show every component of Christoffel symbol or curvature tensor, which needs `NDimArray`.
> 
> To me, equation is more like a container that helps symbolic manipulation than a mathematical equality. It's very disputable and restrictive to check the type of its arguments. It will be better to let user decide what to put in at own discretion.

I understand your point, but that is contrary to the discussion and suggestions from @oscarbenjamin and @asmeurer to my original commit. It was at their urging that I originally limited the arguments of `Eqn` to valid sympy expressions. I think the loosening of that restriction should be a separate issue.

**Comment by JSS95** [comment]
I requested review to them. I will wait for their response.

**Comment by sylee957** [comment]
I would favor this idea over #21333 for the reason that the object have no special methods and could be better for handling universal objects.
I think that handling universal symbolic objects and building an abstract rewriting system is sufficient for the usage, especially for projects of building step-by-step solvers. 
We shoudn't begin with defining operations too much (like endowing `__add__`, `__mul__`, ...) 
I think that sympy had been uncontrollable with automatic evaluations which had brought the need of `Kind` system, but I still question that idea such that if we had begin with objects with no automated evaluation at all.

**Comment by gutow** [comment]
> I would favor this idea over #21333 for the reason that the object have no special methods and could be better for handling universal objects.
> I think that handling universal symbolic objects and building an abstract rewriting system is sufficient for the usage, especially for projects of building step-by-step solvers.
> We shoudn't begin with defining operations too much (like endowing `__add__`, `__mul__`, ...)
> I think that sympy had been uncontrollable with automatic evaluations which had brought the need of `Kind` system, but I still question that idea such if we had begin with objects with no automated evaluation at all.

I may misunderstand you, but this sounds more like an effort to write a programming language on top of python, which is already written on top of C, rather than writing a tool to facilitate symbolic manipulation of mathematical entities. I envision the equation class as a tool to be used much like a calculator to allow more rapid algebraic manipulations. To do this there are a number of requirements:
1. The syntax should be as close to standard on paper mathematics as possible.
2. You should have to understand mathematics, not how the program works to use it.
3. It should provide descriptive and errors and warnings that do not require that the user understands the details or writing code or pythonic OO code.

These requirements do not preclude adding the backend coding tools you are envisioning, but they necessitate the definition of things like `__mul__` for the tool to even reach rudimentary utility.

**Comment by sylee957** [comment]
I don't think that adding/multiplying arbitrary numbers is a necessary utility, rather than ontological meanings, 
Take an example, solving `a*b/c**2*x = y` with respect to `x`, you can clearly see that the steps to add/multiply `2, pi, z, ...` doesn't need to be utilized at all, but you can notice that the actual blocks that is needed is multiplying/dividing a finite combination of `a, b, c` or `a, b, c**2`.
A lot of computerized strategies of 'hand equation solving' lies in finite [group](https://en.wikipedia.org/wiki/Group_(mathematics)) operation, which I believe that can depreciate the need of `__add__, __mul__` with arbitrary constants at least.

**Comment by gutow** [comment]
> Take an example, solving `a*b/c**2*x = y` with respect to `x`, you can clearly see that the steps to add/multiply `2, pi, z, ...` doesn't need to be utilized at all, but you can notice that the actual blocks that is needed is multiplying/dividing a finite combination of `a, b, c` or `a, b, c**2`.

> A lot of computerized strategies of 'hand equation solving' lies in finite [group](https://en.wikipedia.org/wiki/Group_(mathematics)) operation, which I believe that can depreciate the need of `__add__, __mul__` with arbitrary constants at least.

I believe you are suggesting a system that would limit what choices of objects could be combined with the equation using `__mul__`, `__add__`, etc. I think you are describing a system specifically for directed or computer aided solutions to equations. I actually want something more general, where I can add or multiply by arbitrary symbols, constants or equations to modify the form of the equation in valid, but useful ways. For some very simple examples see the section on `Combining Equations (math with equations)` in the `Demonstration of equation class.ipynb` notebook available in my [Algebra_with_Sympy binder instance](https://mybinder.org/v2/gh/gutow/Algebra_with_Sympy/36b9f0d9602713447db977eb106870b90166a4e6).

If you are actually talking about a more general replacement for `__mul__`, `__add__`, etc. then, I think, that should be implemented on expressions first.

**Comment by oscarbenjamin** [comment]
The class here looks good to me. I don't think we should merge this without agreeing what at least some of the next steps are though.

Compared to Equality the differences here are:

1. Equation is not a Boolean.
2. Equation does not evaluate and always has sides etc.
3. Equation has the methods apply, applylhs and applyrhs.

For point 3 we could just add those methods to Equality but their usefulness would be limited by point 2. The fact that it is not a `Boolean` means it can't be used in e.g. `And` and is probably just confusing for users but seems cleaner to me.

So far this is useful but it's not that useful and introducing this class will be very confusing for users so there needs to be a lot more to this. I realise that the intention is to add more stuff later but I don't see how we can merge anything without having any agreement on what that is.

There has been a lot of discussion about things like `eq + eq` etc. I'm happy to put those aside if we can agree on other features that make this a worthwhile addition anyway.

1. Do we want to make this the standard equation type that is used e.g. as recommended for passing equations to `solve`, `dsolve`, etc?
2. Would there be implicit conversions to allow this to be used in a boolean context such as when constructing a `Piecewise`?
3. Should this work with `subs` like `x.subs(Eqn(x, y))` or `x.subs([Eqn(x, y), Eqn(z, t)])`?
4. How would you convert from `Equality` to `Equation` and vice versa?
5. Should the types of objects that can appear on each side be limited e.g. to `Expr` or should it be possible to have any kind of object on each side of the `Equation`?

Really where we are now is the same as before which is that we need to write up a clear rationale somewhere and agree on at least some things that are a clear improvement making the changes worthwhile.

**Comment by gutow** [comment]
> There has been a lot of discussion about things like `eq + eq` etc. I'm happy to put those aside if we can agree on other features that make this a worthwhile addition anyway.

I suggest that this discussion be offloaded to the the [SymPEP](https://github.com/sympy/SymPEPs/pull/1), which I started for the equation class. I haven't edited it yet, but we should remove consideration of how differentiation and integration of an equation should be handled. That requires thought and discussion on how the calculus module should work.

The SymPEP seems the appropriate place to map out a strategy.

We can discuss it more in the SymPEP, but cannot imagine `Eqn` receiving any significant use unless it implements basic algebra.

**Comment by gutow** [comment]
The PR for the SymPEP is https://github.com/sympy/SymPEPs/pull/1

**Comment by JSS95** [comment]
> 1. Do we want to make this the standard equation type that is used e.g. as recommended for passing equations to `solve`, `dsolve`, etc?
> 2. Would there be implicit conversions to allow this to be used in a boolean context such as when constructing a `Piecewise`?
> 3. Should this work with `subs` like `x.subs(Eqn(x, y))` or `x.subs([Eqn(x, y), Eqn(z, t)])`?
> 4. How would you convert from `Equality` to `Equation` and vice versa?
> 5. Should the types of objects that can appear on each side be limited e.g. to `Expr` or should it be possible to have any kind of object on each side of the `Equation`?

1. Yes. `solve` and `dsolve` treats the equation as a binary container rather than boolean equality. I think most use case will be that user manipulates the equation (like `eqn + eqn`) and pass it to solver functions.
2. I doubt it. `Piecewise` is where equality and inequality are treated as boolean objects. `Eqn` and `Eq` should be strictly distinguished by their purposes, and too much implicit conversion makes everything very confusing in the end.
3. Yes. Since we are treating `Eqn` as a container, I think there is nothing strange to it.
4. Maybe `Eqn(*eq.args)` will suffice.
5. Every `Basic` should be allowed into `Eqn`. What to pass needs to be decided at user discretion.

**Comment by JSS95** [comment]
Any more opinion for this? We need more discussion, especially on the topics that @oscarbenjamin posted:

> 1. Do we want to make this the standard equation type that is used e.g. as recommended for passing equations to `solve`, `dsolve`, etc?
> 2. Would there be implicit conversions to allow this to be used in a boolean context such as when constructing a `Piecewise`?
> 3. Should this work with `subs` like `x.subs(Eqn(x, y))` or `x.subs([Eqn(x, y), Eqn(z, t)])`?
> 4. How would you convert from `Equality` to `Equation` and vice versa?
> 5. Should the types of objects that can appear on each side be limited e.g. to `Expr` or should it be possible to have any kind of object on each side of the `Equation`?

If no one is willing to join the discussion, I cannot but merge this PR with two more changes:

- allow solve functions to take `Equation`
- allow substitution by `Eqn`

**Comment by gutow** [comment]
>     * allow solve functions to take `Equation`

This one I believe is clear. We want solve to accept `Equation`. This is a simple adjustment. When Solve gets an `Equation` it adjusts it to `eq.lhs -eq.rhs` to make it an `Expr` equivalent to the equation to solve of `expr = 0`. I think we also want to output the results as a set of equations, but I am not sure there is agreement on how this last part should behave.
> 
>     * allow substitution by `Eqn`

I think the following part or this is clear `.subs(Eqn(a,b))` == `.subs({a:b})`. I am not sure how it should behave beyond that. It was also pointed out by @sylee957 in this comment https://github.com/sympy/SymPEPs/pull/1#discussion_r619603454, that we need to make sure it does not impinge on `.xreplace`.

**Comment by JSS95** [comment]
I made `subs` to take equation as argument. Modifying solve functions (`solve`, `dsolve`, `solveset`, ...) turned out to be a bit difficult which will make the diff large, so I decided to do it in another PR.

@oscarbenjamin @sylee957 @gutow please review this.

**Comment by JSS95** [comment]
I will wait for a few more days and merge this.

**Comment by oscarbenjamin** [comment]
I think this needs to reviewed properly by more people. Since there has been discussion on the mailing list I think that before this is merged a summary of what is actually done here, what was agreed, what is deferred etc should be sent to the mailing list.

**Comment by JSS95** [comment]
No review has been made for 2 weeks, so I think this can be merged now. Thanks @gutow and everyone else for participating!

**Comment by oscarbenjamin** [comment]
> No review has been made for 2 weeks, so I think this can be merged now.

Unless the changes are uncontroversial or inconsequential that is not how this works. There has been a lot of discussion on this issue in the past and there is a comment above clearly saying not to merge this without more review.

I'm not sure what I think about the changes here in general but one specific point that I object to is the introduction of a `sympy.equation` package: this does not warrant a top-level package. Another problem is that this seems to have almost no tests for the new class.

**Comment by oscarbenjamin** [comment]
> there is a comment above clearly saying not to merge this without more review.

Actually maybe that comment was not so clear. I do think that this needs to be considered more though because introducing a new class like this is the kind of thing that can lead to a lot of user confusion down the line.

This PR adds the new class with no documentation explaining what it is or why it is different from the other Equality class.

The way that this is structured indicates that you expect this to be part of a broader framework but I think that the whole plan needs to be explained somewhere before we embark on that.

**Comment by JSS95** [comment]
Okay. Not so hasty, then. I will revert this merge, add docs section and make a detailed wiki page.

**Comment by asmeurer** [comment]
@JSS95 It would be better to not squash commits from multiple authors together. Git it itself does not recognize the Co-authored-by flag, meaning things like our AUTHORS scripts will not recognize it. You also should generally avoid force-pushing to other people's branches without their permission. Squashing is not generally necessary unless it's to do something like remove an accidentally committed file.

**Comment by JSS95** [comment]
I forked gutow's branch and squashed with his permission, but didn't know that Git cannot recognize it.

**Comment by mgeier** [comment]
> It would be better to not squash commits from multiple authors together. Git it itself does not recognize the Co-authored-by flag, meaning things like our AUTHORS scripts will not recognize it.

However, it shouldn't be a problem to squash multiple commits of a *single* author.

Git stores separate "author" and "committer" information, so if squashing is done properly, the original "author" information will stay intact.

I'm sure there are several ways to do this with Git, the one that I can easily remember is to use `git rebase --interactive`, as I recommended in https://groups.google.com/g/sympy/c/GtrTGHaev4A/m/FNeLlBXLAwAJ.

**Comment by gutow** [comment]
> I forked gutow's branch and squashed with his permission, but didn't know that Git cannot recognize it.

If you fork from the latest version of my [minimal_eq branch](https://github.com/gutow/sympy/tree/minimal_eqn), I have done the work of untangling my commits and squashing them into a single commit. This is the current state of pull request https://github.com/sympy/sympy/pull/21333. I suggest starting there if you are trying to harmonize this implementation with the front-end behavior I have worked on.

I have just finished my semester and hope to be able to spend some time on this stuff now.

**Comment by asmeurer** [comment]
I didn't notice that this was your PR and not @gutow's, and it didn't look like he had given permission here.

**Comment by smichr** [comment]
This is a little confusing: this PR shows as merged but it is not in the master branch. I also saw a revert. So what is the github purpose of this PR with no merge button -- is it just like an issue page now? How would the changes get merged if there is no merge button?

**Comment by asmeurer** [comment]
I think we should start a new PR, with extended discussion. It wasn't really ready to merge yet.

**Comment by gutow** [comment]
@JSS95 can clarify this, but I believe the idea was to make the equation class use some of the mechanics of the assumptions module rather than work directly from core properties. The logic is that the equation type with an equals sign is just one type of relation. Figuring out how to do that may make it easier to develop an on-paper like interface for inequalities.

I think discussion and planning for this should either move to the SymPEP I started (https://github.com/sympy/SymPEPs/pull/1) or extend my pull request (https://github.com/sympy/sympy/pull/21333), which I believe has the minimal set of behaviors people have requested or said they expect. 

Ultimately, I do think that an equation should accept all the relational operators (=, > , <, =>, <=). Therefore combining these would be useful. However, it is unclear to me whether that should be done before or after the newer assumptions completely replaces the older version. The lack of clarity for me comes mostly from a lack of clarity on the roadmap and time frame for the switch.

**Pull request merged**
