### PR TITLE
Add a prec option to nsolve and change it to return Float and Matrix

### PR DESCRIPTION
**Pull request by asmeurer**
Just adding a prec option to nsolve without changing it to return Floats
doesn't seem like a very good idea, since mpmath has a global precision,
meaning we either don't reset it (bad), or we do reset it and the returned mpf
prints with less precision than what was asked (although the full precision
would be saved in the mpf itself).

It makes sense that nsolve, which is a SymPy wrapper around mpmath.findroot,
should return SymPy types. However, this is technically a backwards
incompatible change, so I'm unsure if it should be made, and if so, if we
should attempt some kind of deprecation (I don't know how to deprecate a
return type). The best I can think of would be to only return a Float if the
prec option is used, but that would be inconsistent and confusing.

This depends on #11862 but I'm submitting it separately as it might be
controversial, and I don't want it to block the fixes there.

### CODE REVIEW

**Comment by asmeurer** [comment]
CC @cbm755 @scopatz

**Comment by cbm755** [comment]
I remember finding it strange that `nsolve` didn't return a `Float`: that behaviour seems like a bug to me.  Something to be fixed, rather than something to deprecate.  Just my $0.02.

So this looks good to me.  :+1:

**Comment by scopatz** [comment]
This looks good to me! I approve.

**Comment by asmeurer** [comment]
@cbm755 thanks for the review.

I've pushed some more tests. I will merge once Travis passes.

**Comment by asmeurer** [comment]
You can always cast `Float` back to `mpf` if you really want it. The two should be interchangeable in most instances anyway. I've added this change to the [release notes](https://github.com/sympy/sympy/wiki/Release-Notes-for-1.1).

**Pull request merged**
