### PR TITLE
Code printing: Fix C-style comments: /* ... */

### PR DESCRIPTION
**Pull request by bjodah**
#### Brief description of what is fixed or changed
Use correct comment format in C printer (C++ style comments `//` are not universally supported).

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscargus** [comment]
LGTM!

**Comment by asmeurer** [comment]
What about C++? Another advantage of /* */ comments is that they support multiple lines.

**Comment by bjodah** [comment]
> And they can be inside of expressions.

Yes, I think that's another reason to prefer them. They are fully supported by C++.

**Comment by asmeurer** [comment]
I mean does the C++ printer also use them?

**Comment by bjodah** [comment]
I see, yes it does:
```python
In [6]: cxxcode(Comment("foobar"))
Out[6]: '/* foobar */'
```

**Pull request merged**
