### PR TITLE
[WIP] Explicit characteristic functions for some continuous distributions

### PR DESCRIPTION
**Pull request by ethankward**
Added explicit definitions for Beta, Cauchy, Chi, ChiNoncentral, ChiSquared, FDistribution, Gamma, GammaInverse, Gumbel, Laplace, Logistic, Pareto, RaisedCosine, Rayleigh, StudentT, Triangular, QuadraticU, UniformSum, VonMises, and WignerSemicircle.

I am struggling to formulate tests for this in a way that doesn't just repeat the formulas in the tests and implementation. One idea I had was to use mpmath to invert the Fourier transform and then compare the original PDF at sampled points. However it seems like mpmath performs very poorly on these types of integrals, for example:

    >>> from sympy import *
    >>> from sympy.stats import *
    >>> import mpmath
    >>> x = 3.0
    >>> D = ChiSquared('D', 1)
    >>> cf = characteristic_function(D)
    >>> n1 = N(density(D)(x))
    >>> n2 = mpmath.quad(lambda t: N(cf(t)*exp(I*t*x)), [-mpmath.inf, mpmath.inf]) / (2*mpmath.pi)
    >>> print(n1)
    0.0513934432679231
    >>> print(n2)
    -422170937.487966

### CODE REVIEW

**Comment by normalhuman** [comment]
Don't blame mpmath for wrong integral: `[-mpmath.inf, mpmath.inf]` should be `[0, 2*mpmath.pi]`

**Comment by normalhuman** [comment]
Maybe do the opposite: compute the CF numerically (integration against the pdf) and compare with the precomputed value?

**Comment by ethankward** [comment]
That's a little better. An example:
```
def test_precomputed_characteristic_functions():
    import mpmath

    def test_cf(dist, x, ll, ul):
        pdf = density(dist)
        cf1 = lambda t: N(characteristic_function(dist)(t))
        cf2 = lambda t: mpmath.quad(lambda x: N(pdf(x) * exp(I * t * x)), [ll, ul])

        n1 = cf1(x)
        n2 = cf2(x)
        assert abs(re(n1) - re(n2)) < 1e-6
        assert abs(im(n1) - im(n2)) < 1e-6

    test_cf(Beta('b', 1, 2), 5, 0, 1)
    test_cf(Chi('c', 3), 2.0, 0, mpmath.inf)
    test_cf(ChiSquared('c', 2), 2.5, 0, mpmath.inf)
    test_cf(Exponential('e', 6), 3, 0, mpmath.inf)
    test_cf(Logistic('l', 1, 2), 1.25, -mpmath.inf, mpmath.inf)
    test_cf(RaisedCosine('r', 3, 1), 2.5, 2, 4)
    test_cf(Rayleigh('r', 0.5), 1.5, 0, mpmath.inf)
    test_cf(WignerSemicircle('w', 3), -1, -3, 3)
    test_cf(UniformSum('u', 3), 2.25, 0, 3)
    test_cf(Normal('n', -1, 5), 1, -mpmath.inf, mpmath.inf)
    test_cf(Uniform('u', -1, 1), -0.5, -1, 1)
```
It's pretty slow though- this takes around 10 seconds on my computer.

**Comment by normalhuman** [comment]
10 seconds is not awful for testing multiple things at once. Try `method=’gauss-legendre’` in case it's faster than the default tanh-sinh.

**Comment by ethankward** [comment]
Not really satisfied with this, I will think about better tests.

**Pull request closed without merging**
