### PR TITLE
Remove redundant `.doit()` in `_matrix_derivative()`

### LINKED ISSUE #21195: Results diverge when use `diff` on a matrix or its elemetns
create a one-element matrix A as below:
```python
>>> from sympy import *
>>> t = symbols('t')
>>> x = Function('x')(t)
>>> dx = x.diff(t)
>>> A = Matrix([cos(x) + cos(x) * dx])
```
when use `diff` on matrix A:
```python
>>> (A.diff(x))[0,0]
-sin(x(t))
```
when use `diff` on the single element of A: 
```python
>>> A[0,0].diff(x)
-sin(x(t))*Derivative(x(t), t) - sin(x(t))
```
but if use `applyfunc` method on A, the result is the same as above:
```python
>>> A.applyfunc(lambda ij: ij.diff(x))[0,0]
-sin(x(t))*Derivative(x(t), t) - sin(x(t))
```
is this a bug or supposed behavior of matrix calculus?

### PR DESCRIPTION
**Pull request by akshanshbhatt**
#### References to other Issues or PRs

Fixes #21195 

#### Brief description of what is fixed or changed

In the derivative calculation of Matrix expressions, `doit()` in _matrix_derivative() made some of the terms vanish when carried out with respect to a variable belonging to `sympy.core.function.Function` class. Moreover, there was no significance of `doit()` in computing the derivative so I removed it.

#### Other comments

I have given a detailed explanation in the issue thread. 

#### Release Notes

* matrices
  * Fixed a bug that led to the wrong derivative result in matrix expressions.

### CODE REVIEW

**Comment by akshanshbhatt** [comment]
@Upabjojr please review

**Comment by moorepants** [comment]
Please add a unit test based on https://github.com/sympy/sympy/issues/21195.

**Comment by akshanshbhatt** [comment]
> Please add a unit test based on #21195.

@moorepants I have added a unit test based on the issue.

**Comment by moorepants** [comment]
This LGTM. @Upabjojr, maybe you want to sign off.

**Comment by Upabjojr** [comment]
> > Please add a unit test based on #21195.
> 
> @moorepants I have added a unit test based on the issue.

Unit tests are important... I am currently rewriting the matrix derivation algorithm (will still take some time before it's ready), so probably all those classes will be replaced in the future. It's important to have unit tests in order to prevent this bug from being inadvertently reintroduced.

This PR looks good to me.

**Pull request merged**
