### PR TITLE
Added macOS platform support for compilation module

### LINKED ISSUE #24058: Test failure for compilation utility in macOS 11 and 12
### Failure description

In the sympy test, utilities/_compilation/tests/test_compilation.py::test_compile_link_import_strings is FAILED in macOS.

```
FAILED utilities/_compilation/tests/test_compilation.py::test_compile_link_import_strings - FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/d_...
```

It can be reproduced by
```
py.test utilities/_compilation/tests/test_compilation.py
```
in macOS 11 and 12.

### Environments

The version of SymPy fails the test is `1.11.1` and `1.12.dev`(master branch)

The version of python is (as in macOS 12):
3.8.14(Homebrew) 
```
Python 3.8.14 (default, Sep  6 2022, 23:17:06)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
```

3.9.14(Homebrew)
```
Python 3.9.14 (main, Sep  6 2022, 23:16:16)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
```

3.9.6(XCode Command Line Tools)
```
Python 3.9.6 (default, Aug  5 2022, 15:21:02)
[Clang 14.0.0 (clang-1400.0.29.102)] on darwin
```

The OS version of macOS is:
```
Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
```

### PR DESCRIPTION
**Pull request by vxst**
#### References to other Issues or PRs

Fixes #24058

#### Brief description of what is fixed or changed

 * Write the linker configure block for darwin(macOS) platform
 * Using realpath instead of abspath to find the right path in macOS

#### Release Notes

* utilities
  * Added macOS platform support for compilation module

### CODE REVIEW

**Comment by vxst** [comment]
`Shan Chunqing` is my legal name, which I don't like that much. Please use `Jyn Spring 琴春 <me@vx.st>` for the mailmap. 

Sorry for the inconvenience.

**Comment by bjodah** [comment]
This looks good. I tried to browse our test results for a passing test of test_compilation.py, but I have a hard time navigating our test logs, and I don't see a search feature, does any one know in what configuration that test is being run? Is it one of the optional-dependencies runs? (I see wurlitzer being installed which I know is needed for some tests using the compilation module).

**Comment by vxst** [comment]
To my knowledge, NumPy, cython, pytest is required. And the CC, CXX, FC environment variables should be set to the right compiler, in macOS it can be done with xcode-select and brew install gcc.

GCC is used to provide gfortran, in the default settings, clang will be the default CC. Python needs to be installed with python-dev or python-devel package to provide the configparser.

typing_extensions is required if the python is really old.

**Comment by bjodah** [comment]
Sure, that sounds just about right. I was just hoping to be able to find a line indicating that the test is being run in one of our configurations here:
https://github.com/sympy/sympy/pull/24059/checks

**Comment by vxst** [comment]
Screen Shot 2022-09-15 at 17 08 25

**Comment by vxst** [comment]
It seems there is no test for macOS. Perhaps I can help with that in the future. Many mac users in my laboratory use isympy daily. It might be one of largest user base after Linux.

**Comment by bjodah** [comment]
@vxst thank you for clarifying, and thank you for the patch! A macOS CI job sounds like something useful, I'm not up to speed with what our current situation is there, but any help to improve things are of course much appreciated!

**Pull request merged**
