### PR TITLE
Fixes #11981

### LINKED ISSUE #11981: powsimp() fails with noncommutative variables
```python
import sympy as sp

x, y = sp.symbols('x, y', commutative=False)

v = (x*y)**2 * (y*x)**2
print(v)
print(sp.powsimp(v))
```

Output:

```
(x*y)**2*(y*x)**2
(x*y**2*x)**2
```

Needless to say, `xyxy yxyx != xyyx xyyx`.

The bug is apparently around [here](https://github.com/sympy/sympy/blob/master/sympy/simplify/powsimp.py#L384).

Possible fix: replace line 390 from

```python
if (e1 == e2 and e2.is_commutative):
```

to

```python
if (e1 == e2 and e2.is_commutative) and (not isinstance(b1, Mul) or not isinstance(b2, Mul)):
```

Is this the preferred way for testing whether an expression is a `Mul`?

### PR DESCRIPTION
**Pull request by mohit3011**
<If this pull request fixes an issue please indicate which issue by typing "Fixes #NNNN" below.>

### CODE REVIEW

**Comment by jksuom** [comment]
There is another pending PR #12008 on this issue. That will probably settle the issue.

BTW, for your next PR it is recommended to create a new branch with a name different from 'master' since that may lead to confusion.

**Comment by mohit3011** [comment]
Sorry I read your comment after the tests had been initiated . I am getting the same rror as #12008 got , If there is no problem then can you look into what is wrong in my PR.

**Comment by jksuom** [comment]
"File contains trailing whitespace: /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/sympy-1.0.1.dev0-py2.7.egg/sympy/simplify/tests/test_powsimp.py, line 297"

This is from the Travis CI log https://travis-ci.org/sympy/sympy/jobs/188216580,

You can catch such errors before pushing to GitHub by running `bin/test quality`.

**Comment by mohit3011** [comment]
Thank you very much for guiding me.

**Pull request closed without merging**
