### PR TITLE
Fix float values not rounding correctly.

### LINKED ISSUE #12056: round for Float loses precision
The `__round__` method on `Float` uses `float`, which causes it to lose precision.

### PR DESCRIPTION
**Pull request by barun511**
<!-- If this pull request fixes an issue please indicate which issue by typing "Fixes #NNNN" below.>
Fixes #12056 by manually rounding when greater precision is required.

### CODE REVIEW

**Comment by asmeurer** [comment]
Can you add some tests?

**Comment by asmeurer** [comment]
`round` should do round to even behavior. You could remove the float special case and use that to test it against `float` for normal precision floats.

**Comment by barun511** [comment]
Correct me if I'm wrong, round to even behaviour means the last digit
should be even?

I'll add some tests. Also note that this patch doesn't work for negative
numbers. I'll update that as well.

On Jan 21, 2017 8:30 AM, "Aaron Meurer" <notifications@github.com> wrote:

round should do round to even behavior. You could remove the float special
case and use that to test it against float for normal precision floats.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sympy/sympy/pull/12076#issuecomment-274228866>, or mute
the thread

**Comment by barun511** [comment]
I.e. round to even is what I know as bankers rounding.

**Comment by barun511** [comment]
I'm not entirely sure how to test this.. since == is not reliable for float values. Any ideas?

**Pull request closed without merging**
