### PR TITLE
New debug function with lazy formatting

### PR DESCRIPTION
**Pull request by hanspi42**
#### References to other Issues or PRs
Part of #24561 

#### Brief description of what is fixed or changed
Introduced a new debug function, `debugf`, that can print `str%args`, but will only do the formatting if debugging is switched on. Inserted it in all places where I found a `debug(str % args)` in the code base. This does not make any functional changes, it just saves computation power.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by hanspi42** [comment]
@sylee957: If you have a bit of time, this PR is a very short one to review.

**Comment by sylee957** [comment]
I thought that `debug("str", a, b, c)` should already be lazy though.

**Comment by sylee957** [comment]
Eventually, I think that debug should be removed because they have messy format.

**Comment by hanspi42** [comment]
> Eventually, I think that debug should be removed because they have messy format.

I agree, but since this is mainly for debugging purposes, it may not have a very high priority.

**Pull request merged**
