### PR TITLE
Remove rubi

### PR DESCRIPTION
**Pull request by eagleoflqj**
#### References to other Issues or PRs

#24310
#### Brief description of what is fixed or changed

I moved rubi to https://github.com/sympy/rubi, so clean up stuff here.
#### Release Notes

* integrals
  * The broken rubi package is removed.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
CC @Upabjojr

**Comment by oscarbenjamin** [comment]
> I moved rubi to https://github.com/sympy/rubi, so clean up stuff here.

We should add something to the README that at least shows how to use the code in the repo to do something.

I guess it is supposed to be used like this:
```python
In [5]: from sympy import symbols

In [6]: x = symbols('x')

In [7]: from rubi.rubimain import rubi_integrate

In [8]: rubi_integrate(x, x)
```
I haven't waited for `rubi_integrate` to finish though so I don't know if this actually works.

**Comment by Upabjojr** [comment]
> I haven't waited for `rubi_integrate` to finish though so I don't know if this actually works.

We need another GSoC to continue the Rubi project, unfortunately it currently takes a lot of time to load (well, IIRC it takes less than an hour).

We have now a new Mathematica parser, so maybe we could use Rubi's source code as input.

**Comment by oscarbenjamin** [comment]
Does anyone object to this PR?

**Comment by asmeurer** [comment]
No objections from me.

**Comment by eagleoflqj** [comment]
> We have now a new Mathematica parser, so maybe we could use Rubi's source code as input.

Good idea, I hope to spend some time on it.

**Comment by oscargus** [comment]
This is not moved with history, right? It may be worthwhile trying to do that (I gave it a try some time ago, but didn't succeed).

**Comment by asmeurer** [comment]
You can do it with filter-branch. See https://stackoverflow.com/questions/41811986/git-move-directory-to-another-repository-while-keeping-the-history

**Comment by samithkavishke** [comment]
@asmeurer Is this [sympy.rubi](https://github.com/sympy/rubi) in production I cannot see any where someone use this?

**Comment by samithkavishke** [comment]
Even though Rubi moved to another repository, its importing directories hasn't change. There might be other places that has the same issue .

**Pull request merged**
