### PR TITLE
correct doc

### LINKED ISSUE #24342: correct documentation for `interpolating_spline`
The documentation says, about the `y` values: "list of strictly increasing integer values". This must have been a copy and paste error. While the `x` values must be strictly increasing, the `y` values need not be so. In fact, the first example shows a case where they are not and the second examples shows where there are repeated values. The `y` values are simply the `y` values for the corresponding `x` values. In addition, it does not appear that `x` or `y` values must be integers.

### PR DESCRIPTION
**Pull request by KenanHanke**
Resolves #24342

### CODE REVIEW

**Comment by smichr** [comment]
You will need to add your name to the authors (see error message).

**Comment by Ishanned** [comment]
You have to add them in .mailmap file
refer https://github.com/sympy/sympy/wiki/Development-workflow#add-your-name-and-email-address-to-the-mailmap-file

**Comment by k-hanke** [comment]
I added myself to the .mailmap file and don't understand why the tests aren't working

**Comment by smichr** [comment]
> I added myself to the .mailmap file and don't understand why the tests aren't working

test says:
```
The mailmap file was reordered

For instructions on updating the .mailmap file see:
https://github.com/sympy/sympy/wiki/Development-workflow#add-your-name-and-email-address-to-the-mailmap-file
```

**Comment by Ishanned** [comment]
Run `$ python bin/mailmap_check.py` on your local machine, then make a commit

**Pull request closed without merging**
