### PR TITLE
About letting sympy could be used in paddle.

### PR DESCRIPTION
**Pull request by KRISWIU**
#### Brief description of what is fixed or changed
Let sympy could be used in paddle

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
What is paddle?

**Comment by ThePauliPrinciple** [comment]
Looks like the python pabble package is an interface to: https://developer.paddle.com/api-reference/intro

**Comment by oscarbenjamin** [comment]
Why should this be supported and what does it even mean to support this?

**Comment by KRISWIU** [comment]
> What is paddle?

PaddlePaddle (PArallel Distributed Deep LEarning) is an efficient, flexible, and extensible deep learning framework, commits to making the innovation and application of deep learning technology easier.
Here is the website. https://www.paddlepaddle.org.cn/documentation/docs/en/api/index_en.html

**Comment by KRISWIU** [comment]
> Why should this be supported and what does it even mean to support this?

Our team is trying to use sympy for the symbolic representing PDE. And sympy now could be used in tensorflow, paddle is also a DL framework. Sympy is important since with out it, it is hard for user to write their equation ( hard code is hard to write and understand).

**Comment by oscarbenjamin** [comment]
I'm sorry I still don't understand what this PR is for. Please take the time to make clear what this PR is useful for.

**Comment by KRISWIU** [comment]
Oh my bad. I mean that sympy is a good approach for represent pde symbolized which could make user clear for relate the equation and the function. So if sympy could be used in paddle, it is really a big help for us . For example, d/dt (u(x, t)) could be write as D(u(x, t), t)) directly and clear, but without sympy it is hard for user to see this differentiation straight forward.

**Comment by asmeurer** [comment]
Does this PR work as written? Can you show an example of it?

**Comment by eagleoflqj** [comment]
If you want lambdify to work with paddle, you should reference how tensorflow is supported. At least there should be a `sympy/printing/paddle.py` that implements `PaddlePrinter`. I saw you committed a dummy `paddle.py` and deleted it. As that version doesn't work, I'd close this PR. Feel free to reopen when you commit a complete `paddle.py` and update CI to test it.

**Pull request closed without merging**
