### PR TITLE
pretty : vector printing doesnot break now 

### LINKED ISSUE #12675: vectors break pretty printing
```py
In [1]: from sympy.vector import *

In [2]: e = CoordSysCartesian('e')

In [3]: (x/y)**t*e.j
Out[3]:
⎛   t⎞ e_j
⎜⎛x⎞ e_j ⎟
⎜⎜─⎟ ⎟
⎝⎝y⎠ ⎠
```

Also, when it does print correctly, the baseline is wrong (it should be centered).

### PR DESCRIPTION
**Pull request by jashan498**
Fixes #12675

#### Brief description of what is fixed or changed
The only deleted line made every right parenthesis to get replaced, which was making `e_j` to appear twice. Now the loop takes care of that only editing the outermost right parenthesis in the vector. 
```
>>> pprint((x/y)**t*e.j)
⎛   t⎞ e_j
⎜⎛x⎞ ⎟    
⎜⎜─⎟ ⎟    
⎝⎝y⎠ ⎠  
```

#### Other comments
I tried making `e_j`  print near baseline( by replacing `⎟` instead of `⎞`) but idk the code ahead omits `e_j` (maybe because in normal case no newline character would be expected like in `(x) e_j` ). So I thought it would be better to print like this only.

What do you say @asmeurer @smichr ?

### CODE REVIEW

**Comment by moorepants** [comment]
LGTM

**Comment by gxyd** [comment]
May be I don't completely understand. See code samples below:
```python
In [18]: (x/y)**t*2
Out[18]: 
     t
  ⎛x⎞ 
2⋅⎜─⎟ 
  ⎝y⎠ 

In [19]: ((x/y)**t)*e.i
Out[19]: 
⎛   t⎞ e_i
⎜⎛x⎞ ⎟    
⎜⎜─⎟ ⎟    
⎝⎝y⎠ ⎠    

```
So I was expecting [19] to print the same way as [18] did with `2`.

**Comment by moorepants** [comment]
Hmm, the `e_i` should be centered vertically, no?

**Comment by gxyd** [comment]
Yes, I think that would be right. Thanks for wording that properly, I just gave code sample.

**Comment by jashan498** [comment]
I think @gxyd is right, it was bit confusing. Now:
```
>>> pprint((x/y)**t*e.j)
⎛   t⎞    
⎜⎛x⎞ ⎟ e_j
⎜⎜─⎟ ⎟    
⎝⎝y⎠ ⎠    
```
@moorepants feel free to take the previous commit if that is more appropriate.

**Comment by jashan498** [comment]
Added few more comments too, so that it would be easier for others to understand the changed code.

**Comment by jashan498** [comment]
ping @moorepants

**Comment by Abdullahjavednesar** [comment]
@moorepants, @gxyd anyone available can review this, thanks!

**Comment by jashan498** [comment]
Also Fixes #13039

**Pull request merged**
