### PR TITLE
Remove default `printer=None` arguments from `_latex` and `_pretty`

### PR DESCRIPTION
**Pull request by eric-wieser**
These are API hooks, and the hooks guarantee the arguments will always be provided.

Since this argument is never `None`, there is no need for the code that tried to handle the case when it was.

#### References to other Issues or PRs

Split from #19621

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by eric-wieser** [comment]
Close/reopen to pull in changes to test splits which should prevent timeouts.

@Abdullahjavednesar, perhaps a `printing` label would make sense here too.

**Comment by eric-wieser** [comment]
CI failure was a network issue

**Comment by oscarbenjamin** [comment]
Is it sympy or other libraries that use these API hooks?

**Comment by eric-wieser** [comment]
Sympy uses them itself inside `sympy.printing.printer.Printer._print`

**Comment by oscarbenjamin** [comment]
They aren't used by e.g. ipython or something?

**Comment by eric-wieser** [comment]
Nope, IPython uses `_repr_latex_`. `_latex`, `_sympystr`, and `_pretty` are designed to be for sympy only.

**Comment by oscarbenjamin** [comment]
Okay, looks good

**Comment by oscarbenjamin** [comment]
Thanks

**Pull request merged**
