### PR TITLE
modifying accessibility of S.Reals and S.Complexes

### LINKED ISSUE #11378: S.Reals should be accessible as just "Reals"
I think it's confusing that things like S.Reals are only accessible from the S object. We should just import `Reals` into the namespace. Personally I would also avoid using `S` outside of library code (i.e., don't use it in the docs), as I think the fact that things are singletonized is an implementation detail that most users shouldn't care about. 

I think there can be some issues if we use the same name for the class and the instance, but we already do it for [a few items](https://github.com/sympy/sympy/blob/39c6a9e42356d1afd6d8eb8a056e77ebfff6e5d4/sympy/core/__init__.py#L32-L34).

I believe this is just a matter of adding the set objects to that `__init__.py` file.

### PR DESCRIPTION
**Pull request by ashishkg0022**
`S.Reals` and `S.Complexes`  are now accessed as `Reals` and `Complexes` respectively as needed by #11378 
Used Commits from #11383 and #11686  
```
>>> from sympy import solveset, S
>>> from sympy.abc import x
>>> solveset(x**2 + 1, x, domain = Complexes)
{-I, I}
>>> solveset(x**2 + 1, x, domain = Reals)
EmptySet()
```
Fixes #11378

### CODE REVIEW

**Comment by ashishkg0022** [comment]
@asmeurer now it works without any build error.

**Comment by ashishkg0022** [comment]
ping @asmeurer

**Comment by ashishkg0022** [comment]
@jksuom  can you please reveiw it .

**Comment by smichr** [comment]
Looks good. Thanks for finishing this up.

**Pull request merged**
