### PR TITLE
sympy.simplify.radsimp.collect rectified to give correct results

### LINKED ISSUE #15394: collect() incorrect on fractional equations
Calling collect() on a equation with a fraction and more than one term does not collect the terms within the fraction. Below is a example of collect() working on a equation with a fraction, and then not working when a term is added to the equation.
```
>>> import sympy
>>> x, y = sympy.symbols('x y')
>>> equation = 1/(x*y + x)
>>> #correct output
>>> equation.collect(x)
1/(x*(y + 1))
>>> equation = 1 + 1/(x*y + x)
>>> #incorrect output, expected 1 + 1/(x*(y + 1))
>>> equation.collect(x)
1 + 1/(x*y + x)
>>> import platform; platform.python_version()
'3.6.5'
>>> sympy.__version__
'1.3'
```

### PR DESCRIPTION
**Pull request by czgdp1807**
Fixes #15394 

collect method has been modified by adding a condition for expressions
which have is_Add = True. A test has also been added in
sympy.simplify.tests.test_radsimp

* simplify
  * collect method modified to give correct results for expressions belonging to Add class

### CODE REVIEW

**Comment by smichr** [comment]
What happens with `1/z + 1/(x+x*y)`?

**Comment by czgdp1807** [comment]
Before introducing my modification the collect method gave,  `1/(x*y + x) + 1/z` for `(1/z + 1/(x + x*y)).collect(x)`.
After introducing my modification the collect method gave, `1/z + 1/(x*(y + 1))` for  `(1/z + 1/(x + x*y)).collect(x)`.

**Comment by asmeurer** [comment]
Use ` around code in GitHub comments do it doesn't render the multiplications as italics.

**Comment by czgdp1807** [comment]
@smichr I tried `factor_terms` on `eq = 1/f(x) + 1/f(x)*diff(f(x), x) + x*diff(f(x), x)/f(x)` for preprocessing. Then applied eq.collect(f(x).diff(x)). It gave, `((x + 1)*Derivative(f(x), x) + 1)/f(x)`. The expected result is, `(1/f(x) + x/f(x))*Derivative(f(x), x) + 1/f(x)`. It seems my modifications are different from what factor_terms does.

**Comment by smichr** [comment]
I'm not sure this should be happening. This is a recursive step that applies `collect` to the arguments of terms whereas the docstring says "Collect additive terms of an expression." Also, for the expression that you cite in the previous comment, it looks like `collect` already does what you wanted (at least in the version at sympy.live.org):
```
>>> collect(1/f(x) + 1/f(x)*diff(f(x), x) + x*diff(f(x), x)/f(x),f(x).diff(x))
(x/f(x) + 1/f(x))*Derivative(f(x), x) + 1/f(x)
```

On the other hand, if someone doesn't want this behavior they can use the `radsimp` version.

Does `collect(1+1/(x+x/(x+x*y)), x)` now become `1+1/(x*(1+1/(x*(1 + y))))`?

Should this be controlled with a keyword `rational` or maybe `recursive` where, instead of looking out only for `Add`, `collect` is applied to the args of an expression and then applied to the resulting expression if it is an `Add` so `collect(cos(x+x*y), x, recursive=True)`->`cos(x*(1+y))`?

**Comment by smichr** [comment]
I envision the following which only applies the recursive step when explicitly told to or when the input is an Add; the case for `1/(x+x*y)` already recurses into the denominator so I think that allowing it to process args of an Add (as you had done in this PR) is not too far afield.

What do you think?

```
def collect(self, syms, func=None, evaluate=True, exact=False, distribute_order_term=True, recursive=False):
        """See the collect function in sympy.simplify"""
        from sympy.simplify import collect as _collect
        if not self.args:
            return self
        s = self
        deep = recursive
        if recursive or s.is_Add:
            args = [collect(a, syms, func, evaluate, exact, distribute_order_term, deep)
                for a in args]
            s = self.func(*args)
        return _collect(s, syms, func, evaluate, exact, distribute_order_term)
```

**Comment by czgdp1807** [comment]
I think your code is more generalized and less prone to conceptual errors. I have removed a few bugs from the code you provided. If you find the below code correct, then I will make changes in this PR.
` def collect(self, syms, func=None, evaluate=True, exact=False, distribute_order_term=True, recursive = False):
        """See the collect function in sympy.simplify"""
        from sympy.simplify import collect
        if not self.args:
            return self
        s = self
        if recursive or s.is_Add:
            new_args = [collect(a, syms, func, evaluate, exact, distribute_order_term) for a in self.args]
            s = self.func(*new_args)
        return collect(s, syms, func, evaluate, exact, distribute_order_term)`

**Comment by smichr** [comment]
`args` or `new_args` doesn't matter to me; either is fine.

`deep` is passed because maybe one doesn't want to recurse past an Add. So if recurse is False but you are dealing with an Add then nested Adds will be collected but args of functions, for example, won't be.

If you don't pass `deep` in the loop call to collect then recursion will stop after one level.

These are not tested but indicate my intention:
```
assert collect(cos(x + x*cos(x + x*y)), x, recursive=True) == cos(x*(1 + cos(x*(1 + y))))
eq = collect(1/x + 1/(x + x*y/(x + x*y)), x)
assert collect(eq, x) == 1/x*(1 + 1/(x*(1+y/(x*(1 + y)))))
eq = eq.subs(y, cos(x + x*y))
assert list(collect(eq, x).atoms(cos))[0].args[0] == x + x*y
assert list(collect(eq, x, recursive=True).atoms(cos))[0].args[0] == x*(1 + y)
```

**Comment by czgdp1807** [comment]
I got your point. I understood the cause of the bug. Finally, I suggest only one change in the code, which is given below.
`args = [a.collect(syms, func, evaluate, exact, distribute_order_term, deep) for a in args]`
For recursion, `a.collect` works, otherwise, `collect(a, ...)` calls the `simplify` version.
Please give your views.

**Comment by smichr** [comment]
> Please give your views.

I imported (in the code snippet) the `simplify` version as `_collect` to disambiguate the two.

**Comment by czgdp1807** [comment]
I used your code snippet for collect and executed the following code,

```
from sympy import *
x, y = symbols('x y')
eq = x + 1/(x*y + x)
eq.collect(x)
```
Below is the `Traceback`
```
Traceback (most recent call last):
  File "/home/gagandeep/sympy_debug.py", line 4, in <module>
    eq.collect(x)
  File "/home/gagandeep/sympy/sympy/core/expr.py", line 3214, in collect
    args = [collect(a, syms, func, evaluate, exact, distribute_order_term, deep) for a in args]
UnboundLocalError: local variable 'args' referenced before assignment

```

Then I made correction by using `self.args` instead `args`.
Then the code resulted in the following `Traceback`,

```
Traceback (most recent call last):
  File "/home/gagandeep/sympy_debug.py", line 4, in <module>
    eq.collect(x)
  File "/home/gagandeep/sympy/sympy/core/expr.py", line 3214, in collect
    args = [collect(a, syms, func, evaluate, exact, distribute_order_term, deep) for a in self.args]
  File "/home/gagandeep/sympy/sympy/core/expr.py", line 3214, in <listcomp>
    args = [collect(a, syms, func, evaluate, exact, distribute_order_term, deep) for a in self.args]
NameError: name 'collect' is not defined

```

However, on using `a.collect` instead `collect(a, ...)`, resulted in successful execution. 
Please guide me on how should I proceed.

**Comment by smichr** [comment]
ahh...`for a in args` should be `for a in s.args`

**Comment by smichr** [comment]
What about just making the change in radsimp's collect and not changing Expr's version:
```diff
diff --git a/sympy/simplify/radsimp.py b/sympy/simplify/radsimp.py
index 028d3a1..6183780 100644
--- a/sympy/simplify/radsimp.py
+++ b/sympy/simplify/radsimp.py
@@ -325,7 +325,12 @@ def parse_expression(terms, pattern):
             return [_f for _f in terms if _f], elems, common_expo, has_deriv

     if evaluate:
-        if expr.is_Mul:
+        if expr.is_Add:
+            o = expr.getO() or 0
+            expr = expr.func(*[
+                collect(a, syms, func, True, exact, distribute_order_term)
+                for a in expr.args if a != o]) + o
+        elif expr.is_Mul:
             return expr.func(*[
                 collect(term, syms, func, True, exact, distribute_order_term)
                 for term in expr.args])
diff --git a/sympy/simplify/tests/test_radsimp.py b/sympy/simplify/tests/test_ra
dsimp.py
index dd8bc90..fe971ad 100644
--- a/sympy/simplify/tests/test_radsimp.py
+++ b/sympy/simplify/tests/test_radsimp.py
@@ -239,6 +239,8 @@ def test_collect_D():
         (x*f(x) + f(x))*D(f(x), x) + f(x)
     assert collect(1/f(x) + 1/f(x)*diff(f(x), x) + x*diff(f(x), x)/f(x), f(x).d
iff(x), exact=True) == \
         (1/f(x) + x/f(x))*D(f(x), x) + 1/f(x)
+    e = (1 + x*fx + fx)/f(x)
+    assert collect(e.expand(), fx) == fx*(x/f(x) + 1/f(x)) + 1/f(x)


 def test_collect_func():
@@ -288,14 +290,6 @@ def test_rcollect():
     assert rcollect(sqrt(-((x + 1)*(y + 1))), z) == sqrt(-((x + 1)*(y + 1)))


-@XFAIL
-def test_collect_issues():
-    D = Derivative
-    f = Function('f')
-    e = (1 + x*D(f(x), x) + D(f(x), x))/f(x)
-    assert collect(e.expand(), f(x).diff(x)) != e
-
-
 def test_collect_D_0():
     D = Derivative
     f = Function('f')
```

**Comment by czgdp1807** [comment]
That would be much better, since a user can directly use `collect` method of `radsimp.py`. If we solve the issue there, then the problem will be eradicated from the root. 
So can I change this PR by modifying the code according to the discussion held so far?

**Comment by czgdp1807** [comment]
@smichr I have changed the PR. Thanks for the suggestions you gave in your last comment. :-)

**Comment by smichr** [comment]
Looks good.

**Pull request merged**
