### PR TITLE
Updated heurisch_wrapper to avoid None object

### LINKED ISSUE #14613: integration fails in creation of piecewise result
```
In [17]: b,c,p,m,n=symbols('b,c,p,m,n')
In [18]: integrate((c*x)**m*(b*x**n)**p,x)
...
/usr/lib/python3.4/site-packages/sympy-1.1.2.dev0-py3.4.egg/sympy/integrals/heurisch.py in heurisch_wrapper(f, x, rewrite, hints, mappings, retries, degree_offset, unnecessary_permutations)
    177                               degree_offset, unnecessary_permutations),
    178                               True))
--> 179     return Piecewise(*pairs)
    180 
    181 class BesselTable(object):

/usr/lib/python3.4/site-packages/sympy-1.1.2.dev0-py3.4.egg/sympy/functions/elementary/piecewise.py in __new__(cls, *args, **options)
    125         for ec in args:
    126             # ec could be a ExprCondPair or a tuple
--> 127             pair = ExprCondPair(*getattr(ec, 'args', ec))
    128             cond = pair.cond
    129             if cond is false:

/usr/lib/python3.4/site-packages/sympy-1.1.2.dev0-py3.4.egg/sympy/functions/elementary/piecewise.py in __new__(cls, expr, cond)
     21 
     22     def __new__(cls, expr, cond):
---> 23         expr = as_Basic(expr)
     24         if cond == True:
     25             return Tuple.__new__(cls, expr, true)

/usr/lib/python3.4/site-packages/sympy-1.1.2.dev0-py3.4.egg/sympy/core/basic.py in as_Basic(expr)
     24         raise TypeError(
     25             'Argument must be a Basic object, not `%s`' % func_name(
---> 26             expr))
     27 
     28 

TypeError: Argument must be a Basic object, not `NoneType`
```

### LINKED ISSUE #18140: TypeError from integrate using sympy 1.5
I do not know if this is known issue. If it is, please feel free to close this.

```
(base) >python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.5'
>>> from sympy import *
>>> from sympy.abc import a,x,n
>>> integrate((x**n)-ln(x),x)
-x*log(x) + x + Piecewise((x**(n + 1)/(n + 1), Ne(n, -1)), (log(x), True))
>>> integrate((x**n)*ln(x),x)
Traceback (most recent call last):
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 22, in as_Basic
    return _sympify(expr)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/core/sympify.py", line 418, in _sympify
    return sympify(a, strict=True)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/core/sympify.py", line 286, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1522, in integrate
    return integral.doit(**doit_flags)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 576, in doit
    function, xab[0], **eval_kwargs)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1032, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 188, in heurisch_wrapper
    return Piecewise(*pairs)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/functions/elementary/piecewise.py", line 130, in __new__
    pair = ExprCondPair(*getattr(ec, 'args', ec))
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/functions/elementary/piecewise.py", line 22, in __new__
    expr = as_Basic(expr)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 26, in as_Basic
    expr))
TypeError: Argument must be a Basic object, not `NoneType`
>>>

```
It does not like `x**n`. Changing it to `x**2`, the error goes away

```
>>> integrate((x**2)*ln(x),x)
x**3*log(x)/3 - x**3/9

```

Here is another one that gives same TypeError, I am assuming it is related to same cause. If not, feel free to make it separate issue.

```
>>> integrate(1/(cos(x)+sin(x)),x)
Traceback (most recent call last):
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/matrices/dense.py", line 198, in _eval_matrix_mul
    new_mat[i] = Add(*vec)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/matrices/dense.py", line 196, in <genexpr>
    vec = (mat[a]*other_mat[b] for a,b in zip(row_indices, col_indices))
TypeError: unsupported operand type(s) for *: 'Expression' and 'PolyElement'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1522, in integrate
    return integral.doit(**doit_flags)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 576, in doit
    function, xab[0], **eval_kwargs)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1032, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 136, in heurisch_wrapper
    unnecessary_permutations, _try_heurisch)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 735, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 735, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 489, in heurisch
    unnecessary_permutations=unnecessary_permutations)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 721, in heurisch
    solution = _integrate()
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 709, in _integrate
    solution = solve_lin_sys(numer.coeffs(), coeff_ring, _raw=False)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/polys/solvers.py", line 60, in solve_lin_sys
    v = (echelon[i, p + 1:]*vect)[0]
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/core/decorators.py", line 129, in binary_op_wrapper
    return func(self, other)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/matrices/common.py", line 2205, in __mul__
    return self._eval_matrix_mul(other)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/matrices/dense.py", line 206, in _eval_matrix_mul
    new_mat[i] = reduce(lambda a,b: a + b, vec)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/matrices/dense.py", line 205, in <genexpr>
    vec = (mat[a]*other_mat[b] for a,b in zip(row_indices, col_indices))
TypeError: unsupported operand type(s) for *: 'Expression' and 'PolyElement'
>>>

```
Thank you
--Nasser

### PR DESCRIPTION
**Pull request by risubaba**
In `heurish_wrapper()` evaluate `expr` again using `integrate()` if `heurisch()` returns `None`

#### References to other Issues or PRs

Fixes #14613
Fixes partially #15213
Fixes #18140

#### Brief description of what is fixed or changed
The following output is produced :
```
In [5]: integrate(x**n*log(x),x)
Out[5]: 
⎧     n             n                  n                
⎪n⋅x⋅x ⋅log(x)   x⋅x ⋅log(x)        x⋅x                 
⎪───────────── + ──────────── - ────────────  for n ≠ -1
⎪  2              2              2                      
⎪ n  + 2⋅n + 1   n  + 2⋅n + 1   n  + 2⋅n + 1            
⎨                                                       
⎪                     2                                 
⎪                  log (x)                              
⎪                  ───────                    otherwise 
⎪                     2                                 
⎩                                                
```

#### Release Notes

* integrals
  * Added extra step to evaluate integral if `heurisch()` returns `None` in `heurisch_wrapper()`

### CODE REVIEW

**Comment by risubaba** [comment]
@czgdp1807 what is the process of reviewing? Do i need to ask someone to do the same?

**Comment by jksuom** [comment]
Can you add a test for #14613. It looks like `f.subs(sub_dict)` should be simplified (when `heurisch` returns `None`). I would first try `.expand()`, and then the full `.simplify()` if that does not suffice.

**Comment by risubaba** [comment]
Just tried but neither help give the desired output

**Comment by risubaba** [comment]
```
In [21]: simplify(x**(a*b))==simplify((x**a)**b)
                                                      
Out[21]: False

```
This shouldn't happen right?

**Comment by jksuom** [comment]
I think that we can define `p = symbols('p', integer=True)` for the test of https://github.com/sympy/sympy/issues/14613. See https://docs.sympy.org/latest/tutorial/simplification.html#powers 3.

**Comment by risubaba** [comment]
OK i will soon add another test for #14613. Is there anything else that needs to be done?

**Comment by jksuom** [comment]
I think this is enough for one PR. More work is needed for #15213. This will remove the error but the result is not satisfactory. That can be handled in another PR. I have edited the OP to not close the issue.

**Comment by risubaba** [comment]
It is taking too long to evaluate the integral if we define p to be an integer @jksuom

**Comment by jksuom** [comment]
It takes a long time with a generic `p` as well. Is there a big difference?

**Comment by jksuom** [comment]
I see that it really takes a very long time with integral `p`. So we have to be satisfied with the generic `p` for the test. (The reason for the long time should be investigated but that is another issue.)

**Comment by risubaba** [comment]
Yep , it is taking around 7 minutes to calculate with integer `p` . Should i still add a test?

**Comment by jksuom** [comment]
> Should i still add a test?

Maybe that is not necessary. The test would probably have to be `@slow` and the result does not look nice. But can you open another issue on this timing problem after the original is closed.

I'll merge this now. Thank you for your contribution.

**Pull request merged**
