### PR TITLE
Fixed two issues pointed out related to #14933

### LINKED ISSUE #14933: RecursionError with Piecewise.xreplace containing Indexed objects
Minimal example to reproduce the issue:

```python
from sympy import Piecewise, Symbol, ITE, MatrixSymbol

x = Symbol('x')
y = Symbol('y')

inp = MatrixSymbol('inp', 1, 1)
rep_dict = {y: inp[0, 0], x: inp[0, 0]}

p = Piecewise((1, ITE(y > 0, x < 0, True)))
z = p.xreplace(rep_dict)
```

```
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-44-46c498a48320> in <module>()
----> 1 z = p.xreplace(rep_dict)
      2 print(z)

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/core/basic.py in xreplace(self, rule)
   1113 
   1114         """
-> 1115         value, _ = self._xreplace(rule)
   1116         return value
   1117 

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1134             args = tuple(args)
   1135             if changed:
-> 1136                 return self.func(*args), True
   1137         return self, False
   1138 

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/functions/elementary/piecewise.py in __new__(cls, *args, **options)
    134 
    135         if options.pop('evaluate', True):
--> 136             r = cls.eval(*newargs)
    137         else:
    138             r = None

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/functions/elementary/piecewise.py in eval(cls, *_args)
    183                     x = free.pop()
    184                     try:
--> 185                         c = c.as_set().as_relational(x)
    186                     except NotImplementedError:
    187                         pass

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/logic/boolalg.py in as_set(self)
    144             reps = {}
    145             for r in self.atoms(Relational):
--> 146                 if periodicity(r, x) not in (0, None):
    147                     s = r._eval_as_set()
    148                     if s in (S.EmptySet, S.UniversalSet, S.Reals):

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/calculus/util.py in periodicity(f, symbol, check)
    471     elif period is None:
    472         from sympy.solvers.decompogen import compogen
--> 473         g_s = decompogen(f, symbol)
    474         num_of_gs = len(g_s)
    475         if num_of_gs > 1:

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59 

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59 

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59 

... last 3 frames repeated, from the frame below ...

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59 

RecursionError: maximum recursion depth exceeded
```

Note that this will occur even if you pass `evaluate=False` to `Piecewise`.
This may be related to #14899

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Fixes #14933

#### Brief description of what is fixed or changed
Two of the three points in https://github.com/sympy/sympy/issues/14933#issuecomment-925300998 are fixed here. This avoids the error in #14933 if nothing else, but it may still be slower than before. 

#### Other comments
This is independent of #22152.

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
> but it may still be slower that before.

Why might anything be slower as a result of the changes here?

**Comment by smichr** [comment]
The tests pass when the changes to rv are *not* made.

**Comment by oscargus** [comment]
> Why might anything be slower as a result of the changes here?

I understood that things became slower in 1.9 compared to earlier versions, and this doesn't fix that. But I might have missed the point.

**Comment by oscargus** [comment]
> The tests pass when the changes to rv are _not_ made.

I'm quite sure I got some error making me try those changes.

**Comment by oscargus** [comment]
I've reverted those changes now. If I recall correctly, the `is_random` check for a matrix with a stochastic process as an element will fail.

**Comment by smichr** [comment]
> I understood that things became slower in 1.9 compared to earlier versions

There are two issue: recursion and slow-down. This is only fixing recursion by allowing it to pass through but avoid the recursion by now getting a NotImplementedError when trying to make the set.

**Comment by oscargus** [comment]
> There are two issue: recursion and slow-down.

That is what I understood. Thanks for confirming. So the comment was about not solving the slow-down.

**Comment by smichr** [comment]
There are probably lots of functions that need to be guarded with a check for NumberKind symbols. But this is at least one. I think this is better than what I had proposed and removed those changes from #22152.

**Comment by oscarbenjamin** [comment]
I guess we need this for the 1.9 branch as well.

@richardotis @bocklund can you check that this works?

**Pull request merged**
