### PR TITLE
Redefinition of Rootof

### PR DESCRIPTION
**Pull request by jksuom**
This PR aims to be the first step in a plan to make the `RootOf` class
independent of complex numbers (see #9541).

Direct calls of `RootOf` are deprecated and its functionality is
transferred to a new function `rootof`.

`rootof` will return an indexed complex root either as an expression
involving radicals or as an object of a new subclass `ComplexRootOf` 
(abbreviated `CRootOf`) of `RootOf`. Apart from this name change
the current functionality of `RootOf` is preserved.

### CODE REVIEW

**Comment by asmeurer** [comment]
There are merge conflicts.

**Comment by asmeurer** [comment]
What is the motivation behind this change?

**Comment by asmeurer** [comment]
Why can't we just have `RootOf` do what `rootof` does? I don't see the point of the deprecation.

**Comment by jksuom** [comment]
The motivation is in #9541. We also had [this discussion](https://groups.google.com/forum/#!topic/sympy/jm0pliiiCVY). I think it is important to have a more general ``RootOf`` class that could be used for example in function fields to make the Risch algorithm work with algebraic extensions.

I'll fix the merge conflicts. (There were none when I sent the PR.)

**Comment by asmeurer** [comment]
I see why we should have separate classes. I don't see why we need to deprecate RootOf as a way to instantiate them. 

Great to see work on this, by the way. SymPy's algebraic function support is in great need of improvement.

**Comment by jksuom** [comment]
The idea was to have a class having more specialized root classes as subclasses, and the name ``RootOf`` seem the best name for this class. I could not think of a better way to free the name for such a class. Deprecation seemed necessary for this.

**Comment by certik** [comment]
Thanks for working on this @jksuom. What is the status of this?

**Comment by jksuom** [comment]
It has been forgotten for some time (there have been so many other things...), but I was planning to bring it up to date. Aaron thinks that no deprecation should be necessary and I agree. This should probably be ready for merge once I remove the deprecation and resolve the merge conflicts. (Those have arisen when some import lines have been modified.) The whole deprecation business was probably a misunderstanding on my part.

**Comment by certik** [comment]
Ok. Please ping me once you update it, so that I can review it.

**Comment by jksuom** [comment]
@asmeurer @certik I have removed the deprecation. But I believe some kind of comment should be added to the release notes of 1.0. Perhaps in the section "Backwards compatibility breaks and deprecations"?

**Comment by jksuom** [comment]
Again some lines changed. I'm testing a new version.

**Comment by jksuom** [comment]
@certik @asmeurer This is again free of conflicts.

**Comment by jksuom** [comment]
Ping @certik . This keeps getting easily out of sync,

**Comment by asmeurer** [comment]
If I am reading this correctly, RootOf(poly) will still work as before, right? That is, there are no backwards incompatible changes.

**Comment by jksuom** [comment]
Yes, that is true. But I hope that at some point in the future RootOf would become an abstract class with subclasses for complex roots, function field roots, etc... 
Presently, the changes are mainly of the type RootOf -> rootof (with resulting merge conflicts if one of the files is edited).

**Comment by asmeurer** [comment]
OK, I am +1 then.

**Comment by jksuom** [comment]
Thanks. Repeated merging was getting a bit frustrating...

**Comment by jksuom** [comment]
I also think this is good to have in v1.0. Should I add something to the notes?

**Comment by asmeurer** [comment]
Yeah, updating the release notes is always a good thing :)

**Comment by asmeurer** [comment]
Sorry this fell through the cracks. Unfortunately, pinging me on an issue is not sufficient for me to see it, because I get way too many notifications (even pings only) to look at. Feel free to ping me on Gitter if you've got a PR that you want me to look at, or if I started a review and you need me to look at something again after some fixes.

**Comment by jksuom** [comment]
Ok, I'll keep that in mind. Thanks again.

**Pull request merged**
