### PR TITLE
Link geometry class names to their descriptions

### PR DESCRIPTION
**Pull request by RavicharanN**
#### References to other Issues or PRs

This PR is a fix for the issue #13936.

#### Brief description of what is fixed or changed
Linked the geometry class names to their descriptions.

### CODE REVIEW

**Comment by gxyd** [comment]
There is a already a PR # for issue #13940 . Thanks for attempting this. You should be careful when contributing to new issues that others have already submitted a PR. You can ask on the issue, when in doubt.

**Comment by RavicharanN** [comment]
Okay, should I close the PR?

**Comment by gxyd** [comment]
Let's wait to see if the other PR actually gets merged.

**Comment by gxyd** [comment]
Closing this now, since the issue has been fixed.

**Pull request closed without merging**
