### PR TITLE
Fixed integrate to use meijerint definite #11742

### PR DESCRIPTION
**Pull request by Lakshya1605**
#11742

### CODE REVIEW

**Comment by jksuom** [comment]
It is not clear to me why the integration should start again from the beginning if meijerint fails at some point. There are several alternative integrators some of which may fail, but it should not be necessary to always restart after one failure since another integrator might succeed. Why would restart be needed here?

**Comment by Lakshya1605** [comment]
@jksuom I am restarting the integration because many time's none of the alternative integrators are able to find the anti derivative of the result given by meijerint ,thiscondition is mostly occurring when meijerint returns a Piecewise function .But restarting the integration  and integrating without meijerint is giving the ans. For example(after modifying the code to try meijerint even if the limits are not -oo or oo)

> f=integrate(1/(x + y + z), (x, 0, 1))
> f
>Piecewise((log(1 + 1/polar_lift(y + z)), Abs(periodic_argument(1/polar_lift(y + z), oo)) < pi), (Integral(1/(x + y + z), (x, 0, 1)), True))
>integrate(f,(y,0,1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lakshya/sympy/sympy/integrals/integrals.py", line 1305, in integrate
    risch=risch, manual=manual)
  File "/home/lakshya/sympy/sympy/integrals/integrals.py", line 496, in doit
    conds=conds)
  File "/home/lakshya/sympy/sympy/integrals/integrals.py", line 777, in _eval_integral
    return f._eval_integral(x)
  File "/home/lakshya/sympy/sympy/functions/elementary/piecewise.py", line 200, in _eval_integral
    return self.func(*[(integrate(e, x), c) for e, c in self.args])
  File "/home/lakshya/sympy/sympy/integrals/integrals.py", line 1305, in integrate
    risch=risch, manual=manual)
  File "/home/lakshya/sympy/sympy/integrals/integrals.py", line 496, in doit
    conds=conds)
  File "/home/lakshya/sympy/sympy/integrals/integrals.py", line 936, in _eval_integral
    for arg in result.args
  File "/home/lakshya/sympy/sympy/integrals/integrals.py", line 396, in doit
    function = function.doit(**hints)
  File "/home/lakshya/sympy/sympy/core/basic.py", line 1549, in doit
    for term in self.args]
TypeError: doit() got an unexpected keyword argument 'manual'


Now other integrators are not able to integrate the above result and returning error like above , but without using meijerint (the original code in which meijerint is tried only if limits are from -oo to oo)we get the answer

>  f = integrate(1/(x + y + z), (x, 0, 1))
> f
> -log(y + z) + log(y + z + 1)
>integrate(f,(y,0,1))
>z*log(z) - z*log(z + 1) + (-z - 1)*log(z + 1) - (-z - 1)*log(z + 2) - log(z + 1) + log(z + 2)

So i thought we could accomodate case like this by restarting the integration again and by indicating using a flag that meijerint has failed and hence by not meijerint again while reintegrating

**Comment by asmeurer** [comment]
If you add `?w=0` to the end of the diff URL, you can see it simpler. It looks like the key change here is that you are calling simplify on the function. I think this is a bad idea. simplify can be an expensive operation, and it's unclear how often that will actually help the integrators. 

Regarding restart logic, I agree it seems complicated. At the very least, there are ways you can structure the code to do restarts without adding a loop (e.g., call the integration function recursively).

**Comment by asmeurer** [comment]
To be more clear: if there are *targeted* simplifications (more specific functions than the general `simplify`) that it can be shown generally help a certain integrator, then those can be used. But in that case, it would be better to apply those in the integration routine itself.

**Comment by jksuom** [comment]
It seems that the integral produced by `meijerint_definite` is unusable in this example because it involves `polar_lift`. That should not be there since the sum `1 + 1/polar_lift(y + z)` is not well defined. But it should not be necessary to define new flags. One could also make `try_meijer` return `None` pretending that `NotImplementedError` was raised. 

The best solution would be to fix `meijerint_definite`, but that may be hard.

**Comment by Lakshya1605** [comment]
@jksuom @asmeurer So should i start working on changing meijerint_definite ?.And what all types of changes are expected ?.

**Comment by jksuom** [comment]
It seems that meijerint_definite always aims to return results with no polar numbers even if it internally makes use of them. In this case, however, polar_lift is left in the result since it is in the argument of a multivalued function, namely log. It may be hard to find a fix for its removal in meijerint_definite that would not lead to problems elsewhere.

I think that the easiest way to solve the issue is to scan the result produced by meijerint_definite, if any, and make try_meijer return None if the result contains polar_lift. Then it would not be necessary to introduce new flags that would make the logical flow of the code even more complicated. After all, the appearance of polar_lift means that meijerint_definite has failed.

**Comment by Lakshya1605** [comment]
@jksoum By modifying the code to try meijerint even if the limits are not -oo or oo and  doing as mentioned above (that is by "make try_meijer return None if the result contains polar_lift" ) We get

>  File "/home/lakshya/sympy/sympy/integrals/tests/test_transforms.py", line 726, in test_hankel_transform
    assert hankel_transform(1/r, r, k, 0) == 1/k
  File "sympy/integrals/transforms.py", line 1816, in hankel_transform
    return HankelTransform(f, r, k, nu).doit(**hints)
  File "sympy/integrals/transforms.py", line 1746, in doit
    **hints)
  File "sympy/integrals/transforms.py", line 1749, in _compute_transform
    return _hankel_transform(f, r, k, nu, self._name, **hints)
  File "sympy/integrals/transforms.py", line 195, in wrapper
    res = func(*args, **kwargs)
  File "sympy/integrals/transforms.py", line 1727, in _hankel_transform
    raise IntegralTransformError(name, f, 'could not compute integral')
IntegralTransformError: Hankel Transform could not be computed: could not compute integral.

also

>laplace_transform(Si(x), x, s)  is giving "LaplaceTransform(Si(x), x, s)" but intially it was giving "((-atan(s) + pi/2)/s, 0, True)"

**Comment by jksuom** [comment]
> Piecewise((1/k, Eq(Abs(periodic_argument(polar_lift(k)*2, oo)), 0)), (Integral(besselj(0, kr), (r, 0, oo)), True)) and setting ret = None if it contains polar_lift is causing the error.

meijerint_definite returns a tuple that consist of both the integration result and a condition. Since the condition is not integrated, it does not matter if it contains polar numbers. It is only the integration result that need be scanned. In this case the result is `1/k`, which is quite acceptable.

**Comment by Lakshya1605** [comment]
@jksuom  By "making try_meijer return None if the result contains polar_lift" fixes only a part of issue .Their are cases like 

> "integrate(1/(1-(x*y)**2),(x, 0, 1),y)"

 which are running forever because "integrate(1/(1-(x*y)**2), (x, 0, 1))" is returning 

> "Piecewise((Piecewise(((acoth(sqrt(y**2))- I*pi/2)/sqrt(y**2), Abs(y**2) > 1), (atanh(sqrt(y**2))/sqrt(y**2), True)), Abs(periodic_argument(exp_polar(I*pi)*polar_lift(y)**2, oo)) < pi), (Integral(1/(-x**2*y**2 + 1), (x, 0, 1)), True))"

And then none of the methods are able to integrate the above function with respect to y

Also their are cases like "integratesin(x*y*z),(x,0,pi),(y,0,pi))" which are runnnig forever

**Comment by jksuom** [comment]
These multiple integrals may be hard to get right since different integrators produce different intermediate results. meijerint_definite(), in particular, typically gives complicated answers.
 
However, it may be possible to modify the tests by restricting the domains of the variables without compromising the validity of the test. For example, in `integrate(1/(1 - (x*y)**2), (x, 0, 1), (y, 0, 1))` one can define `y = Symbol('y', positive=True)`, which will make the condition `Abs(periodic_argument(exp_polar(I*pi)*polar_lift(y)**2, oo)) < pi` false. The same positive y (and maybe positive z) could also simplify the computation of `integrate(sin(x*y*z), (x, 0, pi), (y, 0, pi))`.

If the results of meijerint_definite() are too complicated for continued integration, it is may be possible to add meijerg=False in the test when some other integrator is able to perform better.

**Comment by czgdp1807** [comment]
Closing this for now. Feel free to re-open this. Thanks for your contributions.

**Pull request closed without merging**
