### PR TITLE
Electrostatics BluePrint(Scalar)

### PR DESCRIPTION
**Pull request by sidhu1012**
#### References to other Issues or PRs

blueprint for issue #20017 

#### Brief description of what is fixed or changed
Added new module Electrostatics

#### Other comments
Currently only for charged particle(scalar)

#### Release Notes

- other
    - Physics Electrostatics
       -Charged Particle
                  -Electric Potential
                      -Electrostatic force
                      -Electric Field Intensity

### CODE REVIEW

**Comment by sidhu1012** [comment]
It was for review. Is it worth to work on?

**Comment by oscarbenjamin** [comment]
It is still unclear to me what the purpose of this module is. I refer back to the questions I asked here: https://github.com/sympy/sympy/issues/20017#issuecomment-683948925

Looking at this now I do not see how it is useful to anyone. Of course you plan to extend this and do more work but from this pull request I can not judge whether this is a reasonable idea. It would be better if you could write something that explains what your plan is for an electrostatics module.

**Comment by sylee957** [comment]
I think that it's better to implement this in documentation like `How to use sympy to solve problems of electrostatics` than in library.
I don't think that there is any clear research of how electrostatics problems can be modeled, or can have its unique algebra for now.

**Comment by sidhu1012** [comment]
Okay 🤔

**Comment by sidhu1012** [comment]
> It is still unclear to me what the purpose of this module is. I refer back to the questions I asked here: [#20017 (comment)](https://github.com/sympy/sympy/issues/20017#issuecomment-683948925)
> 
> Looking at this now I do not see how it is useful to anyone. Of course you plan to extend this and do more work but from this pull request I can not judge whether this is a reasonable idea. It would be better if you could write something that explains what your plan is for an electrostatics module.

Currently sympy's physics module have operations only for those particles/bodies which are not charged. If it's a charged particle or charged body(shell, rod etc) their properties vary and their applications and problems can't be solved currently with sympy.
My idea was to introduce a new submodule in physics  for these electrostatics problems and I don't think it would require it's own algebra. I think it would use vector submodule of physics module and some integration and differentiation.

The way I thought the module would look like this : 
  Physics Module
             -Electrostatics submodule
                           - Point charge.py
                                       - class point_charge(for point charges)
                                                       Functions for stationary charge:-
                                                            -Electrostatic force (net electrostatics force acting on a charged particle in a system of 
                                                                                             charges)                   
                                                            -Electric Potential (at the req point , displacement from point charge to specified charge)
                                                            -Electric   field intensity (at the req point , displacement from point charge to specified 
                                                                                                    charge)
                                                            -Equilibrium
                                                            -Dipole(take displacement or position and consider 2nd charge as -ve of self.charge)
                                                            -Dipole moment
                                                            -Electric field of dipole
                                                            -Potential Energy of dipole
                                                            -Short dipole
                                                            -Force between doples
                                                              etc
                                                      Functions for charge in electric field
                                                            -Charge placed in Electric field(s) (may add magnetism to electrostatics)
                                                                            -displacement
                                                                            -velocity
                                                            -Torque on dipole
                                                            -Work done on rotating dipole in electric field
                                                       similarly charge in magnetic field
                         -Charged_body.py
                                      -class rod
                                      -class linear charge(finite and infinte)
                                      -class  sheet (thin and thick)
                                      -class sphere(normal sphere and hollow sphere)  
                                      -class ring  
                                      -class arc
                                      -class disc
                            All classes with their respective functions like electric field intensity, potential etc
                            Would use integeration alot


                        -Capacitor.py
                                    -class capacitor(parallel plate capacitor and cylindrical capacitor)
                                               -capacitance
                                                          -in medium of dielectric constant A
                                                          -if space between is filed partially with dielectric of thickness t
                                               -short circuit
                                               -Combinations(series and parallel)
                                               -Energy stored
                      - functions.py
                                     -electric flux
                                     -Gauss Theorem
                                     -concentric shells
                                     -cyclotron

**Comment by sidhu1012** [comment]
> > It is still unclear to me what the purpose of this module is. I refer back to the questions I asked here: [#20017 (comment)](https://github.com/sympy/sympy/issues/20017#issuecomment-683948925)
> > 
> > Looking at this now I do not see how it is useful to anyone. Of course you plan to extend this and do more work but from this pull request I can not judge whether this is a reasonable idea. It would be better if you could write something that explains what your plan is for an electrostatics module.
> 
> Currently sympy's physics module have operations only for those particles/bodies which are not charged. If it's a charged particle or charged body(shell, rod etc) their properties vary and their applications and problems can't be solved currently with sympy.
> My idea was to introduce a new submodule in physics  for these electrostatics problems and @sylee957  I don't think it would require it's own algebra. I think it would use vector submodule of physics module and some integration and differentiation.
> 
> The way I thought the module would look like this : 
>   Physics Module
> 
> 
>              -Electrostatics submodule
> 
> 
>                            - Point charge.py
> 
>                                        - class point_charge(for point charges)
>                                                        Functions for stationary charge:-
>                                                             -Electrostatic force (net electrostatics force acting on a charged particle in a system of 
>                                                                                              charges)                   
>                                                             -Electric Potential (at the req point , displacement from point charge to specified charge)
>                                                             -Electric   field intensity (at the req point , displacement from point charge to specified 
>                                                                                                     charge)
>                                                             -Equilibrium
>                                                             -Dipole(take displacement or position and consider 2nd charge as -ve of self.charge)
>                                                             -Dipole moment
>                                                             -Electric field of dipole
>                                                             -Potential Energy of dipole
>                                                             -Short dipole
>                                                             -Force between doples
>                                                               etc
>                                                       Functions for charge in electric field
>                                                             -Charge placed in Electric field(s) (may add magnetism to electrostatics)
>                                                                             -displacement
>                                                                             -velocity
>                                                             -Torque on dipole
>                                                             -Work done on rotating dipole in electric field
>                                                        similarly charge in magnetic field
> 
> 
>                          -Charged_body.py
>                                       -class rod
>                                       -class linear charge(finite and infinte)
>                                       -class  sheet (thin and thick)
>                                       -class sphere(normal sphere and hollow sphere)  
>                                       -class ring  
>                                       -class arc
>                                       -class disc
>                             All classes with their respective functions like electric field intensity, potential etc
>                             Would use integeration alot
> 
> 
>                         -Capacitor.py
>                                     -class capacitor(parallel plate capacitor and cylindrical capacitor)
>                                                -capacitance
>                                                           -in medium of dielectric constant A
>                                                           -if space between is filed partially with dielectric of thickness t
>                                                -short circuit
>                                                -Combinations(series and parallel)
>                                                -Energy stored
> 
> 
>                       - functions.py
>                                      -electric flux
>                                      -Gauss Theorem
>                                      -concentric shells
>                                      -cyclotron

How does it seems?

**Comment by oscarbenjamin** [comment]
I think that's a bit better but I would rather see an explanation of the purpose of the module from the perspective of end users:

Who would use these functions and classes and why?

What classes of problems in electrostatics might someone solve with this?

Can you give an example of a problem in electrostatics that can be solved in sympy? What would it look like now to solve the problem without making any changes to sympy itself? How would the new electrostatics module help?

At the moment this PR adds 250 lines of code just to implement Coulomb's law along with tests for trivial behaviour. I don't see why anyone would want to use that rather than simply write out Coulomb's law themselves though. What I don't want is something that turns into 10000 lines of code that just lists all the simplest formulae from electrostatics.

Rather than having classes for each possible shape of charged body perhaps there could be general routines that could compute the electric field/potential for any arbitrary shapes specified using the classes in the geometry module. I could imagine something like that being useful because someone could use it to derive results that are not just the standard formulas for the most simple shapes. Most likely the bulk of the work to implement something like that is actually in the geometry, vector and integrals packages rather than in a new electrostatics package though.

@moorepants @Upabjojr does either of you have an idea of what would make sense if there was to be an electrostatics module in Physics? Do you think it makes sense to have a module like that?

**Comment by sidhu1012** [comment]
> I think that's a bit better but I would rather see an explanation of the purpose of the module from the perspective of end users:
> 
> Who would use these functions and classes and why?
> 
> What classes of problems in electrostatics might someone solve with this?
> 
> Can you give an example of a problem in electrostatics that can be solved in sympy? What would it look like now to solve the problem without making any changes to sympy itself? How would the new electrostatics module help?
> 
> At the moment this PR adds 250 lines of code just to implement Coulomb's law along with tests for trivial behaviour. I don't see why anyone would want to use that rather than simply write out Coulomb's law themselves though. What I don't want is something that turns into 10000 lines of code that just lists all the simplest formulae from electrostatics.
> 
> Rather than having classes for each possible shape of charged body perhaps there could be general routines that could compute the electric field/potential for any arbitrary shapes specified using the classes in the geometry module. I could imagine something like that being useful because someone could use it to derive results that are not just the standard formulas for the most simple shapes. Most likely the bulk of the work to implement something like that is actually in the geometry, vector and integrals packages rather than in a new electrostatics package though.
> 
> @moorepants @Upabjojr does either of you have an idea of what would make sense if there was to be an electrostatics module in Physics? Do you think it makes sense to have a module like that?



> I think that's a bit better but I would rather see an explanation of the purpose of the module from the perspective of end users:
> 
> Who would use these functions and classes and why?
> 
> What classes of problems in electrostatics might someone solve with this?
> 
> Can you give an example of a problem in electrostatics that can be solved in sympy? What would it look like now to solve the problem without making any changes to sympy itself? How would the new electrostatics module help?
> 
> At the moment this PR adds 250 lines of code just to implement Coulomb's law along with tests for trivial behaviour. I don't see why anyone would want to use that rather than simply write out Coulomb's law themselves though. What I don't want is something that turns into 10000 lines of code that just lists all the simplest formulae from electrostatics.
> 
> Rather than having classes for each possible shape of charged body perhaps there could be general routines that could compute the electric field/potential for any arbitrary shapes specified using the classes in the geometry module. I could imagine something like that being useful because someone could use it to derive results that are not just the standard formulas for the most simple shapes. Most likely the bulk of the work to implement something like that is actually in the geometry, vector and integrals packages rather than in a new electrostatics package though.
> 
> @moorepants @Upabjojr does either of you have an idea of what would make sense if there was to be an electrostatics module in Physics? Do you think it makes sense to have a module like that?

Consider a system of charges , to find  net force on each charge or net electric field of system, Currently sympy cant do it because it currently doesn't support any operation for charged particles and its one of simple questions.

I thought of having different class for known shapes because deriving formulas from arbitrary/unknown shapes would involve a lot of calculus.
Which gives another application of this module that user's may like to solve complex topics like field/potential etc for arbitrary charges shapes, work done in electric field , dipole and applications

This would boost sympy's involvement in scientific field.

250 lines were for field intensity, coulomb's law and potential and that too were raw. We could generalize these things , reducing tons of lines.

Plus this just an idea and would shape better as we work on it 😄

**Comment by oscarbenjamin** [comment]
Can you stop quoting entire long posts? Quoting the entire post is pointless if anyone who wants can scroll up and read the post you are replying to. If you want to respond to a particular part of a post you can quote only that bit like this:

> Consider a system of charges , to find net force on each charge or net electric field of system, Currently sympy cant do it because it currently doesn't support any operation for charged particles and its one of simple questions.

SymPy can do it. You just need to write a couple of lines of code to calculate it. There is no need to use the particle class or an electrostatics module in order to solve problems in electrostatics. The code that you add to calculate this in an electrostatics module will not fundamentally change what sympy can or can not do. It might make some things easier or it might implement things in a better way than an average user would.

As an example I can do this right now:
```julia
In [8]: from sympy.physics.units.definitions.unit_definitions import e0                                                                                       

In [9]: q1, q2, r, E = symbols('q1 q2 r E')                                                                                                                   

In [10]: F = q1*q2/(4*pi*e0*r**2)                                                                                                                             

In [11]: F                                                                                                                                                    
Out[11]: 
          q₁⋅q₂           
──────────────────────────
     2                    
4⋅π⋅r ⋅vacuum_permittivity
```
That does the same thing as the code so far in this pull request and I can do it without having any electrostatics module.

I think it would be better to write some code using sympy that shows how to do some sort of electrostatics calculation. Then we can think about whether or not it is worth adding anything in sympy to make it easier to do that sort of calculation. I am pretty sure that the most useful changes in sympy to facilitate that calculation will be in other parts of sympy.

**Comment by sidhu1012** [comment]
@oscarbenjamin sorry for quoting big messages.

You implemented Coulomb's law which is quite basic

What is its a random charged body

Now my thinking is if we have toh make a module for charged bodies then why not for point charges

Now in point charge , Coulomb's force is not the only topic, dipole , potential, field intensity etc, there are many more

Some basic one we can do using sympy

But wouldn't it be easy for end user to do things by just calling a function rather than doing everything by hand

For small concepts it may seems unimportant but for complex aur mix questions (body and charge in one , system etc) isn't it good to have?

**Comment by moorepants** [comment]
> @moorepants @Upabjojr does either of you have an idea of what would make sense if there was to be an electrostatics module in Physics? Do you think it makes sense to have a module like that?

Maybe, but I agree completely with @sylee957 that before adding any kind of new modules, classes, functions, etc. one needs to solve these problems manually using existing SymPy features. It really isn't until after you solve lots of problems of a certain type that you start to get a good idea of what abstractions may simplify that process.

Also @sidhu1012 seems like a new contributor and is eager to add things to SymPy. This is great, but I think they need to focus on fixing simpler existing issues to get started. Looking for the "easy to fix" labeled issues would be a good start and trying to avoid adding new features is also preferable. Once you have solved existing problems and/or made significant improvements to documentation of existing functionality, then you @sidhu1012 will be able to formulate good ideas for new features.

**Comment by sidhu1012** [comment]
Okay @moorepants , actually when I started contributing to sympy , this was the first idea I got for sympy , so I shared will all , with my point of view.

**Comment by moorepants** [comment]
We definitely want your ideas but adding new features to SymPy require careful attention and thought. For example, look at how much conversation and design it took to add one new class for a transfer function:

**Comment by sidhu1012** [comment]
@moorepants okay 😁

**Comment by Smit-create** [comment]
I think this PR might be related to this https://github.com/sympy/sympy/pull/2361

**Comment by Upabjojr** [comment]
> It was for review. Is it worth to work on?

I see a lot of code just for the Coulomb law. I think we should add classes only if really needed... too many classes make the code difficult to use.

Furthermore, this implementation is restricted to Coulomb's law in SI units. SymPy should implement physics independently of unit systems.

**Pull request closed without merging**
