### PR TITLE
Sympy Stats assume expressions to be equal to zero

### LINKED ISSUE #6700: SymPy Stats should assume expressions are equal to zero
```
If you have something like

X = Die("X", 6)
P(Eq(X, 3))

It's a little annoying that you have to use Eq (unlike, e.q., P(X > 3)).  Most places in SymPy solve this problem by automatically assuming that expressions are equal to zero, (like solve(x**2 - 2, x) instead of solve(Eq(x**2, 2), x)).  So functions in SymPy Stats like P() that usually take in boolean expressions should assume non-booleans are equal to zero.
```

Original issue for #6700: http://code.google.com/p/sympy/issues/detail?id=3601
Original author: https://code.google.com/u/asmeurer@gmail.com/

### PR DESCRIPTION
**Pull request by akash9712**
Expressions in sympy.stats are now assumed to be equal to zero. Tests were added.
For example:
```
>>> X = Die('X', 6)
>>> P(X - 3) # This is same as P(Eq(X - 3, 0))
1/6
```

Fixes #6700

### CODE REVIEW

**Comment by Upabjojr** [comment]
Are you sure about this feature?

**Comment by akash9712** [comment]
@Upabjojr I was not a part of the original discussion, but I think the agreement was to go forward with this, since there are comments about sending a PR for this feature at the issue.

**Comment by Upabjojr** [comment]
> since there are comments about sending a PR for this feature at the issue.

I guess the discussion there was clear, that this feature is potentially confusing.

**Comment by akash9712** [comment]
@Upabjojr I agree that this could be confusing. I am closing the PR.

**Comment by Upabjojr** [comment]
The point is: what is the mathematical definition of `P(X)`? If you have `X = val`, that's clearly a subset of the application of `X: omega -> R`, which is a subset of the probability space. `P(X)` could be a function (as @rlamy pointed out), so assuming `X == 0` could be wrong.

**Pull request closed without merging**
