### PR TITLE
Operations on Formal Power Series

### PR DESCRIPTION
**Pull request by leosartaj**
This PR defines addition, subtraction, differentiation, integration of Formal Power Series.

@jcrist @flacjacket

### CODE REVIEW

**Comment by leosartaj** [comment]
I implemented ``_eval_Integral`` for defining integration. But this way rather than an unevaluated integral an evaluated integral is returned. eg.

```
>>> Integral(fps(sin(x), x), x)
-1 + x**2/2 - x**4/24 + O(x**6)
``` 

I am not really sure how to fix this. I tried implementing ``_eval_integrate`` instead, but couldn't get it working. I didn't find any documentation on what method should be implemented.

Plus ``integrate`` does not work. On some debugging, it gets stuck in an infinite loop. Any suggestions? @jcrist @flacjacket

**Comment by jcrist** [comment]
Overall, most of this looks good to me. I'm not sure about the integral question though. A quick grep through the codebase shows that only one file (vector/basisdependent.py) implements `_eval_Integral`. I'd ask someone who knows more about the integration routines (ping @asmeurer).

**Comment by leosartaj** [comment]
Except from integration issue this is almost complete. I would like to get it in before GSoC ends. Any pointers as to what is best to do here would be really helpful. Ping @asmeurer

**Comment by jksuom** [comment]
I think integrals of formal power series can only be defined as antiderivatives ("indefinite integrals"). The derivative is obtained by replacing each ``x**n`` with ``n*x**(n - 1)`` and the antiderivative by replacing ``x**n`` with ``x**(n + 1)/(n + 1)``.

**Comment by leosartaj** [comment]
@jksuom logic for integration is more or less done. Question is to as how to implement this in SymPy. See [this](https://github.com/sympy/sympy/pull/9782#issuecomment-128151694)

**Comment by jksuom** [comment]
> what method should be implemented.

There is only one method (apart from the choice of the constant term) to integrate a formal power series. A formal power series is conventionally written ``\sum_{n \in N)a_n x^n`` but conceptually it is just as sequence ``(a_n)``. (It is not assumed that the series be convergent, hence there is no sum function involved in general.) Its integral is determined by the sequence ``(b_n)``, where ``b_0 = 0`` (or any other constant of integration) and ``b_n = a_{n-1}/n`` for ``n > 0``.

**Comment by leosartaj** [comment]
I think we are not talking about the same thing. I implemented ``_eval_Integral`` method, but that does not work very well. Any suggestions as to what method/function should be implemented to get integration of ``FormalPowerSeries`` working.

**Comment by asmeurer** [comment]
There is no _eval_integral method, since for most objects, such a method doesn't make sense (the integration algorithm works by knowing how to compute the derivative of any expression). Unfortunately, it looks like basic operations on fps (like multiplication by `x`) don't simplify, so there's no chance for the integration algorithm to work in that way. 

You will either need to add `_eval_integrate` to the integration algorithm, or add support for `fps` to it directly.

**Comment by leosartaj** [comment]
I am not very familiar with the integration code. I will have a look.

**Comment by jcrist** [comment]
Perhaps for now just move the `_eval_Integral` code to an `integrate` method (like `Expr` has), so users can do `some_fps.integrate(x)` and have that work. This of course wouldn't work if the `fps` was inside another expression, or if the user tried `integrate(some_fps, x)`, but it's a start. It also allows the rest of this useful PR to get merged, while you (or someone else) figures out how to add this into the proper integration code.

**Comment by leosartaj** [comment]
That sounds good. I will open an issue for it after this gets merged.

**Comment by leosartaj** [comment]
Please have a look @jcrist.

**Comment by jcrist** [comment]
Looks good to me. Merging.

**Comment by leosartaj** [comment]
Thanks @jcrist

**Pull request merged**
