### PR TITLE
symbols -> Dummy_symbols in ComplexPlane

### LINKED ISSUE #9865: Use Dummy symbols in ComplexPlane
We implemented `ComplexPlane` here #9463,  Currently we defined symbols internally as:
```
x, y, r, theta = symbols('x, y, r, theta')
```
The above symbols should be changed to Dummy symbols.

### PR DESCRIPTION
**Pull request by gxyd**
fixed #9865

### CODE REVIEW

**Comment by gxyd** [comment]
Ping @aktech

**Comment by aktech** [comment]
Looks good. +1

**Comment by aktech** [comment]
Thanks! Merging.

**Comment by gxyd** [comment]
Thanks @aktech

**Pull request merged**
