### PR TITLE
Updated readme.md - toc added

### PR DESCRIPTION
**Pull request by variable-jain**
# Added Table of Contents to REAMDE.md
A table of contents is required for enabling fast walkthrough on all topics for readers.

#### References to other Issues or PRs
This pull request fixes one out the two tasks mentioned in Issue #21072 [Updating readme.md](https://github.com/sympy/sympy/issues/21072).

#### Brief description of what is fixed or changed
A table of contents is added in the beginning of the github readme.

#### Release Notes

* other
  * Added a table of content to readme

### CODE REVIEW

**Comment by bhav09** [comment]
@variable-jain, can you please be ethical and stop stealing someone else's issue?

**Comment by oscarbenjamin** [comment]
> can you please be ethical and stop stealing someone else's issue?

It is not unethical to open a PR that addresses an issue regardless of who opened the issue. If you open an issue then others can work on it.

**Comment by oscarbenjamin** [comment]
I don't really see what these changes to the README actually achieve. Why do we need a table of contents in the README file?

**Comment by oscarbenjamin** [comment]
I don't think this is needed

**Pull request closed without merging**
