### PR TITLE
extend sqrt_linear_rule to handle nested sqrt

### LINKED ISSUE #9723: analytical integrate
Sympy cannot do this?

```
integrate(sqrt(x+sqrt(x)))
```

BTW, this is computed by SAGE:

```
-1/12*(3*(sqrt(x) + 1)^(5/2)/x^(5/4) - 8*(sqrt(x) + 1)^(3/2)/x^(3/4) - 3*sqrt(sqrt(x) + 1)/x^(1/4))/((sqrt(x) + 1)^3/x^(3/2) - 3*(sqrt(x) + 1)^2/x + 3*(sqrt(x) + 1)/sqrt(x) - 1) + 1/8*log(sqrt(sqrt(x) + 1)/x^(1/4) + 1) - 1/8*log(sqrt(sqrt(x) + 1)/x^(1/4) - 1)
```

### PR DESCRIPTION
**Pull request by eagleoflqj**
#### References to other Issues or PRs

Fixes #9723
#### Brief description of what is fixed or changed
On top of #23674, with a little extension to #23642, `sqrt(x+sqrt(x))` can be integrated.
#### Other comments
First several steps from SymPy Beta
Screenshot from 2022-06-25 14-39-29
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I'm not sure I fully understand how this works but it looks okay to me.

**Comment by eagleoflqj** [comment]
Previously, `sqrt_linear_rule` finds all `base**rational`, and proceeds when all `base`s are linear and collinear, e.g. for `(3*x+2)**(1/2)` and `(6*x+4)**(1/3)` it substitutes with `u=(3*x+2)**(1/6)` to remove root expression.
However, for `sqrt(x+sqrt(x))`, although `x+sqrt(x)` isn't linear, substituting with `u=sqrt(x)` still makes sense, so linear restriction could be removed.

**Comment by oscarbenjamin** [comment]
> so linear restriction could be removed.

Okay, that makes sense. Can you add a comment to the code that explains this? The comment currently is
```
# don't return, for sqrt(x+sqrt(x))
```
It's not clear to me reading that what it means. The manual integrate code definitely needs more comments in general...

**Comment by eagleoflqj** [comment]
> The manual integrate code definitely needs more comments in general...

I'd refactor it and add comments after a new release https://github.com/sympy/sympy/issues/23624#issuecomment-1154687092

**Comment by eagleoflqj** [comment]
> Does this only apply for `sqrt(x)` or will we hit this branch in other cases as well?

This branch is hit on nested `Pow`. Currently only `sqrt(a+b*x+sqrt(c+d*x))**n` can be handled.
* If outer `Pow` is not `sqrt`, like `cbrt(x+sqrt(x))`, we get a `2*u*cbrt(u**2 + u)`, which can't be handled now. See Wolfram Alpha result https://www.wolframalpha.com/input?i=integrate+x*%28x%5E2%2Bx%29%5E%281%2F3%29
* If inner `Pow` is not `sqrt`, like `sqrt(x+cbrt(x))`, we get a `3*u**2*sqrt(u**3 + u)`, which can't be handled now. See Wolfram Alpha result https://www.wolframalpha.com/input?i=integrate+3*x%5E2*sqrt%28x%5E3%2Bx%29

**Pull request merged**
