### PR TITLE
Equate S.Complexes with ComplexPlane(S.Reals*S.Reals)

### PR DESCRIPTION
**Pull request by aktech**
It works now:

``` python
In [3]: S.Complex == ComplexPlane(S.Reals*S.Reals)
Out[3]: True
```

@hargup  @flacjacket  @jksuom

### CODE REVIEW

**Comment by aktech** [comment]
Ideally, the following should also return `True`, but I think we should not equate `S.Complex` to two different objects. 
```python
 S.Complex == ComplexPlane(Interval(0, oo)*Interval(0, 2*pi), polar=True)
```
@hargup 
BTW, Should there be something like `S.Complex(polar=True)` object, for having the case like above?

**Comment by jksuom** [comment]
I think the name ``S.Complex`` is not quite proper for a *set* of numbers. In analogy with ``S.Reals``, one possibility might be ``S.Complexes``. Otherwise, equating the singleton with ``ComplexPlane(S.Reals*S.Reals)`` seems plausible.

**Comment by aktech** [comment]
> In analogy with S.Reals, one possibility might be S.Complexes.

I think, that sounds good. I'll change it to `S.Complexes`.

**Comment by aktech** [comment]
Replaced S.Complex with S.Complexes.
BTW, Wolfram also calls it `Complexes`.

**Comment by jksuom** [comment]
One deficiency in both ``S.Reals`` and ``S.Complexes`` is that neither one has any algebraic structure. If such structure were to be added later, the singletons could no more be equated with the set objects in the same way. That may not be important now, but perhaps it should be kept in mind.

**Comment by aktech** [comment]
`S.Reals` inherits from `Interval` class & `S.Complexes` inherits from `ComplexPlane` class and all the operations are defined on `Interval` and `ComplexPlane` classes, doesn't that an algebraic structure?

**Comment by jksuom** [comment]
It seems to me that the algebraic type operations currently defined for sets are actually set theoretic. Sum (defined by ``__add__``) is union, etc..

**Comment by aktech** [comment]
Yes, Indeed, in the Base `Set` class.

**Comment by jksuom** [comment]
The algebraic operations could be defined as mappings. For example, the product in ``S.Complexes`` would be the mapping from ``S.Complexes*S.Complexes`` to ``S.Complexes`` taking ``((x1, y1), (x2, y2))`` to ``(x1*x2 - y1*y2, x1*y2 + y1*x2)``.

**Comment by aktech** [comment]
Probably in that case:
`ComplexPlane(FiniteSet(x)*FiniteSet(y))` should simplify to `{x + I*y}`. As of now it doesn't.

```python
In [6]: c1 = ComplexPlane(FiniteSet(x)*FiniteSet(y))
In [7]: c2 = ComplexPlane(FiniteSet(a)*FiniteSet(b))

In [8]: c1
Out[8]: ComplexPlane(Lambda((x, y), x + I*y), {x} x {y})

In [9]: c2
Out[9]: ComplexPlane(Lambda((x, y), x + I*y), {a} x {b})

In [10]: c1*c2
Out[10]: ComplexPlane(Lambda((x, y), x + I*y), {x} x {y}) x ComplexPlane(Lambda((x, y), x + I*y), {a} x {b})
```

**Comment by jksuom** [comment]
I have not been thinking of these matters so far, but using the notation ``{x + I*y}`` certainly feels right.

**Comment by aktech** [comment]
I have reported the issue here: #9669

**Comment by hargup** [comment]
+1, @aktech also update the name change in the [release notes](https://github.com/sympy/sympy/wiki/Release-Notes-for-0.7.7).

**Pull request merged**
