### PR TITLE
Complexanalysis

### PR DESCRIPTION
**Pull request by Teut2711**
#### Release Notes

* complexanalysis
 * complex integration +much more in future 
    * Contour Integration
     * Jordan Type

### CODE REVIEW

**Comment by XtremeGood** [comment]
Hi, my code is a working one. Can I get some help on fixing first of all why my older PR's are being shown here? Also, what is the problem in the notes since I have mentioned the module name, a text, file name and then text? Once done I can further implement trigonometric type, Mellin's integral(inverse Laplace transforms) etc.

**Comment by sylee957** [comment]
Maybe rebasing your PR and squashing your changes can be the easiest way of solving the bloated logs.
In my own opinion, unlike the recommendation from SymPy wiki,
I personally think that rebasing is better than merging the master, unless you are working on the single commit in a team or such.

And also, I see the sympy bot only sees these modules
https://github.com/sympy/sympy-bot/blob/master/sympy_bot/submodules.txt
as valid.
You would have to open a issue there, if you really need the new section.

**Comment by sylee957** [comment]
I visited your fork, but I see you may have corrupted the master.

You may clone the sympy main repository in a new directory in your PC, and force push to your forked master to purge.
But if you can't do that, you would have to copy all your work and reset your fork entirely, maybe.

**Comment by XtremeGood** [comment]
Well I have already tried the following steps 3 times:
Steps:
git checkout master
git fetch upstream
git merge upstream/master
git checkout -b complexanalysis                                                     "new branch here"
Copied the new folder complexanalysis from desktop to the sympy/sympy in GitHub folder
git add "complexanalysis/Contour Integration.py"
git commit -m "Some text here"
git push origin complexanalysis

**Pull request closed without merging**
