### PR TITLE
Adjust alignment of the Sum pretty printer

### LINKED ISSUE #16346: Bad centering for Sum pretty print
```
>>> pprint(Sum(x, (x, 1, oo)) + 3)
  ∞
 ___
 ╲
  ╲   x
  ╱     + 3
 ╱
 ‾‾‾
x = 1
```

The `x` and the `+ 3` should be aligned. I'm not sure if the `x` should be lower of if the `+ 3` should be higher.

### PR DESCRIPTION
**Pull request by anpandey**
#### References to other Issues or PRs

Fixes #16346

#### Brief description of what is fixed or changed
The `Sum` pretty printer now renders expressions on the same line

Previously:

```
In [2]: pprint(x + Sum(n,  (n, 1, oo)) + 3)
      ∞        
     ___       
     ╲         
      ╲   n    
x +   ╱     + 3
     ╱         
     ‾‾‾       
    n = 1      

In [3]: pprint(x + Sum(n**2,  (n, 1, oo)) + 3, use_unicode=False)
      oo        
     ___        
     \  `       
x +   \    2 + 3
      /   n     
     /__,       
    n = 1       
```

Now:
```
In [3]: pprint(x + Sum(n,  (n, 1, oo)) + 3)
      ∞        
     ___       
     ╲         
      ╲        
x +   ╱   n + 3
     ╱         
     ‾‾‾       
    n = 1      


In [5]: pprint(x + Sum(n**2,  (n, 1, oo)) + 3, use_unicode=False)
      oo        
     ___        
     \  `       
      \    2    
x +   /   n  + 3
     /__,       
    n = 1       
```

#### Release Notes

* printing
  * Fixed alignment of expressions inside sums in pretty printer

### CODE REVIEW

**Comment by anpandey** [comment]
There's currently one failing assertion in `print_pretty`. For the expression `Sum(k**(Integral(x**n, (x, -oo, oo))), (k, 0, Integral(x**x, (x, -oo, oo))))`, the expected is

```
∞                 
⌠                 
⎮   x             
⎮  x  dx          
⌡                 
-∞                
 ______           
 ╲                
  ╲       ∞       
   ╲      ⌠       
    ╲     ⎮   n   
     ╲    ⎮  x  dx
     ╱    ⌡       
    ╱     -∞      
   ╱     k        
  ╱               
 ╱                
 ‾‾‾‾‾‾           
 k = 0            
```

while the actual is

```
∞                 
⌠                 
⎮   x             
⎮  x  dx          
⌡                 
-∞                
 ______           
 ╲                
  ╲               
   ╲      ∞       
    ╲     ⌠       
     ╲    ⎮   n   
     ╱    ⎮  x  dx
    ╱     ⌡       
   ╱      -∞      
  ╱      k        
 ╱                
 ‾‾‾‾‾‾           
 k = 0            
```
which centers the sum on the integral within the power. If this looks ok, I'll fix that and add more tests (the current tests seem to only test sigmas of an even height).

**Comment by oscarbenjamin** [comment]
> If this looks ok, I'll fix that and add more tests (the current tests seem to only test sigmas of an even height).

Please do. This looks good.

**Comment by asmeurer** [comment]
This should have a release notes entry.

**Comment by oscargus** [comment]
Thanks!

**Pull request merged**
