### PR TITLE
Linear 2eq order1 fixes

### PR DESCRIPTION
**Pull request by FAndersson**
Rewrite of functions _linear_2eq_order1_type1 and _linear_2eq_order1_type2. 

The old version of _linear_2eq_order1_type1 failed for a zero rhs, i.e. x' = 0. 
The old version of _linear_2eq_order1_type2 failed for a number of different particular solutions and returned an incorrect solution for one corner case (see commit 2416caac). 

All the previous failures are now covered by tests. 
Fixes a small part of #9235.

### CODE REVIEW

**Comment by asmeurer** [comment]
CC @cbm755

**Comment by moorepants** [comment]
There is an error in the docstring:

```
Warning, treated as error:

/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/sympy-1.0.1.dev0-py3.5.egg/sympy/solvers/ode.py:docstring of sympy.solvers.ode._linear_2eq_order1_type1:33: WARNING: Block quote ends without a blank line; unexpected unindent.

make: *** [html] Error 1

```

**Comment by mijo2** [comment]
Linear 2 equations, First order Type 1 and Type 2 solvers will be removed soon and the system of ODEs of 2 equations Type 1 are dealt by a new version of ```linear_2eq_order1_type1``` introduced in PR #18720

**Comment by oscarbenjamin** [comment]
The test cases from this PR look useful. Maybe they can still be added even if the changes to type and type2 aren't needed any more.

**Comment by mijo2** [comment]
> The test cases from this PR look useful. Maybe they can still be added even if the changes to type and type2 aren't needed any more.

I agree. But maybe instead of adding it myself, we can create two good first issues out of it for the new contributors and wait for sometime. If no one takes up to solve the issue, then I would add it.

**Comment by mijo2** [comment]
@oscarbenjamin I have created an easy to fix issue [here](https://github.com/sympy/sympy/issues/19312).

**Comment by czgdp1807** [comment]
@mijo2 @oscarbenjamin Can we close this?

**Comment by mijo2** [comment]
Not yet, we need some of the test cases from this PR and I am planning on opening another good first issue soon to get all the test cases from this PR.

**Comment by oscarbenjamin** [comment]
Thanks @FAndersson for this. It looks like good work but is not needed now that these cases are handled by a more generalised solver. The test cases are being added.

**Pull request closed without merging**
