### PR TITLE
Added simplification of matrix multiplication with inverse matrices containing MatMul objects

### PR DESCRIPTION
**Pull request by Upabjojr**
Just trying to simplify expressions like `Inverse(X*X.T)*X*X.T`, which can be useful to deal with equations of matrix expressions.

NO ENTRY

### CODE REVIEW

**Comment by oscargus** [comment]
Isn't there a risk that we run into the x/x discussion here again? What if the matrices are not invertible?

**Comment by Upabjojr** [comment]
> Isn't there a risk that we run into the x/x discussion here again? What if the matrices are not invertible?

The code is already simplifying expressions like `Inverse(X)*X` or even `Inverse(X*Y)*X*Y` if `X` and `Y` are both square matrices. It's already happening without checking for singularity.

This PR just adds the possibility of extending it to inverses of matrix multiplications: `Inverse(X*Y)*X*Y` when `X` and `Y` are not square matrices but their product is.

If you worry about the x/x problem, it's already there.

**Comment by oscargus** [comment]
OK! I know that x/x is already there, but also that it is debated. 

Anyway, this doesn't introduce any new "issue", so fair enough.

In the long term one should possibly add some assumption for matrices and matrixsymbols to indicate if they are non-singular (maybe there already is, if so, it should probably be used).

**Comment by Upabjojr** [comment]
> In the long term one should possibly add some assumption for matrices and matrixsymbols to indicate if they are non-singular (maybe there already is, if so, it should probably be used).

This is a bit complicated for this PR as it deals with non-square matrices whose product is square and invertible.

**Pull request merged**
