### PR TITLE
[Ready to review] Added a module docstring to sympy.abc.

### PR DESCRIPTION
**Pull request by toolforger**

### CODE REVIEW

**Comment by smichr** [comment]
> accidentally type ``from sympy.abc import *``

I just follow that import with `from sympy import *` which restores default single letter SymPy definitions. (One could be more targetted with `from sympy import C,O,S,I,N,E,Q`)

**Comment by toolforger** [comment]
Should I modify the docstring? (Can do.)

**Comment by smichr** [comment]
> Should I modify the docstring

I guess I would -- in my startup file I use `from sympy.abc import *; from sympy import *` but if you don't want to encourage star imports then the "COSINEQ" mnemonic is pretty easy to remember.

**Comment by toolforger** [comment]
After thinking more about the issue, I'm rejecting the idea that ``from sympy import *`` could happen by accident. I think the real issue is that the `sympy` namespace may acquire more single-letter names, and combining multiple star imports leaves you with no guarantees whether that X you got is from ``sympy.abc`` or from `sympy` so your code is going to be fragile against version upgrades.
I hope the latest update to the docstring is reflecting that properly.

I'm not going to reword this more, I'm noticing I started to develop tunnel vision and overlook issues.
So unless somebody has concrete feedback what to change, this should go in or be rejected.

**Comment by jcrist** [comment]
@smichr: is your disagreement a -1 or a -0? I think it looks fine as is, and would be a nice addition to our docs. Up to you.

**Comment by smichr** [comment]
I have no disagreement.

Regarding the concern about static analysis not being able to work: is that still a concern after your other PR (that removes the `exec`) is committed? Because if so, then that part of the docstring should be removed.

**Comment by toolforger** [comment]
You're right, I'll redo the docstring.

**Comment by toolforger** [comment]
Phew :-)

**Pull request merged**
