### PR TITLE
Unbundle mpmath (issue #5581)

### LINKED ISSUE #5581: Stop bundling mpmath
```
Bundling mpmath causes problems for interoperation with user code and libraries using mpmath themselves (cf. discussions about this in issue 5259 ). It's also a problem for porting to Python3, as mpmath uses the same source under Python2 and 3, while we want to use 2to3, but no existing tool allows to mix the two approaches inside a single package.

So, I think that we should make mpmath an external dependency and remove it from our source tree. To specify the dependency properly, we'll need to port our setup.py to Distribute. I have a branch that does all this: https://github.com/rlamy/sympy/tree/unbundle-mpmath - it's not quite polished enough for a pull request but it works under tox (though not in python2.4, because mpmath 0.17 is incompatiblme with it).
```
Original issue for #5581: http://code.google.com/p/sympy/issues/detail?id=2482
Original author: https://code.google.com/u/101272611947379421629/
Referenced issues: #5259
Original owner: https://code.google.com/u/101272611947379421629/

### LINKED ISSUE #8022: 0.7.5 in recent Sage: cannot import from sympy
I'm at a loss, but I'm a Python noob, so please help. At the moment, Sage is happy with plain sympy-0.7.4 but we need the new 0.7.5 functionality. What happens with 0.7.5 when importing anything from sympy:

        from sympy.printing.pretty.stringpict import stringPict
      File "/home/ralf/sage/local/lib/python2.7/site-packages/sympy/__init__.py", line 32, in <module>
        from .core import *
      File "/home/ralf/sage/local/lib/python2.7/site-packages/sympy/core/__init__.py", line 8, in <module>
        from .expr import Expr, AtomicExpr
      File "/home/ralf/sage/local/lib/python2.7/site-packages/sympy/core/expr.py", line 7, in <module>
        from .evalf import EvalfMixin, pure_complex
      File "/home/ralf/sage/local/lib/python2.7/site-packages/sympy/core/evalf.py", line 9, in <module>
        import sympy.mpmath.libmp as libmp
      File "/home/ralf/sage/local/lib/python2.7/site-packages/sympy/mpmath/__init__.py", line 6, in <module>
        from .ctx_mp import MPContext
      File "/home/ralf/sage/local/lib/python2.7/site-packages/sympy/mpmath/ctx_mp.py", line 47, in <module>
        from sage.libs.mpmath.ext_main import Context as BaseMPContext
      File "ext_main.pyx", line 38, in init sage.libs.mpmath.ext_main (build/cythonized/sage/libs/mpmath/ext_main.c:28725)
      File "/home/ralf/sage/local/lib/python2.7/site-packages/mpmath/__init__.py", line 6, in <module>
        from .ctx_mp import MPContext
      File "/home/ralf/sage/local/lib/python2.7/site-packages/mpmath/ctx_mp.py", line 49, in <module>
        import sage.libs.mpmath.ext_main as _mpf_module
    AttributeError: 'module' object has no attribute 'ext_main'

After patching mpmath:

    --- mpmath/mpmath/libmp/backend.py~    2013-08-08 14:49:58.000000000 +0200
    +++ mpmath/mpmath/libmp/backend.py     2014-07-11 08:54:28.759388954 +0200
    @@ -71,6 +71,7 @@
         try:
             import sage.all
             import sage.libs.mpmath.utils as _sage_utils
    +        import sage.libs.mpmath.ext_main as _mpf_module
             sage = sage.all
             sage_utils = _sage_utils
             BACKEND = 'sage'

the behaviour changes but it's still impossible to import, see http://trac.sagemath.org/ticket/16624#comment:8 for a synopsis

My question: what changed in 0.7.5 that had this effect?

### PR DESCRIPTION
**Pull request by skirpichev**
Discussion:
#5581

https://groups.google.com/forum/?fromgroups=#!topic/sympy/BCOn8oOyUV4

fixes #5581
fixes #8022

### CODE REVIEW

**Comment by skirpichev** [comment]
Ok, will merge when tests pass.

TODO:
- [ ] edit wiki pages for newcomers ([this](https://github.com/sympy/sympy/wiki/Development-workflow), is there something more?)
- [ ] patch mpmath's (e.g. remove [this](http://mpmath.org/doc/current/setup.html#mpmath-under-sympy))

**Comment by skirpichev** [comment]
Ok, this is in.  Thank you all for review.

**Comment by pelegm** [comment]
Is it possible that since the merging of this PR I can't import SymPy?
I get:
```pytb
Traceback (most recent call last):
  File "<ipython-input-2-f6f75f934722>", line 1, in <module>
    from sympy import *
  File "sympy/__init__.py", line 37, in <module>
    from .core import *
  File "sympy/core/__init__.py", line 8, in <module>
    from .expr import Expr, AtomicExpr
  File "sympy/core/expr.py", line 7, in <module>
    from .evalf import EvalfMixin, pure_complex
  File "sympy/core/evalf.py", line 9, in <module>
    import mpmath.libmp as libmp
ImportError: No module named mpmath.libmp
```

**Comment by skirpichev** [comment]
> Is it possible that since the merging of this PR I can't import SymPy?

Please read [README.rst](https://github.com/sympy/sympy/) and [instructions for developers](https://github.com/sympy/sympy/wiki/Development-workflow).

**Comment by pelegm** [comment]
Thanks. I shouldn't have read all of this, simply install `mpmath`...

**Comment by skirpichev** [comment]
My bad, I should announce this change on the mailing list.  Will do.

**Pull request merged**
