### PR TITLE
feat: allow assumptions to be taken for equality query

### PR DESCRIPTION
**Pull request by JSS95**
#### Brief description of what is fixed or changed

Fix handler for `Q.extended_real`
Allow `is_neq` to take assumptions.
Apply the change from #21235 to `Q.eq` and `Q.neq`.

In the future, facts will modified so that assuming binary predicates such as `x != y` or `x > y` can return the appropriate result.

#### Release Notes

* core
  * `is_neq` now takes assumptions
  * `Eq` and `Ne` can be refined by predicates such as `Q.positive`, `Q.zero`, etc.

### CODE REVIEW

**Comment by JSS95** [comment]
@oscarbenjamin 

Inspired by your [comment](https://github.com/sympy/sympy/pull/21055#issuecomment-792360730) in #21055, I came up with the design to implement refine logic without having duplicate code. The idea is to pass different getter functions as parameter. In `obj.__new__`, getter function which uses old assumption system (e.g. `x.is_zero`) is passed for faster evaluation. In `ask()` and `refine()`, getter function which uses new assumption system is passed in order to take local assumptions into account.

I tried with that approach here to let `ask(Q.eq(x,0), Q.zero(x))` return `True`. Please review this PR. If this looks OK, I think other refine logic can be changed in this way to remove the duplication.

**Comment by oscarbenjamin** [comment]
I have thought about something like this. We do need to be clear about whether it does slow some things down though e.g.:
```python
In [12]: x = S.Zero

In [13]: getter = lambda obj, key: getattr(obj, 'is_%s' % key)

In [14]: %timeit x.is_zero
86.7 ns ± 0.865 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [15]: %timeit getter(x, 'zero')
785 ns ± 60.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
Also the approach here requires putting `getter` everywhere in the logic which makes the code messy.

Another approach I thought about was to make a wrapper class that wraps an object with assumptions and then presents the interface of the old assumptions e.g.:
```python
def func(obj, assumptions=None):
    objq = AssumptionsWrapper(obj, assumptions):
    if objq.is_positive:
        ...
```
The idea here is that if assumptions are not given then AssumptionsWrapper can just return the object unmodified so that `is_positive` is exactly as fast as it would be otherwise. If assumptions are given then an `AssumptionsWrapper` instance is returned with methods like:
```python
def _eval_is_positive(self):
    return ask(Q.positive(self.obj), self.assumptions)
```

**Comment by JSS95** [comment]
That is an interesting idea. I will open a discussion i mailing list.

**Comment by JSS95** [comment]
@oscarbenjamin 
Please check the discussion I opened : https://groups.google.com/u/3/g/sympy/c/0NStDt45U-s

**Comment by JSS95** [comment]
This PR is an improvement of what was introduced in #21235. I will wait for a few days for review and merge this.

**Pull request merged**
