### PR TITLE
modifications to inequalities and sets

### LINKED ISSUE #9451: `solve(abs(1/x) < 1)` gives `ValueError: only non-negative integer powers are allowed`
In current SymPy (commit 86b8ff), I see:
```
In [1]: solve(abs(1/x) < 1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-dd7aaa7c3716> in <module>()
----> 1 solve(abs(1/x) < 1)

/home/robert/bin/sympy/sympy/solvers/solvers.pyc in solve(f, *symbols, **flags)
    811             f[i] = fi.as_expr()
    812         elif isinstance(fi, (bool, BooleanAtom)) or fi.is_Relational:
--> 813             return reduce_inequalities(f, symbols=symbols)
    814 
    815         # rewrite hyperbolics in terms of exp

/home/robert/bin/sympy/sympy/solvers/inequalities.pyc in reduce_inequalities(inequalities, symbols)
    587 
    588     # solve system
--> 589     rv = _reduce_inequalities(inequalities, symbols)
    590 
    591     # restore original symbols and return

/home/robert/bin/sympy/sympy/solvers/inequalities.pyc in _reduce_inequalities(inequalities, symbols)
    532 
    533     for gen, exprs in abs_part.items():
--> 534         abs_reduced.append(reduce_abs_inequalities(exprs, gen))
    535 
    536     return And(*(poly_reduced + abs_reduced + other))

/home/robert/bin/sympy/sympy/solvers/inequalities.pyc in reduce_abs_inequalities(exprs, gen)
    376     """
    377     return And(*[ reduce_abs_inequality(expr, rel, gen)
--> 378         for expr, rel in exprs ])
    379 
    380 

/home/robert/bin/sympy/sympy/solvers/inequalities.pyc in reduce_abs_inequality(expr, rel, gen)
    336         return exprs
    337 
--> 338     exprs = _bottom_up_scan(expr)
    339 
    340     mapping = {'<': '>', '<=': '>='}

/home/robert/bin/sympy/sympy/solvers/inequalities.pyc in _bottom_up_scan(expr)
    302 
    303             for arg in expr.args:
--> 304                 _exprs = _bottom_up_scan(arg)
    305 
    306                 if not exprs:

/home/robert/bin/sympy/sympy/solvers/inequalities.pyc in _bottom_up_scan(expr)
    319             if not n.is_Integer or n < 0:
    320                 raise ValueError(
--> 321                     "only non-negative integer powers are allowed")
    322 
    323             _exprs = _bottom_up_scan(expr.base)

ValueError: only non-negative integer powers are allowed
```
The correct result would be `(-∞ < x ∧ x < -1) ∨ (1 < x ∧ x < ∞)`.

### LINKED ISSUE #9565: solveset should solve the rational inequality abs((x-1)/(x-5)) <= 1/3
```python
In [1]: x = symbols('x', real=True)
In [2]: from sympy.solvers.solveset import solveset
In [3]: solveset(abs((x-1)/(x-5)) <= 1/3)
```
gives
```
NotImplementedError: 
No algorithms are implemented to solve equation Piecewise(((x - 1)/(x - 5), x - 1 >= 0), ((-x + 1)/(x - 5), True)) - 1/3
```

Workaround, resolving the `abs`:
```python
In [4]: Intersection(solveset((x-1)/(x-5) <= 1/3), solveset(-(x-1)/(x-5) <= 1/3))
Out[4]: [-1.0, 2.0]
```

(Btw., this inequality also causes [trouble](https://groups.google.com/d/msg/sage-devel/QLEFLgkuXRg/RyYA7jpiuAAJ) in Sage.)

### LINKED ISSUE #9956: Union(Interval(-oo, oo), FiniteSet(1)) not evaluated
```
>>> Union(Interval(-oo, oo), FiniteSet(1))
(-∞, ∞) ∪ {1}       # this should return (-∞, ∞) i guess
```

Can some one please verify the validity of issue?

### LINKED ISSUE #10047: solve(sin(x) < 2) is wrong
```
In [24]: solve(sin(x) < 2)
Out[24]: False

In [27]: solveset.solveset(sin(x) < 2, domain=S.Reals)
Out[27]: ∅
```

The answer should be all real x. Note, this is from the Wester paper (N13).

### PR DESCRIPTION
**Pull request by smichr**
closes #9451 
closes #9956 (which was needed to keep the desired results after the inequalites modifications)
closes #9565 
closes #10042 
closes #10047

See commit notes for comments.

### CODE REVIEW

**Comment by gxyd** [comment]
Perhaps the issue #9451 is already fixed in `solveset`:
```
>>> x = Symbol('x')
>>> from sympy.solvers.solveset import solveset
>>> solveset(abs(1/x) < 1, x, S.Reals)
(-∞, -1) ∪ (1, ∞)
```
Now just recently @hargup mentioned about closing the `solve` issue, and opening the corresponding `solveset` issues(if they are not solved in `solveset`). So i guess, #9451  is necessary to be solved.

**Comment by gxyd** [comment]
Also using this PR, i get:
```
>>> solveset(abs(1/x) < 1, x, S.Reals)
ConditionSet(x, Abs(1/x) < 1, (-oo, oo))
```
So `solveset` rather returns the expression un-evaluated.

**Comment by gxyd** [comment]
As for the first commit: The way you are solving seems to me a way of hiding a bigger problem that we have in `SymPy`, [this comment](https://github.com/sympy/sympy/pull/9958#discussion_r41706779) by @jksuom looks good to me, for the `oo` related things. Issues like #8257  will be solved after that i guess.

**Comment by gxyd** [comment]
I would really appreciate if you could also look [this conversation on gitter](https://gitter.im/sympy/sympy?at=561352b176d984a358756298). With PR #9958 , this issue is fixed(i have already added the test for that). Let me know what you think.

**Comment by smichr** [comment]
> Also using this PR [unevaluate result]

That has been fixed in the last commit.

> As for the first commit: The way you are solving seems to me a way of hiding a bigger problem

I agree. Even though I now reworked changes, I think more thought needs to go into this and it will take some more time to see what you have already discussed. I noted that non-set related `contains` functions (like in geometry) return True, not S.true and one has to watch out for that (as I learned while trying to modify the `reduce` method). But some tests were added to assert that set-related `contains` methods can return expressions (so it's probably right that they use S.true? -- not sure, a closer read of what you've discussed is necessary).

I am favorable to your modifications; I think these commits will add a few more changes. I am happy to commit yours first, however, and then discuss which of mine should be kept after rebasing over yours.  Are you ready for your #9958 PR to be committed?

**Comment by gxyd** [comment]
> Are you ready for your #9958 PR to be committed?

Yes, Ok, i have now squashed the commits in my PR into 1. Thanks.
One thing i still don't get is: Why are you still trying to improve the `solve`? (Are not you wasting your efforts, i guess). Since `solveset` is able to solve those problems already.

**Comment by smichr** [comment]
> Since solveset is able to solve those problems already

`solveset` is using `reduce_inequalities` (in my PR, formerly `solve_univariate_inequality`) to do its work.  #10022 breaks that connection. But during the transition from one to the other, it might be nice to have the old form working until we are sure that the new one can do all the old one does.

**Comment by smichr** [comment]
Let's do a few at a time. I will close this and open a new PR with fewer commits.

**Pull request closed without merging**
