### PR TITLE
docs changes in rv.py

### PR DESCRIPTION
**Pull request by gxyd**

### CODE REVIEW

**Comment by jksuom** [comment]
+1

**Comment by gxyd** [comment]
Thanks for reviewing @jksuom :)

**Comment by leosartaj** [comment]
Any idea what can be possible kwargs? If there are not anymore, maybe it can also be removed from the function definition.

**Comment by jksuom** [comment]
kwargs seem to be used in crv.py to control the integration of continuous density functions.

**Comment by gxyd** [comment]
Yes. BTW the use of **kwargs for `Integral` using `Probability` function
looks odd. But i guess that is OK.

**Pull request merged**
