### PR TITLE
Add pep8 config, use pep8 in travis

### PR DESCRIPTION
**Pull request by skirpichev**
also, fix E111-E113 errors:
E111 - indentation is not a multiple of four
E112 - expected an indented block
E113 - unexpected indentation

### CODE REVIEW

**Comment by toolforger** [comment]
Am 31.12.2014 um 18:43 schrieb Sergey B Kirpichev:
>> TEST_PEP
>
> Oh, that's just for travis.
>
> Yes, ideally, everything stylistic should go out of our regular tests.

I doubt that that is possible. Some of the tests are quite specific 
about what subdirectories they cover, for example.

 > There should be no problem to do so with pep8/flake8/whatever.

Again, that's going to run into all kinds of trouble, because people 
will see messages for stuff that the project does not care about, and 
miss style rules that the project does care about.

> We can run pep8.py in the test_code_quality.py, instead of the current variant.

That's exactly what I've been saying all along.

 >  But I think that we should just instruct our contributors to run 
pep8.py.

That's going to require everybody to figure out how to apply the 
delivered pep8.py configuration to their copy of pep8.py. People will 
also have to make sure they don't accidentally commit their downloaded 
pep8.py, at least those who download into their working copy (which will 
be the knee-jerk reaction for many if not most users).

So I'm strongly -1 to that plan.

I'm -0 about downloading pep8.py instead of keeping a local copy.
-0 instead of +0 because it can be an entry barrier if somebody starts 
hacking on SymPy, and his first bin/test run happens to be offline - 
he's going to get error messages and won't really know how to deal with 
them (he's new to SymPy after all, and being offline he can't even 
google anything).
-0 instead of -1 because it's going to be rare. I'd still want to avoid 
it, and I still don't see any reason against distributing a copy of 
pep8.py if we're committed to sticking with a given version for a while 
- but not important enough to -1 it.

>> Because people who're getting error messages from Travis that don't see them locally won't be thrilled.
>
> Sure.  But these people should be redirected to the documentation.

If we can automate things so they "just work", we should.
In this case, we can.

Plus, I see no attempts at redirecting them to the docs. There is no 
hint in the error messages. (Or is there?)

>> Requiring them to install, configure and run pep8.py is the exact opposite of what this all is about: automating tests as far as possible.
>
> I don't know why installing pep8 is such a big matter for you.  It's easy - one-line command.

Arghl. "Install, configure, and run".
That's three steps, each of which can fail or require help.

This is just making life harder for everybody.
Automate it and be done with it, what's so hard about this?

>> External dependencies do require justification.
>
> Sure.  We can use own style checkers, own testing framework, own standard library.  You listed here [various reasons](https://github.com/sympy/sympy/pull/8538#issuecomment-68432006) of why it's bad.

I know.
Still they require justification.

This is not a game of who's right, or who's on what side.
This is a game of finding the best solution.

>> I was asking about what pep8.py reported before your changes.
>
> You can revert "Fix PEP 8 errors" commit and see these errors.

Now you're wasting my time.
(Actually you've been wasting my time by not properly reading my points, 
quoting them out of context, and generally missing the point.)

**Comment by skirpichev** [comment]
On Wed, Dec 31, 2014 at 05:33:20PM -0800, Joachim Durchholz wrote:
>    I doubt that that is possible.

Any concrete example?

>    because people will see messages for stuff that the project does not care about

Why?  Please run pep8.py in this branch, do you see any messages?

>    miss style rules that the project does care about.

Why?

>    That's going to require everybody to figure out how to apply the
>    delivered pep8.py configuration to their copy of pep8.py.

Oh, just run pep8.py without arguments, it's all.

>    People will
>    also have to make sure they don't accidentally commit their downloaded
>    pep8.py, at least those who download into their working copy (which will
>    be the knee-jerk reaction for many if not most users).

I doubt so.  I hope, that most people will read installation instructions
from the pep8 project first.  Why do you believe they will do such a
crazy thing instead?

>    I still don't see any reason against distributing a copy of
>    pep8.py if we're committed to sticking with a given version for a while

Nothing specific just for this library.  Here, an example:
http://unix.stackexchange.com/questions/15050/why-are-libraries-shipped-separately-instead-of-bundled-with-every-program

>    If we can automate things so they "just work", we should.

People should read developer instructions, install all
required stuff, and everything will "just work".

Also, we can suggest Git hooks.

>    Plus, I see no attempts at redirecting them to the docs. There is no
>    hint in the error messages. (Or is there?)

There are several useful options.  For example, --show-source (this can
be default) or --show-pep8.

>    Arghl. "Install, configure, and run".

No, just install and run.

>    >> I was asking about what pep8.py reported before your changes.
>    >
>    > You can revert "Fix PEP 8 errors" commit and see these errors.
>
>    Now you're wasting my time.

Good answer.  Ok, I think this is the end of "discussion".  I hope, I
did my best.

**Comment by toolforger** [comment]
Okay, -1 then.

**Comment by skirpichev** [comment]
> Okay, -1 then.

I don't think we should count this vote.  Merely, it's based on misunderstanding.  As a little summary, I'll give here answers for your [critique](https://github.com/sympy/sympy/pull/8538#issuecomment-68432006):

> 1) It makes style checking optional.

No, it doesn't.  See the pr code.

> 2) It makes style checking partly optional (check_code_style is run unconditionally, pep8.py conditionally).

Travis runs both pep8 and remaining stuff in the test_code_quality.py.  And you can do same locally.

> 3) It picks the latest version of pep8.py.

That's a known issue.  We can disable some checks, or just wait a little and use next stable release.  I don't like first option, E112 and E113 checks looks to be useful for me.

> 4) It relies on the availability of an external service (pep8.py's git repo), introducing a new point of failure. 

We already use pip to install things in the travis builds (in fact, we even install Theano from github).  I'm sorry, but there is nothing new.

> 5) It contains superficial changes. Indenting multi-line function calls less, while it may improve the code, does not fix any warnings. Even if it did, we shouldn't arbitrarily impose new style guidelines without discussing them first.

We could discuss which checks will be enabled.  Current (very short) list based on [astropy](https://github.com/astropy/astropy/) setup.  Regarding multi-line function calls, it does fix some errors.  Revert the third commit (or any specific fix for such calls) - and you can see them.

**Comment by toolforger** [comment]
Am 01.01.2015 um 15:56 schrieb Sergey B Kirpichev:
>> Okay, -1 then.
>
> I don't think we should count this vote.

Leave that judgement to others, please.
You can't claim that you're impartial after all.

 > Merely, it's based on misunderstanding.

I disagree.

 > As a little summary, I'll give here answers for your
> [critique](https://github.com/sympy/sympy/pull/8538#issuecomment-68432006):

Note that this is not a complete writeup of all relevant points.
I'll stick with those that you mentioned though.

>> 1) It makes style checking optional.
>
> No, it doesn't.  See the pr code.

It depends on whether TEST_PEP is set.
For the local testing case, that's "optional".
I haven't checked whether and where the Travis setup sets that variable. 
I do not see how it's necessary to make this optional in the first case 
though.

>> 2) It makes style checking partly optional (check_code_style is run
>> unconditionally, pep8.py conditionally).
>
> Travis runs both pep8 and remaining stuff in the
> test_code_quality.py.  And you can do same locally.

Again, that "can" means "it is optional".

Also, it means that local tests do different thing than Travis tests.
Some of these deviations are unavoidable (slow tests come to mind).
This deviation is gratuitious - or at least I haven't read a good reason 
for it.

>> 3) It picks the latest version of pep8.py.
>
> That's a known issue.  We can disable some checks, or just wait a
> little and use next stable release.  I don't like first option,

That's fixed already, so that point is moot.

 > E112 and E113 checks looks to be useful for me.

We disagree on that then.
(See above for the reasons why I consider them useless.)

>> 4) It relies on the availability of an external service (pep8.py's
>> git repo), introducing a new point of failure.
>
> We already use pip to install things in the travis builds (in fact,
> we even install Theano from github).  I'm sorry, but there is nothing
> new.

I assume that you're correct for the Travis builds, but that doesn't 
help for local testing.

>> 5) It contains superficial changes. Indenting multi-line function
>> calls less, while it may improve the code, does not fix any
>> warnings. Even if it did, we shouldn't arbitrarily impose new style
>> guidelines without discussing them first.
>
> We could discuss which checks will be enabled.  Current (very short)
> list based on [astropy](https://github.com/astropy/astropy/) setup.

I think the list is mostly okay, though I wouldn't derive it from some 
other project; instead, I'd use the maximum set of test that generates 
only messages that consensus actually wants fixed.

> Regarding multi-line function calls, it does fix some errors.  Revert
> the third commit (or any specific fix for such calls) - and you can
> see them.

I mentioned these changes because I was curious whether pep8.py reports 
them or not.
If it does, the pep8 configuration needs to be adapted (your task), or 
pep8.py needs to be adapted (making pep8.py in its current form useless 
to us, and the whole PR unmergeable until pep8.py is adapted).
Not my task to investigate these things; it's you who considered using 
pep8.py, so your task to validate that it is indeed useful.

**Comment by skirpichev** [comment]
On Thu, Jan 01, 2015 at 09:33:20AM -0800, Joachim Durchholz wrote:
>    You can't claim that you're impartial after all.

Why not?

>    >> 1) It makes style checking optional.
>    >
>    > No, it doesn't. See the pr code.
> 
>    It depends on whether TEST_PEP is set.
>    For the local testing case, that's "optional".

TEST_PEP - for travis builds.

>    I haven't checked whether and where the Travis setup sets that variable.

Then please read the code first.

>    >> 2) It makes style checking partly optional (check_code_style is run
>    >> unconditionally, pep8.py conditionally).
>    >
>    > Travis runs both pep8 and remaining stuff in the
>    > test_code_quality.py. And you can do same locally.
> 
>    Again, that "can" means "it is optional".

No.  It is what it is.

>    Also, it means that local tests do different thing than Travis tests.

No.

>>> 3) It picks the latest version of pep8.py.
>>
>> That's a known issue. We can disable some checks, or just wait a
>> little and use next stable release. I don't like first option,
>    That's fixed already, so that point is moot.

No.  That's not fixed yet.

>    > E112 and E113 checks looks to be useful for me.
> 
>    We disagree on that then.
>    (See above for the reasons why I consider them useless.)

I don't see anything meaningful from you in this sense, sorry.
We don't use here same pep8 version as your PyDev
environment.  Please understand this.

>    I assume that you're correct for the Travis builds, but that doesn't
>    help for local testing.

For local testing we should edit instructions for developers in the
wiki.  That's all.

>    I'd use the maximum set of test that generates
>    only messages that consensus actually wants fixed.

Thanks, KO.

>    > Regarding multi-line function calls, it does fix some errors. Revert
>    > the third commit (or any specific fix for such calls) - and you can
>    > see them.
> 
>    I mentioned these changes because I was curious whether pep8.py reports
>    them or not.

Sure, it reports.

**Comment by skirpichev** [comment]
Ok, I'll close this for now.  If someone is ready to do review, please just reopen.

**Comment by asmeurer** [comment]
I haven't been able to read everything here, but wasn't there some issue where this had to wait on a release of pep8?

**Comment by skirpichev** [comment]
On Fri, Jan 02, 2015 at 03:25:21PM -0800, Aaron Meurer wrote:
>    I haven't been able to read everything here, but wasn't there some issue
>    where this had to wait on a release of pep8?

Yes.  Or we can pick some specific commit in pep8, which I dislike.
See this:
https://github.com/sympy/sympy/pull/8538#discussion-diff-21098044
Or we can disable some E11* errors.

**Comment by toolforger** [comment]
Am 03.01.2015 um 00:25 schrieb Aaron Meurer:
> I haven't been able to read everything here, but wasn't there some issue where this had to wait on a release of pep8?

I understand that pep8.py had a bug that made it needlessly warn about 
indented comment lines, and that a fix was scheduled for the next 
version of pep8.py.

**Comment by toolforger** [comment]
Am 03.01.2015 um 00:47 schrieb Sergey B Kirpichev:
> Yes.  Or we can pick some specific commit in pep8, which I dislike.

What's the problem with that?

**Pull request closed without merging**
