### PR TITLE
Reorganise ComplexRegion class hierarchy

### LINKED ISSUE #17370: Reorganise ComplexRegion
This comes from working on #17280.

ComplexRegion looks a bit of a mess to me. If I summarise briefly the class structure it looks like:
```python
class ImageSet(Set):
    ...

class ComplexRegion(Set):
    def __new__(cls, sets, polar=True):
        if polar == True:
            obj = ImageSet.__new__(cls, Lambda((r, theta), r*(cos(theta) + I*sin(theta))), sets)
        elif polar == False:
            obj = ImageSet.__new__(cls, Lambda((x, y), x + I*y), sets)
        obj._sets = sets
        obj._polar = polar
        return obj

    @property
    def args(self):
        return (self._sets, self._polar)
```
This makes ComplexRegion something of a pseudo-subclass of ImageSet. It uses `ImageSet.__new__(cls, ...)` with `cls=ComplexRegion` although there is no inheritance relationship between them. The args are emulated over the top using a property that is separate from the underlying _args seen by methods of `Basic`:
```julia
In [2]: S1 = ComplexRegion(Interval(0, 1)**2)                                                                                     

In [3]: S1.args                                                                                                                   
Out[3]: 
⎛      2       ⎞
⎝[0, 1] , False⎠

In [4]: S1._args                                                                                                                  
Out[4]: 
⎛                        2⎞
⎝(x, y) ↦ x + y⋅ⅈ, [0, 1] ⎠
```
We also have in `.args` a boolean parameter to distinguish between polar and rectangular form (those should just be separate classes).

One way to clean this up would be:
```python
class ImageSet(Set):
    ...

class ComplexRegion(ImageSet):
    ...

class PolarComplexRegion(ComplexRegion):
   ...

class RectangularComplexRegion(ComplexRegion):
   ...
```
Then for backwards compatibility `ComplexRegion(..., polar=True/False)` can return instances of `PolarComplexRegion` or `RectangularComplexRegion`.

On the other hand I can't really tell what the purpose of ComplexRegion is. It is basically just a weird wrapper around ImageSet so why not just use ImageSet directly?

Also after a quick grep I can't tell if ComplexRegion is actually used anywhere. Do we even need this class?

### PR DESCRIPTION
**Pull request by oscarbenjamin**
#### References to other Issues or PRs

Fixes #17370 

#### Brief description of what is fixed or changed

* Add PolarComplexRegion and CartesianComplexRegion as subclasses of ComplexRegion representing the two different cases.
* Make Polar/Cartesian ComplexRegion use args like proper Basic instances
* Don't use `ImageSet.__new__` to initialise objects that are no instances of ImageSet
* Make Complexes a proper singleton with no args.
* Have `CartesianComplexRegion(S.Reals**2)` evaluate to `S.Complexes` instead of redefining `S.Complexes.__eq__`.
* Add docstrings for all classes

#### Other comments

I am still unsure what the purpose of the ComplexRegion classes is but this cleans up the hierarchy. I found while working on Lambda that I needed to do this because otherwise some changes there resulted in an infinite recursion for `hash(S.Complexes)` (which happens during import). This is fixed now that Complexes is a proper no args SingleTon class with a sets attribute.

#### Release Notes

* sets
    * Cleaned up inheritance scheme for ComplexRegion and Complexes.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
There is a doctest failure that I don't understand. I pushed here so that I could ask for help with it:
```
Failed example:
    S.Complexes
Expected:
    S.Complexes
Got:
    Complexes()
```
I don't understand this because with this PR under isympy:
```julia
In [1]: S.Complexes
Out[1]: S.Complexes

In [2]: str(S.Complexes)
Out[2]: 'S.Complexes'

In [3]: repr(S.Complexes)
Out[3]: 'S.Complexes'

In [4]: init_printing(use_unicode=False)

In [5]: S.Complexes
Out[5]: S.Complexes
```
In the normal Python REPL:
```python
>>> from sympy import S
>>> S.Complexes
S.Complexes
```
So somehow the doctest is using a different printer from the above. Does anyone know how to fix this?

**Comment by oscarbenjamin** [comment]
I've removed that doctest but readding locally I managed to get this stack-trace:
```
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/doctest.py", line 1328, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest sympy.sets.fancysets.Complexes[1]>", line 1, in <module>
        S.Complexes
      File "/Users/enojb/current/sympy/sympy/sympy/interactive/printing.py", line 30, in _displayhook
        print(stringify_func(arg, **settings))
      File "/Users/enojb/current/sympy/sympy/sympy/printing/str.py", line 890, in sstrrepr
        s = p.doprint(expr)
      File "/Users/enojb/current/sympy/sympy/sympy/printing/printer.py", line 249, in doprint
        return self._str(self._print(expr))
      File "/Users/enojb/current/sympy/sympy/sympy/printing/printer.py", line 287, in _print
        return getattr(self, printmethod)(expr, **kwargs)
      File "/Users/enojb/current/sympy/sympy/sympy/printing/str.py", line 89, in _print_Basic
        l = [self._print(o) for o in expr.args]
```
So for some reason the changes here are causing S.Complexes to print with `_print_Basic` under the doctests. I don't know enough about the printing code to know how/why that should/shouldn't happen...

**Comment by oscarbenjamin** [comment]
I'm getting the error from both doctest runners. I've removed the doctest in this PR now but if I add it back:
```diff
diff --git a/sympy/sets/fancysets.py b/sympy/sets/fancysets.py
index 253d996776..c486e26e8f 100644
--- a/sympy/sets/fancysets.py
+++ b/sympy/sets/fancysets.py
@@ -1254,6 +1254,8 @@ class Complexes(with_metaclass(Singleton, CartesianComplexRegion)):
     ========
 
     >>> from sympy import S, I
+    >>> S.Complexes
+    S.Complexes
     >>> 1 + I in S.Complexes
     True
```
Then
```julia
In [1]: import sympy                                                                                                              

In [2]: sympy.doctest('fancysets')                                                                                                
====================================================== test process starts =======================================================
executable:         /Users/enojb/current/sympy/35venv/bin/python3.5  (3.5.7-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              1.16.2
hash randomization: on (PYTHONHASHSEED=724955334)

sympy/sets/fancysets.py[18] F.................                                                                              [FAIL]

__________________________________________________________________________________________________________________________________
_________________________________________________ sympy.sets.fancysets.Complexes _________________________________________________
File "/Users/enojb/current/sympy/sympy/sympy/sets/fancysets.py", line 1257, in sympy.sets.fancysets.Complexes
Failed example:
    S.Complexes
Expected:
    S.Complexes
Got:
    Complexes()

====================================== tests finished: 17 passed, 1 failed, in 0.63 seconds ======================================
DO *NOT* COMMIT!
Out[2]: False
```
In this PR I have removed the args of Complexes. On master we have
```julia
In [1]: S.Complexes.args                                                                                                          
Out[1]: 
⎛ 2       ⎞
⎝ℝ , False⎠
```
but here the args are just `()` so it makes sense the `_print_Basic` prints it that way.

I think there is just something missing that should connect this class to the appropriate printer (that is used in the doctests). I've tried initialising printing as is done in the doctests but it prints fine as far as I can tell:
```julia
In [1]: from sympy.utilities.runtests import setup_pprint                                                                         

In [2]: setup_pprint()                                                                                                            
Out[2]: True

In [3]: S.Complexes                                                                                                               
Out[3]: S.Complexes
```
I haven't been able to reproduce the failure outside of the doctests.

**Comment by oscarbenjamin** [comment]
> I haven't been able to reproduce the failure outside of the doctests.

I spoke too soon. It is sstr that gives this output:
```julia
In [1]: S.Complexes                                                                                                               
Out[1]: S.Complexes

In [2]: sstr(_)                                                                                                                   
Out[2]: 'Complexes()'
```
I just need to figure out how to change that.

**Comment by oscarbenjamin** [comment]
This isn't a new issue in this PR since on master we also have:
```julia
In [8]: sstr(S.Reals)                                                                                                             
Out[8]: 'Reals'

In [9]: sstr(S.Complexes)                                                                                                         
Out[9]: 'Complexes(ProductSet(Reals, Reals), False)'
```

**Comment by oscarbenjamin** [comment]
And it's fixed:
```diff
diff --git a/sympy/printing/str.py b/sympy/printing/str.py
index fcb5a5f706..2ec879b0aa 100644
--- a/sympy/printing/str.py
+++ b/sympy/printing/str.py
@@ -612,6 +612,9 @@ def _print_Rationals(self, expr):
     def _print_Reals(self, expr):
         return 'Reals'
 
+    def _print_Complexes(self, expr):
+        return 'Complexes'
+
     def _print_int(self, expr):
         return str(expr)
 
```

**Comment by oscarbenjamin** [comment]
I'll merge this soon if no one objects

**Comment by jksuom** [comment]
This looks good though I'm not sure how `expr` should be used. Could it be a method with variables as arguments?

**Comment by oscarbenjamin** [comment]
I'm not sure what expr is for. This PR preserves its existing behaviour. Really I'm not sure why the ComplexRegion classes exist at all since they're just imagesets. Ultimately I think it would be best to remove these classes.

For now this is (as much as possible) a backwards compatible change. The changes here are necessary because Complexes is implemented on top of ComplexRegion and it isn't possible to fix ImageSet without this.

**Pull request merged**
