### PR TITLE
Better eval for beta

### PR DESCRIPTION
**Pull request by oscargus**
#### Brief description of what is fixed or changed

Added a few more cases for evaluating `beta`.

#### Release Notes

* functions
   * `beta` evaluates directly for more cases.

### CODE REVIEW

**Comment by asmeurer** [comment]
I'd like to think more about avoiding automatic evaluation based on assumptions and symbolic identities, preferring to have those in `doit` and other simplification methods instead (see the discussion here https://docs.sympy.org/dev/guides/custom-functions.html#best-practices-for-eval). I know this is something that we aren't doing a good job of right now, but we should try to move in that direction.

So how do you feel about only evaluating these cases when they are explicit numbers (which are the only things you added tests for anyway), and moving the more fully symbolic cases to `doit` (I'm referring specifically to the last two cases you added here)?

**Comment by oscargus** [comment]
Sure!

I'm actually thinking that in general one may not always want automatic evaluation for numbers either, only for "trivial" (however that is defined...). There are e.g. the often very useful trigonometric evaluation tables that one may not always want. So going in the direction of moving more time-consuming and/or symbolic evaluation to `doit` surely makes sense.

**Comment by oscargus** [comment]
This opens up some questions about how to deal with this in general, especially when `evaluate=False` to start with. Once we use `_eval_doit` one should probably do an `eval` first in that?

Also found a printing issue with LaTeX (didn't check the other printers though...).

**Comment by oscargus** [comment]
`pprint` works, but code generation relying on rewriting doesn't, with `evaluate=False` and single argument. Not sure it is a problem though.

**Comment by asmeurer** [comment]
Ideally there should be so little automatic evaluation that evaluate=False isn't even necessary. But for things like this, you typically have the same identity in `eval` and `doit`, where the `eval` version applies only for Rational and `doit` applies it to any symbolic input. So maybe a good pattern is to just implement the general case in `doit`, and have `eval` call `doit` when the inputs are Rational. Or otherwise split it out into a separate helper method so it isn't duplicated.

**Comment by oscargus** [comment]
I used this pattern now, having all the actual eval in doit and calling it if both arguments are Numbers. This changes so that direct evaluation of e.g. `beta(1, y)` does not automatically evaluate to `1/y`. Easily changed to just put an `or` instead of `and` in `eval`.

This particular function becomes a bit messy as it must support one or two arguments, but apart from that I believe that this is probably a quite good pattern.

**Comment by oscargus** [comment]
For some functions, such as `lerchphi` one would probably also want to involve `expand_func` in `doit`. For numerical arguments, `expand_func`, gives a plain numerical output for `lerchphi`.

**Comment by asmeurer** [comment]
Maybe we should think of ways to make this pattern easier in the `Function` superclass, like having a special `eval` method that only evaluates on Rational inputs and isn't even called on symbolic inputs. See also https://github.com/sympy/sympy/issues/23701.

**Comment by oscargus** [comment]
I rebased.

**Pull request merged**
