### PR TITLE
Different symbols for Laplacian

### PR DESCRIPTION
**Pull request by wermos**
#### Brief description of what is fixed or changed
SymPy uses `\triangle` to denote the Laplacian, which is nonstandard. However, using `\Delta` for that is very widespread:
* The [Comprehensive LaTeX Symbol List](https://mirror.kku.ac.th/CTAN/info/symbols/comprehensive/symbols-a4.pdf) lists \Delta as the symbol for the Laplacian on page 318. This is also mentioned in [this answer on tex.stackexchange.com](https://tex.stackexchange.com/a/76563/203821).
image
* As [this answer to a question about what to use for the Laplace Operator](https://tex.stackexchange.com/a/76564/203821) states, one of the aliases of U+2206 (increment) is indeed [Laplace Operator](https://unicode-table.com/en/2206/).
* [Wikipedia](https://en.wikipedia.org/wiki/Laplace_operator) exclusively uses \Delta, or U+0394 to denote the Laplace operator.

Because using `\Delta` is much more common than using `\triangle` for the Laplace operator, I propose changing the symbol used in the LaTeX printer.
#### Release Notes

* printing
  * The LaTeX printer now uses `\Delta` instead of `\triangle` for the Laplace operator.

### CODE REVIEW

**Comment by ThePauliPrinciple** [comment]
> because most people use `\Delta`, as described [here](https://tex.stackexchange.com/q/76553/203821).

The accepted answer uses `\newcommand*\Laplace{\mathop{}\!\mathbin\bigtriangleup}`. Not sure where your conclusion that "most people use `\Delta`" comes from.

**Comment by asmeurer** [comment]
What is the difference between the two?

**Comment by sylee957** [comment]
I think that `\triangle` prints out more thinner font, while `\Delta` prints out the correct reflection of the `\nabla`. But this can depend on the fonts.
(Check out in https://katex.org/)

**Comment by wermos** [comment]
@ThePauliPrinciple It was my bad for being unclear, but I linked to the question itself, and not the accepted answer, because I expected people to read the comments. The comments state that the Comprehensive LaTeX Symbol List lists `\Delta` as the symbol for the Laplacian:
image
this is on page 318 on [here](https://mirror.kku.ac.th/CTAN/info/symbols/comprehensive/symbols-a4.pdf). (I was unable to find it on page 50 or 150, as suggested by the comments in that question.) This is also mentioned in [this answer](https://tex.stackexchange.com/a/76563/203821).

Moreover, as [this answer to that question](https://tex.stackexchange.com/a/76564/203821) states, one of the aliases of U+2206 (increment) is indeed [Laplace Operator](https://unicode-table.com/en/2206/).

Finally, we can see that, as suggested in the comments to that question, we see that [Wikipedia](https://en.wikipedia.org/wiki/Laplace_operator) exlcusively uses `\Delta`, or U+0394 to denote the Laplace operator.

(Technically, U+0394 is incorrect, because U+2206 is the one which has "Laplace operator" as an alias, but I digress.)

**Comment by oscargus** [comment]
I guess it depends on the context. If the d'Alembert operator is also used (which I do not think it is in SymPy), then \bigtriangle may be better. However, considering where it is defined etc, I think that matching with \nabla is more important, so I cast my vote on \Delta.

(An option is to use \nabla^2...)

**Comment by oscargus** [comment]
If it turns out to be a problem, it is always possible to add a keyword option to the printer that determines how it is printed. But since it is incorrect at the moment, any solution is better than the current.

**Comment by oscargus** [comment]
Sorry, I came in to this thinking that it printed as \nabla...

I'd then suggest to add a keyword argument to let the user select. And I think that \triangle should be the default, for historical reasons (it is not obviously wrong).

Note that it is better to use "sensible keywords" than to simply let the user select whatever LaTeX-code they want to put there. Maybe 't', 'b', and 'd' for triangle, bigtriangle, and delta. In that way we can check and throw and error (with a message including valid options).

**Comment by wermos** [comment]
That's a good idea. I will implement that, if the others (@ThePauliPrinciple, @asmeurer, @sylee957) are onboard with this idea.

**Comment by ThePauliPrinciple** [comment]
I agree that there should be the option to choose. If one would take the time to read all points of view in the linked stackexchange article it is clear that there is no consensus on what symbol should be used. The OP should be updated to reflect this as it might cause confusion in the future when this PR is used as a reference.

**Comment by wermos** [comment]
@ThePauliPrinciple Do you have any suggestions as to what the OP should be changed to?

**Comment by ThePauliPrinciple** [comment]
It should indicate that there is discussion about what is the right symbol and that SymPy provides an option for that reason.

**Comment by wermos** [comment]
@ThePauliPrinciple @asmeurer @sylee957 @oscargus Is the new description and proposed change better? I will have to update this PR to reflect the changes.

**Comment by asmeurer** [comment]
IMO we should just use \Delta. It seems that is the best option. We could add a configuration option for it, but I don't really see a need to do that unless someone requests it. Note that it's always possible for users to fine-tune the printer manually by subclassing it and overwriting the methods.

**Comment by anutosh491** [comment]
> IMO we should just use \Delta. It seems that is the best option. We could add a configuration option for it, but I don't really see a need to do that unless someone requests it. Note that it's always possible for users to fine-tune the printer manually by subclassing it and overwriting the methods.

+1, I feel this is the correct way to go here .

**Comment by wermos** [comment]
@asmeurer What should I do to this PR then? Should I implement a keyword argument, or can it be merged as is?

**Comment by sylee957** [comment]
I think that I'm +1 to merge this, unless we receive an argument in a couple of days, for the reasons that

- We don't consider printing out the LaTeX in exact string literal a 'feature', than printing out in correct LaTeX.
- The implementation without options is more simple and easy to extend than the implementation with options.

But I think that you should first change the release notes before the merge.

**Comment by oscargus** [comment]
Yeah, I am also not objecting to not implementing configuration at this stage. But please revert the release note. (Sorry about that.)

**Comment by wermos** [comment]
@oscargus The release notes and the description have both been changed, as requested.

**Comment by oscargus** [comment]
Thanks!

**Pull request merged**
