### PR TITLE
Add UndefinedMatrixShapeSymbol class

### PR DESCRIPTION
**Pull request by asmeurer**
This can be used as a symbolic shape in a matrix expression, and will not
result in errors when compared to a different shape. For instance,

    _n = UndefinedMatrixShapeSymbol('_n')
    k = Symbol('k')
    A = MatrixSymbol("A", _n, _n)
    B = MatrixSymbol("B", k, k)
    A + B # does not result in an error

In particular, MatAdd() and MatMul() with no arguments now return a ZeroMatrix
and Identity with Dummy UndefinedMatrixShapeSymbol, rather than scalar 0 and
1.

Also makes it so that is_square returns None if one of the arguments has an
UndefinedMatrixShapeSymbol.

I'm still not 100% sure if this is a good idea. I'd like feedback on it. It does fix the issue described at https://github.com/sympy/sympy/pull/15948#issuecomment-463432718. Although with it, `cancel` returns matrices with unevaluated `0` and `I` matrices, so we probably should add better automatic simplification of these. 

#### Release Notes

* matrices
  * new class in `sympy.matrices.expressions.matexpr`, `UndefinedMatrixShapeSymbol`, which can be used in symbolic matrix shapes to not compare unequal to other matrix shapes for the purposes of type checking.
  * `MatAdd()` and `MatMul()` with no arguments now return `ZeroMatrix` and `Identity` with Dummy `UndefinedMatrixShapeSymbol`, resp.
  * `MatrixExpr.is_square` returns `None` if the shape contains an `UndefinedMatrixShapeSymbol`.

### CODE REVIEW

**Comment by asmeurer** [comment]
Another alternative to this would be to simply be less aggressive with type checking in the matrix expressions. I think that would be a much harder change, and we do want to do type checking at some point, so it's not clear where it should be done and not done.

**Comment by smichr** [comment]
I wonder if we could have a Chameleon (Symbol) which always passes `Eq(Chameleon(), foo)` but not `Eq(Chameleon(), Chameleon())`?

**Comment by asmeurer** [comment]
Being always equal to everything could cause issues. It could get swapped out for things that SymPy thinks it is equal to. For instance it would be impossible to `subs` the chameleon with something else because subs would think the first expression it comes across is equal to it.

**Comment by smichr** [comment]
> could cause issues

crumple, crumple, toss. We have PurePoly with a common symbol. Could we have a Symbol that is recognized as being an arbitrary integer: `IntSymbol('n') == IntSymbol('n') != IntSymbol('m')`?

**Comment by asmeurer** [comment]
I'm not sure about it. We really only need to bypass the type checks, which are basically three places in the code, the check that the shapes are equal in MatAdd, the check that rows == cols in MatMul, and the check for is_square in Inverse. 

To take a step back, the problem that we are trying to solve is to make matrix expressions work with any function that already works with noncommutative Symbols. The problem is that MatAdd and MatMul subclass from Add and Mul, but there are some ways that they don't behave the same, leading to errors from any algorithm that assumes they do. One of these ways is that you can't add 0 to a matrix expression, because 0 is a scalar and doesn't have the proper shape. You also can't create an empty `MatAdd()` or `MatMul()`, which causes issues with functions like the one in https://github.com/sympy/sympy/pull/15948#issuecomment-463432718 which call `expr.func(*l)` where `l` could be empty. For `Add()` and `Mul()` those are obviously the identities `0` and `1`, but for `MatAdd()` and `MatMul()` the exact identity depends on the shape of the matrix.

Actually, since this is really only needed for ZeroMatrix and Identity, maybe instead of doing this with the shape parameter, we could create special ZeroMatrix and Identity objects that don't have a specified shape (the `.shape` could raise an exception). As long as these are aggressively removed once they are part of a larger expression, it might work. By "aggressively" I mean MatAdd and MatMul should remove them even without calling `doit` (unlike `Add` and `Mul`,`MatAdd` and `MatMul` are completely unevaluated by default).

**Comment by jksuom** [comment]
Would it suffice to define two special matrix expressions, `MatZero` and `MatOne`?

**Comment by asmeurer** [comment]
Here is a pull request implementing that idea https://github.com/sympy/sympy/pull/15994. I'm a little worried about it that the TypeErrors could cause issues. On the other hand, with the aggressive simplification, `cancel` no longer returns expressions with zero and identity matrices in it.

**Comment by asmeurer** [comment]
@jksuom I didn't notice your comment. That's basically what my PR #15994 does. I used different names than you, but they can be changed.

**Comment by jksuom** [comment]
It seems that we had the same idea about the same time.

**Pull request closed without merging**
