### PR TITLE
Rewrote Abs as sign in another way

### LINKED ISSUE #16217: Integrals with abs much slower recently
The following test was added in #15710

https://github.com/sympy/sympy/blob/8fc3b3a96b9f982ed6dc8f626129abee36bcda95/sympy/integrals/tests/test_integrals.py#L1480-L1487

In #16216 I marked it as slow as it took at least 100 seconds to run the test depending on Python version.

When I revisited the run times of tests in #16010 it was not close to being that slow as I marked everything taking more than 10 seconds as slow.

Hence, something merged in the last two weeks has severely slowed this down.

### PR DESCRIPTION
**Pull request by oscargus**
#### References to other Issues or PRs

Fixes #16217 

#### Brief description of what is fixed or changed
I may be to tired, but I think that this is valid so let us see if it breaks something else...

#### Other comments
To be honest, I do not fully understand how 0/sign(0) evaluates to 0 anyway since sign(0) = 0 ...,

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by asmeurer** [comment]
This doesn't work for complex numbers. 

```py
>>> -3*I/sign(-3*I)
3
>>> -3*I*sign(-3*I)
-3
```

**Comment by asmeurer** [comment]
I believe x/sign(x) is 0 at x=0 in the limit, which is often the best we can do with rewrite without returning a Piecewise (it's the same with the `sinc` function).

**Comment by oscargus** [comment]
Makes sense.

**Comment by oscargus** [comment]
I considered the following, but there seems to be no obvious time advantage from the tests I did:

```
    def _eval_rewrite_as_sign(self, arg, **kwargs):
        if arg.is_real:
            return arg*sign(arg)
        else:
            return arg/sign(arg)
```

**Pull request closed without merging**
