### PR TITLE
xreplace check for rebuild is faster

### PR DESCRIPTION
**Pull request by abloomston**
Rather than an intensive call to _aresame, xreplace simply tracks whether a rule has been applied (via helper function _xreplace). In applications where xreplace is called frequently on expressions with complicated argument trees, this optimization can have a considerable impact.

See https://github.com/sympy/sympy/issues/5999 for the original optimization to xreplace.

### CODE REVIEW

**Comment by abloomston** [comment]
It looks like the failed checks were due to a travis error, not a problem in my PR. I've run the tests in my environment with no problem.

**Comment by toolforger** [comment]
> I've run the tests in my environment with no problem.

That in itself isn't saying much. The whole point of Travis is to see 
failures that happen if it's not running in one's own environment, just 
to see whether anything needs fixing for that case.

> It looks like the failed checks were due to a travis error, not a problem in my PR.

Yeah, the error message indicates that mpmath.org was down, probably 
when trying to download the package for installation.
Normally I'd agree that that's good enough to go in, but since this 
looks like a critical part of the SymPy infrastructure, I'd like to see 
somebody with proper authority to restart that test. Or you could do 
some minor change and trigger a retest that way (see next comment for a 
possibility of such a change).

**Comment by abloomston** [comment]
Thanks for the recommendation @toolforger- I've modified the code per your advice.

Also, understood regarding travis. I was hoping someone else knew how to restart the build- I didn't see the option in travis. I've taken a closer look at the travis failure, and am separately working a change to .travis.yml to more gracefully handle such problems installing libraries.

**Comment by truongduy134** [comment]
I usually close the PR, and then open it again in these cases to restart the Travis CI build

**Comment by abloomston** [comment]
Closed an reopened the PR to restart the Travis CI build, because another error occurred.

**Comment by certik** [comment]
That looks good, thanks!

**Pull request merged**
