### PR TITLE
Add inv(mat) functionality to expressions/inverse.py

### LINKED ISSUE #13859: inv(matrix) should exist just like matrix.inv() does
The inverse of a matrix M can be computed as  M.inv(). It should also be able to be computed using inv(M) which is more intuitive for people using Matlab or Scilab. 
det(Matrix) exists to compute the determinant of a matrix, similarly inv(Matrix) can also be added.

### PR DESCRIPTION
**Pull request by sharanry**
#### References to other Issues or PRs
Fixes #13859 

#### Brief description of what is fixed or changed

inv(matrix) added like matrix.inv() as it exists for determinant.

### CODE REVIEW

**Comment by abhigyank** [comment]
You should also add tests for the changes.

**Comment by ylemkimon** [comment]
I think it should be applicable to every objects that has inverse.

**Comment by jksuom** [comment]
The name `inv` gives no indication that it is for matrices only. The name could be something like `matrix_inverse` or `invert_matrix`. It could be imported as `inv` if needed. Otherwise, `inv` would not be in SymPy's namespace.

**Comment by moorepants** [comment]
Closing this. Seems abandoned. Reopen if desired.

**Pull request closed without merging**
