### PR TITLE
AssocOp.flatten reverses the operands

### PR DESCRIPTION
**Pull request by sylee957**
#### Brief description of what is fixed or changed

I found this while experimenting with custom operator

```
from sympy import *
from sympy.core.operations import AssocOp

x, y, z = symbols('x y z')

class MyAssoc(AssocOp):
    identity = S(1)

MyAssoc(x, y, z).args
```

Because of this line, it reverses even if it is not commutative

https://github.com/sympy/sympy/blob/fb98dbb5a50dc13489b365ea6558e1efc5e62377/sympy/core/operations.py#L126

#### Release Notes

- core
  - Fixed `AssocOp` reversing the order of operands

### CODE REVIEW

**Comment by smichr** [comment]
Would it be better to extend with the reversed args of o and do a final reversal of seq when done?

**Comment by sylee957** [comment]
I will inspect this for a while.
I see my changes concurs with the more older version , but I see the point of efae4bb41ab67479b9ff1ca38675145f186673d6 was about the efficiency.

And in my opinion, if we find any speed improvement of using `pop()` instead of `pop(0)` or such, your idea can have a point.
But if there is no speed difference, I think having reversed one only makes it more difficult to figure out the code.

**Comment by sylee957** [comment]
I have done some experiments

## pop() vs pop(0)

```python
import cProfile
l = list(range(999999))
```

```python
def test():
    for i in range(10000):
        l.pop()

cProfile.run('test()')
```
```10000    0.001    0.000    0.001    0.000 {method 'pop' of 'list' objects}```

```python
def test():
    for i in range(10000):
        l.pop(0)
        
cProfile.run('test()')
```
```10000    4.616    0.000    4.616    0.000 {method 'pop' of 'list' objects}```

# extend() vs +
```python
import cProfile
l = list(range(99999))
```

```python
def test():
    for i in range(1000):
        l.extend([1, 2, 3])
        
cProfile.run('test()')
```
```1004 function calls in 0.000 seconds```

```python
def test():
    for i in range(1000):
        global l
        l = l + [1, 2, 3]
        
cProfile.run('test()')
```
```4 function calls in 0.403 seconds```

I guess the actuall time complexity suggests to use last element deleting or appending, than first element prepending or deleting.

https://stackoverflow.com/questions/195625/what-is-the-time-complexity-of-popping-elements-from-list-in-python

Python internals are not optimizing latter ones?
Though I am not aware about the actual CPython code.

**Comment by smichr** [comment]
The added test will guard against doing the faster `new_seq.extend(reversed(o.args))` which will not denest nested args.

**Pull request merged**
