### PR TITLE
Added backend option in plotting

### LINKED ISSUE #13516: Add tests for added attribute 'usebackend' for Plot
The task is to complete the closed PR #11983. In which I think (all) necessary changes were made for introducing attribute `backend` but no test cases were added.

Also address a few minor comments mentioned on PR #11983.

We would need to 'use the commits' of PR #11983  and on top of those add test cases for it.

### PR DESCRIPTION
**Pull request by Smit-create**
Added backend option in plotting
#### References to other Issues or PRs

Fixes #13516

#### Brief description of what is fixed or changed
Added option to choose the backend from `{'default',  'matplotlib', 'text'}`

#### Release Notes

* plotting
  * Added backend option

### CODE REVIEW

**Comment by Smit-create** [comment]
Please review this. Locally the tests passes, but on travis it fails:
```
>>> sympy.test('/plotting/tests/test_plot.py')
==================================================== test process starts ====================================================
executable:         /home/smit/anaconda3/bin/python  (3.7.4-final-0) [CPython]
architecture:       64-bit
cache:              yes

ground types:       gmpy 2.0.8
numpy:              1.17.2
random seed:        92280031
hash randomization: on (PYTHONHASHSEED=1076863135)

sympy/plotting/tests/test_plot.py[19] ...................                                                                [OK]

_______________________________________________________ slowest tests _______________________________________________________
test_matplotlib_3 - Took 10.445 seconds
test_matplotlib_2 - Took 12.185 seconds
test_matplotlib_6 - Took 18.436 seconds
test_matplotlib_4 - Took 47.299 seconds
test_matplotlib_5 - Took 83.441 seconds
======================================= tests finished: 19 passed, in 189.57 seconds ========================================
True
```

**Comment by sylee957** [comment]
You may have to skip the tests if numpy is not installed.

**Comment by Smit-create** [comment]
Is it ready to merge?

**Comment by sylee957** [comment]
I don't think that `plot.show` is working since you have changed the backend to string.
```
>>> from sympy import *

>>> x = Symbol('x')
>>> pm = plot(sin(x), backend="matplotlib")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-258a79a1bf54> in <module>
      2 
      3 x = Symbol('x')
----> 4 pm = plot(sin(x), backend="matplotlib")

~\Documents\Github\sympy\sympy\plotting\plot.py in plot(*args, **kwargs)
   1559 
   1560     plots = Plot(*series, **kwargs)
-> 1561     if show:
   1562         plots.show()
   1563     return plots

~\Documents\Github\sympy\sympy\plotting\plot.py in show(self)
    188         # TODO move this to the backend (also for save)
    189         if hasattr(self, '_backend'):
--> 190             self._backend.close()
    191         self._backend = self.backend(self)
    192         self._backend.show()

TypeError: 'str' object is not callable
```

**Pull request merged**
