### PR TITLE
[Prototype] Mpmath and NumPy matrix wrapper

### PR DESCRIPTION
**Pull request by sylee957**
#### Brief description of what is fixed or changed

So from the comment https://github.com/sympy/sympy/pull/17250#issuecomment-514814547 there had been discussion of using wrapped numeric matrices dedicated for some purpose.

However, I think that things may be overly complicated from the MatrixBase, to integrate with other matrix types

Instead, I have an another idea of using the interface of matrix expressions instead, and it looks like it is actually more simpler from this perspective, only having to be careful about copying and mutating the original matrices.

Possible usage can be below. I've not implemented addition and multiplication yet

image

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
This looks good.

I see why the copy argument is needed but I wonder if there is a cleaner way. Do any other Basic subclasses wrap the underlying mutable objects?

I see `__getitem__` isn't added yet but it should return a Float (when not slicing).

How does mpmath.matrix compare with Matrix-of-Float for speed?

**Comment by sylee957** [comment]
I think that there is only about 30 ~ 100% improvement
```
import mpmath
from sympy import *
from sympy.matrices.expressions.mpmath import MpmathMatrix

m1 = mpmath.matrix(
    [
        [0, 0, 1, 0, 2, 0],
        [0, 0, 0, 1, 0, 0],
        [1, 0, 0, 1, 0, 2],
        [0, 2, 1, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0]
    ]
)
m1 = MpmathMatrix(m1)
%timeit m1 ** 100000
```
```
m2 = m1.as_explicit()
%timeit m2 ** 100000
```


```20.4 ms ± 424 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)```
->
```15.4 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)```

Matrix determinant :

```1.13 ms ± 9.79 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)```
->
```494 µs ± 11.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)```

Inverse :

```2.63 ms ± 78.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)```
->
```1.02 ms ± 12 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)```

**Comment by sylee957** [comment]
I've only added copy to force the internal to be immutable. if they don't provide any immutable version.
Some other way would be creating some subclass of mpmath matrix directly, with `setitem` and other mutable methods locked, and with hash enabled.

**Comment by oscarbenjamin** [comment]
> I think that there is only about 30 ~ 100% improvement

That's disappointing. I was hoping for a lot more. Maybe there are other cases that can be faster... I expect that the complex case would be. Eigenvalue problems seem a lot faster with mpmath though:
```julia
In [82]: m1 = mpmath.matrix( 
    ...:     [ 
    ...:         [0, 0, 1, 0, 2, 0], 
    ...:         [0, 0, 0, 1, 0, 0], 
    ...:         [1, 0, 0, 1, 0, 2], 
    ...:         [0, 2, 1, 0, 0, 0], 
    ...:         [1, 0, 0, 0, 0, 0], 
    ...:         [0, 0, 1, 0, 0, 0] 
    ...:     ] 
    ...: )                                                                                                                        

In [83]: M1 = Matrix(m1).reshape(m1.rows, m1.cols)                                                                                

In [84]: %timeit mpmath.eig(m1)                                                                                                   
14.1 ms ± 217 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [85]: %timeit M1.eigenvects()                                                                                                  
408 ms ± 8.19 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Here's the complex version:
```julia
In [93]: m1 = mpmath.matrix( 
    ...:     [ 
    ...:         [0, 0, 1, 0, 2, 0], 
    ...:         [0, 0, 0, 1, 0, 0], 
    ...:         [1, 0, 0, 1, 0, 2], 
    ...:         [0, 2, 1+1j, 0, 0, 0], 
    ...:         [1, 0, 0, 0, 0, 0], 
    ...:         [0, 0, 1, 0, 0, 0] 
    ...:     ] 
    ...: )  
```
With that `m1**100000` takes 30ms but `M1**100000` hangs (This is expression blowup #17247 )

In general I think that good algorithms for the floating point case are usually very different from the exact case. It would be good to delegate all of that to mpmath or other libraries if possible.

**Comment by sylee957** [comment]
I've also tried some experiment with `rref` and in some cases sympy expressions can blow up, 
mpmath seems like giving constant computation time

```
mpmath.matrix( 
    [ 
        [1, 1+1j, 1-1j, 0, 0, 0], 
        [0, 0, 0, 1, 2+1j, 0], 
        [1, 9+1j, 0, 1, 0, 2], 
        [0, 2, 1+1j, 0, 0, 0], 
        [1, 0, 0, 0, 0, 0], 
        [0, 0, 1, 0, 0, 0] 
    ] 
)
```
For example, this seems like 10 times slower in sympy, 
however, surprisingly, I find some cases where using rref is slower with my implementation here using mpmath matrix though.
(Note that we may have to reimplement some things like `rref` which those libraries doesn't provide natively.)

**Comment by sylee957** [comment]
Also, there can be some notable difference using numpy, compared with mpmath
```
mat = mpmath.matrix( 
    [ 
        [1, 1+1j, 1-1j, 0, 0, 0], 
        [0, 0, 0, 1, 2+1j, 0], 
        [1, 9+1j, 0, 1, 0, 2], 
        [0, 2, 1+1j, 0, 0, 0], 
        [1, 0, 0, 0, 0, 0], 
        [0, 0, 1, 0, 0, 0] 
    ] 
)

%timeit mat ** 100
```

```
mat = numpy.array( 
    [ 
        [1, 1+1j, 1-1j, 0, 0, 0], 
        [0, 0, 0, 1, 2+1j, 0], 
        [1, 9+1j, 0, 1, 0, 2], 
        [0, 2, 1+1j, 0, 0, 0], 
        [1, 0, 0, 0, 0, 0], 
        [0, 0, 1, 0, 0, 0] 
    ] 
)

%timeit numpy.linalg.matrix_power(mat, 100)
```

I see numpy is 1000 times faster than mpmath
`13 ms ± 227 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)`
`18.8 µs ± 279 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)`

**Comment by oscarbenjamin** [comment]
> I see numpy is 1000 times faster than mpmath

Indeed. I'm not sure we can use numpy without major changes in SymPy's floating point model though. The result you show in the OP for `m1**100000` demonstrates a situation where numpy would just overflow.

I see that Mathematica distinguishes between floats and "machine precision" floats. If we had that distinction in SymPy then numpy could serve the machine precision case.

**Comment by sylee957** [comment]
Whatever, I would propose an another idea of making this rather as some `MatrixAtom` class that can be some wrapper for the numeric matrix, like how sympy integers, rationals are wrapping the python numeric types.

**Pull request closed without merging**
