### PR TITLE
3809 isprime

### PR DESCRIPTION
**Pull request by asmeurer**
TODO: rebase

### CODE REVIEW

**Comment by pelegm** [comment]
What's the future of this pull request? @danaj, do you plan to do it?

**Comment by pelegm** [comment]
@asmeurer, if @danaj is not doing that, can I somehow rebase and resolve conflicts, and push it again here?

**Comment by danaj** [comment]
@asmeurer, @pelegm, the earliest I can get to it is mid-February.  I can commit to doing it then and ready for review by end of February if someone else doesn't take over.

**Comment by pelegm** [comment]
@danaj I guess this is good enough.

**Pull request closed without merging**
