### PR TITLE
Skip some slow tests on Travis

### PR DESCRIPTION
**Pull request by asmeurer**
See discussion at https://github.com/sympy/sympy/pull/12795. We should figure
out what is going on here, but for now, we need to stop the Travis build
errors.

### CODE REVIEW

**Comment by asmeurer** [comment]
Any other tests that should be skipped?

**Comment by jksuom** [comment]
test_pmint_logexp only takes 30-40 seconds in most cases. It may not be necessary to skip it.

**Comment by asmeurer** [comment]
It seems to fail a lot, e.g., https://travis-ci.org/sympy/sympy/jobs/247330784.

**Comment by asmeurer** [comment]
Any objections to merging this? It will make Travis much less of a headache.

**Comment by jksuom** [comment]
There were 2 cases of test_pmint_logexp timeout among 16 that I inspected, the rest were test_prudnikov_3.

On the other hand, there are several tests in test_query.py that consistently take several minutes without timing out. That makes the test_pmint_logexp timeouts all the more mysterious. Maybe there is something that makes it behave randomly.

Anyway, I think this should be merged (and noone seems to object).

**Comment by asmeurer** [comment]
I opened https://github.com/sympy/sympy/issues/12818 to figure it out. I don't have time to look into it now, but we should figure it out at some point.

**Pull request merged**
