### PR TITLE
[WIP] refactor(core) : Unify Add and MatAdd

### PR DESCRIPTION
**Pull request by JSS95**
#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by JSS95** [comment]
@oscarbenjamin @Upabjojr 
Okay, here we are. I implemented basic structure to unify `Add` and `MatAdd`. In commit 05c0f9b:

```python
In [7]: A = MatrixSymbol('A', 2,2)

In [8]: Add(A,A)
Out[8]: A + A

In [9]: Add(A,A, evaluate=True)
Out[9]: 2⋅A

In [10]: Add(A,A).func
Out[10]: sympy.core.add.Add

In [11]: Add(A,A).kind
Out[11]: MatrixKind(NumberKind)

In [12]: Add(x,x)
Out[12]: 2⋅x

In [13]: Add(x,x, evaluate=False).func
Out[13]: sympy.core.add.Add

In [14]: Add(x,x, evaluate=False).kind
Out[14]: NumberKind
```

`Add` first determines the kind from the arguments, and call `.add()` method. Please review `Kind.add()` and `MatrixKind.add()` methods.

 Note that methods of `MatAdd` are not migrated yet so tests fail for now.

**Comment by JSS95** [comment]
I also wonder if we can enhance `Add.flatten` and apply it to numbers and matrices alike.

**Comment by JSS95** [comment]
@oscarbenjamin @Upabjojr  If the general design looks OK, I will start resolving test failures.

**Comment by oscarbenjamin** [comment]
The general approach looks good to me.

Is it possible to compare benchmark results with 1.7.1?

The performance of `Add` is crucial in many slow operations.

**Comment by Upabjojr** [comment]
> `Add` first determines the kind from the arguments, and call `.add()` method. Please review `Kind.add()` and `MatrixKind.add()` methods.

Interesting, you've been able to keep the difference in evaluation behavior between _Add_ and _MatAdd_.

**Comment by JSS95** [comment]
I am currently focusing on introducing relational predicate. I'll return to this topic after that's finished.

**Pull request closed without merging**
