### PR TITLE
calculus: AccumulationBounds is now an Expr

### PR DESCRIPTION
**Pull request by ThePauliPrinciple**
#### Brief description of what is fixed or changed
@oscarbenjamin 

#### Release Notes

NO ENTRY

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
The test fails ultimately because `is_number` has changed. The PR gives:
```python
In [1]: AccumBounds(-S(3)/2, S(1)/2).is_number
Out[1]: True
```
However master gives:
```python
In [1]: AccumBounds(-S(3)/2, S(1)/2).is_number
Out[1]: False
```
The correct answer is `False` because `is_number=True` means that the expression can be numerically evaluated to a complex number in floating point but an AccumBounds represents an interval rather than a complex number.

That change is because `AtomicExpr` sets `is_number` to `False` as a class attribute:
https://github.com/sympy/sympy/blob/ef854dad43c9cef361857782dd0b8523e43f2430/sympy/core/expr.py#L3920-L3927

So `AccumBounds` just needs to set that as well. Also all subclasses of `AtomicExpr` should be reviewed to see whether this value of `False` is correct or whether this class attribute should actually just be removed from `AtomicExpr` because it doesn't really make sense to set `is_number=False` for all `AtomicExpr` (although it does make sense to set it for `AccumBounds`).

**Comment by ThePauliPrinciple** [comment]
The class also defines: `is_extended_real = True`, does that make sense if `is_number = False`?

**Comment by smichr** [comment]
I feel like `AccumBounds` is like sneaking SetExpr behavior into Expr. But perhaps this is just how it has to be...like special casing Order, too, in Add.flatten.

**Comment by oscarbenjamin** [comment]
> The class also defines: `is_extended_real = True`, does that make sense if `is_number = False`?

All the numbers contained by an `AccumBounds` are extended real but it is not itself an extended real. I'm not entirely sure how that should be handled but it is probably best to leave it unchanged for now.

**Comment by oscarbenjamin** [comment]
Looks good. Thanks!

**Pull request merged**
