### PR TITLE
Removed lots of bare except clauses

### PR DESCRIPTION
**Pull request by amiller27**
Partial fix for issue #12000.  One of the except clauses was just unnecessary, a few were able to be narrowed to `NotImplementedError` (although I'm not completely sure about those), and a few were also modified so that they reraise the exception they catch.

### CODE REVIEW

**Comment by gxyd** [comment]
@amiller27 can you please merge master branch into your branch?

**Comment by amiller27** [comment]
Done

**Comment by gxyd** [comment]
Thanks. I'll review the PR tomorrow and will get back to you.

**Comment by amiller27** [comment]
Test failures have been fixed.  One of the `except`s was covering up a bug in the trig substitution rule, so I fixed that as well.  Not entirely sure if I did it correctly, but it passes tests.  The only reason it might not be correct would be if the solver doesn't just try all methods when no hint is specified, I'm not sure what the actual behavior is.

You'll notice that I changed the expected result of the tests, but the changed result is algebraically equivalent to the previous.  Not sure if there's a better way to check for equivalence that would be more robust.

**Comment by jksuom** [comment]
The fix for trig_substitution_rule appears in the changes. Was is intended for another PR?

**Comment by amiller27** [comment]
I wasn't sure about sympy's policy for PR scope, the fix is finished and this PR depends on that fix so I just threw it in.  If I separate it out the PR with the `trig_substitution_rule` fix would have to be merged before this one.

**Comment by jksuom** [comment]
I think that fix could be included, but perhaps it should be mentioned in the opening paragraph. There is also an issue concerning the bug (though I couldn't find it right now). It should be mentioned as "Fixes #xxxxx" so that it will be closed when this is merged. There should also be "test_issue_xxxxx" in test_manual.py.

**Comment by jksuom** [comment]
This is the issue #12645.

**Comment by jksuom** [comment]
There is an error in the test: TypeError: manualintegrate() takes exactly 2 arguments (3 given)

**Comment by amiller27** [comment]
I moved it to `test_integrals.py` and changed it to call `integrate` instead of `manualintegrate` like it did in that issue originally, passes on my computer so should pass Travis.

**Comment by jksuom** [comment]
Thanks. This looks good.

**Pull request merged**
